@echo off
setlocal enabledelayedexpansion

:: ============================================================
::  Sutta Archive - Build Script
::  Noi cac module JS thanh 1 file app.bundle.js de deploy
::  Usage:  build.bat          (version tu dong tang)
::          build.bat 50       (chi dinh version)
:: ============================================================

set "OUT=app.bundle.js"

:: Version: dung tham so dong lenh hoac doc tu file
if "%~1" neq "" (
    set "VER=%~1"
) else (
    if exist .buildver (
        set /p VER=<.buildver
        set /a VER=!VER!+1
    ) else (
        set "VER=50"
    )
)
echo !VER!>.buildver

echo [BUILD] Concatenating JS modules -^> %OUT% (v!VER!)

:: Noi theo dung thu tu load
(
    echo // Sutta Archive - app.bundle.js v!VER!
    echo // Built: %date% %time%
    echo // DO NOT EDIT - generated by build.bat
    echo.
    type "toc.js"
    echo.
    type "js\utils.js"
    echo.
    type "js\bilara.js"
    echo.
    type "js\state.js"
    echo.
    type "js\ui.js"
    echo.
    type "js\anchor.js"
    echo.
    type "js\render.js"
    echo.
    type "js\menu.js"
    echo.
    type "js\tts.js"
) > "%OUT%"

if errorlevel 1 (
    echo [ERROR] Failed to concatenate files!
    exit /b 1
)

:: Tinh kich thuoc file
for %%A in ("%OUT%") do set "SIZE=%%~zA"
set /a KB=!SIZE!/1024
echo [BUILD] Created %OUT% (!KB! KB)

:: Cap nhat index.html: thay 9 script tags bang 1 (dung PowerShell cho an toan)
set "BUILDVER=!VER!"
powershell -NoProfile -ExecutionPolicy Bypass -Command "$v=$env:BUILDVER; $f=(Resolve-Path index.html).Path; $h=[System.IO.File]::ReadAllText($f); $q=[char]34; $block='(?s)<script src=.toc\.js\?v=\d+. defer></script>.*?<script src=.js/tts\.js\?v=\d+. defer></script>'; $bundle='<script src=.app\.bundle\.js\?v=\d+. defer></script>'; $rep='<script src='+$q+'app.bundle.js?v='+$v+$q+' defer></script>'; if($h -match $block){ $h=[regex]::Replace($h,$block,$rep) } elseif($h -match $bundle){ $h=[regex]::Replace($h,$bundle,$rep); Write-Host '[BUILD] index.html da bundle san - chi cap nhat version' } else { Write-Host '[ERROR] Khong tim thay script trong index.html'; exit 1 }; [System.IO.File]::WriteAllText($f,$h,(New-Object System.Text.UTF8Encoding $false))"
if errorlevel 1 (
    echo [ERROR] Failed to update index.html!
    exit /b 1
)

echo [BUILD] Updated index.html -^> app.bundle.js?v=!VER!
echo.
echo [DONE] Ready to commit and push!
  git add .
  git commit -m "build: bundle JS v!VER!"
  git push origin main

endlocal
pause