window.SUTRA_INDEX = [
  {
    type: "nikaya",
    key: "DN",
    labelVi: "Digha Nikaya - Trường Bộ Kinh",
    labelEn: "Dīgha Nikāya - Long Discourses",
   children: [
  { type: "sutta", id: "dn01", code: "DN 1", titlePali: "Brahmajāla Sutta", titleVi: "Kinh Phạm Võng", titleEn: "The Supreme Net" },
  { type: "sutta", id: "dn02", code: "DN 2", titlePali: "Sāmaññaphala Sutta", titleVi: "Kinh Sa Môn Quả", titleEn: "The Fruits of the Contemplative Life" },
  { type: "sutta", id: "dn03", code: "DN 3", titlePali: "Ambaṭṭha Sutta", titleVi: "Kinh Ambattha", titleEn: "About Ambaṭṭha" },
  { type: "sutta", id: "dn04", code: "DN 4", titlePali: "Soṇadaṇḍa Sutta", titleVi: "Kinh Sonadanda", titleEn: "With Soṇadaṇḍa" },
  { type: "sutta", id: "dn05", code: "DN 5", titlePali: "Kūṭadanta Sutta", titleVi: "Kinh Kutadanta", titleEn: "With Kūṭadanta" },
  { type: "sutta", id: "dn06", code: "DN 6", titlePali: "Mahāli Sutta", titleVi: "Kinh Mahāli", titleEn: "With Mahāli" },
  { type: "sutta", id: "dn07", code: "DN 7", titlePali: "Jāliya Sutta", titleVi: "Kinh Jāliya", titleEn: "With Jāliya" },
  { type: "sutta", id: "dn08", code: "DN 8", titlePali: "Mahāsīhanāda Sutta", titleVi: "Kinh Sư Tử Hống với Kassapa", titleEn: "The Great Lion’s Roar" },
  { type: "sutta", id: "dn09", code: "DN 9", titlePali: "Poṭṭhapāda Sutta", titleVi: "Kinh Potthapada", titleEn: "With Poṭṭhapāda" },
  { type: "sutta", id: "dn10", code: "DN 10", titlePali: "Subha Sutta", titleVi: "Kinh Subha", titleEn: "To Subha" },
  { type: "sutta", id: "dn11", code: "DN 11", titlePali: "Kevaṭṭa Sutta", titleVi: "Kinh Kevatta", titleEn: "With Kevaṭṭa" },
  { type: "sutta", id: "dn12", code: "DN 12", titlePali: "Lohicca Sutta", titleVi: "Kinh Lohicca", titleEn: "To Lohicca" },
  { type: "sutta", id: "dn13", code: "DN 13", titlePali: "Tevijja Sutta", titleVi: "Kinh Tam Minh", titleEn: "The Threefold Knowledge" },
  { type: "sutta", id: "dn14", code: "DN 14", titlePali: "Mahāpadāna Sutta", titleVi: "Kinh Đại Bổn", titleEn: "The Great Discourse on Past Buddhas" },
  { type: "sutta", id: "dn15", code: "DN 15", titlePali: "Mahānidāna Sutta", titleVi: "Kinh Đại Nhân Duyên", titleEn: "The Great Discourse on Causation" },
  { type: "sutta", id: "dn16", code: "DN 16", titlePali: "Mahāparinibbāna Sutta", titleVi: "Kinh Đại Bát Niết Bàn", titleEn: "The Great Passing Away" },
  { type: "sutta", id: "dn17", code: "DN 17", titlePali: "Mahāsudassana Sutta", titleVi: "Kinh Đại Thiện Kiến", titleEn: "The Great King of Glory" },
  { type: "sutta", id: "dn18", code: "DN 18", titlePali: "Janavasabha Sutta", titleVi: "Kinh Mahāgovinda", titleEn: "With Janavasabha" },
  { type: "sutta", id: "dn19", code: "DN 19", titlePali: "Mahāgovinda Sutta", titleVi: "Kinh Đại Govinda", titleEn: "The Great Steward" },
  { type: "sutta", id: "dn20", code: "DN 20", titlePali: "Mahāsamaya Sutta", titleVi: "Kinh Đại Hội", titleEn: "The Great Assembly" },
  { type: "sutta", id: "dn21", code: "DN 21", titlePali: "Sakkapañha Sutta", titleVi: "Kinh Đế Thích Vấn Đạo", titleEn: "Sakka’s Questions" },
  { type: "sutta", id: "dn22", code: "DN 22", titlePali: "Mahāsatipaṭṭhāna Sutta", titleVi: "Kinh Đại Niệm Xứ", titleEn: "The Great Foundations of Mindfulness" },
  { type: "sutta", id: "dn23", code: "DN 23", titlePali: "Pāyāsi Sutta", titleVi: "Kinh Pāyāsi", titleEn: "With Pāyāsi" },
  { type: "sutta", id: "dn24", code: "DN 24", titlePali: "Pāṭika Sutta", titleVi: "Kinh Pāṭika", titleEn: "About Pāṭika" },
  { type: "sutta", id: "dn25", code: "DN 25", titlePali: "Udumbarikasīhanāda Sutta", titleVi: "Kinh Udumbarika", titleEn: "The Lion’s Roar at Udumbarikā" },
  { type: "sutta", id: "dn26", code: "DN 26", titlePali: "Cakkavattisīhanāda Sutta", titleVi: "Kinh Chuyển Luân Thánh Vương", titleEn: "The Wheel-Turning Monarch’s Lion’s Roar" },
  { type: "sutta", id: "dn27", code: "DN 27", titlePali: "Aggañña Sutta", titleVi: "Kinh Khởi Thế", titleEn: "On Origins" },
  { type: "sutta", id: "dn28", code: "DN 28", titlePali: "Sampasādanīya Sutta", titleVi: "Kinh Tịnh Tín", titleEn: "Inspiring Confidence" },
  { type: "sutta", id: "dn29", code: "DN 29", titlePali: "Pāsādika Sutta", titleVi: "Kinh Khả Hỷ", titleEn: "Inspiring Approval" },
  { type: "sutta", id: "dn30", code: "DN 30", titlePali: "Lakkhaṇa Sutta", titleVi: "Kinh Tướng", titleEn: "The Marks of a Great Man" },
  { type: "sutta", id: "dn31", code: "DN 31", titlePali: "Siṅgālovāda Sutta", titleVi: "Kinh Giáo Thọ Thiện Sanh", titleEn: "Advice to Sigala" },
  { type: "sutta", id: "dn32", code: "DN 32", titlePali: "Āṭānāṭiya Sutta", titleVi: "Kinh Hộ Trì", titleEn: "The Discourse on Atanatiya Protection" },
  { type: "sutta", id: "dn33", code: "DN 33", titlePali: "Saṅgīti Sutta", titleVi: "Kinh Kết Tập", titleEn: "The Recitation" },
  { type: "sutta", id: "dn34", code: "DN 34", titlePali: "Dasuttara Sutta", titleVi: "Kinh Thập Thượng", titleEn: "Up to Ten" }
]
  },
  {
    type: "nikaya",
    key: "MN",
    labelVi: "Majjhima Nikāya - Trung Bộ Kinh",
    labelEn: "Majjhima Nikāya - Middle-Length",
    children:
    [
  { type: "sutta", id: "mn01", code: "MN 1", titlePali: "Mūlapariyāya Sutta", titleVi: "Kinh Căn Bản Pháp Môn", titleEn: "The Root of All Things" },
  { type: "sutta", id: "mn02", code: "MN 2", titlePali: "Sabbāsava Sutta", titleVi: "Kinh Nhất Thiết Lậu Hoặc", titleEn: "All the Taints" },
  { type: "sutta", id: "mn03", code: "MN 3", titlePali: "Dhammadāyāda Sutta", titleVi: "Kinh Thừa Tự Pháp", titleEn: "Heirs in Dhamma" },
  { type: "sutta", id: "mn04", code: "MN 4", titlePali: "Bhayabherava Sutta", titleVi: "Kinh Sợ Hãi và Khiếp Đảm", titleEn: "Fear and Dread" },
  { type: "sutta", id: "mn05", code: "MN 5", titlePali: "Anaṅgaṇa Sutta", titleVi: "Kinh Không Uế Nhiễm", titleEn: "Without Corruption" },
  { type: "sutta", id: "mn06", code: "MN 6", titlePali: "Ākaṅkheyya Sutta", titleVi: "Kinh Ước Nguyện", titleEn: "If One Should Wish" },
  { type: "sutta", id: "mn07", code: "MN 7", titlePali: "Vatthūpama Sutta", titleVi: "Kinh Ví Dụ Tấm Vải", titleEn: "The Simile of the Cloth" },
  { type: "sutta", id: "mn08", code: "MN 8", titlePali: "Sallekha Sutta", titleVi: "Kinh Tẩy Trừ", titleEn: "Effacement" },
  { type: "sutta", id: "mn09", code: "MN 9", titlePali: "Sammādiṭṭhi Sutta", titleVi: "Kinh Chánh Tri Kiến", titleEn: "Right View" },
  { type: "sutta", id: "mn10", code: "MN 10", titlePali: "Satipaṭṭhāna Sutta", titleVi: "Kinh Niệm Xứ", titleEn: "The Foundations of Mindfulness" },
  { type: "sutta", id: "mn11", code: "MN 11", titlePali: "Cūḷasīhanāda Sutta", titleVi: "Kinh Tiểu Sư Tử Hống", titleEn: "The Shorter Discourse on the Lion’s Roar" },
  { type: "sutta", id: "mn12", code: "MN 12", titlePali: "Mahāsīhanāda Sutta", titleVi: "Kinh Đại Sư Tử Hống", titleEn: "The Greater Discourse on the Lion’s Roar" },
  { type: "sutta", id: "mn13", code: "MN 13", titlePali: "Mahādukkhakkhandha Sutta", titleVi: "Kinh Đại Khổ Uẩn", titleEn: "The Greater Mass of Suffering" },
  { type: "sutta", id: "mn14", code: "MN 14", titlePali: "Cūḷadukkhakkhandha Sutta", titleVi: "Kinh Tiểu Khổ Uẩn", titleEn: "The Lesser Mass of Suffering" },
  { type: "sutta", id: "mn15", code: "MN 15", titlePali: "Anumāna Sutta", titleVi: "Kinh Suy Tư", titleEn: "Inference" },
  { type: "sutta", id: "mn16", code: "MN 16", titlePali: "Cetokhila Sutta", titleVi: "Kinh Tâm Hoang Vu", titleEn: "The Wilderness of the Mind" },
  { type: "sutta", id: "mn17", code: "MN 17", titlePali: "Vanapattha Sutta", titleVi: "Kinh Rừng Rậm", titleEn: "Jungle Thickets" },
  { type: "sutta", id: "mn18", code: "MN 18", titlePali: "Madhupiṇḍika Sutta", titleVi: "Kinh Bánh Mật", titleEn: "The Honeyball" },
  { type: "sutta", id: "mn19", code: "MN 19", titlePali: "Dvedhāvitakka Sutta", titleVi: "Kinh Hai Loại Tư Duy", titleEn: "Two Kinds of Thought" },
  { type: "sutta", id: "mn20", code: "MN 20", titlePali: "Vitakkasaṇṭhāna Sutta", titleVi: "Kinh Đối Trị Tư Duy", titleEn: "The Removal of Distracting Thoughts" },
  { type: "sutta", id: "mn21", code: "MN 21", titlePali: "Kakacūpama Sutta", titleVi: "Kinh Ví Dụ Cái Cưa", titleEn: "The Simile of the Saw" },
  { type: "sutta", id: "mn22", code: "MN 22", titlePali: "Alagaddūpama Sutta", titleVi: "Kinh Ví Dụ Con Rắn", titleEn: "The Simile of the Snake" },
  { type: "sutta", id: "mn23", code: "MN 23", titlePali: "Vammika Sutta", titleVi: "Kinh Tổ Mối", titleEn: "The Ant-hill" },
  { type: "sutta", id: "mn24", code: "MN 24", titlePali: "Rathavinīta Sutta", titleVi: "Kinh Xe Trạm", titleEn: "Relay Chariots" },
  { type: "sutta", id: "mn25", code: "MN 25", titlePali: "Nivāpa Sutta", titleVi: "Kinh Mồi Nhử", titleEn: "The Bait" },
  { type: "sutta", id: "mn26", code: "MN 26", titlePali: "Ariyapariyesanā Sutta", titleVi: "Kinh Thánh Cầu", titleEn: "The Noble Search" },
  { type: "sutta", id: "mn27", code: "MN 27", titlePali: "Cūḷahatthipadopama Sutta", titleVi: "Kinh Dấu Chân Voi Nhỏ", titleEn: "The Shorter Elephant Footprint Simile" },
  { type: "sutta", id: "mn28", code: "MN 28", titlePali: "Mahāhatthipadopama Sutta", titleVi: "Kinh Dấu Chân Voi Lớn", titleEn: "The Greater Elephant Footprint Simile" },
  { type: "sutta", id: "mn29", code: "MN 29", titlePali: "Mahāsāropama Sutta", titleVi: "Kinh Ví Dụ Lõi Cây Lớn", titleEn: "The Greater Discourse on the Simile of the Heartwood" },
  { type: "sutta", id: "mn30", code: "MN 30", titlePali: "Cūḷasāropama Sutta", titleVi: "Kinh Ví Dụ Lõi Cây Nhỏ", titleEn: "The Shorter Discourse on the Heartwood" },
  { type: "sutta", id: "mn31", code: "MN 31", titlePali: "Cūḷagosiṅga Sutta", titleVi: "Kinh Rừng Gosiṅga Nhỏ", titleEn: "The Shorter Gosiṅga Forest Discourse" },
  { type: "sutta", id: "mn32", code: "MN 32", titlePali: "Mahāgosiṅga Sutta", titleVi: "Kinh Rừng Gosiṅga Lớn", titleEn: "The Greater Gosiṅga Forest Discourse" },
  { type: "sutta", id: "mn33", code: "MN 33", titlePali: "Mahāgopālaka Sutta", titleVi: "Kinh Người Chăn Bò Lớn", titleEn: "The Greater Cowherd Discourse" },
  { type: "sutta", id: "mn34", code: "MN 34", titlePali: "Cūḷagopālaka Sutta", titleVi: "Kinh Người Chăn Bò Nhỏ", titleEn: "The Shorter Cowherd Discourse" },
  { type: "sutta", id: "mn35", code: "MN 35", titlePali: "Cūḷasaccaka Sutta", titleVi: "Kinh Saccaka Nhỏ", titleEn: "The Shorter Discourse to Saccaka" },
  { type: "sutta", id: "mn36", code: "MN 36", titlePali: "Mahāsaccaka Sutta", titleVi: "Kinh Saccaka Lớn", titleEn: "The Greater Discourse to Saccaka" },
  { type: "sutta", id: "mn37", code: "MN 37", titlePali: "Cūḷataṇhāsaṅkhaya Sutta", titleVi: "Kinh Diệt Ái Nhỏ", titleEn: "The Shorter Discourse on the Destruction of Craving" },
  { type: "sutta", id: "mn38", code: "MN 38", titlePali: "Mahātaṇhāsaṅkhaya Sutta", titleVi: "Kinh Diệt Ái Lớn", titleEn: "The Greater Discourse on the Destruction of Craving" },
  { type: "sutta", id: "mn39", code: "MN 39", titlePali: "Mahāassapura Sutta", titleVi: "Kinh Đại Assapura", titleEn: "The Greater Discourse at Assapura" },
  { type: "sutta", id: "mn40", code: "MN 40", titlePali: "Cūḷaassapura Sutta", titleVi: "Kinh Tiểu Assapura", titleEn: "The Shorter Discourse at Assapura" },
  { type: "sutta", id: "mn41", code: "MN 41", titlePali: "Sāleyyaka Sutta", titleVi: "Kinh Sāleyyaka", titleEn: "The People of Sālā" },
  { type: "sutta", id: "mn42", code: "MN 42", titlePali: "Verañjaka Sutta", titleVi: "Kinh Verañja", titleEn: "At Verañjā" },
  { type: "sutta", id: "mn43", code: "MN 43", titlePali: "Mahāvedalla Sutta", titleVi: "Kinh Đại Vấn Đáp", titleEn: "The Greater Set of Questions and Answers" },
  { type: "sutta", id: "mn44", code: "MN 44", titlePali: "Cūḷavedalla Sutta", titleVi: "Kinh Tiểu Vấn Đáp", titleEn: "The Shorter Set of Questions and Answers" },
  { type: "sutta", id: "mn45", code: "MN 45", titlePali: "Cūḷadhammasamādāna Sutta", titleVi: "Kinh Tiểu Thọ Trì Pháp", titleEn: "The Shorter Discourse on Taking Up Practices" },
  { type: "sutta", id: "mn46", code: "MN 46", titlePali: "Mahādhammasamādāna Sutta", titleVi: "Kinh Đại Thọ Trì Pháp", titleEn: "The Greater Discourse on Taking Up Practices" },
  { type: "sutta", id: "mn47", code: "MN 47", titlePali: "Vīmaṁsaka Sutta", titleVi: "Kinh Tư Sát", titleEn: "The Inquirer" },
  { type: "sutta", id: "mn48", code: "MN 48", titlePali: "Kosambiya Sutta", titleVi: "Kinh Kosambi", titleEn: "The Kosambiyans" },
  { type: "sutta", id: "mn49", code: "MN 49", titlePali: "Brahmanimantanika Sutta", titleVi: "Kinh Phạm Thiên Thỉnh Phật", titleEn: "The Invitation of the Brahmā" },
  { type: "sutta", id: "mn50", code: "MN 50", titlePali: "Māratajjaniya Sutta", titleVi: "Kinh Quở Trách Ác Ma", titleEn: "The Rebuke to Māra" },
  { type: "sutta", id: "mn51", code: "MN 51", titlePali: "Kandaraka Sutta", titleVi: "Kinh Kandaraka", titleEn: "With Kandaraka" },
  { type: "sutta", id: "mn52", code: "MN 52", titlePali: "Aṭṭhakanāgara Sutta", titleVi: "Kinh Aṭṭhakanāgara", titleEn: "The Man from Aṭṭhakanagara" },
  { type: "sutta", id: "mn53", code: "MN 53", titlePali: "Sekha Sutta", titleVi: "Kinh Hữu Học", titleEn: "The Disciple in Higher Training" },
  { type: "sutta", id: "mn54", code: "MN 54", titlePali: "Potaliya Sutta", titleVi: "Kinh Potaliya", titleEn: "To Potaliya" },
  { type: "sutta", id: "mn55", code: "MN 55", titlePali: "Jīvaka Sutta", titleVi: "Kinh Jīvaka", titleEn: "To Jīvaka" },
  { type: "sutta", id: "mn56", code: "MN 56", titlePali: "Upāli Sutta", titleVi: "Kinh Upāli", titleEn: "To Upāli" },
  { type: "sutta", id: "mn57", code: "MN 57", titlePali: "Kukkuravatika Sutta", titleVi: "Kinh Hạnh Chó", titleEn: "The Dog-Duty Ascetic" },
  { type: "sutta", id: "mn58", code: "MN 58", titlePali: "Abhayarājakumāra Sutta", titleVi: "Kinh Thái Tử Abhaya", titleEn: "To Prince Abhaya" },
  { type: "sutta", id: "mn59", code: "MN 59", titlePali: "Bahuvedanīya Sutta", titleVi: "Kinh Nhiều Cảm Thọ", titleEn: "The Many Kinds of Feeling" },
  { type: "sutta", id: "mn60", code: "MN 60", titlePali: "Apaṇṇaka Sutta", titleVi: "Kinh Không Thể Sai Lầm", titleEn: "The Incontrovertible Teaching" },
  { type: "sutta", id: "mn61", code: "MN 61", titlePali: "Ambalaṭṭhikā Rāhulovāda Sutta", titleVi: "Kinh Giáo Giới Rāhula tại Amba", titleEn: "Advice to Rāhula at Ambalaṭṭhikā" },
  { type: "sutta", id: "mn62", code: "MN 62", titlePali: "Mahārāhulovāda Sutta", titleVi: "Kinh Đại Giáo Giới Rāhula", titleEn: "The Greater Discourse on Advice to Rāhula" },
  { type: "sutta", id: "mn63", code: "MN 63", titlePali: "Cūḷamālukya Sutta", titleVi: "Kinh Tiểu Māluṅkyā", titleEn: "The Shorter Discourse to Māluṅkyāputta" },
  { type: "sutta", id: "mn64", code: "MN 64", titlePali: "Mahāmālukya Sutta", titleVi: "Kinh Đại Māluṅkyā", titleEn: "The Greater Discourse to Māluṅkyāputta" },
  { type: "sutta", id: "mn65", code: "MN 65", titlePali: "Bhaddāli Sutta", titleVi: "Kinh Bhaddāli", titleEn: "To Bhaddāli" },
  { type: "sutta", id: "mn66", code: "MN 66", titlePali: "Laṭukikopama Sutta", titleVi: "Kinh Ví Dụ Chim Cút", titleEn: "The Quail Simile" },
  { type: "sutta", id: "mn67", code: "MN 67", titlePali: "Cātumā Sutta", titleVi: "Kinh Cātumā", titleEn: "At Cātumā" },
  { type: "sutta", id: "mn68", code: "MN 68", titlePali: "Naḷakapāna Sutta", titleVi: "Kinh Naḷakapāna", titleEn: "At Naḷakapāna" },
  { type: "sutta", id: "mn69", code: "MN 69", titlePali: "Goliyāni Sutta", titleVi: "Kinh Goliyāni", titleEn: "At Goliyāni" },
  { type: "sutta", id: "mn70", code: "MN 70", titlePali: "Kīṭāgiri Sutta", titleVi: "Kinh Kīṭāgiri", titleEn: "At Kīṭāgiri" },
  { type: "sutta", id: "mn71", code: "MN 71", titlePali: "Tevijjavacchagotta Sutta", titleVi: "Kinh Tevijja Vacchagotta", titleEn: "To Vacchagotta on the Threefold Knowledge" },
  { type: "sutta", id: "mn72", code: "MN 72", titlePali: "Aggivacchagotta Sutta", titleVi: "Kinh Aggivacchagotta", titleEn: "To Vacchagotta on Fire" },
  { type: "sutta", id: "mn73", code: "MN 73", titlePali: "Mahāvacchagotta Sutta", titleVi: "Kinh Đại Vacchagotta", titleEn: "The Greater Discourse to Vacchagotta" },
  { type: "sutta", id: "mn74", code: "MN 74", titlePali: "Dīghanakha Sutta", titleVi: "Kinh Trường Trảo", titleEn: "To Dīghanakha" },
  { type: "sutta", id: "mn75", code: "MN 75", titlePali: "Māgaṇḍiya Sutta", titleVi: "Kinh Māgaṇḍiya", titleEn: "To Māgaṇḍiya" },
  { type: "sutta", id: "mn76", code: "MN 76", titlePali: "Sandaka Sutta", titleVi: "Kinh Sandaka", titleEn: "To Sandaka" },
  { type: "sutta", id: "mn77", code: "MN 77", titlePali: "Mahāsakuludāyi Sutta", titleVi: "Kinh Đại Sakuludāyi", titleEn: "The Greater Discourse to Sakuludāyī" },
  { type: "sutta", id: "mn78", code: "MN 78", titlePali: "Samaṇamuṇḍika Sutta", titleVi: "Kinh Sa Môn Trọc Đầu", titleEn: "The Shaveling Ascetic" },
  { type: "sutta", id: "mn79", code: "MN 79", titlePali: "Cūḷasakuludāyi Sutta", titleVi: "Kinh Tiểu Sakuludāyi", titleEn: "The Shorter Discourse to Sakuludāyī" },
  { type: "sutta", id: "mn80", code: "MN 80", titlePali: "Vekhanassa Sutta", titleVi: "Kinh Vekhanassa", titleEn: "To Vekhanassa" },
  { type: "sutta", id: "mn81", code: "MN 81", titlePali: "Ghaṭikāra Sutta", titleVi: "Kinh Ghaṭikāra", titleEn: "With Ghaṭikāra" },
  { type: "sutta", id: "mn82", code: "MN 82", titlePali: "Raṭṭhapāla Sutta", titleVi: "Kinh Raṭṭhapāla", titleEn: "About Raṭṭhapāla" },
  { type: "sutta", id: "mn83", code: "MN 83", titlePali: "Maghadeva Sutta", titleVi: "Kinh Maghadeva", titleEn: "On King Maghadeva" },
  { type: "sutta", id: "mn84", code: "MN 84", titlePali: "Madhura Sutta", titleVi: "Kinh Madhura", titleEn: "At Madhurā" },
  { type: "sutta", id: "mn85", code: "MN 85", titlePali: "Bodhirājakumāra Sutta", titleVi: "Kinh Thái Tử Bodhi", titleEn: "To Prince Bodhi" },
  { type: "sutta", id: "mn86", code: "MN 86", titlePali: "Aṅgulimāla Sutta", titleVi: "Kinh Aṅgulimāla", titleEn: "About Aṅgulimāla" },
  { type: "sutta", id: "mn87", code: "MN 87", titlePali: "Piyajātika Sutta", titleVi: "Kinh Ái Sanh", titleEn: "Born from Affection" },
  { type: "sutta", id: "mn88", code: "MN 88", titlePali: "Bāhitika Sutta", titleVi: "Kinh Bāhitika", titleEn: "About the Cloak" },
  { type: "sutta", id: "mn89", code: "MN 89", titlePali: "Dhammacetiya Sutta", titleVi: "Kinh Bảo Tháp Pháp", titleEn: "Monuments to the Dhamma" },
  { type: "sutta", id: "mn90", code: "MN 90", titlePali: "Kaṇṇakatthala Sutta", titleVi: "Kinh Kaṇṇakatthala", titleEn: "At Kaṇṇakatthala" },
  { type: "sutta", id: "mn91", code: "MN 91", titlePali: "Brahmāyu Sutta", titleVi: "Kinh Bà La Môn Brahmāyu", titleEn: "With Brahmāyu" },
  { type: "sutta", id: "mn92", code: "MN 92", titlePali: "Sela Sutta", titleVi: "Kinh Sela", titleEn: "With Sela" },
  { type: "sutta", id: "mn93", code: "MN 93", titlePali: "Assalāyana Sutta", titleVi: "Kinh Assalāyana", titleEn: "To Assalāyana" },
  { type: "sutta", id: "mn94", code: "MN 94", titlePali: "Ghoṭamukha Sutta", titleVi: "Kinh Ghoṭamukha", titleEn: "With Ghoṭamukha" },
  { type: "sutta", id: "mn95", code: "MN 95", titlePali: "Caṅkī Sutta", titleVi: "Kinh Caṅkī", titleEn: "With Caṅkī" },
  { type: "sutta", id: "mn96", code: "MN 96", titlePali: "Esukārī Sutta", titleVi: "Kinh Esukārī", titleEn: "With Esukārī" },
  { type: "sutta", id: "mn97", code: "MN 97", titlePali: "Dhanañjāni Sutta", titleVi: "Kinh Dhanañjāni", titleEn: "With Dhanañjāni" },
  { type: "sutta", id: "mn98", code: "MN 98", titlePali: "Vāseṭṭha Sutta", titleVi: "Kinh Vāseṭṭha", titleEn: "With Vāseṭṭha" },
  { type: "sutta", id: "mn99", code: "MN 99", titlePali: "Subha Sutta", titleVi: "Kinh Subha", titleEn: "To Subha" },
  { type: "sutta", id: "mn100", code: "MN 100", titlePali: "Saṅgārava Sutta", titleVi: "Kinh Saṅgārava", titleEn: "To Saṅgārava" },
  { type: "sutta", id: "mn101", code: "MN 101", titlePali: "Devadaha Sutta", titleVi: "Kinh Devadaha", titleEn: "At Devadaha" },
  { type: "sutta", id: "mn102", code: "MN 102", titlePali: "Pañcattaya Sutta", titleVi: "Kinh Năm Quan Điểm", titleEn: "Five and Three" },
  { type: "sutta", id: "mn103", code: "MN 103", titlePali: "Kinti Sutta", titleVi: "Kinh Kinti", titleEn: "What Do You Think of Me?" },
  { type: "sutta", id: "mn104", code: "MN 104", titlePali: "Sāmagāma Sutta", titleVi: "Kinh Sāmagāma", titleEn: "At Sāmagāma" },
  { type: "sutta", id: "mn105", code: "MN 105", titlePali: "Sunakkhatta Sutta", titleVi: "Kinh Sunakkhatta", titleEn: "To Sunakkhatta" },
  { type: "sutta", id: "mn106", code: "MN 106", titlePali: "Āneñjasappāya Sutta", titleVi: "Kinh Con Đường Bất Động", titleEn: "The Way to the Imperturbable" },
  { type: "sutta", id: "mn107", code: "MN 107", titlePali: "Gaṇakamoggallāna Sutta", titleVi: "Kinh Moggallāna Người Tính Toán", titleEn: "To Gaṇaka Moggallāna" },
  { type: "sutta", id: "mn108", code: "MN 108", titlePali: "Gopakamoggallāna Sutta", titleVi: "Kinh Gopaka Moggallāna", titleEn: "With Gopaka Moggallāna" },
  { type: "sutta", id: "mn109", code: "MN 109", titlePali: "Mahāpuṇṇama Sutta", titleVi: "Kinh Đêm Trăng Tròn Lớn", titleEn: "The Greater Full-Moon Night" },
  { type: "sutta", id: "mn110", code: "MN 110", titlePali: "Cūḷapuṇṇama Sutta", titleVi: "Kinh Đêm Trăng Tròn Nhỏ", titleEn: "The Smaller Full-Moon Night" },
  { type: "sutta", id: "mn111", code: "MN 111", titlePali: "Anupada Sutta", titleVi: "Kinh Từng Bước", titleEn: "One by One as They Occurred" },
  { type: "sutta", id: "mn112", code: "MN 112", titlePali: "Chabbisodhana Sutta", titleVi: "Kinh Sáu Thanh Tịnh", titleEn: "The Sixfold Purity" },
  { type: "sutta", id: "mn113", code: "MN 113", titlePali: "Sappurisa Sutta", titleVi: "Kinh Người Chân Chánh", titleEn: "The True Person" },
  { type: "sutta", id: "mn114", code: "MN 114", titlePali: "Sevitabba Sutta", titleVi: "Kinh Nên Gần Gũi", titleEn: "To Be Cultivated" },
  { type: "sutta", id: "mn115", code: "MN 115", titlePali: "Bahudhātuka Sutta", titleVi: "Kinh Nhiều Giới", titleEn: "The Many Kinds of Elements" },
  { type: "sutta", id: "mn116", code: "MN 116", titlePali: "Isigili Sutta", titleVi: "Kinh Isigili", titleEn: "At Isigili" },
  { type: "sutta", id: "mn117", code: "MN 117", titlePali: "Mahācattārīsaka Sutta", titleVi: "Kinh Bốn Mươi Lớn", titleEn: "The Great Forty" },
  { type: "sutta", id: "mn118", code: "MN 118", titlePali: "Ānāpānasati Sutta", titleVi: "Kinh Niệm Hơi Thở", titleEn: "Mindfulness of Breathing" },
  { type: "sutta", id: "mn119", code: "MN 119", titlePali: "Kāyagatāsati Sutta", titleVi: "Kinh Niệm Thân", titleEn: "Mindfulness of the Body" },
  { type: "sutta", id: "mn120", code: "MN 120", titlePali: "Saṅkhārupapatti Sutta", titleVi: "Kinh Sanh Theo Nghiệp", titleEn: "Reappearance by Volitional Formations" },
  { type: "sutta", id: "mn121", code: "MN 121", titlePali: "Cūḷasuññata Sutta", titleVi: "Kinh Không Nhỏ", titleEn: "The Shorter Discourse on Emptiness" },
  { type: "sutta", id: "mn122", code: "MN 122", titlePali: "Mahāsuññata Sutta", titleVi: "Kinh Không Lớn", titleEn: "The Greater Discourse on Emptiness" },
  { type: "sutta", id: "mn123", code: "MN 123", titlePali: "Acchariyabbhuta Sutta", titleVi: "Kinh Hy Hữu Vị Tằng Hữu", titleEn: "Wonderful and Marvellous" },
  { type: "sutta", id: "mn124", code: "MN 124", titlePali: "Bakkula Sutta", titleVi: "Kinh Bakkula", titleEn: "About Bakkula" },
  { type: "sutta", id: "mn125", code: "MN 125", titlePali: "Dantabhūmi Sutta", titleVi: "Kinh Điều Phục", titleEn: "The Grade of the Tamed" },
  { type: "sutta", id: "mn126", code: "MN 126", titlePali: "Bhūmija Sutta", titleVi: "Kinh Bhūmija", titleEn: "To Bhūmija" },
  { type: "sutta", id: "mn127", code: "MN 127", titlePali: "Anuruddha Sutta", titleVi: "Kinh Anuruddha", titleEn: "To Anuruddha" },
  { type: "sutta", id: "mn128", code: "MN 128", titlePali: "Upakkilesa Sutta", titleVi: "Kinh Nhiễm Ô", titleEn: "The Corruptions" },
  { type: "sutta", id: "mn129", code: "MN 129", titlePali: "Bālapaṇḍita Sutta", titleVi: "Kinh Người Ngu – Người Trí", titleEn: "The Fool and the Wise" },
  { type: "sutta", id: "mn130", code: "MN 130", titlePali: "Devadūta Sutta", titleVi: "Kinh Sứ Giả Chư Thiên", titleEn: "The Divine Messengers" },
  { type: "sutta", id: "mn131", code: "MN 131", titlePali: "Bhaddekaratta Sutta", titleVi: "Kinh Một Đêm An Lành", titleEn: "One Fortunate Attachment to the Present" },
  { type: "sutta", id: "mn132", code: "MN 132", titlePali: "Ānandabhaddekaratta Sutta", titleVi: "Kinh Một Đêm An Lành với Ananda", titleEn: "Ānanda and One Fortunate Attachment to the Present" },
  { type: "sutta", id: "mn133", code: "MN 133", titlePali: "Mahākaccānabhaddekaratta Sutta", titleVi: "Kinh Một Đêm An Lành với Mahākaccāna", titleEn: "Mahākaccāna and One Fortunate Attachment to the Present" },
  { type: "sutta", id: "mn134", code: "MN 134", titlePali: "Lomasakaṅgiya Sutta", titleVi: "Kinh Lomasakaṅgiya", titleEn: "To Lomasakaṅgiya" },
  { type: "sutta", id: "mn135", code: "MN 135", titlePali: "Cūḷakammavibhaṅga Sutta", titleVi: "Kinh Tiểu Nghiệp Phân Biệt", titleEn: "The Shorter Exposition of Kamma" },
  { type: "sutta", id: "mn136", code: "MN 136", titlePali: "Mahākammavibhaṅga Sutta", titleVi: "Kinh Đại Nghiệp Phân Biệt", titleEn: "The Greater Exposition of Kamma" },
  { type: "sutta", id: "mn137", code: "MN 137", titlePali: "Saḷāyatanavibhaṅga Sutta", titleVi: "Kinh Phân Biệt Sáu Xứ", titleEn: "The Exposition of the Six Sense Bases" },
  { type: "sutta", id: "mn138", code: "MN 138", titlePali: "Uddesavibhaṅga Sutta", titleVi: "Kinh Phân Biệt Tóm Tắt", titleEn: "The Exposition of a Summary" },
  { type: "sutta", id: "mn139", code: "MN 139", titlePali: "Araṇavibhaṅga Sutta", titleVi: "Kinh Phân Biệt Không Tranh Cãi", titleEn: "The Exposition of Non-Conflict" },
  { type: "sutta", id: "mn140", code: "MN 140", titlePali: "Dhātuvibhaṅga Sutta", titleVi: "Kinh Phân Biệt Các Giới", titleEn: "The Exposition of the Elements" },
  { type: "sutta", id: "mn141", code: "MN 141", titlePali: "Saccavibhaṅga Sutta", titleVi: "Kinh Phân Biệt Thánh Đế", titleEn: "The Exposition of the Truths" },
  { type: "sutta", id: "mn142", code: "MN 142", titlePali: "Dakkhiṇāvibhaṅga Sutta", titleVi: "Kinh Phân Biệt Bố Thí", titleEn: "The Exposition of Offerings" },
  { type: "sutta", id: "mn143", code: "MN 143", titlePali: "Anāthapiṇḍikovāda Sutta", titleVi: "Kinh Giáo Giới Cấp Cô Độc", titleEn: "Advice to Anāthapiṇḍika" },
  { type: "sutta", id: "mn144", code: "MN 144", titlePali: "Channovāda Sutta", titleVi: "Kinh Giáo Giới Channa", titleEn: "Advice to Channa" },
  { type: "sutta", id: "mn145", code: "MN 145", titlePali: "Puṇṇovāda Sutta", titleVi: "Kinh Giáo Giới Puṇṇa", titleEn: "Advice to Puṇṇa" },
  { type: "sutta", id: "mn146", code: "MN 146", titlePali: "Nandakovāda Sutta", titleVi: "Kinh Giáo Giới Nandaka", titleEn: "Advice to Nandaka" },
  { type: "sutta", id: "mn147", code: "MN 147", titlePali: "Cūḷarāhulovāda Sutta", titleVi: "Kinh Tiểu Giáo Giới Rāhula", titleEn: "The Shorter Advice to Rāhula" },
  { type: "sutta", id: "mn148", code: "MN 148", titlePali: "Chachakka Sutta", titleVi: "Kinh Sáu Bộ Sáu", titleEn: "The Analysis of the Six Sets of Six" },
  { type: "sutta", id: "mn149", code: "MN 149", titlePali: "Mahāsaḷāyatanika Sutta", titleVi: "Kinh Đại Sáu Xứ", titleEn: "The Great Sixfold Sense Base" },
  { type: "sutta", id: "mn150", code: "MN 150", titlePali: "Nagaravindeyya Sutta", titleVi: "Kinh Nagaravindeyya", titleEn: "At Nagaravinda" },
  { type: "sutta", id: "mn151", code: "MN 151", titlePali: "Piṇḍapātapārisuddhi Sutta", titleVi: "Kinh Thanh Tịnh Thọ Dụng", titleEn: "The Purification of Alms-food" },
  { type: "sutta", id: "mn152", code: "MN 152", titlePali: "Indriyabhāvanā Sutta", titleVi: "Kinh Tu Tập Các Căn", titleEn: "The Development of the Faculties" }


]


  },
  {
    type: "nikaya",
    key: "SN",
    labelVi: "Saṃyutta Nikāya - Tương Ưng Bộ Kinh",
    labelEn: "Saṃyutta Nikāya - Connected Discourses",
    children: [
  { type: "sutta", id: "sn1_v1", code: "SN 1", titlePali: "Devatā-saṁyutta", titleVi: "Chủ đề 1: Chư Thiên", titleEn: "Linked Discourses With Deities" },
  { type: "sutta", id: "sn2_v1", code: "SN 2", titlePali: "Devaputta-saṁyutta", titleVi: "Chủ đề 2: Thiên Tử", titleEn: "Linked Discourses With Gods' Sons" },
  { type: "sutta", id: "sn3_v1", code: "SN 3", titlePali: "Kosala-saṁyutta", titleVi: "Chủ đề 3: Kosala", titleEn: "Linked Discourses With the Kosalan" },
  { type: "sutta", id: "sn4_v1", code: "SN 4", titlePali: "Māra-saṁyutta", titleVi: "Chủ đề 4: Mara", titleEn: "Linked Discourses With Māra" },
  { type: "sutta", id: "sn5_v1", code: "SN 5", titlePali: "Bhikkhunī-saṁyutta", titleVi: "Chủ đề 5: Tỳ-Kheo-Ni", titleEn: "Linked Discourses With Nuns" },
  { type: "sutta", id: "sn6_v1", code: "SN 6", titlePali: "Brahma-saṁyutta", titleVi: "Chủ đề 6: Phạm Thiên", titleEn: "Linked Discourses With Brahmās" },
  { type: "sutta", id: "sn7_v1", code: "SN 7", titlePali: "Brāhmaṇa-saṁyutta", titleVi: "Chủ đề 7: Bà-la-môn", titleEn: "Linked Discourses With Brahmins" },
  { type: "sutta", id: "sn8_v1", code: "SN 8", titlePali: "Vaṅgīsa-saṁyutta", titleVi: "Chủ đề 8: Trưởng Lão Vaṅgīsa", titleEn: "Linked Discourses With Vaṅgīsa" },
  { type: "sutta", id: "sn9_v1", code: "SN 9", titlePali: "Vana-saṁyutta", titleVi: "Chủ đề 9: Rừng", titleEn: "Linked Discourses in the Woods" },
  { type: "sutta", id: "sn10_v1", code: "SN 10", titlePali: "Yakkha-saṁyutta", titleVi: "Chủ đề 10: Dạ Xoa", titleEn: "Linked Discourses With Spirits" },
  { type: "sutta", id: "sn11_v1", code: "SN 11", titlePali: "Sakka-saṁyutta", titleVi: "Chủ đề 11: Đế thích", titleEn: "Linked Discourses With Sakka" },
  { type: "sutta", id: "sn12_v1", code: "SN 12", titlePali: "Nidāna-saṁyutta", titleVi: "Chủ đề 12: Nhân duyên", titleEn: "Linked Discourses on Causation" },
  { type: "sutta", id: "sn13_v1", code: "SN 13", titlePali: "Abhisamaya-saṁyutta", titleVi: "Chủ đề 13: Đột hiện", titleEn: "Linked Discourses on Comprehension" },
  { type: "sutta", id: "sn14_v1", code: "SN 14", titlePali: "Dhātu-saṁyutta", titleVi: "Chủ đề 14: Các thành tố", titleEn: "Linked Discourses on the Elements" },
  { type: "sutta", id: "sn15_v1", code: "SN 15", titlePali: "Anamatagga-saṁyutta", titleVi: "Chủ đề 15: Vô thỉ", titleEn: "Linked Discourses on the Unknown Beginning" },
  { type: "sutta", id: "sn16_v1", code: "SN 16", titlePali: "Kassapa-saṁyutta", titleVi: "Chủ đề 16: Kassapa", titleEn: "Linked Discourses With Kassapa" },
  { type: "sutta", id: "sn17_v1", code: "SN 17", titlePali: "Lābhasakkāra-saṁyutta", titleVi: "Chủ đề 17: Lợi đắc Cung kính", titleEn: "Linked Discourses on Possessions, Honor, and Popularity" },
  { type: "sutta", id: "sn18_v1", code: "SN 18", titlePali: "Rāhula-saṁyutta", titleVi: "Chủ đề 18: Rāhula", titleEn: "Linked Discourses With Rāhula" },
  { type: "sutta", id: "sn19_v1", code: "SN 19", titlePali: "Lakkhaṇa-saṁyutta", titleVi: "Chủ đề 19: Lakkhaṇa", titleEn: "Linked Discourses With Lakkhaṇa" },
  { type: "sutta", id: "sn20_v1", code: "SN 20", titlePali: "Opamma-saṁyutta", titleVi: "Chủ đề 20: Thí dụ", titleEn: "Linked Discourses on Similes" },
  { type: "sutta", id: "sn21_v1", code: "SN 21", titlePali: "Bhikkhu-saṁyutta", titleVi: "Chủ đề 21: Tỳ-Kheo", titleEn: "Linked Discourses With Mendicants" },
  { type: "sutta", id: "sn22_v1", code: "SN 22", titlePali: "Khandha-saṁyutta", titleVi: "Chủ đề 22: Uẩn", titleEn: "Linked Discourses on the Aggregates" },
  { type: "sutta", id: "sn23_v1", code: "SN 23", titlePali: "Rādha-saṁyutta", titleVi: "Chủ đề 23: Rādha", titleEn: "Linked Discourses With Rādha" },
  { type: "sutta", id: "sn24_v1", code: "SN 24", titlePali: "Diṭṭhi-saṁyutta", titleVi: "Chủ đề 24: Kiến", titleEn: "Linked Discourses on Views" },
  { type: "sutta", id: "sn25_v1", code: "SN 25", titlePali: "Okkanta-saṁyutta", titleVi: "Chủ đề 25: Nhập", titleEn: "Linked Discourses on Arrival" },
  { type: "sutta", id: "sn26_v1", code: "SN 26", titlePali: "Uppāda-saṁyutta", titleVi: "Chủ đề 26: Sanh", titleEn: "Linked Discourses on Arising" },
  { type: "sutta", id: "sn27_v1", code: "SN 27", titlePali: "Kilesa-saṁyutta", titleVi: "Chủ đề 27: Phiền não", titleEn: "Linked Discourses on Corruptions" },
  { type: "sutta", id: "sn28_v1", code: "SN 28", titlePali: "Sāriputta-saṁyutta", titleVi: "Chủ đề 28: Sāriputta", titleEn: "Linked Discourses With Sāriputta" },
  { type: "sutta", id: "sn29_v1", code: "SN 29", titlePali: "Nāga-saṁyutta", titleVi: "Chủ đề 29: Rồng", titleEn: "Linked Discourses on Dragons" },
  { type: "sutta", id: "sn30_v1", code: "SN 30", titlePali: "Supaṇṇa-saṁyutta", titleVi: "Chủ đề 30: Supaṇṇa", titleEn: "Linked Discourses With Phoenixes" },
  { type: "sutta", id: "sn31_v1", code: "SN 31", titlePali: "Gandhabbakāya-saṁyutta", titleVi: "Chủ đề 31: Gandhabba", titleEn: "Linked Discourses With Centaurs" },
  { type: "sutta", id: "sn32_v1", code: "SN 32", titlePali: "Valāhaka-saṁyutta", titleVi: "Chủ đề 32: Thần mây", titleEn: "Linked Discourses With Cloud Gods" },
  { type: "sutta", id: "sn33_v1", code: "SN 33", titlePali: "Vacchagotta-saṁyutta", titleVi: "Chủ đề 33: Vacchagotta", titleEn: "Linked Discourses With Vacchagotta" },
  { type: "sutta", id: "sn34_v1", code: "SN 34", titlePali: "Jhāna-saṁyutta", titleVi: "Chủ đề 34: Thiền định", titleEn: "Linked Discourses on Absorption" },
  { type: "sutta", id: "sn35_v1", code: "SN 35", titlePali: "Saḷāyatana-saṁyutta", titleVi: "Chủ đề 35: Sáu xứ", titleEn: "Linked Discourses on the Six Sense Fields" },
  { type: "sutta", id: "sn36_v1", code: "SN 36", titlePali: "Vedanā-saṁyutta", titleVi: "Chủ đề 36: Cảm giác", titleEn: "Linked Discourses on Feeling" },
  { type: "sutta", id: "sn37_v1", code: "SN 37", titlePali: "Mātugāma-saṁyutta", titleVi: "Chủ đề 37: Nữ nhân", titleEn: "Linked Discourses With Women" },
  { type: "sutta", id: "sn38_v1", code: "SN 38", titlePali: "Jambukhādaka-saṁyutta", titleVi: "Chủ đề 38: Jambukhādaka", titleEn: "Linked Discourses With Jambukhādaka" },
  { type: "sutta", id: "sn39_v1", code: "SN 39", titlePali: "Sāmaṇḍaka-saṁyutta", titleVi: "Chủ đề 39: Jambukhādaka", titleEn: "Linked Discourses With Sāmaṇḍaka" },
  { type: "sutta", id: "sn40_v1", code: "SN 40", titlePali: "Moggallāna-saṁyutta", titleVi: "Chủ đề 40: Moggallāna", titleEn: "Linked Discourses With Moggallāna" },
  { type: "sutta", id: "sn41_v1", code: "SN 41", titlePali: "Citta-saṁyutta", titleVi: "Chủ đề 41: Cư sĩ Citta", titleEn: "Linked Discourses With Citta" },
  { type: "sutta", id: "sn42_v1", code: "SN 42", titlePali: "Gāmaṇi-saṁyutta", titleVi: "Chủ đề 42: Thôn trưởng", titleEn: "Linked Discourses With Chiefs" },
  { type: "sutta", id: "sn43_v1", code: "SN 43", titlePali: "Asaṅkhata-saṁyutta", titleVi: "Chủ đề 43: Vô vi", titleEn: "Linked Discourses on the Unconditioned" },
  { type: "sutta", id: "sn44_v1", code: "SN 44", titlePali: "Abyākata-saṁyutta", titleVi: "Chủ đề 44: Không thuyết", titleEn: "Linked Discourses on the Undeclared Points" },
  { type: "sutta", id: "sn45_v1", code: "SN 45", titlePali: "Magga-saṁyutta", titleVi: "Chủ đề 45: Đạo", titleEn: "Linked Discourses on the Path" },
  { type: "sutta", id: "sn46_v1", code: "SN 46", titlePali: "Bojjhaṅga-saṁyutta", titleVi: "Chủ đề 46: Giác chi", titleEn: "Linked Discourses on the Awakening Factors" },
  { type: "sutta", id: "sn47_v1", code: "SN 47", titlePali: "Satipaṭṭhāna-saṁyutta", titleVi: "Chủ đề 47: Niệm xứ", titleEn: "Linked Discourses on Mindfulness Meditation" },
  { type: "sutta", id: "sn48_v1", code: "SN 48", titlePali: "Indriya-saṁyutta", titleVi: "Chủ đề 48: Căn", titleEn: "Linked Discourses on the Faculties" },
  { type: "sutta", id: "sn49_v1", code: "SN 49", titlePali: "Sammappadhāna-saṁyutta", titleVi: "Chủ đề 49: Chánh cần", titleEn: "Linked Discourses on the Right Efforts" },
  { type: "sutta", id: "sn50_v1", code: "SN 50", titlePali: "Bala-saṁyutta", titleVi: "Chủ đề 50: Lực", titleEn: "Linked Discourses on the Powers" },
  { type: "sutta", id: "sn51_v1", code: "SN 51", titlePali: "Iddhipāda-saṁyutta", titleVi: "Chủ đề 51: Thần túc", titleEn: "Linked Discourses on the Bases of Psychic Power" },
  { type: "sutta", id: "sn52_v1", code: "SN 52", titlePali: "Anuruddha-saṁyutta", titleVi: "Chủ đề 52: Anuruddha", titleEn: "Linked Discourses With Anuruddha" },
  { type: "sutta", id: "sn53_v1", code: "SN 53", titlePali: "Jhāna-saṁyutta", titleVi: "Chủ đề 53: Thiền", titleEn: "Linked Discourses on Absorption" },
  { type: "sutta", id: "sn54_v1", code: "SN 54", titlePali: "Ānāpāna-saṁyutta", titleVi: "Chủ đề 54: Hơi thở vào Hơi thở ra", titleEn: "Linked Discourses on Breath Meditation" },
  { type: "sutta", id: "sn55_v1", code: "SN 55", titlePali: "Sotāpatti-saṁyutta", titleVi: "Chủ đề 55: Dự lưu", titleEn: "Linked Discourses on Stream-Entry" },
  { type: "sutta", id: "sn56_v1", code: "SN 56", titlePali: "Sacca-saṁyutta", titleVi: "Chủ đề 56: Sự thật", titleEn: "Linked Discourses on the Truths" }
]
},
  {
    type: "nikaya",
    key: "AN",
    labelVi: "Aṅguttara Nikāya - Tăng Chi Bộ Kinh",
    labelEn: "Aṅguttara Nikāya - Numerical Discourses",
    children: [
  
  { type: "sutta", id: "an1_v1", code: "AN 1", titlePali: "Aṅguttara Nikāya 1", titleVi: "Nhóm Một Pháp", titleEn: "Numbered Discourses 1" },
  { type: "sutta", id: "an2_v1", code: "AN 2", titlePali: "Aṅguttara Nikāya 2", titleVi: "Nhóm Hai Pháp", titleEn: "Numbered Discourses 2" },
  { type: "sutta", id: "an3_v1", code: "AN 3", titlePali: "Aṅguttara Nikāya 3", titleVi: "Nhóm Ba Pháp", titleEn: "Numbered Discourses 3" },
  { type: "sutta", id: "an4_v1", code: "AN 4", titlePali: "Aṅguttara Nikāya 4", titleVi: "Nhóm Bốn Pháp", titleEn: "Numbered Discourses 4" },
  { type: "sutta", id: "an5_v1", code: "AN 5", titlePali: "Aṅguttara Nikāya 5", titleVi: "Nhóm Năm Pháp", titleEn: "Numbered Discourses 5" },
  { type: "sutta", id: "an6_v1", code: "AN 6", titlePali: "Aṅguttara Nikāya 6", titleVi: "Nhóm Sáu Pháp", titleEn: "Numbered Discourses 6" },
  { type: "sutta", id: "an7_v1", code: "AN 7", titlePali: "Aṅguttara Nikāya 7", titleVi: "Nhóm Bảy Pháp", titleEn: "Numbered Discourses 7" },
  { type: "sutta", id: "an8_v1", code: "AN 8", titlePali: "Aṅguttara Nikāya 8", titleVi: "Nhóm Tám Pháp", titleEn: "Numbered Discourses 8" },
  { type: "sutta", id: "an9_v1", code: "AN 9", titlePali: "Aṅguttara Nikāya 9", titleVi: "Nhóm Chín Pháp", titleEn: "Numbered Discourses 9" },
  { type: "sutta", id: "an10_v1", code: "AN 10", titlePali: "Aṅguttara Nikāya 10", titleVi: "Nhóm Mười Pháp", titleEn: "Numbered Discourses 10" },
  { type: "sutta", id: "an11_v1", code: "AN 11", titlePali: "Aṅguttara Nikāya 11", titleVi: "Nhóm Mười Một Pháp", titleEn: "Numbered Discourses 11" }
	]
   }
]
;
