window.BILARA = window.BILARA || {};
window.BILARA["sn16_v1"] = window.BILARA["sn16_v1"] || {};
window.BILARA["sn16_v1"]["vi"] = {
  "sn16.1:0.1": "Tương Ưng Bộ 16.1 ",
  "sn16.1:0.2": "1. Phẩm Kassapa ",
  "sn16.1:0.3": "Kinh Biết Đủ ",
  "sn16.1:1.1": "Tại Sāvatthī. ",
  "sn16.1:1.2": "'Này các Tỳ Kheo, Kassapa biết đủ với bất kỳ y phục nào, và tán thán sự biết đủ với y phục; '",
  "sn16.1:1.3": "vị ấy không làm điều sai trái, không đáng làm vì lợi lộc y phục; khi không được y phục, không lo âu; khi được y phục, thọ dụng mà không tham đắm, không mê say, không dính mắc, thấy rõ sự nguy hiểm và biết cách thoát ra. ",
  "sn16.1:2.1": "Này các Tỳ Kheo, Kassapa biết đủ với bất kỳ vật thực khất thực nào, và tán thán sự biết đủ với vật thực khất thực; vị ấy không làm điều sai trái, không đáng làm vì lợi lộc vật thực; khi không được vật thực, không lo âu; khi được vật thực, thọ dụng mà không tham đắm, không mê say, không dính mắc, thấy rõ sự nguy hiểm và biết cách thoát ra. ",
  "sn16.1:3.1": "Này các Tỳ Kheo, Kassapa biết đủ với bất kỳ chỗ ở nào, và tán thán sự biết đủ với chỗ ở; vị ấy không làm điều sai trái, không đáng làm vì lợi lộc chỗ ở; khi không được chỗ ở, không lo âu; khi được chỗ ở, thọ dụng mà không tham đắm, không mê say, không dính mắc, thấy rõ sự nguy hiểm và biết cách thoát ra. ",
  "sn16.1:4.1": "Này các Tỳ Kheo, Kassapa biết đủ với bất kỳ thuốc men và vật dụng trị bệnh nào, và tán thán sự biết đủ với thuốc men và vật dụng trị bệnh; vị ấy không làm điều sai trái, không đáng làm vì lợi lộc thuốc men; khi không được thuốc men, không lo âu; khi được thuốc men, thọ dụng mà không tham đắm, không mê say, không dính mắc, thấy rõ sự nguy hiểm và biết cách thoát ra. ",
  "sn16.1:5.1": "Vì vậy, này các Tỳ Kheo, hãy học tập như sau: 'Chúng ta sẽ biết đủ với bất kỳ y phục nào, và tán thán sự biết đủ với y phục; chúng ta sẽ không làm điều sai trái, không đáng làm vì lợi lộc y phục; ",
  "sn16.1:5.2": "khi không được y phục, chúng ta sẽ không lo âu; khi được y phục, chúng ta sẽ thọ dụng mà không tham đắm, không mê say, không dính mắc, thấy rõ sự nguy hiểm và biết cách thoát ra'. ",
  "sn16.1:5.3": "(Tất cả đều phải làm như vậy.) ",
  "sn16.1:6.1": "'Chúng ta sẽ biết đủ với bất kỳ vật thực khất thực nào …vân vân… '",
  "sn16.1:6.2": "chúng ta sẽ biết đủ với bất kỳ chỗ ở nào …vân vân… ",
  "sn16.1:6.3": "chúng ta sẽ biết đủ với bất kỳ thuốc men và vật dụng trị bệnh nào, và tán thán sự biết đủ với thuốc men và vật dụng trị bệnh; chúng ta sẽ không làm điều sai trái, không đáng làm vì lợi lộc thuốc men; khi không được thuốc men, chúng ta sẽ không lo âu; khi được thuốc men, chúng ta sẽ thọ dụng mà không tham đắm, không mê say, không dính mắc, thấy rõ sự nguy hiểm và biết cách thoát ra'. ",
  "sn16.1:6.4": "Như vậy, này các Tỳ Kheo, các ông hãy học tập. ",
  "sn16.1:6.5": "Này các Tỳ Kheo, Ta sẽ giáo giới các ông như Kassapa, hoặc người nào giống như Kassapa; và khi được giáo giới, các ông hãy thực hành đúng như vậy.' ",
  "sn16.1:6.6": "Kinh thứ nhất. ",
  "sn16.2:0.1": "Tương Ưng Bộ 16.2 ",
  "sn16.2:0.2": "1. Phẩm Kassapa ",
  "sn16.2:0.3": "Kinh Không Biết Sợ ",
  "sn16.2:1.1": "Tôi đã nghe như vầy",
  "sn16.2:1.2": "một thời Tôn giả Mahākassapa và Tôn giả Sāriputta đang ở tại Bārāṇasī, vườn Lộc Uyển Isipatana. ",
  "sn16.2:1.3": "Rồi Tôn giả Sāriputta vào buổi chiều, sau khi xuất định, đến chỗ Tôn giả Mahākassapa. ",
  "sn16.2:1.4": "Sau khi chào hỏi thân thiện với Tôn giả Mahākassapa, ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Sāriputta nói với Tôn giả Mahākassapa: ",
  "sn16.2:1.5": "'Thưa hiền giả Kassapa, người ta nói: 'Người không có nhiệt tâm, không có sự biết sợ hãi thì không thể giác ngộ, không thể đạt Niết-bàn, không thể đạt sự an ổn vô thượng thoát khỏi ách phược; ",
  "sn16.2:1.6": "còn người có nhiệt tâm, có sự biết sợ hãi thì có thể giác ngộ, có thể đạt Niết-bàn, có thể đạt sự an ổn vô thượng thoát khỏi ách phược'.' ",
  "sn16.2:2.1": "'Vậy thưa hiền giả, thế nào là người không có nhiệt tâm, không có sự biết sợ hãi, không thể giác ngộ, không thể đạt Niết-bàn, không thể đạt sự an ổn vô thượng thoát khỏi ách phược; '",
  "sn16.2:2.2": "và thế nào là người có nhiệt tâm, có sự biết sợ hãi, có thể giác ngộ, có thể đạt Niết-bàn, có thể đạt sự an ổn vô thượng thoát khỏi ách phược?' ",
  "sn16.2:2.3": "'Thưa hiền giả, ở đây Tỳ Kheo không nỗ lực với suy nghĩ: 'Những pháp bất thiện chưa sinh, nếu sinh khởi sẽ đưa đến bất lợi cho ta'; không nỗ lực với suy nghĩ: 'Những pháp bất thiện đã sinh, nếu không được đoạn trừ sẽ đưa đến bất lợi cho ta'; không nỗ lực với suy nghĩ: 'Những pháp thiện chưa sinh, nếu không sinh khởi sẽ đưa đến bất lợi cho ta'; không nỗ lực với suy nghĩ: 'Những pháp thiện đã sinh, nếu bị đoạn diệt sẽ đưa đến bất lợi cho ta'. '",
  "sn16.2:2.4": "Như vậy, thưa hiền giả, là người không có nhiệt tâm. ",
  "sn16.2:3.1": "Thưa hiền giả, thế nào là người không có sự biết sợ hãi? ",
  "sn16.2:3.2": "Thưa hiền giả, ở đây Tỳ Kheo không lo sợ với suy nghĩ: 'Những pháp bất thiện chưa sinh, nếu sinh khởi sẽ đưa đến bất lợi cho ta'; không lo sợ với suy nghĩ: 'Những pháp bất thiện đã sinh, nếu không được đoạn trừ sẽ đưa đến bất lợi cho ta'; không lo sợ với suy nghĩ: 'Những pháp thiện chưa sinh, nếu không sinh khởi sẽ đưa đến bất lợi cho ta'; không lo sợ với suy nghĩ: 'Những pháp thiện đã sinh, nếu bị đoạn diệt sẽ đưa đến bất lợi cho ta'. ",
  "sn16.2:3.3": "Như vậy, thưa hiền giả, là người không có sự biết sợ hãi. ",
  "sn16.2:3.4": "Như vậy, thưa hiền giả, người không có nhiệt tâm, không có sự biết sợ hãi thì không thể giác ngộ, không thể đạt Niết-bàn, không thể đạt sự an ổn vô thượng thoát khỏi ách phược. ",
  "sn16.2:4.1": "Thưa hiền giả, thế nào là người có nhiệt tâm? ",
  "sn16.2:4.2": "Thưa hiền giả, ở đây Tỳ Kheo nỗ lực với suy nghĩ: 'Những pháp bất thiện chưa sinh, nếu sinh khởi sẽ đưa đến bất lợi cho ta'; nỗ lực với suy nghĩ: 'Những pháp bất thiện đã sinh, nếu không được đoạn trừ sẽ đưa đến bất lợi cho ta'; nỗ lực với suy nghĩ: 'Những pháp thiện chưa sinh …vân vân… nỗ lực. ",
  "sn16.2:4.3": "Như vậy, thưa hiền giả, là người có nhiệt tâm. ",
  "sn16.2:5.1": "Thưa hiền giả, thế nào là người có sự biết sợ hãi? ",
  "sn16.2:5.2": "Thưa hiền giả, ở đây Tỳ Kheo lo sợ với suy nghĩ: 'Những pháp bất thiện chưa sinh, nếu sinh khởi sẽ đưa đến bất lợi cho ta'; lo sợ với suy nghĩ: 'Những pháp bất thiện đã sinh, nếu không được đoạn trừ sẽ đưa đến bất lợi cho ta'; lo sợ với suy nghĩ: 'Những pháp thiện chưa sinh, nếu không sinh khởi sẽ đưa đến bất lợi cho ta'; lo sợ với suy nghĩ: 'Những pháp thiện đã sinh, nếu bị đoạn diệt sẽ đưa đến bất lợi cho ta'. ",
  "sn16.2:5.3": "Như vậy, thưa hiền giả, là người có sự biết sợ hãi. ",
  "sn16.2:5.4": "Như vậy, thưa hiền giả, người có nhiệt tâm, có sự biết sợ hãi thì có thể giác ngộ, có thể đạt Niết-bàn, có thể đạt sự an ổn vô thượng thoát khỏi ách phược.' ",
  "sn16.2:5.5": "Kinh thứ hai. ",
  "sn16.3:0.1": "Tương Ưng Bộ 16.3 ",
  "sn16.3:0.2": "1. Phẩm Kassapa ",
  "sn16.3:0.3": "Kinh Ví Như Mặt Trăng ",
  "sn16.3:1.1": "Tại Sāvatthī. ",
  "sn16.3:1.2": "'Này các Tỳ Kheo, hãy đến viếng thăm các gia đình như mặt trăng'",
  "sn16.3:1.3": "thu thân lại, thu tâm lại, luôn luôn như người mới đến, không có thái độ vô lễ đối với các gia đình. ",
  "sn16.3:1.4": "Này các Tỳ Kheo, ví như một người nhìn xuống giếng cạn, hay nhìn vực núi, hay nhìn dòng sông nguy hiểm",
  "sn16.3:1.5": "thu thân lại, thu tâm lại; ",
  "sn16.3:1.6": "cũng vậy, này các Tỳ Kheo, hãy đến viếng thăm các gia đình như mặt trăng",
  "sn16.3:1.7": "thu thân lại, thu tâm lại, luôn luôn như người mới đến, không có thái độ vô lễ đối với các gia đình. ",
  "sn16.3:2.1": "Này các Tỳ Kheo, Kassapa đến viếng thăm các gia đình như mặt trăng",
  "sn16.3:2.2": "thu thân lại, thu tâm lại, luôn luôn như người mới đến, không có thái độ vô lễ đối với các gia đình. ",
  "sn16.3:2.3": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn16.3:2.4": "Tỳ Kheo như thế nào mới xứng đáng đến viếng thăm các gia đình?' ",
  "sn16.3:2.5": "'Bạch Thế Tôn, pháp của chúng con lấy Thế Tôn làm gốc, lấy Thế Tôn làm hướng dẫn, lấy Thế Tôn làm nơi nương tựa. Lành thay, bạch Thế Tôn, xin Thế Tôn hãy giải thích ý nghĩa lời nói này. Sau khi nghe từ Thế Tôn, các Tỳ Kheo sẽ ghi nhớ.' ",
  "sn16.3:3.1": "Rồi Thế Tôn vẫy tay trong không khí. ",
  "sn16.3:3.2": "'Này các Tỳ Kheo, ví như bàn tay này trong không khí không bị vướng, không bị nắm giữ, không bị trói buộc; '",
  "sn16.3:3.3": "cũng vậy, này các Tỳ Kheo, Tỳ Kheo nào đến viếng thăm các gia đình mà tâm không bị vướng, không bị nắm giữ, không bị trói buộc vào các gia đình đó, ",
  "sn16.3:3.4": "với suy nghĩ: 'Mong những ai muốn được lợi, hãy được lợi; mong những ai muốn làm công đức, hãy làm công đức'; ",
  "sn16.3:3.5": "vị ấy vui mừng với lợi lộc của chính mình, và cũng vui mừng với lợi lộc của người khác như vậy; ",
  "sn16.3:3.6": "Tỳ Kheo như vậy mới xứng đáng đến viếng thăm các gia đình. ",
  "sn16.3:4.1": "Này các Tỳ Kheo, khi Kassapa đến viếng thăm các gia đình, tâm vị ấy không bị vướng, không bị nắm giữ, không bị trói buộc vào các gia đình, ",
  "sn16.3:4.2": "với suy nghĩ: 'Mong những ai muốn được lợi, hãy được lợi; mong những ai muốn làm công đức, hãy làm công đức'; ",
  "sn16.3:4.3": "vị ấy vui mừng với lợi lộc của chính mình; ",
  "sn16.3:4.4": "và cũng vui mừng với lợi lộc của người khác như vậy. ",
  "sn16.3:5.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn16.3:5.2": "Tỳ Kheo như thế nào thì sự thuyết pháp không thanh tịnh, và Tỳ Kheo như thế nào thì sự thuyết pháp thanh tịnh?' ",
  "sn16.3:5.3": "'Bạch Thế Tôn, pháp của chúng con lấy Thế Tôn làm gốc … Sau khi nghe từ Thế Tôn, các Tỳ Kheo sẽ ghi nhớ.' ",
  "sn16.3:5.4": "'Vậy thì, này các Tỳ Kheo, hãy lắng nghe, hãy khéo chú ý, Ta sẽ giảng.' ",
  "sn16.3:5.5": "'Thưa vâng, bạch Thế Tôn', các Tỳ Kheo trả lời Thế Tôn. ",
  "sn16.3:5.6": "Thế Tôn nói như sau: ",
  "sn16.3:6.1": "'Này các Tỳ Kheo, Tỳ Kheo nào thuyết pháp cho người khác với tâm như sau: '",
  "sn16.3:6.2": "'Ước gì họ nghe pháp của ta, sau khi nghe hãy tịnh tín vào pháp, và sau khi tịnh tín hãy làm những điều khiến ta hài lòng'; ",
  "sn16.3:6.3": "Tỳ Kheo như vậy thì sự thuyết pháp không thanh tịnh. ",
  "sn16.3:7.1": "Và Tỳ Kheo nào thuyết pháp cho người khác với tâm như sau: ",
  "sn16.3:7.2": "'Pháp do Thế Tôn khéo giảng, thiết thực hiện tại, không có thời gian, đến để mà thấy, có khả năng hướng thượng, được người trí tự mình giác hiểu. '",
  "sn16.3:7.3": "Ước gì họ nghe pháp của ta, sau khi nghe hãy hiểu pháp, và sau khi hiểu hãy thực hành đúng như vậy'. ",
  "sn16.3:7.4": "Như vậy, vị ấy thuyết pháp cho người khác dựa trên sự trong sáng của pháp, thuyết pháp cho người khác vì lòng từ bi, vì lòng thương xót, vì muốn giúp đỡ. ",
  "sn16.3:7.5": "Tỳ Kheo như vậy thì sự thuyết pháp thanh tịnh. ",
  "sn16.3:8.1": "Này các Tỳ Kheo, Kassapa thuyết pháp cho người khác với tâm như sau: ",
  "sn16.3:8.2": "'Pháp do Thế Tôn khéo giảng, thiết thực hiện tại, không có thời gian, đến để mà thấy, có khả năng hướng thượng, được người trí tự mình giác hiểu. '",
  "sn16.3:8.3": "Ước gì họ nghe pháp của ta, sau khi nghe hãy hiểu pháp, và sau khi hiểu hãy thực hành đúng như vậy'. ",
  "sn16.3:8.4": "Như vậy, vị ấy thuyết pháp cho người khác dựa trên sự trong sáng của pháp, thuyết pháp cho người khác vì lòng từ bi, vì lòng thương xót, vì muốn giúp đỡ. ",
  "sn16.3:8.5": "Này các Tỳ Kheo, Ta sẽ giáo giới các ông như Kassapa, hoặc người nào giống như Kassapa; và khi được giáo giới, các ông hãy thực hành đúng như vậy.' ",
  "sn16.3:8.6": "Kinh thứ ba. ",
  "sn16.4:0.1": "Tương Ưng Bộ 16.4 ",
  "sn16.4:0.2": "1. Phẩm Kassapa ",
  "sn16.4:0.3": "Kinh Thăm Viếng Gia Đình ",
  "sn16.4:1.1": "Tại Sāvatthī. ",
  "sn16.4:1.2": "'Này các Tỳ Kheo, các ông nghĩ thế nào, '",
  "sn16.4:1.3": "Tỳ Kheo như thế nào xứng đáng đến viếng thăm các gia đình, và Tỳ Kheo như thế nào không xứng đáng đến viếng thăm các gia đình?' ",
  "sn16.4:1.4": "Pháp của chúng con lấy Thế Tôn làm gốc …vân vân… ",
  "sn16.4:1.5": "Thế Tôn nói như sau: ",
  "sn16.4:2.1": "'Này các Tỳ Kheo, Tỳ Kheo nào đến viếng thăm các gia đình với tâm như sau: '",
  "sn16.4:2.2": "'Mong họ cho ta, đừng không cho; '",
  "sn16.4:2.3": "mong họ cho ta nhiều, đừng cho ít; ",
  "sn16.4:2.4": "mong họ cho ta đồ tốt, đừng cho đồ thô; ",
  "sn16.4:2.5": "mong họ cho ta nhanh chóng, đừng cho chậm chạp; ",
  "sn16.4:2.6": "mong họ cho ta cung kính, đừng cho không cung kính'. ",
  "sn16.4:2.7": "Này các Tỳ Kheo, nếu Tỳ Kheo có tâm như vậy đến viếng thăm gia đình mà họ không cho, vị ấy buồn phiền; vì lý do đó, vị ấy cảm thọ khổ đau, ưu tư. ",
  "sn16.4:2.8": "Họ cho ít, không cho nhiều …vân vân… ",
  "sn16.4:2.9": "họ cho đồ thô, không cho đồ tốt … ",
  "sn16.4:2.10": "họ cho chậm chạp, không cho nhanh; vị ấy buồn phiền; vì lý do đó, vị ấy cảm thọ khổ đau, ưu tư. ",
  "sn16.4:2.11": "Họ cho không cung kính, không cho cung kính; vị ấy buồn phiền; vì lý do đó, vị ấy cảm thọ khổ đau, ưu tư. ",
  "sn16.4:2.12": "Tỳ Kheo như vậy không xứng đáng đến viếng thăm các gia đình. ",
  "sn16.4:3.1": "Này các Tỳ Kheo, Tỳ Kheo nào đến viếng thăm các gia đình với tâm như sau: ",
  "sn16.4:3.2": "'Làm sao có thể đòi hỏi ở nhà người khác rằng'",
  "sn16.4:3.3": "mong họ cho ta, đừng không cho; ",
  "sn16.4:3.4": "mong họ cho ta nhiều, đừng cho ít; ",
  "sn16.4:3.5": "mong họ cho ta đồ tốt, đừng cho đồ thô; ",
  "sn16.4:3.6": "mong họ cho ta nhanh chóng, đừng cho chậm chạp; ",
  "sn16.4:3.7": "mong họ cho ta cung kính, đừng cho không cung kính'. ",
  "sn16.4:3.8": "Này các Tỳ Kheo, nếu Tỳ Kheo có tâm như vậy đến viếng thăm gia đình mà họ không cho, vị ấy không buồn phiền; vì lý do đó, vị ấy không cảm thọ khổ đau, ưu tư. ",
  "sn16.4:3.9": "Họ cho ít, không cho nhiều; vị ấy không buồn phiền; vì lý do đó, vị ấy không cảm thọ khổ đau, ưu tư. ",
  "sn16.4:3.10": "Họ cho đồ thô, không cho đồ tốt; vị ấy không buồn phiền; vì lý do đó, vị ấy không cảm thọ khổ đau, ưu tư. ",
  "sn16.4:3.11": "Họ cho chậm chạp, không cho nhanh; vị ấy không buồn phiền; vì lý do đó, vị ấy không cảm thọ khổ đau, ưu tư. ",
  "sn16.4:3.12": "Họ cho không cung kính, không cho cung kính; vị ấy không buồn phiền; vì lý do đó, vị ấy không cảm thọ khổ đau, ưu tư. ",
  "sn16.4:3.13": "Tỳ Kheo như vậy xứng đáng đến viếng thăm các gia đình. ",
  "sn16.4:4.1": "Này các Tỳ Kheo, Kassapa đến viếng thăm các gia đình với tâm như sau: ",
  "sn16.4:4.2": "'Làm sao có thể đòi hỏi ở nhà người khác rằng'",
  "sn16.4:4.3": "mong họ cho ta, đừng không cho; ",
  "sn16.4:4.4": "mong họ cho ta nhiều, đừng cho ít; ",
  "sn16.4:4.5": "mong họ cho ta đồ tốt, đừng cho đồ thô; ",
  "sn16.4:4.6": "mong họ cho ta nhanh chóng, đừng cho chậm chạp; ",
  "sn16.4:4.7": "mong họ cho ta cung kính, đừng cho không cung kính'. ",
  "sn16.4:4.8": "Này các Tỳ Kheo, khi Kassapa có tâm như vậy đến viếng thăm gia đình mà họ không cho, Kassapa không buồn phiền; vì lý do đó, vị ấy không cảm thọ khổ đau, ưu tư. ",
  "sn16.4:4.9": "Họ cho ít, không cho nhiều; Kassapa không buồn phiền; vì lý do đó, vị ấy không cảm thọ khổ đau, ưu tư. ",
  "sn16.4:4.10": "Họ cho đồ thô, không cho đồ tốt; Kassapa không buồn phiền; vì lý do đó, vị ấy không cảm thọ khổ đau, ưu tư. ",
  "sn16.4:4.11": "Họ cho chậm chạp, không cho nhanh; Kassapa không buồn phiền; vì lý do đó, vị ấy không cảm thọ khổ đau, ưu tư. ",
  "sn16.4:4.12": "Họ cho không cung kính, không cho cung kính; Kassapa không buồn phiền; vì lý do đó, vị ấy không cảm thọ khổ đau, ưu tư. ",
  "sn16.4:4.13": "Này các Tỳ Kheo, Ta sẽ giáo giới các ông như Kassapa, hoặc người nào giống như Kassapa; và khi được giáo giới, hãy thực hành đúng như vậy.' ",
  "sn16.4:4.14": "Kinh thứ tư. ",
  "sn16.5:0.1": "Tương Ưng Bộ 16.5 ",
  "sn16.5:0.2": "1. Phẩm Kassapa ",
  "sn16.5:0.3": "Kinh Già Nua ",
  "sn16.5:1.1": "Tôi đã nghe như vầy … ",
  "sn16.5:1.2": "tại Rājagaha, vườn Trúc Lâm. ",
  "sn16.5:1.3": "Rồi Tôn giả Mahākassapa đến chỗ Thế Tôn, sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Tôn giả Mahākassapa đang ngồi một bên, Thế Tôn nói với Tôn giả ấy: ",
  "sn16.5:1.4": "'Nay ông đã già rồi, Kassapa, những tấm vải gai thô nặng nề này thật mệt mỏi khi mặc. '",
  "sn16.5:1.5": "Vậy, Kassapa, ông hãy mặc y của cư sĩ, nhận lời mời thọ trai, và ở gần bên Ta.' ",
  "sn16.5:2.1": "'Bạch Thế Tôn, con đã lâu dài là người sống ở rừng và tán thán hạnh sống ở rừng, là người khất thực và tán thán hạnh khất thực, là người mặc y phấn tảo và tán thán hạnh mặc y phấn tảo, là người chỉ mang ba y và tán thán hạnh mang ba y, là người ít ham muốn và tán thán hạnh ít ham muốn, là người biết đủ và tán thán hạnh biết đủ, là người ưa sống viễn ly và tán thán hạnh sống viễn ly, là người không giao thiệp và tán thán hạnh không giao thiệp, là người tinh tấn và tán thán hạnh tinh tấn.' ",
  "sn16.5:3.1": "'Vậy Kassapa, ông thấy lợi ích gì mà lâu dài ông là người sống ở rừng và tán thán hạnh sống ở rừng, là người khất thực và tán thán hạnh khất thực …vân vân… '",
  "sn16.5:3.2": "mặc y phấn tảo và tán thán … ",
  "sn16.5:3.3": "chỉ mang ba y và tán thán … ",
  "sn16.5:3.4": "ít ham muốn và tán thán … ",
  "sn16.5:3.5": "biết đủ và tán thán … ",
  "sn16.5:3.6": "ưa sống viễn ly và tán thán … ",
  "sn16.5:3.7": "không giao thiệp và tán thán … ",
  "sn16.5:3.8": "tinh tấn và tán thán hạnh tinh tấn?' ",
  "sn16.5:4.1": "'Bạch Thế Tôn, con thấy hai lợi ích mà lâu dài con là người sống ở rừng và tán thán hạnh sống ở rừng, là người khất thực và tán thán …vân vân… '",
  "sn16.5:4.2": "mặc y phấn tảo và tán thán … ",
  "sn16.5:4.3": "chỉ mang ba y và tán thán … ",
  "sn16.5:4.4": "ít ham muốn và tán thán … ",
  "sn16.5:4.5": "biết đủ và tán thán … ",
  "sn16.5:4.6": "ưa sống viễn ly và tán thán … ",
  "sn16.5:4.7": "không giao thiệp và tán thán … ",
  "sn16.5:4.8": "tinh tấn và tán thán hạnh tinh tấn. ",
  "sn16.5:5.1": "Con thấy sự an lạc trong hiện tại cho chính mình, và con thương xót những người đời sau: ",
  "sn16.5:5.2": "'Mong rằng những người đời sau có thể noi gương này. '",
  "sn16.5:5.3": "Những vị đệ tử của các vị Phật trước kia đã là người sống ở rừng và tán thán hạnh sống ở rừng …vân vân… ",
  "sn16.5:5.4": "là người khất thực và tán thán …vân vân… ",
  "sn16.5:5.5": "mặc y phấn tảo và tán thán … ",
  "sn16.5:5.6": "chỉ mang ba y và tán thán … ",
  "sn16.5:5.7": "ít ham muốn và tán thán … ",
  "sn16.5:5.8": "biết đủ và tán thán … ",
  "sn16.5:5.9": "ưa sống viễn ly và tán thán … ",
  "sn16.5:5.10": "không giao thiệp và tán thán … ",
  "sn16.5:5.11": "tinh tấn và tán thán hạnh tinh tấn'. ",
  "sn16.5:5.12": "Họ sẽ thực hành như vậy, và điều đó sẽ đem lại hạnh phúc và an lạc lâu dài cho họ. ",
  "sn16.5:6.1": "Bạch Thế Tôn, đây là hai lợi ích con thấy mà lâu dài con là người sống ở rừng và tán thán hạnh sống ở rừng, là người khất thực và tán thán …vân vân… ",
  "sn16.5:6.2": "mặc y phấn tảo và tán thán … ",
  "sn16.5:6.3": "chỉ mang ba y và tán thán … ",
  "sn16.5:6.4": "ít ham muốn và tán thán … ",
  "sn16.5:6.5": "biết đủ và tán thán … ",
  "sn16.5:6.6": "ưa sống viễn ly và tán thán … ",
  "sn16.5:6.7": "không giao thiệp và tán thán … ",
  "sn16.5:6.8": "tinh tấn và tán thán hạnh tinh tấn.' ",
  "sn16.5:7.1": "'Lành thay, lành thay, Kassapa. '",
  "sn16.5:7.2": "Này Kassapa, ông đang thực hành vì lợi ích và hạnh phúc của nhiều người, vì lòng thương xót thế gian, vì lợi ích, hạnh phúc và an lạc của chư thiên và loài người. ",
  "sn16.5:7.3": "Vậy, Kassapa, hãy tiếp tục mặc những tấm vải gai thô, đi khất thực, và sống ở rừng.' ",
  "sn16.5:7.4": "Kinh thứ năm. ",
  "sn16.6:0.1": "Tương Ưng Bộ 16.6 ",
  "sn16.6:0.2": "1. Phẩm Kassapa ",
  "sn16.6:0.3": "Kinh Giáo Giới ",
  "sn16.6:1.1": "Tại Rājagaha, vườn Trúc Lâm. ",
  "sn16.6:1.2": "Rồi Tôn giả Mahākassapa đến chỗ Thế Tôn, sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Tôn giả Mahākassapa đang ngồi một bên, Thế Tôn nói với Tôn giả ấy: ",
  "sn16.6:1.3": "'Kassapa, hãy giáo giới các Tỳ Kheo; '",
  "sn16.6:1.4": "Kassapa, hãy thuyết pháp cho các Tỳ Kheo. ",
  "sn16.6:1.5": "Hoặc Ta, hoặc Kassapa hãy giáo giới các Tỳ Kheo; ",
  "sn16.6:1.6": "hoặc Ta, hoặc ông hãy thuyết pháp cho các Tỳ Kheo.' ",
  "sn16.6:2.1": "'Bạch Thế Tôn, ngày nay các Tỳ Kheo khó nói, được phú cho những đặc tính khiến người ta khó nói, thiếu kiên nhẫn, không chịu nhận lời khuyên bảo. '",
  "sn16.6:2.2": "Bạch Thế Tôn, ở đây con thấy Tỳ Kheo Bhaṇḍa là người cùng tu với Ānanda, và Tỳ Kheo Abhijika là người cùng tu với Anuruddha, đang tranh cãi nhau về kiến thức: ",
  "sn16.6:2.3": "'Nào, ai sẽ nói nhiều hơn, ai sẽ nói hay hơn, ai sẽ nói lâu hơn?'' '",
  "sn16.6:3.1": "Rồi Thế Tôn bảo một Tỳ Kheo: ",
  "sn16.6:3.2": "'Này Tỳ Kheo, hãy đến gặp Tỳ Kheo Bhaṇḍa, người cùng tu với Ānanda, và Tỳ Kheo Abhijika, người cùng tu với Anuruddha, và nói với họ: '",
  "sn16.6:3.3": "'Bậc Đạo Sư mời các Tôn giả đến.'' '",
  "sn16.6:3.4": "'Thưa vâng, bạch Thế Tôn', vị Tỳ Kheo ấy trả lời Thế Tôn, rồi đến chỗ các Tỳ Kheo đó và nói: ",
  "sn16.6:3.5": "'Bậc Đạo Sư mời các Tôn giả đến.' ",
  "sn16.6:4.1": "'Thưa vâng, hiền giả', hai Tỳ Kheo ấy trả lời, rồi đến chỗ Thế Tôn, đảnh lễ và ngồi xuống một bên. Thế Tôn nói với hai Tỳ Kheo đang ngồi một bên: ",
  "sn16.6:4.2": "'Có thật không, này các Tỳ Kheo, các ông đang tranh cãi nhau về kiến thức: '",
  "sn16.6:4.3": "'Nào, ai sẽ nói nhiều hơn, ai sẽ nói hay hơn, ai sẽ nói lâu hơn?'' '",
  "sn16.6:4.4": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn16.6:4.5": "'Các ông có hiểu pháp Ta dạy như vầy không: '",
  "sn16.6:4.6": "'Hỡi các Tỳ Kheo, hãy đến tranh cãi nhau về kiến thức '",
  "sn16.6:4.7": "nào, ai sẽ nói nhiều hơn, ai sẽ nói hay hơn, ai sẽ nói lâu hơn?'' ",
  "sn16.6:4.8": "'Thưa không, bạch Thế Tôn.' ",
  "sn16.6:4.9": "'Nếu các ông không hiểu Ta dạy như vậy, thì này những kẻ vô tích sự, biết gì, thấy gì mà các ông đã xuất gia trong giáo pháp và luật được khéo giảng này lại đi tranh cãi nhau về kiến thức: '",
  "sn16.6:4.10": "'Nào, ai sẽ nói nhiều hơn, ai sẽ nói hay hơn, ai sẽ nói lâu hơn?'' '",
  "sn16.6:5.1": "Rồi hai Tỳ Kheo ấy cúi đầu xuống chân Thế Tôn và bạch: ",
  "sn16.6:5.2": "'Bạch Thế Tôn, chúng con đã phạm lỗi lầm, hành động như kẻ ngu si, như kẻ si mê, như kẻ vụng vềchúng con đã xuất gia trong giáo pháp và luật được khéo giảng này lại đi tranh cãi nhau về kiến thức: '",
  "sn16.6:5.3": "'Nào, ai sẽ nói nhiều hơn, ai sẽ nói hay hơn, ai sẽ nói lâu hơn'. ",
  "sn16.6:5.4": "Bạch Thế Tôn, xin Thế Tôn chấp nhận lỗi lầm của chúng con như là lỗi lầm, để chúng con kiềm chế trong tương lai.' ",
  "sn16.6:6.1": "'Đúng vậy, này các Tỳ Kheo, các ông đã phạm lỗi lầm, hành động như kẻ ngu si, như kẻ si mê, như kẻ vụng vềcác ông đã xuất gia trong giáo pháp và luật được khéo giảng này lại đi tranh cãi nhau về kiến thức: '",
  "sn16.6:6.2": "'Nào, ai sẽ nói nhiều hơn, ai sẽ nói hay hơn, ai sẽ nói lâu hơn'. ",
  "sn16.6:6.3": "Nhưng vì các ông đã thấy lỗi lầm là lỗi lầm và đã hành động đúng pháp, Ta chấp nhận điều đó. ",
  "sn16.6:6.4": "Này các Tỳ Kheo, trong giới luật của bậc Thánh, đây là sự trưởng thànhngười thấy lỗi lầm là lỗi lầm, hành động đúng pháp và kiềm chế trong tương lai.' ",
  "sn16.6:6.5": "Kinh thứ sáu. ",
  "sn16.7:0.1": "Tương Ưng Bộ 16.7 ",
  "sn16.7:0.2": "1. Phẩm Kassapa ",
  "sn16.7:0.3": "Kinh Giáo Giới Lần Hai ",
  "sn16.7:1.1": "Tại Rājagaha, vườn Trúc Lâm. ",
  "sn16.7:1.2": "Rồi Tôn giả Mahākassapa đến chỗ Thế Tôn …vân vân… ",
  "sn16.7:1.3": "Tôn giả Mahākassapa đang ngồi một bên, Thế Tôn nói với Tôn giả ấy: ",
  "sn16.7:1.4": "'Kassapa, hãy giáo giới các Tỳ Kheo; '",
  "sn16.7:1.5": "Kassapa, hãy thuyết pháp cho các Tỳ Kheo. ",
  "sn16.7:1.6": "Hoặc Ta, hoặc Kassapa hãy giáo giới các Tỳ Kheo; ",
  "sn16.7:1.7": "hoặc Ta, hoặc ông hãy thuyết pháp cho các Tỳ Kheo.' ",
  "sn16.7:2.1": "'Bạch Thế Tôn, ngày nay các Tỳ Kheo khó nói, được phú cho những đặc tính khiến người ta khó nói, thiếu kiên nhẫn, không chịu nhận lời khuyên bảo. '",
  "sn16.7:2.2": "Bạch Thế Tôn, ai không có đức tin đối với các pháp thiện, không có sự hổ thẹn đối với các pháp thiện, không có sự biết sợ hãi đối với các pháp thiện, không có tinh tấn đối với các pháp thiện, không có trí tuệ đối với các pháp thiện, thì mỗi đêm, mỗi ngày trôi qua, người ấy chỉ có thể mong đợi sự suy giảm các pháp thiện, không phải sự tăng trưởng. ",
  "sn16.7:3.1": "Bạch Thế Tôn, ví như trong tuần trăng khuyết, mỗi đêm, mỗi ngày trôi qua, mặt trăng suy giảm về sắc đẹp, tròn đầy, ánh sáng, kích thước và chu vi. ",
  "sn16.7:3.2": "Cũng vậy, bạch Thế Tôn, ai không có đức tin đối với các pháp thiện …vân vân… ",
  "sn16.7:3.3": "không có sự hổ thẹn … ",
  "sn16.7:3.4": "không có sự biết sợ hãi … ",
  "sn16.7:3.5": "không có tinh tấn … ",
  "sn16.7:3.6": "không có trí tuệ đối với các pháp thiện, thì mỗi đêm, mỗi ngày trôi qua, người ấy chỉ có thể mong đợi sự suy giảm các pháp thiện, không phải sự tăng trưởng. ",
  "sn16.7:4.1": "Bạch Thế Tôn, 'người không có đức tin'đây là sự suy giảm; ",
  "sn16.7:4.2": "'người không có sự hổ thẹn'đây là sự suy giảm; ",
  "sn16.7:4.3": "'người không có sự biết sợ hãi'đây là sự suy giảm; ",
  "sn16.7:4.4": "'người lười biếng'đây là sự suy giảm; ",
  "sn16.7:4.5": "'người thiếu trí tuệ'đây là sự suy giảm; ",
  "sn16.7:4.6": "'người hay giận dữ'đây là sự suy giảm; ",
  "sn16.7:4.7": "'người hay thù oán'đây là sự suy giảm; ",
  "sn16.7:4.8": "'không có Tỳ Kheo biết giáo giới'đây là sự suy giảm. ",
  "sn16.7:5.1": "Bạch Thế Tôn, ai có đức tin đối với các pháp thiện, có sự hổ thẹn đối với các pháp thiện, có sự biết sợ hãi đối với các pháp thiện, có tinh tấn đối với các pháp thiện, có trí tuệ đối với các pháp thiện, thì mỗi đêm, mỗi ngày trôi qua, người ấy chỉ có thể mong đợi sự tăng trưởng các pháp thiện, không phải sự suy giảm. ",
  "sn16.7:6.1": "Bạch Thế Tôn, ví như trong tuần trăng tròn, mỗi đêm, mỗi ngày trôi qua, mặt trăng tăng trưởng về sắc đẹp, tròn đầy, ánh sáng, kích thước và chu vi. ",
  "sn16.7:6.2": "Cũng vậy, bạch Thế Tôn, ai có đức tin đối với các pháp thiện … ",
  "sn16.7:6.3": "có sự hổ thẹn …vân vân… ",
  "sn16.7:6.4": "có sự biết sợ hãi … ",
  "sn16.7:6.5": "có tinh tấn … ",
  "sn16.7:6.6": "có trí tuệ đối với các pháp thiện, thì mỗi đêm, mỗi ngày trôi qua, người ấy chỉ có thể mong đợi sự tăng trưởng các pháp thiện, không phải sự suy giảm. ",
  "sn16.7:7.1": "Bạch Thế Tôn, 'người có đức tin'đây là không suy giảm; ",
  "sn16.7:7.2": "'người có sự hổ thẹn'đây là không suy giảm; ",
  "sn16.7:7.3": "'người có sự biết sợ hãi'đây là không suy giảm; ",
  "sn16.7:7.4": "'người tinh tấn'đây là không suy giảm; ",
  "sn16.7:7.5": "'người có trí tuệ'đây là không suy giảm; ",
  "sn16.7:7.6": "'người không hay giận dữ'đây là không suy giảm; ",
  "sn16.7:7.7": "'người không hay thù oán'đây là không suy giảm; ",
  "sn16.7:7.8": "'có Tỳ Kheo biết giáo giới'đây là không suy giảm.' '",
  "sn16.7:8.1": "'Lành thay, lành thay, Kassapa. '",
  "sn16.7:8.2": "Này Kassapa, ai không có đức tin đối với các pháp thiện …vân vân… ",
  "sn16.7:8.3": "không có sự hổ thẹn … ",
  "sn16.7:8.4": "không có sự biết sợ hãi … ",
  "sn16.7:8.5": "không có tinh tấn … ",
  "sn16.7:8.6": "không có trí tuệ đối với các pháp thiện, thì mỗi đêm, mỗi ngày trôi qua, người ấy chỉ có thể mong đợi sự suy giảm các pháp thiện, không phải sự tăng trưởng. ",
  "sn16.7:9.1": "Này Kassapa, ví như trong tuần trăng khuyết, mỗi đêm, mỗi ngày trôi qua, mặt trăng suy giảm về sắc đẹp …vân vân… ",
  "sn16.7:9.2": "suy giảm về kích thước và chu vi. ",
  "sn16.7:9.3": "Cũng vậy, này Kassapa, ai không có đức tin đối với các pháp thiện …vân vân… ",
  "sn16.7:9.4": "không có sự hổ thẹn … ",
  "sn16.7:9.5": "không có sự biết sợ hãi … ",
  "sn16.7:9.6": "không có tinh tấn … ",
  "sn16.7:9.7": "không có trí tuệ đối với các pháp thiện, thì mỗi đêm, mỗi ngày trôi qua, người ấy chỉ có thể mong đợi sự suy giảm các pháp thiện, không phải sự tăng trưởng. ",
  "sn16.7:9.8": "Này Kassapa, 'người không có đức tin'đây là sự suy giảm; ",
  "sn16.7:9.9": "không có sự hổ thẹn …vân vân… ",
  "sn16.7:9.10": "không có sự biết sợ hãi … ",
  "sn16.7:9.11": "lười biếng … ",
  "sn16.7:9.12": "thiếu trí tuệ … ",
  "sn16.7:9.13": "hay giận dữ … ",
  "sn16.7:9.14": "Này Kassapa, 'người hay thù oán'đây là sự suy giảm; ",
  "sn16.7:9.15": "Này Kassapa, 'không có Tỳ Kheo biết giáo giới'đây là sự suy giảm. ",
  "sn16.7:10.1": "Này Kassapa, ai có đức tin đối với các pháp thiện …vân vân… ",
  "sn16.7:10.2": "có sự hổ thẹn … ",
  "sn16.7:10.3": "có sự biết sợ hãi … ",
  "sn16.7:10.4": "có tinh tấn … ",
  "sn16.7:10.5": "có trí tuệ đối với các pháp thiện, thì mỗi đêm, mỗi ngày trôi qua, người ấy chỉ có thể mong đợi sự tăng trưởng các pháp thiện, không phải sự suy giảm. ",
  "sn16.7:11.1": "Này Kassapa, ví như trong tuần trăng tròn, mỗi đêm, mỗi ngày trôi qua, mặt trăng tăng trưởng về sắc đẹp, tròn đầy, ánh sáng, kích thước và chu vi. ",
  "sn16.7:11.2": "Cũng vậy, này Kassapa, ai có đức tin đối với các pháp thiện; có sự hổ thẹn … ",
  "sn16.7:11.3": "có sự biết sợ hãi … ",
  "sn16.7:11.4": "có tinh tấn … ",
  "sn16.7:11.5": "có trí tuệ đối với các pháp thiện, thì mỗi đêm, mỗi ngày trôi qua, người ấy chỉ có thể mong đợi sự tăng trưởng các pháp thiện, không phải sự suy giảm. ",
  "sn16.7:12.1": "Này Kassapa, 'người có đức tin'đây là không suy giảm; ",
  "sn16.7:12.2": "có sự hổ thẹn …vân vân… ",
  "sn16.7:12.3": "có sự biết sợ hãi … ",
  "sn16.7:12.4": "tinh tấn … ",
  "sn16.7:12.5": "có trí tuệ … ",
  "sn16.7:12.6": "không hay giận dữ … ",
  "sn16.7:12.7": "Này Kassapa, 'người không hay thù oán'đây là không suy giảm; ",
  "sn16.7:12.8": "Này Kassapa, 'có Tỳ Kheo biết giáo giới'đây là không suy giảm.' ",
  "sn16.7:12.9": "Kinh thứ bảy. ",
  "sn16.8:0.1": "Tương Ưng Bộ 16.8 ",
  "sn16.8:0.2": "1. Phẩm Kassapa ",
  "sn16.8:0.3": "Kinh Giáo Giới Lần Ba ",
  "sn16.8:1.1": "Tại Rājagaha, vườn Kalandakanivāpa. ",
  "sn16.8:1.2": "Rồi Tôn giả Mahākassapa đến chỗ Thế Tôn, sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Tôn giả Mahākassapa đang ngồi một bên, Thế Tôn nói với Tôn giả ấy: ",
  "sn16.8:1.3": "'Kassapa, hãy giáo giới các Tỳ Kheo; '",
  "sn16.8:1.4": "Kassapa, hãy thuyết pháp cho các Tỳ Kheo. ",
  "sn16.8:1.5": "Hoặc Ta, hoặc Kassapa hãy giáo giới các Tỳ Kheo; ",
  "sn16.8:1.6": "hoặc Ta, hoặc ông hãy thuyết pháp cho các Tỳ Kheo.' ",
  "sn16.8:2.1": "'Bạch Thế Tôn, ngày nay các Tỳ Kheo khó nói, được phú cho những đặc tính khiến người ta khó nói, thiếu kiên nhẫn, không chịu nhận lời khuyên bảo.' ",
  "sn16.8:2.2": "'Này Kassapa, đúng vậy, trước kia các Tỳ Kheo trưởng lão là người sống ở rừng và tán thán hạnh sống ở rừng, là người khất thực và tán thán hạnh khất thực, là người mặc y phấn tảo và tán thán hạnh mặc y phấn tảo, là người chỉ mang ba y và tán thán hạnh mang ba y, là người ít ham muốn và tán thán hạnh ít ham muốn, là người biết đủ và tán thán hạnh biết đủ, là người ưa sống viễn ly và tán thán hạnh sống viễn ly, là người không giao thiệp và tán thán hạnh không giao thiệp, là người tinh tấn và tán thán hạnh tinh tấn. '",
  "sn16.8:3.1": "Ở đó, Tỳ Kheo nào là người sống ở rừng và tán thán hạnh sống ở rừng, là người khất thực và tán thán hạnh khất thực, là người mặc y phấn tảo và tán thán hạnh mặc y phấn tảo, là người chỉ mang ba y và tán thán hạnh mang ba y, là người ít ham muốn và tán thán hạnh ít ham muốn, là người biết đủ và tán thán hạnh biết đủ, là người ưa sống viễn ly và tán thán hạnh sống viễn ly, là người không giao thiệp và tán thán hạnh không giao thiệp, là người tinh tấn và tán thán hạnh tinh tấn, thì các Tỳ Kheo trưởng lão mời ngồi vào chỗ ngồi: ",
  "sn16.8:3.2": "'Đây là Tỳ Kheo nào? Tỳ Kheo này thật đáng khen, Tỳ Kheo này muốn học hỏi; hãy đến, Tỳ Kheo, hãy ngồi vào chỗ này'. ",
  "sn16.8:4.1": "Này Kassapa, các Tỳ Kheo trẻ ở đó nghĩ: ",
  "sn16.8:4.2": "'Tỳ Kheo nào là người sống ở rừng và tán thán hạnh sống ở rừng, là người khất thực và tán thán …vân vân… mặc y phấn tảo và tán thán … chỉ mang ba y và tán thán … ít ham muốn và tán thán … biết đủ và tán thán … ưa sống viễn ly và tán thán … không giao thiệp và tán thán … tinh tấn và tán thán hạnh tinh tấn, thì các Tỳ Kheo trưởng lão mời ngồi vào chỗ ngồi '",
  "sn16.8:4.3": "đây là Tỳ Kheo nào? Tỳ Kheo này thật đáng khen, Tỳ Kheo này muốn học hỏi; hãy đến, Tỳ Kheo, hãy ngồi vào chỗ này'. ",
  "sn16.8:4.4": "Họ thực hành như vậy; ",
  "sn16.8:4.5": "điều đó sẽ đem lại hạnh phúc và an lạc lâu dài cho họ. ",
  "sn16.8:5.1": "Nhưng ngày nay, này Kassapa, các Tỳ Kheo trưởng lão không phải là người sống ở rừng, không tán thán hạnh sống ở rừng; không phải là người khất thực, không tán thán hạnh khất thực; không phải là người mặc y phấn tảo, không tán thán hạnh mặc y phấn tảo; không phải là người chỉ mang ba y, không tán thán hạnh mang ba y; không phải là người ít ham muốn, không tán thán hạnh ít ham muốn; không phải là người biết đủ, không tán thán hạnh biết đủ; không phải là người ưa sống viễn ly, không tán thán hạnh sống viễn ly; không phải là người không giao thiệp, không tán thán hạnh không giao thiệp; không phải là người tinh tấn, không tán thán hạnh tinh tấn. ",
  "sn16.8:6.1": "Ở đó, Tỳ Kheo nào nổi tiếng, có danh vọng, được nhiều lợi lộc về y phục, vật thực khất thực, chỗ ở, thuốc men và vật dụng trị bệnh, thì các Tỳ Kheo trưởng lão mời ngồi vào chỗ ngồi: ",
  "sn16.8:6.2": "'Đây là Tỳ Kheo nào? Tỳ Kheo này thật đáng khen, Tỳ Kheo này muốn sống cùng với chúng tăng; hãy đến, Tỳ Kheo, hãy ngồi vào chỗ này'. ",
  "sn16.8:7.1": "Này Kassapa, các Tỳ Kheo trẻ ở đó nghĩ: ",
  "sn16.8:7.2": "'Tỳ Kheo nào nổi tiếng, có danh vọng, được nhiều lợi lộc về y phục, vật thực khất thực, chỗ ở, thuốc men và vật dụng trị bệnh, thì các Tỳ Kheo trưởng lão mời ngồi vào chỗ ngồi '",
  "sn16.8:7.3": "đây là Tỳ Kheo nào? Tỳ Kheo này thật đáng khen, Tỳ Kheo này muốn sống cùng với chúng tăng; hãy đến, Tỳ Kheo, hãy ngồi vào chỗ này'. ",
  "sn16.8:7.4": "Họ thực hành như vậy. ",
  "sn16.8:7.5": "Điều đó sẽ đem lại bất hạnh và đau khổ lâu dài cho họ. ",
  "sn16.8:7.6": "Này Kassapa, nếu nói đúng, người ta có thể nói: ",
  "sn16.8:7.7": "'Người sống phạm hạnh bị quấy rầy bởi kẻ phá hoại phạm hạnh, người sống phạm hạnh bị kẻ đó mong muốn'ngày nay, này Kassapa, nếu nói đúng, người ta có thể nói: 'Người sống phạm hạnh bị quấy rầy bởi kẻ phá hoại phạm hạnh, người sống phạm hạnh bị kẻ đó mong muốn'.' '",
  "sn16.8:7.8": "Kinh thứ tám. ",
  "sn16.9:0.1": "Tương Ưng Bộ 16.9 ",
  "sn16.9:0.2": "1. Phẩm Kassapa ",
  "sn16.9:0.3": "Kinh Thiền Định và Thần Thông ",
  "sn16.9:1.1": "Tại Sāvatthī. ",
  "sn16.9:1.2": "'Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta ly dục, ly pháp bất thiện, chứng và trú Sơ thiền, một trạng thái có tầm và tứ, có hỷ và lạc do ly dục sinh. '",
  "sn16.9:1.3": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng ly dục, ly pháp bất thiện, chứng và trú Sơ thiền, một trạng thái có tầm và tứ, có hỷ và lạc do ly dục sinh. ",
  "sn16.9:2.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta diệt tầm và tứ, chứng và trú Nhị thiền, một trạng thái nội tĩnh, nhất tâm, không tầm không tứ, có hỷ và lạc do định sinh. ",
  "sn16.9:2.2": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng diệt tầm và tứ …vân vân… chứng và trú Nhị thiền. ",
  "sn16.9:3.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta ly hỷ, trú xả, chánh niệm, tỉnh giác, thân cảm thọ lạc mà các bậc Thánh gọi là 'người xả, có niệm, an trú lạc', chứng và trú Tam thiền. ",
  "sn16.9:3.2": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng ly hỷ, trú xả, chánh niệm, tỉnh giác, thân cảm thọ lạc mà các bậc Thánh gọi là 'người xả, có niệm, an trú lạc', chứng và trú Tam thiền. ",
  "sn16.9:4.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta xả lạc, xả khổ, diệt hỷ ưu đã cảm thọ trước, chứng và trú Tứ thiền, không khổ không lạc, xả niệm thanh tịnh. ",
  "sn16.9:4.2": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng xả lạc, xả khổ …vân vân… chứng và trú Tứ thiền. ",
  "sn16.9:5.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta vượt qua hoàn toàn sắc tưởng, diệt trừ đối ngại tưởng, không tác ý đến dị tưởng, với suy nghĩ 'hư không là vô biên', chứng và trú Không vô biên xứ. ",
  "sn16.9:5.2": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng vượt qua hoàn toàn sắc tưởng …vân vân… chứng và trú Không vô biên xứ. ",
  "sn16.9:6.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta vượt qua hoàn toàn Không vô biên xứ, với suy nghĩ 'thức là vô biên', chứng và trú Thức vô biên xứ. ",
  "sn16.9:6.2": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng vượt qua hoàn toàn Không vô biên xứ, với suy nghĩ 'thức là vô biên', chứng và trú Thức vô biên xứ. ",
  "sn16.9:7.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta vượt qua hoàn toàn Thức vô biên xứ, với suy nghĩ 'không có gì cả', chứng và trú Vô sở hữu xứ. ",
  "sn16.9:7.2": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng …vân vân… chứng và trú Vô sở hữu xứ. ",
  "sn16.9:8.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta vượt qua hoàn toàn Vô sở hữu xứ, chứng và trú Phi tưởng phi phi tưởng xứ. ",
  "sn16.9:8.2": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng …vân vân… chứng và trú Phi tưởng phi phi tưởng xứ. ",
  "sn16.9:9.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta vượt qua hoàn toàn Phi tưởng phi phi tưởng xứ, chứng và trú Diệt thọ tưởng định. ",
  "sn16.9:9.2": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng …vân vân… chứng và trú Diệt thọ tưởng định. ",
  "sn16.9:10.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta thực hiện các loại thần thông khác nhautừ một hóa ra nhiều, từ nhiều hóa ra một; hiện hình, biến mất; đi xuyên qua tường, qua rào, qua núi như đi qua hư không; lặn xuống đất và trồi lên như trong nước; đi trên mặt nước không chìm như trên mặt đất; ngồi kiết già bay đi trong hư không như con chim; dùng tay chạm và xoa mặt trăng và mặt trời dù chúng có thần lực và oai lực lớn như vậy; và có thể dùng thân bay đến tận cõi Phạm thiên. ",
  "sn16.9:10.2": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng thực hiện các loại thần thông khác nhau …vân vân… có thể dùng thân bay đến tận cõi Phạm thiên. ",
  "sn16.9:11.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta nghe bằng thiên nhĩ thanh tịnh, vượt qua tai người thường, nghe cả hai loại âm thanh, âm thanh của chư thiên và âm thanh của loài người, từ xa cũng như gần. ",
  "sn16.9:11.2": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng nghe bằng thiên nhĩ thanh tịnh …vân vân… từ xa cũng như gần. ",
  "sn16.9:12.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta dùng tâm biết tâm của các chúng sinh khác, các cá nhân khác",
  "sn16.9:12.2": "tâm có tham, biết là tâm có tham; ",
  "sn16.9:12.3": "tâm không tham, biết là tâm không tham; ",
  "sn16.9:12.4": "tâm có sân …vân vân… ",
  "sn16.9:12.5": "tâm không sân … ",
  "sn16.9:12.6": "tâm có si … ",
  "sn16.9:12.7": "tâm không si … ",
  "sn16.9:12.8": "tâm bị thu hẹp … ",
  "sn16.9:12.9": "tâm tán loạn … ",
  "sn16.9:12.10": "tâm rộng lớn … ",
  "sn16.9:12.11": "tâm không rộng lớn … ",
  "sn16.9:12.12": "tâm hữu hạn … ",
  "sn16.9:12.13": "tâm vô thượng … ",
  "sn16.9:12.14": "tâm định … ",
  "sn16.9:12.15": "tâm không định … ",
  "sn16.9:12.16": "tâm giải thoát … ",
  "sn16.9:12.17": "tâm không giải thoát, biết là tâm không giải thoát. ",
  "sn16.9:12.18": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng dùng tâm biết tâm của các chúng sinh khác, các cá nhân khác",
  "sn16.9:12.19": "tâm có tham, biết là tâm có tham …vân vân… ",
  "sn16.9:12.20": "tâm không giải thoát, biết là tâm không giải thoát. ",
  "sn16.9:13.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta nhớ lại nhiều đời sống trong quá khứ, như một đời, hai đời, ba đời, bốn đời, năm đời, mười đời, hai mươi đời, ba mươi đời, bốn mươi đời, năm mươi đời, một trăm đời, một ngàn đời, một trăm ngàn đời, nhiều kiếp thế giới co lại, nhiều kiếp thế giới giãn ra, nhiều kiếp thế giới co lại và giãn ra: 'Ở đó ta có tên như vậy, dòng họ như vậy, sắc tướng như vậy, thức ăn như vậy, cảm thọ khổ lạc như vậy, tuổi thọ như vậy; sau khi mất ở đó, ta tái sinh ở kia; ở kia ta có tên như vậy, dòng họ như vậy, sắc tướng như vậy, thức ăn như vậy, cảm thọ khổ lạc như vậy, tuổi thọ như vậy; sau khi mất ở kia, ta tái sinh ở đây'. Như vậy Ta nhớ lại nhiều đời sống trong quá khứ với các nét đặc trưng và chi tiết cụ thể. ",
  "sn16.9:13.2": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng nhớ lại nhiều đời sống trong quá khứ, như một đời …vân vân… với các nét đặc trưng và chi tiết cụ thể. ",
  "sn16.9:14.1": "Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta với thiên nhãn thanh tịnh, vượt qua mắt thường của loài người, thấy các chúng sinh chết và tái sinh, hèn kém hay cao quý, đẹp hay xấu, may mắn hay bất hạnh, Ta hiểu các chúng sinh đi theo nghiệp của họ: 'Thật vậy, những chúng sinh này làm điều ác bằng thân, khẩu, ý, phỉ báng các bậc Thánh, có tà kiến, tạo nghiệp theo tà kiến; sau khi thân hoại mạng chung, họ tái sinh vào cõi dữ, ác thú, đọa xứ, địa ngục; còn những chúng sinh này làm điều lành bằng thân, khẩu, ý, không phỉ báng các bậc Thánh, có chánh kiến, tạo nghiệp theo chánh kiến; sau khi thân hoại mạng chung, họ tái sinh vào cõi lành, cõi trời'. Như vậy Ta với thiên nhãn thanh tịnh, vượt qua mắt thường của loài người, thấy các chúng sinh chết và tái sinh, hèn kém hay cao quý, đẹp hay xấu, may mắn hay bất hạnh, Ta hiểu các chúng sinh đi theo nghiệp của họ. ",
  "sn16.9:14.2": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng với thiên nhãn thanh tịnh, thấy các chúng sinh chết và tái sinh …vân vân… hiểu các chúng sinh đi theo nghiệp của họ. ",
  "sn16.9:15.1": "Này các Tỳ Kheo, Ta do đoạn trừ các lậu hoặc, chứng và trú vô lậu tâm giải thoát, tuệ giải thoát, ngay trong đời này, tự mình biết và chứng ngộ. ",
  "sn16.9:15.2": "Này các Tỳ Kheo, Kassapa cũng do đoạn trừ các lậu hoặc, chứng và trú vô lậu tâm giải thoát, tuệ giải thoát, ngay trong đời này, tự mình biết và chứng ngộ.' ",
  "sn16.9:15.3": "Kinh thứ chín. ",
  "sn16.10:0.1": "Tương Ưng Bộ 16.10 ",
  "sn16.10:0.2": "1. Phẩm Kassapa ",
  "sn16.10:0.3": "Kinh Ni Viện ",
  "sn16.10:1.1": "Tôi đã nghe như vầy",
  "sn16.10:1.2": "một thời Tôn giả Mahākassapa đang ở tại Sāvatthī, rừng Jetavana, tu viện của Anāthapiṇḍika. ",
  "sn16.10:1.3": "Rồi Tôn giả Ānanda vào buổi sáng, đắp y, mang bát, đến chỗ Tôn giả Mahākassapa và nói: ",
  "sn16.10:1.4": "'Thưa Tôn giả Kassapa, hãy cùng đến ni viện nọ.' ",
  "sn16.10:1.5": "'Thưa hiền giả Ānanda, ông cứ đi, ông còn nhiều việc phải làm.' ",
  "sn16.10:1.6": "Lần thứ hai, Tôn giả Ānanda lại nói với Tôn giả Mahākassapa: ",
  "sn16.10:1.7": "'Thưa Tôn giả Kassapa, hãy cùng đến ni viện nọ.' ",
  "sn16.10:1.8": "'Thưa hiền giả Ānanda, ông cứ đi, ông còn nhiều việc phải làm.' ",
  "sn16.10:1.9": "Lần thứ ba, Tôn giả Ānanda lại nói với Tôn giả Mahākassapa: ",
  "sn16.10:1.10": "'Thưa Tôn giả Kassapa, hãy cùng đến ni viện nọ.' ",
  "sn16.10:2.1": "Rồi Tôn giả Mahākassapa vào buổi sáng, đắp y, mang bát, cùng với Tôn giả Ānanda đi theo sau, đến ni viện nọ; sau khi đến, ngồi vào chỗ đã được soạn sẵn. ",
  "sn16.10:2.2": "Rồi nhiều Tỳ Kheo Ni đến chỗ Tôn giả Mahākassapa; sau khi đến, đảnh lễ Tôn giả Mahākassapa rồi ngồi xuống một bên. ",
  "sn16.10:2.3": "Các Tỳ Kheo Ni đang ngồi một bên, Tôn giả Mahākassapa thuyết pháp, khích lệ, làm cho hoan hỷ, làm cho phấn khởi. ",
  "sn16.10:2.4": "Sau khi Tôn giả Mahākassapa thuyết pháp, khích lệ, làm cho hoan hỷ, làm cho phấn khởi các Tỳ Kheo Ni, vị ấy đứng dậy khỏi chỗ ngồi và ra đi. ",
  "sn16.10:3.1": "Rồi Tỳ Kheo Ni Thullatissā không vui lòng và nói ra lời không vui lòng: ",
  "sn16.10:3.2": "'Sao Tôn giả Mahākassapa lại nghĩ mình có thể thuyết pháp trước mặt Tôn giả Ānanda, bậc Vệ-đà mâu ni? '",
  "sn16.10:3.3": "Cũng giống như người bán kim lại nghĩ mình có thể bán kim cho người thợ làm kim; ",
  "sn16.10:3.4": "cũng vậy, Tôn giả Mahākassapa nghĩ mình có thể thuyết pháp trước mặt Tôn giả Ānanda, bậc Vệ-đà mâu ni.' ",
  "sn16.10:4.1": "Tôn giả Mahākassapa nghe Tỳ Kheo Ni Thullatissā nói những lời đó. ",
  "sn16.10:4.2": "Rồi Tôn giả Mahākassapa nói với Tôn giả Ānanda: ",
  "sn16.10:4.3": "'Thưa hiền giả Ānanda, ông nghĩ saota là người bán kim, còn ông là thợ làm kim; '",
  "sn16.10:4.4": "hay ta là thợ làm kim, còn ông là người bán kim?' ",
  "sn16.10:4.5": "'Thưa Tôn giả Kassapa, xin hãy nhẫn nhục, người phụ nữ đó còn ngu muội.' ",
  "sn16.10:4.6": "'Thưa hiền giả Ānanda, xin hãy chờ đó, đừng để chúng tăng phải điều tra thêm. '",
  "sn16.10:5.1": "Thưa hiền giả Ānanda, ông nghĩ thế nào, ",
  "sn16.10:5.2": "Thế Tôn có tuyên bố trước hội chúng Tỳ Kheo rằng: ",
  "sn16.10:5.3": "'Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta ly dục, ly pháp bất thiện, chứng và trú Sơ thiền, có tầm và tứ, có hỷ và lạc do ly dục sinh. '",
  "sn16.10:5.4": "Này các Tỳ Kheo, bất cứ khi nào Ānanda muốn, vị ấy cũng ly dục, ly pháp bất thiện, chứng và trú Sơ thiền, có tầm và tứ, có hỷ và lạc do ly dục sinh' không?' ",
  "sn16.10:5.5": "'Thưa không, bạch Tôn giả.' ",
  "sn16.10:6.1": "'Thưa hiền giả, chính Ta được Thế Tôn tuyên bố trước hội chúng Tỳ Kheo rằng: '",
  "sn16.10:6.2": "'Này các Tỳ Kheo, bất cứ khi nào Ta muốn, Ta ly dục, ly pháp bất thiện, chứng và trú Sơ thiền, có tầm và tứ, có hỷ và lạc do ly dục sinh. '",
  "sn16.10:6.3": "Này các Tỳ Kheo, bất cứ khi nào Kassapa muốn, vị ấy cũng ly dục, ly pháp bất thiện …vân vân… chứng và trú Sơ thiền' …vân vân… ",
  "sn16.10:6.4": "(Toàn bộ chín loại định và năm loại thần thông cần được hiểu theo cách mở rộng như vậy.) ",
  "sn16.10:7.1": "Thưa hiền giả Ānanda, ông nghĩ thế nào, ",
  "sn16.10:7.2": "Thế Tôn có tuyên bố trước hội chúng Tỳ Kheo rằng: ",
  "sn16.10:7.3": "'Này các Tỳ Kheo, Ta do đoạn trừ các lậu hoặc, chứng và trú vô lậu tâm giải thoát, tuệ giải thoát, ngay trong đời này, tự mình biết và chứng ngộ. '",
  "sn16.10:7.4": "Ānanda cũng do đoạn trừ các lậu hoặc, chứng và trú vô lậu tâm giải thoát, tuệ giải thoát, ngay trong đời này, tự mình biết và chứng ngộ' không?' ",
  "sn16.10:7.5": "'Thưa không, bạch Tôn giả.' ",
  "sn16.10:8.1": "'Thưa hiền giả, chính Ta được Thế Tôn tuyên bố trước hội chúng Tỳ Kheo rằng: '",
  "sn16.10:8.2": "'Này các Tỳ Kheo, Ta do đoạn trừ các lậu hoặc, chứng và trú vô lậu tâm giải thoát, tuệ giải thoát, ngay trong đời này, tự mình biết và chứng ngộ. '",
  "sn16.10:8.3": "Kassapa cũng do đoạn trừ các lậu hoặc, chứng và trú vô lậu tâm giải thoát, tuệ giải thoát, ngay trong đời này, tự mình biết và chứng ngộ'. ",
  "sn16.10:9.1": "Thưa hiền giả, ai nghĩ mình có thể che khuất sáu thần thông của ta, cũng giống như nghĩ có thể dùng một chiếc lá cọ che khuất một con voi bảy thước hoặc bảy thước rưỡi.' ",
  "sn16.10:10.1": "Và Tỳ Kheo Ni Thullatissā sau đó đã rời bỏ đời sống phạm hạnh. ",
  "sn16.10:10.2": "Kinh thứ mười. ",
  "sn16.11:0.1": "Tương Ưng Bộ 16.11 ",
  "sn16.11:0.2": "1. Phẩm Kassapa ",
  "sn16.11:0.3": "Kinh Y Phục ",
  "sn16.11:1.1": "Một thời Tôn giả Mahākassapa đang ở tại Rājagaha, vườn Trúc Lâm, vườn Kalandakanivāpa. ",
  "sn16.11:1.2": "Lúc bấy giờ Tôn giả Ānanda đang du hành ở vùng phía Nam cùng với đại chúng Tỳ Kheo. ",
  "sn16.11:2.1": "Lúc bấy giờ khoảng ba mươi Tỳ Kheo là người cùng tu với Tôn giả Ānanda đã từ bỏ học giới và hoàn tục, phần lớn là những người trẻ tuổi. ",
  "sn16.11:2.2": "Rồi Tôn giả Ānanda sau khi du hành ở vùng phía Nam tùy ý, đến Rājagaha, vườn Trúc Lâm, vườn Kalandakanivāpa, đến chỗ Tôn giả Mahākassapa; sau khi đến, đảnh lễ Tôn giả Mahākassapa rồi ngồi xuống một bên. Tôn giả Mahākassapa nói với Tôn giả Ānanda đang ngồi một bên: ",
  "sn16.11:2.3": "'Thưa hiền giả Ānanda, Thế Tôn đã quy định phép ăn ba nhà vì những lý do gì?' ",
  "sn16.11:3.1": "'Thưa Tôn giả Kassapa, Thế Tôn đã quy định phép ăn ba nhà vì ba lý do'",
  "sn16.11:3.2": "để chế ngự những người xấu ác, để các Tỳ Kheo lương thiện được sống an vui, để những kẻ có ác ý không dựa vào phe phái nào đó mà phá vỡ chúng tăng. ",
  "sn16.11:3.3": "Thưa Tôn giả Kassapa, đây là ba lý do Thế Tôn đã quy định phép ăn ba nhà.' ",
  "sn16.11:4.1": "'Vậy thưa hiền giả Ānanda, tại sao ông lại đi du hành cùng với những Tỳ Kheo trẻ nàynhững người chưa thu thúc các căn, không biết tiết độ trong ăn uống, không tinh tấn không ngủ? '",
  "sn16.11:4.2": "Ông đang đi như kẻ phá hoại mùa màng, như kẻ phá hoại các gia đình. ",
  "sn16.11:4.3": "Thưa hiền giả Ānanda, đồ chúng của ông đang tan rã; ",
  "sn16.11:4.4": "thưa hiền giả, những người mới vào đạo đang bị mất đi. ",
  "sn16.11:4.5": "Người trẻ này không biết điều độ.' ",
  "sn16.11:5.1": "'Thưa Tôn giả Kassapa, tóc bạc đã mọc trên đầu con rồi. '",
  "sn16.11:5.2": "Ấy vậy mà chúng con ngày nay vẫn không thoát khỏi lời 'trẻ con' của Tôn giả Mahākassapa.' ",
  "sn16.11:5.3": "'Đúng vậy, thưa hiền giả Ānanda, ông đang đi du hành cùng với những Tỳ Kheo trẻ nàynhững người chưa thu thúc các căn, không biết tiết độ trong ăn uống, không tinh tấn không ngủ. Ông đang đi như kẻ phá hoại mùa màng, như kẻ phá hoại các gia đình. '",
  "sn16.11:5.4": "Thưa hiền giả Ānanda, đồ chúng của ông đang tan rã; ",
  "sn16.11:5.5": "thưa hiền giả, những người mới vào đạo đang bị mất đi. ",
  "sn16.11:5.6": "Người trẻ này không biết điều độ.' ",
  "sn16.11:6.1": "Tỳ Kheo Ni Thullanandā nghe được điều đó: ",
  "sn16.11:6.2": "'Tôn giả Mahākassapa đã chê bai Tôn giả Ānanda, bậc Vệ-đà mâu ni, bằng lời 'trẻ con'.' ",
  "sn16.11:7.1": "Rồi Tỳ Kheo Ni Thullanandā không vui lòng và nói ra lời không vui lòng: ",
  "sn16.11:7.2": "'Sao Tôn giả Mahākassapa, người trước kia là ngoại đạo, lại nghĩ mình có thể chê bai Tôn giả Ānanda, bậc Vệ-đà mâu ni, bằng lời 'trẻ con'?' ",
  "sn16.11:7.3": "Tôn giả Mahākassapa nghe Tỳ Kheo Ni Thullanandā nói những lời đó. ",
  "sn16.11:8.1": "Rồi Tôn giả Mahākassapa nói với Tôn giả Ānanda: ",
  "sn16.11:8.2": "'Thưa hiền giả Ānanda, Tỳ Kheo Ni Thullanandā đã nói những lời vội vàng, không suy nghĩ chín chắn. '",
  "sn16.11:8.3": "Thưa hiền giả, kể từ khi ta cạo tóc và râu, đắp y vàng, xuất gia từ gia đình đến với đời sống không gia đình, ta không biết đến vị Thầy nào khác ngoài Thế Tôn, bậc Arahant, Chánh Đẳng Giác. ",
  "sn16.11:8.4": "Thưa hiền giả, trước kia khi còn là cư sĩ, ta nghĩ: ",
  "sn16.11:8.5": "'Đời sống tại gia chật hẹp, đầy bụi bặm; đời sống xuất gia như hư không rộng mở. '",
  "sn16.11:8.6": "Sống trong gia đình không dễ gì sống hoàn toàn đầy đủ, hoàn toàn thanh tịnh, trắng trong như vỏ ốc đánh bóng, đời sống phạm hạnh. ",
  "sn16.11:8.7": "Thà ta hãy cạo tóc và râu, đắp y vàng, xuất gia từ gia đình đến với đời sống không gia đình'. ",
  "sn16.11:8.8": "Về sau, thưa hiền giả, ta làm một chiếc y bằng vải rách khâu lại, và hướng đến các bậc Arahant trên đời, ta cạo tóc và râu, đắp y vàng, xuất gia từ gia đình đến với đời sống không gia đình. ",
  "sn16.11:9.1": "Sau khi xuất gia như vậy, trên đường đi, ta thấy Thế Tôn đang ngồi ở đền Bahuputta, giữa Rājagaha và Nāḷanda. ",
  "sn16.11:9.2": "Khi thấy, ta nghĩ: ",
  "sn16.11:9.3": "'Nếu ta được gặp bậc Thầy, ta được gặp Thế Tôn; '",
  "sn16.11:9.4": "nếu ta được gặp bậc Thiện Thệ, ta được gặp Thế Tôn; ",
  "sn16.11:9.5": "nếu ta được gặp bậc Chánh Đẳng Giác, ",
  "sn16.11:9.6": "ta được gặp Thế Tôn'. ",
  "sn16.11:9.7": "Thưa hiền giả, ta liền cúi đầu xuống chân Thế Tôn tại chỗ đó và thưa: ",
  "sn16.11:9.8": "'Bạch Thế Tôn, Thế Tôn là Thầy của con, con là đệ tử; '",
  "sn16.11:9.9": "bạch Thế Tôn, Thế Tôn là Thầy của con, con là đệ tử'. ",
  "sn16.11:9.10": "Thưa hiền giả, khi ta nói vậy, Thế Tôn nói với ta: ",
  "sn16.11:9.11": "'Này Kassapa, người nào nói với đệ tử đã thành tựu trọn vẹn với tâm như vậy rằng: «Ta biết» trong khi không biết, rằng «Ta thấy» trong khi không thấy, thì đầu của người đó sẽ vỡ ra. '",
  "sn16.11:9.12": "Nhưng này Kassapa, Ta nói «Ta biết» vì thực sự Ta biết, nói «Ta thấy» vì thực sự Ta thấy. ",
  "sn16.11:10.1": "Vậy, này Kassapa, ông hãy học tập như sau: ",
  "sn16.11:10.2": "«Ta sẽ có sự hổ thẹn và biết sợ hãi mạnh mẽ đối với các bậc trưởng lão, bậc trung và bậc mới tu»'. ",
  "sn16.11:10.3": "Như vậy, này Kassapa, ông hãy học tập. ",
  "sn16.11:11.1": "Vậy, này Kassapa, ông hãy học tập như sau: ",
  "sn16.11:11.2": "«Bất kỳ pháp nào ta nghe liên quan đến thiện pháp, ta sẽ lấy đó làm trọng yếu, chú ý kỹ, lắng nghe pháp với toàn tâm»'. ",
  "sn16.11:11.3": "Như vậy, này Kassapa, ông hãy học tập. ",
  "sn16.11:12.1": "Vậy, này Kassapa, ông hãy học tập như sau: ",
  "sn16.11:12.2": "«Niệm thân hướng đến thân sẽ không rời bỏ ta»'. ",
  "sn16.11:12.3": "Như vậy, này Kassapa, ông hãy học tập'. ",
  "sn16.11:13.1": "Thưa hiền giả, sau khi Thế Tôn giáo giới ta bằng lời giáo giới này, Ngài đứng dậy khỏi chỗ ngồi và ra đi. ",
  "sn16.11:13.2": "Thưa hiền giả, ta đã thọ thực của người đời bảy ngày, và đến ngày thứ tám thì chứng ngộ tuệ giác. ",
  "sn16.11:14.1": "Rồi, thưa hiền giả, Thế Tôn rời khỏi đường đi và đến gốc một cây nọ. ",
  "sn16.11:14.2": "Rồi ta trải tấm y bằng vải rách khâu lại thành bốn lớp và thưa Thế Tôn: ",
  "sn16.11:14.3": "'Bạch Thế Tôn, xin Thế Tôn hãy ngồi đây, điều đó sẽ đem lại hạnh phúc và an lạc lâu dài cho con'. ",
  "sn16.11:14.4": "Thế Tôn liền ngồi vào chỗ đã soạn sẵn. ",
  "sn16.11:14.5": "Sau khi ngồi, thưa hiền giả, Thế Tôn nói với ta: ",
  "sn16.11:14.6": "'Này Kassapa, tấm y bằng vải rách khâu lại của ông thật mềm mại'. ",
  "sn16.11:14.7": "'Bạch Thế Tôn, xin Thế Tôn hãy nhận tấm y bằng vải rách khâu lại này vì lòng thương xót con'. ",
  "sn16.11:14.8": "'Nhưng ông có chịu mặc những tấm vải gai thô của Ta không, Kassapa?' ",
  "sn16.11:14.9": "'Bạch Thế Tôn, con sẽ mặc những tấm vải gai thô của Thế Tôn'. ",
  "sn16.11:14.10": "Thưa hiền giả, ta đã dâng tấm y bằng vải rách khâu lại cho Thế Tôn. ",
  "sn16.11:14.11": "Và ta đã nhận những tấm vải gai thô của Thế Tôn. ",
  "sn16.11:15.1": "Thưa hiền giả, nếu nói đúng, người ta có thể nói về ta: ",
  "sn16.11:15.2": "'Con ruột của Thế Tôn, sinh từ miệng Ngài, sinh từ Pháp, được Pháp tạo ra, thừa hưởng Pháp, đã nhận những tấm vải gai thô'nếu nói đúng, người ta có thể nói về ta: ",
  "sn16.11:15.3": "'Con ruột của Thế Tôn, sinh từ miệng Ngài, sinh từ Pháp, được Pháp tạo ra, thừa hưởng Pháp, đã nhận những tấm vải gai thô'. ",
  "sn16.11:16.1": "Thưa hiền giả, bất cứ khi nào ta muốn, ta ly dục, ly pháp bất thiện, chứng và trú Sơ thiền, có tầm và tứ, có hỷ và lạc do ly dục sinh. ",
  "sn16.11:16.2": "Thưa hiền giả, bất cứ khi nào ta muốn …vân vân… ",
  "sn16.11:16.3": "(Toàn bộ chín loại định và năm loại thần thông cần được hiểu theo cách mở rộng như vậy.) ",
  "sn16.11:17.1": "Thưa hiền giả, ta do đoạn trừ các lậu hoặc, chứng và trú vô lậu tâm giải thoát, tuệ giải thoát, ngay trong đời này, tự mình biết và chứng ngộ; ",
  "sn16.11:17.2": "ai nghĩ mình có thể che khuất sáu thần thông của ta, thưa hiền giả, cũng giống như nghĩ có thể dùng một chiếc lá cọ che khuất một con voi bảy thước hoặc bảy thước rưỡi.' ",
  "sn16.11:18.1": "Và Tỳ Kheo Ni Thullanandā sau đó đã rời bỏ đời sống phạm hạnh. ",
  "sn16.11:18.2": "Kinh thứ mười một. ",
  "sn16.12:0.1": "Tương Ưng Bộ 16.12 ",
  "sn16.12:0.2": "1. Phẩm Kassapa ",
  "sn16.12:0.3": "Kinh Sau Khi Chết ",
  "sn16.12:1.1": "Một thời Tôn giả Mahākassapa và Tôn giả Sāriputta đang ở tại Bārāṇasī, vườn Lộc Uyển Isipatana. ",
  "sn16.12:1.2": "Rồi Tôn giả Sāriputta vào buổi chiều, sau khi xuất định, đến chỗ Tôn giả Mahākassapa. ",
  "sn16.12:1.3": "Sau khi chào hỏi thân thiện với Tôn giả Mahākassapa, ngồi xuống một bên. Tôn giả Sāriputta đang ngồi một bên, liền hỏi Tôn giả Mahākassapa: ",
  "sn16.12:1.4": "'Thưa hiền giả Kassapa, Như Lai có tồn tại sau khi chết không?' ",
  "sn16.12:1.5": "'Thưa hiền giả, Thế Tôn không có trả lời câu hỏi đó: '",
  "sn16.12:1.6": "'Như Lai tồn tại sau khi chết'.' '",
  "sn16.12:1.7": "'Vậy thưa hiền giả, Như Lai không tồn tại sau khi chết?' ",
  "sn16.12:1.8": "'Thưa hiền giả, Thế Tôn cũng không có trả lời câu hỏi đó: '",
  "sn16.12:1.9": "'Như Lai không tồn tại sau khi chết'.' '",
  "sn16.12:1.10": "'Vậy thưa hiền giả, Như Lai vừa tồn tại vừa không tồn tại sau khi chết?' ",
  "sn16.12:1.11": "'Thưa hiền giả, Thế Tôn cũng không có trả lời câu hỏi đó: '",
  "sn16.12:1.12": "'Như Lai vừa tồn tại vừa không tồn tại sau khi chết'.' '",
  "sn16.12:1.13": "'Vậy thưa hiền giả, Như Lai không tồn tại cũng không phải là không tồn tại sau khi chết?' ",
  "sn16.12:1.14": "'Thưa hiền giả, Thế Tôn cũng không có trả lời câu hỏi đó: '",
  "sn16.12:1.15": "'Như Lai không tồn tại cũng không phải là không tồn tại sau khi chết'.' '",
  "sn16.12:1.16": "'Thưa hiền giả, tại sao Thế Tôn không trả lời những câu hỏi đó?' ",
  "sn16.12:1.17": "'Thưa hiền giả, bởi vì những câu hỏi đó không liên quan đến mục đích, không phải là nền tảng của đời sống phạm hạnh, không dẫn đến yếm ly, không dẫn đến ly tham, không dẫn đến đoạn diệt, không dẫn đến tịch lặng, không dẫn đến thắng trí, không dẫn đến giác ngộ, không dẫn đến Niết-bàn. '",
  "sn16.12:1.18": "Vì vậy Thế Tôn không trả lời những câu hỏi đó.' ",
  "sn16.12:2.1": "'Vậy thưa hiền giả, Thế Tôn đã trả lời điều gì?' ",
  "sn16.12:2.2": "'Thưa hiền giả, Thế Tôn đã trả lời: 'Đây là khổ'; '",
  "sn16.12:2.3": "Thế Tôn đã trả lời: 'Đây là nguyên nhân của khổ'; ",
  "sn16.12:2.4": "Thế Tôn đã trả lời: 'Đây là sự đoạn diệt khổ'; ",
  "sn16.12:2.5": "Thế Tôn đã trả lời: 'Đây là con đường dẫn đến sự đoạn diệt khổ'.' ",
  "sn16.12:2.6": "'Thưa hiền giả, tại sao Thế Tôn lại trả lời những điều đó?' ",
  "sn16.12:2.7": "'Thưa hiền giả, bởi vì những điều đó liên quan đến mục đích, là nền tảng của đời sống phạm hạnh, dẫn đến yếm ly, dẫn đến ly tham, dẫn đến đoạn diệt, dẫn đến tịch lặng, dẫn đến thắng trí, dẫn đến giác ngộ, dẫn đến Niết-bàn. '",
  "sn16.12:2.8": "Vì vậy Thế Tôn đã trả lời những điều đó.' ",
  "sn16.12:2.9": "Kinh thứ mười hai. ",
  "sn16.13:0.1": "Tương Ưng Bộ 16.13 ",
  "sn16.13:0.2": "1. Phẩm Kassapa ",
  "sn16.13:0.3": "Kinh Chánh Pháp Giả Mạo ",
  "sn16.13:1.1": "Tôi đã nghe như vầy",
  "sn16.13:1.2": "một thời Thế Tôn đang ở tại Sāvatthī, rừng Jetavana, tu viện của Anāthapiṇḍika. ",
  "sn16.13:1.3": "Rồi Tôn giả Mahākassapa đến chỗ Thế Tôn, sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Tôn giả Mahākassapa đang ngồi một bên, liền thưa Thế Tôn: ",
  "sn16.13:1.4": "'Bạch Thế Tôn, nguyên nhân và điều kiện gì khiến trước kia có ít học giới hơn mà có nhiều Tỳ Kheo hơn chứng ngộ? '",
  "sn16.13:1.5": "Và bạch Thế Tôn, nguyên nhân và điều kiện gì khiến ngày nay có nhiều học giới hơn mà lại có ít Tỳ Kheo hơn chứng ngộ?' ",
  "sn16.13:1.6": "'Này Kassapa, điều này xảy ra khi các chúng sinh suy giảm và Chánh Pháp bị biến mấtcó nhiều học giới hơn mà ít Tỳ Kheo hơn chứng ngộ. '",
  "sn16.13:1.7": "Này Kassapa, Chánh Pháp chưa biến mất khi pháp giả mạo Chánh Pháp chưa xuất hiện trên đời. ",
  "sn16.13:1.8": "Khi nào pháp giả mạo Chánh Pháp xuất hiện trên đời, thì Chánh Pháp mới biến mất. ",
  "sn16.13:2.1": "Này Kassapa, cũng giống như vàng thật chưa biến mất khi vàng giả chưa xuất hiện trên đời. ",
  "sn16.13:2.2": "Khi nào vàng giả xuất hiện trên đời, thì vàng thật mới biến mất. ",
  "sn16.13:2.3": "Cũng vậy, này Kassapa, Chánh Pháp chưa biến mất khi pháp giả mạo Chánh Pháp chưa xuất hiện trên đời. ",
  "sn16.13:2.4": "Khi nào pháp giả mạo Chánh Pháp xuất hiện trên đời, thì Chánh Pháp mới biến mất. ",
  "sn16.13:3.1": "Này Kassapa, đất không làm cho Chánh Pháp biến mất, nước không làm cho Chánh Pháp biến mất, lửa không làm cho Chánh Pháp biến mất, gió không làm cho Chánh Pháp biến mất; ",
  "sn16.13:3.2": "chính những kẻ vô minh nổi lên ở đây làm cho Chánh Pháp biến mất. ",
  "sn16.13:3.3": "Này Kassapa, ví như một chiếc thuyền chìm ngay từ đầu; ",
  "sn16.13:3.4": "này Kassapa, Chánh Pháp không biến mất theo cách đó. ",
  "sn16.13:4.1": "Này Kassapa, có năm pháp suy đồi này dẫn đến sự rối loạn và biến mất của Chánh Pháp. ",
  "sn16.13:4.2": "Năm pháp đó là gì? ",
  "sn16.13:4.3": "Ở đây, này Kassapa, các Tỳ Kheo, Tỳ Kheo Ni, nam cư sĩ, nữ cư sĩ sống thiếu kính trọng và không tùy thuận Bậc Đạo Sư, sống thiếu kính trọng và không tùy thuận Pháp, sống thiếu kính trọng và không tùy thuận Tăng, sống thiếu kính trọng và không tùy thuận học giới, sống thiếu kính trọng và không tùy thuận định ",
  "sn16.13:4.4": "này Kassapa, đây là năm pháp suy đồi dẫn đến sự rối loạn và biến mất của Chánh Pháp. ",
  "sn16.13:5.1": "Này Kassapa, có năm pháp này dẫn đến sự vững bền, không rối loạn và không biến mất của Chánh Pháp. ",
  "sn16.13:5.2": "Năm pháp đó là gì? ",
  "sn16.13:5.3": "Ở đây, này Kassapa, các Tỳ Kheo, Tỳ Kheo Ni, nam cư sĩ, nữ cư sĩ sống có kính trọng và tùy thuận Bậc Đạo Sư, sống có kính trọng và tùy thuận Pháp, sống có kính trọng và tùy thuận Tăng, sống có kính trọng và tùy thuận học giới, sống có kính trọng và tùy thuận định ",
  "sn16.13:5.4": "này Kassapa, đây là năm pháp dẫn đến sự vững bền, không rối loạn và không biến mất của Chánh Pháp.' ",
  "sn16.13:5.5": "Kinh thứ mười ba. ",
  "sn16.13:5.6": "Phẩm Kassapa thứ nhất. ",
  "sn16.13:6.0": "Tóm tắt phẩm ",
  "sn16.13:6.1": "Biết đủ và không biết sợ, ",
  "sn16.13:6.2": "ví mặt trăng và thăm gia đình; ",
  "sn16.13:6.3": "Già nua, ba lần giáo giới, ",
  "sn16.13:6.4": "thiền định thần thông, ni viện; ",
  "sn16.13:6.5": "Y phục, sau khi chết, ",
  "sn16.13:6.6": "và chánh pháp giả mạo. ",
  "sn16.13:6.7": "Tương Ưng Kassapa hoàn tất. "
}
window.BILARA["sn16_v1"]["vi"]["sn16_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
