window.BILARA = window.BILARA || {};
window.BILARA["sn17_v1"] = window.BILARA["sn17_v1"] || {};
window.BILARA["sn17_v1"]["vi"] = {
  "sn17.1:0.1": "Kinh Tương Ưng 17.1 ",
  "sn17.1:0.2": "1. Phẩm Thứ Nhất ",
  "sn17.1:0.3": "Kinh Tàn Khốc ",
  "sn17.1:1.1": "Tôi nghe như vầy ",
  "sn17.1:1.2": "Một thời, Thế Tôn trú tại Sāvatthī, ở Kỳ Viên, tinh xá của ông Anāthapiṇḍika. ",
  "sn17.1:1.3": "Ở đó, Thế Tôn gọi các Tỳ Kheo: ",
  "sn17.1:1.4": "'Này các Tỳ Kheo!' ",
  "sn17.1:1.5": "'Bạch Thế Tôn!' Các Tỳ Kheo đáp lại Thế Tôn. ",
  "sn17.1:1.6": "Thế Tôn nói điều này: ",
  "sn17.1:2.1": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc, gay go, thô bạo, là chướng ngại cho việc đạt đến an tịnh vô thượng thoát khỏi mọi ách phược. '",
  "sn17.1:2.2": "Do vậy, này các Tỳ Kheo, cần phải học tập như sau: ",
  "sn17.1:2.3": "'Lợi dưỡng, cung kính và danh vọng đã sinh khởi, chúng ta sẽ từ bỏ; và dù đã sinh khởi, sẽ không để chúng nắm giữ tâm ta.' ",
  "sn17.1:2.4": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.1:2.5": "Thứ nhất. ",
  "sn17.2:0.1": "Kinh Tương Ưng 17.2 ",
  "sn17.2:0.2": "1. Phẩm Thứ Nhất ",
  "sn17.2:0.3": "Kinh Lưỡi Câu ",
  "sn17.2:1.1": "Trú tại Sāvatthī. ",
  "sn17.2:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc, gay go, thô bạo, là chướng ngại cho việc đạt đến an tịnh vô thượng thoát khỏi mọi ách phược. '",
  "sn17.2:1.3": "Ví như, này các Tỳ Kheo, một người câu cá thả lưỡi câu có mồi xuống hồ nước sâu. ",
  "sn17.2:1.4": "Một con cá thấy mồi liền nuốt vào. ",
  "sn17.2:1.5": "Như vậy, này các Tỳ Kheo, con cá ấy nuốt lưỡi câu, rơi vào bất hạnh, rơi vào tai họa, chịu sự sai khiến tùy ý của người câu cá. ",
  "sn17.2:2.1": "Này các Tỳ Kheo, 'người câu cá' là tên gọi của Ma vương ác ma. ",
  "sn17.2:2.2": "Này các Tỳ Kheo, 'lưỡi câu' là tên gọi của lợi dưỡng, cung kính và danh vọng. ",
  "sn17.2:2.3": "Này các Tỳ Kheo, bất cứ Tỳ Kheo nào thích thú, say đắm lợi dưỡng, cung kính và danh vọng đã sinh khởi, vị ấy được gọi là Tỳ Kheo nuốt lưỡi câu của Ma vương, rơi vào bất hạnh, rơi vào tai họa, chịu sự sai khiến tùy ý của ác ma. ",
  "sn17.2:2.4": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc, gay go, thô bạo, là chướng ngại cho việc đạt đến an tịnh vô thượng thoát khỏi mọi ách phược. ",
  "sn17.2:2.5": "Do vậy, này các Tỳ Kheo, cần phải học tập như sau: ",
  "sn17.2:2.6": "'Lợi dưỡng, cung kính và danh vọng đã sinh khởi, chúng ta sẽ từ bỏ; và dù đã sinh khởi, sẽ không để chúng nắm giữ tâm ta.' ",
  "sn17.2:2.7": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.2:2.8": "Thứ hai. ",
  "sn17.3:0.1": "Kinh Tương Ưng 17.3 ",
  "sn17.3:0.2": "1. Phẩm Thứ Nhất ",
  "sn17.3:0.3": "Kinh Con Rùa ",
  "sn17.3:1.1": "Trú tại Sāvatthī. ",
  "sn17.3:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... chướng ngại cho việc đạt đến an tịnh vô thượng. '",
  "sn17.3:1.3": "Thuở xưa, này các Tỳ Kheo, có một đàn rùa lớn sống lâu đời ở một hồ nước. ",
  "sn17.3:1.4": "Khi ấy, này các Tỳ Kheo, một con rùa nói với một con rùa khác: ",
  "sn17.3:1.5": "'Này bạn rùa, đừng đến khu vực đó!' ",
  "sn17.3:1.6": "Nhưng, này các Tỳ Kheo, con rùa kia vẫn đi đến khu vực đó. ",
  "sn17.3:1.7": "Một người thợ săn bắn trúng nó bằng mũi lao. ",
  "sn17.3:1.8": "Rồi, này các Tỳ Kheo, con rùa bị thương bò đến chỗ con rùa kia. ",
  "sn17.3:1.9": "Con rùa kia thấy nó đang đến từ đằng xa. ",
  "sn17.3:1.10": "Thấy vậy, nó nói với con rùa bị thương: ",
  "sn17.3:1.11": "'Này bạn rùa, có phải bạn đã đi đến khu vực đó không?' ",
  "sn17.3:1.12": "'Đúng vậy, này bạn rùa, tôi đã đi đến khu vực đó.' ",
  "sn17.3:1.13": "'Này bạn rùa, bạn có bình an, không bị thương không?' ",
  "sn17.3:1.14": "'Tôi bình an, không bị thương, này bạn rùa; nhưng có sợi dây này cứ theo sau lưng tôi mãi.' ",
  "sn17.3:1.15": "'Thực ra bạn đã bị thương, thực ra bạn đã bị tổn hại. '",
  "sn17.3:1.16": "Này bạn rùa, chính vì sợi dây này mà cha và ông của bạn đã rơi vào bất hạnh, rơi vào tai họa. ",
  "sn17.3:1.17": "Thôi, bây giờ bạn không còn là người của chúng tôi nữa.' ",
  "sn17.3:2.1": "Này các Tỳ Kheo, 'người thợ săn' là tên gọi của Ma vương ác ma. ",
  "sn17.3:2.2": "Này các Tỳ Kheo, 'cái bẫy' là tên gọi của lợi dưỡng, cung kính và danh vọng. ",
  "sn17.3:2.3": "Này các Tỳ Kheo, 'sợi dây' là tên gọi của tham ái. ",
  "sn17.3:2.4": "Này các Tỳ Kheo, bất cứ Tỳ Kheo nào thích thú, say đắm lợi dưỡng, cung kính và danh vọng đã sinh khởi ",
  "sn17.3:2.5": "vị ấy được gọi là Tỳ Kheo tham lam bẫy của ác ma, rơi vào bất hạnh, rơi vào tai họa, chịu sự sai khiến tùy ý của ác ma. ",
  "sn17.3:2.6": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.3:2.7": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.3:2.8": "Thứ ba. ",
  "sn17.4:0.1": "Kinh Tương Ưng 17.4 ",
  "sn17.4:0.2": "1. Phẩm Thứ Nhất ",
  "sn17.4:0.3": "Kinh Con Dê Lông Dài ",
  "sn17.4:1.1": "Trú tại Sāvatthī. ",
  "sn17.4:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... chướng ngại cho việc đạt đến an tịnh vô thượng. '",
  "sn17.4:1.3": "Ví như, này các Tỳ Kheo, một con dê lông dài đi vào bụi gai rậm. ",
  "sn17.4:1.4": "Nó bị mắc ở đây, bị vướng ở đây, bị trói ở đây, gặp tai ương bất hạnh ở đây. ",
  "sn17.4:1.5": "Cũng vậy, này các Tỳ Kheo, ở đây có Tỳ Kheo kia bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, vào buổi sáng đắp y, mang bát và y, đi vào làng hay thị trấn để khất thực. ",
  "sn17.4:1.6": "Vị ấy bị mắc ở đây, bị vướng ở đây, bị trói ở đây, gặp tai ương bất hạnh ở đây. ",
  "sn17.4:1.7": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.4:1.8": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.4:1.9": "Thứ tư. ",
  "sn17.5:0.1": "Kinh Tương Ưng 17.5 ",
  "sn17.5:0.2": "1. Phẩm Thứ Nhất ",
  "sn17.5:0.3": "Kinh Con Bọ Phân ",
  "sn17.5:1.1": "Trú tại Sāvatthī. ",
  "sn17.5:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... chướng ngại cho việc đạt đến an tịnh vô thượng. '",
  "sn17.5:1.3": "Ví như, này các Tỳ Kheo, một con bọ phân ăn phân, chứa đầy phân, thân đầy ắp phân. Phía trước nó có một đống phân to lớn. ",
  "sn17.5:1.4": "Vì vậy, nó khinh thường các con bọ phân khác: ",
  "sn17.5:1.5": "'Ta đây ăn phân, chứa đầy phân, thân đầy ắp phân, và trước mặt ta còn có đống phân to lớn này.' ",
  "sn17.5:1.6": "Cũng vậy, này các Tỳ Kheo, ở đây có Tỳ Kheo kia bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, vào buổi sáng đắp y, mang bát và y, đi vào làng hay thị trấn để khất thực. ",
  "sn17.5:1.7": "Vị ấy ăn no nê, được mời đến ngày hôm sau, và bình bát đầy thức ăn. ",
  "sn17.5:1.8": "Trở về tịnh xá, vị ấy khoe khoang trước hội chúng Tỳ Kheo: ",
  "sn17.5:1.9": "'Ta đã ăn no nê, ta được mời cho ngày mai, bình bát ta đầy thức ăn, ta nhận được y phục, thực phẩm, trú xứ và thuốc men; còn các Tỳ Kheo kia ít phước đức, ít uy tín, không nhận được y phục, thực phẩm, trú xứ và thuốc men.' ",
  "sn17.5:1.10": "Bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, vị ấy khinh thường các Tỳ Kheo hiền thiện khác. ",
  "sn17.5:1.11": "Điều này, này các Tỳ Kheo, sẽ mang lại bất lợi và khổ đau lâu dài cho người ngu si đó. ",
  "sn17.5:1.12": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.5:1.13": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.5:1.14": "Thứ năm. ",
  "sn17.6:0.1": "Kinh Tương Ưng 17.6 ",
  "sn17.6:0.2": "1. Phẩm Thứ Nhất ",
  "sn17.6:0.3": "Kinh Tia Sét ",
  "sn17.6:1.1": "Trú tại Sāvatthī. ",
  "sn17.6:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... chướng ngại cho việc đạt đến an tịnh vô thượng. '",
  "sn17.6:1.3": "Này các Tỳ Kheo, th차차차 bánh xe sét có thể đến, nhưng đừng để lợi dưỡng, cung kính và danh vọng đến với bậc hữu học chưa đạt được mục tiêu tâm ý. ",
  "sn17.6:2.1": "Này các Tỳ Kheo, 'bánh xe sét' là tên gọi của lợi dưỡng, cung kính và danh vọng. ",
  "sn17.6:2.2": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.6:2.3": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.6:2.4": "Thứ sáu. ",
  "sn17.7:0.1": "Kinh Tương Ưng 17.7 ",
  "sn17.7:0.2": "1. Phẩm Thứ Nhất ",
  "sn17.7:0.3": "Kinh Mũi Tên Tẩm Độc ",
  "sn17.7:1.1": "Trú tại Sāvatthī. ",
  "sn17.7:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... chướng ngại cho việc đạt đến an tịnh vô thượng. '",
  "sn17.7:1.3": "Này các Tỳ Kheo, th차차차 mũi tên tẩm độc có thể bắn xuyên qua, nhưng đừng để lợi dưỡng, cung kính và danh vọng đến với bậc hữu học chưa đạt được mục tiêu tâm ý. ",
  "sn17.7:2.1": "Này các Tỳ Kheo, 'mũi tên' là tên gọi của lợi dưỡng, cung kính và danh vọng. ",
  "sn17.7:2.2": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.7:2.3": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.7:2.4": "Thứ bảy. ",
  "sn17.8:0.1": "Kinh Tương Ưng 17.8 ",
  "sn17.8:0.2": "1. Phẩm Thứ Nhất ",
  "sn17.8:0.3": "Kinh Con Chó Rừng ",
  "sn17.8:1.1": "Trú tại Sāvatthī. ",
  "sn17.8:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... chướng ngại cho việc đạt đến an tịnh vô thượng. '",
  "sn17.8:1.3": "Này các Tỳ Kheo, các ông có nghe con chó rừng già tru vào lúc rạng sáng không?' ",
  "sn17.8:1.4": "'Thưa có, bạch Thế Tôn.' ",
  "sn17.8:1.5": "'Này các Tỳ Kheo, con chó rừng già đó mắc phải bệnh ghẻ lở, không tìm được niềm vui khi vào hang, không tìm được niềm vui khi đứng dưới gốc cây, không tìm được niềm vui khi ở ngoài trời; '",
  "sn17.8:1.6": "dù đi đâu, đứng đâu, ngồi đâu hay nằm đâu, ở đó nó đều gặp tai ương bất hạnh. ",
  "sn17.8:1.7": "Cũng vậy, này các Tỳ Kheo, ở đây có Tỳ Kheo kia bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, không tìm được niềm vui khi vào ngôi nhà trống, không tìm được niềm vui khi đứng dưới gốc cây, không tìm được niềm vui khi ở ngoài trời; ",
  "sn17.8:1.8": "dù đi đâu, đứng đâu, ngồi đâu hay nằm đâu, ở đó vị ấy đều gặp tai ương bất hạnh. ",
  "sn17.8:1.9": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.8:1.10": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.8:1.11": "Thứ tám. ",
  "sn17.9:0.1": "Kinh Tương Ưng 17.9 ",
  "sn17.9:0.2": "1. Phẩm Thứ Nhất ",
  "sn17.9:0.3": "Kinh Gió Verambha ",
  "sn17.9:1.1": "Trú tại Sāvatthī. ",
  "sn17.9:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... chướng ngại cho việc đạt đến an tịnh vô thượng. '",
  "sn17.9:1.3": "Này các Tỳ Kheo, trên bầu trời cao có những luồng gió tên là Verambha thổi. ",
  "sn17.9:1.4": "Bất cứ con chim nào bay lên đó sẽ bị gió Verambha cuốn đi. ",
  "sn17.9:1.5": "Con chim bị gió Verambha thổi văng, chân bay về một hướng, cánh bay về một hướng, đầu bay về một hướng, thân bay về một hướng khác. ",
  "sn17.9:1.6": "Cũng vậy, này các Tỳ Kheo, ở đây có Tỳ Kheo kia bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, vào buổi sáng đắp y, mang bát và y đi vào làng hay thị trấn để khất thực, với thân không được hộ trì, với miệng không được hộ trì, với tâm không được hộ trì, với niệm không được thiết lập, với các căn không được thu thúc. ",
  "sn17.9:1.7": "Vị ấy nhìn thấy người phụ nữ mặc không kín đáo hoặc không che đậy kỹ. ",
  "sn17.9:1.8": "Thấy người phụ nữ như vậy, tham dục nhiễm ô tâm vị ấy. ",
  "sn17.9:1.9": "Với tâm bị tham dục nhiễm ô, vị ấy từ bỏ học pháp, quay lại bậc hạ. ",
  "sn17.9:1.10": "Người khác mang y đi, người khác mang bát đi, người khác mang tọa cụ đi, người khác mang hộp kim may đigiống như con chim bị gió Verambha thổi văng. ",
  "sn17.9:1.11": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.9:1.12": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.9:1.13": "Thứ chín. ",
  "sn17.10:0.1": "Kinh Tương Ưng 17.10 ",
  "sn17.10:0.2": "1. Phẩm Thứ Nhất ",
  "sn17.10:0.3": "Kinh Có Kệ Ngôn ",
  "sn17.10:1.1": "Trú tại Sāvatthī. ",
  "sn17.10:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... chướng ngại cho việc đạt đến an tịnh vô thượng. '",
  "sn17.10:1.3": "Này các Tỳ Kheo, Ta thấy có người bị cung kính chinh phục, tâm bị nắm giữ hoàn toàn, sau khi thân hoại mạng chung, sinh vào cõi khổ, ác thú, đọa xứ, địa ngục. ",
  "sn17.10:1.4": "Và này các Tỳ Kheo, Ta thấy có người bị thiếu cung kính chinh phục, tâm bị nắm giữ hoàn toàn, sau khi thân hoại mạng chung, sinh vào cõi khổ, ác thú, đọa xứ, địa ngục. ",
  "sn17.10:1.5": "Và này các Tỳ Kheo, Ta thấy có người bị cả haiđược cung kính lẫn thiếu cung kínhchinh phục, tâm bị nắm giữ hoàn toàn, sau khi thân hoại mạng chung, sinh vào cõi khổ, ác thú, đọa xứ, địa ngục. ",
  "sn17.10:1.6": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.10:1.7": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.10:2.1": "Thế Tôn nói điều này. ",
  "sn17.10:2.2": "Sau khi nói điều đó, bậc Thiện Thệbậc Đạo Sưlại nói thêm: ",
  "sn17.10:3.1": "'Ai được cung kính hay không cung kính, '",
  "sn17.10:3.2": "Hay cả hai điều đó; ",
  "sn17.10:3.3": "Định của người ấy không bị dao động, ",
  "sn17.10:3.4": "Vì người ấy sống trong trạng thái vô lượng. ",
  "sn17.10:4.1": "Vị thiền định, kiên trì, ",
  "sn17.10:4.2": "Vi tế, thấy rõ bằng tuệ quán; ",
  "sn17.10:4.3": "Vui thích trong sự diệt tận chấp thủ, ",
  "sn17.10:4.4": "Được người hiền trí gọi là bậc chân nhân.' ",
  "sn17.10:4.5": "Thứ mười. ",
  "sn17.10:4.6": "Phẩm thứ nhất. ",
  "sn17.10:5.0": "Tóm lược: ",
  "sn17.10:5.1": "Tàn khốc, lưỡi câu, con rùa, ",
  "sn17.10:5.2": "Dê lông dài và con bọ phân; ",
  "sn17.10:5.3": "Tia sét, mũi tên tẩm độc, chó rừng, ",
  "sn17.10:5.4": "Gió Verambha và kinh có kệ ngôn. ",
  "sn17.11:0.1": "Kinh Tương Ưng 17.11 ",
  "sn17.11:0.2": "2. Phẩm Thứ Hai ",
  "sn17.11:0.3": "Kinh Chén Vàng ",
  "sn17.11:1.1": "Trú tại Sāvatthī. ",
  "sn17.11:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... chướng ngại cho việc đạt đến an tịnh vô thượng. '",
  "sn17.11:1.3": "Này các Tỳ Kheo, ở đây Ta biết rõ tâm của một người bằng tâm Ta: ",
  "sn17.11:1.4": "'Vị Tôn giả này sẽ không nói dối có chủ ý dù chỉ vì một chén vàng đầy bột bạc.' ",
  "sn17.11:1.5": "Sau đó Ta lại thấy vị ấy bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, đang nói dối có chủ ý. ",
  "sn17.11:1.6": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.11:1.7": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.11:1.8": "Thứ nhất. ",
  "sn17.12:0.1": "Kinh Tương Ưng 17.12 ",
  "sn17.12:0.2": "2. Phẩm Thứ Hai ",
  "sn17.12:0.3": "Kinh Chén Bạc ",
  "sn17.12:1.1": "Trú tại Sāvatthī. ",
  "sn17.12:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... '",
  "sn17.12:1.3": "Này các Tỳ Kheo, ở đây Ta biết rõ tâm của một người bằng tâm Ta: ",
  "sn17.12:1.4": "'Vị Tôn giả này sẽ không nói dối có chủ ý dù chỉ vì một chén bạc đầy bột vàng.' ",
  "sn17.12:1.5": "Sau đó Ta lại thấy vị ấy bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, đang nói dối có chủ ý. ",
  "sn17.12:1.6": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.12:1.7": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.12:1.8": "Thứ hai. ",
  "sn17.13-20:0.1": "Kinh Tương Ưng 17.13–20 ",
  "sn17.13-20:0.2": "2. Phẩm Thứ Hai ",
  "sn17.13-20:0.3": "Kinh Vàng Thoi và Bảy Kinh Kế Tiếp ",
  "sn17.13-20:1.1": "Trú tại Sāvatthī. ",
  "sn17.13-20:1.2": "'Này các Tỳ Kheo, ở đây Ta biết rõ tâm của một người bằng tâm Ta: '",
  "sn17.13-20:1.3": "'Vị Tôn giả này sẽ không nói dối có chủ ý dù chỉ vì một thỏi vàng ...pe... '",
  "sn17.13-20:1.4": "dù chỉ vì một trăm thỏi vàng... ",
  "sn17.13-20:1.5": "dù chỉ vì một thỏi vàng ròng... ",
  "sn17.13-20:1.6": "dù chỉ vì một trăm thỏi vàng ròng... ",
  "sn17.13-20:1.7": "dù chỉ vì cả mặt đất đầy vàng... ",
  "sn17.13-20:1.8": "dù chỉ vì một chút lợi lộc vật chất... ",
  "sn17.13-20:1.9": "dù chỉ vì mạng sống... ",
  "sn17.13-20:1.10": "dù chỉ vì một người đẹp nhất xứ.' ",
  "sn17.13-20:1.11": "Sau đó Ta lại thấy vị ấy bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, đang nói dối có chủ ý. ",
  "sn17.13-20:1.12": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.13-20:1.13": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.13-20:1.14": "Thứ mười. ",
  "sn17.13-20:1.15": "Phẩm thứ hai. ",
  "sn17.13-20:2.0": "Tóm lược: ",
  "sn17.13-20:2.1": "Hai chén, hai loại vàng, ",
  "sn17.13-20:2.2": "Thêm hai loại vàng ròng; ",
  "sn17.13-20:2.3": "Mặt đất, lợi lộc nhỏ, mạng sống, ",
  "sn17.13-20:2.4": "Người đẹp nhất xứmười kinh. ",
  "sn17.21:0.1": "Kinh Tương Ưng 17.21 ",
  "sn17.21:0.2": "3. Phẩm Thứ Ba ",
  "sn17.21:0.3": "Kinh Phụ Nữ ",
  "sn17.21:1.1": "Trú tại Sāvatthī. ",
  "sn17.21:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... '",
  "sn17.21:1.3": "Này các Tỳ Kheo, người phụ nữ không thể một mình chiếm đoạt tâm của một người như lợi dưỡng, cung kính và danh vọng chiếm đoạt tâm. ",
  "sn17.21:1.4": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.21:1.5": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.21:1.6": "Thứ nhất. ",
  "sn17.22:0.1": "Kinh Tương Ưng 17.22 ",
  "sn17.22:0.2": "3. Phẩm Thứ Ba ",
  "sn17.22:0.3": "Kinh Người Đẹp Nhất Xứ ",
  "sn17.22:1.1": "Trú tại Sāvatthī. ",
  "sn17.22:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... '",
  "sn17.22:1.3": "Này các Tỳ Kheo, người đẹp nhất trong xứ sở không thể một mình chiếm đoạt tâm của một người như lợi dưỡng, cung kính và danh vọng chiếm đoạt tâm. ",
  "sn17.22:1.4": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.22:1.5": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.22:1.6": "Thứ hai. ",
  "sn17.23:0.1": "Kinh Tương Ưng 17.23 ",
  "sn17.23:0.2": "3. Phẩm Thứ Ba ",
  "sn17.23:0.3": "Kinh Người Con Trai Duy Nhất ",
  "sn17.23:1.1": "Trú tại Sāvatthī. ",
  "sn17.23:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... '",
  "sn17.23:1.3": "Này các Tỳ Kheo, một nữ cư sĩ có lòng tin, khi cầu nguyện đúng đắn cho người con trai duy nhất thân yêu đáng mến của mình, có thể cầu như vầy: ",
  "sn17.23:1.4": "'Con ơi, hãy trở thành người giống như Citta gia chủ và Hatthaka người Āḷavī.' ",
  "sn17.23:1.5": "Này các Tỳ Kheo, đó là chuẩn mực, đó là thước đo đối với các nam cư sĩ đệ tử của Ta, đó là Citta gia chủ và Hatthaka người Āḷavī. ",
  "sn17.23:1.6": "Còn nếu con xuất gia từ gia đình sang đời sống không gia đình; ",
  "sn17.23:1.7": "'Con ơi, hãy trở thành người giống như Sāriputta và Moggallāna.' ",
  "sn17.23:1.8": "Này các Tỳ Kheo, đó là chuẩn mực, đó là thước đo đối với các Tỳ Kheo đệ tử của Ta, đó là Sāriputta và Moggallāna. ",
  "sn17.23:1.9": "Nhưng này con, đừng để lợi dưỡng, cung kính và danh vọng đến với bậc hữu học chưa đạt được mục tiêu tâm ý. ",
  "sn17.23:1.10": "Này các Tỳ Kheo, nếu lợi dưỡng, cung kính và danh vọng đến với vị Tỳ Kheo hữu học chưa đạt được mục tiêu tâm ý, đó sẽ là chướng ngại cho vị ấy. ",
  "sn17.23:1.11": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.23:1.12": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.23:1.13": "Thứ ba. ",
  "sn17.24:0.1": "Kinh Tương Ưng 17.24 ",
  "sn17.24:0.2": "3. Phẩm Thứ Ba ",
  "sn17.24:0.3": "Kinh Người Con Gái Duy Nhất ",
  "sn17.24:1.1": "Trú tại Sāvatthī. ",
  "sn17.24:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng ...pe... '",
  "sn17.24:1.3": "Này các Tỳ Kheo, một nữ cư sĩ có lòng tin, khi cầu nguyện đúng đắn cho người con gái duy nhất thân yêu đáng mến của mình, có thể cầu như vầy: ",
  "sn17.24:1.4": "'Con ơi, hãy trở thành người giống như Khujjuttarā nữ cư sĩ và Nandamātā ở Veḷukaṇḍaka.' ",
  "sn17.24:1.5": "Này các Tỳ Kheo, đó là chuẩn mực, đó là thước đo đối với các nữ cư sĩ đệ tử của Ta, đó là Khujjuttarā nữ cư sĩ và Nandamātā ở Veḷukaṇḍaka. ",
  "sn17.24:1.6": "Còn nếu con xuất gia từ gia đình sang đời sống không gia đình; ",
  "sn17.24:1.7": "'Con ơi, hãy trở thành người giống như Tỳ Kheo Ni Khemā và Uppalavaṇṇā.' ",
  "sn17.24:1.8": "Này các Tỳ Kheo, đó là chuẩn mực, đó là thước đo đối với các Tỳ Kheo Ni đệ tử của Ta, đó là Tỳ Kheo Ni Khemā và Uppalavaṇṇā. ",
  "sn17.24:1.9": "Nhưng này con, đừng để lợi dưỡng, cung kính và danh vọng đến với bậc hữu học chưa đạt được mục tiêu tâm ý. ",
  "sn17.24:1.10": "Này các Tỳ Kheo, nếu lợi dưỡng, cung kính và danh vọng đến với vị Tỳ Kheo Ni hữu học chưa đạt được mục tiêu tâm ý, đó sẽ là chướng ngại cho vị ấy. ",
  "sn17.24:1.11": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.24:1.12": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.24:1.13": "Thứ tư. ",
  "sn17.25:0.1": "Kinh Tương Ưng 17.25 ",
  "sn17.25:0.2": "3. Phẩm Thứ Ba ",
  "sn17.25:0.3": "Kinh Sa-môn và Bà-la-môn ",
  "sn17.25:1.1": "Trú tại Sāvatthī. ",
  "sn17.25:1.2": "'Này các Tỳ Kheo, những Sa-môn hay Bà-la-môn nào không như thật biết rõ vị ngọt, sự nguy hiểm và sự thoát ly của lợi dưỡng, cung kính và danh vọng, '",
  "sn17.25:1.3": "thì đối với Ta, này các Tỳ Kheo, họ không được xem là Sa-môn giữa các Sa-môn, không được xem là Bà-la-môn giữa các Bà-la-môn; và các Tôn giả đó trong ngay hiện tại này cũng không chứng ngộ bằng thắng trí rồi an trú trong mục đích Sa-môn hay mục đích Bà-la-môn. ",
  "sn17.25:1.4": "Còn những Sa-môn hay Bà-la-môn nào như thật biết rõ vị ngọt, sự nguy hiểm và sự thoát ly của lợi dưỡng, cung kính và danh vọng, ",
  "sn17.25:1.5": "thì đối với Ta, này các Tỳ Kheo, họ được xem là Sa-môn giữa các Sa-môn, được xem là Bà-la-môn giữa các Bà-la-môn; và các Tôn giả đó trong ngay hiện tại này chứng ngộ bằng thắng trí rồi an trú trong mục đích Sa-môn và mục đích Bà-la-môn.' ",
  "sn17.25:1.6": "Thứ năm. ",
  "sn17.26:0.1": "Kinh Tương Ưng 17.26 ",
  "sn17.26:0.2": "3. Phẩm Thứ Ba ",
  "sn17.26:0.3": "Kinh Sa-môn và Bà-la-môn (Thứ Hai) ",
  "sn17.26:1.1": "Trú tại Sāvatthī. ",
  "sn17.26:1.2": "'Này các Tỳ Kheo, những Sa-môn hay Bà-la-môn nào không như thật biết rõ sự sinh khởi, sự đoạn diệt, vị ngọt, sự nguy hiểm và sự thoát ly của lợi dưỡng, cung kính và danh vọng ...pe... '",
  "sn17.26:1.3": "biết rõ ...pe... ",
  "sn17.26:1.4": "chứng ngộ bằng thắng trí rồi an trú.' ",
  "sn17.26:1.5": "Thứ sáu. ",
  "sn17.27:0.1": "Kinh Tương Ưng 17.27 ",
  "sn17.27:0.2": "3. Phẩm Thứ Ba ",
  "sn17.27:0.3": "Kinh Sa-môn và Bà-la-môn (Thứ Ba) ",
  "sn17.27:1.1": "Trú tại Sāvatthī. ",
  "sn17.27:1.2": "'Này các Tỳ Kheo, những Sa-môn hay Bà-la-môn nào không như thật biết rõ lợi dưỡng, cung kính và danh vọng, không biết rõ sự sinh khởi của chúng, không biết rõ sự đoạn diệt của chúng, không biết rõ con đường dẫn đến sự đoạn diệt của chúng ...pe... '",
  "sn17.27:1.3": "biết rõ ...pe... ",
  "sn17.27:1.4": "chứng ngộ bằng thắng trí rồi an trú.' ",
  "sn17.27:1.5": "Thứ bảy. ",
  "sn17.28:0.1": "Kinh Tương Ưng 17.28 ",
  "sn17.28:0.2": "3. Phẩm Thứ Ba ",
  "sn17.28:0.3": "Kinh Da Thịt ",
  "sn17.28:1.1": "Trú tại Sāvatthī. ",
  "sn17.28:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc. '",
  "sn17.28:1.3": "Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng cắt qua da, cắt xong da rồi cắt qua lớp bì, cắt xong lớp bì rồi cắt qua thịt, cắt xong thịt rồi cắt qua gân, cắt xong gân rồi cắt qua xương, cắt xong xương rồi đứng chạm đến tủy xương. ",
  "sn17.28:1.4": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.28:1.5": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.28:1.6": "Thứ tám. ",
  "sn17.29:0.1": "Kinh Tương Ưng 17.29 ",
  "sn17.29:0.2": "3. Phẩm Thứ Ba ",
  "sn17.29:0.3": "Kinh Sợi Dây ",
  "sn17.29:1.1": "Trú tại Sāvatthī. ",
  "sn17.29:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc. '",
  "sn17.29:1.3": "Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng cắt qua da, cắt xong da rồi cắt qua lớp bì, cắt xong lớp bì rồi cắt qua thịt, cắt xong thịt rồi cắt qua gân, cắt xong gân rồi cắt qua xương, cắt xong xương rồi đứng chạm đến tủy xương. ",
  "sn17.29:2.1": "Ví như, này các Tỳ Kheo, một người lực lưỡng lấy sợi dây thừng bện chặt quấn quanh ống chân rồi kéo mạnh. ",
  "sn17.29:2.2": "Sợi dây đó cắt qua da, cắt xong da rồi cắt qua lớp bì, cắt xong lớp bì rồi cắt qua thịt, cắt xong thịt rồi cắt qua gân, cắt xong gân rồi cắt qua xương, cắt xong xương rồi đứng chạm đến tủy xương. ",
  "sn17.29:2.3": "Cũng vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng cắt qua da, cắt xong da rồi cắt qua lớp bì, cắt xong lớp bì rồi cắt qua thịt, cắt xong thịt rồi cắt qua gân, cắt xong gân rồi cắt qua xương, cắt xong xương rồi đứng chạm đến tủy xương. ",
  "sn17.29:2.4": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.29:2.5": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.29:2.6": "Thứ chín. ",
  "sn17.30:0.1": "Kinh Tương Ưng 17.30 ",
  "sn17.30:0.2": "3. Phẩm Thứ Ba ",
  "sn17.30:0.3": "Kinh Tỳ Kheo ",
  "sn17.30:1.1": "Trú tại Sāvatthī. ",
  "sn17.30:1.2": "'Này các Tỳ Kheo, ngay cả vị Tỳ Kheo là bậc A-la-hán lậu tận, Ta cũng nói rằng lợi dưỡng, cung kính và danh vọng là chướng ngại cho vị ấy.' ",
  "sn17.30:1.3": "Khi được nghe vậy, Tôn giả Ānanda bạch Thế Tôn: ",
  "sn17.30:1.4": "'Bạch Thế Tôn, lợi dưỡng, cung kính và danh vọng là chướng ngại cho điều gì của vị Tỳ Kheo lậu tận?' ",
  "sn17.30:1.5": "'Này Ānanda, đối với tâm giải thoát bất động của vị ấy, Ta không nói lợi dưỡng, cung kính và danh vọng là chướng ngại. '",
  "sn17.30:1.6": "Nhưng này Ānanda, đối với các lạc trú hiện tại mà vị ấy đạt được khi sống với tâm chuyên cần, nhiệt tình, quyết tâmTa nói lợi dưỡng, cung kính và danh vọng là chướng ngại cho điều đó. ",
  "sn17.30:1.7": "Như vậy, này Ānanda, lợi dưỡng, cung kính và danh vọng thật tàn khốc, gay go, thô bạo, là chướng ngại cho việc đạt đến an tịnh vô thượng thoát khỏi mọi ách phược. ",
  "sn17.30:1.8": "Do vậy, này Ānanda, cần phải học tập như sau: ",
  "sn17.30:1.9": "'Lợi dưỡng, cung kính và danh vọng đã sinh khởi, chúng ta sẽ từ bỏ; và dù đã sinh khởi, sẽ không để chúng nắm giữ tâm ta.' ",
  "sn17.30:1.10": "Này Ānanda, hãy học tập như vậy.' ",
  "sn17.30:1.11": "Thứ mười. ",
  "sn17.30:1.12": "Phẩm thứ ba. ",
  "sn17.30:2.0": "Tóm lược: ",
  "sn17.30:2.1": "Phụ nữ, người đẹp nhất xứ, ",
  "sn17.30:2.2": "Con trai và con gái duy nhất; ",
  "sn17.30:2.3": "Ba kinh về Sa-môn Bà-la-môn, ",
  "sn17.30:2.4": "Da thịt, sợi dây, và Tỳ Kheo. ",
  "sn17.31:0.1": "Kinh Tương Ưng 17.31 ",
  "sn17.31:0.2": "4. Phẩm Thứ Tư ",
  "sn17.31:0.3": "Kinh Phá Vỡ ",
  "sn17.31:1.1": "Trú tại Sāvatthī. ",
  "sn17.31:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc. '",
  "sn17.31:1.3": "Này các Tỳ Kheo, Đề Bà Đạt Đa bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, đã phá hòa hợp Tăng. ",
  "sn17.31:1.4": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.31:1.5": "Hãy học tập như vậy.' ",
  "sn17.31:1.6": "Thứ nhất. ",
  "sn17.32:0.1": "Kinh Tương Ưng 17.32 ",
  "sn17.32:0.2": "4. Phẩm Thứ Tư ",
  "sn17.32:0.3": "Kinh Thiện Căn ",
  "sn17.32:1.1": "Trú tại Sāvatthī. ",
  "sn17.32:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc. '",
  "sn17.32:1.3": "Này các Tỳ Kheo, vì Đề Bà Đạt Đa bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, thiện căn của ông ta đã bị diệt tận hoàn toàn. ",
  "sn17.32:1.4": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.32:1.5": "Hãy học tập như vậy.' ",
  "sn17.32:1.6": "Thứ hai. ",
  "sn17.33:0.1": "Kinh Tương Ưng 17.33 ",
  "sn17.33:0.2": "4. Phẩm Thứ Tư ",
  "sn17.33:0.3": "Kinh Pháp Thiện ",
  "sn17.33:1.1": "Trú tại Sāvatthī. ",
  "sn17.33:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc. '",
  "sn17.33:1.3": "Này các Tỳ Kheo, vì Đề Bà Đạt Đa bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, các thiện pháp của ông ta đã bị diệt tận hoàn toàn. ",
  "sn17.33:1.4": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.33:1.5": "Hãy học tập như vậy.' ",
  "sn17.33:1.6": "Thứ ba. ",
  "sn17.34:0.1": "Kinh Tương Ưng 17.34 ",
  "sn17.34:0.2": "4. Phẩm Thứ Tư ",
  "sn17.34:0.3": "Kinh Pháp Trong Sáng ",
  "sn17.34:1.1": "Trú tại Sāvatthī. ",
  "sn17.34:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc. '",
  "sn17.34:1.3": "Này các Tỳ Kheo, vì Đề Bà Đạt Đa bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, các pháp trong sáng của ông ta đã bị diệt tận hoàn toàn. ",
  "sn17.34:1.4": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.34:1.5": "Hãy học tập như vậy.' ",
  "sn17.34:1.6": "Thứ tư. ",
  "sn17.35:0.1": "Kinh Tương Ưng 17.35 ",
  "sn17.35:0.2": "4. Phẩm Thứ Tư ",
  "sn17.35:0.3": "Kinh Vừa Mới Rời Đi ",
  "sn17.35:1.1": "Một thời, Thế Tôn trú tại Rājagaha, trên núi Gijjhakūṭa, khi Đề Bà Đạt Đa vừa mới rời đi. ",
  "sn17.35:1.2": "Ở đó, Thế Tôn nhân đề cập đến Đề Bà Đạt Đa, gọi các Tỳ Kheo: ",
  "sn17.35:1.3": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng đã sinh khởi đến hại cho Đề Bà Đạt Đa, đã sinh khởi để hủy diệt Đề Bà Đạt Đa. '",
  "sn17.35:2.1": "Ví như, này các Tỳ Kheo, cây chuối ra trái để hại mình, ra trái để diệt mình; ",
  "sn17.35:2.2": "cũng vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng đã sinh khởi đến hại cho Đề Bà Đạt Đa, đã sinh khởi để hủy diệt Đề Bà Đạt Đa. ",
  "sn17.35:3.1": "Ví như, này các Tỳ Kheo, cây tre ra trái để hại mình, ra trái để diệt mình; ",
  "sn17.35:3.2": "cũng vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng đã sinh khởi đến hại cho Đề Bà Đạt Đa, đã sinh khởi để hủy diệt Đề Bà Đạt Đa. ",
  "sn17.35:4.1": "Ví như, này các Tỳ Kheo, cây lau ra trái để hại mình, ra trái để diệt mình; ",
  "sn17.35:4.2": "cũng vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng đã sinh khởi đến hại cho Đề Bà Đạt Đa, đã sinh khởi để hủy diệt Đề Bà Đạt Đa. ",
  "sn17.35:5.1": "Ví như, này các Tỳ Kheo, con la cái mang thai để hại mình, mang thai để diệt mình; ",
  "sn17.35:5.2": "cũng vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng đã sinh khởi đến hại cho Đề Bà Đạt Đa, đã sinh khởi để hủy diệt Đề Bà Đạt Đa. ",
  "sn17.35:5.3": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc. ",
  "sn17.35:5.4": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.35:6.1": "Thế Tôn nói điều này. ",
  "sn17.35:6.2": "Sau khi nói điều đó, bậc Thiện Thệbậc Đạo Sưlại nói thêm: ",
  "sn17.35:7.1": "'Trái làm hại cây chuối, '",
  "sn17.35:7.2": "Trái làm hại cây tre, cây lau; ",
  "sn17.35:7.3": "Cung kính làm hại kẻ xấu, ",
  "sn17.35:7.4": "Như thai làm hại con la cái.' ",
  "sn17.35:7.5": "Thứ năm. ",
  "sn17.36:0.1": "Kinh Tương Ưng 17.36 ",
  "sn17.36:0.2": "4. Phẩm Thứ Tư ",
  "sn17.36:0.3": "Kinh Năm Trăm Xe Ngựa ",
  "sn17.36:1.1": "Trú tại Rājagaha, ở Trúc Lâm, nơi nuôi dưỡng sóc. ",
  "sn17.36:1.2": "Lúc bấy giờ, thái tử Ajātasattu mỗi sáng chiều đến yết kiến Đề Bà Đạt Đa với năm trăm xe ngựa, và mang đến năm trăm nồi cơm để cúng dường thức ăn. ",
  "sn17.36:1.3": "Rồi nhiều Tỳ Kheo đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi một bên. Ngồi một bên, các Tỳ Kheo ấy bạch Thế Tôn: ",
  "sn17.36:1.4": "'Bạch Thế Tôn, thái tử Ajātasattu mỗi sáng chiều đến yết kiến Đề Bà Đạt Đa với năm trăm xe ngựa, và mang đến năm trăm nồi cơm để cúng dường thức ăn.' ",
  "sn17.36:1.5": "'Này các Tỳ Kheo, đừng thèm muốn lợi dưỡng, cung kính và danh vọng của Đề Bà Đạt Đa. '",
  "sn17.36:1.6": "Này các Tỳ Kheo, chừng nào thái tử Ajātasattu còn đến yết kiến Đề Bà Đạt Đa mỗi sáng chiều với năm trăm xe ngựa, và còn mang đến năm trăm nồi cơm để cúng dường thức ăn, thì Đề Bà Đạt Đa chỉ có thể mong đợi sự suy giảm trong các thiện pháp, không phải tăng trưởng. ",
  "sn17.36:2.1": "Ví như, này các Tỳ Kheo, nếu người ta bôi mật vào mũi con chó hung dữ, thì này các Tỳ Kheo, con chó đó sẽ trở nên hung dữ hơn; ",
  "sn17.36:2.2": "cũng vậy, này các Tỳ Kheo, chừng nào thái tử Ajātasattu còn đến yết kiến Đề Bà Đạt Đa mỗi sáng chiều với năm trăm xe ngựa, và còn mang đến năm trăm nồi cơm để cúng dường thức ăn, thì Đề Bà Đạt Đa chỉ có thể mong đợi sự suy giảm trong các thiện pháp, không phải tăng trưởng. ",
  "sn17.36:2.3": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc ...pe... ",
  "sn17.36:2.4": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.36:2.5": "Thứ sáu. ",
  "sn17.37:0.1": "Kinh Tương Ưng 17.37 ",
  "sn17.37:0.2": "4. Phẩm Thứ Tư ",
  "sn17.37:0.3": "Kinh Người Mẹ ",
  "sn17.37:1.1": "Trú tại Sāvatthī. ",
  "sn17.37:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc, gay go, thô bạo, là chướng ngại cho việc đạt đến an tịnh vô thượng thoát khỏi mọi ách phược. '",
  "sn17.37:1.3": "Này các Tỳ Kheo, ở đây Ta biết rõ tâm của một người bằng tâm Ta: ",
  "sn17.37:1.4": "'Vị Tôn giả này sẽ không nói dối có chủ ý dù chỉ vì lợi ích của người mẹ.' ",
  "sn17.37:1.5": "Sau đó Ta lại thấy vị ấy bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, đang nói dối có chủ ý. ",
  "sn17.37:1.6": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc, gay go, thô bạo, là chướng ngại cho việc đạt đến an tịnh vô thượng thoát khỏi mọi ách phược. ",
  "sn17.37:1.7": "Do vậy, này các Tỳ Kheo, cần phải học tập như sau: ",
  "sn17.37:1.8": "'Lợi dưỡng, cung kính và danh vọng đã sinh khởi, chúng ta sẽ từ bỏ. '",
  "sn17.37:1.9": "Và dù đã sinh khởi, sẽ không để chúng nắm giữ tâm ta.' ",
  "sn17.37:1.10": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.37:1.11": "Thứ bảy. ",
  "sn17.38-43:0.1": "Kinh Tương Ưng 17.38–43 ",
  "sn17.38-43:0.2": "4. Phẩm Thứ Tư ",
  "sn17.38-43:0.3": "Kinh Người Cha và Năm Kinh Kế Tiếp ",
  "sn17.38-43:1.1": "Trú tại Sāvatthī. ",
  "sn17.38-43:1.2": "'Này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc, gay go, thô bạo, là chướng ngại cho việc đạt đến an tịnh vô thượng thoát khỏi mọi ách phược. '",
  "sn17.38-43:1.3": "Này các Tỳ Kheo, ở đây Ta biết rõ tâm của một người bằng tâm Ta: ",
  "sn17.38-43:1.4": "'Vị Tôn giả này sẽ không nói dối có chủ ý dù chỉ vì lợi ích của người cha ...pe... '",
  "sn17.38-43:1.5": "(cần trình bày đầy đủ)... ",
  "sn17.38-43:1.6": "dù chỉ vì lợi ích của người anh/em trai... ",
  "sn17.38-43:1.7": "dù chỉ vì lợi ích của người chị/em gái... ",
  "sn17.38-43:1.8": "dù chỉ vì lợi ích của người con trai... ",
  "sn17.38-43:1.9": "dù chỉ vì lợi ích của người con gái... ",
  "sn17.38-43:1.10": "dù chỉ vì lợi ích của người vợ.' ",
  "sn17.38-43:1.11": "Sau đó Ta lại thấy vị ấy bị lợi dưỡng, cung kính và danh vọng chinh phục, tâm bị nắm giữ hoàn toàn, đang nói dối có chủ ý. ",
  "sn17.38-43:1.12": "Như vậy, này các Tỳ Kheo, lợi dưỡng, cung kính và danh vọng thật tàn khốc, gay go, thô bạo, là chướng ngại cho việc đạt đến an tịnh vô thượng thoát khỏi mọi ách phược. ",
  "sn17.38-43:1.13": "Do vậy, này các Tỳ Kheo, cần phải học tập như sau: ",
  "sn17.38-43:1.14": "'Lợi dưỡng, cung kính và danh vọng đã sinh khởi, chúng ta sẽ từ bỏ; và dù đã sinh khởi, sẽ không để chúng nắm giữ tâm ta.' ",
  "sn17.38-43:1.15": "Này các Tỳ Kheo, hãy học tập như vậy.' ",
  "sn17.38-43:1.16": "Thứ mười ba. ",
  "sn17.38-43:1.17": "Phẩm thứ tư. ",
  "sn17.38-43:2.0": "Tóm lược: ",
  "sn17.38-43:2.1": "Phá vỡ, thiện căn, hai pháp, ",
  "sn17.38-43:2.2": "Vừa rời đi, xe ngựa, người mẹ; ",
  "sn17.38-43:2.3": "Cha, anh em trai và chị em gái, ",
  "sn17.38-43:2.4": "Con trai, con gái, người vợ. ",
  "sn17.38-43:2.5": "Tương Ưng Lợi Dưỡng và Cung Kính hoàn tất. "
}
window.BILARA["sn17_v1"]["vi"]["sn17_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
