window.BILARA = window.BILARA || {};
window.BILARA["sn1_v1"] = window.BILARA["sn1_v1"] || {};
window.BILARA["sn1_v1"]["vi"] = {
  "sn1.1:0.1": "Tương Ưng Bộ Kinh 1.1",
  "sn1.1:0.2": "1. Phẩm Lau Sậy ",
  "sn1.1:0.3": "Kinh Vượt Bộc Lưu ",
  "sn1.1:1.1": "Tôi nghe như vầy",
  "sn1.1:1.2": "Một thời đức Thế Tôn trú tại Sāvatthi, Jetavana, tinh xá của Anāthapiṇḍika (Cấp Cô Độc). ",
  "sn1.1:1.3": "Khi ấy, một vị thiên thần vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Jetavana, đến chỗ Thế Tôn; sau khi đến, cúi đầu đảnh lễ Thế Tôn rồi đứng sang một bên. Đứng sang một bên, vị thiên thần ấy bạch Thế Tôn rằng: ",
  "sn1.1:1.4": "'Thưa Hiền Giả, Ngài đã vượt qua bộc lưu như thế nào?' ",
  "sn1.1:1.5": "'Này Hiền Giả, không dừng lại, không bơi vội, ta đã vượt qua bộc lưu.' ",
  "sn1.1:1.6": "'Thưa Hiền Giả, làm thế nào mà không dừng lại, không bơi vội, Ngài lại vượt qua bộc lưu?' ",
  "sn1.1:1.7": "'Này Hiền Giả, khi ta dừng lại thì ta chìm xuống; '",
  "sn1.1:1.8": "khi ta bơi vội thì ta bị cuốn trôi. ",
  "sn1.1:1.9": "Như vậy, này Hiền Giả, không dừng lại, không bơi vội, ta đã vượt qua bộc lưu.' ",
  "sn1.1:2.1": "'Sau bao lâu mới thấy, '",
  "sn1.1:2.2": "Người có tâm trí hoàn toàn thanh tịnh, vắng lặng phiền não",
  "sn1.1:2.3": "Không dừng lại, không bơi vội, ",
  "sn1.1:2.4": "đã vượt qua sự chấp thủ ở đời.' ",
  "sn1.1:3.1": "Vị thiên thần ấy đã nói như vậy. ",
  "sn1.1:3.2": "Bậc Đạo Sư tỏ vẻ hài lòng. ",
  "sn1.1:3.3": "Khi ấy vị thiên thần nghĩ: ",
  "sn1.1:3.4": "'Bậc Đạo Sư đã hài lòng với ta,' rồi cúi đầu đảnh lễ Thế Tôn, đi nhiễu theo bên phải, và biến mất ngay tại chỗ. ",
  "sn1.2:0.1": "Tương Ưng Bộ Kinh 1.2 ",
  "sn1.2:0.2": "1. Phẩm Lau Sậy ",
  "sn1.2:0.3": "Kinh Giải Thoát ",
  "sn1.2:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.2:1.2": "Đứng sang một bên, vị thiên thần ấy đọc bài kệ này trước Thế Tôn: ",
  "sn1.2:2.1": "'Thưa hiền giả, Ngài có biết không  sự thoát ly, sự giải thoát, sự viễn ly của các chúng sinh?' ",
  "sn1.2:3.1": "'Này hiền giả, ta có biết  sự thoát ly, sự giải thoát, sự viễn ly của các chúng sinh.' ",
  "sn1.2:4.1": "'Thưa hiền giả, làm thế nào mà Ngài biết sự thoát ly, sự giải thoát, sự viễn ly của các chúng sinh?' ",
  "sn1.2:5.1": "'Do sự diệt tận hỷ ái và sự hiện hữu, '",
  "sn1.2:5.2": "Do sự đoạn diệt tưởng và thức; ",
  "sn1.2:5.3": "Do sự diệt và an tịnh của các cảm thọ, ",
  "sn1.2:5.4": "Như vậy, này hiền giả, ta biết; ",
  "sn1.2:5.5": "Sự thoát ly, sự giải thoát, sự viễn ly của các chúng sinh.' ",
  "sn1.3:0.1": "Tương Ưng Bộ Kinh 1.3 ",
  "sn1.3:0.2": "1. Phẩm Lau Sậy ",
  "sn1.3:0.3": "Kinh Bị Dẫn Đến ",
  "sn1.3:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.3:1.2": "Đứng sang một bên, vị thiên thần ấy đọc bài kệ này trước Thế Tôn: ",
  "sn1.3:2.1": "'Đời sống bị dẫn đến, tuổi thọ ngắn ngủi, '",
  "sn1.3:2.2": "Kẻ bị dẫn đến bởi tuổi già, không có nơi nương tựa; ",
  "sn1.3:2.3": "Thấy sự sợ hãi này trong cái chết, ",
  "sn1.3:2.4": "Hãy làm các phước đức, mang lại hạnh phúc.' ",
  "sn1.3:3.1": "'Đời sống bị dẫn đến, tuổi thọ ngắn ngủi, '",
  "sn1.3:3.2": "Kẻ bị dẫn đến bởi tuổi già, không có nơi nương tựa; ",
  "sn1.3:3.3": "Thấy sự sợ hãi này trong cái chết, ",
  "sn1.3:3.4": "Hãy từ bỏ mồi đời, hướng đến an tịnh.' ",
  "sn1.4:0.1": "Tương Ưng Bộ Kinh 1.4 ",
  "sn1.4:0.2": "1. Phẩm Lau Sậy ",
  "sn1.4:0.3": "Kinh Thời Gian Qua Đi ",
  "sn1.4:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.4:1.2": "Đứng sang một bên, vị thiên thần ấy đọc bài kệ này trước Thế Tôn: ",
  "sn1.4:2.1": "'Thời gian trôi qua, đêm ngày lướt qua, '",
  "sn1.4:2.2": "Tuổi thanh xuân lần lượt rời bỏ; ",
  "sn1.4:2.3": "Thấy sự sợ hãi này trong cái chết, ",
  "sn1.4:2.4": "Hãy làm các phước đức, mang lại hạnh phúc.' ",
  "sn1.4:3.1": "'Thời gian trôi qua, đêm ngày lướt qua, '",
  "sn1.4:3.2": "Tuổi thanh xuân lần lượt rời bỏ; ",
  "sn1.4:3.3": "Thấy sự sợ hãi này trong cái chết, ",
  "sn1.4:3.4": "Hãy từ bỏ mồi đời, hướng đến an tịnh.' ",
  "sn1.5:0.1": "Tương Ưng Bộ Kinh 1.5 ",
  "sn1.5:0.2": "1. Phẩm Lau Sậy ",
  "sn1.5:0.3": "Kinh Bao Nhiêu Thứ Phải Đoạn ",
  "sn1.5:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.5:1.2": "Đứng sang một bên, vị thiên thần ấy đọc bài kệ này trước Thế Tôn: ",
  "sn1.5:2.1": "'Bao nhiêu thứ phải chặt đứt, bao nhiêu thứ phải từ bỏ, '",
  "sn1.5:2.2": "Bao nhiêu thứ cần thêm tu tập; ",
  "sn1.5:2.3": "Tỳ Kheo vượt qua bao nhiêu buộc ràng, ",
  "sn1.5:2.4": "Được gọi là đã vượt qua bộc lưu?' ",
  "sn1.5:3.1": "'Năm thứ phải chặt đứt, năm thứ phải từ bỏ, '",
  "sn1.5:3.2": "Năm thứ cần thêm tu tập; ",
  "sn1.5:3.3": "Tỳ Kheo vượt qua năm buộc ràng, ",
  "sn1.5:3.4": "Được gọi là đã vượt qua bộc lưu.' ",
  "sn1.6:0.1": "Tương Ưng Bộ Kinh 1.6 ",
  "sn1.6:0.2": "1. Phẩm Lau Sậy ",
  "sn1.6:0.3": "Kinh Thức Giấc ",
  "sn1.6:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.6:1.2": "Đứng sang một bên, vị thiên thần ấy đọc bài kệ này trước Thế Tôn: ",
  "sn1.6:2.1": "'Bao nhiêu thứ ngủ trong khi thức giấc, '",
  "sn1.6:2.2": "Bao nhiêu thứ thức giấc trong khi ngủ; ",
  "sn1.6:2.3": "Do bao nhiêu thứ mà nhiễm bụi trần, ",
  "sn1.6:2.4": "Do bao nhiêu thứ mà được thanh tịnh?' ",
  "sn1.6:3.1": "'Năm thứ ngủ trong khi thức giấc, '",
  "sn1.6:3.2": "Năm thứ thức giấc trong khi ngủ; ",
  "sn1.6:3.3": "Do năm thứ mà nhiễm bụi trần, ",
  "sn1.6:3.4": "Do năm thứ mà được thanh tịnh.' ",
  "sn1.7:0.1": "Tương Ưng Bộ Kinh 1.7 ",
  "sn1.7:0.2": "1. Phẩm Lau Sậy ",
  "sn1.7:0.3": "Kinh Không Thấu Triệt ",
  "sn1.7:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.7:1.2": "Đứng sang một bên, vị thiên thần ấy đọc bài kệ này trước Thế Tôn: ",
  "sn1.7:2.1": "'Những ai không thấu triệt được Pháp, '",
  "sn1.7:2.2": "Bị dẫn dắt theo các quan điểm của người khác; ",
  "sn1.7:2.3": "Họ ngủ mê mà không tỉnh thức được, ",
  "sn1.7:2.4": "Đã đến lúc họ cần thức dậy.' ",
  "sn1.7:3.1": "'Những ai đã thấu triệt Pháp rõ ràng, '",
  "sn1.7:3.2": "Không bị dẫn dắt theo quan điểm của người khác; ",
  "sn1.7:3.3": "Họ đã giác ngộ, biết rõ đúng đắn, ",
  "sn1.7:3.4": "Bước đi bình thản trên con đường gập ghềnh.' ",
  "sn1.8:0.1": "Tương Ưng Bộ Kinh 1.8 ",
  "sn1.8:0.2": "1. Phẩm Lau Sậy ",
  "sn1.8:0.3": "Kinh Bị Quên Lãng Sâu Xa ",
  "sn1.8:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.8:1.2": "Đứng sang một bên, vị thiên thần ấy đọc bài kệ này trước Thế Tôn: ",
  "sn1.8:2.1": "'Những ai bị lãng quên sâu xa về Pháp, '",
  "sn1.8:2.2": "Bị dẫn dắt theo các quan điểm của người khác; ",
  "sn1.8:2.3": "Họ ngủ mê mà không tỉnh thức được, ",
  "sn1.8:2.4": "Đã đến lúc họ cần thức dậy.' ",
  "sn1.8:3.1": "'Những ai không bị lãng quên về Pháp, '",
  "sn1.8:3.2": "Không bị dẫn dắt theo quan điểm của người khác; ",
  "sn1.8:3.3": "Họ đã giác ngộ, biết rõ đúng đắn, ",
  "sn1.8:3.4": "Bước đi bình thản trên con đường gập ghềnh.' ",
  "sn1.9:0.1": "Tương Ưng Bộ Kinh 1.9 ",
  "sn1.9:0.2": "1. Phẩm Lau Sậy ",
  "sn1.9:0.3": "Kinh Ưa Ngã Mạn ",
  "sn1.9:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.9:1.2": "Đứng sang một bên, vị thiên thần ấy đọc bài kệ này trước Thế Tôn: ",
  "sn1.9:2.1": "'Đối với kẻ ưa ngã mạn, không có sự điều phục ở đây, '",
  "sn1.9:2.2": "Không có sự tịch mặc đối với kẻ tâm không tập trung; ",
  "sn1.9:2.3": "Sống một mình trong rừng mà phóng dật, ",
  "sn1.9:2.4": "Không thể vượt qua lĩnh vực của thần chết.' ",
  "sn1.9:3.1": "'Sau khi từ bỏ ngã mạn, với tự ngã khéo định tĩnh, '",
  "sn1.9:3.2": "Tâm trong sáng, hoàn toàn giải thoát ở mọi phương; ",
  "sn1.9:3.3": "Sống một mình trong rừng, không phóng dật, ",
  "sn1.9:3.4": "Vị ấy có thể vượt qua lĩnh vực của thần chết.' ",
  "sn1.10:0.1": "Tương Ưng Bộ Kinh 1.10 ",
  "sn1.10:0.2": "1. Phẩm Lau Sậy ",
  "sn1.10:0.3": "Kinh Trong Rừng ",
  "sn1.10:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.10:1.2": "Đứng sang một bên, vị thiên thần ấy nói với Thế Tôn bằng bài kệ: ",
  "sn1.10:2.1": "'Những vị đang sống trong rừng, '",
  "sn1.10:2.2": "Tịch tịnh, sống đời phạm hạnh; ",
  "sn1.10:2.3": "Ăn mỗi ngày một bữa, ",
  "sn1.10:2.4": "Sao diện mạo họ lại trong sáng vậy?' ",
  "sn1.10:3.1": "'Họ không sầu muộn về quá khứ, '",
  "sn1.10:3.2": "Không mong ngóng về tương lai; ",
  "sn1.10:3.3": "Sống với hiện tại đang có, ",
  "sn1.10:3.4": "Do đó diện mạo họ trong sáng. ",
  "sn1.10:4.1": "Do mong ngóng tương lai, ",
  "sn1.10:4.2": "Do sầu muộn về quá khứ; ",
  "sn1.10:4.3": "Những kẻ ngu vì vậy mà khô héo, ",
  "sn1.10:4.4": "Như lau sậy xanh bị cắt đứt.' ",
  "sn1.10:4.5": "Phẩm Lau Sậy, thứ nhất. ",
  "sn1.10:5.0": "Tóm lược phẩm này ",
  "sn1.10:5.1": "Bộc lưu, giải thoát, bị dẫn đến, ",
  "sn1.10:5.2": "Thời gian qua đi, bao nhiêu thứ phải chặt; ",
  "sn1.10:5.3": "Thức giấc, không thấu triệt, ",
  "sn1.10:5.4": "Bị quên lãng, ưa ngã mạn; ",
  "sn1.10:5.5": "Trong rừng là bài thứ mười, ",
  "sn1.10:5.6": "Do đó phẩm này được gọi tên. ",
  "sn1.11:0.1": "Tương Ưng Bộ Kinh 1.11 ",
  "sn1.11:0.2": "2. Phẩm Hoan Lạc ",
  "sn1.11:0.3": "Kinh Vườn Nandana ",
  "sn1.11:1.1": "Tôi nghe như vầy",
  "sn1.11:1.2": "một thời Thế Tôn trú tại Sāvatthi, Jetavana, tinh xá của Anāthapiṇḍika. ",
  "sn1.11:1.3": "Tại đó, Thế Tôn gọi các Tỳ Kheo: ",
  "sn1.11:1.4": "'Này các Tỳ Kheo!' ",
  "sn1.11:1.5": "'Bạch Thế Tôn!' Các Tỳ Kheo ấy đáp lại Thế Tôn. ",
  "sn1.11:1.6": "Thế Tôn dạy: ",
  "sn1.11:2.1": "'Này các Tỳ Kheo, thuở xưa, một vị thiên thần thuộc cõi trời Ba Mươi Ba, đang vui chơi trong vườn Nandana, được các tiên nữ vây quanh, thụ hưởng đầy đủ năm loại dục lạc cõi trời, vào lúc ấy đọc bài kệ này: '",
  "sn1.11:3.1": "'Những ai không thấy vườn Nandana, '",
  "sn1.11:3.2": "Họ không biết an lạc là gì; ",
  "sn1.11:3.3": "Là nơi trú ngụ của các thiên thần, ",
  "sn1.11:3.4": "Của các vị trời Ba Mươi Ba danh tiếng.' ",
  "sn1.11:4.1": "Khi được nói vậy, này các Tỳ Kheo, một vị thiên thần khác đã đáp lại bằng bài kệ: ",
  "sn1.11:5.1": "'Này kẻ ngu, ngươi không hiểu được, '",
  "sn1.11:5.2": "Lời nói của các bậc A-la-hán; ",
  "sn1.11:5.3": "Các hành là vô thường, ",
  "sn1.11:5.4": "Có bản chất sanh diệt; ",
  "sn1.11:5.5": "Sau khi sanh, thì diệt, ",
  "sn1.11:5.6": "Sự vắng lặng của chúng là an lạc.'' ",
  "sn1.12:0.1": "Tương Ưng Bộ Kinh 1.12 ",
  "sn1.12:0.2": "2. Phẩm Hoan Lạc ",
  "sn1.12:0.3": "Kinh Hoan Hỷ ",
  "sn1.12:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.12:1.2": "Đứng sang một bên, vị thiên thần ấy đọc bài kệ này trước Thế Tôn: ",
  "sn1.12:2.1": "'Người có con vui mừng vì con, '",
  "sn1.12:2.2": "Người có bò cũng vui mừng vì bò như vậy; ",
  "sn1.12:2.3": "Con người vui mừng vì chỗ nương tựa, ",
  "sn1.12:2.4": "Người không còn nương tựa thì không vui mừng.' ",
  "sn1.12:3.1": "'Người có con sầu khổ vì con, '",
  "sn1.12:3.2": "Người có bò cũng sầu khổ vì bò như vậy; ",
  "sn1.12:3.3": "Con người sầu khổ vì chỗ nương tựa, ",
  "sn1.12:3.4": "Người không còn nương tựa thì không sầu khổ.' ",
  "sn1.13:0.1": "Tương Ưng Bộ Kinh 1.13 ",
  "sn1.13:0.2": "2. Phẩm Hoan Lạc ",
  "sn1.13:0.3": "Kinh Không Gì Bằng Con ",
  "sn1.13:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.13:1.2": "Đứng sang một bên, vị thiên thần ấy đọc bài kệ này trước Thế Tôn: ",
  "sn1.13:2.1": "'Không có tình yêu nào bằng tình yêu con, '",
  "sn1.13:2.2": "Không có tài sản nào bằng bầy bò; ",
  "sn1.13:2.3": "Không có ánh sáng nào bằng mặt trời, ",
  "sn1.13:2.4": "Các hồ nước, biển cả là trên hết.' ",
  "sn1.13:3.1": "'Không có tình yêu nào bằng tình yêu bản thân, '",
  "sn1.13:3.2": "Không có tài sản nào bằng lúa thóc; ",
  "sn1.13:3.3": "Không có ánh sáng nào bằng trí tuệ, ",
  "sn1.13:3.4": "Mưa là trên hết trong các hồ nước.' ",
  "sn1.14:0.1": "Tương Ưng Bộ Kinh 1.14 ",
  "sn1.14:0.2": "2. Phẩm Hoan Lạc ",
  "sn1.14:0.3": "Kinh Vua Sát-đế-lợi ",
  "sn1.14:1.1": "'Vua Sát-đế-lợi là tối thắng trong loài hai chân, '",
  "sn1.14:1.2": "Bò đực là tối thắng trong loài bốn chân; ",
  "sn1.14:1.3": "Người vợ được cưới còn trinh là tốt nhất, ",
  "sn1.14:1.4": "Con cả là trên hết trong các người con.' ",
  "sn1.14:2.1": "'Đức Phật Chánh Đẳng Giác là tối thắng trong loài hai chân, '",
  "sn1.14:2.2": "Con ngựa thuần chủng là tối thắng trong loài bốn chân; ",
  "sn1.14:2.3": "Người vợ vâng lời là tốt nhất, ",
  "sn1.14:2.4": "Con hiếu thuận là trên hết trong các người con.' ",
  "sn1.15:0.1": "Tương Ưng Bộ Kinh 1.15 ",
  "sn1.15:0.2": "2. Phẩm Hoan Lạc ",
  "sn1.15:0.3": "Kinh Rừng Rào Rào ",
  "sn1.15:1.1": "'Vào lúc giữa trưa đứng bóng, '",
  "sn1.15:1.2": "Khi chim chóc đã nghỉ ngơi im lặng; ",
  "sn1.15:1.3": "Rừng rộng lớn rào rào tiếng gió, ",
  "sn1.15:1.4": "Ta cảm thấy sợ hãi trước cảnh này.' ",
  "sn1.15:2.1": "'Vào lúc giữa trưa đứng bóng, '",
  "sn1.15:2.2": "Khi chim chóc đã nghỉ ngơi im lặng; ",
  "sn1.15:2.3": "Rừng rộng lớn rào rào tiếng gió, ",
  "sn1.15:2.4": "Ta cảm thấy thích thú trước cảnh này.' ",
  "sn1.16:0.1": "Tương Ưng Bộ Kinh 1.16 ",
  "sn1.16:0.2": "2. Phẩm Hoan Lạc ",
  "sn1.16:0.3": "Kinh Buồn Ngủ Lười Biếng ",
  "sn1.16:1.1": "'Buồn ngủ, lười biếng, ngáp vặt, '",
  "sn1.16:1.2": "Chán nản, no nê sau bữa ăn; ",
  "sn1.16:1.3": "Vì những thứ này mà không hiển lộ được, ",
  "sn1.16:1.4": "Thánh đạo đối với các chúng sinh ở đây.' ",
  "sn1.16:2.1": "'Buồn ngủ, lười biếng, ngáp vặt, '",
  "sn1.16:2.2": "Chán nản, no nê sau bữa ăn; ",
  "sn1.16:2.3": "Dùng tinh tấn mà xua đuổi chúng, ",
  "sn1.16:2.4": "Thánh đạo trở nên thanh tịnh.' ",
  "sn1.17:0.1": "Tương Ưng Bộ Kinh 1.17 ",
  "sn1.17:0.2": "2. Phẩm Hoan Lạc ",
  "sn1.17:0.3": "Kinh Khó Làm ",
  "sn1.17:1.1": "'Khó làm và khó chịu đựng, '",
  "sn1.17:1.2": "Đời sống tu hành đối với kẻ chưa khéo; ",
  "sn1.17:1.3": "Tại đó có nhiều chướng ngại, ",
  "sn1.17:1.4": "Nơi kẻ ngu bị chìm đắm.' ",
  "sn1.17:2.1": "'Bao lâu mà hành trì tu hành, '",
  "sn1.17:2.2": "Nếu tâm không kiềm chế; ",
  "sn1.17:2.3": "Từng bước từng bước sẽ chìm, ",
  "sn1.17:2.4": "Bị chi phối bởi các suy nghĩ tà vạy.",
  "sn1.17:3.1": "Như con rùa thu các chi vào trong mai, ",
  "sn1.17:3.2": "Tỳ Kheo thu các suy nghĩ của tâm vào trong; ",
  "sn1.17:3.3": "Không nương tựa, không quấy nhiễu người khác, ",
  "sn1.17:3.4": "Đã viên tịch hoàn toàn  không nên trách cứ ai.' ",
  "sn1.18:0.1": "Tương Ưng Bộ Kinh 1.18 ",
  "sn1.18:0.2": "2. Phẩm Hoan Lạc ",
  "sn1.18:0.3": "Kinh Tàm Quý ",
  "sn1.18:1.1": "'Người bị kiềm chế bởi tàm quý, '",
  "sn1.18:1.2": "Có chăng một ai trong đời; ",
  "sn1.18:1.3": "Người tránh xa sự phê phán, ",
  "sn1.18:1.4": "Như ngựa tốt tránh roi.' ",
  "sn1.18:2.1": "'Những ai luôn luôn chánh niệm, '",
  "sn1.18:2.2": "Được kiềm chế bởi tàm quý và sống tiết chế; ",
  "sn1.18:2.3": "Đạt đến cùng tận của khổ đau, ",
  "sn1.18:2.4": "Bước đi bình thản trên con đường gập ghềnh.' ",
  "sn1.19:0.1": "Tương Ưng Bộ Kinh 1.19 ",
  "sn1.19:0.2": "2. Phẩm Hoan Lạc ",
  "sn1.19:0.3": "Kinh Túp Lều ",
  "sn1.19:1.1": "'Ngài không có túp lều chăng, '",
  "sn1.19:1.2": "Ngài không có tổ ấm chăng; ",
  "sn1.19:1.3": "Ngài không có dây leo chăng, ",
  "sn1.19:1.4": "Ngài đã thoát khỏi trói buộc chăng?' ",
  "sn1.19:2.1": "'Thật vậy, ta không có túp lều, '",
  "sn1.19:2.2": "Thật vậy, ta không có tổ ấm; ",
  "sn1.19:2.3": "Thật vậy, ta không có dây leo, ",
  "sn1.19:2.4": "Thật vậy, ta đã thoát khỏi trói buộc.' ",
  "sn1.19:3.1": "'Ta gọi cái gì là túp lều của ngươi, '",
  "sn1.19:3.2": "Ta gọi cái gì là tổ ấm của ngươi; ",
  "sn1.19:3.3": "Ta gọi cái gì là dây leo của ngươi, ",
  "sn1.19:3.4": "Ta gọi cái gì là trói buộc của ngươi?' ",
  "sn1.19:4.1": "'Ngươi gọi mẹ là túp lều, '",
  "sn1.19:4.2": "Ngươi gọi vợ là tổ ấm; ",
  "sn1.19:4.3": "Ngươi gọi con là dây leo, ",
  "sn1.19:4.4": "Ngươi gọi tham ái là trói buộc của ta.' ",
  "sn1.19:5.1": "'Lành thay, ngươi không có túp lều, '",
  "sn1.19:5.2": "Lành thay, ngươi không có tổ ấm; ",
  "sn1.19:5.3": "Lành thay, ngươi không có dây leo, ",
  "sn1.19:5.4": "Lành thay, ngươi đã thoát khỏi trói buộc.' ",
  "sn1.20:0.1": "Tương Ưng Bộ Kinh 1.20 ",
  "sn1.20:0.2": "2. Phẩm Hoan Lạc ",
  "sn1.20:0.3": "Kinh Samiddhi ",
  "sn1.20:1.1": "Tôi nghe như vầy",
  "sn1.20:1.2": "một thời Thế Tôn trú tại Rājagaha, Tapodārāma. ",
  "sn1.20:1.3": "Khi ấy, Tôn giả Samiddhi vào lúc gần sáng, thức dậy đi đến suối nước nóng Tapodā để tắm. ",
  "sn1.20:1.4": "Sau khi tắm ở Tapodā xong, bước lên bờ, mặc một chiếc y, đứng để cho khô ráo thân mình. ",
  "sn1.20:1.5": "Khi ấy, một vị thiên thần vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Tapodā, đến chỗ Tôn giả Samiddhi; sau khi đến, đứng trên hư không, đọc bài kệ này trước Tôn giả Samiddhi: ",
  "sn1.20:2.1": "'Khi chưa thọ hưởng, Tỳ Kheo lại đi khất thực, '",
  "sn1.20:2.2": "Không phải sau khi thọ hưởng rồi mới đi khất thực; ",
  "sn1.20:2.3": "Hỡi Tỳ Kheo, hãy thọ hưởng rồi mới đi khất thực, ",
  "sn1.20:2.4": "Chớ để thời gian qua đi mà không kịp.' ",
  "sn1.20:3.1": "'Ta không biết thời gian, '",
  "sn1.20:3.2": "Thời gian bị che khuất, không thấy được; ",
  "sn1.20:3.3": "Do đó khi chưa thọ hưởng, ta đi khất thực, ",
  "sn1.20:3.4": "Chớ để thời gian qua đi mà không kịp.' ",
  "sn1.20:4.1": "Khi ấy vị thiên thần đứng xuống đất, bạch Tôn giả Samiddhi rằng: ",
  "sn1.20:4.2": "'Này Tỳ Kheo, Ngài còn trẻ, xuất gia, với mái tóc đen huyền, tươi trẻ, trong giai đoạn đầu của tuổi thanh xuân, chưa từng vui chơi với các dục lạc. '",
  "sn1.20:4.3": "Hỡi Tỳ Kheo, hãy thọ hưởng dục lạc của con người; ",
  "sn1.20:4.4": "Đừng từ bỏ hiện tại để chạy theo tương lai.' ",
  "sn1.20:5.1": "'Này hiền giả, ta không từ bỏ hiện tại để chạy theo tương lai. '",
  "sn1.20:5.2": "Này hiền giả, ta từ bỏ tương lai để chạy theo hiện tại. ",
  "sn1.20:5.3": "Này hiền giả, các dục lạc được Thế Tôn dạy là thuộc về tương lai, nhiều khổ đau, nhiều ưu não; và nguy hiểm ở đây còn nhiều hơn. ",
  "sn1.20:5.4": "Pháp này là hiện tại, không bị thời gian chi phối, mời đến để thấy, hướng thượng, được người trí tự mình chứng nghiệm.' ",
  "sn1.20:6.1": "'Này Tỳ Kheo, thế nào là các dục lạc được Thế Tôn dạy là thuộc về tương lai, nhiều khổ đau, nhiều ưu não, và nguy hiểm ở đây còn nhiều hơn? '",
  "sn1.20:6.2": "Thế nào là Pháp hiện tại, không bị thời gian chi phối, mời đến để thấy, hướng thượng, được người trí tự mình chứng nghiệm?' ",
  "sn1.20:7.1": "'Này hiền giả, ta mới xuất gia, chưa bao lâu mới đến học Pháp và Luật này. '",
  "sn1.20:7.2": "Ta không thể giải thích rộng rãi. ",
  "sn1.20:7.3": "Đây là Thế Tôn, bậc A-la-hán, Chánh Đẳng Giác đang trú tại Rājagaha, Tapodārāma. ",
  "sn1.20:7.4": "Hãy đến gặp Thế Tôn và hỏi về điều này. ",
  "sn1.20:7.5": "Như Thế Tôn giải thích thế nào, hãy ghi nhớ như vậy.' ",
  "sn1.20:8.1": "'Này Tỳ Kheo, Thế Tôn không dễ gì đến gặp được bởi chúng ta, vì Ngài được bao quanh bởi các vị thiên thần quyền năng khác. '",
  "sn1.20:8.2": "Nếu Ngài đến gặp Thế Tôn và hỏi về điều này, chúng ta cũng sẽ đến để nghe Pháp.' ",
  "sn1.20:8.3": "'Vâng, hiền giả.' Tôn giả Samiddhi nhận lời vị thiên thần ấy, rồi đến chỗ Thế Tôn; sau khi đến, cúi đầu đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Samiddhi bạch Thế Tôn rằng: ",
  "sn1.20:9.1": "'Bạch Thế Tôn, ở đây con vào lúc gần sáng, thức dậy đi đến suối nước nóng Tapodā để tắm. '",
  "sn1.20:9.2": "Sau khi tắm ở Tapodā xong, bước lên bờ, mặc một chiếc y, đứng để cho khô ráo thân mình. ",
  "sn1.20:9.3": "Khi ấy, bạch Thế Tôn, một vị thiên thần vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Tapodā, đến chỗ con; sau khi đến, đứng trên hư không, đọc bài kệ này: ",
  "sn1.20:10.1": "'Khi chưa thọ hưởng, Tỳ Kheo lại đi khất thực, '",
  "sn1.20:10.2": "Không phải sau khi thọ hưởng rồi mới đi khất thực; ",
  "sn1.20:10.3": "Hỡi Tỳ Kheo, hãy thọ hưởng rồi mới đi khất thực, ",
  "sn1.20:10.4": "Chớ để thời gian qua đi mà không kịp.' ",
  "sn1.20:11.1": "Khi được nói vậy, bạch Thế Tôn, con đã đáp lại vị thiên thần ấy bằng bài kệ: ",
  "sn1.20:12.1": "'Ta không biết thời gian, '",
  "sn1.20:12.2": "Thời gian bị che khuất, không thấy được; ",
  "sn1.20:12.3": "Do đó khi chưa thọ hưởng, ta đi khất thực, ",
  "sn1.20:12.4": "Chớ để thời gian qua đi mà không kịp.' ",
  "sn1.20:13.1": "Khi ấy, bạch Thế Tôn, vị thiên thần đứng xuống đất, bạch con rằng: ",
  "sn1.20:13.2": "'Này Tỳ Kheo, Ngài còn trẻ, xuất gia, với mái tóc đen huyền, tươi trẻ, trong giai đoạn đầu của tuổi thanh xuân, chưa từng vui chơi với các dục lạc. '",
  "sn1.20:13.3": "Hỡi Tỳ Kheo, hãy thọ hưởng dục lạc của con người; ",
  "sn1.20:13.4": "Đừng từ bỏ hiện tại để chạy theo tương lai.' ",
  "sn1.20:14.1": "Khi được nói vậy, bạch Thế Tôn, con đã nói với vị thiên thần ấy rằng: ",
  "sn1.20:14.2": "'Này hiền giả, ta không từ bỏ hiện tại để chạy theo tương lai; '",
  "sn1.20:14.3": "ta từ bỏ tương lai để chạy theo hiện tại. ",
  "sn1.20:14.4": "Này hiền giả, các dục lạc được Thế Tôn dạy là thuộc về tương lai, nhiều khổ đau, nhiều ưu não; và nguy hiểm ở đây còn nhiều hơn. ",
  "sn1.20:14.5": "Pháp này là hiện tại, không bị thời gian chi phối, mời đến để thấy, hướng thượng, được người trí tự mình chứng nghiệm.' ",
  "sn1.20:15.1": "Khi được nói vậy, bạch Thế Tôn, vị thiên thần ấy bạch con rằng: ",
  "sn1.20:15.2": "'Thế nào là các dục lạc được Thế Tôn dạy là thuộc về tương lai, nhiều khổ đau, nhiều ưu não; và nguy hiểm ở đây còn nhiều hơn? '",
  "sn1.20:15.3": "Thế nào là Pháp hiện tại, không bị thời gian chi phối, mời đến để thấy, hướng thượng, được người trí tự mình chứng nghiệm?' ",
  "sn1.20:16.1": "Khi được nói vậy, bạch Thế Tôn, con đã nói với vị thiên thần ấy rằng: ",
  "sn1.20:16.2": "'Này hiền giả, ta mới xuất gia, chưa bao lâu mới đến học Pháp và Luật này, ta không thể giải thích rộng rãi. '",
  "sn1.20:16.3": "Đây là Thế Tôn, bậc A-la-hán, Chánh Đẳng Giác đang trú tại Rājagaha, Tapodārāma. ",
  "sn1.20:16.4": "Hãy đến gặp Thế Tôn và hỏi về điều này. ",
  "sn1.20:16.5": "Như Thế Tôn giải thích thế nào, hãy ghi nhớ như vậy.' ",
  "sn1.20:17.1": "Khi được nói vậy, bạch Thế Tôn, vị thiên thần ấy bạch con rằng: ",
  "sn1.20:17.2": "'Này Tỳ Kheo, Thế Tôn không dễ gì đến gặp được bởi chúng ta, vì Ngài được bao quanh bởi các vị thiên thần quyền năng khác. '",
  "sn1.20:17.3": "Nếu Ngài đến gặp Thế Tôn và hỏi về điều này, chúng ta cũng sẽ đến để nghe Pháp.' ",
  "sn1.20:17.4": "Nếu lời nói của vị thiên thần ấy là thật, bạch Thế Tôn, thì vị thiên thần ấy đang ở gần đây.' ",
  "sn1.20:18.1": "Khi được nói vậy, vị thiên thần ấy bạch Tôn giả Samiddhi rằng: ",
  "sn1.20:18.2": "'Hãy hỏi đi, Tỳ Kheo, hãy hỏi đi, Tỳ Kheo, ta đã đến đây.' ",
  "sn1.20:19.1": "Khi ấy Thế Tôn nói với vị thiên thần bằng các bài kệ: ",
  "sn1.20:20.1": "'Các chúng sinh có tưởng về những gì có thể nói, '",
  "sn1.20:20.2": "Bám chặt vào những gì có thể nói; ",
  "sn1.20:20.3": "Không thấu triệt những gì có thể nói, ",
  "sn1.20:20.4": "Họ đến dưới ách của thần chết. ",
  "sn1.20:21.1": "Sau khi thấu triệt những gì có thể nói, ",
  "sn1.20:21.2": "Không nghĩ mình là người nói; ",
  "sn1.20:21.3": "Vì điều đó không tồn tại nơi người ấy, ",
  "sn1.20:21.4": "Qua đó không thể nói được về người ấy; ",
  "sn1.20:21.5": "Nếu ngươi biết, hãy nói đi, hỡi dạ-xoa.' ",
  "sn1.20:22.1": "'Bạch Thế Tôn, con không hiểu rõ ý nghĩa của điều Thế Tôn nói vắn tắt này một cách chi tiết. '",
  "sn1.20:22.2": "Lành thay, bạch Thế Tôn, xin Thế Tôn hãy dạy con sao cho con có thể hiểu rõ ý nghĩa của điều này một cách chi tiết.' ",
  "sn1.20:23.1": "'Bằng, hơn, hay kém, '",
  "sn1.20:23.2": "Ai nghĩ như vậy sẽ tranh luận vì điều đó; ",
  "sn1.20:23.3": "Người không dao động trước ba điều này, ",
  "sn1.20:23.4": "Không có ý niệm bằng hay hơn; ",
  "sn1.20:23.5": "Nếu ngươi biết, hãy nói đi, hỡi dạ-xoa.' ",
  "sn1.20:24.1": "'Bạch Thế Tôn, con cũng không hiểu rõ ý nghĩa của điều này một cách chi tiết. '",
  "sn1.20:24.2": "Lành thay, bạch Thế Tôn, xin Thế Tôn hãy dạy con sao cho con có thể hiểu rõ ý nghĩa của điều này một cách chi tiết.' ",
  "sn1.20:25.1": "'Vị ấy đã từ bỏ sự kiêu ngạo, không đạt đến ngã mạn, '",
  "sn1.20:25.2": "Đã cắt đứt tham ái ở đây đối với danh và sắc; ",
  "sn1.20:25.3": "Vị ấy đã đoạn trói buộc, không khổ não, không ưu phiền, ",
  "sn1.20:25.4": "Khi tìm kiếm, họ không tìm thấy vị ấy; ",
  "sn1.20:25.5": "Các vị trời và người ở đây hay ở nơi kia, ",
  "sn1.20:25.6": "Hay trong các cõi trời trong mọi nơi trú ngụ. ",
  "sn1.20:26.1": "Nếu ngươi biết, hãy nói đi, hỡi dạ-xoa.' ",
  "sn1.20:27.1": "'Bạch Thế Tôn, con hiểu rõ ý nghĩa của điều Thế Tôn nói vắn tắt này một cách chi tiết như vầy '",
  "sn1.20:28.1": "Không làm bất kỳ điều ác nào bằng lời, bằng tâm, ",
  "sn1.20:28.2": "Hay bằng thân trong toàn thế giới; ",
  "sn1.20:28.3": "Từ bỏ các dục, với chánh niệm và tỉnh giác, ",
  "sn1.20:28.4": "Không theo đuổi khổ đau là điều bất lợi.' ",
  "sn1.20:28.5": "Phẩm Hoan Lạc, thứ hai. ",
  "sn1.20:29.0": "Tóm lược phẩm này ",
  "sn1.20:29.1": "Nandana, hoan hỷ, ",
  "sn1.20:29.2": "Không gì bằng con; ",
  "sn1.20:29.3": "Vua Sát-đế-lợi, rào rào, ",
  "sn1.20:29.4": "Buồn ngủ lười biếng và khó làm; ",
  "sn1.20:29.5": "Tàm quý, túp lều là thứ chín, ",
  "sn1.20:29.6": "Thứ mười là Samiddhi được nói đến. ",
  "sn1.21:0.1": "Tương Ưng Bộ Kinh 1.21 ",
  "sn1.21:0.2": "3. Phẩm Cây Thương ",
  "sn1.21:0.3": "Kinh Cây Thương ",
  "sn1.21:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.21:1.2": "Đứng sang một bên, vị thiên thần ấy đọc bài kệ này trước Thế Tôn: ",
  "sn1.21:2.1": "'Như bị đâm bởi cây thương, '",
  "sn1.21:2.2": "Như đầu đang bốc lửa; ",
  "sn1.21:2.3": "Để từ bỏ tham dục, ",
  "sn1.21:2.4": "Tỳ Kheo hãy sống chánh niệm du hành.' ",
  "sn1.21:3.1": "'Như bị đâm bởi cây thương, '",
  "sn1.21:3.2": "Như đầu đang bốc lửa; ",
  "sn1.21:3.3": "Để từ bỏ thân kiến, ",
  "sn1.21:3.4": "Tỳ Kheo hãy sống chánh niệm du hành.' ",
  "sn1.22:0.1": "Tương Ưng Bộ Kinh 1.22 ",
  "sn1.22:0.2": "3. Phẩm Cây Thương ",
  "sn1.22:0.3": "Kinh Xúc Chạm ",
  "sn1.22:1.1": "'Không xúc chạm người không xúc chạm mình, '",
  "sn1.22:1.2": "Ai xúc chạm mình thì xúc chạm lại; ",
  "sn1.22:1.3": "Do đó xúc chạm người xúc chạm mình, ",
  "sn1.22:1.4": "Kẻ làm hại người không làm hại mình.' ",
  "sn1.22:2.1": "'Ai xúc phạm người hiền không lỗi lầm, '",
  "sn1.22:2.2": "Người trong sạch, không bụi nhơ; ",
  "sn1.22:2.3": "Điều ác ấy quay lại với kẻ ngu, ",
  "sn1.22:2.4": "Như bụi mịn ném ngược chiều gió.' ",
  "sn1.23:0.1": "Tương Ưng Bộ Kinh 1.23 ",
  "sn1.23:0.2": "3. Phẩm Cây Thương ",
  "sn1.23:0.3": "Kinh Cái Gút ",
  "sn1.23:1.1": "'Gút bên trong, gút bên ngoài, '",
  "sn1.23:1.2": "Người đời bị ràng buộc trong gút; ",
  "sn1.23:1.3": "Ta hỏi ngài Gotama điều này, ",
  "sn1.23:1.4": "Ai có thể tháo gỡ cái gút này?' ",
  "sn1.23:2.1": "'Người có trí tuệ được thiết lập trong giới, '",
  "sn1.23:2.2": "Tu tập tâm và tuệ; ",
  "sn1.23:2.3": "Tỳ Kheo nhiệt tâm, thận trọng, ",
  "sn1.23:2.4": "Vị ấy có thể tháo gỡ cái gút này. ",
  "sn1.23:3.1": "Những ai đã ly tham, ly sân, ",
  "sn1.23:3.2": "Và vô minh đã tan biến; ",
  "sn1.23:3.3": "Là những bậc A-la-hán, lậu hoặc đã diệt, ",
  "sn1.23:3.4": "Đối với họ, cái gút đã được tháo gỡ. ",
  "sn1.23:4.1": "Nơi nào danh và sắc, ",
  "sn1.23:4.2": "Đoạn diệt không còn dư sót; ",
  "sn1.23:4.3": "Nơi nào chướng ngại và tưởng về hình sắc, ",
  "sn1.23:4.4": "Chính tại đây cái gút được tháo gỡ.' ",
  "sn1.24:0.1": "Tương Ưng Bộ Kinh 1.24 ",
  "sn1.24:0.2": "3. Phẩm Cây Thương ",
  "sn1.24:0.3": "Kinh Kiềm Chế Tâm ",
  "sn1.24:1.1": "'Ở đâu mà tâm được kiềm chế, '",
  "sn1.24:1.2": "Thì khổ đau không đến từ đó; ",
  "sn1.24:1.3": "Người hãy kiềm chế tâm ở mọi nơi, ",
  "sn1.24:1.4": "Người sẽ được giải thoát khỏi mọi khổ đau.' ",
  "sn1.24:2.1": "'Không phải kiềm chế tâm ở mọi nơi, '",
  "sn1.24:2.2": "Không phải tâm đã đạt đến sự kiềm chế; ",
  "sn1.24:2.3": "Ở đâu và ở đó có điều ác, ",
  "sn1.24:2.4": "Thì tại đó hãy kiềm chế tâm.' ",
  "sn1.25:0.1": "Tương Ưng Bộ Kinh 1.25 ",
  "sn1.25:0.2": "3. Phẩm Cây Thương ",
  "sn1.25:0.3": "Kinh Bậc A-la-hán ",
  "sn1.25:1.1": "'Tỳ Kheo là bậc A-la-hán, đã làm những gì cần làm, '",
  "sn1.25:1.2": "Lậu hoặc đã diệt, mang thân cuối cùng; ",
  "sn1.25:1.3": "Người ấy có thể nói 'Ta nói' chăng, ",
  "sn1.25:1.4": "Và có thể nói 'Người ta nói về ta' chăng?' ",
  "sn1.25:2.1": "'Tỳ Kheo là bậc A-la-hán, đã làm những gì cần làm, '",
  "sn1.25:2.2": "Lậu hoặc đã diệt, mang thân cuối cùng; ",
  "sn1.25:2.3": "Người ấy có thể nói 'Ta nói', ",
  "sn1.25:2.4": "Và có thể nói 'Người ta nói về ta'; ",
  "sn1.25:2.5": "Khéo biết ngôn ngữ thông thường ở đời, ",
  "sn1.25:2.6": "Vị ấy nói chỉ theo cách nói thông thường.' ",
  "sn1.25:3.1": "'Tỳ Kheo là bậc A-la-hán, đã làm những gì cần làm, '",
  "sn1.25:3.2": "Lậu hoặc đã diệt, mang thân cuối cùng; ",
  "sn1.25:3.3": "Vị Tỳ Kheo ấy có chấp thủ ngã mạn không, ",
  "sn1.25:3.4": "Mà lại nói 'Ta nói'; ",
  "sn1.25:3.5": "Và có thể nói 'Người ta nói về ta' chăng?' ",
  "sn1.25:4.1": "'Không có trói buộc đối với người đã từ bỏ ngã mạn, '",
  "sn1.25:4.2": "Tất cả các gút của ngã mạn đã được tiêu tan; ",
  "sn1.25:4.3": "Bậc trí ấy đã vượt qua các ý niệm phân biệt, ",
  "sn1.25:4.4": "Người ấy có thể nói 'Ta nói'. ",
  "sn1.25:5.1": "Và có thể nói 'Người ta nói về ta', ",
  "sn1.25:5.2": "Khéo biết ngôn ngữ thông thường ở đời; ",
  "sn1.25:5.3": "Vị ấy nói chỉ theo cách nói thông thường.' ",
  "sn1.26:0.1": "Tương Ưng Bộ Kinh 1.26 ",
  "sn1.26:0.2": "3. Phẩm Cây Thương ",
  "sn1.26:0.3": "Kinh Ánh Sáng ",
  "sn1.26:1.1": "'Có bao nhiêu ánh sáng trong thế gian, '",
  "sn1.26:1.2": "Nhờ chúng mà thế gian được soi sáng; ",
  "sn1.26:1.3": "Chúng con đến hỏi Thế Tôn, ",
  "sn1.26:1.4": "Làm sao chúng con biết được điều này?' ",
  "sn1.26:2.1": "'Có bốn loại ánh sáng trong thế gian, '",
  "sn1.26:2.2": "Loại thứ năm không tìm thấy được ở đây; ",
  "sn1.26:2.3": "Ban ngày mặt trời tỏa sáng, ",
  "sn1.26:2.4": "Ban đêm mặt trăng chiếu sáng. ",
  "sn1.26:3.1": "Rồi lửa tỏa sáng ngày và đêm, ",
  "sn1.26:3.2": "Tại đây và tại đó; ",
  "sn1.26:3.3": "Phật Chánh Đẳng Giác là tối thắng trong những gì tỏa sáng, ",
  "sn1.26:3.4": "Đây là ánh sáng vô thượng.' ",
  "sn1.27:0.1": "Tương Ưng Bộ Kinh 1.27 ",
  "sn1.27:0.2": "3. Phẩm Cây Thương ",
  "sn1.27:0.3": "Kinh Dòng Chảy ",
  "sn1.27:1.1": "'Dòng chảy quay trở về từ đâu, '",
  "sn1.27:1.2": "Bánh xe ở đâu mà không quay; ",
  "sn1.27:1.3": "Ở đâu danh và sắc, ",
  "sn1.27:1.4": "Đoạn diệt không còn dư sót?' ",
  "sn1.27:2.1": "'Nơi nào nước, đất, '",
  "sn1.27:2.2": "Lửa và gió không bám trụ; ",
  "sn1.27:2.3": "Từ đó dòng chảy quay trở về, ",
  "sn1.27:2.4": "Tại đó bánh xe không quay; ",
  "sn1.27:2.5": "Tại đó danh và sắc, ",
  "sn1.27:2.6": "Đoạn diệt không còn dư sót.' ",
  "sn1.28:0.1": "Tương Ưng Bộ Kinh 1.28 ",
  "sn1.28:0.2": "3. Phẩm Cây Thương ",
  "sn1.28:0.3": "Kinh Tài Sản Lớn ",
  "sn1.28:1.1": "'Những vua Sát-đế-lợi giàu có, của cải dồi dào, '",
  "sn1.28:1.2": "Có đất đai rộng lớn; ",
  "sn1.28:1.3": "Họ tham lam lẫn nhau, ",
  "sn1.28:1.4": "Không bao giờ thỏa mãn với các dục lạc. ",
  "sn1.28:2.1": "Trong số những người bận rộn như vậy, ",
  "sn1.28:2.2": "Theo dòng của sự hiện hữu; ",
  "sn1.28:2.3": "Ai ở đây đã từ bỏ tham ái, ",
  "sn1.28:2.4": "Ai ở thế gian không còn bận rộn?' ",
  "sn1.28:3.1": "'Những ai từ bỏ gia đình xuất gia, '",
  "sn1.28:3.2": "Từ bỏ con cái, gia súc thân yêu; ",
  "sn1.28:3.3": "Từ bỏ tham, sân, ",
  "sn1.28:3.4": "Và vô minh đã ly tham; ",
  "sn1.28:3.5": "Những bậc A-la-hán, lậu hoặc đã diệt, ",
  "sn1.28:3.6": "Họ ở thế gian không còn bận rộn.' ",
  "sn1.29:0.1": "Tương Ưng Bộ Kinh 1.29 ",
  "sn1.29:0.2": "3. Phẩm Cây Thương ",
  "sn1.29:0.3": "Kinh Bốn Bánh Xe ",
  "sn1.29:1.1": "'Bốn bánh xe, chín cửa, '",
  "sn1.29:1.2": "Đầy ắp, gắn liền với tham; ",
  "sn1.29:1.3": "Sinh ra trong lầy lội, hỡi bậc đại hùng, ",
  "sn1.29:1.4": "Làm sao để thoát ra được?' ",
  "sn1.29:2.1": "'Sau khi cắt đứt dây da và dây buộc, '",
  "sn1.29:2.2": "Dục vọng, tham ái ác độc; ",
  "sn1.29:2.3": "Nhổ tận gốc tham ái, ",
  "sn1.29:2.4": "Như vậy sẽ thoát ra được.' ",
  "sn1.30:0.1": "Tương Ưng Bộ Kinh 1.30 ",
  "sn1.30:0.2": "3. Phẩm Cây Thương ",
  "sn1.30:0.3": "Kinh Chân Nai ",
  "sn1.30:1.1": "'Có chân nai, gầy gò, dũng mãnh, '",
  "sn1.30:1.2": "Ăn ít, không tham lam; ",
  "sn1.30:1.3": "Như sư tử sống một mình, như voi chúa, ",
  "sn1.30:1.4": "Không quan tâm đến các dục lạc; ",
  "sn1.30:1.5": "Chúng con đến hỏi, ",
  "sn1.30:1.6": "Làm sao thoát khỏi khổ đau?' ",
  "sn1.30:2.1": "'Năm loại dục lạc ở đời, '",
  "sn1.30:2.2": "Tâm là loại thứ sáu được tuyên thuyết; ",
  "sn1.30:2.3": "Sau khi ly tham đối với chúng, ",
  "sn1.30:2.4": "Như vậy thoát khỏi khổ đau.' ",
  "sn1.30:2.5": "Phẩm Cây Thương, thứ ba. ",
  "sn1.30:3.0": "Tóm lược phẩm này ",
  "sn1.30:3.1": "Cây thương, xúc chạm, ",
  "sn1.30:3.2": "Cái gút, kiềm chế tâm; ",
  "sn1.30:3.3": "Bậc A-la-hán, ánh sáng, ",
  "sn1.30:3.4": "Dòng chảy, tài sản lớn; ",
  "sn1.30:3.5": "Bốn bánh xe là thứ chín, ",
  "sn1.30:3.6": "Chân nai là thứ mười.' ",
  "sn1.31:0.1": "Tương Ưng Bộ Kinh 1.31 ",
  "sn1.31:0.2": "4. Phẩm Satullapa ",
  "sn1.31:0.3": "Kinh Cùng Với Bậc Chân Thiện ",
  "sn1.31:1.1": "Tôi nghe như vầy",
  "sn1.31:1.2": "một thời Thế Tôn trú tại Sāvatthi, Jetavana, tinh xá của Anāthapiṇḍika. ",
  "sn1.31:1.3": "Khi ấy, nhiều vị thiên thần thuộc nhóm Satullapa vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Jetavana, đến chỗ Thế Tôn; sau khi đến, cúi đầu đảnh lễ Thế Tôn rồi đứng sang một bên. ",
  "sn1.31:1.4": "Đứng sang một bên, một vị thiên thần đọc bài kệ này trước Thế Tôn: ",
  "sn1.31:2.1": "'Hãy giao tiếp cùng bậc chân thiện, '",
  "sn1.31:2.2": "Hãy kết thân với bậc chân thiện; ",
  "sn1.31:2.3": "Sau khi biết được chánh pháp của bậc chân thiện, ",
  "sn1.31:2.4": "Sẽ tốt hơn, không xấu hơn.' ",
  "sn1.31:3.1": "Khi ấy một vị thiên thần khác đọc bài kệ này trước Thế Tôn: ",
  "sn1.31:4.1": "'Hãy giao tiếp cùng bậc chân thiện, '",
  "sn1.31:4.2": "Hãy kết thân với bậc chân thiện; ",
  "sn1.31:4.3": "Sau khi biết được chánh pháp của bậc chân thiện, ",
  "sn1.31:4.4": "Trí tuệ có được chứ không từ nơi khác.' ",
  "sn1.31:5.1": "Khi ấy một vị thiên thần khác đọc bài kệ này trước Thế Tôn: ",
  "sn1.31:6.1": "'Hãy giao tiếp cùng bậc chân thiện, '",
  "sn1.31:6.2": "Hãy kết thân với bậc chân thiện; ",
  "sn1.31:6.3": "Sau khi biết được chánh pháp của bậc chân thiện, ",
  "sn1.31:6.4": "Giữa nỗi sầu mà không sầu.' ",
  "sn1.31:7.1": "Khi ấy một vị thiên thần khác đọc bài kệ này trước Thế Tôn: ",
  "sn1.31:8.1": "'Hãy giao tiếp cùng bậc chân thiện, '",
  "sn1.31:8.2": "Hãy kết thân với bậc chân thiện; ",
  "sn1.31:8.3": "Sau khi biết được chánh pháp của bậc chân thiện, ",
  "sn1.31:8.4": "Tỏa sáng giữa hàng quyến thuộc.' ",
  "sn1.31:9.1": "Khi ấy một vị thiên thần khác đọc bài kệ này trước Thế Tôn: ",
  "sn1.31:10.1": "'Hãy giao tiếp cùng bậc chân thiện, '",
  "sn1.31:10.2": "Hãy kết thân với bậc chân thiện; ",
  "sn1.31:10.3": "Sau khi biết được chánh pháp của bậc chân thiện, ",
  "sn1.31:10.4": "Chúng sinh đi đến cõi lành.' ",
  "sn1.31:11.1": "Khi ấy một vị thiên thần khác đọc bài kệ này trước Thế Tôn: ",
  "sn1.31:12.1": "'Hãy giao tiếp cùng bậc chân thiện, '",
  "sn1.31:12.2": "Hãy kết thân với bậc chân thiện; ",
  "sn1.31:12.3": "Sau khi biết được chánh pháp của bậc chân thiện, ",
  "sn1.31:12.4": "Chúng sinh an trú lâu dài.' ",
  "sn1.31:13.1": "Khi ấy một vị thiên thần khác bạch Thế Tôn rằng: ",
  "sn1.31:13.2": "'Bạch Thế Tôn, ai nói hay?' ",
  "sn1.31:14.1": "'Tất cả các vị đều nói hay theo cách riêng của mình, nhưng hãy nghe ta nói thêm '",
  "sn1.31:15.1": "Hãy giao tiếp cùng bậc chân thiện, ",
  "sn1.31:15.2": "Hãy kết thân với bậc chân thiện; ",
  "sn1.31:15.3": "Sau khi biết được chánh pháp của bậc chân thiện, ",
  "sn1.31:15.4": "Được giải thoát khỏi mọi khổ đau.' ",
  "sn1.31:16.1": "Thế Tôn đã nói như vậy. ",
  "sn1.31:16.2": "Các vị thiên thần hoan hỷ, cúi đầu đảnh lễ Thế Tôn, đi nhiễu theo bên phải, và biến mất ngay tại chỗ. ",
  "sn1.32:0.1": "Tương Ưng Bộ Kinh 1.32 ",
  "sn1.32:0.2": "4. Phẩm Satullapa ",
  "sn1.32:0.3": "Kinh Keo Kiệt ",
  "sn1.32:1.1": "Một thời Thế Tôn trú tại Sāvatthi, Jetavana, tinh xá của Anāthapiṇḍika. ",
  "sn1.32:1.2": "Khi ấy, nhiều vị thiên thần thuộc nhóm Satullapa vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Jetavana, đến chỗ Thế Tôn; sau khi đến, cúi đầu đảnh lễ Thế Tôn rồi đứng sang một bên. ",
  "sn1.32:1.3": "Đứng sang một bên, một vị thiên thần đọc bài kệ này trước Thế Tôn: ",
  "sn1.32:2.1": "'Do keo kiệt và phóng dật, '",
  "sn1.32:2.2": "Mà không bố thí như vậy; ",
  "sn1.32:2.3": "Người muốn công đức, ",
  "sn1.32:2.4": "Phải biết bố thí những gì cần bố thí.' ",
  "sn1.32:3.1": "Khi ấy một vị thiên thần khác đọc các bài kệ này trước Thế Tôn: ",
  "sn1.32:4.1": "'Điều mà kẻ keo kiệt sợ hãi mà không bố thí, '",
  "sn1.32:4.2": "Chính điều đó xảy ra cho kẻ không bố thí; ",
  "sn1.32:4.3": "Cả đói lẫn khát, ",
  "sn1.32:4.4": "Điều mà kẻ keo kiệt sợ hãi; ",
  "sn1.32:4.5": "Chính điều đó chạm đến kẻ ngu, ",
  "sn1.32:4.6": "Ở đời này và đời sau. ",
  "sn1.32:5.1": "Do đó hãy từ bỏ keo kiệt, ",
  "sn1.32:5.2": "Hãy bố thí, chiến thắng cấu uế; ",
  "sn1.32:5.3": "Các công đức ở đời sau, ",
  "sn1.32:5.4": "Là nơi nương tựa cho chúng sinh.' ",
  "sn1.32:6.1": "Khi ấy một vị thiên thần khác đọc các bài kệ này trước Thế Tôn: ",
  "sn1.32:7.1": "'Họ không chết khi những người thân chết, '",
  "sn1.32:7.2": "Như bạn đồng hành trên đường cùng đi; ",
  "sn1.32:7.3": "Những ai bố thí với ít ỏi, ",
  "sn1.32:7.4": "Đây là pháp xưa nay. ",
  "sn1.32:8.1": "Một số bố thí với ít, ",
  "sn1.32:8.2": "Nhiều người không bố thí; ",
  "sn1.32:8.3": "Vật cúng dường được bố thí với ít, ",
  "sn1.32:8.4": "Đáng giá bằng cả nghìn.' ",
  "sn1.32:9.1": "Khi ấy một vị thiên thần khác đọc các bài kệ này trước Thế Tôn: ",
  "sn1.32:10.1": "'Bố thí vật khó bố thí, '",
  "sn1.32:10.2": "Làm điều khó làm; ",
  "sn1.32:10.3": "Kẻ bất thiện không làm theo, ",
  "sn1.32:10.4": "Pháp của bậc chân thiện khó theo. ",
  "sn1.32:11.1": "Do đó giữa người thiện và bất thiện, ",
  "sn1.32:11.2": "Cảnh giới khác nhau từ đây; ",
  "sn1.32:11.3": "Kẻ bất thiện đi vào địa ngục, ",
  "sn1.32:11.4": "Người thiện hướng đến cõi trời.' ",
  "sn1.32:12.1": "Khi ấy một vị thiên thần khác bạch Thế Tôn rằng: ",
  "sn1.32:12.2": "'Bạch Thế Tôn, ai nói hay?' ",
  "sn1.32:13.1": "'Tất cả các vị đều nói hay theo cách riêng của mình; nhưng hãy nghe ta nói thêm '",
  "sn1.32:14.1": "Người nào thực hành Pháp dù nhỏ nhoi, ",
  "sn1.32:14.2": "Nuôi dưỡng vợ con với ít ỏi; ",
  "sn1.32:14.3": "Hàng nghìn người tế lễ hàng nghìn, ",
  "sn1.32:14.4": "Không đáng một phần của người như vậy.' ",
  "sn1.32:15.1": "Khi ấy một vị thiên thần khác nói với Thế Tôn bằng bài kệ: ",
  "sn1.32:16.1": "'Tại sao lễ tế lớn lao, rộng rãi này, '",
  "sn1.32:16.2": "Không bằng vật bố thí được bố thí bình đẳng; ",
  "sn1.32:16.3": "Tại sao hàng nghìn người tế lễ hàng nghìn, ",
  "sn1.32:16.4": "Không đáng một phần của người như vậy?' ",
  "sn1.32:17.1": "'Một số bố thí khi đứng vào chỗ bất bình đẳng, '",
  "sn1.32:17.2": "Sau khi chém giết, hành hạ, rồi gây khổ đau; ",
  "sn1.32:17.3": "Vật cúng dường ấy đến với nước mắt và gậy gộc, ",
  "sn1.32:17.4": "Không bằng vật bố thí được bố thí bình đẳng. ",
  "sn1.32:18.1": "Như vậy hàng nghìn người tế lễ hàng nghìn, ",
  "sn1.32:18.2": "Không đáng một phần của người như vậy.' ",
  "sn1.33:0.1": "Tương Ưng Bộ Kinh 1.33 ",
  "sn1.33:0.2": "4. Phẩm Satullapa ",
  "sn1.33:0.3": "Kinh Lành Thay ",
  "sn1.33:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.33:1.2": "Khi ấy, nhiều vị thiên thần thuộc nhóm Satullapa vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Jetavana, đến chỗ Thế Tôn; sau khi đến, cúi đầu đảnh lễ Thế Tôn rồi đứng sang một bên. ",
  "sn1.33:1.3": "Đứng sang một bên, một vị thiên thần thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.33:2.1": "'Lành thay, hiền giả, bố thí là lành, '",
  "sn1.33:2.2": "Do keo kiệt và phóng dật; ",
  "sn1.33:2.3": "Mà không bố thí như vậy, ",
  "sn1.33:2.4": "Người muốn công đức; ",
  "sn1.33:2.5": "Phải biết bố thí những gì cần bố thí.' ",
  "sn1.33:3.1": "Khi ấy một vị thiên thần khác thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.33:4.1": "'Lành thay, hiền giả, bố thí là lành, '",
  "sn1.33:4.2": "Dù bố thí với ít ỏi cũng lành thay. ",
  "sn1.33:5.1": "Một số bố thí với ít, ",
  "sn1.33:5.2": "Nhiều người không bố thí; ",
  "sn1.33:5.3": "Vật cúng dường được bố thí với ít, ",
  "sn1.33:5.4": "Đáng giá bằng cả nghìn.' ",
  "sn1.33:6.1": "Khi ấy một vị thiên thần khác thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.33:7.1": "'Lành thay, hiền giả, bố thí là lành, '",
  "sn1.33:7.2": "Dù ít cũng lành thay; ",
  "sn1.33:7.3": "Bố thí với tín tâm cũng lành thay, ",
  "sn1.33:7.4": "Bố thí và chiến đấu được ví như nhau; ",
  "sn1.33:7.5": "Dù ít người mà đã giác ngộ cũng chiến thắng nhiều, ",
  "sn1.33:7.6": "Dù ít mà bố thí với lòng tin; ",
  "sn1.33:7.7": "Chính nhờ đó mà vị ấy được hạnh phúc ở đời sau.' ",
  "sn1.33:8.1": "Khi ấy một vị thiên thần khác thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.33:9.1": "'Lành thay, hiền giả, bố thí là lành, '",
  "sn1.33:9.2": "Dù ít cũng lành thay; ",
  "sn1.33:9.3": "Bố thí với tín tâm cũng lành thay, ",
  "sn1.33:9.4": "Bố thí những gì có được bằng chánh pháp cũng lành thay. ",
  "sn1.33:10.1": "Ai bố thí những gì có được bằng chánh pháp, ",
  "sn1.33:10.2": "Người đạt được nhờ nỗ lực và tinh tấn; ",
  "sn1.33:10.3": "Vượt qua sông Vetaraṇī của Yama, ",
  "sn1.33:10.4": "Con người đạt được những cõi thiên thần.' ",
  "sn1.33:11.1": "Khi ấy một vị thiên thần khác thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.33:12.1": "'Lành thay, hiền giả, bố thí là lành, '",
  "sn1.33:12.2": "Dù ít cũng lành thay; ",
  "sn1.33:12.3": "Bố thí với tín tâm cũng lành thay, ",
  "sn1.33:12.4": "Bố thí những gì có được bằng chánh pháp cũng lành thay; ",
  "sn1.33:12.5": "Bố thí có chọn lọc cũng lành thay. ",
  "sn1.33:13.1": "Bố thí có chọn lọc được bậc Thiện Thệ tán thán, ",
  "sn1.33:13.2": "Những ai xứng đáng nhận cúng dường ở thế gian này; ",
  "sn1.33:13.3": "Những gì bố thí cho họ có quả lớn, ",
  "sn1.33:13.4": "Như hạt giống được gieo trên ruộng tốt.' ",
  "sn1.33:14.1": "Khi ấy một vị thiên thần khác thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.33:15.1": "'Lành thay, hiền giả, bố thí là lành, '",
  "sn1.33:15.2": "Dù ít cũng lành thay; ",
  "sn1.33:15.3": "Bố thí với tín tâm cũng lành thay, ",
  "sn1.33:15.4": "Bố thí những gì có được bằng chánh pháp cũng lành thay; ",
  "sn1.33:15.5": "Bố thí có chọn lọc cũng lành thay, ",
  "sn1.33:15.6": "Tự chế đối với chúng sinh cũng là lành. ",
  "sn1.33:16.1": "Ai đi lại không làm hại chúng sinh, ",
  "sn1.33:16.2": "Không làm điều ác do người khác khiển trách; ",
  "sn1.33:16.3": "Người ta ca ngợi kẻ sợ hãi, không phải kẻ dũng cảm, ",
  "sn1.33:16.4": "Vì người thiện không làm điều ác do sợ hãi.' ",
  "sn1.33:17.1": "Khi ấy một vị thiên thần khác bạch Thế Tôn rằng: ",
  "sn1.33:17.2": "'Bạch Thế Tôn, ai nói hay?' ",
  "sn1.33:18.1": "'Tất cả các vị đều nói hay theo cách riêng của mình; nhưng hãy nghe ta nói thêm '",
  "sn1.33:19.1": "Quả thật bố thí với tín tâm được ca ngợi theo nhiều cách, ",
  "sn1.33:19.2": "Nhưng hơn bố thí, con đường Pháp là tốt hơn; ",
  "sn1.33:19.3": "Thật vậy cả những người xưa và người trước đây là bậc thiện, ",
  "sn1.33:19.4": "Những người có trí tuệ đã chứng đạt Niết-bàn.' ",
  "sn1.34:0.1": "Tương Ưng Bộ Kinh 1.34 ",
  "sn1.34:0.2": "4. Phẩm Satullapa ",
  "sn1.34:0.3": "Kinh Không Có Gì ",
  "sn1.34:1.1": "Một thời Thế Tôn trú tại Sāvatthi, Jetavana, tinh xá của Anāthapiṇḍika. ",
  "sn1.34:1.2": "Khi ấy, nhiều vị thiên thần thuộc nhóm Satullapa vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Jetavana, đến chỗ Thế Tôn; sau khi đến, cúi đầu đảnh lễ Thế Tôn rồi đứng sang một bên. ",
  "sn1.34:1.3": "Đứng sang một bên, một vị thiên thần đọc bài kệ này trước Thế Tôn: ",
  "sn1.34:2.1": "'Không có dục lạc thường hằng nơi con người, '",
  "sn1.34:2.2": "Tuy ở đây có những điều đáng mong muốn mà người bị trói buộc; ",
  "sn1.34:2.3": "Người phóng dật vào chúng, không trở lại, ",
  "sn1.34:2.4": "Sẽ không đến được với lĩnh vực của thần chết.' ",
  "sn1.34:3.1": "'Khổ đau sinh ra từ dục, khổ đau sinh ra từ dục, '",
  "sn1.34:3.2": "Do đoạn trừ dục mà đoạn trừ khổ đau; ",
  "sn1.34:3.3": "Do đoạn trừ khổ đau mà đoạn trừ khổ đau.' ",
  "sn1.34:4.1": "'Không phải những gì đẹp đẽ ở đời là dục lạc, '",
  "sn1.34:4.2": "Dục của người là tư duy và tham ái; ",
  "sn1.34:4.3": "Những gì đẹp đẽ vẫn ở đời như vậy, ",
  "sn1.34:4.4": "Nhưng bậc trí ở đó đoạn trừ dục. ",
  "sn1.34:5.1": "Hãy từ bỏ sân hận, hãy hoàn toàn từ bỏ ngã mạn, ",
  "sn1.34:5.2": "Hãy vượt qua tất cả mọi kiết sử; ",
  "sn1.34:5.3": "Vị không chấp thủ danh và sắc, ",
  "sn1.34:5.4": "Vô sở hữu, khổ đau không đến với vị ấy. ",
  "sn1.34:6.1": "Vị ấy đã từ bỏ sự kiêu ngạo, không đạt đến ngã mạn, ",
  "sn1.34:6.2": "Đã cắt đứt tham ái ở đây đối với danh và sắc; ",
  "sn1.34:6.3": "Vị ấy đã đoạn trói buộc, không khổ não, không ưu phiền, ",
  "sn1.34:6.4": "Khi tìm kiếm, họ không tìm thấy vị ấy; ",
  "sn1.34:6.5": "Các vị trời và người ở đây hay ở nơi kia, ",
  "sn1.34:6.6": "Hay trong các cõi trời trong mọi nơi trú ngụ.' ",
  "sn1.34:7.1": "'Nếu họ không thấy vị được giải thoát như vậy, '",
  "sn1.34:7.2": "(Tôn giả Mogharāja nói) ",
  "sn1.34:7.3": "Các vị trời và người ở đây hay ở nơi kia; ",
  "sn1.34:7.4": "Bậc tối thượng trong người, phục vụ lợi ích cho người, ",
  "sn1.34:7.5": "Những ai đảnh lễ vị ấy thật đáng tán thán.' ",
  "sn1.34:8.1": "'Những Tỳ Kheo ấy cũng đáng tán thán, '",
  "sn1.34:8.2": "(Thế Tôn nói với Mogharāja) ",
  "sn1.34:8.3": "Những ai đảnh lễ vị được giải thoát như vậy; ",
  "sn1.34:8.4": "Sau khi biết Pháp, từ bỏ nghi ngờ, ",
  "sn1.34:8.5": "Những Tỳ Kheo ấy đã vượt qua các kiết sử.' ",
  "sn1.35:0.1": "Tương Ưng Bộ Kinh 1.35 ",
  "sn1.35:0.2": "4. Phẩm Satullapa ",
  "sn1.35:0.3": "Kinh Các Thiên Thần Hay Chê Bai ",
  "sn1.35:1.1": "Một thời Thế Tôn trú tại Sāvatthi, Jetavana, tinh xá của Anāthapiṇḍika. ",
  "sn1.35:1.2": "Khi ấy, nhiều vị thiên thần hay chê bai vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Jetavana, đến chỗ Thế Tôn; sau khi đến, đứng trên hư không. ",
  "sn1.35:1.3": "Đứng trên hư không, một vị thiên thần đọc bài kệ này trước Thế Tôn: ",
  "sn1.35:2.1": "'Người thực sự là thế này, '",
  "sn1.35:2.2": "Mà tuyên bố mình là khác; ",
  "sn1.35:2.3": "Như tên trộm ăn trộm, ",
  "sn1.35:2.4": "Điều đó là ăn trộm đối với người ấy. ",
  "sn1.35:3.1": "Những gì mà người làm thì nói, ",
  "sn1.35:3.2": "Những gì không làm thì không nói; ",
  "sn1.35:3.3": "Kẻ nói mà không làm, ",
  "sn1.35:3.4": "Người trí biết rõ.' ",
  "sn1.35:4.1": "'Không phải chỉ bằng lời nói thôi, '",
  "sn1.35:4.2": "Hay chỉ nghe một chiều; ",
  "sn1.35:4.3": "Có thể đi theo được, ",
  "sn1.35:4.4": "Con đường vững chắc này; ",
  "sn1.35:4.5": "Con đường mà bậc trí giải thoát nhờ đó, ",
  "sn1.35:4.6": "Những người thiền định thoát khỏi trói buộc của Ma-vương. ",
  "sn1.35:5.1": "Bậc trí thực sự không làm như vậy, ",
  "sn1.35:5.2": "Sau khi biết con đường của thế gian; ",
  "sn1.35:5.3": "Bậc trí giác ngộ, viên tịch, ",
  "sn1.35:5.4": "Đã vượt qua sự chấp thủ ở đời.' ",
  "sn1.35:6.1": "Khi ấy các vị thiên thần ấy đứng xuống đất, cúi đầu xuống chân Thế Tôn và thưa với Thế Tôn rằng: ",
  "sn1.35:6.2": "'Bạch Thế Tôn, chúng con đã phạm lỗi, ngu si, mê muội, bất thiện, khi chúng con nghĩ rằng có thể xúc phạm Thế Tôn. '",
  "sn1.35:6.3": "Bạch Thế Tôn, xin Thế Tôn hãy chấp nhận lỗi lầm của chúng con vì lỗi đã phạm, để chúng con tự kiềm chế trong tương lai.' ",
  "sn1.35:6.4": "Khi ấy Thế Tôn mỉm cười. ",
  "sn1.35:6.5": "Khi ấy các vị thiên thần ấy ngày càng bất mãn hơn, bay lên hư không. ",
  "sn1.35:6.6": "Một vị thiên thần đọc bài kệ này trước Thế Tôn: ",
  "sn1.35:7.1": "'Đối với những ai đang sám hối lỗi lầm, '",
  "sn1.35:7.2": "Nếu không chấp nhận; ",
  "sn1.35:7.3": "Trong lòng có sân, nặng về sân hận, ",
  "sn1.35:7.4": "Vị ấy giải phóng oán thù.' ",
  "sn1.35:8.1": "'Nếu không có lỗi lầm, '",
  "sn1.35:8.2": "Và không có điều đã bị từ bỏ; ",
  "sn1.35:8.3": "Oán thù sẽ không được hòa giải, ",
  "sn1.35:8.4": "Ai ở đây sẽ khéo léo?' ",
  "sn1.35:9.1": "'Ai không có lỗi lầm, '",
  "sn1.35:9.2": "Ai không có điều đã bị từ bỏ; ",
  "sn1.35:9.3": "Ai không rơi vào mê muội, ",
  "sn1.35:9.4": "Ai là bậc trí luôn chánh niệm?' ",
  "sn1.35:10.1": "'Như Lai, bậc Phật, '",
  "sn1.35:10.2": "Người từ bi với tất cả chúng sinh; ",
  "sn1.35:10.3": "Ngài không có lỗi lầm, ",
  "sn1.35:10.4": "Ngài không có điều đã bị từ bỏ; ",
  "sn1.35:10.5": "Ngài không rơi vào mê muội, ",
  "sn1.35:10.6": "Ngài là bậc trí luôn chánh niệm. ",
  "sn1.35:11.1": "Đối với những ai đang sám hối lỗi lầm, ",
  "sn1.35:11.2": "Nếu không chấp nhận; ",
  "sn1.35:11.3": "Trong lòng có sân, nặng về sân hận, ",
  "sn1.35:11.4": "Vị ấy giải phóng oán thù; ",
  "sn1.35:11.5": "Oán thù đó ta không hoan hỷ, ",
  "sn1.35:11.6": "Ta chấp nhận lời nhận lỗi.' ",
  "sn1.36:0.1": "Tương Ưng Bộ Kinh 1.36 ",
  "sn1.36:0.2": "4. Phẩm Satullapa ",
  "sn1.36:0.3": "Kinh Đức Tin ",
  "sn1.36:1.1": "Một thời Thế Tôn trú tại Sāvatthi, Jetavana, tinh xá của Anāthapiṇḍika. ",
  "sn1.36:1.2": "Khi ấy, nhiều vị thiên thần thuộc nhóm Satullapa vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Jetavana, đến chỗ Thế Tôn; sau khi đến, cúi đầu đảnh lễ Thế Tôn rồi đứng sang một bên. ",
  "sn1.36:1.3": "Đứng sang một bên, một vị thiên thần đọc bài kệ này trước Thế Tôn: ",
  "sn1.36:2.1": "'Đức tin là bạn đồng hành thứ hai của người, '",
  "sn1.36:2.2": "Nếu không có lòng bất tín; ",
  "sn1.36:2.3": "Danh tiếng và vinh quang đến với vị ấy, ",
  "sn1.36:2.4": "Sau khi từ bỏ thân xác, vị ấy đi đến cõi trời.' ",
  "sn1.36:3.1": "Khi ấy một vị thiên thần khác đọc các bài kệ này trước Thế Tôn: ",
  "sn1.36:4.1": "'Hãy từ bỏ sân hận, hãy hoàn toàn từ bỏ ngã mạn, '",
  "sn1.36:4.2": "Hãy vượt qua tất cả mọi kiết sử; ",
  "sn1.36:4.3": "Vị không chấp thủ danh và sắc, ",
  "sn1.36:4.4": "Vô sở hữu, không bị các chấp thủ đuổi theo.' ",
  "sn1.36:5.1": "'Những kẻ ngu si, thiếu trí tuệ, '",
  "sn1.36:5.2": "Theo đuổi sự phóng dật; ",
  "sn1.36:5.3": "Bậc trí gìn giữ sự không phóng dật, ",
  "sn1.36:5.4": "Như bảo vệ tài sản quý nhất. ",
  "sn1.36:6.1": "Đừng theo đuổi sự phóng dật, ",
  "sn1.36:6.2": "Đừng thân cận với khoái lạc dục; ",
  "sn1.36:6.3": "Người không phóng dật thiền định, ",
  "sn1.36:6.4": "Đạt được hạnh phúc tối thượng.' ",
  "sn1.37:0.1": "Tương Ưng Bộ Kinh 1.37 ",
  "sn1.37:0.2": "4. Phẩm Satullapa ",
  "sn1.37:0.3": "Kinh Đại Hội ",
  "sn1.37:1.1": "Tôi nghe như vầy",
  "sn1.37:1.2": "một thời Thế Tôn trú tại xứ Sakka, Kapilavatthu, Đại Lâm, cùng với đại chúng Tỳ Kheo khoảng năm trăm vị, tất cả đều là bậc A-la-hán; ",
  "sn1.37:1.3": "và các thiên thần từ mười thế giới phần lớn đều tụ họp để yết kiến Thế Tôn và Tăng đoàn Tỳ Kheo. ",
  "sn1.37:1.4": "Khi ấy, bốn vị thiên thần thuộc cõi Tịnh Cư nghĩ rằng: ",
  "sn1.37:1.5": "'Thế Tôn đang trú tại xứ Sakka, Kapilavatthu, Đại Lâm, cùng với đại chúng Tỳ Kheo khoảng năm trăm vị, tất cả đều là bậc A-la-hán; '",
  "sn1.37:1.6": "và các thiên thần từ mười thế giới phần lớn đều tụ họp để yết kiến Thế Tôn và Tăng đoàn Tỳ Kheo. ",
  "sn1.37:1.7": "Vậy tại sao chúng ta không đến chỗ Thế Tôn; sau khi đến, mỗi người nói một bài kệ trước Thế Tôn?' ",
  "sn1.37:2.1": "Khi ấy, các vị thiên thần ấy  như một người lực lưỡng duỗi cánh tay đang co lại hay co cánh tay đang duỗi ra  từ cõi Tịnh Cư biến mất và hiện ra trước Thế Tôn. ",
  "sn1.37:2.2": "Khi ấy các vị thiên thần ấy cúi đầu đảnh lễ Thế Tôn rồi đứng sang một bên. ",
  "sn1.37:2.3": "Đứng sang một bên, một vị thiên thần đọc bài kệ này trước Thế Tôn: ",
  "sn1.37:3.1": "'Đây là đại hội lớn trong rừng sâu, '",
  "sn1.37:3.2": "Các đoàn thiên thần đã tụ họp; ",
  "sn1.37:3.3": "Chúng con đến trong dịp Pháp hội này, ",
  "sn1.37:3.4": "Để nhìn thấy Tăng đoàn vô địch.' ",
  "sn1.37:4.1": "Khi ấy một vị thiên thần khác đọc bài kệ này trước Thế Tôn: ",
  "sn1.37:5.1": "'Tại đó các Tỳ Kheo đã tập trung, '",
  "sn1.37:5.2": "Làm cho tâm mình thẳng thắn; ",
  "sn1.37:5.3": "Như người đánh xe nắm giữ dây cương, ",
  "sn1.37:5.4": "Bậc trí gìn giữ các căn.' ",
  "sn1.37:6.1": "Khi ấy một vị thiên thần khác đọc bài kệ này trước Thế Tôn: ",
  "sn1.37:7.1": "'Sau khi chặt đứt cái chốt, chặt đứt rào cản, '",
  "sn1.37:7.2": "Nhổ lên cọc Indra, không còn dao động; ",
  "sn1.37:7.3": "Họ bước đi trong sạch, không cấu uế, ",
  "sn1.37:7.4": "Được Đấng Nhãn Quan điều phục khéo, như voi chúa.' ",
  "sn1.37:8.1": "Khi ấy một vị thiên thần khác đọc bài kệ này trước Thế Tôn: ",
  "sn1.37:9.1": "'Những ai nào đã quy y Phật, '",
  "sn1.37:9.2": "Họ sẽ không đi đến cõi khổ; ",
  "sn1.37:9.3": "Sau khi từ bỏ thân người, ",
  "sn1.37:9.4": "Họ sẽ làm đầy đủ thân thiên thần.' ",
  "sn1.38:0.1": "Tương Ưng Bộ Kinh 1.38 ",
  "sn1.38:0.2": "4. Phẩm Satullapa ",
  "sn1.38:0.3": "Kinh Mảnh Đá ",
  "sn1.38:1.1": "Tôi nghe như vầy",
  "sn1.38:1.2": "một thời Thế Tôn trú tại Rājagaha, vườn nai Maddakucchi. ",
  "sn1.38:1.3": "Lúc bấy giờ chân Thế Tôn bị một mảnh đá đâm vào. ",
  "sn1.38:1.4": "Thế Tôn cảm thọ những cảm giác thân thể mãnh liệt, đau đớn, dữ dội, nhói buốt, khó chịu, không dễ chịu; ",
  "sn1.38:1.5": "Thế Tôn nhẫn chịu chúng với chánh niệm và tỉnh giác, không bị khuất phục. ",
  "sn1.38:1.6": "Khi ấy Thế Tôn xếp y tăng-già-lê làm bốn lớp, nằm theo kiểu nằm của sư tử ở phía hông bên phải, chồng chân lên chân, với chánh niệm và tỉnh giác. ",
  "sn1.38:2.1": "Khi ấy, bảy trăm vị thiên thần thuộc nhóm Satullapa vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Maddakucchi, đến chỗ Thế Tôn; sau khi đến, cúi đầu đảnh lễ Thế Tôn rồi đứng sang một bên. ",
  "sn1.38:2.2": "Đứng sang một bên, một vị thiên thần thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.38:2.3": "'Sa-môn Gotama thật là voi chúa! '",
  "sn1.38:2.4": "Những cảm giác thân thể đau đớn, dữ dội, nhói buốt, khó chịu, không dễ chịu phát sanh với bản chất voi chúa, Ngài nhẫn chịu với chánh niệm và tỉnh giác, không bị khuất phục.' ",
  "sn1.38:3.1": "Khi ấy một vị thiên thần khác thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.38:3.2": "'Sa-môn Gotama thật là sư tử! '",
  "sn1.38:3.3": "Những cảm giác thân thể đau đớn, dữ dội, nhói buốt, khó chịu, không dễ chịu phát sanh với bản chất sư tử, Ngài nhẫn chịu với chánh niệm và tỉnh giác, không bị khuất phục.' ",
  "sn1.38:4.1": "Khi ấy một vị thiên thần khác thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.38:4.2": "'Sa-môn Gotama thật là ngựa thuần chủng! '",
  "sn1.38:4.3": "Những cảm giác thân thể đau đớn, dữ dội, nhói buốt, khó chịu, không dễ chịu phát sanh với bản chất ngựa thuần chủng, Ngài nhẫn chịu với chánh niệm và tỉnh giác, không bị khuất phục.' ",
  "sn1.38:5.1": "Khi ấy một vị thiên thần khác thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.38:5.2": "'Sa-môn Gotama thật là bò chúa! '",
  "sn1.38:5.3": "Những cảm giác thân thể đau đớn, dữ dội, nhói buốt, khó chịu, không dễ chịu phát sanh với bản chất bò chúa, Ngài nhẫn chịu với chánh niệm và tỉnh giác, không bị khuất phục.' ",
  "sn1.38:6.1": "Khi ấy một vị thiên thần khác thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.38:6.2": "'Sa-môn Gotama thật là con vật gánh nặng! '",
  "sn1.38:6.3": "Những cảm giác thân thể đau đớn, dữ dội, nhói buốt, khó chịu, không dễ chịu phát sanh với bản chất con vật gánh nặng, Ngài nhẫn chịu với chánh niệm và tỉnh giác, không bị khuất phục.' ",
  "sn1.38:7.1": "Khi ấy một vị thiên thần khác thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.38:7.2": "'Sa-môn Gotama thật đã được điều phục! '",
  "sn1.38:7.3": "Những cảm giác thân thể đau đớn, dữ dội, nhói buốt, khó chịu, không dễ chịu phát sanh với sự đã được điều phục, Ngài nhẫn chịu với chánh niệm và tỉnh giác, không bị khuất phục.' ",
  "sn1.38:8.1": "Khi ấy một vị thiên thần khác thốt lên lời cảm hứng này trước Thế Tôn: ",
  "sn1.38:8.2": "'Hãy nhìn định đã được tu tập khéo, và tâm đã được giải thoát khéo, không hướng đến, không hướng đi, không bị ngăn giữ bởi các hành. '",
  "sn1.38:8.3": "Ai có thể nghĩ rằng có thể vượt qua một vị người-voi, người-sư tử, người-ngựa thuần chủng, người-bò chúa, người-gánh nặng, người đã được điều phục, thì trừ việc không thấy ra sao?' ",
  "sn1.38:9.1": "'Năm trăm vị Bà-la-môn tu tập khổ hạnh cùng nhau, '",
  "sn1.38:9.2": "Đi lang thang trăm năm; ",
  "sn1.38:9.3": "Tâm của họ không được giải thoát đúng đắn, ",
  "sn1.38:9.4": "Có bản chất hạ liệt, họ không đạt đến bờ kia. ",
  "sn1.38:10.1": "Bị tham ái cuốn trôi, bị trói buộc bởi giới cấm, ",
  "sn1.38:10.2": "Thực hành khổ hạnh thô cứng suốt trăm năm; ",
  "sn1.38:10.3": "Tâm của họ không được giải thoát đúng đắn, ",
  "sn1.38:10.4": "Có bản chất hạ liệt, họ không đạt đến bờ kia. ",
  "sn1.38:11.1": "Đối với kẻ ưa ngã mạn, không có sự điều phục ở đây, ",
  "sn1.38:11.2": "Không có sự tịch mặc đối với kẻ tâm không tập trung; ",
  "sn1.38:11.3": "Sống một mình trong rừng mà phóng dật, ",
  "sn1.38:11.4": "Không thể vượt qua lĩnh vực của thần chết.' ",
  "sn1.38:12.1": "'Sau khi từ bỏ ngã mạn, với tự ngã khéo định tĩnh, '",
  "sn1.38:12.2": "Tâm trong sáng, hoàn toàn giải thoát ở mọi phương; ",
  "sn1.38:12.3": "Sống một mình trong rừng, không phóng dật, ",
  "sn1.38:12.4": "Vị ấy có thể vượt qua lĩnh vực của thần chết.' ",
  "sn1.39:0.1": "Tương Ưng Bộ Kinh 1.39 ",
  "sn1.39:0.2": "4. Phẩm Satullapa ",
  "sn1.39:0.3": "Kinh Con Gái Pajjuna (I) ",
  "sn1.39:1.1": "Tôi nghe như vầy",
  "sn1.39:1.2": "một thời Thế Tôn trú tại Vesālī, Đại Lâm, tại ngôi nhà có nóc nhọn. ",
  "sn1.39:1.3": "Khi ấy, Kokanadā, con gái của Pajjuna, vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Đại Lâm, đến chỗ Thế Tôn; sau khi đến, cúi đầu đảnh lễ Thế Tôn rồi đứng sang một bên. ",
  "sn1.39:1.4": "Đứng sang một bên, thiên nữ Kokanadā, con gái của Pajjuna, đọc các bài kệ này trước Thế Tôn: ",
  "sn1.39:2.1": "'Ngài đang trú trong rừng Vesālī, '",
  "sn1.39:2.2": "Bậc Chánh Đẳng Giác, đỉnh cao của các chúng sinh; ",
  "sn1.39:2.3": "Con là Kokanadā đảnh lễ Ngài, ",
  "sn1.39:2.4": "Kokanadā, con gái của Pajjuna. ",
  "sn1.39:3.1": "Trước đây chỉ nghe qua, ",
  "sn1.39:3.2": "Pháp được bậc Nhãn Quan giác ngộ; ",
  "sn1.39:3.3": "Giờ con biết trực tiếp chứng kiến, ",
  "sn1.39:3.4": "Bậc Mâu-ni, bậc Thiện Thệ đang thuyết Pháp. ",
  "sn1.39:4.1": "Những ai đi với tâm ngu si, ",
  "sn1.39:4.2": "Phê phán Thánh Pháp; ",
  "sn1.39:4.3": "Đi đến địa ngục khủng khiếp, ",
  "sn1.39:4.4": "Chịu đựng khổ đau lâu dài. ",
  "sn1.39:5.1": "Còn những ai ở trong Thánh Pháp, ",
  "sn1.39:5.2": "Sống với nhẫn nhục và an tịnh; ",
  "sn1.39:5.3": "Sau khi từ bỏ thân người, ",
  "sn1.39:5.4": "Họ sẽ làm đầy đủ thân thiên thần.' ",
  "sn1.40:0.1": "Tương Ưng Bộ Kinh 1.40 ",
  "sn1.40:0.2": "4. Phẩm Satullapa ",
  "sn1.40:0.3": "Kinh Con Gái Pajjuna (II) ",
  "sn1.40:1.1": "Tôi nghe như vầy",
  "sn1.40:1.2": "một thời Thế Tôn trú tại Vesālī, Đại Lâm, tại ngôi nhà có nóc nhọn. ",
  "sn1.40:1.3": "Khi ấy, Cūḷakokanadā, con gái của Pajjuna, vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Đại Lâm, đến chỗ Thế Tôn; sau khi đến, cúi đầu đảnh lễ Thế Tôn rồi đứng sang một bên. ",
  "sn1.40:1.4": "Đứng sang một bên, thiên nữ Cūḷakokanadā, con gái của Pajjuna, đọc các bài kệ này trước Thế Tôn: ",
  "sn1.40:2.1": "'Con đã đến đây với vẻ sáng như ánh chớp, '",
  "sn1.40:2.2": "Kokanadā, con gái của Pajjuna; ",
  "sn1.40:2.3": "Đảnh lễ Phật và Pháp, ",
  "sn1.40:2.4": "Đọc những bài kệ có ý nghĩa này. ",
  "sn1.40:3.1": "Con có thể phân tích Pháp này theo nhiều cách, ",
  "sn1.40:3.2": "Theo từng phương diện như vậy; ",
  "sn1.40:3.3": "Con sẽ nói ý nghĩa vắn tắt, ",
  "sn1.40:3.4": "Cho đến mức tâm con có thể nắm giữ. ",
  "sn1.40:4.1": "Không làm bất kỳ điều ác nào bằng lời, bằng tâm, ",
  "sn1.40:4.2": "Hay bằng thân trong toàn thế giới; ",
  "sn1.40:4.3": "Từ bỏ các dục, với chánh niệm và tỉnh giác, ",
  "sn1.40:4.4": "Không theo đuổi khổ đau là điều bất lợi.' ",
  "sn1.40:4.5": "Phẩm Satullapa, thứ tư. ",
  "sn1.40:5.0": "Tóm lược phẩm này ",
  "sn1.40:5.1": "Bậc thiện, keo kiệt, lành thay, ",
  "sn1.40:5.2": "Không có gì, thiên thần hay chê bai; ",
  "sn1.40:5.3": "Đức tin, đại hội, mảnh đá, ",
  "sn1.40:5.4": "Và hai con gái Pajjuna.' ",
  "sn1.41:0.1": "Tương Ưng Bộ Kinh 1.41 ",
  "sn1.41:0.2": "5. Phẩm Đang Bốc Lửa ",
  "sn1.41:0.3": "Kinh Đang Bốc Lửa ",
  "sn1.41:1.1": "Tôi nghe như vầy",
  "sn1.41:1.2": "một thời Thế Tôn trú tại Sāvatthi, Jetavana, tinh xá của Anāthapiṇḍika. ",
  "sn1.41:1.3": "Khi ấy, một vị thiên thần vào lúc nửa đêm, với vẻ đẹp rực rỡ soi sáng toàn bộ Jetavana, đến chỗ Thế Tôn; sau khi đến, cúi đầu đảnh lễ Thế Tôn rồi đứng sang một bên. ",
  "sn1.41:1.4": "Đứng sang một bên, vị thiên thần ấy đọc các bài kệ này trước Thế Tôn: ",
  "sn1.41:2.1": "'Khi ngôi nhà đang bốc lửa, '",
  "sn1.41:2.2": "Đồ vật nào được mang ra ngoài; ",
  "sn1.41:2.3": "Đồ vật đó mang lại lợi ích cho người ấy, ",
  "sn1.41:2.4": "Chứ không phải những gì bị đốt cháy ở đó. ",
  "sn1.41:3.1": "Cũng vậy, thế gian đang bốc lửa, ",
  "sn1.41:3.2": "Bởi tuổi già và cái chết; ",
  "sn1.41:3.3": "Hãy mang ra ngoài bằng cách bố thí, ",
  "sn1.41:3.4": "Những gì đã bố thí là đã được mang ra tốt. ",
  "sn1.41:4.1": "Những gì đã bố thí mang lại quả hạnh phúc, ",
  "sn1.41:4.2": "Những gì chưa bố thí thì không như vậy; ",
  "sn1.41:4.3": "Kẻ trộm cướp lấy, vua tịch thu, ",
  "sn1.41:4.4": "Lửa đốt cháy và mất mát xảy ra. ",
  "sn1.41:5.1": "Rồi cuối cùng phải từ bỏ, ",
  "sn1.41:5.2": "Thân xác cùng với tất cả tài sản; ",
  "sn1.41:5.3": "Bậc trí biết điều này, ",
  "sn1.41:5.4": "Hãy thọ hưởng và bố thí; ",
  "sn1.41:5.5": "Sau khi bố thí và thọ hưởng theo khả năng, ",
  "sn1.41:5.6": "Không bị chê trách, vị ấy đến cõi trời.' ",
  "sn1.42:0.1": "Tương Ưng Bộ Kinh 1.42 ",
  "sn1.42:0.2": "5. Phẩm Đang Bốc Lửa ",
  "sn1.42:0.3": "Kinh Bố Thí Cái Gì ",
  "sn1.42:1.1": "'Bố thí cái gì thì cho sức mạnh, '",
  "sn1.42:1.2": "Bố thí cái gì thì cho sắc đẹp; ",
  "sn1.42:1.3": "Bố thí cái gì thì cho hạnh phúc, ",
  "sn1.42:1.4": "Bố thí cái gì thì cho mắt sáng; ",
  "sn1.42:1.5": "Ai là người bố thí tất cả, ",
  "sn1.42:1.6": "Hãy nói cho ta khi được hỏi.' ",
  "sn1.42:2.1": "'Bố thí thức ăn thì cho sức mạnh, '",
  "sn1.42:2.2": "Bố thí y phục thì cho sắc đẹp; ",
  "sn1.42:2.3": "Bố thí phương tiện đi lại thì cho hạnh phúc, ",
  "sn1.42:2.4": "Bố thí đèn đuốc thì cho mắt sáng. ",
  "sn1.42:3.1": "Người bố thí tất cả là người, ",
  "sn1.42:3.2": "Bố thí nơi trú ngụ; ",
  "sn1.42:3.3": "Người bố thí bất tử là người, ",
  "sn1.42:3.4": "Giảng dạy Pháp.' ",
  "sn1.43:0.1": "Tương Ưng Bộ Kinh 1.43 ",
  "sn1.43:0.2": "5. Phẩm Đang Bốc Lửa ",
  "sn1.43:0.3": "Kinh Thức Ăn ",
  "sn1.43:1.1": "'Cả hai trời và người đều vui mừng vì thức ăn, '",
  "sn1.43:1.2": "Thức ăn là thứ mà cả hai hoan hỷ; ",
  "sn1.43:1.3": "Vậy ai là vị thiên thần nào đó, ",
  "sn1.43:1.4": "Mà không hoan hỷ vì thức ăn?' ",
  "sn1.43:2.1": "'Những ai bố thí với lòng tin, '",
  "sn1.43:2.2": "Với tâm trong sáng; ",
  "sn1.43:2.3": "Chính thức ăn ấy theo họ, ",
  "sn1.43:2.4": "Ở đời này và đời sau. ",
  "sn1.43:3.1": "Do đó hãy từ bỏ keo kiệt, ",
  "sn1.43:3.2": "Hãy bố thí, chiến thắng cấu uế; ",
  "sn1.43:3.3": "Các công đức ở đời sau, ",
  "sn1.43:3.4": "Là nơi nương tựa cho chúng sinh.' ",
  "sn1.44:0.1": "Tương Ưng Bộ Kinh 1.44 ",
  "sn1.44:0.2": "5. Phẩm Đang Bốc Lửa ",
  "sn1.44:0.3": "Kinh Một Gốc Rễ ",
  "sn1.44:1.1": "'Một gốc rễ, hai xoáy cuộn, '",
  "sn1.44:1.2": "Ba cấu uế, năm lớp trải ra; ",
  "sn1.44:1.3": "Đại dương mười hai xoáy cuộn, ",
  "sn1.44:1.4": "Bậc ẩn sĩ đã vượt qua vực thẳm.' ",
  "sn1.45:0.1": "Tương Ưng Bộ Kinh 1.45 ",
  "sn1.45:0.2": "5. Phẩm Đang Bốc Lửa ",
  "sn1.45:0.3": "Kinh Cao Quý ",
  "sn1.45:1.1": "'Hãy nhìn vị ấy, danh tiếng vô thượng, khéo thấy điều vi tế, '",
  "sn1.45:1.2": "Người cho trí tuệ, không bị trói buộc vào nơi trú ngụ dục lạc; ",
  "sn1.45:1.3": "Hãy nhìn vị ấy biết tất cả, có trí tuệ sâu sắc, ",
  "sn1.45:1.4": "Bậc đại ẩn sĩ bước đi trên con đường Thánh.' ",
  "sn1.46:0.1": "Tương Ưng Bộ Kinh 1.46 ",
  "sn1.46:0.2": "5. Phẩm Đang Bốc Lửa ",
  "sn1.46:0.3": "Kinh Nàng Tiên ",
  "sn1.46:1.1": "'Vang vọng bởi đám tiên nữ, '",
  "sn1.46:1.2": "Được các dạ-xoa tụ hội; ",
  "sn1.46:1.3": "Khu rừng gọi là Moha (Si mê), ",
  "sn1.46:1.4": "Làm sao để thoát ra được?' ",
  "sn1.46:2.1": "'Con đường tên là Thẳng Thắn, '",
  "sn1.46:2.2": "Phương hướng tên là Không Sợ Hãi; ",
  "sn1.46:2.3": "Cỗ xe tên là Không Ồn Ào, ",
  "sn1.46:2.4": "Được trang bị với các bánh xe Pháp. ",
  "sn1.46:3.1": "Tàm quý là lan can đỡ của xe, ",
  "sn1.46:3.2": "Chánh niệm là hàng rào bảo vệ; ",
  "sn1.46:3.3": "Ta gọi Pháp là người đánh xe, ",
  "sn1.46:3.4": "Chánh kiến là người chạy phía trước. ",
  "sn1.46:4.1": "Ai có cỗ xe như vậy, ",
  "sn1.46:4.2": "Dù là phụ nữ hay đàn ông; ",
  "sn1.46:4.3": "Người ấy thật sự với cỗ xe này, ",
  "sn1.46:4.4": "Gần với Niết-bàn.' ",
  "sn1.47:0.1": "Tương Ưng Bộ Kinh 1.47 ",
  "sn1.47:0.2": "5. Phẩm Đang Bốc Lửa ",
  "sn1.47:0.3": "Kinh Trồng Cây ",
  "sn1.47:1.1": "'Những ai ngày và đêm, '",
  "sn1.47:1.2": "Công đức luôn luôn tăng trưởng; ",
  "sn1.47:1.3": "Những người an trú trong Pháp, đầy đủ giới hạnh, ",
  "sn1.47:1.4": "Những người nào đi đến cõi trời?' ",
  "sn1.47:2.1": "'Những ai trồng vườn, trồng rừng, '",
  "sn1.47:2.2": "Những người xây cầu; ",
  "sn1.47:2.3": "Những ai làm giếng và ao, ",
  "sn1.47:2.4": "Và bố thí nơi trú ngụ. ",
  "sn1.47:3.1": "Đối với họ, ngày và đêm, ",
  "sn1.47:3.2": "Công đức luôn luôn tăng trưởng; ",
  "sn1.47:3.3": "Những người an trú trong Pháp, đầy đủ giới hạnh, ",
  "sn1.47:3.4": "Những người ấy đi đến cõi trời.' ",
  "sn1.48:0.1": "Tương Ưng Bộ Kinh 1.48 ",
  "sn1.48:0.2": "5. Phẩm Đang Bốc Lửa ",
  "sn1.48:0.3": "Kinh Jetavana ",
  "sn1.48:1.1": "'Đây chính là Jetavana ấy, '",
  "sn1.48:1.2": "Được các bậc ẩn sĩ tụ hội; ",
  "sn1.48:1.3": "Được bậc Pháp Vương trú ngụ, ",
  "sn1.48:1.4": "Là nơi tạo nên niềm vui cho ta. ",
  "sn1.48:2.1": "Nghiệp, minh, pháp, ",
  "sn1.48:2.2": "Giới và đời sống tối thượng; ",
  "sn1.48:2.3": "Nhờ đây mà người được thanh tịnh, ",
  "sn1.48:2.4": "Không phải nhờ dòng dõi hay tài sản. ",
  "sn1.48:3.1": "Do đó bậc trí, ",
  "sn1.48:3.2": "Nhìn thấy lợi ích của mình; ",
  "sn1.48:3.3": "Khéo tư duy Pháp, ",
  "sn1.48:3.4": "Như vậy được thanh tịnh tại đó. ",
  "sn1.48:4.1": "Như Sāriputta, với trí tuệ, ",
  "sn1.48:4.2": "Với giới và an tịnh; ",
  "sn1.48:4.3": "Tỳ Kheo nào đạt đến bờ kia, ",
  "sn1.48:4.4": "Tối đa chỉ có thể bằng vị ấy mà thôi.' ",
  "sn1.49:0.1": "Tương Ưng Bộ Kinh 1.49 ",
  "sn1.49:0.2": "5. Phẩm Đang Bốc Lửa ",
  "sn1.49:0.3": "Kinh Keo Kiệt ",
  "sn1.49:1.1": "'Những kẻ keo kiệt ở đây trong thế gian, '",
  "sn1.49:1.2": "Bủn xỉn, phỉ báng; ",
  "sn1.49:1.3": "Những người ngăn cản người khác bố thí, ",
  "sn1.49:1.4": "Gây chướng ngại cho người bố thí. ",
  "sn1.49:2.1": "Quả báo của họ là gì, ",
  "sn1.49:2.2": "Và đời sau của họ như thế nào; ",
  "sn1.49:2.3": "Chúng con đến hỏi Thế Tôn, ",
  "sn1.49:2.4": "Làm sao chúng con biết được điều này?' ",
  "sn1.49:3.1": "'Những kẻ keo kiệt ở đây trong thế gian, '",
  "sn1.49:3.2": "Bủn xỉn, phỉ báng; ",
  "sn1.49:3.3": "Những người ngăn cản người khác bố thí, ",
  "sn1.49:3.4": "Gây chướng ngại cho người bố thí. ",
  "sn1.49:4.1": "Đọa vào địa ngục, bàng sanh, ",
  "sn1.49:4.2": "Hay cõi Yama; ",
  "sn1.49:4.3": "Nếu trở lại làm người, ",
  "sn1.49:4.4": "Sinh vào gia đình nghèo khổ. ",
  "sn1.49:5.1": "Y phục, thức ăn, khoái lạc và vui chơi, ",
  "sn1.49:5.2": "Khó có được ở đó; ",
  "sn1.49:5.3": "Kẻ ngu mong đợi từ người khác, ",
  "sn1.49:5.4": "Cũng không có được điều đó; ",
  "sn1.49:5.5": "Quả báo hiện tại như vậy, ",
  "sn1.49:5.6": "Và đời sau là cảnh khổ.' ",
  "sn1.49:6.1": "'Vậy chúng con đã hiểu điều này, '",
  "sn1.49:6.2": "Chúng con hỏi điều khác, hỡi Gotama; ",
  "sn1.49:6.3": "Những ai đạt được thân người ở đây, ",
  "sn1.49:6.4": "Rộng lượng, không keo kiệt. ",
  "sn1.49:7.1": "Có tịnh tín với Phật và Pháp, ",
  "sn1.49:7.2": "Và có lòng kính trọng sâu sắc với Tăng; ",
  "sn1.49:7.3": "Quả báo của họ là gì, ",
  "sn1.49:7.4": "Và đời sau của họ như thế nào; ",
  "sn1.49:7.5": "Chúng con đến hỏi Thế Tôn, ",
  "sn1.49:7.6": "Làm sao chúng con biết được điều này?' ",
  "sn1.49:8.1": "'Những ai đạt được thân người ở đây, '",
  "sn1.49:8.2": "Rộng lượng, không keo kiệt; ",
  "sn1.49:8.3": "Có tịnh tín với Phật và Pháp, ",
  "sn1.49:8.4": "Và có lòng kính trọng sâu sắc với Tăng; ",
  "sn1.49:8.5": "Những cõi trời chiếu sáng, ",
  "sn1.49:8.6": "Nơi họ được tái sanh. ",
  "sn1.49:9.1": "Nếu trở lại làm người, ",
  "sn1.49:9.2": "Sinh vào gia đình giàu có; ",
  "sn1.49:9.3": "Y phục, thức ăn, khoái lạc và vui chơi, ",
  "sn1.49:9.4": "Dễ dàng có được ở đó. ",
  "sn1.49:10.1": "Họ thọ hưởng tài sản của người khác, ",
  "sn1.49:10.2": "Như vị vua cai trị; ",
  "sn1.49:10.3": "Quả báo hiện tại như vậy, ",
  "sn1.49:10.4": "Và đời sau là cảnh lành.' ",
  "sn1.50:0.1": "Tương Ưng Bộ Kinh 1.50 ",
  "sn1.50:0.2": "5. Phẩm Đang Bốc Lửa ",
  "sn1.50:0.3": "Kinh Ghaṭīkāra ",
  "sn1.50:1.1": "'Bảy Tỳ Kheo đã sanh vào cõi Avihā, '",
  "sn1.50:1.2": "Được giải thoát; ",
  "sn1.50:1.3": "Tham và sân đã diệt tận, ",
  "sn1.50:1.4": "Đã vượt qua sự chấp thủ ở đời.' ",
  "sn1.50:2.1": "'Những ai đã vượt qua bùn lầy, '",
  "sn1.50:2.2": "Lĩnh vực của thần chết rất khó vượt qua; ",
  "sn1.50:2.3": "Những ai từ bỏ thân người, ",
  "sn1.50:2.4": "Đã vượt qua sự kết nối cõi trời?' ",
  "sn1.50:3.1": "'Upaka, Palagaṇḍa, '",
  "sn1.50:3.2": "Và Pukkusāti là ba vị; ",
  "sn1.50:3.3": "Bhaddiyo, Khaṇḍadeva, ",
  "sn1.50:3.4": "Bāhuraggī và Siṅgiya; ",
  "sn1.50:3.5": "Họ từ bỏ thân người, ",
  "sn1.50:3.6": "Đã vượt qua sự kết nối cõi trời.' ",
  "sn1.50:4.1": "'Ngài nói tốt về họ, '",
  "sn1.50:4.2": "Những người đã từ bỏ bẫy của Ma-vương; ",
  "sn1.50:4.3": "Nhờ biết Pháp của ai, ",
  "sn1.50:4.4": "Mà họ cắt đứt trói buộc của hiện hữu?' ",
  "sn1.50:5.1": "'Không phải từ ai khác ngoài Thế Tôn, '",
  "sn1.50:5.2": "Không phải từ ai khác ngoài giáo huấn của Ngài; ",
  "sn1.50:5.3": "Nhờ biết Pháp của Ngài, ",
  "sn1.50:5.4": "Mà họ cắt đứt trói buộc của hiện hữu. ",
  "sn1.50:6.1": "Nơi mà danh và sắc, ",
  "sn1.50:6.2": "Đoạn diệt không còn dư sót; ",
  "sn1.50:6.3": "Nhờ biết Pháp của Ngài ở đây, ",
  "sn1.50:6.4": "Mà họ cắt đứt trói buộc của hiện hữu.' ",
  "sn1.50:7.1": "'Ngài nói lời sâu sắc, '",
  "sn1.50:7.2": "Khó hiểu, khó giác ngộ; ",
  "sn1.50:7.3": "Biết Pháp của ai, ",
  "sn1.50:7.4": "Mà Ngài nói những lời như vậy?' ",
  "sn1.50:8.1": "'Trước đây ta là thợ gốm, '",
  "sn1.50:8.2": "Ghaṭīkāra ở Vekaḷiṅga; ",
  "sn1.50:8.3": "Ta là người phụng dưỡng cha mẹ, ",
  "sn1.50:8.4": "Là cư sĩ của Kassapa. ",
  "sn1.50:9.1": "Ta đã từ bỏ pháp dâm dục, ",
  "sn1.50:9.2": "Sống đời phạm hạnh không tham ái; ",
  "sn1.50:9.3": "Ta đã là người cùng làng với ông, ",
  "sn1.50:9.4": "Ta đã là bạn cũ của ông. ",
  "sn1.50:10.1": "Chính ta biết những vị đó, ",
  "sn1.50:10.2": "Bảy Tỳ Kheo đã được giải thoát; ",
  "sn1.50:10.3": "Tham và sân đã diệt tận, ",
  "sn1.50:10.4": "Đã vượt qua sự chấp thủ ở đời.' ",
  "sn1.50:11.1": "'Đúng như vậy lúc đó, '",
  "sn1.50:11.2": "Như Ngài nói, hỡi Bhaggava; ",
  "sn1.50:11.3": "Trước đây là thợ gốm, ",
  "sn1.50:11.4": "Ghaṭīkāra ở Vekaḷiṅga; ",
  "sn1.50:11.5": "Là người phụng dưỡng cha mẹ, ",
  "sn1.50:11.6": "Là cư sĩ của Kassapa. ",
  "sn1.50:12.1": "Đã từ bỏ pháp dâm dục, ",
  "sn1.50:12.2": "Sống đời phạm hạnh không tham ái; ",
  "sn1.50:12.3": "Đã là người cùng làng với ta, ",
  "sn1.50:12.4": "Đã là bạn cũ của ta.' ",
  "sn1.50:13.1": "'Đây là cuộc gặp gỡ, '",
  "sn1.50:13.2": "Của hai người bạn cũ; ",
  "sn1.50:13.3": "Cả hai đã tu tập, ",
  "sn1.50:13.4": "Mang thân cuối cùng.' ",
  "sn1.50:13.5": "Phẩm Đang Bốc Lửa, thứ năm. ",
  "sn1.50:14.0": "Tóm lược phẩm này ",
  "sn1.50:14.1": "Đang bốc lửa, bố thí cái gì, thức ăn, ",
  "sn1.50:14.2": "Một gốc rễ, cao quý; ",
  "sn1.50:14.3": "Nàng tiên, trồng cây, Jetavana, ",
  "sn1.50:14.4": "Keo kiệt và Ghaṭīkāra.' ",
  "sn1.51:0.1": "Tương Ưng Bộ Kinh 1.51 ",
  "sn1.51:0.2": "6. Phẩm Tuổi Già ",
  "sn1.51:0.3": "Kinh Tuổi Già ",
  "sn1.51:1.1": "'Cái gì là tốt đẹp cho đến tuổi già, '",
  "sn1.51:1.2": "Cái gì được khéo thiết lập; ",
  "sn1.51:1.3": "Cái gì là châu báu của con người, ",
  "sn1.51:1.4": "Cái gì là thứ khó cướp đoạt bởi kẻ trộm?' ",
  "sn1.51:2.1": "'Giới là tốt đẹp cho đến tuổi già, '",
  "sn1.51:2.2": "Đức tin được khéo thiết lập; ",
  "sn1.51:2.3": "Trí tuệ là châu báu của con người, ",
  "sn1.51:2.4": "Phước là thứ khó cướp đoạt bởi kẻ trộm.' ",
  "sn1.52:0.1": "Tương Ưng Bộ Kinh 1.52 ",
  "sn1.52:0.2": "6. Phẩm Tuổi Già ",
  "sn1.52:0.3": "Kinh Không Già ",
  "sn1.52:1.1": "'Cái gì là tốt đẹp khi không già, '",
  "sn1.52:1.2": "Cái gì được khéo quyết định; ",
  "sn1.52:1.3": "Cái gì là châu báu của con người, ",
  "sn1.52:1.4": "Cái gì là thứ kẻ trộm không thể lấy đi?' ",
  "sn1.52:2.1": "'Giới là tốt đẹp khi không già, '",
  "sn1.52:2.2": "Đức tin được khéo quyết định; ",
  "sn1.52:2.3": "Trí tuệ là châu báu của con người, ",
  "sn1.52:2.4": "Phước là thứ kẻ trộm không thể lấy đi.' ",
  "sn1.53:0.1": "Tương Ưng Bộ Kinh 1.53 ",
  "sn1.53:0.2": "6. Phẩm Tuổi Già ",
  "sn1.53:0.3": "Kinh Bạn Bè ",
  "sn1.53:1.1": "'Ai là bạn khi đi xa, '",
  "sn1.53:1.2": "Ai là bạn ở nhà; ",
  "sn1.53:1.3": "Ai là bạn khi có việc cần, ",
  "sn1.53:1.4": "Ai là bạn ở đời sau?' ",
  "sn1.53:2.1": "'Đoàn lữ hành là bạn khi đi xa, '",
  "sn1.53:2.2": "Mẹ là bạn ở nhà; ",
  "sn1.53:2.3": "Bạn đồng hành là bạn khi có việc cần, ",
  "sn1.53:2.4": "Là người bạn mãi mãi; ",
  "sn1.53:2.5": "Những phước đức tự mình làm, ",
  "sn1.53:2.6": "Đó là bạn ở đời sau.' ",
  "sn1.54:0.1": "Tương Ưng Bộ Kinh 1.54 ",
  "sn1.54:0.2": "6. Phẩm Tuổi Già ",
  "sn1.54:0.3": "Kinh Nền Tảng ",
  "sn1.54:1.1": "'Cái gì là nền tảng của con người, '",
  "sn1.54:1.2": "Cái gì là người bạn tốt nhất ở đây; ",
  "sn1.54:1.3": "Các sinh vật nương vào cái gì để sống, ",
  "sn1.54:1.4": "Những chúng sinh nương vào đất?' ",
  "sn1.54:2.1": "'Con cái là nền tảng của con người, '",
  "sn1.54:2.2": "Người vợ là người bạn tốt nhất; ",
  "sn1.54:2.3": "Các sinh vật nương vào mưa để sống, ",
  "sn1.54:2.4": "Những chúng sinh nương vào đất.' ",
  "sn1.55:0.1": "Tương Ưng Bộ Kinh 1.55 ",
  "sn1.55:0.2": "6. Phẩm Tuổi Già ",
  "sn1.55:0.3": "Kinh Người Phát Sanh (I) ",
  "sn1.55:1.1": "'Cái gì làm sanh khởi người, '",
  "sn1.55:1.2": "Cái gì chạy vội vàng theo người ấy; ",
  "sn1.55:1.3": "Cái gì dẫn người đến luân hồi, ",
  "sn1.55:1.4": "Cái gì là điều đáng sợ lớn nhất của người ấy?' ",
  "sn1.55:2.1": "'Tham ái làm sanh khởi người, '",
  "sn1.55:2.2": "Tâm chạy vội vàng theo người ấy; ",
  "sn1.55:2.3": "Chúng sinh dẫn đến luân hồi, ",
  "sn1.55:2.4": "Khổ đau là điều đáng sợ lớn nhất của người ấy.' ",
  "sn1.56:0.1": "Tương Ưng Bộ Kinh 1.56 ",
  "sn1.56:0.2": "6. Phẩm Tuổi Già ",
  "sn1.56:0.3": "Kinh Người Phát Sanh (II) ",
  "sn1.56:1.1": "'Cái gì làm sanh khởi người, '",
  "sn1.56:1.2": "Cái gì chạy vội vàng theo người ấy; ",
  "sn1.56:1.3": "Cái gì dẫn người đến luân hồi, ",
  "sn1.56:1.4": "Từ cái gì mà không được giải thoát?' ",
  "sn1.56:2.1": "'Tham ái làm sanh khởi người, '",
  "sn1.56:2.2": "Tâm chạy vội vàng theo người ấy; ",
  "sn1.56:2.3": "Chúng sinh dẫn đến luân hồi, ",
  "sn1.56:2.4": "Từ khổ đau mà không được giải thoát.' ",
  "sn1.57:0.1": "Tương Ưng Bộ Kinh 1.57 ",
  "sn1.57:0.2": "6. Phẩm Tuổi Già ",
  "sn1.57:0.3": "Kinh Người Phát Sanh (III) ",
  "sn1.57:1.1": "'Cái gì làm sanh khởi người, '",
  "sn1.57:1.2": "Cái gì chạy vội vàng theo người ấy; ",
  "sn1.57:1.3": "Cái gì dẫn người đến luân hồi, ",
  "sn1.57:1.4": "Cái gì là chỗ nương tựa của người ấy?' ",
  "sn1.57:2.1": "'Tham ái làm sanh khởi người, '",
  "sn1.57:2.2": "Tâm chạy vội vàng theo người ấy; ",
  "sn1.57:2.3": "Chúng sinh dẫn đến luân hồi, ",
  "sn1.57:2.4": "Nghiệp là chỗ nương tựa của người ấy.' ",
  "sn1.58:0.1": "Tương Ưng Bộ Kinh 1.58 ",
  "sn1.58:0.2": "6. Phẩm Tuổi Già ",
  "sn1.58:0.3": "Kinh Tà Đạo ",
  "sn1.58:1.1": "'Cái gì được gọi là tà đạo, '",
  "sn1.58:1.2": "Ngày đêm tiêu hao cái gì; ",
  "sn1.58:1.3": "Cái gì là cấu uế của đời phạm hạnh, ",
  "sn1.58:1.4": "Cái là nước tắm không có nước?' ",
  "sn1.58:2.1": "'Tham được gọi là tà đạo, '",
  "sn1.58:2.2": "Tuổi trẻ tiêu hao ngày đêm; ",
  "sn1.58:2.3": "Phụ nữ là cấu uế của đời phạm hạnh, ",
  "sn1.58:2.4": "Người đời bị trói buộc ở đây; ",
  "sn1.58:2.5": "Khổ hạnh và đời phạm hạnh, ",
  "sn1.58:2.6": "Đó là nước tắm không có nước.' ",
  "sn1.59:0.1": "Tương Ưng Bộ Kinh 1.59 ",
  "sn1.59:0.2": "6. Phẩm Tuổi Già ",
  "sn1.59:0.3": "Kinh Người Bạn Đồng Hành ",
  "sn1.59:1.1": "'Cái gì là người bạn đồng hành của người, '",
  "sn1.59:1.2": "Cái gì dẫn dắt người ấy; ",
  "sn1.59:1.3": "Con người hoan hỷ với cái gì, ",
  "sn1.59:1.4": "Thì được giải thoát khỏi mọi khổ đau?' ",
  "sn1.59:2.1": "'Đức tin là người bạn đồng hành của người, '",
  "sn1.59:2.2": "Trí tuệ dẫn dắt người ấy; ",
  "sn1.59:2.3": "Con người hoan hỷ với Niết-bàn, ",
  "sn1.59:2.4": "Thì được giải thoát khỏi mọi khổ đau.' ",
  "sn1.60:0.1": "Tương Ưng Bộ Kinh 1.60 ",
  "sn1.60:0.2": "6. Phẩm Tuổi Già ",
  "sn1.60:0.3": "Kinh Nhà Thơ ",
  "sn1.60:1.1": "'Cái gì là nguồn gốc của các bài kệ, '",
  "sn1.60:1.2": "Cái gì là văn từ của chúng; ",
  "sn1.60:1.3": "Các bài kệ nương vào cái gì, ",
  "sn1.60:1.4": "Cái gì là chỗ trú của các bài kệ?' ",
  "sn1.60:2.1": "'Tâm hứng là nguồn gốc của các bài kệ, '",
  "sn1.60:2.2": "Chữ cái là văn từ của chúng; ",
  "sn1.60:2.3": "Các bài kệ nương vào danh, ",
  "sn1.60:2.4": "Nhà thơ là chỗ trú của các bài kệ.' ",
  "sn1.60:2.5": "Phẩm Tuổi Già, thứ sáu. ",
  "sn1.60:3.0": "Tóm lược phẩm này ",
  "sn1.60:3.1": "Tuổi già, không già, bạn bè, ",
  "sn1.60:3.2": "Nền tảng, ba bài người phát sanh; ",
  "sn1.60:3.3": "Tà đạo, người bạn đồng hành, ",
  "sn1.60:3.4": "Nhà thơ hoàn thành phẩm này.' ",
  "sn1.61:0.1": "Tương Ưng Bộ Kinh 1.61 ",
  "sn1.61:0.2": "7. Phẩm Con Đường ",
  "sn1.61:0.3": "Kinh Danh ",
  "sn1.61:1.1": "'Cái gì vượt qua tất cả, '",
  "sn1.61:1.2": "Không có gì lớn hơn cái gì; ",
  "sn1.61:1.3": "Tất cả đều phụ thuộc vào một pháp nào, ",
  "sn1.61:1.4": "Tất cả đều nằm trong quyền lực của gì?' ",
  "sn1.61:2.1": "'Danh vượt qua tất cả, '",
  "sn1.61:2.2": "Không có gì lớn hơn danh; ",
  "sn1.61:2.3": "Tất cả đều phụ thuộc vào một pháp danh, ",
  "sn1.61:2.4": "Tất cả đều nằm trong quyền lực của danh.' ",
  "sn1.62:0.1": "Tương Ưng Bộ Kinh 1.62 ",
  "sn1.62:0.2": "7. Phẩm Con Đường ",
  "sn1.62:0.3": "Kinh Tâm ",
  "sn1.62:1.1": "'Điều gì dẫn dắt thế gian, '",
  "sn1.62:1.2": "Điều gì lôi kéo thế gian; ",
  "sn1.62:1.3": "Tất cả đều phụ thuộc vào một pháp nào, ",
  "sn1.62:1.4": "Tất cả đều nằm trong quyền lực của gì?' ",
  "sn1.62:2.1": "'Tâm dẫn dắt thế gian, '",
  "sn1.62:2.2": "Tâm lôi kéo thế gian; ",
  "sn1.62:2.3": "Tất cả đều phụ thuộc vào một pháp tâm, ",
  "sn1.62:2.4": "Tất cả đều nằm trong quyền lực của tâm.' ",
  "sn1.63:0.1": "Tương Ưng Bộ Kinh 1.63 ",
  "sn1.63:0.2": "7. Phẩm Con Đường ",
  "sn1.63:0.3": "Kinh Tham Ái ",
  "sn1.63:1.1": "'Điều gì dẫn dắt thế gian, '",
  "sn1.63:1.2": "Điều gì lôi kéo thế gian; ",
  "sn1.63:1.3": "Tất cả đều phụ thuộc vào một pháp nào, ",
  "sn1.63:1.4": "Tất cả đều nằm trong quyền lực của gì?' ",
  "sn1.63:2.1": "'Tham ái dẫn dắt thế gian, '",
  "sn1.63:2.2": "Tham ái lôi kéo thế gian; ",
  "sn1.63:2.3": "Tất cả đều phụ thuộc vào một pháp tham ái, ",
  "sn1.63:2.4": "Tất cả đều nằm trong quyền lực của tham ái.' ",
  "sn1.64:0.1": "Tương Ưng Bộ Kinh 1.64 ",
  "sn1.64:0.2": "7. Phẩm Con Đường ",
  "sn1.64:0.3": "Kinh Kiết Sử ",
  "sn1.64:1.1": "'Điều gì trói buộc thế gian, '",
  "sn1.64:1.2": "Điều gì là sự di chuyển của thế gian; ",
  "sn1.64:1.3": "Do đoạn trừ điều gì, ",
  "sn1.64:1.4": "Được gọi là Niết-bàn?' ",
  "sn1.64:2.1": "'Hỷ ái là kiết sử của thế gian, '",
  "sn1.64:2.2": "Tầm là sự di chuyển của thế gian; ",
  "sn1.64:2.3": "Do đoạn trừ tham ái, ",
  "sn1.64:2.4": "Được gọi là Niết-bàn.' ",
  "sn1.65:0.1": "Tương Ưng Bộ Kinh 1.65 ",
  "sn1.65:0.2": "7. Phẩm Con Đường ",
  "sn1.65:0.3": "Kinh Trói Buộc ",
  "sn1.65:1.1": "'Điều gì trói chặt thế gian, '",
  "sn1.65:1.2": "Điều gì là sự di chuyển của thế gian; ",
  "sn1.65:1.3": "Do đoạn trừ điều gì, ",
  "sn1.65:1.4": "Mà cắt đứt tất cả trói buộc?' ",
  "sn1.65:2.1": "'Hỷ ái trói chặt thế gian, '",
  "sn1.65:2.2": "Tầm là sự di chuyển của thế gian; ",
  "sn1.65:2.3": "Do đoạn trừ tham ái, ",
  "sn1.65:2.4": "Mà cắt đứt tất cả trói buộc.' ",
  "sn1.66:0.1": "Tương Ưng Bộ Kinh 1.66 ",
  "sn1.66:0.2": "7. Phẩm Con Đường ",
  "sn1.66:0.3": "Kinh Bị Đánh Mạnh ",
  "sn1.66:1.1": "'Thế gian bị đánh mạnh bởi cái gì, '",
  "sn1.66:1.2": "Bị bao vây bởi cái gì; ",
  "sn1.66:1.3": "Bị đâm bởi mũi tên gì, ",
  "sn1.66:1.4": "Luôn luôn bị đốt cháy bởi cái gì?' ",
  "sn1.66:2.1": "'Thế gian bị đánh mạnh bởi thần chết, '",
  "sn1.66:2.2": "Bị bao vây bởi tuổi già; ",
  "sn1.66:2.3": "Bị đâm bởi mũi tên tham ái, ",
  "sn1.66:2.4": "Luôn luôn bị đốt cháy bởi dục vọng.' ",
  "sn1.67:0.1": "Tương Ưng Bộ Kinh 1.67 ",
  "sn1.67:0.2": "7. Phẩm Con Đường ",
  "sn1.67:0.3": "Kinh Bị Bẫy ",
  "sn1.67:1.1": "'Thế gian bị bẫy bởi cái gì, '",
  "sn1.67:1.2": "Bị bao vây bởi cái gì; ",
  "sn1.67:1.3": "Thế gian bị che khuất bởi cái gì, ",
  "sn1.67:1.4": "Thế gian nằm tựa vào cái gì?' ",
  "sn1.67:2.1": "'Thế gian bị bẫy bởi tham ái, '",
  "sn1.67:2.2": "Bị bao vây bởi tuổi già; ",
  "sn1.67:2.3": "Thế gian bị che khuất bởi thần chết, ",
  "sn1.67:2.4": "Thế gian nằm tựa vào khổ đau.' ",
  "sn1.68:0.1": "Tương Ưng Bộ Kinh 1.68 ",
  "sn1.68:0.2": "7. Phẩm Con Đường ",
  "sn1.68:0.3": "Kinh Bị Che Khuất ",
  "sn1.68:1.1": "'Thế gian bị che khuất bởi cái gì, '",
  "sn1.68:1.2": "Thế gian nằm tựa vào cái gì; ",
  "sn1.68:1.3": "Thế gian bị bẫy bởi cái gì, ",
  "sn1.68:1.4": "Bị bao vây bởi cái gì?' ",
  "sn1.68:2.1": "'Thế gian bị che khuất bởi thần chết, '",
  "sn1.68:2.2": "Thế gian nằm tựa vào khổ đau; ",
  "sn1.68:2.3": "Thế gian bị bẫy bởi tham ái, ",
  "sn1.68:2.4": "Bị bao vây bởi tuổi già.' ",
  "sn1.69:0.1": "Tương Ưng Bộ Kinh 1.69 ",
  "sn1.69:0.2": "7. Phẩm Con Đường ",
  "sn1.69:0.3": "Kinh Ước Muốn ",
  "sn1.69:1.1": "'Thế gian bị trói buộc bởi cái gì, '",
  "sn1.69:1.2": "Do điều phục cái gì mà được giải thoát; ",
  "sn1.69:1.3": "Do đoạn trừ điều gì, ",
  "sn1.69:1.4": "Mà cắt đứt tất cả trói buộc?' ",
  "sn1.69:2.1": "'Thế gian bị trói buộc bởi ước muốn, '",
  "sn1.69:2.2": "Do điều phục ước muốn mà được giải thoát; ",
  "sn1.69:2.3": "Do đoạn trừ ước muốn, ",
  "sn1.69:2.4": "Mà cắt đứt tất cả trói buộc.' ",
  "sn1.70:0.1": "Tương Ưng Bộ Kinh 1.70 ",
  "sn1.70:0.2": "7. Phẩm Con Đường ",
  "sn1.70:0.3": "Kinh Thế Gian ",
  "sn1.70:1.1": "'Thế gian phát sanh từ cái gì, '",
  "sn1.70:1.2": "Thân cận với cái gì; ",
  "sn1.70:1.3": "Thế gian chấp thủ vào cái gì, ",
  "sn1.70:1.4": "Thế gian bị não hại bởi cái gì?' ",
  "sn1.70:2.1": "'Thế gian phát sanh từ sáu, '",
  "sn1.70:2.2": "Thân cận với sáu; ",
  "sn1.70:2.3": "Chấp thủ vào chính sáu, ",
  "sn1.70:2.4": "Thế gian bị não hại bởi sáu.' ",
  "sn1.70:2.5": "Phẩm Con Đường, thứ bảy. ",
  "sn1.70:3.0": "Tóm lược phẩm này ",
  "sn1.70:3.1": "Danh, tâm và tham ái, ",
  "sn1.70:3.2": "Kiết sử và trói buộc; ",
  "sn1.70:3.3": "Bị đánh mạnh, bị bẫy, bị che khuất, ",
  "sn1.70:3.4": "Ước muốn và thế gian là mười.' ",
  "sn1.71:0.1": "Tương Ưng Bộ Kinh 1.71 ",
  "sn1.71:0.2": "8. Phẩm Chặt Đứt ",
  "sn1.71:0.3": "Kinh Chặt Đứt ",
  "sn1.71:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn1.71:1.2": "Đứng sang một bên, vị thiên thần ấy đọc bài kệ này trước Thế Tôn: ",
  "sn1.71:2.1": "'Chặt đứt cái gì mà ngủ ngon, '",
  "sn1.71:2.2": "Chặt đứt cái gì mà không sầu khổ; ",
  "sn1.71:2.3": "Chặt đứt một pháp nào đó, ",
  "sn1.71:2.4": "Này Gotama, Ngài tán thán điều gì?' ",
  "sn1.71:3.1": "'Chặt đứt sân hận thì ngủ ngon, '",
  "sn1.71:3.2": "Chặt đứt sân hận thì không sầu khổ; ",
  "sn1.71:3.3": "Này thiên thần, sân hận có gốc rễ độc hại, ",
  "sn1.71:3.4": "Nhưng ngọn lại ngọt ngào; ",
  "sn1.71:3.5": "Các bậc Thánh tán thán việc tiêu diệt nó, ",
  "sn1.71:3.6": "Vì chặt đứt nó thì không còn sầu khổ.' ",
  "sn1.72:0.1": "Tương Ưng Bộ Kinh 1.72 ",
  "sn1.72:0.2": "8. Phẩm Chặt Đứt ",
  "sn1.72:0.3": "Kinh Cỗ Xe ",
  "sn1.72:1.1": "'Dấu hiệu của cỗ xe là gì, '",
  "sn1.72:1.2": "Dấu hiệu của lửa là gì; ",
  "sn1.72:1.3": "Dấu hiệu của vương quốc là gì, ",
  "sn1.72:1.4": "Dấu hiệu của người phụ nữ là gì?' ",
  "sn1.72:2.1": "'Dấu hiệu của cỗ xe là lá cờ, '",
  "sn1.72:2.2": "Dấu hiệu của lửa là khói; ",
  "sn1.72:2.3": "Dấu hiệu của vương quốc là vị vua, ",
  "sn1.72:2.4": "Dấu hiệu của người phụ nữ là người chồng.' ",
  "sn1.73:0.1": "Tương Ưng Bộ Kinh 1.73 ",
  "sn1.73:0.2": "8. Phẩm Chặt Đứt ",
  "sn1.73:0.3": "Kinh Tài Sản ",
  "sn1.73:1.1": "'Ở đây tài sản nào là tốt nhất cho người, '",
  "sn1.73:1.2": "Thực hành điều gì mang lại hạnh phúc; ",
  "sn1.73:1.3": "Vị nào thật sự là ngon nhất trong các vị, ",
  "sn1.73:1.4": "Sống cuộc đời nào được gọi là tốt nhất?' ",
  "sn1.73:2.1": "'Ở đây đức tin là tài sản tốt nhất cho người, '",
  "sn1.73:2.2": "Thực hành Pháp mang lại hạnh phúc; ",
  "sn1.73:2.3": "Sự thật thật sự là ngon nhất trong các vị, ",
  "sn1.73:2.4": "Sống với trí tuệ được gọi là tốt nhất.' ",
  "sn1.74:0.1": "Tương Ưng Bộ Kinh 1.74 ",
  "sn1.74:0.2": "8. Phẩm Chặt Đứt ",
  "sn1.74:0.3": "Kinh Mưa ",
  "sn1.74:1.1": "'Cái gì tốt nhất trong những thứ bay lên, '",
  "sn1.74:1.2": "Cái gì quý nhất trong những thứ rơi xuống; ",
  "sn1.74:1.3": "Cái gì tốt nhất trong những thứ di chuyển, ",
  "sn1.74:1.4": "Cái gì quý nhất trong những thứ nói chuyện?' ",
  "sn1.74:2.1": "'Hạt giống tốt nhất trong những thứ bay lên, '",
  "sn1.74:2.2": "Mưa quý nhất trong những thứ rơi xuống; ",
  "sn1.74:2.3": "Bò tốt nhất trong những thứ di chuyển, ",
  "sn1.74:2.4": "Con trai quý nhất trong những thứ nói chuyện.' ",
  "sn1.74:3.1": "'Minh (trí tuệ) tốt nhất trong những thứ bay lên, '",
  "sn1.74:3.2": "Vô minh xấu nhất trong những thứ rơi xuống; ",
  "sn1.74:3.3": "Tăng đoàn tốt nhất trong những thứ di chuyển, ",
  "sn1.74:3.4": "Đức Phật quý nhất trong những thứ nói chuyện.' ",
  "sn1.75:0.1": "Tương Ưng Bộ Kinh 1.75 ",
  "sn1.75:0.2": "8. Phẩm Chặt Đứt ",
  "sn1.75:0.3": "Kinh Sợ Hãi ",
  "sn1.75:1.1": "'Nhiều người ở đây đang sợ hãi, '",
  "sn1.75:1.2": "Con đường được nói đến qua nhiều cách; ",
  "sn1.75:1.3": "Con hỏi Ngài, Gotama với trí tuệ rộng lớn, ",
  "sn1.75:1.4": "Đứng vững trong điều gì mà không sợ hãi đời sau?' ",
  "sn1.75:2.1": "'Khéo hướng lời nói và tâm ý đúng đắn, '",
  "sn1.75:2.2": "Không làm các điều ác bằng thân; ",
  "sn1.75:2.3": "Sống tại gia với nhiều thức ăn và đồ uống, ",
  "sn1.75:2.4": "Có đức tin, nhu hòa, biết chia sẻ, biết nói lời đúng lúc; ",
  "sn1.75:2.5": "Đứng vững trong bốn pháp này, ",
  "sn1.75:2.6": "Đứng vững trong Pháp thì không sợ hãi đời sau.' ",
  "sn1.76:0.1": "Tương Ưng Bộ Kinh 1.76 ",
  "sn1.76:0.2": "8. Phẩm Chặt Đứt ",
  "sn1.76:0.3": "Kinh Không Già ",
  "sn1.76:1.1": "'Cái gì già đi, cái gì không già; '",
  "sn1.76:1.2": "Cái gì được gọi là tà đạo; ",
  "sn1.76:1.3": "Cái gì là chướng ngại cho các pháp, ",
  "sn1.76:1.4": "Cái gì làm hao mòn ngày đêm; ",
  "sn1.76:1.5": "Cái gì là cấu uế của phạm hạnh, ",
  "sn1.76:1.6": "Cái gì là tắm gội không cần nước. ",
  "sn1.76:2.1": "Có bao nhiêu lỗ hổng ở thế gian, ",
  "sn1.76:2.2": "Nơi mà tài sản không đứng vững; ",
  "sn1.76:2.3": "Chúng con đến hỏi Thế Tôn, ",
  "sn1.76:2.4": "Làm sao chúng con có thể biết điều đó?' ",
  "sn1.76:3.1": "'Sắc thân của chúng sinh thì già đi, '",
  "sn1.76:3.2": "Nhưng danh tiếng và dòng họ không già; ",
  "sn1.76:3.3": "Tham dục được gọi là tà đạo. ",
  "sn1.76:4.1": "Lòng tham là chướng ngại cho các pháp, ",
  "sn1.76:4.2": "Tuổi tác làm hao mòn ngày đêm; ",
  "sn1.76:4.3": "Phụ nữ là cấu uế của phạm hạnh, ",
  "sn1.76:4.4": "Chúng sinh bị mắc kẹt ở đây; ",
  "sn1.76:4.5": "Khổ hạnh và phạm hạnh, ",
  "sn1.76:4.6": "Đó là tắm gội không cần nước. ",
  "sn1.76:5.1": "Có sáu lỗ hổng ở thế gian, ",
  "sn1.76:5.2": "Nơi mà tài sản không đứng vững; ",
  "sn1.76:5.3": "Lười biếng và phóng dật, ",
  "sn1.76:5.4": "Không nỗ lực và không tự chế; ",
  "sn1.76:5.5": "Buồn ngủ và uể oải là những lỗ hổng đó, ",
  "sn1.76:5.6": "Hãy hoàn toàn tránh xa chúng.' ",
  "sn1.77:0.1": "Tương Ưng Bộ Kinh 1.77 ",
  "sn1.77:0.2": "8. Phẩm Chặt Đứt ",
  "sn1.77:0.3": "Kinh Quyền Lực ",
  "sn1.77:1.1": "'Cái gì là quyền lực ở thế gian, '",
  "sn1.77:1.2": "Cái gì là hàng hóa tốt nhất; ",
  "sn1.77:1.3": "Cái gì là gỉ sét của vũ khí ở thế gian, ",
  "sn1.77:1.4": "Cái gì là tai họa của thế gian. ",
  "sn1.77:2.1": "Cái gì ngăn cản kẻ ăn trộm, ",
  "sn1.77:2.2": "Kẻ ăn trộm nào thì được yêu mến; ",
  "sn1.77:2.3": "Kẻ nào đến đi đi lại, ",
  "sn1.77:2.4": "Bậc trí hoan hỷ chào đón?' ",
  "sn1.77:3.1": "'Quyền kiểm soát là quyền lực ở thế gian, '",
  "sn1.77:3.2": "Phụ nữ là hàng hóa tốt nhất; ",
  "sn1.77:3.3": "Sân hận là gỉ sét của vũ khí ở thế gian, ",
  "sn1.77:3.4": "Kẻ trộm là tai họa của thế gian. ",
  "sn1.77:4.1": "Kẻ trộm bị ngăn cản khi đang lấy đồ, ",
  "sn1.77:4.2": "Vị sa-môn khi lấy thì được yêu mến; ",
  "sn1.77:4.3": "Vị sa-môn đến đi đi lại, ",
  "sn1.77:4.4": "Bậc trí hoan hỷ chào đón.' ",
  "sn1.78:0.1": "Tương Ưng Bộ Kinh 1.78 ",
  "sn1.78:0.2": "8. Phẩm Chặt Đứt ",
  "sn1.78:0.3": "Kinh Dục ",
  "sn1.78:1.1": "'Người muốn gì mà không bố thí, '",
  "sn1.78:1.2": "Người phàm phu không từ bỏ cái gì; ",
  "sn1.78:1.3": "Cái gì nên buông bỏ điều tốt lành, ",
  "sn1.78:1.4": "Và không buông bỏ điều xấu ác?' ",
  "sn1.78:2.1": "'Người không bố thí bản thân mình, '",
  "sn1.78:2.2": "Người phàm phu không từ bỏ bản thân; ",
  "sn1.78:2.3": "Hãy buông bỏ lời nói tốt lành, ",
  "sn1.78:2.4": "Và đừng buông bỏ điều xấu ác.' ",
  "sn1.79:0.1": "Tương Ưng Bộ Kinh 1.79 ",
  "sn1.79:0.2": "8. Phẩm Chặt Đứt ",
  "sn1.79:0.3": "Kinh Lương Thực Đi Đường ",
  "sn1.79:1.1": "'Cái gì ràng buộc lương thực đi đường, '",
  "sn1.79:1.2": "Cái gì là nơi nương tựa của tài sản; ",
  "sn1.79:1.3": "Cái gì lôi cuốn người ta đi, ",
  "sn1.79:1.4": "Cái gì ở thế gian khó từ bỏ; ",
  "sn1.79:1.5": "Nhiều chúng sinh bị buộc bởi cái gì, ",
  "sn1.79:1.6": "Như chim bị mắc vào bẫy?' ",
  "sn1.79:2.1": "'Đức tin ràng buộc lương thực đi đường, '",
  "sn1.79:2.2": "Phúc lộc là nơi nương tựa của tài sản; ",
  "sn1.79:2.3": "Dục vọng lôi cuốn người ta đi, ",
  "sn1.79:2.4": "Dục vọng ở thế gian khó từ bỏ; ",
  "sn1.79:2.5": "Nhiều chúng sinh bị buộc bởi dục vọng, ",
  "sn1.79:2.6": "Như chim bị mắc vào bẫy.' ",
  "sn1.80:0.1": "Tương Ưng Bộ Kinh 1.80 ",
  "sn1.80:0.2": "8. Phẩm Chặt Đứt ",
  "sn1.80:0.3": "Kinh Ánh Sáng ",
  "sn1.80:1.1": "'Cái gì là ánh sáng ở thế gian, '",
  "sn1.80:1.2": "Cái gì là người canh giữ ở thế gian; ",
  "sn1.80:1.3": "Cái gì là sinh kế của những chúng sinh, ",
  "sn1.80:1.4": "Đó là phong thái của họ. ",
  "sn1.80:2.1": "Cái gì nuôi dưỡng cả kẻ lười biếng lẫn người siêng năng, ",
  "sn1.80:2.2": "Như người mẹ nuôi dưỡng người con; ",
  "sn1.80:2.3": "Chúng sinh nào sống nhờ vào cái đó, ",
  "sn1.80:2.4": "Những sinh vật nương tựa vào đất?' ",
  "sn1.80:3.1": "'Trí tuệ là ánh sáng ở thế gian, '",
  "sn1.80:3.2": "Chánh niệm là người canh giữ ở thế gian; ",
  "sn1.80:3.3": "Bò là sinh kế của những chúng sinh, ",
  "sn1.80:3.4": "Đó là phong thái của trâu bò. ",
  "sn1.80:4.1": "Mưa nuôi dưỡng cả kẻ lười biếng lẫn người siêng năng, ",
  "sn1.80:4.2": "Như người mẹ nuôi dưỡng người con; ",
  "sn1.80:4.3": "Chúng sinh sống nhờ vào mưa, ",
  "sn1.80:4.4": "Những sinh vật nương tựa vào đất.' ",
  "sn1.81:0.1": "Tương Ưng Bộ Kinh 1.81 ",
  "sn1.81:0.2": "8. Phẩm Chặt Đứt ",
  "sn1.81:0.3": "Kinh Không Tranh Chấp ",
  "sn1.81:1.1": "'Ai ở đây không tranh chấp ở thế gian, '",
  "sn1.81:1.2": "Ai có phạm hạnh hoàn tất không bị hủy diệt; ",
  "sn1.81:1.3": "Ai ở đây thấu hiểu dục vọng trọn vẹn, ",
  "sn1.81:1.4": "Ai luôn luôn được tự do. ",
  "sn1.81:2.1": "Cha mẹ và anh chị em, ",
  "sn1.81:2.2": "Cúi đầu đảnh lễ vị ấy khi đứng vững; ",
  "sn1.81:2.3": "Ai tuy xuất thân thấp kém ở đây, ",
  "sn1.81:2.4": "Mà các vị Sát-đế-lỵ cúi đầu đảnh lễ?' ",
  "sn1.81:3.1": "'Các vị sa-môn không tranh chấp ở thế gian, '",
  "sn1.81:3.2": "Phạm hạnh của các vị sa-môn không bị hủy diệt; ",
  "sn1.81:3.3": "Các vị sa-môn thấu hiểu dục vọng trọn vẹn, ",
  "sn1.81:3.4": "Các vị sa-môn luôn luôn được tự do. ",
  "sn1.81:4.1": "Cha mẹ và anh chị em, ",
  "sn1.81:4.2": "Cúi đầu đảnh lễ vị sa-môn khi đứng vững; ",
  "sn1.81:4.3": "Vị sa-môn tuy xuất thân thấp kém ở đây, ",
  "sn1.81:4.4": "Mà các vị Sát-đế-lỵ cúi đầu đảnh lễ.' ",
  "sn1.81:4.5": "Phẩm Chặt Đứt, thứ tám. ",
  "sn1.81:5.0": "Tóm tắt phẩm ",
  "sn1.81:5.1": "Chặt đứt, cỗ xe và tâm ý, ",
  "sn1.81:5.2": "Mưa, sợ hãi, không già; ",
  "sn1.81:5.3": "Quyền lực, dục, lương thực đi đường, ",
  "sn1.81:5.4": "Ánh sáng và không tranh chấp. ",
  "sn1.81:5.5": "Tương Ưng Chư Thiên, hoàn tất. "
}
window.BILARA["sn1_v1"]["vi"]["sn1_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
