window.BILARA = window.BILARA || {};
window.BILARA["sn20_v1"] = window.BILARA["sn20_v1"] || {};
window.BILARA["sn20_v1"]["vi"] = {
  "sn20.1:0.1": "Tương Ưng Bộ Kinh 20.1 ",
  "sn20.1:0.2": "1. Phẩm Ví Dụ ",
  "sn20.1:0.3": "Kinh Nóc Nhà ",
  "sn20.1:1.1": "Tôi nghe như vầy",
  "sn20.1:1.2": "một thời, Thế Tôn trú tại Sāvatthi, trong rừng Jeta, vườn của ông Anāthapiṇḍika. ",
  "sn20.1:1.3": "Ở đó, Thế Tôn … đã nói điều này: ",
  "sn20.1:1.4": "'Này các Tỳ Kheo, ví như mọi đòn tay của ngôi nhà có nóc đều hướng về phía nóc, quy về phía nóc, tập trung ở phía nóc; khi nóc bị phá bỏ, tất cả đều bị phá bỏ; '",
  "sn20.1:1.5": "cũng vậy, này các Tỳ Kheo, tất cả các pháp bất thiện đều có gốc từ vô minh, quy về vô minh, tập trung ở vô minh; khi vô minh bị phá trừ, tất cả đều bị phá trừ. ",
  "sn20.1:1.6": "Do vậy, này các Tỳ Kheo, hãy học tập như sau: ",
  "sn20.1:1.7": "'Chúng ta sẽ sống không phóng dật.' ",
  "sn20.1:1.8": "Này các Tỳ Kheo, các ông hãy học tập như vậy.' ",
  "sn20.1:1.9": "Thứ nhất. ",
  "sn20.2:0.1": "Tương Ưng Bộ Kinh 20.2 ",
  "sn20.2:0.2": "1. Phẩm Ví Dụ ",
  "sn20.2:0.3": "Kinh Đầu Móng Tay ",
  "sn20.2:1.1": "Trú tại Sāvatthi. ",
  "sn20.2:1.2": "Rồi Thế Tôn lấy một chút đất đặt lên đầu móng tay và hỏi các Tỳ Kheo: ",
  "sn20.2:1.3": "'Này các Tỳ Kheo, các ông nghĩ thế nào? '",
  "sn20.2:1.4": "Cái nào nhiều hơn: chút đất ta đặt lên đầu móng tay, hay đại địa này?' ",
  "sn20.2:1.5": "'Bạch Thế Tôn, đại địa mới là nhiều hơn. '",
  "sn20.2:1.6": "Chút đất Thế Tôn đặt lên đầu móng tay thật là nhỏ bé. ",
  "sn20.2:1.7": "Chút đất ấy không thể so sánh được, không thể ví dụ được, không thể kể là một phần nhỏ so với đại địa.' ",
  "sn20.2:1.8": "'Cũng vậy, này các Tỳ Kheo, rất ít những chúng sinh được tái sinh làm người; '",
  "sn20.2:1.9": "còn những chúng sinh tái sinh vào chỗ khác, không phải làm người, thì nhiều hơn nhiều. ",
  "sn20.2:1.10": "Do vậy, này các Tỳ Kheo, hãy học tập như sau: ",
  "sn20.2:1.11": "'Chúng ta sẽ sống không phóng dật.' ",
  "sn20.2:1.12": "Này các Tỳ Kheo, các ông hãy học tập như vậy.' ",
  "sn20.2:1.13": "Thứ hai. ",
  "sn20.3:0.1": "Tương Ưng Bộ Kinh 20.3 ",
  "sn20.3:0.2": "1. Phẩm Ví Dụ ",
  "sn20.3:0.3": "Kinh Gia Đình ",
  "sn20.3:1.1": "Trú tại Sāvatthi. ",
  "sn20.3:1.2": "'Này các Tỳ Kheo, ví như những gia đình nào nhiều phụ nữ, ít đàn ông, thì dễ bị bọn trộm cướp xâm phạm; '",
  "sn20.3:1.3": "cũng vậy, này các Tỳ Kheo, vị Tỳ Kheo nào không tu tập, không thực hành nhiều tâm từ giải thoát, vị ấy dễ bị phi nhân xâm phạm. ",
  "sn20.3:1.4": "Này các Tỳ Kheo, ví như những gia đình nào ít phụ nữ, nhiều đàn ông, thì khó bị bọn trộm cướp xâm phạm; ",
  "sn20.3:1.5": "cũng vậy, này các Tỳ Kheo, vị Tỳ Kheo nào tu tập, thực hành nhiều tâm từ giải thoát, vị ấy khó bị phi nhân xâm phạm. ",
  "sn20.3:1.6": "Do vậy, này các Tỳ Kheo, hãy học tập như sau: ",
  "sn20.3:1.7": "'Tâm từ giải thoát của chúng ta sẽ được tu tập, thực hành nhiều, làm thành phương tiện, làm thành nền tảng, được an trú, được tích lũy, được khéo léo thực hiện.' ",
  "sn20.3:1.8": "Này các Tỳ Kheo, các ông hãy học tập như vậy.' ",
  "sn20.3:1.9": "Thứ ba. ",
  "sn20.4:0.1": "Tương Ưng Bộ Kinh 20.4 ",
  "sn20.4:0.2": "1. Phẩm Ví Dụ ",
  "sn20.4:0.3": "Kinh Nồi Cơm ",
  "sn20.4:1.1": "Trú tại Sāvatthi. ",
  "sn20.4:1.2": "'Này các Tỳ Kheo, dù ai bố thí một trăm nồi cơm vào buổi sáng, dù ai bố thí một trăm nồi cơm vào buổi trưa, dù ai bố thí một trăm nồi cơm vào buổi chiều; nhưng nếu ai vào buổi sáng tu tập tâm từ dù chỉ trong khoảnh khắc vắt sữa bò, nếu ai vào buổi trưa tu tập tâm từ dù chỉ trong khoảnh khắc vắt sữa bò, nếu ai vào buổi chiều tu tập tâm từ dù chỉ trong khoảnh khắc vắt sữa bò  điều này có phước báo lớn hơn điều kia. '",
  "sn20.4:1.3": "Do vậy, này các Tỳ Kheo, hãy học tập như sau: ",
  "sn20.4:1.4": "'Tâm từ giải thoát của chúng ta sẽ được tu tập, thực hành nhiều, làm thành phương tiện, làm thành nền tảng, được an trú, được tích lũy, được khéo léo thực hiện.' ",
  "sn20.4:1.5": "Này các Tỳ Kheo, các ông hãy học tập như vậy.' ",
  "sn20.4:1.6": "Thứ tư. ",
  "sn20.5:0.1": "Tương Ưng Bộ Kinh 20.5 ",
  "sn20.5:0.2": "1. Phẩm Ví Dụ ",
  "sn20.5:0.3": "Kinh Cây Thương ",
  "sn20.5:1.1": "Trú tại Sāvatthi. ",
  "sn20.5:1.2": "'Này các Tỳ Kheo, ví như một cây thương sắc bén. '",
  "sn20.5:1.3": "Rồi có người đến nói: ",
  "sn20.5:1.4": "'Ta sẽ dùng bàn tay hay nắm đấm để bẻ cong, bẻ gãy, hay vặn xoắn cây thương sắc bén này.' ",
  "sn20.5:1.5": "Này các Tỳ Kheo, các ông nghĩ thế nào? ",
  "sn20.5:1.6": "Người ấy có thể dùng bàn tay hay nắm đấm mà bẻ cong, bẻ gãy, hay vặn xoắn cây thương sắc bén ấy không?' ",
  "sn20.5:1.7": "'Thưa không, bạch Thế Tôn.' ",
  "sn20.5:1.8": "'Tại sao vậy?' ",
  "sn20.5:1.9": "'Bạch Thế Tôn, vì cây thương sắc bén ấy không thể dùng bàn tay hay nắm đấm mà bẻ cong, bẻ gãy hay vặn xoắn được. '",
  "sn20.5:1.10": "Người ấy chỉ chuốc lấy mệt nhọc và khổ sở mà thôi.' ",
  "sn20.5:2.1": "'Cũng vậy, này các Tỳ Kheo, vị Tỳ Kheo nào tu tập, thực hành nhiều tâm từ giải thoát, làm thành phương tiện, làm thành nền tảng, được an trú, được tích lũy, được khéo léo thực hiện; nếu phi nhân nghĩ đến việc làm rối loạn tâm vị ấy, '",
  "sn20.5:2.2": "thì chính phi nhân đó sẽ chuốc lấy mệt nhọc và khổ sở. ",
  "sn20.5:2.3": "Do vậy, này các Tỳ Kheo, hãy học tập như sau: ",
  "sn20.5:2.4": "'Tâm từ giải thoát của chúng ta sẽ được tu tập, thực hành nhiều, làm thành phương tiện, làm thành nền tảng, được an trú, được tích lũy, được khéo léo thực hiện.' ",
  "sn20.5:2.5": "Này các Tỳ Kheo, các ông hãy học tập như vậy.' ",
  "sn20.5:2.6": "Thứ năm. ",
  "sn20.6:0.1": "Tương Ưng Bộ Kinh 20.6 ",
  "sn20.6:0.2": "1. Phẩm Ví Dụ ",
  "sn20.6:0.3": "Kinh Cung Thủ ",
  "sn20.6:1.1": "Trú tại Sāvatthi. ",
  "sn20.6:1.2": "'Này các Tỳ Kheo, ví như có bốn cung thủ thiện xảo, được huấn luyện thuần thục, khéo léo trong tay, đứng ở bốn phương. '",
  "sn20.6:1.3": "Rồi có người đến nói: ",
  "sn20.6:1.4": "'Ta sẽ bắt lấy các mũi tên do bốn cung thủ thiện xảo, được huấn luyện thuần thục, khéo léo trong tay ấy bắn ra từ bốn phương, trước khi chúng chạm đất, rồi mang trở lại.' ",
  "sn20.6:1.5": "Này các Tỳ Kheo, các ông nghĩ thế nào? ",
  "sn20.6:1.6": "Gọi người ấy là 'người nhanh lẹ với tốc độ cao nhất' có xứng đáng không?' ",
  "sn20.6:2.1": "'Bạch Thế Tôn, nếu người ấy bắt lấy chỉ một mũi tên của một cung thủ thiện xảo, được huấn luyện thuần thục, khéo léo trong tay, trước khi nó chạm đất, rồi mang trở lại, thì đã xứng đáng được gọi là 'người nhanh lẹ với tốc độ cao nhất' rồi, huống chi là bắt lấy mũi tên của bốn cung thủ.' ",
  "sn20.6:3.1": "'Này các Tỳ Kheo, tốc độ của người ấy còn thua xa tốc độ của mặt trăng mặt trời. '",
  "sn20.6:3.2": "Tốc độ của người ấy, tốc độ của mặt trăng mặt trời, cộng với tốc độ của các thiên thần chạy trước mặt trăng mặt trời  tuổi thọ còn tiêu mất nhanh hơn tất cả những điều đó. ",
  "sn20.6:3.3": "Do vậy, này các Tỳ Kheo, hãy học tập như sau: ",
  "sn20.6:3.4": "'Chúng ta sẽ sống không phóng dật.' ",
  "sn20.6:3.5": "Này các Tỳ Kheo, các ông hãy học tập như vậy.' ",
  "sn20.6:3.6": "Thứ sáu. ",
  "sn20.7:0.1": "Tương Ưng Bộ Kinh 20.7 ",
  "sn20.7:0.2": "1. Phẩm Ví Dụ ",
  "sn20.7:0.3": "Kinh Cái Chốt ",
  "sn20.7:1.1": "Trú tại Sāvatthi. ",
  "sn20.7:1.2": "'Này các Tỳ Kheo, thuở xưa người dân Dasāraha có một chiếc trống gọi là Ānaka. '",
  "sn20.7:1.3": "Khi chiếc trống Ānaka bị nứt, người dân Dasāraha đóng thêm một chốt mới vào. ",
  "sn20.7:1.4": "Này các Tỳ Kheo, đã đến lúc mặt trống cổ xưa của chiếc trống Ānaka biến mất. ",
  "sn20.7:1.5": "Chỉ còn lại những cái chốt mà thôi. ",
  "sn20.7:1.6": "Cũng vậy, này các Tỳ Kheo, trong tương lai sẽ có những Tỳ Kheo  khi các kinh sâu xa do Như Lai thuyết, sâu xa về nghĩa, siêu thế, liên hệ đến Không, được tụng đọc; họ sẽ không lắng nghe, không chú ý lắng tai, không khởi tâm hiểu biết, và không xem những pháp ấy là cần phải học, cần phải thông thuộc. ",
  "sn20.7:2.1": "Nhưng khi các kinh được sáng tác bởi các nhà thơ, với văn từ hoa mỹ, ngôn ngữ đẹp đẽ  thuộc ngoại đạo hay do đệ tử thuyết  được tụng đọc; họ sẽ lắng nghe, chú ý lắng tai, khởi tâm hiểu biết, và xem những pháp ấy là cần phải học, cần phải thông thuộc. ",
  "sn20.7:2.2": "Này các Tỳ Kheo, như vậy các kinh do Như Lai thuyết, sâu xa, sâu xa về nghĩa, siêu thế, liên hệ đến Không, sẽ bị biến mất. ",
  "sn20.7:2.3": "Do vậy, này các Tỳ Kheo, hãy học tập như sau: ",
  "sn20.7:2.4": "'Khi các kinh sâu xa do Như Lai thuyết, sâu xa về nghĩa, siêu thế, liên hệ đến Không, được tụng đọc; chúng ta sẽ lắng nghe, chú ý lắng tai, khởi tâm hiểu biết, và xem những pháp ấy là cần phải học, cần phải thông thuộc.' ",
  "sn20.7:2.5": "Này các Tỳ Kheo, các ông hãy học tập như vậy.' ",
  "sn20.7:2.6": "Thứ bảy. ",
  "sn20.8:0.1": "Tương Ưng Bộ Kinh 20.8 ",
  "sn20.8:0.2": "1. Phẩm Ví Dụ ",
  "sn20.8:0.3": "Kinh Chiếc Gối ",
  "sn20.8:1.1": "Tôi nghe như vầy",
  "sn20.8:1.2": "một thời, Thế Tôn trú tại Vesāli, tại giảng đường Mái Nhọn, trong rừng Đại Lâm. ",
  "sn20.8:1.3": "Ở đó, Thế Tôn gọi các Tỳ Kheo: ",
  "sn20.8:1.4": "'Này các Tỳ Kheo.' ",
  "sn20.8:1.5": "'Bạch Thế Tôn,' các Tỳ Kheo ấy đáp lại. ",
  "sn20.8:1.6": "Thế Tôn nói điều này: ",
  "sn20.8:2.1": "'Này các Tỳ Kheo, hiện nay người Licchavi sống dựa vào gỗ kaliṅga, tinh tấn và nhiệt tâm trong việc phòng hộ. '",
  "sn20.8:2.2": "Vua Māgadha Ajātasattu con bà Videhi không tìm được cơ hội, không tìm được chỗ hở nơi họ. ",
  "sn20.8:2.3": "Này các Tỳ Kheo, trong tương lai sẽ có những người Licchavi mềm mại, mịn màng, tay chân non yếu, ",
  "sn20.8:2.4": "họ sẽ nằm ngủ trên giường nệm mềm mại, với gối bông, cho đến khi mặt trời mọc. ",
  "sn20.8:2.5": "Lúc đó vua Māgadha Ajātasattu con bà Videhi sẽ tìm được cơ hội, tìm được chỗ hở nơi họ. ",
  "sn20.8:3.1": "Này các Tỳ Kheo, hiện nay các Tỳ Kheo sống dựa vào gỗ kaliṅga, tinh tấn và nhiệt tâm trong việc tu tập. ",
  "sn20.8:3.2": "Ác ma không tìm được cơ hội, không tìm được chỗ hở nơi họ. ",
  "sn20.8:3.3": "Này các Tỳ Kheo, trong tương lai sẽ có những Tỳ Kheo mềm mại, mịn màng, tay chân non yếu. ",
  "sn20.8:3.4": "Họ sẽ nằm ngủ trên giường nệm mềm mại, với gối bông, cho đến khi mặt trời mọc. ",
  "sn20.8:3.5": "Lúc đó Ác ma sẽ tìm được cơ hội, tìm được chỗ hở nơi họ. ",
  "sn20.8:3.6": "Do vậy, này các Tỳ Kheo, hãy học tập như sau: ",
  "sn20.8:3.7": "'Chúng ta sẽ sống dựa vào gỗ kaliṅga, tinh tấn và nhiệt tâm trong việc tu tập.' ",
  "sn20.8:3.8": "Này các Tỳ Kheo, các ông hãy học tập như vậy.' ",
  "sn20.8:3.9": "Thứ tám. ",
  "sn20.9:0.1": "Tương Ưng Bộ Kinh 20.9 ",
  "sn20.9:0.2": "1. Phẩm Ví Dụ ",
  "sn20.9:0.3": "Kinh Con Voi ",
  "sn20.9:1.1": "Tôi nghe như vầy",
  "sn20.9:1.2": "một thời, Thế Tôn trú tại Sāvatthi, trong rừng Jeta, vườn của ông Anāthapiṇḍika. ",
  "sn20.9:1.3": "Lúc bấy giờ, có một Tỳ Kheo mới thường xuyên đi thăm viếng các gia đình quá mức. ",
  "sn20.9:1.4": "Các Tỳ Kheo liền nói với vị ấy: ",
  "sn20.9:1.5": "'Thưa Đại Đức, chớ nên đi thăm viếng các gia đình quá mức.' ",
  "sn20.9:1.6": "Khi bị các Tỳ Kheo khuyên nhủ, vị Tỳ Kheo ấy đáp lại: ",
  "sn20.9:1.7": "'Ngay cả các Tỳ Kheo trưởng thượng còn đi thăm viếng các gia đình, thì huống gì là ta?' ",
  "sn20.9:2.1": "Rồi nhiều Tỳ Kheo đến gặp Thế Tôn, đảnh lễ và ngồi xuống một bên. Ngồi xuống một bên, các Tỳ Kheo ấy bạch Thế Tôn: ",
  "sn20.9:2.2": "'Bạch Thế Tôn, ở đây có một Tỳ Kheo mới thường xuyên đi thăm viếng các gia đình quá mức. '",
  "sn20.9:2.3": "Các Tỳ Kheo liền nói với vị ấy: ",
  "sn20.9:2.4": "'Thưa Đại Đức, chớ nên đi thăm viếng các gia đình quá mức.' ",
  "sn20.9:2.5": "Khi bị các Tỳ Kheo khuyên nhủ, vị Tỳ Kheo ấy đáp lại: ",
  "sn20.9:2.6": "'Ngay cả các Tỳ Kheo trưởng thượng còn đi thăm viếng các gia đình, thì huống gì là ta?'' '",
  "sn20.9:3.1": "'Này các Tỳ Kheo, thuở xưa có một hồ nước lớn trong vùng rừng núi. '",
  "sn20.9:3.2": "Các voi sống nương nhờ vào hồ nước ấy. ",
  "sn20.9:3.3": "Chúng lội xuống hồ, dùng vòi nhổ lên những ngó sen, rửa sạch kỹ càng, cho hết bùn đất rồi mới nhai nuốt. ",
  "sn20.9:3.4": "Điều ấy làm cho chúng được đẹp và có sức lực, và vì vậy không bị chết hay chịu đau khổ như sắp chết. ",
  "sn20.9:3.5": "Nhưng này các Tỳ Kheo, những voi con đang học theo các đại tượng ấy, cũng lội xuống hồ, dùng vòi nhổ lên những ngó sen, nhưng không rửa sạch kỹ càng, còn đầy bùn đất thì đã nhai nuốt. ",
  "sn20.9:3.6": "Điều ấy không làm cho chúng được đẹp hay có sức lực. ",
  "sn20.9:3.7": "Vì vậy chúng bị chết hay chịu đau khổ như sắp chết. ",
  "sn20.9:4.1": "Cũng vậy, này các Tỳ Kheo, ở đây các Tỳ Kheo trưởng thượng vào buổi sáng đắp y, mang bát đi vào làng hay thị trấn khất thực. ",
  "sn20.9:4.2": "Ở đó, các ngài thuyết pháp. ",
  "sn20.9:4.3": "Các cư sĩ cúng dường với lòng tịnh tín. ",
  "sn20.9:4.4": "Các ngài thọ dụng những vật cúng dường ấy không tham đắm, không mê say, không chấp thủ, thấy rõ sự nguy hiểm, có trí tuệ xuất ly. ",
  "sn20.9:4.5": "Điều ấy làm cho các ngài được đẹp và có sức lực, và vì vậy không bị chết hay chịu đau khổ như sắp chết. ",
  "sn20.9:4.6": "Nhưng này các Tỳ Kheo, các Tỳ Kheo mới đang học theo các Tỳ Kheo trưởng thượng ấy, cũng vào buổi sáng đắp y, mang bát đi vào làng hay thị trấn khất thực. ",
  "sn20.9:4.7": "Ở đó, họ thuyết pháp. ",
  "sn20.9:4.8": "Các cư sĩ cúng dường với lòng tịnh tín. ",
  "sn20.9:4.9": "Họ thọ dụng những vật cúng dường ấy với tâm tham đắm, mê say, chấp thủ, không thấy sự nguy hiểm, không có trí tuệ xuất ly. ",
  "sn20.9:4.10": "Điều ấy không làm cho họ được đẹp hay có sức lực. Vì vậy họ bị chết hay chịu đau khổ như sắp chết. ",
  "sn20.9:4.11": "Do vậy, này các Tỳ Kheo, hãy học tập như sau: ",
  "sn20.9:4.12": "'Chúng ta sẽ thọ dụng những vật cúng dường không tham đắm, không mê say, không chấp thủ, thấy rõ sự nguy hiểm, có trí tuệ xuất ly.' ",
  "sn20.9:4.13": "Này các Tỳ Kheo, các ông hãy học tập như vậy.' ",
  "sn20.9:4.14": "Thứ chín. ",
  "sn20.10:0.1": "Tương Ưng Bộ Kinh 20.10 ",
  "sn20.10:0.2": "1. Phẩm Ví Dụ ",
  "sn20.10:0.3": "Kinh Con Mèo ",
  "sn20.10:1.1": "Trú tại Sāvatthi. ",
  "sn20.10:1.2": "Lúc bấy giờ, có một Tỳ Kheo thường xuyên lui tới các gia đình quá mức. ",
  "sn20.10:1.3": "Các Tỳ Kheo liền nói với vị ấy: ",
  "sn20.10:1.4": "'Thưa Đại Đức, chớ nên lui tới các gia đình quá mức.' ",
  "sn20.10:1.5": "Vị Tỳ Kheo ấy khi bị các Tỳ Kheo khuyên nhủ thì không chịu từ bỏ. ",
  "sn20.10:1.6": "Rồi nhiều Tỳ Kheo đến gặp Thế Tôn, đảnh lễ và ngồi xuống một bên. Ngồi xuống một bên, các Tỳ Kheo ấy bạch Thế Tôn: ",
  "sn20.10:1.7": "'Bạch Thế Tôn, ở đây có một Tỳ Kheo thường xuyên lui tới các gia đình quá mức. '",
  "sn20.10:1.8": "Các Tỳ Kheo liền nói với vị ấy: ",
  "sn20.10:1.9": "'Thưa Đại Đức, chớ nên lui tới các gia đình quá mức.' ",
  "sn20.10:1.10": "Vị Tỳ Kheo ấy khi bị các Tỳ Kheo khuyên nhủ thì không chịu từ bỏ.' ",
  "sn20.10:2.1": "'Này các Tỳ Kheo, thuở xưa có một con mèo đứng ở góc tường đống rác đợi một con chuột mềm mại: '",
  "sn20.10:2.2": "'Khi con chuột mềm mại này đi kiếm ăn, ta sẽ bắt lấy và ăn ngay tại đó.' ",
  "sn20.10:2.3": "Này các Tỳ Kheo, rồi con chuột mềm mại đi kiếm ăn. ",
  "sn20.10:2.4": "Con mèo liền bắt lấy và vội vàng nhai nuốt. ",
  "sn20.10:2.5": "Con chuột ăn vào ruột của con mèo, gặm cả ruột non lẫn ruột già. ",
  "sn20.10:2.6": "Vì đó mà con mèo bị chết hay chịu đau khổ như sắp chết. ",
  "sn20.10:3.1": "Cũng vậy, này các Tỳ Kheo, ở đây có một Tỳ Kheo vào buổi sáng đắp y, mang bát đi vào làng hay thị trấn khất thực mà không hộ trì thân, không hộ trì lời nói, không hộ trì tâm ý, không có chánh niệm, không thu thúc các căn. ",
  "sn20.10:3.2": "Ở đó, vị ấy thấy người phụ nữ mặc áo lộng lẫy hoặc để hở hang. ",
  "sn20.10:3.3": "Thấy người phụ nữ ăn mặc lộng lẫy hoặc để hở hang, tham dục xâm chiếm tâm vị ấy. ",
  "sn20.10:3.4": "Với tâm bị tham dục xâm chiếm, vị ấy bị chết hay chịu đau khổ như sắp chết. ",
  "sn20.10:3.5": "Này các Tỳ Kheo, cái chết trong giới luật của bậc Thánh là từ bỏ học pháp và trở về đời thế tục. ",
  "sn20.10:3.6": "Này các Tỳ Kheo, đau khổ như sắp chết là phạm vào một giới nào đó có thể được phục hồi. ",
  "sn20.10:3.7": "Từ giới ấy có thể xuất tội được. ",
  "sn20.10:3.8": "Do vậy, này các Tỳ Kheo, hãy học tập như sau: ",
  "sn20.10:3.9": "'Chúng ta sẽ đi vào làng hay thị trấn khất thực với thân hộ trì, lời nói hộ trì, tâm hộ trì, với chánh niệm, với các căn thu thúc.' ",
  "sn20.10:3.10": "Này các Tỳ Kheo, các ông hãy học tập như vậy.' ",
  "sn20.10:3.11": "Thứ mười. ",
  "sn20.11:0.1": "Tương Ưng Bộ Kinh 20.11 ",
  "sn20.11:0.2": "1. Phẩm Ví Dụ ",
  "sn20.11:0.3": "Kinh Con Chó Rừng ",
  "sn20.11:1.1": "Trú tại Sāvatthi. ",
  "sn20.11:1.2": "'Này các Tỳ Kheo, các ông có nghe con chó rừng già hú lên vào lúc gần sáng không?' ",
  "sn20.11:1.3": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn20.11:1.4": "'Này các Tỳ Kheo, con chó rừng già ấy đang bị một loại bệnh gọi là ukkaṇḍaka. '",
  "sn20.11:1.5": "Nó muốn đi đâu thì đi đó; ",
  "sn20.11:1.6": "nó muốn đứng ở đâu thì đứng ở đó; ",
  "sn20.11:1.7": "nó muốn ngồi ở đâu thì ngồi ở đó; ",
  "sn20.11:1.8": "nó muốn nằm ở đâu thì nằm ở đó; ",
  "sn20.11:1.9": "ngọn gió lạnh cũng thổi đến mà không làm nó đau khổ. ",
  "sn20.11:1.10": "Này các Tỳ Kheo, thật tốt nếu ai đó tự nhận mình là con của Thích Ca mà lại được hưởng thân phận như vậy. ",
  "sn20.11:1.11": "Do vậy, này các Tỳ Kheo, hãy học tập như sau: ",
  "sn20.11:1.12": "'Chúng ta sẽ sống không phóng dật.' ",
  "sn20.11:1.13": "Này các Tỳ Kheo, các ông hãy học tập như vậy.' ",
  "sn20.11:1.14": "Thứ mười một. ",
  "sn20.12:0.1": "Tương Ưng Bộ Kinh 20.12 ",
  "sn20.12:0.2": "1. Phẩm Ví Dụ ",
  "sn20.12:0.3": "Kinh Con Chó Rừng Thứ Hai ",
  "sn20.12:1.1": "Trú tại Sāvatthi. ",
  "sn20.12:1.2": "'Này các Tỳ Kheo, các ông có nghe con chó rừng già hú lên vào lúc gần sáng không?' ",
  "sn20.12:1.3": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn20.12:1.4": "'Này các Tỳ Kheo, con chó rừng già ấy có thể có lòng biết ơn và nhớ ơn; nhưng có một số người tự nhận là con của Thích Ca lại không có lòng biết ơn và nhớ ơn như vậy. '",
  "sn20.12:1.5": "Do vậy, này các Tỳ Kheo, hãy học tập như sau: ",
  "sn20.12:1.6": "'Chúng ta sẽ có lòng biết ơn và nhớ ơn; '",
  "sn20.12:1.7": "dù chỉ một ân huệ nhỏ được làm cho chúng ta cũng sẽ không bị quên lãng.' ",
  "sn20.12:1.8": "Này các Tỳ Kheo, các ông hãy học tập như vậy.' ",
  "sn20.12:1.9": "Thứ mười hai. ",
  "sn20.12:1.10": "Phẩm Ví Dụ thứ nhất. ",
  "sn20.12:2.0": "Kệ tóm tắt phẩm: ",
  "sn20.12:2.1": "Nóc nhà, đầu móng tay, gia đình, ",
  "sn20.12:2.2": "nồi cơm, cây thương, cung thủ; ",
  "sn20.12:2.3": "Cái chốt, chiếc gối, con voi, ",
  "sn20.12:2.4": "con mèo, hai con chó rừng. ",
  "sn20.12:2.5": "Tương Ưng Ví Dụ hoàn tất. "
}
window.BILARA["sn20_v1"]["vi"]["sn20_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
