window.BILARA = window.BILARA || {};
window.BILARA["sn24_v1"] = window.BILARA["sn24_v1"] || {};
window.BILARA["sn24_v1"]["vi"] = {
  "sn24.1:0.1": "Tương Ưng Bộ 24.1 ",
  "sn24.1:0.2": "1. Phẩm Dự Lưu ",
  "sn24.1:0.3": "Kinh Gió ",
  "sn24.1:1.1": "Một thời, Thế Tôn trú tại Sāvatthi (Xá-vệ), Jetavana (Kỳ-đà Lâm). ",
  "sn24.1:1.2": "Thế Tôn dạy: ",
  "sn24.1:1.3": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.1:1.4": "'gió không thổi, sông không chảy, phụ nữ mang thai không sinh con, mặt trăng mặt trời không mọc không lặn, đứng vững như cột trụ''? '",
  "sn24.1:2.1": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản, lấy Thế Tôn làm dẫn đạo, lấy Thế Tôn làm nơi nương tựa. Lành thay, bạch Thế Tôn, xin Thế Tôn hãy giải thích ý nghĩa của lời nói này. Sau khi nghe Thế Tôn, các Tỳ Kheo sẽ ghi nhớ.' ",
  "sn24.1:2.2": "'Vậy thì, này các Tỳ Kheo, hãy nghe, hãy tác ý kỹ, Ta sẽ nói.' ",
  "sn24.1:2.3": "'Thưa vâng, bạch Thế Tôn', các Tỳ Kheo ấy đáp lời Thế Tôn. ",
  "sn24.1:2.4": "Thế Tôn dạy: ",
  "sn24.1:3.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.1:3.2": "'gió không thổi, sông không chảy, phụ nữ mang thai không sinh con, mặt trăng mặt trời không mọc không lặn, đứng vững như cột trụ'. ",
  "sn24.1:3.3": "Do có thọ …(viết tắt)… ",
  "sn24.1:3.4": "do có tưởng … ",
  "sn24.1:3.5": "do có hành … ",
  "sn24.1:3.6": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.1:3.7": "'gió không thổi, sông không chảy, phụ nữ mang thai không sinh con, mặt trăng mặt trời không mọc không lặn, đứng vững như cột trụ'. ",
  "sn24.1:3.8": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.1:3.9": "sắc là thường còn hay vô thường?' ",
  "sn24.1:3.10": "'Vô thường, bạch Thế Tôn.' ",
  "sn24.1:3.11": "'Cái gì vô thường, cái đó là khổ hay lạc?' ",
  "sn24.1:3.12": "'Khổ, bạch Thế Tôn.' ",
  "sn24.1:3.13": "'Cái gì vô thường, khổ, chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: '",
  "sn24.1:3.14": "'gió không thổi, sông không chảy, phụ nữ mang thai không sinh con, mặt trăng mặt trời không mọc không lặn, đứng vững như cột trụ''? '",
  "sn24.1:3.15": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.1:4.1": "'Thọ là thường còn hay vô thường?' … ",
  "sn24.1:4.2": "'Tưởng … '",
  "sn24.1:4.3": "hành … ",
  "sn24.1:4.4": "thức là thường còn hay vô thường?' ",
  "sn24.1:4.5": "'Vô thường, bạch Thế Tôn.' ",
  "sn24.1:4.6": "'Cái gì vô thường, cái đó là khổ hay lạc?' ",
  "sn24.1:4.7": "'Khổ, bạch Thế Tôn.' ",
  "sn24.1:4.8": "'Cái gì vô thường, khổ, chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: '",
  "sn24.1:4.9": "'gió không thổi, sông không chảy, phụ nữ mang thai không sinh con, mặt trăng mặt trời không mọc không lặn, đứng vững như cột trụ''? '",
  "sn24.1:4.10": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.1:4.11": "'Bất cứ điều gì đã được thấy, nghe, cảm nhận, nhận thức, đạt đến, tìm cầu, suy tầm bởi tâm  cái đó là thường còn hay vô thường?' ",
  "sn24.1:4.12": "'Vô thường, bạch Thế Tôn.' ",
  "sn24.1:4.13": "'Cái gì vô thường, cái đó là khổ hay lạc?' ",
  "sn24.1:4.14": "'Khổ, bạch Thế Tôn.' ",
  "sn24.1:4.15": "'Cái gì vô thường, khổ, chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: '",
  "sn24.1:4.16": "'gió không thổi, sông không chảy, phụ nữ mang thai không sinh con, mặt trăng mặt trời không mọc không lặn, đứng vững như cột trụ''? '",
  "sn24.1:4.17": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.1:5.1": "'Này các Tỳ Kheo, khi bậc Thánh đệ tử đã đoạn trừ nghi hoặc ở các điểm này, đã đoạn trừ nghi hoặc về khổ, đã đoạn trừ nghi hoặc về khổ tập, đã đoạn trừ nghi hoặc về khổ diệt, đã đoạn trừ nghi hoặc về con đường dẫn đến khổ diệt  '",
  "sn24.1:5.2": "vị ấy được gọi là, này các Tỳ Kheo, bậc Thánh đệ tử đã chứng Dự lưu, không còn đọa vào cõi ác, chắc chắn hướng đến giác ngộ.' ",
  "sn24.1:5.3": "Thứ nhất. ",
  "sn24.2:0.1": "Tương Ưng Bộ 24.2 ",
  "sn24.2:0.2": "1. Phẩm Dự Lưu ",
  "sn24.2:0.3": "Kinh Đây Là Của Ta ",
  "sn24.2:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.2:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.2:1.3": "'đây là của ta, ta là cái này, đây là tự ngã của ta''? '",
  "sn24.2:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.2:1.5": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.2:1.6": "'đây là của ta, ta là cái này, đây là tự ngã của ta'. ",
  "sn24.2:1.7": "Do có thọ …(viết tắt)… ",
  "sn24.2:1.8": "do có tưởng … ",
  "sn24.2:1.9": "do có hành … ",
  "sn24.2:1.10": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.2:1.11": "'đây là của ta, ta là cái này, đây là tự ngã của ta'. ",
  "sn24.2:2.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.2:2.2": "sắc là thường còn hay vô thường?' ",
  "sn24.2:2.3": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.2:2.4": "'thọ … '",
  "sn24.2:2.5": "tưởng … ",
  "sn24.2:2.6": "hành … ",
  "sn24.2:2.7": "thức là thường còn hay vô thường?' ",
  "sn24.2:2.8": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.2:2.9": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.2:2.10": "'đây là của ta, ta là cái này, đây là tự ngã của ta''? '",
  "sn24.2:2.11": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.2:2.12": "'Bất cứ điều gì đã được thấy, nghe, cảm nhận, nhận thức, đạt đến, tìm cầu, suy tầm bởi tâm  cái đó là thường còn hay vô thường?' ",
  "sn24.2:2.13": "'Vô thường, bạch Thế Tôn.' ",
  "sn24.2:2.14": "'Cái gì vô thường, cái đó là khổ hay lạc?' ",
  "sn24.2:2.15": "'Khổ, bạch Thế Tôn.' ",
  "sn24.2:2.16": "'Cái gì vô thường, khổ, chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: '",
  "sn24.2:2.17": "'đây là của ta, ta là cái này, đây là tự ngã của ta''? '",
  "sn24.2:2.18": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.2:3.1": "'Này các Tỳ Kheo, khi bậc Thánh đệ tử đã đoạn trừ nghi hoặc ở các điểm này, đã đoạn trừ nghi hoặc về khổ …(viết tắt)… đã đoạn trừ nghi hoặc về con đường dẫn đến khổ diệt  '",
  "sn24.2:3.2": "vị ấy được gọi là, này các Tỳ Kheo, bậc Thánh đệ tử đã chứng Dự lưu, không còn đọa vào cõi ác, chắc chắn hướng đến giác ngộ.' ",
  "sn24.2:3.3": "Thứ hai. ",
  "sn24.3:0.1": "Tương Ưng Bộ 24.3 ",
  "sn24.3:0.2": "1. Phẩm Dự Lưu ",
  "sn24.3:0.3": "Kinh Tự Ngã Đó Là Thế Giới Đó ",
  "sn24.3:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.3:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.3:1.3": "'tự ngã đó là thế giới đó, sau khi chết ta sẽ trở thành thường còn, vĩnh cửu, bất biến, không chịu sự biến hoại''? '",
  "sn24.3:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)…. '",
  "sn24.3:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.3:2.2": "'tự ngã đó là thế giới đó, sau khi chết ta sẽ trở thành thường còn, vĩnh cửu, bất biến, không chịu sự biến hoại'. ",
  "sn24.3:2.3": "Do có thọ …(viết tắt)… ",
  "sn24.3:2.4": "do có tưởng … ",
  "sn24.3:2.5": "do có hành … ",
  "sn24.3:2.6": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.3:2.7": "'tự ngã đó là thế giới đó, sau khi chết ta sẽ trở thành thường còn, vĩnh cửu, bất biến, không chịu sự biến hoại'. ",
  "sn24.3:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.3:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.3:3.3": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.3:3.4": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.3:3.5": "'tự ngã đó …(viết tắt)… '",
  "sn24.3:3.6": "không chịu sự biến hoại''? ",
  "sn24.3:3.7": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.3:3.8": "'Thọ … '",
  "sn24.3:3.9": "tưởng … ",
  "sn24.3:3.10": "hành … ",
  "sn24.3:3.11": "thức là thường còn hay vô thường?' ",
  "sn24.3:3.12": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.3:3.13": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.3:3.14": "'tự ngã đó …(viết tắt)… '",
  "sn24.3:3.15": "không chịu sự biến hoại''? ",
  "sn24.3:3.16": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.3:3.17": "'Bất cứ điều gì đã được thấy, nghe, cảm nhận, nhận thức, đạt đến, tìm cầu, suy tầm bởi tâm  cái đó là thường còn hay vô thường?' ",
  "sn24.3:3.18": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.3:3.19": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.3:3.20": "'tự ngã đó là thế giới đó, sau khi chết ta sẽ trở thành thường còn, vĩnh cửu, bất biến, không chịu sự biến hoại''? '",
  "sn24.3:3.21": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.3:4.1": "'Này các Tỳ Kheo, khi bậc Thánh đệ tử đã đoạn trừ nghi hoặc ở các điểm này, đã đoạn trừ nghi hoặc về khổ …(viết tắt)… đã đoạn trừ nghi hoặc về con đường dẫn đến khổ diệt  '",
  "sn24.3:4.2": "vị ấy được gọi là, này các Tỳ Kheo, bậc Thánh đệ tử đã chứng Dự lưu, không còn đọa vào cõi ác, chắc chắn hướng đến giác ngộ.' ",
  "sn24.3:4.3": "Thứ ba. ",
  "sn24.4:0.1": "Tương Ưng Bộ 24.4 ",
  "sn24.4:0.2": "1. Phẩm Dự Lưu ",
  "sn24.4:0.3": "Kinh Chớ Có Như Vậy Với Ta ",
  "sn24.4:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.4:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.4:1.3": "'ước gì ta không có, ước gì không có gì là của ta; ta sẽ không hiện hữu, sẽ không có gì là của ta''? '",
  "sn24.4:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)…. '",
  "sn24.4:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.4:2.2": "'ước gì ta không có, ước gì không có gì là của ta; ta sẽ không hiện hữu, sẽ không có gì là của ta'. ",
  "sn24.4:2.3": "Do có thọ … ",
  "sn24.4:2.4": "do có tưởng … ",
  "sn24.4:2.5": "do có hành … ",
  "sn24.4:2.6": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.4:2.7": "'ước gì ta không có, ước gì không có gì là của ta; ta sẽ không hiện hữu, sẽ không có gì là của ta'. ",
  "sn24.4:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.4:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.4:3.3": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.4:3.4": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.4:3.5": "'ước gì ta không có, ước gì không có gì là của ta; ta sẽ không hiện hữu, sẽ không có gì là của ta''? '",
  "sn24.4:3.6": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.4:3.7": "'Thọ … '",
  "sn24.4:3.8": "tưởng … ",
  "sn24.4:3.9": "hành … ",
  "sn24.4:3.10": "thức là thường còn hay vô thường?' ",
  "sn24.4:3.11": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.4:3.12": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.4:3.13": "'ước gì ta không có, ước gì không có gì là của ta; ta sẽ không hiện hữu, sẽ không có gì là của ta''? '",
  "sn24.4:3.14": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.4:3.15": "'Bất cứ điều gì đã được thấy, nghe, cảm nhận, nhận thức, đạt đến, tìm cầu, suy tầm bởi tâm  cái đó là thường còn hay vô thường?' ",
  "sn24.4:3.16": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.4:3.17": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.4:3.18": "'ước gì ta không có, ước gì không có gì là của ta; ta sẽ không hiện hữu, sẽ không có gì là của ta''? '",
  "sn24.4:3.19": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.4:4.1": "'Này các Tỳ Kheo, khi bậc Thánh đệ tử đã đoạn trừ nghi hoặc ở các điểm này, đã đoạn trừ nghi hoặc về khổ …(viết tắt)… đã đoạn trừ nghi hoặc về con đường dẫn đến khổ diệt  '",
  "sn24.4:4.2": "vị ấy được gọi là, này các Tỳ Kheo, bậc Thánh đệ tử đã chứng Dự lưu, không còn đọa vào cõi ác, chắc chắn hướng đến giác ngộ.' ",
  "sn24.4:4.3": "Thứ tư. ",
  "sn24.5:0.1": "Tương Ưng Bộ 24.5 ",
  "sn24.5:0.2": "1. Phẩm Dự Lưu ",
  "sn24.5:0.3": "Kinh Không Có Bố Thí ",
  "sn24.5:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.5:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.5:1.3": "'không có bố thí, không có cúng dường, không có hiến cúng, không có quả báo của các nghiệp thiện ác; không có đời này, không có đời sau, không có mẹ, không có cha, không có các chúng sanh hóa sanh; trong đời không có các sa-môn, bà-la-môn chân chánh tu hành, tự mình chứng ngộ và tuyên thuyết về đời này và đời sau. '",
  "sn24.5:1.4": "Con người gồm bốn đại, khi mệnh chung, địa đại trở về với địa, thủy đại trở về với thủy, hỏa đại trở về với hỏa, phong đại trở về với phong. ",
  "sn24.5:1.5": "Các căn tan biến vào hư không. ",
  "sn24.5:1.6": "Bốn người khiêng cáng đưa thi thể ra đi. ",
  "sn24.5:1.7": "Dấu chân chỉ còn thấy đến nơi hỏa thiêu. ",
  "sn24.5:1.8": "Xương trắng còn lại. ",
  "sn24.5:1.9": "Tro tàn sau khi thiêu. ",
  "sn24.5:1.10": "Bố thí là giáo lý của kẻ ngu si. ",
  "sn24.5:1.11": "Những ai nói về sự hiện hữu là nói lời trống rỗng, dối trá, vô nghĩa. ",
  "sn24.5:1.12": "Cả kẻ ngu lẫn người trí, khi thân hoại mạng chung đều bị đoạn diệt, tiêu mất, không còn tồn tại sau khi chết''? ",
  "sn24.5:1.13": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.5:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.5:2.2": "'không có bố thí, không có cúng dường …(viết tắt)… '",
  "sn24.5:2.3": "đều bị đoạn diệt, tiêu mất, không còn tồn tại sau khi chết'. ",
  "sn24.5:2.4": "Do có thọ …(viết tắt)… ",
  "sn24.5:2.5": "do có tưởng … ",
  "sn24.5:2.6": "do có hành … ",
  "sn24.5:2.7": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.5:2.8": "'không có bố thí, không có cúng dường …(viết tắt)… '",
  "sn24.5:2.9": "đều bị đoạn diệt, tiêu mất, không còn tồn tại sau khi chết'. ",
  "sn24.5:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.5:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.5:3.3": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.5:3.4": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.5:3.5": "'không có bố thí, không có cúng dường …(viết tắt)… '",
  "sn24.5:3.6": "đều bị đoạn diệt, tiêu mất, không còn tồn tại sau khi chết''? ",
  "sn24.5:3.7": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.5:3.8": "'Thọ … '",
  "sn24.5:3.9": "tưởng … ",
  "sn24.5:3.10": "hành … ",
  "sn24.5:3.11": "thức là thường còn hay vô thường?' ",
  "sn24.5:3.12": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.5:3.13": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.5:3.14": "'không có bố thí, không có cúng dường …(viết tắt)… '",
  "sn24.5:3.15": "đều bị đoạn diệt, tiêu mất, không còn tồn tại sau khi chết''? ",
  "sn24.5:3.16": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.5:3.17": "'Bất cứ điều gì đã được thấy, nghe, cảm nhận, nhận thức, đạt đến, tìm cầu, suy tầm bởi tâm  cái đó là thường còn hay vô thường?' ",
  "sn24.5:3.18": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.5:3.19": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.5:3.20": "'không có bố thí, không có cúng dường …(viết tắt)… '",
  "sn24.5:3.21": "những ai nói về sự hiện hữu là nói lời trống rỗng, dối trá, vô nghĩa; ",
  "sn24.5:3.22": "cả kẻ ngu lẫn người trí, khi thân hoại mạng chung đều bị đoạn diệt, tiêu mất, không còn tồn tại sau khi chết''? ",
  "sn24.5:3.23": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.5:4.1": "'Này các Tỳ Kheo, khi bậc Thánh đệ tử đã đoạn trừ nghi hoặc ở các điểm này, đã đoạn trừ nghi hoặc về khổ …(viết tắt)… đã đoạn trừ nghi hoặc về con đường dẫn đến khổ diệt  '",
  "sn24.5:4.2": "vị ấy được gọi là, này các Tỳ Kheo, bậc Thánh đệ tử đã chứng Dự lưu, không còn đọa vào cõi ác, chắc chắn hướng đến giác ngộ.' ",
  "sn24.5:4.3": "Thứ năm. ",
  "sn24.6:0.1": "Tương Ưng Bộ 24.6 ",
  "sn24.6:0.2": "1. Phẩm Dự Lưu ",
  "sn24.6:0.3": "Kinh Kẻ Làm ",
  "sn24.6:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.6:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.6:1.3": "'kẻ tự làm hay sai người làm, tự chặt hay sai người chặt, tự nấu hay sai người nấu, tự gây buồn hay làm người khác buồn, tự mệt mỏi hay làm người khác mệt mỏi, tự run rẩy hay làm người khác run rẩy, tự sát sanh, tự trộm cắp, tự đột nhập, tự cướp bóc, tự làm kẻ trộm một nhà, tự tà dâm, tự nói dối  kẻ ấy không tạo tác điều ác. '",
  "sn24.6:1.4": "Dù có dùng bánh xe bén sắc như dao cạo mà giết hại tất cả chúng sanh trên đất này thành một đống thịt, một đống thịt lớn, cũng không có tội lỗi nào từ đó, không có ác nghiệp nào đến. ",
  "sn24.6:1.5": "Dù có đi đến bờ nam sông Hằng, giết hại, sát sanh, chặt đứt, sai người chặt đứt, nấu, sai người nấu  cũng không có tội lỗi nào từ đó, không có ác nghiệp nào đến. ",
  "sn24.6:1.6": "Dù có đi đến bờ bắc sông Hằng, bố thí, sai người bố thí, tế lễ, sai người tế lễ  cũng không có phước đức nào từ đó, không có thiện nghiệp nào đến. ",
  "sn24.6:1.7": "Bố thí, tự chế, trì giới, nói thật  không có phước đức, không có thiện nghiệp nào đến''. ",
  "sn24.6:1.8": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.6:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.6:2.2": "'kẻ tự làm hay sai người làm …(viết tắt)… '",
  "sn24.6:2.3": "không có phước đức, không có thiện nghiệp nào đến'. ",
  "sn24.6:2.4": "Do có thọ …(viết tắt)… ",
  "sn24.6:2.5": "do có tưởng … ",
  "sn24.6:2.6": "do có hành … ",
  "sn24.6:2.7": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.6:2.8": "'kẻ tự làm hay sai người làm …(viết tắt)… '",
  "sn24.6:2.9": "không có phước đức, không có thiện nghiệp nào đến'. ",
  "sn24.6:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.6:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.6:3.3": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.6:3.4": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.6:3.5": "'kẻ tự làm hay sai người làm …(viết tắt)… '",
  "sn24.6:3.6": "không có phước đức, không có thiện nghiệp nào đến'? ",
  "sn24.6:3.7": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.6:3.8": "'Thọ … '",
  "sn24.6:3.9": "tưởng … ",
  "sn24.6:3.10": "hành … ",
  "sn24.6:3.11": "thức là thường còn hay vô thường?' ",
  "sn24.6:3.12": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.6:3.13": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.6:3.14": "'kẻ tự làm hay sai người làm …(viết tắt)… '",
  "sn24.6:3.15": "không có phước đức, không có thiện nghiệp nào đến''? ",
  "sn24.6:3.16": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.6:3.17": "'Bất cứ điều gì đã được thấy, nghe, cảm nhận, nhận thức, đạt đến, tìm cầu, suy tầm bởi tâm  cái đó là thường còn hay vô thường?' ",
  "sn24.6:3.18": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.6:3.19": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.6:3.20": "'kẻ tự làm hay sai người làm …(viết tắt)… '",
  "sn24.6:3.21": "không có phước đức, không có thiện nghiệp nào đến''? ",
  "sn24.6:3.22": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.6:4.1": "'Này các Tỳ Kheo, khi bậc Thánh đệ tử đã đoạn trừ nghi hoặc ở các điểm này, đã đoạn trừ nghi hoặc về khổ …(viết tắt)… đã đoạn trừ nghi hoặc về con đường dẫn đến khổ diệt  '",
  "sn24.6:4.2": "vị ấy được gọi là, này các Tỳ Kheo, bậc Thánh đệ tử đã chứng Dự lưu, không còn đọa vào cõi ác, chắc chắn hướng đến giác ngộ.' ",
  "sn24.6:4.3": "Thứ sáu. ",
  "sn24.7:0.1": "Tương Ưng Bộ 24.7 ",
  "sn24.7:0.2": "1. Phẩm Dự Lưu ",
  "sn24.7:0.3": "Kinh Không Có Nhân ",
  "sn24.7:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.7:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.7:1.3": "'không có nhân, không có duyên cho sự ô nhiễm của chúng sanh. '",
  "sn24.7:1.4": "Không nhân, không duyên mà chúng sanh bị ô nhiễm. ",
  "sn24.7:1.5": "Không có nhân, không có duyên cho sự thanh tịnh của chúng sanh. ",
  "sn24.7:1.6": "Không nhân, không duyên mà chúng sanh được thanh tịnh. ",
  "sn24.7:1.7": "Không có sức mạnh, không có tinh tấn, không có nỗ lực của người nam, không có sự cố gắng của người nam. ",
  "sn24.7:1.8": "Tất cả chúng sanh, tất cả loài hữu tình, tất cả loài sanh linh, tất cả loài có mạng sống  đều không có quyền năng, không có sức mạnh, không có tinh tấn; bị chi phối bởi số phận, sự ngẫu nhiên và bản chất, và cảm thọ khổ lạc trong sáu loại giai cấp''? ",
  "sn24.7:1.9": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.7:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.7:2.2": "'không có nhân, không có duyên …(viết tắt)… '",
  "sn24.7:2.3": "cảm thọ khổ lạc trong sáu loại giai cấp'. ",
  "sn24.7:2.4": "Do có thọ …(viết tắt)… ",
  "sn24.7:2.5": "do có tưởng … ",
  "sn24.7:2.6": "do có hành … ",
  "sn24.7:2.7": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.7:2.8": "'không có nhân, không có duyên …(viết tắt)… '",
  "sn24.7:2.9": "cảm thọ khổ lạc trong sáu loại giai cấp'. ",
  "sn24.7:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.7:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.7:3.3": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.7:3.4": "chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.7:3.5": "'không có nhân, không có duyên …(viết tắt)… '",
  "sn24.7:3.6": "cảm thọ khổ lạc trong sáu loại giai cấp''? ",
  "sn24.7:3.7": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.7:3.8": "'Thọ … '",
  "sn24.7:3.9": "tưởng … ",
  "sn24.7:3.10": "hành … ",
  "sn24.7:3.11": "thức là thường còn hay vô thường?' ",
  "sn24.7:3.12": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.7:3.13": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.7:3.14": "'không có nhân, không có duyên …(viết tắt)… '",
  "sn24.7:3.15": "cảm thọ khổ lạc trong sáu loại giai cấp''? ",
  "sn24.7:3.16": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.7:3.17": "'Bất cứ điều gì đã được thấy, nghe, cảm nhận, nhận thức, đạt đến, tìm cầu, suy tầm bởi tâm  cái đó là thường còn hay vô thường?' ",
  "sn24.7:3.18": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.7:3.19": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.7:3.20": "'không có nhân, không có duyên …(viết tắt)… '",
  "sn24.7:3.21": "cảm thọ khổ lạc trong sáu loại giai cấp''? ",
  "sn24.7:3.22": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.7:4.1": "'Này các Tỳ Kheo, khi bậc Thánh đệ tử đã đoạn trừ nghi hoặc ở các điểm này, đã đoạn trừ nghi hoặc về khổ …(viết tắt)… đã đoạn trừ nghi hoặc về con đường dẫn đến khổ diệt  '",
  "sn24.7:4.2": "vị ấy được gọi là, này các Tỳ Kheo, bậc Thánh đệ tử đã chứng Dự lưu, không còn đọa vào cõi ác, chắc chắn hướng đến giác ngộ.' ",
  "sn24.7:4.3": "Thứ bảy. ",
  "sn24.8:0.1": "Tương Ưng Bộ 24.8 ",
  "sn24.8:0.2": "1. Phẩm Dự Lưu ",
  "sn24.8:0.3": "Kinh Đại Tà Kiến ",
  "sn24.8:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.8:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.8:1.3": "'có bảy loại thân này, không do tạo tác, không do ai tạo ra theo khuôn mẫu, không do ai tạo nên, không do ai tạo ra, không sinh sản, đứng vững như đỉnh núi, đứng vững như cột trụ; '",
  "sn24.8:1.4": "chúng không lay chuyển, không biến đổi, không làm hại lẫn nhau; không có khả năng đem lại lạc hay khổ hay cả lạc lẫn khổ cho nhau. ",
  "sn24.8:1.5": "Bảy thứ đó là gì? ",
  "sn24.8:1.6": "Địa thân, thủy thân, hỏa thân, phong thân, lạc, khổ, và mạng sống là thứ bảy. ",
  "sn24.8:1.7": "Bảy loại thân này không do tạo tác, không do ai tạo ra theo khuôn mẫu, không do ai tạo nên, không do ai tạo ra, không sinh sản, đứng vững như đỉnh núi, đứng vững như cột trụ; ",
  "sn24.8:1.8": "chúng không lay chuyển, không biến đổi, không làm hại lẫn nhau; không có khả năng đem lại lạc hay khổ hay cả lạc lẫn khổ cho nhau. ",
  "sn24.8:1.9": "Dù kẻ nào dùng kiếm sắc bén chặt đầu người, cũng không có ai tước đoạt mạng sống của ai; ",
  "sn24.8:1.10": "kiếm chỉ lọt qua khoảng hở giữa bảy loại thân ấy mà thôi. ",
  "sn24.8:1.11": "Có một trăm bốn mươi bốn nghìn ngàn cửa thai sanh, sáu trăm tám mươi và sáu trăm nghiệp, năm trăm nghiệp, năm nghiệp, ba nghiệp, nghiệp và nửa nghiệp; sáu mươi hai con đường, sáu mươi hai thời kiếp, sáu loại sanh giai, tám địa vị của con người, bốn mươi chín trăm Ājīvaka, bốn mươi chín trăm du sĩ, bốn mươi chín trăm long cung, hai mươi trăm căn, ba mươi trăm địa ngục, ba mươi sáu loại bụi trần, bảy loại hữu tưởng thai, bảy loại vô tưởng thai, bảy loại Nigantha thai, bảy hạng thiên nhân, bảy hạng nhân loại, bảy loại phi nhân, bảy hồ, bảy nơi kết nút, bảy vực thẳm, bảy trăm vực thẳm, bảy loại mộng, bảy trăm loại mộng  có tám mươi tư nghìn đại kiếp mà kẻ ngu lẫn người trí đều phải lang thang luân hồi và rồi sẽ chấm dứt khổ đau. ",
  "sn24.8:1.12": "Ở đó không có điều này: 'do giới này, hay nguyện này, hay khổ hạnh này, hay phạm hạnh này, ta sẽ làm chín muồi nghiệp chưa chín muồi; ",
  "sn24.8:1.13": "hay ta sẽ tiếp xúc và đoạn trừ nghiệp đã chín muồi'  điều đó không có. Khổ lạc được đong đo như bằng đấu trong luân hồi có giới hạn, không có tăng thêm hay giảm bớt, không có thăng lên hay hạ xuống. ",
  "sn24.8:1.14": "Ví như cuộn chỉ khi tung ra thì tự duỗi ra hết; ",
  "sn24.8:1.15": "cũng vậy, kẻ ngu lẫn người trí, khi đã trải qua hết, sẽ chấm dứt khổ đau''? ",
  "sn24.8:1.16": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.8:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.8:2.2": "'có bảy loại thân này, không do tạo tác, không do ai tạo ra theo khuôn mẫu …(viết tắt)… '",
  "sn24.8:2.3": "kẻ ngu lẫn người trí, khi đã trải qua hết, sẽ chấm dứt khổ đau'. ",
  "sn24.8:2.4": "Do có thọ …(viết tắt)… ",
  "sn24.8:2.5": "do có tưởng … ",
  "sn24.8:2.6": "do có hành … ",
  "sn24.8:2.7": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.8:2.8": "'có bảy loại thân này, không do tạo tác, không do ai tạo ra theo khuôn mẫu …(viết tắt)… '",
  "sn24.8:2.9": "kẻ ngu lẫn người trí, khi đã trải qua hết, sẽ chấm dứt khổ đau'. ",
  "sn24.8:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.8:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.8:3.3": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.8:3.4": "'cái gì vô thường, khổ, chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: '",
  "sn24.8:3.5": "'có bảy loại thân này, không do tạo tác, không do ai tạo ra theo khuôn mẫu …(viết tắt)… '",
  "sn24.8:3.6": "kẻ ngu lẫn người trí, khi đã trải qua hết, sẽ chấm dứt khổ đau''? ",
  "sn24.8:3.7": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.8:3.8": "'Bất cứ điều gì đã được thấy, nghe, cảm nhận, nhận thức, đạt đến, tìm cầu, suy tầm bởi tâm  cái đó là thường còn hay vô thường?' ",
  "sn24.8:3.9": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.8:3.10": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.8:3.11": "'có bảy loại thân này, không do tạo tác, không do ai tạo ra theo khuôn mẫu …(viết tắt)… '",
  "sn24.8:3.12": "kẻ ngu lẫn người trí, khi đã trải qua hết, sẽ chấm dứt khổ đau''? ",
  "sn24.8:3.13": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.8:4.1": "'Này các Tỳ Kheo, khi bậc Thánh đệ tử đã đoạn trừ nghi hoặc ở các điểm này, đã đoạn trừ nghi hoặc về khổ …(viết tắt)… đã đoạn trừ nghi hoặc về con đường dẫn đến khổ diệt  '",
  "sn24.8:4.2": "vị ấy được gọi là, này các Tỳ Kheo, bậc Thánh đệ tử đã chứng Dự lưu, không còn đọa vào cõi ác, chắc chắn hướng đến giác ngộ.' ",
  "sn24.8:4.3": "Thứ tám. ",
  "sn24.9:0.1": "Tương Ưng Bộ 24.9 ",
  "sn24.9:0.2": "1. Phẩm Dự Lưu ",
  "sn24.9:0.3": "Kinh Thường Kiến ",
  "sn24.9:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.9:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.9:1.3": "'thế giới là thường còn''? '",
  "sn24.9:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.9:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.9:2.2": "'thế giới là thường còn'. ",
  "sn24.9:2.3": "Do có thọ …(viết tắt)… ",
  "sn24.9:2.4": "do có hành … ",
  "sn24.9:2.5": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.9:2.6": "'thế giới là thường còn'. ",
  "sn24.9:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.9:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.9:3.3": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.9:3.4": "chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.9:3.5": "'thế giới là thường còn''? '",
  "sn24.9:3.6": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.9:3.7": "'Thọ … '",
  "sn24.9:3.8": "tưởng … ",
  "sn24.9:3.9": "hành … ",
  "sn24.9:3.10": "thức là thường còn hay vô thường?' ",
  "sn24.9:3.11": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.9:3.12": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.9:3.13": "'thế giới là thường còn''? '",
  "sn24.9:3.14": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.9:3.15": "'Bất cứ điều gì đã được thấy, nghe, cảm nhận, nhận thức, đạt đến, tìm cầu, suy tầm bởi tâm  cái đó là thường còn hay vô thường?' ",
  "sn24.9:3.16": "'Vô thường, bạch Thế Tôn.' ",
  "sn24.9:3.17": "'Cái gì vô thường, cái đó là khổ hay lạc?' ",
  "sn24.9:3.18": "'Khổ, bạch Thế Tôn.' ",
  "sn24.9:3.19": "'Cái gì vô thường, khổ, chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: '",
  "sn24.9:3.20": "'thế giới là thường còn''? '",
  "sn24.9:3.21": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.9:4.1": "'Này các Tỳ Kheo, khi bậc Thánh đệ tử đã đoạn trừ nghi hoặc ở các điểm này, đã đoạn trừ nghi hoặc về khổ …(viết tắt)… đã đoạn trừ nghi hoặc về con đường dẫn đến khổ diệt  '",
  "sn24.9:4.2": "vị ấy được gọi là, này các Tỳ Kheo, bậc Thánh đệ tử đã chứng Dự lưu, không còn đọa vào cõi ác, chắc chắn hướng đến giác ngộ.' ",
  "sn24.9:4.3": "Thứ chín. ",
  "sn24.10:0.1": "Tương Ưng Bộ 24.10 ",
  "sn24.10:0.2": "1. Phẩm Dự Lưu ",
  "sn24.10:0.3": "Kinh Đoạn Kiến ",
  "sn24.10:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.10:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.10:1.3": "'thế giới là vô thường''? '",
  "sn24.10:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.10:2.1": "'Này các Tỳ Kheo, do có sắc …(viết tắt)… '",
  "sn24.10:2.2": "thức là thường còn hay vô thường?' ",
  "sn24.10:2.3": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.10:2.4": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.10:2.5": "'thế giới là vô thường''? '",
  "sn24.10:2.6": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.10:2.7": "'Bất cứ điều gì đã được thấy, nghe, cảm nhận, nhận thức, đạt đến, tìm cầu, suy tầm bởi tâm  cái đó là thường còn hay vô thường?' ",
  "sn24.10:2.8": "'Vô thường, bạch Thế Tôn …(viết tắt)… '",
  "sn24.10:2.9": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.10:2.10": "'thế giới là vô thường''? '",
  "sn24.10:2.11": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.10:3.1": "'Này các Tỳ Kheo, khi bậc Thánh đệ tử đã đoạn trừ nghi hoặc ở các điểm này, đã đoạn trừ nghi hoặc về khổ …(viết tắt)… đã đoạn trừ nghi hoặc về con đường dẫn đến khổ diệt  '",
  "sn24.10:3.2": "vị ấy được gọi là, này các Tỳ Kheo, bậc Thánh đệ tử đã chứng Dự lưu, không còn đọa vào cõi ác, chắc chắn hướng đến giác ngộ.' ",
  "sn24.10:3.3": "Thứ mười. ",
  "sn24.11:0.1": "Tương Ưng Bộ 24.11 ",
  "sn24.11:0.2": "1. Phẩm Dự Lưu ",
  "sn24.11:0.3": "Kinh Thế Giới Là Hữu Hạn ",
  "sn24.11:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.11:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.11:1.3": "'thế giới là hữu hạn''? '",
  "sn24.11:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.11:1.5": "chắc chắn hướng đến giác ngộ.' ",
  "sn24.11:1.6": "Thứ mười một. ",
  "sn24.12:0.1": "Tương Ưng Bộ 24.12 ",
  "sn24.12:0.2": "1. Phẩm Dự Lưu ",
  "sn24.12:0.3": "Kinh Thế Giới Là Vô Hạn ",
  "sn24.12:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.12:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.12:1.3": "'thế giới là vô hạn''? '",
  "sn24.12:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.12:1.5": "chắc chắn hướng đến giác ngộ.' ",
  "sn24.12:1.6": "Thứ mười hai. ",
  "sn24.13:0.1": "Tương Ưng Bộ 24.13 ",
  "sn24.13:0.2": "1. Phẩm Dự Lưu ",
  "sn24.13:0.3": "Kinh Linh Hồn Và Thân Xác Là Một ",
  "sn24.13:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.13:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.13:1.3": "'linh hồn và thân xác là một''? '",
  "sn24.13:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.13:1.5": "chắc chắn hướng đến giác ngộ.' ",
  "sn24.13:1.6": "Thứ mười ba. ",
  "sn24.14:0.1": "Tương Ưng Bộ 24.14 ",
  "sn24.14:0.2": "1. Phẩm Dự Lưu ",
  "sn24.14:0.3": "Kinh Linh Hồn Và Thân Xác Là Khác Nhau ",
  "sn24.14:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.14:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.14:1.3": "'linh hồn và thân xác là khác nhau''? '",
  "sn24.14:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.14:1.5": "chắc chắn hướng đến giác ngộ.' ",
  "sn24.14:1.6": "Thứ mười bốn. ",
  "sn24.15:0.1": "Tương Ưng Bộ 24.15 ",
  "sn24.15:0.2": "1. Phẩm Dự Lưu ",
  "sn24.15:0.3": "Kinh Như Lai Tồn Tại Sau Khi Chết ",
  "sn24.15:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.15:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.15:1.3": "'Như Lai tồn tại sau khi chết''? '",
  "sn24.15:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.15:1.5": "chắc chắn hướng đến giác ngộ.' ",
  "sn24.15:1.6": "Thứ mười lăm. ",
  "sn24.16:0.1": "Tương Ưng Bộ 24.16 ",
  "sn24.16:0.2": "1. Phẩm Dự Lưu ",
  "sn24.16:0.3": "Kinh Như Lai Không Tồn Tại Sau Khi Chết ",
  "sn24.16:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.16:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.16:1.3": "'Như Lai không tồn tại sau khi chết''? '",
  "sn24.16:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.16:1.5": "chắc chắn hướng đến giác ngộ.' ",
  "sn24.16:1.6": "Thứ mười sáu. ",
  "sn24.17:0.1": "Tương Ưng Bộ 24.17 ",
  "sn24.17:0.2": "1. Phẩm Dự Lưu ",
  "sn24.17:0.3": "Kinh Như Lai Vừa Tồn Tại Vừa Không Tồn Tại Sau Khi Chết ",
  "sn24.17:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.17:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.17:1.3": "'Như Lai vừa tồn tại vừa không tồn tại sau khi chết''? '",
  "sn24.17:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.17:1.5": "chắc chắn hướng đến giác ngộ.' ",
  "sn24.17:1.6": "Thứ mười bảy. ",
  "sn24.18:0.1": "Tương Ưng Bộ 24.18 ",
  "sn24.18:0.2": "1. Phẩm Dự Lưu ",
  "sn24.18:0.3": "Kinh Như Lai Không Tồn Tại Cũng Không Không Tồn Tại Sau Khi Chết ",
  "sn24.18:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.18:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.18:1.3": "'Như Lai không tồn tại cũng không không tồn tại sau khi chết''? '",
  "sn24.18:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.18:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.18:2.2": "'Như Lai không tồn tại cũng không không tồn tại sau khi chết'' …(viết tắt)…. '",
  "sn24.18:3.1": "'Này các Tỳ Kheo, các ông nghĩ thế nào, '",
  "sn24.18:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.18:3.3": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.18:3.4": "chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.18:3.5": "'Như Lai không tồn tại cũng không không tồn tại sau khi chết''? '",
  "sn24.18:3.6": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.18:3.7": "'Bất cứ điều gì đã được thấy, nghe, cảm nhận, nhận thức, đạt đến, tìm cầu, suy tầm bởi tâm  cái đó là thường còn hay vô thường?' ",
  "sn24.18:3.8": "'Vô thường, bạch Thế Tôn.' ",
  "sn24.18:3.9": "'Cái gì vô thường, cái đó là khổ hay lạc?' ",
  "sn24.18:3.10": "'Khổ, bạch Thế Tôn.' ",
  "sn24.18:3.11": "'Cái gì vô thường, khổ, chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: '",
  "sn24.18:3.12": "'Như Lai không tồn tại cũng không không tồn tại sau khi chết''? '",
  "sn24.18:3.13": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.18:4.1": "'Này các Tỳ Kheo, khi bậc Thánh đệ tử đã đoạn trừ nghi hoặc ở các điểm này, đã đoạn trừ nghi hoặc về khổ, đã đoạn trừ nghi hoặc về khổ tập, đã đoạn trừ nghi hoặc về khổ diệt, đã đoạn trừ nghi hoặc về con đường dẫn đến khổ diệt  '",
  "sn24.18:4.2": "vị ấy được gọi là, này các Tỳ Kheo, bậc Thánh đệ tử đã chứng Dự lưu, không còn đọa vào cõi ác, chắc chắn hướng đến giác ngộ.' ",
  "sn24.18:4.3": "Thứ mười tám. ",
  "sn24.18:4.4": "Phẩm Dự Lưu. ",
  "sn24.18:4.5": "Mười tám giải thuyết đã hoàn tất. ",
  "sn24.18:5.0": "Kệ tóm lược ",
  "sn24.18:5.1": "Gió, đây là của ta, ",
  "sn24.18:5.2": "tự ngã đó, ước gì không có gì là của ta; ",
  "sn24.18:5.3": "Không có bố thí, kẻ làm, không có nhân, ",
  "sn24.18:5.4": "đại tà kiến là thứ tám. ",
  "sn24.18:6.1": "Thế giới là thường còn, ",
  "sn24.18:6.2": "vô thường và hữu hạn; ",
  "sn24.18:6.3": "vô hạn, linh hồn và thân xác là một, ",
  "sn24.18:6.4": "linh hồn và thân xác là khác nhau. ",
  "sn24.18:7.1": "Như Lai tồn tại sau khi chết, ",
  "sn24.18:7.2": "Như Lai không tồn tại sau khi chết; ",
  "sn24.18:7.3": "Như Lai vừa tồn tại vừa không tồn tại sau khi chết. ",
  "sn24.19:0.1": "Tương Ưng Bộ 24.19 ",
  "sn24.19:0.2": "2. Phẩm Lần Thứ Hai ",
  "sn24.19:0.3": "Kinh Gió ",
  "sn24.19:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.19:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.19:1.3": "'gió không thổi, sông không chảy, phụ nữ mang thai không sinh con, mặt trăng mặt trời không mọc không lặn, đứng vững như cột trụ''? '",
  "sn24.19:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.19:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.19:2.2": "'gió không thổi …(viết tắt)… đứng vững như cột trụ'. ",
  "sn24.19:2.3": "Do có thọ …(viết tắt)… ",
  "sn24.19:2.4": "do có tưởng …(viết tắt)… ",
  "sn24.19:2.5": "do có hành … ",
  "sn24.19:2.6": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.19:2.7": "'gió không thổi …(viết tắt)… đứng vững như cột trụ'. ",
  "sn24.19:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.19:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.19:3.3": "'Vô thường, bạch Thế Tôn' …(viết tắt)… chịu sự biến hoại, ",
  "sn24.19:3.4": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không  ",
  "sn24.19:3.5": "gió không thổi …(viết tắt)… đứng vững như cột trụ'? ",
  "sn24.19:3.6": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.19:3.7": "'Như vậy, này các Tỳ Kheo, do có khổ, do chấp thủ khổ, do thiên chấp khổ mà tà kiến này sinh khởi: '",
  "sn24.19:3.8": "'gió không thổi …(viết tắt)… đứng vững như cột trụ''. '",
  "sn24.19:3.9": "'Thọ … '",
  "sn24.19:3.10": "tưởng … ",
  "sn24.19:3.11": "hành … ",
  "sn24.19:3.12": "thức là thường còn hay vô thường?' ",
  "sn24.19:3.13": "'Vô thường, bạch Thế Tôn' …(viết tắt)… chịu sự biến hoại, ",
  "sn24.19:3.14": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không ",
  "sn24.19:3.15": "'gió không thổi …(viết tắt)… đứng vững như cột trụ''? '",
  "sn24.19:3.16": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.19:3.17": "'Như vậy, này các Tỳ Kheo, do có khổ, do chấp thủ khổ, do thiên chấp khổ mà tà kiến này sinh khởi: '",
  "sn24.19:3.18": "'gió không thổi, sông không chảy, phụ nữ mang thai không sinh con, mặt trăng mặt trời không mọc không lặn, đứng vững như cột trụ''. '",
  "sn24.19:3.19": "Thứ nhất. ",
  "sn24.20-35:0.1": "Tương Ưng Bộ 24.20–35 ",
  "sn24.20-35:0.2": "2. Phẩm Lần Thứ Hai ",
  "sn24.20-35:0.3": "Kinh Đây Là Của Ta v.v. ",
  "sn24.20-35:1.1": "(Nên trình bày đầy đủ mười tám giải thuyết như phẩm trước.) ",
  "sn24.20-35:1.2": "Thứ mười bảy. ",
  "sn24.36:0.1": "Tương Ưng Bộ 24.36 ",
  "sn24.36:0.2": "2. Phẩm Lần Thứ Hai ",
  "sn24.36:0.3": "Kinh Như Lai Không Tồn Tại Cũng Không Không Tồn Tại ",
  "sn24.36:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.36:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.36:1.3": "'Như Lai không tồn tại cũng không không tồn tại sau khi chết''? '",
  "sn24.36:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.36:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.36:2.2": "'Như Lai không tồn tại cũng không không tồn tại sau khi chết''. '",
  "sn24.36:2.3": "'Do có thọ … '",
  "sn24.36:2.4": "do có tưởng … ",
  "sn24.36:2.5": "do có hành … ",
  "sn24.36:2.6": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.36:2.7": "'Như Lai không tồn tại cũng không không tồn tại sau khi chết'. ",
  "sn24.36:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.36:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.36:3.3": "'Vô thường, bạch Thế Tôn' …(viết tắt)… chịu sự biến hoại, ",
  "sn24.36:3.4": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.36:3.5": "'Như Lai không tồn tại cũng không không tồn tại sau khi chết''? '",
  "sn24.36:3.6": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.36:3.7": "'Như vậy, này các Tỳ Kheo, do có khổ, do chấp thủ khổ, do thiên chấp khổ mà tà kiến này sinh khởi: '",
  "sn24.36:3.8": "'Như Lai không tồn tại cũng không không tồn tại sau khi chết''. '",
  "sn24.36:3.9": "'Thọ … '",
  "sn24.36:3.10": "tưởng … ",
  "sn24.36:3.11": "hành … ",
  "sn24.36:3.12": "thức là thường còn hay vô thường?' ",
  "sn24.36:3.13": "'Vô thường, bạch Thế Tôn' …(viết tắt)… chịu sự biến hoại, ",
  "sn24.36:3.14": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.36:3.15": "'Như Lai không tồn tại cũng không không tồn tại sau khi chết''? '",
  "sn24.36:3.16": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.36:3.17": "'Như vậy, này các Tỳ Kheo, do có khổ, do chấp thủ khổ, do thiên chấp khổ mà tà kiến này sinh khởi: '",
  "sn24.36:3.18": "'Như Lai không tồn tại cũng không không tồn tại sau khi chết''. '",
  "sn24.36:3.19": "Thứ mười tám. ",
  "sn24.37:0.1": "Tương Ưng Bộ 24.37 ",
  "sn24.37:0.2": "2. Phẩm Lần Thứ Hai ",
  "sn24.37:0.3": "Kinh Tự Ngã Có Sắc ",
  "sn24.37:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.37:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.37:1.3": "'tự ngã có sắc, không bệnh hoạn, tồn tại sau khi chết''? '",
  "sn24.37:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.37:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.37:2.2": "'tự ngã có sắc, không bệnh hoạn, tồn tại sau khi chết'. ",
  "sn24.37:2.3": "Do có thọ …(viết tắt)… ",
  "sn24.37:2.4": "do có tưởng … ",
  "sn24.37:2.5": "do có hành … ",
  "sn24.37:2.6": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.37:2.7": "'tự ngã có sắc, không bệnh hoạn, tồn tại sau khi chết'. ",
  "sn24.37:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, sắc là thường còn hay vô thường?' ",
  "sn24.37:3.2": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.37:3.3": "chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.37:3.4": "'tự ngã có sắc, không bệnh hoạn, tồn tại sau khi chết''? '",
  "sn24.37:3.5": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.37:3.6": "'Như vậy, này các Tỳ Kheo, do có khổ, do chấp thủ khổ, do thiên chấp khổ mà tà kiến này sinh khởi: '",
  "sn24.37:3.7": "'tự ngã có sắc, không bệnh hoạn, tồn tại sau khi chết''? '",
  "sn24.37:3.8": "'Thọ …(viết tắt)… '",
  "sn24.37:3.9": "'thưa không, bạch Thế Tôn.' ",
  "sn24.37:3.10": "'Như vậy, này các Tỳ Kheo, do có khổ, do chấp thủ khổ, do thiên chấp khổ mà tà kiến này sinh khởi: '",
  "sn24.37:3.11": "'tự ngã có sắc, không bệnh hoạn, tồn tại sau khi chết''. '",
  "sn24.37:3.12": "Thứ mười chín. ",
  "sn24.38:0.1": "Tương Ưng Bộ 24.38 ",
  "sn24.38:0.2": "2. Phẩm Lần Thứ Hai ",
  "sn24.38:0.3": "Kinh Tự Ngã Không Có Sắc ",
  "sn24.38:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.38:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.38:1.3": "'tự ngã không có sắc, không bệnh hoạn, tồn tại sau khi chết''? '",
  "sn24.38:1.4": "(Toát yếu.) ",
  "sn24.38:1.5": "Thứ hai mươi. ",
  "sn24.39:0.1": "Tương Ưng Bộ 24.39 ",
  "sn24.39:0.2": "2. Phẩm Lần Thứ Hai ",
  "sn24.39:0.3": "Kinh Tự Ngã Vừa Có Sắc Vừa Không Có Sắc ",
  "sn24.39:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.39:1.2": "'Tự ngã vừa có sắc vừa không có sắc, không bệnh hoạn, tồn tại sau khi chết'' …(viết tắt)…. '",
  "sn24.39:1.3": "Thứ hai mươi mốt. ",
  "sn24.40:0.1": "Tương Ưng Bộ 24.40 ",
  "sn24.40:0.2": "2. Phẩm Lần Thứ Hai ",
  "sn24.40:0.3": "Kinh Tự Ngã Không Sắc Không Phi Sắc ",
  "sn24.40:1.1": "'Tự ngã không có sắc cũng không không có sắc, không bệnh hoạn, tồn tại sau khi chết'' …(viết tắt)…. '",
  "sn24.40:1.2": "Thứ hai mươi hai. ",
  "sn24.41:0.1": "Tương Ưng Bộ 24.41 ",
  "sn24.41:0.2": "2. Phẩm Lần Thứ Hai ",
  "sn24.41:0.3": "Kinh Tự Ngã Thuần Lạc ",
  "sn24.41:1.1": "'Tự ngã thuần lạc, không bệnh hoạn, tồn tại sau khi chết'' …(viết tắt)…. '",
  "sn24.41:1.2": "Thứ hai mươi ba. ",
  "sn24.42:0.1": "Tương Ưng Bộ 24.42 ",
  "sn24.42:0.2": "2. Phẩm Lần Thứ Hai ",
  "sn24.42:0.3": "Kinh Tự Ngã Thuần Khổ ",
  "sn24.42:1.1": "'Tự ngã thuần khổ, không bệnh hoạn, tồn tại sau khi chết'' …(viết tắt)…. '",
  "sn24.42:1.2": "Thứ hai mươi bốn. ",
  "sn24.43:0.1": "Tương Ưng Bộ 24.43 ",
  "sn24.43:0.2": "2. Phẩm Lần Thứ Hai ",
  "sn24.43:0.3": "Kinh Tự Ngã Vừa Lạc Vừa Khổ ",
  "sn24.43:1.1": "'Tự ngã vừa lạc vừa khổ, không bệnh hoạn, tồn tại sau khi chết'' …(viết tắt)…. '",
  "sn24.43:1.2": "Thứ hai mươi lăm. ",
  "sn24.44:0.1": "Tương Ưng Bộ 24.44 ",
  "sn24.44:0.2": "2. Phẩm Lần Thứ Hai ",
  "sn24.44:0.3": "Kinh Tự Ngã Không Khổ Không Lạc ",
  "sn24.44:1.1": "'Tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết''? '",
  "sn24.44:1.2": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)… '",
  "sn24.44:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.44:2.2": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết'. ",
  "sn24.44:2.3": "Do có thọ … ",
  "sn24.44:2.4": "do có tưởng … ",
  "sn24.44:2.5": "do có hành … ",
  "sn24.44:2.6": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.44:2.7": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết'. ",
  "sn24.44:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, sắc là thường còn hay vô thường?' ",
  "sn24.44:3.2": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.44:3.3": "chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.44:3.4": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết''? '",
  "sn24.44:3.5": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.44:3.6": "'Như vậy, này các Tỳ Kheo, do có khổ, do chấp thủ khổ, do thiên chấp khổ mà tà kiến này sinh khởi: '",
  "sn24.44:3.7": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết''. '",
  "sn24.44:3.8": "'Thọ … '",
  "sn24.44:3.9": "tưởng … ",
  "sn24.44:3.10": "hành … ",
  "sn24.44:3.11": "thức là thường còn hay vô thường?' ",
  "sn24.44:3.12": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.44:3.13": "chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.44:3.14": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết''? '",
  "sn24.44:3.15": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.44:3.16": "'Như vậy, này các Tỳ Kheo, do có khổ, do chấp thủ khổ, do thiên chấp khổ mà tà kiến này sinh khởi: '",
  "sn24.44:3.17": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết''. '",
  "sn24.44:3.18": "Thứ hai mươi sáu. ",
  "sn24.44:3.19": "Toát yếu lần thứ hai. ",
  "sn24.44:4.0": "Kệ tóm lược ",
  "sn24.44:4.1": "Gió, đây là của ta, tự ngã đó, ",
  "sn24.44:4.2": "ước gì không có gì là của ta; ",
  "sn24.44:4.3": "không có bố thí, kẻ làm, không có nhân, ",
  "sn24.44:4.4": "đại tà kiến là thứ tám. ",
  "sn24.44:5.1": "Thế giới là thường còn và vô thường, ",
  "sn24.44:5.2": "hữu hạn và vô hạn; ",
  "sn24.44:5.3": "linh hồn và thân xác là một, linh hồn và thân xác là khác, ",
  "sn24.44:5.4": "bốn kiến về Như Lai. ",
  "sn24.44:6.1": "Tự ngã có sắc tồn tại, tự ngã không có sắc tồn tại, ",
  "sn24.44:6.2": "tự ngã vừa có sắc vừa không có sắc tồn tại; ",
  "sn24.44:6.3": "tự ngã không sắc không phi sắc tồn tại, ",
  "sn24.44:6.4": "tự ngã thuần lạc tồn tại. ",
  "sn24.44:7.1": "Tự ngã thuần khổ tồn tại, ",
  "sn24.44:7.2": "tự ngã vừa lạc vừa khổ tồn tại; ",
  "sn24.44:7.3": "tự ngã không khổ không lạc tồn tại, ",
  "sn24.44:7.4": "không bệnh hoạn sau khi chết; ",
  "sn24.44:7.5": "hai mươi sáu bài kinh này, ",
  "sn24.44:7.6": "được thuyết giảng lần thứ hai. ",
  "sn24.45:0.1": "Tương Ưng Bộ 24.45 ",
  "sn24.45:0.2": "3. Phẩm Lần Thứ Ba ",
  "sn24.45:0.3": "Kinh Gió ",
  "sn24.45:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.45:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.45:1.3": "'gió không thổi, sông không chảy, phụ nữ mang thai không sinh con, mặt trăng mặt trời không mọc không lặn, đứng vững như cột trụ''? '",
  "sn24.45:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)…. '",
  "sn24.45:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi  '",
  "sn24.45:2.2": "gió không thổi …(viết tắt)… ",
  "sn24.45:2.3": "do có thọ … ",
  "sn24.45:2.4": "do có tưởng … ",
  "sn24.45:2.5": "do có hành … ",
  "sn24.45:2.6": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.45:2.7": "'gió không thổi …(viết tắt)… đứng vững như cột trụ'. ",
  "sn24.45:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.45:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.45:3.3": "'Vô thường, bạch Thế Tôn' …(viết tắt)… ",
  "sn24.45:3.4": "chịu sự biến hoại, nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.45:3.5": "'gió không thổi …(viết tắt)… đứng vững như cột trụ''? '",
  "sn24.45:3.6": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.45:3.7": "'Như vậy, này các Tỳ Kheo, cái gì vô thường thì cái đó là khổ. '",
  "sn24.45:3.8": "Do có cái đó, do chấp thủ cái đó, tà kiến này sinh khởi: ",
  "sn24.45:3.9": "'gió không thổi, sông không chảy, phụ nữ mang thai không sinh con, mặt trăng mặt trời không mọc không lặn, đứng vững như cột trụ''. '",
  "sn24.45:3.10": "'Thọ … '",
  "sn24.45:3.11": "tưởng … ",
  "sn24.45:3.12": "hành … ",
  "sn24.45:3.13": "thức là thường còn hay vô thường?' ",
  "sn24.45:3.14": "'Vô thường, bạch Thế Tôn' …(viết tắt)… chịu sự biến hoại, ",
  "sn24.45:3.15": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.45:3.16": "'gió không thổi …(viết tắt)… đứng vững như cột trụ''? '",
  "sn24.45:3.17": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.45:3.18": "'Như vậy, này các Tỳ Kheo, cái gì vô thường thì cái đó là khổ. '",
  "sn24.45:3.19": "Do có cái đó, do chấp thủ cái đó, tà kiến này sinh khởi: ",
  "sn24.45:3.20": "'gió không thổi …(viết tắt)… đứng vững như cột trụ''. '",
  "sn24.45:3.21": "Thứ nhất. ",
  "sn24.46-69:0.1": "Tương Ưng Bộ 24.46–69 ",
  "sn24.46-69:0.2": "3. Phẩm Lần Thứ Ba ",
  "sn24.46-69:0.3": "Kinh Đây Là Của Ta v.v. ",
  "sn24.46-69:1.1": "(Nên hoàn tất hai mươi bốn bài kinh như phẩm thứ hai.) ",
  "sn24.46-69:1.2": "Thứ hai mươi lăm. ",
  "sn24.70:0.1": "Tương Ưng Bộ 24.70 ",
  "sn24.70:0.2": "3. Phẩm Lần Thứ Ba ",
  "sn24.70:0.3": "Kinh Tự Ngã Không Khổ Không Lạc ",
  "sn24.70:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.70:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.70:1.3": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết''? '",
  "sn24.70:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)…. '",
  "sn24.70:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.70:2.2": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết''. '",
  "sn24.70:2.3": "'Do có thọ …(viết tắt)… '",
  "sn24.70:2.4": "do có tưởng … ",
  "sn24.70:2.5": "do có hành … ",
  "sn24.70:2.6": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.70:2.7": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết'. ",
  "sn24.70:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.70:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.70:3.3": "'Vô thường, bạch Thế Tôn' …(viết tắt)… chịu sự biến hoại, ",
  "sn24.70:3.4": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.70:3.5": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết''? '",
  "sn24.70:3.6": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.70:3.7": "'Như vậy, này các Tỳ Kheo, cái gì vô thường thì cái đó là khổ. '",
  "sn24.70:3.8": "Do có cái đó, do chấp thủ cái đó, tà kiến này sinh khởi: ",
  "sn24.70:3.9": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết''. '",
  "sn24.70:3.10": "'Thọ …(viết tắt)… '",
  "sn24.70:3.11": "tưởng … ",
  "sn24.70:3.12": "hành … ",
  "sn24.70:3.13": "thức là thường còn hay vô thường?' ",
  "sn24.70:3.14": "'Vô thường, bạch Thế Tôn' …(viết tắt)… chịu sự biến hoại, ",
  "sn24.70:3.15": "nếu không chấp thủ cái đó, liệu tà kiến này có sinh khởi không: ",
  "sn24.70:3.16": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết''? '",
  "sn24.70:3.17": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.70:3.18": "'Như vậy, này các Tỳ Kheo, cái gì vô thường thì cái đó là khổ. '",
  "sn24.70:3.19": "Do có cái đó, do chấp thủ cái đó, tà kiến này sinh khởi: ",
  "sn24.70:3.20": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết''. '",
  "sn24.70:3.21": "Thứ hai mươi sáu. ",
  "sn24.70:3.22": "Toát yếu lần thứ ba. ",
  "sn24.71:0.1": "Tương Ưng Bộ 24.71 ",
  "sn24.71:0.2": "4. Phẩm Lần Thứ Tư ",
  "sn24.71:0.3": "Kinh Gió ",
  "sn24.71:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.71:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.71:1.3": "'gió không thổi, sông không chảy, phụ nữ mang thai không sinh con, mặt trăng mặt trời không mọc không lặn, đứng vững như cột trụ''? '",
  "sn24.71:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)…. '",
  "sn24.71:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.71:2.2": "'gió không thổi …(viết tắt)… đứng vững như cột trụ'. ",
  "sn24.71:2.3": "Do có thọ …(viết tắt)… ",
  "sn24.71:2.4": "do có tưởng … ",
  "sn24.71:2.5": "do có hành … ",
  "sn24.71:2.6": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.71:2.7": "'gió không thổi …(viết tắt)… đứng vững như cột trụ''. '",
  "sn24.71:2.8": "'Này các Tỳ Kheo, các ông nghĩ thế nào, '",
  "sn24.71:2.9": "sắc là thường còn hay vô thường?' ",
  "sn24.71:2.10": "'Vô thường, bạch Thế Tôn.' ",
  "sn24.71:2.11": "'Cái gì vô thường, cái đó là khổ hay lạc?' ",
  "sn24.71:2.12": "'Khổ, bạch Thế Tôn.' ",
  "sn24.71:2.13": "'Cái gì vô thường, khổ, chịu sự biến hoại, liệu có nên quán chiếu cái đó là: '",
  "sn24.71:2.14": "'đây là của ta, ta là cái này, đây là tự ngã của ta''? '",
  "sn24.71:2.15": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.71:2.16": "'Thọ … '",
  "sn24.71:2.17": "tưởng … ",
  "sn24.71:2.18": "hành … ",
  "sn24.71:2.19": "thức là thường còn hay vô thường?' ",
  "sn24.71:2.20": "'Vô thường, bạch Thế Tôn.' ",
  "sn24.71:2.21": "'Cái gì vô thường, cái đó là khổ hay lạc?' ",
  "sn24.71:2.22": "'Khổ, bạch Thế Tôn.' ",
  "sn24.71:2.23": "'Cái gì vô thường, khổ, chịu sự biến hoại, liệu có nên quán chiếu cái đó là: '",
  "sn24.71:2.24": "'đây là của ta, ta là cái này, đây là tự ngã của ta''? '",
  "sn24.71:2.25": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.71:3.1": "'Do vậy, này các Tỳ Kheo, bất kỳ sắc nào  quá khứ, vị lai hay hiện tại; nội hay ngoại; thô hay tế; hạ liệt hay cao thượng; xa hay gần  tất cả sắc đều nên được quán chiếu đúng như thật bằng trí tuệ chân chánh rằng: 'cái này không phải của ta, ta không phải là cái này, cái này không phải là tự ngã của ta'. '",
  "sn24.71:3.2": "Bất kỳ thọ nào … ",
  "sn24.71:3.3": "bất kỳ tưởng nào … ",
  "sn24.71:3.4": "bất kỳ hành nào … ",
  "sn24.71:3.5": "bất kỳ thức nào  quá khứ, vị lai hay hiện tại; nội hay ngoại; thô hay tế; hạ liệt hay cao thượng; xa hay gần  tất cả thức đều nên được quán chiếu đúng như thật bằng trí tuệ chân chánh rằng: 'cái này không phải của ta, ta không phải là cái này, cái này không phải là tự ngã của ta'. ",
  "sn24.71:4.1": "Thấy vậy …(viết tắt)… ",
  "sn24.71:4.2": "vị ấy biết rõ: 'không còn tái sanh nữa'.' ",
  "sn24.71:4.3": "Thứ nhất. ",
  "sn24.72-95:0.1": "Tương Ưng Bộ 24.72–95 ",
  "sn24.72-95:0.2": "4. Phẩm Lần Thứ Tư ",
  "sn24.72-95:0.3": "Kinh Đây Là Của Ta v.v. ",
  "sn24.72-95:1.1": "(Nên hoàn tất hai mươi bốn bài kinh như phẩm thứ hai.) ",
  "sn24.72-95:1.2": "Thứ hai mươi lăm. ",
  "sn24.96:0.1": "Tương Ưng Bộ 24.96 ",
  "sn24.96:0.2": "4. Phẩm Lần Thứ Tư ",
  "sn24.96:0.3": "Kinh Tự Ngã Không Khổ Không Lạc ",
  "sn24.96:1.1": "Nhân duyên tại Sāvatthi (Xá-vệ). ",
  "sn24.96:1.2": "'Này các Tỳ Kheo, do có cái gì, do chấp thủ cái gì, do thiên chấp cái gì mà tà kiến này sinh khởi: '",
  "sn24.96:1.3": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết''? '",
  "sn24.96:1.4": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản …(viết tắt)…. '",
  "sn24.96:2.1": "'Này các Tỳ Kheo, do có sắc, do chấp thủ sắc, do thiên chấp sắc mà tà kiến này sinh khởi: '",
  "sn24.96:2.2": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết'. ",
  "sn24.96:2.3": "Do có thọ … ",
  "sn24.96:2.4": "do có tưởng … ",
  "sn24.96:2.5": "do có hành … ",
  "sn24.96:2.6": "do có thức, do chấp thủ thức, do thiên chấp thức mà tà kiến này sinh khởi: ",
  "sn24.96:2.7": "'tự ngã không khổ không lạc, không bệnh hoạn, tồn tại sau khi chết'. ",
  "sn24.96:3.1": "Này các Tỳ Kheo, các ông nghĩ thế nào, ",
  "sn24.96:3.2": "sắc là thường còn hay vô thường?' ",
  "sn24.96:3.3": "'Vô thường, bạch Thế Tôn.' ",
  "sn24.96:3.4": "'Cái gì vô thường, cái đó là khổ hay lạc?' ",
  "sn24.96:3.5": "'Khổ, bạch Thế Tôn.' ",
  "sn24.96:3.6": "'Cái gì vô thường, khổ, chịu sự biến hoại, liệu có nên quán chiếu cái đó là: '",
  "sn24.96:3.7": "'đây là của ta, ta là cái này, đây là tự ngã của ta''? '",
  "sn24.96:3.8": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.96:3.9": "'Thọ … '",
  "sn24.96:3.10": "tưởng … ",
  "sn24.96:3.11": "hành … ",
  "sn24.96:3.12": "thức là thường còn hay vô thường?' ",
  "sn24.96:3.13": "'Vô thường, bạch Thế Tôn.' ",
  "sn24.96:3.14": "'Cái gì vô thường, cái đó là khổ hay lạc?' ",
  "sn24.96:3.15": "'Khổ, bạch Thế Tôn.' ",
  "sn24.96:3.16": "'Cái gì vô thường, khổ, chịu sự biến hoại, liệu có nên quán chiếu cái đó là: '",
  "sn24.96:3.17": "'đây là của ta, ta là cái này, đây là tự ngã của ta''? '",
  "sn24.96:3.18": "'Thưa không, bạch Thế Tôn.' ",
  "sn24.96:4.1": "'Do vậy, này các Tỳ Kheo, bất kỳ sắc nào  quá khứ, vị lai hay hiện tại; nội hay ngoại; thô hay tế; hạ liệt hay cao thượng; xa hay gần  tất cả sắc đều nên được quán chiếu đúng như thật bằng trí tuệ chân chánh rằng: 'cái này không phải của ta, ta không phải là cái này, cái này không phải là tự ngã của ta'. '",
  "sn24.96:4.2": "Bất kỳ thọ nào … ",
  "sn24.96:4.3": "bất kỳ tưởng nào … ",
  "sn24.96:4.4": "bất kỳ hành nào … ",
  "sn24.96:4.5": "bất kỳ thức nào  quá khứ, vị lai hay hiện tại; nội hay ngoại; thô hay tế; hạ liệt hay cao thượng; xa hay gần  tất cả thức đều nên được quán chiếu đúng như thật bằng trí tuệ chân chánh rằng: 'cái này không phải của ta, ta không phải là cái này, cái này không phải là tự ngã của ta'. ",
  "sn24.96:5.1": "Này các Tỳ Kheo, thấy vậy, bậc Thánh đệ tử có văn học nhàm chán đối với sắc, nhàm chán đối với thọ, nhàm chán đối với tưởng, nhàm chán đối với hành, nhàm chán đối với thức. ",
  "sn24.96:5.2": "Do nhàm chán, vị ấy ly tham; do ly tham, vị ấy giải thoát. Khi đã giải thoát, trí biết rằng: 'Ta đã giải thoát'. ",
  "sn24.96:5.3": "'Sanh đã tận, phạm hạnh đã thành, việc cần làm đã làm, không còn trở lại đời sống này nữa'.' '",
  "sn24.96:5.4": "Toát yếu lần thứ tư. ",
  "sn24.96:6.0": "Kệ tóm lược ",
  "sn24.96:6.1": "Lần đầu mười tám giải thuyết, ",
  "sn24.96:6.2": "lần thứ hai hai mươi sáu nên trình bày đầy đủ; ",
  "sn24.96:6.3": "lần thứ ba hai mươi sáu nên trình bày đầy đủ, ",
  "sn24.96:6.4": "lần thứ tư hai mươi sáu nên trình bày đầy đủ. ",
  "sn24.96:6.5": "Tương Ưng Kiến đã hoàn tất. "
}
window.BILARA["sn24_v1"]["vi"]["sn24_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
