window.BILARA = window.BILARA || {};
window.BILARA["sn26_v1"] = window.BILARA["sn26_v1"] || {};
window.BILARA["sn26_v1"]["vi"] = {
  "sn26.1:0.1": "Tương Ưng Bộ 26.1 ",
  "sn26.1:0.2": "1. Phẩm Sinh Khởi ",
  "sn26.1:0.3": "Kinh Mắt ",
  "sn26.1:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn26.1:1.2": "'Này các Tỳ Kheo, sự sinh khởi, tồn tại, phát sinh, hiện khởi của mắt chính là sự sinh khởi của khổ, sự tồn tại của bệnh, sự hiện khởi của già và chết. '",
  "sn26.1:1.3": "Sự sinh khởi, tồn tại… của tai… ",
  "sn26.1:1.4": "Sự sinh khởi, tồn tại… của mũi… ",
  "sn26.1:1.5": "Sự sinh khởi, tồn tại… của lưỡi… ",
  "sn26.1:1.6": "Sự sinh khởi, tồn tại… của thân… ",
  "sn26.1:1.7": "Sự sinh khởi, tồn tại, phát sinh, hiện khởi của ý chính là sự sinh khởi của khổ, sự tồn tại của bệnh, sự hiện khởi của già và chết. ",
  "sn26.1:1.8": "Này các Tỳ Kheo, sự diệt, lắng dịu, tiêu diệt của mắt chính là sự diệt của khổ, sự lắng dịu của bệnh, sự tiêu diệt của già và chết. ",
  "sn26.1:1.9": "Sự diệt… của tai… ",
  "sn26.1:1.10": "Sự diệt… của mũi… ",
  "sn26.1:1.11": "Sự diệt… của lưỡi… ",
  "sn26.1:1.12": "Sự diệt… của thân… ",
  "sn26.1:1.13": "Sự diệt, lắng dịu, tiêu diệt của ý chính là sự diệt của khổ, sự lắng dịu của bệnh, sự tiêu diệt của già và chết'. ",
  "sn26.1:1.14": "Phần thứ nhất. ",
  "sn26.2:0.1": "Tương Ưng Bộ 26.2 ",
  "sn26.2:0.2": "1. Phẩm Sinh Khởi ",
  "sn26.2:0.3": "Kinh Sắc ",
  "sn26.2:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn26.2:1.2": "'Này các Tỳ Kheo, sự sinh khởi, tồn tại, phát sinh, hiện khởi của các sắc chính là sự sinh khởi của khổ, sự tồn tại của bệnh, sự hiện khởi của già và chết. '",
  "sn26.2:1.3": "Sự sinh khởi… của các âm thanh… ",
  "sn26.2:1.4": "Sự sinh khởi… của các mùi… ",
  "sn26.2:1.5": "Sự sinh khởi… của các vị… ",
  "sn26.2:1.6": "Sự sinh khởi… của các xúc chạm… ",
  "sn26.2:1.7": "Sự sinh khởi, tồn tại, phát sinh, hiện khởi của các pháp chính là sự sinh khởi của khổ, sự tồn tại của bệnh, sự hiện khởi của già và chết. ",
  "sn26.2:1.8": "Này các Tỳ Kheo, sự diệt, lắng dịu, tiêu diệt của các sắc chính là sự diệt của khổ, sự lắng dịu của bệnh, sự tiêu diệt của già và chết. ",
  "sn26.2:1.9": "Sự diệt… của các âm thanh… ",
  "sn26.2:1.10": "Sự diệt… của các mùi… ",
  "sn26.2:1.11": "Sự diệt… của các vị… ",
  "sn26.2:1.12": "Sự diệt… của các xúc chạm… ",
  "sn26.2:1.13": "Sự diệt, lắng dịu, tiêu diệt của các pháp chính là sự diệt của khổ, sự lắng dịu của bệnh, sự tiêu diệt của già và chết'. ",
  "sn26.2:1.14": "Phần thứ hai. ",
  "sn26.3:0.1": "Tương Ưng Bộ 26.3 ",
  "sn26.3:0.2": "1. Phẩm Sinh Khởi ",
  "sn26.3:0.3": "Kinh Thức ",
  "sn26.3:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn26.3:1.2": "'Này các Tỳ Kheo, sự sinh khởi, tồn tại… của nhãn thức… '",
  "sn26.3:1.3": "sự hiện khởi của già và chết… ",
  "sn26.3:1.4": "Sự sinh khởi, tồn tại… của ý thức… ",
  "sn26.3:1.5": "sự hiện khởi của già và chết. ",
  "sn26.3:1.6": "Này các Tỳ Kheo, sự diệt… của nhãn thức… ",
  "sn26.3:1.7": "sự tiêu diệt của già và chết… ",
  "sn26.3:1.8": "Sự diệt… của ý thức… ",
  "sn26.3:1.9": "sự tiêu diệt của già và chết'. ",
  "sn26.3:1.10": "Phần thứ ba. ",
  "sn26.4:0.1": "Tương Ưng Bộ 26.4 ",
  "sn26.4:0.2": "1. Phẩm Sinh Khởi ",
  "sn26.4:0.3": "Kinh Xúc ",
  "sn26.4:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn26.4:1.2": "'Này các Tỳ Kheo, sự sinh khởi, tồn tại… của nhãn xúc… '",
  "sn26.4:1.3": "sự hiện khởi của già và chết… ",
  "sn26.4:1.4": "Sự sinh khởi, tồn tại… của ý xúc… ",
  "sn26.4:1.5": "sự hiện khởi của già và chết. ",
  "sn26.4:1.6": "Này các Tỳ Kheo, sự diệt… của nhãn xúc… ",
  "sn26.4:1.7": "sự tiêu diệt của già và chết… ",
  "sn26.4:1.8": "Sự diệt… của ý xúc… ",
  "sn26.4:1.9": "sự tiêu diệt của già và chết'. ",
  "sn26.4:1.10": "Phần thứ tư. ",
  "sn26.5:0.1": "Tương Ưng Bộ 26.5 ",
  "sn26.5:0.2": "1. Phẩm Sinh Khởi ",
  "sn26.5:0.3": "Kinh Thọ Do Xúc Sinh ",
  "sn26.5:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn26.5:1.2": "'Này các Tỳ Kheo, sự sinh khởi, tồn tại… của thọ do nhãn xúc sinh… sự hiện khởi của già và chết… '",
  "sn26.5:2.1": "Sự sinh khởi, tồn tại… của thọ do ý xúc sinh… ",
  "sn26.5:2.2": "sự hiện khởi của già và chết. ",
  "sn26.5:2.3": "Này các Tỳ Kheo, sự diệt, lắng dịu… của thọ do nhãn xúc sinh… ",
  "sn26.5:2.4": "sự tiêu diệt của già và chết… ",
  "sn26.5:2.5": "Sự diệt, lắng dịu, tiêu diệt của thọ do ý xúc sinh chính là sự diệt của khổ, sự lắng dịu của bệnh, sự tiêu diệt của già và chết'. ",
  "sn26.5:2.6": "Phần thứ năm. ",
  "sn26.6:0.1": "Tương Ưng Bộ 26.6 ",
  "sn26.6:0.2": "1. Phẩm Sinh Khởi ",
  "sn26.6:0.3": "Kinh Tưởng ",
  "sn26.6:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn26.6:1.2": "'Này các Tỳ Kheo, sự sinh khởi, tồn tại… của tưởng về sắc… '",
  "sn26.6:1.3": "sự hiện khởi của già và chết… ",
  "sn26.6:1.4": "Sự sinh khởi, tồn tại, phát sinh, hiện khởi của tưởng về pháp chính là sự sinh khởi của khổ, sự tồn tại của bệnh, sự hiện khởi của già và chết. ",
  "sn26.6:1.5": "Này các Tỳ Kheo, sự diệt… của tưởng về sắc… ",
  "sn26.6:1.6": "sự tiêu diệt của già và chết… ",
  "sn26.6:1.7": "Sự diệt, lắng dịu, tiêu diệt của tưởng về pháp chính là sự diệt của khổ, sự lắng dịu của bệnh, sự tiêu diệt của già và chết'. ",
  "sn26.6:1.8": "Phần thứ sáu. ",
  "sn26.7:0.1": "Tương Ưng Bộ 26.7 ",
  "sn26.7:0.2": "1. Phẩm Sinh Khởi ",
  "sn26.7:0.3": "Kinh Tư ",
  "sn26.7:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn26.7:1.2": "'Này các Tỳ Kheo, sự sinh khởi, tồn tại… của tư về sắc… '",
  "sn26.7:1.3": "sự hiện khởi của già và chết… ",
  "sn26.7:1.4": "Sự sinh khởi, tồn tại, phát sinh, hiện khởi của tư về pháp chính là sự sinh khởi của khổ, sự tồn tại của bệnh, sự hiện khởi của già và chết. ",
  "sn26.7:1.5": "Này các Tỳ Kheo, sự diệt… của tư về sắc… ",
  "sn26.7:1.6": "sự tiêu diệt của già và chết… ",
  "sn26.7:1.7": "Sự diệt, lắng dịu, tiêu diệt của tư về pháp chính là sự diệt của khổ, sự lắng dịu của bệnh, sự tiêu diệt của già và chết'. ",
  "sn26.7:1.8": "Phần thứ bảy. ",
  "sn26.8:0.1": "Tương Ưng Bộ 26.8 ",
  "sn26.8:0.2": "1. Phẩm Sinh Khởi ",
  "sn26.8:0.3": "Kinh Tham Ái ",
  "sn26.8:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn26.8:1.2": "'Này các Tỳ Kheo, sự sinh khởi, tồn tại… của tham ái về sắc… '",
  "sn26.8:1.3": "sự hiện khởi của già và chết… ",
  "sn26.8:1.4": "Sự sinh khởi, tồn tại, phát sinh, hiện khởi của tham ái về pháp chính là sự sinh khởi của khổ, sự tồn tại của bệnh, sự hiện khởi của già và chết. ",
  "sn26.8:1.5": "Này các Tỳ Kheo, sự diệt… của tham ái về sắc… ",
  "sn26.8:1.6": "sự tiêu diệt của già và chết… ",
  "sn26.8:1.7": "Sự diệt, lắng dịu, tiêu diệt của tham ái về pháp chính là sự diệt của khổ, sự lắng dịu của bệnh, sự tiêu diệt của già và chết'. ",
  "sn26.8:1.8": "Phần thứ tám. ",
  "sn26.9:0.1": "Tương Ưng Bộ 26.9 ",
  "sn26.9:0.2": "1. Phẩm Sinh Khởi ",
  "sn26.9:0.3": "Kinh Giới ",
  "sn26.9:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn26.9:1.2": "'Này các Tỳ Kheo, sự sinh khởi, tồn tại, phát sinh, hiện khởi của địa đại… sự hiện khởi của già và chết; '",
  "sn26.9:1.3": "Sự sinh khởi… của thủy đại… ",
  "sn26.9:1.4": "Sự sinh khởi… của hỏa đại… ",
  "sn26.9:1.5": "Sự sinh khởi… của phong đại… ",
  "sn26.9:1.6": "Sự sinh khởi… của không đại… ",
  "sn26.9:1.7": "Sự sinh khởi, tồn tại, phát sinh, hiện khởi của thức đại chính là sự sinh khởi của khổ, sự tồn tại của bệnh, sự hiện khởi của già và chết. ",
  "sn26.9:1.8": "Này các Tỳ Kheo, sự diệt… của địa đại… sự tiêu diệt của già và chết; ",
  "sn26.9:1.9": "Sự diệt… của thủy đại… ",
  "sn26.9:1.10": "Sự diệt… của hỏa đại… ",
  "sn26.9:1.11": "Sự diệt… của phong đại… ",
  "sn26.9:1.12": "Sự diệt… của không đại… ",
  "sn26.9:1.13": "Sự diệt, lắng dịu, tiêu diệt của thức đại chính là sự diệt của khổ, sự lắng dịu của bệnh, sự tiêu diệt của già và chết'. ",
  "sn26.9:1.14": "Phần thứ chín. ",
  "sn26.10:0.1": "Tương Ưng Bộ 26.10 ",
  "sn26.10:0.2": "1. Phẩm Sinh Khởi ",
  "sn26.10:0.3": "Kinh Uẩn ",
  "sn26.10:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn26.10:1.2": "'Này các Tỳ Kheo, sự sinh khởi, tồn tại, phát sinh, hiện khởi của sắc chính là sự sinh khởi của khổ, sự tồn tại của bệnh, sự hiện khởi của già và chết. '",
  "sn26.10:1.3": "Sự sinh khởi… của thọ… ",
  "sn26.10:1.4": "Sự sinh khởi… của tưởng… ",
  "sn26.10:1.5": "Sự sinh khởi… của các hành… ",
  "sn26.10:1.6": "Sự sinh khởi, tồn tại, phát sinh, hiện khởi của thức chính là sự sinh khởi của khổ, sự tồn tại của bệnh, sự hiện khởi của già và chết. ",
  "sn26.10:1.7": "Này các Tỳ Kheo, sự diệt, lắng dịu, tiêu diệt của sắc chính là sự diệt của khổ, sự lắng dịu của bệnh, sự tiêu diệt của già và chết. ",
  "sn26.10:1.8": "Sự diệt… của thọ… ",
  "sn26.10:1.9": "Sự diệt… của tưởng… ",
  "sn26.10:1.10": "Sự diệt… của các hành… ",
  "sn26.10:1.11": "Sự diệt, lắng dịu, tiêu diệt của thức chính là sự diệt của khổ, sự lắng dịu của bệnh, sự tiêu diệt của già và chết'. ",
  "sn26.10:1.12": "Phần thứ mười. ",
  "sn26.10:1.13": "Phẩm Sinh Khởi, phần thứ nhất. ",
  "sn26.10:2.0": "Tóm lược: ",
  "sn26.10:2.1": "Mắt và sắc, thức, ",
  "sn26.10:2.2": "xúc và thọ; ",
  "sn26.10:2.3": "Tưởng, tư, tham ái, ",
  "sn26.10:2.4": "giới và uẩn  mười bài đó. ",
  "sn26.10:2.5": "Tương Ưng Sinh Khởi kết thúc. "
}
window.BILARA["sn26_v1"]["vi"]["sn26_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
