window.BILARA = window.BILARA || {};
window.BILARA["sn28_v1"] = window.BILARA["sn28_v1"] || {};
window.BILARA["sn28_v1"]["vi"] = {
  "sn28.1:0.1": "Tương Ưng Bộ 28.1 ",
  "sn28.1:0.2": "1. Phẩm Xá-Lợi-Phất ",
  "sn28.1:0.3": "Kinh Sinh Từ Viễn Ly ",
  "sn28.1:1.1": "Một thời, Tôn giả Sāriputta trú tại Sāvatthi, rừng Jetavana, tu viện của Anāthapiṇḍika. ",
  "sn28.1:1.2": "Rồi Tôn giả Sāriputta vào buổi sáng, đắp y, mang bát đi vào Sāvatthi để khất thực. ",
  "sn28.1:1.3": "Sau khi khất thực ở Sāvatthi và dùng bữa xong, Ngài đi đến rừng Andha để nghỉ ngơi ban ngày. ",
  "sn28.1:1.4": "Đi sâu vào rừng Andha, Ngài ngồi nghỉ ngơi ban ngày dưới gốc một cây. ",
  "sn28.1:2.1": "Rồi Tôn giả Sāriputta, vào buổi chiều, từ chỗ thiền tịnh đứng dậy, đi đến tu viện Jetavana của Anāthapiṇḍika. ",
  "sn28.1:2.2": "Tôn giả Ānanda thấy Tôn giả Sāriputta từ xa đang đi đến. ",
  "sn28.1:2.3": "Thấy vậy, Ngài nói với Tôn giả Sāriputta rằng: ",
  "sn28.1:2.4": "'Thưa đạo hữu Sāriputta, các căn của Ngài thật trong sáng; nhan sắc thật thanh tịnh, thuần khiết. '",
  "sn28.1:2.5": "Hôm nay Tôn giả Sāriputta đã an trú trong trạng thái thiền nào?' ",
  "sn28.1:3.1": "'Ở đây, thưa đạo hữu, hoàn toàn ly dục, ly các pháp bất thiện, tôi chứng và trú sơ thiền, có tầm, có tứ, với hỷ và lạc sinh từ viễn ly. '",
  "sn28.1:3.2": "Nhưng, thưa đạo hữu, tôi không có ý nghĩ: ",
  "sn28.1:3.3": "'Tôi đang nhập sơ thiền', hay 'Tôi đã nhập sơ thiền', hay 'Tôi đã xuất khỏi sơ thiền'.' '",
  "sn28.1:3.4": "Vì rằng, Tôn giả Sāriputta từ lâu đã nhổ tận gốc ngã chấp, ngã sở chấp và mạn tùy miên. ",
  "sn28.1:3.5": "Vì vậy, Tôn giả Sāriputta không có ý nghĩ: ",
  "sn28.1:3.6": "''Tôi đang nhập sơ thiền', hay 'Tôi đã nhập sơ thiền', hay 'Tôi đã xuất khỏi sơ thiền'.' ",
  "sn28.1:3.7": "Thứ nhất. ",
  "sn28.2:0.1": "Tương Ưng Bộ 28.2 ",
  "sn28.2:0.2": "1. Phẩm Xá-Lợi-Phất ",
  "sn28.2:0.3": "Kinh Không Tầm ",
  "sn28.2:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn28.2:1.2": "Tôn giả Ānanda thấy... Tôn giả Sāriputta nói rằng: ",
  "sn28.2:1.3": "'Thưa đạo hữu Sāriputta, các căn của Ngài thật trong sáng; nhan sắc thật thanh tịnh, thuần khiết. '",
  "sn28.2:1.4": "Hôm nay Tôn giả Sāriputta đã an trú trong trạng thái thiền nào?' ",
  "sn28.2:2.1": "'Ở đây, thưa đạo hữu, do sự lắng dịu của tầm và tứ, nội tâm tịnh tín, nhất tâm, không tầm, không tứ, tôi chứng và trú nhị thiền, với hỷ và lạc sinh từ định. '",
  "sn28.2:2.2": "Nhưng, thưa đạo hữu, tôi không có ý nghĩ: ",
  "sn28.2:2.3": "'Tôi đang nhập nhị thiền', hay 'Tôi đã nhập nhị thiền', hay 'Tôi đã xuất khỏi nhị thiền'.' '",
  "sn28.2:2.4": "Vì rằng, Tôn giả Sāriputta từ lâu đã nhổ tận gốc ngã chấp, ngã sở chấp và mạn tùy miên. ",
  "sn28.2:2.5": "Vì vậy, Tôn giả Sāriputta không có ý nghĩ: ",
  "sn28.2:2.6": "''Tôi đang nhập nhị thiền', hay 'Tôi đã nhập nhị thiền', hay 'Tôi đã xuất khỏi nhị thiền'.' ",
  "sn28.2:2.7": "Thứ hai. ",
  "sn28.3:0.1": "Tương Ưng Bộ 28.3 ",
  "sn28.3:0.2": "1. Phẩm Xá-Lợi-Phất ",
  "sn28.3:0.3": "Kinh Hỷ ",
  "sn28.3:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn28.3:1.2": "Tôn giả Ānanda thấy... ",
  "sn28.3:1.3": "'Thưa đạo hữu Sāriputta, các căn của Ngài thật trong sáng; nhan sắc thật thanh tịnh, thuần khiết. '",
  "sn28.3:1.4": "Hôm nay Tôn giả Sāriputta đã an trú trong trạng thái thiền nào?' ",
  "sn28.3:2.1": "'Ở đây, thưa đạo hữu, do ly hỷ, tôi trú xả, có chánh niệm và tỉnh giác, thân cảm thọ lạc mà các bậc Thánh gọi là 'người xả, có niệm, an trú lạc'; tôi chứng và trú tam thiền. '",
  "sn28.3:2.2": "Nhưng, thưa đạo hữu, tôi không có ý nghĩ: ",
  "sn28.3:2.3": "'Tôi đang nhập tam thiền', hay 'Tôi đã nhập tam thiền', hay 'Tôi đã xuất khỏi tam thiền'.' '",
  "sn28.3:2.4": "Vì rằng, Tôn giả Sāriputta từ lâu đã nhổ tận gốc ngã chấp, ngã sở chấp và mạn tùy miên. ",
  "sn28.3:2.5": "Vì vậy, Tôn giả Sāriputta không có ý nghĩ: ",
  "sn28.3:2.6": "''Tôi đang nhập tam thiền', hay 'Tôi đã nhập tam thiền', hay 'Tôi đã xuất khỏi tam thiền'.' ",
  "sn28.3:2.7": "Thứ ba. ",
  "sn28.4:0.1": "Tương Ưng Bộ 28.4 ",
  "sn28.4:0.2": "1. Phẩm Xá-Lợi-Phất ",
  "sn28.4:0.3": "Kinh Xả ",
  "sn28.4:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn28.4:1.2": "Tôn giả Ānanda thấy... ",
  "sn28.4:1.3": "'Thưa đạo hữu Sāriputta, các căn của Ngài thật trong sáng; nhan sắc thật thanh tịnh, thuần khiết. '",
  "sn28.4:1.4": "Hôm nay Tôn giả Sāriputta đã an trú trong trạng thái thiền nào?' ",
  "sn28.4:2.1": "'Ở đây, thưa đạo hữu, do đoạn trừ lạc và khổ, do sự biến mất của hỷ ưu từ trước, tôi chứng và trú tứ thiền, không khổ không lạc, xả niệm thanh tịnh. '",
  "sn28.4:2.2": "Nhưng, thưa đạo hữu, tôi không có ý nghĩ: ",
  "sn28.4:2.3": "'Tôi đang nhập tứ thiền', hay 'Tôi đã nhập tứ thiền', hay 'Tôi đã xuất khỏi tứ thiền'.' '",
  "sn28.4:2.4": "Vì rằng, Tôn giả Sāriputta từ lâu đã nhổ tận gốc ngã chấp, ngã sở chấp và mạn tùy miên. ",
  "sn28.4:2.5": "Vì vậy, Tôn giả Sāriputta không có ý nghĩ: ",
  "sn28.4:2.6": "''Tôi đang nhập tứ thiền', hay 'Tôi đã nhập tứ thiền', hay 'Tôi đã xuất khỏi tứ thiền'.' ",
  "sn28.4:2.7": "Thứ tư. ",
  "sn28.5:0.1": "Tương Ưng Bộ 28.5 ",
  "sn28.5:0.2": "1. Phẩm Xá-Lợi-Phất ",
  "sn28.5:0.3": "Kinh Không Vô Biên Xứ ",
  "sn28.5:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn28.5:1.2": "Tôn giả Ānanda thấy... ",
  "sn28.5:1.3": "'Ở đây, thưa đạo hữu, vượt qua hoàn toàn các sắc tưởng, đoạn diệt các đối ngại tưởng, không tác ý đến các dị tưởng, với ý tưởng 'hư không là vô biên', tôi chứng và trú không vô biên xứ... '",
  "sn28.5:1.4": "hay 'Tôi đã xuất khỏi'.' ",
  "sn28.5:1.5": "Thứ năm. ",
  "sn28.6:0.1": "Tương Ưng Bộ 28.6 ",
  "sn28.6:0.2": "1. Phẩm Xá-Lợi-Phất ",
  "sn28.6:0.3": "Kinh Thức Vô Biên Xứ ",
  "sn28.6:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn28.6:1.2": "Tôn giả Ānanda thấy... ",
  "sn28.6:1.3": "'Ở đây, thưa đạo hữu, vượt qua hoàn toàn không vô biên xứ, với ý tưởng 'thức là vô biên', tôi chứng và trú thức vô biên xứ... '",
  "sn28.6:1.4": "hay 'Tôi đã xuất khỏi'.' ",
  "sn28.6:1.5": "Thứ sáu. ",
  "sn28.7:0.1": "Tương Ưng Bộ 28.7 ",
  "sn28.7:0.2": "1. Phẩm Xá-Lợi-Phất ",
  "sn28.7:0.3": "Kinh Vô Sở Hữu Xứ ",
  "sn28.7:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn28.7:1.2": "Rồi Tôn giả Sāriputta... ",
  "sn28.7:1.3": "'Ở đây, thưa đạo hữu, vượt qua hoàn toàn thức vô biên xứ, với ý tưởng 'không có gì cả', tôi chứng và trú vô sở hữu xứ... '",
  "sn28.7:1.4": "hay 'Tôi đã xuất khỏi'.' ",
  "sn28.7:1.5": "Thứ bảy. ",
  "sn28.8:0.1": "Tương Ưng Bộ 28.8 ",
  "sn28.8:0.2": "1. Phẩm Xá-Lợi-Phất ",
  "sn28.8:0.3": "Kinh Phi Tưởng Phi Phi Tưởng Xứ ",
  "sn28.8:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn28.8:1.2": "Rồi Tôn giả Sāriputta... ",
  "sn28.8:1.3": "'Ở đây, thưa đạo hữu, vượt qua hoàn toàn vô sở hữu xứ, tôi chứng và trú phi tưởng phi phi tưởng xứ... '",
  "sn28.8:1.4": "hay 'Tôi đã xuất khỏi'.' ",
  "sn28.8:1.5": "Thứ tám. ",
  "sn28.9:0.1": "Tương Ưng Bộ 28.9 ",
  "sn28.9:0.2": "1. Phẩm Xá-Lợi-Phất ",
  "sn28.9:0.3": "Kinh Diệt Thọ Tưởng Định ",
  "sn28.9:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn28.9:1.2": "Rồi Tôn giả Sāriputta... ",
  "sn28.9:1.3": "'Ở đây, thưa đạo hữu, vượt qua hoàn toàn phi tưởng phi phi tưởng xứ, tôi chứng và trú diệt thọ tưởng. '",
  "sn28.9:1.4": "Nhưng, thưa đạo hữu, tôi không có ý nghĩ: ",
  "sn28.9:1.5": "'Tôi đang nhập diệt thọ tưởng định', hay 'Tôi đã nhập diệt thọ tưởng định', hay 'Tôi đã xuất khỏi diệt thọ tưởng định'.' '",
  "sn28.9:1.6": "Vì rằng, Tôn giả Sāriputta từ lâu đã nhổ tận gốc ngã chấp, ngã sở chấp và mạn tùy miên. ",
  "sn28.9:1.7": "Vì vậy, Tôn giả Sāriputta không có ý nghĩ: ",
  "sn28.9:1.8": "''Tôi đang nhập diệt thọ tưởng định', hay 'Tôi đã nhập diệt thọ tưởng định', hay 'Tôi đã xuất khỏi diệt thọ tưởng định'.' ",
  "sn28.9:1.9": "Thứ chín. ",
  "sn28.10:0.1": "Tương Ưng Bộ 28.10 ",
  "sn28.10:0.2": "1. Phẩm Xá-Lợi-Phất ",
  "sn28.10:0.3": "Kinh Sucimukhī ",
  "sn28.10:1.1": "Một thời, Tôn giả Sāriputta trú tại Rājagaha, rừng Trúc Lâm, vườn Kalandaka. ",
  "sn28.10:1.2": "Rồi Tôn giả Sāriputta vào buổi sáng, đắp y, mang bát đi vào Rājagaha để khất thực. ",
  "sn28.10:1.3": "Sau khi đi khất thực theo từng nhà ở Rājagaha, Ngài ngồi dùng bữa dựa vào một bức tường. ",
  "sn28.10:1.4": "Rồi nữ du sĩ Sucimukhī đi đến chỗ Tôn giả Sāriputta; đến nơi, bà nói với Tôn giả Sāriputta rằng: ",
  "sn28.10:2.1": "'Này Sa-môn, ông ăn với mặt cúi xuống phải không?' ",
  "sn28.10:2.2": "'Thưa chị, tôi không ăn với mặt cúi xuống.' ",
  "sn28.10:2.3": "'Vậy thì, này Sa-môn, ông ăn với mặt ngửa lên phải không?' ",
  "sn28.10:2.4": "'Thưa chị, tôi không ăn với mặt ngửa lên.' ",
  "sn28.10:2.5": "'Vậy thì, này Sa-môn, ông ăn với mặt hướng về các phương phải không?' ",
  "sn28.10:2.6": "'Thưa chị, tôi không ăn với mặt hướng về các phương.' ",
  "sn28.10:2.7": "'Vậy thì, này Sa-môn, ông ăn với mặt hướng về các góc phải không?' ",
  "sn28.10:2.8": "'Thưa chị, tôi không ăn với mặt hướng về các góc.' ",
  "sn28.10:3.1": "'Khi được hỏi 'Này Sa-môn, ông ăn với mặt cúi xuống phải không?', ông nói 'Thưa chị, tôi không ăn với mặt cúi xuống'. '",
  "sn28.10:3.2": "Khi được hỏi 'Vậy thì, này Sa-môn, ông ăn với mặt ngửa lên phải không?', ông nói 'Thưa chị, tôi không ăn với mặt ngửa lên'. ",
  "sn28.10:3.3": "Khi được hỏi 'Vậy thì, này Sa-môn, ông ăn với mặt hướng về các phương phải không?', ông nói 'Thưa chị, tôi không ăn với mặt hướng về các phương'. ",
  "sn28.10:3.4": "Khi được hỏi 'Vậy thì, này Sa-môn, ông ăn với mặt hướng về các góc phải không?', ông nói 'Thưa chị, tôi không ăn với mặt hướng về các góc'. ",
  "sn28.10:4.1": "Vậy thì, này Sa-môn, ông ăn như thế nào?' ",
  "sn28.10:4.2": "'Thưa chị, những Sa-môn, Bà-la-môn nào nuôi sống bằng tà mệnh qua thuật địa lý phong thủy, những vị ấy được gọi là 'ăn với mặt cúi xuống'. '",
  "sn28.10:4.3": "Những Sa-môn, Bà-la-môn nào nuôi sống bằng tà mệnh qua thuật chiêm tinh xem sao, những vị ấy được gọi là 'ăn với mặt ngửa lên'. ",
  "sn28.10:4.4": "Những Sa-môn, Bà-la-môn nào nuôi sống bằng tà mệnh qua việc làm sứ giả và đưa tin nhắn, những vị ấy được gọi là 'ăn với mặt hướng về các phương'. ",
  "sn28.10:4.5": "Những Sa-môn, Bà-la-môn nào nuôi sống bằng tà mệnh qua thuật xem tướng số, những vị ấy được gọi là 'ăn với mặt hướng về các góc'. ",
  "sn28.10:5.1": "Thưa chị, còn tôi, tôi không nuôi sống bằng tà mệnh qua thuật địa lý phong thủy, không nuôi sống bằng tà mệnh qua thuật chiêm tinh xem sao, không nuôi sống bằng tà mệnh qua việc làm sứ giả và đưa tin nhắn, không nuôi sống bằng tà mệnh qua thuật xem tướng số. ",
  "sn28.10:5.2": "Tôi tầm cầu vật thực bằng chánh pháp; ",
  "sn28.10:5.3": "tầm cầu vật thực bằng chánh pháp rồi tôi dùng bữa.' ",
  "sn28.10:6.1": "Rồi nữ du sĩ Sucimukhī, đi từ con đường này sang con đường khác, từ ngã tư này sang ngã tư khác ở Rājagaha, thông báo rằng: ",
  "sn28.10:6.2": "'Các Tỳ Kheo đệ tử Thích-Ca thọ thực đúng pháp; '",
  "sn28.10:6.3": "các Tỳ Kheo đệ tử Thích-Ca thọ thực vô tội. ",
  "sn28.10:6.4": "Hãy cúng dường vật thực cho các Tỳ Kheo đệ tử Thích-Ca.' ",
  "sn28.10:6.5": "Thứ mười. ",
  "sn28.10:6.6": "Phẩm Xá-Lợi-Phất, phẩm thứ nhất. ",
  "sn28.10:7.0": "Tóm lược phẩm này: ",
  "sn28.10:7.1": "Sinh từ viễn ly, không tầm, ",
  "sn28.10:7.2": "hỷ, xả và thứ tư; ",
  "sn28.10:7.3": "Không vô biên và thức vô biên, ",
  "sn28.10:7.4": "vô sở hữu và phi tưởng phi phi tưởng; ",
  "sn28.10:7.5": "Diệt là bài kinh thứ chín, ",
  "sn28.10:7.6": "thứ mười là Sucimukhī. ",
  "sn28.10:7.7": "Tương Ưng Xá-Lợi-Phất, kết thúc. "
}
window.BILARA["sn28_v1"]["vi"]["sn28_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
