window.BILARA = window.BILARA || {};
window.BILARA["sn33_v1"] = window.BILARA["sn33_v1"] || {};
window.BILARA["sn33_v1"]["vi"] = {
  "sn33.1:0.1": "Tương Ưng Bộ 33.1 ",
  "sn33.1:0.2": "1. Phẩm Vacchagotta ",
  "sn33.1:0.3": "Kinh Thiếu Hiểu Biết về Sắc ",
  "sn33.1:1.1": "Một thời, Đức Thế Tôn đang trú tại Sāvatthī, trong Kỳ Viên, vườn của Trưởng giả Anāthapiṇḍika. ",
  "sn33.1:1.2": "Rồi du sĩ ngoại đạo Vacchagotta đi đến chỗ Đức Thế Tôn đang ở; sau khi đến, chào hỏi Đức Thế Tôn. ",
  "sn33.1:1.3": "Sau khi trao đổi những lời thân ái và xã giao, ông ngồi xuống một bên. Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta thưa với Đức Thế Tôn rằng: ",
  "sn33.1:1.4": "'Thưa Tôn giả Gotama, nhân gì, duyên gì mà những tà kiến đa dạng này sinh khởi trong thế gian '",
  "sn33.1:1.5": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' hay 'Thế giới là hữu biên,' hay 'Thế giới là vô biên,' hay 'Sinh mệnh và thân xác là một,' hay 'Sinh mệnh và thân xác là khác,' hay 'Như Lai tồn tại sau khi chết,' hay 'Như Lai không tồn tại sau khi chết,' hay 'Như Lai vừa tồn tại vừa không tồn tại sau khi chết,' hay 'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết'?' '",
  "sn33.1:1.6": "'Do không biết về sắc, do không biết về sự sinh khởi của sắc, do không biết về sự diệt của sắc, do không biết về con đường đưa đến sự diệt của sắc; '",
  "sn33.1:1.7": "mà những tà kiến đa dạng này sinh khởi trong thế gian ",
  "sn33.1:1.8": "'Thế giới là thường hằng,' hay …v.v… ",
  "sn33.1:1.9": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết.' ",
  "sn33.1:1.10": "Đây là nhân, đây là duyên, Vaccha, mà những tà kiến đa dạng này sinh khởi trong thế gian ",
  "sn33.1:1.11": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.1:1.12": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết.'' '",
  "sn33.1:1.13": "Kinh thứ nhất. ",
  "sn33.2:0.1": "Tương Ưng Bộ 33.2 ",
  "sn33.2:0.2": "1. Phẩm Vacchagotta ",
  "sn33.2:0.3": "Kinh Thiếu Hiểu Biết về Thọ ",
  "sn33.2:1.1": "Tại Sāvatthī. ",
  "sn33.2:1.2": "Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta thưa với Đức Thế Tôn rằng: ",
  "sn33.2:1.3": "'Thưa Tôn giả Gotama, nhân gì, duyên gì mà những tà kiến đa dạng này sinh khởi trong thế gian '",
  "sn33.2:1.4": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.2:1.5": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết'?' '",
  "sn33.2:1.6": "'Do không biết về thọ, do không biết về sự sinh khởi của thọ, do không biết về sự diệt của thọ, do không biết về con đường đưa đến sự diệt của thọ; '",
  "sn33.2:1.7": "mà những tà kiến đa dạng này sinh khởi trong thế gian ",
  "sn33.2:1.8": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.2:1.9": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết.' ",
  "sn33.2:1.10": "Đây là nhân, đây là duyên, Vaccha, mà những tà kiến đa dạng này sinh khởi trong thế gian ",
  "sn33.2:1.11": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.2:1.12": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết.'' '",
  "sn33.2:1.13": "Kinh thứ hai. ",
  "sn33.3:0.1": "Tương Ưng Bộ 33.3 ",
  "sn33.3:0.2": "1. Phẩm Vacchagotta ",
  "sn33.3:0.3": "Kinh Thiếu Hiểu Biết về Tưởng ",
  "sn33.3:1.1": "Tại Sāvatthī. ",
  "sn33.3:1.2": "Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta thưa với Đức Thế Tôn rằng: ",
  "sn33.3:1.3": "'Thưa Tôn giả Gotama, nhân gì, duyên gì mà những tà kiến đa dạng này sinh khởi trong thế gian '",
  "sn33.3:1.4": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.3:1.5": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết'?' '",
  "sn33.3:1.6": "'Do không biết về tưởng, do không biết về sự sinh khởi của tưởng, do không biết về sự diệt của tưởng, do không biết về con đường đưa đến sự diệt của tưởng; '",
  "sn33.3:1.7": "mà những tà kiến đa dạng này sinh khởi trong thế gian ",
  "sn33.3:1.8": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.3:1.9": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết.' ",
  "sn33.3:1.10": "Đây là nhân, đây là duyên, Vaccha, mà những tà kiến đa dạng này sinh khởi trong thế gian ",
  "sn33.3:1.11": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.3:1.12": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết.'' '",
  "sn33.3:1.13": "Kinh thứ ba. ",
  "sn33.4:0.1": "Tương Ưng Bộ 33.4 ",
  "sn33.4:0.2": "1. Phẩm Vacchagotta ",
  "sn33.4:0.3": "Kinh Thiếu Hiểu Biết về Hành ",
  "sn33.4:1.1": "Tại Sāvatthī. ",
  "sn33.4:1.2": "Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta thưa với Đức Thế Tôn rằng: ",
  "sn33.4:1.3": "'Thưa Tôn giả Gotama, nhân gì, duyên gì mà những tà kiến đa dạng này sinh khởi trong thế gian '",
  "sn33.4:1.4": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.4:1.5": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết'?' '",
  "sn33.4:1.6": "'Do không biết về các hành, do không biết về sự sinh khởi của các hành, do không biết về sự diệt của các hành, do không biết về con đường đưa đến sự diệt của các hành; '",
  "sn33.4:1.7": "mà những tà kiến đa dạng này sinh khởi trong thế gian ",
  "sn33.4:1.8": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.4:1.9": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết.' ",
  "sn33.4:1.10": "Đây là nhân, đây là duyên, Vaccha, mà những tà kiến đa dạng này sinh khởi trong thế gian ",
  "sn33.4:1.11": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.4:1.12": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết.'' '",
  "sn33.4:1.13": "Kinh thứ tư. ",
  "sn33.5:0.1": "Tương Ưng Bộ 33.5 ",
  "sn33.5:0.2": "1. Phẩm Vacchagotta ",
  "sn33.5:0.3": "Kinh Thiếu Hiểu Biết về Thức ",
  "sn33.5:1.1": "Tại Sāvatthī. ",
  "sn33.5:1.2": "Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta thưa với Đức Thế Tôn rằng: ",
  "sn33.5:1.3": "'Thưa Tôn giả Gotama, nhân gì, duyên gì mà những tà kiến đa dạng này sinh khởi trong thế gian '",
  "sn33.5:1.4": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.5:1.5": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết'?' '",
  "sn33.5:1.6": "'Do không biết về thức, do không biết về sự sinh khởi của thức, do không biết về sự diệt của thức, do không biết về con đường đưa đến sự diệt của thức; '",
  "sn33.5:1.7": "mà những tà kiến đa dạng này sinh khởi trong thế gian ",
  "sn33.5:1.8": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.5:1.9": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết.' ",
  "sn33.5:1.10": "Đây là nhân, đây là duyên, Vaccha, mà những tà kiến đa dạng này sinh khởi trong thế gian ",
  "sn33.5:1.11": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.5:1.12": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết.'' '",
  "sn33.5:1.13": "Kinh thứ năm. ",
  "sn33.6-10:0.1": "Tương Ưng Bộ 33.6–10 ",
  "sn33.6-10:0.2": "1. Phẩm Vacchagotta ",
  "sn33.6-10:0.3": "Năm Kinh về Sự Không Nhận Thấy Sắc v.v. ",
  "sn33.6-10:1.1": "Tại Sāvatthī. ",
  "sn33.6-10:1.2": "Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta thưa với Đức Thế Tôn rằng: ",
  "sn33.6-10:1.3": "'Thưa Tôn giả Gotama, nhân gì, duyên gì mà những tà kiến đa dạng này sinh khởi trong thế gian '",
  "sn33.6-10:1.4": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.6-10:1.5": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết'?' '",
  "sn33.6-10:1.6": "'Do không nhận thấy sắc, Vaccha, …v.v… '",
  "sn33.6-10:1.7": "do không nhận thấy con đường đưa đến sự diệt của sắc …v.v… ",
  "sn33.6-10:1.8": "về thọ … ",
  "sn33.6-10:1.9": "về tưởng … ",
  "sn33.6-10:1.10": "do không nhận thấy các hành, Vaccha, …v.v… ",
  "sn33.6-10:1.11": "do không nhận thấy thức, Vaccha, …v.v… do không nhận thấy con đường đưa đến sự diệt của thức …v.v… ",
  "sn33.6-10:1.12": "Kinh thứ mười. ",
  "sn33.11:0.1": "Tương Ưng Bộ 33.11–15 ",
  "sn33.11:0.2": "1. Phẩm Vacchagotta ",
  "sn33.11:0.3": "Năm Kinh về Sự Không Thông Suốt về Sắc v.v. ",
  "sn33.11:1.1": "Tại Sāvatthī. ",
  "sn33.11:1.2": "'Do không thông suốt về sắc, Vaccha, …v.v… do không thông suốt về con đường đưa đến sự diệt của sắc …v.v… '",
  "sn33.12:1.1": "Tại Sāvatthī. ",
  "sn33.12:1.2": "'Do không thông suốt về thọ, Vaccha, …v.v… '",
  "sn33.13:1.1": "Tại Sāvatthī. ",
  "sn33.13:1.2": "'Do không thông suốt về tưởng, Vaccha, …v.v… '",
  "sn33.14:1.1": "Tại Sāvatthī. ",
  "sn33.14:1.2": "'Do không thông suốt về các hành, Vaccha, …v.v… '",
  "sn33.15:1.1": "Tại Sāvatthī. ",
  "sn33.15:1.2": "'Do không thông suốt về thức, Vaccha, …v.v… '",
  "sn33.15:1.3": "Kinh thứ mười lăm. ",
  "sn33.16:0.1": "Tương Ưng Bộ 33.16–20 ",
  "sn33.16:0.2": "1. Phẩm Vacchagotta ",
  "sn33.16:0.3": "Năm Kinh về Sự Không Giác Ngộ về Sắc v.v. ",
  "sn33.16:1.1": "Tại Sāvatthī. ",
  "sn33.16:1.2": "Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta thưa với Đức Thế Tôn rằng ",
  "sn33.16:1.3": "nhân gì, duyên gì, thưa Tôn giả Gotama, …v.v… ",
  "sn33.16:1.4": "do không giác ngộ về sắc, Vaccha, …v.v… do không giác ngộ về con đường đưa đến sự diệt của sắc …v.v… ",
  "sn33.17:1.1": "Tại Sāvatthī. ",
  "sn33.17:1.2": "'Do không giác ngộ về thọ, Vaccha …v.v… '",
  "sn33.18:1.1": "Tại Sāvatthī. ",
  "sn33.18:1.2": "'Do không giác ngộ về tưởng, Vaccha …v.v… '",
  "sn33.19:1.1": "Tại Sāvatthī. ",
  "sn33.19:1.2": "'Do không giác ngộ về các hành, Vaccha …v.v… '",
  "sn33.20:1.1": "Tại Sāvatthī. ",
  "sn33.20:1.2": "'Do không giác ngộ về thức, Vaccha, …v.v… '",
  "sn33.20:1.3": "do không giác ngộ về con đường đưa đến sự diệt của thức …v.v… ",
  "sn33.20:1.4": "Kinh thứ hai mươi. ",
  "sn33.21-25:0.1": "Tương Ưng Bộ 33.21–25 ",
  "sn33.21-25:0.2": "1. Phẩm Vacchagotta ",
  "sn33.21-25:0.3": "Năm Kinh về Sự Không Thấu Triệt về Sắc v.v. ",
  "sn33.21-25:1.1": "Tại Sāvatthī. Nhân gì, duyên gì, thưa Tôn giả Gotama, …v.v… ",
  "sn33.21-25:1.2": "'Do không thấu triệt về sắc, Vaccha, …v.v… do không thấu triệt về thức, Vaccha, …v.v… '",
  "sn33.21-25:1.3": "Kinh thứ hai mươi lăm. ",
  "sn33.26-30:0.1": "Tương Ưng Bộ 33.26–30 ",
  "sn33.26-30:0.2": "1. Phẩm Vacchagotta ",
  "sn33.26-30:0.3": "Năm Kinh về Sự Không Nhận Biết Đặc Tính của Sắc v.v. ",
  "sn33.26-30:1.1": "Tại Sāvatthī. ",
  "sn33.26-30:1.2": "'Do không nhận biết đặc tính của sắc, Vaccha, …v.v… do không nhận biết đặc tính của thức, Vaccha, …v.v… '",
  "sn33.26-30:1.3": "Kinh thứ ba mươi. ",
  "sn33.31-35:0.1": "Tương Ưng Bộ 33.31–35 ",
  "sn33.31-35:0.2": "1. Phẩm Vacchagotta ",
  "sn33.31-35:0.3": "Năm Kinh về Sự Không Quan Sát Tỉ Mỉ về Sắc v.v. ",
  "sn33.31-35:1.1": "Tại Sāvatthī. ",
  "sn33.31-35:1.2": "'Do không quan sát tỉ mỉ về sắc, Vaccha, …v.v… do không quan sát tỉ mỉ về thức, Vaccha, …v.v… '",
  "sn33.31-35:1.3": "Kinh thứ ba mươi lăm. ",
  "sn33.36-40:0.1": "Tương Ưng Bộ 33.36–40 ",
  "sn33.36-40:0.2": "1. Phẩm Vacchagotta ",
  "sn33.36-40:0.3": "Năm Kinh về Sự Không Nhìn Nhận Đúng Đắn về Sắc v.v. ",
  "sn33.36-40:1.1": "Tại Sāvatthī. ",
  "sn33.36-40:1.2": "'Do không nhìn nhận đúng đắn về sắc, Vaccha, …v.v… do không nhìn nhận đúng đắn về thức, Vaccha, …v.v… '",
  "sn33.36-40:1.3": "Kinh thứ bốn mươi. ",
  "sn33.41-45:0.1": "Tương Ưng Bộ 33.41–45 ",
  "sn33.41-45:0.2": "1. Phẩm Vacchagotta ",
  "sn33.41-45:0.3": "Năm Kinh về Sự Không Xem Xét về Sắc v.v. ",
  "sn33.41-45:1.1": "Tại Sāvatthī. ",
  "sn33.41-45:1.2": "'Do không xem xét về sắc, Vaccha, …v.v… do không xem xét về thức, Vaccha, …v.v… '",
  "sn33.41-45:1.3": "Kinh thứ bốn mươi lăm. ",
  "sn33.46-50:0.1": "Tương Ưng Bộ 33.46–50 ",
  "sn33.46-50:0.2": "1. Phẩm Vacchagotta ",
  "sn33.46-50:0.3": "Năm Kinh về Sự Không Quán Sát về Sắc v.v. ",
  "sn33.46-50:1.1": "Tại Sāvatthī. ",
  "sn33.46-50:1.2": "'Do không quán sát về sắc, Vaccha, …v.v… do không quán sát về thức, Vaccha, …v.v… '",
  "sn33.46-50:1.3": "Kinh thứ năm mươi. ",
  "sn33.51:0.1": "Tương Ưng Bộ 33.51–54 ",
  "sn33.51:0.2": "1. Phẩm Vacchagotta ",
  "sn33.51:0.3": "Bốn Kinh về Sự Không Trực Tiếp Chứng Nghiệm về Sắc v.v. ",
  "sn33.51:1.1": "Tại Sāvatthī. ",
  "sn33.51:1.2": "Rồi du sĩ ngoại đạo Vacchagotta đi đến chỗ Đức Thế Tôn đang ở; sau khi đến, chào hỏi Đức Thế Tôn. ",
  "sn33.51:1.3": "Sau khi trao đổi những lời thân ái và xã giao, ông ngồi xuống một bên. Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta thưa với Đức Thế Tôn rằng: ",
  "sn33.51:1.4": "'Thưa Tôn giả Gotama, nhân gì, duyên gì mà những tà kiến đa dạng này sinh khởi trong thế gian '",
  "sn33.51:1.5": "'Thế giới là thường hằng,' hay …v.v… ",
  "sn33.51:1.6": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết'?' '",
  "sn33.51:1.7": "'Do không trực tiếp chứng nghiệm về sắc, Vaccha, do không trực tiếp chứng nghiệm về sự sinh khởi của sắc, do không trực tiếp chứng nghiệm về sự diệt của sắc, do không trực tiếp chứng nghiệm về con đường đưa đến sự diệt của sắc …v.v… '",
  "sn33.52:1.1": "Tại Sāvatthī. ",
  "sn33.52:1.2": "'Do không trực tiếp chứng nghiệm về thọ, Vaccha, …v.v… do không trực tiếp chứng nghiệm về con đường đưa đến sự diệt của thọ …v.v… '",
  "sn33.53:1.1": "Tại Sāvatthī. ",
  "sn33.53:1.2": "'Do không trực tiếp chứng nghiệm về tưởng, Vaccha, …v.v… do không trực tiếp chứng nghiệm về con đường đưa đến sự diệt của tưởng …v.v… '",
  "sn33.54:1.1": "Tại Sāvatthī. ",
  "sn33.54:1.2": "'Do không trực tiếp chứng nghiệm về các hành, Vaccha, …v.v… do không trực tiếp chứng nghiệm về con đường đưa đến sự diệt của các hành …v.v… '",
  "sn33.54:1.3": "Kinh thứ năm mươi bốn. ",
  "sn33.55:0.1": "Tương Ưng Bộ 33.55 ",
  "sn33.55:0.2": "1. Phẩm Vacchagotta ",
  "sn33.55:0.3": "Kinh Không Trực Tiếp Chứng Nghiệm về Thức ",
  "sn33.55:1.1": "Tại Sāvatthī. ",
  "sn33.55:1.2": "'Do không trực tiếp chứng nghiệm về thức, do không trực tiếp chứng nghiệm về sự sinh khởi của thức, do không trực tiếp chứng nghiệm về sự diệt của thức, do không trực tiếp chứng nghiệm về con đường đưa đến sự diệt của thức; '",
  "sn33.55:1.3": "mà những tà kiến đa dạng này sinh khởi trong thế gian ",
  "sn33.55:1.4": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' …v.v… ",
  "sn33.55:1.5": "'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết.' ",
  "sn33.55:1.6": "Đây là nhân, đây là duyên, Vaccha, mà những tà kiến đa dạng này sinh khởi trong thế gian ",
  "sn33.55:1.7": "'Thế giới là thường hằng,' hay 'Thế giới là không thường hằng,' hay 'Thế giới là hữu biên,' hay 'Thế giới là vô biên,' hay 'Sinh mệnh và thân xác là một,' hay 'Sinh mệnh và thân xác là khác,' hay 'Như Lai tồn tại sau khi chết,' hay 'Như Lai không tồn tại sau khi chết,' hay 'Như Lai vừa tồn tại vừa không tồn tại sau khi chết,' hay 'Như Lai không phải tồn tại cũng không phải không tồn tại sau khi chết.'' '",
  "sn33.55:1.8": "Kinh thứ năm mươi lăm. ",
  "sn33.55:1.9": "Phẩm Vacchagotta, phẩm thứ nhất. ",
  "sn33.55:2.0": "Kệ tóm tắt: ",
  "sn33.55:2.1": "Thiếu hiểu biết, không nhận thấy, ",
  "sn33.55:2.2": "Không thông suốt, không giác ngộ; ",
  "sn33.55:2.3": "Không thấu triệt, không nhận biết đặc tính, ",
  "sn33.55:2.4": "Không quan sát tỉ mỉ, không nhìn nhận đúng đắn; ",
  "sn33.55:2.5": "Không xem xét, không quán sát, ",
  "sn33.55:2.6": "Không trực tiếp chứng nghiệm. ",
  "sn33.55:2.7": "Tương Ưng Vacchagotta đã hoàn tất. "
}
window.BILARA["sn33_v1"]["vi"]["sn33_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
