window.BILARA = window.BILARA || {};
window.BILARA["sn34_v1"] = window.BILARA["sn34_v1"] || {};
window.BILARA["sn34_v1"]["vi"] = {
  "sn34.1:0.1": "Tương Ưng Bộ 34.1 ",
  "sn34.1:0.2": "1. Phẩm Thiền ",
  "sn34.1:0.3": "Kinh Định Làm Căn Bản - Nhập Định ",
  "sn34.1:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.1:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.1:1.3": "Thế nào là bốn? ",
  "sn34.1:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong định, nhưng không thiện xảo trong việc nhập định. ",
  "sn34.1:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo trong việc nhập định, nhưng không thiện xảo trong định. ",
  "sn34.1:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong định, cũng không thiện xảo trong việc nhập định. ",
  "sn34.1:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong định, vừa thiện xảo trong việc nhập định. ",
  "sn34.1:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong định vừa thiện xảo trong việc nhập định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.1:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa, từ sữa có lạc, từ lạc có bơ tươi, từ bơ tươi có bơ, từ bơ có tinh chất bơ, và tinh chất bơ được xem là tối thượng trong số đó; ",
  "sn34.1:1.10": "cũng vậy, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong định vừa thiện xảo trong việc nhập định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy'. ",
  "sn34.1:1.11": "Thứ nhất. ",
  "sn34.2:0.1": "Tương Ưng Bộ 34.2 ",
  "sn34.2:0.2": "1. Phẩm Thiền ",
  "sn34.2:0.3": "Kinh Định Làm Căn Bản - An Trú ",
  "sn34.2:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.2:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.2:1.3": "Thế nào là bốn? ",
  "sn34.2:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong định, nhưng không thiện xảo trong việc an trú định. ",
  "sn34.2:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo trong việc an trú định, nhưng không thiện xảo trong định. ",
  "sn34.2:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong định, cũng không thiện xảo trong việc an trú định. ",
  "sn34.2:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong định, vừa thiện xảo trong việc an trú định. ",
  "sn34.2:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong định vừa thiện xảo trong việc an trú định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.2:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa, từ sữa có lạc, từ lạc có bơ tươi, từ bơ tươi có bơ, từ bơ có tinh chất bơ, và tinh chất bơ được xem là tối thượng trong số đó; ",
  "sn34.2:1.10": "cũng vậy, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong định vừa thiện xảo trong việc an trú định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy'. ",
  "sn34.2:1.11": "Thứ hai. ",
  "sn34.3:0.1": "Tương Ưng Bộ 34.3 ",
  "sn34.3:0.2": "1. Phẩm Thiền ",
  "sn34.3:0.3": "Kinh Định Làm Căn Bản - Xuất Định ",
  "sn34.3:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.3:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.3:1.3": "Thế nào là bốn? ",
  "sn34.3:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong định, nhưng không thiện xảo trong việc xuất định. ",
  "sn34.3:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo trong việc xuất định, nhưng không thiện xảo trong định. ",
  "sn34.3:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong định, cũng không thiện xảo trong việc xuất định. ",
  "sn34.3:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong định, vừa thiện xảo trong việc xuất định. ",
  "sn34.3:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong định vừa thiện xảo trong việc xuất định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.3:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa … ",
  "sn34.3:1.10": "tuyệt hảo nhất'. ",
  "sn34.3:1.11": "Thứ ba. ",
  "sn34.4:0.1": "Tương Ưng Bộ 34.4 ",
  "sn34.4:0.2": "1. Phẩm Thiền ",
  "sn34.4:0.3": "Kinh Định Làm Căn Bản - Thuần Thục ",
  "sn34.4:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.4:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.4:1.3": "Thế nào là bốn? ",
  "sn34.4:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong định, nhưng không thiện xảo trong việc thuần thục định. ",
  "sn34.4:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo trong việc thuần thục định, nhưng không thiện xảo trong định. ",
  "sn34.4:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong định, cũng không thiện xảo trong việc thuần thục định. ",
  "sn34.4:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong định, vừa thiện xảo trong việc thuần thục định. ",
  "sn34.4:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong định vừa thiện xảo trong việc thuần thục định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.4:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa … ",
  "sn34.4:1.10": "tuyệt hảo nhất'. ",
  "sn34.4:1.11": "Thứ tư. ",
  "sn34.5:0.1": "Tương Ưng Bộ 34.5 ",
  "sn34.5:0.2": "1. Phẩm Thiền ",
  "sn34.5:0.3": "Kinh Định Làm Căn Bản - Đối Tượng ",
  "sn34.5:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.5:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.5:1.3": "Thế nào là bốn? ",
  "sn34.5:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong định, nhưng không thiện xảo về đối tượng của định. ",
  "sn34.5:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo về đối tượng của định, nhưng không thiện xảo trong định. ",
  "sn34.5:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong định, cũng không thiện xảo về đối tượng của định. ",
  "sn34.5:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong định, vừa thiện xảo về đối tượng của định. ",
  "sn34.5:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong định vừa thiện xảo về đối tượng của định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.5:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa … ",
  "sn34.5:1.10": "tuyệt hảo nhất'. ",
  "sn34.5:1.11": "Thứ năm. ",
  "sn34.6:0.1": "Tương Ưng Bộ 34.6 ",
  "sn34.6:0.2": "1. Phẩm Thiền ",
  "sn34.6:0.3": "Kinh Định Làm Căn Bản - Hành Xứ ",
  "sn34.6:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.6:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.6:1.3": "Thế nào là bốn? ",
  "sn34.6:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong định, nhưng không thiện xảo về hành xứ của định. ",
  "sn34.6:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo về hành xứ của định, nhưng không thiện xảo trong định. ",
  "sn34.6:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong định, cũng không thiện xảo về hành xứ của định. ",
  "sn34.6:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong định, vừa thiện xảo về hành xứ của định. ",
  "sn34.6:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong định vừa thiện xảo về hành xứ của định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.6:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa … ",
  "sn34.6:1.10": "tuyệt hảo nhất'. ",
  "sn34.6:1.11": "Thứ sáu. ",
  "sn34.7:0.1": "Tương Ưng Bộ 34.7 ",
  "sn34.7:0.2": "1. Phẩm Thiền ",
  "sn34.7:0.3": "Kinh Định Làm Căn Bản - Hướng Tâm ",
  "sn34.7:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.7:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.7:1.3": "Thế nào là bốn? ",
  "sn34.7:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong định, nhưng không thiện xảo trong việc hướng tâm đến định. ",
  "sn34.7:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo trong việc hướng tâm đến định, nhưng không thiện xảo trong định. ",
  "sn34.7:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong định, cũng không thiện xảo trong việc hướng tâm đến định. ",
  "sn34.7:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong định, vừa thiện xảo trong việc hướng tâm đến định. ",
  "sn34.7:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong định vừa thiện xảo trong việc hướng tâm đến định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.7:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa … ",
  "sn34.7:1.10": "tuyệt hảo nhất'. ",
  "sn34.7:1.11": "Thứ bảy. ",
  "sn34.8:0.1": "Tương Ưng Bộ 34.8 ",
  "sn34.8:0.2": "1. Phẩm Thiền ",
  "sn34.8:0.3": "Kinh Định Làm Căn Bản - Cẩn Thận ",
  "sn34.8:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.8:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.8:1.3": "Thế nào là bốn? ",
  "sn34.8:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong định, nhưng không hành thiền với sự cẩn thận. ",
  "sn34.8:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả hành thiền với sự cẩn thận, nhưng không thiện xảo trong định. ",
  "sn34.8:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong định, cũng không hành thiền với sự cẩn thận. ",
  "sn34.8:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong định, vừa hành thiền với sự cẩn thận. ",
  "sn34.8:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong định vừa hành thiền với sự cẩn thận  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.8:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa … ",
  "sn34.8:1.10": "tuyệt hảo nhất'. ",
  "sn34.8:1.11": "Thứ tám. ",
  "sn34.9:0.1": "Tương Ưng Bộ 34.9 ",
  "sn34.9:0.2": "1. Phẩm Thiền ",
  "sn34.9:0.3": "Kinh Định Làm Căn Bản - Kiên Trì ",
  "sn34.9:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.9:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.9:1.3": "Thế nào là bốn? ",
  "sn34.9:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong định, nhưng không hành thiền với sự kiên trì. ",
  "sn34.9:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả hành thiền với sự kiên trì, nhưng không thiện xảo trong định. ",
  "sn34.9:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong định, cũng không hành thiền với sự kiên trì. ",
  "sn34.9:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong định, vừa hành thiền với sự kiên trì. ",
  "sn34.9:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong định vừa hành thiền với sự kiên trì  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.9:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa … ",
  "sn34.9:1.10": "tuyệt hảo nhất'. ",
  "sn34.9:1.11": "Thứ chín. ",
  "sn34.10:0.1": "Tương Ưng Bộ 34.10 ",
  "sn34.10:0.2": "1. Phẩm Thiền ",
  "sn34.10:0.3": "Kinh Định Làm Căn Bản - Thích Hợp ",
  "sn34.10:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.10:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.10:1.3": "Thế nào là bốn? ",
  "sn34.10:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong định, nhưng không làm những điều thích hợp cho định. ",
  "sn34.10:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả làm những điều thích hợp cho định, nhưng không thiện xảo trong định. ",
  "sn34.10:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong định, cũng không làm những điều thích hợp cho định. ",
  "sn34.10:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong định, vừa làm những điều thích hợp cho định. ",
  "sn34.10:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong định vừa làm những điều thích hợp cho định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.10:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa … ",
  "sn34.10:1.10": "tuyệt hảo nhất'. ",
  "sn34.10:1.11": "Thứ mười. ",
  "sn34.10:1.12": "(Phần Định Làm Căn Bản.) ",
  "sn34.11:0.1": "Tương Ưng Bộ 34.11 ",
  "sn34.11:0.2": "1. Phẩm Thiền ",
  "sn34.11:0.3": "Kinh Nhập Định Làm Căn Bản - An Trú ",
  "sn34.11:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.11:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.11:1.3": "Thế nào là bốn? ",
  "sn34.11:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong việc nhập định, nhưng không thiện xảo trong việc an trú định. ",
  "sn34.11:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo trong việc an trú định, nhưng không thiện xảo trong việc nhập định. ",
  "sn34.11:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong việc nhập định, cũng không thiện xảo trong việc an trú định. ",
  "sn34.11:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong việc nhập định, vừa thiện xảo trong việc an trú định. ",
  "sn34.11:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong việc nhập định vừa thiện xảo trong việc an trú định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.11:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa … ",
  "sn34.11:1.10": "tuyệt hảo nhất'. ",
  "sn34.11:1.11": "Thứ mười một. ",
  "sn34.12:0.1": "Tương Ưng Bộ 34.12 ",
  "sn34.12:0.2": "1. Phẩm Thiền ",
  "sn34.12:0.3": "Kinh Nhập Định Làm Căn Bản - Xuất Định ",
  "sn34.12:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.12:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.12:1.3": "Thế nào là bốn? ",
  "sn34.12:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong việc nhập định, nhưng không thiện xảo trong việc xuất định. ",
  "sn34.12:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo trong việc xuất định, nhưng không thiện xảo trong việc nhập định. ",
  "sn34.12:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong việc nhập định, cũng không thiện xảo trong việc xuất định. ",
  "sn34.12:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong việc nhập định, vừa thiện xảo trong việc xuất định. ",
  "sn34.12:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả … ",
  "sn34.12:1.9": "tuyệt hảo nhất'. ",
  "sn34.12:1.10": "Thứ mười hai. ",
  "sn34.13:0.1": "Tương Ưng Bộ 34.13 ",
  "sn34.13:0.2": "1. Phẩm Thiền ",
  "sn34.13:0.3": "Kinh Nhập Định Làm Căn Bản - Thuần Thục ",
  "sn34.13:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.13:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.13:1.3": "Thế nào là bốn? ",
  "sn34.13:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong việc nhập định, nhưng không thiện xảo trong việc thuần thục định. ",
  "sn34.13:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo trong việc thuần thục định, nhưng không thiện xảo trong việc nhập định. ",
  "sn34.13:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong việc nhập định, cũng không thiện xảo trong việc thuần thục định. ",
  "sn34.13:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong việc nhập định, vừa thiện xảo trong việc thuần thục định. ",
  "sn34.13:1.8": "Trong số đó … ",
  "sn34.13:1.9": "tuyệt hảo nhất'. ",
  "sn34.13:1.10": "Thứ mười ba. ",
  "sn34.14:0.1": "Tương Ưng Bộ 34.14 ",
  "sn34.14:0.2": "1. Phẩm Thiền ",
  "sn34.14:0.3": "Kinh Nhập Định Làm Căn Bản - Đối Tượng ",
  "sn34.14:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.14:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.14:1.3": "Thế nào là bốn? ",
  "sn34.14:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong việc nhập định, nhưng không thiện xảo về đối tượng của định. ",
  "sn34.14:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo về đối tượng của định, nhưng không thiện xảo trong việc nhập định. ",
  "sn34.14:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong việc nhập định, cũng không thiện xảo về đối tượng của định. ",
  "sn34.14:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong việc nhập định, vừa thiện xảo về đối tượng của định. ",
  "sn34.14:1.8": "Trong số đó … ",
  "sn34.14:1.9": "tuyệt hảo nhất'. ",
  "sn34.14:1.10": "Thứ mười bốn. ",
  "sn34.15:0.1": "Tương Ưng Bộ 34.15 ",
  "sn34.15:0.2": "1. Phẩm Thiền ",
  "sn34.15:0.3": "Kinh Nhập Định Làm Căn Bản - Hành Xứ ",
  "sn34.15:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.15:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.15:1.3": "Thế nào là bốn? ",
  "sn34.15:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong việc nhập định, nhưng không thiện xảo về hành xứ của định. ",
  "sn34.15:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo về hành xứ của định, nhưng không thiện xảo trong việc nhập định. ",
  "sn34.15:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong việc nhập định, cũng không thiện xảo về hành xứ của định. ",
  "sn34.15:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong việc nhập định, vừa thiện xảo về hành xứ của định. ",
  "sn34.15:1.8": "Trong số đó … ",
  "sn34.15:1.9": "tuyệt hảo nhất'. ",
  "sn34.15:1.10": "Thứ mười lăm. ",
  "sn34.16:0.1": "Tương Ưng Bộ 34.16 ",
  "sn34.16:0.2": "1. Phẩm Thiền ",
  "sn34.16:0.3": "Kinh Nhập Định Làm Căn Bản - Hướng Tâm ",
  "sn34.16:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.16:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.16:1.3": "Thế nào là bốn? ",
  "sn34.16:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong việc nhập định, nhưng không thiện xảo trong việc hướng tâm đến định. ",
  "sn34.16:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo trong việc hướng tâm đến định, nhưng không thiện xảo trong việc nhập định. ",
  "sn34.16:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong việc nhập định, cũng không thiện xảo trong việc hướng tâm đến định. ",
  "sn34.16:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong việc nhập định, vừa thiện xảo trong việc hướng tâm đến định. ",
  "sn34.16:1.8": "Trong số đó … ",
  "sn34.16:1.9": "tuyệt hảo nhất'. ",
  "sn34.16:1.10": "Thứ mười sáu. ",
  "sn34.17:0.1": "Tương Ưng Bộ 34.17 ",
  "sn34.17:0.2": "1. Phẩm Thiền ",
  "sn34.17:0.3": "Kinh Nhập Định Làm Căn Bản - Cẩn Thận ",
  "sn34.17:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.17:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.17:1.3": "Thế nào là bốn? ",
  "sn34.17:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong việc nhập định, nhưng không hành thiền với sự cẩn thận. ",
  "sn34.17:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả hành thiền với sự cẩn thận, nhưng không thiện xảo trong việc nhập định. ",
  "sn34.17:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong việc nhập định, cũng không hành thiền với sự cẩn thận. ",
  "sn34.17:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong việc nhập định, vừa hành thiền với sự cẩn thận. ",
  "sn34.17:1.8": "Trong số đó … ",
  "sn34.17:1.9": "tuyệt hảo nhất'. ",
  "sn34.17:1.10": "Thứ mười bảy. ",
  "sn34.18:0.1": "Tương Ưng Bộ 34.18 ",
  "sn34.18:0.2": "1. Phẩm Thiền ",
  "sn34.18:0.3": "Kinh Nhập Định Làm Căn Bản - Kiên Trì ",
  "sn34.18:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.18:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.18:1.3": "Thế nào là bốn? ",
  "sn34.18:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong việc nhập định, nhưng không hành thiền với sự kiên trì. ",
  "sn34.18:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả hành thiền với sự kiên trì, nhưng không thiện xảo trong việc nhập định. ",
  "sn34.18:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong việc nhập định, cũng không hành thiền với sự kiên trì. ",
  "sn34.18:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong việc nhập định, vừa hành thiền với sự kiên trì. ",
  "sn34.18:1.8": "Trong số đó … ",
  "sn34.18:1.9": "tuyệt hảo nhất'. ",
  "sn34.18:1.10": "Thứ mười tám. ",
  "sn34.19:0.1": "Tương Ưng Bộ 34.19 ",
  "sn34.19:0.2": "1. Phẩm Thiền ",
  "sn34.19:0.3": "Kinh Nhập Định Làm Căn Bản - Thích Hợp ",
  "sn34.19:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.19:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.19:1.3": "Thế nào là bốn? ",
  "sn34.19:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong việc nhập định, nhưng không làm những điều thích hợp cho định. ",
  "sn34.19:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả làm những điều thích hợp cho định, nhưng không thiện xảo trong việc nhập định. ",
  "sn34.19:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong việc nhập định, cũng không làm những điều thích hợp cho định. ",
  "sn34.19:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong việc nhập định, vừa làm những điều thích hợp cho định. ",
  "sn34.19:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong việc nhập định vừa làm những điều thích hợp cho định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.19:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa, từ sữa có lạc, từ lạc có bơ tươi, từ bơ tươi có bơ, từ bơ có tinh chất bơ, và tinh chất bơ được xem là tối thượng trong số đó; ",
  "sn34.19:1.10": "cũng vậy, này các Tỳ Kheo, vị thiền giả vừa thiện xảo trong việc nhập định vừa làm những điều thích hợp cho định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy'. ",
  "sn34.19:1.11": "Thứ mười chín. ",
  "sn34.19:1.12": "(Phần Nhập Định Làm Căn Bản.) ",
  "sn34.20-27:0.1": "Tương Ưng Bộ 34.20–27 ",
  "sn34.20-27:0.2": "1. Phẩm Thiền ",
  "sn34.20-27:0.3": "Tám Kinh Bắt Đầu Từ Kinh An Trú Làm Căn Bản - Xuất Định ",
  "sn34.20-27:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.20-27:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.20-27:1.3": "Thế nào là bốn? ",
  "sn34.20-27:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong việc an trú định, nhưng không thiện xảo trong việc xuất định. ",
  "sn34.20-27:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả thiện xảo trong việc xuất định, nhưng không thiện xảo trong việc an trú định. ",
  "sn34.20-27:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không thiện xảo trong việc an trú định, cũng không thiện xảo trong việc xuất định. ",
  "sn34.20-27:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa thiện xảo trong việc an trú định, vừa thiện xảo trong việc xuất định. ",
  "sn34.20-27:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả … ",
  "sn34.20-27:1.9": "tối thượng và tuyệt hảo nhất'. ",
  "sn34.20-27:1.10": "Thứ hai mươi. ",
  "sn34.20-27:1.11": "(Tương tự các phần căn bản trước, cho đến bài kinh thứ hai mươi bảy 'An Trú Làm Căn Bản - Thích Hợp', cần bổ sung tám bài kinh.) ",
  "sn34.20-27:1.12": "(Phần An Trú Làm Căn Bản.) ",
  "sn34.28-34:0.1": "Tương Ưng Bộ 34.28–34 ",
  "sn34.28-34:0.2": "1. Phẩm Thiền ",
  "sn34.28-34:0.3": "Bảy Kinh Bắt Đầu Từ Kinh Xuất Định Làm Căn Bản - Thuần Thục ",
  "sn34.28-34:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.28-34:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.28-34:1.3": "Thế nào là bốn? ",
  "sn34.28-34:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả thiện xảo trong việc xuất định, nhưng không thiện xảo trong việc thuần thục định … ",
  "sn34.28-34:1.5": "thiện xảo trong việc thuần thục định, nhưng không thiện xảo trong việc xuất định … ",
  "sn34.28-34:1.6": "không thiện xảo trong việc xuất định, cũng không thiện xảo trong việc thuần thục định … ",
  "sn34.28-34:1.7": "vừa thiện xảo trong việc xuất định vừa thiện xảo trong việc thuần thục định. ",
  "sn34.28-34:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả … ",
  "sn34.28-34:1.9": "tối thượng và tuyệt hảo nhất'. ",
  "sn34.28-34:1.10": "Thứ hai mươi tám. ",
  "sn34.28-34:1.11": "(Tương tự các phần căn bản trước, cho đến bài kinh thứ ba mươi tư 'Xuất Định Làm Căn Bản - Thích Hợp', cần bổ sung bảy bài kinh.) ",
  "sn34.28-34:1.12": "(Phần Xuất Định Làm Căn Bản.) ",
  "sn34.35-40:0.1": "Tương Ưng Bộ 34.35–40 ",
  "sn34.35-40:0.2": "1. Phẩm Thiền ",
  "sn34.35-40:0.3": "Sáu Kinh Bắt Đầu Từ Kinh Thuần Thục Làm Căn Bản - Đối Tượng ",
  "sn34.35-40:1.1": "Nhân duyên ở Sāvatthī … ",
  "sn34.35-40:1.2": "'thiện xảo trong việc thuần thục định, nhưng không thiện xảo về đối tượng của định … '",
  "sn34.35-40:1.3": "thiện xảo về đối tượng của định, nhưng không thiện xảo trong việc thuần thục định … ",
  "sn34.35-40:1.4": "không thiện xảo trong việc thuần thục định, cũng không thiện xảo về đối tượng của định … ",
  "sn34.35-40:1.5": "vừa thiện xảo trong việc thuần thục định, vừa thiện xảo về đối tượng của định. ",
  "sn34.35-40:1.6": "Trong số đó, này các Tỳ Kheo, vị thiền giả … ",
  "sn34.35-40:1.7": "tối thượng và tuyệt hảo nhất'. ",
  "sn34.35-40:1.8": "Thứ ba mươi lăm. ",
  "sn34.35-40:1.9": "(Tương tự các phần căn bản trước, cho đến bài kinh thứ bốn mươi 'Thuần Thục Làm Căn Bản - Thích Hợp', cần bổ sung sáu bài kinh.) ",
  "sn34.35-40:1.10": "(Phần Thuần Thục Làm Căn Bản.) ",
  "sn34.41-45:0.1": "Tương Ưng Bộ 34.41–45 ",
  "sn34.41-45:0.2": "1. Phẩm Thiền ",
  "sn34.41-45:0.3": "Năm Kinh Bắt Đầu Từ Kinh Đối Tượng Làm Căn Bản - Hành Xứ ",
  "sn34.41-45:1.1": "Nhân duyên ở Sāvatthī … ",
  "sn34.41-45:1.2": "'thiện xảo về đối tượng của định, nhưng không thiện xảo về hành xứ của định … '",
  "sn34.41-45:1.3": "thiện xảo về hành xứ của định, nhưng không thiện xảo về đối tượng của định … ",
  "sn34.41-45:1.4": "không thiện xảo về đối tượng của định, cũng không thiện xảo về hành xứ của định … ",
  "sn34.41-45:1.5": "vừa thiện xảo về đối tượng của định, vừa thiện xảo về hành xứ của định. ",
  "sn34.41-45:1.6": "Trong số đó, này các Tỳ Kheo, vị thiền giả … ",
  "sn34.41-45:1.7": "tối thượng và tuyệt hảo nhất'. ",
  "sn34.41-45:1.8": "Thứ bốn mươi mốt. ",
  "sn34.41-45:1.9": "(Tương tự các phần căn bản trước, cho đến bài kinh thứ bốn mươi lăm 'Đối Tượng Làm Căn Bản - Thích Hợp', cần bổ sung năm bài kinh.) ",
  "sn34.41-45:1.10": "(Phần Đối Tượng Làm Căn Bản.) ",
  "sn34.46:0.1": "Tương Ưng Bộ 34.46–49 ",
  "sn34.46:0.2": "1. Phẩm Thiền ",
  "sn34.46:0.3": "Bốn Kinh Bắt Đầu Từ Kinh Hành Xứ Làm Căn Bản - Hướng Tâm ",
  "sn34.46:1.1": "Nhân duyên ở Sāvatthī … ",
  "sn34.46:1.2": "'thiện xảo về hành xứ của định, nhưng không thiện xảo trong việc hướng tâm đến định … '",
  "sn34.46:1.3": "thiện xảo trong việc hướng tâm đến định, nhưng không thiện xảo về hành xứ của định … ",
  "sn34.46:1.4": "không thiện xảo về hành xứ của định, cũng không thiện xảo trong việc hướng tâm đến định … ",
  "sn34.46:1.5": "vừa thiện xảo về hành xứ của định, vừa thiện xảo trong việc hướng tâm đến định … ",
  "sn34.46:1.6": "này các Tỳ Kheo, ví như từ bò có sữa, từ sữa có lạc, từ lạc có bơ tươi, từ bơ tươi có bơ, từ bơ có tinh chất bơ, và tinh chất bơ được xem là tối thượng trong số đó; ",
  "sn34.46:1.7": "cũng vậy, này các Tỳ Kheo, vị thiền giả vừa thiện xảo về hành xứ của định vừa thiện xảo trong việc hướng tâm đến định  vị này trong số bốn hạng thiền giả ấy … ",
  "sn34.46:1.8": "tối thượng và tuyệt hảo nhất'. ",
  "sn34.46:1.9": "Thứ bốn mươi sáu. ",
  "sn34.47:1.1": "'Thiện xảo về hành xứ của định, nhưng không hành thiền với sự cẩn thận … '",
  "sn34.47:1.2": "Cần giải thích đầy đủ. ",
  "sn34.47:1.3": "Thứ bốn mươi bảy. ",
  "sn34.48:1.1": "'Thiện xảo về hành xứ của định, nhưng không hành thiền với sự kiên trì … '",
  "sn34.48:1.2": "Thứ bốn mươi tám. ",
  "sn34.49:1.1": "'Thiện xảo về hành xứ của định, nhưng không làm những điều thích hợp cho định … '",
  "sn34.49:1.2": "Thứ bốn mươi chín. ",
  "sn34.49:1.3": "(Phần Hành Xứ Làm Căn Bản.) ",
  "sn34.50:0.1": "Tương Ưng Bộ 34.50–52 ",
  "sn34.50:0.2": "1. Phẩm Thiền ",
  "sn34.50:0.3": "Ba Kinh Bắt Đầu Từ Kinh Hướng Tâm Làm Căn Bản - Cẩn Thận ",
  "sn34.50:1.1": "Nhân duyên ở Sāvatthī … ",
  "sn34.50:1.2": "'thiện xảo trong việc hướng tâm đến định, nhưng không hành thiền với sự cẩn thận … '",
  "sn34.50:1.3": "hành thiền với sự cẩn thận, nhưng không thiện xảo trong việc hướng tâm đến định … ",
  "sn34.50:1.4": "không thiện xảo trong việc hướng tâm đến định, cũng không hành thiền với sự cẩn thận … ",
  "sn34.50:1.5": "vừa thiện xảo trong việc hướng tâm đến định, vừa hành thiền với sự cẩn thận. ",
  "sn34.50:1.6": "Trong số đó, này các Tỳ Kheo, vị thiền giả … ",
  "sn34.50:1.7": "tối thượng và tuyệt hảo nhất'. ",
  "sn34.50:1.8": "Thứ năm mươi. ",
  "sn34.51:1.1": "'Thiện xảo trong việc hướng tâm đến định, nhưng không hành thiền với sự kiên trì … '",
  "sn34.51:1.2": "Thứ năm mươi mốt. ",
  "sn34.52:1.1": "'Thiện xảo trong việc hướng tâm đến định, nhưng không làm những điều thích hợp cho định … '",
  "sn34.52:1.2": "Thứ năm mươi hai. ",
  "sn34.52:1.3": "(Phần Hướng Tâm Làm Căn Bản.) ",
  "sn34.53:0.1": "Tương Ưng Bộ 34.53–54 ",
  "sn34.53:0.2": "1. Phẩm Thiền ",
  "sn34.53:0.3": "Cặp Kinh Cẩn Thận Làm Căn Bản - Kiên Trì và các kinh khác ",
  "sn34.53:1.1": "Nhân duyên ở Sāvatthī … ",
  "sn34.53:1.2": "'hành thiền với sự cẩn thận, nhưng không hành thiền với sự kiên trì … '",
  "sn34.53:1.3": "hành thiền với sự kiên trì, nhưng không hành thiền với sự cẩn thận … ",
  "sn34.53:1.4": "không hành thiền với sự cẩn thận, cũng không hành thiền với sự kiên trì … ",
  "sn34.53:1.5": "vừa hành thiền với sự cẩn thận, vừa hành thiền với sự kiên trì. ",
  "sn34.53:1.6": "Trong số đó, này các Tỳ Kheo, vị thiền giả … ",
  "sn34.53:1.7": "tối thượng và tuyệt hảo nhất'. ",
  "sn34.53:1.8": "Thứ năm mươi ba. ",
  "sn34.54:1.1": "'Hành thiền với sự cẩn thận, nhưng không làm những điều thích hợp cho định … '",
  "sn34.54:1.2": "Thứ năm mươi bốn. ",
  "sn34.55:0.1": "Tương Ưng Bộ 34.55 ",
  "sn34.55:0.2": "1. Phẩm Thiền ",
  "sn34.55:0.3": "Kinh Kiên Trì Làm Căn Bản - Thích Hợp ",
  "sn34.55:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn34.55:1.2": "'Này các Tỳ Kheo, có bốn hạng thiền giả này. '",
  "sn34.55:1.3": "Thế nào là bốn? ",
  "sn34.55:1.4": "Ở đây, này các Tỳ Kheo, có một thiền giả hành thiền với sự kiên trì, nhưng không làm những điều thích hợp cho định. ",
  "sn34.55:1.5": "Ở đây, này các Tỳ Kheo, lại có một thiền giả làm những điều thích hợp cho định, nhưng không hành thiền với sự kiên trì. ",
  "sn34.55:1.6": "Ở đây, này các Tỳ Kheo, lại có một thiền giả không hành thiền với sự kiên trì, cũng không làm những điều thích hợp cho định. ",
  "sn34.55:1.7": "Ở đây, này các Tỳ Kheo, lại có một thiền giả vừa hành thiền với sự kiên trì, vừa làm những điều thích hợp cho định. ",
  "sn34.55:1.8": "Trong số đó, này các Tỳ Kheo, vị thiền giả vừa hành thiền với sự kiên trì vừa làm những điều thích hợp cho định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy. ",
  "sn34.55:1.9": "Này các Tỳ Kheo, ví như từ bò có sữa, từ sữa có lạc, từ lạc có bơ tươi, từ bơ tươi có bơ, từ bơ có tinh chất bơ, và tinh chất bơ được xem là tối thượng trong số đó; ",
  "sn34.55:1.10": "cũng vậy, này các Tỳ Kheo, vị thiền giả vừa hành thiền với sự kiên trì vừa làm những điều thích hợp cho định  vị này là bậc đứng đầu, tốt nhất, tối thắng, tối thượng và tuyệt hảo nhất trong số bốn hạng thiền giả ấy'. ",
  "sn34.55:1.11": "Đức Thế Tôn đã thuyết như vậy. ",
  "sn34.55:1.12": "Các Tỳ Kheo ấy hoan hỷ tín thọ lời dạy của Đức Thế Tôn. ",
  "sn34.55:1.13": "Thứ năm mươi lăm. ",
  "sn34.55:1.14": "(Năm mươi lăm bài kinh này cần được giải thích đầy đủ như vậy.) ",
  "sn34.55:1.15": "Tương Ưng thứ ba trong Khandha Vagga. ",
  "sn34.55:2.0": "Tóm lược: ",
  "sn34.55:2.1": "Định, nhập định, an trú, ",
  "sn34.55:2.2": "Xuất định, thuần thục cùng đối tượng; ",
  "sn34.55:2.3": "Hành xứ, hướng tâm, cẩn thận, ",
  "sn34.55:2.4": "Kiên trì và điều thích hợp. ",
  "sn34.55:2.5": "Tương Ưng Thiền hoàn tất. ",
  "sn34.55:3.0": "Tóm lược: ",
  "sn34.55:3.1": "Tương Ưng Khandha, Rādha, ",
  "sn34.55:3.2": "Diṭṭhi, nhập lưu, sanh khởi; ",
  "sn34.55:3.3": "Phiền não, Sāriputta, ",
  "sn34.55:3.4": "Nāga, Supaṇṇa, Gandhabbā; ",
  "sn34.55:3.5": "Valāha, Vaccha, Thiền, ",
  "sn34.55:3.6": "trong Khandha Vagga là mười ba. ",
  "sn34.55:3.7": "Pāḷi Tương Ưng Khandha Vagga hoàn tất. "
}
window.BILARA["sn34_v1"]["vi"]["sn34_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
