window.BILARA = window.BILARA || {};
window.BILARA["sn36_v1"] = window.BILARA["sn36_v1"] || {};
window.BILARA["sn36_v1"]["vi"] = {
  "sn36.1:0.1": "Tương Ưng Bộ Kinh 36.1 ",
  "sn36.1:0.2": "1. Phẩm Có Kệ ",
  "sn36.1:0.3": "Kinh Định ",
  "sn36.1:1.1": "'Này các Tỳ Kheo, có ba loại cảm giác. '",
  "sn36.1:1.2": "Ba loại đó là gì? ",
  "sn36.1:1.3": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.1:1.4": "đây chính là ba loại cảm giác, này các Tỳ Kheo. ",
  "sn36.1:2.1": "Đệ tử của Đức Phật, ",
  "sn36.1:2.2": "có định, tỉnh giác, chánh niệm; ",
  "sn36.1:2.3": "Rõ biết về cảm giác, ",
  "sn36.1:2.4": "và nguồn gốc của cảm giác. ",
  "sn36.1:3.1": "Biết rõ nơi cảm giác diệt tận, ",
  "sn36.1:3.2": "và con đường dẫn đến đoạn diệt; ",
  "sn36.1:3.3": "Do diệt tận cảm giác, Tỳ Kheo, ",
  "sn36.1:3.4": "không còn đói khát, hoàn toàn Niết Bàn.' ",
  "sn36.1:3.5": "Thứ nhất. ",
  "sn36.2:0.1": "Tương Ưng Bộ Kinh 36.2 ",
  "sn36.2:0.2": "1. Phẩm Có Kệ ",
  "sn36.2:0.3": "Kinh Lạc ",
  "sn36.2:1.1": "'Này các Tỳ Kheo, có ba loại cảm giác. '",
  "sn36.2:1.2": "Ba loại đó là gì? ",
  "sn36.2:1.3": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.2:1.4": "đây chính là ba loại cảm giác, này các Tỳ Kheo. ",
  "sn36.2:2.1": "Dù vui hay khổ, ",
  "sn36.2:2.2": "hay bất khổ bất lạc cùng nhau; ",
  "sn36.2:2.3": "Bên trong cũng như bên ngoài, ",
  "sn36.2:2.4": "bất cứ cảm giác nào được cảm nhận. ",
  "sn36.2:3.1": "Hiểu rõ đây là khổ, ",
  "sn36.2:3.2": "là pháp hư dối, tan hoại; ",
  "sn36.2:3.3": "Nhìn cảm giác sanh rồi diệt, ",
  "sn36.2:3.4": "như vậy, ở đó ly tham.' ",
  "sn36.2:3.5": "Thứ hai. ",
  "sn36.3:0.1": "Tương Ưng Bộ Kinh 36.3 ",
  "sn36.3:0.2": "1. Phẩm Có Kệ ",
  "sn36.3:0.3": "Kinh Đoạn Trừ ",
  "sn36.3:1.1": "'Này các Tỳ Kheo, có ba loại cảm giác. '",
  "sn36.3:1.2": "Ba loại đó là gì? ",
  "sn36.3:1.3": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu. ",
  "sn36.3:1.4": "Này các Tỳ Kheo, đối với cảm giác dễ chịu, cần đoạn trừ tham tùy miên; đối với cảm giác khó chịu, cần đoạn trừ sân tùy miên; đối với cảm giác không khó chịu cũng không dễ chịu, cần đoạn trừ vô minh tùy miên. ",
  "sn36.3:1.5": "Này các Tỳ Kheo, khi một Tỳ Kheo đã đoạn trừ tham tùy miên đối với cảm giác dễ chịu, đã đoạn trừ sân tùy miên đối với cảm giác khó chịu, đã đoạn trừ vô minh tùy miên đối với cảm giác không khó chịu cũng không dễ chịu, thì vị ấy được gọi là 'Tỳ Kheo đã đoạn trừ mọi tùy miên, thấy đúng như thật, đã cắt đứt tham ái, tháo gỡ kiết sử, và nhờ thắng tri về mạn mà đã đoạn tận khổ đau'. ",
  "sn36.3:2.1": "Khi đang cảm cảm giác lạc, ",
  "sn36.3:2.2": "mà không rõ biết về cảm giác; ",
  "sn36.3:2.3": "Vị ấy có tham tùy miên, ",
  "sn36.3:2.4": "không thấy con đường thoát ra. ",
  "sn36.3:3.1": "Khi đang cảm cảm giác khổ, ",
  "sn36.3:3.2": "mà không rõ biết về cảm giác; ",
  "sn36.3:3.3": "Vị ấy có sân tùy miên, ",
  "sn36.3:3.4": "không thấy con đường thoát ra. ",
  "sn36.3:4.1": "Bất khổ bất lạc vi tế này, ",
  "sn36.3:4.2": "được bậc đại trí giảng dạy; ",
  "sn36.3:4.3": "Nếu còn ưa thích điều đó, ",
  "sn36.3:4.4": "sẽ không thoát khỏi khổ đau. ",
  "sn36.3:5.1": "Nhưng Tỳ Kheo tinh tấn, ",
  "sn36.3:5.2": "không bỏ rời tỉnh giác; ",
  "sn36.3:5.3": "Vị ấy rõ biết tất cả cảm giác, ",
  "sn36.3:5.4": "vị trí giả thấu hiểu trọn vẹn. ",
  "sn36.3:6.1": "Đã thông tuệ về cảm giác, ",
  "sn36.3:6.2": "trong đời này không còn lậu hoặc; ",
  "sn36.3:6.3": "Thân hoại, an trú trong Pháp, ",
  "sn36.3:6.4": "bậc minh trí không thể tính đếm được.' ",
  "sn36.3:6.5": "Thứ ba. ",
  "sn36.4:0.1": "Tương Ưng Bộ Kinh 36.4 ",
  "sn36.4:0.2": "1. Phẩm Có Kệ ",
  "sn36.4:0.3": "Kinh Vực Thẳm ",
  "sn36.4:1.1": "'Này các Tỳ Kheo, người phàm phu không được học hỏi nói rằng: '",
  "sn36.4:1.2": "'Có vực thẳm ở đại dương'. ",
  "sn36.4:1.3": "Này các Tỳ Kheo, người phàm phu không được học hỏi đó nói về điều không có thật, không tồn tại, rằng: ",
  "sn36.4:1.4": "'Có vực thẳm ở đại dương'. ",
  "sn36.4:1.5": "Này các Tỳ Kheo, 'vực thẳm' chính là danh từ dùng để chỉ những cảm giác khó chịu thuộc thân. ",
  "sn36.4:1.6": "Này các Tỳ Kheo, khi người phàm phu không được học hỏi bị xúc chạm bởi cảm giác khó chịu thuộc thân, vị ấy sầu khổ, than van, khóc lóc, đấm ngực, rơi vào mê loạn. ",
  "sn36.4:1.7": "Người đó được gọi là 'người phàm phu không được học hỏi không đứng vững được trong vực thẳm, không tìm được chỗ đứng'. ",
  "sn36.4:1.8": "Này các Tỳ Kheo, khi bậc Thánh đệ tử đã được học hỏi bị xúc chạm bởi cảm giác khó chịu thuộc thân, vị ấy không sầu khổ, không than van, không khóc lóc, không đấm ngực, không rơi vào mê loạn. ",
  "sn36.4:1.9": "Người đó được gọi là 'bậc Thánh đệ tử đã được học hỏi đứng vững được trong vực thẳm và tìm được chỗ đứng'. ",
  "sn36.4:2.1": "Người không chịu đựng được, ",
  "sn36.4:2.2": "Cảm giác khó chịu sanh khởi; ",
  "sn36.4:2.3": "Cảm giác khó chịu thuộc thân đoạt mạng, ",
  "sn36.4:2.4": "khi bị xúc chạm, run rẩy. ",
  "sn36.4:3.1": "Khóc than, la hét, ",
  "sn36.4:3.2": "yếu đuối, không có sức mạnh; ",
  "sn36.4:3.3": "Người đó không đứng vững trong vực thẳm, ",
  "sn36.4:3.4": "và không tìm được chỗ đứng. ",
  "sn36.4:4.1": "Người chịu đựng được, ",
  "sn36.4:4.2": "Cảm giác khó chịu sanh khởi; ",
  "sn36.4:4.3": "Cảm giác khó chịu thuộc thân đoạt mạng, ",
  "sn36.4:4.4": "khi bị xúc chạm, không run rẩy; ",
  "sn36.4:4.5": "Người đó đứng vững được trong vực thẳm, ",
  "sn36.4:4.6": "và tìm được chỗ đứng.' ",
  "sn36.4:4.7": "Thứ tư. ",
  "sn36.5:0.1": "Tương Ưng Bộ Kinh 36.5 ",
  "sn36.5:0.2": "1. Phẩm Có Kệ ",
  "sn36.5:0.3": "Kinh Phải Thấy ",
  "sn36.5:1.1": "'Này các Tỳ Kheo, có ba loại cảm giác. '",
  "sn36.5:1.2": "Ba loại đó là gì? ",
  "sn36.5:1.3": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu. ",
  "sn36.5:1.4": "Này các Tỳ Kheo, cảm giác dễ chịu phải được thấy là khổ; cảm giác khó chịu phải được thấy là mũi tên; cảm giác không khó chịu cũng không dễ chịu phải được thấy là vô thường. ",
  "sn36.5:1.5": "Này các Tỳ Kheo, khi một Tỳ Kheo thấy cảm giác dễ chịu là khổ, thấy cảm giác khó chịu là mũi tên, thấy cảm giác không khó chịu cũng không dễ chịu là vô thường",
  "sn36.5:1.6": "vị ấy được gọi là 'Tỳ Kheo thấy đúng như thật, đã cắt đứt tham ái, tháo gỡ kiết sử, và nhờ thắng tri về mạn mà đã đoạn tận khổ đau'. ",
  "sn36.5:2.1": "Người thấy lạc là khổ, ",
  "sn36.5:2.2": "thấy khổ như mũi tên; ",
  "sn36.5:2.3": "Bất khổ bất lạc vi tế, ",
  "sn36.5:2.4": "thấy đó là vô thường. ",
  "sn36.5:3.1": "Chính vị Tỳ Kheo thấy đúng, ",
  "sn36.5:3.2": "rõ biết trọn vẹn về cảm giác; ",
  "sn36.5:3.3": "Đã thông tuệ về cảm giác, ",
  "sn36.5:3.4": "trong đời này không còn lậu hoặc; ",
  "sn36.5:3.5": "Thân hoại, an trú trong Pháp, ",
  "sn36.5:3.6": "bậc minh trí không thể tính đếm được.' ",
  "sn36.5:3.7": "Thứ năm. ",
  "sn36.6:0.1": "Tương Ưng Bộ Kinh 36.6 ",
  "sn36.6:0.2": "1. Phẩm Có Kệ ",
  "sn36.6:0.3": "Kinh Mũi Tên ",
  "sn36.6:1.1": "'Này các Tỳ Kheo, người phàm phu không được học hỏi cảm cảm giác cảm giác dễ chịu, cảm cảm giác cảm giác khó chịu, cảm cảm giác cảm giác không khó chịu cũng không dễ chịu. '",
  "sn36.6:1.2": "Này các Tỳ Kheo, bậc Thánh đệ tử đã được học hỏi cũng cảm cảm giác cảm giác dễ chịu, cảm cảm giác cảm giác khó chịu, cảm cảm giác cảm giác không khó chịu cũng không dễ chịu. ",
  "sn36.6:1.3": "Này các Tỳ Kheo, vậy thì sự khác biệt, sự thù thắng, sự phân biệt giữa bậc Thánh đệ tử đã được học hỏi và người phàm phu không được học hỏi là gì?' ",
  "sn36.6:1.4": "Bạch Thế Tôn, Pháp lấy Thế Tôn làm gốc … ",
  "sn36.6:1.5": "Này các Tỳ Kheo, khi người phàm phu không được học hỏi bị xúc chạm bởi cảm giác khó chịu, vị ấy sầu khổ, than van, khóc lóc, đấm ngực, rơi vào mê loạn. ",
  "sn36.6:1.6": "Vị ấy cảm cảm giác hai loại cảm giác",
  "sn36.6:1.7": "Cảm giác thuộc thân và cảm giác thuộc tâm. ",
  "sn36.6:1.8": "Ví như, này các Tỳ Kheo, có người bị mũi tên bắn trúng. ",
  "sn36.6:1.9": "Rồi người đó lại bị mũi tên thứ hai bắn trúng tiếp theo. ",
  "sn36.6:1.10": "Như vậy, này các Tỳ Kheo, người đó cảm cảm giác với hai mũi tên. ",
  "sn36.6:1.11": "Cũng vậy, này các Tỳ Kheo, khi người phàm phu không được học hỏi bị xúc chạm bởi cảm giác khó chịu, vị ấy sầu khổ, than van, khóc lóc, đấm ngực, rơi vào mê loạn. ",
  "sn36.6:1.12": "Vị ấy cảm cảm giác hai loại cảm giác",
  "sn36.6:1.13": "Cảm giác thuộc thân và cảm giác thuộc tâm. ",
  "sn36.6:1.14": "Khi bị xúc chạm bởi cảm giác khó chịu đó, vị ấy phản ứng với sân hận. ",
  "sn36.6:1.15": "Khi vị ấy phản ứng với sân hận đối với cảm giác khó chịu, sân tùy miên tiềm ẩn đối với cảm giác khó chịu liền nằm ngủ theo. ",
  "sn36.6:1.16": "Khi bị xúc chạm bởi cảm giác khó chịu, vị ấy tìm đến dục lạc. ",
  "sn36.6:1.17": "Tại sao vậy? ",
  "sn36.6:1.18": "Này các Tỳ Kheo, người phàm phu không được học hỏi không biết đến sự thoát khỏi cảm giác khó chịu nào khác ngoài dục lạc, ",
  "sn36.6:1.19": "khi vị ấy tìm đến dục lạc, tham tùy miên tiềm ẩn đối với cảm giác dễ chịu liền nằm ngủ theo. ",
  "sn36.6:1.20": "Vị ấy không như thật rõ biết sự sanh khởi, sự diệt tận, vị ngọt, sự nguy hiểm và sự xuất ly của những cảm giác đó. ",
  "sn36.6:1.21": "Do vị ấy không như thật rõ biết sự sanh khởi, sự diệt tận, vị ngọt, sự nguy hiểm và sự xuất ly của những cảm giác đó, vô minh tùy miên tiềm ẩn đối với cảm giác không khó chịu cũng không dễ chịu liền nằm ngủ theo. ",
  "sn36.6:1.22": "Nếu vị ấy cảm cảm giác cảm giác dễ chịu, vị ấy cảm cảm giác nó trong sự trói buộc. ",
  "sn36.6:1.23": "Nếu vị ấy cảm cảm giác cảm giác khó chịu, vị ấy cảm cảm giác nó trong sự trói buộc. ",
  "sn36.6:1.24": "Nếu vị ấy cảm cảm giác cảm giác không khó chịu cũng không dễ chịu, vị ấy cảm cảm giác nó trong sự trói buộc. ",
  "sn36.6:1.25": "Này các Tỳ Kheo, người phàm phu không được học hỏi này được gọi là 'bị trói buộc bởi sanh, già, chết, sầu, bi, khổ, ưu, não; bị trói buộc bởi khổ đau', Ta nói vậy. ",
  "sn36.6:2.1": "Này các Tỳ Kheo, khi bậc Thánh đệ tử đã được học hỏi bị xúc chạm bởi cảm giác khó chịu, vị ấy không sầu khổ, không than van, không khóc lóc, không đấm ngực, không rơi vào mê loạn. ",
  "sn36.6:2.2": "Vị ấy chỉ cảm cảm giác một loại cảm giác",
  "sn36.6:2.3": "Cảm giác thuộc thân, không phải cảm giác thuộc tâm. ",
  "sn36.6:3.1": "Ví như, này các Tỳ Kheo, có người bị mũi tên bắn trúng. ",
  "sn36.6:3.2": "Rồi người đó không bị mũi tên thứ hai bắn trúng tiếp theo. ",
  "sn36.6:3.3": "Như vậy, này các Tỳ Kheo, người đó chỉ cảm cảm giác với một mũi tên. ",
  "sn36.6:3.4": "Cũng vậy, này các Tỳ Kheo, khi bậc Thánh đệ tử đã được học hỏi bị xúc chạm bởi cảm giác khó chịu, vị ấy không sầu khổ, không than van, không khóc lóc, không đấm ngực, không rơi vào mê loạn. ",
  "sn36.6:3.5": "Vị ấy chỉ cảm cảm giác một loại cảm giác",
  "sn36.6:3.6": "Cảm giác thuộc thân, không phải cảm giác thuộc tâm. ",
  "sn36.6:3.7": "Khi bị xúc chạm bởi cảm giác khó chịu đó, vị ấy không phản ứng với sân hận. ",
  "sn36.6:3.8": "Vì vị ấy không phản ứng với sân hận đối với cảm giác khó chịu, sân tùy miên tiềm ẩn đối với cảm giác khó chịu không nằm ngủ theo. ",
  "sn36.6:3.9": "Khi bị xúc chạm bởi cảm giác khó chịu, vị ấy không tìm đến dục lạc. ",
  "sn36.6:3.10": "Tại sao vậy? ",
  "sn36.6:3.11": "Này các Tỳ Kheo, bậc Thánh đệ tử đã được học hỏi biết đến sự thoát khỏi cảm giác khó chịu khác ngoài dục lạc. ",
  "sn36.6:3.12": "Vì vị ấy không tìm đến dục lạc, tham tùy miên tiềm ẩn đối với cảm giác dễ chịu không nằm ngủ theo. ",
  "sn36.6:3.13": "Vị ấy như thật rõ biết sự sanh khởi, sự diệt tận, vị ngọt, sự nguy hiểm và sự xuất ly của những cảm giác đó. ",
  "sn36.6:3.14": "Do vị ấy như thật rõ biết sự sanh khởi, sự diệt tận, vị ngọt, sự nguy hiểm và sự xuất ly của những cảm giác đó, vô minh tùy miên tiềm ẩn đối với cảm giác không khó chịu cũng không dễ chịu không nằm ngủ theo. ",
  "sn36.6:3.15": "Nếu vị ấy cảm cảm giác cảm giác dễ chịu, vị ấy cảm cảm giác nó trong sự không trói buộc. ",
  "sn36.6:3.16": "Nếu vị ấy cảm cảm giác cảm giác khó chịu, vị ấy cảm cảm giác nó trong sự không trói buộc. ",
  "sn36.6:3.17": "Nếu vị ấy cảm cảm giác cảm giác không khó chịu cũng không dễ chịu, vị ấy cảm cảm giác nó trong sự không trói buộc. ",
  "sn36.6:3.18": "Này các Tỳ Kheo, bậc Thánh đệ tử đã được học hỏi này được gọi là 'không bị trói buộc bởi sanh, già, chết, sầu, bi, khổ, ưu, não; không bị trói buộc bởi khổ đau', Ta nói vậy. ",
  "sn36.6:3.19": "Này các Tỳ Kheo, đây chính là sự khác biệt, sự thù thắng, sự phân biệt giữa bậc Thánh đệ tử đã được học hỏi và người phàm phu không được học hỏi. ",
  "sn36.6:4.1": "Bậc trí tuệ không bị cảm giác dẫn dắt, ",
  "sn36.6:4.2": "dù lạc hay khổ, dù đa văn; ",
  "sn36.6:4.3": "Giữa bậc trí và người phàm phu, ",
  "sn36.6:4.4": "sự khác biệt thật lớn lao. ",
  "sn36.6:5.1": "Người thấu rõ pháp, đa văn, ",
  "sn36.6:5.2": "thấy rõ thế gian này và thế gian kia; ",
  "sn36.6:5.3": "Pháp khả ái không làm tâm dao động, ",
  "sn36.6:5.4": "pháp không khả ái không gây sân hận. ",
  "sn36.6:6.1": "Đối với vị ấy, thuận và nghịch, ",
  "sn36.6:6.2": "đã tan biến, không còn nữa; ",
  "sn36.6:6.3": "Biết rõ con đường không cấu, không sầu, ",
  "sn36.6:6.4": "rõ biết đúng như thật, đã vượt qua hữu.' ",
  "sn36.6:6.5": "Thứ sáu. ",
  "sn36.7:0.1": "Tương Ưng Bộ Kinh 36.7 ",
  "sn36.7:0.2": "1. Phẩm Có Kệ ",
  "sn36.7:0.3": "Kinh Bệnh Thứ Nhất ",
  "sn36.7:1.1": "Một thời Thế Tôn trú ở Vesālī, tại Đại Lâm, trong ngôi nhà có nóc nhọn. ",
  "sn36.7:1.2": "Rồi vào buổi chiều, Thế Tôn từ thiền định đứng dậy, đi đến phòng dành cho người bệnh; đến nơi, Ngài ngồi xuống chỗ đã được sắp sẵn. ",
  "sn36.7:1.3": "Ngồi xuống, Thế Tôn gọi các Tỳ Kheo và nói: ",
  "sn36.7:2.1": "'Này các Tỳ Kheo, Tỳ Kheo có chánh niệm, tỉnh giác, hãy chờ đợi thời điểm. '",
  "sn36.7:2.2": "Đây là lời giáo huấn của chúng ta cho các ông. ",
  "sn36.7:3.1": "Này các Tỳ Kheo, thế nào là Tỳ Kheo có chánh niệm? ",
  "sn36.7:3.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo trú quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, đã chế ngự tham ưu ở đời; ",
  "sn36.7:3.3": "trú quán cảm giác trên các cảm giác … ",
  "sn36.7:3.4": "trú quán tâm trên tâm … ",
  "sn36.7:3.5": "trú quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, đã chế ngự tham ưu ở đời. ",
  "sn36.7:3.6": "Như vậy, này các Tỳ Kheo, Tỳ Kheo có chánh niệm. ",
  "sn36.7:4.1": "Này các Tỳ Kheo, thế nào là Tỳ Kheo có tỉnh giác? ",
  "sn36.7:4.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo khi đi tới, đi lui đều tỉnh giác; khi nhìn thẳng, nhìn qua lại đều tỉnh giác; khi co tay, duỗi tay đều tỉnh giác; khi mang y, bát, sanghāṭi đều tỉnh giác; khi ăn, uống, nhai, nếm đều tỉnh giác; khi đại tiện, tiểu tiện đều tỉnh giác; khi đi, đứng, ngồi, nằm, thức dậy, nói và im lặng đều tỉnh giác. ",
  "sn36.7:4.3": "Như vậy, này các Tỳ Kheo, Tỳ Kheo có tỉnh giác. ",
  "sn36.7:4.4": "Này các Tỳ Kheo, Tỳ Kheo có chánh niệm, tỉnh giác, hãy chờ đợi thời điểm. ",
  "sn36.7:4.5": "Đây là lời giáo huấn của chúng ta cho các ông. ",
  "sn36.7:5.1": "Này các Tỳ Kheo, nếu Tỳ Kheo đó đang trú như vậy, có chánh niệm, tỉnh giác, không phóng dật, nhiệt tâm, tinh cần, mà cảm giác dễ chịu sanh khởi, vị ấy rõ biết: ",
  "sn36.7:5.2": "'cảm giác dễ chịu này đã sanh khởi nơi ta. '",
  "sn36.7:5.3": "Nó có điều kiện, không phải không có điều kiện. ",
  "sn36.7:5.4": "Điều kiện gì? ",
  "sn36.7:5.5": "Chính thân này làm điều kiện. ",
  "sn36.7:5.6": "Thân này là vô thường, hữu vi, do duyên sanh. ",
  "sn36.7:5.7": "Cảm giác dễ chịu sanh khởi do duyên với thân vô thường, hữu vi, do duyên sanh, làm sao có thể thường hằng được?' ",
  "sn36.7:5.8": "Vị ấy trú quán vô thường trên thân và cảm giác dễ chịu, trú quán suy giảm, trú quán ly tham, trú quán diệt, trú quán buông bỏ. ",
  "sn36.7:5.9": "Khi vị ấy trú quán vô thường, suy giảm, ly tham, diệt, buông bỏ trên thân và cảm giác dễ chịu, tham tùy miên tiềm ẩn đối với thân và cảm giác dễ chịu được đoạn trừ. ",
  "sn36.7:6.1": "Này các Tỳ Kheo, nếu Tỳ Kheo đó đang trú như vậy, có chánh niệm, tỉnh giác, không phóng dật, nhiệt tâm, tinh cần, mà cảm giác khó chịu sanh khởi. ",
  "sn36.7:6.2": "Vị ấy rõ biết: ",
  "sn36.7:6.3": "'cảm giác khó chịu này đã sanh khởi nơi ta. '",
  "sn36.7:6.4": "Nó có điều kiện, không phải không có điều kiện. ",
  "sn36.7:6.5": "Điều kiện gì? ",
  "sn36.7:6.6": "Chính thân này làm điều kiện. ",
  "sn36.7:6.7": "Thân này là vô thường, hữu vi, do duyên sanh. ",
  "sn36.7:6.8": "Cảm giác khó chịu sanh khởi do duyên với thân vô thường, hữu vi, do duyên sanh, làm sao có thể thường hằng được?' ",
  "sn36.7:6.9": "Vị ấy trú quán vô thường trên thân và cảm giác khó chịu, trú quán suy giảm, trú quán ly tham, trú quán diệt, trú quán buông bỏ. ",
  "sn36.7:6.10": "Khi vị ấy trú quán vô thường … buông bỏ trên thân và cảm giác khó chịu, sân tùy miên tiềm ẩn đối với thân và cảm giác khó chịu được đoạn trừ. ",
  "sn36.7:7.1": "Này các Tỳ Kheo, nếu Tỳ Kheo đó đang trú như vậy, có chánh niệm, tỉnh giác, không phóng dật, nhiệt tâm, tinh cần, mà cảm giác không khó chịu cũng không dễ chịu sanh khởi, vị ấy rõ biết: ",
  "sn36.7:7.2": "'cảm giác không khó chịu cũng không dễ chịu này đã sanh khởi nơi ta. '",
  "sn36.7:7.3": "Nó có điều kiện, không phải không có điều kiện. ",
  "sn36.7:7.4": "Điều kiện gì? ",
  "sn36.7:7.5": "Chính thân này làm điều kiện. ",
  "sn36.7:7.6": "Thân này là vô thường, hữu vi, do duyên sanh. ",
  "sn36.7:7.7": "Cảm giác không khó chịu cũng không dễ chịu sanh khởi do duyên với thân vô thường, hữu vi, do duyên sanh, làm sao có thể thường hằng được?' ",
  "sn36.7:7.8": "Vị ấy trú quán vô thường trên thân và cảm giác không khó chịu cũng không dễ chịu, trú quán suy giảm, trú quán ly tham, trú quán diệt, trú quán buông bỏ. ",
  "sn36.7:7.9": "Khi vị ấy trú quán vô thường … buông bỏ trên thân và cảm giác không khó chịu cũng không dễ chịu, vô minh tùy miên tiềm ẩn đối với thân và cảm giác không khó chịu cũng không dễ chịu được đoạn trừ. ",
  "sn36.7:8.1": "Nếu vị ấy cảm cảm giác cảm giác dễ chịu, vị ấy rõ biết nó là vô thường, biết là không chấp thủ, biết là không đắm nhiễm; ",
  "sn36.7:8.2": "nếu cảm cảm giác cảm giác khó chịu … ",
  "sn36.7:8.3": "nếu cảm cảm giác cảm giác không khó chịu cũng không dễ chịu, vị ấy rõ biết nó là vô thường, biết là không chấp thủ, biết là không đắm nhiễm. ",
  "sn36.7:8.4": "Nếu cảm cảm giác cảm giác dễ chịu, vị ấy cảm cảm giác nó trong sự không trói buộc; ",
  "sn36.7:8.5": "nếu cảm cảm giác cảm giác khó chịu, vị ấy cảm cảm giác nó trong sự không trói buộc; ",
  "sn36.7:8.6": "nếu cảm cảm giác cảm giác không khó chịu cũng không dễ chịu, vị ấy cảm cảm giác nó trong sự không trói buộc. ",
  "sn36.7:8.7": "Khi cảm cảm giác cảm giác đến tận cùng của thân, vị ấy rõ biết 'Ta đang cảm cảm giác cảm giác đến tận cùng của thân'; khi cảm cảm giác cảm giác đến tận cùng của mạng sống, vị ấy rõ biết 'Ta đang cảm cảm giác cảm giác đến tận cùng của mạng sống'. ",
  "sn36.7:8.8": "Vị ấy rõ biết: 'Khi thân hoại diệt, sau khi mạng sống chấm dứt, ngay tại đây tất cả các cảm giác đều không còn được ưa thích và sẽ trở nên mát lạnh'. ",
  "sn36.7:9.1": "Ví như, này các Tỳ Kheo, một ngọn đèn dầu cháy nhờ có dầu và bấc, ",
  "sn36.7:9.2": "khi hết dầu và bấc, không còn nhiên liệu, ngọn lửa tắt; ",
  "sn36.7:9.3": "cũng vậy, này các Tỳ Kheo, Tỳ Kheo khi cảm cảm giác cảm giác đến tận cùng của thân, rõ biết 'Ta đang cảm cảm giác cảm giác đến tận cùng của thân'. Khi cảm cảm giác cảm giác đến tận cùng của mạng sống, rõ biết 'Ta đang cảm cảm giác cảm giác đến tận cùng của mạng sống'. ",
  "sn36.7:9.4": "Vị ấy rõ biết: 'Khi thân hoại diệt, sau khi mạng sống chấm dứt, ngay tại đây tất cả các cảm giác đều không còn được ưa thích và sẽ trở nên mát lạnh'.' ",
  "sn36.7:9.5": "Thứ bảy. ",
  "sn36.8:0.1": "Tương Ưng Bộ Kinh 36.8 ",
  "sn36.8:0.2": "1. Phẩm Có Kệ ",
  "sn36.8:0.3": "Kinh Bệnh Thứ Hai ",
  "sn36.8:1.1": "Một thời Thế Tôn trú ở Vesālī, tại Đại Lâm, trong ngôi nhà có nóc nhọn. ",
  "sn36.8:1.2": "Rồi vào buổi chiều, Thế Tôn từ thiền định đứng dậy, đi đến phòng dành cho người bệnh; đến nơi, Ngài ngồi xuống chỗ đã được sắp sẵn. ",
  "sn36.8:1.3": "Ngồi xuống, Thế Tôn gọi các Tỳ Kheo và nói: ",
  "sn36.8:2.1": "'Này các Tỳ Kheo, Tỳ Kheo có chánh niệm, tỉnh giác, hãy chờ đợi thời điểm. '",
  "sn36.8:2.2": "Đây là lời giáo huấn của chúng ta cho các ông. ",
  "sn36.8:3.1": "Này các Tỳ Kheo, thế nào là Tỳ Kheo có chánh niệm? ",
  "sn36.8:3.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo trú quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, đã chế ngự tham ưu ở đời; ",
  "sn36.8:3.3": "trú quán cảm giác trên các cảm giác … ",
  "sn36.8:3.4": "trú quán tâm trên tâm … ",
  "sn36.8:3.5": "trú quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, đã chế ngự tham ưu ở đời. ",
  "sn36.8:3.6": "Như vậy, này các Tỳ Kheo, Tỳ Kheo có chánh niệm. ",
  "sn36.8:4.1": "Này các Tỳ Kheo, thế nào là Tỳ Kheo có tỉnh giác? ",
  "sn36.8:4.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo khi đi tới, đi lui đều tỉnh giác … khi nói và im lặng đều tỉnh giác. ",
  "sn36.8:4.3": "Như vậy, này các Tỳ Kheo, Tỳ Kheo có tỉnh giác. ",
  "sn36.8:4.4": "Này các Tỳ Kheo, Tỳ Kheo có chánh niệm, tỉnh giác, hãy chờ đợi thời điểm. ",
  "sn36.8:4.5": "Đây là lời giáo huấn của chúng ta cho các ông. ",
  "sn36.8:5.1": "Này các Tỳ Kheo, nếu Tỳ Kheo đó đang trú như vậy, có chánh niệm, tỉnh giác, không phóng dật, nhiệt tâm, tinh cần, mà cảm giác dễ chịu sanh khởi. ",
  "sn36.8:5.2": "Vị ấy rõ biết: ",
  "sn36.8:5.3": "'cảm giác dễ chịu này đã sanh khởi nơi ta; '",
  "sn36.8:5.4": "nó có điều kiện, không phải không có điều kiện. ",
  "sn36.8:5.5": "Điều kiện gì? ",
  "sn36.8:5.6": "Chính xúc này làm điều kiện. ",
  "sn36.8:5.7": "Xúc này là vô thường, hữu vi, do duyên sanh. ",
  "sn36.8:5.8": "Cảm giác dễ chịu sanh khởi do duyên với xúc vô thường, hữu vi, do duyên sanh, làm sao có thể thường hằng được?' ",
  "sn36.8:5.9": "Vị ấy trú quán vô thường trên xúc và cảm giác dễ chịu, trú quán suy giảm, trú quán ly tham, trú quán diệt, trú quán buông bỏ. ",
  "sn36.8:5.10": "Khi vị ấy trú quán vô thường, suy giảm, ly tham, diệt, buông bỏ trên xúc và cảm giác dễ chịu, tham tùy miên tiềm ẩn đối với xúc và cảm giác dễ chịu được đoạn trừ. ",
  "sn36.8:6.1": "Này các Tỳ Kheo, nếu Tỳ Kheo đó đang trú như vậy … ",
  "sn36.8:6.2": "mà cảm giác khó chịu sanh khởi … ",
  "sn36.8:6.3": "mà cảm giác không khó chịu cũng không dễ chịu sanh khởi. ",
  "sn36.8:6.4": "Vị ấy rõ biết: ",
  "sn36.8:6.5": "'cảm giác không khó chịu cũng không dễ chịu này đã sanh khởi nơi ta; '",
  "sn36.8:6.6": "nó có điều kiện, không phải không có điều kiện. ",
  "sn36.8:6.7": "Điều kiện gì? ",
  "sn36.8:6.8": "Chính xúc này làm điều kiện. ",
  "sn36.8:6.9": "(Nên giải thích đầy đủ như kinh trước.) ",
  "sn36.8:6.10": "Khi thân hoại diệt, sau khi mạng sống chấm dứt, ngay tại đây tất cả các cảm giác đều không còn được ưa thích và sẽ trở nên mát lạnh'. ",
  "sn36.8:7.1": "Ví như, này các Tỳ Kheo, một ngọn đèn dầu cháy nhờ có dầu và bấc, ",
  "sn36.8:7.2": "khi hết dầu và bấc, không còn nhiên liệu, ngọn lửa tắt; ",
  "sn36.8:7.3": "cũng vậy, này các Tỳ Kheo, Tỳ Kheo khi cảm cảm giác cảm giác đến tận cùng của thân, rõ biết 'Ta đang cảm cảm giác cảm giác đến tận cùng của thân'. Khi cảm cảm giác cảm giác đến tận cùng của mạng sống, rõ biết 'Ta đang cảm cảm giác cảm giác đến tận cùng của mạng sống'. ",
  "sn36.8:7.4": "Vị ấy rõ biết: 'Khi thân hoại diệt, sau khi mạng sống chấm dứt, ngay tại đây tất cả các cảm giác đều không còn được ưa thích và sẽ trở nên mát lạnh'.' ",
  "sn36.8:7.5": "Thứ tám. ",
  "sn36.9:0.1": "Tương Ưng Bộ Kinh 36.9 ",
  "sn36.9:0.2": "1. Phẩm Có Kệ ",
  "sn36.9:0.3": "Kinh Vô Thường ",
  "sn36.9:1.1": "'Này các Tỳ Kheo, ba loại cảm giác này là vô thường, hữu vi, do duyên sanh, có bản chất hoại diệt, có bản chất suy giảm, có bản chất ly tham, có bản chất đoạn diệt. '",
  "sn36.9:1.2": "Ba loại đó là gì? ",
  "sn36.9:1.3": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.9:1.4": "đây chính là ba loại cảm giác vô thường, hữu vi, do duyên sanh, có bản chất hoại diệt, có bản chất suy giảm, có bản chất ly tham, có bản chất đoạn diệt, này các Tỳ Kheo.' ",
  "sn36.9:1.5": "Thứ chín. ",
  "sn36.10:0.1": "Tương Ưng Bộ Kinh 36.10 ",
  "sn36.10:0.2": "1. Phẩm Có Kệ ",
  "sn36.10:0.3": "Kinh Gốc Rễ Là Xúc ",
  "sn36.10:1.1": "'Này các Tỳ Kheo, ba loại cảm giác này sanh ra từ xúc, lấy xúc làm gốc rễ, lấy xúc làm nhân, lấy xúc làm duyên. '",
  "sn36.10:1.2": "Ba loại đó là gì? ",
  "sn36.10:1.3": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu. ",
  "sn36.10:1.4": "Này các Tỳ Kheo, do duyên với xúc mang lại lạc, cảm giác dễ chịu sanh khởi. ",
  "sn36.10:1.5": "Khi xúc mang lại lạc đó diệt, cảm giác tương ứngtức cảm giác dễ chịu đã sanh do duyên với xúc mang lại lạc đócũng diệt, lắng xuống. ",
  "sn36.10:1.6": "Này các Tỳ Kheo, do duyên với xúc mang lại khổ, cảm giác khó chịu sanh khởi. ",
  "sn36.10:1.7": "Khi xúc mang lại khổ đó diệt, cảm giác tương ứngtức cảm giác khó chịu đã sanh do duyên với xúc mang lại khổ đócũng diệt, lắng xuống. ",
  "sn36.10:1.8": "Này các Tỳ Kheo, do duyên với xúc mang lại bất khổ bất lạc, cảm giác không khó chịu cũng không dễ chịu sanh khởi. ",
  "sn36.10:1.9": "Khi xúc mang lại bất khổ bất lạc đó diệt, cảm giác tương ứngtức cảm giác không khó chịu cũng không dễ chịu đã sanh do duyên với xúc mang lại bất khổ bất lạc đócũng diệt, lắng xuống. ",
  "sn36.10:1.10": "Ví như, này các Tỳ Kheo, do hai cây củi cọ xát và tiếp xúc nhau mà hơi ấm sanh ra và lửa xuất hiện. Khi hai cây củi đó tách rời nhau, hơi ấm tương ứng cũng diệt, lắng xuống. ",
  "sn36.10:1.11": "Cũng vậy, này các Tỳ Kheo, ba loại cảm giác này sanh ra từ xúc, lấy xúc làm gốc rễ, lấy xúc làm nhân, lấy xúc làm duyên. ",
  "sn36.10:1.12": "Do duyên với xúc tương ứng, cảm giác tương ứng sanh khởi. ",
  "sn36.10:1.13": "Do xúc tương ứng diệt, cảm giác tương ứng cũng diệt.' ",
  "sn36.10:1.14": "Thứ mười. ",
  "sn36.10:1.15": "Phẩm Có Kệ thuộc Tương Ưng cảm giác, thứ nhất. ",
  "sn36.10:2.0": "Tóm tắt phẩm này: ",
  "sn36.10:2.1": "Định, lạc, đoạn trừ, ",
  "sn36.10:2.2": "vực thẳm, phải thấy; ",
  "sn36.10:2.3": "Mũi tên, bệnh tật, ",
  "sn36.10:2.4": "vô thường, gốc rễ là xúc. ",
  "sn36.11:0.1": "Tương Ưng Bộ Kinh 36.11 ",
  "sn36.11:0.2": "2. Phẩm Một Mình Tĩnh Tọa ",
  "sn36.11:0.3": "Kinh Một Mình Tĩnh Tọa ",
  "sn36.11:1.1": "Rồi một Tỳ Kheo đến gặp Thế Tôn; đến nơi, vị ấy đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, vị Tỳ Kheo đó bạch Thế Tôn: ",
  "sn36.11:1.2": "'Bạch Thế Tôn, khi con đang ở một mình tĩnh tọa, tư duy này đã khởi lên trong tâm con '",
  "sn36.11:1.3": "Thế Tôn đã dạy có ba loại cảm giác. ",
  "sn36.11:1.4": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.11:1.5": "đây là ba loại cảm giác mà Thế Tôn đã dạy. ",
  "sn36.11:1.6": "Nhưng Thế Tôn cũng đã nói: ",
  "sn36.11:1.7": "'Bất cứ điều gì được cảm cảm giác đều là khổ'. ",
  "sn36.11:1.8": "Thế Tôn đã nói điều gì với lời nói đó: ",
  "sn36.11:1.9": "'Bất cứ điều gì được cảm cảm giác đều là khổ'?' '",
  "sn36.11:2.1": "'Lành thay, lành thay, này Tỳ Kheo. '",
  "sn36.11:2.2": "Này Tỳ Kheo, Ta đã dạy có ba loại cảm giác. ",
  "sn36.11:2.3": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.11:2.4": "đây là ba loại cảm giác mà Ta đã dạy. ",
  "sn36.11:2.5": "Nhưng, này Tỳ Kheo, Ta cũng đã nói: ",
  "sn36.11:2.6": "'Bất cứ điều gì được cảm cảm giác đều là khổ'. ",
  "sn36.11:2.7": "Này Tỳ Kheo, điều đó Ta đã nói để chỉ ra tính vô thường của các hành: ",
  "sn36.11:2.8": "'Bất cứ điều gì được cảm cảm giác đều là khổ'. ",
  "sn36.11:2.9": "Này Tỳ Kheo, điều đó Ta đã nói để chỉ ra bản chất hoại diệt của các hành … ",
  "sn36.11:2.10": "bản chất suy giảm … ",
  "sn36.11:2.11": "bản chất ly tham … ",
  "sn36.11:2.12": "bản chất đoạn diệt … ",
  "sn36.11:2.13": "bản chất biến đổi của các hành: ",
  "sn36.11:2.14": "'Bất cứ điều gì được cảm cảm giác đều là khổ'. ",
  "sn36.11:2.15": "Này Tỳ Kheo, Ta cũng đã nói về sự diệt dần dần của các hành. ",
  "sn36.11:2.16": "Với người đạt sơ thiền, lời nói được diệt. ",
  "sn36.11:2.17": "Với người đạt nhị thiền, tầm và tứ được diệt. ",
  "sn36.11:2.18": "Với người đạt tam thiền, hỷ được diệt. ",
  "sn36.11:2.19": "Với người đạt tứ thiền, hơi thở vào và ra được diệt. ",
  "sn36.11:2.20": "Với người đạt không vô biên xứ, tưởng về sắc được diệt. ",
  "sn36.11:2.21": "Với người đạt thức vô biên xứ, tưởng về không vô biên xứ được diệt. ",
  "sn36.11:2.22": "Với người đạt vô sở hữu xứ, tưởng về thức vô biên xứ được diệt. ",
  "sn36.11:2.23": "Với người đạt phi tưởng phi phi tưởng xứ, tưởng về vô sở hữu xứ được diệt. ",
  "sn36.11:2.24": "Với người đạt diệt cảm giác tưởng, tưởng và cảm giác được diệt. ",
  "sn36.11:2.25": "Đối với Tỳ Kheo đã đoạn tận lậu hoặc, tham được diệt, sân được diệt, si được diệt. ",
  "sn36.11:2.26": "Này Tỳ Kheo, Ta cũng đã nói về sự lắng xuống dần dần của các hành. ",
  "sn36.11:2.27": "Với người đạt sơ thiền, lời nói được lắng xuống. ",
  "sn36.11:2.28": "Với người đạt nhị thiền, tầm và tứ được lắng xuống … ",
  "sn36.11:2.29": "Với người đạt diệt cảm giác tưởng, tưởng và cảm giác được lắng xuống. ",
  "sn36.11:2.30": "Đối với Tỳ Kheo đã đoạn tận lậu hoặc, tham được lắng xuống, sân được lắng xuống, si được lắng xuống. ",
  "sn36.11:2.31": "Này Tỳ Kheo, có sáu loại khinh an. ",
  "sn36.11:2.32": "Với người đạt sơ thiền, lời nói được khinh an. ",
  "sn36.11:2.33": "Với người đạt nhị thiền, tầm và tứ được khinh an. ",
  "sn36.11:2.34": "Với người đạt tam thiền, hỷ được khinh an. ",
  "sn36.11:2.35": "Với người đạt tứ thiền, hơi thở vào và ra được khinh an. ",
  "sn36.11:2.36": "Với người đạt diệt cảm giác tưởng, tưởng và cảm giác được khinh an. ",
  "sn36.11:2.37": "Đối với Tỳ Kheo đã đoạn tận lậu hoặc, tham được khinh an, sân được khinh an, si được khinh an.' ",
  "sn36.11:2.38": "Thứ nhất. ",
  "sn36.12:0.1": "Tương Ưng Bộ Kinh 36.12 ",
  "sn36.12:0.2": "2. Phẩm Một Mình Tĩnh Tọa ",
  "sn36.12:0.3": "Kinh Hư Không Thứ Nhất ",
  "sn36.12:1.1": "'Ví như, này các Tỳ Kheo, ở trên hư không, các luồng gió khác nhau thổi qua. '",
  "sn36.12:1.2": "Gió đông thổi, gió tây thổi, gió bắc thổi, gió nam thổi, gió bụi bặm thổi, gió không bụi bặm thổi, gió lạnh thổi, gió nóng thổi, gió nhẹ thổi, gió mạnh thổi. ",
  "sn36.12:1.3": "Cũng vậy, này các Tỳ Kheo, trong thân này, các loại cảm giác khác nhau sanh khởi: cảm giác dễ chịu sanh khởi, cảm giác khó chịu sanh khởi, cảm giác không khó chịu cũng không dễ chịu sanh khởi.' ",
  "sn36.12:2.1": "Như những luồng gió trên bầu trời, ",
  "sn36.12:2.2": "thổi đủ loại, đủ hướng; ",
  "sn36.12:2.3": "Gió đông cũng như gió tây, ",
  "sn36.12:2.4": "gió bắc và gió nam. ",
  "sn36.12:3.1": "Gió bụi và gió không bụi, ",
  "sn36.12:3.2": "gió lạnh và gió nóng đôi khi; ",
  "sn36.12:3.3": "Gió mạnh và gió nhẹ, ",
  "sn36.12:3.4": "nhiều luồng gió thổi qua. ",
  "sn36.12:4.1": "Cũng vậy, trong thân này, ",
  "sn36.12:4.2": "các cảm giác sanh khởi; ",
  "sn36.12:4.3": "Cảm giác dễ chịu và cảm giác khó chịu sanh khởi, ",
  "sn36.12:4.4": "và cảm giác không khó chịu cũng không dễ chịu nữa. ",
  "sn36.12:5.1": "Tỳ Kheo tinh tấn, ",
  "sn36.12:5.2": "không bỏ rời tỉnh giác; ",
  "sn36.12:5.3": "Vị ấy rõ biết tất cả cảm giác, ",
  "sn36.12:5.4": "vị trí giả thấu hiểu trọn vẹn. ",
  "sn36.12:6.1": "Đã thông tuệ về cảm giác, ",
  "sn36.12:6.2": "trong đời này không còn lậu hoặc; ",
  "sn36.12:6.3": "Thân hoại, an trú trong Pháp, ",
  "sn36.12:6.4": "bậc minh trí không thể tính đếm được.' ",
  "sn36.12:6.5": "Thứ hai. ",
  "sn36.13:0.1": "Tương Ưng Bộ Kinh 36.13 ",
  "sn36.13:0.2": "2. Phẩm Một Mình Tĩnh Tọa ",
  "sn36.13:0.3": "Kinh Hư Không Thứ Hai ",
  "sn36.13:1.1": "'Ví như, này các Tỳ Kheo, ở trên hư không, các luồng gió khác nhau thổi qua. '",
  "sn36.13:1.2": "Gió đông thổi … gió mạnh thổi. ",
  "sn36.13:1.3": "Cũng vậy, này các Tỳ Kheo, trong thân này, các loại cảm giác khác nhau sanh khởi: cảm giác dễ chịu sanh khởi, cảm giác khó chịu sanh khởi, cảm giác không khó chịu cũng không dễ chịu sanh khởi.' ",
  "sn36.13:1.4": "Thứ ba. ",
  "sn36.14:0.1": "Tương Ưng Bộ Kinh 36.14 ",
  "sn36.14:0.2": "2. Phẩm Một Mình Tĩnh Tọa ",
  "sn36.14:0.3": "Kinh Ngôi Nhà ",
  "sn36.14:1.1": "'Ví như, này các Tỳ Kheo, có một nhà trọ. Ở đó, những người từ phương đông đến cũng dừng lại trú ngụ, người từ phương tây đến cũng dừng lại trú ngụ, người từ phương bắc đến cũng dừng lại trú ngụ, người từ phương nam đến cũng dừng lại trú ngụ. Hàng Sát Đế Lị đến cũng trú ngụ, hàng Bà La Môn đến cũng trú ngụ, hàng Thương Gia đến cũng trú ngụ, hàng Nô Lệ đến cũng trú ngụ. '",
  "sn36.14:1.2": "Cũng vậy, này các Tỳ Kheo, trong thân này, các loại cảm giác khác nhau sanh khởi. cảm giác dễ chịu sanh khởi, cảm giác khó chịu sanh khởi, cảm giác không khó chịu cũng không dễ chịu sanh khởi. ",
  "sn36.14:1.3": "Cảm giác dễ chịu có vật dục sanh khởi, cảm giác khó chịu có vật dục sanh khởi, cảm giác không khó chịu cũng không dễ chịu có vật dục sanh khởi. ",
  "sn36.14:1.4": "Cảm giác dễ chịu không có vật dục sanh khởi, cảm giác khó chịu không có vật dục sanh khởi, cảm giác không khó chịu cũng không dễ chịu không có vật dục sanh khởi.' ",
  "sn36.14:1.5": "Thứ tư. ",
  "sn36.15:0.1": "Tương Ưng Bộ Kinh 36.15 ",
  "sn36.15:0.2": "2. Phẩm Một Mình Tĩnh Tọa ",
  "sn36.15:0.3": "Kinh Ānanda Thứ Nhất ",
  "sn36.15:1.1": "Rồi Tôn giả Ānanda đến gặp Thế Tôn; đến nơi, ngồi xuống một bên, Tôn giả Ānanda bạch Thế Tôn: ",
  "sn36.15:1.2": "'Bạch Thế Tôn, cảm giác là gì, nguồn gốc của cảm giác là gì, sự diệt của cảm giác là gì, con đường dẫn đến diệt cảm giác là gì? '",
  "sn36.15:1.3": "Vị ngọt của cảm giác là gì, sự nguy hiểm của cảm giác là gì, sự xuất ly của cảm giác là gì?' ",
  "sn36.15:1.4": "'Này Ānanda, có ba loại cảm giác'",
  "sn36.15:1.5": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.15:1.6": "đây gọi là cảm giác, này Ānanda. ",
  "sn36.15:1.7": "Do xúc sanh, cảm giác sanh; ",
  "sn36.15:1.8": "do xúc diệt, cảm giác diệt. ",
  "sn36.15:1.9": "Chính Bát Thánh Đạo này là con đường dẫn đến diệt cảm giác, tức là",
  "sn36.15:1.10": "chánh kiến … chánh định. ",
  "sn36.15:1.11": "Do duyên với cảm giác mà lạc và hỷ sanh khởiđây là vị ngọt của cảm giác. ",
  "sn36.15:1.12": "Cảm giác là vô thường, khổ, có bản chất biến đổiđây là sự nguy hiểm của cảm giác. ",
  "sn36.15:1.13": "Sự điều phục và đoạn trừ dục tham đối với cảm giácđây là sự xuất ly của cảm giác. ",
  "sn36.15:1.14": "Này Ānanda, Ta cũng đã nói về sự diệt dần dần của các hành. ",
  "sn36.15:1.15": "Với người đạt sơ thiền, lời nói được diệt … ",
  "sn36.15:1.16": "Với người đạt diệt cảm giác tưởng, tưởng và cảm giác được diệt. ",
  "sn36.15:1.17": "Đối với Tỳ Kheo đã đoạn tận lậu hoặc, tham được diệt, sân được diệt, si được diệt. ",
  "sn36.15:1.18": "Này Ānanda, Ta cũng đã nói về sự lắng xuống dần dần của các hành. ",
  "sn36.15:1.19": "Với người đạt sơ thiền, lời nói được lắng xuống … ",
  "sn36.15:1.20": "Với người đạt diệt cảm giác tưởng, tưởng và cảm giác được lắng xuống. ",
  "sn36.15:1.21": "Đối với Tỳ Kheo đã đoạn tận lậu hoặc, tham được lắng xuống, sân được lắng xuống, si được lắng xuống. ",
  "sn36.15:1.22": "Này Ānanda, Ta cũng đã nói về sự khinh an dần dần của các hành. ",
  "sn36.15:1.23": "Với người đạt sơ thiền, lời nói được khinh an … ",
  "sn36.15:1.24": "Với người đạt không vô biên xứ, tưởng về sắc được khinh an. ",
  "sn36.15:1.25": "Với người đạt thức vô biên xứ, tưởng về không vô biên xứ được khinh an. ",
  "sn36.15:1.26": "Với người đạt vô sở hữu xứ, tưởng về thức vô biên xứ được khinh an. ",
  "sn36.15:1.27": "Với người đạt phi tưởng phi phi tưởng xứ, tưởng về vô sở hữu xứ được khinh an. ",
  "sn36.15:1.28": "Với người đạt diệt cảm giác tưởng, tưởng và cảm giác được khinh an. ",
  "sn36.15:1.29": "Đối với Tỳ Kheo đã đoạn tận lậu hoặc, tham được khinh an, sân được khinh an, si được khinh an.' ",
  "sn36.15:1.30": "Thứ năm. ",
  "sn36.16:0.1": "Tương Ưng Bộ Kinh 36.16 ",
  "sn36.16:0.2": "2. Phẩm Một Mình Tĩnh Tọa ",
  "sn36.16:0.3": "Kinh Ānanda Thứ Hai ",
  "sn36.16:1.1": "Rồi Tôn giả Ānanda đến gặp Thế Tôn; đến nơi, vị ấy đảnh lễ Thế Tôn rồi ngồi xuống một bên. Tôn giả Ānanda đang ngồi một bên, Thế Tôn nói với Tôn giả ấy: ",
  "sn36.16:1.2": "'Này Ānanda, cảm giác là gì, nguồn gốc của cảm giác là gì, sự diệt của cảm giác là gì, con đường dẫn đến diệt cảm giác là gì? '",
  "sn36.16:1.3": "Vị ngọt của cảm giác là gì, sự nguy hiểm của cảm giác là gì, sự xuất ly của cảm giác là gì?' ",
  "sn36.16:1.4": "'Bạch Thế Tôn, Pháp lấy Thế Tôn làm gốc, lấy Thế Tôn làm người dẫn đường, lấy Thế Tôn làm chỗ nương tựa. Lành thay, bạch Thế Tôn, mong Thế Tôn giải thích ý nghĩa của lời nói này. Sau khi nghe Thế Tôn, các Tỳ Kheo sẽ cảm giác trì.' ",
  "sn36.16:1.5": "'Vậy thì, này Ānanda, hãy nghe và khéo tác ý; Ta sẽ nói.' ",
  "sn36.16:1.6": "'Thưa vâng, bạch Thế Tôn,' Tôn giả Ānanda đáp lại Thế Tôn. ",
  "sn36.16:1.7": "Thế Tôn nói: ",
  "sn36.16:1.8": "'Này Ānanda, có ba loại cảm giác'",
  "sn36.16:1.9": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.16:1.10": "đây gọi là cảm giác, này Ānanda … ",
  "sn36.16:1.11": "do xúc sanh … ",
  "sn36.16:1.12": "đối với Tỳ Kheo đã đoạn tận lậu hoặc, tham được khinh an, sân được khinh an, si được khinh an.' ",
  "sn36.16:1.13": "Thứ sáu. ",
  "sn36.17:0.1": "Tương Ưng Bộ Kinh 36.17 ",
  "sn36.17:0.2": "2. Phẩm Một Mình Tĩnh Tọa ",
  "sn36.17:0.3": "Kinh Nhiều Tỳ Kheo Thứ Nhất ",
  "sn36.17:1.1": "Rồi nhiều Tỳ Kheo đến gặp Thế Tôn; đến nơi, các vị đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, các Tỳ Kheo đó bạch Thế Tôn: ",
  "sn36.17:1.2": "'Bạch Thế Tôn, cảm giác là gì, nguồn gốc của cảm giác là gì, sự diệt của cảm giác là gì, con đường dẫn đến diệt cảm giác là gì? '",
  "sn36.17:1.3": "Vị ngọt của cảm giác là gì, sự nguy hiểm của cảm giác là gì, sự xuất ly của cảm giác là gì?' ",
  "sn36.17:1.4": "'Này các Tỳ Kheo, có ba loại cảm giác'",
  "sn36.17:1.5": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.17:1.6": "đây gọi là cảm giác, này các Tỳ Kheo. ",
  "sn36.17:1.7": "Do xúc sanh, cảm giác sanh; ",
  "sn36.17:1.8": "do xúc diệt, cảm giác diệt. ",
  "sn36.17:1.9": "Chính Bát Thánh Đạo này là con đường dẫn đến diệt cảm giác, tức là",
  "sn36.17:1.10": "chánh kiến … chánh định. ",
  "sn36.17:1.11": "Do duyên với cảm giác mà lạc và hỷ sanh khởiđây là vị ngọt của cảm giác. ",
  "sn36.17:1.12": "Cảm giác là vô thường, khổ, có bản chất biến đổiđây là sự nguy hiểm của cảm giác. ",
  "sn36.17:1.13": "Sự điều phục và đoạn trừ dục tham đối với cảm giácđây là sự xuất ly của cảm giác. ",
  "sn36.17:2.1": "Này các Tỳ Kheo, Ta cũng đã nói về sự diệt dần dần của các hành. ",
  "sn36.17:2.2": "Với người đạt sơ thiền, lời nói được diệt … ",
  "sn36.17:2.3": "đối với Tỳ Kheo đã đoạn tận lậu hoặc, tham được diệt, sân được diệt, si được diệt. ",
  "sn36.17:2.4": "Này các Tỳ Kheo, Ta cũng đã nói về sự lắng xuống dần dần của các hành. ",
  "sn36.17:2.5": "Với người đạt sơ thiền, lời nói được lắng xuống … ",
  "sn36.17:2.6": "đối với Tỳ Kheo đã đoạn tận lậu hoặc, tham được lắng xuống, sân được lắng xuống, si được lắng xuống. ",
  "sn36.17:2.7": "Này các Tỳ Kheo, có sáu loại khinh an. ",
  "sn36.17:2.8": "Với người đạt sơ thiền, lời nói được khinh an. ",
  "sn36.17:2.9": "Với người đạt nhị thiền, tầm và tứ được khinh an. ",
  "sn36.17:2.10": "Với người đạt tam thiền, hỷ được khinh an. ",
  "sn36.17:2.11": "Với người đạt tứ thiền, hơi thở vào và ra được khinh an. ",
  "sn36.17:2.12": "Với người đạt diệt cảm giác tưởng, tưởng và cảm giác được khinh an. ",
  "sn36.17:2.13": "Đối với Tỳ Kheo đã đoạn tận lậu hoặc, tham được khinh an, sân được khinh an, si được khinh an.' ",
  "sn36.17:2.14": "Thứ bảy. ",
  "sn36.18:0.1": "Tương Ưng Bộ Kinh 36.18 ",
  "sn36.18:0.2": "2. Phẩm Một Mình Tĩnh Tọa ",
  "sn36.18:0.3": "Kinh Nhiều Tỳ Kheo Thứ Hai ",
  "sn36.18:1.1": "Rồi nhiều Tỳ Kheo đến gặp Thế Tôn … ",
  "sn36.18:1.2": "đang ngồi một bên, Thế Tôn nói với các Tỳ Kheo đó: ",
  "sn36.18:1.3": "'Này các Tỳ Kheo, cảm giác là gì, nguồn gốc của cảm giác là gì, sự diệt của cảm giác là gì, con đường dẫn đến diệt cảm giác là gì? '",
  "sn36.18:1.4": "Vị ngọt của cảm giác là gì, sự nguy hiểm của cảm giác là gì, sự xuất ly của cảm giác là gì?' ",
  "sn36.18:1.5": "'Bạch Thế Tôn, Pháp lấy Thế Tôn làm gốc …' ",
  "sn36.18:1.6": "'Này các Tỳ Kheo, có ba loại cảm giác'",
  "sn36.18:1.7": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.18:1.8": "đây gọi là cảm giác, này các Tỳ Kheo … do xúc sanh … ",
  "sn36.18:1.9": "(Nên giải thích đầy đủ như kinh trước.) ",
  "sn36.18:1.10": "Thứ tám. ",
  "sn36.19:0.1": "Tương Ưng Bộ Kinh 36.19 ",
  "sn36.19:0.2": "2. Phẩm Một Mình Tĩnh Tọa ",
  "sn36.19:0.3": "Kinh Pañcakaṅga ",
  "sn36.19:1.1": "Rồi ông thợ mộc Pañcakaṅga đến gặp Tôn giả Udāyī; đến nơi, ông đảnh lễ Tôn giả Udāyī rồi ngồi xuống một bên. Ngồi xuống một bên, ông thợ mộc Pañcakaṅga hỏi Tôn giả Udāyī: ",
  "sn36.19:1.2": "'Thưa Tôn giả Udāyī, Thế Tôn dạy có bao nhiêu loại cảm giác?' ",
  "sn36.19:1.3": "'Này thợ mộc, Thế Tôn dạy có ba loại cảm giác. '",
  "sn36.19:1.4": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.19:1.5": "đây là ba loại cảm giác mà Thế Tôn đã dạy, này thợ mộc.' ",
  "sn36.19:1.6": "Khi được nói vậy, ông thợ mộc Pañcakaṅga nói với Tôn giả Udāyī: ",
  "sn36.19:1.7": "'Thưa Tôn giả Udāyī, Thế Tôn không dạy có ba loại cảm giác. '",
  "sn36.19:1.8": "Thế Tôn dạy có hai loại cảm giác",
  "sn36.19:1.9": "Cảm giác dễ chịu và cảm giác khó chịu. ",
  "sn36.19:1.10": "Thưa Tôn giả, cảm giác không khó chịu cũng không dễ chịu đó, Thế Tôn đã đề cập đến trong lạc tịnh tế.' ",
  "sn36.19:2.1": "Lần thứ hai, Tôn giả Udāyī nói với ông thợ mộc Pañcakaṅga: ",
  "sn36.19:2.2": "'Này thợ mộc, Thế Tôn không dạy có hai loại cảm giác. '",
  "sn36.19:2.3": "Thế Tôn dạy có ba loại cảm giác. ",
  "sn36.19:2.4": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.19:2.5": "đây là ba loại cảm giác mà Thế Tôn đã dạy.' ",
  "sn36.19:2.6": "Lần thứ hai, ông thợ mộc Pañcakaṅga nói với Tôn giả Udāyī: ",
  "sn36.19:2.7": "'Thưa Tôn giả Udāyī, Thế Tôn không dạy có ba loại cảm giác. '",
  "sn36.19:2.8": "Thế Tôn dạy có hai loại cảm giác",
  "sn36.19:2.9": "Cảm giác dễ chịu và cảm giác khó chịu. ",
  "sn36.19:2.10": "Thưa Tôn giả, cảm giác không khó chịu cũng không dễ chịu đó, Thế Tôn đã đề cập đến trong lạc tịnh tế.' ",
  "sn36.19:3.1": "Lần thứ ba, Tôn giả Udāyī nói với ông thợ mộc Pañcakaṅga: ",
  "sn36.19:3.2": "'Này thợ mộc, Thế Tôn không dạy có hai loại cảm giác. '",
  "sn36.19:3.3": "Thế Tôn dạy có ba loại cảm giác. ",
  "sn36.19:3.4": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.19:3.5": "đây là ba loại cảm giác mà Thế Tôn đã dạy.' ",
  "sn36.19:3.6": "Lần thứ ba, ông thợ mộc Pañcakaṅga nói với Tôn giả Udāyī: ",
  "sn36.19:3.7": "'Thưa Tôn giả Udāyī, Thế Tôn không dạy có ba loại cảm giác. '",
  "sn36.19:3.8": "Thế Tôn dạy có hai loại cảm giác",
  "sn36.19:3.9": "Cảm giác dễ chịu và cảm giác khó chịu. ",
  "sn36.19:3.10": "Thưa Tôn giả, cảm giác không khó chịu cũng không dễ chịu đó, Thế Tôn đã đề cập đến trong lạc tịnh tế.' ",
  "sn36.19:3.11": "Tôn giả Udāyī không thể thuyết phục ông thợ mộc Pañcakaṅga, và ông thợ mộc Pañcakaṅga cũng không thể thuyết phục Tôn giả Udāyī. ",
  "sn36.19:3.12": "Tôn giả Ānanda nghe được cuộc tranh luận đó giữa Tôn giả Udāyī và ông thợ mộc Pañcakaṅga. ",
  "sn36.19:4.1": "Rồi Tôn giả Ānanda đến gặp Thế Tôn; đến nơi, ngồi xuống một bên. ",
  "sn36.19:4.2": "Ngồi xuống một bên, Tôn giả Ānanda thuật lại toàn bộ cuộc hội thoại giữa Tôn giả Udāyī và ông thợ mộc Pañcakaṅga cho Thế Tôn nghe. ",
  "sn36.19:5.1": "'Này Ānanda, ông thợ mộc Pañcakaṅga không tán đồng cách trình bày đúng đắn của Tỳ Kheo Udāyī; '",
  "sn36.19:5.2": "nhưng, này Ānanda, Tỳ Kheo Udāyī cũng không tán đồng cách trình bày đúng đắn của ông thợ mộc Pañcakaṅga. ",
  "sn36.19:5.3": "Này Ānanda, Ta đã dạy hai loại cảm giác theo một cách trình bày. ",
  "sn36.19:5.4": "Ta đã dạy ba loại cảm giác theo một cách trình bày. ",
  "sn36.19:5.5": "Ta đã dạy năm loại cảm giác theo một cách trình bày. ",
  "sn36.19:5.6": "Ta đã dạy sáu loại cảm giác theo một cách trình bày. ",
  "sn36.19:5.7": "Ta đã dạy mười tám loại cảm giác theo một cách trình bày. ",
  "sn36.19:5.8": "Ta đã dạy ba mươi sáu loại cảm giác theo một cách trình bày. ",
  "sn36.19:5.9": "Ta đã dạy một trăm lẻ tám loại cảm giác theo một cách trình bày. ",
  "sn36.19:5.10": "Này Ānanda, Pháp của Ta được giảng dạy theo nhiều cách như vậy. ",
  "sn36.19:5.11": "Này Ānanda, khi Pháp được Ta giảng dạy theo nhiều cách như vậy, những người không tán đồng, không chấp nhận, không hoan hỷ với những điều được khéo nói, khéo trình bày của nhau, điều này có thể được mong đợi từ họhọ sẽ sống trong tranh chấp, cãi vã, bất đồng, đâm chém nhau bằng lưỡi dao miệng. ",
  "sn36.19:5.12": "Này Ānanda, khi Pháp được Ta giảng dạy theo nhiều cách như vậy, những người tán đồng, chấp nhận, hoan hỷ với những điều được khéo nói, khéo trình bày của nhau, điều này có thể được mong đợi từ họhọ sẽ sống hòa hợp, thân thiện, không tranh chấp, hòa tan như nước với sữa, nhìn nhau bằng đôi mắt thân ái. ",
  "sn36.19:6.1": "Này Ānanda, có năm dục công đức. ",
  "sn36.19:6.2": "Năm thứ đó là gì? ",
  "sn36.19:6.3": "Các sắc do mắt nhận thức, khả ái, dễ chịu, đáng yêu, đẹp lòng, liên hệ đến dục, hấp dẫn … ",
  "sn36.19:6.4": "các xúc do thân nhận thức, khả ái, dễ chịu, đáng yêu, đẹp lòng, liên hệ đến dục, hấp dẫn. ",
  "sn36.19:6.5": "Này Ānanda, đây là năm dục công đức. ",
  "sn36.19:6.6": "Này Ānanda, lạc và hỷ sanh khởi do duyên với năm dục công đức này",
  "sn36.19:6.7": "đây gọi là dục lạc. ",
  "sn36.19:6.8": "Này Ānanda, những ai nói rằng: ",
  "sn36.19:6.9": "'Đây là lạc và hỷ tối thượng được cảm cảm giác'",
  "sn36.19:6.10": "điều đó Ta không chấp nhận. ",
  "sn36.19:6.11": "Tại sao vậy? ",
  "sn36.19:6.12": "Này Ānanda, có một lạc khác tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:7.1": "Này Ānanda, lạc khác tốt hơn và thù thắng hơn lạc đó là gì? ",
  "sn36.19:7.2": "Này Ānanda, ở đây Tỳ Kheo ly dục, ly bất thiện pháp, chứng đạt và an trú sơ thiền, có tầm có tứ, với hỷ lạc do ly dục sanh. ",
  "sn36.19:7.3": "Này Ānanda, đây là lạc tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:7.4": "Này Ānanda, những ai nói rằng: ",
  "sn36.19:7.5": "'Đây là lạc và hỷ tối thượng được cảm cảm giác'",
  "sn36.19:7.6": "điều đó Ta không chấp nhận. ",
  "sn36.19:7.7": "Tại sao vậy? ",
  "sn36.19:7.8": "Này Ānanda, có một lạc khác tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:8.1": "Này Ānanda, lạc khác tốt hơn và thù thắng hơn lạc đó là gì? ",
  "sn36.19:8.2": "Này Ānanda, ở đây Tỳ Kheo do tầm tứ diệt, nội tâm thanh tịnh, nhất tâm, chứng đạt và an trú nhị thiền, không tầm không tứ, với hỷ lạc do định sanh. ",
  "sn36.19:8.3": "Này Ānanda, đây là lạc tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:8.4": "Này Ānanda, những ai nói rằng: ",
  "sn36.19:8.5": "'Đây là lạc và hỷ tối thượng được cảm cảm giác'",
  "sn36.19:8.6": "điều đó Ta không chấp nhận. ",
  "sn36.19:8.7": "Tại sao vậy? ",
  "sn36.19:8.8": "Này Ānanda, có một lạc khác tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:9.1": "Này Ānanda, lạc khác tốt hơn và thù thắng hơn lạc đó là gì? ",
  "sn36.19:9.2": "Này Ānanda, ở đây Tỳ Kheo ly hỷ, trú xả, chánh niệm tỉnh giác, thân cảm cảm giác lạc, điều mà các bậc Thánh gọi là 'người xả, có chánh niệm, an trú trong lạc', chứng đạt và an trú tam thiền. ",
  "sn36.19:9.3": "Này Ānanda, đây là lạc tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:9.4": "Này Ānanda, những ai nói rằng: ",
  "sn36.19:9.5": "'Đây là lạc và hỷ tối thượng được cảm cảm giác'",
  "sn36.19:9.6": "điều đó Ta không chấp nhận. ",
  "sn36.19:9.7": "Tại sao vậy? ",
  "sn36.19:9.8": "Này Ānanda, có một lạc khác tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:10.1": "Này Ānanda, lạc khác tốt hơn và thù thắng hơn lạc đó là gì? ",
  "sn36.19:10.2": "Này Ānanda, ở đây Tỳ Kheo xả lạc, xả khổ, diệt hỷ ưu đã có trước, chứng đạt và an trú tứ thiền, không khổ không lạc, với xả niệm thanh tịnh. ",
  "sn36.19:10.3": "Này Ānanda, đây là lạc tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:10.4": "Này Ānanda, những ai nói rằng: ",
  "sn36.19:10.5": "'Đây là lạc và hỷ tối thượng được cảm cảm giác'",
  "sn36.19:10.6": "điều đó Ta không chấp nhận. ",
  "sn36.19:10.7": "Tại sao vậy? ",
  "sn36.19:10.8": "Này Ānanda, có một lạc khác tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:11.1": "Này Ānanda, lạc khác tốt hơn và thù thắng hơn lạc đó là gì? ",
  "sn36.19:11.2": "Này Ānanda, ở đây Tỳ Kheo vượt qua hoàn toàn các tưởng về sắc, đoạn diệt các tưởng về chướng ngại, không tác ý các tưởng về dị biệt, nghĩ 'Hư không là vô biên', chứng đạt và an trú không vô biên xứ. ",
  "sn36.19:11.3": "Này Ānanda, đây là lạc tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:11.4": "Này Ānanda, những ai nói rằng: ",
  "sn36.19:11.5": "'Đây là lạc và hỷ tối thượng được cảm cảm giác'",
  "sn36.19:11.6": "điều đó Ta không chấp nhận. ",
  "sn36.19:11.7": "Tại sao vậy? ",
  "sn36.19:11.8": "Này Ānanda, có một lạc khác tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:12.1": "Này Ānanda, lạc khác tốt hơn và thù thắng hơn lạc đó là gì? ",
  "sn36.19:12.2": "Này Ānanda, ở đây Tỳ Kheo vượt qua hoàn toàn không vô biên xứ, nghĩ 'Thức là vô biên', chứng đạt và an trú thức vô biên xứ. ",
  "sn36.19:12.3": "Này Ānanda, đây là lạc tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:12.4": "Này Ānanda, những ai nói rằng: ",
  "sn36.19:12.5": "'Đây là lạc và hỷ tối thượng được cảm cảm giác'",
  "sn36.19:12.6": "điều đó Ta không chấp nhận. ",
  "sn36.19:12.7": "Tại sao vậy? ",
  "sn36.19:12.8": "Này Ānanda, có một lạc khác tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:13.1": "Này Ānanda, lạc khác tốt hơn và thù thắng hơn lạc đó là gì? ",
  "sn36.19:13.2": "Này Ānanda, ở đây Tỳ Kheo vượt qua hoàn toàn thức vô biên xứ, nghĩ 'Không có gì cả', chứng đạt và an trú vô sở hữu xứ. ",
  "sn36.19:13.3": "Này Ānanda, đây là lạc tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:13.4": "Này Ānanda, những ai nói rằng: ",
  "sn36.19:13.5": "'Đây là lạc và hỷ tối thượng được cảm cảm giác'",
  "sn36.19:13.6": "điều đó Ta không chấp nhận. ",
  "sn36.19:13.7": "Tại sao vậy? ",
  "sn36.19:13.8": "Này Ānanda, có một lạc khác tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:14.1": "Này Ānanda, lạc khác tốt hơn và thù thắng hơn lạc đó là gì? ",
  "sn36.19:14.2": "Này Ānanda, ở đây Tỳ Kheo vượt qua hoàn toàn vô sở hữu xứ, chứng đạt và an trú phi tưởng phi phi tưởng xứ. ",
  "sn36.19:14.3": "Này Ānanda, đây là lạc tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:14.4": "Này Ānanda, những ai nói rằng: ",
  "sn36.19:14.5": "'Đây là lạc và hỷ tối thượng được cảm cảm giác'",
  "sn36.19:14.6": "điều đó Ta không chấp nhận. ",
  "sn36.19:14.7": "Tại sao vậy? ",
  "sn36.19:14.8": "Này Ānanda, có một lạc khác tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:15.1": "Này Ānanda, lạc khác tốt hơn và thù thắng hơn lạc đó là gì? ",
  "sn36.19:15.2": "Này Ānanda, ở đây Tỳ Kheo vượt qua hoàn toàn phi tưởng phi phi tưởng xứ, chứng đạt và an trú diệt cảm giác tưởng. ",
  "sn36.19:15.3": "Này Ānanda, đây là lạc tốt hơn và thù thắng hơn lạc đó. ",
  "sn36.19:16.1": "Này Ānanda, có thể xảy ra trường hợp các du sĩ ngoại đạo nói rằng: ",
  "sn36.19:16.2": "'Sa-môn Gotama dạy về diệt cảm giác tưởng và đặt nó trong phạm trù lạc. '",
  "sn36.19:16.3": "Điều đó có nghĩa gì, điều đó như thế nào?' ",
  "sn36.19:16.4": "Này Ānanda, khi các du sĩ ngoại đạo nói như vậy, hãy nói với họ: ",
  "sn36.19:16.5": "'Này chư hiền, Thế Tôn không chỉ đặt lạc trong phạm trù cảm giác lạc. '",
  "sn36.19:16.6": "Này chư hiền, bất cứ ở đâu có lạc được tìm thấy, bất cứ điều gì, Như Lai đặt điều đó trong phạm trù lạc'.' ",
  "sn36.19:16.7": "Thứ chín. ",
  "sn36.20:0.1": "Tương Ưng Bộ Kinh 36.20 ",
  "sn36.20:0.2": "2. Phẩm Một Mình Tĩnh Tọa ",
  "sn36.20:0.3": "Kinh Tỳ Kheo ",
  "sn36.20:1.1": "'Này các Tỳ Kheo, Ta đã dạy hai loại cảm giác theo một cách trình bày, ba loại cảm giác theo một cách trình bày, năm loại cảm giác theo một cách trình bày, sáu loại cảm giác theo một cách trình bày, mười tám loại cảm giác theo một cách trình bày, ba mươi sáu loại cảm giác theo một cách trình bày, một trăm lẻ tám loại cảm giác theo một cách trình bày. '",
  "sn36.20:1.2": "Này các Tỳ Kheo, Pháp của Ta được giảng dạy theo nhiều cách như vậy. ",
  "sn36.20:1.3": "Này các Tỳ Kheo, khi Pháp được Ta giảng dạy theo nhiều cách như vậy, những người không tán đồng, không chấp nhận, không hoan hỷ với những điều được khéo nói, khéo trình bày của nhau, điều này có thể được mong đợi từ họhọ sẽ sống trong tranh chấp, cãi vã, bất đồng, đâm chém nhau bằng lưỡi dao miệng. ",
  "sn36.20:1.4": "Này các Tỳ Kheo, khi Pháp được Ta giảng dạy theo nhiều cách như vậy, những người tán đồng, chấp nhận, hoan hỷ với những điều được khéo nói, khéo trình bày của nhau, điều này có thể được mong đợi từ họhọ sẽ sống hòa hợp, thân thiện, không tranh chấp, hòa tan như nước với sữa, nhìn nhau bằng đôi mắt thân ái. ",
  "sn36.20:2.1": "Này các Tỳ Kheo, có năm dục công đức … ",
  "sn36.20:2.2": "này các Tỳ Kheo, có thể xảy ra trường hợp các du sĩ ngoại đạo nói rằng: ",
  "sn36.20:2.3": "'Sa-môn Gotama dạy về diệt cảm giác tưởng và đặt nó trong phạm trù lạc. '",
  "sn36.20:2.4": "Điều đó có nghĩa gì, điều đó như thế nào?' ",
  "sn36.20:2.5": "Này các Tỳ Kheo, khi các du sĩ ngoại đạo nói như vậy, hãy nói với họ: ",
  "sn36.20:2.6": "'Này chư hiền, Thế Tôn không chỉ đặt lạc trong phạm trù cảm giác lạc. '",
  "sn36.20:2.7": "Này chư hiền, bất cứ ở đâu có lạc được tìm thấy, bất cứ điều gì, Như Lai đặt điều đó trong phạm trù lạc'.' ",
  "sn36.20:2.8": "Thứ mười. ",
  "sn36.20:2.9": "Phẩm Một Mình Tĩnh Tọa, thứ hai. ",
  "sn36.20:3.0": "Tóm tắt phẩm này: ",
  "sn36.20:3.1": "Một mình tĩnh tọa, hai bài hư không, ",
  "sn36.20:3.2": "ngôi nhà, hai bài Ānanda; ",
  "sn36.20:3.3": "Hai bài nhiều Tỳ Kheo, ",
  "sn36.20:3.4": "Pañcakaṅga và Tỳ Kheo. ",
  "sn36.21:0.1": "Tương Ưng Bộ Kinh 36.21 ",
  "sn36.21:0.2": "3. Phẩm Một Trăm Lẻ Tám Pháp Môn ",
  "sn36.21:0.3": "Kinh Sīvaka ",
  "sn36.21:1.1": "Một thời Thế Tôn trú ở Rājagaha, tại Trúc Lâm, chỗ nuôi dưỡng sóc. ",
  "sn36.21:1.2": "Rồi du sĩ Moḷiyasīvaka đến gặp Thế Tôn; đến nơi, ông chào hỏi thân thiện với Thế Tôn. ",
  "sn36.21:1.3": "Sau khi chào hỏi thân thiện và đáng nhớ, ông ngồi xuống một bên. Ngồi xuống một bên, du sĩ Moḷiyasīvaka nói với Thế Tôn: ",
  "sn36.21:1.4": "'Thưa Ngài Gotama, có một số sa-môn và bà-la-môn có quan điểm và kiến giải như sau: '",
  "sn36.21:1.5": "'Bất cứ điều gì mà con người cảm cảm giác, dù vui, khổ hay bất khổ bất lạc, tất cả đều do nghiệp đời trước'. ",
  "sn36.21:1.6": "Ngài Gotama nói gì về điều này?' ",
  "sn36.21:2.1": "'Này Sīvaka, một số cảm giác sanh khởi ở đây do mật sanh. '",
  "sn36.21:2.2": "Này Sīvaka, điều này có thể biết được bằng chính mình, rằng một số cảm giác sanh khởi ở đây do mật sanh. ",
  "sn36.21:2.3": "Này Sīvaka, điều này cũng được thế gian chấp nhận là thật, rằng một số cảm giác sanh khởi ở đây do mật sanh. ",
  "sn36.21:2.4": "Vì vậy, này Sīvaka, những sa-môn và bà-la-môn có quan điểm và kiến giải rằng: ",
  "sn36.21:2.5": "'Bất cứ điều gì mà con người cảm cảm giác, dù vui, khổ hay bất khổ bất lạc, tất cả đều do nghiệp đời trước' ",
  "sn36.21:2.6": "họ vượt qua những gì biết được bằng chính mình, và vượt qua những gì được thế gian chấp nhận là thật. ",
  "sn36.21:2.7": "Vì vậy, Ta nói những sa-môn và bà-la-môn đó là sai. ",
  "sn36.21:3.1": "Này Sīvaka, một số cảm giác sanh khởi do đàm sanh … ",
  "sn36.21:3.2": "do phong sanh … ",
  "sn36.21:3.3": "do hội tụ của ba yếu tố … ",
  "sn36.21:3.4": "do thay đổi khí hậu … ",
  "sn36.21:3.5": "do điều kiện sinh hoạt bất thường … ",
  "sn36.21:3.6": "do bạo lực gây ra … ",
  "sn36.21:3.7": "một số cảm giác sanh khởi ở đây do nghiệp báo. ",
  "sn36.21:3.8": "Này Sīvaka, điều này có thể biết được bằng chính mình. ",
  "sn36.21:3.9": "Rằng một số cảm giác sanh khởi ở đây do nghiệp báo; ",
  "sn36.21:3.10": "điều này cũng được thế gian chấp nhận là thật. ",
  "sn36.21:3.11": "Rằng một số cảm giác sanh khởi ở đây do nghiệp báo; ",
  "sn36.21:3.12": "vì vậy, này Sīvaka, những sa-môn và bà-la-môn có quan điểm và kiến giải rằng: ",
  "sn36.21:3.13": "'Bất cứ điều gì mà con người cảm cảm giác, dù vui, khổ hay bất khổ bất lạc, tất cả đều do nghiệp đời trước' ",
  "sn36.21:3.14": "họ vượt qua những gì biết được bằng chính mình, và vượt qua những gì được thế gian chấp nhận là thật. ",
  "sn36.21:3.15": "Vì vậy, Ta nói những sa-môn và bà-la-môn đó là sai'.' ",
  "sn36.21:4.1": "Khi được nói vậy, du sĩ Moḷiyasīvaka nói với Thế Tôn: ",
  "sn36.21:4.2": "'Thật tuyệt vời, thưa Ngài Gotama, thật tuyệt vời … '",
  "sn36.21:4.3": "mong Ngài Gotama nhận con làm Ưu-bà-tắc, từ nay cho đến trọn đời quy y Tam Bảo.' ",
  "sn36.21:5.1": "'Mật, đàm và phong, '",
  "sn36.21:5.2": "Hội tụ cùng khí hậu; ",
  "sn36.21:5.3": "Bất thường và bạo lực, ",
  "sn36.21:5.4": "Nghiệp báo là thứ tám.' ",
  "sn36.21:5.5": "Thứ nhất. ",
  "sn36.22:0.1": "Tương Ưng Bộ Kinh 36.22 ",
  "sn36.22:0.2": "3. Phẩm Một Trăm Lẻ Tám Pháp Môn ",
  "sn36.22:0.3": "Kinh Một Trăm Lẻ Tám ",
  "sn36.22:1.1": "'Này các Tỳ Kheo, Ta sẽ giảng pháp môn một trăm lẻ tám cho các ông. '",
  "sn36.22:1.2": "Hãy lắng nghe. ",
  "sn36.22:1.3": "Này các Tỳ Kheo, pháp môn một trăm lẻ tám là gì? ",
  "sn36.22:1.4": "Này các Tỳ Kheo, Ta đã dạy hai loại cảm giác theo một cách trình bày; ",
  "sn36.22:1.5": "Ta đã dạy ba loại cảm giác theo một cách trình bày; ",
  "sn36.22:1.6": "Ta đã dạy năm loại cảm giác theo một cách trình bày; ",
  "sn36.22:1.7": "Ta đã dạy sáu loại cảm giác theo một cách trình bày; ",
  "sn36.22:1.8": "Ta đã dạy mười tám loại cảm giác theo một cách trình bày; ",
  "sn36.22:1.9": "Ta đã dạy ba mươi sáu loại cảm giác theo một cách trình bày; ",
  "sn36.22:1.10": "Ta đã dạy một trăm lẻ tám loại cảm giác theo một cách trình bày. ",
  "sn36.22:2.1": "Này các Tỳ Kheo, hai loại cảm giác là gì? ",
  "sn36.22:2.2": "Cảm giác thuộc thân và cảm giác thuộc tâm",
  "sn36.22:2.3": "đây gọi là hai loại cảm giác, này các Tỳ Kheo. ",
  "sn36.22:2.4": "Này các Tỳ Kheo, ba loại cảm giác là gì? ",
  "sn36.22:2.5": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.22:2.6": "đây gọi là ba loại cảm giác, này các Tỳ Kheo. ",
  "sn36.22:2.7": "Này các Tỳ Kheo, năm loại cảm giác là gì? ",
  "sn36.22:2.8": "Lạc quyền, khổ quyền, hỷ quyền, ưu quyền, xả quyền",
  "sn36.22:2.9": "đây gọi là năm loại cảm giác, này các Tỳ Kheo. ",
  "sn36.22:2.10": "Này các Tỳ Kheo, sáu loại cảm giác là gì? ",
  "sn36.22:2.11": "Cảm giác sanh từ nhãn xúc … ",
  "sn36.22:2.12": "Cảm giác sanh từ ý xúc",
  "sn36.22:2.13": "đây gọi là sáu loại cảm giác, này các Tỳ Kheo. ",
  "sn36.22:2.14": "Này các Tỳ Kheo, mười tám loại cảm giác là gì? ",
  "sn36.22:2.15": "Sáu tầm hỷ, sáu tầm ưu, sáu tầm xả",
  "sn36.22:2.16": "đây gọi là mười tám loại cảm giác, này các Tỳ Kheo. ",
  "sn36.22:2.17": "Này các Tỳ Kheo, ba mươi sáu loại cảm giác là gì? ",
  "sn36.22:2.18": "Sáu hỷ tại gia, sáu hỷ xuất gia, sáu ưu tại gia, sáu ưu xuất gia, sáu xả tại gia, sáu xả xuất gia",
  "sn36.22:2.19": "đây gọi là ba mươi sáu loại cảm giác, này các Tỳ Kheo. ",
  "sn36.22:2.20": "Này các Tỳ Kheo, một trăm lẻ tám loại cảm giác là gì? ",
  "sn36.22:2.21": "Ba mươi sáu cảm giác thuộc quá khứ, ba mươi sáu cảm giác thuộc tương lai, ba mươi sáu cảm giác thuộc hiện tại",
  "sn36.22:2.22": "đây gọi là một trăm lẻ tám loại cảm giác, này các Tỳ Kheo. ",
  "sn36.22:2.23": "Này các Tỳ Kheo, đây là pháp môn một trăm lẻ tám.' ",
  "sn36.22:2.24": "Thứ hai. ",
  "sn36.23:0.1": "Tương Ưng Bộ Kinh 36.23 ",
  "sn36.23:0.2": "3. Phẩm Một Trăm Lẻ Tám Pháp Môn ",
  "sn36.23:0.3": "Kinh Một Tỳ Kheo ",
  "sn36.23:1.1": "Rồi một Tỳ Kheo đến gặp Thế Tôn; đến nơi, vị ấy đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, vị Tỳ Kheo đó bạch Thế Tôn: ",
  "sn36.23:1.2": "'Bạch Thế Tôn, cảm giác là gì, nguồn gốc của cảm giác là gì, con đường dẫn đến sanh cảm giác là gì? '",
  "sn36.23:1.3": "Sự diệt của cảm giác là gì, con đường dẫn đến diệt cảm giác là gì? ",
  "sn36.23:1.4": "Vị ngọt của cảm giác là gì, sự nguy hiểm của cảm giác là gì, sự xuất ly của cảm giác là gì?' ",
  "sn36.23:2.1": "'Này Tỳ Kheo, có ba loại cảm giác'",
  "sn36.23:2.2": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu. ",
  "sn36.23:2.3": "Đây gọi là cảm giác, này Tỳ Kheo. ",
  "sn36.23:2.4": "Do xúc sanh, cảm giác sanh. ",
  "sn36.23:2.5": "Ái là con đường dẫn đến sanh cảm giác. ",
  "sn36.23:2.6": "Do xúc diệt, cảm giác diệt. ",
  "sn36.23:2.7": "Chính Bát Thánh Đạo này là con đường dẫn đến diệt cảm giác, tức là",
  "sn36.23:2.8": "chánh kiến … chánh định. ",
  "sn36.23:2.9": "Do duyên với cảm giác mà lạc và hỷ sanh khởiđây là vị ngọt của cảm giác; ",
  "sn36.23:2.10": "Cảm giác là vô thường, khổ, có bản chất biến đổiđây là sự nguy hiểm của cảm giác; ",
  "sn36.23:2.11": "sự điều phục và đoạn trừ dục tham đối với cảm giácđây là sự xuất ly của cảm giác.' ",
  "sn36.23:2.12": "Thứ ba. ",
  "sn36.24:0.1": "Tương Ưng Bộ Kinh 36.24 ",
  "sn36.24:0.2": "3. Phẩm Một Trăm Lẻ Tám Pháp Môn ",
  "sn36.24:0.3": "Kinh Trước Kia ",
  "sn36.24:1.1": "'Này các Tỳ Kheo, trước khi Ta giác ngộ, khi còn là Bồ Tát chưa giác ngộ, tư duy này đã khởi lên nơi Ta: '",
  "sn36.24:1.2": "'cảm giác là gì, nguồn gốc của cảm giác là gì, con đường dẫn đến sanh cảm giác là gì, sự diệt của cảm giác là gì, con đường dẫn đến diệt cảm giác là gì? '",
  "sn36.24:1.3": "Vị ngọt của cảm giác là gì, sự nguy hiểm của cảm giác là gì, sự xuất ly của cảm giác là gì?' ",
  "sn36.24:1.4": "Này các Tỳ Kheo, rồi tư duy này đã đến với Ta: ",
  "sn36.24:1.5": "'Có ba loại cảm giác'",
  "sn36.24:1.6": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu. ",
  "sn36.24:1.7": "Đây gọi là cảm giác. ",
  "sn36.24:1.8": "Do xúc sanh, cảm giác sanh. ",
  "sn36.24:1.9": "Ái là con đường dẫn đến sanh cảm giác … ",
  "sn36.24:1.10": "sự điều phục và đoạn trừ dục tham đối với cảm giácđây là sự xuất ly của cảm giác'.' ",
  "sn36.24:1.11": "Thứ tư. ",
  "sn36.25:0.1": "Tương Ưng Bộ Kinh 36.25 ",
  "sn36.25:0.2": "3. Phẩm Một Trăm Lẻ Tám Pháp Môn ",
  "sn36.25:0.3": "Kinh Trí ",
  "sn36.25:1.1": "'Này các Tỳ Kheo, đối với Ta, về những pháp trước đây chưa được nghe, nhãn đã sanh, trí đã sanh, tuệ đã sanh, minh đã sanh, quang đã sanh: 'Đây là cảm giác'. '",
  "sn36.25:1.2": "Này các Tỳ Kheo, đối với Ta, về những pháp trước đây chưa được nghe, nhãn đã sanh … quang đã sanh: 'Đây là nguồn gốc của cảm giác'. ",
  "sn36.25:1.3": "Này các Tỳ Kheo, đối với Ta, về những pháp trước đây chưa được nghe, nhãn đã sanh … 'Đây là con đường dẫn đến sanh cảm giác'. ",
  "sn36.25:1.4": "Này các Tỳ Kheo, đối với Ta, về những pháp trước đây chưa được nghe, nhãn đã sanh … 'Đây là sự diệt của cảm giác'. ",
  "sn36.25:1.5": "Này các Tỳ Kheo, đối với Ta, về những pháp trước đây chưa được nghe, nhãn đã sanh … 'Đây là con đường dẫn đến diệt cảm giác'. ",
  "sn36.25:1.6": "Này các Tỳ Kheo, đối với Ta, về những pháp trước đây chưa được nghe … 'Đây là vị ngọt của cảm giác'. ",
  "sn36.25:1.7": "Này các Tỳ Kheo, đối với Ta, về những pháp trước đây chưa được nghe … 'Đây là sự nguy hiểm của cảm giác'. ",
  "sn36.25:1.8": "Này các Tỳ Kheo, đối với Ta, về những pháp trước đây chưa được nghe, nhãn đã sanh, trí đã sanh, tuệ đã sanh, minh đã sanh, quang đã sanh: 'Đây chính là sự xuất ly'.' ",
  "sn36.25:1.9": "Thứ năm. ",
  "sn36.26:0.1": "Tương Ưng Bộ Kinh 36.26 ",
  "sn36.26:0.2": "3. Phẩm Một Trăm Lẻ Tám Pháp Môn ",
  "sn36.26:0.3": "Kinh Nhiều Tỳ Kheo ",
  "sn36.26:1.1": "Rồi nhiều Tỳ Kheo đến gặp Thế Tôn; đến nơi … ngồi xuống một bên, các Tỳ Kheo đó bạch Thế Tôn: ",
  "sn36.26:1.2": "'Bạch Thế Tôn, cảm giác là gì, nguồn gốc của cảm giác là gì, con đường dẫn đến sanh cảm giác là gì? '",
  "sn36.26:1.3": "Sự diệt của cảm giác là gì, con đường dẫn đến diệt cảm giác là gì? ",
  "sn36.26:1.4": "Vị ngọt của cảm giác là gì, sự nguy hiểm của cảm giác là gì, sự xuất ly của cảm giác là gì?' ",
  "sn36.26:1.5": "'Này các Tỳ Kheo, có ba loại cảm giác'",
  "sn36.26:1.6": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu. ",
  "sn36.26:1.7": "Đây gọi là cảm giác, này các Tỳ Kheo. ",
  "sn36.26:1.8": "Do xúc sanh, cảm giác sanh. ",
  "sn36.26:1.9": "Ái là con đường dẫn đến sanh cảm giác. ",
  "sn36.26:1.10": "Do xúc diệt … ",
  "sn36.26:1.11": "sự điều phục và đoạn trừ dục tham đối với cảm giácđây là sự xuất ly của cảm giác.' ",
  "sn36.26:1.12": "Thứ sáu. ",
  "sn36.27:0.1": "Tương Ưng Bộ Kinh 36.27 ",
  "sn36.27:0.2": "3. Phẩm Một Trăm Lẻ Tám Pháp Môn ",
  "sn36.27:0.3": "Kinh Sa Môn Bà La Môn Thứ Nhất ",
  "sn36.27:1.1": "'Này các Tỳ Kheo, có ba loại cảm giác. '",
  "sn36.27:1.2": "Ba loại đó là gì? ",
  "sn36.27:1.3": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu. ",
  "sn36.27:1.4": "Này các Tỳ Kheo, những sa-môn hay bà-la-môn nào không như thật rõ biết sự sanh khởi, sự diệt tận, vị ngọt, sự nguy hiểm và sự xuất ly của ba loại cảm giác này. ",
  "sn36.27:1.5": "Ta nói rằng những sa-môn hay bà-la-môn đó không được thừa nhận là sa-môn trong hàng sa-môn, không được thừa nhận là bà-la-môn trong hàng bà-la-môn, và các tôn giả đó cũng không tự mình chứng ngộ và an trú vào mục tiêu của sa-môn hay mục tiêu của bà-la-môn ngay trong đời này. ",
  "sn36.27:1.6": "Này các Tỳ Kheo, những sa-môn hay bà-la-môn nào như thật rõ biết sự sanh khởi, sự diệt tận, vị ngọt, sự nguy hiểm và sự xuất ly của ba loại cảm giác này. ",
  "sn36.27:1.7": "Ta nói rằng những sa-môn hay bà-la-môn đó được thừa nhận là sa-môn trong hàng sa-môn và được thừa nhận là bà-la-môn trong hàng bà-la-môn. Và các tôn giả đó tự mình chứng ngộ và an trú vào mục tiêu của sa-môn và mục tiêu của bà-la-môn ngay trong đời này.' ",
  "sn36.27:1.8": "Thứ bảy. ",
  "sn36.28:0.1": "Tương Ưng Bộ Kinh 36.28 ",
  "sn36.28:0.2": "3. Phẩm Một Trăm Lẻ Tám Pháp Môn ",
  "sn36.28:0.3": "Kinh Sa Môn Bà La Môn Thứ Hai ",
  "sn36.28:1.1": "'Này các Tỳ Kheo, có ba loại cảm giác. '",
  "sn36.28:1.2": "Ba loại đó là gì? ",
  "sn36.28:1.3": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu. ",
  "sn36.28:1.4": "Này các Tỳ Kheo, những sa-môn hay bà-la-môn nào không như thật rõ biết sự sanh khởi, sự diệt tận, vị ngọt, sự nguy hiểm và sự xuất ly của ba loại cảm giác này … ",
  "sn36.28:1.5": "những ai rõ biết … tự mình chứng ngộ và an trú ngay trong đời này.' ",
  "sn36.28:1.6": "Thứ tám. ",
  "sn36.29:0.1": "Tương Ưng Bộ Kinh 36.29 ",
  "sn36.29:0.2": "3. Phẩm Một Trăm Lẻ Tám Pháp Môn ",
  "sn36.29:0.3": "Kinh Sa Môn Bà La Môn Thứ Ba ",
  "sn36.29:1.1": "'Này các Tỳ Kheo, những sa-môn hay bà-la-môn nào không như thật rõ biết cảm giác, không rõ biết nguồn gốc của cảm giác, không rõ biết sự diệt của cảm giác, không rõ biết con đường dẫn đến diệt cảm giác … '",
  "sn36.29:1.2": "những ai rõ biết … tự mình chứng ngộ và an trú ngay trong đời này.' ",
  "sn36.29:1.3": "Thứ chín. ",
  "sn36.30:0.1": "Tương Ưng Bộ Kinh 36.30 ",
  "sn36.30:0.2": "3. Phẩm Một Trăm Lẻ Tám Pháp Môn ",
  "sn36.30:0.3": "Kinh Đơn Thuần ",
  "sn36.30:1.1": "'Này các Tỳ Kheo, có ba loại cảm giác. '",
  "sn36.30:1.2": "Ba loại đó là gì? ",
  "sn36.30:1.3": "Cảm giác dễ chịu, cảm giác khó chịu, cảm giác không khó chịu cũng không dễ chịu",
  "sn36.30:1.4": "đây là ba loại cảm giác, này các Tỳ Kheo.' ",
  "sn36.30:1.5": "Thứ mười. ",
  "sn36.31:0.1": "Tương Ưng Bộ Kinh 36.31 ",
  "sn36.31:0.2": "3. Phẩm Một Trăm Lẻ Tám Pháp Môn ",
  "sn36.31:0.3": "Kinh Không Vật Dục ",
  "sn36.31:1.1": "'Này các Tỳ Kheo, có hỷ có vật dục, có hỷ không có vật dục, có hỷ không có vật dục còn thù thắng hơn; '",
  "sn36.31:1.2": "có lạc có vật dục, có lạc không có vật dục, có lạc không có vật dục còn thù thắng hơn; ",
  "sn36.31:1.3": "có xả có vật dục, có xả không có vật dục, có xả không có vật dục còn thù thắng hơn; ",
  "sn36.31:1.4": "có giải thoát có vật dục, có giải thoát không có vật dục, có giải thoát không có vật dục còn thù thắng hơn. ",
  "sn36.31:1.5": "Này các Tỳ Kheo, hỷ có vật dục là gì? ",
  "sn36.31:1.6": "Này các Tỳ Kheo, có năm dục công đức. ",
  "sn36.31:1.7": "Năm thứ đó là gì? ",
  "sn36.31:1.8": "Các sắc do mắt nhận thức, khả ái, dễ chịu, đáng yêu, đẹp lòng, liên hệ đến dục, hấp dẫn … ",
  "sn36.31:1.9": "các xúc do thân nhận thức, khả ái, dễ chịu, đáng yêu, đẹp lòng, liên hệ đến dục, hấp dẫn. ",
  "sn36.31:1.10": "Này các Tỳ Kheo, đây là năm dục công đức. ",
  "sn36.31:1.11": "Này các Tỳ Kheo, hỷ sanh khởi do duyên với năm dục công đức nàyđây gọi là hỷ có vật dục. ",
  "sn36.31:2.1": "Này các Tỳ Kheo, hỷ không có vật dục là gì? ",
  "sn36.31:2.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo ly dục, ly bất thiện pháp, chứng đạt và an trú sơ thiền, có tầm có tứ, với hỷ lạc do ly dục sanh. ",
  "sn36.31:2.3": "Do tầm tứ diệt, nội tâm thanh tịnh, nhất tâm, chứng đạt và an trú nhị thiền, không tầm không tứ, với hỷ lạc do định sanh. ",
  "sn36.31:2.4": "Đây gọi là hỷ không có vật dục, này các Tỳ Kheo. ",
  "sn36.31:3.1": "Này các Tỳ Kheo, hỷ không có vật dục còn thù thắng hơn là gì? ",
  "sn36.31:3.2": "Này các Tỳ Kheo, hỷ sanh khởi khi Tỳ Kheo đã đoạn tận lậu hoặc nhìn lại tâm được giải thoát khỏi tham, nhìn lại tâm được giải thoát khỏi sân, nhìn lại tâm được giải thoát khỏi siđây gọi là hỷ không có vật dục còn thù thắng hơn, này các Tỳ Kheo. ",
  "sn36.31:4.1": "Này các Tỳ Kheo, lạc có vật dục là gì? ",
  "sn36.31:4.2": "Này các Tỳ Kheo, có năm dục công đức. ",
  "sn36.31:4.3": "Năm thứ đó là gì? ",
  "sn36.31:4.4": "Các sắc do mắt nhận thức, khả ái, dễ chịu, đáng yêu, đẹp lòng, liên hệ đến dục, hấp dẫn … ",
  "sn36.31:4.5": "các xúc do thân nhận thức, khả ái, dễ chịu, đáng yêu, đẹp lòng, liên hệ đến dục, hấp dẫn. ",
  "sn36.31:4.6": "Này các Tỳ Kheo, đây là năm dục công đức. ",
  "sn36.31:4.7": "Này các Tỳ Kheo, lạc và hỷ sanh khởi do duyên với năm dục công đức nàyđây gọi là lạc có vật dục. ",
  "sn36.31:5.1": "Này các Tỳ Kheo, lạc không có vật dục là gì? ",
  "sn36.31:5.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo ly dục, ly bất thiện pháp, chứng đạt và an trú sơ thiền, có tầm có tứ, với hỷ lạc do ly dục sanh. ",
  "sn36.31:5.3": "Do tầm tứ diệt, nội tâm thanh tịnh, nhất tâm, chứng đạt và an trú nhị thiền, không tầm không tứ, với hỷ lạc do định sanh. ",
  "sn36.31:5.4": "Ly hỷ, trú xả, chánh niệm tỉnh giác, thân cảm cảm giác lạc, điều mà các bậc Thánh gọi là 'người xả, có chánh niệm, an trú trong lạc', chứng đạt và an trú tam thiền. ",
  "sn36.31:5.5": "Đây gọi là lạc không có vật dục, này các Tỳ Kheo. ",
  "sn36.31:6.1": "Này các Tỳ Kheo, lạc không có vật dục còn thù thắng hơn là gì? ",
  "sn36.31:6.2": "Này các Tỳ Kheo, lạc và hỷ sanh khởi khi Tỳ Kheo đã đoạn tận lậu hoặc nhìn lại tâm được giải thoát khỏi tham, nhìn lại tâm được giải thoát khỏi sân, nhìn lại tâm được giải thoát khỏi siđây gọi là lạc không có vật dục còn thù thắng hơn, này các Tỳ Kheo. ",
  "sn36.31:7.1": "Này các Tỳ Kheo, xả có vật dục là gì? ",
  "sn36.31:7.2": "Này các Tỳ Kheo, có năm dục công đức. ",
  "sn36.31:7.3": "Năm thứ đó là gì? ",
  "sn36.31:7.4": "Các sắc do mắt nhận thức, khả ái, dễ chịu, đáng yêu, đẹp lòng, liên hệ đến dục, hấp dẫn … ",
  "sn36.31:7.5": "các xúc do thân nhận thức, khả ái, dễ chịu, đáng yêu, đẹp lòng, liên hệ đến dục, hấp dẫn. ",
  "sn36.31:7.6": "Này các Tỳ Kheo, đây là năm dục công đức. ",
  "sn36.31:7.7": "Này các Tỳ Kheo, xả sanh khởi do duyên với năm dục công đức nàyđây gọi là xả có vật dục. ",
  "sn36.31:8.1": "Này các Tỳ Kheo, xả không có vật dục là gì? ",
  "sn36.31:8.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo xả lạc, xả khổ, diệt hỷ ưu đã có trước, chứng đạt và an trú tứ thiền, không khổ không lạc, với xả niệm thanh tịnh. ",
  "sn36.31:8.3": "Đây gọi là xả không có vật dục, này các Tỳ Kheo. ",
  "sn36.31:9.1": "Này các Tỳ Kheo, xả không có vật dục còn thù thắng hơn là gì? ",
  "sn36.31:9.2": "Này các Tỳ Kheo, xả sanh khởi khi Tỳ Kheo đã đoạn tận lậu hoặc nhìn lại tâm được giải thoát khỏi tham, nhìn lại tâm được giải thoát khỏi sân, nhìn lại tâm được giải thoát khỏi siđây gọi là xả không có vật dục còn thù thắng hơn, này các Tỳ Kheo. ",
  "sn36.31:10.1": "Này các Tỳ Kheo, giải thoát có vật dục là gì? ",
  "sn36.31:10.2": "Giải thoát gắn liền với sắc là giải thoát có vật dục. ",
  "sn36.31:11.1": "Này các Tỳ Kheo, giải thoát không có vật dục là gì? ",
  "sn36.31:11.2": "Giải thoát gắn liền với vô sắc là giải thoát không có vật dục. ",
  "sn36.31:12.1": "Này các Tỳ Kheo, giải thoát không có vật dục còn thù thắng hơn là gì? ",
  "sn36.31:12.2": "Này các Tỳ Kheo, giải thoát sanh khởi khi Tỳ Kheo đã đoạn tận lậu hoặc nhìn lại tâm được giải thoát khỏi tham, nhìn lại tâm được giải thoát khỏi sân, nhìn lại tâm được giải thoát khỏi siđây gọi là giải thoát không có vật dục còn thù thắng hơn, này các Tỳ Kheo.' ",
  "sn36.31:12.3": "Thứ mười một. ",
  "sn36.31:12.4": "Phẩm Một Trăm Lẻ Tám Pháp Môn, thứ ba. ",
  "sn36.31:13.0": "Tóm tắt phẩm này: ",
  "sn36.31:13.1": "Sīvaka, một trăm lẻ tám, Tỳ Kheo, ",
  "sn36.31:13.2": "trước kia, trí, và Tỳ Kheo; ",
  "sn36.31:13.3": "Sa-môn bà-la-môn ba bài, ",
  "sn36.31:13.4": "đơn thuần và không vật dục. ",
  "sn36.31:13.5": "Tương Ưng cảm giác viên mãn. "
}
window.BILARA["sn36_v1"]["vi"]["sn36_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
