window.BILARA = window.BILARA || {};
window.BILARA["sn3_v1"] = window.BILARA["sn3_v1"] || {};
window.BILARA["sn3_v1"]["vi"] = {
  "sn3.1:0.1": "Tương Ưng Bộ 3.1 ",
  "sn3.1:0.2": "1. Phẩm Thứ Nhất ",
  "sn3.1:0.3": "Kinh Người Trẻ Tuổi ",
  "sn3.1:1.1": "Tôi đã nghe như vầy",
  "sn3.1:1.2": "Một thời, Thế Tôn đang cư ngụ tại Xá Vệ, trong Kỳ Viên, tịnh xá của ông Cấp Cô Độc. ",
  "sn3.1:1.3": "Lúc ấy, vua Pasenadi nước Kosala đến chỗ Thế Tôn; sau khi đến, cùng với Thế Tôn hoan hỷ chào hỏi. ",
  "sn3.1:1.4": "Sau khi trao đổi những lời chào hỏi thân thiện đáng nhớ, vua ngồi xuống một bên. Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.1:1.5": "'Thưa Ngài Cồ Đàm, Ngài có tự nhận là đã chứng đắc Vô Thượng Chánh Đẳng Giác không?' ",
  "sn3.1:1.6": "'Thưa Đại vương, nếu ai có thể nói đúng thì người đó sẽ nói về Ta: 'Đã chứng đắc Vô Thượng Chánh Đẳng Giác.' '",
  "sn3.1:1.7": "Thưa Đại vương, Ta đã chứng đắc Vô Thượng Chánh Đẳng Giác.' ",
  "sn3.1:2.1": "'Thưa Ngài Cồ Đàm, những vị sa-môn, bà-la-môn có đoàn chúng, có môn đệ, là bậc thầy của đoàn nhóm, nổi tiếng, lừng danh, là vị khai tổ được nhiều người tôn kính, như: '",
  "sn3.1:2.2": "Pūraṇa Kassapa, Makkhali Gosāla, Nigaṇṭha Nāṭaputta, Sañcaya Belaṭṭhaputta, Pakudha Kaccāyana, Ajita Kesakambala; ",
  "sn3.1:2.3": "khi tôi hỏi họ có tự nhận đã chứng đắc Vô Thượng Chánh Đẳng Giác không, họ đều không tự nhận. ",
  "sn3.1:2.4": "Vậy mà Ngài Cồ Đàm vừa còn trẻ tuổi lại vừa mới xuất gia, sao lại tự nhận như vậy?' ",
  "sn3.1:3.1": "'Thưa Đại vương, có bốn hạng không nên khinh thường vì còn trẻ, không nên coi nhẹ vì còn trẻ. '",
  "sn3.1:3.2": "Bốn hạng đó là gì? ",
  "sn3.1:3.3": "Thưa Đại vương, một vị vương tử không nên khinh thường vì còn trẻ, không nên coi nhẹ vì còn trẻ. ",
  "sn3.1:3.4": "Thưa Đại vương, một con rắn không nên khinh thường vì còn nhỏ, không nên coi nhẹ vì còn nhỏ. ",
  "sn3.1:3.5": "Thưa Đại vương, một ngọn lửa không nên khinh thường vì còn nhỏ, không nên coi nhẹ vì còn nhỏ. ",
  "sn3.1:3.6": "Thưa Đại vương, một Tỳ Kheo không nên khinh thường vì còn trẻ, không nên coi nhẹ vì còn trẻ. ",
  "sn3.1:3.7": "Thưa Đại vương, đây là bốn hạng không nên khinh thường vì còn trẻ, không nên coi nhẹ vì còn trẻ.' ",
  "sn3.1:4.1": "Thế Tôn nói như vậy. ",
  "sn3.1:4.2": "Sau khi nói vậy, Thiện Thệ, bậc Đạo Sư, lại nói thêm: ",
  "sn3.1:5.1": "'Một vị vương tử sinh ra trong dòng dõi cao quý, '",
  "sn3.1:5.2": "xuất thân danh giá, lừng danh; ",
  "sn3.1:5.3": "Chớ khinh thường vì còn trẻ, ",
  "sn3.1:5.4": "người thức trí không nên khinh miệt. ",
  "sn3.1:6.1": "Vì khi lên ngôi vua, ",
  "sn3.1:6.2": "bậc vương hầu dòng Sát-đế-lỵ; ",
  "sn3.1:6.3": "Khi nổi giận, dùng hình phạt vương quyền, ",
  "sn3.1:6.4": "có thể trừng phạt nặng nề người đó; ",
  "sn3.1:6.5": "Vì vậy hãy tránh xa người đó, ",
  "sn3.1:6.6": "để bảo toàn mạng sống của mình. ",
  "sn3.1:7.1": "Ở làng mạc hay nơi rừng rú, ",
  "sn3.1:7.2": "nếu gặp con rắn đang bò; ",
  "sn3.1:7.3": "Chớ khinh thường vì còn nhỏ, ",
  "sn3.1:7.4": "người thức trí không nên khinh miệt. ",
  "sn3.1:8.1": "Với đủ màu sắc sặc sỡ, ",
  "sn3.1:8.2": "con rắn bò đầy uy lực; ",
  "sn3.1:8.3": "Có thể cắn kẻ dại khờ, ",
  "sn3.1:8.4": "cả đàn ông lẫn đàn bà; ",
  "sn3.1:8.5": "Vì vậy hãy tránh xa nó, ",
  "sn3.1:8.6": "để bảo toàn mạng sống của mình. ",
  "sn3.1:9.1": "Lửa ăn nhiều nhiên liệu, tỏa sáng rực rỡ, ",
  "sn3.1:9.2": "ngọn lửa đen bốc lên cuồn cuộn; ",
  "sn3.1:9.3": "Chớ khinh thường vì còn nhỏ, ",
  "sn3.1:9.4": "người thức trí không nên khinh miệt. ",
  "sn3.1:10.1": "Vì khi tìm được chất đốt, ",
  "sn3.1:10.2": "ngọn lửa bùng cháy to lên; ",
  "sn3.1:10.3": "Có thể thiêu đốt kẻ dại, ",
  "sn3.1:10.4": "cả đàn ông lẫn đàn bà; ",
  "sn3.1:10.5": "Vì vậy hãy tránh xa nó, ",
  "sn3.1:10.6": "để bảo toàn mạng sống của mình. ",
  "sn3.1:11.1": "Khi lửa đốt cháy khu rừng, ",
  "sn3.1:11.2": "ngọn lửa đen bốc lên; ",
  "sn3.1:11.3": "Ngày qua đêm qua rồi, ",
  "sn3.1:11.4": "cây cỏ lại đâm chồi mọc lên. ",
  "sn3.1:12.1": "Nhưng khi một Tỳ Kheo có giới hạnh, ",
  "sn3.1:12.2": "dùng ngọn lửa oai đức mà đốt cháy; ",
  "sn3.1:12.3": "Thì con cái và gia súc của kẻ đó, ",
  "sn3.1:12.4": "không thể thừa hưởng tài sản; ",
  "sn3.1:12.5": "Không con nối dõi, không người thừa kế, ",
  "sn3.1:12.6": "chúng trở nên như cây dừa bị bứng gốc. ",
  "sn3.1:13.1": "Vì vậy người trí, ",
  "sn3.1:13.2": "thấy rõ lợi ích của mình; ",
  "sn3.1:13.3": "Với rắn, với lửa, ",
  "sn3.1:13.4": "với vương tử danh tiếng; ",
  "sn3.1:13.5": "Và với Tỳ Kheo có giới hạnh, ",
  "sn3.1:13.6": "hãy cư xử đúng đắn.' ",
  "sn3.1:14.1": "Khi Thế Tôn nói vậy, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.1:14.2": "'Thật vi diệu, thưa Ngài! Thật vi diệu, thưa Ngài! '",
  "sn3.1:14.3": "Thưa Ngài, ví như người ta dựng đứng lại cái đã bị lật ngã, hay mở ra cái đã bị che kín, hay chỉ đường cho người lạc lối, hay thắp đèn dầu vào nơi tối tăm để những ai có mắt có thể thấy hình sắc; cũng vậy, Thế Tôn đã dùng nhiều phương tiện để giảng giải Giáo Pháp. ",
  "sn3.1:14.4": "Con nay xin quy y Thế Tôn, Giáo Pháp, và chúng Tỳ Kheo Tăng. ",
  "sn3.1:14.5": "Xin Thế Tôn nhận con làm đệ tử tại gia, từ nay cho đến khi mạng sống còn.",
  "sn3.2:0.1": "Tương Ưng Bộ 3.2 ",
  "sn3.2:0.2": "1. Phẩm Thứ Nhất ",
  "sn3.2:0.3": "Kinh Người Đàn Ông ",
  "sn3.2:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.2:1.2": "Lúc ấy, vua Pasenadi nước Kosala đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.2:1.3": "'Thưa Ngài, có bao nhiêu pháp khởi lên trong tâm con người, khởi lên đưa đến bất hạnh, khổ đau và sống không an lạc?' ",
  "sn3.2:2.1": "'Thưa Đại vương, có ba pháp khởi lên trong tâm con người, khởi lên đưa đến bất hạnh, khổ đau và sống không an lạc. '",
  "sn3.2:2.2": "Ba pháp đó là gì? ",
  "sn3.2:2.3": "Thưa Đại vương, lòng tham khởi lên trong tâm con người, khởi lên đưa đến bất hạnh, khổ đau và sống không an lạc. ",
  "sn3.2:2.4": "Thưa Đại vương, lòng sân khởi lên trong tâm con người, khởi lên đưa đến bất hạnh, khổ đau và sống không an lạc. ",
  "sn3.2:2.5": "Thưa Đại vương, lòng si khởi lên trong tâm con người, khởi lên đưa đến bất hạnh, khổ đau và sống không an lạc. ",
  "sn3.2:2.6": "Thưa Đại vương, đây là ba pháp khởi lên trong tâm con người, khởi lên đưa đến bất hạnh, khổ đau và sống không an lạc.' ",
  "sn3.2:2.7": "Thế Tôn nói như vậy... ",
  "sn3.2:3.1": "'Tham, sân và si, '",
  "sn3.2:3.2": "sinh ra từ trong lòng người có tâm xấu ác; ",
  "sn3.2:3.3": "Tự mình hại mình, ",
  "sn3.2:3.4": "như trái cây tự làm hỏng cây của nó.",
  "sn3.3:0.1": "Tương Ưng Bộ 3.3 ",
  "sn3.3:0.2": "1. Phẩm Thứ Nhất ",
  "sn3.3:0.3": "Kinh Già và Chết ",
  "sn3.3:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.3:1.2": "Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.3:1.3": "'Thưa Ngài, đối với những ai đã sinh ra, có cách nào thoát khỏi già và chết không?' ",
  "sn3.3:1.4": "'Thưa Đại vương, đối với những ai đã sinh ra, không có cách nào thoát khỏi già và chết. '",
  "sn3.3:1.5": "Thưa Đại vương, những vị đại phú hào dòng Sát-đế-lỵ giàu có, nhiều của cải, nhiều tài sản, nhiều vàng bạc, nhiều tiền của và lương thực; họ đã sinh ra cũng không thoát khỏi già và chết. ",
  "sn3.3:1.6": "Thưa Đại vương, những vị đại phú hào dòng bà-la-môn... ",
  "sn3.3:1.7": "những vị đại phú hào dòng cư sĩ giàu có, nhiều của cải, nhiều tài sản, nhiều vàng bạc, nhiều tiền của và lương thực; họ đã sinh ra cũng không thoát khỏi già và chết. ",
  "sn3.3:1.8": "Thưa Đại vương, những Tỳ Kheo đã thành bậc A-la-hán, đã đoạn tận các lậu hoặc, đã sống đời phạm hạnh, đã làm xong những việc cần làm, đã đặt gánh nặng xuống, đã đạt được mục đích của mình, đã đoạn tận kiết sử đưa đến tái sinh, đã được giải thoát nhờ chánh trí; thì thân xác của họ cũng mang bản chất sẽ tan rã, sẽ bị bỏ lại.' ",
  "sn3.3:1.9": "Thế Tôn nói như vậy... ",
  "sn3.3:2.1": "'Những cỗ xe lộng lẫy của vua cũng phải mục nát, '",
  "sn3.3:2.2": "Và thân xác cũng phải chịu già; ",
  "sn3.3:2.3": "Nhưng Pháp của bậc thiện nhân không bao giờ già, ",
  "sn3.3:2.4": "Bậc thiện nhân truyền dạy cho nhau như vậy.",
  "sn3.4:0.1": "Tương Ưng Bộ 3.4 ",
  "sn3.4:0.2": "1. Phẩm Thứ Nhất ",
  "sn3.4:0.3": "Kinh Người Thân Yêu ",
  "sn3.4:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.4:1.2": "Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.4:1.3": "'Thưa Ngài, khi tôi đang ngồi một mình, yên tĩnh, suy nghĩ trong lòng khởi lên như vầy: '",
  "sn3.4:1.4": "'Những ai coi bản thân là người thân yêu? Những ai coi bản thân là người không thân yêu?' ",
  "sn3.4:1.5": "Thưa Ngài, tôi nghĩ như vầy: ",
  "sn3.4:1.6": "'Những ai làm điều xấu ác bằng thân, bằng lời nói, bằng tâm ý; '",
  "sn3.4:1.7": "thì họ coi bản thân là người không thân yêu. ",
  "sn3.4:1.8": "Dù họ có nói: ",
  "sn3.4:1.9": "'Bản thân ta là người ta yêu thương,' nhưng thực ra họ đang coi bản thân là người không thân yêu.' '",
  "sn3.4:1.10": "Vì sao vậy? ",
  "sn3.4:1.11": "Vì những gì kẻ thù làm cho kẻ thù, thì họ tự làm điều đó cho chính bản thân mình; ",
  "sn3.4:1.12": "vì vậy họ coi bản thân là người không thân yêu. ",
  "sn3.4:1.13": "Còn những ai làm điều thiện lành bằng thân, bằng lời nói, bằng tâm ý; ",
  "sn3.4:1.14": "thì họ coi bản thân là người thân yêu. ",
  "sn3.4:1.15": "Dù họ có nói: ",
  "sn3.4:1.16": "'Bản thân ta là người ta không yêu thương,' nhưng thực ra họ đang coi bản thân là người thân yêu. ",
  "sn3.4:1.17": "Vì sao vậy? ",
  "sn3.4:1.18": "Vì những gì người thân yêu làm cho người thân yêu, thì họ tự làm điều đó cho chính bản thân mình; ",
  "sn3.4:1.19": "vì vậy họ coi bản thân là người thân yêu.' ",
  "sn3.4:2.1": "'Đúng vậy, thưa Đại vương! Đúng vậy, thưa Đại vương! '",
  "sn3.4:2.2": "Thưa Đại vương, những ai làm điều xấu ác bằng thân, bằng lời nói, bằng tâm ý; ",
  "sn3.4:2.3": "thì họ coi bản thân là người không thân yêu. ",
  "sn3.4:2.4": "Dù họ có nói: ",
  "sn3.4:2.5": "'Bản thân ta là người ta yêu thương,' nhưng thực ra họ đang coi bản thân là người không thân yêu. ",
  "sn3.4:2.6": "Vì sao vậy? ",
  "sn3.4:2.7": "Thưa Đại vương, vì những gì kẻ thù làm cho kẻ thù, thì họ tự làm điều đó cho chính bản thân mình; ",
  "sn3.4:2.8": "vì vậy họ coi bản thân là người không thân yêu. ",
  "sn3.4:2.9": "Còn những ai làm điều thiện lành bằng thân, bằng lời nói, bằng tâm ý; ",
  "sn3.4:2.10": "thì họ coi bản thân là người thân yêu. ",
  "sn3.4:2.11": "Dù họ có nói: ",
  "sn3.4:2.12": "'Bản thân ta là người ta không yêu thương;' ",
  "sn3.4:2.13": "nhưng thực ra họ đang coi bản thân là người thân yêu. ",
  "sn3.4:2.14": "Vì sao vậy? ",
  "sn3.4:2.15": "Thưa Đại vương, vì những gì người thân yêu làm cho người thân yêu, thì họ tự làm điều đó cho chính bản thân mình; ",
  "sn3.4:2.16": "vì vậy họ coi bản thân là người thân yêu.' ",
  "sn3.4:2.17": "Thế Tôn nói như vậy... ",
  "sn3.4:3.1": "'Nếu ai biết yêu thương bản thân mình, '",
  "sn3.4:3.2": "thì đừng để mình vướng vào điều ác; ",
  "sn3.4:3.3": "Vì hạnh phúc không dễ tìm được, ",
  "sn3.4:3.4": "đối với người làm điều xấu. ",
  "sn3.4:4.1": "Khi thần chết đã đến, ",
  "sn3.4:4.2": "lúc phải bỏ lại kiếp người; ",
  "sn3.4:4.3": "Thì của cải gì là của mình? ",
  "sn3.4:4.4": "Cái gì người đó mang theo được? ",
  "sn3.4:4.5": "Cái gì theo sau người đó, ",
  "sn3.4:4.6": "như bóng không rời hình? ",
  "sn3.4:5.1": "Cả phước và tội, ",
  "sn3.4:5.2": "mà người phàm làm ở đây; ",
  "sn3.4:5.3": "Đó là của người đó thực sự, ",
  "sn3.4:5.4": "đó là cái người đó mang theo; ",
  "sn3.4:5.5": "Đó là cái theo sau người đó, ",
  "sn3.4:5.6": "như bóng không rời hình. ",
  "sn3.4:6.1": "Vì vậy hãy làm điều thiện, ",
  "sn3.4:6.2": "tích lũy cho đời sau; ",
  "sn3.4:6.3": "Công đức ở thế giới bên kia, ",
  "sn3.4:6.4": "là chỗ nương tựa cho chúng sinh.",
  "sn3.5:0.1": "Tương Ưng Bộ 3.5 ",
  "sn3.5:0.2": "1. Phẩm Thứ Nhất ",
  "sn3.5:0.3": "Kinh Tự Bảo Vệ ",
  "sn3.5:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.5:1.2": "Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.5:1.3": "'Thưa Ngài, khi tôi đang ngồi một mình, yên tĩnh, suy nghĩ trong lòng khởi lên như vầy: '",
  "sn3.5:1.4": "'Những ai bảo vệ được bản thân mình? Những ai không bảo vệ được bản thân mình?' ",
  "sn3.5:1.5": "Thưa Ngài, tôi nghĩ như vầy: ",
  "sn3.5:1.6": "'Những ai làm điều xấu ác bằng thân, bằng lời nói, bằng tâm ý; '",
  "sn3.5:1.7": "thì họ không bảo vệ được bản thân mình. ",
  "sn3.5:1.8": "Dù cho họ có được đội voi hộ vệ, đội ngựa hộ vệ, đội xe hộ vệ, đội bộ binh hộ vệ; ",
  "sn3.5:1.9": "thì họ cũng không bảo vệ được bản thân mình. ",
  "sn3.5:1.10": "Vì sao vậy? ",
  "sn3.5:1.11": "Vì đó là sự bảo vệ bên ngoài, không phải sự bảo vệ bên trong; ",
  "sn3.5:1.12": "vì vậy họ không bảo vệ được bản thân mình. ",
  "sn3.5:1.13": "Còn những ai làm điều thiện lành bằng thân, bằng lời nói, bằng tâm ý; ",
  "sn3.5:1.14": "thì họ bảo vệ được bản thân mình. ",
  "sn3.5:1.15": "Dù cho họ không có đội voi hộ vệ, không có đội ngựa hộ vệ, không có đội xe hộ vệ, không có đội bộ binh hộ vệ; ",
  "sn3.5:1.16": "thì họ vẫn bảo vệ được bản thân mình. ",
  "sn3.5:1.17": "Vì sao vậy? ",
  "sn3.5:1.18": "Vì đó là sự bảo vệ bên trong, không phải sự bảo vệ bên ngoài; ",
  "sn3.5:1.19": "vì vậy họ bảo vệ được bản thân mình.'' ",
  "sn3.5:2.1": "'Đúng vậy, thưa Đại vương! Đúng vậy, thưa Đại vương! '",
  "sn3.5:2.2": "Thưa Đại vương, những ai làm điều xấu ác bằng thân... ",
  "sn3.5:2.3": "thì họ không bảo vệ được bản thân mình. ",
  "sn3.5:2.4": "Vì sao vậy? ",
  "sn3.5:2.5": "Thưa Đại vương, vì đó là sự bảo vệ bên ngoài, không phải sự bảo vệ bên trong; ",
  "sn3.5:2.6": "vì vậy họ không bảo vệ được bản thân mình. ",
  "sn3.5:2.7": "Thưa Đại vương, còn những ai làm điều thiện lành bằng thân, bằng lời nói, bằng tâm ý; ",
  "sn3.5:2.8": "thì họ bảo vệ được bản thân mình. ",
  "sn3.5:2.9": "Dù cho họ không có đội voi hộ vệ, không có đội ngựa hộ vệ, không có đội xe hộ vệ, không có đội bộ binh hộ vệ; ",
  "sn3.5:2.10": "thì họ vẫn bảo vệ được bản thân mình. ",
  "sn3.5:2.11": "Vì sao vậy? ",
  "sn3.5:2.12": "Thưa Đại vương, vì đó là sự bảo vệ bên trong, không phải sự bảo vệ bên ngoài; ",
  "sn3.5:2.13": "vì vậy họ bảo vệ được bản thân mình.' ",
  "sn3.5:2.14": "Thế Tôn nói như vậy... ",
  "sn3.5:3.1": "'Thu thúc nơi thân là tốt, '",
  "sn3.5:3.2": "thu thúc nơi lời nói là tốt; ",
  "sn3.5:3.3": "Thu thúc nơi tâm ý là tốt, ",
  "sn3.5:3.4": "thu thúc khắp nơi là tốt; ",
  "sn3.5:3.5": "Ai thu thúc khắp nơi, biết hổ thẹn, ",
  "sn3.5:3.6": "người đó được gọi là người bảo vệ được bản thân.",
  "sn3.6:0.1": "Tương Ưng Bộ 3.6 ",
  "sn3.6:0.2": "1. Phẩm Thứ Nhất ",
  "sn3.6:0.3": "Kinh Số Ít ",
  "sn3.6:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.6:1.2": "Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.6:1.3": "'Thưa Ngài, khi tôi đang ngồi một mình, yên tĩnh, suy nghĩ trong lòng khởi lên như vầy: '",
  "sn3.6:1.4": "'Thật ít ỏi thay những chúng sinh trên đời, khi được hưởng của cải sung túc lớn lao, mà không sa đà, không phóng túng, không rơi vào tham đắm dục lạc, không đối xử tệ với người khác. '",
  "sn3.6:1.5": "Mà thật nhiều những chúng sinh trên đời, khi được hưởng của cải sung túc lớn lao, lại sa đà, phóng túng, rơi vào tham đắm dục lạc, đối xử tệ với người khác.'' ",
  "sn3.6:2.1": "'Đúng vậy, thưa Đại vương! Đúng vậy, thưa Đại vương! '",
  "sn3.6:2.2": "Thưa Đại vương, thật ít ỏi những chúng sinh trên đời, khi được hưởng của cải sung túc lớn lao, mà không sa đà, không phóng túng, không rơi vào tham đắm dục lạc, không đối xử tệ với người khác. ",
  "sn3.6:2.3": "Mà thật nhiều những chúng sinh trên đời, khi được hưởng của cải sung túc lớn lao, lại sa đà, phóng túng, rơi vào tham đắm dục lạc, đối xử tệ với người khác.' ",
  "sn3.6:2.4": "Thế Tôn nói như vậy... ",
  "sn3.6:3.1": "'Những ai say đắm trong dục lạc, '",
  "sn3.6:3.2": "tham lam, mê đắm trong dục lạc; ",
  "sn3.6:3.3": "Không nhận ra khi đã đi quá đà, ",
  "sn3.6:3.4": "như con nai sa vào bẫy; ",
  "sn3.6:3.5": "Về sau phải chịu đắng cay, ",
  "sn3.6:3.6": "quả báo xấu ác đến với họ.",
  "sn3.7:0.1": "Tương Ưng Bộ 3.7 ",
  "sn3.7:0.2": "1. Phẩm Thứ Nhất ",
  "sn3.7:0.3": "Kinh Phòng Xử Án ",
  "sn3.7:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.7:1.2": "Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.7:1.3": "'Thưa Ngài, khi tôi đang ngồi xử án, tôi thấy những đại phú hào dòng Sát-đế-lỵ, những đại phú hào dòng bà-la-môn, những đại phú hào dòng cư sĩ, giàu có, nhiều tiền của, nhiều tài sản, nhiều vàng bạc; vì lợi dục mà cố tình nói dối. '",
  "sn3.7:1.4": "Thưa Ngài, tôi nghĩ như vầy: ",
  "sn3.7:1.5": "'Thôi, ta không muốn ngồi xử án nữa. Từ nay trở đi chỉ có người khác mới ngồi xử án.'' '",
  "sn3.7:2.1": "'Đúng vậy, thưa Đại vương! Đúng vậy, thưa Đại vương! '",
  "sn3.7:2.2": "Thưa Đại vương, những đại phú hào dòng Sát-đế-lỵ, những đại phú hào dòng bà-la-môn, những đại phú hào dòng cư sĩ, giàu có, nhiều tiền của, nhiều tài sản, nhiều vàng bạc; vì lợi dục mà cố tình nói dối; ",
  "sn3.7:2.3": "điều đó sẽ mang lại cho họ bất hạnh và khổ đau lâu dài.' ",
  "sn3.7:2.4": "Thế Tôn nói như vậy... ",
  "sn3.7:3.1": "'Những ai say đắm trong dục lạc, '",
  "sn3.7:3.2": "tham lam, mê đắm trong dục lạc; ",
  "sn3.7:3.3": "Không nhận ra khi đã đi quá đà, ",
  "sn3.7:3.4": "như con cá mắc vào lưới; ",
  "sn3.7:3.5": "Về sau phải chịu đắng cay, ",
  "sn3.7:3.6": "quả báo xấu ác đến với họ.",
  "sn3.8:0.1": "Tương Ưng Bộ 3.8 ",
  "sn3.8:0.2": "1. Phẩm Thứ Nhất ",
  "sn3.8:0.3": "Kinh Mallikā ",
  "sn3.8:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.8:1.2": "Lúc ấy, vua Pasenadi nước Kosala đang ở trên lầu thượng với hoàng hậu Mallikā. ",
  "sn3.8:1.3": "Lúc ấy, vua Pasenadi nước Kosala nói với hoàng hậu Mallikā: ",
  "sn3.8:1.4": "'Này Mallikā, có ai mà nàng yêu thương hơn bản thân mình không?' ",
  "sn3.8:1.5": "'Thưa Đại vương, không có ai mà thiếp yêu thương hơn bản thân mình. '",
  "sn3.8:1.6": "Còn Đại vương, có ai mà ngài yêu thương hơn bản thân mình không?' ",
  "sn3.8:1.7": "'Này Mallikā, cũng không có ai mà ta yêu thương hơn bản thân ta.' ",
  "sn3.8:2.1": "Lúc ấy, vua Pasenadi nước Kosala xuống khỏi lầu thượng, đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.8:2.2": "'Thưa Ngài, khi tôi đang ở trên lầu thượng với hoàng hậu Mallikā, tôi có hỏi nàng: '",
  "sn3.8:2.3": "'Này Mallikā, có ai mà nàng yêu thương hơn bản thân mình không?' ",
  "sn3.8:2.4": "Thưa Ngài, khi được hỏi vậy, hoàng hậu Mallikā trả lời tôi: ",
  "sn3.8:2.5": "'Thưa Đại vương, không có ai mà thiếp yêu thương hơn bản thân mình. '",
  "sn3.8:2.6": "Còn Đại vương, có ai mà ngài yêu thương hơn bản thân mình không?' ",
  "sn3.8:2.7": "Thưa Ngài, khi được hỏi vậy, tôi trả lời hoàng hậu Mallikā: ",
  "sn3.8:2.8": "'Này Mallikā, cũng không có ai mà ta yêu thương hơn bản thân ta.'' '",
  "sn3.8:3.1": "Lúc ấy, Thế Tôn hiểu rõ ý nghĩa này, liền đọc bài kệ: ",
  "sn3.8:4.1": "'Dù tâm tư đi khắp mọi phương, '",
  "sn3.8:4.2": "Cũng chẳng tìm được ai thân yêu hơn bản thân mình; ",
  "sn3.8:4.3": "Bản thân mình là người thân yêu nhất đối với mọi người, ",
  "sn3.8:4.4": "Vì vậy ai muốn tự yêu mình thì đừng làm hại người khác.",
  "sn3.9:0.1": "Tương Ưng Bộ 3.9 ",
  "sn3.9:0.2": "1. Phẩm Thứ Nhất ",
  "sn3.9:0.3": "Kinh Tế Lễ ",
  "sn3.9:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.9:1.2": "Lúc ấy, vua Pasenadi nước Kosala đang chuẩn bị một buổi tế lễ lớn. Năm trăm con bò đực, năm trăm con bê đực, năm trăm con bê cái, năm trăm con dê, năm trăm con cừu đã được dắt đến cột vào trụ, sẵn sàng cho cuộc tế lễ. ",
  "sn3.9:1.3": "Những nô lệ, người làm thuê và nhân công của nhà vua, vì sợ bị đánh đòn, vì sợ hãi, mặt đầm đìa nước mắt, vừa khóc vừa làm công việc chuẩn bị. ",
  "sn3.9:2.1": "Lúc ấy, nhiều Tỳ Kheo vào buổi sáng sớm, đắp y, cầm bát đi vào thành Xá Vệ để khất thực. ",
  "sn3.9:2.2": "Sau khi đi khất thực trong thành Xá Vệ xong, trên đường trở về sau bữa ăn, các Tỳ Kheo đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi một bên, các Tỳ Kheo bạch Thế Tôn: ",
  "sn3.9:2.3": "'Thưa Ngài, lúc này vua Pasenadi nước Kosala đang chuẩn bị một buổi tế lễ lớn. Năm trăm con bò đực, năm trăm con bê đực, năm trăm con bê cái, năm trăm con dê, năm trăm con cừu đã được dắt đến cột vào trụ, sẵn sàng cho cuộc tế lễ. '",
  "sn3.9:2.4": "Những nô lệ, người làm thuê và nhân công của nhà vua, vì sợ bị đánh đòn, vì sợ hãi, mặt đầm đìa nước mắt, vừa khóc vừa làm công việc chuẩn bị.' ",
  "sn3.9:3.1": "Lúc ấy, Thế Tôn hiểu rõ ý nghĩa này, liền đọc những bài kệ: ",
  "sn3.9:4.1": "'Lễ tế ngựa, lễ tế người, '",
  "sn3.9:4.2": "lễ tế sammapassā, lễ vājapeyya; ",
  "sn3.9:4.3": "Những lễ lớn không có rào cản, ",
  "sn3.9:4.4": "những lễ ấy không mang lại quả lớn. ",
  "sn3.9:5.1": "Những cuộc tế lễ có giết hại dê, cừu, bò, ",
  "sn3.9:5.2": "và nhiều loại thú vật khác nhau; ",
  "sn3.9:5.3": "Những cuộc tế lễ như vậy không đúng cách, ",
  "sn3.9:5.4": "các bậc đại nhân không đến dự. ",
  "sn3.9:6.1": "Những cuộc tế lễ không có sát sanh, ",
  "sn3.9:6.2": "tế lễ thường xuyên theo đúng phong tục; ",
  "sn3.9:6.3": "Không giết hại dê, cừu, bò, ",
  "sn3.9:6.4": "không có nhiều loài vật bị giết hại; ",
  "sn3.9:6.5": "Những cuộc tế lễ như vậy là đúng cách, ",
  "sn3.9:6.6": "các bậc đại nhân đến dự. ",
  "sn3.9:7.1": "Người trí hãy cúng dường như vậy, ",
  "sn3.9:7.2": "đây là loại tế lễ mang quả lớn; ",
  "sn3.9:7.3": "Tế lễ như vậy mang lại lợi ích cho người cúng dường, ",
  "sn3.9:7.4": "tốt hơn chứ không xấu hơn; ",
  "sn3.9:7.5": "Cuộc tế lễ thật phong phú dồi dào, ",
  "sn3.9:7.6": "chư thiên cũng hoan hỷ.",
  "sn3.10:0.1": "Tương Ưng Bộ 3.10 ",
  "sn3.10:0.2": "1. Phẩm Thứ Nhất ",
  "sn3.10:0.3": "Kinh Trói Buộc ",
  "sn3.10:1.1": "Lúc ấy, vua Pasenadi nước Kosala đã cho bắt và giam cầm một nhóm người đông đảo, người thì bị trói bằng dây thừng, người thì bị trói bằng xiềng xích, người thì bị trói bằng dây sắt. ",
  "sn3.10:2.1": "Lúc ấy, nhiều Tỳ Kheo vào buổi sáng sớm, đắp y, cầm bát đi vào thành Xá Vệ để khất thực. ",
  "sn3.10:2.2": "Sau khi đi khất thực trong thành Xá Vệ xong, trên đường trở về sau bữa ăn, các Tỳ Kheo đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi một bên, các Tỳ Kheo bạch Thế Tôn: ",
  "sn3.10:2.3": "'Thưa Ngài, vua Pasenadi nước Kosala đã cho bắt và giam cầm một nhóm người đông đảo, người thì bị trói bằng dây thừng, người thì bị trói bằng xiềng xích, người thì bị trói bằng dây sắt.' ",
  "sn3.10:3.1": "Lúc ấy, Thế Tôn hiểu rõ ý nghĩa này, liền đọc những bài kệ: ",
  "sn3.10:4.1": "'Bậc trí không gọi là xiềng xích bền chắc, '",
  "sn3.10:4.2": "những xiềng xích làm bằng sắt, bằng gỗ hay bằng cỏ tranh; ",
  "sn3.10:4.3": "Mà chính sự say mê đối với châu ngọc và vòng tay, ",
  "sn3.10:4.4": "và sự luyến ái con cái và vợ chồng. ",
  "sn3.10:5.1": "Bậc trí mới gọi đó là xiềng xích bền chắc, ",
  "sn3.10:5.2": "kéo xuống, lỏng lẻo, khó tháo gỡ; ",
  "sn3.10:5.3": "Sau khi cắt đứt xiềng xích này, họ xuất gia, ",
  "sn3.10:5.4": "không còn luyến tiếc, từ bỏ dục lạc mà ra đi.",
  "sn3.10:5.5": "Phẩm Thứ Nhất. ",
  "sn3.10:6.0": "Tóm tắt phẩm: ",
  "sn3.10:6.1": "Người trẻ tuổi, người đàn ông, già và chết, ",
  "sn3.10:6.2": "người thân yêu, tự bảo vệ; ",
  "sn3.10:6.3": "Số ít, phòng xử án, ",
  "sn3.10:6.4": "Mallikā, tế lễ, trói buộc.",
  "sn3.11:0.1": "Tương Ưng Bộ 3.11 ",
  "sn3.11:0.2": "2. Phẩm Thứ Hai ",
  "sn3.11:0.3": "Kinh Bảy Người Bện Tóc ",
  "sn3.11:1.1": "Một thời, Thế Tôn đang cư ngụ tại Xá Vệ, trong Đông Viên, tại lầu cao của bà Migāramātā. ",
  "sn3.11:1.2": "Lúc ấy, Thế Tôn vào buổi chiều, sau khi xả thiền, đang ngồi ở ngoài cổng. ",
  "sn3.11:1.3": "Lúc ấy, vua Pasenadi nước Kosala đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. ",
  "sn3.11:2.1": "Lúc ấy, bảy người bện tóc, bảy người Ni-kiền-tử, bảy người khổ hạnh trần truồng, bảy người mặc một tấm vải, bảy người du hành, tóc và râu dài lòa xòa, mang các vật dụng khác nhau, đang đi ngang qua không xa Thế Tôn. ",
  "sn3.11:2.2": "Lúc ấy, vua Pasenadi nước Kosala đứng dậy, vắt y lên một vai, quỳ gối phải xuống đất, chắp tay hướng về những bảy người bện tóc, bảy người Ni-kiền-tử, bảy người khổ hạnh trần truồng, bảy người mặc một tấm vải, bảy người du hành đó, ba lần xưng danh: ",
  "sn3.11:2.3": "'Thưa các Ngài, tôi là vua Pasenadi nước Kosala... '",
  "sn3.11:2.4": "Tôi là vua Pasenadi nước Kosala.' ",
  "sn3.11:3.1": "Sau khi những bảy người bện tóc, bảy người Ni-kiền-tử, bảy người khổ hạnh trần truồng, bảy người mặc một tấm vải, bảy người du hành đó vừa đi khỏi không lâu, vua Pasenadi nước Kosala đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.11:3.2": "'Thưa Ngài, những vị đó có phải là bậc A-la-hán hay đang trên đường chứng đắc A-la-hán trong đời này không?' ",
  "sn3.11:4.1": "'Thưa Đại vương, thật khó để Đại vương biết được điều đó, vì Đại vương là người cư sĩ, đang hưởng dục lạc, sống trong gia đình đông đúc con cái, đang sử dụng vải Kāsi chiên đàn, đang đeo tràng hoa, hương liệu và dầu thơm, đang nhận vàng bạc: 'Đây là bậc A-la-hán, hay đây là người đang trên đường chứng đắc A-la-hán.' '",
  "sn3.11:5.1": "Thưa Đại vương, giới hạnh của người ta phải được biết qua sự chung sống lâu dài, không phải qua thời gian ngắn; và phải có sự chú tâm quan sát, không phải qua sự bất cẩn; và phải bằng trí tuệ, không phải bằng kẻ thiếu trí. ",
  "sn3.11:5.2": "Thưa Đại vương, sự thanh tịnh của người ta phải được biết qua sự giao tiếp lâu dài, không phải qua thời gian ngắn; và phải có sự chú tâm quan sát, không phải qua sự bất cẩn; và phải bằng trí tuệ, không phải bằng kẻ thiếu trí. ",
  "sn3.11:5.3": "Thưa Đại vương, sức mạnh của người ta trong lúc gặp nghịch cảnh phải được biết qua thời gian lâu dài, không phải qua thời gian ngắn; và phải có sự chú tâm quan sát, không phải qua sự bất cẩn; và phải bằng trí tuệ, không phải bằng kẻ thiếu trí. ",
  "sn3.11:5.4": "Thưa Đại vương, trí tuệ của người ta phải được biết qua cuộc đàm thoại lâu dài, không phải qua thời gian ngắn; và phải có sự chú tâm quan sát, không phải qua sự bất cẩn; và phải bằng trí tuệ, không phải bằng kẻ thiếu trí.' ",
  "sn3.11:6.1": "'Thật kỳ diệu, thưa Ngài! Thật phi thường, thưa Ngài! '",
  "sn3.11:6.2": "Thật là khéo nói, thưa Ngài, khi Thế Tôn nói: ",
  "sn3.11:6.3": "'Thật khó để Đại vương biết được điều đó, vì Đại vương là người cư sĩ, đang hưởng dục lạc, sống trong gia đình đông đúc con cái, đang sử dụng vải Kāsi chiên đàn, đang đeo tràng hoa, hương liệu và dầu thơm, đang nhận vàng bạc: '",
  "sn3.11:6.4": "'Đây là bậc A-la-hán, hay đây là người đang trên đường chứng đắc A-la-hán.' ",
  "sn3.11:6.5": "Thưa Đại vương, giới hạnh của người ta phải được biết qua sự chung sống lâu dài, không phải qua thời gian ngắn; và phải có sự chú tâm quan sát, không phải qua sự bất cẩn; và phải bằng trí tuệ, không phải bằng kẻ thiếu trí. ",
  "sn3.11:6.6": "Thưa Đại vương, sự thanh tịnh của người ta phải được biết qua sự giao tiếp lâu dài, không phải qua thời gian ngắn; và phải có sự chú tâm quan sát, không phải qua sự bất cẩn; và phải bằng trí tuệ, không phải bằng kẻ thiếu trí. ",
  "sn3.11:6.7": "Thưa Đại vương, sức mạnh của người ta trong lúc gặp nghịch cảnh phải được biết qua thời gian lâu dài, không phải qua thời gian ngắn; và phải có sự chú tâm quan sát, không phải qua sự bất cẩn; và phải bằng trí tuệ, không phải bằng kẻ thiếu trí. ",
  "sn3.11:6.8": "Thưa Đại vương, trí tuệ của người ta phải được biết qua cuộc đàm thoại lâu dài, không phải qua thời gian ngắn; và phải có sự chú tâm quan sát, không phải qua sự bất cẩn; và phải bằng trí tuệ, không phải bằng kẻ thiếu trí.' ",
  "sn3.11:7.1": "Thưa Ngài, những người đó là mật thám của tôi, đã đi thám thính khắp đất nước và vừa trở về. ",
  "sn3.11:7.2": "Trước tiên họ báo cáo, sau đó tôi sẽ xem xét lại. ",
  "sn3.11:7.3": "Thưa Ngài, bây giờ họ sẽ tắm rửa sạch sẽ, xức dầu thơm, cắt tỉa râu tóc, mặc y phục trắng, và sẽ hưởng thụ năm dục lạc.' ",
  "sn3.11:8.1": "Lúc ấy, Thế Tôn hiểu rõ ý nghĩa này, liền đọc những bài kệ: ",
  "sn3.11:9.1": "'Không thể biết người tốt qua vẻ bề ngoài, '",
  "sn3.11:9.2": "không nên tin ngay qua lần thấy đầu tiên; ",
  "sn3.11:9.3": "Vì những kẻ không thu thúc, ẩn mình bên dưới vẻ ngoài thu thúc, ",
  "sn3.11:9.4": "vẫn đang lang thang trong đời này. ",
  "sn3.11:10.1": "Như chiếc vòng tai giả làm bằng đất sét, ",
  "sn3.11:10.2": "hay đồng tiền nửa xu bọc vàng; ",
  "sn3.11:10.3": "Họ lang thang trên đời với vẻ ngoài che đậy, ",
  "sn3.11:10.4": "bên trong ô uế nhưng bên ngoài sáng bóng.",
  "sn3.12:0.1": "Tương Ưng Bộ 3.12 ",
  "sn3.12:0.2": "2. Phẩm Thứ Hai ",
  "sn3.12:0.3": "Kinh Năm Vị Vua ",
  "sn3.12:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.12:1.2": "Lúc ấy, năm vị vua do vua Pasenadi đứng đầu, đang cùng nhau hưởng thụ năm dục lạc. Trong lúc đó, cuộc bàn luận sau đây khởi lên giữa họ: ",
  "sn3.12:1.3": "'Điều gì là tuyệt vời nhất trong dục lạc?' ",
  "sn3.12:1.4": "Có người nói: ",
  "sn3.12:1.5": "'Hình sắc là tuyệt vời nhất trong dục lạc.' ",
  "sn3.12:1.6": "Có người nói: ",
  "sn3.12:1.7": "'Âm thanh là tuyệt vời nhất trong dục lạc.' ",
  "sn3.12:1.8": "Có người nói: ",
  "sn3.12:1.9": "'Mùi hương là tuyệt vời nhất trong dục lạc.' ",
  "sn3.12:1.10": "Có người nói: ",
  "sn3.12:1.11": "'Vị nếm là tuyệt vời nhất trong dục lạc.' ",
  "sn3.12:1.12": "Có người nói: ",
  "sn3.12:1.13": "'Xúc chạm là tuyệt vời nhất trong dục lạc.' ",
  "sn3.12:1.14": "Nhưng họ không thể thuyết phục nhau đồng ý. ",
  "sn3.12:2.1": "Lúc ấy, vua Pasenadi nước Kosala nói với các vị vua đó: ",
  "sn3.12:2.2": "'Thưa các vị, hãy đến, chúng ta đến gặp Thế Tôn; sau khi đến, hãy hỏi Thế Tôn về điều này. '",
  "sn3.12:2.3": "Thế Tôn trả lời thế nào, chúng ta sẽ ghi nhớ như vậy.' ",
  "sn3.12:2.4": "'Vâng, thưa Đại vương,' các vị vua đó đồng ý với vua Pasenadi nước Kosala. ",
  "sn3.12:3.1": "Lúc ấy, năm vị vua do vua Pasenadi đứng đầu đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.12:3.2": "'Thưa Ngài, chúng tôi năm vua đang cùng nhau hưởng thụ năm dục lạc, thì cuộc bàn luận này khởi lên: '",
  "sn3.12:3.3": "'Điều gì là tuyệt vời nhất trong dục lạc?' ",
  "sn3.12:3.4": "Có người nói: ",
  "sn3.12:3.5": "'Hình sắc là tuyệt vời nhất trong dục lạc.' ",
  "sn3.12:3.6": "Có người nói: ",
  "sn3.12:3.7": "'Âm thanh là tuyệt vời nhất trong dục lạc.' ",
  "sn3.12:3.8": "Có người nói: ",
  "sn3.12:3.9": "'Mùi hương là tuyệt vời nhất trong dục lạc.' ",
  "sn3.12:3.10": "Có người nói: ",
  "sn3.12:3.11": "'Vị nếm là tuyệt vời nhất trong dục lạc.' ",
  "sn3.12:3.12": "Có người nói: ",
  "sn3.12:3.13": "'Xúc chạm là tuyệt vời nhất trong dục lạc.' ",
  "sn3.12:3.14": "Thưa Ngài, điều gì là tuyệt vời nhất trong dục lạc?' ",
  "sn3.12:4.1": "'Thưa Đại vương, Ta nói điều tuyệt vời nhất trong năm dục lạc là cái gì vừa lòng nhất. '",
  "sn3.12:4.2": "Thưa Đại vương, chính những hình sắc đó có thể làm vừa lòng người này, nhưng lại làm không vừa lòng người khác. ",
  "sn3.12:4.3": "Và khi người nào được thỏa mãn, được như ý với những hình sắc đó, người đó không ao ước hình sắc nào khác cao hơn hay tốt hơn. ",
  "sn3.12:4.4": "Những hình sắc đó là tuyệt vời nhất đối với người đó. ",
  "sn3.12:4.5": "Những hình sắc đó là vô thượng đối với người đó. ",
  "sn3.12:5.1": "Thưa Đại vương, chính những âm thanh đó có thể làm vừa lòng người này, nhưng lại làm không vừa lòng người khác. ",
  "sn3.12:5.2": "Và khi người nào được thỏa mãn, được như ý với những âm thanh đó, người đó không ao ước âm thanh nào khác cao hơn hay tốt hơn. ",
  "sn3.12:5.3": "Những âm thanh đó là tuyệt vời nhất đối với người đó. ",
  "sn3.12:5.4": "Những âm thanh đó là vô thượng đối với người đó. ",
  "sn3.12:6.1": "Thưa Đại vương, chính những mùi hương đó có thể làm vừa lòng người này, nhưng lại làm không vừa lòng người khác. ",
  "sn3.12:6.2": "Và khi người nào được thỏa mãn, được như ý với những mùi hương đó, người đó không ao ước mùi hương nào khác cao hơn hay tốt hơn. ",
  "sn3.12:6.3": "Những mùi hương đó là tuyệt vời nhất đối với người đó. ",
  "sn3.12:6.4": "Những mùi hương đó là vô thượng đối với người đó. ",
  "sn3.12:7.1": "Thưa Đại vương, chính những vị nếm đó có thể làm vừa lòng người này, nhưng lại làm không vừa lòng người khác. ",
  "sn3.12:7.2": "Và khi người nào được thỏa mãn, được như ý với những vị nếm đó, người đó không ao ước vị nếm nào khác cao hơn hay tốt hơn. ",
  "sn3.12:7.3": "Những vị nếm đó là tuyệt vời nhất đối với người đó. ",
  "sn3.12:7.4": "Những vị nếm đó là vô thượng đối với người đó. ",
  "sn3.12:8.1": "Thưa Đại vương, chính những xúc chạm đó có thể làm vừa lòng người này, nhưng lại làm không vừa lòng người khác. ",
  "sn3.12:8.2": "Và khi người nào được thỏa mãn, được như ý với những xúc chạm đó, người đó không ao ước xúc chạm nào khác cao hơn hay tốt hơn. ",
  "sn3.12:8.3": "Những xúc chạm đó là tuyệt vời nhất đối với người đó. ",
  "sn3.12:8.4": "Những xúc chạm đó là vô thượng đối với người đó.' ",
  "sn3.12:9.1": "Lúc ấy, có cư sĩ Candanaṅgalika đang ngồi trong hội chúng đó. ",
  "sn3.12:9.2": "Lúc ấy, cư sĩ Candanaṅgalika đứng dậy, vắt y lên một vai, chắp tay hướng về Thế Tôn, bạch Thế Tôn: ",
  "sn3.12:9.3": "'Thưa Thế Tôn, con có cảm hứng muốn nói! Thưa Thiện Thệ, con có cảm hứng muốn nói!' ",
  "sn3.12:9.4": "'Hãy nói đi, Candanaṅgalika,' Thế Tôn bảo. ",
  "sn3.12:10.1": "Lúc ấy, cư sĩ Candanaṅgalika tán thán Thế Tôn trước mặt Ngài bằng bài kệ thích hợp: ",
  "sn3.12:11.1": "'Như hoa sen hồng kokanada thơm ngát, '",
  "sn3.12:11.2": "nở rộ vào buổi sáng, còn đầy hương thơm; ",
  "sn3.12:11.3": "Hãy nhìn Angīrasa đang tỏa sáng rực rỡ, ",
  "sn3.12:11.4": "như mặt trời chiếu sáng trên bầu trời.' ",
  "sn3.12:12.1": "Lúc ấy, năm vị vua đó tặng cho cư sĩ Candanaṅgalika năm tấm y thượng. ",
  "sn3.12:12.2": "Lúc ấy, cư sĩ Candanaṅgalika dâng cúng năm tấm y thượng đó cho Thế Tôn.",
  "sn3.13:0.1": "Tương Ưng Bộ 3.13 ",
  "sn3.13:0.2": "2. Phẩm Thứ Hai ",
  "sn3.13:0.3": "Kinh Bát Cơm Đầy ",
  "sn3.13:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.13:1.2": "Lúc ấy, vua Pasenadi nước Kosala đang ăn một bát cơm đầy ắp. ",
  "sn3.13:1.3": "Sau khi ăn xong, vua Pasenadi no nê bội thực, đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. ",
  "sn3.13:2.1": "Lúc ấy, Thế Tôn nhận thấy vua Pasenadi nước Kosala vừa ăn xong, no nê bội thực, liền đọc bài kệ: ",
  "sn3.13:3.1": "'Người luôn có chánh niệm, '",
  "sn3.13:3.2": "biết tiết độ trong ăn uống; ",
  "sn3.13:3.3": "Thì mọi cảm giác của người đó sẽ nhẹ nhàng, ",
  "sn3.13:3.4": "tuổi thọ sẽ lâu dài, già chậm.' ",
  "sn3.13:4.1": "Lúc ấy, có chàng trai Sudassana đang đứng sau lưng vua Pasenadi nước Kosala. ",
  "sn3.13:4.2": "Lúc ấy, vua Pasenadi nước Kosala gọi chàng trai Sudassana: ",
  "sn3.13:4.3": "'Này Sudassana, hãy đến học thuộc lòng bài kệ này từ Thế Tôn, rồi đọc cho ta nghe mỗi khi ta ăn. '",
  "sn3.13:4.4": "Ta sẽ cấp cho ngươi mỗi ngày một trăm đồng tiền vàng như bổng lộc thường xuyên.' ",
  "sn3.13:4.5": "'Vâng, thưa Đại vương,' chàng trai Sudassana thưa vua Pasenadi nước Kosala, rồi học thuộc lòng bài kệ từ Thế Tôn, mỗi khi vua Pasenadi nước Kosala ăn cơm, liền đọc: ",
  "sn3.13:5.1": "'Người luôn có chánh niệm, '",
  "sn3.13:5.2": "biết tiết độ trong ăn uống; ",
  "sn3.13:5.3": "Thì mọi cảm giác của người đó sẽ nhẹ nhàng, ",
  "sn3.13:5.4": "tuổi thọ sẽ lâu dài, già chậm.' ",
  "sn3.13:6.1": "Dần dần, vua Pasenadi nước Kosala quen ăn chỉ một bát cơm đầy nửa. ",
  "sn3.13:6.2": "Sau một thời gian, vua Pasenadi nước Kosala trở nên thân thể thon gọn, vuốt ve thân thể bằng tay, rồi thốt lên lời cảm thán: ",
  "sn3.13:6.3": "'Thật vậy, Thế Tôn đã thương tưởng đến ta theo hai cách '",
  "sn3.13:6.4": "cả lợi ích đời này lẫn lợi ích đời sau.",
  "sn3.14:0.1": "Tương Ưng Bộ 3.14 ",
  "sn3.14:0.2": "2. Phẩm Thứ Hai ",
  "sn3.14:0.3": "Kinh Trận Chiến Thứ Nhất ",
  "sn3.14:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.14:1.2": "Lúc ấy, vua Ajātasattu nước Magadha, con bà Videhi, chuẩn bị đại quân bốn binh chủng, tiến đánh vua Pasenadi nước Kosala về phía xứ Kāsi. ",
  "sn3.14:1.3": "Vua Pasenadi nước Kosala nghe tin: ",
  "sn3.14:1.4": "'Nghe nói vua Ajātasattu nước Magadha, con bà Videhi, chuẩn bị đại quân bốn binh chủng, tiến đánh ta về phía xứ Kāsi.' ",
  "sn3.14:1.5": "Lúc ấy, vua Pasenadi nước Kosala cũng chuẩn bị đại quân bốn binh chủng, tiến đánh vua Ajātasattu nước Magadha, con bà Videhi, về phía xứ Kāsi. ",
  "sn3.14:1.6": "Lúc ấy, vua Ajātasattu nước Magadha, con bà Videhi, và vua Pasenadi nước Kosala giao chiến. ",
  "sn3.14:1.7": "Trong trận chiến đó, vua Ajātasattu nước Magadha, con bà Videhi, đã đánh bại vua Pasenadi nước Kosala. ",
  "sn3.14:1.8": "Sau khi bại trận, vua Pasenadi nước Kosala rút lui về kinh thành Xá Vệ của mình. ",
  "sn3.14:2.1": "Lúc ấy, nhiều Tỳ Kheo vào buổi sáng sớm, đắp y, cầm bát đi vào thành Xá Vệ để khất thực. ",
  "sn3.14:2.2": "Sau khi đi khất thực trong thành Xá Vệ xong, trên đường trở về sau bữa ăn, các Tỳ Kheo đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi một bên, các Tỳ Kheo bạch Thế Tôn: ",
  "sn3.14:3.1": "'Thưa Ngài, vua Ajātasattu nước Magadha, con bà Videhi, chuẩn bị đại quân bốn binh chủng, tiến đánh vua Pasenadi nước Kosala về phía xứ Kāsi. '",
  "sn3.14:3.2": "Vua Pasenadi nước Kosala nghe tin: ",
  "sn3.14:3.3": "'Nghe nói vua Ajātasattu nước Magadha, con bà Videhi, chuẩn bị đại quân bốn binh chủng, tiến đánh ta về phía xứ Kāsi.' ",
  "sn3.14:3.4": "Thưa Ngài, lúc ấy vua Pasenadi nước Kosala cũng chuẩn bị đại quân bốn binh chủng, tiến đánh vua Ajātasattu nước Magadha, con bà Videhi, về phía xứ Kāsi. ",
  "sn3.14:3.5": "Thưa Ngài, lúc ấy vua Ajātasattu nước Magadha, con bà Videhi, và vua Pasenadi nước Kosala giao chiến. ",
  "sn3.14:3.6": "Thưa Ngài, trong trận chiến đó, vua Ajātasattu nước Magadha, con bà Videhi, đã đánh bại vua Pasenadi nước Kosala. ",
  "sn3.14:3.7": "Thưa Ngài, sau khi bại trận, vua Pasenadi nước Kosala rút lui về kinh thành Xá Vệ của mình.' ",
  "sn3.14:4.1": "'Này các Tỳ Kheo, vua Ajātasattu nước Magadha có bạn xấu, bè bạn xấu, kẻ đồng hành xấu; '",
  "sn3.14:4.2": "còn vua Pasenadi nước Kosala có bạn lành, bè bạn lành, kẻ đồng hành lành. ",
  "sn3.14:4.3": "Này các Tỳ Kheo, đêm nay vua Pasenadi nước Kosala ngủ không yên vì bại trận.' ",
  "sn3.14:4.4": "Thế Tôn nói như vậy... ",
  "sn3.14:5.1": "'Chiến thắng sinh ra thù oán, '",
  "sn3.14:5.2": "kẻ bại trận ngủ khổ sở; ",
  "sn3.14:5.3": "Người bình an ngủ an lành, ",
  "sn3.14:5.4": "từ bỏ cả thắng lẫn thua.",
  "sn3.15:0.1": "Tương Ưng Bộ 3.15 ",
  "sn3.15:0.2": "2. Phẩm Thứ Hai ",
  "sn3.15:0.3": "Kinh Trận Chiến Thứ Hai ",
  "sn3.15:1.1": "Lúc ấy, vua Ajātasattu nước Magadha, con bà Videhi, chuẩn bị đại quân bốn binh chủng, tiến đánh vua Pasenadi nước Kosala về phía xứ Kāsi. ",
  "sn3.15:1.2": "Vua Pasenadi nước Kosala nghe tin: ",
  "sn3.15:1.3": "'Nghe nói vua Ajātasattu nước Magadha, con bà Videhi, chuẩn bị đại quân bốn binh chủng, tiến đánh ta về phía xứ Kāsi.' ",
  "sn3.15:1.4": "Lúc ấy, vua Pasenadi nước Kosala cũng chuẩn bị đại quân bốn binh chủng, tiến đánh vua Ajātasattu nước Magadha, con bà Videhi, về phía xứ Kāsi. ",
  "sn3.15:1.5": "Lúc ấy, vua Ajātasattu nước Magadha, con bà Videhi, và vua Pasenadi nước Kosala giao chiến. ",
  "sn3.15:1.6": "Trong trận chiến đó, vua Pasenadi nước Kosala đã đánh bại vua Ajātasattu nước Magadha, con bà Videhi, và bắt sống ông ta. ",
  "sn3.15:1.7": "Lúc ấy, vua Pasenadi nước Kosala suy nghĩ: ",
  "sn3.15:1.8": "'Mặc dù vua Ajātasattu nước Magadha, con bà Videhi, không làm hại ta trước nhưng vẫn làm hại ta, dù sao ông ta cũng là cháu trai của ta. '",
  "sn3.15:1.9": "Ta hãy tịch thu toàn bộ đội voi, toàn bộ đội ngựa, toàn bộ đội xe, toàn bộ đội bộ binh của vua Ajātasattu nước Magadha, con bà Videhi, rồi thả ông ta sống về.' ",
  "sn3.15:2.1": "Lúc ấy, vua Pasenadi nước Kosala tịch thu toàn bộ đội voi, toàn bộ đội ngựa, toàn bộ đội xe, toàn bộ đội bộ binh của vua Ajātasattu nước Magadha, con bà Videhi, rồi thả ông ta sống về. ",
  "sn3.15:3.1": "Lúc ấy, nhiều Tỳ Kheo vào buổi sáng sớm, đắp y, cầm bát đi vào thành Xá Vệ để khất thực. ",
  "sn3.15:3.2": "Sau khi đi khất thực trong thành Xá Vệ xong, trên đường trở về sau bữa ăn, các Tỳ Kheo đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi một bên, các Tỳ Kheo bạch Thế Tôn: ",
  "sn3.15:4.1": "'Thưa Ngài, vua Ajātasattu nước Magadha, con bà Videhi, chuẩn bị đại quân bốn binh chủng, tiến đánh vua Pasenadi nước Kosala về phía xứ Kāsi. '",
  "sn3.15:4.2": "Vua Pasenadi nước Kosala nghe tin: ",
  "sn3.15:4.3": "'Nghe nói vua Ajātasattu nước Magadha, con bà Videhi, chuẩn bị đại quân bốn binh chủng, tiến đánh ta về phía xứ Kāsi.' ",
  "sn3.15:4.4": "Thưa Ngài, lúc ấy vua Pasenadi nước Kosala cũng chuẩn bị đại quân bốn binh chủng, tiến đánh vua Ajātasattu nước Magadha, con bà Videhi, về phía xứ Kāsi. ",
  "sn3.15:4.5": "Thưa Ngài, lúc ấy vua Ajātasattu nước Magadha, con bà Videhi, và vua Pasenadi nước Kosala giao chiến. ",
  "sn3.15:4.6": "Thưa Ngài, trong trận chiến đó, vua Pasenadi nước Kosala đã đánh bại vua Ajātasattu nước Magadha, con bà Videhi, và bắt sống ông ta. ",
  "sn3.15:4.7": "Thưa Ngài, lúc ấy vua Pasenadi nước Kosala suy nghĩ: ",
  "sn3.15:4.8": "'Mặc dù vua Ajātasattu nước Magadha, con bà Videhi, không làm hại ta trước nhưng vẫn làm hại ta, dù sao ông ta cũng là cháu trai của ta. '",
  "sn3.15:4.9": "Ta hãy tịch thu toàn bộ đội voi, toàn bộ đội ngựa, toàn bộ đội xe, toàn bộ đội bộ binh của vua Ajātasattu, rồi thả ông ta sống về.'' ",
  "sn3.15:5.1": "'Thưa Ngài, lúc ấy vua Pasenadi nước Kosala tịch thu toàn bộ đội voi, toàn bộ đội ngựa, toàn bộ đội xe, toàn bộ đội bộ binh của vua Ajātasattu nước Magadha, con bà Videhi, rồi thả ông ta sống về.' ",
  "sn3.15:6.1": "Lúc ấy, Thế Tôn hiểu rõ ý nghĩa này, liền đọc những bài kệ: ",
  "sn3.15:7.1": "'Người ta cướp bóc chừng nào, '",
  "sn3.15:7.2": "chừng nào còn có thể được; ",
  "sn3.15:7.3": "Khi kẻ khác cướp bóc lại, ",
  "sn3.15:7.4": "chính họ bị cướp bóc. ",
  "sn3.15:8.1": "Kẻ ngu tưởng còn cơ hội, ",
  "sn3.15:8.2": "chừng nào điều ác chưa chín muồi; ",
  "sn3.15:8.3": "Nhưng khi điều ác đã chín muồi, ",
  "sn3.15:8.4": "thì kẻ ngu phải chịu khổ đau. ",
  "sn3.15:9.1": "Kẻ giết người tìm thấy kẻ giết lại, ",
  "sn3.15:9.2": "kẻ chinh phục gặp kẻ chinh phục; ",
  "sn3.15:9.3": "Kẻ chửi mắng bị chửi mắng lại, ",
  "sn3.15:9.4": "kẻ giận dữ gặp kẻ làm mình giận dữ; ",
  "sn3.15:9.5": "Rồi do sự xoay vần của nghiệp, ",
  "sn3.15:9.6": "chính họ bị cướp bóc.",
  "sn3.16:0.1": "Tương Ưng Bộ 3.16 ",
  "sn3.16:0.2": "2. Phẩm Thứ Hai ",
  "sn3.16:0.3": "Kinh Mallikā (2) ",
  "sn3.16:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.16:1.2": "Lúc ấy, vua Pasenadi nước Kosala đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. ",
  "sn3.16:1.3": "Lúc ấy, có một người đến chỗ vua Pasenadi nước Kosala; sau khi đến, ghé tai vua và báo: ",
  "sn3.16:1.4": "'Thưa Đại vương, hoàng hậu Mallikā vừa sinh hạ một người con gái.' ",
  "sn3.16:1.5": "Khi nghe vậy, vua Pasenadi nước Kosala không vui. ",
  "sn3.16:2.1": "Lúc ấy, Thế Tôn thấy vua Pasenadi nước Kosala không vui, liền đọc những bài kệ: ",
  "sn3.16:3.1": "'Thưa bậc lãnh đạo muôn dân, đôi khi một người con gái, '",
  "sn3.16:3.2": "còn tốt hơn người con trai; ",
  "sn3.16:3.3": "Nếu nàng có trí tuệ, có giới hạnh, ",
  "sn3.16:3.4": "hiếu thảo với mẹ chồng, trung thành với chồng. ",
  "sn3.16:4.1": "Người con trai sinh ra từ người vợ như vậy, ",
  "sn3.16:4.2": "có thể trở thành anh hùng, chúa tể muôn phương; ",
  "sn3.16:4.3": "Con của người vợ phúc đức như vậy, ",
  "sn3.16:4.4": "có thể cai trị cả đất nước.",
  "sn3.17:0.1": "Tương Ưng Bộ 3.17 ",
  "sn3.17:0.2": "2. Phẩm Thứ Hai ",
  "sn3.17:0.3": "Kinh Không Phóng Dật ",
  "sn3.17:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.17:1.2": "Vua ngồi xuống một bên. ",
  "sn3.17:1.3": "Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.17:1.4": "'Thưa Ngài, có một pháp nào giúp đạt được cả hai lợi ích '",
  "sn3.17:1.5": "lợi ích đời này lẫn lợi ích đời sau không?' ",
  "sn3.17:2.1": "'Thưa Đại vương, có một pháp giúp đạt được cả hai lợi ích '",
  "sn3.17:2.2": "lợi ích đời này lẫn lợi ích đời sau.' ",
  "sn3.17:3.1": "'Thưa Ngài, pháp đó là pháp gì, giúp đạt được cả hai lợi ích '",
  "sn3.17:3.2": "lợi ích đời này lẫn lợi ích đời sau?' ",
  "sn3.17:4.1": "'Thưa Đại vương, không phóng dật là một pháp giúp đạt được cả hai lợi ích '",
  "sn3.17:4.2": "lợi ích đời này lẫn lợi ích đời sau. ",
  "sn3.17:4.3": "Thưa Đại vương, ví như bao nhiêu loài thú đi bằng chân, tất cả chân chúng đều in vào trong dấu chân voi, và dấu chân voi được gọi là lớn nhất trong số chúng, vì nó to lớn nhất; ",
  "sn3.17:4.4": "cũng vậy, thưa Đại vương, không phóng dật là một pháp giúp đạt được cả hai lợi ích ",
  "sn3.17:4.5": "lợi ích đời này lẫn lợi ích đời sau.' ",
  "sn3.17:4.6": "Thế Tôn nói như vậy... ",
  "sn3.17:5.1": "'Ai mong cầu tuổi thọ, sức khỏe, dung mạo đẹp, '",
  "sn3.17:5.2": "cõi trời, dòng dõi cao quý; ",
  "sn3.17:5.3": "Ai mong cầu nhiều niềm vui, ",
  "sn3.17:5.4": "lớn lao và tiếp nối nhau. ",
  "sn3.17:6.1": "Bậc trí khen ngợi không phóng dật, ",
  "sn3.17:6.2": "trong việc làm công đức; ",
  "sn3.17:6.3": "Người trí không phóng dật đạt được cả hai lợi ích, ",
  "sn3.17:6.4": "thâu nhận được cả hai. ",
  "sn3.17:7.1": "Lợi ích ở đời này, ",
  "sn3.17:7.2": "và lợi ích ở đời sau; ",
  "sn3.17:7.3": "Bậc kiên trí thấu rõ lợi ích, ",
  "sn3.17:7.4": "được gọi là người trí thức.",
  "sn3.18:0.1": "Tương Ưng Bộ 3.18 ",
  "sn3.18:0.2": "2. Phẩm Thứ Hai ",
  "sn3.18:0.3": "Kinh Bạn Lành ",
  "sn3.18:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.18:1.2": "Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.18:1.3": "'Thưa Ngài, khi tôi đang ngồi một mình, yên tĩnh, suy nghĩ trong lòng khởi lên như vầy: '",
  "sn3.18:1.4": "'Giáo Pháp được Thế Tôn khéo thuyết giảng; và điều đó đến được với người có bạn lành, bè bạn lành, kẻ đồng hành lành, chứ không phải người có bạn xấu, bè bạn xấu, kẻ đồng hành xấu.'' '",
  "sn3.18:2.1": "'Đúng vậy, thưa Đại vương! Đúng vậy, thưa Đại vương! '",
  "sn3.18:2.2": "Thưa Đại vương, Giáo Pháp được Ta khéo thuyết giảng. Và điều đó đến được với người có bạn lành, bè bạn lành, kẻ đồng hành lành, chứ không phải người có bạn xấu, bè bạn xấu, kẻ đồng hành xấu. ",
  "sn3.18:3.1": "Thưa Đại vương, có một lần Ta đang ở giữa người Sākya, tại một thị trấn tên Nagaraka. ",
  "sn3.18:3.2": "Thưa Đại vương, lúc ấy Tỳ Kheo Ānanda đến chỗ Ta; sau khi đến, đảnh lễ Ta rồi ngồi xuống một bên. Ngồi một bên, thưa Đại vương, Tỳ Kheo Ānanda bạch Ta: ",
  "sn3.18:3.3": "'Thưa Ngài, bạn lành, bè bạn lành, kẻ đồng hành lànhđây là một nửa của đời sống phạm hạnh.' ",
  "sn3.18:4.1": "Khi được nói vậy, thưa Đại vương, Ta đã bảo Tỳ Kheo Ānanda: ",
  "sn3.18:4.2": "'Ānanda, đừng nói vậy, đừng nói vậy. '",
  "sn3.18:4.3": "Ānanda, bạn lành, bè bạn lành, kẻ đồng hành lànhđây là toàn bộ đời sống phạm hạnh. ",
  "sn3.18:4.4": "Ānanda, có thể mong đợi rằng Tỳ Kheo có bạn lành, bè bạn lành, kẻ đồng hành lành sẽ tu tập Bát Thánh Đạo, sẽ thực hành Bát Thánh Đạo nhiều lần. ",
  "sn3.18:5.1": "Và này Ānanda, Tỳ Kheo có bạn lành, bè bạn lành, kẻ đồng hành lành tu tập Bát Thánh Đạo, thực hành Bát Thánh Đạo nhiều lần như thế nào? ",
  "sn3.18:5.2": "Này Ānanda, ở đây Tỳ Kheo tu tập chánh kiếnhướng đến ly dục, hướng đến vô tham, hướng đến tịch diệt, hướng đến buông xả; tu tập chánh tư duy... tu tập chánh ngữ... tu tập chánh nghiệp... tu tập chánh mạng... tu tập chánh tinh tấn... tu tập chánh niệm... tu tập chánh địnhhướng đến ly dục, hướng đến vô tham, hướng đến tịch diệt, hướng đến buông xả. ",
  "sn3.18:5.3": "Này Ānanda, như vậy Tỳ Kheo có bạn lành, bè bạn lành, kẻ đồng hành lành tu tập Bát Thánh Đạo, thực hành Bát Thánh Đạo nhiều lần. ",
  "sn3.18:5.4": "Này Ānanda, đây cũng là phương cách để hiểu rằng toàn bộ đời sống phạm hạnh chính là bạn lành, bè bạn lành, kẻ đồng hành lành. ",
  "sn3.18:6.1": "Này Ānanda, nhờ Ta là bạn lành, những chúng sinh bị sinh, được thoát khỏi sinh; những chúng sinh bị già, được thoát khỏi già; những chúng sinh bị bệnh, được thoát khỏi bệnh; những chúng sinh bị chết, được thoát khỏi chết; những chúng sinh bị sầu, bi, khổ, ưu, não, được thoát khỏi sầu, bi, khổ, ưu, não. ",
  "sn3.18:6.2": "Này Ānanda, đây là phương cách để hiểu rằng toàn bộ đời sống phạm hạnh chính là bạn lành, bè bạn lành, kẻ đồng hành lành.' ",
  "sn3.18:7.1": "Vì vậy, thưa Đại vương, ngài hãy học tập như vầy: ",
  "sn3.18:7.2": "'Ta sẽ có bạn lành, bè bạn lành, kẻ đồng hành lành.' ",
  "sn3.18:7.3": "Thưa Đại vương, ngài phải học tập như vậy. ",
  "sn3.18:8.1": "Thưa Đại vương, khi ngài có bạn lành, bè bạn lành, kẻ đồng hành lành, ngài nên nương tựa vào một pháp này để sống ",
  "sn3.18:8.2": "không phóng dật trong các thiện pháp. ",
  "sn3.18:9.1": "Thưa Đại vương, khi ngài sống không phóng dật, nương tựa vào không phóng dật, thì các cung phi trong cung cũng sẽ nghĩ: ",
  "sn3.18:9.2": "'Đức vua đang sống không phóng dật, nương tựa vào không phóng dật. '",
  "sn3.18:9.3": "Vậy chúng ta cũng hãy sống không phóng dật, nương tựa vào không phóng dật.' ",
  "sn3.18:10.1": "Thưa Đại vương, khi ngài sống không phóng dật, nương tựa vào không phóng dật, thì các quần thần dòng Sát-đế-lỵ cũng sẽ nghĩ: ",
  "sn3.18:10.2": "'Đức vua đang sống không phóng dật, nương tựa vào không phóng dật. '",
  "sn3.18:10.3": "Vậy chúng ta cũng hãy sống không phóng dật, nương tựa vào không phóng dật.' ",
  "sn3.18:11.1": "Thưa Đại vương, khi ngài sống không phóng dật, nương tựa vào không phóng dật, thì đội quân cũng sẽ nghĩ: ",
  "sn3.18:11.2": "'Đức vua đang sống không phóng dật, nương tựa vào không phóng dật. '",
  "sn3.18:11.3": "Vậy chúng ta cũng hãy sống không phóng dật, nương tựa vào không phóng dật.' ",
  "sn3.18:12.1": "Thưa Đại vương, khi ngài sống không phóng dật, nương tựa vào không phóng dật, thì dân chúng trong thành và ngoài nước cũng sẽ nghĩ: ",
  "sn3.18:12.2": "'Đức vua đang sống không phóng dật, nương tựa vào không phóng dật. '",
  "sn3.18:12.3": "Vậy chúng ta cũng hãy sống không phóng dật, nương tựa vào không phóng dật.' ",
  "sn3.18:13.1": "Thưa Đại vương, khi ngài sống không phóng dật, nương tựa vào không phóng dật, thì bản thân ngài sẽ được bảo vệ ",
  "sn3.18:13.2": "cung phi trong cung cũng sẽ được bảo vệ, kho báu và lương thực cũng sẽ được bảo vệ.' ",
  "sn3.18:13.3": "Thế Tôn nói như vậy... ",
  "sn3.18:14.1": "'Ai mong cầu của cải, '",
  "sn3.18:14.2": "lớn lao và tiếp nối nhau; ",
  "sn3.18:14.3": "Bậc trí khen ngợi không phóng dật, ",
  "sn3.18:14.4": "trong việc làm công đức; ",
  "sn3.18:14.5": "Người trí không phóng dật đạt được cả hai lợi ích, ",
  "sn3.18:14.6": "thâu nhận được cả hai. ",
  "sn3.18:15.1": "Lợi ích ở đời này, ",
  "sn3.18:15.2": "và lợi ích ở đời sau; ",
  "sn3.18:15.3": "Bậc kiên trí thấu rõ lợi ích, ",
  "sn3.18:15.4": "được gọi là người trí thức.",
  "sn3.19:0.1": "Tương Ưng Bộ 3.19 ",
  "sn3.19:0.2": "2. Phẩm Thứ Hai ",
  "sn3.19:0.3": "Kinh Người Không Con (1) ",
  "sn3.19:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.19:1.2": "Lúc ấy, vua Pasenadi nước Kosala vào ban ngày đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Thế Tôn nói với vua Pasenadi nước Kosala đang ngồi một bên: ",
  "sn3.19:1.3": "'Thưa Đại vương, ngài từ đâu đến vào ban ngày thế này?' ",
  "sn3.19:2.1": "'Thưa Ngài, tại Xá Vệ có một vị trưởng giả vừa qua đời. '",
  "sn3.19:2.2": "Tôi đang chuyển tài sản không người thừa kế của ông ta vào hoàng cung nên mới đến đây. ",
  "sn3.19:2.3": "Thưa Ngài, chỉ riêng vàng thôi đã có tám mươi lạc tiền, chưa kể đến bạc. ",
  "sn3.19:2.4": "Thưa Ngài, vị trưởng giả đó có chế độ ăn như vầy ",
  "sn3.19:2.5": "ông ta ăn cháo tấm với dưa cải muối. ",
  "sn3.19:2.6": "Chế độ mặc của ông ta là thế này ",
  "sn3.19:2.7": "ông ta mặc vải gai, mặc ba lớp vải. ",
  "sn3.19:2.8": "Chế độ đi lại của ông ta là thế này ",
  "sn3.19:2.9": "ông ta đi bằng chiếc xe cũ kỹ, che bằng cây lá.' ",
  "sn3.19:3.1": "'Đúng vậy, thưa Đại vương! Đúng vậy, thưa Đại vương! '",
  "sn3.19:3.2": "Thưa Đại vương, kẻ xấu người có được của cải lớn lao mà không làm mình vui sướng, không làm cha mẹ vui sướng, không làm vợ con vui sướng, không làm đầy tớ và nhân công vui sướng, không làm bạn bè vui sướng, không bố thí cho sa-môn và bà-la-môn để tạo phước lành đưa đến cõi trời, mang lại quả vui, dẫn đến thiên đường. ",
  "sn3.19:3.3": "Những tài sản của ông ta không được sử dụng đúng cách như vậy, thì vua sẽ tịch thu, hay trộm cướp sẽ lấy đi, hay lửa sẽ thiêu đốt, hay nước sẽ cuốn trôi, hay người thừa kế ghét bỏ sẽ lấy đi. ",
  "sn3.19:3.4": "Thưa Đại vương, khi tài sản không được sử dụng đúng cách như vậy, thì chúng bị hao mòn mà không được hưởng thụ. ",
  "sn3.19:4.1": "Thưa Đại vương, ví như ở nơi không có người ở, có một cái hồ nước mát trong, nước lạnh, nước ngon, nước sạch, bờ hồ tốt đẹp, dễ chịu. ",
  "sn3.19:4.2": "Không ai múc nước, uống nước, tắm nước hay sử dụng theo nhu cầu. ",
  "sn3.19:4.3": "Thưa Đại vương, khi nước đó không được sử dụng đúng cách như vậy, thì nó sẽ cạn khô mà không được hưởng thụ. ",
  "sn3.19:4.4": "Cũng vậy, thưa Đại vương, kẻ xấu người có được của cải lớn lao mà không làm mình vui sướng, không làm cha mẹ vui sướng, không làm vợ con vui sướng, không làm đầy tớ và nhân công vui sướng, không làm bạn bè vui sướng, không bố thí cho sa-môn và bà-la-môn để tạo phước lành đưa đến cõi trời, mang lại quả vui, dẫn đến thiên đường. ",
  "sn3.19:4.5": "Những tài sản của ông ta không được sử dụng đúng cách như vậy, thì vua sẽ tịch thu, hay trộm cướp sẽ lấy đi, hay lửa sẽ thiêu đốt, hay nước sẽ cuốn trôi, hay người thừa kế ghét bỏ sẽ lấy đi. ",
  "sn3.19:4.6": "Thưa Đại vương, khi tài sản không được sử dụng đúng cách như vậy, thì chúng bị hao mòn mà không được hưởng thụ. ",
  "sn3.19:5.1": "Thưa Đại vương, còn người tốt có được của cải lớn lao thì làm mình vui sướng, làm cha mẹ vui sướng, làm vợ con vui sướng, làm đầy tớ và nhân công vui sướng, làm bạn bè vui sướng, bố thí cho sa-môn và bà-la-môn để tạo phước lành đưa đến cõi trời, mang lại quả vui, dẫn đến thiên đường. ",
  "sn3.19:5.2": "Những tài sản của ông ta được sử dụng đúng cách như vậy, thì vua không tịch thu, trộm cướp không lấy đi, lửa không thiêu đốt, nước không cuốn trôi, người thừa kế ghét bỏ không lấy đi. ",
  "sn3.19:5.3": "Thưa Đại vương, khi tài sản được sử dụng đúng cách như vậy, thì chúng được hưởng thụ mà không bị hao mòn. ",
  "sn3.19:6.1": "Thưa Đại vương, ví như gần một làng hoặc một thị trấn, có một cái hồ nước mát trong, nước lạnh, nước ngon, nước sạch, bờ hồ tốt đẹp, dễ chịu. ",
  "sn3.19:6.2": "Người ta đến múc nước, uống nước, tắm nước và sử dụng theo nhu cầu. ",
  "sn3.19:6.3": "Thưa Đại vương, khi nước đó được sử dụng đúng cách như vậy, thì nó được hưởng thụ mà không bị cạn khô. ",
  "sn3.19:6.4": "Cũng vậy, thưa Đại vương, người tốt có được của cải lớn lao thì làm mình vui sướng, làm cha mẹ vui sướng, làm vợ con vui sướng, làm đầy tớ và nhân công vui sướng, làm bạn bè vui sướng, bố thí cho sa-môn và bà-la-môn để tạo phước lành đưa đến cõi trời, mang lại quả vui, dẫn đến thiên đường. ",
  "sn3.19:6.5": "Những tài sản của ông ta được sử dụng đúng cách như vậy, thì vua không tịch thu, trộm cướp không lấy đi, lửa không thiêu đốt, nước không cuốn trôi, người thừa kế ghét bỏ không lấy đi. ",
  "sn3.19:6.6": "Thưa Đại vương, khi tài sản được sử dụng đúng cách như vậy, thì chúng được hưởng thụ mà không bị hao mòn.' ",
  "sn3.19:7.1": "'Như nước lạnh ở nơi vắng vẻ, '",
  "sn3.19:7.2": "không ai uống thì sẽ cạn khô; ",
  "sn3.19:7.3": "Cũng vậy kẻ xấu có được tài sản, ",
  "sn3.19:7.4": "không tự hưởng cũng không bố thí. ",
  "sn3.19:8.1": "Người trí, người hiểu biết đạt được tài sản, ",
  "sn3.19:8.2": "tự hưởng thụ và làm tròn bổn phận; ",
  "sn3.19:8.3": "Sau khi nuôi dưỡng bà con họ hàng xứng đáng, ",
  "sn3.19:8.4": "người đó không bị chê trách và đến được cõi trời.",
  "sn3.20:0.1": "Tương Ưng Bộ 3.20 ",
  "sn3.20:0.2": "2. Phẩm Thứ Hai ",
  "sn3.20:0.3": "Kinh Người Không Con (2) ",
  "sn3.20:1.1": "Lúc ấy, vua Pasenadi nước Kosala vào ban ngày đến chỗ Thế Tôn; sau khi đến, ngồi xuống một bên. Thế Tôn nói với vua Pasenadi nước Kosala đang ngồi một bên: ",
  "sn3.20:1.2": "'Thưa Đại vương, ngài từ đâu đến vào ban ngày thế này?' ",
  "sn3.20:2.1": "'Thưa Ngài, tại Xá Vệ có một vị trưởng giả vừa qua đời. '",
  "sn3.20:2.2": "Tôi đang chuyển tài sản không người thừa kế của ông ta vào hoàng cung nên mới đến đây. ",
  "sn3.20:2.3": "Thưa Ngài, chỉ riêng vàng thôi đã có một trăm lần mười vạn đồng tiền, chưa kể đến bạc. ",
  "sn3.20:2.4": "Thưa Ngài, vị trưởng giả đó có chế độ ăn như vầy ",
  "sn3.20:2.5": "ông ta ăn cháo tấm với dưa cải muối. ",
  "sn3.20:2.6": "Chế độ mặc của ông ta là thế này ",
  "sn3.20:2.7": "ông ta mặc vải gai, mặc ba lớp vải. ",
  "sn3.20:2.8": "Chế độ đi lại của ông ta là thế này ",
  "sn3.20:2.9": "ông ta đi bằng chiếc xe cũ kỹ, che bằng cây lá.' ",
  "sn3.20:3.1": "'Đúng vậy, thưa Đại vương! Đúng vậy, thưa Đại vương! '",
  "sn3.20:3.2": "Thưa Đại vương, ngày xưa vị trưởng giả đó đã dâng cơm khất thực cho vị Độc Giác Phật tên là Taggarasikhī. ",
  "sn3.20:3.3": "Nói 'Hãy dâng thức ăn cho vị sa-môn,' rồi ông ta đứng dậy bỏ đi. ",
  "sn3.20:3.4": "Sau khi đã dâng cúng rồi, về sau ông ta lại hối hận: ",
  "sn3.20:3.5": "'Thà cho đầy tớ hay nhân công ăn phần cơm đó còn hơn.' ",
  "sn3.20:3.6": "Ông ta còn giết chết đứa con trai duy nhất của người anh vì tài sản. ",
  "sn3.20:4.1": "Thưa Đại vương, vì quả báo của việc dâng cơm khất thực cho vị Độc Giác Phật Taggarasikhī, ông ta đã bảy lần tái sinh vào cõi lành, cõi trời. ",
  "sn3.20:4.2": "Do phần quả báo còn lại của hành động đó, ông ta làm trưởng giả bảy lần tại chính thành Xá Vệ này. ",
  "sn3.20:4.3": "Thưa Đại vương, còn vì quả báo của việc dâng cúng rồi về sau lại hối hận: ",
  "sn3.20:4.4": "'Thà cho đầy tớ hay nhân công ăn phần cơm đó còn hơn,' nên do quả báo của hành động đó, tâm ông ta không hướng đến việc hưởng thụ thức ăn ngon, tâm ông ta không hướng đến việc hưởng thụ quần áo đẹp, tâm ông ta không hướng đến việc hưởng thụ phương tiện đi lại tốt, tâm ông ta không hướng đến việc hưởng thụ năm dục lạc. ",
  "sn3.20:4.5": "Thưa Đại vương, còn vì quả báo của việc giết chết đứa con trai duy nhất của người anh vì tài sản, ông ta đã trải qua nhiều năm, nhiều trăm năm, nhiều ngàn năm, nhiều trăm ngàn năm trong địa ngục. ",
  "sn3.20:4.6": "Do phần quả báo còn lại của hành động đó, lần thứ bảy này tài sản không có người thừa kế được chuyển vào hoàng cung. ",
  "sn3.20:4.7": "Thưa Đại vương, phước lành cũ của vị trưởng giả đó đã cạn kiệt, phước lành mới chưa được tích lũy. ",
  "sn3.20:4.8": "Thưa Đại vương, hôm nay vị trưởng giả đó đang chịu khổ trong địa ngục Mahāroruva.' ",
  "sn3.20:4.9": "'Thưa Ngài, vị trưởng giả đó đã tái sinh vào địa ngục Mahāroruva sao?' ",
  "sn3.20:4.10": "'Đúng vậy, thưa Đại vương, vị trưởng giả đó đã tái sinh vào địa ngục Mahāroruva.' ",
  "sn3.20:4.11": "Thế Tôn nói như vậy.... ",
  "sn3.20:5.1": "'Lúa gạo, của cải, bạc và vàng, '",
  "sn3.20:5.2": "và bất kỳ tài sản hay vật sở hữu nào; ",
  "sn3.20:5.3": "Đầy tớ, nhân công, người hầu cận, ",
  "sn3.20:5.4": "và những kẻ sống nhờ vào người đó. ",
  "sn3.20:6.1": "Tất cả không thể mang theo được, ",
  "sn3.20:6.2": "tất cả phải bỏ lại khi ra đi; ",
  "sn3.20:6.3": "Những gì người đó làm bằng thân, ",
  "sn3.20:6.4": "bằng lời nói hay bằng tâm ý. ",
  "sn3.20:7.1": "Chỉ những điều đó mới thực sự là của người đó, ",
  "sn3.20:7.2": "chỉ những điều đó người đó mang theo được; ",
  "sn3.20:7.3": "Chỉ những điều đó theo sau người đó, ",
  "sn3.20:7.4": "như bóng không rời hình. ",
  "sn3.20:8.1": "Vì vậy hãy làm điều thiện, ",
  "sn3.20:8.2": "tích lũy cho đời sau; ",
  "sn3.20:8.3": "Công đức ở thế giới bên kia, ",
  "sn3.20:8.4": "là chỗ nương tựa cho chúng sinh.",
  "sn3.20:8.5": "Phẩm Thứ Hai. ",
  "sn3.20:9.0": "Tóm tắt phẩm: ",
  "sn3.20:9.1": "Người bện tóc, năm vua, ",
  "sn3.20:9.2": "bát cơm đầy; ",
  "sn3.20:9.3": "Hai bài về trận chiến, ",
  "sn3.20:9.4": "Mallikā, hai bài về không phóng dật; ",
  "sn3.20:9.5": "Hai bài về người không con được nói, ",
  "sn3.20:9.6": "phẩm được gọi như vậy.",
  "sn3.21:0.1": "Tương Ưng Bộ 3.21 ",
  "sn3.21:0.2": "3. Phẩm Thứ Ba ",
  "sn3.21:0.3": "Kinh Hạng Người ",
  "sn3.21:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.21:1.2": "Lúc ấy, vua Pasenadi nước Kosala đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Thế Tôn nói với vua Pasenadi nước Kosala đang ngồi một bên: ",
  "sn3.21:1.3": "'Thưa Đại vương, có bốn hạng người này tồn tại, có mặt ở trên đời. '",
  "sn3.21:1.4": "Bốn hạng người đó là gì? ",
  "sn3.21:1.5": "Hạng từ tối đi vào tối, ",
  "sn3.21:1.6": "hạng từ tối đi vào sáng, ",
  "sn3.21:1.7": "hạng từ sáng đi vào tối, ",
  "sn3.21:1.8": "hạng từ sáng đi vào sáng. ",
  "sn3.21:2.1": "Thưa Đại vương, thế nào là người từ tối đi vào tối? ",
  "sn3.21:2.2": "Ở đây, thưa Đại vương, có người sinh ra trong gia đình thấp kém, như gia đình người hốt rác, gia đình người đan lát, gia đình người thợ săn, gia đình người làm xe hay gia đình người quét rác, nghèo khó, ít cơm ăn áo mặc, sống vất vả, khó kiếm được miếng ăn. ",
  "sn3.21:2.3": "Người đó lại xấu xí, khó nhìn, còm cõi, hay đau ốm, mù quáng, hay cụt tay, hay khập khiễng, hay liệt nửa người, không được cơm ăn, nước uống, áo mặc, phương tiện đi lại, vòng hoa, hương liệu và dầu thơm, chỗ nằm, chỗ ở, đèn sáng. ",
  "sn3.21:2.4": "Người đó làm điều xấu ác bằng thân, làm điều xấu ác bằng lời nói, làm điều xấu ác bằng tâm ý. ",
  "sn3.21:2.5": "Sau khi làm điều xấu ác bằng thân, bằng lời nói, bằng tâm ý, khi thân hoại mạng chung, người đó tái sinh vào cõi dữ, đường ác, chỗ sa đọa, địa ngục. ",
  "sn3.21:3.1": "Thưa Đại vương, ví như có người đi từ bóng tối sang bóng tối, hay từ chỗ tối tăm sang chỗ tối tăm, hay từ vết nhơ máu sang vết nhơ máu khác. ",
  "sn3.21:3.2": "Thưa Đại vương, Ta ví hạng người này như vậy. ",
  "sn3.21:3.3": "Thưa Đại vương, như vậy là người từ tối đi vào tối. ",
  "sn3.21:4.1": "Thưa Đại vương, thế nào là người từ tối đi vào sáng? ",
  "sn3.21:4.2": "Ở đây, thưa Đại vương, có người sinh ra trong gia đình thấp kém, như gia đình người hốt rác, gia đình người đan lát, gia đình người thợ săn, gia đình người làm xe hay gia đình người quét rác, nghèo khó, ít cơm ăn áo mặc, sống vất vả, khó kiếm được miếng ăn. ",
  "sn3.21:4.3": "Người đó lại xấu xí, khó nhìn, còm cõi, hay đau ốm, mù quáng, hay cụt tay, hay khập khiễng, hay liệt nửa người, không được cơm ăn, nước uống, áo mặc, phương tiện đi lại, vòng hoa, hương liệu và dầu thơm, chỗ nằm, chỗ ở, đèn sáng. ",
  "sn3.21:4.4": "Nhưng người đó làm điều thiện lành bằng thân, làm điều thiện lành bằng lời nói, làm điều thiện lành bằng tâm ý. ",
  "sn3.21:4.5": "Sau khi làm điều thiện lành bằng thân, bằng lời nói, bằng tâm ý, khi thân hoại mạng chung, người đó tái sinh vào cõi lành, cõi trời. ",
  "sn3.21:5.1": "Thưa Đại vương, ví như có người từ mặt đất bước lên cái giường, từ cái giường leo lên lưng ngựa, từ lưng ngựa leo lên lưng voi, từ lưng voi leo lên lầu cao. ",
  "sn3.21:5.2": "Thưa Đại vương, Ta ví hạng người này như vậy. ",
  "sn3.21:5.3": "Thưa Đại vương, như vậy là người từ tối đi vào sáng. ",
  "sn3.21:6.1": "Thưa Đại vương, thế nào là người từ sáng đi vào tối? ",
  "sn3.21:6.2": "Ở đây, thưa Đại vương, có người sinh ra trong gia đình cao quý, như gia đình Sát-đế-lỵ đại phú hào, hay gia đình bà-la-môn đại phú hào, hay gia đình cư sĩ đại phú hào, giàu có, nhiều tiền của, nhiều tài sản, nhiều vàng bạc, nhiều tiền của và lương thực. ",
  "sn3.21:6.3": "Người đó lại đẹp đẽ, dễ nhìn, đáng yêu, có nét đẹp tuyệt hảo, được cơm ăn, nước uống, áo mặc, phương tiện đi lại, vòng hoa, hương liệu và dầu thơm, chỗ nằm, chỗ ở, đèn sáng. ",
  "sn3.21:6.4": "Nhưng người đó làm điều xấu ác bằng thân, làm điều xấu ác bằng lời nói, làm điều xấu ác bằng tâm ý. ",
  "sn3.21:6.5": "Sau khi làm điều xấu ác bằng thân, bằng lời nói, bằng tâm ý, khi thân hoại mạng chung, người đó tái sinh vào cõi dữ, đường ác, chỗ sa đọa, địa ngục. ",
  "sn3.21:7.1": "Thưa Đại vương, ví như có người từ lầu cao xuống lưng voi, từ lưng voi xuống lưng ngựa, từ lưng ngựa xuống cái giường, từ cái giường xuống mặt đất, từ mặt đất đi vào chỗ tối tăm. ",
  "sn3.21:7.2": "Thưa Đại vương, Ta ví hạng người này như vậy. ",
  "sn3.21:7.3": "Thưa Đại vương, như vậy là người từ sáng đi vào tối. ",
  "sn3.21:8.1": "Thưa Đại vương, thế nào là người từ sáng đi vào sáng? ",
  "sn3.21:8.2": "Ở đây, thưa Đại vương, có người sinh ra trong gia đình cao quý, như gia đình Sát-đế-lỵ đại phú hào, hay gia đình bà-la-môn đại phú hào, hay gia đình cư sĩ đại phú hào, giàu có, nhiều tiền của, nhiều tài sản, nhiều vàng bạc, nhiều tiền của và lương thực. ",
  "sn3.21:8.3": "Người đó lại đẹp đẽ, dễ nhìn, đáng yêu, có nét đẹp tuyệt hảo, được cơm ăn, nước uống, áo mặc, phương tiện đi lại, vòng hoa, hương liệu và dầu thơm, chỗ nằm, chỗ ở, đèn sáng. ",
  "sn3.21:8.4": "Người đó làm điều thiện lành bằng thân, làm điều thiện lành bằng lời nói, làm điều thiện lành bằng tâm ý. ",
  "sn3.21:8.5": "Sau khi làm điều thiện lành bằng thân, bằng lời nói, bằng tâm ý, khi thân hoại mạng chung, người đó tái sinh vào cõi lành, cõi trời. ",
  "sn3.21:9.1": "Thưa Đại vương, ví như có người từ cái giường bước sang cái giường khác, từ lưng ngựa sang lưng ngựa khác, từ lưng voi sang lưng voi khác, từ lầu cao sang lầu cao khác. ",
  "sn3.21:9.2": "Thưa Đại vương, Ta ví hạng người này như vậy. ",
  "sn3.21:9.3": "Thưa Đại vương, như vậy là người từ sáng đi vào sáng. ",
  "sn3.21:9.4": "Thưa Đại vương, đây là bốn hạng người tồn tại, có mặt ở trên đời.' ",
  "sn3.21:9.5": "Thế Tôn nói như vậy... ",
  "sn3.21:10.1": "'Người nghèo khó, thưa Đại vương, '",
  "sn3.21:10.2": "không có lòng tin, keo kiệt; ",
  "sn3.21:10.3": "Bủn xỉn, có ý định xấu, ",
  "sn3.21:10.4": "tà kiến, vô lễ. ",
  "sn3.21:11.1": "Chửi mắng sa-môn hay bà-la-môn, ",
  "sn3.21:11.2": "hay những người ăn xin khác; ",
  "sn3.21:11.3": "Mắng chửi, chê bai, ",
  "sn3.21:11.4": "phủ nhận, hay thù oán. ",
  "sn3.21:12.1": "Ngăn cản người bố thí, ",
  "sn3.21:12.2": "thức ăn cho những người xin; ",
  "sn3.21:12.3": "Người như vậy, thưa Đại vương, ",
  "sn3.21:12.4": "khi chết đi, hỡi bậc lãnh đạo muôn dân; ",
  "sn3.21:12.5": "Đến địa ngục đáng sợ, ",
  "sn3.21:12.6": "đây là người từ tối đi vào tối. ",
  "sn3.21:13.1": "Người nghèo khó, thưa Đại vương, ",
  "sn3.21:13.2": "có lòng tin, không keo kiệt; ",
  "sn3.21:13.3": "Bố thí, có ý định tốt, ",
  "sn3.21:13.4": "tâm trí không tán loạn. ",
  "sn3.21:14.1": "Đứng dậy kính lễ sa-môn hay bà-la-môn, ",
  "sn3.21:14.2": "hay những người ăn xin khác; ",
  "sn3.21:14.3": "Học tập theo hạnh thiện lành, ",
  "sn3.21:14.4": "tu tập đời sống bình đẳng. ",
  "sn3.21:15.1": "Không ngăn cản người bố thí, ",
  "sn3.21:15.2": "thức ăn cho những người xin; ",
  "sn3.21:15.3": "Người như vậy, thưa Đại vương, ",
  "sn3.21:15.4": "khi chết đi, hỡi bậc lãnh đạo muôn dân; ",
  "sn3.21:15.5": "Đến cõi trời ba mươi ba, ",
  "sn3.21:15.6": "đây là người từ tối đi vào sáng. ",
  "sn3.21:16.1": "Người giàu có, thưa Đại vương, ",
  "sn3.21:16.2": "không có lòng tin, keo kiệt; ",
  "sn3.21:16.3": "Bủn xỉn, có ý định xấu, ",
  "sn3.21:16.4": "tà kiến, vô lễ. ",
  "sn3.21:17.1": "Chửi mắng sa-môn hay bà-la-môn, ",
  "sn3.21:17.2": "hay những người ăn xin khác; ",
  "sn3.21:17.3": "Mắng chửi, chê bai, ",
  "sn3.21:17.4": "phủ nhận, hay thù oán. ",
  "sn3.21:18.1": "Ngăn cản người bố thí, ",
  "sn3.21:18.2": "thức ăn cho những người xin; ",
  "sn3.21:18.3": "Người như vậy, thưa Đại vương, ",
  "sn3.21:18.4": "khi chết đi, hỡi bậc lãnh đạo muôn dân; ",
  "sn3.21:18.5": "Đến địa ngục đáng sợ, ",
  "sn3.21:18.6": "đây là người từ sáng đi vào tối. ",
  "sn3.21:19.1": "Người giàu có, thưa Đại vương, ",
  "sn3.21:19.2": "có lòng tin, không keo kiệt; ",
  "sn3.21:19.3": "Bố thí, có ý định tốt, ",
  "sn3.21:19.4": "tâm trí không tán loạn. ",
  "sn3.21:20.1": "Đứng dậy kính lễ sa-môn hay bà-la-môn, ",
  "sn3.21:20.2": "hay những người ăn xin khác; ",
  "sn3.21:20.3": "Học tập theo hạnh thiện lành, ",
  "sn3.21:20.4": "tu tập đời sống bình đẳng. ",
  "sn3.21:21.1": "Không ngăn cản người bố thí, ",
  "sn3.21:21.2": "thức ăn cho những người xin; ",
  "sn3.21:21.3": "Người như vậy, thưa Đại vương, ",
  "sn3.21:21.4": "khi chết đi, hỡi bậc lãnh đạo muôn dân; ",
  "sn3.21:21.5": "Đến cõi trời ba mươi ba, ",
  "sn3.21:21.6": "đây là người từ sáng đi vào sáng.",
  "sn3.22:0.1": "Tương Ưng Bộ 3.22 ",
  "sn3.22:0.2": "3. Phẩm Thứ Ba ",
  "sn3.22:0.3": "Kinh Bà Nội ",
  "sn3.22:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.22:1.2": "Thế Tôn nói với vua Pasenadi nước Kosala đang ngồi một bên: ",
  "sn3.22:1.3": "'Thưa Đại vương, ngài từ đâu đến vào ban ngày thế này?' ",
  "sn3.22:2.1": "'Thưa Ngài, bà nội của tôi vừa qua đời, đã già cả, lớn tuổi, cao niên, đã đi được nửa đường, đã đến tuổi già, thọ được một trăm hai mươi tuổi. '",
  "sn3.22:2.2": "Thưa Ngài, bà nội của tôi là người tôi yêu thương, trân trọng. ",
  "sn3.22:2.3": "Thưa Ngài, nếu tôi có thể đổi bảo vật voi báu để bà nội tôi khỏi chết, tôi sẽ đổi: ",
  "sn3.22:2.4": "'Để bà nội tôi khỏi chết.' ",
  "sn3.22:2.5": "Thưa Ngài, nếu tôi có thể đổi bảo vật ngựa báu để bà nội tôi khỏi chết, tôi sẽ đổi: ",
  "sn3.22:2.6": "'Để bà nội tôi khỏi chết.' ",
  "sn3.22:2.7": "Thưa Ngài, nếu tôi có thể đổi một làng tốt để bà nội tôi khỏi chết, tôi sẽ đổi: ",
  "sn3.22:2.8": "'Để bà nội tôi khỏi chết.' ",
  "sn3.22:2.9": "Thưa Ngài, nếu tôi có thể đổi một vùng đất để bà nội tôi khỏi chết, tôi sẽ đổi: ",
  "sn3.22:2.10": "'Để bà nội tôi khỏi chết.'' '",
  "sn3.22:2.11": "'Thưa Đại vương, mọi chúng sinh đều có bản chất phải chết, kết thúc bằng cái chết, không thể thoát khỏi cái chết.' ",
  "sn3.22:2.12": "'Thật kỳ diệu, thưa Ngài! Thật phi thường, thưa Ngài! '",
  "sn3.22:2.13": "Thật là khéo nói, thưa Ngài, khi Thế Tôn nói ",
  "sn3.22:2.14": "mọi chúng sinh đều có bản chất phải chết, kết thúc bằng cái chết, không thể thoát khỏi cái chết.'' ",
  "sn3.22:3.1": "'Đúng vậy, thưa Đại vương! Đúng vậy, thưa Đại vương! '",
  "sn3.22:3.2": "Mọi chúng sinh đều có bản chất phải chết, kết thúc bằng cái chết, không thể thoát khỏi cái chết. ",
  "sn3.22:3.3": "Thưa Đại vương, ví như tất cả đồ gốm do thợ gốm làm ra, dù sống hay chín, tất cả đều có bản chất bị vỡ, kết thúc bằng sự vỡ nát, không thể thoát khỏi sự vỡ nát; ",
  "sn3.22:3.4": "cũng vậy, thưa Đại vương, mọi chúng sinh đều có bản chất phải chết, kết thúc bằng cái chết, không thể thoát khỏi cái chết.' ",
  "sn3.22:3.5": "Thế Tôn nói như vậy... ",
  "sn3.22:4.1": "'Mọi chúng sinh đều sẽ chết, '",
  "sn3.22:4.2": "vì cuộc đời kết thúc bằng cái chết; ",
  "sn3.22:4.3": "Họ sẽ đi theo nghiệp của mình, ",
  "sn3.22:4.4": "gặt hái quả phước hay quả tội; ",
  "sn3.22:4.5": "Kẻ làm ác đến địa ngục, ",
  "sn3.22:4.6": "người làm lành đến cõi an vui. ",
  "sn3.22:5.1": "Vì vậy hãy làm điều thiện, ",
  "sn3.22:5.2": "tích lũy cho đời sau; ",
  "sn3.22:5.3": "Công đức ở thế giới bên kia, ",
  "sn3.22:5.4": "là chỗ nương tựa cho chúng sinh.",
  "sn3.23:0.1": "Tương Ưng Bộ 3.23 ",
  "sn3.23:0.2": "3. Phẩm Thứ Ba ",
  "sn3.23:0.3": "Kinh Thế Gian ",
  "sn3.23:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.23:1.2": "Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.23:1.3": "'Thưa Ngài, có bao nhiêu pháp khởi lên trong thế gian, khởi lên đưa đến bất hạnh, khổ đau và sống không an lạc?' ",
  "sn3.23:1.4": "'Thưa Đại vương, có ba pháp khởi lên trong thế gian, khởi lên đưa đến bất hạnh, khổ đau và sống không an lạc. '",
  "sn3.23:1.5": "Ba pháp đó là gì? ",
  "sn3.23:1.6": "Thưa Đại vương, lòng tham là pháp của thế gian, khởi lên đưa đến bất hạnh, khổ đau và sống không an lạc. ",
  "sn3.23:1.7": "Thưa Đại vương, lòng sân là pháp của thế gian, khởi lên đưa đến bất hạnh, khổ đau và sống không an lạc. ",
  "sn3.23:1.8": "Thưa Đại vương, lòng si là pháp của thế gian, khởi lên đưa đến bất hạnh, khổ đau và sống không an lạc. ",
  "sn3.23:1.9": "Thưa Đại vương, đây là ba pháp khởi lên trong thế gian, khởi lên đưa đến bất hạnh, khổ đau và sống không an lạc.' ",
  "sn3.23:1.10": "Thế Tôn nói như vậy... ",
  "sn3.23:2.1": "'Tham, sân và si, '",
  "sn3.23:2.2": "sinh ra từ trong lòng người có tâm xấu ác; ",
  "sn3.23:2.3": "Tự mình hại mình, ",
  "sn3.23:2.4": "như trái cây tự làm hỏng cây của nó.",
  "sn3.24:0.1": "Tương Ưng Bộ 3.24 ",
  "sn3.24:0.2": "3. Phẩm Thứ Ba ",
  "sn3.24:0.3": "Kinh Nghề Cung Thủ ",
  "sn3.24:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.24:1.2": "Ngồi một bên, vua Pasenadi nước Kosala bạch Thế Tôn: ",
  "sn3.24:1.3": "'Thưa Ngài, nên bố thí ở đâu?' ",
  "sn3.24:1.4": "'Thưa Đại vương, nên bố thí ở nơi tâm ngài hoan hỷ.' ",
  "sn3.24:1.5": "'Thưa Ngài, bố thí ở đâu thì có quả lớn?' ",
  "sn3.24:1.6": "'Thưa Đại vương, đây là hai câu hỏi khác nhau: nên bố thí ở đâu, và bố thí ở đâu có quả lớn. '",
  "sn3.24:1.7": "Thưa Đại vương, bố thí cho người có giới hạnh thì có quả lớn, không phải bố thí cho người phá giới. ",
  "sn3.24:1.8": "Thưa Đại vương, để rõ hơn về điều này, Ta sẽ hỏi ngài. Ngài có thể trả lời theo cách ngài thấy hợp. ",
  "sn3.24:1.9": "Thưa Đại vương, ngài nghĩ sao, ",
  "sn3.24:1.10": "giả sử có một trận chiến đang chuẩn bị xảy ra, quân đội đang tập hợp. ",
  "sn3.24:1.11": "Lúc đó có một chàng trai Sát-đế-lỵ đến, chưa qua huấn luyện, chưa giỏi nghề, chưa luyện tập, chưa thành thạo, nhút nhát, sợ hãi, hay bỏ chạy. ",
  "sn3.24:1.12": "Ngài có thuê mướn người đó không, ngài có cần người như vậy không?' ",
  "sn3.24:1.13": "'Thưa Ngài, tôi không thuê người đó, tôi không cần người như vậy.' ",
  "sn3.24:1.14": "'Lại có một chàng trai bà-la-môn đến, chưa qua huấn luyện... '",
  "sn3.24:1.15": "lại có một chàng trai dòng thương nhân đến, chưa qua huấn luyện... ",
  "sn3.24:1.16": "lại có một chàng trai dòng thấp hèn đến, chưa qua huấn luyện... ",
  "sn3.24:1.17": "tôi không cần người như vậy.' ",
  "sn3.24:2.1": "'Thưa Đại vương, ngài nghĩ sao, '",
  "sn3.24:2.2": "giả sử có một trận chiến đang chuẩn bị xảy ra, quân đội đang tập hợp. ",
  "sn3.24:2.3": "Lúc đó có một chàng trai Sát-đế-lỵ đến, đã qua huấn luyện, đã giỏi nghề, đã luyện tập, đã thành thạo, không nhút nhát, không sợ hãi, không bỏ chạy. ",
  "sn3.24:2.4": "Ngài có thuê mướn người đó không, ngài có cần người như vậy không?' ",
  "sn3.24:2.5": "'Thưa Ngài, tôi có thuê người đó, tôi có cần người như vậy.' ",
  "sn3.24:2.6": "'Lại có một chàng trai bà-la-môn... '",
  "sn3.24:2.7": "lại có một chàng trai dòng thương nhân... ",
  "sn3.24:2.8": "lại có một chàng trai dòng thấp hèn đến, đã qua huấn luyện, đã giỏi nghề, đã luyện tập, đã thành thạo, không nhút nhát, không sợ hãi, không bỏ chạy. ",
  "sn3.24:2.9": "Ngài có thuê mướn người đó không, ngài có cần người như vậy không?' ",
  "sn3.24:2.10": "'Thưa Ngài, tôi có thuê người đó, tôi có cần người như vậy.' ",
  "sn3.24:3.1": "'Cũng vậy, thưa Đại vương, dù người đó thuộc dòng dõi nào mà xuất gia từ gia đình trở thành người không nhà, nếu người đó đã từ bỏ năm chi phần và có đủ năm chi phần, thì bố thí cho người đó sẽ có quả lớn. '",
  "sn3.24:3.2": "Năm chi phần nào được từ bỏ? ",
  "sn3.24:3.3": "Dục tham được từ bỏ, sân được từ bỏ, hôn trầm thụy miên được từ bỏ, trạo hối được từ bỏ, nghi hoặc được từ bỏ. ",
  "sn3.24:3.4": "Đây là năm chi phần được từ bỏ. ",
  "sn3.24:3.5": "Người đó có đủ năm chi phần nào? ",
  "sn3.24:3.6": "Người đó có đủ giới uẩn của bậc vô học, có đủ định uẩn của bậc vô học, có đủ tuệ uẩn của bậc vô học, có đủ giải thoát uẩn của bậc vô học, có đủ giải thoát tri kiến uẩn của bậc vô học. ",
  "sn3.24:3.7": "Người đó có đủ năm chi phần này. ",
  "sn3.24:3.8": "Như vậy, bố thí cho người đã từ bỏ năm chi phần và có đủ năm chi phần sẽ có quả lớn.' ",
  "sn3.24:3.9": "Thế Tôn nói như vậy... ",
  "sn3.24:3.10": "bậc Đạo Sư: ",
  "sn3.24:4.1": "'Nếu thấy người trẻ có bắn cung, có sức lực và nghị lực, '",
  "sn3.24:4.2": "ở trong hàng ngũ quân đội; ",
  "sn3.24:4.3": "Vua cần chiến trận thì nuôi người đó, ",
  "sn3.24:4.4": "không phải vì họ anh hùng do dòng dõi. ",
  "sn3.24:5.1": "Cũng vậy, người có nhẫn nhục và hiền lành, ",
  "sn3.24:5.2": "có giáo pháp vững vàng; ",
  "sn3.24:5.3": "Người có đời sống cao quý, có trí tuệ, ",
  "sn3.24:5.4": "dù sinh ra trong gia đình thấp hèn cũng đáng được cúng dường. ",
  "sn3.24:6.1": "Hãy xây dựng nơi ẩn cư tốt đẹp, ",
  "sn3.24:6.2": "mời bậc đa văn trú ngụ; ",
  "sn3.24:6.3": "Hãy làm giếng nước ở nơi hoang vu, ",
  "sn3.24:6.4": "và làm cầu qua nơi hiểm trở. ",
  "sn3.24:7.1": "Hãy dâng cơm, nước uống, thức ăn, ",
  "sn3.24:7.2": "áo mặc, chỗ ngủ và chỗ ở; ",
  "sn3.24:7.3": "Dâng cho những bậc chân thật, ngay thẳng, ",
  "sn3.24:7.4": "với tâm hoan hỷ trong sáng. ",
  "sn3.24:8.1": "Ví như đám mây sấm vang, ",
  "sn3.24:8.2": "rực chớp sáng ngời, mưa xuống trăm trận; ",
  "sn3.24:8.3": "Làm đầy cả vùng đất cao lẫn thấp, ",
  "sn3.24:8.4": "mưa xuống khắp đất đai. ",
  "sn3.24:9.1": "Cũng vậy người có lòng tin, người nghe nhiều, ",
  "sn3.24:9.2": "chuẩn bị thức ăn rồi bố thí; ",
  "sn3.24:9.3": "Làm thỏa mãn những người ăn xin, ",
  "sn3.24:9.4": "với cơm và nước uống như người trí. ",
  "sn3.24:10.1": "Hoan hỷ bố thí rộng rãi, ",
  "sn3.24:10.2": "nói 'Hãy lấy! Hãy lấy!'; ",
  "sn3.24:10.3": "Tiếng nói đó như tiếng sấm của người ấy, ",
  "sn3.24:10.4": "như mưa của trời đổ xuống; ",
  "sn3.24:10.5": "Dòng phước đức phong phú ấy, ",
  "sn3.24:10.6": "đổ xuống trên người bố thí.",
  "sn3.25:0.1": "Tương Ưng Bộ 3.25 ",
  "sn3.25:0.2": "3. Phẩm Thứ Ba ",
  "sn3.25:0.3": "Kinh Ví Dụ Ngọn Núi ",
  "sn3.25:1.1": "Thuở đó, Đức Phật đang ngụ tại Xá Vệ. ",
  "sn3.25:1.2": "Thế Tôn nói với vua Pasenadi nước Kosala đang ngồi một bên: ",
  "sn3.25:1.3": "'Thưa Đại vương, ngài từ đâu đến vào ban ngày thế này?' ",
  "sn3.25:1.4": "'Thưa Ngài, những công việc triều chính của các vị vua Sát-đế-lỵ đã được tấn phong, kiêu ngạo vì quyền lực, tham đắm dục vọng, đã đạt được sự ổn định trong lãnh thổ, đang cai trị vùng đất rộng lớncon đang bận rộn với những công việc đó, thưa Ngài.' ",
  "sn3.25:2.1": "'Thưa Đại vương, ngài nghĩ sao, '",
  "sn3.25:2.2": "giả sử có người đến từ phương Đông, đáng tin cậy, đáng tín nhiệm. ",
  "sn3.25:2.3": "Người đó đến gặp ngài và nói: ",
  "sn3.25:2.4": "'Thưa Đại vương, xin ngài biết rằng, tôi đang đến từ phương Đông. '",
  "sn3.25:2.5": "Ở đó tôi thấy một ngọn núi to lớn cao ngang mây, đang nghiền nát tất cả sinh linh mà tiến đến. ",
  "sn3.25:2.6": "Thưa Đại vương, ngài hãy làm điều gì cần làm.' ",
  "sn3.25:2.7": "Rồi có người thứ hai đến từ phương Tây... ",
  "sn3.25:2.8": "rồi có người thứ ba đến từ phương Bắc... ",
  "sn3.25:2.9": "rồi có người thứ tư đến từ phương Nam, đáng tin cậy, đáng tín nhiệm. ",
  "sn3.25:2.10": "Người đó đến gặp ngài và nói: ",
  "sn3.25:2.11": "'Thưa Đại vương, xin ngài biết rằng, tôi đang đến từ phương Nam. '",
  "sn3.25:2.12": "Ở đó tôi thấy một ngọn núi to lớn cao ngang mây, đang nghiền nát tất cả sinh linh mà tiến đến. ",
  "sn3.25:2.13": "Thưa Đại vương, ngài hãy làm điều gì cần làm.' ",
  "sn3.25:2.14": "Thưa Đại vương, khi nguy hiểm to lớn như vậy xảy ra, khi sự hủy diệt khủng khiếp đối với con người xảy ra, khi thân người khó có được như vậy, thì ngài phải làm gì?' ",
  "sn3.25:3.1": "'Thưa Ngài, khi nguy hiểm to lớn như vậy xảy ra, khi sự hủy diệt khủng khiếp đối với con người xảy ra, khi thân người khó có được như vậy, thì con phải làm gì ngoài việc tu tập theo Giáo Pháp, tu tập hạnh thiện lành, làm việc lành, làm công đức phước báu?' ",
  "sn3.25:4.1": "'Thưa Đại vương, Ta nói với ngài, Ta tuyên bố với ngài, thưa Đại vương, già và chết đang tiến đến ngài. '",
  "sn3.25:4.2": "Thưa Đại vương, khi già và chết đang tiến đến ngài, thì ngài phải làm gì?' ",
  "sn3.25:4.3": "'Thưa Ngài, khi già và chết đang tiến đến con, thì con phải làm gì ngoài việc tu tập theo Giáo Pháp, tu tập hạnh thiện lành, làm việc lành, làm công đức phước báu? '",
  "sn3.25:4.4": "Thưa Ngài, những cuộc chiến trên lưng voi của các vị vua Sát-đế-lỵ đã được tấn phong, kiêu ngạo vì quyền lực, tham đắm dục vọng, đã đạt được sự ổn định trong lãnh thổ, đang cai trị vùng đất rộng lớn; ",
  "sn3.25:4.5": "thưa Ngài, khi già và chết đang tiến đến, những cuộc chiến trên lưng voi đó không có chỗ đứng, không có chỗ nương tựa. ",
  "sn3.25:4.6": "Thưa Ngài, những cuộc chiến... ",
  "sn3.25:4.7": "trên lưng ngựa... ",
  "sn3.25:4.8": "trên xe... ",
  "sn3.25:4.9": "của bộ binh; ",
  "sn3.25:4.10": "thưa Ngài, khi già và chết đang tiến đến, những cuộc chiến của bộ binh đó không có chỗ đứng, không có chỗ nương tựa. ",
  "sn3.25:4.11": "Thưa Ngài, trong triều đình này có những vị cố vấn, đại thần, có thể bẻ gãy kẻ thù đến bằng mưu kế. ",
  "sn3.25:4.12": "Thưa Ngài, khi già và chết đang tiến đến, những cuộc chiến bằng mưu kế đó không có chỗ đứng, không có chỗ nương tựa. ",
  "sn3.25:4.13": "Thưa Ngài, trong triều đình này có vàng bạc dồi dào, cả trong kho dưới đất lẫn trong kho trên không, với đó chúng tôi có thể dùng tiền của để thu phục kẻ thù đến. ",
  "sn3.25:4.14": "Thưa Ngài, khi già và chết đang tiến đến, những cuộc chiến bằng tiền của đó không có chỗ đứng, không có chỗ nương tựa. ",
  "sn3.25:4.15": "Thưa Ngài, khi già và chết đang tiến đến con, thì con phải làm gì ngoài việc tu tập theo Giáo Pháp, tu tập hạnh thiện lành, làm việc lành, làm công đức phước báu?' ",
  "sn3.25:5.1": "'Đúng vậy, thưa Đại vương! Đúng vậy, thưa Đại vương! '",
  "sn3.25:5.2": "Khi già và chết đang tiến đến, thì phải làm gì ngoài việc tu tập theo Giáo Pháp, tu tập hạnh thiện lành, làm việc lành, làm công đức phước báu?' ",
  "sn3.25:5.3": "Thế Tôn nói như vậy... ",
  "sn3.25:5.4": "bậc Đạo Sư: ",
  "sn3.25:6.1": "'Ví như những ngọn núi đồ sộ, '",
  "sn3.25:6.2": "chạm đến bầu trời, vươn lên cao; ",
  "sn3.25:6.3": "Từ bốn phía cùng kéo đến, ",
  "sn3.25:6.4": "nghiền nát mọi thứ theo bốn hướng. ",
  "sn3.25:7.1": "Cũng vậy già nua và cái chết, ",
  "sn3.25:7.2": "đang tiến đến mọi sinh linh; ",
  "sn3.25:7.3": "Sát-đế-lỵ, bà-la-môn, thương nhân, ",
  "sn3.25:7.4": "người thấp hèn, người hốt rác; ",
  "sn3.25:7.5": "Không loại trừ ai cả, ",
  "sn3.25:7.6": "nghiền nát tất cả mọi người. ",
  "sn3.25:8.1": "Ở đó không có chỗ cho đội voi, ",
  "sn3.25:8.2": "không có chỗ cho đội xe, không có chỗ cho bộ binh; ",
  "sn3.25:8.3": "Cũng không thể dùng mưu kế, ",
  "sn3.25:8.4": "hay tiền của mà thắng được. ",
  "sn3.25:9.1": "Vì vậy người trí, ",
  "sn3.25:9.2": "thấy rõ lợi ích của mình; ",
  "sn3.25:9.3": "Hãy đặt lòng tin vào Phật, Pháp và Tăng, ",
  "sn3.25:9.4": "người có trí tuệ hãy vững lòng tin. ",
  "sn3.25:10.1": "Ai tu tập Giáo Pháp bằng thân, ",
  "sn3.25:10.2": "bằng lời nói và bằng tâm ý; ",
  "sn3.25:10.3": "Ngay ở đây người đó được tán thán, ",
  "sn3.25:10.4": "và sau khi chết hoan hỷ trên cõi trời.",
  "sn3.25:10.5": "Phẩm Thứ Ba. ",
  "sn3.25:11.0": "Tóm tắt phẩm: ",
  "sn3.25:11.1": "Hạng người, bà nội, thế gian, ",
  "sn3.25:11.2": "nghề cung thủ, ví dụ ngọn núi; ",
  "sn3.25:11.3": "Được Đức Phật tối thượng giảng dạy, ",
  "sn3.25:11.4": "đây là năm kinh thuộc Kosala.",
  "sn3.25:11.5": "Tương Ưng Kosala kết thúc."
}
window.BILARA["sn3_v1"]["vi"]["sn3_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
