window.BILARA = window.BILARA || {};
window.BILARA["sn40_v1"] = window.BILARA["sn40_v1"] || {};
window.BILARA["sn40_v1"]["vi"] = {
  "sn40.1:0.1": "Tương Ưng Bộ 40.1 ",
  "sn40.1:0.2": "1. Phẩm Moggallāna ",
  "sn40.1:0.3": "Kinh Hỏi Về Sơ Thiền ",
  "sn40.1:1.1": "Một thời, Tôn giả Mahāmoggallāna trú tại Sāvatthī, rừng Jetavana, vườn ông Anāthapiṇḍika. ",
  "sn40.1:1.2": "Ở đó, Tôn giả Mahāmoggallāna gọi các Tỳ Kheo và nói: ",
  "sn40.1:1.3": "'Này các Hiền giả Tỳ Kheo.' ",
  "sn40.1:1.4": "'Thưa Hiền giả,' các Tỳ Kheo ấy đáp lại Tôn giả Mahāmoggallāna. ",
  "sn40.1:1.5": "Tôn giả Mahāmoggallāna nói điều này: ",
  "sn40.1:2.1": "'Ở đây, này các Hiền giả, khi tôi đang độc cư, ẩn mình tĩnh lặng, một suy tư như vậy đã khởi lên trong tâm tôi: '",
  "sn40.1:2.2": "'Sơ Thiền, Sơ Thiền', người ta nói vậy. ",
  "sn40.1:2.3": "Vậy thế nào là Sơ Thiền? ",
  "sn40.1:2.4": "Rồi, này các Hiền giả, tôi nghĩ như vầy: ",
  "sn40.1:2.5": "'Ở đây, Tỳ Kheo ly dục, ly các bất thiện pháp, chứng và trú Sơ Thiền, một trạng thái có tầm có tứ, với hỷ lạc do ly dục sinh. '",
  "sn40.1:2.6": "Đây gọi là Sơ Thiền.' ",
  "sn40.1:2.7": "Rồi, này các Hiền giả, tôi ly dục, ly các bất thiện pháp, chứng và trú Sơ Thiền, một trạng thái có tầm có tứ, với hỷ lạc do ly dục sinh. ",
  "sn40.1:2.8": "Nhưng, này các Hiền giả, trong khi tôi đang trú trong trạng thái ấy, các tưởng và tác ý liên hệ đến dục vọng vẫn còn khởi lên. ",
  "sn40.1:3.1": "Rồi, này các Hiền giả, Thế Tôn dùng thần thông đến gặp tôi và nói: ",
  "sn40.1:3.2": "'Moggallāna, Moggallāna. '",
  "sn40.1:3.3": "Này Bà-la-môn, chớ có phóng dật trong Sơ Thiền. Hãy an định tâm trong Sơ Thiền, hãy nhất tâm trong Sơ Thiền, hãy định tâm trong Sơ Thiền.' ",
  "sn40.1:3.4": "Rồi, này các Hiền giả, sau đó tôi ly dục, ly các bất thiện pháp, chứng và trú Sơ Thiền, một trạng thái có tầm có tứ, với hỷ lạc do ly dục sinh. ",
  "sn40.1:3.5": "Và ai nói đúng, này các Hiền giả: ",
  "sn40.1:3.6": "'Đệ tử được bậc Đạo Sư hỗ trợ đã đạt được thần thông lớn', thì người ấy nói đúng về tôi: ",
  "sn40.1:3.7": "'Đệ tử được bậc Đạo Sư hỗ trợ đã đạt được thần thông lớn.'' '",
  "sn40.1:3.8": "Thứ nhất. ",
  "sn40.2:0.1": "Tương Ưng Bộ 40.2 ",
  "sn40.2:0.2": "1. Phẩm Moggallāna ",
  "sn40.2:0.3": "Kinh Hỏi Về Nhị Thiền ",
  "sn40.2:1.1": "''Nhị Thiền, Nhị Thiền', người ta nói vậy. '",
  "sn40.2:1.2": "Vậy thế nào là Nhị Thiền? ",
  "sn40.2:1.3": "Rồi, này các Hiền giả, tôi nghĩ như vầy: ",
  "sn40.2:1.4": "'Ở đây, Tỳ Kheo do tầm tứ lắng dịu, nội tâm được tịnh tín, tâm chuyên nhất, không tầm không tứ, chứng và trú Nhị Thiền, với hỷ lạc do định sinh. '",
  "sn40.2:1.5": "Đây gọi là Nhị Thiền.' ",
  "sn40.2:1.6": "Rồi, này các Hiền giả, do tầm tứ lắng dịu, nội tâm được tịnh tín, tâm chuyên nhất, không tầm không tứ, tôi chứng và trú Nhị Thiền, với hỷ lạc do định sinh. ",
  "sn40.2:1.7": "Nhưng, này các Hiền giả, trong khi tôi đang trú trong trạng thái ấy, các tưởng và tác ý liên hệ đến tầm vẫn còn khởi lên. ",
  "sn40.2:2.1": "Rồi, này các Hiền giả, Thế Tôn dùng thần thông đến gặp tôi và nói: ",
  "sn40.2:2.2": "'Moggallāna, Moggallāna. '",
  "sn40.2:2.3": "Này Bà-la-môn, chớ có phóng dật trong Nhị Thiền. Hãy an định tâm trong Nhị Thiền, hãy nhất tâm trong Nhị Thiền, hãy định tâm trong Nhị Thiền.' ",
  "sn40.2:2.4": "Rồi, này các Hiền giả, sau đó do tầm tứ lắng dịu, nội tâm được tịnh tín, tâm chuyên nhất, không tầm không tứ, tôi chứng và trú Nhị Thiền, với hỷ lạc do định sinh. ",
  "sn40.2:2.5": "Và ai nói đúng, này các Hiền giả: ",
  "sn40.2:2.6": "'Đệ tử được bậc Đạo Sư hỗ trợ đã đạt được thần thông lớn', thì người ấy nói đúng về tôi: ",
  "sn40.2:2.7": "'Đệ tử được bậc Đạo Sư hỗ trợ đã đạt được thần thông lớn.'' '",
  "sn40.2:2.8": "Thứ hai. ",
  "sn40.3:0.1": "Tương Ưng Bộ 40.3 ",
  "sn40.3:0.2": "1. Phẩm Moggallāna ",
  "sn40.3:0.3": "Kinh Hỏi Về Tam Thiền ",
  "sn40.3:1.1": "''Tam Thiền, Tam Thiền', người ta nói vậy. '",
  "sn40.3:1.2": "Vậy thế nào là Tam Thiền? ",
  "sn40.3:1.3": "Rồi, này các Hiền giả, tôi nghĩ như vầy ",
  "sn40.3:1.4": "Ở đây, Tỳ Kheo ly hỷ, trú xả, chánh niệm tỉnh giác, thân cảm thọ lạc, đúng như lời bậc Thánh tuyên bố: 'Xả ly, có niệm, an trú lạc', chứng và trú Tam Thiền. ",
  "sn40.3:1.5": "Đây gọi là Tam Thiền. ",
  "sn40.3:1.6": "Rồi, này các Hiền giả, tôi ly hỷ, trú xả, chánh niệm tỉnh giác, thân cảm thọ lạc, đúng như lời bậc Thánh tuyên bố: 'Xả ly, có niệm, an trú lạc', tôi chứng và trú Tam Thiền. ",
  "sn40.3:1.7": "Nhưng, này các Hiền giả, trong khi tôi đang trú trong trạng thái ấy, các tưởng và tác ý liên hệ đến hỷ vẫn còn khởi lên. ",
  "sn40.3:2.1": "Rồi, này các Hiền giả, Thế Tôn dùng thần thông đến gặp tôi và nói: ",
  "sn40.3:2.2": "'Moggallāna, Moggallāna. '",
  "sn40.3:2.3": "Này Bà-la-môn, chớ có phóng dật trong Tam Thiền. Hãy an định tâm trong Tam Thiền, hãy nhất tâm trong Tam Thiền, hãy định tâm trong Tam Thiền.' ",
  "sn40.3:2.4": "Rồi, này các Hiền giả, sau đó tôi ly hỷ, trú xả, chánh niệm tỉnh giác, thân cảm thọ lạc, đúng như lời bậc Thánh tuyên bố: 'Xả ly, có niệm, an trú lạc', tôi chứng và trú Tam Thiền. ",
  "sn40.3:2.5": "Và ai nói đúng, này các Hiền giả …pe… đã đạt được thần thông lớn.' ",
  "sn40.3:2.6": "Thứ ba. ",
  "sn40.4:0.1": "Tương Ưng Bộ 40.4 ",
  "sn40.4:0.2": "1. Phẩm Moggallāna ",
  "sn40.4:0.3": "Kinh Hỏi Về Tứ Thiền ",
  "sn40.4:1.1": "''Tứ Thiền, Tứ Thiền', người ta nói vậy. '",
  "sn40.4:1.2": "Vậy thế nào là Tứ Thiền? ",
  "sn40.4:1.3": "Rồi, này các Hiền giả, tôi nghĩ như vầy: ",
  "sn40.4:1.4": "'Ở đây, Tỳ Kheo đoạn trừ lạc, đoạn trừ khổ, trước đó hỷ và ưu đã diệt, chứng và trú Tứ Thiền, không khổ không lạc, xả niệm thanh tịnh. '",
  "sn40.4:1.5": "Đây gọi là Tứ Thiền.' ",
  "sn40.4:1.6": "Rồi, này các Hiền giả, tôi đoạn trừ lạc, đoạn trừ khổ, trước đó hỷ và ưu đã diệt, tôi chứng và trú Tứ Thiền, không khổ không lạc, xả niệm thanh tịnh. ",
  "sn40.4:1.7": "Nhưng, này các Hiền giả, trong khi tôi đang trú trong trạng thái ấy, các tưởng và tác ý liên hệ đến lạc vẫn còn khởi lên. ",
  "sn40.4:2.1": "Rồi, này các Hiền giả, Thế Tôn dùng thần thông đến gặp tôi và nói: ",
  "sn40.4:2.2": "'Moggallāna, Moggallāna. '",
  "sn40.4:2.3": "Này Bà-la-môn, chớ có phóng dật trong Tứ Thiền. Hãy an định tâm trong Tứ Thiền, hãy nhất tâm trong Tứ Thiền, hãy định tâm trong Tứ Thiền.' ",
  "sn40.4:2.4": "Rồi, này các Hiền giả, sau đó tôi đoạn trừ lạc, đoạn trừ khổ, trước đó hỷ và ưu đã diệt, tôi chứng và trú Tứ Thiền, không khổ không lạc, xả niệm thanh tịnh. ",
  "sn40.4:2.5": "Và ai nói đúng, này các Hiền giả …pe… đã đạt được thần thông lớn.' ",
  "sn40.4:2.6": "Thứ tư. ",
  "sn40.5:0.1": "Tương Ưng Bộ 40.5 ",
  "sn40.5:0.2": "1. Phẩm Moggallāna ",
  "sn40.5:0.3": "Kinh Hỏi Về Không Vô Biên Xứ ",
  "sn40.5:1.1": "''Không Vô Biên Xứ, Không Vô Biên Xứ', người ta nói vậy. '",
  "sn40.5:1.2": "Vậy thế nào là Không Vô Biên Xứ? ",
  "sn40.5:1.3": "Rồi, này các Hiền giả, tôi nghĩ như vầy: ",
  "sn40.5:1.4": "'Ở đây, Tỳ Kheo vượt qua hoàn toàn các sắc tưởng, diệt các tưởng chướng ngại, không tác ý các tưởng sai biệt, với niệm 'hư không là vô biên', chứng và trú Không Vô Biên Xứ. '",
  "sn40.5:1.5": "Đây gọi là Không Vô Biên Xứ.' ",
  "sn40.5:1.6": "Rồi, này các Hiền giả, tôi vượt qua hoàn toàn các sắc tưởng, diệt các tưởng chướng ngại, không tác ý các tưởng sai biệt, với niệm 'hư không là vô biên', tôi chứng và trú Không Vô Biên Xứ. ",
  "sn40.5:1.7": "Nhưng, này các Hiền giả, trong khi tôi đang trú trong trạng thái ấy, các tưởng và tác ý liên hệ đến sắc vẫn còn khởi lên. ",
  "sn40.5:2.1": "Rồi, này các Hiền giả, Thế Tôn dùng thần thông đến gặp tôi và nói: ",
  "sn40.5:2.2": "'Moggallāna, Moggallāna. '",
  "sn40.5:2.3": "Này Bà-la-môn, chớ có phóng dật trong Không Vô Biên Xứ. Hãy an định tâm trong Không Vô Biên Xứ, hãy nhất tâm trong Không Vô Biên Xứ, hãy định tâm trong Không Vô Biên Xứ.' ",
  "sn40.5:2.4": "Rồi, này các Hiền giả, sau đó tôi vượt qua hoàn toàn các sắc tưởng, diệt các tưởng chướng ngại, không tác ý các tưởng sai biệt, với niệm 'hư không là vô biên', tôi chứng và trú Không Vô Biên Xứ. ",
  "sn40.5:2.5": "Và ai nói đúng, này các Hiền giả …pe… đã đạt được thần thông lớn.' ",
  "sn40.5:2.6": "Thứ năm. ",
  "sn40.6:0.1": "Tương Ưng Bộ 40.6 ",
  "sn40.6:0.2": "1. Phẩm Moggallāna ",
  "sn40.6:0.3": "Kinh Hỏi Về Thức Vô Biên Xứ ",
  "sn40.6:1.1": "''Thức Vô Biên Xứ, Thức Vô Biên Xứ', người ta nói vậy. '",
  "sn40.6:1.2": "Vậy thế nào là Thức Vô Biên Xứ? ",
  "sn40.6:1.3": "Rồi, này các Hiền giả, tôi nghĩ như vầy: ",
  "sn40.6:1.4": "'Ở đây, Tỳ Kheo vượt qua hoàn toàn Không Vô Biên Xứ, với niệm 'thức là vô biên', chứng và trú Thức Vô Biên Xứ. '",
  "sn40.6:1.5": "Đây gọi là Thức Vô Biên Xứ.' ",
  "sn40.6:1.6": "Rồi, này các Hiền giả, tôi vượt qua hoàn toàn Không Vô Biên Xứ, với niệm 'thức là vô biên', tôi chứng và trú Thức Vô Biên Xứ. ",
  "sn40.6:1.7": "Nhưng, này các Hiền giả, trong khi tôi đang trú trong trạng thái ấy, các tưởng và tác ý liên hệ đến Không Vô Biên Xứ vẫn còn khởi lên. ",
  "sn40.6:2.1": "Rồi, này các Hiền giả, Thế Tôn dùng thần thông đến gặp tôi và nói: ",
  "sn40.6:2.2": "'Moggallāna, Moggallāna. '",
  "sn40.6:2.3": "Này Bà-la-môn, chớ có phóng dật trong Thức Vô Biên Xứ. Hãy an định tâm trong Thức Vô Biên Xứ, hãy nhất tâm trong Thức Vô Biên Xứ, hãy định tâm trong Thức Vô Biên Xứ.' ",
  "sn40.6:2.4": "Rồi, này các Hiền giả, sau đó tôi vượt qua hoàn toàn Không Vô Biên Xứ, với niệm 'thức là vô biên', tôi chứng và trú Thức Vô Biên Xứ. ",
  "sn40.6:2.5": "Và ai nói đúng, này các Hiền giả …pe… đã đạt được thần thông lớn.' ",
  "sn40.6:2.6": "Thứ sáu. ",
  "sn40.7:0.1": "Tương Ưng Bộ 40.7 ",
  "sn40.7:0.2": "1. Phẩm Moggallāna ",
  "sn40.7:0.3": "Kinh Hỏi Về Vô Sở Hữu Xứ ",
  "sn40.7:1.1": "''Vô Sở Hữu Xứ, Vô Sở Hữu Xứ', người ta nói vậy. '",
  "sn40.7:1.2": "Vậy thế nào là Vô Sở Hữu Xứ? ",
  "sn40.7:1.3": "Rồi, này các Hiền giả, tôi nghĩ như vầy: ",
  "sn40.7:1.4": "'Ở đây, Tỳ Kheo vượt qua hoàn toàn Thức Vô Biên Xứ, với niệm 'không có gì cả', chứng và trú Vô Sở Hữu Xứ. '",
  "sn40.7:1.5": "Đây gọi là Vô Sở Hữu Xứ.' ",
  "sn40.7:1.6": "Rồi, này các Hiền giả, tôi vượt qua hoàn toàn Thức Vô Biên Xứ, với niệm 'không có gì cả', tôi chứng và trú Vô Sở Hữu Xứ. ",
  "sn40.7:1.7": "Nhưng, này các Hiền giả, trong khi tôi đang trú trong trạng thái ấy, các tưởng và tác ý liên hệ đến Thức Vô Biên Xứ vẫn còn khởi lên. ",
  "sn40.7:2.1": "Rồi, này các Hiền giả, Thế Tôn dùng thần thông đến gặp tôi và nói: ",
  "sn40.7:2.2": "'Moggallāna, Moggallāna. '",
  "sn40.7:2.3": "Này Bà-la-môn, chớ có phóng dật trong Vô Sở Hữu Xứ. Hãy an định tâm trong Vô Sở Hữu Xứ, hãy nhất tâm trong Vô Sở Hữu Xứ, hãy định tâm trong Vô Sở Hữu Xứ.' ",
  "sn40.7:2.4": "Rồi, này các Hiền giả, sau đó tôi vượt qua hoàn toàn Thức Vô Biên Xứ, với niệm 'không có gì cả', tôi chứng và trú Vô Sở Hữu Xứ. ",
  "sn40.7:2.5": "Và ai nói đúng, này các Hiền giả …pe… đã đạt được thần thông lớn.' ",
  "sn40.7:2.6": "Thứ bảy. ",
  "sn40.8:0.1": "Tương Ưng Bộ 40.8 ",
  "sn40.8:0.2": "1. Phẩm Moggallāna ",
  "sn40.8:0.3": "Kinh Hỏi Về Phi Tưởng Phi Phi Tưởng Xứ ",
  "sn40.8:1.1": "''Phi Tưởng Phi Phi Tưởng Xứ, Phi Tưởng Phi Phi Tưởng Xứ', người ta nói vậy. '",
  "sn40.8:1.2": "Vậy thế nào là Phi Tưởng Phi Phi Tưởng Xứ? ",
  "sn40.8:1.3": "Rồi, này các Hiền giả, tôi nghĩ như vầy: ",
  "sn40.8:1.4": "'Ở đây, Tỳ Kheo vượt qua hoàn toàn Vô Sở Hữu Xứ, chứng và trú Phi Tưởng Phi Phi Tưởng Xứ. '",
  "sn40.8:1.5": "Đây gọi là Phi Tưởng Phi Phi Tưởng Xứ.' ",
  "sn40.8:1.6": "Rồi, này các Hiền giả, tôi vượt qua hoàn toàn Vô Sở Hữu Xứ, tôi chứng và trú Phi Tưởng Phi Phi Tưởng Xứ. ",
  "sn40.8:1.7": "Nhưng, này các Hiền giả, trong khi tôi đang trú trong trạng thái ấy, các tưởng và tác ý liên hệ đến Vô Sở Hữu Xứ vẫn còn khởi lên. ",
  "sn40.8:2.1": "Rồi, này các Hiền giả, Thế Tôn dùng thần thông đến gặp tôi và nói: ",
  "sn40.8:2.2": "'Moggallāna, Moggallāna. '",
  "sn40.8:2.3": "Này Bà-la-môn, chớ có phóng dật trong Phi Tưởng Phi Phi Tưởng Xứ. Hãy an định tâm trong Phi Tưởng Phi Phi Tưởng Xứ, hãy nhất tâm trong Phi Tưởng Phi Phi Tưởng Xứ, hãy định tâm trong Phi Tưởng Phi Phi Tưởng Xứ.' ",
  "sn40.8:2.4": "Rồi, này các Hiền giả, sau đó tôi vượt qua hoàn toàn Vô Sở Hữu Xứ, tôi chứng và trú Phi Tưởng Phi Phi Tưởng Xứ. ",
  "sn40.8:2.5": "Và ai nói đúng, này các Hiền giả …pe… đã đạt được thần thông lớn.' ",
  "sn40.8:2.6": "Thứ tám. ",
  "sn40.9:0.1": "Tương Ưng Bộ 40.9 ",
  "sn40.9:0.2": "1. Phẩm Moggallāna ",
  "sn40.9:0.3": "Kinh Hỏi Về Vô Tướng Tâm Định ",
  "sn40.9:1.1": "''Vô Tướng Tâm Định, Vô Tướng Tâm Định', người ta nói vậy. '",
  "sn40.9:1.2": "Vậy thế nào là Vô Tướng Tâm Định? ",
  "sn40.9:1.3": "Rồi, này các Hiền giả, tôi nghĩ như vầy: ",
  "sn40.9:1.4": "'Ở đây, Tỳ Kheo không tác ý tất cả các tướng, chứng và trú Vô Tướng Tâm Định. '",
  "sn40.9:1.5": "Đây gọi là Vô Tướng Tâm Định.' ",
  "sn40.9:1.6": "Rồi, này các Hiền giả, không tác ý tất cả các tướng, tôi chứng và trú Vô Tướng Tâm Định. ",
  "sn40.9:1.7": "Nhưng, này các Hiền giả, trong khi tôi đang trú trong trạng thái ấy, thức của tôi chạy theo các tướng. ",
  "sn40.9:2.1": "Rồi, này các Hiền giả, Thế Tôn dùng thần thông đến gặp tôi và nói: ",
  "sn40.9:2.2": "'Moggallāna, Moggallāna. '",
  "sn40.9:2.3": "Này Bà-la-môn, chớ có phóng dật trong Vô Tướng Tâm Định. Hãy an định tâm trong Vô Tướng Tâm Định, hãy nhất tâm trong Vô Tướng Tâm Định, hãy định tâm trong Vô Tướng Tâm Định.' ",
  "sn40.9:2.4": "Rồi, này các Hiền giả, sau đó không tác ý tất cả các tướng, tôi chứng và trú Vô Tướng Tâm Định. ",
  "sn40.9:2.5": "Và ai nói đúng, này các Hiền giả: ",
  "sn40.9:2.6": "'Đệ tử được bậc Đạo Sư hỗ trợ đã đạt được thần thông lớn', thì người ấy nói đúng về tôi: ",
  "sn40.9:2.7": "'Đệ tử được bậc Đạo Sư hỗ trợ đã đạt được thần thông lớn.'' '",
  "sn40.9:2.8": "Thứ chín. ",
  "sn40.10:0.1": "Tương Ưng Bộ 40.10 ",
  "sn40.10:0.2": "1. Phẩm Moggallāna ",
  "sn40.10:0.3": "Kinh Sakka ",
  "sn40.10:1.1": "Bấy giờ, Tôn giả Mahāmoggallānacũng như một người lực sĩ duỗi cánh tay đang co lại hoặc co cánh tay đang duỗi rabiến mất khỏi rừng Jetavana và xuất hiện giữa chư thiên cõi Đao Lợi. ",
  "sn40.10:1.2": "Rồi Thiên Đế Sakka cùng với năm trăm chư thiên đến gặp Tôn giả Mahāmoggallāna; sau khi đến, đảnh lễ Tôn giả Mahāmoggallāna rồi đứng một bên. Đứng một bên, Tôn giả Mahāmoggallāna nói với Thiên Đế Sakka rằng: ",
  "sn40.10:2.1": "'Lành thay, thưa Thiên Đế, là sự quy y Phật. '",
  "sn40.10:2.2": "Do nhân quy y Phật, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:2.3": "Lành thay, thưa Thiên Đế, là sự quy y Pháp. ",
  "sn40.10:2.4": "Do nhân quy y Pháp, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:2.5": "Lành thay, thưa Thiên Đế, là sự quy y Tăng. ",
  "sn40.10:2.6": "Do nhân quy y Tăng, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời.' ",
  "sn40.10:3.1": "'Lành thay, thưa Hiền giả Moggallāna, là sự quy y Phật. '",
  "sn40.10:3.2": "Do nhân quy y Phật, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:3.3": "Lành thay, thưa Hiền giả Moggallāna, là sự quy y Pháp. ",
  "sn40.10:3.4": "Do nhân quy y Pháp, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:3.5": "Lành thay, thưa Hiền giả Moggallāna, là sự quy y Tăng …pe… ",
  "sn40.10:3.6": "được tái sinh vào cõi thiện, cõi trời.' ",
  "sn40.10:4.1": "Rồi Thiên Đế Sakka cùng với sáu trăm chư thiên …pe… ",
  "sn40.10:4.2": "rồi Thiên Đế Sakka cùng với bảy trăm chư thiên …pe… ",
  "sn40.10:4.3": "rồi Thiên Đế Sakka cùng với tám trăm chư thiên …pe… ",
  "sn40.10:4.4": "rồi Thiên Đế Sakka cùng với tám mươi ngàn chư thiên đến gặp Tôn giả Mahāmoggallāna; sau khi đến, đảnh lễ Tôn giả Mahāmoggallāna rồi đứng một bên. Đứng một bên, Tôn giả Mahāmoggallāna nói với Thiên Đế Sakka rằng: ",
  "sn40.10:5.1": "'Lành thay, thưa Thiên Đế, là sự quy y Phật. '",
  "sn40.10:5.2": "Do nhân quy y Phật, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:5.3": "Lành thay, thưa Thiên Đế, là sự quy y Pháp. ",
  "sn40.10:5.4": "Do nhân quy y Pháp, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:5.5": "Lành thay, thưa Thiên Đế, là sự quy y Tăng. ",
  "sn40.10:5.6": "Do nhân quy y Tăng, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời.' ",
  "sn40.10:6.1": "'Lành thay, thưa Hiền giả Moggallāna, là sự quy y Phật. '",
  "sn40.10:6.2": "Do nhân quy y Phật, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:6.3": "Lành thay, thưa Hiền giả Moggallāna, là sự quy y Pháp …pe… ",
  "sn40.10:6.4": "lành thay, thưa Hiền giả Moggallāna, là sự quy y Tăng. ",
  "sn40.10:6.5": "Do nhân quy y Tăng, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời.' ",
  "sn40.10:7.1": "Rồi Thiên Đế Sakka cùng với năm trăm chư thiên đến gặp Tôn giả Mahāmoggallāna; sau khi đến, đảnh lễ Tôn giả Mahāmoggallāna rồi đứng một bên. Đứng một bên, Tôn giả Mahāmoggallāna nói với Thiên Đế Sakka rằng: ",
  "sn40.10:8.1": "'Lành thay, thưa Thiên Đế, là có được tịnh tín bất động đối với Phật: '",
  "sn40.10:8.2": "'Đây là Thế Tôn, bậc Ứng Cúng, Chánh Biến Tri, Minh Hạnh Túc, Thiện Thệ, Thế Gian Giải, Vô Thượng Sĩ Điều Ngự Trượng Phu, Thiên Nhân Sư, Phật, Thế Tôn.' ",
  "sn40.10:8.3": "Do nhân có được tịnh tín bất động đối với Phật, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:9.1": "Lành thay, thưa Thiên Đế, là có được tịnh tín bất động đối với Pháp: ",
  "sn40.10:9.2": "'Pháp được Thế Tôn khéo thuyết, thiết thực, vượt thời gian, đến để thấy, hướng thượng, được người trí tự mình chứng nghiệm.' ",
  "sn40.10:9.3": "Do nhân có được tịnh tín bất động đối với Pháp, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:10.1": "Lành thay, thưa Thiên Đế, là có được tịnh tín bất động đối với Tăng: ",
  "sn40.10:10.2": "'Tăng chúng đệ tử Thế Tôn hành trì thiện, hành trì chánh trực, hành trì đúng pháp, hành trì hợp lễ, tức là bốn đôi tám vị; Tăng chúng đệ tử Thế Tôn này xứng đáng cúng dường, xứng đáng tiếp đón, xứng đáng cúng thí, xứng đáng chắp tay, là phước điền vô thượng ở đời.' ",
  "sn40.10:10.3": "Do nhân có được tịnh tín bất động đối với Tăng, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:11.1": "Lành thay, thưa Thiên Đế, là có đầy đủ các giới được bậc Thánh ái mộ, không bị bẻ vỡ, không bị đứt đoạn, không bị tỳ vết, không bị ô nhiễm, thuộc người tự do, được người trí khen ngợi, không bị chấp thủ, đưa đến định. ",
  "sn40.10:11.2": "Do nhân có đầy đủ các giới được bậc Thánh ái mộ, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời.' ",
  "sn40.10:12.1": "'Lành thay, thưa Hiền giả Moggallāna, là có được tịnh tín bất động đối với Phật: '",
  "sn40.10:12.2": "'Đây là Thế Tôn …pe… Thiên Nhân Sư, Phật, Thế Tôn.' ",
  "sn40.10:12.3": "Do nhân có được tịnh tín bất động đối với Phật, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:13.1": "Lành thay, thưa Hiền giả Moggallāna, là có được tịnh tín bất động đối với Pháp: ",
  "sn40.10:13.2": "'Pháp được Thế Tôn khéo thuyết …pe… được người trí tự mình chứng nghiệm.' ",
  "sn40.10:13.3": "Do nhân có được tịnh tín bất động đối với Pháp, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:14.1": "Lành thay, thưa Hiền giả Moggallāna, là có được tịnh tín bất động đối với Tăng: ",
  "sn40.10:14.2": "'Tăng chúng đệ tử Thế Tôn hành trì thiện …pe… là phước điền vô thượng ở đời.' ",
  "sn40.10:14.3": "Do nhân có được tịnh tín bất động đối với Tăng, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:15.1": "Lành thay, thưa Hiền giả Moggallāna, là có đầy đủ các giới được bậc Thánh ái mộ, không bị bẻ vỡ …pe… đưa đến định. ",
  "sn40.10:15.2": "Do nhân có đầy đủ các giới được bậc Thánh ái mộ, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời.' ",
  "sn40.10:16.1": "Rồi Thiên Đế Sakka cùng với sáu trăm chư thiên …pe… ",
  "sn40.10:16.2": "rồi Thiên Đế Sakka cùng với bảy trăm chư thiên …pe… ",
  "sn40.10:16.3": "rồi Thiên Đế Sakka cùng với tám trăm chư thiên …pe… ",
  "sn40.10:16.4": "rồi Thiên Đế Sakka cùng với tám mươi ngàn chư thiên đến gặp Tôn giả Mahāmoggallāna; sau khi đến, đảnh lễ Tôn giả Mahāmoggallāna rồi đứng một bên. Đứng một bên, Tôn giả Mahāmoggallāna nói với Thiên Đế Sakka rằng: ",
  "sn40.10:17.1": "'Lành thay, thưa Thiên Đế, là có được tịnh tín bất động đối với Phật: '",
  "sn40.10:17.2": "'Đây là Thế Tôn …pe… Thiên Nhân Sư, Phật, Thế Tôn.' ",
  "sn40.10:17.3": "Do nhân có được tịnh tín bất động đối với Phật, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:18.1": "Lành thay, thưa Thiên Đế, là có được tịnh tín bất động đối với Pháp: ",
  "sn40.10:18.2": "'Pháp được Thế Tôn khéo thuyết …pe… được người trí tự mình chứng nghiệm.' ",
  "sn40.10:18.3": "Do nhân có được tịnh tín bất động đối với Pháp, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:19.1": "Lành thay, thưa Thiên Đế, là có được tịnh tín bất động đối với Tăng: ",
  "sn40.10:19.2": "'Tăng chúng đệ tử Thế Tôn hành trì thiện …pe… là phước điền vô thượng ở đời.' ",
  "sn40.10:19.3": "Do nhân có được tịnh tín bất động đối với Tăng, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:20.1": "Lành thay, thưa Thiên Đế, là có đầy đủ các giới được bậc Thánh ái mộ, không bị bẻ vỡ …pe… đưa đến định. ",
  "sn40.10:20.2": "Do nhân có đầy đủ các giới được bậc Thánh ái mộ, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời.' ",
  "sn40.10:21.1": "'Lành thay, thưa Hiền giả Moggallāna, là có được tịnh tín bất động đối với Phật: '",
  "sn40.10:21.2": "'Đây là Thế Tôn …pe… Thiên Nhân Sư, Phật, Thế Tôn.' ",
  "sn40.10:21.3": "Do nhân có được tịnh tín bất động đối với Phật, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:22.1": "Lành thay, thưa Hiền giả Moggallāna, là có được tịnh tín bất động đối với Pháp: ",
  "sn40.10:22.2": "'Pháp được Thế Tôn khéo thuyết …pe… được người trí tự mình chứng nghiệm.' ",
  "sn40.10:22.3": "Do nhân có được tịnh tín bất động đối với Pháp, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:23.1": "Lành thay, thưa Hiền giả Moggallāna, là có được tịnh tín bất động đối với Tăng: ",
  "sn40.10:23.2": "'Tăng chúng đệ tử Thế Tôn hành trì thiện …pe… là phước điền vô thượng ở đời.' ",
  "sn40.10:23.3": "Do nhân có được tịnh tín bất động đối với Tăng, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:24.1": "Lành thay, thưa Hiền giả Moggallāna, là có đầy đủ các giới được bậc Thánh ái mộ, không bị bẻ vỡ …pe… đưa đến định. ",
  "sn40.10:24.2": "Do nhân có đầy đủ các giới được bậc Thánh ái mộ, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời.' ",
  "sn40.10:25.1": "Rồi Thiên Đế Sakka cùng với năm trăm chư thiên đến gặp Tôn giả Mahāmoggallāna …pe… ",
  "sn40.10:25.2": "đứng một bên, Tôn giả Mahāmoggallāna nói với Thiên Đế Sakka rằng: ",
  "sn40.10:26.1": "'Lành thay, thưa Thiên Đế, là sự quy y Phật. '",
  "sn40.10:26.2": "Do nhân quy y Phật, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:26.3": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:26.4": "về thiên thọ, về thiên sắc, về thiên lạc, về thiên danh, về thiên quyền lực, về hình sắc cõi trời, về âm thanh cõi trời, về hương thơm cõi trời, về vị ngọt cõi trời, về xúc chạm cõi trời. ",
  "sn40.10:27.1": "Lành thay, thưa Thiên Đế, là sự quy y Pháp. ",
  "sn40.10:27.2": "Do nhân quy y Pháp, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:27.3": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:27.4": "về thiên thọ, về thiên sắc, về thiên lạc, về thiên danh, về thiên quyền lực, về hình sắc cõi trời, về âm thanh cõi trời, về hương thơm cõi trời, về vị ngọt cõi trời, về xúc chạm cõi trời. ",
  "sn40.10:28.1": "Lành thay, thưa Thiên Đế, là sự quy y Tăng. ",
  "sn40.10:28.2": "Do nhân quy y Tăng, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:28.3": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:28.4": "về thiên thọ, về thiên sắc, về thiên lạc, về thiên danh, về thiên quyền lực, về hình sắc cõi trời, về âm thanh cõi trời, về hương thơm cõi trời, về vị ngọt cõi trời, về xúc chạm cõi trời.' ",
  "sn40.10:29.1": "'Lành thay, thưa Hiền giả Moggallāna, là sự quy y Phật. '",
  "sn40.10:29.2": "Do nhân quy y Phật, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:29.3": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:29.4": "về thiên thọ …pe… về xúc chạm cõi trời. ",
  "sn40.10:30.1": "Lành thay, thưa Hiền giả Moggallāna, là sự quy y Pháp …pe…. ",
  "sn40.10:31.1": "Lành thay, thưa Hiền giả Moggallāna, là sự quy y Tăng. ",
  "sn40.10:31.2": "Do nhân quy y Tăng, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:31.3": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:31.4": "về thiên thọ, về thiên sắc, về thiên lạc, về thiên danh, về thiên quyền lực, về hình sắc cõi trời, về âm thanh cõi trời, về hương thơm cõi trời, về vị ngọt cõi trời, về xúc chạm cõi trời.' ",
  "sn40.10:32.1": "Rồi Thiên Đế Sakka cùng với sáu trăm chư thiên …pe… ",
  "sn40.10:32.2": "rồi Thiên Đế Sakka cùng với bảy trăm chư thiên …pe… ",
  "sn40.10:32.3": "rồi Thiên Đế Sakka cùng với tám trăm chư thiên …pe… ",
  "sn40.10:32.4": "rồi Thiên Đế Sakka cùng với tám mươi ngàn chư thiên đến gặp Tôn giả Mahāmoggallāna; sau khi đến, đảnh lễ Tôn giả Mahāmoggallāna rồi đứng một bên. Đứng một bên, Tôn giả Mahāmoggallāna nói với Thiên Đế Sakka rằng: ",
  "sn40.10:33.1": "'Lành thay, thưa Thiên Đế, là sự quy y Phật. '",
  "sn40.10:33.2": "Do nhân quy y Phật, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:33.3": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:33.4": "về thiên thọ …pe… về xúc chạm cõi trời. ",
  "sn40.10:34.1": "Lành thay, thưa Thiên Đế, là sự quy y Pháp …pe…. ",
  "sn40.10:35.1": "Lành thay, thưa Thiên Đế, là sự quy y Tăng. ",
  "sn40.10:35.2": "Do nhân quy y Tăng, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:35.3": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:35.4": "về thiên thọ, về thiên sắc, về thiên lạc, về thiên danh, về thiên quyền lực, về hình sắc cõi trời, về âm thanh cõi trời, về hương thơm cõi trời, về vị ngọt cõi trời, về xúc chạm cõi trời.' ",
  "sn40.10:36.1": "'Lành thay, thưa Hiền giả Moggallāna, là sự quy y Phật …pe… '",
  "sn40.10:36.2": "lành thay, thưa Hiền giả Moggallāna, là sự quy y Pháp …pe… ",
  "sn40.10:36.3": "lành thay, thưa Hiền giả Moggallāna, là sự quy y Tăng. ",
  "sn40.10:36.4": "Do nhân quy y Tăng, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:36.5": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:36.6": "về thiên thọ, về thiên sắc, về thiên lạc, về thiên danh, về thiên quyền lực, về hình sắc cõi trời, về âm thanh cõi trời, về hương thơm cõi trời, về vị ngọt cõi trời, về xúc chạm cõi trời.' ",
  "sn40.10:37.1": "Rồi Thiên Đế Sakka cùng với năm trăm chư thiên đến gặp Tôn giả Mahāmoggallāna; sau khi đến, đảnh lễ Tôn giả Mahāmoggallāna rồi đứng một bên. Đứng một bên, Tôn giả Mahāmoggallāna nói với Thiên Đế Sakka rằng: ",
  "sn40.10:38.1": "'Lành thay, thưa Thiên Đế, là có được tịnh tín bất động đối với Phật: '",
  "sn40.10:38.2": "'Đây là Thế Tôn …pe… Thiên Nhân Sư, Phật, Thế Tôn.' ",
  "sn40.10:38.3": "Do nhân có được tịnh tín bất động đối với Phật, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:38.4": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:38.5": "về thiên thọ …pe… về xúc chạm cõi trời. ",
  "sn40.10:39.1": "Lành thay, thưa Thiên Đế, là có được tịnh tín bất động đối với Pháp: ",
  "sn40.10:39.2": "'Pháp được Thế Tôn khéo thuyết …pe… được người trí tự mình chứng nghiệm.' ",
  "sn40.10:39.3": "Do nhân có được tịnh tín bất động đối với Pháp, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời …pe…. ",
  "sn40.10:40.1": "Lành thay, thưa Thiên Đế, là có được tịnh tín bất động đối với Tăng: ",
  "sn40.10:40.2": "'Tăng chúng đệ tử Thế Tôn hành trì thiện …pe… là phước điền vô thượng ở đời.' ",
  "sn40.10:40.3": "Do nhân có được tịnh tín bất động đối với Tăng, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời …pe…. ",
  "sn40.10:41.1": "Lành thay, thưa Thiên Đế, là có đầy đủ các giới được bậc Thánh ái mộ, không bị bẻ vỡ …pe… đưa đến định. ",
  "sn40.10:41.2": "Do nhân có đầy đủ các giới được bậc Thánh ái mộ, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:41.3": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:41.4": "về thiên thọ …pe… về xúc chạm cõi trời.' ",
  "sn40.10:42.1": "'Lành thay, thưa Hiền giả Moggallāna, là có được tịnh tín bất động đối với Phật: '",
  "sn40.10:42.2": "'Đây là Thế Tôn …pe… Thiên Nhân Sư, Phật, Thế Tôn.' ",
  "sn40.10:42.3": "Do nhân có được tịnh tín bất động đối với Phật, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:42.4": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:42.5": "về thiên thọ …pe… về xúc chạm cõi trời. ",
  "sn40.10:43.1": "Lành thay, thưa Hiền giả Moggallāna, là có được tịnh tín bất động đối với Pháp: ",
  "sn40.10:43.2": "'Pháp được Thế Tôn khéo thuyết …pe… được người trí tự mình chứng nghiệm.' ",
  "sn40.10:43.3": "Do nhân có được tịnh tín bất động đối với Pháp, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:43.4": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:43.5": "về thiên thọ …pe… về xúc chạm cõi trời. ",
  "sn40.10:44.1": "Lành thay, thưa Hiền giả Moggallāna, là có được tịnh tín bất động đối với Tăng: ",
  "sn40.10:44.2": "'Tăng chúng đệ tử Thế Tôn hành trì thiện …pe… là phước điền vô thượng ở đời.' ",
  "sn40.10:44.3": "Do nhân có được tịnh tín bất động đối với Tăng, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời …pe…. ",
  "sn40.10:45.1": "Lành thay, thưa Hiền giả Moggallāna, là có đầy đủ các giới được bậc Thánh ái mộ, không bị bẻ vỡ …pe… đưa đến định. ",
  "sn40.10:45.2": "Do nhân có đầy đủ các giới được bậc Thánh ái mộ, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:45.3": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:45.4": "về thiên thọ …pe… về xúc chạm cõi trời.' ",
  "sn40.10:46.1": "Rồi Thiên Đế Sakka cùng với sáu trăm chư thiên …pe… ",
  "sn40.10:46.2": "rồi Thiên Đế Sakka cùng với bảy trăm chư thiên …pe… ",
  "sn40.10:46.3": "rồi Thiên Đế Sakka cùng với tám trăm chư thiên …pe… ",
  "sn40.10:46.4": "rồi Thiên Đế Sakka cùng với tám mươi ngàn chư thiên đến gặp Tôn giả Mahāmoggallāna; sau khi đến, đảnh lễ Tôn giả Mahāmoggallāna rồi đứng một bên. Đứng một bên, Tôn giả Mahāmoggallāna nói với Thiên Đế Sakka rằng: ",
  "sn40.10:47.1": "'Lành thay, thưa Thiên Đế, là có được tịnh tín bất động đối với Phật: '",
  "sn40.10:47.2": "'Đây là Thế Tôn, bậc Ứng Cúng, Chánh Biến Tri, Minh Hạnh Túc, Thiện Thệ, Thế Gian Giải, Vô Thượng Sĩ Điều Ngự Trượng Phu, Thiên Nhân Sư, Phật, Thế Tôn.' ",
  "sn40.10:47.3": "Do nhân có được tịnh tín bất động đối với Phật, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:47.4": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:47.5": "về thiên thọ, về thiên sắc, về thiên lạc, về thiên danh, về thiên quyền lực, về hình sắc cõi trời, về âm thanh cõi trời, về hương thơm cõi trời, về vị ngọt cõi trời, về xúc chạm cõi trời. ",
  "sn40.10:48.1": "Lành thay, thưa Thiên Đế, là có được tịnh tín bất động đối với Pháp: ",
  "sn40.10:48.2": "'Pháp được Thế Tôn khéo thuyết, thiết thực, vượt thời gian, đến để thấy, hướng thượng, được người trí tự mình chứng nghiệm.' ",
  "sn40.10:48.3": "Do nhân có được tịnh tín bất động đối với Pháp, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:48.4": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:48.5": "về thiên thọ …pe… về xúc chạm cõi trời. ",
  "sn40.10:49.1": "Lành thay, thưa Thiên Đế, là có được tịnh tín bất động đối với Tăng: ",
  "sn40.10:49.2": "'Tăng chúng đệ tử Thế Tôn hành trì thiện, hành trì chánh trực, hành trì đúng pháp, hành trì hợp lễ, tức là bốn đôi tám vị; Tăng chúng đệ tử Thế Tôn này xứng đáng cúng dường, xứng đáng tiếp đón, xứng đáng cúng thí, xứng đáng chắp tay, là phước điền vô thượng ở đời.' ",
  "sn40.10:49.3": "Do nhân có được tịnh tín bất động đối với Tăng, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:49.4": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:49.5": "về thiên thọ …pe… về xúc chạm cõi trời. ",
  "sn40.10:50.1": "Lành thay, thưa Thiên Đế, là có đầy đủ các giới được bậc Thánh ái mộ, không bị bẻ vỡ, không bị đứt đoạn, không bị tỳ vết, không bị ô nhiễm, thuộc người tự do, được người trí khen ngợi, không bị chấp thủ, đưa đến định. ",
  "sn40.10:50.2": "Do nhân có đầy đủ các giới được bậc Thánh ái mộ, thưa Thiên Đế, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:50.3": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:50.4": "về thiên thọ, về thiên sắc, về thiên lạc, về thiên danh, về thiên quyền lực, về hình sắc cõi trời, về âm thanh cõi trời, về hương thơm cõi trời, về vị ngọt cõi trời, về xúc chạm cõi trời.' ",
  "sn40.10:51.1": "'Lành thay, thưa Hiền giả Moggallāna, là có được tịnh tín bất động đối với Phật: '",
  "sn40.10:51.2": "'Đây là Thế Tôn …pe… Thiên Nhân Sư, Phật, Thế Tôn.' ",
  "sn40.10:51.3": "Do nhân có được tịnh tín bất động đối với Phật, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:51.4": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:51.5": "về thiên thọ …pe… về xúc chạm cõi trời. ",
  "sn40.10:52.1": "Lành thay, thưa Hiền giả Moggallāna, là có được tịnh tín bất động đối với Pháp: ",
  "sn40.10:52.2": "'Pháp được Thế Tôn khéo thuyết …pe… được người trí tự mình chứng nghiệm.' ",
  "sn40.10:52.3": "Do nhân có được tịnh tín bất động đối với Pháp, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:52.4": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:52.5": "về thiên thọ …pe… về xúc chạm cõi trời. ",
  "sn40.10:53.1": "Lành thay, thưa Hiền giả Moggallāna, là có được tịnh tín bất động đối với Tăng: ",
  "sn40.10:53.2": "'Tăng chúng đệ tử Thế Tôn hành trì thiện …pe… là phước điền vô thượng ở đời.' ",
  "sn40.10:53.3": "Do nhân có được tịnh tín bất động đối với Tăng, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:53.4": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:53.5": "về thiên thọ …pe… về xúc chạm cõi trời. ",
  "sn40.10:54.1": "Lành thay, thưa Hiền giả Moggallāna, là có đầy đủ các giới được bậc Thánh ái mộ, không bị bẻ vỡ …pe… đưa đến định. ",
  "sn40.10:54.2": "Do nhân có đầy đủ các giới được bậc Thánh ái mộ, thưa Hiền giả Moggallāna, một số chúng sinh ở đây, sau khi thân hoại mạng chung, được tái sinh vào cõi thiện, cõi trời. ",
  "sn40.10:54.3": "Họ vượt trội các chư thiên khác về mười phương diện ",
  "sn40.10:54.4": "về thiên thọ, về thiên sắc, về thiên lạc, về thiên danh, về thiên quyền lực, về hình sắc cõi trời, về âm thanh cõi trời, về hương thơm cõi trời, về vị ngọt cõi trời, về xúc chạm cõi trời.' ",
  "sn40.10:54.5": "Thứ mười. ",
  "sn40.11:0.1": "Tương Ưng Bộ 40.11 ",
  "sn40.11:0.2": "1. Phẩm Moggallāna ",
  "sn40.11:0.3": "Kinh Candana ",
  "sn40.11:1.1": "Rồi thiên tử Candana …pe…. ",
  "sn40.11:2.1": "Rồi thiên tử Suyāma …pe…. ",
  "sn40.11:3.1": "Rồi thiên tử Santusita …pe…. ",
  "sn40.11:4.1": "Rồi thiên tử Sunimmita …pe…. ",
  "sn40.11:5.1": "Rồi thiên tử Vasavatti …pe…. ",
  "sn40.11:6.1": "(Giống như Kinh Sakka, năm kinh rút gọn này cần được trình bày đầy đủ.) ",
  "sn40.11:6.2": "Thứ mười một. ",
  "sn40.11:6.3": "Phẩm Moggallāna thứ nhất. ",
  "sn40.11:7.0": "Tóm tắt phẩm: ",
  "sn40.11:7.1": "Có tầm và không tầm, ",
  "sn40.11:7.2": "lạc thọ và hành xả; ",
  "sn40.11:7.3": "Hư không và thức, ",
  "sn40.11:7.4": "vô sở hữu và phi tưởng; ",
  "sn40.11:7.5": "Vô tướng, Sakka, ",
  "sn40.11:7.6": "và Candana là thứ mười một. ",
  "sn40.11:7.7": "Tương Ưng Moggallāna hoàn mãn. "
}
window.BILARA["sn40_v1"]["vi"]["sn40_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
