window.BILARA = window.BILARA || {};
window.BILARA["sn41_v1"] = window.BILARA["sn41_v1"] || {};
window.BILARA["sn41_v1"]["vi"] = {
  "sn41.1:0.1": "Tương Ưng Bộ 41.1 ",
  "sn41.1:0.2": "1. Phẩm Citta ",
  "sn41.1:0.3": "Kinh Kiết Sử ",
  "sn41.1:1.1": "Một thời, nhiều Tỳ Kheo trưởng lão đang trú tại Macchikāsaṇḍa, trong rừng Ambāṭaka. ",
  "sn41.1:1.2": "Lúc bấy giờ, nhiều Tỳ Kheo trưởng lão, sau buổi khất thực trở về, ngồi tụ họp tại nhà tròn, và câu chuyện sau đây được khởi lên: ",
  "sn41.1:1.3": "'Này chư Hiền, 'kiết sử' và 'các pháp bị trói buộc'  những pháp này có khác nghĩa khác văn, hay cùng nghĩa chỉ khác văn?' ",
  "sn41.1:1.4": "Một số vị Tỳ Kheo trưởng lão đã trả lời như vầy: ",
  "sn41.1:1.5": "'Này chư Hiền, 'kiết sử' và 'các pháp bị trói buộc'  những pháp này khác nghĩa lẫn khác văn.' ",
  "sn41.1:1.6": "Một số vị Tỳ Kheo trưởng lão khác trả lời như vầy: ",
  "sn41.1:1.7": "'Này chư Hiền, 'kiết sử' và 'các pháp bị trói buộc'  những pháp này cùng nghĩa, chỉ khác văn.' ",
  "sn41.1:2.1": "Lúc bấy giờ, gia chủ Citta đi đến Migapathaka vì một việc gì đó. ",
  "sn41.1:2.2": "Gia chủ Citta nghe rằng nhiều Tỳ Kheo trưởng lão, sau buổi khất thực trở về, ngồi tụ họp tại nhà tròn, và câu chuyện sau đây được khởi lên: ",
  "sn41.1:2.3": "'Này chư Hiền, 'kiết sử' và 'các pháp bị trói buộc'  những pháp này có khác nghĩa khác văn, hay cùng nghĩa chỉ khác văn?' ",
  "sn41.1:2.4": "Một số vị Tỳ Kheo trưởng lão trả lời: ",
  "sn41.1:2.5": "'Này chư Hiền, 'kiết sử' và 'các pháp bị trói buộc'  những pháp này khác nghĩa lẫn khác văn.' ",
  "sn41.1:2.6": "Một số vị Tỳ Kheo trưởng lão khác trả lời: ",
  "sn41.1:2.7": "'Này chư Hiền, 'kiết sử' và 'các pháp bị trói buộc'  những pháp này cùng nghĩa, chỉ khác văn.' ",
  "sn41.1:3.1": "Rồi gia chủ Citta đi đến các Tỳ Kheo trưởng lão; sau khi đến, đảnh lễ các Tỳ Kheo trưởng lão rồi ngồi xuống một bên. Ngồi xuống một bên, gia chủ Citta thưa với các Tỳ Kheo trưởng lão: ",
  "sn41.1:3.2": "'Thưa chư Tôn giả, tôi nghe rằng nhiều Tỳ Kheo trưởng lão, sau buổi khất thực trở về, ngồi tụ họp tại nhà tròn, và câu chuyện sau đây được khởi lên: '",
  "sn41.1:3.3": "'Này chư Hiền, kiết sử và các pháp bị trói buộc  những pháp này có khác nghĩa khác văn, hay cùng nghĩa chỉ khác văn?' ",
  "sn41.1:3.4": "Một số vị trưởng lão trả lời: ",
  "sn41.1:3.5": "'Này chư Hiền, kiết sử và các pháp bị trói buộc  những pháp này khác nghĩa lẫn khác văn.' ",
  "sn41.1:3.6": "Một số vị trưởng lão khác trả lời: 'Này chư Hiền, kiết sử và các pháp bị trói buộc  những pháp này cùng nghĩa, chỉ khác văn.' ",
  "sn41.1:3.7": "'Đúng vậy, thưa gia chủ.' ",
  "sn41.1:4.1": "'Thưa chư Tôn giả, 'kiết sử' và 'các pháp bị trói buộc'  những pháp này khác nghĩa lẫn khác văn. '",
  "sn41.1:4.2": "Vậy thì, thưa chư Tôn giả, tôi sẽ đưa ra một ví dụ. ",
  "sn41.1:4.3": "Nhờ ví dụ, một số người trí có thể hiểu được ý nghĩa của điều đã nói. ",
  "sn41.1:4.4": "Thưa chư Tôn giả, ví như con bò đen và con bò trắng được buộc bằng một sợi dây hay một cái ách. ",
  "sn41.1:4.5": "Nếu có người nói rằng: ",
  "sn41.1:4.6": "'Con bò đen là kiết sử của con bò trắng, con bò trắng là kiết sử của con bò đen'  người ấy nói có đúng không?' '",
  "sn41.1:4.7": "'Không phải vậy, thưa gia chủ. '",
  "sn41.1:4.8": "Thưa gia chủ, con bò đen không phải là kiết sử của con bò trắng, và con bò trắng cũng không phải là kiết sử của con bò đen; ",
  "sn41.1:4.9": "cái dây hay cái ách mà chúng bị trói buộc vào nhau  đó mới là kiết sử ở đây.' ",
  "sn41.1:4.10": "'Cũng vậy, thưa chư Tôn giả, mắt không phải là kiết sử của các sắc, các sắc không phải là kiết sử của mắt; '",
  "sn41.1:4.11": "dục tham khởi lên do duyên cả hai  đó mới là kiết sử ở đây. ",
  "sn41.1:4.12": "Tai không phải là kiết sử của các tiếng… ",
  "sn41.1:4.13": "mũi không phải là kiết sử của các mùi… ",
  "sn41.1:4.14": "lưỡi không phải là kiết sử của các vị… ",
  "sn41.1:4.15": "thân không phải là kiết sử của các xúc, và các xúc không phải là kiết sử của thân; ",
  "sn41.1:4.16": "dục tham khởi lên do duyên cả hai  đó mới là kiết sử ở đây. ",
  "sn41.1:4.17": "Ý không phải là kiết sử của các pháp, các pháp không phải là kiết sử của ý; ",
  "sn41.1:4.18": "dục tham khởi lên do duyên cả hai  đó mới là kiết sử ở đây.' ",
  "sn41.1:4.19": "'Thật là lợi ích cho ông, thưa gia chủ! Thật là thiện lợi cho ông, thưa gia chủ! '",
  "sn41.1:4.20": "Con mắt tuệ của ông đã thấu đạt lời dạy thâm sâu của Đức Phật.' ",
  "sn41.1:4.21": "Thứ nhất. ",
  "sn41.2:0.1": "Tương Ưng Bộ 41.2 ",
  "sn41.2:0.2": "1. Phẩm Citta ",
  "sn41.2:0.3": "Kinh Isidatta (1) ",
  "sn41.2:1.1": "Một thời, nhiều Tỳ Kheo trưởng lão đang trú tại Macchikāsaṇḍa, trong rừng Ambāṭaka. ",
  "sn41.2:1.2": "Rồi gia chủ Citta đi đến các Tỳ Kheo trưởng lão; sau khi đến, đảnh lễ các Tỳ Kheo trưởng lão rồi ngồi xuống một bên. Ngồi xuống một bên, gia chủ Citta thưa với các Tỳ Kheo trưởng lão: ",
  "sn41.2:1.3": "'Thưa chư Tôn giả, xin chư Tôn giả trưởng lão nhận lời mời thọ trai ngày mai tại nhà con.' ",
  "sn41.2:1.4": "Các Tỳ Kheo trưởng lão im lặng nhận lời. ",
  "sn41.2:1.5": "Rồi gia chủ Citta, biết các Tỳ Kheo trưởng lão đã nhận lời, liền từ chỗ ngồi đứng dậy, đảnh lễ các Tỳ Kheo trưởng lão, đi nhiễu bên phải rồi ra về. ",
  "sn41.2:1.6": "Rồi các Tỳ Kheo trưởng lão, vào buổi sáng hôm sau, đắp y mang bát đi đến nhà gia chủ Citta; sau khi đến, ngồi vào chỗ đã soạn sẵn. ",
  "sn41.2:2.1": "Rồi gia chủ Citta đi đến các Tỳ Kheo trưởng lão; sau khi đến, đảnh lễ rồi ngồi xuống một bên. Ngồi xuống một bên, gia chủ Citta thưa với vị Tỳ Kheo trưởng lão: ",
  "sn41.2:2.2": "'Thưa Tôn giả trưởng lão, người ta thường nói 'tính đa dạng của các giới, tính đa dạng của các giới'. '",
  "sn41.2:2.3": "Thưa Tôn giả, tính đa dạng của các giới được Đức Thế Tôn nói đến theo nghĩa nào?' ",
  "sn41.2:2.4": "Khi được hỏi vậy, vị Tỳ Kheo trưởng lão im lặng. ",
  "sn41.2:2.5": "Lần thứ hai, gia chủ Citta hỏi vị Tỳ Kheo trưởng lão: ",
  "sn41.2:2.6": "'Thưa Tôn giả trưởng lão, người ta thường nói 'tính đa dạng của các giới, tính đa dạng của các giới'. '",
  "sn41.2:2.7": "Thưa Tôn giả, tính đa dạng của các giới được Đức Thế Tôn nói đến theo nghĩa nào?' ",
  "sn41.2:2.8": "Lần thứ hai, vị Tỳ Kheo trưởng lão vẫn im lặng. ",
  "sn41.2:2.9": "Lần thứ ba, gia chủ Citta hỏi vị Tỳ Kheo trưởng lão: ",
  "sn41.2:2.10": "'Thưa Tôn giả trưởng lão, người ta thường nói 'tính đa dạng của các giới, tính đa dạng của các giới'. '",
  "sn41.2:2.11": "Thưa Tôn giả, tính đa dạng của các giới được Đức Thế Tôn nói đến theo nghĩa nào?' ",
  "sn41.2:2.12": "Lần thứ ba, vị Tỳ Kheo trưởng lão vẫn im lặng. ",
  "sn41.2:3.1": "Lúc bấy giờ, Tôn giả Isidatta là vị mới thụ giới nhất trong Tăng đoàn đó. ",
  "sn41.2:3.2": "Rồi Tôn giả Isidatta thưa với vị Tỳ Kheo trưởng lão: ",
  "sn41.2:3.3": "'Thưa Tôn giả trưởng lão, để con trả lời câu hỏi của gia chủ Citta.' ",
  "sn41.2:3.4": "'Này Hiền giả Isidatta, hãy trả lời câu hỏi của gia chủ Citta.' ",
  "sn41.2:3.5": "'Này gia chủ, ông hỏi như vầy phải không: '",
  "sn41.2:3.6": "'Thưa Tôn giả trưởng lão, người ta thường nói tính đa dạng của các giới, tính đa dạng của các giới. '",
  "sn41.2:3.7": "Thưa Tôn giả, tính đa dạng của các giới được Đức Thế Tôn nói đến theo nghĩa nào?'' ",
  "sn41.2:3.8": "'Vâng, thưa Tôn giả.' ",
  "sn41.2:3.9": "'Này gia chủ, đây là tính đa dạng của các giới được Đức Thế Tôn nói đến '",
  "sn41.2:3.10": "nhãn giới, sắc giới, nhãn thức giới… ",
  "sn41.2:3.11": "ý giới, pháp giới, ý thức giới. ",
  "sn41.2:3.12": "Này gia chủ, đây là tính đa dạng của các giới được Đức Thế Tôn nói đến.' ",
  "sn41.2:4.1": "Rồi gia chủ Citta, sau khi hoan hỷ và tán thán lời nói của Tôn giả Isidatta, liền tự tay cúng dường và phục vụ các Tỳ Kheo trưởng lão với các món ăn thượng vị cả cứng lẫn mềm. ",
  "sn41.2:4.2": "Rồi các Tỳ Kheo trưởng lão, sau khi ăn xong, tay rời khỏi bát, đứng dậy ra về. ",
  "sn41.2:4.3": "Rồi vị Tỳ Kheo trưởng lão nói với Tôn giả Isidatta: ",
  "sn41.2:4.4": "'Lành thay, này Hiền giả Isidatta! Câu hỏi đó hiện ra với ông, không phải với ta. '",
  "sn41.2:4.5": "Vậy này Hiền giả Isidatta, khi nào có câu hỏi tương tự như vậy được hỏi, hãy trả lời ngay.' ",
  "sn41.2:4.6": "Thứ hai. ",
  "sn41.3:0.1": "Tương Ưng Bộ 41.3 ",
  "sn41.3:0.2": "1. Phẩm Citta ",
  "sn41.3:0.3": "Kinh Isidatta (2) ",
  "sn41.3:1.1": "Một thời, nhiều Tỳ Kheo trưởng lão đang trú tại Macchikāsaṇḍa, trong rừng Ambāṭaka. ",
  "sn41.3:1.2": "Rồi gia chủ Citta đi đến các Tỳ Kheo trưởng lão; sau khi đến, đảnh lễ rồi ngồi xuống một bên. Ngồi xuống một bên, gia chủ Citta thưa với các Tỳ Kheo trưởng lão: ",
  "sn41.3:1.3": "'Thưa chư Tôn giả, xin chư Tôn giả trưởng lão nhận lời mời thọ trai ngày mai tại nhà con.' ",
  "sn41.3:1.4": "Các Tỳ Kheo trưởng lão im lặng nhận lời. ",
  "sn41.3:1.5": "Rồi gia chủ Citta, biết các Tỳ Kheo trưởng lão đã nhận lời, liền từ chỗ ngồi đứng dậy, đảnh lễ, đi nhiễu bên phải rồi ra về. ",
  "sn41.3:1.6": "Rồi các Tỳ Kheo trưởng lão, vào buổi sáng hôm sau, đắp y mang bát đi đến nhà gia chủ Citta; sau khi đến, ngồi vào chỗ đã soạn sẵn. ",
  "sn41.3:2.1": "Rồi gia chủ Citta đi đến các Tỳ Kheo trưởng lão; sau khi đến, đảnh lễ rồi ngồi xuống một bên. Ngồi xuống một bên, gia chủ Citta thưa với vị Tỳ Kheo trưởng lão: ",
  "sn41.3:2.2": "'Thưa Tôn giả trưởng lão, những tà kiến đa dạng khởi lên ở đời: '",
  "sn41.3:2.3": "'thế giới là thường còn hay vô thường, thế giới là hữu biên hay vô biên, linh hồn và thân xác là một hay khác, Như Lai có tồn tại sau khi chết hay không, hay vừa có vừa không, hay vừa không phải có vừa không phải không có.' ",
  "sn41.3:2.4": "Và sáu mươi hai tà kiến được đề cập trong Phạm Võng kinh; ",
  "sn41.3:2.5": "thưa Tôn giả, những tà kiến này khi cái gì có mặt thì chúng có mặt, khi cái gì vắng mặt thì chúng vắng mặt?' ",
  "sn41.3:3.1": "Khi được hỏi vậy, vị Tỳ Kheo trưởng lão im lặng. ",
  "sn41.3:3.2": "Lần thứ hai, gia chủ Citta hỏi… ",
  "sn41.3:3.3": "Lần thứ ba, gia chủ Citta hỏi vị Tỳ Kheo trưởng lão: ",
  "sn41.3:3.4": "'Thưa Tôn giả trưởng lão, những tà kiến đa dạng khởi lên ở đời '",
  "sn41.3:3.5": "thế giới là thường còn hay vô thường, thế giới là hữu biên hay vô biên, linh hồn và thân xác là một hay khác, Như Lai có tồn tại sau khi chết hay không, hay vừa có vừa không, hay vừa không phải có vừa không phải không có. ",
  "sn41.3:3.6": "Và sáu mươi hai tà kiến được đề cập trong Phạm Võng kinh; ",
  "sn41.3:3.7": "thưa Tôn giả, những tà kiến này khi cái gì có mặt thì chúng có mặt, khi cái gì vắng mặt thì chúng vắng mặt?' ",
  "sn41.3:3.8": "Lần thứ ba, vị Tỳ Kheo trưởng lão vẫn im lặng. ",
  "sn41.3:4.1": "Lúc bấy giờ, Tôn giả Isidatta là vị mới thụ giới nhất trong Tăng đoàn đó. ",
  "sn41.3:4.2": "Rồi Tôn giả Isidatta thưa với vị Tỳ Kheo trưởng lão: ",
  "sn41.3:4.3": "'Thưa Tôn giả trưởng lão, để con trả lời câu hỏi của gia chủ Citta.' ",
  "sn41.3:4.4": "'Này Hiền giả Isidatta, hãy trả lời câu hỏi của gia chủ Citta.' ",
  "sn41.3:4.5": "'Này gia chủ, ông hỏi như vầy phải không: '",
  "sn41.3:4.6": "'Thưa Tôn giả trưởng lão, những tà kiến đa dạng khởi lên ở đời '",
  "sn41.3:4.7": "thế giới là thường còn hay vô thường…; ",
  "sn41.3:4.8": "những tà kiến này khi cái gì có mặt thì chúng có mặt, khi cái gì vắng mặt thì chúng vắng mặt?'' ",
  "sn41.3:4.9": "'Vâng, thưa Tôn giả.' ",
  "sn41.3:4.10": "'Này gia chủ, những tà kiến đa dạng khởi lên ở đời: '",
  "sn41.3:4.11": "'thế giới là thường còn hay vô thường, thế giới là hữu biên hay vô biên, linh hồn và thân xác là một hay khác, Như Lai có tồn tại sau khi chết hay không, hay vừa có vừa không, hay vừa không phải có vừa không phải không có.' ",
  "sn41.3:4.12": "Và sáu mươi hai tà kiến được đề cập trong Phạm Võng kinh; ",
  "sn41.3:4.13": "những tà kiến này khi thân kiến có mặt thì chúng có mặt, khi thân kiến vắng mặt thì chúng vắng mặt.' ",
  "sn41.3:5.1": "'Thưa Tôn giả, thân kiến sinh khởi như thế nào?' ",
  "sn41.3:5.2": "'Này gia chủ, kẻ phàm phu chưa nghe Pháp, không gặp gỡ bậc Thánh, không rành Pháp bậc Thánh, không được huấn luyện trong Pháp bậc Thánh, không gặp gỡ bậc Chân nhân, không rành Pháp bậc Chân nhân, không được huấn luyện trong Pháp bậc Chân nhân, '",
  "sn41.3:5.3": "thấy sắc là tự ngã, hay thấy tự ngã có sắc, hay thấy sắc ở trong tự ngã, hay thấy tự ngã ở trong sắc; ",
  "sn41.3:5.4": "thấy thọ là tự ngã… ",
  "sn41.3:5.5": "tưởng… ",
  "sn41.3:5.6": "hành… ",
  "sn41.3:5.7": "thấy thức là tự ngã, hay thấy tự ngã có thức, hay thấy thức ở trong tự ngã, hay thấy tự ngã ở trong thức. ",
  "sn41.3:5.8": "Này gia chủ, như vậy thân kiến sinh khởi.' ",
  "sn41.3:6.1": "'Thưa Tôn giả, thân kiến không sinh khởi như thế nào?' ",
  "sn41.3:6.2": "'Này gia chủ, bậc Thánh đệ tử có nghe Pháp, gặp gỡ bậc Thánh, rành Pháp bậc Thánh, được huấn luyện trong Pháp bậc Thánh, gặp gỡ bậc Chân nhân, rành Pháp bậc Chân nhân, được huấn luyện trong Pháp bậc Chân nhân, '",
  "sn41.3:6.3": "không thấy sắc là tự ngã, không thấy tự ngã có sắc, không thấy sắc ở trong tự ngã, không thấy tự ngã ở trong sắc; ",
  "sn41.3:6.4": "không thấy thọ… ",
  "sn41.3:6.5": "không thấy tưởng… ",
  "sn41.3:6.6": "không thấy hành… ",
  "sn41.3:6.7": "không thấy thức là tự ngã, không thấy tự ngã có thức, không thấy thức ở trong tự ngã, không thấy tự ngã ở trong thức. ",
  "sn41.3:6.8": "Này gia chủ, như vậy thân kiến không sinh khởi.' ",
  "sn41.3:7.1": "'Thưa Tôn giả, Tôn giả Isidatta từ đâu đến?' ",
  "sn41.3:7.2": "'Này gia chủ, tôi từ Avanti đến.' ",
  "sn41.3:7.3": "'Thưa Tôn giả, ở Avanti có người con nhà lành tên Isidatta chưa từng gặp mặt của chúng tôi đã xuất gia. Tôn giả có gặp vị ấy không?' ",
  "sn41.3:7.4": "'Vâng, tôi có gặp.' ",
  "sn41.3:7.5": "'Vâng, thưa gia chủ.' ",
  "sn41.3:7.6": "'Thưa Tôn giả, hiện nay Tôn giả Isidatta ấy đang ở đâu?' ",
  "sn41.3:7.7": "Khi được hỏi vậy, Tôn giả Isidatta im lặng. ",
  "sn41.3:7.8": "'Thưa Tôn giả, Tôn giả Isidatta chính là Ngài phải không?' ",
  "sn41.3:7.9": "'Vâng, thưa gia chủ.' ",
  "sn41.3:7.10": "'Thưa Tôn giả, xin Tôn giả Isidatta hãy ở lại Macchikāsaṇḍa. '",
  "sn41.3:7.11": "Rừng Ambāṭaka thật dễ chịu. ",
  "sn41.3:7.12": "Con sẽ lo liệu y phục, vật thực khất thực, chỗ ở, thuốc men và các vật dụng cần thiết cho Tôn giả Isidatta.' ",
  "sn41.3:7.13": "'Lành thay, thưa gia chủ.' ",
  "sn41.3:8.1": "Rồi gia chủ Citta, sau khi hoan hỷ và tán thán lời nói của Tôn giả Isidatta, liền tự tay cúng dường và phục vụ các Tỳ Kheo trưởng lão với các món ăn thượng vị cả cứng lẫn mềm. ",
  "sn41.3:8.2": "Rồi các Tỳ Kheo trưởng lão, sau khi ăn xong, tay rời khỏi bát, đứng dậy ra về. ",
  "sn41.3:8.3": "Rồi vị Tỳ Kheo trưởng lão nói với Tôn giả Isidatta: ",
  "sn41.3:8.4": "'Lành thay, này Hiền giả Isidatta! Câu hỏi đó hiện ra với ông. '",
  "sn41.3:8.5": "Không phải với ta. ",
  "sn41.3:8.6": "Vậy này Hiền giả Isidatta, khi nào có câu hỏi tương tự như vậy được hỏi, hãy trả lời ngay.' ",
  "sn41.3:8.7": "Rồi Tôn giả Isidatta dọn dẹp chỗ ở, mang bát y rồi từ bỏ Macchikāsaṇḍa ra đi. ",
  "sn41.3:8.8": "Khi từ bỏ Macchikāsaṇḍa ra đi, Ngài đi mà không trở lại. ",
  "sn41.3:8.9": "Thứ ba. ",
  "sn41.4:0.1": "Tương Ưng Bộ 41.4 ",
  "sn41.4:0.2": "1. Phẩm Citta ",
  "sn41.4:0.3": "Kinh Thần Thông Của Mahaka ",
  "sn41.4:1.1": "Một thời, nhiều Tỳ Kheo trưởng lão đang trú tại Macchikāsaṇḍa, trong rừng Ambāṭaka. ",
  "sn41.4:1.2": "Rồi gia chủ Citta đi đến các Tỳ Kheo trưởng lão; sau khi đến, đảnh lễ rồi ngồi xuống một bên. Ngồi xuống một bên, gia chủ Citta thưa với các Tỳ Kheo trưởng lão: ",
  "sn41.4:1.3": "'Thưa chư Tôn giả, xin chư Tôn giả trưởng lão nhận lời mời thọ trai ngày mai tại trại bò của con.' ",
  "sn41.4:1.4": "Các Tỳ Kheo trưởng lão im lặng nhận lời. ",
  "sn41.4:1.5": "Rồi gia chủ Citta, biết các Tỳ Kheo trưởng lão đã nhận lời, liền từ chỗ ngồi đứng dậy, đảnh lễ, đi nhiễu bên phải rồi ra về. ",
  "sn41.4:1.6": "Rồi các Tỳ Kheo trưởng lão, vào buổi sáng hôm sau, đắp y mang bát đi đến trại bò của gia chủ Citta; sau khi đến, ngồi vào chỗ đã soạn sẵn. ",
  "sn41.4:2.1": "Rồi gia chủ Citta tự tay cúng dường các Tỳ Kheo trưởng lão với cháo bơ thượng vị. ",
  "sn41.4:2.2": "Rồi các Tỳ Kheo trưởng lão, sau khi ăn xong, tay rời khỏi bát, đứng dậy ra về. ",
  "sn41.4:2.3": "Gia chủ Citta bảo dọn dẹp phần còn lại rồi đi theo sau các Tỳ Kheo trưởng lão. ",
  "sn41.4:2.4": "Lúc bấy giờ trời nóng và oi bức; ",
  "sn41.4:2.5": "các Tỳ Kheo trưởng lão đi với thân mình có vẻ uể oải như người vừa ăn no. ",
  "sn41.4:3.1": "Lúc bấy giờ, Tôn giả Mahaka là vị mới thụ giới nhất trong Tăng đoàn đó. ",
  "sn41.4:3.2": "Rồi Tôn giả Mahaka thưa với vị Tỳ Kheo trưởng lão: ",
  "sn41.4:3.3": "'Lành thay, thưa Tôn giả trưởng lão, nếu có gió mát thổi đến, mây kéo tới, và mưa nhỏ từng hạt rơi xuống.' ",
  "sn41.4:4.1": "'Lành thay, này Hiền giả Mahaka, nếu có gió mát thổi đến, mây kéo tới, và mưa nhỏ từng hạt rơi xuống.' ",
  "sn41.4:4.2": "Rồi Tôn giả Mahaka thực hiện sự tập trung thần thông sao cho gió mát thổi đến, mây kéo tới, và mưa nhỏ từng hạt rơi xuống. ",
  "sn41.4:4.3": "Rồi gia chủ Citta nghĩ: ",
  "sn41.4:4.4": "'Vị Tỳ Kheo mới nhất trong Tăng đoàn này mà đã có thần thông lực như vậy!' ",
  "sn41.4:4.5": "Rồi Tôn giả Mahaka, khi đến tinh xá, thưa với vị Tỳ Kheo trưởng lão: ",
  "sn41.4:4.6": "'Thế là đủ rồi, thưa chư Tôn giả trưởng lão?' ",
  "sn41.4:4.7": "'Thế là đủ rồi, này Hiền giả Mahaka. '",
  "sn41.4:4.8": "Thế là đủ rồi, này Hiền giả Mahaka. ",
  "sn41.4:4.9": "Đã được cúng dường đầy đủ rồi, này Hiền giả Mahaka.' ",
  "sn41.4:4.10": "Rồi các Tỳ Kheo trưởng lão mỗi người về cốc của mình. ",
  "sn41.4:4.11": "Tôn giả Mahaka cũng về cốc của mình. ",
  "sn41.4:5.1": "Rồi gia chủ Citta đi đến Tôn giả Mahaka; sau khi đến, đảnh lễ rồi ngồi xuống một bên. Ngồi xuống một bên, gia chủ Citta thưa với Tôn giả Mahaka: ",
  "sn41.4:5.2": "'Thưa Tôn giả, xin Tôn giả Mahaka hãy thị hiện thần thông vượt bậc của con người cho con xem.' ",
  "sn41.4:5.3": "'Vậy thì, thưa gia chủ, hãy trải y thượng trên hiên nhà và đặt một bó cỏ lên đó.' ",
  "sn41.4:5.4": "'Vâng, thưa Tôn giả.' Gia chủ Citta vâng theo lời Tôn giả Mahaka, liền trải y thượng trên hiên nhà và đặt một bó cỏ lên đó. ",
  "sn41.4:5.5": "Rồi Tôn giả Mahaka vào trong cốc, cài then cửa, rồi thực hiện sự tập trung thần thông sao cho ngọn lửa từ khe hở của cánh cửa và khe cửa lọt ra và đốt cháy bó cỏ, nhưng không đốt y thượng. ",
  "sn41.4:5.6": "Rồi gia chủ Citta phủi y thượng, kinh sợ, dựng lông, đứng sang một bên. ",
  "sn41.4:5.7": "Rồi Tôn giả Mahaka từ trong cốc bước ra, nói với gia chủ Citta: ",
  "sn41.4:5.8": "'Thế là đủ rồi, thưa gia chủ?' ",
  "sn41.4:6.1": "'Thế là đủ rồi, thưa Tôn giả Mahaka. '",
  "sn41.4:6.2": "Thế là đủ rồi, thưa Tôn giả Mahaka. ",
  "sn41.4:6.3": "Đã được cúng dường đầy đủ rồi, thưa Tôn giả Mahaka. ",
  "sn41.4:6.4": "Thưa Tôn giả, xin Tôn giả Mahaka hãy ở lại Macchikāsaṇḍa. ",
  "sn41.4:6.5": "Rừng Ambāṭaka thật dễ chịu. ",
  "sn41.4:6.6": "Con sẽ lo liệu y phục, vật thực khất thực, chỗ ở, thuốc men và các vật dụng cần thiết cho Tôn giả Mahaka.' ",
  "sn41.4:6.7": "'Lành thay, thưa gia chủ.' ",
  "sn41.4:6.8": "Rồi Tôn giả Mahaka dọn dẹp chỗ ở, mang bát y rồi từ bỏ Macchikāsaṇḍa ra đi. ",
  "sn41.4:6.9": "Khi từ bỏ Macchikāsaṇḍa ra đi, Ngài đi mà không trở lại; ",
  "sn41.4:6.10": "không trở lại nữa. ",
  "sn41.4:6.11": "Thứ tư. ",
  "sn41.5:0.1": "Tương Ưng Bộ 41.5 ",
  "sn41.5:0.2": "1. Phẩm Citta ",
  "sn41.5:0.3": "Kinh Kāmabhū (1) ",
  "sn41.5:1.1": "Một thời, Tôn giả Kāmabhū đang trú tại Macchikāsaṇḍa, trong rừng Ambāṭaka. ",
  "sn41.5:1.2": "Rồi gia chủ Citta đi đến Tôn giả Kāmabhū; sau khi đến, đảnh lễ Tôn giả Kāmabhū rồi ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Kāmabhū nói với gia chủ Citta: ",
  "sn41.5:2.1": "'Thưa gia chủ, có lời dạy này: '",
  "sn41.5:3.1": "'Cỗ xe không vết bẩn, phủ trắng phía sau, '",
  "sn41.5:3.2": "một bánh xe lăn chuyển; ",
  "sn41.5:3.3": "Hãy nhìn vị đang đến, không còn khổ não, ",
  "sn41.5:3.4": "dòng chảy đã đoạn, không còn ràng buộc.' ",
  "sn41.5:4.1": "Thưa gia chủ, lời nói vắn tắt này của Đức Thế Tôn nên được hiểu chi tiết như thế nào?' ",
  "sn41.5:4.2": "'Thưa Tôn giả, đây có phải là lời dạy của Đức Thế Tôn không?' ",
  "sn41.5:4.3": "'Đúng vậy, thưa gia chủ.' ",
  "sn41.5:4.4": "'Vậy thì, thưa Tôn giả, xin Tôn giả đợi một lát để con suy nghĩ về ý nghĩa.' ",
  "sn41.5:4.5": "Rồi gia chủ Citta, sau khi im lặng một lát, thưa với Tôn giả Kāmabhū: ",
  "sn41.5:5.1": "''Không vết bẩn', thưa Tôn giả, là đồng nghĩa với giới hạnh. '",
  "sn41.5:5.2": "'Phủ trắng phía sau', thưa Tôn giả, là đồng nghĩa với giải thoát. ",
  "sn41.5:5.3": "'Một bánh xe', thưa Tôn giả, là đồng nghĩa với niệm. ",
  "sn41.5:5.4": "'Lăn chuyển', thưa Tôn giả, là đồng nghĩa với đi tới và đi lui. ",
  "sn41.5:5.5": "'Cỗ xe', thưa Tôn giả, là đồng nghĩa với thân xác bốn đại này, được sinh ra từ cha mẹ, nuôi dưỡng bằng cơm cháo, vô thường, phải bôi trơn xoa bóp, bị phân hủy và tan rã. ",
  "sn41.5:5.6": "Thưa Tôn giả, tham là gánh nặng, sân là gánh nặng, si là gánh nặng. ",
  "sn41.5:5.7": "Đối với vị Tỳ Kheo đã đoạn tận lậu hoặc, chúng đã được đoạn trừ, cắt đứt tận gốc, làm cho không còn nền tảng như cây thốt nốt bị đốn, không còn khả năng phát sinh trở lại trong tương lai. ",
  "sn41.5:5.8": "Do đó vị Tỳ Kheo đã đoạn tận lậu hoặc được gọi là 'không còn khổ não'. ",
  "sn41.5:5.9": "'Đang đến', thưa Tôn giả, là đồng nghĩa với bậc A-la-hán. ",
  "sn41.5:5.10": "'Dòng chảy', thưa Tôn giả, là đồng nghĩa với tham ái. ",
  "sn41.5:5.11": "Đối với vị Tỳ Kheo đã đoạn tận lậu hoặc, nó đã được đoạn trừ, cắt đứt tận gốc, làm cho không còn nền tảng như cây thốt nốt bị đốn, không còn khả năng phát sinh trở lại trong tương lai. ",
  "sn41.5:5.12": "Do đó vị Tỳ Kheo đã đoạn tận lậu hoặc được gọi là 'dòng chảy đã đoạn'. ",
  "sn41.5:5.13": "Thưa Tôn giả, tham là sự trói buộc, sân là sự trói buộc, si là sự trói buộc. ",
  "sn41.5:5.14": "Đối với vị Tỳ Kheo đã đoạn tận lậu hoặc, chúng đã được đoạn trừ, cắt đứt tận gốc, làm cho không còn nền tảng như cây thốt nốt bị đốn, không còn khả năng phát sinh trở lại trong tương lai. ",
  "sn41.5:5.15": "Do đó vị Tỳ Kheo đã đoạn tận lậu hoặc được gọi là 'không còn ràng buộc'. ",
  "sn41.5:5.16": "Thưa Tôn giả, đây là ý nghĩa chi tiết của lời dạy vắn tắt của Đức Thế Tôn: ",
  "sn41.5:6.1": "'Cỗ xe không vết bẩn, phủ trắng phía sau, '",
  "sn41.5:6.2": "một bánh xe lăn chuyển; ",
  "sn41.5:6.3": "Hãy nhìn vị đang đến, không còn khổ não, ",
  "sn41.5:6.4": "dòng chảy đã đoạn, không còn ràng buộc.' ",
  "sn41.5:7.1": "Thưa Tôn giả, con hiểu ý nghĩa chi tiết của lời dạy vắn tắt của Đức Thế Tôn là như vậy.' ",
  "sn41.5:7.2": "'Thật là lợi ích cho ông, thưa gia chủ! Thật là thiện lợi cho ông, thưa gia chủ! '",
  "sn41.5:7.3": "Con mắt tuệ của ông đã thấu đạt lời dạy thâm sâu của Đức Phật.' ",
  "sn41.5:7.4": "Thứ năm. ",
  "sn41.6:0.1": "Tương Ưng Bộ 41.6 ",
  "sn41.6:0.2": "1. Phẩm Citta ",
  "sn41.6:0.3": "Kinh Kāmabhū (2) ",
  "sn41.6:1.1": "Một thời, Tôn giả Kāmabhū đang trú tại Macchikāsaṇḍa, trong rừng Ambāṭaka. ",
  "sn41.6:1.2": "Rồi gia chủ Citta đi đến Tôn giả Kāmabhū; sau khi đến, ngồi xuống một bên. Ngồi xuống một bên, gia chủ Citta thưa với Tôn giả Kāmabhū: ",
  "sn41.6:1.3": "'Thưa Tôn giả, có bao nhiêu loại hành?' ",
  "sn41.6:1.4": "'Thưa gia chủ, có ba loại hành '",
  "sn41.6:1.5": "thân hành, khẩu hành, tâm hành.' ",
  "sn41.6:1.6": "'Lành thay, thưa Tôn giả.' Gia chủ Citta hoan hỷ, tán thán lời Tôn giả Kāmabhū rồi hỏi thêm: ",
  "sn41.6:1.7": "'Thưa Tôn giả, thân hành là gì, khẩu hành là gì, tâm hành là gì?' ",
  "sn41.6:1.8": "'Thưa gia chủ, hơi thở vào ra là thân hành, tầm và tứ là khẩu hành, tưởng và thọ là tâm hành.' ",
  "sn41.6:2.1": "'Lành thay, thưa Tôn giả.' Gia chủ Citta hoan hỷ… rồi hỏi thêm: ",
  "sn41.6:2.2": "'Thưa Tôn giả, vì sao hơi thở vào ra là thân hành, vì sao tầm và tứ là khẩu hành, vì sao tưởng và thọ là tâm hành?' ",
  "sn41.6:2.3": "'Thưa gia chủ, hơi thở vào ra là thuộc thân. Những pháp này gắn liền với thân, do đó hơi thở vào ra là thân hành. '",
  "sn41.6:2.4": "Thưa gia chủ, trước tiên người ta tầm rồi tứ, sau đó mới thốt lời ra, do đó tầm và tứ là khẩu hành. ",
  "sn41.6:2.5": "Tưởng và thọ là thuộc tâm. Những pháp này gắn liền với tâm, do đó tưởng và thọ là tâm hành.' ",
  "sn41.6:3.1": "'Lành thay…' rồi hỏi thêm: ",
  "sn41.6:3.2": "'Thưa Tôn giả, diệt thọ tưởng định sinh khởi như thế nào?' ",
  "sn41.6:3.3": "'Thưa gia chủ, vị Tỳ Kheo đang nhập diệt thọ tưởng định không nghĩ rằng: '",
  "sn41.6:3.4": "'Ta sẽ nhập diệt thọ tưởng định' hay 'Ta đang nhập diệt thọ tưởng định' hay 'Ta đã nhập diệt thọ tưởng định'. ",
  "sn41.6:3.5": "Mà là tâm của vị ấy đã được tu tập trước đó dẫn đến trạng thái như vậy.' ",
  "sn41.6:4.1": "'Lành thay…' rồi hỏi thêm: ",
  "sn41.6:4.2": "'Thưa Tôn giả, vị Tỳ Kheo đang nhập diệt thọ tưởng định, pháp nào diệt trước  thân hành, khẩu hành, hay tâm hành?' ",
  "sn41.6:4.3": "'Thưa gia chủ, đối với vị Tỳ Kheo đang nhập diệt thọ tưởng định, trước tiên khẩu hành diệt, rồi thân hành, rồi tâm hành.' ",
  "sn41.6:5.1": "'Lành thay…' rồi hỏi thêm: ",
  "sn41.6:5.2": "'Thưa Tôn giả, người đã chết và người đang nhập diệt thọ tưởng định  sự khác biệt là gì?' ",
  "sn41.6:5.3": "'Thưa gia chủ, đối với người đã chết, thân hành đã diệt và an tịnh, khẩu hành đã diệt và an tịnh, tâm hành đã diệt và an tịnh, thọ mạng đã kiệt, hơi ấm đã tắt, các căn đã hoại. '",
  "sn41.6:5.4": "Còn đối với vị Tỳ Kheo đang nhập diệt thọ tưởng định, thân hành đã diệt và an tịnh, khẩu hành đã diệt và an tịnh, tâm hành đã diệt và an tịnh, nhưng thọ mạng chưa kiệt, hơi ấm chưa tắt, các căn còn trong sáng. ",
  "sn41.6:5.5": "Thưa gia chủ, đây là sự khác biệt giữa người đã chết và vị Tỳ Kheo đang nhập diệt thọ tưởng định.' ",
  "sn41.6:6.1": "'Lành thay…' rồi hỏi thêm: ",
  "sn41.6:6.2": "'Thưa Tôn giả, vị Tỳ Kheo xuất khỏi diệt thọ tưởng định như thế nào?' ",
  "sn41.6:6.3": "'Thưa gia chủ, vị Tỳ Kheo đang xuất khỏi diệt thọ tưởng định không nghĩ rằng: '",
  "sn41.6:6.4": "'Ta sẽ xuất khỏi diệt thọ tưởng định' hay 'Ta đang xuất khỏi diệt thọ tưởng định' hay 'Ta đã xuất khỏi diệt thọ tưởng định'. ",
  "sn41.6:6.5": "Mà là tâm của vị ấy đã được tu tập trước đó dẫn đến trạng thái như vậy.' ",
  "sn41.6:7.1": "'Lành thay, thưa Tôn giả…' rồi hỏi thêm: ",
  "sn41.6:7.2": "'Thưa Tôn giả, vị Tỳ Kheo đang xuất khỏi diệt thọ tưởng định, pháp nào khởi sinh trước  thân hành, khẩu hành, hay tâm hành?' ",
  "sn41.6:7.3": "'Thưa gia chủ, đối với vị Tỳ Kheo đang xuất khỏi diệt thọ tưởng định, trước tiên tâm hành khởi sinh, rồi thân hành, rồi khẩu hành.' ",
  "sn41.6:8.1": "'Lành thay…' rồi hỏi thêm: ",
  "sn41.6:8.2": "'Thưa Tôn giả, vị Tỳ Kheo đã xuất khỏi diệt thọ tưởng định thì được mấy loại xúc chạm?' ",
  "sn41.6:8.3": "'Thưa gia chủ, vị Tỳ Kheo đã xuất khỏi diệt thọ tưởng định được ba loại xúc chạm '",
  "sn41.6:8.4": "không xúc, vô tướng xúc, vô nguyện xúc.' ",
  "sn41.6:9.1": "'Lành thay…' rồi hỏi thêm: ",
  "sn41.6:9.2": "'Thưa Tôn giả, đối với vị Tỳ Kheo đã xuất khỏi diệt thọ tưởng định, tâm nghiêng về đâu, hướng về đâu, ngả về đâu?' ",
  "sn41.6:9.3": "'Thưa gia chủ, đối với vị Tỳ Kheo đã xuất khỏi diệt thọ tưởng định, tâm nghiêng về viễn ly, hướng về viễn ly, ngả về viễn ly.' ",
  "sn41.6:10.1": "'Lành thay, thưa Tôn giả.' Gia chủ Citta hoan hỷ, tán thán lời Tôn giả Kāmabhū rồi hỏi thêm: ",
  "sn41.6:10.2": "'Thưa Tôn giả, bao nhiêu pháp là trợ duyên cho diệt thọ tưởng định?' ",
  "sn41.6:10.3": "'Thưa gia chủ, ông đang hỏi điều đáng hỏi trước tiên. '",
  "sn41.6:10.4": "Tuy nhiên, ta sẽ trả lời ông. ",
  "sn41.6:10.5": "Thưa gia chủ, có hai pháp là trợ duyên cho diệt thọ tưởng định ",
  "sn41.6:10.6": "chỉ và quán.' ",
  "sn41.6:10.7": "Thứ sáu. ",
  "sn41.7:0.1": "Tương Ưng Bộ 41.7 ",
  "sn41.7:0.2": "1. Phẩm Citta ",
  "sn41.7:0.3": "Kinh Godatta ",
  "sn41.7:1.1": "Một thời, Tôn giả Godatta đang trú tại Macchikāsaṇḍa, trong rừng Ambāṭaka. ",
  "sn41.7:1.2": "Rồi gia chủ Citta đi đến Tôn giả Godatta; sau khi đến, đảnh lễ Tôn giả Godatta rồi ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Godatta nói với gia chủ Citta: ",
  "sn41.7:1.3": "'Thưa gia chủ, vô lượng tâm giải thoát, vô sở hữu tâm giải thoát, không tâm giải thoát, và vô tướng tâm giải thoát  những pháp này có khác nghĩa khác văn, hay cùng nghĩa chỉ khác văn?' ",
  "sn41.7:1.4": "'Thưa Tôn giả, có cách thức mà theo đó những pháp này khác nghĩa lẫn khác văn. '",
  "sn41.7:1.5": "Và cũng có cách thức mà theo đó những pháp này cùng nghĩa, chỉ khác văn.' ",
  "sn41.7:2.1": "'Thưa Tôn giả, cách thức nào mà theo đó những pháp này khác nghĩa lẫn khác văn? '",
  "sn41.7:2.2": "Thưa Tôn giả, ở đây vị Tỳ Kheo trú với tâm câu hữu từ bi biến mãn một phương, rồi phương thứ hai, rồi phương thứ ba, rồi phương thứ tư. Như vậy trên, dưới, ngang, khắp tất cả, đối với tất cả như với chính mình, vị ấy trú với tâm câu hữu từ bi rộng lớn, vô biên, không oán, không sân biến mãn thế giới. ",
  "sn41.7:2.3": "Với tâm câu hữu bi… ",
  "sn41.7:2.4": "với tâm câu hữu hỷ… ",
  "sn41.7:2.5": "vị ấy trú với tâm câu hữu xả biến mãn một phương, rồi phương thứ hai, rồi phương thứ ba, rồi phương thứ tư. Như vậy trên, dưới, ngang, khắp tất cả, đối với tất cả như với chính mình, vị ấy trú với tâm câu hữu xả rộng lớn, vô biên, không oán, không sân biến mãn thế giới. ",
  "sn41.7:2.6": "Thưa Tôn giả, đây gọi là vô lượng tâm giải thoát. ",
  "sn41.7:3.1": "Thưa Tôn giả, vô sở hữu tâm giải thoát là gì? ",
  "sn41.7:3.2": "Thưa Tôn giả, ở đây vị Tỳ Kheo vượt hoàn toàn thức vô biên xứ, biết rằng 'không có gì cả', vị ấy nhập và trú vô sở hữu xứ. ",
  "sn41.7:3.3": "Thưa Tôn giả, đây gọi là vô sở hữu tâm giải thoát. ",
  "sn41.7:4.1": "Thưa Tôn giả, không tâm giải thoát là gì? ",
  "sn41.7:4.2": "Thưa Tôn giả, ở đây vị Tỳ Kheo đi vào rừng, hay đến gốc cây, hay đến nơi vắng vẻ, suy nghĩ như vầy: ",
  "sn41.7:4.3": "'Điều này trống không của ngã và của vật thuộc ngã.' ",
  "sn41.7:4.4": "Thưa Tôn giả, đây gọi là không tâm giải thoát. ",
  "sn41.7:5.1": "Thưa Tôn giả, vô tướng tâm giải thoát là gì? ",
  "sn41.7:5.2": "Thưa Tôn giả, ở đây vị Tỳ Kheo không tác ý đến tất cả các tướng, nhập và trú vô tướng tâm định. ",
  "sn41.7:5.3": "Thưa Tôn giả, đây gọi là vô tướng tâm giải thoát. ",
  "sn41.7:5.4": "Thưa Tôn giả, đây là cách thức mà theo đó những pháp này khác nghĩa lẫn khác văn. ",
  "sn41.7:6.1": "Thưa Tôn giả, cách thức nào mà theo đó những pháp này cùng nghĩa, chỉ khác văn? ",
  "sn41.7:6.2": "Thưa Tôn giả, tham là nhân tạo ra lượng, sân là nhân tạo ra lượng, si là nhân tạo ra lượng. ",
  "sn41.7:6.3": "Đối với vị Tỳ Kheo đã đoạn tận lậu hoặc, chúng đã được đoạn trừ, cắt đứt tận gốc, làm cho không còn nền tảng như cây thốt nốt bị đốn, không còn khả năng phát sinh trở lại trong tương lai. ",
  "sn41.7:6.4": "Trong tất cả các vô lượng tâm giải thoát, bất động tâm giải thoát được gọi là tối thượng. ",
  "sn41.7:6.5": "Bất động tâm giải thoát ấy trống không tham, trống không sân, trống không si. ",
  "sn41.7:6.6": "Thưa Tôn giả, tham là điều kiện để có cái gì đó, sân là điều kiện để có cái gì đó, si là điều kiện để có cái gì đó. ",
  "sn41.7:6.7": "Đối với vị Tỳ Kheo đã đoạn tận lậu hoặc, chúng đã được đoạn trừ, cắt đứt tận gốc, làm cho không còn nền tảng như cây thốt nốt bị đốn, không còn khả năng phát sinh trở lại trong tương lai. ",
  "sn41.7:6.8": "Trong tất cả các vô sở hữu tâm giải thoát, bất động tâm giải thoát được gọi là tối thượng. ",
  "sn41.7:6.9": "Bất động tâm giải thoát ấy trống không tham, trống không sân, trống không si. ",
  "sn41.7:6.10": "Thưa Tôn giả, tham là nhân tạo ra tướng, sân là nhân tạo ra tướng, si là nhân tạo ra tướng. ",
  "sn41.7:6.11": "Đối với vị Tỳ Kheo đã đoạn tận lậu hoặc, chúng đã được đoạn trừ, cắt đứt tận gốc, làm cho không còn nền tảng như cây thốt nốt bị đốn, không còn khả năng phát sinh trở lại trong tương lai. ",
  "sn41.7:6.12": "Trong tất cả các vô tướng tâm giải thoát, bất động tâm giải thoát được gọi là tối thượng. ",
  "sn41.7:6.13": "Bất động tâm giải thoát ấy trống không tham, trống không sân, trống không si. ",
  "sn41.7:6.14": "Thưa Tôn giả, đây là cách thức mà theo đó những pháp này cùng nghĩa, chỉ khác văn.' ",
  "sn41.7:6.15": "'Thật là lợi ích cho ông, thưa gia chủ! Thật là thiện lợi cho ông, thưa gia chủ! '",
  "sn41.7:6.16": "Con mắt tuệ của ông đã thấu đạt lời dạy thâm sâu của Đức Phật.' ",
  "sn41.7:6.17": "Thứ bảy. ",
  "sn41.8:0.1": "Tương Ưng Bộ 41.8 ",
  "sn41.8:0.2": "1. Phẩm Citta ",
  "sn41.8:0.3": "Kinh Nigaṇṭha Nāṭaputta ",
  "sn41.8:1.1": "Lúc bấy giờ, Nigaṇṭha Nāṭaputta đến Macchikāsaṇḍa cùng với một đại hội chúng Nigaṇṭha. ",
  "sn41.8:1.2": "Gia chủ Citta nghe tin: 'Nigaṇṭha Nāṭaputta đã đến Macchikāsaṇḍa cùng với một đại hội chúng Nigaṇṭha.' ",
  "sn41.8:1.3": "Rồi gia chủ Citta cùng nhiều cư sĩ đi đến Nigaṇṭha Nāṭaputta; sau khi đến, chào hỏi với Nigaṇṭha Nāṭaputta. ",
  "sn41.8:1.4": "Sau khi trao đổi những lời xã giao thân thiện, ngồi xuống một bên. Ngồi xuống một bên, Nigaṇṭha Nāṭaputta nói với gia chủ Citta: ",
  "sn41.8:1.5": "'Thưa gia chủ, ông có tin vào Sa-môn Gotama  '",
  "sn41.8:1.6": "rằng có định không tầm không tứ, rằng có sự diệt của tầm và tứ không?' ",
  "sn41.8:2.1": "'Thưa Tôn giả, trong việc này con không dựa vào đức tin của Đức Thế Tôn. '",
  "sn41.8:2.2": "Có định không tầm không tứ, có sự diệt của tầm và tứ.' ",
  "sn41.8:2.3": "Khi được nói vậy, Nigaṇṭha Nāṭaputta nhìn lên và nói: ",
  "sn41.8:2.4": "'Thưa các vị, hãy nhìn xem gia chủ Citta ngay thẳng thế nào, trung thực thế nào, không xảo trá thế nào  người cho rằng có thể ngăn chặn được tầm và tứ thì cũng như muốn bắt gió trong lưới, hoặc muốn ngăn dòng sông Hằng bằng nắm tay vậy.' ",
  "sn41.8:3.1": "'Thưa Tôn giả, ông nghĩ sao, '",
  "sn41.8:3.2": "cái gì cao quý hơn  trí hay đức tin?' ",
  "sn41.8:3.3": "'Thưa gia chủ, trí cao quý hơn đức tin.' ",
  "sn41.8:3.4": "'Thưa Tôn giả, bất cứ khi nào con muốn, con ly dục, ly các pháp bất thiện, nhập và trú sơ thiền, có tầm có tứ, có hỷ lạc do ly dục sinh. '",
  "sn41.8:3.5": "Thưa Tôn giả, bất cứ khi nào con muốn, con làm cho tầm tứ an tịnh… nhập và trú nhị thiền. ",
  "sn41.8:3.6": "Thưa Tôn giả, bất cứ khi nào con muốn, con với sự ly tham đối với hỷ… nhập và trú tam thiền. ",
  "sn41.8:3.7": "Thưa Tôn giả, bất cứ khi nào con muốn, con với sự xả bỏ lạc… nhập và trú tứ thiền. ",
  "sn41.8:3.8": "Thưa Tôn giả, con đã biết, đã thấy như vậy, sao con lại đi dựa vào đức tin của Sa-môn hay Bà-la-môn nào khác? ",
  "sn41.8:3.9": "Có định không tầm không tứ, có sự diệt của tầm và tứ.' ",
  "sn41.8:4.1": "Khi được nói vậy, Nigaṇṭha Nāṭaputta nhìn vào hội chúng của mình và nói: ",
  "sn41.8:4.2": "'Thưa các vị, hãy nhìn xem gia chủ Citta không ngay thẳng thế nào, không trung thực thế nào, xảo trá thế nào.' ",
  "sn41.8:5.1": "'Thưa Tôn giả, vừa rồi ông đã nói: '",
  "sn41.8:5.2": "'Thưa các vị, hãy nhìn xem gia chủ Citta ngay thẳng thế nào, trung thực thế nào, không xảo trá thế nào.' ",
  "sn41.8:5.3": "Và bây giờ ông lại nói: ",
  "sn41.8:5.4": "'Thưa các vị, hãy nhìn xem gia chủ Citta không ngay thẳng thế nào, không trung thực thế nào, xảo trá thế nào.' ",
  "sn41.8:5.5": "Nếu lời trước của ông là thật thì lời sau là sai. ",
  "sn41.8:5.6": "Còn nếu lời trước là sai thì lời sau là thật. ",
  "sn41.8:5.7": "Thưa Tôn giả, có mười câu hỏi hợp pháp này đang đặt ra. ",
  "sn41.8:5.8": "Khi nào ông biết được ý nghĩa của chúng, hãy phản bác tôi cùng với hội chúng Nigaṇṭha. ",
  "sn41.8:5.9": "Một câu hỏi, một đề mục, một trả lời. ",
  "sn41.8:5.10": "Hai câu hỏi, hai đề mục, hai trả lời. ",
  "sn41.8:5.11": "Ba câu hỏi, ba đề mục, ba trả lời. ",
  "sn41.8:5.12": "Bốn câu hỏi, bốn đề mục, bốn trả lời. ",
  "sn41.8:5.13": "Năm câu hỏi, năm đề mục, năm trả lời. ",
  "sn41.8:5.14": "Sáu câu hỏi, sáu đề mục, sáu trả lời. ",
  "sn41.8:5.15": "Bảy câu hỏi, bảy đề mục, bảy trả lời. ",
  "sn41.8:5.16": "Tám câu hỏi, tám đề mục, tám trả lời. ",
  "sn41.8:5.17": "Chín câu hỏi, chín đề mục, chín trả lời. ",
  "sn41.8:5.18": "Mười câu hỏi, mười đề mục, mười trả lời.' ",
  "sn41.8:5.19": "Rồi gia chủ Citta, sau khi đặt ra mười câu hỏi hợp pháp này với Nigaṇṭha Nāṭaputta, từ chỗ ngồi đứng dậy ra về. ",
  "sn41.8:5.20": "Thứ tám. ",
  "sn41.9:0.1": "Tương Ưng Bộ 41.9 ",
  "sn41.9:0.2": "1. Phẩm Citta ",
  "sn41.9:0.3": "Kinh Kassapa Lõa Thể ",
  "sn41.9:1.1": "Lúc bấy giờ, Kassapa lõa thể đến Macchikāsaṇḍa, là người bạn thời còn tại gia của gia chủ Citta. ",
  "sn41.9:1.2": "Gia chủ Citta nghe tin: 'Kassapa lõa thể đã đến Macchikāsaṇḍa, là bạn thời tại gia của chúng ta.' ",
  "sn41.9:1.3": "Rồi gia chủ Citta đi đến Kassapa lõa thể; sau khi đến, chào hỏi với Kassapa lõa thể. ",
  "sn41.9:1.4": "Sau khi trao đổi những lời xã giao thân thiện, ngồi xuống một bên. Ngồi xuống một bên, gia chủ Citta thưa với Kassapa lõa thể: ",
  "sn41.9:1.5": "'Thưa Tôn giả Kassapa, đã xuất gia được bao lâu rồi?' ",
  "sn41.9:1.6": "'Thưa gia chủ, khoảng ba mươi năm xuất gia rồi.' ",
  "sn41.9:1.7": "'Thưa Tôn giả, trong suốt ba mươi năm đó, Tôn giả có đạt được pháp vượt bậc của con người, trí tuệ và thấy biết xứng đáng bậc Thánh, trú an ổn không?' ",
  "sn41.9:1.8": "'Thưa gia chủ, trong suốt ba mươi năm xuất gia đó, con không đạt được pháp vượt bậc của con người, trí tuệ và thấy biết xứng đáng bậc Thánh, trú an ổn, ngoại trừ lõa thể, cạo đầu, và phủi bụi trên vai mà thôi.' ",
  "sn41.9:1.9": "Khi được nói vậy, gia chủ Citta nói với Kassapa lõa thể: ",
  "sn41.9:1.10": "'Thật là kỳ diệu, thưa ông! Thật là phi thường, thưa ông! '",
  "sn41.9:1.11": "Pháp được khéo tuyên thuyết mà trong ba mươi năm không đạt được pháp vượt bậc của con người, trí tuệ và thấy biết xứng đáng bậc Thánh, trú an ổn, ngoại trừ lõa thể, cạo đầu, và phủi bụi trên vai mà thôi.' ",
  "sn41.9:2.1": "'Còn ông, thưa gia chủ, đã là cư sĩ được bao lâu rồi?' ",
  "sn41.9:2.2": "'Thưa Tôn giả, con cũng khoảng ba mươi năm là cư sĩ rồi.' ",
  "sn41.9:2.3": "'Trong suốt ba mươi năm đó, thưa gia chủ, ông có đạt được pháp vượt bậc của con người, trí tuệ và thấy biết xứng đáng bậc Thánh, trú an ổn không?' ",
  "sn41.9:2.4": "'Thưa Tôn giả, điều đó có thể xảy ra với người tại gia. '",
  "sn41.9:2.5": "Thưa Tôn giả, bất cứ khi nào con muốn, con ly dục, ly các pháp bất thiện, nhập và trú sơ thiền, có tầm có tứ, có hỷ lạc do ly dục sinh. ",
  "sn41.9:2.6": "Thưa Tôn giả, bất cứ khi nào con muốn, con làm cho tầm tứ an tịnh… nhập và trú nhị thiền. ",
  "sn41.9:2.7": "Thưa Tôn giả, bất cứ khi nào con muốn, con với sự ly tham đối với hỷ… nhập và trú tam thiền. ",
  "sn41.9:2.8": "Thưa Tôn giả, bất cứ khi nào con muốn, con với sự xả bỏ lạc… nhập và trú tứ thiền. ",
  "sn41.9:2.9": "Nếu con qua đời trước Đức Thế Tôn, thì thật không có gì đáng ngạc nhiên nếu Đức Thế Tôn tuyên bố về con rằng: ",
  "sn41.9:2.10": "'Không còn kiết sử nào mà gia chủ Citta đã trói buộc có thể đưa ông ấy trở lại thế giới này nữa.'' '",
  "sn41.9:2.11": "Khi được nói vậy, Kassapa lõa thể nói với gia chủ Citta: ",
  "sn41.9:2.12": "'Thật là kỳ diệu, thưa ông! Thật là phi thường, thưa ông! '",
  "sn41.9:2.13": "Pháp được khéo tuyên thuyết, mà người tại gia mặc áo trắng lại có thể đạt được pháp vượt bậc của con người, trí tuệ và thấy biết xứng đáng bậc Thánh như vậy. ",
  "sn41.9:2.14": "Thưa gia chủ, mong con được xuất gia trong giáo pháp và luật này, được thọ giới cụ túc.' ",
  "sn41.9:3.1": "Rồi gia chủ Citta đưa Kassapa lõa thể đến các Tỳ Kheo trưởng lão; sau khi đến, thưa với các Tỳ Kheo trưởng lão: ",
  "sn41.9:3.2": "'Thưa chư Tôn giả, vị Kassapa lõa thể này là bạn thời tại gia của chúng con. '",
  "sn41.9:3.3": "Xin chư Tôn giả hãy cho vị ấy xuất gia và thọ giới cụ túc. ",
  "sn41.9:3.4": "Con sẽ lo liệu y phục, vật thực khất thực, chỗ ở, thuốc men và các vật dụng cần thiết cho vị ấy.' ",
  "sn41.9:3.5": "Kassapa lõa thể được xuất gia trong giáo pháp và luật này, được thọ giới cụ túc. ",
  "sn41.9:3.6": "Vừa thọ giới cụ túc xong, Tôn giả Kassapa sống một mình, xa lánh, không phóng dật, nhiệt tâm, tinh cần, và không bao lâu  vì lý do mà các thiện nam tử từ bỏ gia đình, sống không gia đình  ngay trong hiện tại, bằng trí tuệ trực tiếp, tự mình chứng ngộ và trú trong cứu cánh vô thượng của Phạm hạnh. ",
  "sn41.9:3.7": "Vị ấy biết rõ: 'Sanh đã tận, Phạm hạnh đã sống, việc cần làm đã làm, không còn trở lại trạng thái này nữa.' ",
  "sn41.9:3.8": "Và Tôn giả Kassapa trở thành một trong những vị A-la-hán. ",
  "sn41.9:3.9": "Thứ chín. ",
  "sn41.10:0.1": "Tương Ưng Bộ 41.10 ",
  "sn41.10:0.2": "1. Phẩm Citta ",
  "sn41.10:0.3": "Kinh Thăm Người Bệnh ",
  "sn41.10:1.1": "Lúc bấy giờ, gia chủ Citta bị bệnh, đau khổ, bệnh nặng. ",
  "sn41.10:1.2": "Rồi nhiều chư thiên cõi vườn, chư thiên cõi rừng, chư thiên cõi cây, chư thiên trú trong cỏ thuốc, cây cỏ và rừng rậm, cùng nhau tụ họp lại, nói với gia chủ Citta: ",
  "sn41.10:1.3": "'Thưa gia chủ, hãy phát nguyện rằng trong tương lai sẽ làm Chuyển Luân Thánh Vương.' ",
  "sn41.10:2.1": "Khi được nói vậy, gia chủ Citta nói với chư thiên cõi vườn, chư thiên cõi rừng, chư thiên cõi cây, chư thiên trú trong cỏ thuốc, cây cỏ và rừng rậm: ",
  "sn41.10:2.2": "'Điều đó cũng vô thường, điều đó cũng không bền vững, điều đó cũng phải bỏ lại mà đi.' ",
  "sn41.10:2.3": "Khi được nói vậy, bạn bè, người thân thuộc và bà con huyết thống của gia chủ Citta nói với gia chủ Citta: ",
  "sn41.10:2.4": "'Thưa chàng, hãy giữ chánh niệm, đừng mê sảng.' ",
  "sn41.10:2.5": "'Sao các vị lại nói với con: '",
  "sn41.10:2.6": "'Thưa chàng, hãy giữ chánh niệm, đừng mê sảng'?' '",
  "sn41.10:2.7": "'Thưa chàng, chàng nói rằng: '",
  "sn41.10:2.8": "'Điều đó cũng vô thường, điều đó cũng không bền vững, điều đó cũng phải bỏ lại mà đi.'' '",
  "sn41.10:2.9": "'Đó là vì chư thiên cõi vườn, chư thiên cõi rừng, chư thiên cõi cây, chư thiên trú trong cỏ thuốc, cây cỏ và rừng rậm đã nói với con: '",
  "sn41.10:2.10": "'Hãy phát nguyện, thưa gia chủ, rằng trong tương lai sẽ làm Chuyển Luân Thánh Vương.' ",
  "sn41.10:2.11": "Con đã nói với họ: ",
  "sn41.10:2.12": "'Điều đó cũng vô thường… điều đó cũng phải bỏ lại mà đi.'' '",
  "sn41.10:2.13": "'Thưa chàng, vậy thì chư thiên cõi vườn, chư thiên cõi rừng, chư thiên cõi cây, chư thiên trú trong cỏ thuốc, cây cỏ và rừng rậm đã thấy lợi ích gì mà nói: '",
  "sn41.10:2.14": "'Hãy phát nguyện, thưa gia chủ, rằng trong tương lai sẽ làm Chuyển Luân Thánh Vương'?' '",
  "sn41.10:2.15": "'Các chư thiên cõi vườn, chư thiên cõi rừng, chư thiên cõi cây, chư thiên trú trong cỏ thuốc, cây cỏ và rừng rậm đã nghĩ: '",
  "sn41.10:2.16": "'Gia chủ Citta này là người có giới hạnh, có pháp lành. '",
  "sn41.10:2.17": "Nếu ông ấy phát nguyện ",
  "sn41.10:2.18": "trong tương lai sẽ làm Chuyển Luân Thánh Vương', nguyện ấy sẽ thành tựu đối với người có giới hạnh, vì tâm nguyện trong sạch của người có giới hạnh có quả pháp tương xứng.' ",
  "sn41.10:2.19": "Đó là lý do chư thiên cõi vườn, chư thiên cõi rừng, chư thiên cõi cây, chư thiên trú trong cỏ thuốc, cây cỏ và rừng rậm đã nói: ",
  "sn41.10:2.20": "'Hãy phát nguyện, thưa gia chủ, rằng trong tương lai sẽ làm Chuyển Luân Thánh Vương.' ",
  "sn41.10:2.21": "Con đã nói với họ: ",
  "sn41.10:2.22": "'Điều đó cũng vô thường, điều đó cũng không bền vững, điều đó cũng phải bỏ lại mà đi.'' '",
  "sn41.10:3.1": "'Vậy thì, thưa chàng, hãy dạy bảo chúng con.' ",
  "sn41.10:3.2": "'Vậy thì các vị hãy học tập như vầy '",
  "sn41.10:3.3": "chúng ta sẽ có lòng tin bất động đối với Đức Phật: ",
  "sn41.10:3.4": "'Đức Thế Tôn là bậc A-la-hán, Chánh Đẳng Giác, Minh Hạnh Túc, Thiện Thệ, Thế Gian Giải, Vô Thượng Sĩ, Điều Ngự Trượng Phu, Thiên Nhân Sư, Phật, Thế Tôn.' ",
  "sn41.10:3.5": "Chúng ta sẽ có lòng tin bất động đối với Pháp: ",
  "sn41.10:3.6": "'Pháp được Đức Thế Tôn khéo thuyết giảng, thiết thực hiện tại, không có thời gian, đến để mà thấy, hướng thượng, được người trí tự mình giác hiểu.' ",
  "sn41.10:3.7": "Chúng ta sẽ có lòng tin bất động đối với Tăng: ",
  "sn41.10:3.8": "'Tăng đoàn đệ tử của Đức Thế Tôn thực hành tốt, thực hành thẳng thắn, thực hành đúng pháp, thực hành chân chánh  đó là bốn đôi, tám vị  Tăng đoàn đệ tử của Đức Thế Tôn đáng được cúng dường, đáng được cung kính, đáng được tôn trọng, đáng được chắp tay, là ruộng phước vô thượng ở đời.' ",
  "sn41.10:3.9": "Và bất cứ vật gì đáng để bố thí trong gia đình, tất cả đều nên được chia sẻ rộng rãi cho những người có giới hạnh, có pháp lành  đây là điều các vị phải học tập.' ",
  "sn41.10:3.10": "Rồi gia chủ Citta, sau khi khuyến khích bạn bè, người thân thuộc và bà con huyết thống hướng đến Phật, Pháp, Tăng và đức bố thí, liền qua đời. ",
  "sn41.10:3.11": "Thứ mười. ",
  "sn41.10:3.12": "Phẩm Citta, thứ nhất. ",
  "sn41.10:4.0": "Tóm lược phẩm này: ",
  "sn41.10:4.1": "Kiết sử, hai kinh Isidatta, ",
  "sn41.10:4.2": "Mahaka và Kāmabhū; ",
  "sn41.10:4.3": "Godatta và Nigaṇṭha, ",
  "sn41.10:4.4": "Kassapa lõa thể và thăm người bệnh. ",
  "sn41.10:4.5": "Tương Ưng Citta hoàn tất. "
}
window.BILARA["sn41_v1"]["vi"]["sn41_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
