window.BILARA = window.BILARA || {};
window.BILARA["sn44_v1"] = window.BILARA["sn44_v1"] || {};
window.BILARA["sn44_v1"]["vi"] = {
  "sn44.1:0.1": "Tương Ưng Bộ 44.1 ",
  "sn44.1:0.2": "1. Phẩm Vô Ký ",
  "sn44.1:0.3": "Kinh Khemā ",
  "sn44.1:1.1": "Một thời Thế Tôn trú tại Sāvatthī, rừng Jetavana, tịnh xá của Anāthapiṇḍika. ",
  "sn44.1:1.2": "Lúc bấy giờ, Tỳ Kheo Ni Khemā đang du hành trong nước Kosala, giữa đường từ Sāvatthī đến Sāketa, trú lại tại Toraṇavatthu. ",
  "sn44.1:1.3": "Khi ấy, vua Pasenadi nước Kosala đang đi từ Sāketa đến Sāvatthī, giữa đường từ Sāketa đến Sāvatthī, cũng trú lại Toraṇavatthu một đêm. ",
  "sn44.1:1.4": "Khi ấy, vua Pasenadi nước Kosala gọi một người kia lại và bảo: ",
  "sn44.1:1.5": "'Này người kia, hãy đi tìm trong Toraṇavatthu xem có vị sa-môn hay bà-la-môn nào xứng đáng để ta đến thăm viếng hôm nay.' ",
  "sn44.1:2.1": "'Thưa vâng, Đại vương.' Người ấy vâng lời vua Pasenadi nước Kosala, đi khắp Toraṇavatthu nhưng không tìm thấy vị sa-môn hay bà-la-môn nào xứng đáng để vua Pasenadi đến thăm viếng. ",
  "sn44.1:2.2": "Người ấy thấy Tỳ Kheo Ni Khemā đang trú tại Toraṇavatthu. ",
  "sn44.1:2.3": "Thấy vậy, người ấy đến chỗ vua Pasenadi nước Kosala, khi đến rồi thưa với vua Pasenadi nước Kosala rằng: ",
  "sn44.1:3.1": "'Thưa Đại vương, trong Toraṇavatthu không có vị sa-môn hay bà-la-môn nào xứng đáng để Đại vương đến thăm viếng. '",
  "sn44.1:3.2": "Tuy nhiên, thưa Đại vương, có Tỳ Kheo Ni Khemā, đệ tử của Thế Tôn, bậc Ứng Cúng, Chánh Đẳng Giác. ",
  "sn44.1:3.3": "Về vị ni sư này, tiếng tốt đẹp được lan truyền như vậy: ",
  "sn44.1:3.4": "'Trí tuệ, thông minh, lanh lợi, đa văn, khéo giảng, biện tài.' ",
  "sn44.1:3.5": "Xin Đại vương hãy đến thăm viếng vị ấy.' ",
  "sn44.1:4.1": "Khi ấy, vua Pasenadi nước Kosala đến chỗ Tỳ Kheo Ni Khemā; khi đến rồi, đảnh lễ Tỳ Kheo Ni Khemā và ngồi xuống một bên. Ngồi xuống một bên, vua Pasenadi nước Kosala nói với Tỳ Kheo Ni Khemā rằng: ",
  "sn44.1:4.2": "'Thưa Ni sư, sau khi chết Như Lai có tồn tại không?' ",
  "sn44.1:4.3": "'Thưa Đại vương, điều này không được Thế Tôn tuyên bố: '",
  "sn44.1:4.4": "'Sau khi chết Như Lai có tồn tại.'' '",
  "sn44.1:4.5": "'Vậy thưa Ni sư, sau khi chết Như Lai không tồn tại?' ",
  "sn44.1:4.6": "'Thưa Đại vương, điều này cũng không được Thế Tôn tuyên bố: '",
  "sn44.1:4.7": "'Sau khi chết Như Lai không tồn tại.'' '",
  "sn44.1:4.8": "'Thưa Ni sư, sau khi chết Như Lai vừa tồn tại vừa không tồn tại?' ",
  "sn44.1:4.9": "'Thưa Đại vương, điều này không được Thế Tôn tuyên bố: '",
  "sn44.1:4.10": "'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại.'' '",
  "sn44.1:4.11": "'Thưa Ni sư, sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại?' ",
  "sn44.1:4.12": "'Thưa Đại vương, điều này cũng không được Thế Tôn tuyên bố: '",
  "sn44.1:4.13": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.'' '",
  "sn44.1:5.1": "'Khi được hỏi 'Thưa Ni sư, sau khi chết Như Lai có tồn tại không?', Ni sư nói: '",
  "sn44.1:5.2": "'Thưa Đại vương, điều này không được Thế Tôn tuyên bố '",
  "sn44.1:5.3": "sau khi chết Như Lai có tồn tại.' ",
  "sn44.1:5.4": "Khi được hỏi 'Vậy thưa Ni sư, sau khi chết Như Lai không tồn tại?', Ni sư nói: ",
  "sn44.1:5.5": "'Thưa Đại vương, điều này cũng không được Thế Tôn tuyên bố '",
  "sn44.1:5.6": "sau khi chết Như Lai không tồn tại.' ",
  "sn44.1:5.7": "Khi được hỏi 'Thưa Ni sư, sau khi chết Như Lai vừa tồn tại vừa không tồn tại?', Ni sư nói: ",
  "sn44.1:5.8": "'Thưa Đại vương, điều này không được Thế Tôn tuyên bố '",
  "sn44.1:5.9": "sau khi chết Như Lai vừa tồn tại vừa không tồn tại.' ",
  "sn44.1:5.10": "Khi được hỏi 'Thưa Ni sư, sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại?', Ni sư nói: ",
  "sn44.1:5.11": "'Thưa Đại vương, điều này cũng không được Thế Tôn tuyên bố '",
  "sn44.1:5.12": "sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.1:5.13": "Vậy thưa Ni sư, nguyên nhân gì, duyên gì mà Thế Tôn không tuyên bố điều này?' ",
  "sn44.1:6.1": "'Vậy thì, thưa Đại vương, tôi sẽ hỏi lại điều này. Đại vương hãy trả lời tùy theo chỗ Đại vương thấy hợp. '",
  "sn44.1:6.2": "Đại vương nghĩ thế nào, ",
  "sn44.1:6.3": "Đại vương có người tính toán, kế toán, hay nhà toán học nào có thể đếm cát sông Hằng ",
  "sn44.1:6.4": "bao nhiêu hạt cát, hay bao nhiêu trăm hạt cát, hay bao nhiêu nghìn hạt cát, hay bao nhiêu trăm nghìn hạt cát không?' ",
  "sn44.1:6.5": "'Thưa không, Ni sư.' ",
  "sn44.1:6.6": "'Đại vương có người tính toán, kế toán, hay nhà toán học nào có thể đong nước biển lớn '",
  "sn44.1:6.7": "bao nhiêu đấu nước, hay bao nhiêu trăm đấu nước, hay bao nhiêu nghìn đấu nước, hay bao nhiêu trăm nghìn đấu nước không?' ",
  "sn44.1:6.8": "'Thưa không, Ni sư.' ",
  "sn44.1:6.9": "'Tại sao vậy?' ",
  "sn44.1:6.10": "'Thưa Ni sư, biển lớn sâu thẳm, vô lượng, khó thấu đáo.' ",
  "sn44.1:6.11": "'Cũng vậy, thưa Đại vương, sắc nào mà người ta dùng để mô tả Như Lai, sắc đó của Như Lai đã bị đoạn trừ, tận gốc rễ, như thân cây ta-la bị chặt, không còn tồn tại nữa, không thể sinh khởi trong tương lai. '",
  "sn44.1:6.12": "Thưa Đại vương, Như Lai được giải thoát khỏi sự quy định bởi sắc, sâu thẳm, vô lượng, khó thấu đáo ",
  "sn44.1:6.13": "như biển lớn vậy. ",
  "sn44.1:6.14": "'Sau khi chết Như Lai có tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai không tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'  điều đó không thích hợp. ",
  "sn44.1:7.1": "Thọ nào mà người ta dùng để mô tả Như Lai, thọ đó của Như Lai đã bị đoạn trừ, tận gốc rễ, như thân cây ta-la bị chặt, không còn tồn tại nữa, không thể sinh khởi trong tương lai. ",
  "sn44.1:7.2": "Thưa Đại vương, Như Lai được giải thoát khỏi sự quy định bởi thọ, sâu thẳm, vô lượng, khó thấu đáo ",
  "sn44.1:7.3": "như biển lớn vậy. ",
  "sn44.1:7.4": "'Sau khi chết Như Lai có tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai không tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'  điều đó không thích hợp. ",
  "sn44.1:8.1": "Tưởng nào mà người ta dùng để mô tả Như Lai… ",
  "sn44.1:8.2": "các hành nào mà người ta dùng để mô tả Như Lai, các hành đó của Như Lai đã bị đoạn trừ, tận gốc rễ, như thân cây ta-la bị chặt, không còn tồn tại nữa, không thể sinh khởi trong tương lai. ",
  "sn44.1:8.3": "Thưa Đại vương, Như Lai được giải thoát khỏi sự quy định bởi hành, sâu thẳm, vô lượng, khó thấu đáo ",
  "sn44.1:8.4": "như biển lớn vậy. ",
  "sn44.1:8.5": "'Sau khi chết Như Lai có tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai không tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'  điều đó không thích hợp. ",
  "sn44.1:9.1": "Thức nào mà người ta dùng để mô tả Như Lai, thức đó của Như Lai đã bị đoạn trừ, tận gốc rễ, như thân cây ta-la bị chặt, không còn tồn tại nữa, không thể sinh khởi trong tương lai. ",
  "sn44.1:9.2": "Thưa Đại vương, Như Lai được giải thoát khỏi sự quy định bởi thức, sâu thẳm, vô lượng, khó thấu đáo ",
  "sn44.1:9.3": "như biển lớn vậy. ",
  "sn44.1:9.4": "'Sau khi chết Như Lai có tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai không tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'  điều đó không thích hợp.' '",
  "sn44.1:9.5": "Khi ấy, vua Pasenadi nước Kosala, sau khi hoan hỷ, tán thán lời Tỳ Kheo Ni Khemā, đứng dậy khỏi chỗ ngồi, đảnh lễ Tỳ Kheo Ni Khemā, đi nhiễu bên phải rồi ra đi. ",
  "sn44.1:10.1": "Khi ấy, vua Pasenadi nước Kosala sau đó đến chỗ Thế Tôn; khi đến rồi, đảnh lễ Thế Tôn và ngồi xuống một bên. Ngồi xuống một bên, vua Pasenadi nước Kosala bạch Thế Tôn rằng: ",
  "sn44.1:10.2": "'Bạch Thế Tôn, sau khi chết Như Lai có tồn tại không?' ",
  "sn44.1:10.3": "'Thưa Đại vương, điều này Ta không tuyên bố: '",
  "sn44.1:10.4": "'Sau khi chết Như Lai có tồn tại.'' '",
  "sn44.1:10.5": "'Bạch Thế Tôn, sau khi chết Như Lai không tồn tại?' ",
  "sn44.1:10.6": "'Thưa Đại vương, điều này cũng không được Ta tuyên bố: '",
  "sn44.1:10.7": "'Sau khi chết Như Lai không tồn tại.'' '",
  "sn44.1:10.8": "'Bạch Thế Tôn, sau khi chết Như Lai vừa tồn tại vừa không tồn tại?' ",
  "sn44.1:10.9": "'Thưa Đại vương, điều này Ta không tuyên bố: '",
  "sn44.1:10.10": "'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại.'' '",
  "sn44.1:10.11": "'Bạch Thế Tôn, sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại?' ",
  "sn44.1:10.12": "'Thưa Đại vương, điều này cũng không được Ta tuyên bố: '",
  "sn44.1:10.13": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.'' '",
  "sn44.1:10.14": "'Khi được hỏi 'Bạch Thế Tôn, sau khi chết Như Lai có tồn tại không?', Ngài nói: '",
  "sn44.1:10.15": "'Thưa Đại vương, điều này Ta không tuyên bố  sau khi chết Như Lai có tồn tại'… ",
  "sn44.1:10.16": "'Khi được hỏi 'Bạch Thế Tôn, sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại?', Ngài nói: '",
  "sn44.1:10.17": "'Thưa Đại vương, điều này cũng không được Ta tuyên bố '",
  "sn44.1:10.18": "sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.1:10.19": "Bạch Thế Tôn, nguyên nhân gì, duyên gì mà Thế Tôn không tuyên bố điều này?' ",
  "sn44.1:11.1": "'Vậy thì, thưa Đại vương, Ta sẽ hỏi lại điều này. Đại vương hãy trả lời tùy theo chỗ Đại vương thấy hợp. '",
  "sn44.1:11.2": "Đại vương nghĩ thế nào, Đại vương có người tính toán, kế toán, hay nhà toán học nào có thể đếm cát sông Hằng ",
  "sn44.1:11.3": "bao nhiêu hạt cát,… bao nhiêu trăm nghìn hạt cát không?' ",
  "sn44.1:11.4": "'Bạch Thế Tôn, không ạ.' ",
  "sn44.1:11.5": "'Đại vương có người tính toán, kế toán, hay nhà toán học nào có thể đong nước biển lớn '",
  "sn44.1:11.6": "bao nhiêu đấu nước,… bao nhiêu trăm nghìn đấu nước không?' ",
  "sn44.1:11.7": "'Bạch Thế Tôn, không ạ.' ",
  "sn44.1:11.8": "'Tại sao vậy?' ",
  "sn44.1:11.9": "'Bạch Thế Tôn, biển lớn sâu thẳm, vô lượng, khó thấu đáo. '",
  "sn44.1:11.10": "Cũng vậy, thưa Đại vương, sắc nào mà người ta dùng để mô tả Như Lai, sắc đó của Như Lai đã bị đoạn trừ, tận gốc rễ, như thân cây ta-la bị chặt, không còn tồn tại nữa, không thể sinh khởi trong tương lai. ",
  "sn44.1:11.11": "Thưa Đại vương, Như Lai được giải thoát khỏi sự quy định bởi sắc, sâu thẳm, vô lượng, khó thấu đáo ",
  "sn44.1:11.12": "như biển lớn vậy. ",
  "sn44.1:11.13": "'Sau khi chết Như Lai có tồn tại'  điều đó không thích hợp… ",
  "sn44.1:11.14": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'  điều đó không thích hợp. ",
  "sn44.1:11.15": "Thọ nào… ",
  "sn44.1:11.16": "tưởng nào… các hành nào…. ",
  "sn44.1:12.1": "Thức nào mà người ta dùng để mô tả Như Lai, thức đó của Như Lai đã bị đoạn trừ, tận gốc rễ, như thân cây ta-la bị chặt, không còn tồn tại nữa, không thể sinh khởi trong tương lai. ",
  "sn44.1:12.2": "Thưa Đại vương, Như Lai được giải thoát khỏi sự quy định bởi thức, sâu thẳm, vô lượng, khó thấu đáo ",
  "sn44.1:12.3": "như biển lớn vậy. ",
  "sn44.1:12.4": "'Sau khi chết Như Lai có tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai không tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'  điều đó không thích hợp; 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'  điều đó không thích hợp.' '",
  "sn44.1:13.1": "'Thật kỳ diệu, bạch Thế Tôn, thật hy hữu, bạch Thế Tôn. '",
  "sn44.1:13.2": "Thật vậy, lời dạy của bậc Đạo Sư và của đệ tử đồng nhất về nghĩa, đồng nhất về văn cú, không mâu thuẫn nhau, ở điều tối thượng. ",
  "sn44.1:13.3": "Một thời, bạch Thế Tôn, con đến chỗ Tỳ Kheo Ni Khemā và hỏi điều này. ",
  "sn44.1:13.4": "Ni sư ấy cũng đã giải thích điều này cho con bằng những từ ngữ và văn cú đó, giống như Thế Tôn vậy. ",
  "sn44.1:13.5": "Thật kỳ diệu, bạch Thế Tôn, thật hy hữu, bạch Thế Tôn. ",
  "sn44.1:13.6": "Thật vậy, lời dạy của bậc Đạo Sư và của đệ tử đồng nhất về nghĩa, đồng nhất về văn cú, không mâu thuẫn nhau, ở điều tối thượng. ",
  "sn44.1:13.7": "Bạch Thế Tôn, nay chúng con xin cáo lui. ",
  "sn44.1:13.8": "Chúng con có nhiều công việc, nhiều bổn phận cần làm.' ",
  "sn44.1:13.9": "'Thưa Đại vương, nay là lúc thích hợp.' ",
  "sn44.1:13.10": "Khi ấy, vua Pasenadi nước Kosala, sau khi hoan hỷ, tán thán lời Thế Tôn, đứng dậy khỏi chỗ ngồi, đảnh lễ Thế Tôn, đi nhiễu bên phải rồi ra đi. ",
  "sn44.1:13.11": "Thứ nhất. ",
  "sn44.2:0.1": "Tương Ưng Bộ 44.2 ",
  "sn44.2:0.2": "1. Phẩm Vô Ký ",
  "sn44.2:0.3": "Kinh Anurādha ",
  "sn44.2:1.1": "Một thời Thế Tôn trú tại Vesālī, rừng Đại Lâm, giảng đường có nóc nhọn. ",
  "sn44.2:1.2": "Lúc bấy giờ, Tôn giả Anurādha đang trú trong am cốc nơi rừng, không xa Thế Tôn. ",
  "sn44.2:1.3": "Khi ấy, nhiều du sĩ ngoại đạo đến chỗ Tôn giả Anurādha; khi đến rồi, chào hỏi Tôn giả Anurādha. ",
  "sn44.2:1.4": "Sau khi chào hỏi thân thiện rồi, ngồi xuống một bên. Ngồi xuống một bên, các du sĩ ngoại đạo ấy nói với Tôn giả Anurādha rằng: ",
  "sn44.2:1.5": "'Này Hiền giả Anurādha, Như Lai là bậc tối thượng, bậc tối thắng, đã đạt đến địa vị tối thắng. Như Lai được mô tả bằng bốn trường hợp này: '",
  "sn44.2:1.6": "'Sau khi chết Như Lai có tồn tại', hay 'Sau khi chết Như Lai không tồn tại', hay 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại', hay 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'?' '",
  "sn44.2:1.7": "'Này Hiền giả, Như Lai là bậc tối thượng, bậc tối thắng, đã đạt đến địa vị tối thắng. Như Lai được mô tả ngoài bốn trường hợp này: '",
  "sn44.2:1.8": "'Sau khi chết Như Lai có tồn tại', hay 'Sau khi chết Như Lai không tồn tại', hay 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại', hay 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'.' '",
  "sn44.2:1.9": "Khi nghe vậy, các du sĩ ngoại đạo ấy nói với Tôn giả Anurādha: ",
  "sn44.2:1.10": "'Vị Tỳ Kheo này chắc là người mới xuất gia, chưa lâu, hay là bậc trưởng lão ngu si, chưa thông đạt.' ",
  "sn44.2:1.11": "Khi ấy, các du sĩ ngoại đạo ấy sau khi chê bai Tôn giả Anurādha bằng những lời như người mới và người ngu, đứng dậy khỏi chỗ ngồi rồi bỏ đi. ",
  "sn44.2:2.1": "Khi ấy, Tôn giả Anurādha, sau khi các du sĩ ngoại đạo vừa rời đi, nghĩ rằng: ",
  "sn44.2:2.2": "'Nếu các du sĩ ngoại đạo ấy hỏi thêm ta, '",
  "sn44.2:2.3": "ta trả lời như thế nào mới là nói đúng lời Thế Tôn, không xuyên tạc Thế Tôn bằng điều không thật, giải thích đúng pháp, và không bị ai có cùng quan điểm phê phán một cách chính đáng?' ",
  "sn44.2:2.4": "Khi ấy, Tôn giả Anurādha đến chỗ Thế Tôn; khi đến rồi, đảnh lễ Thế Tôn và ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Anurādha bạch Thế Tôn rằng: ",
  "sn44.2:2.5": "'Bạch Thế Tôn, ở đây con đang trú trong am cốc nơi rừng, không xa Thế Tôn. '",
  "sn44.2:2.6": "Bạch Thế Tôn, khi ấy nhiều du sĩ ngoại đạo đến chỗ con; khi đến rồi, chào hỏi con. ",
  "sn44.2:2.7": "Sau khi chào hỏi thân thiện rồi, ngồi xuống một bên. Ngồi xuống một bên, bạch Thế Tôn, các du sĩ ngoại đạo ấy nói với con rằng: ",
  "sn44.2:2.8": "'Này Hiền giả Anurādha, Như Lai là bậc tối thượng, bậc tối thắng, đã đạt đến địa vị tối thắng. Như Lai được mô tả bằng bốn trường hợp này: '",
  "sn44.2:2.9": "'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.2:2.10": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'?' '",
  "sn44.2:2.11": "Khi được hỏi như vậy, bạch Thế Tôn, con đã nói với các du sĩ ngoại đạo ấy rằng: ",
  "sn44.2:2.12": "'Này Hiền giả, Như Lai là bậc tối thượng, bậc tối thắng, đã đạt đến địa vị tối thắng. Như Lai được mô tả ngoài bốn trường hợp này: '",
  "sn44.2:2.13": "'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.2:2.14": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'.' '",
  "sn44.2:2.15": "Khi con nói vậy, bạch Thế Tôn, các du sĩ ngoại đạo ấy nói với con rằng: ",
  "sn44.2:2.16": "'Vị Tỳ Kheo này chắc là người mới xuất gia, chưa lâu, hay là bậc trưởng lão ngu si, chưa thông đạt.' ",
  "sn44.2:2.17": "Khi ấy, bạch Thế Tôn, các du sĩ ngoại đạo ấy sau khi chê bai con bằng những lời như người mới và người ngu, đứng dậy khỏi chỗ ngồi rồi bỏ đi. ",
  "sn44.2:2.18": "Thưa Thế Tôn, khi các du sĩ ngoại đạo vừa rời đi, con nghĩ rằng: ",
  "sn44.2:2.19": "'Nếu các du sĩ ngoại đạo ấy hỏi thêm ta, ta trả lời như thế nào mới là nói đúng lời Thế Tôn, không xuyên tạc Thế Tôn bằng điều không thật, giải thích đúng pháp, và không bị ai có cùng quan điểm phê phán một cách chính đáng?'' '",
  "sn44.2:3.1": "'Này Anurādha, ông nghĩ thế nào, '",
  "sn44.2:3.2": "sắc là thường hay vô thường?' ",
  "sn44.2:4.1": "'Vô thường, bạch Thế Tôn.' ",
  "sn44.2:5.1": "'Cái gì vô thường, là khổ hay là lạc?' ",
  "sn44.2:6.1": "'Là khổ, bạch Thế Tôn.' ",
  "sn44.2:7.1": "'Cái gì vô thường, khổ, biến hoại, có hợp lý không khi nhìn nhận: '",
  "sn44.2:7.2": "'Cái này là của ta, đây là ta, đây là tự ngã của ta'?' '",
  "sn44.2:8.1": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:9.1": "'Thọ là thường hay vô thường?' ",
  "sn44.2:9.2": "… ",
  "sn44.2:9.3": "Tưởng… ",
  "sn44.2:9.4": "Hành… ",
  "sn44.2:9.5": "'Thức là thường hay vô thường?' ",
  "sn44.2:10.1": "'Vô thường, bạch Thế Tôn.' ",
  "sn44.2:11.1": "'Cái gì vô thường, là khổ hay là lạc?' ",
  "sn44.2:12.1": "'Là khổ, bạch Thế Tôn.' ",
  "sn44.2:13.1": "'Cái gì vô thường, khổ, biến hoại, có hợp lý không khi nhìn nhận: '",
  "sn44.2:13.2": "'Cái này là của ta, đây là ta, đây là tự ngã của ta'?' '",
  "sn44.2:14.1": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:15.1": "'Vì vậy, này Anurādha, bất kỳ sắc nào thuộc quá khứ, tương lai, hay hiện tại, trong hay ngoài, thô hay tế, hèn hay cao, xa hay gần, tất cả sắc đều phải được quán chiếu đúng như thật bằng chánh trí: 'Cái này không phải của ta, đây không phải là ta, đây không phải tự ngã của ta.' '",
  "sn44.2:15.2": "Bất kỳ thọ nào thuộc quá khứ, tương lai, hay hiện tại… ",
  "sn44.2:15.3": "bất kỳ tưởng nào… ",
  "sn44.2:15.4": "bất kỳ hành nào… ",
  "sn44.2:15.5": "bất kỳ thức nào thuộc quá khứ, tương lai, hay hiện tại, trong hay ngoài, thô hay tế, hèn hay cao, xa hay gần, tất cả thức đều phải được quán chiếu đúng như thật bằng chánh trí: 'Cái này không phải của ta, đây không phải là ta, đây không phải tự ngã của ta.' ",
  "sn44.2:15.6": "Thấy vậy, này Anurādha, bậc đa văn Thánh đệ tử nhàm chán sắc, nhàm chán thọ, nhàm chán tưởng, nhàm chán hành, nhàm chán thức. ",
  "sn44.2:15.7": "Do nhàm chán nên ly tham; do ly tham nên giải thoát; khi giải thoát, có trí biết rằng đã giải thoát. ",
  "sn44.2:15.8": "'Sinh đã tận, phạm hạnh đã thành, việc cần làm đã làm, không còn trở lại đời này nữa.' Vị ấy biết vậy. ",
  "sn44.2:16.1": "Này Anurādha, ông nghĩ thế nào, ",
  "sn44.2:16.2": "ông có xem sắc là Như Lai không?' ",
  "sn44.2:16.3": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:16.4": "'Ông có xem thọ là Như Lai không?' ",
  "sn44.2:16.5": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:16.6": "'Ông có xem tưởng là Như Lai không?' ",
  "sn44.2:16.7": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:16.8": "'Ông có xem hành là Như Lai không?' ",
  "sn44.2:16.9": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:16.10": "'Ông có xem thức là Như Lai không?' ",
  "sn44.2:16.11": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:16.12": "Này Anurādha, ông nghĩ thế nào, ",
  "sn44.2:16.13": "ông có xem Như Lai là ở trong sắc không?' ",
  "sn44.2:16.14": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:16.15": "'Ông có xem Như Lai là ngoài sắc không?' ",
  "sn44.2:16.16": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:16.17": "'Trong thọ… '",
  "sn44.2:16.18": "ngoài thọ… ",
  "sn44.2:16.19": "trong tưởng… ",
  "sn44.2:16.20": "ngoài tưởng… ",
  "sn44.2:16.21": "trong hành… ",
  "sn44.2:16.22": "ngoài hành… ",
  "sn44.2:16.23": "ông có xem Như Lai là ở trong thức không?' ",
  "sn44.2:16.24": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:16.25": "'Ông có xem Như Lai là ngoài thức không?' ",
  "sn44.2:16.26": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:17.1": "'Này Anurādha, ông nghĩ thế nào, '",
  "sn44.2:17.2": "ông có xem sắc, thọ, tưởng, hành, thức là Như Lai không?' ",
  "sn44.2:17.3": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:17.4": "'Này Anurādha, ông nghĩ thế nào, '",
  "sn44.2:17.5": "ông có xem đây là Như Lai  không có sắc, không có thọ, không có tưởng, không có hành, không có thức không?' ",
  "sn44.2:17.6": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:17.7": "'Này Anurādha, vì ngay trong đời này mà không thể tìm thấy Như Lai là thực, là chắc thật, thì lời tuyên bố đó của ông có hợp lý không '",
  "sn44.2:17.8": "rằng Như Lai là bậc tối thượng, bậc tối thắng, đã đạt đến địa vị tối thắng, và Như Lai được mô tả ngoài bốn trường hợp này: ",
  "sn44.2:17.9": "'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.2:17.10": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'?' '",
  "sn44.2:17.11": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.2:17.12": "'Lành thay, lành thay, này Anurādha. '",
  "sn44.2:17.13": "Trước đây và ngay bây giờ, Ta chỉ tuyên bố khổ và sự đoạn diệt của khổ.' ",
  "sn44.2:17.14": "Thứ hai. ",
  "sn44.3:0.1": "Tương Ưng Bộ 44.3 ",
  "sn44.3:0.2": "1. Phẩm Vô Ký ",
  "sn44.3:0.3": "Kinh Sāriputta-Koṭṭhika lần thứ nhất ",
  "sn44.3:1.1": "Một thời Tôn giả Sāriputta và Tôn giả Mahākoṭṭhika đang trú tại Bārāṇasī, vườn Nai, Isipatana. ",
  "sn44.3:1.2": "Khi ấy, Tôn giả Mahākoṭṭhika vào buổi chiều, sau khi xuất thiền định, đến chỗ Tôn giả Sāriputta; khi đến rồi, chào hỏi Tôn giả Sāriputta. ",
  "sn44.3:1.3": "Sau khi chào hỏi thân thiện rồi, ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Mahākoṭṭhika nói với Tôn giả Sāriputta rằng: ",
  "sn44.3:2.1": "'Thưa Hiền giả Sāriputta, sau khi chết Như Lai có tồn tại không?' ",
  "sn44.3:2.2": "'Thưa Hiền giả, điều này không được Thế Tôn tuyên bố: '",
  "sn44.3:2.3": "'Sau khi chết Như Lai có tồn tại.'' '",
  "sn44.3:2.4": "'Vậy thưa Hiền giả, sau khi chết Như Lai không tồn tại?' ",
  "sn44.3:2.5": "'Thưa Hiền giả, điều này cũng không được Thế Tôn tuyên bố: '",
  "sn44.3:2.6": "'Sau khi chết Như Lai không tồn tại.'' '",
  "sn44.3:2.7": "'Thưa Hiền giả, sau khi chết Như Lai vừa tồn tại vừa không tồn tại?' ",
  "sn44.3:2.8": "'Thưa Hiền giả, điều này không được Thế Tôn tuyên bố: '",
  "sn44.3:2.9": "'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại.'' '",
  "sn44.3:2.10": "'Vậy thưa Hiền giả, sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại?' ",
  "sn44.3:2.11": "'Thưa Hiền giả, điều này cũng không được Thế Tôn tuyên bố: '",
  "sn44.3:2.12": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.'' '",
  "sn44.3:3.1": "'Khi được hỏi 'Thưa Hiền giả, sau khi chết Như Lai có tồn tại không?', Hiền giả nói: 'Điều này không được Thế Tôn tuyên bố ",
  "sn44.3:3.2": "sau khi chết Như Lai có tồn tại'… ",
  "sn44.3:3.3": "Khi được hỏi 'Vậy thưa Hiền giả, sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại?', Hiền giả nói: ",
  "sn44.3:3.4": "'Thưa Hiền giả, điều này cũng không được Thế Tôn tuyên bố '",
  "sn44.3:3.5": "sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.3:3.6": "Vậy thưa Hiền giả, nguyên nhân gì, duyên gì mà Thế Tôn không tuyên bố điều này?' ",
  "sn44.3:4.1": "''Sau khi chết Như Lai có tồn tại'  thưa Hiền giả, đó là quy về sắc. '",
  "sn44.3:4.2": "'Sau khi chết Như Lai không tồn tại'  đó là quy về sắc. ",
  "sn44.3:4.3": "'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'  đó là quy về sắc. ",
  "sn44.3:4.4": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'  đó là quy về sắc. ",
  "sn44.3:4.5": "'Sau khi chết Như Lai có tồn tại'  thưa Hiền giả, đó là quy về thọ. ",
  "sn44.3:4.6": "'Sau khi chết Như Lai không tồn tại'  đó là quy về thọ. ",
  "sn44.3:4.7": "'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'  đó là quy về thọ. ",
  "sn44.3:4.8": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'  đó là quy về thọ. ",
  "sn44.3:4.9": "'Sau khi chết Như Lai có tồn tại'  thưa Hiền giả, đó là quy về tưởng. ",
  "sn44.3:4.10": "'Sau khi chết Như Lai không tồn tại'  đó là quy về tưởng. ",
  "sn44.3:4.11": "'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'  đó là quy về tưởng. ",
  "sn44.3:4.12": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'  đó là quy về tưởng. ",
  "sn44.3:4.13": "'Sau khi chết Như Lai có tồn tại'  thưa Hiền giả, đó là quy về hành. ",
  "sn44.3:4.14": "'Sau khi chết Như Lai không tồn tại'  đó là quy về hành. ",
  "sn44.3:4.15": "'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'  đó là quy về hành. ",
  "sn44.3:4.16": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'  đó là quy về hành. ",
  "sn44.3:4.17": "'Sau khi chết Như Lai có tồn tại'  thưa Hiền giả, đó là quy về thức. ",
  "sn44.3:4.18": "'Sau khi chết Như Lai không tồn tại'  đó là quy về thức. ",
  "sn44.3:4.19": "'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'  đó là quy về thức. ",
  "sn44.3:4.20": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'  đó là quy về thức. ",
  "sn44.3:4.21": "Đây, thưa Hiền giả, là nguyên nhân, là duyên, vì sao Thế Tôn không tuyên bố điều đó.' ",
  "sn44.3:4.22": "Thứ ba. ",
  "sn44.4:0.1": "Tương Ưng Bộ 44.4 ",
  "sn44.4:0.2": "1. Phẩm Vô Ký ",
  "sn44.4:0.3": "Kinh Sāriputta-Koṭṭhika lần thứ hai ",
  "sn44.4:1.1": "Một thời Tôn giả Sāriputta và Tôn giả Mahākoṭṭhika đang trú tại Bārāṇasī, vườn Nai, Isipatana… ",
  "sn44.4:1.2": "(Câu hỏi giống như trên.) ",
  "sn44.4:1.3": "'Thưa Hiền giả, nguyên nhân gì, duyên gì mà Thế Tôn không tuyên bố điều này?' ",
  "sn44.4:1.4": "'Thưa Hiền giả, người không biết, không thấy sắc đúng như thật, không biết, không thấy sự tập khởi của sắc đúng như thật, không biết, không thấy sự đoạn diệt của sắc đúng như thật, không biết, không thấy con đường dẫn đến sự đoạn diệt của sắc đúng như thật, người đó có quan niệm 'Sau khi chết Như Lai có tồn tại'; '",
  "sn44.4:1.5": "có quan niệm 'Sau khi chết Như Lai không tồn tại'; ",
  "sn44.4:1.6": "có quan niệm 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'; ",
  "sn44.4:1.7": "có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.4:1.8": "Thọ… ",
  "sn44.4:1.9": "tưởng… ",
  "sn44.4:1.10": "hành… ",
  "sn44.4:1.11": "người không biết, không thấy thức đúng như thật, không biết, không thấy sự tập khởi của thức đúng như thật, không biết, không thấy sự đoạn diệt của thức đúng như thật, không biết, không thấy con đường dẫn đến sự đoạn diệt của thức đúng như thật, người đó có quan niệm 'Sau khi chết Như Lai có tồn tại'; ",
  "sn44.4:1.12": "có quan niệm 'Sau khi chết Như Lai không tồn tại'; ",
  "sn44.4:1.13": "có quan niệm 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'; ",
  "sn44.4:1.14": "có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.4:2.1": "Thưa Hiền giả, người biết, thấy sắc đúng như thật, biết, thấy sự tập khởi của sắc đúng như thật, biết, thấy sự đoạn diệt của sắc đúng như thật, biết, thấy con đường dẫn đến sự đoạn diệt của sắc đúng như thật, người đó không có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.4:2.2": "không có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.4:2.3": "Thọ… ",
  "sn44.4:2.4": "tưởng… ",
  "sn44.4:2.5": "hành… ",
  "sn44.4:2.6": "người biết, thấy thức đúng như thật, biết, thấy sự tập khởi của thức đúng như thật, biết, thấy sự đoạn diệt của thức đúng như thật, biết, thấy con đường dẫn đến sự đoạn diệt của thức đúng như thật, người đó không có quan niệm 'Sau khi chết Như Lai có tồn tại'; ",
  "sn44.4:2.7": "không có quan niệm 'Sau khi chết Như Lai không tồn tại'; ",
  "sn44.4:2.8": "không có quan niệm 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'; ",
  "sn44.4:2.9": "không có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.4:2.10": "Đây, thưa Hiền giả, là nguyên nhân, là duyên, vì sao Thế Tôn không tuyên bố điều đó.' ",
  "sn44.4:2.11": "Thứ tư. ",
  "sn44.5:0.1": "Tương Ưng Bộ 44.5 ",
  "sn44.5:0.2": "1. Phẩm Vô Ký ",
  "sn44.5:0.3": "Kinh Sāriputta-Koṭṭhika lần thứ ba ",
  "sn44.5:1.1": "Một thời Tôn giả Sāriputta và Tôn giả Mahākoṭṭhika đang trú tại Bārāṇasī, vườn Nai, Isipatana… ",
  "sn44.5:1.2": "(Câu hỏi giống như trên.) ",
  "sn44.5:1.3": "'Thưa Hiền giả, nguyên nhân gì, duyên gì mà Thế Tôn không tuyên bố điều này?' ",
  "sn44.5:1.4": "'Thưa Hiền giả, người chưa ly tham đối với sắc, chưa ly dục, chưa ly ái, chưa ly khát vọng, chưa ly nhiệt tình, chưa ly tham ái  người đó có quan niệm 'Sau khi chết Như Lai có tồn tại'… '",
  "sn44.5:1.5": "có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.5:1.6": "Đối với thọ… ",
  "sn44.5:1.7": "đối với tưởng… ",
  "sn44.5:1.8": "đối với hành… ",
  "sn44.5:1.9": "người chưa ly tham đối với thức, chưa ly dục, chưa ly ái, chưa ly khát vọng, chưa ly nhiệt tình, chưa ly tham ái  người đó có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.5:1.10": "có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.5:1.11": "Thưa Hiền giả, người đã ly tham đối với sắc… ",
  "sn44.5:1.12": "đối với thọ… ",
  "sn44.5:1.13": "đối với tưởng… ",
  "sn44.5:1.14": "đối với hành… ",
  "sn44.5:1.15": "người đã ly tham đối với thức, đã ly dục, đã ly ái, đã ly khát vọng, đã ly nhiệt tình, đã ly tham ái  người đó không có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.5:1.16": "không có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.5:1.17": "Đây, thưa Hiền giả, là nguyên nhân, là duyên, vì sao Thế Tôn không tuyên bố điều đó.' ",
  "sn44.5:1.18": "Thứ năm. ",
  "sn44.6:0.1": "Tương Ưng Bộ 44.6 ",
  "sn44.6:0.2": "1. Phẩm Vô Ký ",
  "sn44.6:0.3": "Kinh Sāriputta-Koṭṭhika lần thứ tư ",
  "sn44.6:1.1": "Một thời Tôn giả Sāriputta và Tôn giả Mahākoṭṭhika đang trú tại Bārāṇasī, vườn Nai, Isipatana. ",
  "sn44.6:1.2": "Khi ấy, Tôn giả Sāriputta vào buổi chiều, sau khi xuất thiền định, đến chỗ Tôn giả Mahākoṭṭhika; khi đến rồi, chào hỏi Tôn giả Mahākoṭṭhika. ",
  "sn44.6:1.3": "Sau khi chào hỏi thân thiện rồi, ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Sāriputta nói với Tôn giả Mahākoṭṭhika rằng: ",
  "sn44.6:1.4": "''Thưa Hiền giả Koṭṭhika, sau khi chết Như Lai có tồn tại không?'… '",
  "sn44.6:1.5": "'Vậy thưa Hiền giả, sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại?' Khi được hỏi vậy, Hiền giả nói: ",
  "sn44.6:1.6": "'Thưa Hiền giả, điều này cũng không được Thế Tôn tuyên bố '",
  "sn44.6:1.7": "sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.6:1.8": "Vậy thưa Hiền giả, nguyên nhân gì, duyên gì mà Thế Tôn không tuyên bố điều này?' ",
  "sn44.6:2.1": "'Thưa Hiền giả, người ưa thích sắc, đắm say sắc, vui thích sắc, không biết không thấy sự đoạn diệt của sắc đúng như thật  người đó có quan niệm 'Sau khi chết Như Lai có tồn tại'; '",
  "sn44.6:2.2": "có quan niệm 'Sau khi chết Như Lai không tồn tại'; ",
  "sn44.6:2.3": "có quan niệm 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại'; ",
  "sn44.6:2.4": "có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.6:2.5": "Thưa Hiền giả, người ưa thích thọ, đắm say thọ, vui thích thọ, không biết không thấy sự đoạn diệt của thọ đúng như thật  người đó có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.6:2.6": "người ưa thích tưởng, thưa Hiền giả… ",
  "sn44.6:2.7": "người ưa thích hành, thưa Hiền giả… ",
  "sn44.6:2.8": "thưa Hiền giả, người ưa thích thức, đắm say thức, vui thích thức, không biết không thấy sự đoạn diệt của thức đúng như thật  người đó có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.6:2.9": "có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.6:3.1": "Thưa Hiền giả, người không ưa thích sắc, không đắm say sắc, không vui thích sắc, biết thấy sự đoạn diệt của sắc đúng như thật  người đó không có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.6:3.2": "không có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.6:3.3": "Người không ưa thích thọ, thưa Hiền giả… ",
  "sn44.6:3.4": "người không ưa thích tưởng, thưa Hiền giả… ",
  "sn44.6:3.5": "người không ưa thích hành, thưa Hiền giả… ",
  "sn44.6:3.6": "thưa Hiền giả, người không ưa thích thức, không đắm say thức, không vui thích thức, biết thấy sự đoạn diệt của thức đúng như thật  người đó không có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.6:3.7": "không có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.6:3.8": "Đây, thưa Hiền giả, là nguyên nhân, là duyên, vì sao Thế Tôn không tuyên bố điều đó.' ",
  "sn44.6:4.1": "'Thưa Hiền giả, có thể có cách giải thích nào khác không, vì sao Thế Tôn không tuyên bố điều này?' ",
  "sn44.6:4.2": "'Có thể, thưa Hiền giả. '",
  "sn44.6:4.3": "Thưa Hiền giả, người ưa thích hữu, đắm say hữu, vui thích hữu, không biết không thấy sự đoạn diệt của hữu đúng như thật  người đó có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.6:4.4": "có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.6:4.5": "Thưa Hiền giả, người không ưa thích hữu, không đắm say hữu, không vui thích hữu, biết thấy sự đoạn diệt của hữu đúng như thật  người đó không có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.6:4.6": "không có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.6:4.7": "Đây cũng là một cách giải thích, thưa Hiền giả, vì sao Thế Tôn không tuyên bố điều đó.' ",
  "sn44.6:5.1": "'Thưa Hiền giả, có thể có cách giải thích nào khác không, vì sao Thế Tôn không tuyên bố điều này?' ",
  "sn44.6:5.2": "'Có thể, thưa Hiền giả. '",
  "sn44.6:5.3": "Thưa Hiền giả, người ưa thích thủ, đắm say thủ, vui thích thủ, không biết không thấy sự đoạn diệt của thủ đúng như thật  người đó có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.6:5.4": "có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.6:5.5": "Thưa Hiền giả, người không ưa thích thủ, không đắm say thủ, không vui thích thủ, biết thấy sự đoạn diệt của thủ đúng như thật  người đó không có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.6:5.6": "không có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.6:5.7": "Đây cũng là một cách giải thích, thưa Hiền giả, vì sao Thế Tôn không tuyên bố điều đó.' ",
  "sn44.6:6.1": "'Thưa Hiền giả, có thể có cách giải thích nào khác không, vì sao Thế Tôn không tuyên bố điều này?' ",
  "sn44.6:6.2": "'Có thể, thưa Hiền giả. '",
  "sn44.6:6.3": "Thưa Hiền giả, người ưa thích ái, đắm say ái, vui thích ái, không biết không thấy sự đoạn diệt của ái đúng như thật  người đó có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.6:6.4": "có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.6:6.5": "Thưa Hiền giả, người không ưa thích ái, không đắm say ái, không vui thích ái, biết thấy sự đoạn diệt của ái đúng như thật  người đó không có quan niệm 'Sau khi chết Như Lai có tồn tại'… ",
  "sn44.6:6.6": "không có quan niệm 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.6:6.7": "Đây cũng là một cách giải thích, thưa Hiền giả, vì sao Thế Tôn không tuyên bố điều đó.' ",
  "sn44.6:7.1": "'Thưa Hiền giả, có thể có cách giải thích nào khác không, vì sao Thế Tôn không tuyên bố điều này?' ",
  "sn44.6:7.2": "'Thưa Hiền giả Sāriputta, về điều này, còn muốn gì hơn nữa? '",
  "sn44.6:7.3": "Thưa Hiền giả Sāriputta, đối với vị Tỳ Kheo đã được giải thoát nhờ đoạn trừ tham ái, không còn sự luân hồi nào để mô tả thêm.' ",
  "sn44.6:7.4": "Thứ sáu. ",
  "sn44.7:0.1": "Tương Ưng Bộ 44.7 ",
  "sn44.7:0.2": "1. Phẩm Vô Ký ",
  "sn44.7:0.3": "Kinh Moggallāna ",
  "sn44.7:1.1": "Khi ấy, du sĩ ngoại đạo Vacchagotta đến chỗ Tôn giả Mahāmoggallāna; khi đến rồi, chào hỏi Tôn giả Mahāmoggallāna. ",
  "sn44.7:1.2": "Sau khi chào hỏi thân thiện rồi, ngồi xuống một bên. Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta nói với Tôn giả Mahāmoggallāna rằng: ",
  "sn44.7:2.1": "'Thưa Tôn giả Moggallāna, thế giới là thường hằng không?' ",
  "sn44.7:2.2": "'Thưa Vaccha, điều này không được Thế Tôn tuyên bố: '",
  "sn44.7:2.3": "'Thế giới là thường hằng.'' '",
  "sn44.7:2.4": "'Vậy thưa Tôn giả Moggallāna, thế giới là vô thường không?' ",
  "sn44.7:2.5": "'Thưa Vaccha, điều này cũng không được Thế Tôn tuyên bố: '",
  "sn44.7:2.6": "'Thế giới là vô thường.'' '",
  "sn44.7:2.7": "'Thưa Tôn giả Moggallāna, thế giới có giới hạn không?' ",
  "sn44.7:2.8": "'Thưa Vaccha, điều này không được Thế Tôn tuyên bố: '",
  "sn44.7:2.9": "'Thế giới có giới hạn.'' '",
  "sn44.7:2.10": "'Vậy thưa Tôn giả Moggallāna, thế giới là vô tận không?' ",
  "sn44.7:2.11": "'Thưa Vaccha, điều này cũng không được Thế Tôn tuyên bố: '",
  "sn44.7:2.12": "'Thế giới là vô tận.'' '",
  "sn44.7:2.13": "'Thưa Tôn giả Moggallāna, sinh mạng và thân xác là một không?' ",
  "sn44.7:2.14": "'Thưa Vaccha, điều này không được Thế Tôn tuyên bố: '",
  "sn44.7:2.15": "'Sinh mạng và thân xác là một.'' '",
  "sn44.7:2.16": "'Vậy thưa Tôn giả Moggallāna, sinh mạng và thân xác là khác nhau không?' ",
  "sn44.7:2.17": "'Thưa Vaccha, điều này cũng không được Thế Tôn tuyên bố: '",
  "sn44.7:2.18": "'Sinh mạng và thân xác là khác nhau.'' '",
  "sn44.7:2.19": "'Thưa Tôn giả Moggallāna, sau khi chết Như Lai có tồn tại không?' ",
  "sn44.7:2.20": "'Thưa Vaccha, điều này không được Thế Tôn tuyên bố: '",
  "sn44.7:2.21": "'Sau khi chết Như Lai có tồn tại.'' '",
  "sn44.7:2.22": "'Vậy thưa Tôn giả Moggallāna, sau khi chết Như Lai không tồn tại không?' ",
  "sn44.7:2.23": "'Thưa Vaccha, điều này cũng không được Thế Tôn tuyên bố: '",
  "sn44.7:2.24": "'Sau khi chết Như Lai không tồn tại.'' '",
  "sn44.7:2.25": "'Thưa Tôn giả Moggallāna, sau khi chết Như Lai vừa tồn tại vừa không tồn tại không?' ",
  "sn44.7:2.26": "'Thưa Vaccha, điều này không được Thế Tôn tuyên bố: '",
  "sn44.7:2.27": "'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại.'' '",
  "sn44.7:2.28": "'Vậy thưa Tôn giả Moggallāna, sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại không?' ",
  "sn44.7:2.29": "'Thưa Vaccha, điều này cũng không được Thế Tôn tuyên bố: '",
  "sn44.7:2.30": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.'' '",
  "sn44.7:3.1": "'Thưa Tôn giả Moggallāna, nguyên nhân gì, duyên gì mà khi được hỏi như vậy, các du sĩ ngoại đạo trả lời '",
  "sn44.7:3.2": "'Thế giới là thường hằng', hay 'Thế giới là vô thường', hay 'Thế giới có giới hạn', hay 'Thế giới là vô tận', hay 'Sinh mạng và thân xác là một', hay 'Sinh mạng và thân xác là khác nhau', hay 'Sau khi chết Như Lai có tồn tại', hay 'Sau khi chết Như Lai không tồn tại', hay 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại', hay 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'? ",
  "sn44.7:3.3": "Còn nguyên nhân gì, duyên gì mà khi được hỏi như vậy, sa-môn Gotama không trả lời như vậy ",
  "sn44.7:3.4": "'Thế giới là thường hằng', hay 'Thế giới là vô thường', hay 'Thế giới có giới hạn', hay 'Thế giới là vô tận', hay 'Sinh mạng và thân xác là một', hay 'Sinh mạng và thân xác là khác nhau', hay 'Sau khi chết Như Lai có tồn tại', hay 'Sau khi chết Như Lai không tồn tại', hay 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại', hay 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'?' '",
  "sn44.7:4.1": "'Thưa Vaccha, các du sĩ ngoại đạo xem mắt là 'cái này là của ta, đây là ta, đây là tự ngã của ta'… '",
  "sn44.7:4.2": "xem lưỡi là 'cái này là của ta, đây là ta, đây là tự ngã của ta'… ",
  "sn44.7:4.3": "xem ý là 'cái này là của ta, đây là ta, đây là tự ngã của ta.' ",
  "sn44.7:4.4": "Vì vậy, khi các du sĩ ngoại đạo được hỏi như vậy, họ trả lời ",
  "sn44.7:4.5": "'Thế giới là thường hằng'… ",
  "sn44.7:4.6": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.7:4.7": "Còn Như Lai, bậc Ứng Cúng, Chánh Đẳng Giác, xem mắt là 'cái này không phải của ta, đây không phải là ta, đây không phải tự ngã của ta'… ",
  "sn44.7:4.8": "xem lưỡi là 'cái này không phải của ta, đây không phải là ta, đây không phải tự ngã của ta'… ",
  "sn44.7:4.9": "xem ý là 'cái này không phải của ta, đây không phải là ta, đây không phải tự ngã của ta.' ",
  "sn44.7:4.10": "Vì vậy, khi Như Lai được hỏi như vậy, Ngài không trả lời ",
  "sn44.7:4.11": "'Thế giới là thường hằng'… ",
  "sn44.7:4.12": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.'' '",
  "sn44.7:5.1": "Khi ấy, du sĩ ngoại đạo Vacchagotta đứng dậy khỏi chỗ ngồi, đến chỗ Thế Tôn; khi đến rồi, chào hỏi Thế Tôn. ",
  "sn44.7:5.2": "Sau khi chào hỏi thân thiện rồi, ngồi xuống một bên. Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta bạch Thế Tôn rằng: ",
  "sn44.7:5.3": "'Thưa Tôn giả Gotama, thế giới là thường hằng không?' ",
  "sn44.7:5.4": "'Thưa Vaccha, điều này Ta không tuyên bố: 'Thế giới là thường hằng'… '",
  "sn44.7:5.5": "'Vậy thưa Tôn giả Gotama, sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại không?' ",
  "sn44.7:5.6": "'Thưa Vaccha, điều này cũng không được Ta tuyên bố: '",
  "sn44.7:5.7": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.'' '",
  "sn44.7:6.1": "'Thưa Tôn giả Gotama, nguyên nhân gì, duyên gì mà khi được hỏi như vậy, các du sĩ ngoại đạo trả lời: '",
  "sn44.7:6.2": "'Thế giới là thường hằng'… ",
  "sn44.7:6.3": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'? ",
  "sn44.7:6.4": "Còn nguyên nhân gì, duyên gì mà khi được hỏi như vậy, Tôn giả Gotama không trả lời: ",
  "sn44.7:6.5": "'Thế giới là thường hằng'… ",
  "sn44.7:6.6": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'?' '",
  "sn44.7:7.1": "'Thưa Vaccha, các du sĩ ngoại đạo xem mắt là 'cái này là của ta, đây là ta, đây là tự ngã của ta'… '",
  "sn44.7:7.2": "xem lưỡi là 'cái này là của ta, đây là ta, đây là tự ngã của ta'… ",
  "sn44.7:7.3": "xem ý là 'cái này là của ta, đây là ta, đây là tự ngã của ta.' ",
  "sn44.7:7.4": "Vì vậy, khi các du sĩ ngoại đạo được hỏi như vậy, họ trả lời: ",
  "sn44.7:7.5": "'Thế giới là thường hằng'… ",
  "sn44.7:7.6": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.7:7.7": "Còn Như Lai, bậc Ứng Cúng, Chánh Đẳng Giác, xem mắt là 'cái này không phải của ta, đây không phải là ta, đây không phải tự ngã của ta'… ",
  "sn44.7:7.8": "xem lưỡi là 'cái này không phải của ta, đây không phải là ta, đây không phải tự ngã của ta'… ",
  "sn44.7:7.9": "xem ý là 'cái này không phải của ta, đây không phải là ta, đây không phải tự ngã của ta.' ",
  "sn44.7:7.10": "Vì vậy, khi Như Lai được hỏi như vậy, Ngài không trả lời: ",
  "sn44.7:7.11": "'Thế giới là thường hằng', 'Thế giới là vô thường', 'Thế giới có giới hạn', 'Thế giới là vô tận', 'Sinh mạng và thân xác là một', 'Sinh mạng và thân xác là khác nhau', 'Sau khi chết Như Lai có tồn tại', 'Sau khi chết Như Lai không tồn tại', 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại', 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.'' '",
  "sn44.7:8.1": "'Thật kỳ diệu, thưa Tôn giả Gotama, thật hy hữu, thưa Tôn giả Gotama. '",
  "sn44.7:8.2": "Thật vậy, lời dạy của bậc Đạo Sư và của đệ tử đồng nhất về nghĩa, đồng nhất về văn cú, không mâu thuẫn nhau, ở điều tối thượng. ",
  "sn44.7:8.3": "Nay con, thưa Tôn giả Gotama, đã đến chỗ sa-môn Mahāmoggallāna và hỏi điều này. ",
  "sn44.7:8.4": "Sa-môn Moggallāna cũng đã giải thích điều này cho con bằng những từ ngữ và văn cú đó, giống như Tôn giả Gotama vậy. ",
  "sn44.7:8.5": "Thật kỳ diệu, thưa Tôn giả Gotama, thật hy hữu, thưa Tôn giả Gotama. ",
  "sn44.7:8.6": "Thật vậy, lời dạy của bậc Đạo Sư và của đệ tử đồng nhất về nghĩa, đồng nhất về văn cú, không mâu thuẫn nhau, ở điều tối thượng.' ",
  "sn44.7:8.7": "Thứ bảy. ",
  "sn44.8:0.1": "Tương Ưng Bộ 44.8 ",
  "sn44.8:0.2": "1. Phẩm Vô Ký ",
  "sn44.8:0.3": "Kinh Vacchagotta ",
  "sn44.8:1.1": "Khi ấy, du sĩ ngoại đạo Vacchagotta đến chỗ Thế Tôn; khi đến rồi, chào hỏi Thế Tôn. ",
  "sn44.8:1.2": "Sau khi chào hỏi thân thiện rồi, ngồi xuống một bên. Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta bạch Thế Tôn rằng: ",
  "sn44.8:1.3": "'Thưa Tôn giả Gotama, thế giới là thường hằng không?' ",
  "sn44.8:1.4": "'Thưa Vaccha, điều này Ta không tuyên bố: 'Thế giới là thường hằng'… '",
  "sn44.8:1.5": "'Vậy thưa Tôn giả Gotama, 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'?' ",
  "sn44.8:1.6": "'Thưa Vaccha, điều này cũng không được Ta tuyên bố: '",
  "sn44.8:1.7": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.'' '",
  "sn44.8:2.1": "'Thưa Tôn giả Gotama, nguyên nhân gì, duyên gì mà khi được hỏi như vậy, các du sĩ ngoại đạo trả lời: '",
  "sn44.8:2.2": "'Thế giới là thường hằng'… ",
  "sn44.8:2.3": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'? ",
  "sn44.8:2.4": "Còn nguyên nhân gì, duyên gì mà khi được hỏi như vậy, Tôn giả Gotama không trả lời: ",
  "sn44.8:2.5": "'Thế giới là thường hằng'… ",
  "sn44.8:2.6": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'?' '",
  "sn44.8:3.1": "'Thưa Vaccha, các du sĩ ngoại đạo xem sắc là tự ngã, hay xem tự ngã là có sắc, hay xem sắc trong tự ngã, hay xem tự ngã trong sắc. '",
  "sn44.8:3.2": "Xem thọ là tự ngã… ",
  "sn44.8:3.3": "tưởng… ",
  "sn44.8:3.4": "hành… ",
  "sn44.8:3.5": "xem thức là tự ngã, hay xem tự ngã là có thức, hay xem thức trong tự ngã, hay xem tự ngã trong thức. ",
  "sn44.8:3.6": "Vì vậy, khi các du sĩ ngoại đạo được hỏi như vậy, họ trả lời: ",
  "sn44.8:3.7": "'Thế giới là thường hằng'… ",
  "sn44.8:3.8": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.8:3.9": "Còn Như Lai, bậc Ứng Cúng, Chánh Đẳng Giác, không xem sắc là tự ngã, không xem tự ngã là có sắc, không xem sắc trong tự ngã, không xem tự ngã trong sắc. ",
  "sn44.8:3.10": "Không xem thọ là tự ngã… ",
  "sn44.8:3.11": "không xem tưởng… ",
  "sn44.8:3.12": "không xem hành… ",
  "sn44.8:3.13": "không xem thức là tự ngã, không xem tự ngã là có thức, không xem thức trong tự ngã, không xem tự ngã trong thức. ",
  "sn44.8:3.14": "Vì vậy, khi Như Lai được hỏi như vậy, Ngài không trả lời: ",
  "sn44.8:3.15": "'Thế giới là thường hằng'… ",
  "sn44.8:3.16": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.'' '",
  "sn44.8:4.1": "Khi ấy, du sĩ ngoại đạo Vacchagotta đứng dậy khỏi chỗ ngồi, đến chỗ Tôn giả Mahāmoggallāna; khi đến rồi, chào hỏi Tôn giả Mahāmoggallāna. ",
  "sn44.8:4.2": "Sau khi chào hỏi thân thiện rồi, ngồi xuống một bên. Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta nói với Tôn giả Mahāmoggallāna rằng: ",
  "sn44.8:4.3": "'Thưa Tôn giả Moggallāna, thế giới là thường hằng không?' ",
  "sn44.8:4.4": "'Thưa Vaccha, điều này không được Thế Tôn tuyên bố: 'Thế giới là thường hằng'… '",
  "sn44.8:4.5": "'Vậy thưa Tôn giả Moggallāna, 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'?' ",
  "sn44.8:4.6": "'Thưa Vaccha, điều này cũng không được Thế Tôn tuyên bố: '",
  "sn44.8:4.7": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.'' '",
  "sn44.8:5.1": "'Thưa Tôn giả Moggallāna, nguyên nhân gì, duyên gì mà khi được hỏi như vậy, các du sĩ ngoại đạo trả lời: '",
  "sn44.8:5.2": "'Thế giới là thường hằng'… ",
  "sn44.8:5.3": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'? ",
  "sn44.8:5.4": "Còn nguyên nhân gì, duyên gì mà khi được hỏi như vậy, sa-môn Gotama không trả lời: ",
  "sn44.8:5.5": "'Thế giới là thường hằng'… ",
  "sn44.8:5.6": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại'?' '",
  "sn44.8:6.1": "'Thưa Vaccha, các du sĩ ngoại đạo xem sắc là tự ngã, hay xem tự ngã là có sắc, hay xem sắc trong tự ngã, hay xem tự ngã trong sắc. '",
  "sn44.8:6.2": "Xem thọ là tự ngã… ",
  "sn44.8:6.3": "tưởng… ",
  "sn44.8:6.4": "hành… ",
  "sn44.8:6.5": "xem thức là tự ngã, hay xem tự ngã là có thức, hay xem thức trong tự ngã, hay xem tự ngã trong thức. ",
  "sn44.8:6.6": "Vì vậy, khi các du sĩ ngoại đạo được hỏi như vậy, họ trả lời: ",
  "sn44.8:6.7": "'Thế giới là thường hằng'… ",
  "sn44.8:6.8": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.8:6.9": "Còn Như Lai, bậc Ứng Cúng, Chánh Đẳng Giác, không xem sắc là tự ngã, không xem tự ngã là có sắc, không xem sắc trong tự ngã, không xem tự ngã trong sắc. ",
  "sn44.8:6.10": "Không xem thọ là tự ngã… ",
  "sn44.8:6.11": "không xem tưởng… ",
  "sn44.8:6.12": "không xem hành… ",
  "sn44.8:6.13": "không xem thức là tự ngã, không xem tự ngã là có thức, không xem thức trong tự ngã, không xem tự ngã trong thức. ",
  "sn44.8:6.14": "Vì vậy, khi Như Lai được hỏi như vậy, Ngài không trả lời: ",
  "sn44.8:6.15": "'Thế giới là thường hằng', 'Thế giới là vô thường', 'Thế giới có giới hạn', 'Thế giới là vô tận', 'Sinh mạng và thân xác là một', 'Sinh mạng và thân xác là khác nhau', 'Sau khi chết Như Lai có tồn tại', 'Sau khi chết Như Lai không tồn tại', 'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại', 'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.'' '",
  "sn44.8:7.1": "'Thật kỳ diệu, thưa Tôn giả Moggallāna, thật hy hữu, thưa Tôn giả Moggallāna. '",
  "sn44.8:7.2": "Thật vậy, lời dạy của bậc Đạo Sư và của đệ tử đồng nhất về nghĩa, đồng nhất về văn cú, không mâu thuẫn nhau, ở điều tối thượng. ",
  "sn44.8:7.3": "Nay con, thưa Tôn giả Moggallāna, đã đến chỗ sa-môn Gotama và hỏi điều này. ",
  "sn44.8:7.4": "Sa-môn Gotama cũng đã giải thích điều này cho con bằng những từ ngữ và văn cú đó, giống như Tôn giả Moggallāna vậy. ",
  "sn44.8:7.5": "Thật kỳ diệu, thưa Tôn giả Moggallāna, thật hy hữu, thưa Tôn giả Moggallāna. ",
  "sn44.8:7.6": "Thật vậy, lời dạy của bậc Đạo Sư và của đệ tử đồng nhất về nghĩa, đồng nhất về văn cú, không mâu thuẫn nhau, ở điều tối thượng.' ",
  "sn44.8:7.7": "Thứ tám. ",
  "sn44.9:0.1": "Tương Ưng Bộ 44.9 ",
  "sn44.9:0.2": "1. Phẩm Vô Ký ",
  "sn44.9:0.3": "Kinh Hội Trường Bàn Luận ",
  "sn44.9:1.1": "Khi ấy, du sĩ ngoại đạo Vacchagotta đến chỗ Thế Tôn; khi đến rồi, chào hỏi Thế Tôn. ",
  "sn44.9:1.2": "Sau khi chào hỏi thân thiện rồi, ngồi xuống một bên. Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta bạch Thế Tôn rằng: ",
  "sn44.9:2.1": "'Thưa Tôn giả Gotama, vài ngày trước đây, nhiều sa-môn, bà-la-môn, du sĩ ngoại đạo thuộc nhiều tông phái đang ngồi hội họp tại hội trường bàn luận, có cuộc trò chuyện này nổi lên: '",
  "sn44.9:2.2": "'Ông Pūraṇa Kassapa này có tăng đoàn, có hội chúng, là thầy của hội chúng, được biết đến, có danh tiếng, là vị sáng lập giáo phái, được nhiều người xem là bậc thiện. '",
  "sn44.9:2.3": "Ông ấy cũng tuyên bố về đệ tử đã qua đời, về sự tái sinh của họ: ",
  "sn44.9:2.4": "'Vị đó được tái sinh ở đó, vị đó được tái sinh ở đó.' ",
  "sn44.9:2.5": "Ngay cả đệ tử là bậc tối thượng, bậc tối thắng, đã đạt đến địa vị tối thắng khi đã qua đời, ông ấy cũng tuyên bố về sự tái sinh: ",
  "sn44.9:2.6": "'Vị đó được tái sinh ở đó, vị đó được tái sinh ở đó.' ",
  "sn44.9:3.1": "Ông Makkhali Gosāla cũng vậy… ",
  "sn44.9:3.2": "Ông Nigaṇṭha Nāṭaputta cũng vậy… ",
  "sn44.9:3.3": "Ông Sañcaya Belaṭṭhaputta cũng vậy… ",
  "sn44.9:3.4": "Ông Pakudha Kaccāyana cũng vậy… ",
  "sn44.9:3.5": "Ông Ajita Kesakambala này có tăng đoàn, có hội chúng, là thầy của hội chúng, được biết đến, có danh tiếng, là vị sáng lập giáo phái, được nhiều người xem là bậc thiện. ",
  "sn44.9:3.6": "Ông ấy cũng tuyên bố về đệ tử đã qua đời, về sự tái sinh của họ: ",
  "sn44.9:3.7": "'Vị đó được tái sinh ở đó, vị đó được tái sinh ở đó.' ",
  "sn44.9:3.8": "Ngay cả đệ tử là bậc tối thượng, bậc tối thắng, đã đạt đến địa vị tối thắng khi đã qua đời, ông ấy cũng tuyên bố về sự tái sinh: ",
  "sn44.9:3.9": "'Vị đó được tái sinh ở đó, vị đó được tái sinh ở đó.' ",
  "sn44.9:4.1": "Sa-môn Gotama này có tăng đoàn, có hội chúng, là thầy của hội chúng, được biết đến, có danh tiếng, là vị sáng lập giáo phái, được nhiều người xem là bậc thiện. ",
  "sn44.9:4.2": "Ông ấy cũng tuyên bố về đệ tử đã qua đời, về sự tái sinh của họ: ",
  "sn44.9:4.3": "'Vị đó được tái sinh ở đó, vị đó được tái sinh ở đó.' ",
  "sn44.9:4.4": "Nhưng đệ tử là bậc tối thượng, bậc tối thắng, đã đạt đến địa vị tối thắng khi đã qua đời, ông ấy không tuyên bố về sự tái sinh: ",
  "sn44.9:4.5": "'Vị đó được tái sinh ở đó, vị đó được tái sinh ở đó.' ",
  "sn44.9:4.6": "Trái lại, ông ấy tuyên bố như vầy: ",
  "sn44.9:4.7": "'Vị đó đã cắt đứt tham ái, tháo bỏ kiết sử, nhờ thắng tri về mạn mà đã chấm dứt khổ đau.'' '",
  "sn44.9:4.8": "Thưa Tôn giả Gotama, con có hoài nghi, có phân vân: ",
  "sn44.9:4.9": "'Làm sao có thể hiểu được pháp của sa-môn Gotama?'' '",
  "sn44.9:5.1": "'Thưa Vaccha, đủ lý do để ông hoài nghi, đủ lý do để ông phân vân. '",
  "sn44.9:5.2": "Sự phân vân nổi lên ở chỗ đáng phân vân. ",
  "sn44.9:5.3": "Thưa Vaccha, Ta nói sự tái sinh là dành cho người còn thủ, không phải cho người không còn thủ. ",
  "sn44.9:5.4": "Cũng như, thưa Vaccha, ngọn lửa cháy khi còn nhiên liệu, không cháy khi không còn nhiên liệu; ",
  "sn44.9:5.5": "cũng vậy, thưa Vaccha, Ta nói sự tái sinh là dành cho người còn thủ, không phải cho người không còn thủ.' ",
  "sn44.9:6.1": "'Thưa Tôn giả Gotama, khi ngọn lửa bị gió thổi bay đi xa, Tôn giả Gotama gọi đó là thủ gì?' ",
  "sn44.9:6.2": "'Thưa Vaccha, khi ngọn lửa bị gió thổi bay đi xa, Ta gọi đó là lấy gió làm thủ. '",
  "sn44.9:6.3": "Thưa Vaccha, lúc đó gió là chỗ nương của ngọn lửa.' ",
  "sn44.9:6.4": "'Thưa Tôn giả Gotama, khi chúng sinh bỏ thân này mà chưa tái sinh vào thân khác, Tôn giả Gotama gọi đó là thủ gì?' ",
  "sn44.9:6.5": "'Thưa Vaccha, khi chúng sinh bỏ thân này mà chưa tái sinh vào thân khác, Ta nói đó là lấy ái làm thủ. '",
  "sn44.9:6.6": "Thưa Vaccha, lúc đó ái là chỗ nương của chúng sinh.' ",
  "sn44.9:6.7": "Thứ chín. ",
  "sn44.10:0.1": "Tương Ưng Bộ 44.10 ",
  "sn44.10:0.2": "1. Phẩm Vô Ký ",
  "sn44.10:0.3": "Kinh Ānanda ",
  "sn44.10:1.1": "Khi ấy, du sĩ ngoại đạo Vacchagotta đến chỗ Thế Tôn; khi đến rồi, chào hỏi Thế Tôn. ",
  "sn44.10:1.2": "Sau khi chào hỏi thân thiện rồi, ngồi xuống một bên. Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta bạch Thế Tôn rằng: ",
  "sn44.10:1.3": "'Thưa Tôn giả Gotama, có tự ngã không?' ",
  "sn44.10:1.4": "Khi được hỏi vậy, Thế Tôn im lặng. ",
  "sn44.10:1.5": "'Thưa Tôn giả Gotama, vậy không có tự ngã không?' ",
  "sn44.10:1.6": "Lần thứ hai Thế Tôn cũng im lặng. ",
  "sn44.10:1.7": "Khi ấy, du sĩ ngoại đạo Vacchagotta đứng dậy khỏi chỗ ngồi rồi bỏ đi. ",
  "sn44.10:2.1": "Khi ấy, Tôn giả Ānanda, sau khi du sĩ ngoại đạo Vacchagotta vừa rời đi, bạch Thế Tôn rằng: ",
  "sn44.10:2.2": "'Bạch Thế Tôn, tại sao khi du sĩ ngoại đạo Vacchagotta hỏi, Thế Tôn lại không trả lời?' ",
  "sn44.10:2.3": "'Này Ānanda, nếu Ta khi được hỏi 'Có tự ngã không?' mà trả lời 'Có tự ngã', thì điều đó sẽ phù hợp với những sa-môn, bà-la-môn thuộc phái thường kiến. '",
  "sn44.10:2.4": "Này Ānanda, nếu Ta khi được hỏi 'Không có tự ngã không?' mà trả lời 'Không có tự ngã', thì điều đó sẽ phù hợp với những sa-môn, bà-la-môn thuộc phái đoạn kiến. ",
  "sn44.10:2.5": "Này Ānanda, nếu Ta khi được hỏi 'Có tự ngã không?' mà trả lời 'Có tự ngã', thì điều đó có phù hợp với sự phát sinh trí tuệ: ",
  "sn44.10:2.6": "'Tất cả các pháp là vô ngã' không?' '",
  "sn44.10:2.7": "'Thưa không, bạch Thế Tôn.' ",
  "sn44.10:2.8": "'Này Ānanda, nếu Ta khi được hỏi 'Không có tự ngã không?' mà trả lời 'Không có tự ngã', thì du sĩ ngoại đạo Vacchagotta vốn đã mê lầm sẽ càng thêm mê lầm hơn: '",
  "sn44.10:2.9": "'Trước đây ta đã có tự ngã, giờ thì không còn nữa.'' '",
  "sn44.10:2.10": "Thứ mười. ",
  "sn44.11:0.1": "Tương Ưng Bộ 44.11 ",
  "sn44.11:0.2": "1. Phẩm Vô Ký ",
  "sn44.11:0.3": "Kinh Sabhiya Kaccāna ",
  "sn44.11:1.1": "Một thời Tôn giả Sabhiya Kaccāna đang trú tại Ñātika, nhà nghỉ bằng gạch. ",
  "sn44.11:1.2": "Khi ấy, du sĩ ngoại đạo Vacchagotta đến chỗ Tôn giả Sabhiya Kaccāna; khi đến rồi, chào hỏi Tôn giả Sabhiya Kaccāna. ",
  "sn44.11:1.3": "Sau khi chào hỏi thân thiện rồi, ngồi xuống một bên. Ngồi xuống một bên, du sĩ ngoại đạo Vacchagotta nói với Tôn giả Sabhiya Kaccāna rằng: ",
  "sn44.11:1.4": "'Thưa Tôn giả Kaccāna, sau khi chết Như Lai có tồn tại không?' ",
  "sn44.11:1.5": "'Thưa Vaccha, điều này không được Thế Tôn tuyên bố: '",
  "sn44.11:1.6": "'Sau khi chết Như Lai có tồn tại.'' '",
  "sn44.11:1.7": "'Vậy thưa Tôn giả Kaccāna, sau khi chết Như Lai không tồn tại không?' ",
  "sn44.11:1.8": "'Thưa Vaccha, điều này cũng không được Thế Tôn tuyên bố: '",
  "sn44.11:1.9": "'Sau khi chết Như Lai không tồn tại.'' '",
  "sn44.11:2.1": "'Thưa Tôn giả Kaccāna, sau khi chết Như Lai vừa tồn tại vừa không tồn tại không?' ",
  "sn44.11:2.2": "'Thưa Vaccha, điều này không được Thế Tôn tuyên bố: '",
  "sn44.11:2.3": "'Sau khi chết Như Lai vừa tồn tại vừa không tồn tại.'' '",
  "sn44.11:2.4": "'Vậy thưa Tôn giả Kaccāna, sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại không?' ",
  "sn44.11:2.5": "'Thưa Vaccha, điều này cũng không được Thế Tôn tuyên bố: '",
  "sn44.11:2.6": "'Sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.'' '",
  "sn44.11:3.1": "'Khi được hỏi 'Thưa Tôn giả Kaccāna, sau khi chết Như Lai có tồn tại không?', Tôn giả nói: '",
  "sn44.11:3.2": "'Thưa Vaccha, điều này không được Thế Tôn tuyên bố '",
  "sn44.11:3.3": "sau khi chết Như Lai có tồn tại.' ",
  "sn44.11:3.4": "Khi được hỏi 'Vậy thưa Tôn giả Kaccāna, sau khi chết Như Lai không tồn tại không?', Tôn giả nói: ",
  "sn44.11:3.5": "'Thưa Vaccha, điều này không được Thế Tôn tuyên bố '",
  "sn44.11:3.6": "sau khi chết Như Lai không tồn tại.' ",
  "sn44.11:3.7": "Khi được hỏi 'Thưa Tôn giả Kaccāna, sau khi chết Như Lai vừa tồn tại vừa không tồn tại không?', Tôn giả nói: ",
  "sn44.11:3.8": "'Thưa Vaccha, điều này không được Thế Tôn tuyên bố '",
  "sn44.11:3.9": "sau khi chết Như Lai vừa tồn tại vừa không tồn tại.' ",
  "sn44.11:3.10": "Khi được hỏi 'Vậy thưa Tôn giả Kaccāna, sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại không?', Tôn giả nói: ",
  "sn44.11:3.11": "'Thưa Vaccha, điều này cũng không được Thế Tôn tuyên bố '",
  "sn44.11:3.12": "sau khi chết Như Lai không phải tồn tại cũng không phải không tồn tại.' ",
  "sn44.11:3.13": "Vậy thưa Tôn giả Kaccāna, nguyên nhân gì, duyên gì mà sa-môn Gotama không tuyên bố điều này?' ",
  "sn44.11:3.14": "'Thưa Vaccha, nguyên nhân và duyên nào dẫn đến việc mô tả là 'có sắc' hay 'không có sắc', 'có tưởng' hay 'không có tưởng', 'không có tưởng cũng không phải không có tưởng', nếu những nguyên nhân và duyên đó hoàn toàn bị đoạn diệt không còn sót lại, thì còn dùng gì để mô tả là 'có sắc' hay 'không có sắc', 'có tưởng' hay 'không có tưởng', 'không có tưởng cũng không phải không có tưởng'?' ",
  "sn44.11:3.15": "",
  "sn44.11:3.16": "'Thưa Tôn giả Kaccāna, Tôn giả xuất gia được bao lâu rồi?' ",
  "sn44.11:3.17": "'Thưa Hiền giả, không lâu, được ba năm.' ",
  "sn44.11:3.18": "'Nếu ai đã chứng ngộ được đến mức này trong thời gian ngắn như vậy, thì còn nói gì thêm nữa về người đã tu tập lâu dài hơn.' ",
  "sn44.11:3.19": "Thứ mười một. ",
  "sn44.11:3.20": "Phẩm Vô Ký thứ nhất. ",
  "sn44.11:4.0": "Tóm tắt phẩm ",
  "sn44.11:4.1": "Tỳ Kheo Ni trưởng lão Khemā, Anurādha, ",
  "sn44.11:4.2": "Sāriputta và Koṭṭhika; ",
  "sn44.11:4.3": "Moggallāna và Vaccha, ",
  "sn44.11:4.4": "hội trường bàn luận và Ānanda; ",
  "sn44.11:4.5": "Sabhiya là bài thứ mười một. ",
  "sn44.11:4.6": "Tương Ưng Vô Ký hoàn tất. ",
  "sn44.11:5.0": "Tóm tắt ",
  "sn44.11:5.1": "Sáu xứ, thọ, ",
  "sn44.11:5.2": "nữ nhân, Jambukhādaka; ",
  "sn44.11:5.3": "Sāmaṇḍaka, Moggallāna, ",
  "sn44.11:5.4": "Citta, trưởng giả, hữu vi; ",
  "sn44.11:5.5": "vô ký là mười phần. ",
  "sn44.11:5.6": "Phẩm Sáu Xứ thứ tư. ",
  "sn44.11:5.7": "Tương Ưng Bộ Phẩm Sáu Xứ hoàn tất. "
}
window.BILARA["sn44_v1"]["vi"]["sn44_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
