window.BILARA = window.BILARA || {};
window.BILARA["sn4_v1"] = window.BILARA["sn4_v1"] || {};
window.BILARA["sn4_v1"]["vi"] = {
  "sn4.1:0.1": "Tương Ưng Bộ 4.1 ",
  "sn4.1:0.2": "1. Phẩm Thứ Nhất ",
  "sn4.1:0.3": "Kinh Khổ Hạnh ",
  "sn4.1:1.1": "Tôi nghe như vầy",
  "sn4.1:1.2": "Một thời, Thế Tôn trú tại Uruvelā, trên bờ sông Nerañjarā, dưới gốc cây Nigrodha của người chăn dê, khi vừa mới thành đạo Chánh Đẳng Giác. ",
  "sn4.1:1.3": "Khi ấy, Thế Tôn đang độc cư thiền tịnh, tư duy này khởi lên trong tâm: ",
  "sn4.1:1.4": "'Ta đã thoát khỏi sự khổ hạnh ấy. '",
  "sn4.1:1.5": "Thật lành thay, ta đã thoát khỏi sự khổ hạnh vô ích ấy. ",
  "sn4.1:1.6": "Thật lành thay, ta đã thoát và chứng đắc Bồ Đề.' ",
  "sn4.1:2.1": "Rồi Ma Vương Pāpimā, biết được tư duy trong tâm Thế Tôn, đi đến Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn4.1:3.1": "'Bỏ lại khổ hạnh sau lưng, '",
  "sn4.1:3.2": "Con đường thanh tịnh của người đời; ",
  "sn4.1:3.3": "Bất tịnh mà tự cho là tịnh, ",
  "sn4.1:3.4": "Đã lạc mất con đường thanh tịnh.' ",
  "sn4.1:4.1": "Rồi Thế Tôn biết rằng 'Đây là Ma Vương Pāpimā', liền đáp lại Ma Vương bằng những bài kệ: ",
  "sn4.1:5.1": "'Biết rằng mọi khổ hạnh, '",
  "sn4.1:5.2": "Dù trường tồn, đều vô ích; ",
  "sn4.1:5.3": "Tất cả đều không đem lại gì, ",
  "sn4.1:5.4": "Như mái chèo giữa đất bằng. ",
  "sn4.1:6.1": "Giới, định, và tuệ, ",
  "sn4.1:6.2": "Tu tập con đường dẫn đến Bồ Đề; ",
  "sn4.1:6.3": "Ta đã đạt thanh tịnh tối thượng, ",
  "sn4.1:6.4": "Ngươi đã bị đánh bại, hỡi Tử Thần.' ",
  "sn4.1:7.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Thế Tôn đã biết ta, Thiện Thệ đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.2:0.1": "Tương Ưng Bộ 4.2 ",
  "sn4.2:0.2": "1. Phẩm Thứ Nhất ",
  "sn4.2:0.3": "Kinh Hình Tượng Voi Chúa ",
  "sn4.2:1.1": "Tôi nghe như vầy",
  "sn4.2:1.2": "Một thời, Thế Tôn trú tại Uruvelā, trên bờ sông Nerañjarā, dưới gốc cây Nigrodha của người chăn dê, khi vừa mới thành đạo Chánh Đẳng Giác. ",
  "sn4.2:1.3": "Lúc bấy giờ, Thế Tôn đang ngồi ngoài trời trong đêm tối đen kịt, và trời đang mưa từng hạt một. ",
  "sn4.2:1.4": "Rồi Ma Vương Pāpimā, muốn khơi dậy sự sợ hãi, kinh hoàng, dựng lông trong Thế Tôn, hóa thành hình tượng một con voi chúa khổng lồ, đi đến Thế Tôn. ",
  "sn4.2:1.5": "Cái đầu của nó như viên ngọc lớn màu đen; ",
  "sn4.2:1.6": "như vậy là cái đầu của nó. ",
  "sn4.2:1.7": "Răng của nó như bạc trắng tinh; ",
  "sn4.2:1.8": "như vậy là những chiếc răng của nó. ",
  "sn4.2:1.9": "Vòi của nó như cái ách lớn; ",
  "sn4.2:1.10": "như vậy là cái vòi của nó. ",
  "sn4.2:1.11": "Rồi Thế Tôn biết rằng 'Đây là Ma Vương Pāpimā', liền đáp lại Ma Vương bằng bài kệ: ",
  "sn4.2:2.1": "'Lang thang khắp cõi luân hồi lâu dài, '",
  "sn4.2:2.2": "Mang đủ hình sắc đẹp xấu; ",
  "sn4.2:2.3": "Thế là đủ rồi với ngươi, hỡi ác ma, ",
  "sn4.2:2.4": "Ngươi đã bị đánh bại, hỡi Tử Thần.' ",
  "sn4.2:3.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Thế Tôn đã biết ta, Thiện Thệ đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.3:0.1": "Tương Ưng Bộ 4.3 ",
  "sn4.3:0.2": "1. Phẩm Thứ Nhất ",
  "sn4.3:0.3": "Kinh Hào Quang ",
  "sn4.3:1.1": "Tôi nghe như vầy",
  "sn4.3:1.2": "Một thời, Thế Tôn trú tại Uruvelā, trên bờ sông Nerañjarā, dưới gốc cây Nigrodha của người chăn dê, khi vừa mới thành đạo Chánh Đẳng Giác. ",
  "sn4.3:1.3": "Lúc bấy giờ, Thế Tôn đang ngồi ngoài trời trong đêm tối đen kịt, và trời đang mưa từng hạt một. ",
  "sn4.3:1.4": "Rồi Ma Vương Pāpimā, muốn khơi dậy sự sợ hãi, kinh hoàng, dựng lông trong Thế Tôn, đi đến gần Thế Tôn; sau khi đến, phát ra các sắc hào quang cao thấp, đẹp lẫn xấu, ngay trước mặt Thế Tôn. ",
  "sn4.3:1.5": "Rồi Thế Tôn biết rằng 'Đây là Ma Vương Pāpimā', liền đáp lại Ma Vương bằng những bài kệ: ",
  "sn4.3:2.1": "'Lang thang khắp cõi luân hồi lâu dài, '",
  "sn4.3:2.2": "Mang đủ hình sắc đẹp xấu; ",
  "sn4.3:2.3": "Thế là đủ rồi với ngươi, hỡi ác ma, ",
  "sn4.3:2.4": "Ngươi đã bị đánh bại, hỡi Tử Thần. ",
  "sn4.3:3.1": "Ai khéo thu thúc thân, lời, ",
  "sn4.3:3.2": "Và cả tâm ý; ",
  "sn4.3:3.3": "Những ai ấy không thuộc quyền Ma, ",
  "sn4.3:3.4": "Không bị Ma trói buộc.' ",
  "sn4.3:4.1": "Rồi Ma Vương... biến mất ngay tại đó. ",
  "sn4.4:0.1": "Tương Ưng Bộ 4.4 ",
  "sn4.4:0.2": "1. Phẩm Thứ Nhất ",
  "sn4.4:0.3": "Kinh Bẫy Của Ma - Bài Thứ Nhất ",
  "sn4.4:1.1": "Tôi nghe như vầy",
  "sn4.4:1.2": "Một thời, Thế Tôn trú tại Bārāṇasī, ở vườn Lộc Uyển, chỗ dành cho các ẩn sĩ. ",
  "sn4.4:1.3": "Ở đó, Thế Tôn gọi các Tỳ Kheo: ",
  "sn4.4:1.4": "'Này các Tỳ Kheo.' ",
  "sn4.4:1.5": "'Bạch Thế Tôn', các Tỳ Kheo ấy đáp lại Thế Tôn. ",
  "sn4.4:1.6": "Thế Tôn nói như vầy: ",
  "sn4.4:2.1": "'Này các Tỳ Kheo, với sự tác ý đúng đắn, với sự tinh tấn đúng đắn, Ta đã chứng đắc giải thoát vô thượng, đã làm chứng giải thoát vô thượng. '",
  "sn4.4:2.2": "Này các Tỳ Kheo, các ông cũng hãy với sự tác ý đúng đắn, với sự tinh tấn đúng đắn, chứng đắc giải thoát vô thượng, làm chứng giải thoát vô thượng.' ",
  "sn4.4:2.3": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn4.4:3.1": "'Ngươi bị trói bởi bẫy của Ma, '",
  "sn4.4:3.2": "Dù là bẫy cõi trời hay cõi người; ",
  "sn4.4:3.3": "Ngươi bị trói bởi xiềng của Ma, ",
  "sn4.4:3.4": "Hỡi sa-môn, ngươi không thể thoát khỏi ta.' ",
  "sn4.4:4.1": "'Ta đã thoát khỏi bẫy của Ma, '",
  "sn4.4:4.2": "Dù là bẫy cõi trời hay cõi người; ",
  "sn4.4:4.3": "Ta đã thoát khỏi xiềng của Ma, ",
  "sn4.4:4.4": "Ngươi đã bị đánh bại, hỡi Tử Thần.' ",
  "sn4.4:5.1": "Rồi Ma Vương Pāpimā... biến mất ngay tại đó. ",
  "sn4.5:0.1": "Tương Ưng Bộ 4.5 ",
  "sn4.5:0.2": "1. Phẩm Thứ Nhất ",
  "sn4.5:0.3": "Kinh Bẫy Của Ma - Bài Thứ Hai ",
  "sn4.5:1.1": "Một thời, Thế Tôn trú tại Bārāṇasī, ở vườn Lộc Uyển, chỗ dành cho các ẩn sĩ. ",
  "sn4.5:1.2": "Ở đó, Thế Tôn gọi các Tỳ Kheo: ",
  "sn4.5:1.3": "'Này các Tỳ Kheo.' ",
  "sn4.5:1.4": "'Bạch Thế Tôn', các Tỳ Kheo ấy đáp lại Thế Tôn. ",
  "sn4.5:1.5": "Thế Tôn nói như vầy: ",
  "sn4.5:2.1": "'Này các Tỳ Kheo, Ta đã thoát khỏi tất cả mọi bẫy, dù là bẫy cõi trời hay cõi người. '",
  "sn4.5:2.2": "Này các Tỳ Kheo, các ông cũng đã thoát khỏi tất cả mọi bẫy, dù là bẫy cõi trời hay cõi người. ",
  "sn4.5:2.3": "Này các Tỳ Kheo, hãy du hành vì lợi ích của nhiều người, vì hạnh phúc của nhiều người, vì lòng thương tưởng đến thế gian, vì lợi ích, vì hạnh phúc của chư thiên và loài người. ",
  "sn4.5:2.4": "Đừng đi hai người trên cùng một con đường. ",
  "sn4.5:2.5": "Này các Tỳ Kheo, hãy thuyết Pháp, tốt đẹp ở đoạn đầu, tốt đẹp ở đoạn giữa, tốt đẹp ở đoạn cuối, đầy đủ ý nghĩa và văn cú, hoàn toàn viên mãn, thanh tịnh; hãy tuyên thuyết đời sống phạm hạnh. ",
  "sn4.5:2.6": "Có những chúng sinh ít bụi trong mắt sẽ bị tổn hại nếu không được nghe Pháp. ",
  "sn4.5:2.7": "Sẽ có những người hiểu được Pháp. ",
  "sn4.5:2.8": "Này các Tỳ Kheo, Ta cũng sẽ đi đến Uruvelā Senānigama để thuyết Pháp.' ",
  "sn4.5:2.9": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn4.5:3.1": "'Ngươi bị trói bởi tất cả mọi bẫy, '",
  "sn4.5:3.2": "Dù là bẫy cõi trời hay cõi người; ",
  "sn4.5:3.3": "Ngươi bị trói bởi xiềng lớn, ",
  "sn4.5:3.4": "Hỡi sa-môn, ngươi không thể thoát khỏi ta.' ",
  "sn4.5:4.1": "'Ta đã thoát khỏi tất cả mọi bẫy, '",
  "sn4.5:4.2": "Dù là bẫy cõi trời hay cõi người; ",
  "sn4.5:4.3": "Ta đã thoát khỏi xiềng lớn, ",
  "sn4.5:4.4": "Ngươi đã bị đánh bại, hỡi Tử Thần.' ",
  "sn4.5:5.1": "Rồi Ma Vương Pāpimā... biến mất ngay tại đó. ",
  "sn4.6:0.1": "Tương Ưng Bộ 4.6 ",
  "sn4.6:0.2": "1. Phẩm Thứ Nhất ",
  "sn4.6:0.3": "Kinh Con Rắn ",
  "sn4.6:1.1": "Tôi nghe như vầy",
  "sn4.6:1.2": "Một thời, Thế Tôn trú tại Rājagaha, ở rừng Trúc Lâm, chỗ nuôi dưỡng sóc. ",
  "sn4.6:1.3": "Lúc bấy giờ, Thế Tôn đang ngồi ngoài trời trong đêm tối đen kịt, và trời đang mưa từng hạt một. ",
  "sn4.6:2.1": "Rồi Ma Vương Pāpimā, muốn khơi dậy sự sợ hãi, kinh hoàng, dựng lông trong Thế Tôn, hóa thành hình tượng một con rắn chúa khổng lồ, đi đến Thế Tôn. ",
  "sn4.6:2.2": "Thân con rắn ấy to như một chiếc thuyền lớn đóng bằng một cây; ",
  "sn4.6:2.3": "như vậy là thân của nó. ",
  "sn4.6:2.4": "Mang của nó như tấm chiếu lớn bằng lát; ",
  "sn4.6:2.5": "như vậy là cái mang của nó. ",
  "sn4.6:2.6": "Mắt của nó như chén đồng lớn xứ Kosala; ",
  "sn4.6:2.7": "như vậy là những cặp mắt của nó. ",
  "sn4.6:2.8": "Lưỡi của nó thè ra như tia chớp trong cơn bão; ",
  "sn4.6:2.9": "như vậy là cái lưỡi thè ra từ miệng của nó. ",
  "sn4.6:2.10": "Tiếng thở của nó như tiếng ống bễ thợ rèn đang thổi; ",
  "sn4.6:2.11": "như vậy là tiếng thở ra hít vào của nó. ",
  "sn4.6:3.1": "Rồi Thế Tôn biết rằng 'Đây là Ma Vương Pāpimā', liền đáp lại Ma Vương bằng những bài kệ: ",
  "sn4.6:4.1": "'Ai thường lui tới chỗ trống vắng, '",
  "sn4.6:4.2": "Vị ẩn sĩ ấy tự điều phục, an nhiên tịnh tọa; ",
  "sn4.6:4.3": "Hãy xả bỏ mà trú tại đó, ",
  "sn4.6:4.4": "Vì vậy thích hợp với người như thế. ",
  "sn4.6:5.1": "Dù nhiều loài bò sát, nhiều điều đáng sợ, ",
  "sn4.6:5.2": "Hay nhiều loài côn trùng và rắn độc; ",
  "sn4.6:5.3": "Bậc đại ẩn sĩ vào nơi trống vắng, ",
  "sn4.6:5.4": "Không hề run rẩy dù một sợi lông. ",
  "sn4.6:6.1": "Dù bầu trời có vỡ, đất đai rung chuyển, ",
  "sn4.6:6.2": "Dù tất cả chúng sinh kinh hãi; ",
  "sn4.6:6.3": "Dù mũi tên có cắm vào ngực, ",
  "sn4.6:6.4": "Các vị Phật không nương tựa vào hữu.' ",
  "sn4.6:7.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Thế Tôn đã biết ta, Thiện Thệ đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.7:0.1": "Tương Ưng Bộ 4.7 ",
  "sn4.7:0.2": "1. Phẩm Thứ Nhất ",
  "sn4.7:0.3": "Kinh Ngủ Ngon ",
  "sn4.7:1.1": "Một thời, Thế Tôn trú tại Rājagaha, ở rừng Trúc Lâm, chỗ nuôi dưỡng sóc. ",
  "sn4.7:1.2": "Rồi Thế Tôn, sau khi kinh hành suốt phần lớn đêm ngoài trời, vào lúc gần sáng, rửa chân rồi bước vào tịnh thất, ",
  "sn4.7:1.3": "nằm nghiêng bên phải theo tư thế nằm của sư tử, đặt chân này lên chân kia, chánh niệm tỉnh giác, tác ý đến việc thức dậy. ",
  "sn4.7:1.4": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn4.7:2.1": "'Sao ngươi ngủ, sao ngươi ngủ, '",
  "sn4.7:2.2": "Ngươi ngủ như kẻ khờ dại; ",
  "sn4.7:2.3": "Ngươi ngủ trong ngôi nhà trống vắng, ",
  "sn4.7:2.4": "Sao ngươi ngủ khi mặt trời đã mọc?' ",
  "sn4.7:3.1": "'Người không còn ái dục dẫn dắt, '",
  "sn4.7:3.2": "Như lưới giăng mắc khắp nơi; ",
  "sn4.7:3.3": "Bậc Giác Ngộ, diệt trừ mọi hữu, ",
  "sn4.7:3.4": "Ngủ, thì có can hệ gì với ngươi, hỡi Ma?' ",
  "sn4.7:4.1": "Rồi Ma Vương Pāpimā... biến mất ngay tại đó. ",
  "sn4.8:0.1": "Tương Ưng Bộ 4.8 ",
  "sn4.8:0.2": "1. Phẩm Thứ Nhất ",
  "sn4.8:0.3": "Kinh Vui Mừng ",
  "sn4.8:1.1": "Tôi nghe như vầy",
  "sn4.8:1.2": "Một thời, Thế Tôn trú tại Sāvatthī, ở rừng Jeta, vườn của ông Anāthapiṇḍika. ",
  "sn4.8:1.3": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, đọc bài kệ này trước Thế Tôn: ",
  "sn4.8:2.1": "'Ai có con thì vui mừng vì có con, '",
  "sn4.8:2.2": "Ai có bò thì cũng vui mừng vì có bò; ",
  "sn4.8:2.3": "Niềm vui của người gắn liền với hữu, ",
  "sn4.8:2.4": "Ai không hữu thì không có niềm vui.' ",
  "sn4.8:3.1": "'Ai có con thì lo lắng vì có con, '",
  "sn4.8:3.2": "Ai có bò thì cũng lo lắng vì có bò; ",
  "sn4.8:3.3": "Nỗi lo của người gắn liền với hữu, ",
  "sn4.8:3.4": "Ai không hữu thì không có nỗi lo.' ",
  "sn4.8:4.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Thế Tôn đã biết ta, Thiện Thệ đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.9:0.1": "Tương Ưng Bộ 4.9 ",
  "sn4.9:0.2": "1. Phẩm Thứ Nhất ",
  "sn4.9:0.3": "Kinh Tuổi Thọ - Bài Thứ Nhất ",
  "sn4.9:1.1": "Tôi nghe như vầy",
  "sn4.9:1.2": "Một thời, Thế Tôn trú tại Rājagaha, ở rừng Trúc Lâm, chỗ nuôi dưỡng sóc. ",
  "sn4.9:1.3": "Ở đó, Thế Tôn gọi các Tỳ Kheo: ",
  "sn4.9:1.4": "'Này các Tỳ Kheo.' ",
  "sn4.9:1.5": "'Bạch Thế Tôn', các Tỳ Kheo ấy đáp lại Thế Tôn. ",
  "sn4.9:1.6": "Thế Tôn nói như vầy: ",
  "sn4.9:2.1": "'Này các Tỳ Kheo, tuổi thọ của con người thật ngắn ngủi. '",
  "sn4.9:2.2": "Đời sau thì phải đến, cần phải làm điều thiện, cần phải sống đời phạm hạnh. ",
  "sn4.9:2.3": "Không có sự bất tử đối với kẻ đã sinh. ",
  "sn4.9:2.4": "Này các Tỳ Kheo, người sống lâu chỉ sống được một trăm năm, hoặc ít hơn hoặc nhiều hơn một chút.' ",
  "sn4.9:3.1": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn4.9:4.1": "'Tuổi thọ của loài người thật dài, '",
  "sn4.9:4.2": "Bậc thiện nhân không nên khinh thường; ",
  "sn4.9:4.3": "Hãy sống như em bú sữa, ",
  "sn4.9:4.4": "Thần chết chưa đến đâu.' ",
  "sn4.9:5.1": "'Tuổi thọ của loài người thật ngắn, '",
  "sn4.9:5.2": "Bậc thiện nhân không nên xem thường; ",
  "sn4.9:5.3": "Hãy sống như đầu đang bốc lửa, ",
  "sn4.9:5.4": "Thần chết nhất định sẽ đến.' ",
  "sn4.9:6.1": "Rồi Ma Vương... biến mất ngay tại đó. ",
  "sn4.10:0.1": "Tương Ưng Bộ 4.10 ",
  "sn4.10:0.2": "1. Phẩm Thứ Nhất ",
  "sn4.10:0.3": "Kinh Tuổi Thọ - Bài Thứ Hai ",
  "sn4.10:1.1": "Tôi nghe như vầy",
  "sn4.10:1.2": "Một thời, Thế Tôn trú tại Rājagaha, ở rừng Trúc Lâm, chỗ nuôi dưỡng sóc. ",
  "sn4.10:1.3": "Ở đó, Thế Tôn... nói như vầy: ",
  "sn4.10:2.1": "'Này các Tỳ Kheo, tuổi thọ của con người thật ngắn ngủi. '",
  "sn4.10:2.2": "Đời sau thì phải đến, cần phải làm điều thiện, cần phải sống đời phạm hạnh. ",
  "sn4.10:2.3": "Không có sự bất tử đối với kẻ đã sinh. ",
  "sn4.10:2.4": "Này các Tỳ Kheo, người sống lâu chỉ sống được một trăm năm, hoặc ít hơn hoặc nhiều hơn một chút.' ",
  "sn4.10:3.1": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn4.10:4.1": "'Ngày và đêm không trôi qua, '",
  "sn4.10:4.2": "Mạng sống không bị gián đoạn; ",
  "sn4.10:4.3": "Tuổi thọ của chúng sinh trôi vòng, ",
  "sn4.10:4.4": "Như vành bánh xe quanh trục.' ",
  "sn4.10:5.1": "'Ngày và đêm cứ trôi qua, '",
  "sn4.10:5.2": "Mạng sống bị gián đoạn dần; ",
  "sn4.10:5.3": "Tuổi thọ của chúng sinh cạn dần, ",
  "sn4.10:5.4": "Như nước suối nhỏ cạn kiệt.' ",
  "sn4.10:6.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Thế Tôn đã biết ta, Thiện Thệ đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.10:6.2": "Phẩm thứ nhất. ",
  "sn4.10:7.0": "Tóm lược phẩm này: ",
  "sn4.10:7.1": "Khổ hạnh và con rắn, ",
  "sn4.10:7.2": "Hào quang và bẫy hai kinh; ",
  "sn4.10:7.3": "Rắn, ngủ, vui mừng, ",
  "sn4.10:7.4": "Hai kinh về tuổi thọ. ",
  "sn4.11:0.1": "Tương Ưng Bộ 4.11 ",
  "sn4.11:0.2": "2. Phẩm Thứ Hai ",
  "sn4.11:0.3": "Kinh Tảng Đá ",
  "sn4.11:1.1": "Một thời, Thế Tôn trú tại Rājagaha, trên núi Gijjhakūṭa. ",
  "sn4.11:1.2": "Lúc bấy giờ, Thế Tôn đang ngồi ngoài trời trong đêm tối đen kịt, và trời đang mưa từng hạt một. ",
  "sn4.11:1.3": "Rồi Ma Vương Pāpimā, muốn khơi dậy sự sợ hãi, kinh hoàng, dựng lông trong Thế Tôn, đi đến Thế Tôn; sau khi đến, lăn những tảng đá lớn sát bên Thế Tôn. ",
  "sn4.11:2.1": "Rồi Thế Tôn biết rằng 'Đây là Ma Vương Pāpimā', liền đáp lại Ma Vương bằng bài kệ: ",
  "sn4.11:3.1": "'Dù ngươi làm rung chuyển cả, '",
  "sn4.11:3.2": "Toàn bộ núi Gijjhakūṭa; ",
  "sn4.11:3.3": "Những bậc đã giải thoát hoàn toàn, ",
  "sn4.11:3.4": "Các vị Phật không hề bị lay động.' ",
  "sn4.11:4.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Thế Tôn đã biết ta, Thiện Thệ đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.12:0.1": "Tương Ưng Bộ 4.12 ",
  "sn4.12:0.2": "2. Phẩm Thứ Hai ",
  "sn4.12:0.3": "Kinh Sư Tử Hống ",
  "sn4.12:1.1": "Một thời, Thế Tôn trú tại Sāvatthī, ở rừng Jeta, vườn của ông Anāthapiṇḍika. ",
  "sn4.12:1.2": "Lúc bấy giờ, Thế Tôn đang thuyết Pháp cho đại chúng vây quanh. ",
  "sn4.12:2.1": "Rồi Ma Vương Pāpimā nghĩ rằng: ",
  "sn4.12:2.2": "'Sa-môn Gotama đang thuyết Pháp cho đại chúng vây quanh. '",
  "sn4.12:2.3": "Ta hãy đến chỗ sa-môn Gotama để làm cho ngài mù mắt.' ",
  "sn4.12:2.4": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn4.12:3.1": "'Sao ngươi hống như sư tử, '",
  "sn4.12:3.2": "Tự tin giữa đại chúng; ",
  "sn4.12:3.3": "Có kẻ địch thủ đối với ngươi, ",
  "sn4.12:3.4": "Ngươi tưởng mình đã chiến thắng?' ",
  "sn4.12:4.1": "'Những bậc anh hùng hống lên, '",
  "sn4.12:4.2": "Tự tin giữa đại chúng; ",
  "sn4.12:4.3": "Những vị Như Lai đã đạt sức mạnh, ",
  "sn4.12:4.4": "Đã vượt qua ái dục trên đời.' ",
  "sn4.12:5.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Thế Tôn đã biết ta, Thiện Thệ đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.13:0.1": "Tương Ưng Bộ 4.13 ",
  "sn4.13:0.2": "2. Phẩm Thứ Hai ",
  "sn4.13:0.3": "Kinh Mảnh Đá Văng ",
  "sn4.13:1.1": "Tôi nghe như vầy",
  "sn4.13:1.2": "Một thời, Thế Tôn trú tại Rājagaha, trong vườn Nai ở Maddakucchi. ",
  "sn4.13:1.3": "Lúc bấy giờ, bàn chân Thế Tôn bị thương do một mảnh đá văng vào, ",
  "sn4.13:1.4": "Thế Tôn phải chịu những cảm thọ thân xác rất mãnh liệt, đau đớn, nhói buốt, sắc bén, khổ sở, khó chịu. ",
  "sn4.13:1.5": "Thế Tôn nhẫn chịu những cảm thọ ấy với chánh niệm tỉnh giác, không bị khổ não. ",
  "sn4.13:1.6": "Rồi Thế Tôn gấp y sanghāṭi làm bốn lớp, nằm nghiêng bên phải theo tư thế nằm của sư tử, đặt chân này lên chân kia, chánh niệm tỉnh giác. ",
  "sn4.13:1.7": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn4.13:2.1": "'Ngươi ngủ vì lười biếng hay say thơ ca, '",
  "sn4.13:2.2": "Phải chăng ngươi không có mục tiêu gì; ",
  "sn4.13:2.3": "Một mình trong phòng trú ẩn vắng vẻ, ",
  "sn4.13:2.4": "Sao ngươi ngủ gà ngủ gật như thế?' ",
  "sn4.13:3.1": "'Ta không ngủ vì lười biếng hay say thơ ca, '",
  "sn4.13:3.2": "Ta đã đạt mục tiêu, không còn lo âu; ",
  "sn4.13:3.3": "Một mình trong phòng trú ẩn vắng vẻ, ",
  "sn4.13:3.4": "Ta nằm với lòng thương tưởng tất cả chúng sinh. ",
  "sn4.13:4.1": "Những ai bị mũi tên cắm vào ngực, ",
  "sn4.13:4.2": "Liên tục đâm vào tim; ",
  "sn4.13:4.3": "Những kẻ ấy có mũi tên vẫn còn ngủ được, ",
  "sn4.13:4.4": "Còn Ta đã nhổ mũi tên ra, Ta không ngủ. ",
  "sn4.13:5.1": "Ta không sợ khi thức, cũng không sợ khi ngủ, ",
  "sn4.13:5.2": "Ngày đêm không đốt cháy Ta; ",
  "sn4.13:5.3": "Ta không thấy mất mát gì trên đời, ",
  "sn4.13:5.4": "Vì vậy Ta nằm với lòng thương tưởng tất cả chúng sinh.' ",
  "sn4.13:6.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Thế Tôn đã biết ta, Thiện Thệ đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.14:0.1": "Tương Ưng Bộ 4.14 ",
  "sn4.14:0.2": "2. Phẩm Thứ Hai ",
  "sn4.14:0.3": "Kinh Thích Hợp ",
  "sn4.14:1.1": "Một thời, Thế Tôn trú tại xứ Kosala, ở làng bà-la-môn Ekasālā. ",
  "sn4.14:1.2": "Lúc bấy giờ, Thế Tôn đang thuyết Pháp cho đại chúng cư sĩ vây quanh. ",
  "sn4.14:2.1": "Rồi Ma Vương Pāpimā nghĩ rằng: ",
  "sn4.14:2.2": "'Sa-môn Gotama đang thuyết Pháp cho đại chúng cư sĩ vây quanh. '",
  "sn4.14:2.3": "Ta hãy đến chỗ sa-môn Gotama để làm cho ngài mù mắt.' ",
  "sn4.14:2.4": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn4.14:3.1": "'Đây không phải điều thích hợp với ngươi, '",
  "sn4.14:3.2": "Khi ngươi dạy bảo người khác; ",
  "sn4.14:3.3": "Giữa việc thuận và nghịch, ",
  "sn4.14:3.4": "Chớ dính vào điều đó.' ",
  "sn4.14:4.1": "'Bậc Chánh Đẳng Giác thuyết Pháp vì lợi ích, '",
  "sn4.14:4.2": "Khi dạy bảo người khác; ",
  "sn4.14:4.3": "Thoát khỏi thuận và nghịch, ",
  "sn4.14:4.4": "Như Lai hoàn toàn giải thoát.' ",
  "sn4.14:5.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Thế Tôn đã biết ta, Thiện Thệ đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.15:0.1": "Tương Ưng Bộ 4.15 ",
  "sn4.15:0.2": "2. Phẩm Thứ Hai ",
  "sn4.15:0.3": "Kinh Tâm Ý ",
  "sn4.15:1.1": "Tôi nghe như vầy",
  "sn4.15:1.2": "Một thời, Thế Tôn trú tại Sāvatthī, ở rừng Jeta, vườn của ông Anāthapiṇḍika. ",
  "sn4.15:1.3": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn4.15:2.1": "'Bẫy giăng khắp hư không, '",
  "sn4.15:2.2": "Theo đó mà tâm ý bay lượn; ",
  "sn4.15:2.3": "Ta sẽ trói buộc ngươi bằng đó, ",
  "sn4.15:2.4": "Hỡi sa-môn, ngươi không thể thoát khỏi ta.' ",
  "sn4.15:3.1": "'Sắc, thanh, vị, hương, '",
  "sn4.15:3.2": "Xúc và pháp làm vui tâm; ",
  "sn4.15:3.3": "Ta đã không còn ước muốn những điều đó, ",
  "sn4.15:3.4": "Ngươi đã bị đánh bại, hỡi Tử Thần.' ",
  "sn4.15:4.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Thế Tôn đã biết ta, Thiện Thệ đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.16:0.1": "Tương Ưng Bộ 4.16 ",
  "sn4.16:0.2": "2. Phẩm Thứ Hai ",
  "sn4.16:0.3": "Kinh Bình Bát ",
  "sn4.16:1.1": "Tại Sāvatthī. ",
  "sn4.16:1.2": "Lúc bấy giờ, Thế Tôn đang lấy năm thủ uẩn làm đề tài, dạy Pháp cho các Tỳ Kheo, khai thị, khuyến khích, làm phấn khởi, làm hoan hỷ. ",
  "sn4.16:1.3": "Và các Tỳ Kheo ấy chú tâm, để tâm, lắng nghe Pháp với toàn tâm ý, lắng tai nghe Pháp. ",
  "sn4.16:2.1": "Rồi Ma Vương Pāpimā nghĩ rằng: ",
  "sn4.16:2.2": "'Sa-môn Gotama đang lấy năm thủ uẩn làm đề tài, dạy Pháp cho các Tỳ Kheo, khai thị, khuyến khích, làm phấn khởi, làm hoan hỷ. '",
  "sn4.16:2.3": "Và các Tỳ Kheo ấy chú tâm, để tâm, lắng nghe Pháp với toàn tâm ý, lắng tai nghe Pháp. ",
  "sn4.16:2.4": "Ta hãy đến chỗ sa-môn Gotama để làm cho ngài mù mắt.' ",
  "sn4.16:3.1": "Lúc bấy giờ, nhiều bình bát đang được để ngoài trời. ",
  "sn4.16:3.2": "Rồi Ma Vương Pāpimā hóa thành hình con bò, đi đến chỗ để các bình bát đó. ",
  "sn4.16:3.3": "Rồi một Tỳ Kheo nói với Tỳ Kheo khác: ",
  "sn4.16:3.4": "'Này Tỳ Kheo, này Tỳ Kheo, con bò đó có thể phá vỡ các bình bát.' ",
  "sn4.16:3.5": "Khi được nói vậy, Thế Tôn nói với Tỳ Kheo ấy: ",
  "sn4.16:3.6": "'Đó không phải con bò, này Tỳ Kheo. '",
  "sn4.16:3.7": "Đó là Ma Vương Pāpimā, đến để làm mù mắt các ông.' ",
  "sn4.16:3.8": "Rồi Thế Tôn biết rằng 'Đây là Ma Vương Pāpimā', liền đáp lại Ma Vương bằng bài kệ: ",
  "sn4.16:4.1": "'Sắc, thọ, tưởng, '",
  "sn4.16:4.2": "Thức và hành uẩn; ",
  "sn4.16:4.3": "Đó không phải là ta, không phải của ta, ",
  "sn4.16:4.4": "Hiểu vậy rồi, ta lìa tham đối với chúng. ",
  "sn4.16:5.1": "Ai ly tham như vậy, sống an ổn, ",
  "sn4.16:5.2": "Vượt qua tất cả mọi kiết sử; ",
  "sn4.16:5.3": "Tìm kiếm khắp nơi, ",
  "sn4.16:5.4": "Ngay quân Ma cũng không tìm được ta.' ",
  "sn4.16:6.1": "Rồi Ma Vương Pāpimā... biến mất ngay tại đó. ",
  "sn4.17:0.1": "Tương Ưng Bộ 4.17 ",
  "sn4.17:0.2": "2. Phẩm Thứ Hai ",
  "sn4.17:0.3": "Kinh Sáu Xúc Xứ ",
  "sn4.17:1.1": "Một thời, Thế Tôn trú tại Vesālī, ở Đại Lâm, trong giảng đường có mái nhọn. ",
  "sn4.17:1.2": "Lúc bấy giờ, Thế Tôn đang lấy sáu xúc xứ làm đề tài, dạy Pháp cho các Tỳ Kheo, khai thị, khuyến khích, làm phấn khởi, làm hoan hỷ. ",
  "sn4.17:1.3": "Và các Tỳ Kheo ấy chú tâm, để tâm, lắng nghe Pháp với toàn tâm ý, lắng tai nghe Pháp. ",
  "sn4.17:2.1": "Rồi Ma Vương Pāpimā nghĩ rằng: ",
  "sn4.17:2.2": "'Sa-môn Gotama đang lấy sáu xúc xứ làm đề tài, dạy Pháp cho các Tỳ Kheo, khai thị, khuyến khích, làm phấn khởi, làm hoan hỷ. '",
  "sn4.17:2.3": "Và các Tỳ Kheo ấy chú tâm, để tâm, lắng nghe Pháp với toàn tâm ý, lắng tai nghe Pháp. ",
  "sn4.17:2.4": "Ta hãy đến chỗ sa-môn Gotama để làm cho ngài mù mắt.' ",
  "sn4.17:2.5": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, tạo ra một tiếng động dữ dội đáng sợ ngay gần Thế Tôn, đến mức như thể mặt đất đang vỡ ra. Rồi một Tỳ Kheo nói với Tỳ Kheo khác: ",
  "sn4.17:2.6": "'Này Tỳ Kheo, này Tỳ Kheo, dường như mặt đất đang vỡ ra.' ",
  "sn4.17:2.7": "Khi được nói vậy, Thế Tôn nói với Tỳ Kheo ấy: ",
  "sn4.17:2.8": "'Đất không vỡ đâu, này Tỳ Kheo. '",
  "sn4.17:2.9": "Đó là Ma Vương Pāpimā, đến để làm mù mắt các ông.' ",
  "sn4.17:2.10": "Rồi Thế Tôn biết rằng 'Đây là Ma Vương Pāpimā', liền đáp lại Ma Vương bằng bài kệ: ",
  "sn4.17:3.1": "'Sắc, thanh, vị, hương, '",
  "sn4.17:3.2": "Xúc và tất cả các pháp; ",
  "sn4.17:3.3": "Đây là mồi nhử đáng sợ của thế gian, ",
  "sn4.17:3.4": "Nơi đây thế gian bị mê đắm. ",
  "sn4.17:4.1": "Vượt qua điều đó, ",
  "sn4.17:4.2": "Đệ tử của Phật, chánh niệm; ",
  "sn4.17:4.3": "Vượt qua cõi của Ma, ",
  "sn4.17:4.4": "Sáng chói như mặt trời.' ",
  "sn4.17:5.1": "Rồi Ma Vương Pāpimā... biến mất ngay tại đó. ",
  "sn4.18:0.1": "Tương Ưng Bộ 4.18 ",
  "sn4.18:0.2": "2. Phẩm Thứ Hai ",
  "sn4.18:0.3": "Kinh Khất Thực ",
  "sn4.18:1.1": "Một thời, Thế Tôn trú tại xứ Magadha, ở làng bà-la-môn Pañcasālā. ",
  "sn4.18:1.2": "Lúc bấy giờ, ở làng bà-la-môn Pañcasālā đang có lễ hội của các thiếu nữ. ",
  "sn4.18:1.3": "Rồi Thế Tôn vào buổi sáng, đắp y, mang bát đi vào làng bà-la-môn Pañcasālā để khất thực. ",
  "sn4.18:1.4": "Lúc bấy giờ, các gia chủ bà-la-môn làng Pañcasālā bị Ma Vương Pāpimā xâm nhập tâm: ",
  "sn4.18:1.5": "'Đừng để sa-môn Gotama nhận được vật thực.' ",
  "sn4.18:2.1": "Rồi Thế Tôn đi vào làng bà-la-môn Pañcasālā để khất thực với cái bát sạch, rồi trở ra với cái bát sạch như vậy. ",
  "sn4.18:2.2": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, nói với Thế Tôn: ",
  "sn4.18:2.3": "'Này sa-môn, ngài có nhận được vật thực không?' ",
  "sn4.18:2.4": "'Phải chăng chính ngươi đã làm như vậy để ta không nhận được vật thực, hỡi ác ma?' ",
  "sn4.18:2.5": "'Vậy thì, bạch Thế Tôn, Thế Tôn hãy vào lần nữa làng bà-la-môn Pañcasālā để khất thực. '",
  "sn4.18:2.6": "Ta sẽ làm cho Thế Tôn nhận được vật thực.' ",
  "sn4.18:3.1": "'Ma Vương gieo trồng bất thiện, '",
  "sn4.18:3.2": "Khi xúc phạm đến Như Lai; ",
  "sn4.18:3.3": "Ngươi có nghĩ rằng, hỡi ác ma, ",
  "sn4.18:3.4": "Ác nghiệp của ngươi sẽ không trổ quả? ",
  "sn4.18:4.1": "Chúng ta sống rất an lạc, ",
  "sn4.18:4.2": "Những ai không có gì cả; ",
  "sn4.18:4.3": "Chúng ta sẽ sống với hỷ làm thức ăn, ",
  "sn4.18:4.4": "Như các vị trời Quang Âm.' ",
  "sn4.18:5.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Thế Tôn đã biết ta, Thiện Thệ đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.19:0.1": "Tương Ưng Bộ 4.19 ",
  "sn4.19:0.2": "2. Phẩm Thứ Hai ",
  "sn4.19:0.3": "Kinh Người Nông Dân ",
  "sn4.19:1.1": "Tại Sāvatthī. ",
  "sn4.19:1.2": "Lúc bấy giờ, Thế Tôn đang thuyết Pháp cho các Tỳ Kheo về Niết-bàn, khai thị, khuyến khích, làm phấn khởi, làm hoan hỷ. ",
  "sn4.19:1.3": "Và các Tỳ Kheo ấy chú tâm, để tâm, lắng nghe Pháp với toàn tâm ý, lắng tai nghe Pháp. ",
  "sn4.19:2.1": "Rồi Ma Vương Pāpimā nghĩ rằng: ",
  "sn4.19:2.2": "'Sa-môn Gotama đang thuyết Pháp cho các Tỳ Kheo về Niết-bàn... '",
  "sn4.19:2.3": "Ta hãy đến chỗ sa-môn Gotama để làm cho ngài mù mắt.' ",
  "sn4.19:2.4": "Rồi Ma Vương Pāpimā hóa thành hình người nông dân, vác cái cày lớn lên vai, tay cầm cây gậy dài, tóc bù xù, mặc áo vải thô, chân dính bùn, đi đến Thế Tôn; sau khi đến, nói với Thế Tôn: ",
  "sn4.19:2.5": "'Này sa-môn, ngài có thấy những con bò của tôi không?' ",
  "sn4.19:2.6": "'Những con bò đó có liên quan gì đến ta, hỡi ác ma?' ",
  "sn4.19:2.7": "'Mắt chính là của ta, hỡi sa-môn, sắc chính là của ta, xứ thức thân nhãn xúc chính là của ta. '",
  "sn4.19:2.8": "Ngài đi đâu để thoát khỏi ta? ",
  "sn4.19:2.9": "Tai chính là của ta, thanh chính là của ta... ",
  "sn4.19:2.10": "mũi chính là của ta, hương chính là của ta; ",
  "sn4.19:2.11": "lưỡi chính là của ta, vị chính là của ta; ",
  "sn4.19:2.12": "thân chính là của ta, xúc chính là của ta; ",
  "sn4.19:2.13": "ý chính là của ta, pháp chính là của ta, xứ thức thân ý xúc chính là của ta. ",
  "sn4.19:2.14": "Ngài đi đâu để thoát khỏi ta?' ",
  "sn4.19:3.1": "'Mắt chính là của ngươi, sắc chính là của ngươi, xứ thức thân nhãn xúc chính là của ngươi. '",
  "sn4.19:3.2": "Nhưng chỗ nào, hỡi ác ma, không có mắt, không có sắc, không có xứ thức thân nhãn xúc, thì ngươi không thể đến đó. ",
  "sn4.19:3.3": "Tai chính là của ngươi, thanh chính là của ngươi, xứ thức thân nhĩ xúc chính là của ngươi. ",
  "sn4.19:3.4": "Nhưng chỗ nào, hỡi ác ma, không có tai, không có thanh, không có xứ thức thân nhĩ xúc, thì ngươi không thể đến đó. ",
  "sn4.19:3.5": "Mũi chính là của ngươi, hương chính là của ngươi, xứ thức thân tỷ xúc chính là của ngươi. ",
  "sn4.19:3.6": "Nhưng chỗ nào, hỡi ác ma, không có mũi, không có hương, không có xứ thức thân tỷ xúc, thì ngươi không thể đến đó. ",
  "sn4.19:3.7": "Lưỡi chính là của ngươi, vị chính là của ngươi, xứ thức thân thiệt xúc chính là của ngươi... ",
  "sn4.19:3.8": "thân chính là của ngươi, xúc chính là của ngươi, xứ thức thân thân xúc chính là của ngươi... ",
  "sn4.19:3.9": "ý chính là của ngươi, pháp chính là của ngươi, xứ thức thân ý xúc chính là của ngươi. ",
  "sn4.19:3.10": "Nhưng chỗ nào, hỡi ác ma, không có ý, không có pháp, không có xứ thức thân ý xúc, thì ngươi không thể đến đó.' ",
  "sn4.19:4.1": "'Những gì người ta gọi là 'của ta', '",
  "sn4.19:4.2": "Những ai nói rằng 'của ta'; ",
  "sn4.19:4.3": "Nếu tâm ngươi còn ở đó, ",
  "sn4.19:4.4": "Hỡi sa-môn, ngươi không thể thoát khỏi ta.' ",
  "sn4.19:5.1": "'Những gì người ta gọi là 'của ta', không phải là của ta, '",
  "sn4.19:5.2": "Những ai nói 'của ta', đó không phải là ta; ",
  "sn4.19:5.3": "Hỡi ác ma, hãy hiểu như vậy, ",
  "sn4.19:5.4": "Ngươi sẽ không thể thấy được con đường của ta.' ",
  "sn4.19:6.1": "Rồi Ma Vương Pāpimā... biến mất ngay tại đó. ",
  "sn4.20:0.1": "Tương Ưng Bộ 4.20 ",
  "sn4.20:0.2": "2. Phẩm Thứ Hai ",
  "sn4.20:0.3": "Kinh Vương Quyền ",
  "sn4.20:1.1": "Một thời, Thế Tôn trú tại xứ Kosala, trong một túp lều ở rừng gần chân núi Himalaya. ",
  "sn4.20:1.2": "Rồi, khi Thế Tôn đang độc cư thiền tịnh, tư duy này khởi lên trong tâm: ",
  "sn4.20:1.3": "'Liệu có thể trị vì vương quốc mà không giết người, không sai người giết, không chinh phạt, không sai người chinh phạt, không gây khổ, không sai gây khổ, theo Chánh Pháp không?' ",
  "sn4.20:2.1": "Rồi Ma Vương Pāpimā, biết được tư duy trong tâm Thế Tôn, đi đến Thế Tôn; sau khi đến, nói với Thế Tôn: ",
  "sn4.20:2.2": "'Bạch Thế Tôn, Thế Tôn hãy trị vì vương quốc, Thiện Thệ hãy trị vì vương quốc, không giết người, không sai người giết, không chinh phạt, không sai người chinh phạt, không gây khổ, không sai gây khổ, theo Chánh Pháp.' ",
  "sn4.20:2.3": "'Ngươi thấy gì ở ta, hỡi ác ma, mà ngươi nói với ta như vậy: '",
  "sn4.20:2.4": "'Bạch Thế Tôn, Thế Tôn hãy trị vì vương quốc, Thiện Thệ hãy trị vì vương quốc, không giết người... theo Chánh Pháp'?' '",
  "sn4.20:2.5": "'Bạch Thế Tôn, Thế Tôn đã tu tập, thực hành, làm cho sung mãn, làm nền tảng, thực hiện, tích lũy, khéo tinh tấn bốn thần túc. '",
  "sn4.20:2.6": "Và bạch Thế Tôn, nếu Thế Tôn muốn, Thế Tôn có thể biến núi Himalaya, chúa tể các núi, thành vàng, và vàng đó sẽ là của ngài.' ",
  "sn4.20:3.1": "'Cả một núi vàng ròng, '",
  "sn4.20:3.2": "Dù là vàng thật toàn phần; ",
  "sn4.20:3.3": "Không đủ cho một người, ",
  "sn4.20:3.4": "Bậc trí biết vậy mà sống. ",
  "sn4.20:4.1": "Ai thấy khổ từ nguồn gốc nó, ",
  "sn4.20:4.2": "Con người ấy làm sao cúi đầu trước dục; ",
  "sn4.20:4.3": "Biết hữu là sự ràng buộc trên đời, ",
  "sn4.20:4.4": "Người ấy hãy tu tập để diệt trừ nó.' ",
  "sn4.20:5.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Thế Tôn đã biết ta, Thiện Thệ đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.20:5.2": "Phẩm thứ hai. ",
  "sn4.20:6.0": "Tóm lược phẩm này: ",
  "sn4.20:6.1": "Tảng đá, sư tử, mảnh đá văng, ",
  "sn4.20:6.2": "Thích hợp và tâm ý; ",
  "sn4.20:6.3": "Bình bát, xúc xứ, khất thực, ",
  "sn4.20:6.4": "Người nông dân và vương quyền, mười kinh đó. ",
  "sn4.21:0.1": "Tương Ưng Bộ 4.21 ",
  "sn4.21:0.2": "3. Phẩm Thứ Ba ",
  "sn4.21:0.3": "Kinh Nhiều Vị ",
  "sn4.21:1.1": "Tôi nghe như vầy",
  "sn4.21:1.2": "Một thời, Thế Tôn trú tại xứ Sakka, ở Silāvatī. ",
  "sn4.21:1.3": "Lúc bấy giờ, nhiều Tỳ Kheo đang trú không xa Thế Tôn, tinh tấn, nhiệt tâm, hết lòng tu tập. ",
  "sn4.21:1.4": "Rồi Ma Vương Pāpimā hóa thành hình một bà-la-môn, đầu búi tóc lớn bù xù, mặc áo da dê, già nua còng lưng, thở khò khè, tay cầm gậy cây udumbara, đi đến các Tỳ Kheo ấy; sau khi đến, nói với các Tỳ Kheo ấy: ",
  "sn4.21:1.5": "'Quý vị xuất gia còn trẻ, là những thiếu niên tóc đen, ở độ tuổi tốt đẹp của thanh xuân, ở giai đoạn đầu của cuộc đời, chưa được vui hưởng dục lạc. '",
  "sn4.21:1.6": "Quý vị hãy thọ hưởng dục lạc của con người. ",
  "sn4.21:1.7": "Đừng bỏ điều có thể thấy ngay đây để chạy theo điều phải chờ đợi.' ",
  "sn4.21:1.8": "'Này bà-la-môn, chúng tôi không bỏ điều có thể thấy ngay đây để chạy theo điều phải chờ đợi. '",
  "sn4.21:1.9": "Chúng tôi bỏ điều phải chờ đợi để chạy theo điều có thể thấy ngay đây. ",
  "sn4.21:1.10": "Này bà-la-môn, dục lạc được Thế Tôn dạy rằng phải chờ đợi, đầy nhiều khổ đau, nhiều não hại, và còn có nhiều nguy hiểm hơn nữa. ",
  "sn4.21:1.11": "Pháp này là điều có thể thấy ngay, không phải chờ đợi, mời đến mà thấy, có thể áp dụng ngay, bậc trí mỗi người tự mình chứng ngộ.' ",
  "sn4.21:1.12": "Khi nghe vậy, Ma Vương Pāpimā lắc đầu, thè lưỡi, nhíu mày thành ba nếp trên trán, rồi dựa gậy bước đi. ",
  "sn4.21:2.1": "Rồi các Tỳ Kheo ấy đi đến Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi một bên, các Tỳ Kheo ấy bạch Thế Tôn: ",
  "sn4.21:2.2": "'Bạch Thế Tôn, chúng con đang trú không xa Thế Tôn, tinh tấn, nhiệt tâm, hết lòng tu tập. '",
  "sn4.21:2.3": "Rồi, bạch Thế Tôn, một bà-la-môn đầu búi tóc lớn bù xù, mặc áo da dê, già nua còng lưng, thở khò khè, tay cầm gậy cây udumbara, đã đến chỗ chúng con; sau khi đến, nói với chúng con: ",
  "sn4.21:2.4": "'Quý vị xuất gia còn trẻ, là những thiếu niên tóc đen, ở độ tuổi tốt đẹp của thanh xuân, ở giai đoạn đầu của cuộc đời, chưa được vui hưởng dục lạc. '",
  "sn4.21:2.5": "Quý vị hãy thọ hưởng dục lạc của con người. ",
  "sn4.21:2.6": "Đừng bỏ điều có thể thấy ngay đây để chạy theo điều phải chờ đợi.' ",
  "sn4.21:2.7": "Khi nghe vậy, chúng con đã nói với bà-la-môn ấy: ",
  "sn4.21:2.8": "'Này bà-la-môn, chúng tôi không bỏ điều có thể thấy ngay đây để chạy theo điều phải chờ đợi. '",
  "sn4.21:2.9": "Chúng tôi bỏ điều phải chờ đợi để chạy theo điều có thể thấy ngay đây. ",
  "sn4.21:2.10": "Này bà-la-môn, dục lạc được Thế Tôn dạy rằng phải chờ đợi, đầy nhiều khổ đau, nhiều não hại, và còn có nhiều nguy hiểm hơn nữa. ",
  "sn4.21:2.11": "Pháp này là điều có thể thấy ngay, không phải chờ đợi, mời đến mà thấy, có thể áp dụng ngay, bậc trí mỗi người tự mình chứng ngộ.' ",
  "sn4.21:2.12": "Khi nghe vậy, bạch Thế Tôn, bà-la-môn ấy lắc đầu, thè lưỡi, nhíu mày thành ba nếp trên trán, rồi dựa gậy bước đi.' ",
  "sn4.21:3.1": "'Này các Tỳ Kheo, đó không phải bà-la-môn. '",
  "sn4.21:3.2": "Đó là Ma Vương Pāpimā, đến để làm mù mắt các ông.' ",
  "sn4.21:3.3": "Rồi Thế Tôn, hiểu rõ ý nghĩa này, vào lúc đó đọc bài kệ: ",
  "sn4.21:4.1": "'Ai thấy khổ từ nguồn gốc nó, '",
  "sn4.21:4.2": "Con người ấy làm sao cúi đầu trước dục; ",
  "sn4.21:4.3": "Biết hữu là sự ràng buộc trên đời, ",
  "sn4.21:4.4": "Người ấy hãy tu tập để diệt trừ nó.' ",
  "sn4.22:0.1": "Tương Ưng Bộ 4.22 ",
  "sn4.22:0.2": "3. Phẩm Thứ Ba ",
  "sn4.22:0.3": "Kinh Samiddhi ",
  "sn4.22:1.1": "Một thời, Thế Tôn trú tại xứ Sakka, ở Silāvatī. ",
  "sn4.22:1.2": "Lúc bấy giờ, Tôn giả Samiddhi đang trú không xa Thế Tôn, tinh tấn, nhiệt tâm, hết lòng tu tập. ",
  "sn4.22:1.3": "Rồi, khi Tôn giả Samiddhi đang độc cư thiền tịnh, tư duy này khởi lên trong tâm: ",
  "sn4.22:1.4": "'Thật là một điều may mắn, thật là điều tốt lành cho tôi, '",
  "sn4.22:1.5": "Vì thầy của tôi là bậc A-la-hán, Chánh Đẳng Giác. ",
  "sn4.22:1.6": "Thật là một điều may mắn, thật là điều tốt lành cho tôi, ",
  "sn4.22:1.7": "Vì tôi đã xuất gia trong Pháp và Luật được khéo thuyết như thế này. ",
  "sn4.22:1.8": "Thật là một điều may mắn, thật là điều tốt lành cho tôi, ",
  "sn4.22:1.9": "Vì các đồng phạm hạnh của tôi có giới hạnh và pháp lành.' ",
  "sn4.22:1.10": "Rồi Ma Vương Pāpimā, biết được tư duy trong tâm Tôn giả Samiddhi, đi đến Tôn giả Samiddhi; sau khi đến, tạo ra một tiếng động dữ dội đáng sợ ngay gần Tôn giả Samiddhi, đến mức như thể mặt đất đang vỡ ra. ",
  "sn4.22:2.1": "Rồi Tôn giả Samiddhi đi đến Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi một bên, Tôn giả Samiddhi bạch Thế Tôn: ",
  "sn4.22:2.2": "'Bạch Thế Tôn, con đang trú không xa Thế Tôn, tinh tấn, nhiệt tâm, hết lòng tu tập. '",
  "sn4.22:2.3": "Bạch Thế Tôn, khi con đang độc cư thiền tịnh, tư duy này khởi lên trong tâm con: ",
  "sn4.22:2.4": "'Thật là một điều may mắn, thật là điều tốt lành cho tôi, '",
  "sn4.22:2.5": "Vì thầy của tôi là bậc A-la-hán, Chánh Đẳng Giác. ",
  "sn4.22:2.6": "Thật là một điều may mắn, thật là điều tốt lành cho tôi, ",
  "sn4.22:2.7": "Vì tôi đã xuất gia trong Pháp và Luật được khéo thuyết như thế này. ",
  "sn4.22:2.8": "Thật là một điều may mắn, thật là điều tốt lành cho tôi, ",
  "sn4.22:2.9": "Vì các đồng phạm hạnh của tôi có giới hạnh và pháp lành.' ",
  "sn4.22:2.10": "Bạch Thế Tôn, gần con có tiếng động dữ dội đáng sợ, như thể mặt đất đang vỡ ra.' ",
  "sn4.22:3.1": "'Đất không vỡ đâu, này Samiddhi. '",
  "sn4.22:3.2": "Đó là Ma Vương Pāpimā, đến để làm mù mắt ngươi. ",
  "sn4.22:3.3": "Hãy đi, này Samiddhi, hãy trú ngay tại đó với tinh tấn, nhiệt tâm, hết lòng tu tập.' ",
  "sn4.22:3.4": "'Vâng, bạch Thế Tôn', Tôn giả Samiddhi vâng lời Thế Tôn, đứng dậy khỏi chỗ ngồi, đảnh lễ Thế Tôn, đi vòng quanh về phía phải, rồi đi. ",
  "sn4.22:3.5": "Lần thứ hai, Tôn giả Samiddhi trú ngay tại đó với tinh tấn, nhiệt tâm, hết lòng tu tập. ",
  "sn4.22:3.6": "Lần thứ hai, khi Tôn giả Samiddhi đang độc cư thiền tịnh... ",
  "sn4.22:3.7": "Lần thứ hai, Ma Vương Pāpimā, biết được tư duy trong tâm Tôn giả Samiddhi... ",
  "sn4.22:3.8": "như thể mặt đất đang vỡ ra. ",
  "sn4.22:3.9": "Rồi Tôn giả Samiddhi đáp lại Ma Vương Pāpimā bằng bài kệ: ",
  "sn4.22:4.1": "'Con xuất gia với lòng tin, '",
  "sn4.22:4.2": "Từ nhà ra đi không nhà; ",
  "sn4.22:4.3": "Chánh niệm, tuệ giác đã được phát triển, ",
  "sn4.22:4.4": "Tâm được khéo định tĩnh; ",
  "sn4.22:4.5": "Dù ngươi có tạo ra các hình sắc, ",
  "sn4.22:4.6": "Ngươi cũng không thể làm hại con.' ",
  "sn4.22:5.1": "Rồi Ma Vương Pāpimā, nghĩ rằng 'Tỳ Kheo Samiddhi đã biết ta', buồn khổ, chán nản, liền biến mất ngay tại đó. ",
  "sn4.23:0.1": "Tương Ưng Bộ 4.23 ",
  "sn4.23:0.2": "3. Phẩm Thứ Ba ",
  "sn4.23:0.3": "Kinh Godhika ",
  "sn4.23:1.1": "Tôi nghe như vầy",
  "sn4.23:1.2": "Một thời, Thế Tôn trú tại Rājagaha, ở rừng Trúc Lâm, chỗ nuôi dưỡng sóc. ",
  "sn4.23:1.3": "Lúc bấy giờ, Tôn giả Godhika đang trú tại sườn núi Isigili trên tảng đá đen. ",
  "sn4.23:1.4": "Rồi Tôn giả Godhika, với tinh tấn, nhiệt tâm, hết lòng tu tập, đã chứng được tâm giải thoát tạm thời. ",
  "sn4.23:1.5": "Rồi Tôn giả Godhika lại thối thất khỏi tâm giải thoát tạm thời đó. ",
  "sn4.23:1.6": "Lần thứ hai, Tôn giả Godhika, với tinh tấn, nhiệt tâm, hết lòng tu tập, đã chứng được tâm giải thoát tạm thời. ",
  "sn4.23:1.7": "Lần thứ hai, Tôn giả Godhika lại thối thất khỏi tâm giải thoát tạm thời đó. ",
  "sn4.23:1.8": "Lần thứ ba, Tôn giả Godhika, với tinh tấn, nhiệt tâm, hết lòng tu tập, đã chứng được tâm giải thoát tạm thời. ",
  "sn4.23:1.9": "Lần thứ ba, Tôn giả Godhika lại thối thất... ",
  "sn4.23:1.10": "Lần thứ tư, Tôn giả Godhika... đã chứng được tâm giải thoát tạm thời. ",
  "sn4.23:1.11": "Lần thứ tư, Tôn giả Godhika lại thối thất... ",
  "sn4.23:1.12": "Lần thứ năm, Tôn giả Godhika... đã chứng được tâm giải thoát tạm thời. ",
  "sn4.23:1.13": "Lần thứ năm, Tôn giả... lại thối thất. ",
  "sn4.23:1.14": "Lần thứ sáu, Tôn giả Godhika, với tinh tấn, nhiệt tâm, hết lòng tu tập, đã chứng được tâm giải thoát tạm thời. ",
  "sn4.23:1.15": "Lần thứ sáu, Tôn giả Godhika lại thối thất khỏi tâm giải thoát tạm thời đó. ",
  "sn4.23:1.16": "Lần thứ bảy, Tôn giả Godhika, với tinh tấn, nhiệt tâm, hết lòng tu tập, đã chứng được tâm giải thoát tạm thời. ",
  "sn4.23:2.1": "Rồi Tôn giả Godhika nghĩ rằng: ",
  "sn4.23:2.2": "'Ta đã sáu lần thối thất khỏi tâm giải thoát tạm thời. '",
  "sn4.23:2.3": "Ta hãy dùng dao.' ",
  "sn4.23:2.4": "Rồi Ma Vương Pāpimā, biết được tư duy trong tâm Tôn giả Godhika, đi đến Thế Tôn; sau khi đến, đọc những bài kệ trước Thế Tôn: ",
  "sn4.23:3.1": "'Bậc đại hùng, đại trí, '",
  "sn4.23:3.2": "Sáng rỡ thần lực và danh tiếng; ",
  "sn4.23:3.3": "Bậc đã vượt qua mọi oan thù và sợ hãi, ",
  "sn4.23:3.4": "Con đảnh lễ dưới chân Ngài, bậc có mắt thấy. ",
  "sn4.23:4.1": "Đệ tử của Ngài, bậc đại hùng, ",
  "sn4.23:4.2": "Người chiến thắng tử thần, đang muốn chết; ",
  "sn4.23:4.3": "Đang ôm ý định và dự tính, ",
  "sn4.23:4.4": "Xin Ngài hãy ngăn lại, hỡi bậc sáng chói. ",
  "sn4.23:5.1": "Bạch Thế Tôn, làm sao một đệ tử của Ngài, ",
  "sn4.23:5.2": "Người thích thú trong giáo pháp của Ngài; ",
  "sn4.23:5.3": "Vị Hữu Học chưa đạt đích, ",
  "sn4.23:5.4": "Lại có thể từ giã cuộc đời giữa chúng sinh?' ",
  "sn4.23:6.1": "Lúc bấy giờ, Tôn giả Godhika đã dùng dao. ",
  "sn4.23:6.2": "Rồi Thế Tôn biết rằng 'Đây là Ma Vương Pāpimā', liền đáp lại Ma Vương bằng bài kệ: ",
  "sn4.23:7.1": "'Đây là điều bậc trí dũng làm, '",
  "sn4.23:7.2": "Không tham tiếc mạng sống; ",
  "sn4.23:7.3": "Nhổ tận gốc rễ tham ái, ",
  "sn4.23:7.4": "Godhika đã Niết-bàn.' ",
  "sn4.23:8.1": "Rồi Thế Tôn gọi các Tỳ Kheo: ",
  "sn4.23:8.2": "'Này các Tỳ Kheo, hãy đến, chúng ta sẽ đi đến sườn núi Isigili, tảng đá đen, nơi thiện nam tử Godhika đã dùng dao.' ",
  "sn4.23:8.3": "'Vâng, bạch Thế Tôn', các Tỳ Kheo ấy vâng lời Thế Tôn. ",
  "sn4.23:9.1": "Rồi Thế Tôn cùng với nhiều Tỳ Kheo đi đến sườn núi Isigili, tảng đá đen. ",
  "sn4.23:9.2": "Thế Tôn thấy từ xa Tôn giả Godhika đang nằm trên giường, đầu cúi xuống. ",
  "sn4.23:9.3": "Lúc bấy giờ, có một làn khói, một bóng tối đang bay về phía đông, bay về phía tây, bay về phía bắc, bay về phía nam, bay lên trên, bay xuống dưới, bay các hướng phụ. ",
  "sn4.23:10.1": "Rồi Thế Tôn gọi các Tỳ Kheo: ",
  "sn4.23:10.2": "'Này các Tỳ Kheo, các ông có thấy làn khói, bóng tối kia đang bay về phía đông, bay về phía tây, bay về phía bắc, bay về phía nam, bay lên trên, bay xuống dưới, bay các hướng phụ không?' ",
  "sn4.23:10.3": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn4.23:10.4": "'Này các Tỳ Kheo, đó là Ma Vương Pāpimā đang tìm thức của thiện nam tử Godhika: '",
  "sn4.23:10.5": "'Thức của thiện nam tử Godhika an trú ở đâu?' ",
  "sn4.23:10.6": "Nhưng, này các Tỳ Kheo, thiện nam tử Godhika đã Niết-bàn với thức không an trú ở đâu cả.' ",
  "sn4.23:10.7": "Rồi Ma Vương Pāpimā cầm đàn vīṇā màu vàng, đi đến Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn4.23:11.1": "'Trên dưới và ngang, '",
  "sn4.23:11.2": "Các hướng và các hướng phụ, ta tìm khắp; ",
  "sn4.23:11.3": "Tìm mãi mà không thấy, ",
  "sn4.23:11.4": "Godhika ấy đã đi đâu?' ",
  "sn4.23:12.1": "'Bậc trí, đầy đủ ý chí kiên cường, '",
  "sn4.23:12.2": "Luôn thiền định, thích thú thiền định; ",
  "sn4.23:12.3": "Ngày đêm tinh tấn tu tập, ",
  "sn4.23:12.4": "Không tham tiếc mạng sống. ",
  "sn4.23:13.1": "Đã chiến thắng quân đội của Tử Thần, ",
  "sn4.23:13.2": "Không trở lại hữu; ",
  "sn4.23:13.3": "Nhổ tận gốc rễ tham ái, ",
  "sn4.23:13.4": "Godhika đã Niết-bàn.' ",
  "sn4.23:14.1": "Ma Vương ấy chìm đắm trong sầu khổ, ",
  "sn4.23:14.2": "Cây đàn rơi khỏi nách; ",
  "sn4.23:14.3": "Rồi dạ-xoa buồn rầu ấy, ",
  "sn4.23:14.4": "Liền biến mất ngay tại đó. ",
  "sn4.24:0.1": "Tương Ưng Bộ 4.24 ",
  "sn4.24:0.2": "3. Phẩm Thứ Ba ",
  "sn4.24:0.3": "Kinh Bảy Năm Theo Đuổi ",
  "sn4.24:1.1": "Tôi nghe như vầy",
  "sn4.24:1.2": "Một thời, Thế Tôn trú tại Uruvelā, trên bờ sông Nerañjarā, dưới cây Ajapāla Nigrodha. ",
  "sn4.24:1.3": "Lúc bấy giờ, Ma Vương Pāpimā đã theo đuổi Thế Tôn suốt bảy năm, luôn rình tìm cơ hội, nhưng không tìm được cơ hội nào. ",
  "sn4.24:1.4": "Rồi Ma Vương Pāpimā đi đến Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn4.24:2.1": "'Ngài ngồi thiền trong rừng với nỗi ưu sầu, '",
  "sn4.24:2.2": "Phải chăng đã mất của cải hay đang mong muốn; ",
  "sn4.24:2.3": "Phải chăng đã làm điều gì sai trong làng, ",
  "sn4.24:2.4": "Sao không kết thân với người; ",
  "sn4.24:2.5": "Phải chăng Ngài không có ai làm bạn?' ",
  "sn4.24:3.1": "'Ta đã đào bứng hết mọi gốc rễ sầu khổ, '",
  "sn4.24:3.2": "Ta thiền định không sầu, không tội lỗi; ",
  "sn4.24:3.3": "Đã chặt đứt mọi tham đắm hữu, ",
  "sn4.24:3.4": "Ta thiền định không lậu hoặc, hỡi kẻ thích buộc ràng.' ",
  "sn4.24:4.1": "'Những gì người ta gọi là 'của ta', '",
  "sn4.24:4.2": "Những ai nói rằng 'của ta'; ",
  "sn4.24:4.3": "Nếu tâm ngươi còn ở đó, ",
  "sn4.24:4.4": "Hỡi sa-môn, ngươi không thể thoát khỏi ta.' ",
  "sn4.24:5.1": "'Những gì người ta gọi là 'của ta', không phải là của ta, '",
  "sn4.24:5.2": "Những ai nói 'của ta', đó không phải là ta; ",
  "sn4.24:5.3": "Hỡi ác ma, hãy hiểu như vậy, ",
  "sn4.24:5.4": "Ngươi sẽ không thể thấy được con đường của ta.' ",
  "sn4.24:6.1": "'Nếu Ngài đã giác ngộ con đường, '",
  "sn4.24:6.2": "Con đường an ổn dẫn đến bất tử; ",
  "sn4.24:6.3": "Hãy đi một mình, ",
  "sn4.24:6.4": "Việc gì mà dạy bảo người khác?' ",
  "sn4.24:7.1": "'Những ai muốn đến bờ kia, '",
  "sn4.24:7.2": "Hỏi ta về cảnh giới bất tử; ",
  "sn4.24:7.3": "Ta được hỏi, Ta trả lời cho họ, ",
  "sn4.24:7.4": "Điều chân thật ấy là không hữu.' ",
  "sn4.24:8.1": "'Bạch Thế Tôn, ví như gần một làng hay thị trấn có một cái ao. '",
  "sn4.24:8.2": "Ở đó có một con cua. ",
  "sn4.24:8.3": "Rồi, bạch Thế Tôn, nhiều đứa trẻ trai hay gái từ làng hay thị trấn ấy ra đi, đến chỗ cái ao đó; sau khi đến, kéo con cua lên khỏi nước, đặt nó trên đất. ",
  "sn4.24:8.4": "Mỗi khi con cua ấy giơ càng ra, bạch Thế Tôn, các đứa trẻ trai hay gái ấy liền chặt, bẻ gãy, đập vỡ từng cái càng đó. ",
  "sn4.24:8.5": "Như vậy, bạch Thế Tôn, con cua ấy với tất cả các càng bị chặt đứt, bị bẻ gãy, bị đập vỡ, không thể trở lại cái ao đó. ",
  "sn4.24:8.6": "Cũng vậy, bạch Thế Tôn, tất cả những gì có thể che giấu, giả tạo, dao động, Thế Tôn đã chặt đứt tất cả, bẻ gãy, đập vỡ. ",
  "sn4.24:8.7": "Con không thể đến gần Thế Tôn nữa để rình tìm cơ hội.' ",
  "sn4.24:8.8": "Rồi Ma Vương Pāpimā đọc những bài kệ chán nản này trước Thế Tôn: ",
  "sn4.24:9.1": "'Con quạ bay vòng quanh, '",
  "sn4.24:9.2": "Hòn đá màu như mỡ; ",
  "sn4.24:9.3": "Ở đây ta tìm chỗ mềm mại, ",
  "sn4.24:9.4": "Liệu có gì ngon ngọt không. ",
  "sn4.24:10.1": "Không tìm được gì ngon ngọt ở đó, ",
  "sn4.24:10.2": "Con quạ từ đó bay đi; ",
  "sn4.24:10.3": "Như quạ đụng đầu vào đá, ",
  "sn4.24:10.4": "Ta đành bỏ Gotama mà đi.' ",
  "sn4.25:0.1": "Tương Ưng Bộ 4.25 ",
  "sn4.25:0.2": "3. Phẩm Thứ Ba ",
  "sn4.25:0.3": "Kinh Con Gái Của Ma ",
  "sn4.25:1.1": "Rồi Ma Vương Pāpimā, sau khi đọc những bài kệ chán nản đó trước Thế Tôn, rời khỏi chỗ đó, ngồi kiết già không xa Thế Tôn, im lặng, buồn bã, vai sụp xuống, mặt cúi xuống, ngồi thất vọng, không nói gì, dùng que vẽ lên đất. ",
  "sn4.25:1.2": "Rồi Taṇhā, Aratī và Ragā, các con gái của Ma Vương, đi đến Ma Vương Pāpimā; sau khi đến, đọc bài kệ trước Ma Vương Pāpimā: ",
  "sn4.25:2.1": "'Vì sao cha buồn, '",
  "sn4.25:2.2": "Người đàn ông nào cha đang lo; ",
  "sn4.25:2.3": "Chúng con sẽ dùng dây ái dục trói lại, ",
  "sn4.25:2.4": "Như voi rừng; ",
  "sn4.25:2.5": "Trói lại rồi dẫn đến cho cha, ",
  "sn4.25:2.6": "Người ấy sẽ trở thành thuộc hạ của cha.' ",
  "sn4.25:3.1": "'Bậc A-la-hán, Thiện Thệ trên đời, '",
  "sn4.25:3.2": "Không dễ dàng kéo bằng ái dục; ",
  "sn4.25:3.3": "Đã vượt qua cõi của Ma, ",
  "sn4.25:3.4": "Vì vậy ta buồn rất nhiều.' ",
  "sn4.25:4.1": "Rồi Taṇhā, Aratī và Ragā, các con gái của Ma Vương, đi đến Thế Tôn; sau khi đến, bạch Thế Tôn: ",
  "sn4.25:4.2": "'Chúng con xin hầu hạ dưới chân Ngài, hỡi sa-môn.' ",
  "sn4.25:4.3": "Rồi Thế Tôn không để tâm đến điều đó, vì Ngài đã hoàn toàn giải thoát trong sự diệt tận của hữu vô thượng. ",
  "sn4.25:5.1": "Rồi Taṇhā, Aratī và Ragā, các con gái của Ma Vương, lui ra một chỗ và cùng nhau bàn tính: ",
  "sn4.25:5.2": "'Sở thích của đàn ông thật muôn hình vạn trạng. '",
  "sn4.25:5.3": "Ta hãy mỗi người hóa thành một trăm thiếu nữ.' ",
  "sn4.25:5.4": "Rồi Taṇhā, Aratī và Ragā, mỗi người hóa thành một trăm thiếu nữ, đi đến Thế Tôn; sau khi đến, bạch Thế Tôn: ",
  "sn4.25:5.5": "'Chúng con xin hầu hạ dưới chân Ngài, hỡi sa-môn.' ",
  "sn4.25:5.6": "Thế Tôn cũng không để tâm đến điều đó, vì Ngài đã hoàn toàn giải thoát trong sự diệt tận của hữu vô thượng. ",
  "sn4.25:6.1": "Rồi Taṇhā, Aratī và Ragā lui ra một chỗ và cùng nhau bàn tính: ",
  "sn4.25:6.2": "'Sở thích của đàn ông thật muôn hình vạn trạng. '",
  "sn4.25:6.3": "Ta hãy mỗi người hóa thành một trăm người phụ nữ chưa sinh con.' ",
  "sn4.25:6.4": "Rồi Taṇhā, Aratī và Ragā mỗi người hóa thành một trăm người phụ nữ chưa sinh con, đi đến Thế Tôn; sau khi đến, bạch Thế Tôn: ",
  "sn4.25:6.5": "'Chúng con xin hầu hạ dưới chân Ngài, hỡi sa-môn.' ",
  "sn4.25:6.6": "Thế Tôn cũng không để tâm đến điều đó, vì Ngài đã hoàn toàn giải thoát trong sự diệt tận của hữu vô thượng. ",
  "sn4.25:7.1": "Rồi Taṇhā... ",
  "sn4.25:7.2": "Ta hãy mỗi người hóa thành một trăm người phụ nữ đã sinh một lần. ",
  "sn4.25:7.3": "Rồi Taṇhā... ",
  "sn4.25:7.4": "mỗi người hóa thành một trăm người phụ nữ đã sinh một lần, đi đến Thế Tôn; sau khi đến, bạch Thế Tôn: ",
  "sn4.25:7.5": "'Chúng con xin hầu hạ dưới chân Ngài, hỡi sa-môn.' ",
  "sn4.25:7.6": "Thế Tôn cũng không để tâm đến điều đó, vì Ngài đã hoàn toàn giải thoát trong sự diệt tận của hữu vô thượng. ",
  "sn4.25:8.1": "Rồi Taṇhā... ",
  "sn4.25:8.2": "Ta hãy mỗi người hóa thành một trăm người phụ nữ đã sinh hai lần. ",
  "sn4.25:8.3": "Rồi Taṇhā... ",
  "sn4.25:8.4": "mỗi người hóa thành một trăm người phụ nữ đã sinh hai lần, đi đến Thế Tôn... ",
  "sn4.25:8.5": "vì Ngài đã hoàn toàn giải thoát trong sự diệt tận của hữu vô thượng. ",
  "sn4.25:8.6": "Rồi Taṇhā... ",
  "sn4.25:8.7": "Ta hãy mỗi người hóa thành một trăm người phụ nữ trung niên.' ",
  "sn4.25:8.8": "Rồi Taṇhā... ",
  "sn4.25:8.9": "mỗi người hóa thành một trăm người phụ nữ trung niên... ",
  "sn4.25:8.10": "vì Ngài đã hoàn toàn giải thoát trong sự diệt tận của hữu vô thượng. ",
  "sn4.25:9.1": "Rồi Taṇhā... ",
  "sn4.25:9.2": "Ta hãy mỗi người hóa thành một trăm bà già.' ",
  "sn4.25:9.3": "Rồi Taṇhā... ",
  "sn4.25:9.4": "mỗi người hóa thành một trăm bà già, đi đến Thế Tôn... ",
  "sn4.25:9.5": "vì Ngài đã hoàn toàn giải thoát trong sự diệt tận của hữu vô thượng. ",
  "sn4.25:9.6": "Rồi Taṇhā, Aratī và Ragā, các con gái của Ma Vương, lui ra một chỗ và nói với nhau: ",
  "sn4.25:9.7": "'Thật vậy, cha ta đã nói đúng: '",
  "sn4.25:10.1": "'Bậc A-la-hán, Thiện Thệ trên đời, '",
  "sn4.25:10.2": "Không dễ dàng kéo bằng ái dục; ",
  "sn4.25:10.3": "Đã vượt qua cõi của Ma, ",
  "sn4.25:10.4": "Vì vậy ta buồn rất nhiều.' ",
  "sn4.25:11.1": "Nếu chúng ta dùng cách này tiếp cận một sa-môn hay bà-la-môn chưa thoát khỏi tham dục, tim của vị ấy có thể bị vỡ, hoặc máu nóng phun ra từ miệng, hoặc vị ấy có thể trở nên điên loạn. ",
  "sn4.25:11.2": "Cũng như cây sậy non bị cắt đứt thì khô héo, tàn lụi, phai tàn; ",
  "sn4.25:11.3": "Cũng vậy người đó sẽ khô héo, tàn lụi, phai tàn.' ",
  "sn4.25:12.1": "Rồi Taṇhā, Aratī và Ragā, các con gái của Ma Vương, đi đến Thế Tôn; sau khi đến, đứng một bên. ",
  "sn4.25:12.2": "Đứng một bên, Taṇhā, con gái của Ma Vương, đọc bài kệ trước Thế Tôn: ",
  "sn4.25:13.1": "'Ngài ngồi thiền trong rừng với nỗi ưu sầu, '",
  "sn4.25:13.2": "Phải chăng đã mất của cải hay đang mong muốn; ",
  "sn4.25:13.3": "Phải chăng đã làm điều gì sai trong làng, ",
  "sn4.25:13.4": "Sao không kết thân với người; ",
  "sn4.25:13.5": "Phải chăng Ngài không có ai làm bạn?' ",
  "sn4.25:14.1": "'Đã đạt được mục tiêu, bình an trong tâm, '",
  "sn4.25:14.2": "Chiến thắng quân đội mang sắc tướng đáng yêu; ",
  "sn4.25:14.3": "Ta một mình thiền định, giác ngộ an lạc, ",
  "sn4.25:14.4": "Vì vậy ta không kết thân với người; ",
  "sn4.25:14.5": "Ta không có ai làm bạn.' ",
  "sn4.25:15.1": "Rồi Aratī, con gái của Ma Vương, đọc bài kệ trước Thế Tôn: ",
  "sn4.25:16.1": "'Tỳ Kheo ở đây thường trú như thế nào, '",
  "sn4.25:16.2": "Đã vượt qua năm dòng lũ, và vượt qua dòng thứ sáu; ",
  "sn4.25:16.3": "Tỳ Kheo thiền định nhiều như thế nào mà tưởng về dục lạc, ",
  "sn4.25:16.4": "Bị đẩy ra ngoài với kẻ không đạt được điều đó?' ",
  "sn4.25:17.1": "'Với thân khinh an, tâm hoàn toàn giải thoát, '",
  "sn4.25:17.2": "Không tạo tác, chánh niệm, không chỗ ở; ",
  "sn4.25:17.3": "Biết Pháp, thiền định không tầm; ",
  "sn4.25:17.4": "Không bực bội, không tán loạn, không hôn trầm. ",
  "sn4.25:18.1": "Tỳ Kheo ở đây thường trú như vậy, ",
  "sn4.25:18.2": "Đã vượt qua năm dòng lũ, và vượt qua dòng thứ sáu; ",
  "sn4.25:18.3": "Tỳ Kheo thiền định nhiều như vậy mà tưởng về dục lạc, ",
  "sn4.25:18.4": "Bị đẩy ra ngoài với kẻ không đạt được điều đó.' ",
  "sn4.25:19.1": "Rồi Ragā, con gái của Ma Vương, đọc bài kệ trước Thế Tôn: ",
  "sn4.25:20.1": "'Sau khi cắt đứt tham ái, Ngài du hành cùng đại chúng, '",
  "sn4.25:20.2": "Chắc chắn nhiều người sẽ đi theo với lòng tin; ",
  "sn4.25:20.3": "Ngài đã đưa ra con đường không chỗ ở cho bao người, ",
  "sn4.25:20.4": "Ngài sẽ dẫn họ vượt qua cõi của Vua Tử Thần.' ",
  "sn4.25:21.1": "'Các bậc đại hùng, các Như Lai, '",
  "sn4.25:21.2": "Dẫn dắt bằng Chánh Pháp; ",
  "sn4.25:21.3": "Kẻ trí biết rõ được dẫn dắt bằng Pháp, ",
  "sn4.25:21.4": "Thì còn gây ra oán thù làm gì?' ",
  "sn4.25:22.1": "Rồi Taṇhā, Aratī và Ragā, các con gái của Ma Vương, đi đến Ma Vương Pāpimā. ",
  "sn4.25:22.2": "Ma Vương Pāpimā thấy từ xa Taṇhā, Aratī và Ragā, các con gái, đang đến. ",
  "sn4.25:22.3": "Sau khi thấy, đọc những bài kệ: ",
  "sn4.25:23.1": "'Bọn ngốc dùng những cành sen nhỏ, '",
  "sn4.25:23.2": "Cố đâm thủng núi; ",
  "sn4.25:23.3": "Dùng móng tay cào núi đá, ",
  "sn4.25:23.4": "Dùng răng gặm sắt. ",
  "sn4.25:24.1": "Như đập đầu vào đá tảng, ",
  "sn4.25:24.2": "Tìm chỗ đứng dưới vực thẳm; ",
  "sn4.25:24.3": "Như đụng ngực vào cọc, ",
  "sn4.25:24.4": "Hãy chán nản mà bỏ Gotama.' ",
  "sn4.25:25.1": "'Taṇhā, Aratī và Ragā, '",
  "sn4.25:25.2": "Đến với ánh sáng rực rỡ; ",
  "sn4.25:25.3": "Nhưng bậc Đạo Sư đã xua đuổi họ ở đó, ",
  "sn4.25:25.4": "Như gió thổi bay bông gòn.' ",
  "sn4.25:25.5": "Phẩm thứ ba. ",
  "sn4.25:26.0": "Tóm lược phẩm này: ",
  "sn4.25:26.1": "Nhiều vị, Samiddhi, ",
  "sn4.25:26.2": "Godhika, bảy năm; ",
  "sn4.25:26.3": "Các con gái được thuyết bởi Phật, ",
  "sn4.25:26.4": "Đây là năm kinh về Ma, tối thượng. ",
  "sn4.25:26.5": "Tương Ưng Về Ma viên mãn. "
}
window.BILARA["sn4_v1"]["vi"]["sn4_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
