window.BILARA = window.BILARA || {};
window.BILARA["sn51_v1"] = window.BILARA["sn51_v1"] || {};
window.BILARA["sn51_v1"]["vi"] = {
  "sn51.1:0.1": "Tương Ưng Bộ 51.1",
  "sn51.1:0.2": "1. Phẩm Cāpāla",
  "sn51.1:0.3": "Kinh Bờ Kia",
  "sn51.1:1.1": "Này các Tỳ Kheo, bốn thần túc này, được tu tập, được thực hành nhiều, đưa đến việc đi từ bờ bên này sang bờ bên kia.",
  "sn51.1:1.2": "Thế nào là bốn?",
  "sn51.1:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.1:1.4": "tu tập thần túc câu hữu với định do tinh tấn, cùng với các nỗ lực hành,",
  "sn51.1:1.5": "tu tập thần túc câu hữu với định do tâm, cùng với các nỗ lực hành,",
  "sn51.1:1.6": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.1:1.7": "'Này các Tỳ Kheo, chính bốn thần túc này, được tu tập, được thực hành nhiều, đưa đến việc đi từ bờ bên này sang bờ bên kia.'",
  "sn51.1:1.8": "Thứ nhất.",
  "sn51.2:0.1": "Tương Ưng Bộ 51.2",
  "sn51.2:0.2": "1. Phẩm Cāpāla",
  "sn51.2:0.3": "Kinh Từ Bỏ",
  "sn51.2:1.1": "Này các Tỳ Kheo, ai đã từ bỏ bốn thần túc, người ấy đã từ bỏ con đường thánh đưa đến sự diệt khổ hoàn toàn.",
  "sn51.2:1.2": "Này các Tỳ Kheo, ai nỗ lực với bốn thần túc, người ấy nỗ lực với con đường thánh đưa đến sự diệt khổ hoàn toàn.",
  "sn51.2:1.3": "Thế nào là bốn?",
  "sn51.2:1.4": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.2:1.5": "định do tinh tấn …vv…",
  "sn51.2:1.6": "định do tâm …vv…",
  "sn51.2:1.7": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.2:1.8": "Này các Tỳ Kheo, ai đã từ bỏ bốn thần túc này, người ấy đã từ bỏ con đường thánh đưa đến sự diệt khổ hoàn toàn.",
  "sn51.2:1.9": "'Này các Tỳ Kheo, ai nỗ lực với bốn thần túc này, người ấy nỗ lực với con đường thánh đưa đến sự diệt khổ hoàn toàn.'",
  "sn51.2:1.10": "Thứ hai.",
  "sn51.3:0.1": "Tương Ưng Bộ 51.3",
  "sn51.3:0.2": "1. Phẩm Cāpāla",
  "sn51.3:0.3": "Kinh Bậc Thánh",
  "sn51.3:1.1": "Này các Tỳ Kheo, bốn thần túc này, được tu tập, được thực hành nhiều, là bậc thánh, dẫn đến giải thoát, đưa người thực hành đến sự diệt khổ hoàn toàn.",
  "sn51.3:1.2": "Thế nào là bốn?",
  "sn51.3:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.3:1.4": "định do tinh tấn …vv…",
  "sn51.3:1.5": "định do tâm …vv…",
  "sn51.3:1.6": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.3:1.7": "'Này các Tỳ Kheo, chính bốn thần túc này, được tu tập, được thực hành nhiều, là bậc thánh, dẫn đến giải thoát, đưa người thực hành đến sự diệt khổ hoàn toàn.'",
  "sn51.3:1.8": "Thứ ba.",
  "sn51.4:0.1": "Tương Ưng Bộ 51.4",
  "sn51.4:0.2": "1. Phẩm Cāpāla",
  "sn51.4:0.3": "Kinh Nhàm Chán",
  "sn51.4:1.1": "Này các Tỳ Kheo, bốn thần túc này, được tu tập, được thực hành nhiều, đưa đến hoàn toàn nhàm chán, ly tham, đoạn diệt, tịch tịnh, thắng trí, chánh giác, Niết-bàn.",
  "sn51.4:1.2": "Thế nào là bốn?",
  "sn51.4:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.4:1.4": "định do tinh tấn …vv…",
  "sn51.4:1.5": "định do tâm …vv…",
  "sn51.4:1.6": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.4:1.7": "'Này các Tỳ Kheo, chính bốn thần túc này, được tu tập, được thực hành nhiều, đưa đến hoàn toàn nhàm chán, ly tham, đoạn diệt, tịch tịnh, thắng trí, chánh giác, Niết-bàn.'",
  "sn51.4:1.8": "Thứ tư.",
  "sn51.5:0.1": "Tương Ưng Bộ 51.5",
  "sn51.5:0.2": "1. Phẩm Cāpāla",
  "sn51.5:0.3": "Kinh Thần Thông Phần",
  "sn51.5:1.1": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong quá khứ đã thành tựu thần thông phần, tất cả đều do đã tu tập và thực hành nhiều bốn thần túc.",
  "sn51.5:1.2": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong tương lai sẽ thành tựu thần thông phần, tất cả đều do tu tập và thực hành nhiều bốn thần túc.",
  "sn51.5:1.3": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong hiện tại đang thành tựu thần thông phần, tất cả đều do tu tập và thực hành nhiều bốn thần túc.",
  "sn51.5:2.1": "Thế nào là bốn?",
  "sn51.5:2.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.5:2.3": "định do tinh tấn …vv…",
  "sn51.5:2.4": "định do tâm …vv…",
  "sn51.5:2.5": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.5:2.6": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong quá khứ đã thành tựu thần thông phần, tất cả đều do đã tu tập và thực hành nhiều bốn thần túc này.",
  "sn51.5:2.7": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong tương lai sẽ thành tựu thần thông phần, tất cả đều do tu tập và thực hành nhiều bốn thần túc này.",
  "sn51.5:2.8": "'Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong hiện tại đang thành tựu thần thông phần, tất cả đều do tu tập và thực hành nhiều bốn thần túc này.'",
  "sn51.5:2.9": "Thứ năm.",
  "sn51.6:0.1": "Tương Ưng Bộ 51.6",
  "sn51.6:0.2": "1. Phẩm Cāpāla",
  "sn51.6:0.3": "Kinh Thần Thông Viên Mãn",
  "sn51.6:1.1": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong quá khứ đã thành tựu thần thông viên mãn, tất cả đều do đã tu tập và thực hành nhiều bốn thần túc.",
  "sn51.6:1.2": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong tương lai sẽ thành tựu thần thông viên mãn, tất cả đều do tu tập và thực hành nhiều bốn thần túc.",
  "sn51.6:1.3": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong hiện tại đang thành tựu thần thông viên mãn, tất cả đều do tu tập và thực hành nhiều bốn thần túc.",
  "sn51.6:2.1": "Thế nào là bốn?",
  "sn51.6:2.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.6:2.3": "định do tinh tấn …vv…",
  "sn51.6:2.4": "định do tâm …vv…",
  "sn51.6:2.5": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.6:2.6": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong quá khứ đã thành tựu thần thông viên mãn, tất cả đều do đã tu tập và thực hành nhiều bốn thần túc này.",
  "sn51.6:2.7": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong tương lai sẽ thành tựu thần thông viên mãn, tất cả đều do tu tập và thực hành nhiều bốn thần túc này.",
  "sn51.6:2.8": "'Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong hiện tại đang thành tựu thần thông viên mãn, tất cả đều do tu tập và thực hành nhiều bốn thần túc này.'",
  "sn51.6:2.9": "Thứ sáu.",
  "sn51.7:0.1": "Tương Ưng Bộ 51.7",
  "sn51.7:0.2": "1. Phẩm Cāpāla",
  "sn51.7:0.3": "Kinh Tỳ Kheo",
  "sn51.7:1.1": "Này các Tỳ Kheo, bất kỳ Tỳ Kheo nào trong quá khứ đã đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú, tất cả đều do tu tập và thực hành nhiều bốn thần túc.",
  "sn51.7:1.2": "Này các Tỳ Kheo, bất kỳ Tỳ Kheo nào trong tương lai sẽ đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú, tất cả đều do tu tập và thực hành nhiều bốn thần túc.",
  "sn51.7:1.3": "Này các Tỳ Kheo, bất kỳ Tỳ Kheo nào hiện tại đang đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú, tất cả đều do tu tập và thực hành nhiều bốn thần túc.",
  "sn51.7:2.1": "Thế nào là bốn?",
  "sn51.7:2.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.7:2.3": "định do tinh tấn …vv…",
  "sn51.7:2.4": "định do tâm …vv…",
  "sn51.7:2.5": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.7:2.6": "Này các Tỳ Kheo, bất kỳ Tỳ Kheo nào trong quá khứ đã đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú, tất cả đều do tu tập và thực hành nhiều bốn thần túc này.",
  "sn51.7:2.7": "Này các Tỳ Kheo, bất kỳ Tỳ Kheo nào trong tương lai sẽ đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú, tất cả đều do tu tập và thực hành nhiều bốn thần túc này.",
  "sn51.7:2.8": "'Này các Tỳ Kheo, bất kỳ Tỳ Kheo nào hiện tại đang đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú, tất cả đều do tu tập và thực hành nhiều bốn thần túc này.'",
  "sn51.7:2.9": "Thứ bảy.",
  "sn51.8:0.1": "Tương Ưng Bộ 51.8",
  "sn51.8:0.2": "1. Phẩm Cāpāla",
  "sn51.8:0.3": "Kinh Đức Phật",
  "sn51.8:1.1": "Này các Tỳ Kheo, có bốn thần túc.",
  "sn51.8:1.2": "Thế nào là bốn?",
  "sn51.8:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.8:1.4": "định do tinh tấn …vv…",
  "sn51.8:1.5": "định do tâm …vv…",
  "sn51.8:1.6": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.8:1.7": "Này các Tỳ Kheo, đây là bốn thần túc.",
  "sn51.8:1.8": "'Này các Tỳ Kheo, do tu tập và thực hành nhiều bốn thần túc này, Như Lai được gọi là 'Bậc A-la-hán, Chánh Đẳng Giác'.'",
  "sn51.8:1.9": "Thứ tám.",
  "sn51.9:0.1": "Tương Ưng Bộ 51.9",
  "sn51.9:0.2": "1. Phẩm Cāpāla",
  "sn51.9:0.3": "Kinh Tri Kiến",
  "sn51.9:1.1": "Này các Tỳ Kheo, đối với Ta, về 'thần túc câu hữu với định do dục, cùng với các nỗ lực hành' này, trong những pháp trước đây chưa được nghe, mắt đã sanh khởi, trí đã sanh khởi, tuệ đã sanh khởi, minh đã sanh khởi, ánh sáng đã sanh khởi.",
  "sn51.9:1.2": "Này các Tỳ Kheo, về 'thần túc câu hữu với định do dục, cùng với các nỗ lực hành' này cần được tu tập, đối với Ta …",
  "sn51.9:1.3": "Về 'đã được tu tập', này các Tỳ Kheo, trong những pháp trước đây chưa được nghe, mắt đã sanh khởi, trí đã sanh khởi, tuệ đã sanh khởi, minh đã sanh khởi, ánh sáng đã sanh khởi.",
  "sn51.9:2.1": "Này các Tỳ Kheo, đối với Ta, về 'thần túc câu hữu với định do tinh tấn, cùng với các nỗ lực hành' này, trong những pháp trước đây chưa được nghe, mắt đã sanh khởi, trí đã sanh khởi, tuệ đã sanh khởi, minh đã sanh khởi, ánh sáng đã sanh khởi.",
  "sn51.9:2.2": "Này các Tỳ Kheo, về 'thần túc câu hữu với định do tinh tấn, cùng với các nỗ lực hành' này cần được tu tập, đối với Ta …",
  "sn51.9:2.3": "Về 'đã được tu tập', này các Tỳ Kheo, trong những pháp trước đây chưa được nghe, mắt đã sanh khởi, trí đã sanh khởi, tuệ đã sanh khởi, minh đã sanh khởi, ánh sáng đã sanh khởi.",
  "sn51.9:3.1": "Này các Tỳ Kheo, đối với Ta, về 'thần túc câu hữu với định do tâm, cùng với các nỗ lực hành' này, trong những pháp trước đây chưa được nghe, mắt đã sanh khởi, trí đã sanh khởi, tuệ đã sanh khởi, minh đã sanh khởi, ánh sáng đã sanh khởi.",
  "sn51.9:3.2": "Này các Tỳ Kheo, về 'thần túc câu hữu với định do tâm, cùng với các nỗ lực hành' này cần được tu tập, đối với Ta …",
  "sn51.9:3.3": "Về 'đã được tu tập', này các Tỳ Kheo, trong những pháp trước đây chưa được nghe, mắt đã sanh khởi, trí đã sanh khởi, tuệ đã sanh khởi, minh đã sanh khởi, ánh sáng đã sanh khởi.",
  "sn51.9:4.1": "Này các Tỳ Kheo, đối với Ta, về 'thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành' này, trong những pháp trước đây chưa được nghe, mắt đã sanh khởi, trí đã sanh khởi, tuệ đã sanh khởi, minh đã sanh khởi, ánh sáng đã sanh khởi.",
  "sn51.9:4.2": "Này các Tỳ Kheo, về 'thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành' này cần được tu tập, đối với Ta …",
  "sn51.9:4.3": "'Về 'đã được tu tập', này các Tỳ Kheo, trong những pháp trước đây chưa được nghe, mắt đã sanh khởi, trí đã sanh khởi, tuệ đã sanh khởi, minh đã sanh khởi, ánh sáng đã sanh khởi.'",
  "sn51.9:4.4": "Thứ chín.",
  "sn51.10:0.1": "Tương Ưng Bộ 51.10",
  "sn51.10:0.2": "1. Phẩm Cāpāla",
  "sn51.10:0.3": "Kinh Tháp Cāpāla",
  "sn51.10:1.1": "Tôi nghe như vầy",
  "sn51.10:1.2": "một thời, Thế Tôn trú ở Vesālī, tại Mahāvana, trong giảng đường có nóc nhọn.",
  "sn51.10:1.3": "Rồi vào buổi sáng, Thế Tôn đắp y, mang bát đi vào Vesālī để khất thực.",
  "sn51.10:1.4": "Sau khi đi khất thực ở Vesālī, sau bữa ăn, trên đường trở về, Thế Tôn gọi Tôn giả Ānanda:",
  "sn51.10:1.5": "Ānanda, hãy mang tọa cụ theo.",
  "sn51.10:1.6": "'Chúng ta sẽ đến đền Cāpāla để nghỉ ngơi ban ngày.'",
  "sn51.10:1.7": "Thưa vâng, bạch Thế Tôn.' Tôn giả Ānanda vâng đáp, mang tọa cụ và đi theo sau Thế Tôn.",
  "sn51.10:2.1": "Rồi Thế Tôn đến đền Cāpāla; đến nơi, Ngài ngồi xuống chỗ đã soạn sẵn.",
  "sn51.10:2.2": "Tôn giả Ānanda cũng đảnh lễ Thế Tôn rồi ngồi một bên.",
  "sn51.10:2.3": "Khi Tôn giả Ānanda đã ngồi một bên, Thế Tôn nói với Ngài:",
  "sn51.10:3.1": "Này Ānanda, Vesālī thật khả ái, đền Udena thật khả ái, đền Gotamaka thật khả ái, đền Sattamba thật khả ái, đền Bahuputta thật khả ái, đền Sārandada thật khả ái, đền Cāpāla thật khả ái.",
  "sn51.10:3.2": "Này Ānanda, ai đã tu tập và thực hành nhiều bốn thần túc, khiến chúng thành như cỗ xe, như nền tảng, kiên trì thực hiện, tích lũy và tinh cần tu tập; vị ấy nếu muốn, có thể sống suốt một kiếp hay phần còn lại của kiếp.",
  "sn51.10:3.3": "'Này Ānanda, Như Lai đã tu tập và thực hành nhiều bốn thần túc, khiến chúng thành như cỗ xe, như nền tảng, kiên trì thực hiện, tích lũy và tinh cần tu tập. Này Ānanda, nếu muốn, Như Lai có thể sống suốt một kiếp hay phần còn lại của kiếp.'",
  "sn51.10:4.1": "Nhưng dù Thế Tôn đã nói những gợi ý rõ ràng, những dấu hiệu rõ ràng như vậy, Tôn giả Ānanda vẫn không thể nhận ra;",
  "sn51.10:4.2": "Ngài không thỉnh cầu Thế Tôn:",
  "sn51.10:4.3": "Bạch Thế Tôn, xin Thế Tôn hãy trụ thế suốt một kiếp, xin Thiện Thệ hãy trụ thế suốt một kiếp, vì lợi ích cho nhiều người, vì hạnh phúc cho nhiều người, vì lòng thương tưởng cho đời, vì lợi ích, vì hạnh phúc, vì an lạc cho chư thiên và loài người.'  vì tâm Ngài bị Māra ám ảnh.",
  "sn51.10:5.1": "Lần thứ hai, Thế Tôn …vv…",
  "sn51.10:5.2": "lần thứ ba, Thế Tôn gọi Tôn giả Ānanda:",
  "sn51.10:5.3": "Này Ānanda, Vesālī thật khả ái, đền Udena thật khả ái, đền Gotamaka thật khả ái, đền Sattamba thật khả ái, đền Bahuputta thật khả ái, đền Sārandada thật khả ái, đền Cāpāla thật khả ái.",
  "sn51.10:5.4": "Này Ānanda, ai đã tu tập và thực hành nhiều bốn thần túc, khiến chúng thành như cỗ xe, như nền tảng, kiên trì thực hiện, tích lũy và tinh cần tu tập; vị ấy nếu muốn, có thể sống suốt một kiếp hay phần còn lại của kiếp.",
  "sn51.10:5.5": "'Này Ānanda, Như Lai đã tu tập và thực hành nhiều bốn thần túc, khiến chúng thành như cỗ xe, như nền tảng, kiên trì thực hiện, tích lũy và tinh cần tu tập. Này Ānanda, nếu muốn, Như Lai có thể sống suốt một kiếp hay phần còn lại của kiếp.'",
  "sn51.10:6.1": "Nhưng dù Thế Tôn đã nói những gợi ý rõ ràng, những dấu hiệu rõ ràng như vậy, Tôn giả Ānanda vẫn không thể nhận ra;",
  "sn51.10:6.2": "Ngài không thỉnh cầu Thế Tôn:",
  "sn51.10:6.3": "Bạch Thế Tôn, xin Thế Tôn hãy trụ thế suốt một kiếp, xin Thiện Thệ hãy trụ thế suốt một kiếp, vì lợi ích cho nhiều người, vì hạnh phúc cho nhiều người, vì lòng thương tưởng cho đời, vì lợi ích, vì hạnh phúc, vì an lạc cho chư thiên và loài người.'  vì tâm Ngài bị Māra ám ảnh.",
  "sn51.10:7.1": "Rồi Thế Tôn gọi Tôn giả Ānanda:",
  "sn51.10:7.2": "Này Ānanda, ngươi hãy đi,",
  "sn51.10:7.3": "'bây giờ là lúc ngươi nên đi.'",
  "sn51.10:7.4": "Thưa vâng, bạch Thế Tôn.' Tôn giả Ānanda vâng đáp, đứng dậy, đảnh lễ Thế Tôn, đi nhiễu bên phải, rồi ngồi xuống dưới một gốc cây không xa.",
  "sn51.10:8.1": "Rồi Māra Ác Ma, không lâu sau khi Tôn giả Ānanda ra đi, đến gặp Thế Tôn; đến nơi, Māra thưa với Thế Tôn:",
  "sn51.10:9.1": "Bạch Thế Tôn, nay xin Thế Tôn hãy nhập Niết-bàn, nay xin Thiện Thệ hãy nhập Niết-bàn. Bạch Thế Tôn, nay đã đến lúc Thế Tôn nhập Niết-bàn.",
  "sn51.10:9.2": "Bạch Thế Tôn, Thế Tôn đã từng nói rằng:",
  "sn51.10:9.3": "'Này Ác Ma, Ta sẽ không nhập Niết-bàn chừng nào các Tỳ Kheo đệ tử của Ta chưa trở thành những người thông thạo, có học, tự tin, uyên bác, thông thuộc Pháp, thực hành đúng Pháp, thực hành thuận Pháp, thực hành theo Pháp, đã học hỏi từ thầy của mình, có thể tuyên bố, giảng dạy, trình bày, thiết lập, khai mở, phân tích, làm rõ ràng, và có thể bác bỏ các luận điểm ngoại đạo bằng Chánh Pháp và giảng dạy Chánh Pháp kỳ diệu.'",
  "sn51.10:10.1": "Bạch Thế Tôn, nay các Tỳ Kheo đệ tử của Thế Tôn đã trở thành những người thông thạo, có học, tự tin, uyên bác, thông thuộc Pháp, thực hành đúng Pháp, thực hành thuận Pháp, thực hành theo Pháp, đã học hỏi từ thầy của mình, tuyên bố, giảng dạy, trình bày, thiết lập, khai mở, phân tích, làm rõ ràng, và có thể bác bỏ các luận điểm ngoại đạo bằng Chánh Pháp và giảng dạy Chánh Pháp kỳ diệu.",
  "sn51.10:10.2": "Bạch Thế Tôn, nay xin Thế Tôn hãy nhập Niết-bàn, nay xin Thiện Thệ hãy nhập Niết-bàn. Bạch Thế Tôn, nay đã đến lúc Thế Tôn nhập Niết-bàn.",
  "sn51.10:11.1": "Bạch Thế Tôn, Thế Tôn đã từng nói rằng:",
  "sn51.10:11.2": "'Này Ác Ma, Ta sẽ không nhập Niết-bàn chừng nào các Tỳ Kheo ni đệ tử của Ta chưa trở thành những người thông thạo, có học, tự tin, uyên bác, thông thuộc Pháp, thực hành đúng Pháp, thực hành thuận Pháp, thực hành theo Pháp, đã học hỏi từ thầy của mình, có thể tuyên bố, giảng dạy, trình bày, thiết lập, khai mở, phân tích, làm rõ ràng, và có thể bác bỏ các luận điểm ngoại đạo bằng Chánh Pháp và giảng dạy Chánh Pháp kỳ diệu.'",
  "sn51.10:12.1": "Bạch Thế Tôn, nay các Tỳ Kheo ni đệ tử của Thế Tôn đã trở thành những người thông thạo, có học, tự tin, uyên bác, thông thuộc Pháp, thực hành đúng Pháp, thực hành thuận Pháp, thực hành theo Pháp, đã học hỏi từ thầy của mình, tuyên bố, giảng dạy, trình bày, thiết lập, khai mở, phân tích, làm rõ ràng, và có thể bác bỏ các luận điểm ngoại đạo bằng Chánh Pháp và giảng dạy Chánh Pháp kỳ diệu.",
  "sn51.10:12.2": "Bạch Thế Tôn, nay xin Thế Tôn hãy nhập Niết-bàn, nay xin Thiện Thệ hãy nhập Niết-bàn. Bạch Thế Tôn, nay đã đến lúc Thế Tôn nhập Niết-bàn.",
  "sn51.10:13.1": "Bạch Thế Tôn, Thế Tôn đã từng nói rằng:",
  "sn51.10:13.2": "'Này Ác Ma, Ta sẽ không nhập Niết-bàn chừng nào các nam cư sĩ đệ tử của Ta …vv…'",
  "sn51.10:13.3": "'chừng nào các nữ cư sĩ đệ tử của Ta chưa trở thành những người thông thạo, có học, tự tin, uyên bác, thông thuộc Pháp, thực hành đúng Pháp, thực hành thuận Pháp, thực hành theo Pháp, đã học hỏi từ thầy của mình, có thể tuyên bố, giảng dạy, trình bày, thiết lập, khai mở, phân tích, làm rõ ràng, và có thể bác bỏ các luận điểm ngoại đạo bằng Chánh Pháp và giảng dạy Chánh Pháp kỳ diệu.'",
  "sn51.10:14.1": "Bạch Thế Tôn, nay các nam cư sĩ đệ tử của Thế Tôn …",
  "sn51.10:14.2": "các nữ cư sĩ đệ tử của Thế Tôn đã trở thành những người thông thạo, có học, tự tin, uyên bác, thông thuộc Pháp, thực hành đúng Pháp, thực hành thuận Pháp, thực hành theo Pháp, đã học hỏi từ thầy của mình, tuyên bố, giảng dạy, trình bày, thiết lập, khai mở, phân tích, làm rõ ràng, và có thể bác bỏ các luận điểm ngoại đạo bằng Chánh Pháp và giảng dạy Chánh Pháp kỳ diệu.",
  "sn51.10:14.3": "Bạch Thế Tôn, nay xin Thế Tôn hãy nhập Niết-bàn, nay xin Thiện Thệ hãy nhập Niết-bàn. Bạch Thế Tôn, nay đã đến lúc Thế Tôn nhập Niết-bàn.",
  "sn51.10:15.1": "Bạch Thế Tôn, Thế Tôn đã từng nói rằng:",
  "sn51.10:15.2": "'Này Ác Ma, Ta sẽ không nhập Niết-bàn chừng nào Phạm hạnh này chưa được thịnh vượng, phát triển, phổ biến rộng rãi, đông đảo, lan rộng, được tuyên bố khéo léo cho đến chư thiên và loài người.'",
  "sn51.10:15.3": "Bạch Thế Tôn, nay Phạm hạnh của Thế Tôn đã được thịnh vượng, phát triển, phổ biến rộng rãi, đông đảo, lan rộng, được tuyên bố khéo léo cho đến chư thiên và loài người.",
  "sn51.10:15.4": "'Bạch Thế Tôn, nay xin Thế Tôn hãy nhập Niết-bàn, nay xin Thiện Thệ hãy nhập Niết-bàn. Bạch Thế Tôn, nay đã đến lúc Thế Tôn nhập Niết-bàn.'",
  "sn51.10:16.1": "Khi được nói vậy, Thế Tôn nói với Māra Ác Ma:",
  "sn51.10:16.2": "Này Ác Ma, chớ lo lắng. Không bao lâu nữa, Như Lai sẽ nhập Niết-bàn.",
  "sn51.10:16.3": "'Sau ba tháng nữa kể từ nay, Như Lai sẽ nhập Niết-bàn.'",
  "sn51.10:17.1": "Rồi Thế Tôn, với chánh niệm và tỉnh giác, tại đền Cāpāla, đã buông bỏ hành thọ mạng.",
  "sn51.10:17.2": "Khi Thế Tôn buông bỏ hành thọ mạng, một trận động đất lớn kinh khiếp, rùng rợn đã xảy ra, và trống chư thiên vang lên.",
  "sn51.10:17.3": "Rồi Thế Tôn, hiểu rõ ý nghĩa này, vào lúc ấy đã thốt lên lời cảm hứng:",
  "sn51.10:18.1": "Bậc Mâu-ni đã từ bỏ hành sanh tồn,",
  "sn51.10:18.2": "cả những hành có thể cân đo và không thể cân đo;",
  "sn51.10:18.3": "nội tâm hỷ lạc, an trú thiền định,",
  "sn51.10:18.4": "'như phá vỡ lớp áo giáp do tự thân tạo ra.'",
  "sn51.10:18.5": "Thứ mười.",
  "sn51.10:18.6": "Phẩm Cāpāla, phẩm thứ nhất.",
  "sn51.10:19.0": "Tóm tắt phẩm:",
  "sn51.10:19.1": "Bờ kia và từ bỏ,",
  "sn51.10:19.2": "Bậc thánh và nhàm chán;",
  "sn51.10:19.3": "Thần thông phần, viên mãn, Tỳ Kheo,",
  "sn51.10:19.4": "Đức Phật, tri kiến và tháp Cāpāla.",
  "sn51.11:0.1": "Tương Ưng Bộ 51.11",
  "sn51.11:0.2": "2. Phẩm Rung Chuyển Tịnh Xá",
  "sn51.11:0.3": "Kinh Trước Giác Ngộ",
  "sn51.11:1.1": "Nhân duyên ở Sāvatthi.",
  "sn51.11:1.2": "Này các Tỳ Kheo, trước khi Ta giác ngộ, khi còn là vị Bồ-tát chưa thành Chánh Đẳng Giác, Ta đã suy nghĩ:",
  "sn51.11:1.3": "'Đâu là nhân, đâu là duyên cho sự tu tập thần túc?'",
  "sn51.11:1.4": "Này các Tỳ Kheo, rồi Ta suy nghĩ:",
  "sn51.11:1.5": "'Ở đây, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành'",
  "sn51.11:1.6": "như vậy, dục của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.11:1.7": "Trú với nhận thức trước sau",
  "sn51.11:1.8": "như trước thì như sau, như sau thì như trước;",
  "sn51.11:1.9": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.11:1.10": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.11:1.11": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng'.",
  "sn51.11:2.1": "Tu tập thần túc câu hữu với định do tinh tấn, cùng với các nỗ lực hành",
  "sn51.11:2.2": "như vậy, tinh tấn của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.11:2.3": "Trú với nhận thức trước sau",
  "sn51.11:2.4": "như trước thì như sau, như sau thì như trước;",
  "sn51.11:2.5": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.11:2.6": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.11:2.7": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.11:3.1": "Tu tập thần túc câu hữu với định do tâm, cùng với các nỗ lực hành",
  "sn51.11:3.2": "như vậy, tâm của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.11:3.3": "Trú với nhận thức trước sau",
  "sn51.11:3.4": "như trước thì như sau, như sau thì như trước;",
  "sn51.11:3.5": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.11:3.6": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.11:3.7": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.11:4.1": "Tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.11:4.2": "như vậy, sự thẩm sát của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.11:4.3": "Trú với nhận thức trước sau",
  "sn51.11:4.4": "như trước thì như sau, như sau thì như trước;",
  "sn51.11:4.5": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.11:4.6": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.11:4.7": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.11:5.1": "Này Tỳ Kheo, khi bốn thần túc đã được tu tập và thực hành nhiều như vậy, vị ấy thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một; hiện ra, biến mất; đi xuyên qua tường, thành lũy, núi non không bị cản trở như đi trong hư không; lặn xuống và trồi lên trong đất như trong nước; đi trên nước không bị chìm như đi trên mặt đất; bay trong hư không kiết già như con chim có cánh; dùng tay sờ mó mặt trăng mặt trời có thần lực, oai đức lớn như vậy; dùng thân thể tự tại cho đến cõi Phạm thiên.",
  "sn51.11:6.1": "Này Tỳ Kheo, khi bốn thần túc đã được tu tập và thực hành nhiều như vậy, vị ấy với thiên nhĩ thanh tịnh, siêu nhân, nghe cả hai loại âm thanhthiên giới và nhân giới, xa và gần.",
  "sn51.11:7.1": "Này Tỳ Kheo, khi bốn thần túc đã được tu tập và thực hành nhiều như vậy, vị ấy dùng tâm của mình thấu suốt tâm của chúng sanh khác, của người khác.",
  "sn51.11:7.2": "Biết rõ tâm có tham là 'tâm có tham';",
  "sn51.11:7.3": "biết rõ tâm không tham là 'tâm không tham';",
  "sn51.11:7.4": "biết rõ tâm có sân là 'tâm có sân';",
  "sn51.11:7.5": "biết rõ tâm không sân là 'tâm không sân';",
  "sn51.11:7.6": "biết rõ tâm có si là 'tâm có si';",
  "sn51.11:7.7": "biết rõ tâm không si là 'tâm không si';",
  "sn51.11:7.8": "biết rõ tâm co rút là 'tâm co rút';",
  "sn51.11:7.9": "biết rõ tâm tán loạn là 'tâm tán loạn';",
  "sn51.11:7.10": "biết rõ tâm đại hành là 'tâm đại hành';",
  "sn51.11:7.11": "biết rõ tâm không đại hành là 'tâm không đại hành';",
  "sn51.11:7.12": "biết rõ tâm có pháp trên là 'tâm có pháp trên';",
  "sn51.11:7.13": "biết rõ tâm vô thượng là 'tâm vô thượng';",
  "sn51.11:7.14": "biết rõ tâm định tĩnh là 'tâm định tĩnh';",
  "sn51.11:7.15": "biết rõ tâm không định tĩnh là 'tâm không định tĩnh';",
  "sn51.11:7.16": "biết rõ tâm giải thoát là 'tâm giải thoát';",
  "sn51.11:7.17": "biết rõ tâm chưa giải thoát là 'tâm chưa giải thoát'.",
  "sn51.11:8.1": "Này Tỳ Kheo, khi bốn thần túc đã được tu tập và thực hành nhiều như vậy, vị ấy nhớ lại nhiều đời sống quá khứ, như: một đời, hai đời, ba đời, bốn đời, năm đời, mười đời, hai mươi đời, ba mươi đời, bốn mươi đời, năm mươi đời, một trăm đời, một nghìn đời, một trăm nghìn đời, nhiều kiếp thành, nhiều kiếp hoại, nhiều kiếp thành và hoại: 'Ở đó Ta có tên như vậy, dòng họ như vậy, màu sắc như vậy, thức ăn như vậy, hưởng thụ lạc khổ như vậy, tuổi thọ như vậy; từ đó mất đi, Ta sanh ra ở chỗ kia; ở đó Ta có tên như vậy, dòng họ như vậy, màu sắc như vậy, thức ăn như vậy, hưởng thụ lạc khổ như vậy, tuổi thọ như vậy; từ đó mất đi, Ta sanh ra ở đây.' Như vậy, vị ấy nhớ lại nhiều đời sống quá khứ cùng với các nét đặc thù và chi tiết.",
  "sn51.11:9.1": "Này Tỳ Kheo, khi bốn thần túc đã được tu tập và thực hành nhiều như vậy, vị ấy với thiên nhãn thanh tịnh, siêu nhân, thấy chúng sanh đang chết đi và tái sanh, tầm thường và cao quý, đẹp đẽ và xấu xí, may mắn và bất hạnh; vị ấy biết rõ chúng sanh đi theo nghiệp của họ: 'Này các bạn, các chúng sanh này có thân ác hạnh, có khẩu ác hạnh, có ý ác hạnh, phỉ báng bậc thánh, có tà kiến, thọ nghiệp tà kiến; sau khi thân hoại mạng chung, họ sanh vào cõi dữ, ác thú, đọa xứ, địa ngục. Còn các chúng sanh kia có thân thiện hạnh, có khẩu thiện hạnh, có ý thiện hạnh, không phỉ báng bậc thánh, có chánh kiến, thọ nghiệp chánh kiến; sau khi thân hoại mạng chung, họ sanh vào thiện thú, cõi trời.' Như vậy, vị ấy với thiên nhãn thanh tịnh, siêu nhân, thấy chúng sanh đang chết đi và tái sanh, tầm thường và cao quý, đẹp đẽ và xấu xí, may mắn và bất hạnh; vị ấy biết rõ chúng sanh đi theo nghiệp của họ.",
  "sn51.11:10.1": "'Này Tỳ Kheo, khi bốn thần túc đã được tu tập và thực hành nhiều như vậy, vị ấy đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú.'",
  "sn51.11:10.2": "Thứ nhất.",
  "sn51.12:0.1": "Tương Ưng Bộ 51.12",
  "sn51.12:0.2": "2. Phẩm Rung Chuyển Tịnh Xá",
  "sn51.12:0.3": "Kinh Quả Lớn",
  "sn51.12:1.1": "Này các Tỳ Kheo, bốn thần túc này, được tu tập, được thực hành nhiều, có quả lớn, có lợi ích lớn.",
  "sn51.12:1.2": "Này các Tỳ Kheo, thế nào là bốn thần túc được tu tập, được thực hành nhiều để có quả lớn, có lợi ích lớn?",
  "sn51.12:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành",
  "sn51.12:1.4": "như vậy, dục của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.12:1.5": "Trú với nhận thức trước sau",
  "sn51.12:1.6": "như trước thì như sau, như sau thì như trước;",
  "sn51.12:1.7": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.12:1.8": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.12:1.9": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.12:2.1": "Định do tinh tấn …vv…",
  "sn51.12:2.2": "định do tâm …",
  "sn51.12:2.3": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.12:2.4": "như vậy, sự thẩm sát của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.12:2.5": "Trú với nhận thức trước sau",
  "sn51.12:2.6": "như trước thì như sau, như sau thì như trước;",
  "sn51.12:2.7": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.12:2.8": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.12:2.9": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.12:2.10": "Này các Tỳ Kheo, được tu tập như vậy, được thực hành nhiều như vậy, bốn thần túc có quả lớn, có lợi ích lớn.",
  "sn51.12:3.1": "Này các Tỳ Kheo, khi Tỳ Kheo đã tu tập và thực hành nhiều bốn thần túc như vậy, vị ấy thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một …vv… dùng thân thể tự tại cho đến cõi Phạm thiên …vv….",
  "sn51.12:4.1": "'Này các Tỳ Kheo, khi Tỳ Kheo đã tu tập và thực hành nhiều bốn thần túc như vậy, vị ấy đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú.'",
  "sn51.12:4.2": "Thứ hai.",
  "sn51.13:0.1": "Tương Ưng Bộ 51.13",
  "sn51.13:0.2": "2. Phẩm Rung Chuyển Tịnh Xá",
  "sn51.13:0.3": "Kinh Định Do Dục",
  "sn51.13:1.1": "Này các Tỳ Kheo, nếu Tỳ Kheo nương vào dục mà đạt được định, đạt được nhất tâm",
  "sn51.13:1.2": "đây được gọi là định do dục.",
  "sn51.13:1.3": "Vị ấy khởi lên ý chí, nỗ lực, tinh tấn, giữ vững tâm và cố gắng để các pháp ác bất thiện chưa sanh không sanh khởi.",
  "sn51.13:1.4": "Vị ấy khởi lên ý chí, nỗ lực, tinh tấn, giữ vững tâm và cố gắng để đoạn trừ các pháp ác bất thiện đã sanh.",
  "sn51.13:1.5": "Vị ấy khởi lên ý chí, nỗ lực, tinh tấn, giữ vững tâm và cố gắng để các thiện pháp chưa sanh được sanh khởi.",
  "sn51.13:1.6": "Vị ấy khởi lên ý chí, nỗ lực, tinh tấn, giữ vững tâm và cố gắng để các thiện pháp đã sanh được duy trì, không bị quên lãng, tăng trưởng, phát triển, tu tập và viên mãn.",
  "sn51.13:1.7": "Đây được gọi là 'các nỗ lực hành'.",
  "sn51.13:1.8": "Như vậy, dục này, định do dục này, và các nỗ lực hành này",
  "sn51.13:1.9": "đây được gọi là, này các Tỳ Kheo, thần túc câu hữu với định do dục, cùng với các nỗ lực hành.",
  "sn51.13:2.1": "Này các Tỳ Kheo, nếu Tỳ Kheo nương vào tinh tấn mà đạt được định, đạt được nhất tâm",
  "sn51.13:2.2": "đây được gọi là 'định do tinh tấn'.",
  "sn51.13:2.3": "Vị ấy khởi lên ý chí …vv…",
  "sn51.13:2.4": "Vị ấy khởi lên ý chí, nỗ lực, tinh tấn, giữ vững tâm và cố gắng để các thiện pháp đã sanh được duy trì, không bị quên lãng, tăng trưởng, phát triển, tu tập và viên mãn.",
  "sn51.13:2.5": "Đây được gọi là 'các nỗ lực hành'.",
  "sn51.13:2.6": "Như vậy, tinh tấn này, định do tinh tấn này, và các nỗ lực hành này",
  "sn51.13:2.7": "đây được gọi là, này các Tỳ Kheo, thần túc câu hữu với định do tinh tấn, cùng với các nỗ lực hành.",
  "sn51.13:3.1": "Này các Tỳ Kheo, nếu Tỳ Kheo nương vào tâm mà đạt được định, đạt được nhất tâm",
  "sn51.13:3.2": "đây được gọi là 'định do tâm'.",
  "sn51.13:3.3": "Vị ấy khởi lên ý chí, nỗ lực đối với các pháp ác bất thiện …vv…",
  "sn51.13:3.4": "Vị ấy khởi lên ý chí, nỗ lực, tinh tấn, giữ vững tâm và cố gắng để các thiện pháp đã sanh được duy trì, không bị quên lãng, tăng trưởng, phát triển, tu tập và viên mãn.",
  "sn51.13:3.5": "Đây được gọi là 'các nỗ lực hành'.",
  "sn51.13:3.6": "Như vậy, tâm này, định do tâm này, và các nỗ lực hành này",
  "sn51.13:3.7": "đây được gọi là, này các Tỳ Kheo, thần túc câu hữu với định do tâm, cùng với các nỗ lực hành.",
  "sn51.13:4.1": "Này các Tỳ Kheo, nếu Tỳ Kheo nương vào sự thẩm sát mà đạt được định, đạt được nhất tâm",
  "sn51.13:4.2": "đây được gọi là 'định do thẩm sát'.",
  "sn51.13:4.3": "Vị ấy khởi lên ý chí, nỗ lực đối với các pháp ác bất thiện chưa sanh để không sanh khởi …vv…",
  "sn51.13:4.4": "Vị ấy khởi lên ý chí, nỗ lực, tinh tấn, giữ vững tâm và cố gắng để các thiện pháp đã sanh được duy trì, không bị quên lãng, tăng trưởng, phát triển, tu tập và viên mãn.",
  "sn51.13:4.5": "Đây được gọi là 'các nỗ lực hành'.",
  "sn51.13:4.6": "Như vậy, sự thẩm sát này, định do thẩm sát này, và các nỗ lực hành này",
  "sn51.13:4.7": "'đây được gọi là, này các Tỳ Kheo, thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.'",
  "sn51.13:4.8": "Thứ ba.",
  "sn51.14:0.1": "Tương Ưng Bộ 51.14",
  "sn51.14:0.2": "2. Phẩm Rung Chuyển Tịnh Xá",
  "sn51.14:0.3": "Kinh Moggallāna",
  "sn51.14:1.1": "Tôi nghe như vầy",
  "sn51.14:1.2": "một thời, Thế Tôn trú ở Sāvatthi, tại Đông Viên, giảng đường của Migāramātā.",
  "sn51.14:1.3": "Bấy giờ, có nhiều Tỳ Kheo đang trú ở tầng dưới của giảng đường Migāramātā, kiêu ngạo, ngã mạn, phóng túng, lắm chuyện, nói nhiều lời thừa, thất niệm, không tỉnh giác, không định tĩnh, tâm tán loạn, các căn không thu thúc.",
  "sn51.14:2.1": "Rồi Thế Tôn gọi Tôn giả Mahāmoggallāna:",
  "sn51.14:2.2": "Này Moggallāna, các đồng Phạm hạnh kia đang trú ở tầng dưới của giảng đường Migāramātā, kiêu ngạo, ngã mạn, phóng túng, lắm chuyện, nói nhiều lời thừa, thất niệm, không tỉnh giác, không định tĩnh, tâm tán loạn, các căn không thu thúc.",
  "sn51.14:2.3": "'Này Moggallāna, hãy đến và làm cho các Tỳ Kheo ấy khởi tâm thán sợ.'",
  "sn51.14:3.1": "Thưa vâng, bạch Thế Tôn.' Tôn giả Mahāmoggallāna vâng đáp, rồi dùng thần lực ấy tập hợp lại đến mức dùng ngón chân cái làm cho giảng đường Migāramātā rung chuyển, chấn động, rúng động.",
  "sn51.14:3.2": "Rồi các Tỳ Kheo ấy kinh hãi, lông tóc dựng đứng, đứng một bên:",
  "sn51.14:3.3": "Thật kỳ diệu thay, thật hy hữu thay!",
  "sn51.14:3.4": "'Giảng đường Migāramātā này sâu nền vững chắc, kiên cố, bất động, không thể rúng động, vậy mà đã bị rung chuyển, chấn động, rúng động.'",
  "sn51.14:4.1": "Rồi Thế Tôn đến chỗ các Tỳ Kheo ấy; đến nơi, Ngài nói với họ:",
  "sn51.14:4.2": "'Này các Tỳ Kheo, sao các ông kinh hãi, lông tóc dựng đứng, đứng một bên?'",
  "sn51.14:4.3": "Bạch Thế Tôn, thật kỳ diệu, thật hy hữu!",
  "sn51.14:4.4": "'Giảng đường Migāramātā này sâu nền vững chắc, kiên cố, bất động, không thể rúng động, vậy mà đã bị rung chuyển, chấn động, rúng động.'",
  "sn51.14:4.5": "Chính Tỳ Kheo Moggallāna, muốn làm cho các ông khởi tâm thán sợ, đã dùng ngón chân cái làm cho giảng đường Migāramātā rung chuyển, chấn động, rúng động.",
  "sn51.14:4.6": "Này các Tỳ Kheo, các ông nghĩ thế nào,",
  "sn51.14:4.7": "'do tu tập và thực hành nhiều pháp nào mà Tỳ Kheo Moggallāna có thần lực lớn, oai đức lớn như vậy?'",
  "sn51.14:4.8": "'Bạch Thế Tôn, chúng con lấy Thế Tôn làm căn bản, lấy Thế Tôn làm người dẫn đạo, lấy Thế Tôn làm chỗ nương tựa. Lành thay, bạch Thế Tôn, xin Thế Tôn tự giải thích ý nghĩa của lời nói ấy. Các Tỳ Kheo nghe Thế Tôn nói sẽ ghi nhớ.'",
  "sn51.14:5.1": "Vậy thì, này các Tỳ Kheo, hãy lắng nghe.",
  "sn51.14:5.2": "Chính do tu tập và thực hành nhiều bốn thần túc mà Tỳ Kheo Moggallāna có thần lực lớn, oai đức lớn như vậy.",
  "sn51.14:5.3": "Thế nào là bốn?",
  "sn51.14:5.4": "Ở đây, này các Tỳ Kheo, Tỳ Kheo Moggallāna tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.14:5.5": "định do tinh tấn …vv…",
  "sn51.14:5.6": "định do tâm …",
  "sn51.14:5.7": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.14:5.8": "như vậy, sự thẩm sát của Ta sẽ không bị uể oải, không bị phấn khích thái quá;",
  "sn51.14:5.9": "không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.14:5.10": "Trú với nhận thức trước sau",
  "sn51.14:5.11": "như trước thì như sau, như sau thì như trước;",
  "sn51.14:5.12": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.14:5.13": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.14:5.14": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.14:5.15": "Này các Tỳ Kheo, chính do tu tập và thực hành nhiều bốn thần túc này mà Tỳ Kheo Moggallāna có thần lực lớn, oai đức lớn như vậy.",
  "sn51.14:5.16": "Này các Tỳ Kheo, chính do tu tập và thực hành nhiều bốn thần túc này mà Tỳ Kheo Moggallāna thể hiện nhiều loại thần thông …vv… dùng thân thể tự tại cho đến cõi Phạm thiên …vv…",
  "sn51.14:5.17": "'Này các Tỳ Kheo, chính do tu tập và thực hành nhiều bốn thần túc này mà Tỳ Kheo Moggallāna đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú.'",
  "sn51.14:5.18": "Thứ tư.",
  "sn51.15:0.1": "Tương Ưng Bộ 51.15",
  "sn51.15:0.2": "2. Phẩm Rung Chuyển Tịnh Xá",
  "sn51.15:0.3": "Kinh Bà-la-môn Uṇṇābha",
  "sn51.15:1.1": "Tôi nghe như vầy",
  "sn51.15:1.2": "một thời, Tôn giả Ānanda trú ở Kosambi, tại Ghosita viên.",
  "sn51.15:1.3": "Rồi Bà-la-môn Uṇṇābha đến chỗ Tôn giả Ānanda; đến nơi, ông chào hỏi thân thiện với Tôn giả Ānanda.",
  "sn51.15:1.4": "Sau khi trao đổi những lời thăm hỏi thân thiện và đáng ghi nhớ, ông ngồi xuống một bên. Ngồi xuống một bên, Bà-la-môn Uṇṇābha nói với Tôn giả Ānanda:",
  "sn51.15:1.5": "'Thưa Tôn giả Ānanda, vì mục đích gì mà Phạm hạnh được sống dưới Sa-môn Gotama?'",
  "sn51.15:1.6": "'Thưa Bà-la-môn, Phạm hạnh được sống dưới Thế Tôn vì mục đích đoạn trừ dục.'",
  "sn51.15:2.1": "'Thưa Tôn giả Ānanda, có con đường, có lối thực hành nào để đoạn trừ dục ấy không?'",
  "sn51.15:2.2": "'Thưa Bà-la-môn, có con đường, có lối thực hành để đoạn trừ dục ấy.'",
  "sn51.15:3.1": "'Thưa Tôn giả Ānanda, đâu là con đường, đâu là lối thực hành để đoạn trừ dục ấy?'",
  "sn51.15:3.2": "Thưa Bà-la-môn, ở đây Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.15:3.3": "định do tinh tấn …vv…",
  "sn51.15:3.4": "định do tâm …",
  "sn51.15:3.5": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.15:3.6": "'thưa Bà-la-môn, đây là con đường, đây là lối thực hành để đoạn trừ dục ấy.'",
  "sn51.15:4.1": "Thưa Tôn giả Ānanda, như vậy thì điều này là điều không thể, không phải điều có thể.",
  "sn51.15:4.2": "'Muốn đoạn trừ dục bằng chính dụcđiều này không thể xảy ra.'",
  "sn51.15:4.3": "Vậy thì, thưa Bà-la-môn, tôi sẽ hỏi lại ông về điều này. Ông hãy trả lời tùy ý.",
  "sn51.15:4.4": "Ông nghĩ thế nào, thưa Bà-la-môn,",
  "sn51.15:4.5": "trước đây ông có dục muốn đến vườn không?",
  "sn51.15:4.6": "'Khi ông đã đến vườn, dục muốn đến vườn ấy của ông đã lắng xuống chưa?'",
  "sn51.15:4.7": "'Thưa vâng, thưa Tôn giả.'",
  "sn51.15:4.8": "Trước đây ông có tinh tấn muốn đến vườn không?",
  "sn51.15:4.9": "'Khi ông đã đến vườn, tinh tấn muốn đến vườn ấy của ông đã lắng xuống chưa?'",
  "sn51.15:4.10": "'Thưa vâng, thưa Tôn giả.'",
  "sn51.15:4.11": "Trước đây ông có tâm muốn đến vườn không?",
  "sn51.15:4.12": "'Khi ông đã đến vườn, tâm muốn đến vườn ấy của ông đã lắng xuống chưa?'",
  "sn51.15:4.13": "'Thưa vâng, thưa Tôn giả.'",
  "sn51.15:4.14": "Trước đây ông có sự thẩm sát muốn đến vườn không?",
  "sn51.15:4.15": "'Khi ông đã đến vườn, sự thẩm sát muốn đến vườn ấy của ông đã lắng xuống chưa?'",
  "sn51.15:4.16": "'Thưa vâng, thưa Tôn giả.'",
  "sn51.15:5.1": "Cũng vậy, thưa Bà-la-môn, vị Tỳ Kheo là bậc A-la-hán, đã đoạn tận các lậu hoặc, đã sống đời Phạm hạnh, đã làm những gì cần làm, đã đặt gánh nặng xuống, đã đạt được mục đích tối thượng của mình, đã đoạn tận hữu kiết sử, đã giải thoát bằng chánh trí; dục trước đây của vị ấy để đạt A-la-hán quả, khi đã đạt A-la-hán quả, dục ấy đã lắng xuống;",
  "sn51.15:5.2": "tinh tấn trước đây của vị ấy để đạt A-la-hán quả, khi đã đạt A-la-hán quả, tinh tấn ấy đã lắng xuống;",
  "sn51.15:5.3": "tâm trước đây của vị ấy để đạt A-la-hán quả, khi đã đạt A-la-hán quả, tâm ấy đã lắng xuống;",
  "sn51.15:5.4": "sự thẩm sát trước đây của vị ấy để đạt A-la-hán quả, khi đã đạt A-la-hán quả, sự thẩm sát ấy đã lắng xuống.",
  "sn51.15:5.5": "Ông nghĩ thế nào, thưa Bà-la-môn,",
  "sn51.15:5.6": "'như vậy thì đây là điều có thể hay điều không thể?'",
  "sn51.15:6.1": "Chắc chắn rồi, thưa Tôn giả Ānanda, như vậy thì đây là điều có thể, không phải điều không thể.",
  "sn51.15:6.2": "Tuyệt vời, thưa Tôn giả Ānanda! Tuyệt vời, thưa Tôn giả Ānanda!",
  "sn51.15:6.3": "Thưa Tôn giả Ānanda, ví như người ta dựng lại cái gì bị đổ ngã, mở ra cái gì bị che kín, chỉ đường cho người lạc lối, thắp đèn trong bóng tối để những ai có mắt có thể thấy hình sắc; cũng vậy, Chánh Pháp đã được Tôn giả Ānanda trình bày bằng nhiều phương thức.",
  "sn51.15:6.4": "Con xin quy y Tôn giả Gotama ấy, quy y Pháp, quy y Tỳ Kheo Tăng.",
  "sn51.15:6.5": "'Mong Tôn giả Ānanda nhận con làm cư sĩ, kể từ hôm nay cho đến trọn đời quy y.'",
  "sn51.15:6.6": "Thứ năm.",
  "sn51.16:0.1": "Tương Ưng Bộ 51.16",
  "sn51.16:0.2": "2. Phẩm Rung Chuyển Tịnh Xá",
  "sn51.16:0.3": "Kinh Sa-môn Bà-la-môn Thứ Nhất",
  "sn51.16:1.1": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong quá khứ có thần lực lớn, oai đức lớn, tất cả đều do đã tu tập và thực hành nhiều bốn thần túc.",
  "sn51.16:1.2": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong tương lai có thần lực lớn, oai đức lớn, tất cả đều do tu tập và thực hành nhiều bốn thần túc.",
  "sn51.16:1.3": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong hiện tại có thần lực lớn, oai đức lớn, tất cả đều do tu tập và thực hành nhiều bốn thần túc.",
  "sn51.16:2.1": "Thế nào là bốn?",
  "sn51.16:2.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.16:2.3": "định do tinh tấn …vv…",
  "sn51.16:2.4": "định do tâm …",
  "sn51.16:2.5": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.16:2.6": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong quá khứ có thần lực lớn, oai đức lớn, tất cả đều do đã tu tập và thực hành nhiều bốn thần túc này.",
  "sn51.16:2.7": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong tương lai có thần lực lớn, oai đức lớn, tất cả đều do tu tập và thực hành nhiều bốn thần túc này.",
  "sn51.16:2.8": "'Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong hiện tại có thần lực lớn, oai đức lớn, tất cả đều do tu tập và thực hành nhiều bốn thần túc này.'",
  "sn51.16:2.9": "Thứ sáu.",
  "sn51.17:0.1": "Tương Ưng Bộ 51.17",
  "sn51.17:0.2": "2. Phẩm Rung Chuyển Tịnh Xá",
  "sn51.17:0.3": "Kinh Sa-môn Bà-la-môn Thứ Hai",
  "sn51.17:1.1": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong quá khứ đã thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một; hiện ra, biến mất; đi xuyên qua tường, thành lũy, núi non không bị cản trở như đi trong hư không; lặn xuống và trồi lên trong đất như trong nước; đi trên nước không bị chìm như đi trên mặt đất; bay trong hư không kiết già như con chim có cánh; dùng tay sờ mó mặt trăng mặt trời có thần lực, oai đức lớn; dùng thân thể tự tại cho đến cõi Phạm thiên,",
  "sn51.17:1.2": "tất cả đều do đã tu tập và thực hành nhiều bốn thần túc.",
  "sn51.17:2.1": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong tương lai sẽ thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một; hiện ra, biến mất; đi xuyên qua tường, thành lũy, núi non không bị cản trở như đi trong hư không; lặn xuống và trồi lên trong đất như trong nước; đi trên nước không bị chìm như đi trên mặt đất; bay trong hư không kiết già như con chim có cánh; dùng tay sờ mó mặt trăng mặt trời có thần lực, oai đức lớn; dùng thân thể tự tại cho đến cõi Phạm thiên,",
  "sn51.17:2.2": "tất cả đều do tu tập và thực hành nhiều bốn thần túc.",
  "sn51.17:3.1": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong hiện tại đang thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một; hiện ra, biến mất; đi xuyên qua tường, thành lũy, núi non không bị cản trở như đi trong hư không; lặn xuống và trồi lên trong đất như trong nước; đi trên nước không bị chìm như đi trên mặt đất; bay trong hư không kiết già như con chim có cánh; dùng tay sờ mó mặt trăng mặt trời có thần lực, oai đức lớn; dùng thân thể tự tại cho đến cõi Phạm thiên,",
  "sn51.17:3.2": "tất cả đều do tu tập và thực hành nhiều bốn thần túc.",
  "sn51.17:4.1": "Thế nào là bốn?",
  "sn51.17:4.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.17:4.3": "định do tinh tấn …vv…",
  "sn51.17:4.4": "định do tâm …",
  "sn51.17:4.5": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.17:4.6": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong quá khứ đã thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một …vv… dùng thân thể tự tại cho đến cõi Phạm thiên,",
  "sn51.17:4.7": "tất cả đều do đã tu tập và thực hành nhiều bốn thần túc này.",
  "sn51.17:5.1": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong tương lai sẽ thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một …vv… dùng thân thể tự tại cho đến cõi Phạm thiên,",
  "sn51.17:5.2": "tất cả đều do tu tập và thực hành nhiều bốn thần túc này.",
  "sn51.17:6.1": "Này các Tỳ Kheo, bất kỳ Sa-môn hay Bà-la-môn nào trong hiện tại đang thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một …vv… dùng thân thể tự tại cho đến cõi Phạm thiên,",
  "sn51.17:6.2": "'tất cả đều do tu tập và thực hành nhiều bốn thần túc này.'",
  "sn51.17:6.3": "Thứ bảy.",
  "sn51.18:0.1": "Tương Ưng Bộ 51.18",
  "sn51.18:0.2": "2. Phẩm Rung Chuyển Tịnh Xá",
  "sn51.18:0.3": "Kinh Tỳ Kheo",
  "sn51.18:1.1": "Này các Tỳ Kheo, do tu tập và thực hành nhiều bốn thần túc, Tỳ Kheo đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú.",
  "sn51.18:2.1": "Thế nào là bốn?",
  "sn51.18:2.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.18:2.3": "định do tinh tấn …vv…",
  "sn51.18:2.4": "định do tâm …",
  "sn51.18:2.5": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.18:2.6": "'Này các Tỳ Kheo, chính do tu tập và thực hành nhiều bốn thần túc này, Tỳ Kheo đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú.'",
  "sn51.18:2.7": "Thứ tám.",
  "sn51.19:0.1": "Tương Ưng Bộ 51.19",
  "sn51.19:0.2": "2. Phẩm Rung Chuyển Tịnh Xá",
  "sn51.19:0.3": "Kinh Giảng Dạy Về Thần Thông v.v.",
  "sn51.19:1.1": "Này các Tỳ Kheo, Ta sẽ giảng cho các ông về thần thông, về thần túc, về sự tu tập thần túc, và về con đường thực hành đưa đến tu tập thần túc.",
  "sn51.19:1.2": "Hãy lắng nghe.",
  "sn51.19:2.1": "Này các Tỳ Kheo, thế nào là thần thông?",
  "sn51.19:2.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một …vv… dùng thân thể tự tại cho đến cõi Phạm thiên",
  "sn51.19:2.3": "này các Tỳ Kheo, đây được gọi là thần thông.",
  "sn51.19:3.1": "Này các Tỳ Kheo, thế nào là thần túc?",
  "sn51.19:3.2": "Này các Tỳ Kheo, con đường, lối thực hành đưa đến sự đạt được thần thông, sự thành tựu thần thông",
  "sn51.19:3.3": "này các Tỳ Kheo, đây được gọi là thần túc.",
  "sn51.19:4.1": "Này các Tỳ Kheo, thế nào là sự tu tập thần túc?",
  "sn51.19:4.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.19:4.3": "định do tinh tấn …vv…",
  "sn51.19:4.4": "định do tâm …",
  "sn51.19:4.5": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.19:4.6": "này các Tỳ Kheo, đây được gọi là sự tu tập thần túc.",
  "sn51.19:5.1": "Này các Tỳ Kheo, thế nào là con đường thực hành đưa đến tu tập thần túc?",
  "sn51.19:5.2": "Chính là Thánh đạo tám chi phần này, tức là",
  "sn51.19:5.3": "Chánh kiến, Chánh tư duy, Chánh ngữ, Chánh nghiệp, Chánh mạng, Chánh tinh tấn, Chánh niệm, Chánh định",
  "sn51.19:5.4": "'này các Tỳ Kheo, đây được gọi là con đường thực hành đưa đến tu tập thần túc.'",
  "sn51.19:5.5": "Thứ chín.",
  "sn51.20:0.1": "Tương Ưng Bộ 51.20",
  "sn51.20:0.2": "2. Phẩm Rung Chuyển Tịnh Xá",
  "sn51.20:0.3": "Kinh Phân Tích",
  "sn51.20:1.1": "'Này các Tỳ Kheo, bốn thần túc này, được tu tập, được thực hành nhiều, có quả lớn, có lợi ích lớn.'",
  "sn51.20:2.1": "Này các Tỳ Kheo, thế nào là bốn thần túc được tu tập, được thực hành nhiều để có quả lớn, có lợi ích lớn?",
  "sn51.20:2.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành",
  "sn51.20:2.3": "như vậy, dục của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.20:2.4": "Trú với nhận thức trước sau",
  "sn51.20:2.5": "như trước thì như sau, như sau thì như trước;",
  "sn51.20:2.6": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.20:2.7": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.20:2.8": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.20:2.9": "Định do tinh tấn …vv…",
  "sn51.20:2.10": "định do tâm …",
  "sn51.20:2.11": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.20:2.12": "như vậy, sự thẩm sát của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.20:2.13": "Trú với nhận thức trước sau",
  "sn51.20:2.14": "như trước thì như sau, như sau thì như trước;",
  "sn51.20:2.15": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.20:2.16": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.20:2.17": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.20:3.1": "Này các Tỳ Kheo, thế nào là dục bị uể oải?",
  "sn51.20:3.2": "Này các Tỳ Kheo, dục câu hữu với hôn trầm, tương ưng với hôn trầm",
  "sn51.20:3.3": "này các Tỳ Kheo, đây được gọi là dục bị uể oải.",
  "sn51.20:4.1": "Này các Tỳ Kheo, thế nào là dục bị phấn khích thái quá?",
  "sn51.20:4.2": "Này các Tỳ Kheo, dục câu hữu với trạo cử, tương ưng với trạo cử",
  "sn51.20:4.3": "này các Tỳ Kheo, đây được gọi là dục bị phấn khích thái quá.",
  "sn51.20:5.1": "Này các Tỳ Kheo, thế nào là dục bị co rút vào trong?",
  "sn51.20:5.2": "Này các Tỳ Kheo, dục câu hữu với hôn thụy, tương ưng với hôn thụy",
  "sn51.20:5.3": "này các Tỳ Kheo, đây được gọi là dục bị co rút vào trong.",
  "sn51.20:6.1": "Này các Tỳ Kheo, thế nào là dục bị tán loạn ra ngoài?",
  "sn51.20:6.2": "Này các Tỳ Kheo, dục bị tán loạn, bị phân tán ra ngoài đối với năm dục trưởng dưỡng",
  "sn51.20:6.3": "này các Tỳ Kheo, đây được gọi là dục bị tán loạn ra ngoài.",
  "sn51.20:7.1": "Này các Tỳ Kheo, thế nào là Tỳ Kheo trú với nhận thức trước sau",
  "sn51.20:7.2": "như trước thì như sau, như sau thì như trước?",
  "sn51.20:7.3": "Ở đây, này các Tỳ Kheo, nhận thức trước sau của Tỳ Kheo được nắm giữ khéo léo, được tư duy khéo léo, được duy trì khéo léo, được thấu triệt khéo léo bằng tuệ.",
  "sn51.20:7.4": "Này các Tỳ Kheo, như vậy Tỳ Kheo trú với nhận thức trước sau",
  "sn51.20:7.5": "như trước thì như sau, như sau thì như trước.",
  "sn51.20:8.1": "Này các Tỳ Kheo, thế nào là Tỳ Kheo trú như dưới thì như trên, như trên thì như dưới?",
  "sn51.20:8.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo quán sát thân này từ bàn chân trở lên, từ đỉnh đầu trở xuống, bao bọc bởi da, đầy những thứ bất tịnh đủ loại:",
  "sn51.20:8.3": "'Trong thân này có tóc, lông, móng, răng, da, thịt, gân, xương, tủy, thận, tim, gan, màng phổi, lá lách, phổi, ruột già, ruột non, dạ dày, phân, mật, đờm, mủ, máu, mồ hôi, mỡ, nước mắt, mỡ da, nước miếng, chất nhầy, chất bôi trơn khớp, nước tiểu.'",
  "sn51.20:8.4": "Này các Tỳ Kheo, như vậy Tỳ Kheo trú như dưới thì như trên, như trên thì như dưới.",
  "sn51.20:9.1": "Này các Tỳ Kheo, thế nào là Tỳ Kheo trú như ban ngày thì như ban đêm, như ban đêm thì như ban ngày?",
  "sn51.20:9.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo với những tướng, những đặc điểm, những dấu hiệu nào mà ban ngày tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành, thì ban đêm cũng với những tướng, những đặc điểm, những dấu hiệu ấy tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành;",
  "sn51.20:9.3": "và với những tướng, những đặc điểm, những dấu hiệu nào mà ban đêm tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành, thì ban ngày cũng với những tướng, những đặc điểm, những dấu hiệu ấy tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành.",
  "sn51.20:9.4": "Này các Tỳ Kheo, như vậy Tỳ Kheo trú như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.20:10.1": "Này các Tỳ Kheo, thế nào là Tỳ Kheo với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng?",
  "sn51.20:10.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo có nhận thức ánh sáng được nắm giữ khéo léo, có nhận thức ban ngày được thiết lập vững chắc.",
  "sn51.20:10.3": "Này các Tỳ Kheo, như vậy Tỳ Kheo với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.20:11.1": "Này các Tỳ Kheo, thế nào là tinh tấn bị uể oải?",
  "sn51.20:11.2": "Này các Tỳ Kheo, tinh tấn câu hữu với hôn trầm, tương ưng với hôn trầm",
  "sn51.20:11.3": "này được gọi là, này các Tỳ Kheo, tinh tấn bị uể oải.",
  "sn51.20:12.1": "Này các Tỳ Kheo, thế nào là tinh tấn bị phấn khích thái quá?",
  "sn51.20:12.2": "Này các Tỳ Kheo, tinh tấn câu hữu với trạo cử, tương ưng với trạo cử",
  "sn51.20:12.3": "này được gọi là, này các Tỳ Kheo, tinh tấn bị phấn khích thái quá.",
  "sn51.20:13.1": "Này các Tỳ Kheo, thế nào là tinh tấn bị co rút vào trong?",
  "sn51.20:13.2": "Này các Tỳ Kheo, tinh tấn câu hữu với hôn thụy, tương ưng với hôn thụy",
  "sn51.20:13.3": "này được gọi là, này các Tỳ Kheo, tinh tấn bị co rút vào trong.",
  "sn51.20:14.1": "Này các Tỳ Kheo, thế nào là tinh tấn bị tán loạn ra ngoài?",
  "sn51.20:14.2": "Này các Tỳ Kheo, tinh tấn bị tán loạn, bị phân tán ra ngoài đối với năm dục trưởng dưỡngnày được gọi là, này các Tỳ Kheo, tinh tấn bị tán loạn ra ngoài …vv….",
  "sn51.20:15.1": "Này các Tỳ Kheo, thế nào là Tỳ Kheo với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng?",
  "sn51.20:15.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo có nhận thức ánh sáng được nắm giữ khéo léo, có nhận thức ban ngày được thiết lập vững chắc.",
  "sn51.20:15.3": "Này các Tỳ Kheo, như vậy Tỳ Kheo với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.20:16.1": "Này các Tỳ Kheo, thế nào là tâm bị uể oải?",
  "sn51.20:16.2": "Này các Tỳ Kheo, tâm câu hữu với hôn trầm, tương ưng với hôn trầm",
  "sn51.20:16.3": "này được gọi là, này các Tỳ Kheo, tâm bị uể oải.",
  "sn51.20:17.1": "Này các Tỳ Kheo, thế nào là tâm bị phấn khích thái quá?",
  "sn51.20:17.2": "Này các Tỳ Kheo, tâm câu hữu với trạo cử, tương ưng với trạo cử",
  "sn51.20:17.3": "này được gọi là, này các Tỳ Kheo, tâm bị phấn khích thái quá.",
  "sn51.20:18.1": "Này các Tỳ Kheo, thế nào là tâm bị co rút vào trong?",
  "sn51.20:18.2": "Này các Tỳ Kheo, tâm câu hữu với hôn thụy, tương ưng với hôn thụy",
  "sn51.20:18.3": "này được gọi là, này các Tỳ Kheo, tâm bị co rút vào trong.",
  "sn51.20:19.1": "Này các Tỳ Kheo, thế nào là tâm bị tán loạn ra ngoài?",
  "sn51.20:19.2": "Này các Tỳ Kheo, tâm bị tán loạn, bị phân tán ra ngoài đối với năm dục trưởng dưỡng",
  "sn51.20:19.3": "này được gọi là, này các Tỳ Kheo, tâm bị tán loạn ra ngoài …vv…",
  "sn51.20:19.4": "này các Tỳ Kheo, như vậy Tỳ Kheo với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.20:20.1": "Này các Tỳ Kheo, thế nào là sự thẩm sát bị uể oải?",
  "sn51.20:20.2": "Này các Tỳ Kheo, sự thẩm sát câu hữu với hôn trầm, tương ưng với hôn trầm",
  "sn51.20:20.3": "này được gọi là, này các Tỳ Kheo, sự thẩm sát bị uể oải.",
  "sn51.20:21.1": "Này các Tỳ Kheo, thế nào là sự thẩm sát bị phấn khích thái quá?",
  "sn51.20:21.2": "Này các Tỳ Kheo, sự thẩm sát câu hữu với trạo cử, tương ưng với trạo cử",
  "sn51.20:21.3": "này được gọi là, này các Tỳ Kheo, sự thẩm sát bị phấn khích thái quá.",
  "sn51.20:22.1": "Này các Tỳ Kheo, thế nào là sự thẩm sát bị co rút vào trong?",
  "sn51.20:22.2": "Này các Tỳ Kheo, sự thẩm sát câu hữu với hôn thụy, tương ưng với hôn thụy",
  "sn51.20:22.3": "này được gọi là, này các Tỳ Kheo, sự thẩm sát bị co rút vào trong.",
  "sn51.20:23.1": "Này các Tỳ Kheo, thế nào là sự thẩm sát bị tán loạn ra ngoài?",
  "sn51.20:23.2": "Này các Tỳ Kheo, sự thẩm sát bị tán loạn, bị phân tán ra ngoài đối với năm dục trưởng dưỡng",
  "sn51.20:23.3": "này được gọi là, này các Tỳ Kheo, sự thẩm sát bị tán loạn ra ngoài …vv…",
  "sn51.20:23.4": "này các Tỳ Kheo, như vậy Tỳ Kheo với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.20:23.5": "Này các Tỳ Kheo, được tu tập như vậy, được thực hành nhiều như vậy, bốn thần túc có quả lớn, có lợi ích lớn.",
  "sn51.20:24.1": "Này các Tỳ Kheo, khi Tỳ Kheo đã tu tập và thực hành nhiều bốn thần túc như vậy, vị ấy thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một …vv… dùng thân thể tự tại cho đến cõi Phạm thiên.",
  "sn51.20:24.2": "'Này các Tỳ Kheo, khi Tỳ Kheo đã tu tập và thực hành nhiều bốn thần túc như vậy, vị ấy đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú.'",
  "sn51.20:24.3": "Thứ mười.",
  "sn51.20:24.4": "Phẩm Rung Chuyển Tịnh Xá, phẩm thứ hai.",
  "sn51.20:25.0": "Tóm tắt phẩm:",
  "sn51.20:25.1": "Trước giác ngộ, quả lớn, dục,",
  "sn51.20:25.2": "Moggallāna và Uṇṇābha;",
  "sn51.20:25.3": "Hai Sa-môn Bà-la-môn, Tỳ Kheo,",
  "sn51.20:25.4": "Giảng dạy và phân tích vậy.",
  "sn51.21:0.1": "Tương Ưng Bộ 51.21",
  "sn51.21:0.2": "3. Phẩm Cục Sắt",
  "sn51.21:0.3": "Kinh Con Đường",
  "sn51.21:1.1": "Nhân duyên ở Sāvatthi.",
  "sn51.21:1.2": "Này các Tỳ Kheo, trước khi Ta giác ngộ, khi còn là vị Bồ-tát chưa thành Chánh Đẳng Giác, Ta đã suy nghĩ:",
  "sn51.21:1.3": "'Đâu là con đường, đâu là lối thực hành cho sự tu tập thần túc?'",
  "sn51.21:1.4": "Này các Tỳ Kheo, rồi Ta suy nghĩ:",
  "sn51.21:1.5": "'Ở đây, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành'",
  "sn51.21:1.6": "như vậy, dục của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.21:1.7": "Trú với nhận thức trước sau",
  "sn51.21:1.8": "như trước thì như sau, như sau thì như trước;",
  "sn51.21:1.9": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.21:1.10": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.21:1.11": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.21:1.12": "Định do tinh tấn …vv…",
  "sn51.21:1.13": "định do tâm …",
  "sn51.21:1.14": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.21:1.15": "như vậy, sự thẩm sát của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.21:1.16": "Trú với nhận thức trước sau",
  "sn51.21:1.17": "như trước thì như sau, như sau thì như trước;",
  "sn51.21:1.18": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.21:1.19": "'như ban ngày thì như ban đêm, như ban đêm thì như ban ngày'",
  "sn51.21:1.20": "như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.21:2.1": "Này các Tỳ Kheo, khi Tỳ Kheo đã tu tập và thực hành nhiều bốn thần túc như vậy, vị ấy thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một …vv… dùng thân thể tự tại cho đến cõi Phạm thiên.",
  "sn51.21:2.2": "'Này các Tỳ Kheo, khi Tỳ Kheo đã tu tập và thực hành nhiều bốn thần túc như vậy, vị ấy đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú.'",
  "sn51.21:2.3": "Thứ nhất.",
  "sn51.21:2.4": "(Sáu thắng trí cần được trình bày đầy đủ.)",
  "sn51.22:0.1": "Tương Ưng Bộ 51.22",
  "sn51.22:0.2": "3. Phẩm Cục Sắt",
  "sn51.22:0.3": "Kinh Cục Sắt",
  "sn51.22:1.1": "Nhân duyên ở Sāvatthi.",
  "sn51.22:1.2": "Rồi Tôn giả Ānanda đến chỗ Thế Tôn; đến nơi, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Ānanda thưa với Thế Tôn:",
  "sn51.22:1.3": "'Bạch Thế Tôn, Thế Tôn có nhớ lại việc đã đến cõi Phạm thiên bằng thần lực với thân do tâm tạo không?'",
  "sn51.22:1.4": "'Này Ānanda, Ta nhớ lại việc đã đến cõi Phạm thiên bằng thần lực với thân do tâm tạo.'",
  "sn51.22:1.5": "'Bạch Thế Tôn, Thế Tôn có nhớ lại việc đã đến cõi Phạm thiên bằng thần lực với thân tứ đại này không?'",
  "sn51.22:1.6": "'Này Ānanda, Ta nhớ lại việc đã đến cõi Phạm thiên bằng thần lực với thân tứ đại này.'",
  "sn51.22:2.1": "'Bạch Thế Tôn, điều Thế Tôn biếtrằng đã đến cõi Phạm thiên bằng thần lực với thân do tâm tạo, và điều Thế Tôn biếtrằng đã đến cõi Phạm thiên bằng thần lực với thân tứ đại nàyđiều này, bạch Thế Tôn, thật kỳ diệu và hy hữu đối với Thế Tôn.'",
  "sn51.22:2.2": "Này Ānanda, các Như Lai thật kỳ diệu và câu hữu với pháp kỳ diệu, thật hy hữu và câu hữu với pháp hy hữu.",
  "sn51.22:3.1": "Này Ānanda, trong thời điểm mà Như Lai thu nhiếp thân vào tâm và tâm vào thân, trú nhập vào thân với nhận thức hỷ lạc và nhận thức nhẹ nhàng;",
  "sn51.22:3.2": "này Ānanda, vào thời điểm đó thân của Như Lai trở nên nhẹ hơn, mềm mại hơn, dễ vận dụng hơn và sáng trong hơn.",
  "sn51.22:4.1": "Ví như, này Ānanda, một cục sắt nung đỏ suốt một ngày trở nên nhẹ hơn, mềm mại hơn, dễ vận dụng hơn và sáng trong hơn;",
  "sn51.22:4.2": "cũng vậy, này Ānanda, trong thời điểm mà Như Lai thu nhiếp thân vào tâm và tâm vào thân, trú nhập vào thân với nhận thức hỷ lạc và nhận thức nhẹ nhàng;",
  "sn51.22:4.3": "này Ānanda, vào thời điểm đó thân của Như Lai trở nên nhẹ hơn, mềm mại hơn, dễ vận dụng hơn và sáng trong hơn.",
  "sn51.22:5.1": "Này Ānanda, trong thời điểm mà Như Lai thu nhiếp thân vào tâm và tâm vào thân, trú nhập vào thân với nhận thức hỷ lạc và nhận thức nhẹ nhàng;",
  "sn51.22:5.2": "này Ānanda, vào thời điểm đó thân của Như Lai dễ dàng bay lên khỏi mặt đất vào hư không,",
  "sn51.22:5.3": "và Ngài thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một …vv… dùng thân thể tự tại cho đến cõi Phạm thiên.",
  "sn51.22:6.1": "Ví như, này Ānanda, một cục bông hay một cục bông vải nhẹ khi bị gió thổi dễ dàng bay lên khỏi mặt đất vào hư không;",
  "sn51.22:6.2": "cũng vậy, này Ānanda, trong thời điểm mà Như Lai thu nhiếp thân vào tâm và tâm vào thân, trú nhập vào thân với nhận thức hỷ lạc và nhận thức nhẹ nhàng;",
  "sn51.22:6.3": "này Ānanda, vào thời điểm đó thân của Như Lai dễ dàng bay lên khỏi mặt đất vào hư không,",
  "sn51.22:6.4": "'và Ngài thể hiện nhiều loại thần thôngtừ một thành nhiều …vv… dùng thân thể tự tại cho đến cõi Phạm thiên.'",
  "sn51.22:6.5": "Thứ hai.",
  "sn51.23:0.1": "Tương Ưng Bộ 51.23",
  "sn51.23:0.2": "3. Phẩm Cục Sắt",
  "sn51.23:0.3": "Kinh Tỳ Kheo",
  "sn51.23:1.1": "Này các Tỳ Kheo, có bốn thần túc.",
  "sn51.23:1.2": "Thế nào là bốn?",
  "sn51.23:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.23:1.4": "định do tinh tấn …vv…",
  "sn51.23:1.5": "định do tâm …",
  "sn51.23:1.6": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.23:1.7": "này các Tỳ Kheo, đây là bốn thần túc.",
  "sn51.23:1.8": "'Này các Tỳ Kheo, chính do tu tập và thực hành nhiều bốn thần túc này, Tỳ Kheo đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú.'",
  "sn51.23:1.9": "Thứ ba.",
  "sn51.24:0.1": "Tương Ưng Bộ 51.24",
  "sn51.24:0.2": "3. Phẩm Cục Sắt",
  "sn51.24:0.3": "Kinh Thuần Túy",
  "sn51.24:1.1": "Này các Tỳ Kheo, có bốn thần túc.",
  "sn51.24:1.2": "Thế nào là bốn?",
  "sn51.24:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.24:1.4": "định do tinh tấn …vv…",
  "sn51.24:1.5": "định do tâm …",
  "sn51.24:1.6": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.24:1.7": "'này các Tỳ Kheo, đây là bốn thần túc.'",
  "sn51.24:1.8": "Thứ tư.",
  "sn51.25:0.1": "Tương Ưng Bộ 51.25",
  "sn51.25:0.2": "3. Phẩm Cục Sắt",
  "sn51.25:0.3": "Kinh Quả Thứ Nhất",
  "sn51.25:1.1": "Này các Tỳ Kheo, có bốn thần túc.",
  "sn51.25:1.2": "Thế nào là bốn?",
  "sn51.25:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.25:1.4": "định do tinh tấn …vv…",
  "sn51.25:1.5": "định do tâm …",
  "sn51.25:1.6": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.25:1.7": "này các Tỳ Kheo, đây là bốn thần túc.",
  "sn51.25:1.8": "Này các Tỳ Kheo, do tu tập và thực hành nhiều bốn thần túc này, Tỳ Kheo có thể kỳ vọng đạt một trong hai quả",
  "sn51.25:1.9": "'Chánh trí ngay trong đời này, hay nếu còn chấp thủ thì đạt quả Bất lai.'",
  "sn51.25:1.10": "Thứ năm.",
  "sn51.26:0.1": "Tương Ưng Bộ 51.26",
  "sn51.26:0.2": "3. Phẩm Cục Sắt",
  "sn51.26:0.3": "Kinh Quả Thứ Hai",
  "sn51.26:1.1": "Này các Tỳ Kheo, có bốn thần túc.",
  "sn51.26:1.2": "Thế nào là bốn?",
  "sn51.26:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.26:1.4": "định do tinh tấn …vv…",
  "sn51.26:1.5": "định do tâm …",
  "sn51.26:1.6": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.26:1.7": "này các Tỳ Kheo, đây là bốn thần túc.",
  "sn51.26:1.8": "Này các Tỳ Kheo, do tu tập và thực hành nhiều bốn thần túc này, có thể kỳ vọng bảy quả, bảy lợi ích.",
  "sn51.26:2.1": "Thế nào là bảy quả, bảy lợi ích?",
  "sn51.26:2.2": "Chứng ngộ Chánh trí ngay trong đời này;",
  "sn51.26:2.3": "nếu không chứng ngộ Chánh trí ngay trong đời này, thì chứng ngộ Chánh trí vào lúc lâm chung;",
  "sn51.26:2.4": "nếu không chứng ngộ Chánh trí ngay trong đời này, không chứng ngộ Chánh trí vào lúc lâm chung; thì do đoạn tận năm hạ phần kiết sử, vị ấy là người Bát Niết-bàn ở giữa chừng, là người Bát Niết-bàn khi tiếp xúc, là người Bát Niết-bàn không cần nỗ lực, là người Bát Niết-bàn có nỗ lực, hay là người đi ngược dòng đến cõi Vô Phiền.",
  "sn51.26:2.5": "'Này các Tỳ Kheo, do tu tập và thực hành nhiều bốn thần túc này, có thể kỳ vọng bảy quả, bảy lợi ích này.'",
  "sn51.26:2.6": "Thứ sáu.",
  "sn51.27:0.1": "Tương Ưng Bộ 51.27",
  "sn51.27:0.2": "3. Phẩm Cục Sắt",
  "sn51.27:0.3": "Kinh Ānanda Thứ Nhất",
  "sn51.27:1.1": "Nhân duyên ở Sāvatthi.",
  "sn51.27:1.2": "Rồi Tôn giả Ānanda đến chỗ Thế Tôn; đến nơi, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Ānanda thưa với Thế Tôn:",
  "sn51.27:2.1": "'Bạch Thế Tôn, thế nào là thần thông, thế nào là thần túc, thế nào là sự tu tập thần túc, thế nào là con đường thực hành đưa đến tu tập thần túc?'",
  "sn51.27:2.2": "Này Ānanda, ở đây Tỳ Kheo thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một …vv… dùng thân thể tự tại cho đến cõi Phạm thiên",
  "sn51.27:2.3": "này Ānanda, đây được gọi là thần thông.",
  "sn51.27:3.1": "Này Ānanda, thế nào là thần túc?",
  "sn51.27:3.2": "Này Ānanda, con đường, lối thực hành đưa đến sự đạt được thần thông, sự thành tựu thần thông",
  "sn51.27:3.3": "này Ānanda, đây được gọi là thần túc.",
  "sn51.27:4.1": "Này Ānanda, thế nào là sự tu tập thần túc?",
  "sn51.27:4.2": "Này Ānanda, ở đây Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.27:4.3": "định do tinh tấn …vv…",
  "sn51.27:4.4": "định do tâm …",
  "sn51.27:4.5": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.27:4.6": "này Ānanda, đây được gọi là sự tu tập thần túc.",
  "sn51.27:5.1": "Này Ānanda, thế nào là con đường thực hành đưa đến tu tập thần túc?",
  "sn51.27:5.2": "Chính là Thánh đạo tám chi phần này, tức là",
  "sn51.27:5.3": "Chánh kiến …vv… Chánh định",
  "sn51.27:5.4": "'này Ānanda, đây được gọi là con đường thực hành đưa đến tu tập thần túc.'",
  "sn51.27:5.5": "Thứ bảy.",
  "sn51.28:0.1": "Tương Ưng Bộ 51.28",
  "sn51.28:0.2": "3. Phẩm Cục Sắt",
  "sn51.28:0.3": "Kinh Ānanda Thứ Hai",
  "sn51.28:1.1": "Tôn giả Ānanda đang ngồi một bên, Thế Tôn nói với Ngài:",
  "sn51.28:1.2": "'Này Ānanda, thế nào là thần thông, thế nào là thần túc, thế nào là sự tu tập thần túc, thế nào là con đường thực hành đưa đến tu tập thần túc?'",
  "sn51.28:1.3": "Chúng con lấy Thế Tôn làm căn bản, lấy Thế Tôn làm người dẫn đạo …vv….",
  "sn51.28:2.1": "Này Ānanda, ở đây Tỳ Kheo thể hiện nhiều loại thần thôngtừ một thành nhiều …vv… dùng thân thể tự tại cho đến cõi Phạm thiên",
  "sn51.28:2.2": "này Ānanda, đây được gọi là thần thông.",
  "sn51.28:3.1": "Này Ānanda, thế nào là thần túc?",
  "sn51.28:3.2": "Này Ānanda, con đường, lối thực hành đưa đến sự đạt được thần thông, sự thành tựu thần thông",
  "sn51.28:3.3": "này Ānanda, đây được gọi là thần túc.",
  "sn51.28:4.1": "Này Ānanda, thế nào là sự tu tập thần túc?",
  "sn51.28:4.2": "Này Ānanda, ở đây Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.28:4.3": "định do tinh tấn …vv…",
  "sn51.28:4.4": "định do tâm …",
  "sn51.28:4.5": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.28:4.6": "này Ānanda, đây được gọi là sự tu tập thần túc.",
  "sn51.28:5.1": "Này Ānanda, thế nào là con đường thực hành đưa đến tu tập thần túc?",
  "sn51.28:5.2": "Chính là Thánh đạo tám chi phần này, tức là",
  "sn51.28:5.3": "Chánh kiến …vv… Chánh định",
  "sn51.28:5.4": "'này Ānanda, đây được gọi là con đường thực hành đưa đến tu tập thần túc.'",
  "sn51.28:5.5": "Thứ tám.",
  "sn51.29:0.1": "Tương Ưng Bộ 51.29",
  "sn51.29:0.2": "3. Phẩm Cục Sắt",
  "sn51.29:0.3": "Kinh Tỳ Kheo Thứ Nhất",
  "sn51.29:1.1": "Rồi nhiều Tỳ Kheo đến chỗ Thế Tôn; đến nơi, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, các Tỳ Kheo ấy thưa với Thế Tôn:",
  "sn51.29:1.2": "'Bạch Thế Tôn, thế nào là thần thông, thế nào là thần túc, thế nào là sự tu tập thần túc, thế nào là con đường thực hành đưa đến tu tập thần túc?'",
  "sn51.29:2.1": "Này các Tỳ Kheo, ở đây Tỳ Kheo thể hiện nhiều loại thần thôngtừ một thành nhiều …vv… dùng thân thể tự tại cho đến cõi Phạm thiên",
  "sn51.29:2.2": "này các Tỳ Kheo, đây được gọi là thần thông.",
  "sn51.29:3.1": "Này các Tỳ Kheo, thế nào là thần túc?",
  "sn51.29:3.2": "Này các Tỳ Kheo, con đường, lối thực hành đưa đến sự đạt được thần thông, sự thành tựu thần thông",
  "sn51.29:3.3": "này các Tỳ Kheo, đây được gọi là thần túc.",
  "sn51.29:4.1": "Này các Tỳ Kheo, thế nào là sự tu tập thần túc?",
  "sn51.29:4.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.29:4.3": "định do tinh tấn …vv…",
  "sn51.29:4.4": "định do tâm …",
  "sn51.29:4.5": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.29:4.6": "này các Tỳ Kheo, đây được gọi là sự tu tập thần túc.",
  "sn51.29:5.1": "Này các Tỳ Kheo, thế nào là con đường thực hành đưa đến tu tập thần túc?",
  "sn51.29:5.2": "Chính là Thánh đạo tám chi phần này, tức là",
  "sn51.29:5.3": "Chánh kiến …vv… Chánh định",
  "sn51.29:5.4": "'này các Tỳ Kheo, đây được gọi là con đường thực hành đưa đến tu tập thần túc.'",
  "sn51.29:5.5": "Thứ chín.",
  "sn51.30:0.1": "Tương Ưng Bộ 51.30",
  "sn51.30:0.2": "3. Phẩm Cục Sắt",
  "sn51.30:0.3": "Kinh Tỳ Kheo Thứ Hai",
  "sn51.30:1.1": "Rồi nhiều Tỳ Kheo đến chỗ Thế Tôn …vv…",
  "sn51.30:1.2": "khi các Tỳ Kheo ấy đã ngồi một bên, Thế Tôn nói với họ:",
  "sn51.30:1.3": "'Này các Tỳ Kheo, thế nào là thần thông, thế nào là thần túc, thế nào là sự tu tập thần túc, thế nào là con đường thực hành đưa đến tu tập thần túc?'",
  "sn51.30:1.4": "Chúng con lấy Thế Tôn làm căn bản, lấy Thế Tôn làm người dẫn đạo …vv….",
  "sn51.30:2.1": "Này các Tỳ Kheo, thế nào là thần thông?",
  "sn51.30:2.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo thể hiện nhiều loại thần thôngtừ một thành nhiều …vv… dùng thân thể tự tại cho đến cõi Phạm thiên",
  "sn51.30:2.3": "này các Tỳ Kheo, đây được gọi là thần thông.",
  "sn51.30:3.1": "Này các Tỳ Kheo, thế nào là thần túc?",
  "sn51.30:3.2": "Này các Tỳ Kheo, con đường, lối thực hành đưa đến sự đạt được thần thông, sự thành tựu thần thông",
  "sn51.30:3.3": "này các Tỳ Kheo, đây được gọi là thần túc.",
  "sn51.30:4.1": "Này các Tỳ Kheo, thế nào là sự tu tập thần túc?",
  "sn51.30:4.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.30:4.3": "định do tinh tấn …vv…",
  "sn51.30:4.4": "định do tâm …",
  "sn51.30:4.5": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.30:4.6": "này các Tỳ Kheo, đây được gọi là sự tu tập thần túc.",
  "sn51.30:5.1": "Này các Tỳ Kheo, thế nào là con đường thực hành đưa đến tu tập thần túc?",
  "sn51.30:5.2": "Chính là Thánh đạo tám chi phần này, tức là",
  "sn51.30:5.3": "Chánh kiến …vv… Chánh định",
  "sn51.30:5.4": "'này các Tỳ Kheo, đây được gọi là con đường thực hành đưa đến tu tập thần túc.'",
  "sn51.30:5.5": "Thứ mười.",
  "sn51.31:0.1": "Tương Ưng Bộ 51.31",
  "sn51.31:0.2": "3. Phẩm Cục Sắt",
  "sn51.31:0.3": "Kinh Moggallāna",
  "sn51.31:1.1": "Bấy giờ, Thế Tôn gọi các Tỳ Kheo:",
  "sn51.31:1.2": "Này các Tỳ Kheo, các ông nghĩ thế nào,",
  "sn51.31:1.3": "'do tu tập và thực hành nhiều pháp nào mà Tỳ Kheo Moggallāna có thần lực lớn, oai đức lớn như vậy?'",
  "sn51.31:2.1": "Bạch Thế Tôn, chúng con lấy Thế Tôn làm căn bản, lấy Thế Tôn làm người dẫn đạo …vv…",
  "sn51.31:2.2": "Chính do tu tập và thực hành nhiều bốn thần túc mà Tỳ Kheo Moggallāna có thần lực lớn, oai đức lớn như vậy.",
  "sn51.31:3.1": "Thế nào là bốn?",
  "sn51.31:3.2": "Ở đây, này các Tỳ Kheo, Tỳ Kheo Moggallāna tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành",
  "sn51.31:3.3": "như vậy, dục của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.31:3.4": "Trú với nhận thức trước sau",
  "sn51.31:3.5": "như trước thì như sau, như sau thì như trước;",
  "sn51.31:3.6": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.31:3.7": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.31:3.8": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.31:3.9": "Định do tinh tấn …vv…",
  "sn51.31:3.10": "định do tâm …",
  "sn51.31:3.11": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.31:3.12": "như vậy, sự thẩm sát của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài …vv…",
  "sn51.31:3.13": "như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.31:3.14": "Này các Tỳ Kheo, chính do tu tập và thực hành nhiều bốn thần túc này mà Tỳ Kheo Moggallāna có thần lực lớn, oai đức lớn như vậy.",
  "sn51.31:4.1": "Này các Tỳ Kheo, chính do tu tập và thực hành nhiều bốn thần túc này mà Tỳ Kheo Moggallāna thể hiện nhiều loại thần thôngtừ một thành nhiều, từ nhiều thành một …vv… dùng thân thể tự tại cho đến cõi Phạm thiên.",
  "sn51.31:4.2": "'Này các Tỳ Kheo, chính do tu tập và thực hành nhiều bốn thần túc này mà Tỳ Kheo Moggallāna đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú.'",
  "sn51.31:4.3": "Thứ mười một.",
  "sn51.32:0.1": "Tương Ưng Bộ 51.32",
  "sn51.32:0.2": "3. Phẩm Cục Sắt",
  "sn51.32:0.3": "Kinh Như Lai",
  "sn51.32:1.1": "Bấy giờ, Thế Tôn gọi các Tỳ Kheo:",
  "sn51.32:1.2": "Này các Tỳ Kheo, các ông nghĩ thế nào,",
  "sn51.32:1.3": "'do tu tập và thực hành nhiều pháp nào mà Như Lai có thần lực lớn, oai đức lớn như vậy?'",
  "sn51.32:2.1": "Bạch Thế Tôn, chúng con lấy Thế Tôn làm căn bản, các pháp …vv…",
  "sn51.32:2.2": "Chính do tu tập và thực hành nhiều bốn thần túc mà Như Lai có thần lực lớn, oai đức lớn như vậy.",
  "sn51.32:3.1": "Thế nào là bốn?",
  "sn51.32:3.2": "Ở đây, này các Tỳ Kheo, Như Lai tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành",
  "sn51.32:3.3": "như vậy, dục của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.32:3.4": "Trú với nhận thức trước sau",
  "sn51.32:3.5": "như trước thì như sau, như sau thì như trước;",
  "sn51.32:3.6": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.32:3.7": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.32:3.8": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.32:3.9": "Định do tinh tấn …vv…",
  "sn51.32:3.10": "định do tâm …",
  "sn51.32:3.11": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành",
  "sn51.32:3.12": "như vậy, sự thẩm sát của Ta sẽ không bị uể oải, không bị phấn khích thái quá, không bị co rút vào trong, không bị tán loạn ra ngoài.",
  "sn51.32:3.13": "Trú với nhận thức trước sau",
  "sn51.32:3.14": "như trước thì như sau, như sau thì như trước;",
  "sn51.32:3.15": "như dưới thì như trên, như trên thì như dưới;",
  "sn51.32:3.16": "như ban ngày thì như ban đêm, như ban đêm thì như ban ngày.",
  "sn51.32:3.17": "Như vậy, với tâm rộng mở, không bị che khuất, tu tập tâm có ánh sáng.",
  "sn51.32:3.18": "Này các Tỳ Kheo, chính do tu tập và thực hành nhiều bốn thần túc này mà Như Lai có thần lực lớn, oai đức lớn như vậy.",
  "sn51.32:4.1": "Này các Tỳ Kheo, chính do tu tập và thực hành nhiều bốn thần túc này mà Như Lai thể hiện nhiều loại thần thôngtừ một thành nhiều …vv… dùng thân thể tự tại cho đến cõi Phạm thiên.",
  "sn51.32:4.2": "'Này các Tỳ Kheo, chính do tu tập và thực hành nhiều bốn thần túc này mà Như Lai đoạn tận các lậu hoặc, chứng đạt tâm giải thoát không lậu và tuệ giải thoát ngay trong đời này bằng thắng trí, chứng đạt và an trú.'",
  "sn51.32:4.3": "Thứ mười hai.",
  "sn51.32:4.4": "(Sáu thắng trí cần được trình bày đầy đủ.)",
  "sn51.32:4.5": "Phẩm Cục Sắt, phẩm thứ ba.",
  "sn51.32:5.0": "Tóm tắt phẩm:",
  "sn51.32:5.1": "Con đường, cục sắt, Tỳ Kheo,",
  "sn51.32:5.2": "thuần túy và hai quả;",
  "sn51.32:5.3": "Hai Ānanda, hai Tỳ Kheo,",
  "sn51.32:5.4": "Moggallāna và Như Lai vậy.",
  "sn51.33-44:0.1": "Tương Ưng Bộ 51.33–44",
  "sn51.33-44:0.2": "4. Phẩm Sông Hằng Peyyāla",
  "sn51.33-44:0.3": "Kinh Sông Hằng v.v.",
  "sn51.33-44:1.1": "Ví như, này các Tỳ Kheo, sông Hằng chảy về phía đông, dốc về phía đông, nghiêng về phía đông;",
  "sn51.33-44:1.2": "cũng vậy, này các Tỳ Kheo, Tỳ Kheo tu tập bốn thần túc, thực hành nhiều bốn thần túc, thì hướng về Niết-bàn, dốc về Niết-bàn, nghiêng về Niết-bàn.",
  "sn51.33-44:1.3": "Này các Tỳ Kheo, thế nào là Tỳ Kheo tu tập bốn thần túc, thực hành nhiều bốn thần túc, hướng về Niết-bàn, dốc về Niết-bàn, nghiêng về Niết-bàn?",
  "sn51.33-44:1.4": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.33-44:1.5": "định do tinh tấn …vv…",
  "sn51.33-44:1.6": "định do tâm …",
  "sn51.33-44:1.7": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.33-44:2.1": "'Này các Tỳ Kheo, như vậy Tỳ Kheo tu tập bốn thần túc, thực hành nhiều bốn thần túc, hướng về Niết-bàn, dốc về Niết-bàn, nghiêng về Niết-bàn.'",
  "sn51.33-44:2.2": "Thứ mười hai.",
  "sn51.33-44:2.3": "Phẩm Sông Hằng Peyyāla, phẩm thứ tư.",
  "sn51.33-44:3.0": "Tóm tắt phẩm:",
  "sn51.33-44:3.1": "Sáu dốc về hướng đông,",
  "sn51.33-44:3.2": "sáu dốc về đại dương;",
  "sn51.33-44:3.3": "Hai nhóm sáu thành mười hai,",
  "sn51.33-44:3.4": "phẩm vì vậy được gọi vậy.",
  "sn51.45-54:0.1": "Tương Ưng Bộ 51.45",
  "sn51.45-54:0.2": "5. Phẩm Không Phóng Dật",
  "sn51.45-54:0.3": "Phẩm Không Phóng Dật",
  "sn51.45-54:1.1": "(Phẩm Không Phóng Dật cần được trình bày đầy đủ.)",
  "sn51.45-54:2.0": "Tóm tắt phẩm:",
  "sn51.45-54:2.1": "Như Lai, dấu chân, đỉnh,",
  "sn51.45-54:2.2": "gốc rễ, lõi cây và hoa lài;",
  "sn51.45-54:2.3": "Vua, mặt trăng mặt trời,",
  "sn51.45-54:2.4": "vải và bài kệ thứ mười vậy.",
  "sn51.55-66:0.1": "Tương Ưng Bộ 51.55",
  "sn51.55-66:0.2": "6. Phẩm Điều Cần Làm Với Sức Mạnh",
  "sn51.55-66:0.3": "Phẩm Điều Cần Làm Với Sức Mạnh",
  "sn51.55-66:1.1": "(Phẩm Điều Cần Làm Với Sức Mạnh cần được trình bày đầy đủ.)",
  "sn51.55-66:2.0": "Tóm tắt phẩm:",
  "sn51.55-66:2.1": "Sức mạnh, hạt giống và rồng,",
  "sn51.55-66:2.2": "cây, cái bình và cây sậy;",
  "sn51.55-66:2.3": "Hư không và hai đám mây,",
  "sn51.55-66:2.4": "con thuyền, khách phương xa và dòng sông.",
  "sn51.67-76:0.1": "Tương Ưng Bộ 51.67",
  "sn51.67-76:0.2": "7. Phẩm Tìm Cầu",
  "sn51.67-76:0.3": "Phẩm Tìm Cầu",
  "sn51.67-76:1.1": "(Phẩm Tìm Cầu cần được trình bày đầy đủ.)",
  "sn51.67-76:2.0": "Tóm tắt phẩm:",
  "sn51.67-76:2.1": "Tìm cầu, tầm, lậu hoặc,",
  "sn51.67-76:2.2": "hữu và khổ, ba loại;",
  "sn51.67-76:2.3": "Triền cái, cấu uế, nhiệt não,",
  "sn51.67-76:2.4": "thọ, ái và khát vọng vậy.",
  "sn51.77-86:0.1": "Tương Ưng Bộ 51.77–86",
  "sn51.77-86:0.2": "8. Phẩm Bộc Lưu",
  "sn51.77-86:0.3": "Kinh Bộc Lưu v.v.",
  "sn51.77-86:1.1": "Này các Tỳ Kheo, có năm thượng phần kiết sử này.",
  "sn51.77-86:1.2": "Thế nào là năm?",
  "sn51.77-86:1.3": "Sắc ái, vô sắc ái, mạn, trạo cử, vô minh",
  "sn51.77-86:1.4": "này các Tỳ Kheo, đây là năm thượng phần kiết sử.",
  "sn51.77-86:1.5": "Này các Tỳ Kheo, để thắng tri, biến tri, đoạn tận và từ bỏ năm thượng phần kiết sử này, cần tu tập bốn thần túc.",
  "sn51.77-86:1.6": "Thế nào là bốn?",
  "sn51.77-86:1.7": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập thần túc câu hữu với định do dục, cùng với các nỗ lực hành,",
  "sn51.77-86:1.8": "định do tinh tấn …vv…",
  "sn51.77-86:1.9": "định do tâm …",
  "sn51.77-86:1.10": "tu tập thần túc câu hữu với định do thẩm sát, cùng với các nỗ lực hành.",
  "sn51.77-86:1.11": "'Này các Tỳ Kheo, để thắng tri, biến tri, đoạn tận và từ bỏ năm thượng phần kiết sử này, cần tu tập bốn thần túc này.'",
  "sn51.77-86:1.12": "(Cần trình bày đầy đủ như Tương Ưng Đạo.)",
  "sn51.77-86:1.13": "Phẩm Bộc Lưu, phẩm thứ tám.",
  "sn51.77-86:2.0": "Tóm tắt phẩm:",
  "sn51.77-86:2.1": "Bộc lưu, phối hợp, thủ,",
  "sn51.77-86:2.2": "kiết và tùy miên;",
  "sn51.77-86:2.3": "Dục trưởng dưỡng, triền cái,",
  "sn51.77-86:2.4": "uẩn, hạ phần và thượng phần.",
  "sn51.77-86:2.5": "Tương Ưng Thần Túc, thứ bảy."
}
window.BILARA["sn51_v1"]["vi"]["sn51_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
