window.BILARA = window.BILARA || {};
window.BILARA["sn54_v1"] = window.BILARA["sn54_v1"] || {};
window.BILARA["sn54_v1"]["vi"] = {
  "sn54.1:0.1": "Tương Ưng Bộ Kinh 54.1",
  "sn54.1:0.2": "1. Phẩm Một Pháp",
  "sn54.1:0.3": "Kinh Một Pháp",
  "sn54.1:1.1": "Tại Sāvatthī.",
  "sn54.1:1.2": "Tại đó... Thế Tôn nói:",
  "sn54.1:1.3": "Này các Tỳ Kheo, một pháp được tu tập, được làm cho sung mãn, có quả lớn, có lợi ích lớn.",
  "sn54.1:1.4": "Một pháp ấy là gì?",
  "sn54.1:1.5": "Niệm hơi thở (ānāpānassati).",
  "sn54.1:1.6": "Này các Tỳ Kheo, niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, mà có quả lớn, có lợi ích lớn?",
  "sn54.1:1.7": "Ở đây, này các Tỳ Kheo, Tỳ Kheo đi đến khu rừng, hay đến gốc cây, hay đến căn nhà trống, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.1:1.8": "Vị ấy chánh niệm thở vào, chánh niệm thở ra.",
  "sn54.1:2.1": "Thở vào dài, vị ấy biết: 'Tôi thở vào dài'; thở ra dài, vị ấy biết: 'Tôi thở ra dài';",
  "sn54.1:2.2": "thở vào ngắn, vị ấy biết: 'Tôi thở vào ngắn'; thở ra ngắn, vị ấy biết: 'Tôi thở ra ngắn';",
  "sn54.1:2.3": "học tập: 'Cảm nhận toàn thân, tôi sẽ thở vào'; học tập: 'Cảm nhận toàn thân, tôi sẽ thở ra';",
  "sn54.1:2.4": "học tập: 'An tịnh thân hành, tôi sẽ thở vào'; học tập: 'An tịnh thân hành, tôi sẽ thở ra'.",
  "sn54.1:3.1": "Học tập: 'Cảm nhận hỷ, tôi sẽ thở vào'; học tập: 'Cảm nhận hỷ, tôi sẽ thở ra';",
  "sn54.1:3.2": "học tập: 'Cảm nhận lạc, tôi sẽ thở vào'; học tập: 'Cảm nhận lạc, tôi sẽ thở ra';",
  "sn54.1:3.3": "học tập: 'Cảm nhận tâm hành, tôi sẽ thở vào'; học tập: 'Cảm nhận tâm hành, tôi sẽ thở ra';",
  "sn54.1:3.4": "học tập: 'An tịnh tâm hành, tôi sẽ thở vào'; học tập: 'An tịnh tâm hành, tôi sẽ thở ra'.",
  "sn54.1:4.1": "Học tập: 'Cảm nhận tâm, tôi sẽ thở vào'; học tập: 'Cảm nhận tâm, tôi sẽ thở ra';",
  "sn54.1:4.2": "học tập: 'Làm hân hoan tâm, tôi sẽ thở vào'; học tập: 'Làm hân hoan tâm, tôi sẽ thở ra';",
  "sn54.1:4.3": "học tập: 'Làm định tĩnh tâm, tôi sẽ thở vào'; học tập: 'Làm định tĩnh tâm, tôi sẽ thở ra';",
  "sn54.1:4.4": "học tập: 'Giải thoát tâm, tôi sẽ thở vào'; học tập: 'Giải thoát tâm, tôi sẽ thở ra';",
  "sn54.1:4.5": "học tập: 'Quán vô thường, tôi sẽ thở vào'.",
  "sn54.1:5.1": "Học tập: 'Quán vô thường, tôi sẽ thở ra';",
  "sn54.1:5.2": "học tập: 'Quán ly tham, tôi sẽ thở vào'; học tập: 'Quán ly tham, tôi sẽ thở ra';",
  "sn54.1:5.3": "học tập: 'Quán đoạn diệt, tôi sẽ thở vào'; học tập: 'Quán đoạn diệt, tôi sẽ thở ra';",
  "sn54.1:5.4": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.1:6.1": "Này các Tỳ Kheo, niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, có quả lớn, có lợi ích lớn'.",
  "sn54.1:6.2": "Thứ nhất.",
  "sn54.2:0.1": "Tương Ưng Bộ Kinh 54.2",
  "sn54.2:0.2": "1. Phẩm Một Pháp",
  "sn54.2:0.3": "Kinh Giác Chi",
  "sn54.2:1.1": "Này các Tỳ Kheo, niệm hơi thở được tu tập, được làm cho sung mãn, có quả lớn, có lợi ích lớn.",
  "sn54.2:1.2": "Này các Tỳ Kheo, niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, mà có quả lớn, có lợi ích lớn?",
  "sn54.2:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo tu tập niệm giác chi câu hữu với niệm hơi thở, y cứ viễn ly, y cứ ly tham, y cứ đoạn diệt, hướng đến xả ly,",
  "sn54.2:1.4": "tu tập trạch pháp giác chi câu hữu với niệm hơi thở... (rút gọn)...",
  "sn54.2:1.5": "tu tập xả giác chi câu hữu với niệm hơi thở, y cứ viễn ly, y cứ ly tham, y cứ đoạn diệt, hướng đến xả ly.",
  "sn54.2:1.6": "Này các Tỳ Kheo, niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, có quả lớn, có lợi ích lớn'.",
  "sn54.2:1.7": "Thứ hai.",
  "sn54.3:0.1": "Tương Ưng Bộ Kinh 54.3",
  "sn54.3:0.2": "1. Phẩm Một Pháp",
  "sn54.3:0.3": "Kinh Thuần Nhất",
  "sn54.3:1.1": "Này các Tỳ Kheo, niệm hơi thở được tu tập, được làm cho sung mãn, có quả lớn, có lợi ích lớn.",
  "sn54.3:1.2": "Này các Tỳ Kheo, niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, mà có quả lớn, có lợi ích lớn?",
  "sn54.3:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo đi đến khu rừng, hay đến gốc cây, hay đến căn nhà trống, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.3:1.4": "Vị ấy chánh niệm thở vào, chánh niệm thở ra... (rút gọn)...",
  "sn54.3:1.5": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.3:1.6": "Này các Tỳ Kheo, niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, có quả lớn, có lợi ích lớn'.",
  "sn54.3:1.7": "Thứ ba.",
  "sn54.4:0.1": "Tương Ưng Bộ Kinh 54.4",
  "sn54.4:0.2": "1. Phẩm Một Pháp",
  "sn54.4:0.3": "Kinh Quả Thứ Nhất",
  "sn54.4:1.1": "Này các Tỳ Kheo, niệm hơi thở được tu tập, được làm cho sung mãn, có quả lớn, có lợi ích lớn.",
  "sn54.4:1.2": "Này các Tỳ Kheo, niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, mà có quả lớn, có lợi ích lớn?",
  "sn54.4:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo đi đến khu rừng, hay đến gốc cây, hay đến căn nhà trống, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.4:1.4": "Vị ấy chánh niệm thở vào, chánh niệm thở ra... (rút gọn)...",
  "sn54.4:1.5": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.4:1.6": "Này các Tỳ Kheo, niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, có quả lớn, có lợi ích lớn.",
  "sn54.4:1.7": "Này các Tỳ Kheo, với niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, một trong hai quả được mong đợi",
  "sn54.4:1.8": "ngay trong đời này đạt chánh trí, hoặc nếu còn dư y, đạt quả Bất hoàn'.",
  "sn54.4:1.9": "Thứ tư.",
  "sn54.5:0.1": "Tương Ưng Bộ Kinh 54.5",
  "sn54.5:0.2": "1. Phẩm Một Pháp",
  "sn54.5:0.3": "Kinh Quả Thứ Hai",
  "sn54.5:1.1": "Này các Tỳ Kheo, niệm hơi thở được tu tập, được làm cho sung mãn, có quả lớn, có lợi ích lớn.",
  "sn54.5:1.2": "Này các Tỳ Kheo, niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, mà có quả lớn, có lợi ích lớn?",
  "sn54.5:1.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo đi đến khu rừng, hay đến gốc cây, hay đến căn nhà trống, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.5:1.4": "Vị ấy chánh niệm thở vào, chánh niệm thở ra... (rút gọn)...",
  "sn54.5:1.5": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.5:1.6": "Này các Tỳ Kheo, niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, có quả lớn, có lợi ích lớn.",
  "sn54.5:2.1": "Này các Tỳ Kheo, với niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, bảy quả và bảy lợi ích được mong đợi.",
  "sn54.5:2.2": "Bảy quả và bảy lợi ích ấy là gì?",
  "sn54.5:2.3": "Ngay trong đời này đạt chánh trí trước;",
  "sn54.5:2.4": "nếu chưa đạt chánh trí ngay trong đời này.",
  "sn54.5:2.5": "Thì đến lúc lâm chung đạt chánh trí;",
  "sn54.5:2.6": "nếu chưa đạt chánh trí ngay trong đời này, chưa đạt chánh trí lúc lâm chung.",
  "sn54.5:2.7": "Thì do đoạn tận năm hạ phần kiết sử, chứng Trung gian Bát-niết-bàn...",
  "sn54.5:2.8": "chứng Sinh tiền Bát-niết-bàn...",
  "sn54.5:2.9": "chứng Vô hành Bát-niết-bàn...",
  "sn54.5:2.10": "chứng Hữu hành Bát-niết-bàn...",
  "sn54.5:2.11": "đi ngược dòng, đến Sắc cứu cánh thiên",
  "sn54.5:2.12": "này các Tỳ Kheo, với niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, bảy quả và bảy lợi ích này được mong đợi'.",
  "sn54.5:2.13": "Thứ năm.",
  "sn54.6:0.1": "Tương Ưng Bộ Kinh 54.6",
  "sn54.6:0.2": "1. Phẩm Một Pháp",
  "sn54.6:0.3": "Kinh Ariṭṭha",
  "sn54.6:1.1": "Tại Sāvatthī.",
  "sn54.6:1.2": "Tại đó, Thế Tôn... (rút gọn)... nói:",
  "sn54.6:1.3": "'Này các Tỳ Kheo, các ông có tu tập niệm hơi thở không?'",
  "sn54.6:1.4": "Khi được nói vậy, Tôn giả Ariṭṭha thưa với Thế Tôn:",
  "sn54.6:1.5": "'Bạch Ngài, con có tu tập niệm hơi thở.'",
  "sn54.6:1.6": "'Này Ariṭṭha, ông tu tập niệm hơi thở như thế nào?'",
  "sn54.6:1.7": "Bạch Ngài, đối với dục trong quá khứ, tham dục đã được từ bỏ; đối với dục trong tương lai, tham dục đã được trừ diệt; đối với các pháp nội và ngoại, tưởng về đối ngại đã được khéo trừ bỏ.",
  "sn54.6:1.8": "Tôi chánh niệm thở vào, chánh niệm thở ra.",
  "sn54.6:1.9": "'Bạch Ngài, như vậy là con tu tập niệm hơi thở.'",
  "sn54.6:2.1": "'Này Ariṭṭha, niệm hơi thở ấy có, ta không nói là không có'.",
  "sn54.6:2.2": "Nhưng này Ariṭṭha, đây là cách niệm hơi thở được trọn vẹn đầy đủ,",
  "sn54.6:2.3": "'hãy nghe và khéo tác ý; Ta sẽ giảng.'",
  "sn54.6:2.4": "Thưa vâng, bạch Ngài', Tôn giả Ariṭṭha vâng lời Thế Tôn.",
  "sn54.6:2.5": "Thế Tôn nói:",
  "sn54.6:3.1": "Này Ariṭṭha, niệm hơi thở được trọn vẹn đầy đủ như thế nào?",
  "sn54.6:3.2": "Ở đây, này Ariṭṭha, Tỳ Kheo đi đến khu rừng, hay đến gốc cây, hay đến căn nhà trống, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.6:3.3": "Vị ấy chánh niệm thở vào, chánh niệm thở ra.",
  "sn54.6:3.4": "Thở vào dài, vị ấy biết: 'Tôi thở vào dài'... (rút gọn)...",
  "sn54.6:3.5": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.6:3.6": "'Này Ariṭṭha, như vậy là niệm hơi thở được trọn vẹn đầy đủ.'",
  "sn54.6:3.7": "Thứ sáu.",
  "sn54.7:0.1": "Tương Ưng Bộ Kinh 54.7",
  "sn54.7:0.2": "1. Phẩm Một Pháp",
  "sn54.7:0.3": "Kinh Mahākappina",
  "sn54.7:1.1": "Tại Sāvatthī.",
  "sn54.7:1.2": "Lúc bấy giờ, Tôn giả Mahākappina đang ngồi không xa Thế Tôn, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.7:1.3": "Thế Tôn trông thấy Tôn giả Mahākappina đang ngồi không xa, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.7:1.4": "Sau khi thấy, Ngài bảo các Tỳ Kheo:",
  "sn54.7:2.1": "'Này các Tỳ Kheo, các ông có thấy thân của Tỳ Kheo ấy cử động hay rung động không?'",
  "sn54.7:2.2": "'Bạch Ngài, dù khi chúng con thấy vị Tôn giả ấy đang ngồi trong chúng Tăng, hay ngồi một mình nơi vắng, chúng con cũng không thấy thân của Tôn giả ấy cử động hay rung động.'",
  "sn54.7:3.1": "Này các Tỳ Kheo, Tỳ Kheo ấy, do tu tập và làm cho sung mãn định ấy, thân không cử động hay rung động, tâm không cử động hay rung động, được định tùy ý, không khó khăn, không vất vả.",
  "sn54.7:3.2": "Này các Tỳ Kheo, định nào được tu tập, được làm cho sung mãn, khiến thân không cử động hay rung động, tâm không cử động hay rung động?",
  "sn54.7:4.1": "Này các Tỳ Kheo, do tu tập và làm cho sung mãn định niệm hơi thở, thân không cử động hay rung động, tâm không cử động hay rung động.",
  "sn54.7:4.2": "Này các Tỳ Kheo, định niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, khiến thân không cử động hay rung động, tâm không cử động hay rung động?",
  "sn54.7:5.1": "Ở đây, này các Tỳ Kheo, Tỳ Kheo đi đến khu rừng, hay đến gốc cây, hay đến căn nhà trống, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.7:5.2": "Vị ấy chánh niệm thở vào, chánh niệm thở ra... (rút gọn)...",
  "sn54.7:5.3": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.7:5.4": "'Này các Tỳ Kheo, khi định niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, thân không cử động hay rung động, tâm không cử động hay rung động.'",
  "sn54.7:5.5": "Thứ bảy.",
  "sn54.8:0.1": "Tương Ưng Bộ Kinh 54.8",
  "sn54.8:0.2": "1. Phẩm Một Pháp",
  "sn54.8:0.3": "Kinh Ví Dụ Ngọn Đèn",
  "sn54.8:1.1": "Này các Tỳ Kheo, định niệm hơi thở được tu tập, được làm cho sung mãn, có quả lớn, có lợi ích lớn.",
  "sn54.8:1.2": "Này các Tỳ Kheo, định niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, mà có quả lớn, có lợi ích lớn?",
  "sn54.8:2.1": "Ở đây, này các Tỳ Kheo, Tỳ Kheo đi đến khu rừng, hay đến gốc cây, hay đến căn nhà trống, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.8:2.2": "Vị ấy chánh niệm thở vào, chánh niệm thở ra.",
  "sn54.8:2.3": "Thở vào dài, vị ấy biết: 'Tôi thở vào dài'... (rút gọn)...",
  "sn54.8:2.4": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.8:2.5": "Này các Tỳ Kheo, định niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, có quả lớn, có lợi ích lớn.",
  "sn54.8:3.1": "Này các Tỳ Kheo, trước khi giác ngộ, khi còn là Bồ-tát chưa giác ngộ, Ta thường trú với trú xứ này.",
  "sn54.8:3.2": "Này các Tỳ Kheo, khi Ta thường trú với trú xứ này, thân không mệt mỏi, mắt không mệt mỏi;",
  "sn54.8:3.3": "và tâm Ta được giải thoát, không chấp thủ vào các lậu hoặc.",
  "sn54.8:4.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:4.2": "'Thân ta sẽ không mệt mỏi, mắt sẽ không mệt mỏi, và tâm ta sẽ được giải thoát, không chấp thủ vào các lậu hoặc',",
  "sn54.8:4.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:5.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:5.2": "'Những ký ức và tư duy liên hệ đến gia đình của ta sẽ được từ bỏ',",
  "sn54.8:5.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:6.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:6.2": "'Ta sẽ sống quán bất tịnh đối với vật không bất tịnh',",
  "sn54.8:6.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:7.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:7.2": "'Ta sẽ sống quán không bất tịnh đối với vật bất tịnh',",
  "sn54.8:7.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:8.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:8.2": "'Ta sẽ sống quán bất tịnh đối với cả vật bất tịnh lẫn vật không bất tịnh',",
  "sn54.8:8.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:9.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:9.2": "'Ta sẽ sống quán không bất tịnh đối với cả vật bất tịnh lẫn vật không bất tịnh',",
  "sn54.8:9.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:10.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:10.2": "'Tránh bỏ cả vật không bất tịnh lẫn vật bất tịnh, ta sẽ sống xả, chánh niệm, tỉnh giác',",
  "sn54.8:10.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:11.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:11.2": "'Ta sẽ chứng và trú sơ thiền, với tầm và tứ, ly dục sinh hỷ và lạc',",
  "sn54.8:11.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:12.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:12.2": "'Ta sẽ chứng và trú nhị thiền, không tầm không tứ, định sinh hỷ lạc, nội tĩnh nhất tâm',",
  "sn54.8:12.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:13.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:13.2": "'Ta sẽ chứng và trú tam thiền, ly hỷ trú xả, chánh niệm tỉnh giác, thân cảm lạc, bậc thánh gọi là: xả, niệm, an lạc trú',",
  "sn54.8:13.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:14.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:14.2": "'Ta sẽ chứng và trú tứ thiền, xả lạc xả khổ, hỷ ưu đã diệt trước, bất khổ bất lạc, xả niệm thanh tịnh',",
  "sn54.8:14.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:15.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:15.2": "'Ta sẽ vượt hẳn sắc tưởng, diệt đối ngại tưởng, không tác ý dị biệt tưởng, với suy nghĩ: Hư không là vô biên, chứng và trú Không vô biên xứ',",
  "sn54.8:15.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:16.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:16.2": "'Ta sẽ vượt hẳn Không vô biên xứ, với suy nghĩ: Thức là vô biên, chứng và trú Thức vô biên xứ',",
  "sn54.8:16.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:17.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:17.2": "'Ta sẽ vượt hẳn Thức vô biên xứ, với suy nghĩ: Không có gì, chứng và trú Vô sở hữu xứ',",
  "sn54.8:17.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:18.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:18.2": "'Ta sẽ vượt hẳn Vô sở hữu xứ, chứng và trú Phi tưởng phi phi tưởng xứ',",
  "sn54.8:18.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:19.1": "Vì vậy, này các Tỳ Kheo, nếu Tỳ Kheo muốn:",
  "sn54.8:19.2": "'Ta sẽ vượt hẳn Phi tưởng phi phi tưởng xứ, chứng và trú Diệt thọ tưởng định',",
  "sn54.8:19.3": "thì định niệm hơi thở này cần được khéo tác ý.",
  "sn54.8:20.1": "Này các Tỳ Kheo, khi định niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, nếu cảm thọ lạc, vị ấy biết: 'Nó vô thường', biết: 'Không nắm giữ', biết: 'Không tham đắm';",
  "sn54.8:20.2": "nếu cảm thọ khổ, vị ấy biết: 'Nó vô thường', biết: 'Không nắm giữ', biết: 'Không tham đắm';",
  "sn54.8:20.3": "nếu cảm thọ không khổ không lạc, vị ấy biết: 'Nó vô thường', biết: 'Không nắm giữ', biết: 'Không tham đắm'.",
  "sn54.8:21.1": "Nếu cảm thọ lạc, vị ấy cảm thọ không bị ràng buộc;",
  "sn54.8:21.2": "nếu cảm thọ khổ, vị ấy cảm thọ không bị ràng buộc;",
  "sn54.8:21.3": "nếu cảm thọ không khổ không lạc, vị ấy cảm thọ không bị ràng buộc.",
  "sn54.8:21.4": "Khi cảm thọ thọ bị giới hạn bởi thân, vị ấy biết: 'Tôi đang cảm thọ thọ bị giới hạn bởi thân'; khi cảm thọ thọ bị giới hạn bởi sinh mạng, vị ấy biết: 'Tôi đang cảm thọ thọ bị giới hạn bởi sinh mạng';",
  "sn54.8:21.5": "vị ấy biết rằng: 'Sau khi thân hoại mạng chung, ngay tại đây tất cả các thọ sẽ trở nên lạnh mát vì không được tham đắm'.",
  "sn54.8:22.1": "Ví như, này các Tỳ Kheo, ngọn đèn dầu cháy dựa vào dầu và dựa vào bấc,",
  "sn54.8:22.2": "khi dầu và bấc đều cạn kiệt, không có vật liệu, đèn tắt;",
  "sn54.8:22.3": "cũng vậy, này các Tỳ Kheo, khi Tỳ Kheo cảm thọ thọ bị giới hạn bởi thân, vị ấy biết: 'Tôi đang cảm thọ thọ bị giới hạn bởi thân'; khi cảm thọ thọ bị giới hạn bởi sinh mạng, vị ấy biết: 'Tôi đang cảm thọ thọ bị giới hạn bởi sinh mạng';",
  "sn54.8:22.4": "'vị ấy biết rằng: 'Sau khi thân hoại mạng chung, ngay tại đây tất cả các thọ sẽ trở nên lạnh mát vì không được tham đắm'.'",
  "sn54.8:22.5": "Thứ tám.",
  "sn54.9:0.1": "Tương Ưng Bộ Kinh 54.9",
  "sn54.9:0.2": "1. Phẩm Một Pháp",
  "sn54.9:0.3": "Kinh Vesālī",
  "sn54.9:1.1": "Tôi đã nghe như vầy",
  "sn54.9:1.2": "một thời Thế Tôn trú ở Vesālī, tại Đại Lâm, trong tịnh xá có mái nhọn.",
  "sn54.9:1.3": "Lúc bấy giờ, Thế Tôn thuyết cho các Tỳ Kheo bằng nhiều phương thức về bất tịnh, ca ngợi bất tịnh, ca ngợi sự tu tập bất tịnh.",
  "sn54.9:2.1": "Rồi Thế Tôn bảo các Tỳ Kheo:",
  "sn54.9:2.2": "Ta muốn, này các Tỳ Kheo, an cư nửa tháng.",
  "sn54.9:2.3": "'Không ai được đến gặp Ta, ngoại trừ một người mang bình bát đến.'",
  "sn54.9:2.4": "Thưa vâng, bạch Ngài', các Tỳ Kheo ấy vâng lời Thế Tôn, không ai đến gặp Thế Tôn, ngoại trừ một người mang bình bát đến.",
  "sn54.9:3.1": "Rồi các Tỳ Kheo ấy,",
  "sn54.9:3.2": "nghĩ rằng: 'Thế Tôn thuyết về bất tịnh bằng nhiều phương thức, ca ngợi bất tịnh, ca ngợi sự tu tập bất tịnh', bằng nhiều cách chuyên tu tập bất tịnh.",
  "sn54.9:3.3": "Họ, nhàm chán, xấu hổ, ghê sợ thân này, đi tìm người cầm dao.",
  "sn54.9:3.4": "Mười Tỳ Kheo trong một ngày dùng dao [tự sát], hai mươi người... (rút gọn)... ba mươi Tỳ Kheo trong một ngày dùng dao [tự sát].",
  "sn54.9:4.1": "Sau khi nửa tháng trôi qua, Thế Tôn xuất khỏi thiền định, bảo Tôn giả Ānanda:",
  "sn54.9:4.2": "'Này Ānanda, sao Tăng đoàn Tỳ Kheo dường như đã giảm thiểu?'",
  "sn54.9:4.3": "Bạch Ngài, vì 'Thế Tôn thuyết về bất tịnh bằng nhiều phương thức, ca ngợi bất tịnh, ca ngợi sự tu tập bất tịnh', nên bằng nhiều cách họ chuyên tu tập bất tịnh.",
  "sn54.9:4.4": "Họ, nhàm chán, xấu hổ, ghê sợ thân này, đi tìm người cầm dao.",
  "sn54.9:4.5": "Mười Tỳ Kheo trong một ngày dùng dao [tự sát], hai mươi người... ba mươi Tỳ Kheo trong một ngày dùng dao [tự sát].",
  "sn54.9:4.6": "'Lành thay, bạch Ngài, Thế Tôn hãy giảng phương pháp khác để Tăng đoàn Tỳ Kheo trụ vững nhờ liễu tri.'",
  "sn54.9:5.1": "'Vậy thì, này Ānanda, hãy tập hợp tất cả Tỳ Kheo đang trú nương Vesālī vào giảng đường.'",
  "sn54.9:5.2": "Thưa vâng, bạch Ngài', Tôn giả Ānanda vâng lời Thế Tôn, tập hợp tất cả Tỳ Kheo đang trú nương Vesālī vào giảng đường, rồi đến chỗ Thế Tôn; đến xong thưa với Thế Tôn:",
  "sn54.9:5.3": "Bạch Ngài, Tăng đoàn Tỳ Kheo đã tập hợp.",
  "sn54.9:5.4": "'Bạch Ngài, nay Thế Tôn hãy làm điều mà Ngài thấy đúng thời.'",
  "sn54.9:6.1": "Rồi Thế Tôn đi đến giảng đường; đến xong ngồi lên chỗ ngồi đã sắp sẵn.",
  "sn54.9:6.2": "Sau khi ngồi xuống, Thế Tôn bảo các Tỳ Kheo:",
  "sn54.9:6.3": "Này các Tỳ Kheo, định niệm hơi thở này, được tu tập, được làm cho sung mãn, là an tịnh, thù thắng, trong sạch, an lạc, và làm cho các pháp ác bất thiện đã sinh lập tức biến mất, lắng xuống.",
  "sn54.9:7.1": "Ví như, này các Tỳ Kheo, bụi và bùn dâng cao vào tháng cuối mùa hè, đám mây lớn và mưa to làm cho nó lập tức biến mất, lắng xuống;",
  "sn54.9:7.2": "cũng vậy, này các Tỳ Kheo, định niệm hơi thở, được tu tập, được làm cho sung mãn, là an tịnh, thù thắng, trong sạch, an lạc, và làm cho các pháp ác bất thiện đã sinh lập tức biến mất, lắng xuống.",
  "sn54.9:7.3": "Này các Tỳ Kheo, định niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, là an tịnh, thù thắng, trong sạch, an lạc, và làm cho các pháp ác bất thiện đã sinh lập tức biến mất, lắng xuống?",
  "sn54.9:8.1": "Ở đây, này các Tỳ Kheo, Tỳ Kheo đi đến khu rừng, hay đến gốc cây, hay đến căn nhà trống, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.9:8.2": "Vị ấy chánh niệm thở vào, chánh niệm thở ra... (rút gọn)...",
  "sn54.9:8.3": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.9:8.4": "'Này các Tỳ Kheo, khi định niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, là an tịnh, thù thắng, trong sạch, an lạc, và làm cho các pháp ác bất thiện đã sinh lập tức biến mất, lắng xuống.'",
  "sn54.9:8.5": "Thứ chín.",
  "sn54.10:0.1": "Tương Ưng Bộ Kinh 54.10",
  "sn54.10:0.2": "1. Phẩm Một Pháp",
  "sn54.10:0.3": "Kinh Kimila",
  "sn54.10:1.1": "Tôi đã nghe như vầy",
  "sn54.10:1.2": "một thời Thế Tôn trú ở Kimila, tại Trúc Lâm.",
  "sn54.10:1.3": "Tại đó, Thế Tôn bảo Tôn giả Kimila:",
  "sn54.10:1.4": "'Này Kimila, định niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, mà có quả lớn, có lợi ích lớn?'",
  "sn54.10:2.1": "Khi được nói vậy, Tôn giả Kimila im lặng.",
  "sn54.10:2.2": "Lần thứ hai, Thế Tôn... (rút gọn)...",
  "sn54.10:2.3": "lần thứ ba, Thế Tôn bảo Tôn giả Kimila:",
  "sn54.10:2.4": "'Này Kimila, định niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, mà có quả lớn, có lợi ích lớn?'",
  "sn54.10:2.5": "Lần thứ ba, Tôn giả Kimila vẫn im lặng.",
  "sn54.10:3.1": "Khi được nói vậy, Tôn giả Ānanda thưa với Thế Tôn:",
  "sn54.10:3.2": "Bạch Thế Tôn, đây là đúng lúc; bạch Thiện Thệ, đây là đúng lúc.",
  "sn54.10:3.3": "'Nếu Thế Tôn giảng về định niệm hơi thở, các Tỳ Kheo sau khi nghe từ Thế Tôn sẽ ghi nhớ.'",
  "sn54.10:4.1": "'Vậy thì, này Ānanda, hãy nghe và khéo tác ý; Ta sẽ giảng.'",
  "sn54.10:4.2": "Thưa vâng, bạch Ngài', Tôn giả Ānanda vâng lời Thế Tôn.",
  "sn54.10:4.3": "Thế Tôn nói:",
  "sn54.10:4.4": "Này Ānanda, định niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, mà có quả lớn, có lợi ích lớn?",
  "sn54.10:4.5": "Này Ānanda, ở đây Tỳ Kheo đi đến khu rừng, hay đến gốc cây, hay đến căn nhà trống, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.10:4.6": "Vị ấy chánh niệm thở vào, chánh niệm thở ra... (rút gọn)...",
  "sn54.10:4.7": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.10:4.8": "Này Ānanda, định niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, có quả lớn, có lợi ích lớn.",
  "sn54.10:5.1": "Này Ānanda, vào lúc Tỳ Kheo thở vào dài, biết: 'Tôi thở vào dài'; thở ra dài, biết: 'Tôi thở ra dài';",
  "sn54.10:5.2": "thở vào ngắn, biết: 'Tôi thở vào ngắn'; thở ra ngắn, biết: 'Tôi thở ra ngắn';",
  "sn54.10:5.3": "học tập: 'Cảm nhận toàn thân, tôi sẽ thở vào'; học tập: 'Cảm nhận toàn thân, tôi sẽ thở ra';",
  "sn54.10:5.4": "học tập: 'An tịnh thân hành, tôi sẽ thở vào'; học tập: 'An tịnh thân hành, tôi sẽ thở ra'",
  "sn54.10:5.5": "vào lúc đó, này Ānanda, Tỳ Kheo trú quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.10:5.6": "Vì sao vậy?",
  "sn54.10:5.7": "Này Ānanda, Ta nói rằng đây là một loại thân, tức là hơi thở vào và hơi thở ra.",
  "sn54.10:5.8": "Vì vậy, này Ānanda, vào lúc đó Tỳ Kheo trú quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.10:6.1": "Này Ānanda, vào lúc Tỳ Kheo học tập: 'Cảm nhận hỷ, tôi sẽ thở vào'; học tập: 'Cảm nhận hỷ, tôi sẽ thở ra';",
  "sn54.10:6.2": "học tập: 'Cảm nhận lạc, tôi sẽ thở vào'; học tập: 'Cảm nhận lạc, tôi sẽ thở ra';",
  "sn54.10:6.3": "học tập: 'Cảm nhận tâm hành, tôi sẽ thở vào'; học tập: 'Cảm nhận tâm hành, tôi sẽ thở ra';",
  "sn54.10:6.4": "học tập: 'An tịnh tâm hành, tôi sẽ thở ra'",
  "sn54.10:6.5": "vào lúc đó, này Ānanda, Tỳ Kheo trú quán thọ trên các thọ, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.10:6.6": "Vì sao vậy?",
  "sn54.10:6.7": "Này Ānanda, Ta nói rằng đây là một loại thọ, tức là sự khéo tác ý hơi thở vào và hơi thở ra.",
  "sn54.10:6.8": "Vì vậy, này Ānanda, vào lúc đó Tỳ Kheo trú quán thọ trên các thọ, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.10:7.1": "Này Ānanda, vào lúc Tỳ Kheo học tập: 'Cảm nhận tâm, tôi sẽ thở vào'; học tập: 'Cảm nhận tâm, tôi sẽ thở ra';",
  "sn54.10:7.2": "làm hân hoan tâm... (rút gọn)...",
  "sn54.10:7.3": "làm định tĩnh tâm...",
  "sn54.10:7.4": "học tập: 'Giải thoát tâm, tôi sẽ thở vào'; học tập: 'Giải thoát tâm, tôi sẽ thở ra'",
  "sn54.10:7.5": "vào lúc đó, này Ānanda, Tỳ Kheo trú quán tâm trên tâm, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.10:7.6": "Vì sao vậy?",
  "sn54.10:7.7": "Này Ānanda, Ta không nói rằng người mất chánh niệm, không tỉnh giác, có tu tập định niệm hơi thở.",
  "sn54.10:7.8": "Vì vậy, này Ānanda, vào lúc đó Tỳ Kheo trú quán tâm trên tâm, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.10:8.1": "Này Ānanda, vào lúc Tỳ Kheo học tập: 'Quán vô thường, tôi sẽ thở vào'... (rút gọn)...",
  "sn54.10:8.2": "quán ly tham...",
  "sn54.10:8.3": "quán đoạn diệt...",
  "sn54.10:8.4": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'",
  "sn54.10:8.5": "vào lúc đó, này Ānanda, Tỳ Kheo trú quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.10:8.6": "Vị ấy, sau khi với trí tuệ thấy sự đoạn trừ tham ưu, khéo tu tập xả.",
  "sn54.10:8.7": "Vì vậy, này Ānanda, vào lúc đó Tỳ Kheo trú quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.10:9.1": "Ví như, này Ānanda, tại ngã tư đường có đống cát lớn.",
  "sn54.10:9.2": "Nếu từ phương Đông có xe bò hay xe ngựa đến, nó sẽ đụng phải đống cát ấy;",
  "sn54.10:9.3": "nếu từ phương Tây đến...",
  "sn54.10:9.4": "nếu từ phương Bắc đến...",
  "sn54.10:9.5": "nếu từ phương Nam có xe bò hay xe ngựa đến, nó sẽ đụng phải đống cát ấy.",
  "sn54.10:9.6": "Cũng vậy, này Ānanda, Tỳ Kheo trú quán thân trên thân cũng đụng phải các pháp ác bất thiện;",
  "sn54.10:9.7": "trên các thọ... (rút gọn)...",
  "sn54.10:9.8": "trên tâm... (rút gọn)...",
  "sn54.10:9.9": "'Tỳ Kheo trú quán pháp trên các pháp cũng đụng phải các pháp ác bất thiện.'",
  "sn54.10:9.10": "Thứ mười.",
  "sn54.10:9.11": "Đây là Phẩm Một Pháp, thứ nhất.",
  "sn54.10:10.0": "Tóm tắt phẩm:",
  "sn54.10:10.1": "Một pháp và giác chi,",
  "sn54.10:10.2": "thuần nhất và hai quả;",
  "sn54.10:10.3": "Ariṭṭha, Kappina, ngọn đèn,",
  "sn54.10:10.4": "Vesālī và Kimila.",
  "sn54.11:0.1": "Tương Ưng Bộ Kinh 54.11",
  "sn54.11:0.2": "2. Phẩm Thứ Hai",
  "sn54.11:0.3": "Kinh Icchānaṅgala",
  "sn54.11:1.1": "Một thời Thế Tôn trú ở Icchānaṅgala, trong rừng Icchānaṅgala.",
  "sn54.11:1.2": "Tại đó, Thế Tôn bảo các Tỳ Kheo:",
  "sn54.11:1.3": "Ta muốn, này các Tỳ Kheo, an cư ba tháng.",
  "sn54.11:1.4": "'Không ai được đến gặp Ta, ngoại trừ một người mang bình bát đến.'",
  "sn54.11:1.5": "Thưa vâng, bạch Ngài', các Tỳ Kheo ấy vâng lời Thế Tôn, không ai đến gặp Thế Tôn, ngoại trừ một người mang bình bát đến.",
  "sn54.11:2.1": "Rồi sau khi ba tháng trôi qua, Thế Tôn xuất khỏi thiền định, bảo các Tỳ Kheo:",
  "sn54.11:2.2": "Này các Tỳ Kheo, nếu các du sĩ ngoại đạo có hỏi:",
  "sn54.11:2.3": "'Thưa hiền giả, Sa-môn Gotama thường trú với trú xứ nào trong mùa an cư?', khi được hỏi như vậy, này các Tỳ Kheo, các ông hãy trả lời cho các du sĩ ngoại đạo ấy như sau:",
  "sn54.11:2.4": "'Thưa hiền giả, Thế Tôn thường trú với định niệm hơi thở trong mùa an cư'.",
  "sn54.11:2.5": "Ở đây, này các Tỳ Kheo, Ta chánh niệm thở vào, chánh niệm thở ra.",
  "sn54.11:2.6": "Thở vào dài, Ta biết: 'Tôi thở vào dài'; thở ra dài, Ta biết: 'Tôi thở ra dài';",
  "sn54.11:2.7": "thở vào ngắn, Ta biết: 'Tôi thở vào ngắn'; thở ra ngắn, Ta biết: 'Tôi thở ra ngắn';",
  "sn54.11:2.8": "học tập: 'Cảm nhận toàn thân, tôi sẽ thở vào'... (rút gọn)...",
  "sn54.11:2.9": "Ta biết: 'Quán từ bỏ, tôi sẽ thở vào'; Ta biết: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.11:3.1": "Này các Tỳ Kheo, nếu ai nói đúng đắn rằng:",
  "sn54.11:3.2": "'trú xứ bậc thánh', hay 'phạm trú', hay 'trú xứ Như Lai'.",
  "sn54.11:3.3": "Nói đúng đắn về định niệm hơi thở, người đó sẽ nói:",
  "sn54.11:3.4": "'trú xứ bậc thánh', hay 'phạm trú', hay 'trú xứ Như Lai'.",
  "sn54.11:3.5": "Này các Tỳ Kheo, những Tỳ Kheo còn đang học tập, chưa đạt được tâm sở nguyện, đang sống hướng đến vô thượng an ổn khỏi ách, đối với họ, định niệm hơi thở được tu tập, được làm cho sung mãn, dẫn đến đoạn tận lậu hoặc.",
  "sn54.11:3.6": "Còn những Tỳ Kheo A-la-hán, lậu hoặc đã tận, phạm hạnh đã thành, việc cần làm đã làm, đã đặt gánh nặng xuống, đạt được mục đích, kiết sử đời sống đã diệt, được giải thoát bằng chánh trí, đối với họ, định niệm hơi thở được tu tập, được làm cho sung mãn, dẫn đến an lạc ngay trong đời hiện tại và đến niệm và tỉnh giác.",
  "sn54.11:4.1": "Này các Tỳ Kheo, nếu ai nói đúng đắn rằng:",
  "sn54.11:4.2": "'trú xứ bậc thánh', hay 'phạm trú', hay 'trú xứ Như Lai'.",
  "sn54.11:4.3": "Nói đúng đắn về định niệm hơi thở, người đó sẽ nói:",
  "sn54.11:4.4": "'trú xứ bậc thánh', hay 'phạm trú', hay 'trú xứ Như Lai'.'",
  "sn54.11:4.5": "Thứ nhất.",
  "sn54.13:0.1": "Tương Ưng Bộ Kinh 54.13",
  "sn54.13:0.2": "2. Phẩm Thứ Hai",
  "sn54.13:0.3": "Kinh Ānanda Thứ Nhất",
  "sn54.13:1.1": "Tại Sāvatthī.",
  "sn54.13:1.2": "Rồi Tôn giả Ānanda đến chỗ Thế Tôn; đến xong, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Khi ngồi xuống một bên, Tôn giả Ānanda thưa với Thế Tôn:",
  "sn54.13:1.3": "'Bạch Ngài, có pháp một nào, được tu tập, được làm cho sung mãn, làm viên mãn bốn pháp; bốn pháp được tu tập, được làm cho sung mãn, làm viên mãn bảy pháp; bảy pháp được tu tập, được làm cho sung mãn, làm viên mãn hai pháp không?'",
  "sn54.13:2.1": "'Này Ānanda, có pháp một, được tu tập, được làm cho sung mãn, làm viên mãn bốn pháp; bốn pháp được tu tập, được làm cho sung mãn, làm viên mãn bảy pháp; bảy pháp được tu tập, được làm cho sung mãn, làm viên mãn hai pháp.'",
  "sn54.13:3.1": "'Bạch Ngài, pháp một ấy là gì, được tu tập, được làm cho sung mãn, làm viên mãn bốn pháp; bốn pháp được tu tập, được làm cho sung mãn, làm viên mãn bảy pháp; bảy pháp được tu tập, được làm cho sung mãn, làm viên mãn hai pháp?'",
  "sn54.13:3.2": "Này Ānanda, định niệm hơi thở là một pháp, được tu tập, được làm cho sung mãn, làm viên mãn bốn niệm xứ; bốn niệm xứ được tu tập, được làm cho sung mãn, làm viên mãn bảy giác chi; bảy giác chi được tu tập, được làm cho sung mãn, làm viên mãn minh và giải thoát.",
  "sn54.13:4.1": "Này Ānanda, định niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, làm viên mãn bốn niệm xứ?",
  "sn54.13:4.2": "Này Ānanda, ở đây Tỳ Kheo đi đến khu rừng, hay đến gốc cây, hay đến căn nhà trống, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.13:4.3": "Vị ấy chánh niệm thở vào, chánh niệm thở ra.",
  "sn54.13:4.4": "Thở vào dài, vị ấy biết: 'Tôi thở vào dài'; thở ra dài, vị ấy biết: 'Tôi thở ra dài'... (rút gọn)...",
  "sn54.13:4.5": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.13:5.1": "Này Ānanda, vào lúc Tỳ Kheo thở vào dài, biết: 'Tôi thở vào dài'; thở ra dài, biết: 'Tôi thở ra dài';",
  "sn54.13:5.2": "thở vào ngắn... (rút gọn)...",
  "sn54.13:5.3": "học tập: 'An tịnh thân hành, tôi sẽ thở vào'; học tập: 'An tịnh thân hành, tôi sẽ thở ra'",
  "sn54.13:5.4": "vào lúc đó, này Ānanda, Tỳ Kheo trú quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.13:5.5": "Vì sao vậy?",
  "sn54.13:5.6": "Này Ānanda, Ta nói rằng đây là một loại thân, tức là hơi thở vào và hơi thở ra.",
  "sn54.13:5.7": "Vì vậy, này Ānanda, vào lúc đó Tỳ Kheo trú quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.13:6.1": "Này Ānanda, vào lúc Tỳ Kheo học tập: 'Cảm nhận hỷ, tôi sẽ thở vào',",
  "sn54.13:6.2": "cảm nhận lạc... (rút gọn)...",
  "sn54.13:6.3": "cảm nhận tâm hành...",
  "sn54.13:6.4": "học tập: 'An tịnh tâm hành, tôi sẽ thở vào'; học tập: 'An tịnh tâm hành, tôi sẽ thở ra'",
  "sn54.13:6.5": "vào lúc đó, này Ānanda, Tỳ Kheo trú quán thọ trên các thọ, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.13:6.6": "Vì sao vậy?",
  "sn54.13:6.7": "Này Ānanda, Ta nói rằng đây là một loại thọ, tức là sự khéo tác ý hơi thở vào và hơi thở ra.",
  "sn54.13:6.8": "Vì vậy, này Ānanda, vào lúc đó Tỳ Kheo trú quán thọ trên các thọ, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.13:7.1": "Này Ānanda, vào lúc Tỳ Kheo học tập: 'Cảm nhận tâm, tôi sẽ thở vào'; học tập: 'Cảm nhận tâm, tôi sẽ thở ra';",
  "sn54.13:7.2": "làm hân hoan tâm... (rút gọn)...",
  "sn54.13:7.3": "làm định tĩnh tâm...",
  "sn54.13:7.4": "học tập: 'Giải thoát tâm, tôi sẽ thở vào'; học tập: 'Giải thoát tâm, tôi sẽ thở ra'",
  "sn54.13:7.5": "vào lúc đó, này Ānanda, Tỳ Kheo trú quán tâm trên tâm, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.13:7.6": "Vì sao vậy?",
  "sn54.13:7.7": "Này Ānanda, Ta không nói rằng người mất chánh niệm, không tỉnh giác, có tu tập định niệm hơi thở.",
  "sn54.13:7.8": "Vì vậy, này Ānanda, vào lúc đó Tỳ Kheo trú quán tâm trên tâm, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.13:8.1": "Này Ānanda, vào lúc Tỳ Kheo quán vô thường... (rút gọn)...",
  "sn54.13:8.2": "quán ly tham...",
  "sn54.13:8.3": "quán đoạn diệt...",
  "sn54.13:8.4": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'",
  "sn54.13:8.5": "vào lúc đó, này Ānanda, Tỳ Kheo trú quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.13:8.6": "Vị ấy, sau khi với trí tuệ thấy sự đoạn trừ tham ưu, khéo tu tập xả.",
  "sn54.13:8.7": "Vì vậy, này Ānanda, vào lúc đó Tỳ Kheo trú quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.13:9.1": "Này Ānanda, định niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, làm viên mãn bốn niệm xứ.",
  "sn54.13:10.1": "Này Ānanda, bốn niệm xứ được tu tập như thế nào, được làm cho sung mãn như thế nào, làm viên mãn bảy giác chi?",
  "sn54.13:10.2": "Này Ānanda, vào lúc Tỳ Kheo trú quán thân trên thân",
  "sn54.13:10.3": "vào lúc đó, niệm của Tỳ Kheo hiện diện không bị quên lãng.",
  "sn54.13:10.4": "Này Ānanda, vào lúc niệm của Tỳ Kheo hiện diện không bị quên lãngniệm giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập niệm giác chi, niệm giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.13:11.1": "Vị ấy trú với chánh niệm như vậy, dùng trí tuệ tìm hiểu, khảo sát, thẩm tra pháp ấy.",
  "sn54.13:11.2": "Này Ānanda, vào lúc Tỳ Kheo trú với chánh niệm như vậy, dùng trí tuệ tìm hiểu, khảo sát, thẩm tra pháp ấy",
  "sn54.13:11.3": "trạch pháp giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập trạch pháp giác chi, trạch pháp giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.13:12.1": "Đối với vị đang dùng trí tuệ tìm hiểu, khảo sát, thẩm tra pháp ấy, tinh tấn không thụ động được khởi đầu.",
  "sn54.13:12.2": "Này Ānanda, vào lúc tinh tấn không thụ động của Tỳ Kheo đang dùng trí tuệ tìm hiểu, khảo sát, thẩm tra pháp ấy được khởi đầu",
  "sn54.13:12.3": "tinh tấn giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập tinh tấn giác chi, tinh tấn giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.13:13.1": "Đối với người đã khởi tinh tấn, hỷ không liên hệ vật chất sinh khởi.",
  "sn54.13:13.2": "Này Ānanda, vào lúc hỷ không liên hệ vật chất sinh khởi đối với Tỳ Kheo đã khởi tinh tấn",
  "sn54.13:13.3": "hỷ giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập hỷ giác chi, hỷ giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.13:14.1": "Với tâm đầy hỷ, cả thân và tâm được khinh an.",
  "sn54.13:14.2": "Này Ānanda, vào lúc cả thân và tâm của Tỳ Kheo tâm đầy hỷ được khinh an",
  "sn54.13:14.3": "khinh an giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập khinh an giác chi, khinh an giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.13:15.1": "Với thân được khinh an, người có lạc, tâm được định.",
  "sn54.13:15.2": "Này Ānanda, vào lúc tâm của Tỳ Kheo có thân được khinh an và có lạc được định",
  "sn54.13:15.3": "định giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập định giác chi, định giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.13:16.1": "Vị ấy với tâm đã định như vậy, khéo tu tập xả.",
  "sn54.13:16.2": "Này Ānanda, vào lúc Tỳ Kheo với tâm đã định như vậy khéo tu tập xả",
  "sn54.13:16.3": "xả giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập xả giác chi, xả giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.13:17.1": "Này Ānanda, vào lúc Tỳ Kheo trú quán thọ trên các thọ... (rút gọn)...",
  "sn54.13:17.2": "trên tâm... (rút gọn)...",
  "sn54.13:17.3": "quán pháp trên các pháp",
  "sn54.13:17.4": "vào lúc đó, niệm của Tỳ Kheo hiện diện không bị quên lãng.",
  "sn54.13:17.5": "Này Ānanda, vào lúc niệm của Tỳ Kheo hiện diện không bị quên lãng",
  "sn54.13:17.6": "niệm giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập niệm giác chi, niệm giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.13:17.7": "(Như đối với niệm xứ thứ nhất, hãy trình bày chi tiết tương tự.)",
  "sn54.13:18.1": "Vị ấy với tâm đã định như vậy, khéo tu tập xả.",
  "sn54.13:18.2": "Này Ānanda, vào lúc Tỳ Kheo với tâm đã định như vậy khéo tu tập xả",
  "sn54.13:18.3": "xả giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập xả giác chi, xả giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.13:18.4": "Này Ānanda, bốn niệm xứ được tu tập như vậy, được làm cho sung mãn như vậy, làm viên mãn bảy giác chi.",
  "sn54.13:19.1": "Này Ānanda, bảy giác chi được tu tập như thế nào, được làm cho sung mãn như thế nào, làm viên mãn minh và giải thoát?",
  "sn54.13:19.2": "Này Ānanda, ở đây Tỳ Kheo tu tập niệm giác chi, y cứ viễn ly, y cứ ly tham, y cứ đoạn diệt, hướng đến xả ly,",
  "sn54.13:19.3": "tu tập trạch pháp giác chi... (rút gọn)...",
  "sn54.13:19.4": "tu tập xả giác chi, y cứ viễn ly, y cứ ly tham, y cứ đoạn diệt, hướng đến xả ly.",
  "sn54.13:19.5": "'Này Ānanda, bảy giác chi được tu tập như vậy, được làm cho sung mãn như vậy, làm viên mãn minh và giải thoát.'",
  "sn54.13:19.6": "Thứ ba.",
  "sn54.14:0.1": "Tương Ưng Bộ Kinh 54.14",
  "sn54.14:0.2": "2. Phẩm Thứ Hai",
  "sn54.14:0.3": "Kinh Ānanda Thứ Hai",
  "sn54.14:1.1": "Rồi Tôn giả Ānanda đến chỗ Thế Tôn; đến xong, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Khi Tôn giả Ānanda đang ngồi một bên, Thế Tôn nói với Ngài:",
  "sn54.14:1.2": "'Này Ānanda, có pháp một nào, được tu tập, được làm cho sung mãn, làm viên mãn bốn pháp; bốn pháp được tu tập, được làm cho sung mãn, làm viên mãn bảy pháp; bảy pháp được tu tập, được làm cho sung mãn, làm viên mãn hai pháp không?'",
  "sn54.14:1.3": "Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản... (rút gọn)...",
  "sn54.14:1.4": "Này Ānanda, có pháp một, được tu tập, được làm cho sung mãn, làm viên mãn bốn pháp; bốn pháp được tu tập, được làm cho sung mãn, làm viên mãn bảy pháp; bảy pháp được tu tập, được làm cho sung mãn, làm viên mãn hai pháp.",
  "sn54.14:2.1": "Này Ānanda, pháp một ấy là gì, được tu tập, được làm cho sung mãn, làm viên mãn bốn pháp; bốn pháp được tu tập, được làm cho sung mãn, làm viên mãn bảy pháp; bảy pháp được tu tập, được làm cho sung mãn, làm viên mãn hai pháp?",
  "sn54.14:2.2": "Này Ānanda, định niệm hơi thở là một pháp, được tu tập, được làm cho sung mãn, làm viên mãn bốn niệm xứ; bốn niệm xứ được tu tập, được làm cho sung mãn, làm viên mãn bảy giác chi; bảy giác chi được tu tập, được làm cho sung mãn, làm viên mãn minh và giải thoát.",
  "sn54.14:2.3": "Này Ānanda, định niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, làm viên mãn bốn niệm xứ?",
  "sn54.14:2.4": "Này Ānanda, ở đây Tỳ Kheo đi đến khu rừng, hay đến gốc cây... (rút gọn)...",
  "sn54.14:2.5": "'Này Ānanda, bảy giác chi được tu tập như vậy, được làm cho sung mãn như vậy, làm viên mãn minh và giải thoát.'",
  "sn54.14:2.6": "Thứ tư.",
  "sn54.15:0.1": "Tương Ưng Bộ Kinh 54.15",
  "sn54.15:0.2": "2. Phẩm Thứ Hai",
  "sn54.15:0.3": "Kinh Các Tỳ Kheo Thứ Nhất",
  "sn54.15:1.1": "Rồi nhiều Tỳ Kheo đến chỗ Thế Tôn; đến xong, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Khi ngồi xuống một bên, các Tỳ Kheo ấy thưa với Thế Tôn:",
  "sn54.15:1.2": "'Bạch Ngài, có pháp một nào, được tu tập, được làm cho sung mãn, làm viên mãn bốn pháp; bốn pháp được tu tập, được làm cho sung mãn, làm viên mãn bảy pháp; bảy pháp được tu tập, được làm cho sung mãn, làm viên mãn hai pháp không?'",
  "sn54.15:1.3": "'Này các Tỳ Kheo, có pháp một, được tu tập, được làm cho sung mãn, làm viên mãn bốn pháp; bốn pháp được tu tập, được làm cho sung mãn, làm viên mãn bảy pháp; bảy pháp được tu tập, được làm cho sung mãn, làm viên mãn hai pháp.'",
  "sn54.15:2.1": "'Bạch Ngài, pháp một ấy là gì, được tu tập, được làm cho sung mãn, làm viên mãn bốn pháp; bốn pháp được tu tập, được làm cho sung mãn, làm viên mãn bảy pháp; bảy pháp được tu tập, được làm cho sung mãn, làm viên mãn hai pháp?'",
  "sn54.15:2.2": "Này các Tỳ Kheo, định niệm hơi thở là một pháp, được tu tập, được làm cho sung mãn, làm viên mãn bốn niệm xứ; bốn niệm xứ được tu tập, được làm cho sung mãn, làm viên mãn bảy giác chi; bảy giác chi được tu tập, được làm cho sung mãn, làm viên mãn minh và giải thoát.",
  "sn54.15:3.1": "Này các Tỳ Kheo, định niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, làm viên mãn bốn niệm xứ?",
  "sn54.15:3.2": "Này các Tỳ Kheo, ở đây Tỳ Kheo đi đến khu rừng, hay đến gốc cây... (rút gọn)...",
  "sn54.15:3.3": "'Này các Tỳ Kheo, bảy giác chi được tu tập như vậy, được làm cho sung mãn như vậy, làm viên mãn minh và giải thoát.'",
  "sn54.15:3.4": "Thứ năm.",
  "sn54.16:0.1": "Tương Ưng Bộ Kinh 54.16",
  "sn54.16:0.2": "2. Phẩm Thứ Hai",
  "sn54.16:0.3": "Kinh Các Tỳ Kheo Thứ Hai",
  "sn54.16:1.1": "Rồi nhiều Tỳ Kheo đến chỗ Thế Tôn; đến xong, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Khi các Tỳ Kheo ấy đang ngồi một bên, Thế Tôn nói với họ:",
  "sn54.16:1.2": "'Này các Tỳ Kheo, có pháp một nào, được tu tập, được làm cho sung mãn, làm viên mãn bốn pháp; bốn pháp được tu tập, được làm cho sung mãn, làm viên mãn bảy pháp; bảy pháp được tu tập, được làm cho sung mãn, làm viên mãn hai pháp không?'",
  "sn54.16:1.3": "'Bạch Thế Tôn, các pháp của chúng con lấy Thế Tôn làm căn bản... (rút gọn)... sau khi nghe từ Thế Tôn, các Tỳ Kheo sẽ ghi nhớ.'",
  "sn54.16:1.4": "Này các Tỳ Kheo, có pháp một, được tu tập, được làm cho sung mãn, làm viên mãn bốn pháp; bốn pháp được tu tập, được làm cho sung mãn, làm viên mãn bảy pháp; bảy pháp được tu tập, được làm cho sung mãn, làm viên mãn hai pháp.",
  "sn54.16:2.1": "Này các Tỳ Kheo, pháp một ấy là gì, được tu tập, được làm cho sung mãn, làm viên mãn bốn pháp; bốn pháp được tu tập, được làm cho sung mãn, làm viên mãn bảy pháp; bảy pháp được tu tập, được làm cho sung mãn, làm viên mãn hai pháp?",
  "sn54.16:2.2": "Này các Tỳ Kheo, định niệm hơi thở là một pháp, được tu tập, được làm cho sung mãn, làm viên mãn bốn niệm xứ; bốn niệm xứ được tu tập, được làm cho sung mãn, làm viên mãn bảy giác chi; bảy giác chi được tu tập, được làm cho sung mãn, làm viên mãn minh và giải thoát.",
  "sn54.16:3.1": "Này các Tỳ Kheo, định niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, làm viên mãn bốn niệm xứ?",
  "sn54.16:3.2": "Này các Tỳ Kheo, ở đây Tỳ Kheo đi đến khu rừng, hay đến gốc cây, hay đến căn nhà trống, ngồi kiết già, lưng thẳng, và an trú chánh niệm trước mặt.",
  "sn54.16:3.3": "Vị ấy chánh niệm thở vào, chánh niệm thở ra... (rút gọn)...",
  "sn54.16:3.4": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.16:4.1": "Này các Tỳ Kheo, vào lúc Tỳ Kheo thở vào dài, biết: 'Tôi thở vào dài'; thở ra dài, biết: 'Tôi thở ra dài'; thở vào ngắn, biết: 'Tôi thở vào ngắn'... (rút gọn)...",
  "sn54.16:4.2": "cảm nhận toàn thân... (rút gọn)...",
  "sn54.16:4.3": "học tập: 'An tịnh thân hành, tôi sẽ thở vào'; học tập: 'An tịnh thân hành, tôi sẽ thở ra'",
  "sn54.16:4.4": "vào lúc đó, này các Tỳ Kheo, Tỳ Kheo trú quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.16:4.5": "Vì sao vậy?",
  "sn54.16:4.6": "Này các Tỳ Kheo, Ta nói rằng đây là một loại thân, tức là hơi thở vào và hơi thở ra.",
  "sn54.16:4.7": "Vì vậy, này các Tỳ Kheo, vào lúc đó Tỳ Kheo trú quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.16:5.1": "Này các Tỳ Kheo, vào lúc Tỳ Kheo cảm nhận hỷ... (rút gọn)...",
  "sn54.16:5.2": "cảm nhận lạc...",
  "sn54.16:5.3": "cảm nhận tâm hành...",
  "sn54.16:5.4": "học tập: 'An tịnh tâm hành, tôi sẽ thở vào'; học tập: 'An tịnh tâm hành, tôi sẽ thở ra'",
  "sn54.16:5.5": "vào lúc đó, này các Tỳ Kheo, Tỳ Kheo trú quán thọ trên các thọ, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.16:5.6": "Vì sao vậy?",
  "sn54.16:5.7": "Này các Tỳ Kheo, Ta nói rằng đây là một loại thọ, tức là sự khéo tác ý hơi thở vào và hơi thở ra.",
  "sn54.16:5.8": "Vì vậy, này các Tỳ Kheo, vào lúc đó Tỳ Kheo trú quán thọ trên các thọ, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.16:6.1": "Này các Tỳ Kheo, vào lúc Tỳ Kheo cảm nhận tâm... (rút gọn)...",
  "sn54.16:6.2": "làm hân hoan tâm... (rút gọn)...",
  "sn54.16:6.3": "học tập: 'Làm định tĩnh tâm, tôi sẽ thở vào'; học tập: 'Làm định tĩnh tâm, tôi sẽ thở ra';",
  "sn54.16:6.4": "học tập: 'Giải thoát tâm, tôi sẽ thở vào'; học tập: 'Giải thoát tâm, tôi sẽ thở ra'",
  "sn54.16:6.5": "vào lúc đó, này các Tỳ Kheo, Tỳ Kheo trú quán tâm trên tâm, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.16:6.6": "Vì sao vậy?",
  "sn54.16:6.7": "Này các Tỳ Kheo, Ta không nói rằng người mất chánh niệm, không tỉnh giác, có tu tập định niệm hơi thở.",
  "sn54.16:6.8": "Vì vậy, này các Tỳ Kheo, vào lúc đó Tỳ Kheo trú quán tâm trên tâm, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.16:7.1": "Này các Tỳ Kheo, vào lúc Tỳ Kheo quán vô thường... (rút gọn)...",
  "sn54.16:7.2": "quán ly tham... (rút gọn)...",
  "sn54.16:7.3": "quán đoạn diệt... (rút gọn)...",
  "sn54.16:7.4": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'",
  "sn54.16:7.5": "vào lúc đó, này các Tỳ Kheo, Tỳ Kheo trú quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.16:7.6": "Vị ấy, sau khi với trí tuệ thấy sự đoạn trừ tham ưu, khéo tu tập xả.",
  "sn54.16:7.7": "Vì vậy, này các Tỳ Kheo, vào lúc đó Tỳ Kheo trú quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, loại bỏ tham ưu ở đời.",
  "sn54.16:8.1": "Này các Tỳ Kheo, định niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, làm viên mãn bốn niệm xứ.",
  "sn54.16:9.1": "Này các Tỳ Kheo, bốn niệm xứ được tu tập như thế nào, được làm cho sung mãn như thế nào, làm viên mãn bảy giác chi?",
  "sn54.16:9.2": "Này các Tỳ Kheo, vào lúc Tỳ Kheo trú quán thân trên thânvào lúc đó, niệm của Tỳ Kheo hiện diện không bị quên lãng.",
  "sn54.16:9.3": "Này các Tỳ Kheo, vào lúc niệm của Tỳ Kheo hiện diện không bị quên lãng",
  "sn54.16:9.4": "niệm giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập niệm giác chi, niệm giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.16:10.1": "Vị ấy trú với chánh niệm như vậy, dùng trí tuệ tìm hiểu, khảo sát, thẩm tra pháp ấy.",
  "sn54.16:10.2": "Này các Tỳ Kheo, vào lúc Tỳ Kheo trú với chánh niệm như vậy, dùng trí tuệ tìm hiểu, khảo sát, thẩm tra pháp ấy",
  "sn54.16:10.3": "trạch pháp giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập trạch pháp giác chi, trạch pháp giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.16:11.1": "Đối với vị đang dùng trí tuệ tìm hiểu, khảo sát, thẩm tra pháp ấy, tinh tấn không thụ động được khởi đầu.",
  "sn54.16:11.2": "Này các Tỳ Kheo, vào lúc tinh tấn không thụ động của Tỳ Kheo đang dùng trí tuệ tìm hiểu, khảo sát, thẩm tra pháp ấy được khởi đầu",
  "sn54.16:11.3": "tinh tấn giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập tinh tấn giác chi, tinh tấn giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.16:12.1": "Đối với người đã khởi tinh tấn, hỷ không liên hệ vật chất sinh khởi.",
  "sn54.16:12.2": "Này các Tỳ Kheo, vào lúc hỷ không liên hệ vật chất sinh khởi đối với Tỳ Kheo đã khởi tinh tấn",
  "sn54.16:12.3": "hỷ giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập hỷ giác chi, hỷ giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.16:13.1": "Với tâm đầy hỷ, cả thân và tâm được khinh an.",
  "sn54.16:13.2": "Này các Tỳ Kheo, vào lúc cả thân và tâm của Tỳ Kheo tâm đầy hỷ được khinh an",
  "sn54.16:13.3": "khinh an giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập khinh an giác chi, khinh an giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.16:14.1": "Với thân được khinh an, người có lạc, tâm được định.",
  "sn54.16:14.2": "Này các Tỳ Kheo, vào lúc tâm của Tỳ Kheo có thân được khinh an và có lạc được định",
  "sn54.16:14.3": "định giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập định giác chi, định giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.16:15.1": "Vị ấy với tâm đã định như vậy, khéo tu tập xả.",
  "sn54.16:15.2": "Này các Tỳ Kheo, vào lúc Tỳ Kheo với tâm đã định như vậy khéo tu tập xả",
  "sn54.16:15.3": "xả giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập xả giác chi, xả giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.16:16.1": "Này các Tỳ Kheo, vào lúc Tỳ Kheo trú quán thọ trên các thọ... (rút gọn)...",
  "sn54.16:16.2": "trên tâm... (rút gọn)...",
  "sn54.16:16.3": "quán pháp trên các phápvào lúc đó, niệm của Tỳ Kheo hiện diện không bị quên lãng.",
  "sn54.16:16.4": "Này các Tỳ Kheo, vào lúc niệm của Tỳ Kheo hiện diện không bị quên lãng",
  "sn54.16:16.5": "niệm giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập niệm giác chiniệm giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập... (rút gọn)...",
  "sn54.16:17.1": "Vị ấy với tâm đã định như vậy, khéo tu tập xả.",
  "sn54.16:17.2": "Này các Tỳ Kheo, vào lúc Tỳ Kheo với tâm đã định như vậy khéo tu tập xả",
  "sn54.16:17.3": "xả giác chi vào lúc đó của Tỳ Kheo được khởi đầu, Tỳ Kheo tu tập xả giác chi, xả giác chi của Tỳ Kheo vào lúc đó đi đến viên mãn tu tập.",
  "sn54.16:17.4": "Này các Tỳ Kheo, bốn niệm xứ được tu tập như vậy, được làm cho sung mãn như vậy, làm viên mãn bảy giác chi.",
  "sn54.16:18.1": "Này các Tỳ Kheo, bảy giác chi được tu tập như thế nào, được làm cho sung mãn như thế nào, làm viên mãn minh và giải thoát?",
  "sn54.16:18.2": "Này các Tỳ Kheo, ở đây Tỳ Kheo tu tập niệm giác chi, y cứ viễn ly, y cứ ly tham, y cứ đoạn diệt, hướng đến xả ly;",
  "sn54.16:18.3": "tu tập trạch pháp giác chi, y cứ viễn ly, y cứ ly tham, y cứ đoạn diệt, hướng đến xả ly... (rút gọn)...",
  "sn54.16:18.4": "tu tập xả giác chi, y cứ viễn ly, y cứ ly tham, y cứ đoạn diệt, hướng đến xả ly.",
  "sn54.16:18.5": "'Này các Tỳ Kheo, bảy giác chi được tu tập như vậy, được làm cho sung mãn như vậy, làm viên mãn minh và giải thoát.'",
  "sn54.16:18.6": "Thứ sáu.",
  "sn54.17:0.1": "Tương Ưng Bộ Kinh 54.17",
  "sn54.17:0.2": "2. Phẩm Thứ Hai",
  "sn54.17:0.3": "Kinh Đoạn Trừ Kiết Sử",
  "sn54.17:1.1": "Này các Tỳ Kheo, định niệm hơi thở được tu tập, được làm cho sung mãn, dẫn đến đoạn trừ kiết sử... (rút gọn)...",
  "sn54.17:1.2": "Thứ bảy.",
  "sn54.18:0.1": "Tương Ưng Bộ Kinh 54.18",
  "sn54.18:0.2": "2. Phẩm Thứ Hai",
  "sn54.18:0.3": "Kinh Nhổ Bật Gốc Tùy Miên",
  "sn54.18:1.1": "... Dẫn đến nhổ bật gốc tùy miên...",
  "sn54.18:1.2": "Thứ tám.",
  "sn54.19:0.1": "Tương Ưng Bộ Kinh 54.19",
  "sn54.19:0.2": "2. Phẩm Thứ Hai",
  "sn54.19:0.3": "Kinh Liễu Tri Con Đường",
  "sn54.19:1.1": "... Dẫn đến liễu tri con đường...",
  "sn54.19:1.2": "Thứ chín.",
  "sn54.20:0.1": "Tương Ưng Bộ Kinh 54.20",
  "sn54.20:0.2": "2. Phẩm Thứ Hai",
  "sn54.20:0.3": "Kinh Đoạn Tận Lậu Hoặc",
  "sn54.20:1.1": "... Dẫn đến đoạn tận lậu hoặc.",
  "sn54.20:1.2": "Này các Tỳ Kheo, định niệm hơi thở được tu tập như thế nào, được làm cho sung mãn như thế nào, dẫn đến đoạn trừ kiết sử...",
  "sn54.20:1.3": "dẫn đến nhổ bật gốc tùy miên...",
  "sn54.20:1.4": "dẫn đến liễu tri con đường...",
  "sn54.20:1.5": "dẫn đến đoạn tận lậu hoặc?",
  "sn54.20:1.6": "Ở đây, này các Tỳ Kheo, Tỳ Kheo đi đến khu rừng, hay đến gốc cây... (rút gọn)...",
  "sn54.20:1.7": "học tập: 'Quán từ bỏ, tôi sẽ thở vào'; học tập: 'Quán từ bỏ, tôi sẽ thở ra'.",
  "sn54.20:1.8": "Này các Tỳ Kheo, khi định niệm hơi thở được tu tập như vậy, được làm cho sung mãn như vậy, dẫn đến đoạn trừ kiết sử... (rút gọn)...",
  "sn54.20:1.9": "dẫn đến nhổ bật gốc tùy miên... (rút gọn)...",
  "sn54.20:1.10": "dẫn đến liễu tri con đường... (rút gọn)...",
  "sn54.20:1.11": "'dẫn đến đoạn tận lậu hoặc.'",
  "sn54.20:1.12": "Thứ mười.",
  "sn54.20:1.13": "Phẩm Thứ Hai.",
  "sn54.20:2.0": "Tóm tắt phẩm:",
  "sn54.20:2.1": "Icchānaṅgala, Kaṅkheyya,",
  "sn54.20:2.2": "hai kinh Ānanda khác;",
  "sn54.20:2.3": "Các Tỳ Kheo, kiết sử, tùy miên,",
  "sn54.20:2.4": "con đường, đoạn tận lậu hoặc.",
  "sn54.20:2.5": "Đây là Tương Ưng Hơi Thở, phần thứ mười."
}
window.BILARA["sn54_v1"]["vi"]["sn54_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
