window.BILARA = window.BILARA || {};
window.BILARA["sn7_v1"] = window.BILARA["sn7_v1"] || {};
window.BILARA["sn7_v1"]["vi"] = {
  "sn7.1:0.1": "Tương Ưng Bộ 7.1 ",
  "sn7.1:0.2": "1. Phẩm A-la-hán ",
  "sn7.1:0.3": "Kinh Dhanañjānī ",
  "sn7.1:1.1": "Tôi nghe như vầy ",
  "sn7.1:1.2": "Một thời, Thế Tôn trú tại Vương Xá, trong Trúc Lâm, chỗ nuôi dưỡng sóc. ",
  "sn7.1:1.3": "Lúc bấy giờ, người vợ bà-la-môn tên Dhanañjānī của một vị bà-la-môn dòng họ Bhāradvāja có niềm tin sâu sắc vào Đức Phật, Pháp và Tăng. ",
  "sn7.1:1.4": "Khi đang mang thức ăn dâng cho vị bà-la-môn Bhāradvāja, bà Dhanañjānī vấp ngã và thốt lên lời cảm kích ba lần: ",
  "sn7.1:2.1": "'Kính lễ Thế Tôn, bậc A-la-hán, Đấng Toàn Giác! '",
  "sn7.1:3.1": "Kính lễ Thế Tôn, bậc A-la-hán, Đấng Toàn Giác! ",
  "sn7.1:4.1": "Kính lễ Thế Tôn, bậc A-la-hán, Đấng Toàn Giác!' ",
  "sn7.1:5.1": "Nghe vậy, vị bà-la-môn Bhāradvāja nói với bà Dhanañjānī: ",
  "sn7.1:5.2": "'Kẻ tiện dân này cứ ca ngợi vị sa-môn đầu trọc đó khắp nơi. '",
  "sn7.1:5.3": "Này kẻ tiện dân, nay ta sẽ đi bác bỏ lời của vị thầy đó!' ",
  "sn7.1:5.4": "'Thưa Bà-la-môn, tôi không thấy ai trong thế giới gồm trời, ma, Phạm thiên, cùng sa-môn, bà-la-môn, trời và người, có thể bác bỏ lời của Thế Tôn, bậc A-la-hán, Đấng Toàn Giác. '",
  "sn7.1:5.5": "Nhưng thưa Bà-la-môn, ông cứ đi rồi sẽ tự biết.' ",
  "sn7.1:6.1": "Vị bà-la-môn Bhāradvāja tức giận, bất mãn, đi đến gặp Thế Tôn; sau khi đến, chào hỏi thân mật với Ngài. ",
  "sn7.1:6.2": "Sau khi trao đổi những lời thân ái đáng nhớ, ngồi xuống một bên. ",
  "sn7.1:6.3": "Ngồi một bên, vị bà-la-môn Bhāradvāja đọc bài kệ thưa với Thế Tôn: ",
  "sn7.1:7.1": "'Cắt đứt cái gì mà được an lạc, '",
  "sn7.1:7.2": "Cắt đứt cái gì mà không sầu khổ; ",
  "sn7.1:7.3": "Diệt trừ một pháp nào, ",
  "sn7.1:7.4": "Ngài tán thán, thưa Gotama?' ",
  "sn7.1:8.1": "'Cắt đứt sân hận mà được an lạc, '",
  "sn7.1:8.2": "Cắt đứt sân hận mà không sầu khổ; ",
  "sn7.1:8.3": "Sân hận có gốc rễ độc hại, ",
  "sn7.1:8.4": "Ngọn lại ngọt ngào, thưa Bà-la-môn; ",
  "sn7.1:8.5": "Bậc thánh tán thán sự diệt trừ nó, ",
  "sn7.1:8.6": "Vì cắt đứt nó thì không còn sầu khổ.' ",
  "sn7.1:9.1": "Nghe vậy, vị bà-la-môn Bhāradvāja nói với Thế Tôn: ",
  "sn7.1:9.2": "'Thật vi diệu, thưa Gotama! Thật vi diệu, thưa Gotama! '",
  "sn7.1:9.3": "Ví như người dựng đứng lại những gì bị lật úp, hay mở ra những gì bị che kín, hay chỉ đường cho người bị lạc, hay thắp đèn dầu trong bóng tối để những ai có mắt có thể thấy sắc; cũng vậy, Pháp đã được Ngài Gotama trình bày bằng nhiều phương cách. ",
  "sn7.1:9.4": "Con xin quy y Thế Tôn Gotama, Pháp và Tăng đoàn Tỳ Kheo. ",
  "sn7.1:9.5": "Mong con được xuất gia, được thọ đại giới từ Ngài Gotama.' ",
  "sn7.1:10.1": "Vị bà-la-môn Bhāradvāja được xuất gia, được thọ đại giới từ Thế Tôn. ",
  "sn7.1:10.2": "Sau khi thọ đại giới không lâu, Tôn giả Bhāradvāja sống một mình, viễn ly, không phóng dật, nhiệt tâm, tinh cần, không bao lâuvì mục đích tối thượng mà các thiện nam tử xuất gia từ gia đình đến chỗ không gia đìnhđạt được vô thượng phạm hạnh, ngay trong hiện tại, tự mình chứng ngộ và an trú. ",
  "sn7.1:10.3": "'Sinh đã tận, phạm hạnh đã sống, việc cần làm đã làm, không còn trở lại đời này nữa,' vị ấy biết vậy. ",
  "sn7.1:10.4": "Tôn giả Bhāradvāja trở thành một trong những bậc A-la-hán. ",
  "sn7.2:0.1": "Tương Ưng Bộ 7.2 ",
  "sn7.2:0.2": "1. Phẩm A-la-hán ",
  "sn7.2:0.3": "Kinh Bị Chửi Mắng ",
  "sn7.2:1.1": "Một thời, Thế Tôn trú tại Vương Xá, trong Trúc Lâm, chỗ nuôi dưỡng sóc. ",
  "sn7.2:1.2": "Bà-la-môn Akkosaka Bhāradvāja nghe tin: ",
  "sn7.2:2.1": "'Nghe nói bà-la-môn Bhāradvāja đã xuất gia theo sa-môn Gotama.' Tức giận, bất mãn, ông đến gặp Thế Tôn; sau khi đến, ông chửi mắng Thế Tôn bằng những lời thô lỗ, thậm tệ. Nghe vậy, Thế Tôn nói với bà-la-môn Akkosaka Bhāradvāja: ",
  "sn7.2:2.2": "'Này Bà-la-môn, ông nghĩ sao, '",
  "sn7.2:2.3": "đôi khi có bạn bè, thân quyến, khách khứa đến nhà ông không?' ",
  "sn7.2:2.4": "'Thưa Gotama, đôi khi có.' ",
  "sn7.2:2.5": "'Này Bà-la-môn, ông có dọn thức ăn, đồ nhắm, món ngon cho họ không?' ",
  "sn7.2:2.6": "'Thưa Gotama, đôi khi tôi có dọn.' ",
  "sn7.2:2.7": "'Nếu họ không nhận, thì đồ ăn đó thuộc về ai?' ",
  "sn7.2:2.8": "'Thưa Gotama, nếu họ không nhận, thì đồ ăn đó vẫn thuộc về chúng tôi.' ",
  "sn7.2:2.9": "'Cũng vậy, này Bà-la-môn, ông chửi mắng ta khi ta không chửi lại, ông giận dữ ta khi ta không giận, ông cãi vã ta khi ta không cãi, ta không nhận những điều đó. '",
  "sn7.2:2.10": "Vậy chúng vẫn thuộc về ông, ",
  "sn7.2:2.11": "Chúng vẫn thuộc về ông, này Bà-la-môn. ",
  "sn7.2:3.1": "Này Bà-la-môn, kẻ nào chửi lại người chửi mắng mình, giận lại người đang giận, cãi lại người đang cãi, kẻ đó được gọi là cùng ăn chung, cùng chịu đựng chung. ",
  "sn7.2:3.2": "Ta không cùng ăn chung, không cùng chịu đựng chung với ông. ",
  "sn7.2:3.3": "Vậy chúng vẫn thuộc về ông, ",
  "sn7.2:3.4": "Chúng vẫn thuộc về ông, này Bà-la-môn.' ",
  "sn7.2:3.5": "'Nhưng mọi người, kể cả vua, đều biết rằng: '",
  "sn7.2:3.6": "'Sa-môn Gotama là bậc A-la-hán.' ",
  "sn7.2:3.7": "Vậy mà Ngài Gotama lại nổi giận?' ",
  "sn7.2:4.1": "'Người không giận, làm sao có giận, '",
  "sn7.2:4.2": "Người đã điều phục, sống đời quân bình; ",
  "sn7.2:4.3": "Người giải thoát với chánh trí, ",
  "sn7.2:4.4": "An tịnh, bình thản như vậy. ",
  "sn7.2:5.1": "Kẻ nào giận trả giận, ",
  "sn7.2:5.2": "Kẻ đó càng tồi tệ hơn người kia; ",
  "sn7.2:5.3": "Người không giận trả lại kẻ giận, ",
  "sn7.2:5.4": "Chiến thắng trận chiến khó thắng. ",
  "sn7.2:6.1": "Người đó mang lợi ích cho cả hai, ",
  "sn7.2:6.2": "Cho mình và cho người kia; ",
  "sn7.2:6.3": "Biết người kia đang tức giận, ",
  "sn7.2:6.4": "Người có chánh niệm giữ tâm an tịnh. ",
  "sn7.2:7.1": "Người chữa lành cho cả hai, ",
  "sn7.2:7.2": "Cho mình và cho người kia; ",
  "sn7.2:7.3": "Những ai không hiểu Pháp, ",
  "sn7.2:7.4": "Họ tưởng người đó là kẻ ngu.' ",
  "sn7.2:8.1": "Nghe vậy, bà-la-môn Akkosaka Bhāradvāja nói với Thế Tôn: ",
  "sn7.2:8.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.2:8.3": "Con xin quy y Ngài Gotama, Pháp và Tăng đoàn Tỳ Kheo. ",
  "sn7.2:8.4": "Mong con được xuất gia, được thọ đại giới từ Ngài Gotama.' ",
  "sn7.2:9.1": "Bà-la-môn Akkosaka Bhāradvāja được xuất gia, được thọ đại giới từ Thế Tôn. ",
  "sn7.2:9.2": "Sau khi thọ đại giới không lâu, Tôn giả Akkosaka Bhāradvāja sống một mình, viễn ly, không phóng dật, nhiệt tâm, tinh cần, không bao lâuvì mục đích tối thượng mà các thiện nam tử xuất gia từ gia đình đến chỗ không gia đìnhđạt được vô thượng phạm hạnh, ngay trong hiện tại, tự mình chứng ngộ và an trú. ",
  "sn7.2:9.3": "'Sinh đã tận, phạm hạnh đã sống, việc cần làm đã làm, không còn trở lại đời này nữa,' vị ấy biết vậy. ",
  "sn7.2:9.4": "Tôn giả Bhāradvāja trở thành một trong những bậc A-la-hán. ",
  "sn7.3:0.1": "Tương Ưng Bộ 7.3 ",
  "sn7.3:0.2": "1. Phẩm A-la-hán ",
  "sn7.3:0.3": "Kinh Asurindaka ",
  "sn7.3:1.1": "Một thời, Thế Tôn trú tại Vương Xá, trong Trúc Lâm, chỗ nuôi dưỡng sóc. ",
  "sn7.3:1.2": "Bà-la-môn Asurindaka Bhāradvāja nghe tin: ",
  "sn7.3:1.3": "'Nghe nói bà-la-môn Bhāradvāja đã xuất gia theo sa-môn Gotama.' Tức giận, bất mãn, ông đến gặp Thế Tôn; sau khi đến, ông chửi mắng Thế Tôn bằng những lời thô lỗ, thậm tệ. ",
  "sn7.3:1.4": "Nghe vậy, Thế Tôn im lặng. ",
  "sn7.3:1.5": "Bà-la-môn Asurindaka Bhāradvāja nói với Thế Tôn: ",
  "sn7.3:1.6": "'Sa-môn thua rồi! Sa-môn thua rồi!' ",
  "sn7.3:2.1": "'Kẻ ngu tưởng mình thắng, '",
  "sn7.3:2.2": "Khi buông lời thô ác; ",
  "sn7.3:2.3": "Nhưng thực ra chiến thắng, ",
  "sn7.3:2.4": "Là nhẫn nhục của người trí. ",
  "sn7.3:3.1": "Kẻ nào giận trả giận, ",
  "sn7.3:3.2": "Kẻ đó càng tồi tệ hơn người kia; ",
  "sn7.3:3.3": "Người không giận trả lại kẻ giận, ",
  "sn7.3:3.4": "Chiến thắng trận chiến khó thắng. ",
  "sn7.3:4.1": "Người đó mang lợi ích cho cả hai, ",
  "sn7.3:4.2": "Cho mình và cho người kia; ",
  "sn7.3:4.3": "Biết người kia đang tức giận, ",
  "sn7.3:4.4": "Người có chánh niệm giữ tâm an tịnh. ",
  "sn7.3:5.1": "Người chữa lành cho cả hai, ",
  "sn7.3:5.2": "Cho mình và cho người kia; ",
  "sn7.3:5.3": "Những ai không hiểu Pháp, ",
  "sn7.3:5.4": "Họ tưởng người đó là kẻ ngu.' ",
  "sn7.3:6.1": "Nghe vậy, bà-la-môn Asurindaka Bhāradvāja nói với Thế Tôn: ",
  "sn7.3:6.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.3:6.3": "vị ấy đã chứng ngộ. ",
  "sn7.3:6.4": "Tôn giả Bhāradvāja trở thành một trong những bậc A-la-hán. ",
  "sn7.4:0.1": "Tương Ưng Bộ 7.4 ",
  "sn7.4:0.2": "1. Phẩm A-la-hán ",
  "sn7.4:0.3": "Kinh Bilaṅgika ",
  "sn7.4:1.1": "Một thời, Thế Tôn trú tại Vương Xá, trong Trúc Lâm, chỗ nuôi dưỡng sóc. ",
  "sn7.4:1.2": "Bà-la-môn Bilaṅgika Bhāradvāja nghe tin: ",
  "sn7.4:1.3": "'Nghe nói bà-la-môn Bhāradvāja đã xuất gia theo sa-môn Gotama.' Tức giận, bất mãn, ông đến gặp Thế Tôn; sau khi đến, đứng im lặng một bên. ",
  "sn7.4:1.4": "Thế Tôn đọc được suy nghĩ trong tâm bà-la-môn Bilaṅgika Bhāradvāja, liền đọc bài kệ: ",
  "sn7.4:2.1": "'Kẻ nào làm hại người vô tội, '",
  "sn7.4:2.2": "Người trong sạch, không tỳ vết; ",
  "sn7.4:2.3": "Tội ác đó quay lại kẻ ngu, ",
  "sn7.4:2.4": "Như bụi mịn tung ngược chiều gió.' ",
  "sn7.4:3.1": "Nghe vậy, bà-la-môn Bilaṅgika Bhāradvāja nói với Thế Tôn: ",
  "sn7.4:3.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.4:3.3": "vị ấy đã chứng ngộ. ",
  "sn7.4:3.4": "Tôn giả Bhāradvāja trở thành một trong những bậc A-la-hán. ",
  "sn7.5:0.1": "Tương Ưng Bộ 7.5 ",
  "sn7.5:0.2": "1. Phẩm A-la-hán ",
  "sn7.5:0.3": "Kinh Bất Hại ",
  "sn7.5:1.1": "Thuật lại tại Xá-vệ. ",
  "sn7.5:1.2": "Bà-la-môn Ahiṁsaka Bhāradvāja đến gặp Thế Tôn; sau khi đến, chào hỏi thân mật với Ngài. ",
  "sn7.5:1.3": "Sau khi trao đổi những lời thân ái đáng nhớ, ngồi xuống một bên. Ngồi một bên, bà-la-môn Ahiṁsaka Bhāradvāja nói với Thế Tôn: ",
  "sn7.5:1.4": "'Thưa Gotama, tôi là người bất hại, tôi là người bất hại.' ",
  "sn7.5:2.1": "'Tên ngươi nếu đúng với bản thân, '",
  "sn7.5:2.2": "Thì ngươi quả thật là người bất hại; ",
  "sn7.5:2.3": "Người không làm hại bằng thân, lời, ",
  "sn7.5:2.4": "Và cả tâm ý; ",
  "sn7.5:2.5": "Người đó mới thật là bất hại, ",
  "sn7.5:2.6": "Vì không gây tổn hại cho ai.' ",
  "sn7.5:3.1": "Nghe vậy, bà-la-môn Ahiṁsaka Bhāradvāja nói với Thế Tôn: ",
  "sn7.5:3.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.5:3.3": "vị ấy đã chứng ngộ. ",
  "sn7.5:3.4": "Tôn giả Ahiṁsaka Bhāradvāja trở thành một trong những bậc A-la-hán. ",
  "sn7.6:0.1": "Tương Ưng Bộ 7.6 ",
  "sn7.6:0.2": "1. Phẩm A-la-hán ",
  "sn7.6:0.3": "Kinh Mớ Bòng Bong ",
  "sn7.6:1.1": "Thuật lại tại Xá-vệ. ",
  "sn7.6:1.2": "Bà-la-môn Jaṭā Bhāradvāja đến gặp Thế Tôn; sau khi đến, chào hỏi thân mật với Ngài. ",
  "sn7.6:1.3": "Sau khi trao đổi những lời thân ái đáng nhớ, ngồi xuống một bên. ",
  "sn7.6:1.4": "Ngồi một bên, bà-la-môn Jaṭā Bhāradvāja đọc bài kệ thưa với Thế Tôn: ",
  "sn7.6:2.1": "'Mớ bòng bong bên trong, mớ bòng bong bên ngoài, '",
  "sn7.6:2.2": "Chúng sinh bị cuốn vào mớ bòng bong; ",
  "sn7.6:2.3": "Con hỏi Ngài điều này, thưa Gotama, ",
  "sn7.6:2.4": "Ai có thể gỡ rối mớ bòng bong này?' ",
  "sn7.6:3.1": "'Người trí đứng vững trên giới hạnh, '",
  "sn7.6:3.2": "Tu tập tâm và tuệ; ",
  "sn7.6:3.3": "Tỳ Kheo nhiệt tâm, sáng suốt, ",
  "sn7.6:3.4": "Có thể gỡ rối mớ bòng bong này. ",
  "sn7.6:4.1": "Những ai đã trừ diệt tham, sân, ",
  "sn7.6:4.2": "Và vô minh; ",
  "sn7.6:4.3": "Là những bậc A-la-hán đã tận lậu hoặc, ",
  "sn7.6:4.4": "Mớ bòng bong đã được gỡ rối nơi họ. ",
  "sn7.6:5.1": "Nơi nào danh và sắc, ",
  "sn7.6:5.2": "Đều diệt tận không còn dư sót; ",
  "sn7.6:5.3": "Nơi đó sự đối kháng và tưởng về sắc, ",
  "sn7.6:5.4": "Mớ bòng bong bị cắt đứt tại đây.' ",
  "sn7.6:6.1": "Nghe vậy, bà-la-môn Jaṭā nói với Thế Tôn: ",
  "sn7.6:6.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.6:6.3": "Tôn giả Bhāradvāja trở thành một trong những bậc A-la-hán.' ",
  "sn7.7:0.1": "Tương Ưng Bộ 7.7 ",
  "sn7.7:0.2": "1. Phẩm A-la-hán ",
  "sn7.7:0.3": "Kinh Thanh Tịnh ",
  "sn7.7:1.1": "Thuật lại tại Xá-vệ. ",
  "sn7.7:1.2": "Bà-la-môn Suddhika Bhāradvāja đến gặp Thế Tôn; sau khi đến, chào hỏi thân mật với Ngài. ",
  "sn7.7:1.3": "Sau khi trao đổi những lời thân ái đáng nhớ, ngồi xuống một bên. ",
  "sn7.7:1.4": "Ngồi một bên, bà-la-môn Suddhika Bhāradvāja đọc bài kệ thưa với Thế Tôn: ",
  "sn7.7:2.1": "'Không có bà-la-môn nào được thanh tịnh, '",
  "sn7.7:2.2": "Dù có giới hạnh hay khổ hạnh trên đời; ",
  "sn7.7:2.3": "Chỉ người đầy đủ minh và hạnh, ",
  "sn7.7:2.4": "Mới được thanh tịnh, không ai khác.' ",
  "sn7.7:3.1": "'Dù tụng kinh thật nhiều, thật to, '",
  "sn7.7:3.2": "Không do sinh mà thành bà-la-môn; ",
  "sn7.7:3.3": "Nội tâm nhơ bẩn như đống rác, ",
  "sn7.7:3.4": "Dựa vào gian trá mà sống. ",
  "sn7.7:4.1": "Dù là sát-đế-lợi, bà-la-môn, phệ-xá, ",
  "sn7.7:4.2": "Thủ-đà hay người hạ tiện; ",
  "sn7.7:4.3": "Ai tinh tấn, kiên trì, ",
  "sn7.7:4.4": "Mãi mãi nỗ lực mạnh mẽ; ",
  "sn7.7:4.5": "Đạt được sự thanh tịnh tối thượng, ",
  "sn7.7:4.6": "Hãy biết như vậy, thưa Bà-la-môn.' ",
  "sn7.7:5.1": "Nghe vậy, bà-la-môn Suddhika Bhāradvāja nói với Thế Tôn: ",
  "sn7.7:5.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.7:5.3": "Tôn giả Bhāradvāja trở thành một trong những bậc A-la-hán. ",
  "sn7.8:0.1": "Tương Ưng Bộ 7.8 ",
  "sn7.8:0.2": "1. Phẩm A-la-hán ",
  "sn7.8:0.3": "Kinh Thờ Lửa ",
  "sn7.8:1.1": "Một thời, Thế Tôn trú tại Vương Xá, trong Trúc Lâm, chỗ nuôi dưỡng sóc. ",
  "sn7.8:1.2": "Lúc bấy giờ, bà-la-môn Aggika Bhāradvāja đã chuẩn bị cháo sữa pha bơ: ",
  "sn7.8:1.3": "'Ta sẽ tế lửa, phụng thờ lửa.' ",
  "sn7.8:2.1": "Rồi Thế Tôn vào buổi sáng đắp y, mang bình bát, vào thành Vương Xá khất thực. ",
  "sn7.8:2.2": "Đi khất thực từng nhà tại Vương Xá, Ngài đến nhà của bà-la-môn Aggika Bhāradvāja; sau khi đến, đứng một bên. ",
  "sn7.8:2.3": "Bà-la-môn Aggika Bhāradvāja thấy Thế Tôn đứng chờ khất thực. ",
  "sn7.8:2.4": "Thấy vậy, ông đọc bài kệ thưa với Thế Tôn: ",
  "sn7.8:3.1": "'Người có đủ ba minh, '",
  "sn7.8:3.2": "Có dòng dõi, học rộng, nghe nhiều; ",
  "sn7.8:3.3": "Người đầy đủ minh và hạnh, ",
  "sn7.8:3.4": "Mới xứng thọ nhận cháo sữa này.' ",
  "sn7.8:4.1": "'Dù tụng kinh thật nhiều, thật to, '",
  "sn7.8:4.2": "Không do sinh mà thành bà-la-môn; ",
  "sn7.8:4.3": "Nội tâm nhơ bẩn như đống rác, ",
  "sn7.8:4.4": "Bao quanh bởi sự gian trá. ",
  "sn7.8:5.1": "Người biết các đời quá khứ, ",
  "sn7.8:5.2": "Thấy được cõi trời và cõi khổ; ",
  "sn7.8:5.3": "Đạt được sự chấm dứt tái sinh, ",
  "sn7.8:5.4": "Bậc ẩn sĩ đã viên mãn thắng trí. ",
  "sn7.8:6.1": "Với ba minh này, ",
  "sn7.8:6.2": "Người đó là bậc tam minh, bà-la-môn; ",
  "sn7.8:6.3": "Người đầy đủ minh và hạnh, ",
  "sn7.8:6.4": "Mới xứng thọ nhận cháo sữa này.' ",
  "sn7.8:7.1": "'Xin mời Ngài Gotama dùng. '",
  "sn7.8:7.2": "Ngài là bà-la-môn.' ",
  "sn7.8:8.1": "'Những gì do tụng kệ mà có, ta không thọ nhận, '",
  "sn7.8:8.2": "Thưa Bà-la-môn, đó không phải là pháp của người trí; ",
  "sn7.8:8.3": "Chư Phật từ chối những gì do tụng kệ mà có, ",
  "sn7.8:8.4": "Khi có Pháp, thưa Bà-la-môn, đó là cách sống đúng. ",
  "sn7.8:9.1": "Hãy cúng dường bằng thức ăn và nước uống khác, ",
  "sn7.8:9.2": "Cho bậc đại ẩn sĩ toàn vẹn, đã tận lậu hoặc, không còn lo lắng; ",
  "sn7.8:9.3": "Phụng sự với thức ăn và đồ uống, ",
  "sn7.8:9.4": "Đó chính là ruộng phước cho người mong cầu công đức.' ",
  "sn7.8:10.1": "Nghe vậy, bà-la-môn Aggika Bhāradvāja nói với Thế Tôn: ",
  "sn7.8:10.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.8:10.3": "Tôn giả Aggika Bhāradvāja trở thành một trong những bậc A-la-hán. ",
  "sn7.9:0.1": "Tương Ưng Bộ 7.9 ",
  "sn7.9:0.2": "1. Phẩm A-la-hán ",
  "sn7.9:0.3": "Kinh Sundarikā ",
  "sn7.9:1.1": "Một thời, Thế Tôn trú tại xứ Kosala, bên bờ sông Sundarikā. ",
  "sn7.9:1.2": "Lúc bấy giờ, bà-la-môn Sundarika Bhāradvāja đang tế lửa, phụng thờ lửa bên bờ sông Sundarikā. ",
  "sn7.9:1.3": "Sau khi tế lửa và phụng thờ lửa xong, ông đứng dậy nhìn khắp bốn phương: ",
  "sn7.9:1.4": "'Ai xứng đáng thọ nhận phần thức ăn còn lại từ lễ tế này?' ",
  "sn7.9:1.5": "Bà-la-môn Sundarika Bhāradvāja thấy Thế Tôn đang ngồi dưới gốc cây, đầu trùm y. ",
  "sn7.9:1.6": "Thấy vậy, ông cầm phần thức ăn tế lễ bằng tay trái, cầm bình nước bằng tay phải, đi đến gặp Thế Tôn. ",
  "sn7.9:1.7": "Thế Tôn nghe tiếng chân của bà-la-môn Sundarika Bhāradvāja, liền ngẩng đầu lên. ",
  "sn7.9:1.8": "Bà-la-môn Sundarika Bhāradvāja nghĩ: 'Vị này đầu trọc, kẻ đầu trọc này,' và muốn quay trở lại. ",
  "sn7.9:1.9": "Rồi bà-la-môn Sundarika Bhāradvāja nghĩ: ",
  "sn7.9:1.10": "'Có một số bà-la-môn cũng cạo đầu ở đây; '",
  "sn7.9:1.11": "Ta hãy đến hỏi về dòng dõi của vị này.' ",
  "sn7.9:2.1": "Bà-la-môn Sundarika Bhāradvāja đến gặp Thế Tôn; sau khi đến, nói với Ngài: ",
  "sn7.9:2.2": "'Ngài thuộc dòng dõi nào?' ",
  "sn7.9:3.1": "'Chớ hỏi dòng dõi, hãy hỏi hành trì, '",
  "sn7.9:3.2": "Lửa sinh ra từ củi; ",
  "sn7.9:3.3": "Bậc ẩn sĩ có chí, dù sinh từ gia đình thấp kém, ",
  "sn7.9:3.4": "Vẫn là tuấn mã, được hổ thẹn ngăn giữ. ",
  "sn7.9:4.1": "Người điều phục bởi sự thật, được chế ngự bằng tự điều phục, ",
  "sn7.9:4.2": "Đạt được mục đích, đã sống phạm hạnh; ",
  "sn7.9:4.3": "Hãy mời vị đó, người xứng đáng lễ tế, ",
  "sn7.9:4.4": "Đúng thời cúng dường vật xứng đáng nhận.' ",
  "sn7.9:5.1": "'Thật vậy, lễ tế của ta đã làm đúng, đã cúng dường đúng, '",
  "sn7.9:5.2": "Khi ta gặp được bậc đã đạt đích như Ngài; ",
  "sn7.9:5.3": "Vì không gặp được bậc như Ngài, ",
  "sn7.9:5.4": "Người khác sẽ thọ nhận phần lễ vật còn lại.' ",
  "sn7.9:6.1": "'Xin mời Ngài Gotama dùng. '",
  "sn7.9:6.2": "Ngài là bà-la-môn.' ",
  "sn7.9:7.1": "'Những gì do tụng kệ mà có, ta không thọ nhận, '",
  "sn7.9:7.2": "Thưa Bà-la-môn, đó không phải là pháp của người trí; ",
  "sn7.9:7.3": "Chư Phật từ chối những gì do tụng kệ mà có, ",
  "sn7.9:7.4": "Khi có Pháp, thưa Bà-la-môn, đó là cách sống đúng. ",
  "sn7.9:8.1": "Hãy cúng dường bằng thức ăn và nước uống khác, ",
  "sn7.9:8.2": "Cho bậc đại ẩn sĩ toàn vẹn, đã tận lậu hoặc, không còn lo lắng; ",
  "sn7.9:8.3": "Phụng sự với thức ăn và đồ uống, ",
  "sn7.9:8.4": "Đó chính là ruộng phước cho người mong cầu công đức.' ",
  "sn7.9:9.1": "'Vậy thưa Gotama, tôi sẽ cho ai phần lễ vật còn lại này?' ",
  "sn7.9:9.2": "'Này Bà-la-môn, ta không thấy ai trong thế giới gồm trời, ma, Phạm thiên, cùng sa-môn, bà-la-môn, trời và người, mà phần lễ vật còn lại đó sau khi thọ dụng sẽ được tiêu hóa tốt, ngoại trừ Như Lai hoặc đệ tử Như Lai. '",
  "sn7.9:9.3": "Vậy, này Bà-la-môn, hãy đổ phần lễ vật đó vào chỗ đất không có cỏ cây, hoặc thả xuống nước không có sinh vật.' ",
  "sn7.9:10.1": "Bà-la-môn Sundarika Bhāradvāja thả phần lễ vật còn lại xuống nước không có sinh vật. ",
  "sn7.9:10.2": "Phần lễ vật đó khi thả xuống nước phát ra tiếng xèo xèo, sôi sục, bốc khói nghi ngút. ",
  "sn7.9:10.3": "Ví như lưỡi cày nung nóng cả ngày khi thả xuống nước phát ra tiếng xèo xèo, sôi sục, bốc khói nghi ngút; ",
  "sn7.9:10.4": "Cũng vậy, phần lễ vật đó khi thả xuống nước phát ra tiếng xèo xèo, sôi sục, bốc khói nghi ngút. ",
  "sn7.9:11.1": "Bà-la-môn Sundarika Bhāradvāja kinh cảm, lông dựng đứng, đến gặp Thế Tôn; sau khi đến, đứng một bên. ",
  "sn7.9:11.2": "Thế Tôn đọc bài kệ cho bà-la-môn Sundarika Bhāradvāja đang đứng một bên: ",
  "sn7.9:12.1": "'Này Bà-la-môn, đừng tưởng đốt củi là thanh tịnh, '",
  "sn7.9:12.2": "Đó chỉ là bề ngoài; ",
  "sn7.9:12.3": "Người trí không nói rằng thanh tịnh, ",
  "sn7.9:12.4": "Ai tìm sự thanh tịnh từ bên ngoài. ",
  "sn7.9:13.1": "Này Bà-la-môn, ta đã bỏ việc đốt củi, ",
  "sn7.9:13.2": "Ta thắp ngọn lửa bên trong; ",
  "sn7.9:13.3": "Ngọn lửa luôn cháy, tâm luôn định, ",
  "sn7.9:13.4": "Ta là bậc A-la-hán sống phạm hạnh. ",
  "sn7.9:14.1": "Này Bà-la-môn, ngã mạn là bó lúa nặng, ",
  "sn7.9:14.2": "Sân hận là khói, nói dối là tro tàn; ",
  "sn7.9:14.3": "Lưỡi là môi, tâm là bàn thờ lửa, ",
  "sn7.9:14.4": "Tự ngã điều phục là ánh sáng của người. ",
  "sn7.9:15.1": "Pháp là hồ, thưa Bà-la-môn, giới là bến tắm, ",
  "sn7.9:15.2": "Trong sáng, được bậc thiện tán thán; ",
  "sn7.9:15.3": "Nơi đây bậc đã đạt đích tắm gội, ",
  "sn7.9:15.4": "Thân không ướt mà vượt sang bờ kia. ",
  "sn7.9:16.1": "Sự thật, Pháp, tự chế, phạm hạnh, ",
  "sn7.9:16.2": "Đây là nền tảng đạt Phạm thiên, thưa Bà-la-môn; ",
  "sn7.9:16.3": "Hãy đảnh lễ người ngay thẳng đó, ",
  "sn7.9:16.4": "Ta gọi người đó là bậc sống theo Pháp.' ",
  "sn7.9:17.1": "Nghe vậy, bà-la-môn Sundarika Bhāradvāja nói với Thế Tôn: ",
  "sn7.9:17.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.9:17.3": "Tôn giả Bhāradvāja trở thành một trong những bậc A-la-hán. ",
  "sn7.10:0.1": "Tương Ưng Bộ 7.10 ",
  "sn7.10:0.2": "1. Phẩm A-la-hán ",
  "sn7.10:0.3": "Kinh Nhiều Con Gái ",
  "sn7.10:1.1": "Một thời, Thế Tôn trú tại xứ Kosala, trong một khu rừng. ",
  "sn7.10:1.2": "Lúc bấy giờ, một vị bà-la-môn dòng họ Bhāradvāja mất mười bốn con bò đực. ",
  "sn7.10:1.3": "Vị bà-la-môn Bhāradvāja đi tìm đàn bò, đến khu rừng đó; sau khi đến, thấy Thế Tôn đang ngồi kiết già trong khu rừng, lưng thẳng, chánh niệm hiện tiền. ",
  "sn7.10:1.4": "Thấy vậy, ông đến gặp Thế Tôn; sau khi đến, đọc bài kệ trước Thế Tôn: ",
  "sn7.10:2.1": "'Sa-môn này chắc chắn, '",
  "sn7.10:2.2": "Không có mười bốn con bò; ",
  "sn7.10:2.3": "Hôm nay không thấy chúng đâu, ",
  "sn7.10:2.4": "Nên sa-môn này được an vui. ",
  "sn7.10:3.1": "Sa-môn này chắc chắn, ",
  "sn7.10:3.2": "Không có ruộng mè bị hư hại; ",
  "sn7.10:3.3": "Không lá này, không lá kia, ",
  "sn7.10:3.4": "Nên sa-môn này được an vui. ",
  "sn7.10:4.1": "Sa-môn này chắc chắn, ",
  "sn7.10:4.2": "Không có chuột trong kho lúa trống; ",
  "sn7.10:4.3": "Chúng không nhảy múa hò reo, ",
  "sn7.10:4.4": "Nên sa-môn này được an vui. ",
  "sn7.10:5.1": "Sa-môn này chắc chắn, ",
  "sn7.10:5.2": "Không có chiếc chiếu bảy tháng; ",
  "sn7.10:5.3": "Phủ đầy cỏ mọc lên, ",
  "sn7.10:5.4": "Nên sa-môn này được an vui. ",
  "sn7.10:6.1": "Sa-môn này chắc chắn, ",
  "sn7.10:6.2": "Không có bảy cô con gái góa bụa; ",
  "sn7.10:6.3": "Người chỉ có một con, người có hai con, ",
  "sn7.10:6.4": "Nên sa-môn này được an vui. ",
  "sn7.10:7.1": "Sa-môn này chắc chắn, ",
  "sn7.10:7.2": "Không có bà vợ có vết nám đánh thức bằng chân; ",
  "sn7.10:7.3": "Bà ta lấy chân đá đánh thức khi ngủ, ",
  "sn7.10:7.4": "Nên sa-môn này được an vui. ",
  "sn7.10:8.1": "Sa-môn này chắc chắn, ",
  "sn7.10:8.2": "Không có chủ nợ đến vào sáng sớm; ",
  "sn7.10:8.3": "Chúng đòi: Trả đây! Trả đây!, ",
  "sn7.10:8.4": "Nên sa-môn này được an vui.' ",
  "sn7.10:9.1": "'Này Bà-la-môn, ta quả thật, '",
  "sn7.10:9.2": "Không có mười bốn con bò; ",
  "sn7.10:9.3": "Hôm nay không thấy chúng đâu, ",
  "sn7.10:9.4": "Nên ta, này Bà-la-môn, được an vui. ",
  "sn7.10:10.1": "Này Bà-la-môn, ta quả thật, ",
  "sn7.10:10.2": "Không có ruộng mè bị hư hại; ",
  "sn7.10:10.3": "Không lá này, không lá kia, ",
  "sn7.10:10.4": "Nên ta, này Bà-la-môn, được an vui. ",
  "sn7.10:11.1": "Này Bà-la-môn, ta quả thật, ",
  "sn7.10:11.2": "Không có chuột trong kho lúa trống; ",
  "sn7.10:11.3": "Chúng không nhảy múa hò reo, ",
  "sn7.10:11.4": "Nên ta, này Bà-la-môn, được an vui. ",
  "sn7.10:12.1": "Này Bà-la-môn, ta quả thật, ",
  "sn7.10:12.2": "Không có chiếc chiếu bảy tháng; ",
  "sn7.10:12.3": "Phủ đầy cỏ mọc lên, ",
  "sn7.10:12.4": "Nên ta, này Bà-la-môn, được an vui. ",
  "sn7.10:13.1": "Này Bà-la-môn, ta quả thật, ",
  "sn7.10:13.2": "Không có bảy cô con gái góa bụa; ",
  "sn7.10:13.3": "Người chỉ có một con, người có hai con, ",
  "sn7.10:13.4": "Nên ta, này Bà-la-môn, được an vui. ",
  "sn7.10:14.1": "Này Bà-la-môn, ta quả thật, ",
  "sn7.10:14.2": "Không có bà vợ có vết nám đánh thức bằng chân; ",
  "sn7.10:14.3": "Bà ta lấy chân đá đánh thức khi ngủ, ",
  "sn7.10:14.4": "Nên ta, này Bà-la-môn, được an vui. ",
  "sn7.10:15.1": "Này Bà-la-môn, ta quả thật, ",
  "sn7.10:15.2": "Không có chủ nợ đến vào sáng sớm; ",
  "sn7.10:15.3": "Chúng đòi: Trả đây! Trả đây!, ",
  "sn7.10:15.4": "Nên ta, này Bà-la-môn, được an vui.' ",
  "sn7.10:16.1": "Nghe vậy, vị bà-la-môn Bhāradvāja nói với Thế Tôn: ",
  "sn7.10:16.2": "'Thật vi diệu, thưa Gotama! Thật vi diệu, thưa Gotama! '",
  "sn7.10:16.3": "Ví như người dựng đứng lại những gì bị lật úp, hay mở ra những gì bị che kín, hay chỉ đường cho người bị lạc, hay thắp đèn dầu trong bóng tối để những ai có mắt có thể thấy sắc; cũng vậy, Pháp đã được Ngài Gotama trình bày bằng nhiều phương cách. ",
  "sn7.10:16.4": "Con xin quy y Ngài Gotama, Pháp và Tăng đoàn Tỳ Kheo. ",
  "sn7.10:16.5": "Mong con được xuất gia, được thọ đại giới từ Ngài Gotama.' ",
  "sn7.10:17.1": "Vị bà-la-môn Bhāradvāja được xuất gia, được thọ đại giới từ Thế Tôn. ",
  "sn7.10:17.2": "Sau khi thọ đại giới không lâu, Tôn giả Bhāradvāja sống một mình, viễn ly, không phóng dật, nhiệt tâm, tinh cần, không bao lâuvì mục đích tối thượng mà các thiện nam tử xuất gia từ gia đình đến chỗ không gia đìnhđạt được vô thượng phạm hạnh, ngay trong hiện tại, tự mình chứng ngộ và an trú. ",
  "sn7.10:17.3": "'Sinh đã tận, phạm hạnh đã sống, việc cần làm đã làm, không còn trở lại đời này nữa,' vị ấy biết vậy. ",
  "sn7.10:17.4": "Tôn giả Bhāradvāja trở thành một trong những bậc A-la-hán. ",
  "sn7.10:17.5": "Phẩm A-la-hán thứ nhất. ",
  "sn7.10:18.0": "Tóm lược phẩm này ",
  "sn7.10:18.1": "Dhanañjānī và bị chửi mắng, ",
  "sn7.10:18.2": "Asurindaka, Bilaṅgika; ",
  "sn7.10:18.3": "Bất hại, mớ bòng bong, ",
  "sn7.10:18.4": "Thanh tịnh và thờ lửa; ",
  "sn7.10:18.5": "Sundarikā, nhiều con gái ",
  "sn7.10:18.6": "Đó là mười kinh. ",
  "sn7.11:0.1": "Tương Ưng Bộ 7.11 ",
  "sn7.11:0.2": "2. Phẩm Cư Sĩ ",
  "sn7.11:0.3": "Kinh Người Cày Ruộng ",
  "sn7.11:1.1": "Tôi nghe như vầy ",
  "sn7.11:1.2": "Một thời, Thế Tôn trú tại xứ Magadha, ở phía nam núi, tại làng bà-la-môn Ekanāḷā. ",
  "sn7.11:1.3": "Lúc bấy giờ, bà-la-môn Kasi Bhāradvāja có khoảng năm trăm cái cày đang được mắc vào trâu bò mùa gieo hạt. ",
  "sn7.11:1.4": "Thế Tôn vào buổi sáng đắp y, mang bình bát, đi đến chỗ làm ruộng của bà-la-môn Kasi Bhāradvāja. ",
  "sn7.11:2.1": "Lúc bấy giờ, đang diễn ra buổi phân phát thức ăn của bà-la-môn Kasi Bhāradvāja. ",
  "sn7.11:2.2": "Thế Tôn đi đến chỗ phân phát thức ăn; sau khi đến, đứng một bên. ",
  "sn7.11:2.3": "Bà-la-môn Kasi Bhāradvāja thấy Thế Tôn đang đứng chờ khất thực. ",
  "sn7.11:2.4": "Thấy vậy, ông nói với Thế Tôn: ",
  "sn7.11:2.5": "'Ta, thưa Sa-môn, cày và gieo hạt, sau khi cày và gieo hạt thì ăn. '",
  "sn7.11:2.6": "Ngài cũng hãy cày và gieo hạt, sau khi cày và gieo hạt thì ăn.' ",
  "sn7.11:2.7": "'Ta, thưa Bà-la-môn, cũng cày và gieo hạt, sau khi cày và gieo hạt thì ăn.' ",
  "sn7.11:2.8": "'Nhưng chúng tôi không thấy ách, cày, lưỡi cày, gậy thúc hay trâu bò của Ngài Gotama, vậy mà Ngài lại nói: '",
  "sn7.11:2.9": "'Ta, thưa Bà-la-môn, cũng cày và gieo hạt, sau khi cày và gieo hạt thì ăn.'' '",
  "sn7.11:2.10": "Bà-la-môn Kasi Bhāradvāja đọc bài kệ thưa với Thế Tôn: ",
  "sn7.11:3.1": "'Ngài tự xưng là người cày, '",
  "sn7.11:3.2": "Nhưng chúng tôi không thấy Ngài cày; ",
  "sn7.11:3.3": "Hãy nói cho chúng tôi biết, người cày, ",
  "sn7.11:3.4": "Để chúng tôi biết việc cày của Ngài.' ",
  "sn7.11:4.1": "'Đức tin là hạt giống, khổ hạnh là mưa, '",
  "sn7.11:4.2": "Trí tuệ là ách và cày của ta; ",
  "sn7.11:4.3": "Hổ thẹn là cán cày, tâm là dây buộc, ",
  "sn7.11:4.4": "Chánh niệm là lưỡi cày và gậy thúc. ",
  "sn7.11:5.1": "Phòng hộ thân, phòng hộ lời, ",
  "sn7.11:5.2": "Tiết độ trong ăn uống; ",
  "sn7.11:5.3": "Ta nhổ cỏ dại bằng sự thật, ",
  "sn7.11:5.4": "Nhu hòa là sự giải thoát của ta. ",
  "sn7.11:6.1": "Tinh tấn là con bò kéo cày của ta, ",
  "sn7.11:6.2": "Đưa đến nơi an ổn, không còn ràng buộc; ",
  "sn7.11:6.3": "Đi mà không quay lại, ",
  "sn7.11:6.4": "Đến nơi rồi không còn sầu khổ. ",
  "sn7.11:7.1": "Đây là cách cày ruộng như vậy, ",
  "sn7.11:7.2": "Cho trái bất tử; ",
  "sn7.11:7.3": "Sau khi cày ruộng như vậy, ",
  "sn7.11:7.4": "Giải thoát khỏi mọi khổ đau.' ",
  "sn7.11:8.1": "'Xin mời Ngài Gotama dùng. '",
  "sn7.11:8.2": "Ngài là người cày. ",
  "sn7.11:8.3": "Ngài Gotama quả thật cày ruộng cho trái bất tử.' ",
  "sn7.11:9.1": "'Những gì do tụng kệ mà có, ta không thọ nhận, '",
  "sn7.11:9.2": "Thưa Bà-la-môn, đó không phải là pháp của người trí; ",
  "sn7.11:9.3": "Chư Phật từ chối những gì do tụng kệ mà có, ",
  "sn7.11:9.4": "Khi có Pháp, thưa Bà-la-môn, đó là cách sống đúng. ",
  "sn7.11:10.1": "Hãy cúng dường bằng thức ăn và nước uống khác, ",
  "sn7.11:10.2": "Cho bậc đại ẩn sĩ toàn vẹn, đã tận lậu hoặc, không còn lo lắng; ",
  "sn7.11:10.3": "Phụng sự với thức ăn và đồ uống, ",
  "sn7.11:10.4": "Đó chính là ruộng phước cho người mong cầu công đức.' ",
  "sn7.11:11.1": "Nghe vậy, bà-la-môn Kasi Bhāradvāja nói với Thế Tôn: ",
  "sn7.11:11.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.11:11.3": "Con xin quy y Ngài, từ hôm nay cho đến trọn đời.' ",
  "sn7.12:0.1": "Tương Ưng Bộ 7.12 ",
  "sn7.12:0.2": "2. Phẩm Cư Sĩ ",
  "sn7.12:0.3": "Kinh Udaya ",
  "sn7.12:1.1": "Thuật lại tại Xá-vệ. ",
  "sn7.12:1.2": "Thế Tôn vào buổi sáng đắp y, mang bình bát, đi đến nhà bà-la-môn Udaya. ",
  "sn7.12:1.3": "Bà-la-môn Udaya đổ cơm đầy bình bát cho Thế Tôn. ",
  "sn7.12:1.4": "Lần thứ hai, Thế Tôn vào buổi sáng đắp y, mang bình bát, lại đến nhà bà-la-môn Udaya …pe… ",
  "sn7.12:1.5": "Lần thứ ba, bà-la-môn Udaya đổ cơm đầy bình bát cho Thế Tôn rồi nói: ",
  "sn7.12:1.6": "'Sa-môn Gotama này thật lắm chuyện, cứ đến mãi!' ",
  "sn7.12:2.1": "'Người ta gieo hạt đi gieo hạt lại, '",
  "sn7.12:2.2": "Mưa trời vua lại mưa đi mưa lại; ",
  "sn7.12:2.3": "Nông phu cày ruộng đi cày lại, ",
  "sn7.12:2.4": "Lúa gạo đến với vương quốc mãi. ",
  "sn7.12:3.1": "Người ăn xin đến xin đi xin lại, ",
  "sn7.12:3.2": "Chủ nhân bố thí đi bố thí lại; ",
  "sn7.12:3.3": "Sau khi bố thí đi bố thí lại, ",
  "sn7.12:3.4": "Họ được lên cõi trời mãi mãi. ",
  "sn7.12:4.1": "Bò cho sữa đi cho lại, ",
  "sn7.12:4.2": "Bê con đến với mẹ đi đến lại; ",
  "sn7.12:4.3": "Kẻ ngu mệt mỏi, vùng vẫy, ",
  "sn7.12:4.4": "Vào bụng mẹ đi vào lại. ",
  "sn7.12:5.1": "Sinh rồi chết đi sinh lại, ",
  "sn7.12:5.2": "Mang đến nghĩa địa đi mang lại; ",
  "sn7.12:5.3": "Người trí đạt được con đường không tái sinh, ",
  "sn7.12:5.4": "Không sinh đi sinh lại nữa.' ",
  "sn7.12:6.1": "Nghe vậy, bà-la-môn Udaya nói với Thế Tôn: ",
  "sn7.12:6.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.12:6.3": "xin Ngài Gotama nhận con là cư sĩ, từ hôm nay cho đến trọn đời quy y.' ",
  "sn7.13:0.1": "Tương Ưng Bộ 7.13 ",
  "sn7.13:0.2": "2. Phẩm Cư Sĩ ",
  "sn7.13:0.3": "Kinh Devahita ",
  "sn7.13:1.1": "Thuật lại tại Xá-vệ. ",
  "sn7.13:1.2": "Lúc bấy giờ, Thế Tôn bị bệnh do gió; ",
  "sn7.13:1.3": "Tôn giả Upavāṇa là người hầu cận Thế Tôn. ",
  "sn7.13:1.4": "Thế Tôn bảo Tôn giả Upavāṇa: ",
  "sn7.13:1.5": "'Này Upavāṇa, hãy đi tìm nước nóng cho ta.' ",
  "sn7.13:1.6": "'Vâng, thưa Ngài.' Tôn giả Upavāṇa vâng lời Thế Tôn, đắp y, mang bình bát, đi đến nhà bà-la-môn Devahita; sau khi đến, đứng im lặng một bên. ",
  "sn7.13:1.7": "Bà-la-môn Devahita thấy Tôn giả Upavāṇa đứng im lặng một bên. ",
  "sn7.13:1.8": "Thấy vậy, ông đọc bài kệ thưa Tôn giả Upavāṇa: ",
  "sn7.13:2.1": "'Ngài đứng im lặng, '",
  "sn7.13:2.2": "Đầu trọc, khoác y tăng-già-lê; ",
  "sn7.13:2.3": "Ngài đang mong cầu gì, tìm kiếm gì, ",
  "sn7.13:2.4": "Hay đến để xin gì?' ",
  "sn7.13:3.1": "'Bậc A-la-hán, bậc Thiện Thệ trên đời, '",
  "sn7.13:3.2": "Bậc ẩn sĩ đang bị bệnh do gió; ",
  "sn7.13:3.3": "Nếu có nước nóng, ",
  "sn7.13:3.4": "Hãy dâng cho bậc ẩn sĩ, thưa Bà-la-môn. ",
  "sn7.13:4.1": "Được tôn kính bởi những người đáng tôn kính, ",
  "sn7.13:4.2": "Được cung kính bởi những người xứng đáng cung kính; ",
  "sn7.13:4.3": "Được lễ bái bởi những người đáng lễ bái, ",
  "sn7.13:4.4": "Ta muốn phục vụ vị đó.' ",
  "sn7.13:5.1": "Bà-la-môn Devahita sai người mang bình nước nóng, cùng gói đường mật, dâng cho Tôn giả Upavāṇa. ",
  "sn7.13:5.2": "Tôn giả Upavāṇa đến gặp Thế Tôn; sau khi đến, tắm cho Thế Tôn bằng nước nóng, hòa tan đường mật vào nước nóng rồi dâng lên Thế Tôn. ",
  "sn7.13:5.3": "Sau đó, bệnh của Thế Tôn được thuyên giảm. ",
  "sn7.13:6.1": "Bà-la-môn Devahita đến gặp Thế Tôn; sau khi đến, chào hỏi thân mật với Ngài. ",
  "sn7.13:6.2": "Sau khi trao đổi những lời thân ái đáng nhớ, ngồi xuống một bên. ",
  "sn7.13:6.3": "Ngồi một bên, bà-la-môn Devahita đọc bài kệ thưa với Thế Tôn: ",
  "sn7.13:7.1": "'Nên dâng cúng ở đâu để được phước, '",
  "sn7.13:7.2": "Dâng ở đâu thì được quả lớn; ",
  "sn7.13:7.3": "Làm sao để việc cúng dường, ",
  "sn7.13:7.4": "Của người thí chủ được thành tựu?' ",
  "sn7.13:8.1": "'Người biết các đời quá khứ, '",
  "sn7.13:8.2": "Thấy được cõi trời và cõi khổ; ",
  "sn7.13:8.3": "Đạt được sự chấm dứt tái sinh, ",
  "sn7.13:8.4": "Bậc ẩn sĩ đã viên mãn thắng trí. ",
  "sn7.13:9.1": "Hãy dâng cúng ở đó để được phước, ",
  "sn7.13:9.2": "Dâng ở đó thì được quả lớn; ",
  "sn7.13:9.3": "Như vậy việc cúng dường, ",
  "sn7.13:9.4": "Của người thí chủ được thành tựu.' ",
  "sn7.13:10.1": "Nghe vậy, bà-la-môn Devahita nói với Thế Tôn: ",
  "sn7.13:10.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.13:10.3": "xin Ngài Gotama nhận con là cư sĩ, từ hôm nay cho đến trọn đời quy y.' ",
  "sn7.14:0.1": "Tương Ưng Bộ 7.14 ",
  "sn7.14:0.2": "2. Phẩm Cư Sĩ ",
  "sn7.14:0.3": "Kinh Đại Phú ",
  "sn7.14:1.1": "Thuật lại tại Xá-vệ. ",
  "sn7.14:1.2": "Một vị bà-la-môn đại phú ăn mặc rách rưới, khoác y thô đến gặp Thế Tôn; sau khi đến, chào hỏi thân mật với Ngài. ",
  "sn7.14:1.3": "Sau khi trao đổi những lời thân ái đáng nhớ, ngồi xuống một bên. Thế Tôn hỏi vị bà-la-môn đại phú đang ngồi một bên: ",
  "sn7.14:1.4": "'Này Bà-la-môn, sao ông lại ăn mặc rách rưới, khoác y thô vậy?' ",
  "sn7.14:1.5": "'Thưa Gotama, ta có bốn người con. '",
  "sn7.14:1.6": "Chúng bàn với vợ rồi đuổi ta ra khỏi nhà.' ",
  "sn7.14:1.7": "'Vậy thì, này Bà-la-môn, hãy học thuộc những bài kệ này, rồi đọc trong hội trường khi đại chúng tụ họp và khi các con ông cũng có mặt: '",
  "sn7.14:2.1": "'Những đứa con mà ta sinh ra với lòng vui mừng, '",
  "sn7.14:2.2": "Những đứa mà ta mong muốn được phát triển; ",
  "sn7.14:2.3": "Chúng bàn với vợ rồi đuổi ta đi, ",
  "sn7.14:2.4": "Như người ta đuổi con lợn đi. ",
  "sn7.14:3.1": "Những đứa độc ác, vô lại này, ",
  "sn7.14:3.2": "Gọi ta là cha, là cha; ",
  "sn7.14:3.3": "Chúng là quỷ dạ-xoa mang hình con người, ",
  "sn7.14:3.4": "Chúng bỏ rơi ta khi ta già yếu. ",
  "sn7.14:4.1": "Như con ngựa già không còn dùng được, ",
  "sn7.14:4.2": "Bị cướp đi phần ăn; ",
  "sn7.14:4.3": "Cha già của những đứa trẻ, ",
  "sn7.14:4.4": "Phải đi khất thực nhà người. ",
  "sn7.14:5.1": "Cây gậy còn tốt hơn những đứa con bất hiếu này; ",
  "sn7.14:5.2": "Gậy ngăn được bò hung hăng, ",
  "sn7.14:5.3": "Và chó dữ cũng vậy. ",
  "sn7.14:6.1": "Trong bóng tối phía trước, ",
  "sn7.14:6.2": "Tìm được chỗ đứng trong nơi sâu thẳm; ",
  "sn7.14:6.3": "Nhờ uy lực của cây gậy, ",
  "sn7.14:6.4": "Vấp ngã rồi lại đứng lên.'' ",
  "sn7.14:7.1": "Vị bà-la-môn đại phú học thuộc bài kệ từ Thế Tôn, rồi đọc trong hội trường khi đại chúng tụ họp và khi các con ông cũng có mặt: ",
  "sn7.14:8.1": "'Những đứa con mà ta sinh ra với lòng vui mừng, '",
  "sn7.14:8.2": "Những đứa mà ta mong muốn được phát triển; ",
  "sn7.14:8.3": "Chúng bàn với vợ rồi đuổi ta đi, ",
  "sn7.14:8.4": "Như người ta đuổi con lợn đi. ",
  "sn7.14:9.1": "Những đứa độc ác, vô lại này, ",
  "sn7.14:9.2": "Gọi ta là cha, là cha; ",
  "sn7.14:9.3": "Chúng là quỷ dạ-xoa mang hình con người, ",
  "sn7.14:9.4": "Chúng bỏ rơi ta khi ta già yếu. ",
  "sn7.14:10.1": "Như con ngựa già không còn dùng được, ",
  "sn7.14:10.2": "Bị cướp đi phần ăn; ",
  "sn7.14:10.3": "Cha già của những đứa trẻ, ",
  "sn7.14:10.4": "Phải đi khất thực nhà người. ",
  "sn7.14:11.1": "Cây gậy còn tốt hơn những đứa con bất hiếu này; ",
  "sn7.14:11.2": "Gậy ngăn được bò hung hăng, ",
  "sn7.14:11.3": "Và chó dữ cũng vậy. ",
  "sn7.14:12.1": "Trong bóng tối phía trước, ",
  "sn7.14:12.2": "Tìm được chỗ đứng trong nơi sâu thẳm; ",
  "sn7.14:12.3": "Nhờ uy lực của cây gậy, ",
  "sn7.14:12.4": "Vấp ngã rồi lại đứng lên.' ",
  "sn7.14:13.1": "Các con đưa ông về nhà, tắm rửa, mỗi người dâng tặng một đôi vải. ",
  "sn7.14:13.2": "Vị bà-la-môn đại phú lấy một đôi vải đến gặp Thế Tôn; sau khi đến, chào hỏi thân mật với Ngài. ",
  "sn7.14:13.3": "Sau khi trao đổi những lời thân ái đáng nhớ, ngồi xuống một bên. Ngồi một bên, vị bà-la-môn đại phú nói với Thế Tôn: ",
  "sn7.14:13.4": "'Thưa Gotama, chúng tôi các bà-la-môn thường tìm thứ trả ơn cho thầy. '",
  "sn7.14:13.5": "Xin Ngài Gotama nhận đôi vải trả ơn này từ tôi.' ",
  "sn7.14:13.6": "Thế Tôn nhận vì lòng từ bi. ",
  "sn7.14:13.7": "Vị bà-la-môn đại phú nói với Thế Tôn: ",
  "sn7.14:13.8": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.14:13.9": "xin Ngài Gotama nhận con là cư sĩ, từ hôm nay cho đến trọn đời quy y.' ",
  "sn7.15:0.1": "Tương Ưng Bộ 7.15 ",
  "sn7.15:0.2": "2. Phẩm Cư Sĩ ",
  "sn7.15:0.3": "Kinh Cứng Đầu ",
  "sn7.15:1.1": "Thuật lại tại Xá-vệ. ",
  "sn7.15:1.2": "Lúc bấy giờ, tại Xá-vệ có một bà-la-môn tên Mānatthaddha đang sống. ",
  "sn7.15:1.3": "Ông không chào hỏi mẹ, không chào hỏi cha, không chào hỏi thầy, không chào hỏi anh cả. ",
  "sn7.15:1.4": "Lúc bấy giờ, Thế Tôn đang thuyết pháp cho đại chúng đông đảo vây quanh. ",
  "sn7.15:1.5": "Bà-la-môn Mānatthaddha nghĩ: ",
  "sn7.15:1.6": "'Sa-môn Gotama này đang thuyết pháp cho đại chúng đông đảo vây quanh. '",
  "sn7.15:1.7": "Ta hãy đến gặp sa-môn Gotama. ",
  "sn7.15:1.8": "Nếu sa-môn Gotama nói chuyện với ta, ta cũng sẽ nói chuyện lại. ",
  "sn7.15:1.9": "Nếu sa-môn Gotama không nói chuyện với ta, ta cũng sẽ không nói.' ",
  "sn7.15:1.10": "Bà-la-môn Mānatthaddha đến gặp Thế Tôn; sau khi đến, đứng im lặng một bên. ",
  "sn7.15:1.11": "Thế Tôn không nói chuyện với ông. ",
  "sn7.15:1.12": "Bà-la-môn Mānatthaddha nghĩ: ",
  "sn7.15:1.13": "'Sa-môn Gotama này không biết gì cả' và muốn quay trở lại. ",
  "sn7.15:1.14": "Thế Tôn đọc được suy nghĩ trong tâm bà-la-môn Mānatthaddha, liền đọc bài kệ: ",
  "sn7.15:2.1": "'Này Bà-la-môn, ngã mạn không tốt, '",
  "sn7.15:2.2": "Cho người đang tìm cầu lợi ích; ",
  "sn7.15:2.3": "Hãy nuôi dưỡng mục đích mà ông đã đến, ",
  "sn7.15:2.4": "Chính vì mục đích đó mà ông tới.' ",
  "sn7.15:3.1": "Bà-la-môn Mānatthaddha nghĩ: ",
  "sn7.15:3.2": "'Sa-môn Gotama biết tâm ta.' Ông ngã xuống dưới chân Thế Tôn, hôn chân Ngài bằng miệng, xoa bằng tay, và nói tên mình: ",
  "sn7.15:3.3": "'Con là Mānatthaddha, thưa Gotama! Con là Mānatthaddha, thưa Gotama!' ",
  "sn7.15:3.4": "Đại chúng kinh ngạc sửng sốt: ",
  "sn7.15:3.5": "'Thật kỳ lạ! Thật phi thường! '",
  "sn7.15:3.6": "Bà-la-môn Mānatthaddha này không chào hỏi mẹ, không chào hỏi cha, không chào hỏi thầy, không chào hỏi anh cả; ",
  "sn7.15:3.7": "Vậy mà lại đảnh lễ sa-môn Gotama một cách cung kính tột bậc như vậy!' ",
  "sn7.15:3.8": "Thế Tôn nói với bà-la-môn Mānatthaddha: ",
  "sn7.15:3.9": "'Thôi được rồi, này Bà-la-môn, hãy đứng dậy, ngồi xuống chỗ ngồi của ông. '",
  "sn7.15:3.10": "Vì tâm ông đã tịnh tín đối với ta.' ",
  "sn7.15:3.11": "Bà-la-môn Mānatthaddha ngồi xuống chỗ ngồi của mình, rồi đọc bài kệ thưa với Thế Tôn: ",
  "sn7.15:4.1": "'Đối với ai không nên có ngã mạn, '",
  "sn7.15:4.2": "Đối với ai nên có sự cung kính; ",
  "sn7.15:4.3": "Ai nên được tôn trọng, ",
  "sn7.15:4.4": "Ai nên được cúng dường tốt đẹp?' ",
  "sn7.15:5.1": "'Đối với mẹ và cha, '",
  "sn7.15:5.2": "Và anh cả; ",
  "sn7.15:5.3": "Thứ tư là thầy giáo, ",
  "sn7.15:5.4": "Đối với họ không nên có ngã mạn; ",
  "sn7.15:5.5": "Đối với họ nên có sự cung kính, ",
  "sn7.15:5.6": "Họ nên được tôn trọng; ",
  "sn7.15:5.7": "Họ nên được cúng dường tốt đẹp. ",
  "sn7.15:6.1": "Đối với bậc A-la-hán mát mẻ, ",
  "sn7.15:6.2": "Đã làm xong việc, không còn lậu hoặc; ",
  "sn7.15:6.3": "Đã diệt trừ ngã mạn, không còn cứng đầu, ",
  "sn7.15:6.4": "Hãy lễ bái những bậc vô thượng đó.' ",
  "sn7.15:7.1": "Nghe vậy, bà-la-môn Mānatthaddha nói với Thế Tôn: ",
  "sn7.15:7.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.15:7.3": "xin Ngài Gotama nhận con là cư sĩ, từ hôm nay cho đến trọn đời quy y.' ",
  "sn7.16:0.1": "Tương Ưng Bộ 7.16 ",
  "sn7.16:0.2": "2. Phẩm Cư Sĩ ",
  "sn7.16:0.3": "Kinh Phản Đối ",
  "sn7.16:1.1": "Thuật lại tại Xá-vệ. ",
  "sn7.16:1.2": "Lúc bấy giờ, tại Xá-vệ có một bà-la-môn tên Paccanīkasāta đang sống. ",
  "sn7.16:1.3": "Bà-la-môn Paccanīkasāta nghĩ: ",
  "sn7.16:1.4": "'Ta hãy đến gặp sa-môn Gotama. '",
  "sn7.16:1.5": "Bất cứ điều gì sa-môn Gotama nói, ta sẽ phản đối tất cả.' ",
  "sn7.16:1.6": "Lúc bấy giờ, Thế Tôn đang đi kinh hành ngoài trời. ",
  "sn7.16:1.7": "Bà-la-môn Paccanīkasāta đến gặp Thế Tôn đang đi kinh hành, rồi nói: ",
  "sn7.16:1.8": "'Hãy nói Pháp của sa-môn đi.' ",
  "sn7.16:2.1": "'Người ưa phản đối, '",
  "sn7.16:2.2": "Khó nhận ra lời khéo nói; ",
  "sn7.16:2.3": "Tâm bị ô nhiễm, ",
  "sn7.16:2.4": "Đầy tranh cãi và xúc phạm. ",
  "sn7.16:3.1": "Người đã dẹp bỏ sự tranh cãi, ",
  "sn7.16:3.2": "Tâm không bất mãn; ",
  "sn7.16:3.3": "Đã từ bỏ sân hận, ",
  "sn7.16:3.4": "Người đó mới nhận ra lời khéo nói.' ",
  "sn7.16:4.1": "Nghe vậy, bà-la-môn Paccanīkasāta nói với Thế Tôn: ",
  "sn7.16:4.2": "'Thật vi diệu, thưa Gotama! Thật vi diệu, thưa Gotama …pe… '",
  "sn7.16:4.3": "xin Ngài Gotama nhận con là cư sĩ, từ hôm nay cho đến trọn đời quy y.' ",
  "sn7.17:0.1": "Tương Ưng Bộ 7.17 ",
  "sn7.17:0.2": "2. Phẩm Cư Sĩ ",
  "sn7.17:0.3": "Kinh Người Giám Sát Công Trình ",
  "sn7.17:1.1": "Một thời, Thế Tôn trú tại xứ Kosala, trong một khu rừng. ",
  "sn7.17:1.2": "Lúc bấy giờ, bà-la-môn Navakammika Bhāradvāja đang giám sát một công trình trong khu rừng đó. ",
  "sn7.17:1.3": "Bà-la-môn Navakammika Bhāradvāja thấy Thế Tôn đang ngồi kiết già dưới gốc cây sāla, lưng thẳng, chánh niệm hiện tiền. ",
  "sn7.17:1.4": "Thấy vậy, ông nghĩ: ",
  "sn7.17:1.5": "'Ta đang giám sát công trình trong khu rừng này mà cảm thấy vui. '",
  "sn7.17:1.6": "Sa-môn Gotama này đang giám sát công trình gì mà vui vậy?' ",
  "sn7.17:1.7": "Bà-la-môn Navakammika Bhāradvāja đến gặp Thế Tôn; sau khi đến, đọc bài kệ thưa với Ngài: ",
  "sn7.17:2.1": "'Công trình nào đang được làm, '",
  "sn7.17:2.2": "Thưa Tỳ Kheo, trong rừng sāla của Ngài; ",
  "sn7.17:2.3": "Một mình trong rừng sâu, ",
  "sn7.17:2.4": "Gotama tìm được gì mà vui?' ",
  "sn7.17:3.1": "'Không có việc gì cần làm trong rừng nữa, '",
  "sn7.17:3.2": "Khu rừng của ta đã bị đốn hết gốc rễ; ",
  "sn7.17:3.3": "Ta trong rừng, không còn rừng, không còn gai góc, ",
  "sn7.17:3.4": "Một mình vui vẻ, đã bỏ được sự không vui.' ",
  "sn7.17:4.1": "Nghe vậy, bà-la-môn Navakammika Bhāradvāja nói với Thế Tôn: ",
  "sn7.17:4.2": "'Thật vi diệu, thưa Gotama …pe… '",
  "sn7.17:4.3": "xin Ngài Gotama nhận con là cư sĩ, từ hôm nay cho đến trọn đời quy y.' ",
  "sn7.18:0.1": "Tương Ưng Bộ 7.18 ",
  "sn7.18:0.2": "2. Phẩm Cư Sĩ ",
  "sn7.18:0.3": "Kinh Người Kiếm Củi ",
  "sn7.18:1.1": "Một thời, Thế Tôn trú tại xứ Kosala, trong một khu rừng. ",
  "sn7.18:1.2": "Lúc bấy giờ, nhiều học trò đi kiếm củi của một vị bà-la-môn dòng họ Bhāradvāja đi vào khu rừng đó; sau khi vào, thấy Thế Tôn đang ngồi kiết già trong khu rừng đó, lưng thẳng, chánh niệm hiện tiền. Thấy vậy, họ đến gặp vị bà-la-môn Bhāradvāja; sau khi đến, nói với ông: ",
  "sn7.18:1.3": "'Bạch Ngài, xin Ngài biết cho. '",
  "sn7.18:1.4": "Trong khu rừng kia có một sa-môn đang ngồi kiết già, lưng thẳng, chánh niệm hiện tiền.' ",
  "sn7.18:1.5": "Vị bà-la-môn Bhāradvāja cùng các học trò đi vào khu rừng đó. ",
  "sn7.18:1.6": "Ông thấy Thế Tôn đang ngồi kiết già trong khu rừng đó, lưng thẳng, chánh niệm hiện tiền. ",
  "sn7.18:1.7": "Thấy vậy, ông đến gặp Thế Tôn; sau khi đến, đọc bài kệ thưa với Ngài: ",
  "sn7.18:2.1": "'Trong khu rừng sâu thẳm, đáng sợ hãi, '",
  "sn7.18:2.2": "Thâm nhập vào rừng hoang vắng, không người; ",
  "sn7.18:2.3": "Ngài ngồi bất động, oai nghi đẹp đẽ, ",
  "sn7.18:2.4": "Thật xinh đẹp, Tỳ Kheo đang thiền định. ",
  "sn7.18:3.1": "Nơi không có tiếng hát, không có tiếng nhạc, ",
  "sn7.18:3.2": "Bậc ẩn sĩ một mình trong rừng hoang; ",
  "sn7.18:3.3": "Điều này thật kỳ diệu đối với tôi, ",
  "sn7.18:3.4": "Khi một mình mà vui vẻ sống trong rừng. ",
  "sn7.18:4.1": "Tôi nghĩ Ngài muốn được làm bạn với vị chúa tể thế gian, ",
  "sn7.18:4.2": "Mong cầu cõi trời tối thượng; ",
  "sn7.18:4.3": "Sao Ngài lại ở ẩn trong rừng hoang, ",
  "sn7.18:4.4": "Tu khổ hạnh ở đây vì mục đích gì?' ",
  "sn7.18:5.1": "'Những nghi hoặc hay vui thích nào, '",
  "sn7.18:5.2": "Bám víu vào nhiều yếu tố khác nhau; ",
  "sn7.18:5.3": "Những lời nói xuất phát từ gốc rễ vô minh, ",
  "sn7.18:5.4": "Ta đã diệt tận tất cả cùng với gốc rễ. ",
  "sn7.18:6.1": "Ta không nghi hoặc, không bám víu, không phụ thuộc, ",
  "sn7.18:6.2": "Thấy rõ tất cả các pháp được thanh tịnh; ",
  "sn7.18:6.3": "Đạt được giác ngộ tối thượng, an lạc, ",
  "sn7.18:6.4": "Ta thiền định, thưa Bà-la-môn, một mình, tự tin.' ",
  "sn7.18:7.1": "Nghe vậy, vị bà-la-môn Bhāradvāja nói với Thế Tôn: ",
  "sn7.18:7.2": "'Thật vi diệu, thưa Gotama! Thật vi diệu, thưa Gotama …pe… '",
  "sn7.18:7.3": "từ hôm nay cho đến trọn đời quy y.' ",
  "sn7.19:0.1": "Tương Ưng Bộ 7.19 ",
  "sn7.19:0.2": "2. Phẩm Cư Sĩ ",
  "sn7.19:0.3": "Kinh Nuôi Mẹ ",
  "sn7.19:1.1": "Thuật lại tại Xá-vệ. ",
  "sn7.19:1.2": "Bà-la-môn Mātuposaka đến gặp Thế Tôn; sau khi đến, chào hỏi thân mật với Ngài. ",
  "sn7.19:1.3": "Sau khi trao đổi những lời thân ái đáng nhớ, ngồi xuống một bên. Ngồi một bên, bà-la-môn Mātuposaka nói với Thế Tôn: ",
  "sn7.19:1.4": "'Thưa Gotama, tôi đi khất thực đúng pháp, sau khi đi khất thực đúng pháp, tôi nuôi dưỡng cha mẹ. '",
  "sn7.19:1.5": "Thưa Gotama, làm như vậy, tôi có làm đúng bổn phận không?' ",
  "sn7.19:1.6": "'Đúng vậy, này Bà-la-môn, ông làm đúng bổn phận. '",
  "sn7.19:1.7": "Này Bà-la-môn, người nào đi khất thực đúng pháp, sau khi đi khất thực đúng pháp, nuôi dưỡng cha mẹ, người đó tạo ra nhiều công đức. ",
  "sn7.19:2.1": "Người phàm phu nào nuôi dưỡng cha hoặc mẹ, ",
  "sn7.19:2.2": "Đúng pháp; ",
  "sn7.19:2.3": "Do sự phụng dưỡng đó, ",
  "sn7.19:2.4": "Bậc trí đối với cha mẹ; ",
  "sn7.19:2.5": "Được người đời ca ngợi ngay tại đây, ",
  "sn7.19:2.6": "Và sau khi mất được hưởng phước trên cõi trời.' ",
  "sn7.19:3.1": "Nghe vậy, bà-la-môn Mātuposaka nói với Thế Tôn: ",
  "sn7.19:3.2": "'Thật vi diệu, thưa Gotama! Thật vi diệu, thưa Gotama …pe… '",
  "sn7.19:3.3": "xin Ngài Gotama nhận con là cư sĩ, từ hôm nay cho đến trọn đời quy y.' ",
  "sn7.20:0.1": "Tương Ưng Bộ 7.20 ",
  "sn7.20:0.2": "2. Phẩm Cư Sĩ ",
  "sn7.20:0.3": "Kinh Kẻ Ăn Xin ",
  "sn7.20:1.1": "Thuật lại tại Xá-vệ. ",
  "sn7.20:1.2": "Bà-la-môn Bhikkhaka đến gặp Thế Tôn; sau khi đến, chào hỏi thân mật với Ngài. ",
  "sn7.20:1.3": "Sau khi trao đổi những lời thân ái đáng nhớ, ngồi xuống một bên. Ngồi một bên, bà-la-môn Bhikkhaka nói với Thế Tôn: ",
  "sn7.20:1.4": "'Thưa Gotama, tôi là kẻ ăn xin, Ngài cũng là kẻ ăn xin, vậy sự khác biệt giữa chúng ta là gì?' ",
  "sn7.20:2.1": "'Không phải cứ đi xin người khác, '",
  "sn7.20:2.2": "Mà được gọi là kẻ ăn xin; ",
  "sn7.20:2.3": "Người chấp nhận một pháp đáng chê trách, ",
  "sn7.20:2.4": "Vẫn không phải là Tỳ Kheo vì điều đó. ",
  "sn7.20:3.1": "Người đã bỏ công đức và tội lỗi ở đây, ",
  "sn7.20:3.2": "Sống phạm hạnh; ",
  "sn7.20:3.3": "Sáng suốt sống trên đời, ",
  "sn7.20:3.4": "Người đó mới được gọi là Tỳ Kheo.' ",
  "sn7.20:4.1": "Nghe vậy, bà-la-môn Bhikkhaka nói với Thế Tôn: ",
  "sn7.20:4.2": "'Thật vi diệu, thưa Gotama! Thật vi diệu, thưa Gotama …pe… '",
  "sn7.20:4.3": "xin Ngài Gotama nhận con là cư sĩ, từ hôm nay cho đến trọn đời quy y.' ",
  "sn7.21:0.1": "Tương Ưng Bộ 7.21 ",
  "sn7.21:0.2": "2. Phẩm Cư Sĩ ",
  "sn7.21:0.3": "Kinh Saṅgārava ",
  "sn7.21:1.1": "Thuật lại tại Xá-vệ. ",
  "sn7.21:1.2": "Lúc bấy giờ, tại Xá-vệ có một bà-la-môn tên Saṅgārava tin vào sự thanh tịnh qua nước, cho rằng nước có thể thanh tịnh hóa, sáng tối đều tắm xuống nước để tu hành. ",
  "sn7.21:1.3": "Tôn giả Ānanda vào buổi sáng đắp y, mang bình bát, vào thành Xá-vệ khất thực. ",
  "sn7.21:1.4": "Sau khi đi khất thực tại Xá-vệ, trên đường trở về sau bữa ăn, Tôn giả Ānanda đến gặp Thế Tôn; sau khi đến, đảnh lễ Thế Tôn và ngồi xuống một bên. Ngồi một bên, Tôn giả Ānanda thưa với Thế Tôn: ",
  "sn7.21:1.5": "'Bạch Thế Tôn, tại Xá-vệ có bà-la-môn Saṅgārava tin vào sự thanh tịnh qua nước, cho rằng nước có thể thanh tịnh hóa, sáng tối đều tắm xuống nước. '",
  "sn7.21:1.6": "Lành thay, bạch Thế Tôn, nếu Ngài đến thăm nhà bà-la-môn Saṅgārava vì lòng từ bi.' ",
  "sn7.21:1.7": "Thế Tôn im lặng chấp thuận. ",
  "sn7.21:2.1": "Thế Tôn vào buổi sáng đắp y, mang bình bát, đi đến nhà bà-la-môn Saṅgārava; sau khi đến, ngồi vào chỗ đã soạn sẵn. ",
  "sn7.21:2.2": "Bà-la-môn Saṅgārava đến gặp Thế Tôn; sau khi đến, chào hỏi thân mật với Ngài. ",
  "sn7.21:2.3": "Sau khi trao đổi những lời thân ái đáng nhớ, ngồi xuống một bên. Thế Tôn hỏi bà-la-môn Saṅgārava đang ngồi một bên: ",
  "sn7.21:2.4": "'Này Bà-la-môn, nghe nói ông tin vào sự thanh tịnh qua nước, cho rằng nước có thể thanh tịnh hóa, sáng tối đều tắm xuống nước để tu hành, có đúng vậy không?' ",
  "sn7.21:2.5": "'Đúng vậy, thưa Gotama.' ",
  "sn7.21:2.6": "'Này Bà-la-môn, ông thấy có lợi ích gì mà tin vào sự thanh tịnh qua nước, cho rằng nước có thể thanh tịnh hóa, sáng tối đều tắm xuống nước?' ",
  "sn7.21:2.7": "'Thưa Gotama, điều ác nào tôi đã làm ban ngày, tôi rửa sạch bằng cách tắm chiều; điều ác nào tôi đã làm ban đêm, tôi rửa sạch bằng cách tắm sáng. '",
  "sn7.21:2.8": "Thưa Gotama, đó là lợi ích mà tôi thấy, nên tin vào sự thanh tịnh qua nước, sáng tối đều tắm xuống nước.' ",
  "sn7.21:3.1": "'Pháp là hồ, thưa Bà-la-môn, giới là bến tắm, '",
  "sn7.21:3.2": "Trong sáng, được bậc thiện tán thán; ",
  "sn7.21:3.3": "Nơi đây bậc đã đạt đích tắm gội, ",
  "sn7.21:3.4": "Thân không ướt mà vượt sang bờ kia.' ",
  "sn7.21:4.1": "Nghe vậy, bà-la-môn Saṅgārava nói với Thế Tôn: ",
  "sn7.21:4.2": "'Thật vi diệu, thưa Gotama! Thật vi diệu, thưa Gotama …pe… '",
  "sn7.21:4.3": "xin Ngài Gotama nhận con là cư sĩ, từ hôm nay cho đến trọn đời quy y.' ",
  "sn7.22:0.1": "Tương Ưng Bộ 7.22 ",
  "sn7.22:0.2": "2. Phẩm Cư Sĩ ",
  "sn7.22:0.3": "Kinh Vải Mịn ",
  "sn7.22:1.1": "Tôi nghe như vầy ",
  "sn7.22:1.2": "Một thời, Thế Tôn trú tại xứ Sakya, tại thị trấn của người Sakya tên Khomadussa. ",
  "sn7.22:1.3": "Thế Tôn vào buổi sáng đắp y, mang bình bát, vào thị trấn Khomadussa khất thực. ",
  "sn7.22:1.4": "Lúc bấy giờ, các bà-la-môn và gia chủ tại Khomadussa đang tụ họp trong hội trường vì một việc gì đó, và mưa đang rỏ từng giọt một. ",
  "sn7.22:1.5": "Thế Tôn đi đến hội trường đó. ",
  "sn7.22:1.6": "Các bà-la-môn và gia chủ tại Khomadussa thấy Thế Tôn từ xa đang đến. ",
  "sn7.22:1.7": "Thấy vậy, họ nói: ",
  "sn7.22:1.8": "'Những kẻ đầu trọc sa-môn này biết gì về phép tắc hội trường?' ",
  "sn7.22:1.9": "Thế Tôn đọc bài kệ cho các bà-la-môn và gia chủ tại Khomadussa: ",
  "sn7.22:2.1": "'Không phải hội trường nơi thiếu bậc thiện, '",
  "sn7.22:2.2": "Không phải bậc thiện kẻ không nói Pháp; ",
  "sn7.22:2.3": "Người đã buông bỏ tham, sân, si, ",
  "sn7.22:2.4": "Nói Pháp, đó mới là bậc thiện.' ",
  "sn7.22:3.1": "Nghe vậy, các bà-la-môn và gia chủ tại Khomadussa nói với Thế Tôn: ",
  "sn7.22:3.2": "'Thật vi diệu, thưa Gotama! Thật vi diệu, thưa Gotama! '",
  "sn7.22:3.3": "Ví như người dựng đứng lại những gì bị lật úp, hay mở ra những gì bị che kín, hay chỉ đường cho người bị lạc, hay thắp đèn dầu trong bóng tối để những ai có mắt có thể thấy sắc; cũng vậy, Pháp đã được Ngài Gotama trình bày bằng nhiều phương cách. ",
  "sn7.22:3.4": "Chúng con xin quy y Ngài Gotama, Pháp và Tăng đoàn Tỳ Kheo. ",
  "sn7.22:3.5": "Xin Ngài Gotama nhận chúng con là những cư sĩ, từ hôm nay cho đến trọn đời quy y.' ",
  "sn7.22:3.6": "Phẩm Cư Sĩ thứ hai. ",
  "sn7.22:4.0": "Tóm lược phẩm này ",
  "sn7.22:4.1": "Người cày, Udaya, Devahita, ",
  "sn7.22:4.2": "Một vị đại phú; ",
  "sn7.22:4.3": "Mānatthaddha, Paccanīka, ",
  "sn7.22:4.4": "Người giám sát công trình, người kiếm củi; ",
  "sn7.22:4.5": "Người nuôi mẹ, kẻ ăn xin, ",
  "sn7.22:4.6": "Saṅgārava và vải mịnmười hai kinh. ",
  "sn7.22:4.7": "Tương Ưng Bà-la-môn kết thúc. "
}
window.BILARA["sn7_v1"]["vi"]["sn7_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
