window.BILARA = window.BILARA || {};
window.BILARA["sn13_v1"] = window.BILARA["sn13_v1"] || {};
window.BILARA["sn13_v1"]["vi"] = {
  "sn13.1:0.1": "Tương Ưng Bộ 13.1 ",
  "sn13.1:0.2": "1. Phẩm Hiện Quán ",
  "sn13.1:0.3": "Kinh Đầu Móng Tay ",
  "sn13.1:1.1": "Tôi nghe như vầy",
  "sn13.1:1.2": "Một thời, Thế Tôn trú ở Sāvatthī, tại tu viện Jetavana của ông Anāthapiṇḍika. ",
  "sn13.1:1.3": "Rồi Thế Tôn đặt một chút bụi đất lên đầu móng tay và hỏi các Tỳ Kheo: ",
  "sn13.1:1.4": "'Này các Tỳ Kheo, các ông nghĩ sao? '",
  "sn13.1:1.5": "Cái nào nhiều hơn: chút bụi đất Ta đặt trên đầu móng tay này, hay đại địa này?' ",
  "sn13.1:2.1": "'Bạch Thế Tôn, đại địa mới là nhiều hơn. '",
  "sn13.1:2.2": "Chút bụi đất mà Thế Tôn đặt trên đầu móng tay thật là nhỏ nhoi. ",
  "sn13.1:2.3": "Chút bụi đất mà Thế Tôn đặt trên đầu móng tay, khi so với đại địa, thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn.' ",
  "sn13.1:2.4": "'Cũng vậy, này các Tỳ Kheo, đối với vị Thánh đệ tử thành tựu chánh kiến, đã hiện quán Pháp, khổ đau đã diệt tận, đã chấm dứt mới là nhiều hơn; '",
  "sn13.1:2.5": "còn lại chỉ là chút ít. ",
  "sn13.1:2.6": "Khi so khối khổ đau trước đây đã diệt tận, đã chấm dứt với phần còn lại  tối đa bảy lần tái sinh  thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn. ",
  "sn13.1:2.7": "Sự hiện quán Pháp, này các Tỳ Kheo, thật lợi ích lớn lao như vậy; ",
  "sn13.1:2.8": "được con mắt Pháp thật lợi ích lớn lao như vậy.' ",
  "sn13.1:2.9": "Thứ nhất. ",
  "sn13.2:0.1": "Tương Ưng Bộ 13.2 ",
  "sn13.2:0.2": "1. Phẩm Hiện Quán ",
  "sn13.2:0.3": "Kinh Ao Hồ ",
  "sn13.2:1.1": "Trú ở Sāvatthī. ",
  "sn13.2:1.2": "'Này các Tỳ Kheo, ví như có một cái ao dài năm mươi do tuần, rộng năm mươi do tuần, sâu năm mươi do tuần, đầy nước đến tận miệng, đến mức quạ có thể uống được. '",
  "sn13.2:1.3": "Rồi một người dùng ngọn cỏ kusa múc nước từ ao đó lên. ",
  "sn13.2:1.4": "Này các Tỳ Kheo, các ông nghĩ sao? ",
  "sn13.2:1.5": "Cái nào nhiều hơn: nước múc lên bằng ngọn cỏ kusa, hay nước trong ao?' ",
  "sn13.2:2.1": "'Bạch Thế Tôn, nước trong ao mới là nhiều hơn. '",
  "sn13.2:2.2": "Nước múc lên bằng ngọn cỏ kusa chỉ là chút ít. ",
  "sn13.2:2.3": "Nước múc lên bằng ngọn cỏ kusa, khi so với nước trong ao, thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn.' ",
  "sn13.2:3.1": "'Cũng vậy, này các Tỳ Kheo, đối với vị Thánh đệ tử thành tựu chánh kiến, đã hiện quán Pháp, khổ đau đã diệt tận, đã chấm dứt mới là nhiều hơn; còn lại chỉ là chút ít. '",
  "sn13.2:3.2": "Khi so khối khổ đau trước đây đã diệt tận, đã chấm dứt với phần còn lại  tối đa bảy lần tái sinh  thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn. ",
  "sn13.2:3.3": "Sự hiện quán Pháp, này các Tỳ Kheo, thật lợi ích lớn lao như vậy; được con mắt Pháp thật lợi ích lớn lao như vậy.' ",
  "sn13.2:3.4": "Thứ hai. ",
  "sn13.3:0.1": "Tương Ưng Bộ 13.3 ",
  "sn13.3:0.2": "1. Phẩm Hiện Quán ",
  "sn13.3:0.3": "Kinh Nước Hợp Lưu ",
  "sn13.3:1.1": "Trú ở Sāvatthī. ",
  "sn13.3:1.2": "'Này các Tỳ Kheo, ví như nơi mà các đại giang này hợp lưu, tụ hội, đó là'",
  "sn13.3:1.3": "Gaṅgā, Yamunā, Aciravatī, Sarabhū, Mahī, rồi một người lấy lên hai hay ba giọt nước. ",
  "sn13.3:1.4": "Này các Tỳ Kheo, các ông nghĩ sao? ",
  "sn13.3:1.5": "Cái nào nhiều hơn: hai hay ba giọt nước lấy lên, hay nước hợp lưu?' ",
  "sn13.3:2.1": "'Bạch Thế Tôn, nước hợp lưu mới là nhiều hơn; '",
  "sn13.3:2.2": "hai hay ba giọt nước lấy lên chỉ là chút ít. ",
  "sn13.3:2.3": "Hai hay ba giọt nước lấy lên, khi so với nước hợp lưu, thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn.' ",
  "sn13.3:2.4": "'Cũng vậy, này các Tỳ Kheo … (viết tắt) … '",
  "sn13.3:2.5": "được con mắt Pháp.' ",
  "sn13.3:2.6": "Thứ ba. ",
  "sn13.4:0.1": "Tương Ưng Bộ 13.4 ",
  "sn13.4:0.2": "1. Phẩm Hiện Quán ",
  "sn13.4:0.3": "Kinh Nước Hợp Lưu (II) ",
  "sn13.4:1.1": "Trú ở Sāvatthī. ",
  "sn13.4:1.2": "'Này các Tỳ Kheo, ví như nơi mà các đại giang này hợp lưu, tụ hội, đó là'",
  "sn13.4:1.3": "Gaṅgā, Yamunā, Aciravatī, Sarabhū, Mahī, nước đó sẽ cạn kiệt, chấm dứt, ngoại trừ hai hay ba giọt nước còn lại. ",
  "sn13.4:1.4": "Này các Tỳ Kheo, các ông nghĩ sao? ",
  "sn13.4:1.5": "Cái nào nhiều hơn: nước hợp lưu đã cạn kiệt, đã chấm dứt, hay hai hay ba giọt nước còn lại?' ",
  "sn13.4:2.1": "'Bạch Thế Tôn, nước hợp lưu đã cạn kiệt, đã chấm dứt mới là nhiều hơn; '",
  "sn13.4:2.2": "hai hay ba giọt nước còn lại chỉ là chút ít. ",
  "sn13.4:2.3": "Hai hay ba giọt nước còn lại, khi so với nước hợp lưu đã cạn kiệt, đã chấm dứt, thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn.' ",
  "sn13.4:2.4": "'Cũng vậy, này các Tỳ Kheo … (viết tắt) … '",
  "sn13.4:2.5": "được con mắt Pháp.' ",
  "sn13.4:2.6": "Thứ tư. ",
  "sn13.5:0.1": "Tương Ưng Bộ 13.5 ",
  "sn13.5:0.2": "1. Phẩm Hiện Quán ",
  "sn13.5:0.3": "Kinh Đại Địa ",
  "sn13.5:1.1": "Trú ở Sāvatthī. ",
  "sn13.5:1.2": "'Này các Tỳ Kheo, ví như một người đặt bảy viên đá tròn bằng hạt táo lên đại địa. '",
  "sn13.5:1.3": "Này các Tỳ Kheo, các ông nghĩ sao? ",
  "sn13.5:1.4": "Cái nào nhiều hơn: bảy viên đá tròn bằng hạt táo đặt lên, hay đại địa?' ",
  "sn13.5:2.1": "'Bạch Thế Tôn, đại địa mới là nhiều hơn; '",
  "sn13.5:2.2": "bảy viên đá tròn bằng hạt táo đặt lên chỉ là chút ít. ",
  "sn13.5:2.3": "Bảy viên đá tròn bằng hạt táo đặt lên, khi so với đại địa, thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn.' ",
  "sn13.5:2.4": "'Cũng vậy, này các Tỳ Kheo … (viết tắt) … '",
  "sn13.5:2.5": "được con mắt Pháp.' ",
  "sn13.5:2.6": "Thứ năm. ",
  "sn13.6:0.1": "Tương Ưng Bộ 13.6 ",
  "sn13.6:0.2": "1. Phẩm Hiện Quán ",
  "sn13.6:0.3": "Kinh Đại Địa (II) ",
  "sn13.6:1.1": "Trú ở Sāvatthī. ",
  "sn13.6:1.2": "'Này các Tỳ Kheo, ví như đại địa sẽ cạn kiệt, chấm dứt, ngoại trừ bảy viên đá tròn bằng hạt táo còn lại. '",
  "sn13.6:1.3": "Này các Tỳ Kheo, các ông nghĩ sao? ",
  "sn13.6:1.4": "Cái nào nhiều hơn: đại địa đã cạn kiệt, đã chấm dứt, hay bảy viên đá tròn bằng hạt táo còn lại?' ",
  "sn13.6:2.1": "'Bạch Thế Tôn, đại địa đã cạn kiệt, đã chấm dứt mới là nhiều hơn; '",
  "sn13.6:2.2": "bảy viên đá tròn bằng hạt táo còn lại chỉ là chút ít. ",
  "sn13.6:2.3": "Bảy viên đá tròn bằng hạt táo còn lại, khi so với đại địa đã cạn kiệt, đã chấm dứt, thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn.' ",
  "sn13.6:2.4": "'Cũng vậy, này các Tỳ Kheo … (viết tắt) … '",
  "sn13.6:2.5": "được con mắt Pháp.' ",
  "sn13.6:2.6": "Thứ sáu. ",
  "sn13.7:0.1": "Tương Ưng Bộ 13.7 ",
  "sn13.7:0.2": "1. Phẩm Hiện Quán ",
  "sn13.7:0.3": "Kinh Biển Lớn ",
  "sn13.7:1.1": "Trú ở Sāvatthī. ",
  "sn13.7:1.2": "'Này các Tỳ Kheo, ví như một người lấy hai hay ba giọt nước từ đại dương. '",
  "sn13.7:1.3": "Này các Tỳ Kheo, các ông nghĩ sao? ",
  "sn13.7:1.4": "Cái nào nhiều hơn: hai hay ba giọt nước lấy lên, hay nước trong đại dương?' ",
  "sn13.7:2.1": "'Bạch Thế Tôn, nước trong đại dương mới là nhiều hơn; '",
  "sn13.7:2.2": "hai hay ba giọt nước lấy lên chỉ là chút ít. ",
  "sn13.7:2.3": "Hai hay ba giọt nước lấy lên, khi so với nước trong đại dương, thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn.' ",
  "sn13.7:2.4": "'Cũng vậy, này các Tỳ Kheo … (viết tắt) … '",
  "sn13.7:2.5": "được con mắt Pháp.' ",
  "sn13.7:2.6": "Thứ bảy. ",
  "sn13.8:0.1": "Tương Ưng Bộ 13.8 ",
  "sn13.8:0.2": "1. Phẩm Hiện Quán ",
  "sn13.8:0.3": "Kinh Biển Lớn (II) ",
  "sn13.8:1.1": "Trú ở Sāvatthī. ",
  "sn13.8:1.2": "'Này các Tỳ Kheo, ví như đại dương sẽ cạn kiệt, chấm dứt, ngoại trừ hai hay ba giọt nước còn lại. '",
  "sn13.8:1.3": "Này các Tỳ Kheo, các ông nghĩ sao? ",
  "sn13.8:1.4": "Cái nào nhiều hơn: nước trong đại dương đã cạn kiệt, đã chấm dứt, hay hai hay ba giọt nước còn lại?' ",
  "sn13.8:2.1": "'Bạch Thế Tôn, nước trong đại dương đã cạn kiệt, đã chấm dứt mới là nhiều hơn; '",
  "sn13.8:2.2": "hai hay ba giọt nước còn lại chỉ là chút ít. ",
  "sn13.8:2.3": "Hai hay ba giọt nước còn lại, khi so với nước trong đại dương đã cạn kiệt, đã chấm dứt, thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn.' ",
  "sn13.8:2.4": "'Cũng vậy, này các Tỳ Kheo … (viết tắt) … '",
  "sn13.8:2.5": "được con mắt Pháp.' ",
  "sn13.8:2.6": "Thứ tám. ",
  "sn13.9:0.1": "Tương Ưng Bộ 13.9 ",
  "sn13.9:0.2": "1. Phẩm Hiện Quán ",
  "sn13.9:0.3": "Kinh Núi ",
  "sn13.9:1.1": "Trú ở Sāvatthī. ",
  "sn13.9:1.2": "'Này các Tỳ Kheo, ví như một người đặt bảy viên đá cuội bằng hạt mù tạt lên núi Himalaya, vua các núi. '",
  "sn13.9:1.3": "Này các Tỳ Kheo, các ông nghĩ sao? ",
  "sn13.9:1.4": "Cái nào nhiều hơn: bảy viên đá cuội bằng hạt mù tạt đặt lên, hay núi Himalaya, vua các núi?' ",
  "sn13.9:2.1": "'Bạch Thế Tôn, núi Himalaya, vua các núi mới là nhiều hơn; '",
  "sn13.9:2.2": "bảy viên đá cuội bằng hạt mù tạt đặt lên chỉ là chút ít. ",
  "sn13.9:2.3": "Bảy viên đá cuội bằng hạt mù tạt đặt lên, khi so với núi Himalaya, vua các núi, thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn.' ",
  "sn13.9:2.4": "'Cũng vậy … (viết tắt) … '",
  "sn13.9:2.5": "được con mắt Pháp.' ",
  "sn13.9:2.6": "Thứ chín. ",
  "sn13.10:0.1": "Tương Ưng Bộ 13.10 ",
  "sn13.10:0.2": "1. Phẩm Hiện Quán ",
  "sn13.10:0.3": "Kinh Núi (II) ",
  "sn13.10:1.1": "Trú ở Sāvatthī. ",
  "sn13.10:1.2": "'Này các Tỳ Kheo, ví như núi Himalaya, vua các núi, sẽ cạn kiệt, chấm dứt, ngoại trừ bảy viên đá cuội bằng hạt mù tạt còn lại. '",
  "sn13.10:1.3": "Này các Tỳ Kheo, các ông nghĩ sao? ",
  "sn13.10:1.4": "Cái nào nhiều hơn: núi Himalaya, vua các núi, đã cạn kiệt, đã chấm dứt, hay bảy viên đá cuội bằng hạt mù tạt còn lại?' ",
  "sn13.10:2.1": "'Bạch Thế Tôn, núi Himalaya, vua các núi, đã cạn kiệt, đã chấm dứt mới là nhiều hơn; '",
  "sn13.10:2.2": "bảy viên đá cuội bằng hạt mù tạt còn lại chỉ là chút ít. ",
  "sn13.10:2.3": "Bảy viên đá cuội bằng hạt mù tạt còn lại, khi so với núi Himalaya, vua các núi, đã cạn kiệt, đã chấm dứt, thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn.' ",
  "sn13.10:3.1": "'Cũng vậy, này các Tỳ Kheo, đối với vị Thánh đệ tử thành tựu chánh kiến, đã hiện quán Pháp, khổ đau đã diệt tận, đã chấm dứt mới là nhiều hơn; '",
  "sn13.10:3.2": "còn lại chỉ là chút ít. ",
  "sn13.10:3.3": "Khi so khối khổ đau trước đây đã diệt tận, đã chấm dứt với phần còn lại  tối đa bảy lần tái sinh  thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn. ",
  "sn13.10:3.4": "Sự hiện quán Pháp, này các Tỳ Kheo, thật lợi ích lớn lao như vậy, được con mắt Pháp thật lợi ích lớn lao như vậy.' ",
  "sn13.10:3.5": "Thứ mười. ",
  "sn13.11:0.1": "Tương Ưng Bộ 13.11 ",
  "sn13.11:0.2": "1. Phẩm Hiện Quán ",
  "sn13.11:0.3": "Kinh Núi (III) ",
  "sn13.11:1.1": "Trú ở Sāvatthī. ",
  "sn13.11:1.2": "'Này các Tỳ Kheo, ví như một người đặt bảy viên đá cuội bằng hạt đậu xanh lên núi Sineru, vua các núi. '",
  "sn13.11:1.3": "Này các Tỳ Kheo, các ông nghĩ sao? ",
  "sn13.11:1.4": "Cái nào nhiều hơn: bảy viên đá cuội bằng hạt đậu xanh đặt lên, hay núi Sineru, vua các núi?' ",
  "sn13.11:2.1": "'Bạch Thế Tôn, núi Sineru, vua các núi mới là nhiều hơn; '",
  "sn13.11:2.2": "bảy viên đá cuội bằng hạt đậu xanh đặt lên chỉ là chút ít. ",
  "sn13.11:2.3": "Bảy viên đá cuội bằng hạt đậu xanh đặt lên, khi so với núi Sineru, vua các núi, thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn.' ",
  "sn13.11:3.1": "'Cũng vậy, này các Tỳ Kheo, khi so sự thành tựu của vị Thánh đệ tử thành tựu chánh kiến với sự thành tựu của các sa-môn, bà-la-môn, du sĩ ngoại đạo, thì không đáng một phần trăm, một phần nghìn, một phần trăm nghìn. '",
  "sn13.11:3.2": "Vị thành tựu chánh kiến, này các Tỳ Kheo, thật đạt được thành tựu lớn lao như vậy, thật đạt được thắng trí lớn lao như vậy.' ",
  "sn13.11:3.3": "Thứ mười một. ",
  "sn13.11:3.4": "Tương Ưng Hiện Quán hoàn tất. ",
  "sn13.11:4.0": "Bài kệ tóm tắt ",
  "sn13.11:4.1": "Đầu móng tay, ao hồ, ",
  "sn13.11:4.2": "và hai kinh nước hợp lưu; ",
  "sn13.11:4.3": "Hai kinh đại địa, hai kinh biển lớn, ",
  "sn13.11:4.4": "và ba ví dụ về núi. "
}
window.BILARA["sn13_v1"]["vi"]["sn13_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
