window.BILARA = window.BILARA || {};
window.BILARA["sn14_v1"] = window.BILARA["sn14_v1"] || {};
window.BILARA["sn14_v1"]["vi"] = {
  "sn14.1:0.1": "Tương Ưng Bộ 14.1 ",
  "sn14.1:0.2": "1. Phẩm Sai Biệt ",
  "sn14.1:0.3": "Kinh Sai Biệt Các Giới ",
  "sn14.1:1.1": "Tại Sāvatthī. ",
  "sn14.1:1.2": "'Này các Tỳ Kheo, Ta sẽ giảng cho các ông về sự sai biệt của các giới. '",
  "sn14.1:1.3": "Hãy nghe và khéo tác ý, Ta sẽ nói.'  ",
  "sn14.1:1.4": "'Thưa vâng, bạch Thế Tôn.' Các Tỳ Kheo ấy vâng đáp Thế Tôn. ",
  "sn14.1:1.5": "Thế Tôn nói như sau: ",
  "sn14.1:2.1": "'Này các Tỳ Kheo, thế nào là sự sai biệt của các giới? '",
  "sn14.1:2.2": "Nhãn giới, sắc giới, nhãn thức giới; nhĩ giới, thanh giới, nhĩ thức giới; tỷ giới, hương giới, tỷ thức giới; thiệt giới, vị giới, thiệt thức giới; thân giới, xúc giới, thân thức giới; ý giới, pháp giới, ý thức giới ",
  "sn14.1:2.3": "này các Tỳ Kheo, đây được gọi là sự sai biệt của các giới.' ",
  "sn14.1:2.4": "Thứ nhất. ",
  "sn14.2:0.1": "Tương Ưng Bộ 14.2 ",
  "sn14.2:0.2": "1. Phẩm Sai Biệt ",
  "sn14.2:0.3": "Kinh Sai Biệt Của Xúc ",
  "sn14.2:1.1": "Tại Sāvatthī. ",
  "sn14.2:1.2": "'Này các Tỳ Kheo, duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của xúc. '",
  "sn14.2:1.3": "Này các Tỳ Kheo, thế nào là sự sai biệt của các giới? ",
  "sn14.2:1.4": "Nhãn giới, nhĩ giới, tỷ giới, thiệt giới, thân giới, ý giới ",
  "sn14.2:1.5": "này các Tỳ Kheo, đây được gọi là sự sai biệt của các giới. ",
  "sn14.2:2.1": "Và này các Tỳ Kheo, thế nào là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của xúc? ",
  "sn14.2:2.2": "Này các Tỳ Kheo, duyên vào nhãn giới mà khởi lên nhãn xúc. ",
  "sn14.2:2.3": "Duyên vào nhĩ giới… ",
  "sn14.2:2.4": "Duyên vào tỷ giới… ",
  "sn14.2:2.5": "Duyên vào thiệt giới… ",
  "sn14.2:2.6": "Duyên vào thân giới… ",
  "sn14.2:2.7": "Duyên vào ý giới mà khởi lên ý xúc. ",
  "sn14.2:2.8": "Này các Tỳ Kheo, như vậy là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của xúc.' ",
  "sn14.2:2.9": "Thứ hai. ",
  "sn14.3:0.1": "Tương Ưng Bộ 14.3 ",
  "sn14.3:0.2": "1. Phẩm Sai Biệt ",
  "sn14.3:0.3": "Kinh Không Phải Sai Biệt Của Xúc ",
  "sn14.3:1.1": "Tại Sāvatthī. ",
  "sn14.3:1.2": "'Này các Tỳ Kheo, duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của xúc, không phải duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của các giới. '",
  "sn14.3:1.3": "Này các Tỳ Kheo, thế nào là sự sai biệt của các giới? ",
  "sn14.3:1.4": "Nhãn giới …cho đến… ",
  "sn14.3:1.5": "ý giới ",
  "sn14.3:1.6": "này các Tỳ Kheo, đây được gọi là sự sai biệt của các giới. ",
  "sn14.3:2.1": "Và này các Tỳ Kheo, thế nào là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của xúc, không phải duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của các giới? ",
  "sn14.3:2.2": "Này các Tỳ Kheo, duyên vào nhãn giới mà khởi lên nhãn xúc, không phải duyên vào nhãn xúc mà khởi lên nhãn giới …cho đến… ",
  "sn14.3:2.3": "duyên vào ý giới mà khởi lên ý xúc, không phải duyên vào ý xúc mà khởi lên ý giới. ",
  "sn14.3:2.4": "Này các Tỳ Kheo, như vậy là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của xúc, không phải duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của các giới.' ",
  "sn14.3:2.5": "Thứ ba. ",
  "sn14.4:0.1": "Tương Ưng Bộ 14.4 ",
  "sn14.4:0.2": "1. Phẩm Sai Biệt ",
  "sn14.4:0.3": "Kinh Sai Biệt Của Thọ ",
  "sn14.4:1.1": "Tại Sāvatthī. ",
  "sn14.4:1.2": "'Này các Tỳ Kheo, duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của xúc, duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của thọ. '",
  "sn14.4:1.3": "Này các Tỳ Kheo, thế nào là sự sai biệt của các giới? ",
  "sn14.4:1.4": "Nhãn giới …cho đến… ý giới ",
  "sn14.4:1.5": "này các Tỳ Kheo, đây được gọi là sự sai biệt của các giới. ",
  "sn14.4:2.1": "Và này các Tỳ Kheo, thế nào là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của xúc, duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của thọ? ",
  "sn14.4:2.2": "Này các Tỳ Kheo, duyên vào nhãn giới mà khởi lên nhãn xúc, duyên vào nhãn xúc mà khởi lên thọ do nhãn xúc sinh …cho đến… ",
  "sn14.4:2.3": "duyên vào ý giới mà khởi lên ý xúc, duyên vào ý xúc mà khởi lên thọ do ý xúc sinh. ",
  "sn14.4:2.4": "Này các Tỳ Kheo, như vậy là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của xúc, duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của thọ.' ",
  "sn14.4:2.5": "Thứ tư. ",
  "sn14.5:0.1": "Tương Ưng Bộ 14.5 ",
  "sn14.5:0.2": "1. Phẩm Sai Biệt ",
  "sn14.5:0.3": "Kinh Sai Biệt Của Thọ (2) ",
  "sn14.5:1.1": "Tại Sāvatthī. ",
  "sn14.5:1.2": "'Này các Tỳ Kheo, duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của xúc, duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của thọ; không phải duyên vào sự sai biệt của thọ mà khởi lên sự sai biệt của xúc, không phải duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của các giới. '",
  "sn14.5:1.3": "Này các Tỳ Kheo, thế nào là sự sai biệt của các giới? ",
  "sn14.5:1.4": "Nhãn giới …cho đến… ý giới ",
  "sn14.5:1.5": "này các Tỳ Kheo, đây được gọi là sự sai biệt của các giới. ",
  "sn14.5:2.1": "Và này các Tỳ Kheo, thế nào là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của xúc, duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của thọ; không phải duyên vào sự sai biệt của thọ mà khởi lên sự sai biệt của xúc, không phải duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của các giới? ",
  "sn14.5:2.2": "Này các Tỳ Kheo, duyên vào nhãn giới mà khởi lên nhãn xúc, duyên vào nhãn xúc mà khởi lên thọ do nhãn xúc sinh; không phải duyên vào thọ do nhãn xúc sinh mà khởi lên nhãn xúc, không phải duyên vào nhãn xúc mà khởi lên nhãn giới …cho đến… ",
  "sn14.5:2.3": "duyên vào ý giới mà khởi lên ý xúc, duyên vào ý xúc mà khởi lên thọ do ý xúc sinh; không phải duyên vào thọ do ý xúc sinh mà khởi lên ý xúc, không phải duyên vào ý xúc mà khởi lên ý giới. ",
  "sn14.5:2.4": "Này các Tỳ Kheo, như vậy là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của xúc, duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của thọ; không phải duyên vào sự sai biệt của thọ mà khởi lên sự sai biệt của xúc, không phải duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của các giới.' ",
  "sn14.5:2.5": "Thứ năm. ",
  "sn14.6:0.1": "Tương Ưng Bộ 14.6 ",
  "sn14.6:0.2": "1. Phẩm Sai Biệt ",
  "sn14.6:0.3": "Kinh Sai Biệt Các Ngoại Giới ",
  "sn14.6:1.1": "Tại Sāvatthī. ",
  "sn14.6:1.2": "'Này các Tỳ Kheo, Ta sẽ giảng cho các ông về sự sai biệt của các giới. '",
  "sn14.6:1.3": "Hãy nghe …cho đến… ",
  "sn14.6:1.4": "này các Tỳ Kheo, thế nào là sự sai biệt của các giới? ",
  "sn14.6:1.5": "Sắc giới, thanh giới, hương giới, vị giới, xúc giới, pháp giới ",
  "sn14.6:1.6": "này các Tỳ Kheo, đây được gọi là sự sai biệt của các giới.' ",
  "sn14.6:1.7": "Thứ sáu. ",
  "sn14.7:0.1": "Tương Ưng Bộ 14.7 ",
  "sn14.7:0.2": "1. Phẩm Sai Biệt ",
  "sn14.7:0.3": "Kinh Sai Biệt Của Tưởng ",
  "sn14.7:1.1": "Tại Sāvatthī. ",
  "sn14.7:1.2": "'Này các Tỳ Kheo, duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của tưởng, duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của tư duy, duyên vào sự sai biệt của tư duy mà khởi lên sự sai biệt của dục, duyên vào sự sai biệt của dục mà khởi lên sự sai biệt của nhiệt não, duyên vào sự sai biệt của nhiệt não mà khởi lên sự sai biệt của tầm cầu. '",
  "sn14.7:1.3": "Này các Tỳ Kheo, thế nào là sự sai biệt của các giới? ",
  "sn14.7:1.4": "Sắc giới …cho đến… pháp giới ",
  "sn14.7:1.5": "này các Tỳ Kheo, đây được gọi là sự sai biệt của các giới. ",
  "sn14.7:2.1": "Và này các Tỳ Kheo, thế nào là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của tưởng, duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của tư duy, duyên vào sự sai biệt của tư duy mà khởi lên sự sai biệt của dục, duyên vào sự sai biệt của dục mà khởi lên sự sai biệt của nhiệt não, duyên vào sự sai biệt của nhiệt não mà khởi lên sự sai biệt của tầm cầu? ",
  "sn14.7:3.1": "Này các Tỳ Kheo, duyên vào sắc giới mà khởi lên sắc tưởng, duyên vào sắc tưởng mà khởi lên sắc tư duy, duyên vào sắc tư duy mà khởi lên sắc dục, duyên vào sắc dục mà khởi lên sắc nhiệt não, duyên vào sắc nhiệt não mà khởi lên sắc tầm cầu …cho đến… ",
  "sn14.7:3.2": "duyên vào pháp giới mà khởi lên pháp tưởng, duyên vào pháp tưởng mà khởi lên pháp tư duy, duyên vào pháp tư duy mà khởi lên pháp dục, duyên vào pháp dục mà khởi lên pháp nhiệt não, duyên vào pháp nhiệt não mà khởi lên pháp tầm cầu. ",
  "sn14.7:4.1": "Này các Tỳ Kheo, như vậy là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của tưởng, duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của tư duy, duyên vào sự sai biệt của tư duy mà khởi lên sự sai biệt của dục, duyên vào sự sai biệt của dục mà khởi lên sự sai biệt của nhiệt não, duyên vào sự sai biệt của nhiệt não mà khởi lên sự sai biệt của tầm cầu.' ",
  "sn14.7:4.2": "Thứ bảy. ",
  "sn14.8:0.1": "Tương Ưng Bộ 14.8 ",
  "sn14.8:0.2": "1. Phẩm Sai Biệt ",
  "sn14.8:0.3": "Kinh Không Phải Sai Biệt Của Tầm Cầu ",
  "sn14.8:1.1": "Tại Sāvatthī. ",
  "sn14.8:1.2": "'Này các Tỳ Kheo, duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của tưởng, duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của tư duy, duyên vào sự sai biệt của tư duy mà khởi lên sự sai biệt của dục, duyên vào sự sai biệt của dục mà khởi lên sự sai biệt của nhiệt não, duyên vào sự sai biệt của nhiệt não mà khởi lên sự sai biệt của tầm cầu; '",
  "sn14.8:1.3": "không phải duyên vào sự sai biệt của tầm cầu mà khởi lên sự sai biệt của nhiệt não, không phải duyên vào sự sai biệt của nhiệt não mà khởi lên sự sai biệt của dục, không phải duyên vào sự sai biệt của dục mà khởi lên sự sai biệt của tư duy, không phải duyên vào sự sai biệt của tư duy mà khởi lên sự sai biệt của tưởng, không phải duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của các giới. ",
  "sn14.8:1.4": "Này các Tỳ Kheo, thế nào là sự sai biệt của các giới? ",
  "sn14.8:1.5": "Sắc giới …cho đến… pháp giới ",
  "sn14.8:1.6": "này các Tỳ Kheo, đây được gọi là sự sai biệt của các giới. ",
  "sn14.8:2.1": "Và này các Tỳ Kheo, thế nào là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của tưởng, duyên vào sự sai biệt của tưởng mà khởi lên …cho đến… sự sai biệt của tầm cầu; ",
  "sn14.8:2.2": "không phải duyên vào sự sai biệt của tầm cầu mà khởi lên sự sai biệt của nhiệt não, không phải duyên vào sự sai biệt của nhiệt não mà khởi lên sự sai biệt của dục, không phải duyên vào sự sai biệt của dục mà khởi lên sự sai biệt của tư duy, không phải duyên vào sự sai biệt của tư duy mà khởi lên sự sai biệt của tưởng, không phải duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của các giới? ",
  "sn14.8:3.1": "Này các Tỳ Kheo, duyên vào sắc giới mà khởi lên sắc tưởng …cho đến… ",
  "sn14.8:3.2": "duyên vào pháp giới mà khởi lên pháp tưởng, duyên vào pháp tưởng mà khởi lên …cho đến… pháp tầm cầu; ",
  "sn14.8:3.3": "không phải duyên vào pháp tầm cầu mà khởi lên pháp nhiệt não, không phải duyên vào pháp nhiệt não mà khởi lên pháp dục, không phải duyên vào pháp dục mà khởi lên pháp tư duy, không phải duyên vào pháp tư duy mà khởi lên pháp tưởng, không phải duyên vào pháp tưởng mà khởi lên pháp giới. ",
  "sn14.8:4.1": "Này các Tỳ Kheo, như vậy là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của tưởng, duyên vào sự sai biệt của tưởng mà khởi lên …cho đến… sự sai biệt của tầm cầu; ",
  "sn14.8:4.2": "không phải duyên vào sự sai biệt của tầm cầu mà khởi lên sự sai biệt của nhiệt não, không phải duyên vào sự sai biệt của nhiệt não mà khởi lên sự sai biệt của dục, không phải duyên vào sự sai biệt của dục mà khởi lên sự sai biệt của tư duy, không phải duyên vào sự sai biệt của tư duy mà khởi lên sự sai biệt của tưởng, không phải duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của các giới.' ",
  "sn14.8:4.3": "Thứ tám. ",
  "sn14.9:0.1": "Tương Ưng Bộ 14.9 ",
  "sn14.9:0.2": "1. Phẩm Sai Biệt ",
  "sn14.9:0.3": "Kinh Sai Biệt Của Ngoại Xúc ",
  "sn14.9:1.1": "Tại Sāvatthī. ",
  "sn14.9:1.2": "'Này các Tỳ Kheo, duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của tưởng, duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của tư duy, duyên vào sự sai biệt của tư duy mà khởi lên sự sai biệt của xúc, duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của thọ, duyên vào sự sai biệt của thọ mà khởi lên sự sai biệt của dục, duyên vào sự sai biệt của dục mà khởi lên sự sai biệt của nhiệt não, duyên vào sự sai biệt của nhiệt não mà khởi lên sự sai biệt của tầm cầu, duyên vào sự sai biệt của tầm cầu mà khởi lên sự sai biệt của lợi đắc. '",
  "sn14.9:1.3": "Này các Tỳ Kheo, thế nào là sự sai biệt của các giới? ",
  "sn14.9:1.4": "Sắc giới …cho đến… pháp giới ",
  "sn14.9:1.5": "này các Tỳ Kheo, đây được gọi là sự sai biệt của các giới. ",
  "sn14.9:2.1": "Và này các Tỳ Kheo, thế nào là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của tưởng, duyên vào sự sai biệt của tưởng mà khởi lên …cho đến… sự sai biệt của lợi đắc? ",
  "sn14.9:3.1": "Này các Tỳ Kheo, duyên vào sắc giới mà khởi lên sắc tưởng, duyên vào sắc tưởng mà khởi lên sắc tư duy, duyên vào sắc tư duy mà khởi lên sắc xúc, duyên vào sắc xúc mà khởi lên thọ do sắc xúc sinh, duyên vào thọ do sắc xúc sinh mà khởi lên sắc dục, duyên vào sắc dục mà khởi lên sắc nhiệt não, duyên vào sắc nhiệt não mà khởi lên sắc tầm cầu, duyên vào sắc tầm cầu mà khởi lên sắc lợi đắc …cho đến… ",
  "sn14.9:3.2": "duyên vào pháp giới mà khởi lên pháp tưởng, duyên vào pháp tưởng mà khởi lên pháp tư duy, duyên vào pháp tư duy mà khởi lên pháp xúc, duyên vào pháp xúc mà khởi lên thọ do pháp xúc sinh, duyên vào thọ do pháp xúc sinh mà khởi lên pháp dục, duyên vào pháp dục mà khởi lên pháp nhiệt não, duyên vào pháp nhiệt não mà khởi lên pháp tầm cầu, duyên vào pháp tầm cầu mà khởi lên pháp lợi đắc. ",
  "sn14.9:4.1": "Này các Tỳ Kheo, như vậy là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của tưởng, duyên vào sự sai biệt của tưởng mà khởi lên …cho đến… sự sai biệt của tầm cầu, duyên vào sự sai biệt của tầm cầu mà khởi lên sự sai biệt của lợi đắc.' ",
  "sn14.9:4.2": "Thứ chín. ",
  "sn14.10:0.1": "Tương Ưng Bộ 14.10 ",
  "sn14.10:0.2": "1. Phẩm Sai Biệt ",
  "sn14.10:0.3": "Kinh Sai Biệt Của Ngoại Xúc (2) ",
  "sn14.10:1.1": "Tại Sāvatthī. ",
  "sn14.10:1.2": "'Này các Tỳ Kheo, duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của tưởng, '",
  "sn14.10:1.3": "duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của tư duy, ",
  "sn14.10:1.4": "xúc… ",
  "sn14.10:1.5": "thọ… ",
  "sn14.10:1.6": "dục… ",
  "sn14.10:1.7": "nhiệt não… ",
  "sn14.10:1.8": "duyên vào sự sai biệt của tầm cầu mà khởi lên sự sai biệt của lợi đắc; ",
  "sn14.10:1.9": "không phải duyên vào sự sai biệt của lợi đắc mà khởi lên sự sai biệt của tầm cầu, ",
  "sn14.10:1.10": "không phải duyên vào sự sai biệt của tầm cầu mà khởi lên sự sai biệt của nhiệt não, không phải duyên vào sự sai biệt của nhiệt não mà khởi lên …cho đến… ",
  "sn14.10:1.11": "dục… ",
  "sn14.10:1.12": "thọ… ",
  "sn14.10:1.13": "xúc… ",
  "sn14.10:1.14": "tư duy… ",
  "sn14.10:1.15": "sự sai biệt của tưởng, không phải duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của các giới. ",
  "sn14.10:1.16": "Này các Tỳ Kheo, thế nào là sự sai biệt của các giới? ",
  "sn14.10:1.17": "Sắc giới …cho đến… pháp giới ",
  "sn14.10:1.18": "này các Tỳ Kheo, đây được gọi là sự sai biệt của các giới. ",
  "sn14.10:2.1": "Và này các Tỳ Kheo, thế nào là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của tưởng, ",
  "sn14.10:2.2": "duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của tư duy? ",
  "sn14.10:2.3": "Xúc… ",
  "sn14.10:2.4": "thọ… ",
  "sn14.10:2.5": "dục… ",
  "sn14.10:2.6": "nhiệt não… ",
  "sn14.10:2.7": "tầm cầu… ",
  "sn14.10:2.8": "lợi đắc… ",
  "sn14.10:2.9": "không phải duyên vào sự sai biệt của lợi đắc mà khởi lên sự sai biệt của tầm cầu, ",
  "sn14.10:2.10": "không phải duyên vào sự sai biệt của tầm cầu mà khởi lên sự sai biệt của nhiệt não… ",
  "sn14.10:2.11": "dục… ",
  "sn14.10:2.12": "thọ… ",
  "sn14.10:2.13": "xúc… ",
  "sn14.10:2.14": "không phải duyên vào sự sai biệt của tư duy mà khởi lên sự sai biệt của tưởng, không phải duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của các giới? ",
  "sn14.10:3.1": "Này các Tỳ Kheo, duyên vào sắc giới mà khởi lên sắc tưởng …cho đến… ",
  "sn14.10:3.2": "duyên vào pháp giới mà khởi lên pháp tưởng, duyên vào pháp tưởng mà khởi lên …cho đến… ",
  "sn14.10:3.3": "pháp tầm cầu, duyên vào pháp tầm cầu mà khởi lên pháp lợi đắc; ",
  "sn14.10:3.4": "không phải duyên vào pháp lợi đắc mà khởi lên pháp tầm cầu, không phải duyên vào pháp tầm cầu mà khởi lên pháp nhiệt não, không phải duyên vào pháp nhiệt não mà khởi lên pháp dục, không phải duyên vào pháp dục mà khởi lên thọ do pháp xúc sinh, không phải duyên vào thọ do pháp xúc sinh mà khởi lên pháp xúc, không phải duyên vào pháp xúc mà khởi lên pháp tư duy, không phải duyên vào pháp tư duy mà khởi lên pháp tưởng, không phải duyên vào pháp tưởng mà khởi lên pháp giới. ",
  "sn14.10:4.1": "Này các Tỳ Kheo, như vậy là duyên vào sự sai biệt của các giới mà khởi lên sự sai biệt của tưởng, duyên vào sự sai biệt của tưởng mà khởi lên …cho đến… ",
  "sn14.10:4.2": "tư duy… ",
  "sn14.10:4.3": "xúc… ",
  "sn14.10:4.4": "thọ… ",
  "sn14.10:4.5": "dục… ",
  "sn14.10:4.6": "nhiệt não… ",
  "sn14.10:4.7": "tầm cầu… ",
  "sn14.10:4.8": "lợi đắc… ",
  "sn14.10:4.9": "không phải duyên vào sự sai biệt của lợi đắc mà khởi lên sự sai biệt của tầm cầu, không phải duyên vào sự sai biệt của tầm cầu mà khởi lên sự sai biệt của nhiệt não, không phải duyên vào sự sai biệt của nhiệt não mà khởi lên sự sai biệt của dục, không phải duyên vào sự sai biệt của dục mà khởi lên sự sai biệt của thọ, không phải duyên vào sự sai biệt của thọ mà khởi lên sự sai biệt của xúc, không phải duyên vào sự sai biệt của xúc mà khởi lên sự sai biệt của tư duy, không phải duyên vào sự sai biệt của tư duy mà khởi lên sự sai biệt của tưởng, không phải duyên vào sự sai biệt của tưởng mà khởi lên sự sai biệt của các giới.' ",
  "sn14.10:4.10": "Thứ mười. ",
  "sn14.10:4.11": "Phẩm Sai Biệt, thứ nhất. ",
  "sn14.10:5.0": "Tóm lược phẩm ",
  "sn14.10:5.1": "Giới, xúc, và không phải xúc, ",
  "sn14.10:5.2": "thọ thêm hai kinh khác; ",
  "sn14.10:5.3": "Đây là năm kinh nội phần, ",
  "sn14.10:5.4": "giới tưởng và không phải tưởng; ",
  "sn14.10:5.5": "Xúc thêm hai kinh khác, ",
  "sn14.10:5.6": "đây là năm kinh ngoại phần. ",
  "sn14.11:0.1": "Tương Ưng Bộ 14.11 ",
  "sn14.11:0.2": "2. Phẩm Thứ Hai ",
  "sn14.11:0.3": "Kinh Bảy Giới ",
  "sn14.11:1.1": "Tại Sāvatthī. ",
  "sn14.11:1.2": "'Này các Tỳ Kheo, có bảy giới này. '",
  "sn14.11:1.3": "Bảy giới ấy là gì? ",
  "sn14.11:1.4": "Quang giới, tịnh giới, không vô biên xứ giới, thức vô biên xứ giới, vô sở hữu xứ giới, phi tưởng phi phi tưởng xứ giới, tưởng thọ diệt giới ",
  "sn14.11:1.5": "này các Tỳ Kheo, đây là bảy giới ấy.' ",
  "sn14.11:2.1": "Khi nghe vậy, một Tỳ Kheo bạch Thế Tôn rằng: ",
  "sn14.11:2.2": "'Bạch Thế Tôn, quang giới, tịnh giới, không vô biên xứ giới, thức vô biên xứ giới, vô sở hữu xứ giới, phi tưởng phi phi tưởng xứ giới, và tưởng thọ diệt giớibạch Thế Tôn, các giới này được nhận biết nhờ duyên vào điều gì?' ",
  "sn14.11:3.1": "'Này Tỳ Kheo, quang giới nàygiới này được nhận biết nhờ duyên vào bóng tối. '",
  "sn14.11:3.2": "Này Tỳ Kheo, tịnh giới nàygiới này được nhận biết nhờ duyên vào bất tịnh. ",
  "sn14.11:3.3": "Này Tỳ Kheo, không vô biên xứ giới nàygiới này được nhận biết nhờ duyên vào sắc. ",
  "sn14.11:3.4": "Này Tỳ Kheo, thức vô biên xứ giới nàygiới này được nhận biết nhờ duyên vào không vô biên xứ. ",
  "sn14.11:3.5": "Này Tỳ Kheo, vô sở hữu xứ giới nàygiới này được nhận biết nhờ duyên vào thức vô biên xứ. ",
  "sn14.11:3.6": "Này Tỳ Kheo, phi tưởng phi phi tưởng xứ giới nàygiới này được nhận biết nhờ duyên vào vô sở hữu xứ. ",
  "sn14.11:3.7": "Này Tỳ Kheo, tưởng thọ diệt giới nàygiới này được nhận biết nhờ duyên vào sự diệt tận.' ",
  "sn14.11:4.1": "'Bạch Thế Tôn, quang giới, tịnh giới, không vô biên xứ giới, thức vô biên xứ giới, vô sở hữu xứ giới, phi tưởng phi phi tưởng xứ giới, và tưởng thọ diệt giớibạch Thế Tôn, các giới này được chứng đạt như thế nào?' ",
  "sn14.11:5.1": "'Này Tỳ Kheo, quang giới, tịnh giới, không vô biên xứ giới, thức vô biên xứ giới, vô sở hữu xứ giớicác giới này được chứng đạt bằng tưởng định. '",
  "sn14.11:5.2": "Này Tỳ Kheo, phi tưởng phi phi tưởng xứ giới nàygiới này được chứng đạt bằng hữu hành dư định. ",
  "sn14.11:5.3": "Này Tỳ Kheo, tưởng thọ diệt giới nàygiới này được chứng đạt bằng diệt tận định.' ",
  "sn14.11:5.4": "Thứ nhất. ",
  "sn14.12:0.1": "Tương Ưng Bộ 14.12 ",
  "sn14.12:0.2": "2. Phẩm Thứ Hai ",
  "sn14.12:0.3": "Kinh Có Nhân ",
  "sn14.12:1.1": "Tại Sāvatthī. ",
  "sn14.12:1.2": "'Này các Tỳ Kheo, dục tầm khởi lên là có nhân, không phải không nhân; sân tầm khởi lên là có nhân, không phải không nhân; hại tầm khởi lên là có nhân, không phải không nhân. '",
  "sn14.12:2.1": "Và này các Tỳ Kheo, thế nào là dục tầm khởi lên là có nhân, không phải không nhân; sân tầm khởi lên là có nhân, không phải không nhân; hại tầm khởi lên là có nhân, không phải không nhân? ",
  "sn14.12:2.2": "Này các Tỳ Kheo, duyên vào dục giới mà khởi lên dục tưởng, duyên vào dục tưởng mà khởi lên dục tư duy, duyên vào dục tư duy mà khởi lên dục dục, duyên vào dục dục mà khởi lên dục nhiệt não, duyên vào dục nhiệt não mà khởi lên dục tầm cầu. ",
  "sn14.12:2.3": "Này các Tỳ Kheo, kẻ phàm phu thiếu học, khi tầm cầu dục, hành động sai lạc ở ba chỗthân, khẩu, ý. ",
  "sn14.12:3.1": "Này các Tỳ Kheo, duyên vào sân giới mà khởi lên sân tưởng, duyên vào sân tưởng mà khởi lên sân tư duy …cho đến… sân dục… sân nhiệt não… sân tầm cầu… ",
  "sn14.12:3.2": "này các Tỳ Kheo, kẻ phàm phu thiếu học, khi tầm cầu sân, hành động sai lạc ở ba chỗthân, khẩu, ý. ",
  "sn14.12:4.1": "Này các Tỳ Kheo, duyên vào hại giới mà khởi lên hại tưởng; duyên vào hại tưởng mà khởi lên hại tư duy …cho đến… hại dục… hại nhiệt não… hại tầm cầu… ",
  "sn14.12:4.2": "này các Tỳ Kheo, kẻ phàm phu thiếu học, khi tầm cầu hại, hành động sai lạc ở ba chỗthân, khẩu, ý. ",
  "sn14.12:5.1": "Này các Tỳ Kheo, ví như một người ném bó đuốc cỏ đang cháy vào đống cỏ khô; nếu y không dùng tay chân dập tắt nhanh chóng, thì này các Tỳ Kheo, những sinh vật sống dựa vào cỏ và cây đó sẽ gặp tai họa, bất hạnh. ",
  "sn14.12:5.2": "Cũng vậy, này các Tỳ Kheo, nếu vị Sa-môn hay Bà-la-môn nào không nhanh chóng từ bỏ, xua đuổi, chấm dứt, diệt trừ tưởng lệch lạc đã khởi lên, vị ấy sống trong đau khổ ngay trong hiện tại, với phiền não, ưu tư, nhiệt não; ",
  "sn14.12:5.3": "và sau khi thân hoại mạng chung, sẽ đi đến ác thú. ",
  "sn14.12:6.1": "Này các Tỳ Kheo, xuất ly tầm khởi lên là có nhân, không phải không nhân; vô sân tầm khởi lên là có nhân, không phải không nhân; vô hại tầm khởi lên là có nhân, không phải không nhân. ",
  "sn14.12:7.1": "Và này các Tỳ Kheo, thế nào là xuất ly tầm khởi lên là có nhân, không phải không nhân; vô sân tầm khởi lên là có nhân, không phải không nhân; vô hại tầm khởi lên là có nhân, không phải không nhân? ",
  "sn14.12:7.2": "Này các Tỳ Kheo, duyên vào xuất ly giới mà khởi lên xuất ly tưởng, ",
  "sn14.12:7.3": "duyên vào xuất ly tưởng mà khởi lên xuất ly tư duy, ",
  "sn14.12:7.4": "duyên vào xuất ly tư duy mà khởi lên xuất ly dục, ",
  "sn14.12:7.5": "duyên vào xuất ly dục mà khởi lên xuất ly nhiệt não, ",
  "sn14.12:7.6": "duyên vào xuất ly nhiệt não mà khởi lên xuất ly tầm cầu; ",
  "sn14.12:7.7": "này các Tỳ Kheo, vị đa văn Thánh đệ tử, khi tầm cầu xuất ly, hành động đúng đắn ở ba chỗthân, khẩu, ý. ",
  "sn14.12:8.1": "Này các Tỳ Kheo, duyên vào vô sân giới mà khởi lên vô sân tưởng, ",
  "sn14.12:8.2": "duyên vào vô sân tưởng mà khởi lên vô sân tư duy …cho đến… ",
  "sn14.12:8.3": "vô sân dục… ",
  "sn14.12:8.4": "vô sân nhiệt não… ",
  "sn14.12:8.5": "vô sân tầm cầu, ",
  "sn14.12:8.6": "này các Tỳ Kheo, vị đa văn Thánh đệ tử, khi tầm cầu vô sân, hành động đúng đắn ở ba chỗthân, khẩu, ý. ",
  "sn14.12:9.1": "Này các Tỳ Kheo, duyên vào vô hại giới mà khởi lên vô hại tưởng, ",
  "sn14.12:9.2": "duyên vào vô hại tưởng mà khởi lên vô hại tư duy, ",
  "sn14.12:9.3": "duyên vào vô hại tư duy mà khởi lên vô hại dục, ",
  "sn14.12:9.4": "duyên vào vô hại dục mà khởi lên vô hại nhiệt não, ",
  "sn14.12:9.5": "duyên vào vô hại nhiệt não mà khởi lên vô hại tầm cầu; ",
  "sn14.12:9.6": "này các Tỳ Kheo, vị đa văn Thánh đệ tử, khi tầm cầu vô hại, hành động đúng đắn ở ba chỗthân, khẩu, ý. ",
  "sn14.12:10.1": "Này các Tỳ Kheo, ví như một người ném bó đuốc cỏ đang cháy vào đống cỏ khô; nếu y dùng tay chân dập tắt nhanh chóng, thì này các Tỳ Kheo, những sinh vật sống dựa vào cỏ và cây đó sẽ không gặp tai họa, bất hạnh. ",
  "sn14.12:10.2": "Cũng vậy, này các Tỳ Kheo, nếu vị Sa-môn hay Bà-la-môn nào nhanh chóng từ bỏ, xua đuổi, chấm dứt, diệt trừ tưởng lệch lạc đã khởi lên, vị ấy sống trong an lạc ngay trong hiện tại, không phiền não, không ưu tư, không nhiệt não; ",
  "sn14.12:10.3": "và sau khi thân hoại mạng chung, sẽ đi đến thiện thú.' ",
  "sn14.12:10.4": "Thứ hai. ",
  "sn14.13:0.1": "Tương Ưng Bộ 14.13 ",
  "sn14.13:0.2": "2. Phẩm Thứ Hai ",
  "sn14.13:0.3": "Kinh Nhà Gạch ",
  "sn14.13:1.1": "Một thời, Thế Tôn trú tại Ñātika, ở nhà gạch. ",
  "sn14.13:1.2": "Tại đó, Thế Tôn gọi các Tỳ Kheo: ",
  "sn14.13:1.3": "'Này các Tỳ Kheo.' ",
  "sn14.13:1.4": "'Thưa vâng, bạch Thế Tôn.' Các Tỳ Kheo ấy vâng đáp Thế Tôn. ",
  "sn14.13:1.5": "Thế Tôn nói như sau: ",
  "sn14.13:2.1": "'Này các Tỳ Kheo, duyên vào giới mà khởi lên tưởng, khởi lên kiến, khởi lên tầm.' ",
  "sn14.13:2.2": "Khi nghe vậy, Tôn giả Kaccāna bạch Thế Tôn rằng: ",
  "sn14.13:2.3": "'Bạch Thế Tôn, kiến này '",
  "sn14.13:2.4": "'Những kẻ không phải Bậc Chánh Đẳng Giác mà được cho là Bậc Chánh Đẳng Giác'bạch Thế Tôn, kiến này được nhận biết nhờ duyên vào điều gì?' '",
  "sn14.13:3.1": "'Này Kaccāna, đây là vô minh giới, một giới lớn. '",
  "sn14.13:3.2": "Này Kaccāna, duyên vào giới thấp kém mà khởi lên tưởng thấp kém, kiến thấp kém, tầm thấp kém, tư thấp kém, nguyện vọng thấp kém, ước nguyện thấp kém, cá nhân thấp kém, lời nói thấp kém; ",
  "sn14.13:3.3": "vị ấy tuyên bố, giảng dạy, trình bày, xác lập, khai mở, phân tích, làm rõ điều thấp kém; ",
  "sn14.13:3.4": "ta nói tái sinh của vị ấy là thấp kém. ",
  "sn14.13:4.1": "Này Kaccāna, duyên vào giới trung bình mà khởi lên tưởng trung bình, kiến trung bình, tầm trung bình, tư trung bình, nguyện vọng trung bình, ước nguyện trung bình, cá nhân trung bình, lời nói trung bình; ",
  "sn14.13:4.2": "vị ấy tuyên bố, giảng dạy, trình bày, xác lập, khai mở, phân tích, làm rõ điều trung bình; ",
  "sn14.13:4.3": "ta nói tái sinh của vị ấy là trung bình. ",
  "sn14.13:5.1": "Này Kaccāna, duyên vào giới cao thượng mà khởi lên tưởng cao thượng, kiến cao thượng, tầm cao thượng, tư cao thượng, nguyện vọng cao thượng, ước nguyện cao thượng, cá nhân cao thượng, lời nói cao thượng; ",
  "sn14.13:5.2": "vị ấy tuyên bố, giảng dạy, trình bày, xác lập, khai mở, phân tích, làm rõ điều cao thượng; ",
  "sn14.13:5.3": "ta nói tái sinh của vị ấy là cao thượng.' ",
  "sn14.13:5.4": "Thứ ba. ",
  "sn14.14:0.1": "Tương Ưng Bộ 14.14 ",
  "sn14.14:0.2": "2. Phẩm Thứ Hai ",
  "sn14.14:0.3": "Kinh Có Xu Hướng Thấp ",
  "sn14.14:1.1": "Tại Sāvatthī. ",
  "sn14.14:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.14:1.3": "Những người có xu hướng thấp hội tụ, gặp gỡ với những người có xu hướng thấp; ",
  "sn14.14:1.4": "những người có xu hướng thiện hội tụ, gặp gỡ với những người có xu hướng thiện. ",
  "sn14.14:2.1": "Này các Tỳ Kheo, trong thời quá khứ, chúng sinh cũng đã hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.14:2.2": "Những người có xu hướng thấp đã hội tụ, gặp gỡ với những người có xu hướng thấp; ",
  "sn14.14:2.3": "những người có xu hướng thiện đã hội tụ, gặp gỡ với những người có xu hướng thiện. ",
  "sn14.14:3.1": "Này các Tỳ Kheo, trong thời vị lai, chúng sinh sẽ hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.14:3.2": "Những người có xu hướng thấp sẽ hội tụ, gặp gỡ với những người có xu hướng thấp; ",
  "sn14.14:3.3": "những người có xu hướng thiện sẽ hội tụ, gặp gỡ với những người có xu hướng thiện. ",
  "sn14.14:4.1": "Này các Tỳ Kheo, trong thời hiện tại này, chúng sinh cũng đang hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.14:4.2": "Những người có xu hướng thấp hội tụ, gặp gỡ với những người có xu hướng thấp; ",
  "sn14.14:4.3": "những người có xu hướng thiện hội tụ, gặp gỡ với những người có xu hướng thiện.' ",
  "sn14.14:4.4": "Thứ tư. ",
  "sn14.15:0.1": "Tương Ưng Bộ 14.15 ",
  "sn14.15:0.2": "2. Phẩm Thứ Hai ",
  "sn14.15:0.3": "Kinh Kinh Hành ",
  "sn14.15:1.1": "Một thời, Thế Tôn trú tại Rājagaha, trên núi Gijjhakūṭa. ",
  "sn14.15:1.2": "Lúc bấy giờ, Tôn giả Sāriputta đang kinh hành cùng với nhiều Tỳ Kheo không xa Thế Tôn; ",
  "sn14.15:1.3": "Tôn giả Mahāmoggallāna cũng đang kinh hành cùng với nhiều Tỳ Kheo không xa Thế Tôn; ",
  "sn14.15:1.4": "Tôn giả Mahākassapa cũng đang kinh hành cùng với nhiều Tỳ Kheo không xa Thế Tôn; ",
  "sn14.15:1.5": "Tôn giả Anuruddha cũng đang kinh hành cùng với nhiều Tỳ Kheo không xa Thế Tôn; ",
  "sn14.15:1.6": "Tôn giả Puṇṇa Mantāniputta cũng đang kinh hành cùng với nhiều Tỳ Kheo không xa Thế Tôn; ",
  "sn14.15:1.7": "Tôn giả Upāli cũng đang kinh hành cùng với nhiều Tỳ Kheo không xa Thế Tôn; ",
  "sn14.15:1.8": "Tôn giả Ānanda cũng đang kinh hành cùng với nhiều Tỳ Kheo không xa Thế Tôn; ",
  "sn14.15:1.9": "Devadatta cũng đang kinh hành cùng với nhiều Tỳ Kheo không xa Thế Tôn. ",
  "sn14.15:2.1": "Rồi Thế Tôn gọi các Tỳ Kheo: ",
  "sn14.15:2.2": "'Này các Tỳ Kheo, các ông có thấy Sāriputta đang kinh hành cùng với nhiều Tỳ Kheo không?' ",
  "sn14.15:2.3": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn14.15:2.4": "'Này các Tỳ Kheo, tất cả những Tỳ Kheo ấy đều là bậc đại tuệ. '",
  "sn14.15:2.5": "Này các Tỳ Kheo, các ông có thấy Moggallāna đang kinh hành cùng với nhiều Tỳ Kheo không?' ",
  "sn14.15:2.6": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn14.15:2.7": "'Này các Tỳ Kheo, tất cả những Tỳ Kheo ấy đều là bậc đại thần lực. '",
  "sn14.15:2.8": "Này các Tỳ Kheo, các ông có thấy Kassapa đang kinh hành cùng với nhiều Tỳ Kheo không?' ",
  "sn14.15:2.9": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn14.15:2.10": "'Này các Tỳ Kheo, tất cả những Tỳ Kheo ấy đều là những người ủng hộ hạnh đầu đà. '",
  "sn14.15:2.11": "Này các Tỳ Kheo, các ông có thấy Anuruddha đang kinh hành cùng với nhiều Tỳ Kheo không?' ",
  "sn14.15:2.12": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn14.15:2.13": "'Này các Tỳ Kheo, tất cả những Tỳ Kheo ấy đều có thiên nhãn. '",
  "sn14.15:2.14": "Này các Tỳ Kheo, các ông có thấy Puṇṇa Mantāniputta đang kinh hành cùng với nhiều Tỳ Kheo không?' ",
  "sn14.15:2.15": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn14.15:2.16": "'Này các Tỳ Kheo, tất cả những Tỳ Kheo ấy đều là những người thuyết pháp. '",
  "sn14.15:2.17": "Này các Tỳ Kheo, các ông có thấy Upāli đang kinh hành cùng với nhiều Tỳ Kheo không?' ",
  "sn14.15:2.18": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn14.15:2.19": "'Này các Tỳ Kheo, tất cả những Tỳ Kheo ấy đều là những người trì luật. '",
  "sn14.15:2.20": "Này các Tỳ Kheo, các ông có thấy Ānanda đang kinh hành cùng với nhiều Tỳ Kheo không?' ",
  "sn14.15:2.21": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn14.15:2.22": "'Này các Tỳ Kheo, tất cả những Tỳ Kheo ấy đều là những người đa văn. '",
  "sn14.15:2.23": "Này các Tỳ Kheo, các ông có thấy Devadatta đang kinh hành cùng với nhiều Tỳ Kheo không?' ",
  "sn14.15:2.24": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn14.15:2.25": "'Này các Tỳ Kheo, tất cả những Tỳ Kheo ấy đều là những người có ác dục. '",
  "sn14.15:3.1": "Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.15:3.2": "Những người có xu hướng thấp hội tụ, gặp gỡ với những người có xu hướng thấp; ",
  "sn14.15:3.3": "những người có xu hướng thiện hội tụ, gặp gỡ với những người có xu hướng thiện. ",
  "sn14.15:3.4": "Này các Tỳ Kheo, trong thời quá khứ, chúng sinh cũng đã hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.15:3.5": "Những người có xu hướng thấp đã hội tụ, gặp gỡ với những người có xu hướng thấp; ",
  "sn14.15:3.6": "những người có xu hướng thiện đã hội tụ, gặp gỡ với những người có xu hướng thiện. ",
  "sn14.15:4.1": "Này các Tỳ Kheo, trong thời vị lai, chúng sinh sẽ hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.15:4.2": "Những người có xu hướng thấp sẽ hội tụ, gặp gỡ với những người có xu hướng thấp; ",
  "sn14.15:4.3": "những người có xu hướng thiện sẽ hội tụ, gặp gỡ với những người có xu hướng thiện. ",
  "sn14.15:5.1": "Này các Tỳ Kheo, trong thời hiện tại này, chúng sinh cũng đang hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.15:5.2": "Những người có xu hướng thấp hội tụ, gặp gỡ với những người có xu hướng thấp; ",
  "sn14.15:5.3": "những người có xu hướng thiện hội tụ, gặp gỡ với những người có xu hướng thiện.' ",
  "sn14.15:5.4": "Thứ năm. ",
  "sn14.16:0.1": "Tương Ưng Bộ 14.16 ",
  "sn14.16:0.2": "2. Phẩm Thứ Hai ",
  "sn14.16:0.3": "Kinh Có Kệ ",
  "sn14.16:1.1": "Tại Sāvatthī. ",
  "sn14.16:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.16:1.3": "Những người có xu hướng thấp hội tụ, gặp gỡ với những người có xu hướng thấp. ",
  "sn14.16:1.4": "Này các Tỳ Kheo, trong thời quá khứ, chúng sinh cũng đã hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.16:1.5": "Những người có xu hướng thấp đã hội tụ, gặp gỡ với những người có xu hướng thấp. ",
  "sn14.16:2.1": "Này các Tỳ Kheo, trong thời vị lai, chúng sinh sẽ hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.16:2.2": "Những người có xu hướng thấp sẽ hội tụ, gặp gỡ với những người có xu hướng thấp. ",
  "sn14.16:3.1": "Này các Tỳ Kheo, trong thời hiện tại này, chúng sinh cũng đang hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.16:3.2": "Những người có xu hướng thấp hội tụ, gặp gỡ với những người có xu hướng thấp. ",
  "sn14.16:4.1": "Này các Tỳ Kheo, ví như phân hội tụ với phân; ",
  "sn14.16:4.2": "nước tiểu hội tụ với nước tiểu; ",
  "sn14.16:4.3": "đờm nhớt hội tụ với đờm nhớt; ",
  "sn14.16:4.4": "mủ hội tụ với mủ; ",
  "sn14.16:4.5": "máu hội tụ với máu; ",
  "sn14.16:4.6": "cũng vậy, này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.16:4.7": "Những người có xu hướng thấp hội tụ, gặp gỡ với những người có xu hướng thấp. ",
  "sn14.16:4.8": "Trong thời quá khứ… ",
  "sn14.16:4.9": "trong thời vị lai… ",
  "sn14.16:4.10": "trong thời hiện tại này, chúng sinh cũng đang hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.16:4.11": "Những người có xu hướng thấp hội tụ, gặp gỡ với những người có xu hướng thấp. ",
  "sn14.16:5.1": "Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.16:5.2": "Những người có xu hướng thiện hội tụ, gặp gỡ với những người có xu hướng thiện. ",
  "sn14.16:5.3": "Này các Tỳ Kheo, trong thời quá khứ, chúng sinh cũng đã hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.16:5.4": "Những người có xu hướng thiện đã hội tụ, gặp gỡ với những người có xu hướng thiện. ",
  "sn14.16:6.1": "Trong thời vị lai… ",
  "sn14.16:6.2": "trong thời hiện tại này, chúng sinh cũng đang hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.16:6.3": "Những người có xu hướng thiện hội tụ, gặp gỡ với những người có xu hướng thiện. ",
  "sn14.16:7.1": "Này các Tỳ Kheo, ví như sữa hội tụ với sữa; ",
  "sn14.16:7.2": "dầu hội tụ với dầu; ",
  "sn14.16:7.3": "bơ hội tụ với bơ; ",
  "sn14.16:7.4": "mật hội tụ với mật; ",
  "sn14.16:7.5": "đường mía hội tụ với đường mía; ",
  "sn14.16:7.6": "cũng vậy, này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.16:7.7": "Những người có xu hướng thiện hội tụ, gặp gỡ với những người có xu hướng thiện. ",
  "sn14.16:7.8": "Trong thời quá khứ… ",
  "sn14.16:7.9": "trong thời vị lai… ",
  "sn14.16:7.10": "trong thời hiện tại này, chúng sinh cũng đang hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.16:7.11": "Những người có xu hướng thiện hội tụ, gặp gỡ với những người có xu hướng thiện.' ",
  "sn14.16:8.1": "Đây là điều Thế Tôn đã nói. ",
  "sn14.16:8.2": "Nói xong điều này, bậc Thiện Thệ, bậc Đạo Sư còn nói thêm: ",
  "sn14.16:9.1": "'Từ giao du, rừng tham ái sinh khởi, '",
  "sn14.16:9.2": "không giao du thì bị cắt đứt; ",
  "sn14.16:9.3": "Như leo lên khúc gỗ nhỏ, ",
  "sn14.16:9.4": "sẽ chìm đắm trong đại dương. ",
  "sn14.16:10.1": "Cũng vậy, gần kẻ biếng nhác, ",
  "sn14.16:10.2": "người sống thiện cũng chìm đắm; ",
  "sn14.16:10.3": "Do vậy, hãy xa lánh người ấy, ",
  "sn14.16:10.4": "kẻ biếng nhác, kém tinh tấn. ",
  "sn14.16:11.1": "Hãy sống cùng bậc Thánh viễn ly, ",
  "sn14.16:11.2": "chuyên tâm, thiền định; ",
  "sn14.16:11.3": "Thường trú cùng bậc tinh cần, ",
  "sn14.16:11.4": "bậc trí giả.' ",
  "sn14.16:11.5": "Thứ sáu. ",
  "sn14.17:0.1": "Tương Ưng Bộ 14.17 ",
  "sn14.17:0.2": "2. Phẩm Thứ Hai ",
  "sn14.17:0.3": "Kinh Người Không Có Tín Hội Tụ ",
  "sn14.17:1.1": "Tại Sāvatthī. ",
  "sn14.17:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.17:1.3": "Người không có tín hội tụ, gặp gỡ với người không có tín; ",
  "sn14.17:1.4": "người không có tàm hội tụ, gặp gỡ với người không có tàm; ",
  "sn14.17:1.5": "người không có úy hội tụ, gặp gỡ với người không có úy; ",
  "sn14.17:1.6": "người ít học hội tụ, gặp gỡ với người ít học; ",
  "sn14.17:1.7": "người biếng nhác hội tụ, gặp gỡ với người biếng nhác; ",
  "sn14.17:1.8": "người thất niệm hội tụ, gặp gỡ với người thất niệm; ",
  "sn14.17:1.9": "người kém trí hội tụ, gặp gỡ với người kém trí. ",
  "sn14.17:2.1": "Này các Tỳ Kheo, trong thời quá khứ, chúng sinh cũng đã hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.17:2.2": "Người không có tín đã hội tụ, gặp gỡ với người không có tín; ",
  "sn14.17:2.3": "người không có tàm đã hội tụ, gặp gỡ với người không có tàm; ",
  "sn14.17:2.4": "người không có úy đã hội tụ, gặp gỡ với người không có úy; ",
  "sn14.17:2.5": "người ít học đã hội tụ, gặp gỡ với người ít học; ",
  "sn14.17:2.6": "người biếng nhác đã hội tụ, gặp gỡ với người biếng nhác; ",
  "sn14.17:2.7": "người thất niệm đã hội tụ, gặp gỡ với người thất niệm; ",
  "sn14.17:2.8": "người kém trí đã hội tụ, gặp gỡ với người kém trí. ",
  "sn14.17:3.1": "Này các Tỳ Kheo, trong thời vị lai, chúng sinh sẽ hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.17:3.2": "Người không có tín sẽ hội tụ, gặp gỡ với người không có tín; ",
  "sn14.17:3.3": "người không có tàm sẽ hội tụ, gặp gỡ với người không có tàm; ",
  "sn14.17:3.4": "người không có úy…  ",
  "sn14.17:3.5": "người ít học… ",
  "sn14.17:3.6": "người biếng nhác… ",
  "sn14.17:3.7": "người thất niệm… ",
  "sn14.17:3.8": "người kém trí sẽ hội tụ, gặp gỡ với người kém trí. ",
  "sn14.17:4.1": "Này các Tỳ Kheo, trong thời hiện tại này, chúng sinh cũng đang hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.17:4.2": "Người không có tín hội tụ, gặp gỡ với người không có tín; ",
  "sn14.17:4.3": "người không có tàm… ",
  "sn14.17:4.4": "người không có úy… ",
  "sn14.17:4.5": "người ít học… ",
  "sn14.17:4.6": "người biếng nhác… ",
  "sn14.17:4.7": "người thất niệm hội tụ, gặp gỡ với người thất niệm; ",
  "sn14.17:4.8": "người kém trí hội tụ, gặp gỡ với người kém trí. ",
  "sn14.17:5.1": "Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.17:5.2": "Người có tín hội tụ, gặp gỡ với người có tín; ",
  "sn14.17:5.3": "người có tàm hội tụ, gặp gỡ với người có tàm; ",
  "sn14.17:5.4": "người có úy hội tụ, gặp gỡ với người có úy; ",
  "sn14.17:5.5": "người đa văn hội tụ, gặp gỡ với người đa văn; ",
  "sn14.17:5.6": "người tinh cần hội tụ, gặp gỡ với người tinh cần; ",
  "sn14.17:5.7": "người có niệm hội tụ, gặp gỡ với người có niệm; ",
  "sn14.17:5.8": "người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ. ",
  "sn14.17:5.9": "Trong thời quá khứ… ",
  "sn14.17:5.10": "trong thời vị lai… ",
  "sn14.17:5.11": "trong thời hiện tại này, chúng sinh cũng đang hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.17:5.12": "Người có tín… ",
  "sn14.17:5.13": "người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ.' ",
  "sn14.17:5.14": "Thứ bảy. ",
  "sn14.18:0.1": "Tương Ưng Bộ 14.18 ",
  "sn14.18:0.2": "2. Phẩm Thứ Hai ",
  "sn14.18:0.3": "Kinh Gốc Rễ Không Tín ",
  "sn14.18:1.1": "Tại Sāvatthī. ",
  "sn14.18:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.18:1.3": "Người không có tín hội tụ, gặp gỡ với người không có tín; ",
  "sn14.18:1.4": "người không có tàm hội tụ, gặp gỡ với người không có tàm; ",
  "sn14.18:1.5": "người kém trí hội tụ, gặp gỡ với người kém trí; ",
  "sn14.18:1.6": "người có tín hội tụ, gặp gỡ với người có tín; ",
  "sn14.18:1.7": "người có tàm hội tụ, gặp gỡ với người có tàm; ",
  "sn14.18:1.8": "người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ. ",
  "sn14.18:1.9": "Trong thời quá khứ, chúng sinh cũng đã hội tụ, gặp gỡ nhau theo giới …cho đến… ",
  "sn14.18:1.10": "trong thời vị lai, chúng sinh sẽ hội tụ, gặp gỡ nhau theo giới …cho đến…. ",
  "sn14.18:2.1": "Trong thời hiện tại này, chúng sinh cũng đang hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.18:2.2": "Người không có tín hội tụ, gặp gỡ với người không có tín; ",
  "sn14.18:2.3": "người không có tàm hội tụ, gặp gỡ với người không có tàm; người kém trí hội tụ, gặp gỡ với người kém trí; ",
  "sn14.18:2.4": "người có tín hội tụ, gặp gỡ với người có tín; ",
  "sn14.18:2.5": "người có tàm hội tụ, gặp gỡ với người có tàm; ",
  "sn14.18:2.6": "người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ. ",
  "sn14.18:3.1": "Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. ",
  "sn14.18:3.2": "Người không có tín hội tụ, gặp gỡ với người không có tín; ",
  "sn14.18:3.3": "người không có úy hội tụ, gặp gỡ với người không có úy; ",
  "sn14.18:3.4": "người kém trí hội tụ, gặp gỡ với người kém trí; ",
  "sn14.18:3.5": "người có tín hội tụ, gặp gỡ với người có tín; ",
  "sn14.18:3.6": "người có úy hội tụ, gặp gỡ với người có úy; ",
  "sn14.18:3.7": "người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ …cho đến… ",
  "sn14.18:3.8": "cần nói đầy đủ như đoạn đầu. ",
  "sn14.18:4.1": "Này các Tỳ Kheo, chúng sinh… ",
  "sn14.18:4.2": "người không có tín hội tụ, gặp gỡ với người không có tín; ",
  "sn14.18:4.3": "người ít học hội tụ, gặp gỡ với người ít học; ",
  "sn14.18:4.4": "người kém trí hội tụ, gặp gỡ với người kém trí; ",
  "sn14.18:4.5": "người có tín hội tụ, gặp gỡ với người có tín; người đa văn hội tụ, gặp gỡ với người đa văn; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ …cho đến…. ",
  "sn14.18:5.1": "Này các Tỳ Kheo, chúng sinh… ",
  "sn14.18:5.2": "người không có tín hội tụ, gặp gỡ với người không có tín; ",
  "sn14.18:5.3": "người biếng nhác hội tụ, gặp gỡ với người biếng nhác; ",
  "sn14.18:5.4": "người kém trí hội tụ, gặp gỡ với người kém trí; ",
  "sn14.18:5.5": "người có tín hội tụ, gặp gỡ với người có tín; ",
  "sn14.18:5.6": "người tinh cần hội tụ, gặp gỡ với người tinh cần; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ …cho đến…. ",
  "sn14.18:6.1": "Này các Tỳ Kheo, chúng sinh… ",
  "sn14.18:6.2": "người không có tín hội tụ, gặp gỡ với người không có tín; ",
  "sn14.18:6.3": "người thất niệm hội tụ, gặp gỡ với người thất niệm; ",
  "sn14.18:6.4": "người kém trí hội tụ, gặp gỡ với người kém trí; ",
  "sn14.18:6.5": "người có tín hội tụ, gặp gỡ với người có tín; ",
  "sn14.18:6.6": "người có niệm hội tụ, gặp gỡ với người có niệm; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ' …cho đến…. ",
  "sn14.18:6.7": "Thứ tám. ",
  "sn14.19:0.1": "Tương Ưng Bộ 14.19 ",
  "sn14.19:0.2": "2. Phẩm Thứ Hai ",
  "sn14.19:0.3": "Kinh Gốc Rễ Không Tàm ",
  "sn14.19:1.1": "Tại Sāvatthī. ",
  "sn14.19:1.2": "'Này các Tỳ Kheo, chúng sinh …cho đến… '",
  "sn14.19:1.3": "người không có tàm hội tụ, gặp gỡ với người không có tàm; người không có úy hội tụ, gặp gỡ với người không có úy; người kém trí hội tụ, gặp gỡ với người kém trí; người có tàm hội tụ, gặp gỡ với người có tàm; người có úy hội tụ, gặp gỡ với người có úy; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ …cho đến…. ",
  "sn14.19:2.1": "Người không có tàm hội tụ, gặp gỡ với người không có tàm; người ít học hội tụ, gặp gỡ với người ít học; người kém trí hội tụ, gặp gỡ với người kém trí; người có tàm hội tụ, gặp gỡ với người có tàm; người đa văn hội tụ, gặp gỡ với người đa văn; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ …cho đến…. ",
  "sn14.19:3.1": "Người không có tàm hội tụ, gặp gỡ với người không có tàm; người biếng nhác hội tụ, gặp gỡ với người biếng nhác; người kém trí hội tụ, gặp gỡ với người kém trí; người có tàm hội tụ, gặp gỡ với người có tàm; người tinh cần hội tụ, gặp gỡ với người tinh cần; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ …cho đến…. ",
  "sn14.19:4.1": "Người không có tàm hội tụ, gặp gỡ với người không có tàm; người thất niệm hội tụ, gặp gỡ với người thất niệm; người kém trí hội tụ, gặp gỡ với người kém trí; người có tàm hội tụ, gặp gỡ với người có tàm; người có niệm hội tụ, gặp gỡ với người có niệm; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ' …cho đến…. ",
  "sn14.19:4.2": "Thứ chín. ",
  "sn14.20:0.1": "Tương Ưng Bộ 14.20 ",
  "sn14.20:0.2": "2. Phẩm Thứ Hai ",
  "sn14.20:0.3": "Kinh Gốc Rễ Không Úy ",
  "sn14.20:1.1": "Tại Sāvatthī. ",
  "sn14.20:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.20:1.3": "Người không có úy hội tụ, gặp gỡ với người không có úy; ",
  "sn14.20:1.4": "người ít học hội tụ, gặp gỡ với người ít học; ",
  "sn14.20:1.5": "người kém trí hội tụ, gặp gỡ với người kém trí; ",
  "sn14.20:1.6": "người có úy hội tụ, gặp gỡ với người có úy; ",
  "sn14.20:1.7": "người đa văn hội tụ, gặp gỡ với người đa văn; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ …cho đến…. ",
  "sn14.20:2.1": "Người không có úy hội tụ, gặp gỡ với người không có úy; ",
  "sn14.20:2.2": "người biếng nhác hội tụ, gặp gỡ với người biếng nhác; ",
  "sn14.20:2.3": "người kém trí hội tụ, gặp gỡ với người kém trí; ",
  "sn14.20:2.4": "người có úy hội tụ, gặp gỡ với người có úy; ",
  "sn14.20:2.5": "người tinh cần hội tụ, gặp gỡ với người tinh cần; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ …cho đến…. ",
  "sn14.20:3.1": "Người không có úy hội tụ, gặp gỡ với người không có úy; ",
  "sn14.20:3.2": "người thất niệm hội tụ, gặp gỡ với người thất niệm; ",
  "sn14.20:3.3": "người kém trí hội tụ, gặp gỡ với người kém trí; ",
  "sn14.20:3.4": "người có úy hội tụ, gặp gỡ với người có úy; ",
  "sn14.20:3.5": "người có niệm hội tụ, gặp gỡ với người có niệm; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ' …cho đến…. ",
  "sn14.20:3.6": "Thứ mười. ",
  "sn14.21:0.1": "Tương Ưng Bộ 14.21 ",
  "sn14.21:0.2": "2. Phẩm Thứ Hai ",
  "sn14.21:0.3": "Kinh Gốc Rễ Ít Học ",
  "sn14.21:1.1": "Tại Sāvatthī. ",
  "sn14.21:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.21:1.3": "Người ít học hội tụ, gặp gỡ với người ít học; ",
  "sn14.21:1.4": "người biếng nhác hội tụ, gặp gỡ với người biếng nhác; ",
  "sn14.21:1.5": "người kém trí hội tụ, gặp gỡ với người kém trí; ",
  "sn14.21:1.6": "người đa văn hội tụ, gặp gỡ với người đa văn; ",
  "sn14.21:1.7": "người tinh cần hội tụ, gặp gỡ với người tinh cần; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ …cho đến…. ",
  "sn14.21:2.1": "Người ít học hội tụ, gặp gỡ với người ít học; ",
  "sn14.21:2.2": "người thất niệm hội tụ, gặp gỡ với người thất niệm; ",
  "sn14.21:2.3": "người kém trí hội tụ, gặp gỡ với người kém trí; ",
  "sn14.21:2.4": "người đa văn hội tụ, gặp gỡ với người đa văn; ",
  "sn14.21:2.5": "người có niệm hội tụ, gặp gỡ với người có niệm; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ' …cho đến…. ",
  "sn14.21:2.6": "Thứ mười một. ",
  "sn14.22:0.1": "Tương Ưng Bộ 14.22 ",
  "sn14.22:0.2": "2. Phẩm Thứ Hai ",
  "sn14.22:0.3": "Kinh Gốc Rễ Biếng Nhác ",
  "sn14.22:1.1": "Tại Sāvatthī. ",
  "sn14.22:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.22:1.3": "Người biếng nhác hội tụ, gặp gỡ với người biếng nhác; ",
  "sn14.22:1.4": "người thất niệm hội tụ, gặp gỡ với người thất niệm; ",
  "sn14.22:1.5": "người kém trí hội tụ, gặp gỡ với người kém trí; ",
  "sn14.22:1.6": "người tinh cần hội tụ, gặp gỡ với người tinh cần; ",
  "sn14.22:1.7": "người có niệm hội tụ, gặp gỡ với người có niệm; người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ' …cho đến…. ",
  "sn14.22:1.8": "Thứ mười hai. ",
  "sn14.22:1.9": "(Ở mọi chỗ cần thêm quá khứ, vị lai, hiện tại.) ",
  "sn14.22:1.10": "Phẩm thứ hai. ",
  "sn14.22:2.0": "Tóm lược phẩm ",
  "sn14.22:2.1": "Bảy giới, có nhân, ",
  "sn14.22:2.2": "nhà gạch; ",
  "sn14.22:2.3": "Xu hướng thấp, kinh hành, ",
  "sn14.22:2.4": "có kệ, không tín thứ bảy. ",
  "sn14.22:3.1": "Gốc rễ không tín năm kinh, ",
  "sn14.22:3.2": "gốc rễ không tàm bốn kinh; ",
  "sn14.22:3.3": "Gốc rễ không úy ba kinh, ",
  "sn14.22:3.4": "hai kinh về ít học. ",
  "sn14.22:4.1": "Biếng nhác một kinh được nói, ",
  "sn14.22:4.2": "ba kinh có năm nhóm; ",
  "sn14.22:4.3": "Hai mươi hai kinh được nói, ",
  "sn14.22:4.4": "đây gọi là phẩm thứ hai. ",
  "sn14.23:0.1": "Tương Ưng Bộ 14.23 ",
  "sn14.23:0.2": "3. Phẩm Nghiệp Đạo ",
  "sn14.23:0.3": "Kinh Không Định ",
  "sn14.23:1.1": "Tại Sāvatthī. ",
  "sn14.23:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.23:1.3": "Người không có tín hội tụ, gặp gỡ với người không có tín; ",
  "sn14.23:1.4": "người không có tàm hội tụ, gặp gỡ với người không có tàm; ",
  "sn14.23:1.5": "người không có úy hội tụ, gặp gỡ với người không có úy; ",
  "sn14.23:1.6": "người không định hội tụ, gặp gỡ với người không định; ",
  "sn14.23:1.7": "người kém trí hội tụ, gặp gỡ với người kém trí. ",
  "sn14.23:2.1": "Người có tín hội tụ, gặp gỡ với người có tín; ",
  "sn14.23:2.2": "người có tàm hội tụ, gặp gỡ với người có tàm; ",
  "sn14.23:2.3": "người có úy hội tụ, gặp gỡ với người có úy; ",
  "sn14.23:2.4": "người có định hội tụ, gặp gỡ với người có định; ",
  "sn14.23:2.5": "người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ.' ",
  "sn14.23:2.6": "Thứ nhất. ",
  "sn14.24:0.1": "Tương Ưng Bộ 14.24 ",
  "sn14.24:0.2": "3. Phẩm Nghiệp Đạo ",
  "sn14.24:0.3": "Kinh Phá Giới ",
  "sn14.24:1.1": "Tại Sāvatthī. ",
  "sn14.24:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.24:1.3": "Người không có tín hội tụ, gặp gỡ với người không có tín; ",
  "sn14.24:1.4": "người không có tàm hội tụ, gặp gỡ với người không có tàm; ",
  "sn14.24:1.5": "người không có úy hội tụ, gặp gỡ với người không có úy; ",
  "sn14.24:1.6": "người phá giới hội tụ, gặp gỡ với người phá giới; ",
  "sn14.24:1.7": "người kém trí hội tụ, gặp gỡ với người kém trí. ",
  "sn14.24:2.1": "Người có tín hội tụ, gặp gỡ với người có tín; ",
  "sn14.24:2.2": "người có tàm hội tụ, gặp gỡ với người có tàm; ",
  "sn14.24:2.3": "người có úy hội tụ, gặp gỡ với người có úy; ",
  "sn14.24:2.4": "người có giới hội tụ, gặp gỡ với người có giới; ",
  "sn14.24:2.5": "người có trí tuệ hội tụ, gặp gỡ với người có trí tuệ.' ",
  "sn14.24:2.6": "Thứ hai. ",
  "sn14.25:0.1": "Tương Ưng Bộ 14.25 ",
  "sn14.25:0.2": "3. Phẩm Nghiệp Đạo ",
  "sn14.25:0.3": "Kinh Năm Giới ",
  "sn14.25:1.1": "Tại Sāvatthī. ",
  "sn14.25:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.25:1.3": "Người sát sinh hội tụ, gặp gỡ với người sát sinh; ",
  "sn14.25:1.4": "người trộm cắp hội tụ, gặp gỡ với người trộm cắp; ",
  "sn14.25:1.5": "người tà dâm hội tụ, gặp gỡ với người tà dâm; ",
  "sn14.25:1.6": "người nói dối hội tụ, gặp gỡ với người nói dối; ",
  "sn14.25:1.7": "người uống rượu bia đến mức phóng dật hội tụ, gặp gỡ với người uống rượu bia đến mức phóng dật. ",
  "sn14.25:2.1": "Người từ bỏ sát sinh hội tụ, gặp gỡ với người từ bỏ sát sinh; ",
  "sn14.25:2.2": "người từ bỏ trộm cắp hội tụ, gặp gỡ với người từ bỏ trộm cắp; ",
  "sn14.25:2.3": "người từ bỏ tà dâm hội tụ, gặp gỡ với người từ bỏ tà dâm; ",
  "sn14.25:2.4": "người từ bỏ nói dối hội tụ, gặp gỡ với người từ bỏ nói dối; ",
  "sn14.25:2.5": "người từ bỏ uống rượu bia đến mức phóng dật hội tụ, gặp gỡ với người từ bỏ uống rượu bia đến mức phóng dật.' ",
  "sn14.25:2.6": "Thứ ba. ",
  "sn14.26:0.1": "Tương Ưng Bộ 14.26 ",
  "sn14.26:0.2": "3. Phẩm Nghiệp Đạo ",
  "sn14.26:0.3": "Kinh Bảy Nghiệp Đạo ",
  "sn14.26:1.1": "Tại Sāvatthī. ",
  "sn14.26:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.26:1.3": "Người sát sinh hội tụ, gặp gỡ với người sát sinh; ",
  "sn14.26:1.4": "người trộm cắp hội tụ, gặp gỡ với người trộm cắp; ",
  "sn14.26:1.5": "người tà dâm hội tụ, gặp gỡ với người tà dâm; ",
  "sn14.26:1.6": "người nói dối hội tụ, gặp gỡ với người nói dối; ",
  "sn14.26:1.7": "người nói lời chia rẽ hội tụ, gặp gỡ với người nói lời chia rẽ; ",
  "sn14.26:1.8": "người nói lời thô ác hội tụ, gặp gỡ với người nói lời thô ác; ",
  "sn14.26:1.9": "người nói lời vô nghĩa hội tụ, gặp gỡ với người nói lời vô nghĩa. ",
  "sn14.26:2.1": "Người từ bỏ sát sinh …cho đến… ",
  "sn14.26:2.2": "người từ bỏ trộm cắp… ",
  "sn14.26:2.3": "người từ bỏ tà dâm… ",
  "sn14.26:2.4": "người từ bỏ nói dối… ",
  "sn14.26:2.5": "người từ bỏ nói lời chia rẽ hội tụ, gặp gỡ với người từ bỏ nói lời chia rẽ; ",
  "sn14.26:2.6": "người từ bỏ nói lời thô ác hội tụ, gặp gỡ với người từ bỏ nói lời thô ác; ",
  "sn14.26:2.7": "người từ bỏ nói lời vô nghĩa hội tụ, gặp gỡ với người từ bỏ nói lời vô nghĩa.' ",
  "sn14.26:2.8": "Thứ tư. ",
  "sn14.27:0.1": "Tương Ưng Bộ 14.27 ",
  "sn14.27:0.2": "3. Phẩm Nghiệp Đạo ",
  "sn14.27:0.3": "Kinh Mười Nghiệp Đạo ",
  "sn14.27:1.1": "Tại Sāvatthī. ",
  "sn14.27:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.27:1.3": "Người sát sinh hội tụ, gặp gỡ với người sát sinh; ",
  "sn14.27:1.4": "người trộm cắp …cho đến… ",
  "sn14.27:1.5": "người tà dâm… ",
  "sn14.27:1.6": "người nói dối… ",
  "sn14.27:1.7": "người nói lời chia rẽ… ",
  "sn14.27:1.8": "người nói lời thô ác… ",
  "sn14.27:1.9": "người nói lời vô nghĩa hội tụ, gặp gỡ với người nói lời vô nghĩa; ",
  "sn14.27:1.10": "người tham dục hội tụ, gặp gỡ với người tham dục; ",
  "sn14.27:1.11": "người có tâm sân hội tụ, gặp gỡ với người có tâm sân; ",
  "sn14.27:1.12": "người có tà kiến hội tụ, gặp gỡ với người có tà kiến. ",
  "sn14.27:2.1": "Người từ bỏ sát sinh hội tụ, gặp gỡ với người từ bỏ sát sinh; ",
  "sn14.27:2.2": "người từ bỏ trộm cắp …cho đến… ",
  "sn14.27:2.3": "người từ bỏ tà dâm… ",
  "sn14.27:2.4": "người từ bỏ nói dối… ",
  "sn14.27:2.5": "người từ bỏ nói lời chia rẽ… ",
  "sn14.27:2.6": "người từ bỏ nói lời thô ác… ",
  "sn14.27:2.7": "người từ bỏ nói lời vô nghĩa hội tụ, gặp gỡ với người từ bỏ nói lời vô nghĩa; ",
  "sn14.27:2.8": "người không tham dục hội tụ, gặp gỡ với người không tham dục; ",
  "sn14.27:2.9": "người không có tâm sân hội tụ, gặp gỡ với người không có tâm sân; ",
  "sn14.27:2.10": "người có chánh kiến hội tụ, gặp gỡ với người có chánh kiến.' ",
  "sn14.27:2.11": "Thứ năm. ",
  "sn14.28:0.1": "Tương Ưng Bộ 14.28 ",
  "sn14.28:0.2": "3. Phẩm Nghiệp Đạo ",
  "sn14.28:0.3": "Kinh Tám Chi ",
  "sn14.28:1.1": "Tại Sāvatthī. ",
  "sn14.28:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.28:1.3": "Người có tà kiến hội tụ, gặp gỡ với người có tà kiến; ",
  "sn14.28:1.4": "người có tà tư duy …cho đến… ",
  "sn14.28:1.5": "người có tà ngữ… ",
  "sn14.28:1.6": "người có tà nghiệp… ",
  "sn14.28:1.7": "người có tà mạng… ",
  "sn14.28:1.8": "người có tà tinh tấn… ",
  "sn14.28:1.9": "người có tà niệm… ",
  "sn14.28:1.10": "người có tà định hội tụ, gặp gỡ với người có tà định. ",
  "sn14.28:2.1": "Người có chánh kiến hội tụ, gặp gỡ với người có chánh kiến; ",
  "sn14.28:2.2": "người có chánh tư duy …cho đến… ",
  "sn14.28:2.3": "người có chánh ngữ… ",
  "sn14.28:2.4": "người có chánh nghiệp… ",
  "sn14.28:2.5": "người có chánh mạng… ",
  "sn14.28:2.6": "người có chánh tinh tấn… ",
  "sn14.28:2.7": "người có chánh niệm… ",
  "sn14.28:2.8": "người có chánh định hội tụ, gặp gỡ với người có chánh định.' ",
  "sn14.28:2.9": "Thứ sáu. ",
  "sn14.29:0.1": "Tương Ưng Bộ 14.29 ",
  "sn14.29:0.2": "3. Phẩm Nghiệp Đạo ",
  "sn14.29:0.3": "Kinh Mười Chi ",
  "sn14.29:1.1": "Tại Sāvatthī. ",
  "sn14.29:1.2": "'Này các Tỳ Kheo, chúng sinh hội tụ, gặp gỡ nhau theo giới. '",
  "sn14.29:1.3": "Người có tà kiến hội tụ, gặp gỡ với người có tà kiến; ",
  "sn14.29:1.4": "người có tà tư duy …cho đến… ",
  "sn14.29:1.5": "người có tà ngữ… ",
  "sn14.29:1.6": "người có tà nghiệp… ",
  "sn14.29:1.7": "người có tà mạng… ",
  "sn14.29:1.8": "người có tà tinh tấn… ",
  "sn14.29:1.9": "người có tà niệm… ",
  "sn14.29:1.10": "người có tà định hội tụ, gặp gỡ với người có tà định; ",
  "sn14.29:1.11": "người có tà trí hội tụ, gặp gỡ với người có tà trí; ",
  "sn14.29:1.12": "người có tà giải thoát hội tụ, gặp gỡ với người có tà giải thoát. ",
  "sn14.29:2.1": "Người có chánh kiến hội tụ, gặp gỡ với người có chánh kiến; ",
  "sn14.29:2.2": "người có chánh tư duy …cho đến… ",
  "sn14.29:2.3": "người có chánh ngữ… ",
  "sn14.29:2.4": "người có chánh nghiệp… ",
  "sn14.29:2.5": "người có chánh mạng… ",
  "sn14.29:2.6": "người có chánh tinh tấn… ",
  "sn14.29:2.7": "người có chánh niệm… ",
  "sn14.29:2.8": "người có chánh định… ",
  "sn14.29:2.9": "người có chánh trí hội tụ, gặp gỡ với người có chánh trí; ",
  "sn14.29:2.10": "người có chánh giải thoát hội tụ, gặp gỡ với người có chánh giải thoát.' ",
  "sn14.29:2.11": "Thứ bảy. ",
  "sn14.29:2.12": "(Ở mọi chỗ cần thêm quá khứ, vị lai, hiện tại.) ",
  "sn14.29:3.0": "Tóm lược bảy kinh ",
  "sn14.29:3.1": "Không định, phá giới, ",
  "sn14.29:3.2": "năm giới; ",
  "sn14.29:3.3": "Bảy nghiệp đạo được nói, ",
  "sn14.29:3.4": "mười nghiệp đạo; ",
  "sn14.29:3.5": "Tám chi được nói là thứ sáu, ",
  "sn14.29:3.6": "mười chi là thứ bảy. ",
  "sn14.29:3.7": "Phẩm Nghiệp Đạo, thứ ba. ",
  "sn14.30:0.1": "Tương Ưng Bộ 14.30 ",
  "sn14.30:0.2": "4. Phẩm Thứ Tư ",
  "sn14.30:0.3": "Kinh Bốn Giới ",
  "sn14.30:1.1": "Một thời, Thế Tôn trú tại Sāvatthī, rừng Jetavana, vườn ông Anāthapiṇḍika… ",
  "sn14.30:1.2": "'Này các Tỳ Kheo, có bốn giới này. '",
  "sn14.30:1.3": "Bốn giới ấy là gì? ",
  "sn14.30:1.4": "Địa giới, thủy giới, hỏa giới, phong giới ",
  "sn14.30:1.5": "này các Tỳ Kheo, đây là bốn giới ấy.' ",
  "sn14.30:1.6": "Thứ nhất. ",
  "sn14.31:0.1": "Tương Ưng Bộ 14.31 ",
  "sn14.31:0.2": "4. Phẩm Thứ Tư ",
  "sn14.31:0.3": "Kinh Trước Khi Giác Ngộ ",
  "sn14.31:1.1": "Tại Sāvatthī. ",
  "sn14.31:1.2": "'Này các Tỳ Kheo, trước khi Ta giác ngộ, khi còn là Bồ-tát chưa chứng Vô thượng Chánh đẳng Chánh giác, Ta đã nghĩ rằng: '",
  "sn14.31:1.3": "'Vị ngọt của địa giới là gì, nguy hiểm là gì, xuất ly là gì? '",
  "sn14.31:1.4": "Vị ngọt của thủy giới là gì, nguy hiểm là gì, xuất ly là gì? ",
  "sn14.31:1.5": "Vị ngọt của hỏa giới là gì, nguy hiểm là gì, xuất ly là gì? ",
  "sn14.31:1.6": "Vị ngọt của phong giới là gì, nguy hiểm là gì, xuất ly là gì?' ",
  "sn14.31:2.1": "Này các Tỳ Kheo, Ta đã nghĩ rằng: ",
  "sn14.31:2.2": "'Lạc và hỷ nào khởi lên duyên vào địa giới, đó là vị ngọt của địa giới; '",
  "sn14.31:2.3": "địa giới vô thường, khổ, thuộc pháp biến dịch, đó là nguy hiểm của địa giới; ",
  "sn14.31:2.4": "sự đoạn trừ, từ bỏ dục tham đối với địa giới, đó là xuất ly của địa giới. ",
  "sn14.31:2.5": "Lạc và hỷ nào khởi lên duyên vào thủy giới …cho đến… ",
  "sn14.31:2.6": "duyên vào hỏa giới …cho đến… ",
  "sn14.31:2.7": "lạc và hỷ nào khởi lên duyên vào phong giới, đó là vị ngọt của phong giới; ",
  "sn14.31:2.8": "phong giới vô thường, khổ, thuộc pháp biến dịch, đó là nguy hiểm của phong giới; ",
  "sn14.31:2.9": "sự đoạn trừ, từ bỏ dục tham đối với phong giới, đó là xuất ly của phong giới.' ",
  "sn14.31:3.1": "Này các Tỳ Kheo, khi Ta chưa như thật tuệ tri vị ngọt là vị ngọt, nguy hiểm là nguy hiểm, xuất ly là xuất ly của bốn giới này, Ta chưa tuyên bố đã chứng Vô thượng Chánh đẳng Chánh giác trong thế giới cùng với chư thiên, ma, Phạm thiên, cùng với dân chúng Sa-môn, Bà-la-môn, chư thiên và loài người. ",
  "sn14.31:4.1": "Này các Tỳ Kheo, khi Ta như thật tuệ tri vị ngọt là vị ngọt, nguy hiểm là nguy hiểm, xuất ly là xuất ly của bốn giới này, Ta tuyên bố đã chứng Vô thượng Chánh đẳng Chánh giác trong thế giới cùng với chư thiên, ma, Phạm thiên, cùng với dân chúng Sa-môn, Bà-la-môn, chư thiên và loài người. ",
  "sn14.31:4.2": "Trí và kiến khởi lên trong Ta: ",
  "sn14.31:4.3": "'Giải thoát của Ta không thể bị lay chuyển, đây là sinh lần cuối, nay không còn tái sinh.'' '",
  "sn14.31:4.4": "Thứ hai. ",
  "sn14.32:0.1": "Tương Ưng Bộ 14.32 ",
  "sn14.32:0.2": "4. Phẩm Thứ Tư ",
  "sn14.32:0.3": "Kinh Ta Đã Đi Tầm Cầu ",
  "sn14.32:1.1": "Tại Sāvatthī. ",
  "sn14.32:1.2": "'Này các Tỳ Kheo, Ta đã đi tầm cầu vị ngọt của địa giới, Ta đã tìm thấy vị ngọt của địa giới, Ta đã thấy rõ bằng trí tuệ vị ngọt của địa giới rộng đến mức nào. '",
  "sn14.32:1.3": "Này các Tỳ Kheo, Ta đã đi tầm cầu nguy hiểm của địa giới, Ta đã tìm thấy nguy hiểm của địa giới, Ta đã thấy rõ bằng trí tuệ nguy hiểm của địa giới rộng đến mức nào. ",
  "sn14.32:1.4": "Này các Tỳ Kheo, Ta đã đi tầm cầu xuất ly của địa giới, Ta đã tìm thấy xuất ly của địa giới, Ta đã thấy rõ bằng trí tuệ xuất ly của địa giới rộng đến mức nào. ",
  "sn14.32:2.1": "Này các Tỳ Kheo, Ta đã đi tầm cầu thủy giới …cho đến… ",
  "sn14.32:2.2": "hỏa giới… ",
  "sn14.32:2.3": "này các Tỳ Kheo, Ta đã đi tầm cầu vị ngọt của phong giới, Ta đã tìm thấy vị ngọt của phong giới, Ta đã thấy rõ bằng trí tuệ vị ngọt của phong giới rộng đến mức nào. ",
  "sn14.32:2.4": "Này các Tỳ Kheo, Ta đã đi tầm cầu nguy hiểm của phong giới, Ta đã tìm thấy nguy hiểm của phong giới, Ta đã thấy rõ bằng trí tuệ nguy hiểm của phong giới rộng đến mức nào. ",
  "sn14.32:2.5": "Này các Tỳ Kheo, Ta đã đi tầm cầu xuất ly của phong giới, Ta đã tìm thấy xuất ly của phong giới, Ta đã thấy rõ bằng trí tuệ xuất ly của phong giới rộng đến mức nào. ",
  "sn14.32:3.1": "Này các Tỳ Kheo, khi Ta chưa như thật tuệ tri vị ngọt là vị ngọt, nguy hiểm là nguy hiểm, xuất ly là xuất ly của bốn giới này, Ta chưa tuyên bố đã chứng Vô thượng Chánh đẳng Chánh giác trong thế giới cùng với chư thiên, ma, Phạm thiên, cùng với dân chúng Sa-môn, Bà-la-môn, chư thiên và loài người. ",
  "sn14.32:4.1": "Này các Tỳ Kheo, khi Ta như thật tuệ tri vị ngọt là vị ngọt, nguy hiểm là nguy hiểm, xuất ly là xuất ly của bốn giới này, Ta tuyên bố đã chứng Vô thượng Chánh đẳng Chánh giác trong thế giới cùng với chư thiên, ma, Phạm thiên, cùng với dân chúng Sa-môn, Bà-la-môn, chư thiên và loài người. ",
  "sn14.32:4.2": "Trí và kiến khởi lên trong Ta: ",
  "sn14.32:4.3": "'Giải thoát của Ta không thể bị lay chuyển, đây là sinh lần cuối, nay không còn tái sinh.'' '",
  "sn14.32:4.4": "Thứ ba. ",
  "sn14.33:0.1": "Tương Ưng Bộ 14.33 ",
  "sn14.33:0.2": "4. Phẩm Thứ Tư ",
  "sn14.33:0.3": "Kinh Nếu Không Có ",
  "sn14.33:1.1": "Tại Sāvatthī. ",
  "sn14.33:1.2": "'Này các Tỳ Kheo, nếu không có vị ngọt của địa giới, thì chúng sinh sẽ không say đắm địa giới. '",
  "sn14.33:1.3": "Nhưng vì, này các Tỳ Kheo, có vị ngọt của địa giới, nên chúng sinh say đắm địa giới. ",
  "sn14.33:1.4": "Này các Tỳ Kheo, nếu không có nguy hiểm của địa giới, thì chúng sinh sẽ không nhàm chán địa giới. ",
  "sn14.33:1.5": "Nhưng vì, này các Tỳ Kheo, có nguy hiểm của địa giới, nên chúng sinh nhàm chán địa giới. ",
  "sn14.33:1.6": "Này các Tỳ Kheo, nếu không có xuất ly của địa giới, thì chúng sinh sẽ không xuất ly địa giới. ",
  "sn14.33:1.7": "Nhưng vì, này các Tỳ Kheo, có xuất ly của địa giới, nên chúng sinh xuất ly địa giới. ",
  "sn14.33:2.1": "Này các Tỳ Kheo, nếu không có vị ngọt của thủy giới …cho đến… ",
  "sn14.33:2.2": "nếu không có vị ngọt của hỏa giới …cho đến… ",
  "sn14.33:2.3": "này các Tỳ Kheo, nếu không có vị ngọt của phong giới, thì chúng sinh sẽ không say đắm phong giới. ",
  "sn14.33:2.4": "Nhưng vì, này các Tỳ Kheo, có vị ngọt của phong giới, nên chúng sinh say đắm phong giới. ",
  "sn14.33:2.5": "Này các Tỳ Kheo, nếu không có nguy hiểm của phong giới, thì chúng sinh sẽ không nhàm chán phong giới. ",
  "sn14.33:2.6": "Nhưng vì, này các Tỳ Kheo, có nguy hiểm của phong giới, nên chúng sinh nhàm chán phong giới. ",
  "sn14.33:2.7": "Này các Tỳ Kheo, nếu không có xuất ly của phong giới, thì chúng sinh sẽ không xuất ly phong giới. ",
  "sn14.33:2.8": "Nhưng vì, này các Tỳ Kheo, có xuất ly của phong giới, nên chúng sinh xuất ly phong giới. ",
  "sn14.33:3.1": "Này các Tỳ Kheo, khi chúng sinh chưa như thật tuệ tri vị ngọt là vị ngọt, nguy hiểm là nguy hiểm, xuất ly là xuất ly của bốn giới này, thì chúng sinh trong thế giới cùng với chư thiên, ma, Phạm thiên, cùng với dân chúng Sa-môn, Bà-la-môn, chư thiên và loài người, chưa thoát ra, chưa tách rời, chưa giải thoát hoàn toàn, chưa an trú với tâm không bị hạn chế. ",
  "sn14.33:4.1": "Này các Tỳ Kheo, khi chúng sinh như thật tuệ tri vị ngọt là vị ngọt, nguy hiểm là nguy hiểm, xuất ly là xuất ly của bốn giới này, thì chúng sinh trong thế giới cùng với chư thiên, ma, Phạm thiên, cùng với dân chúng Sa-môn, Bà-la-môn, chư thiên và loài người, đã thoát ra, tách rời, giải thoát hoàn toàn, an trú với tâm không bị hạn chế.' ",
  "sn14.33:4.2": "Thứ tư. ",
  "sn14.34:0.1": "Tương Ưng Bộ 14.34 ",
  "sn14.34:0.2": "4. Phẩm Thứ Tư ",
  "sn14.34:0.3": "Kinh Hoàn Toàn Khổ ",
  "sn14.34:1.1": "Tại Sāvatthī. ",
  "sn14.34:1.2": "'Này các Tỳ Kheo, nếu địa giới hoàn toàn là khổ, gắn liền với khổ, bị khổ xâm nhập, không có lạc xen vào, thì chúng sinh sẽ không say đắm địa giới. '",
  "sn14.34:1.3": "Nhưng vì, này các Tỳ Kheo, địa giới có lạc, gắn liền với lạc, bị lạc xâm nhập, không có khổ xen vào, nên chúng sinh say đắm địa giới. ",
  "sn14.34:2.1": "Nếu thủy giới …cho đến… ",
  "sn14.34:2.2": "nếu hỏa giới… ",
  "sn14.34:2.3": "này các Tỳ Kheo, nếu phong giới hoàn toàn là khổ, gắn liền với khổ, bị khổ xâm nhập, không có lạc xen vào, thì chúng sinh sẽ không say đắm phong giới. ",
  "sn14.34:2.4": "Nhưng vì, này các Tỳ Kheo, phong giới có lạc, gắn liền với lạc, bị lạc xâm nhập, không có khổ xen vào, nên chúng sinh say đắm phong giới. ",
  "sn14.34:3.1": "Này các Tỳ Kheo, nếu địa giới hoàn toàn là lạc, gắn liền với lạc, bị lạc xâm nhập, không có khổ xen vào, thì chúng sinh sẽ không nhàm chán địa giới. ",
  "sn14.34:3.2": "Nhưng vì, này các Tỳ Kheo, địa giới có khổ, gắn liền với khổ, bị khổ xâm nhập, không có lạc xen vào, nên chúng sinh nhàm chán địa giới. ",
  "sn14.34:4.1": "Nếu thủy giới …cho đến… ",
  "sn14.34:4.2": "nếu hỏa giới… ",
  "sn14.34:4.3": "này các Tỳ Kheo, nếu phong giới hoàn toàn là lạc, gắn liền với lạc, bị lạc xâm nhập, không có khổ xen vào, thì chúng sinh sẽ không nhàm chán phong giới. ",
  "sn14.34:4.4": "Nhưng vì, này các Tỳ Kheo, phong giới có khổ, gắn liền với khổ, bị khổ xâm nhập, không có lạc xen vào, nên chúng sinh nhàm chán phong giới.' ",
  "sn14.34:4.5": "Thứ năm. ",
  "sn14.35:0.1": "Tương Ưng Bộ 14.35 ",
  "sn14.35:0.2": "4. Phẩm Thứ Tư ",
  "sn14.35:0.3": "Kinh Hoan Hỷ ",
  "sn14.35:1.1": "Tại Sāvatthī. ",
  "sn14.35:1.2": "'Này các Tỳ Kheo, ai hoan hỷ địa giới, người ấy hoan hỷ khổ. '",
  "sn14.35:1.3": "Ai hoan hỷ khổ, Ta nói người ấy chưa giải thoát khỏi khổ. ",
  "sn14.35:1.4": "Ai hoan hỷ thủy giới …cho đến… ",
  "sn14.35:1.5": "ai hoan hỷ hỏa giới… ",
  "sn14.35:1.6": "ai hoan hỷ phong giới, người ấy hoan hỷ khổ. ",
  "sn14.35:1.7": "Ai hoan hỷ khổ, Ta nói người ấy chưa giải thoát khỏi khổ. ",
  "sn14.35:2.1": "Này các Tỳ Kheo, ai không hoan hỷ địa giới, người ấy không hoan hỷ khổ. ",
  "sn14.35:2.2": "Ai không hoan hỷ khổ, Ta nói người ấy đã giải thoát khỏi khổ. ",
  "sn14.35:2.3": "Ai không hoan hỷ thủy giới …cho đến… ",
  "sn14.35:2.4": "ai không hoan hỷ hỏa giới… ",
  "sn14.35:2.5": "ai không hoan hỷ phong giới, người ấy không hoan hỷ khổ. ",
  "sn14.35:2.6": "Ai không hoan hỷ khổ, Ta nói người ấy đã giải thoát khỏi khổ.' ",
  "sn14.35:2.7": "Thứ sáu. ",
  "sn14.36:0.1": "Tương Ưng Bộ 14.36 ",
  "sn14.36:0.2": "4. Phẩm Thứ Tư ",
  "sn14.36:0.3": "Kinh Sinh Khởi ",
  "sn14.36:1.1": "Tại Sāvatthī. ",
  "sn14.36:1.2": "'Này các Tỳ Kheo, sự sinh khởi, tồn tại, phát sinh, hiển lộ của địa giới chính là sự sinh khởi của khổ, sự tồn tại của bệnh hoạn, sự hiển lộ của già chết. '",
  "sn14.36:1.3": "Sự sinh khởi của thủy giới …cho đến… ",
  "sn14.36:1.4": "sự sinh khởi của hỏa giới… ",
  "sn14.36:1.5": "này các Tỳ Kheo, sự sinh khởi, tồn tại, phát sinh, hiển lộ của phong giới chính là sự sinh khởi của khổ, sự tồn tại của bệnh hoạn, sự hiển lộ của già chết. ",
  "sn14.36:2.1": "Này các Tỳ Kheo, sự đoạn diệt, lắng dịu, biến mất của địa giới chính là sự đoạn diệt của khổ, sự lắng dịu của bệnh hoạn, sự biến mất của già chết. ",
  "sn14.36:2.2": "Sự đoạn diệt của thủy giới …cho đến… ",
  "sn14.36:2.3": "sự đoạn diệt của hỏa giới… ",
  "sn14.36:2.4": "này các Tỳ Kheo, sự đoạn diệt, lắng dịu, biến mất của phong giới chính là sự đoạn diệt của khổ, sự lắng dịu của bệnh hoạn, sự biến mất của già chết.' ",
  "sn14.36:2.5": "Thứ bảy. ",
  "sn14.37:0.1": "Tương Ưng Bộ 14.37 ",
  "sn14.37:0.2": "4. Phẩm Thứ Tư ",
  "sn14.37:0.3": "Kinh Sa-môn và Bà-la-môn ",
  "sn14.37:1.1": "Tại Sāvatthī. ",
  "sn14.37:1.2": "'Này các Tỳ Kheo, có bốn giới này. '",
  "sn14.37:1.3": "Bốn giới ấy là gì? ",
  "sn14.37:1.4": "Địa giới, thủy giới, hỏa giới, phong giới. ",
  "sn14.37:1.5": "Này các Tỳ Kheo, những Sa-môn hay Bà-la-môn nào không như thật tuệ tri vị ngọt, nguy hiểm, và xuất ly của bốn giới này, ",
  "sn14.37:1.6": "này các Tỳ Kheo, những Sa-môn hay Bà-la-môn ấy không được tôn trọng trong hàng Sa-môn hay được xem là Sa-môn, không được tôn trọng trong hàng Bà-la-môn hay được xem là Bà-la-môn; các vị tôn giả ấy cũng không tự thân chứng ngộ, chứng đắc và an trú trong mục đích Sa-môn hay mục đích Bà-la-môn ngay trong hiện tại. ",
  "sn14.37:2.1": "Này các Tỳ Kheo, những Sa-môn hay Bà-la-môn nào như thật tuệ tri vị ngọt, nguy hiểm, và xuất ly của bốn giới này, ",
  "sn14.37:2.2": "này các Tỳ Kheo, những Sa-môn hay Bà-la-môn ấy được tôn trọng trong hàng Sa-môn và được xem là Sa-môn, được tôn trọng trong hàng Bà-la-môn và được xem là Bà-la-môn; các vị tôn giả ấy tự thân chứng ngộ, chứng đắc và an trú trong mục đích Sa-môn và mục đích Bà-la-môn ngay trong hiện tại.' ",
  "sn14.37:2.3": "Thứ tám. ",
  "sn14.38:0.1": "Tương Ưng Bộ 14.38 ",
  "sn14.38:0.2": "4. Phẩm Thứ Tư ",
  "sn14.38:0.3": "Kinh Sa-môn và Bà-la-môn (2) ",
  "sn14.38:1.1": "Tại Sāvatthī. ",
  "sn14.38:1.2": "'Này các Tỳ Kheo, có bốn giới này. '",
  "sn14.38:1.3": "Bốn giới ấy là gì? ",
  "sn14.38:1.4": "Địa giới, thủy giới, hỏa giới, phong giới. ",
  "sn14.38:1.5": "Này các Tỳ Kheo, những Sa-môn hay Bà-la-môn nào không như thật tuệ tri sự tập khởi, sự đoạn diệt, vị ngọt, nguy hiểm, và xuất ly của bốn giới này …cho đến… ",
  "sn14.38:1.6": "(cần nói đầy đủ) ",
  "sn14.38:1.7": "như thật tuệ tri …cho đến… ",
  "sn14.38:1.8": "tự thân chứng ngộ, chứng đắc và an trú.' ",
  "sn14.38:1.9": "Thứ chín. ",
  "sn14.39:0.1": "Tương Ưng Bộ 14.39 ",
  "sn14.39:0.2": "4. Phẩm Thứ Tư ",
  "sn14.39:0.3": "Kinh Sa-môn và Bà-la-môn (3) ",
  "sn14.39:1.1": "Tại Sāvatthī. ",
  "sn14.39:1.2": "'Này các Tỳ Kheo, những Sa-môn hay Bà-la-môn nào không tuệ tri địa giới, không tuệ tri sự tập khởi của địa giới, không tuệ tri sự đoạn diệt của địa giới, không tuệ tri con đường dẫn đến sự đoạn diệt của địa giới …cho đến… '",
  "sn14.39:1.3": "không tuệ tri thủy giới… ",
  "sn14.39:1.4": "không tuệ tri hỏa giới… ",
  "sn14.39:1.5": "không tuệ tri phong giới, không tuệ tri sự tập khởi của phong giới, không tuệ tri sự đoạn diệt của phong giới, không tuệ tri con đường dẫn đến sự đoạn diệt của phong giới, thì này các Tỳ Kheo, những Sa-môn hay Bà-la-môn ấy không được tôn trọng trong hàng Sa-môn hay được xem là Sa-môn, không được tôn trọng trong hàng Bà-la-môn hay được xem là Bà-la-môn; ",
  "sn14.39:1.6": "các vị tôn giả ấy cũng không tự thân chứng ngộ, chứng đắc và an trú trong mục đích Sa-môn hay mục đích Bà-la-môn ngay trong hiện tại. ",
  "sn14.39:2.1": "Này các Tỳ Kheo, những Sa-môn hay Bà-la-môn nào tuệ tri địa giới, tuệ tri sự tập khởi của địa giới, tuệ tri sự đoạn diệt của địa giới, tuệ tri con đường dẫn đến sự đoạn diệt của địa giới… ",
  "sn14.39:2.2": "này các Tỳ Kheo, những Sa-môn hay Bà-la-môn nào …cho đến… tuệ tri thủy giới… ",
  "sn14.39:2.3": "tuệ tri hỏa giới… ",
  "sn14.39:2.4": "tuệ tri phong giới, tuệ tri sự tập khởi của phong giới, tuệ tri sự đoạn diệt của phong giới, tuệ tri con đường dẫn đến sự đoạn diệt của phong giới, thì này các Tỳ Kheo, những Sa-môn hay Bà-la-môn ấy được tôn trọng trong hàng Sa-môn và được xem là Sa-môn, được tôn trọng trong hàng Bà-la-môn và được xem là Bà-la-môn; ",
  "sn14.39:2.5": "các vị tôn giả ấy tự thân chứng ngộ, chứng đắc và an trú trong mục đích Sa-môn và mục đích Bà-la-môn ngay trong hiện tại.' ",
  "sn14.39:2.6": "Thứ mười. ",
  "sn14.39:2.7": "Phẩm thứ tư. ",
  "sn14.39:3.0": "Tóm lược phẩm ",
  "sn14.39:3.1": "Bốn giới, trước khi giác ngộ, ta đã đi, ",
  "sn14.39:3.2": "nếu không có, và khổ; ",
  "sn14.39:3.3": "Hoan hỷ và sinh khởi, ",
  "sn14.39:3.4": "ba kinh Sa-môn Bà-la-môn. ",
  "sn14.39:3.5": "Tương Ưng Giới hoàn tất. "
}
window.BILARA["sn14_v1"]["vi"]["sn14_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
