window.BILARA = window.BILARA || {};
window.BILARA["sn19_v1"] = window.BILARA["sn19_v1"] || {};
window.BILARA["sn19_v1"]["vi"] = {
  "sn19.1:0.1": "Tương Ưng Bộ 19.1 ",
  "sn19.1:0.2": "1. Phẩm Thứ Nhất ",
  "sn19.1:0.3": "Kinh Bộ Xương ",
  "sn19.1:1.1": "Tôi nghe như vầy",
  "sn19.1:1.2": "Một thời Đức Thế Tôn trú tại Vương Xá, trong rừng Trúc, vườn nuôi sóc. ",
  "sn19.1:1.3": "Lúc bấy giờ Tôn giả Lakkhaṇa và Tôn giả Mahā Moggallāna đang trú tại núi Linh Thứu. ",
  "sn19.1:1.4": "Rồi Tôn giả Mahā Moggallāna vào buổi sáng, đắp y, mang bát, đến chỗ Tôn giả Lakkhaṇa; đến rồi, nói với Tôn giả Lakkhaṇa rằng: ",
  "sn19.1:1.5": "'Thưa Hiền giả Lakkhaṇa, hãy cùng vào Vương Xá khất thực.' ",
  "sn19.1:1.6": "'Thưa Hiền giả, vâng.' Tôn giả Lakkhaṇa đáp lời Tôn giả Mahā Moggallāna. ",
  "sn19.1:1.7": "Rồi Tôn giả Mahā Moggallāna, trong khi xuống núi Linh Thứu, tại một chỗ nọ, nở một nụ cười. ",
  "sn19.1:1.8": "Rồi Tôn giả Lakkhaṇa nói với Tôn giả Mahā Moggallāna: ",
  "sn19.1:1.9": "'Do nhân gì, do duyên gì, thưa Hiền giả Moggallāna, mà Ngài nở nụ cười vậy?' ",
  "sn19.1:1.10": "'Thưa Hiền giả Lakkhaṇa, đây chưa phải lúc thích hợp để hỏi câu này. '",
  "sn19.1:1.11": "Hãy hỏi tôi câu đó khi có Đức Thế Tôn.' ",
  "sn19.1:2.1": "Rồi Tôn giả Lakkhaṇa và Tôn giả Mahā Moggallāna, sau khi đi khất thực ở Vương Xá, trở về sau bữa ăn, đến chỗ Đức Thế Tôn; đến rồi, đảnh lễ Ngài và ngồi xuống một bên. Ngồi một bên, Tôn giả Lakkhaṇa nói với Tôn giả Mahā Moggallāna rằng: ",
  "sn19.1:2.2": "'Thưa Hiền giả Mahā Moggallāna, lúc Ngài xuống núi Linh Thứu, tại một chỗ nọ, Ngài đã nở một nụ cười. '",
  "sn19.1:2.3": "Do nhân gì, do duyên gì mà Ngài nở nụ cười vậy?' ",
  "sn19.1:3.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một bộ xương đang bay trên không trung. '",
  "sn19.1:3.2": "Các con kên kên, quạ và diều hâu bay theo, mổ vào giữa các xương sườn, xé rách và giật ra. ",
  "sn19.1:3.3": "Bộ xương đó kêu la thảm thiết. ",
  "sn19.1:3.4": "Thưa Hiền giả, tôi nghĩ: ",
  "sn19.1:3.5": "'Thật kỳ lạ thay! Thật hi hữu thay! '",
  "sn19.1:3.6": "Lại có loài chúng sinh như vậy. ",
  "sn19.1:3.7": "Lại có loại dạ xoa như vậy. ",
  "sn19.1:3.8": "Lại có loại thân hình như vậy.'' ",
  "sn19.1:4.1": "Rồi Đức Thế Tôn gọi các Tỳ Kheo: ",
  "sn19.1:4.2": "'Này các Tỳ Kheo, các đệ tử đang sống với con mắt trí tuệ; '",
  "sn19.1:4.3": "này các Tỳ Kheo, các đệ tử đang sống với trí tuệ, khi một đệ tử có thể biết, thấy hay chứng kiến điều như vậy. ",
  "sn19.1:4.4": "Này các Tỳ Kheo, trước đây Ta đã thấy chúng sinh đó, nhưng Ta đã không nói. ",
  "sn19.1:4.5": "Nếu Ta nói, người khác sẽ không tin Ta. ",
  "sn19.1:4.6": "Những ai không tin Ta, thì điều đó sẽ là bất lợi và đau khổ lâu dài cho họ. ",
  "sn19.1:4.7": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là người mổ bò. ",
  "sn19.1:4.8": "Do quả báo của nghiệp đó, sau khi đã chịu khổ trong địa ngục nhiều năm, nhiều trăm năm, nhiều ngàn năm, nhiều trăm ngàn năm, với nghiệp còn sót lại, nay chúng sinh đó đang chịu đựng thân hình như vậy.' ",
  "sn19.1:4.9": "(Đây là mẫu chung cho tất cả các kinh.) ",
  "sn19.1:4.10": "Thứ nhất. ",
  "sn19.2:0.1": "Tương Ưng Bộ 19.2 ",
  "sn19.2:0.2": "1. Phẩm Thứ Nhất ",
  "sn19.2:0.3": "Kinh Miếng Thịt ",
  "sn19.2:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một miếng thịt đang bay trên không trung. '",
  "sn19.2:1.2": "Các con kên kên, quạ và diều hâu bay theo, xé rách và giật ra. ",
  "sn19.2:1.3": "Miếng thịt đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.2:1.4": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là người mổ bò …(tiếp theo)…. ",
  "sn19.2:1.5": "Thứ hai. ",
  "sn19.3:0.1": "Tương Ưng Bộ 19.3 ",
  "sn19.3:0.2": "1. Phẩm Thứ Nhất ",
  "sn19.3:0.3": "Kinh Cục Thịt ",
  "sn19.3:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một cục thịt đang bay trên không trung. '",
  "sn19.3:1.2": "Các con kên kên, quạ và diều hâu bay theo, xé rách và giật ra. ",
  "sn19.3:1.3": "Cục thịt đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.3:1.4": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là người săn bẫy chim …(tiếp theo)…. ",
  "sn19.3:1.5": "Thứ ba. ",
  "sn19.4:0.1": "Tương Ưng Bộ 19.4 ",
  "sn19.4:0.2": "1. Phẩm Thứ Nhất ",
  "sn19.4:0.3": "Kinh Người Không Da ",
  "sn19.4:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một người đàn ông không có da đang bay trên không trung. '",
  "sn19.4:1.2": "Các con kên kên, quạ và diều hâu bay theo, xé rách và giật ra. ",
  "sn19.4:1.3": "Người đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.4:1.4": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là người mổ cừu …(tiếp theo)…. ",
  "sn19.4:1.5": "Thứ tư. ",
  "sn19.5:0.1": "Tương Ưng Bộ 19.5 ",
  "sn19.5:0.2": "1. Phẩm Thứ Nhất ",
  "sn19.5:0.3": "Kinh Người Lông Kiếm ",
  "sn19.5:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một người có lông là những lưỡi kiếm đang bay trên không trung. '",
  "sn19.5:1.2": "Những lưỡi kiếm đó bay lên rồi rớt xuống ngay thân của người đó. ",
  "sn19.5:1.3": "Người đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.5:1.4": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là người mổ heo …(tiếp theo)…. ",
  "sn19.5:1.5": "Thứ năm. ",
  "sn19.6:0.1": "Tương Ưng Bộ 19.6 ",
  "sn19.6:0.2": "1. Phẩm Thứ Nhất ",
  "sn19.6:0.3": "Kinh Người Lông Giáo ",
  "sn19.6:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một người có lông là những ngọn giáo đang bay trên không trung. '",
  "sn19.6:1.2": "Những ngọn giáo đó bay lên rồi rớt xuống ngay thân của người đó. ",
  "sn19.6:1.3": "Người đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.6:1.4": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là người săn nai …(tiếp theo)…. ",
  "sn19.6:1.5": "Thứ sáu. ",
  "sn19.7:0.1": "Tương Ưng Bộ 19.7 ",
  "sn19.7:0.2": "1. Phẩm Thứ Nhất ",
  "sn19.7:0.3": "Kinh Người Lông Tên ",
  "sn19.7:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một người có lông là những mũi tên đang bay trên không trung. '",
  "sn19.7:1.2": "Những mũi tên đó bay lên rồi rớt xuống ngay thân của người đó. ",
  "sn19.7:1.3": "Người đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.7:1.4": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là người hành hình …(tiếp theo)…. ",
  "sn19.7:1.5": "Thứ bảy. ",
  "sn19.8:0.1": "Tương Ưng Bộ 19.8 ",
  "sn19.8:0.2": "1. Phẩm Thứ Nhất ",
  "sn19.8:0.3": "Kinh Người Lông Kim ",
  "sn19.8:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một người có lông là những chiếc kim đang bay trên không trung. '",
  "sn19.8:1.2": "Những chiếc kim đó bay lên rồi rớt xuống ngay thân của người đó. ",
  "sn19.8:1.3": "Người đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.8:1.4": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là người đánh xe ngựa …(tiếp theo)…. ",
  "sn19.8:1.5": "Thứ tám. ",
  "sn19.9:0.1": "Tương Ưng Bộ 19.9 ",
  "sn19.9:0.2": "1. Phẩm Thứ Nhất ",
  "sn19.9:0.3": "Kinh Người Lông Kim Thứ Hai ",
  "sn19.9:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một người có lông là những chiếc kim đang bay trên không trung. '",
  "sn19.9:1.2": "Những chiếc kim đó đâm vào đầu rồi chui ra từ miệng; ",
  "sn19.9:1.3": "đâm vào miệng rồi chui ra từ ngực; ",
  "sn19.9:1.4": "đâm vào ngực rồi chui ra từ bụng; ",
  "sn19.9:1.5": "đâm vào bụng rồi chui ra từ đùi; ",
  "sn19.9:1.6": "đâm vào đùi rồi chui ra từ bắp chân; ",
  "sn19.9:1.7": "đâm vào bắp chân rồi chui ra từ bàn chân; ",
  "sn19.9:1.8": "người đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.9:1.9": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là kẻ vu khống …(tiếp theo)…. ",
  "sn19.9:1.10": "Thứ chín. ",
  "sn19.10:0.1": "Tương Ưng Bộ 19.10 ",
  "sn19.10:0.2": "1. Phẩm Thứ Nhất ",
  "sn19.10:0.3": "Kinh Người Tinh Hoàn To Lớn ",
  "sn19.10:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một người có tinh hoàn to lớn đang bay trên không trung. '",
  "sn19.10:1.2": "Khi đi, người đó phải vác tinh hoàn lên vai mà đi. ",
  "sn19.10:1.3": "Khi ngồi, người đó ngồi lên chính tinh hoàn của mình. ",
  "sn19.10:1.4": "Các con kên kên, quạ và diều hâu bay theo, xé rách và giật ra. ",
  "sn19.10:1.5": "Người đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.10:1.6": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là trưởng thôn gian tham …(tiếp theo)…. ",
  "sn19.10:1.7": "Thứ mười. ",
  "sn19.10:1.8": "Phẩm thứ nhất. ",
  "sn19.10:2.0": "Tóm tắt phẩm ",
  "sn19.10:2.1": "Bộ xương và miếng thịtcả hai là người giết bò, ",
  "sn19.10:2.2": "Cục thịt là người săn bẫy chim, người không da là người mổ cừu; ",
  "sn19.10:2.3": "Người lông kiếm là người mổ heo, người lông giáo là người săn nai, ",
  "sn19.10:2.4": "Người lông tên là người hành hình, người lông kim là người đánh xe; ",
  "sn19.10:2.5": "Người mà kim xuyên qua khắp mình là kẻ vu khống, ",
  "sn19.10:2.6": "Người mang tinh hoàn to là trưởng thôn gian tham. ",
  "sn19.11:0.1": "Tương Ưng Bộ 19.11 ",
  "sn19.11:0.2": "2. Phẩm Thứ Hai ",
  "sn19.11:0.3": "Kinh Người Đầu Ngập Phân ",
  "sn19.11:1.1": "Tôi nghe như vầy",
  "sn19.11:1.2": "Một thời tại Vương Xá, rừng Trúc. ",
  "sn19.11:1.3": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một người đang ngập đầu trong hố phân …(tiếp theo)… '",
  "sn19.11:1.4": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là kẻ ngoại tình …(tiếp theo)…. ",
  "sn19.11:1.5": "Thứ nhất. ",
  "sn19.12:0.1": "Tương Ưng Bộ 19.12 ",
  "sn19.12:0.2": "2. Phẩm Thứ Hai ",
  "sn19.12:0.3": "Kinh Người Ăn Phân ",
  "sn19.12:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một người đang ngập trong hố phân, dùng cả hai tay bốc phân ăn …(tiếp theo)… '",
  "sn19.12:1.2": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là một vị Bà La Môn gian ác. ",
  "sn19.12:1.3": "Vị đó đã mời chư Tỳ Kheo trong Tăng đoàn của Đức Phật Kassapa Chánh Đẳng Chánh Giác dùng bữa, rồi cho người đổ đầy phân vào thùng và nói",
  "sn19.12:1.4": "'Này các Ngài, hãy ăn và mang về tùy thích.' …(tiếp theo)…. ",
  "sn19.12:1.5": "Thứ hai. ",
  "sn19.13:0.1": "Tương Ưng Bộ 19.13 ",
  "sn19.13:0.2": "2. Phẩm Thứ Hai ",
  "sn19.13:0.3": "Kinh Người Phụ Nữ Không Da ",
  "sn19.13:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một người phụ nữ không có da đang bay trên không trung. '",
  "sn19.13:1.2": "Các con kên kên, quạ và diều hâu bay theo, xé rách và giật ra. ",
  "sn19.13:1.3": "Người phụ nữ đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.13:1.4": "Này các Tỳ Kheo, người phụ nữ đó ngay tại Vương Xá này đã từng là kẻ ngoại tình …(tiếp theo)…. ",
  "sn19.13:1.5": "Thứ ba. ",
  "sn19.14:0.1": "Tương Ưng Bộ 19.14 ",
  "sn19.14:0.2": "2. Phẩm Thứ Hai ",
  "sn19.14:0.3": "Kinh Người Phụ Nữ Hôi Thối ",
  "sn19.14:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một người phụ nữ hôi thối, xấu xí đang bay trên không trung. '",
  "sn19.14:1.2": "Các con kên kên, quạ và diều hâu bay theo, xé rách và giật ra. ",
  "sn19.14:1.3": "Người phụ nữ đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.14:1.4": "Này các Tỳ Kheo, người phụ nữ đó ngay tại Vương Xá này đã từng là thầy bói lừa đảo …(tiếp theo)…. ",
  "sn19.14:1.5": "Thứ tư. ",
  "sn19.15:0.1": "Tương Ưng Bộ 19.15 ",
  "sn19.15:0.2": "2. Phẩm Thứ Hai ",
  "sn19.15:0.3": "Kinh Người Phụ Nữ Bị Đổ Than Lửa ",
  "sn19.15:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một người phụ nữ bị rải than lửa đỏ rực khắp người đang bay trên không trung. '",
  "sn19.15:1.2": "Người phụ nữ đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.15:1.3": "Này các Tỳ Kheo, người phụ nữ đó đã từng là hoàng hậu chánh cung của vua Kaliṅga. ",
  "sn19.15:1.4": "Do lòng ghen tuông, bà đã dùng nồi than đổ lên người vợ lẽ …(tiếp theo)…. ",
  "sn19.15:1.5": "Thứ năm. ",
  "sn19.16:0.1": "Tương Ưng Bộ 19.16 ",
  "sn19.16:0.2": "2. Phẩm Thứ Hai ",
  "sn19.16:0.3": "Kinh Thân Không Đầu ",
  "sn19.16:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một thân người không có đầu đang bay trên không trung. '",
  "sn19.16:1.2": "Trên ngực có cả hai mắt và miệng. ",
  "sn19.16:1.3": "Các con kên kên, quạ và diều hâu bay theo, xé rách và giật ra. ",
  "sn19.16:1.4": "Thân người đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.16:1.5": "Này các Tỳ Kheo, chúng sinh đó ngay tại Vương Xá này đã từng là tên trộm sát nhân tên là Hāriko …(tiếp theo)…. ",
  "sn19.16:1.6": "Thứ sáu. ",
  "sn19.17:0.1": "Tương Ưng Bộ 19.17 ",
  "sn19.17:0.2": "2. Phẩm Thứ Hai ",
  "sn19.17:0.3": "Kinh Tỳ Kheo Xấu Ác ",
  "sn19.17:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một Tỳ Kheo đang bay trên không trung. '",
  "sn19.17:1.2": "Y kép của vị đó đang cháy rực bùng lửa sáng chói; bình bát cũng đang cháy rực bùng lửa sáng chói; thắt lưng cũng đang cháy rực bùng lửa sáng chói; thân cũng đang cháy rực bùng lửa sáng chói. ",
  "sn19.17:1.3": "Vị đó kêu la thảm thiết …(tiếp theo)… ",
  "sn19.17:1.4": "Này các Tỳ Kheo, Tỳ Kheo đó trong giáo pháp của Đức Phật Kassapa Chánh Đẳng Chánh Giác đã từng là Tỳ Kheo xấu ác …(tiếp theo)…. ",
  "sn19.17:1.5": "Thứ bảy. ",
  "sn19.18:0.1": "Tương Ưng Bộ 19.18 ",
  "sn19.18:0.2": "2. Phẩm Thứ Hai ",
  "sn19.18:0.3": "Kinh Tỳ Kheo Ni Xấu Ác ",
  "sn19.18:1.1": "'Tôi thấy một Tỳ Kheo Ni đang bay trên không trung. '",
  "sn19.18:1.2": "Y kép của vị đó đang cháy rực …(tiếp theo)… ",
  "sn19.18:1.3": "là Tỳ Kheo Ni xấu ác …(tiếp theo)…. ",
  "sn19.18:1.4": "Thứ tám. ",
  "sn19.19:0.1": "Tương Ưng Bộ 19.19 ",
  "sn19.19:0.2": "2. Phẩm Thứ Hai ",
  "sn19.19:0.3": "Kinh Thức Xoa Ma Na Xấu Ác ",
  "sn19.19:1.1": "'Tôi thấy một Thức Xoa Ma Na đang bay trên không trung. '",
  "sn19.19:1.2": "Y kép của vị đó đang cháy rực …(tiếp theo)… ",
  "sn19.19:1.3": "là Thức Xoa Ma Na xấu ác …(tiếp theo)…. ",
  "sn19.19:1.4": "Thứ chín. ",
  "sn19.20:0.1": "Tương Ưng Bộ 19.20 ",
  "sn19.20:0.2": "2. Phẩm Thứ Hai ",
  "sn19.20:0.3": "Kinh Sa Di Xấu Ác ",
  "sn19.20:1.1": "'Tôi thấy một Sa Di đang bay trên không trung. '",
  "sn19.20:1.2": "Y kép của vị đó đang cháy rực …(tiếp theo)… ",
  "sn19.20:1.3": "là Sa Di xấu ác …(tiếp theo)…. ",
  "sn19.20:1.4": "Thứ mười. ",
  "sn19.21:0.1": "Tương Ưng Bộ 19.21 ",
  "sn19.21:0.2": "2. Phẩm Thứ Hai ",
  "sn19.21:0.3": "Kinh Sa Di Ni Xấu Ác ",
  "sn19.21:1.1": "'Thưa Hiền giả, khi tôi xuống núi Linh Thứu, tôi thấy một Sa Di Ni đang bay trên không trung. '",
  "sn19.21:1.2": "Y kép của vị đó đang cháy rực bùng lửa sáng chói; bình bát cũng đang cháy rực bùng lửa sáng chói; thắt lưng cũng đang cháy rực bùng lửa sáng chói; thân cũng đang cháy rực bùng lửa sáng chói. ",
  "sn19.21:1.3": "Vị đó kêu la thảm thiết. ",
  "sn19.21:1.4": "Thưa Hiền giả, tôi nghĩ: ",
  "sn19.21:1.5": "'Thật kỳ lạ thay! Thật hi hữu thay! '",
  "sn19.21:1.6": "Lại có loài chúng sinh như vậy. ",
  "sn19.21:1.7": "Lại có loại dạ xoa như vậy. ",
  "sn19.21:1.8": "Lại có loại thân hình như vậy.'' ",
  "sn19.21:2.1": "Rồi Đức Thế Tôn gọi các Tỳ Kheo: ",
  "sn19.21:2.2": "'Này các Tỳ Kheo, các đệ tử đang sống với con mắt trí tuệ; '",
  "sn19.21:2.3": "này các Tỳ Kheo, các đệ tử đang sống với trí tuệ, khi một đệ tử có thể biết, thấy hay chứng kiến điều như vậy. ",
  "sn19.21:2.4": "Này các Tỳ Kheo, trước đây Ta đã thấy Sa Di Ni đó. ",
  "sn19.21:2.5": "Nhưng Ta đã không nói. ",
  "sn19.21:2.6": "Nếu Ta nói, người khác sẽ không tin Ta. ",
  "sn19.21:2.7": "Những ai không tin Ta, thì điều đó sẽ là bất lợi và đau khổ lâu dài cho họ. ",
  "sn19.21:2.8": "Này các Tỳ Kheo, Sa Di Ni đó trong giáo pháp của Đức Phật Kassapa Chánh Đẳng Chánh Giác đã từng là Sa Di Ni xấu ác. ",
  "sn19.21:2.9": "Do quả báo của nghiệp đó, sau khi đã chịu khổ trong địa ngục nhiều năm, nhiều trăm năm, nhiều ngàn năm, nhiều trăm ngàn năm, với nghiệp còn sót lại, nay Sa Di Ni đó đang chịu đựng thân hình như vậy.' ",
  "sn19.21:2.10": "Thứ mười một. ",
  "sn19.21:2.11": "Phẩm thứ hai. ",
  "sn19.21:3.0": "Tóm tắt phẩm ",
  "sn19.21:3.1": "Người ngập trong hố phân là kẻ ngoại tình, ",
  "sn19.21:3.2": "Người ăn phân là Bà La Môn gian ác; ",
  "sn19.21:3.3": "Người phụ nữ không da là kẻ ngoại tình, ",
  "sn19.21:3.4": "Người phụ nữ xấu xí hôi thối là thầy bói lừa đảo; ",
  "sn19.21:3.5": "Người bị rải than lửa là kẻ đổ than lên vợ lẽ vì ghen tuông, ",
  "sn19.21:3.6": "Người không đầu là tên cướp sát nhân. ",
  "sn19.21:4.1": "Tỳ Kheo, Tỳ Kheo Ni, Thức Xoa Ma Na, ",
  "sn19.21:4.2": "Sa Di và Sa Di Ni; ",
  "sn19.21:4.3": "Xuất gia trong giáo pháp của Đức Phật Kassapa, ",
  "sn19.21:4.4": "Đã làm những hành động xấu ác như vậy. ",
  "sn19.21:4.5": "Kết thúc Tương Ưng Lakkhaṇa. "
}
window.BILARA["sn19_v1"]["vi"]["sn19_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
