window.BILARA = window.BILARA || {};
window.BILARA["sn21_v1"] = window.BILARA["sn21_v1"] || {};
window.BILARA["sn21_v1"]["vi"] = {
  "sn21.1:0.1": "Tương Ưng Bộ 21.1 ",
  "sn21.1:0.2": "1. Phẩm Tỳ Kheo ",
  "sn21.1:0.3": "Kinh Kolita ",
  "sn21.1:1.1": "Tôi nghe như vầy",
  "sn21.1:1.2": "Một thời, Thế Tôn trú tại Sāvatthi, trong Jetavana, tu viện của Anāthapiṇḍika. ",
  "sn21.1:1.3": "Lúc ấy, Tôn giả Mahāmoggallāna gọi các Tỳ Kheo: ",
  "sn21.1:1.4": "'Này các hiền giả Tỳ Kheo.' ",
  "sn21.1:1.5": "'Thưa hiền giả,' các Tỳ Kheo ấy đáp lại Tôn giả Mahāmoggallāna. ",
  "sn21.1:2.1": "Tôn giả Mahāmoggallāna nói: ",
  "sn21.1:2.2": "'Này các hiền giả, khi tôi độc cư thiền định, tâm tư này khởi lên trong lòng tôi: '",
  "sn21.1:2.3": "'Sự im lặng của bậc Thánh, sự im lặng của bậc Thánh'người ta nói vậy. ",
  "sn21.1:2.4": "Sự im lặng của bậc Thánh là gì? ",
  "sn21.1:2.5": "Rồi tôi suy nghĩ: ",
  "sn21.1:2.6": "'Này các hiền giả, ở đây, Tỳ Kheo do đoạn diệt tầm và tứ, chứng và trú Thiền thứ hai, một trạng thái nội tâm thanh tịnh, tâm an trú vào một điểm, không tầm, không tứ, hỷ lạc do định sinh. '",
  "sn21.1:2.7": "Đây được gọi là sự im lặng của bậc Thánh.' ",
  "sn21.1:2.8": "Rồi tôi, này các hiền giả, do đoạn diệt tầm và tứ, chứng và trú Thiền thứ hai, một trạng thái nội tâm thanh tịnh, tâm an trú vào một điểm, không tầm, không tứ, hỷ lạc do định sinh. ",
  "sn21.1:2.9": "Nhưng trong khi tôi trú với trú xứ này, các tư duy và tác ý kèm theo tầm vẫn khởi lên với tôi. ",
  "sn21.1:3.1": "Rồi, này các hiền giả, Thế Tôn dùng thần thông đến gặp tôi và bảo: ",
  "sn21.1:3.2": "'Moggallāna, Moggallāna, này bà-la-môn, chớ buông lung sự im lặng của bậc Thánh. Hãy an trú tâm vào sự im lặng của bậc Thánh, hãy thu nhiếp tâm vào sự im lặng của bậc Thánh, hãy nhất tâm trong sự im lặng của bậc Thánh.' ",
  "sn21.1:3.3": "Rồi tôi, này các hiền giả, sau đó do đoạn diệt tầm và tứ, chứng và trú Thiền thứ hai, một trạng thái nội tâm thanh tịnh, tâm an trú vào một điểm, không tầm, không tứ, hỷ lạc do định sinh. ",
  "sn21.1:3.4": "Nếu ai nói đúng về điều này: ",
  "sn21.1:3.5": "'Đệ tử được Bậc Đạo Sư dẫn dắt đã đạt đại thắng trí', thì người ấy nói đúng về tôi: ",
  "sn21.1:3.6": "'Đệ tử được Bậc Đạo Sư dẫn dắt đã đạt đại thắng trí.'' '",
  "sn21.1:3.7": "Thứ nhất. ",
  "sn21.2:0.1": "Tương Ưng Bộ 21.2 ",
  "sn21.2:0.2": "1. Phẩm Tỳ Kheo ",
  "sn21.2:0.3": "Kinh Upatissa ",
  "sn21.2:1.1": "Duyên khởi tại Sāvatthi. ",
  "sn21.2:1.2": "Lúc ấy, Tôn giả Sāriputta gọi các Tỳ Kheo: ",
  "sn21.2:1.3": "'Này các hiền giả Tỳ Kheo.' ",
  "sn21.2:1.4": "'Thưa hiền giả,' các Tỳ Kheo ấy đáp lại Tôn giả Sāriputta. ",
  "sn21.2:1.5": "Tôn giả Sāriputta nói: ",
  "sn21.2:2.1": "'Này các hiền giả, khi tôi độc cư thiền định, tâm tư này khởi lên trong lòng tôi: '",
  "sn21.2:2.2": "'Có chăng điều gì ở trên đời này mà sự biến đổi và khác đi của nó sẽ làm khởi lên nơi ta sầu, bi, khổ, ưu, não?' ",
  "sn21.2:2.3": "Rồi tôi suy nghĩ: ",
  "sn21.2:2.4": "'Không có điều gì ở trên đời này mà sự biến đổi và khác đi của nó sẽ làm khởi lên nơi ta sầu, bi, khổ, ưu, não.'' '",
  "sn21.2:3.1": "Khi nghe vậy, Tôn giả Ānanda hỏi Tôn giả Sāriputta: ",
  "sn21.2:3.2": "'Ngay cả sự biến đổi và khác đi của Đức Thế Tôn cũng không làm khởi lên nơi hiền giả Sāriputta sầu, bi, khổ, ưu, não sao?' ",
  "sn21.2:3.3": "'Ngay cả sự biến đổi và khác đi của Thế Tôn cũng không làm khởi lên nơi tôi sầu, bi, khổ, ưu, não, nhưng tôi nghĩ rằng: '",
  "sn21.2:3.4": "'Thật sự Thế Tôn là bậc đại oai lực, đại thần thông, nay đã ra đi. '",
  "sn21.2:3.5": "Nếu Thế Tôn còn trú lâu dài, đó sẽ là lợi ích, an lạc cho nhiều người, vì lòng thương xót thế gian, vì lợi ích, an lạc và hạnh phúc của chư thiên và loài người.' ",
  "sn21.2:3.6": "Vì thật sự, Tôn giả Sāriputta đã từ lâu khéo nhổ tận gốc ngã mạn, ngã sở và tùy miên kiêu mạn. ",
  "sn21.2:3.7": "Do vậy, sự biến đổi và khác đi của Thế Tôn không làm khởi lên nơi Tôn giả Sāriputta sầu, bi, khổ, ưu, não.' ",
  "sn21.2:3.8": "Thứ hai. ",
  "sn21.3:0.1": "Tương Ưng Bộ 21.3 ",
  "sn21.3:0.2": "1. Phẩm Tỳ Kheo ",
  "sn21.3:0.3": "Kinh Ghaṭa ",
  "sn21.3:1.1": "Tôi nghe như vầy",
  "sn21.3:1.2": "Một thời, Thế Tôn trú tại Sāvatthi, trong Jetavana, tu viện của Anāthapiṇḍika. ",
  "sn21.3:1.3": "Lúc bấy giờ, Tôn giả Sāriputta và Tôn giả Mahāmoggallāna đang trú tại Rājagaha, trong Veḷuvana, vườn sóc, cùng trú một am thất. ",
  "sn21.3:1.4": "Rồi Tôn giả Sāriputta vào buổi chiều, xuất thiền, đến gặp Tôn giả Mahāmoggallāna; đến rồi cùng với Tôn giả Mahāmoggallāna chào hỏi thân ái. ",
  "sn21.3:1.5": "Sau khi nói những lời thân ái đáng ghi nhớ, liền ngồi xuống một bên. Ngồi một bên, Tôn giả Sāriputta nói với Tôn giả Mahāmoggallāna: ",
  "sn21.3:2.1": "'Này hiền giả Moggallāna, các căn của hiền giả thật trong sáng; '",
  "sn21.3:2.2": "nhan sắc thật thanh tịnh, trong lành. Hôm nay Tôn giả Mahāmoggallāna đã trú với trú xứ nào vậy?' ",
  "sn21.3:2.3": "'Này hiền giả, hôm nay tôi đã trú với trú xứ thô thiển. '",
  "sn21.3:2.4": "Tuy nhiên tôi đã có một buổi đàm thoại Pháp.' ",
  "sn21.3:2.5": "'Tôn giả Mahāmoggallāna đã đàm thoại Pháp với ai?' ",
  "sn21.3:2.6": "'Này hiền giả, tôi đã đàm thoại Pháp với Thế Tôn.' ",
  "sn21.3:2.7": "'Này hiền giả, Thế Tôn hiện đang trú xa tại Sāvatthi, trong Jetavana, tu viện của Anāthapiṇḍika. '",
  "sn21.3:2.8": "Vậy Tôn giả Mahāmoggallāna dùng thần thông đến gặp Thế Tôn, ",
  "sn21.3:2.9": "hay Thế Tôn dùng thần thông đến gặp Tôn giả Mahāmoggallāna?' ",
  "sn21.3:2.10": "'Này hiền giả, tôi không dùng thần thông đến gặp Thế Tôn; '",
  "sn21.3:2.11": "Thế Tôn cũng không dùng thần thông đến gặp tôi. ",
  "sn21.3:2.12": "Mà là thiên nhãn và thiên nhĩ của tôi thanh tịnh đến mức nào thì đến Thế Tôn ở đó. ",
  "sn21.3:2.13": "Và thiên nhãn và thiên nhĩ của Thế Tôn cũng thanh tịnh đến mức nào thì đến chỗ tôi ở đó.' ",
  "sn21.3:2.14": "'Vậy cuộc đàm thoại Pháp giữa Tôn giả Mahāmoggallāna và Thế Tôn diễn ra như thế nào?' ",
  "sn21.3:3.1": "'Này hiền giả, tôi đã hỏi Thế Tôn: '",
  "sn21.3:3.2": "'Thưa Thế Tôn, người ta nói 'tinh tấn dũng mãnh, tinh tấn dũng mãnh'. '",
  "sn21.3:3.3": "Thưa Thế Tôn, thế nào là người có tinh tấn dũng mãnh?' ",
  "sn21.3:3.4": "Khi ấy, này hiền giả, Thế Tôn bảo tôi: ",
  "sn21.3:3.5": "'Này Moggallāna, ở đây Tỳ Kheo tinh tấn dũng mãnh trú '",
  "sn21.3:3.6": "dù chỉ còn lại da, gân và xương, thịt và máu trong thân có thể khô cạn đi, nhưng nếu chưa đạt được điều có thể đạt được bằng sức mạnh, nỗ lực và tinh tấn của con người, thì ta sẽ không dừng nghỉ. ",
  "sn21.3:3.7": "Như vậy là Tỳ Kheo có tinh tấn dũng mãnh.' ",
  "sn21.3:3.8": "Này hiền giả, đó là cuộc đàm thoại Pháp giữa tôi và Thế Tôn.' ",
  "sn21.3:4.1": "'Này hiền giả, ví như những viên đá nhỏ bên cạnh núi chúa Himalaya, chỉ để dùng làm vật kê; '",
  "sn21.3:4.2": "cũng vậy, chúng tôi so với Tôn giả Mahāmoggallāna chỉ như vật kê mà thôi. ",
  "sn21.3:4.3": "Vì Tôn giả Mahāmoggallāna có đại thần thông, đại oai lực, nếu muốn, có thể trú đến cả một kiếp.' ",
  "sn21.3:5.1": "'Này hiền giả, ví như một hạt muối nhỏ trong một bình muối lớn, chỉ thêm vào thêm mắm; '",
  "sn21.3:5.2": "cũng vậy, chúng tôi so với Tôn giả Sāriputta cũng chỉ như vậy mà thôi. ",
  "sn21.3:5.3": "Vì Tôn giả Sāriputta được Thế Tôn tán thán, ca ngợi, xưng tụng bằng nhiều cách: ",
  "sn21.3:6.1": "'Sāriputta về trí tuệ, '",
  "sn21.3:6.2": "về giới hạnh và về tịch tịnh; ",
  "sn21.3:6.3": "Tỳ Kheo nào đã đến bờ kia, ",
  "sn21.3:6.4": "cao nhất cũng chỉ bằng vậy thôi.'' ",
  "sn21.3:7.1": "Như vậy hai vị đại Long tượng ấy vui mừng với những lời khéo nói, khéo thốt của nhau. ",
  "sn21.3:7.2": "Thứ ba. ",
  "sn21.4:0.1": "Tương Ưng Bộ 21.4 ",
  "sn21.4:0.2": "1. Phẩm Tỳ Kheo ",
  "sn21.4:0.3": "Kinh Tỳ Kheo Mới ",
  "sn21.4:1.1": "(Thế Tôn) trú tại Sāvatthi. ",
  "sn21.4:1.2": "Lúc bấy giờ, có một Tỳ Kheo mới kia, sau khi đi khất thực về, bước vào trú xứ, ở yên, im lặng, không hoạt động, không làm các công việc phục vụ các Tỳ Kheo vào thời may y. ",
  "sn21.4:1.3": "Rồi nhiều Tỳ Kheo đến chỗ Thế Tôn; đến rồi, sau khi đảnh lễ Thế Tôn, ngồi xuống một bên. Ngồi một bên, các Tỳ Kheo ấy bạch Thế Tôn: ",
  "sn21.4:1.4": "'Bạch Thế Tôn, ở đây có một Tỳ Kheo mới kia, sau khi đi khất thực về, bước vào trú xứ, ở yên, im lặng, không hoạt động, không làm các công việc phục vụ các Tỳ Kheo vào thời may y.' ",
  "sn21.4:2.1": "Rồi Thế Tôn gọi một Tỳ Kheo: ",
  "sn21.4:2.2": "'Hãy đến đây, Tỳ Kheo, thay mặt ta gọi Tỳ Kheo ấy: 'Này hiền giả, Bậc Đạo Sư gọi hiền giả.'' ",
  "sn21.4:2.3": "'Thưa vâng, bạch Thế Tôn,' Tỳ Kheo ấy vâng lời Thế Tôn, đến chỗ Tỳ Kheo kia; đến rồi nói với Tỳ Kheo ấy: ",
  "sn21.4:2.4": "'Này hiền giả, Bậc Đạo Sư gọi hiền giả.' ",
  "sn21.4:2.5": "'Thưa vâng, hiền giả,' Tỳ Kheo ấy vâng lời Tỳ Kheo kia, đến chỗ Thế Tôn; đến rồi, sau khi đảnh lễ Thế Tôn, ngồi xuống một bên. Thế Tôn nói với Tỳ Kheo ấy đang ngồi một bên: ",
  "sn21.4:2.6": "'Này Tỳ Kheo, có thật chăng rằng sau khi đi khất thực về, ngươi bước vào trú xứ, ở yên, im lặng, không hoạt động, không làm các công việc phục vụ các Tỳ Kheo vào thời may y?' ",
  "sn21.4:2.7": "'Bạch Thế Tôn, con cũng đang làm việc của mình.' ",
  "sn21.4:3.1": "Rồi Thế Tôn, biết được tâm tư suy nghĩ của Tỳ Kheo ấy bằng tâm của mình, gọi các Tỳ Kheo: ",
  "sn21.4:3.2": "'Này các Tỳ Kheo, chớ có chê trách Tỳ Kheo này. '",
  "sn21.4:3.3": "Này các Tỳ Kheo, Tỳ Kheo này tùy ý đắc, không khó khăn, không phí sức về bốn thiền thuộc tâm tăng thượng, hiện tại lạc trú. Tỳ Kheo này đã chứng ngộ, bằng thắng trí, ngay trong đời hiện tại, mục đích tối thượng của phạm hạnh mà các thiện nam tử đã xuất gia từ bỏ gia đình, sống không gia đình vì mục đích đó, và đang an trú trong đó.' ",
  "sn21.4:4.1": "Thế Tôn nói như vậy. ",
  "sn21.4:4.2": "Nói xong, Bậc Thiện Thệ, Bậc Đạo Sư lại nói thêm: ",
  "sn21.4:5.1": "'Không phải do biếng nhác, '",
  "sn21.4:5.2": "không phải do ít sức mạnh; ",
  "sn21.4:5.3": "Niết Bàn phải được chứng đắc, ",
  "sn21.4:5.4": "sự giải thoát khỏi mọi khổ đau. ",
  "sn21.4:6.1": "Tỳ Kheo trẻ tuổi này, ",
  "sn21.4:6.2": "là bậc tối thượng nhân; ",
  "sn21.4:6.3": "Mang thân xác cuối cùng, ",
  "sn21.4:6.4": "đã chiến thắng Ma vương cùng đoàn tùy tùng.' ",
  "sn21.4:6.5": "Thứ tư. ",
  "sn21.5:0.1": "Tương Ưng Bộ 21.5 ",
  "sn21.5:0.2": "1. Phẩm Tỳ Kheo ",
  "sn21.5:0.3": "Kinh Sujāta ",
  "sn21.5:1.1": "(Thế Tôn) trú tại Sāvatthi. ",
  "sn21.5:1.2": "Rồi Tôn giả Sujāta đến chỗ Thế Tôn. ",
  "sn21.5:1.3": "Thế Tôn thấy Tôn giả Sujāta từ xa đi đến. ",
  "sn21.5:1.4": "Thấy vậy, Ngài gọi các Tỳ Kheo: ",
  "sn21.5:1.5": "'Này các Tỳ Kheo, thiện nam tử này đẹp đẽ về cả hai mặt '",
  "sn21.5:1.6": "vừa có dung mạo khả ái, đáng nhìn, dễ mến, vừa đã đạt được mục đích tối thượng của phạm hạnh mà các thiện nam tử đã xuất gia từ bỏ gia đình, sống không gia đình vì mục đích đó, bằng thắng trí, ngay trong đời hiện tại, và đang an trú trong đó.' ",
  "sn21.5:1.7": "Thế Tôn nói như vậy … ",
  "sn21.5:1.8": "Bậc Đạo Sư: ",
  "sn21.5:2.1": "'Tỳ Kheo này thật đáng ngưỡng mộ, '",
  "sn21.5:2.2": "với tâm ngay thẳng; ",
  "sn21.5:2.3": "Đã giải thoát, đã thoát ly, ",
  "sn21.5:2.4": "không chấp thủ, đã tịch diệt; ",
  "sn21.5:2.5": "Mang thân xác cuối cùng, ",
  "sn21.5:2.6": "đã chiến thắng Ma vương cùng đoàn tùy tùng.' ",
  "sn21.5:2.7": "Thứ năm. ",
  "sn21.6:0.1": "Tương Ưng Bộ 21.6 ",
  "sn21.6:0.2": "1. Phẩm Tỳ Kheo ",
  "sn21.6:0.3": "Kinh Lakuṇḍakabhaddiyo ",
  "sn21.6:1.1": "(Thế Tôn) trú tại Sāvatthi. ",
  "sn21.6:1.2": "Rồi Tôn giả Lakuṇḍakabhaddiyo đến chỗ Thế Tôn. ",
  "sn21.6:1.3": "Thế Tôn thấy Tôn giả Lakuṇḍakabhaddiyo từ xa đi đến. ",
  "sn21.6:1.4": "Thấy vậy, Ngài gọi các Tỳ Kheo: ",
  "sn21.6:1.5": "'Này các Tỳ Kheo, các ngươi có thấy Tỳ Kheo kia đang đến khôngdáng xấu, khó nhìn, thấp bé, bị các Tỳ Kheo khinh thường?' ",
  "sn21.6:1.6": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn21.6:1.7": "'Này các Tỳ Kheo, Tỳ Kheo ấy có đại thần thông, đại oai lực. Không dễ gì đạt được các thiền định mà Tỳ Kheo ấy chưa từng đạt trước đây. '",
  "sn21.6:1.8": "Tỳ Kheo này đã chứng ngộ, bằng thắng trí, ngay trong đời hiện tại, mục đích tối thượng của phạm hạnh mà các thiện nam tử đã xuất gia từ bỏ gia đình, sống không gia đình vì mục đích đó, và đang an trú trong đó.' ",
  "sn21.6:1.9": "Thế Tôn nói như vậy … ",
  "sn21.6:1.10": "Bậc Đạo Sư: ",
  "sn21.6:2.1": "'Thiên nga, cò và công, '",
  "sn21.6:2.2": "voi, ngựa và hươu nai; ",
  "sn21.6:2.3": "Tất cả đều sợ sư tử, ",
  "sn21.6:2.4": "thân hình không ai sánh bằng. ",
  "sn21.6:3.1": "Cũng vậy giữa loài người, ",
  "sn21.6:3.2": "dù trẻ tuổi nhưng có trí tuệ; ",
  "sn21.6:3.3": "Người ấy thật sự là bậc vĩ đại ở đó, ",
  "sn21.6:3.4": "kẻ ngu không phải vì thân xác to lớn.' ",
  "sn21.6:3.5": "Thứ sáu. ",
  "sn21.7:0.1": "Tương Ưng Bộ 21.7 ",
  "sn21.7:0.2": "1. Phẩm Tỳ Kheo ",
  "sn21.7:0.3": "Kinh Visākha ",
  "sn21.7:1.1": "Tôi nghe như vầy",
  "sn21.7:1.2": "Một thời, Thế Tôn trú tại Vesāli, trong Mahāvana, tại giảng đường Kūṭāgāra. ",
  "sn21.7:1.3": "Lúc bấy giờ, Tôn giả Visākha Pañcālaputta đang thuyết giảng, khích lệ, cổ vũ, làm hoan hỷ các Tỳ Kheo trong giảng đường bằng một bài pháp thoại, với lời nói tao nhã, rõ ràng, lưu loát, trình bày được nghĩa lý, trọn vẹn và không phụ thuộc. ",
  "sn21.7:2.1": "Rồi Thế Tôn vào buổi chiều, xuất thiền, đến giảng đường; đến rồi ngồi vào chỗ đã được sắp sẵn. ",
  "sn21.7:2.2": "Ngồi rồi, Thế Tôn gọi các Tỳ Kheo: ",
  "sn21.7:2.3": "'Ai vừa rồi trong giảng đường đang thuyết giảng, khích lệ, cổ vũ, làm hoan hỷ các Tỳ Kheo bằng một bài pháp thoại, với lời nói tao nhã, rõ ràng, lưu loát, trình bày được nghĩa lý, trọn vẹn và không phụ thuộc?' ",
  "sn21.7:2.4": "'Bạch Thế Tôn, Tôn giả Visākha Pañcālaputta đang thuyết giảng, khích lệ, cổ vũ, làm hoan hỷ các Tỳ Kheo trong giảng đường bằng một bài pháp thoại, với lời nói tao nhã, rõ ràng, lưu loát, trình bày được nghĩa lý, trọn vẹn và không phụ thuộc.' ",
  "sn21.7:3.1": "Rồi Thế Tôn gọi Tôn giả Visākha Pañcālaputta: ",
  "sn21.7:3.2": "'Lành thay, lành thay, Visākha, '",
  "sn21.7:3.3": "lành thay hiền giả Visākha đã thuyết giảng, khích lệ … trình bày được nghĩa lý, trọn vẹn và không phụ thuộc.' ",
  "sn21.7:4.1": "Thế Tôn nói như vậy. ",
  "sn21.7:4.2": "Nói xong, Bậc Thiện Thệ, Bậc Đạo Sư lại nói thêm: ",
  "sn21.7:5.1": "'Người không giảng, người ta không biết, '",
  "sn21.7:5.2": "bậc trí lẫn lộn giữa đám ngu; ",
  "sn21.7:5.3": "Người giảng, người ta mới biết, ",
  "sn21.7:5.4": "khi truyền dạy con đường bất tử. ",
  "sn21.7:6.1": "Hãy thuyết, hãy soi sáng Pháp, ",
  "sn21.7:6.2": "hãy phất cao cờ hiệu của bậc ẩn sĩ; ",
  "sn21.7:6.3": "Các ẩn sĩ lấy lời khéo nói làm cờ hiệu, ",
  "sn21.7:6.4": "vì Pháp là cờ hiệu của các ẩn sĩ.' ",
  "sn21.7:6.5": "Thứ bảy. ",
  "sn21.8:0.1": "Tương Ưng Bộ 21.8 ",
  "sn21.8:0.2": "1. Phẩm Tỳ Kheo ",
  "sn21.8:0.3": "Kinh Nanda ",
  "sn21.8:1.1": "(Thế Tôn) trú tại Sāvatthi. ",
  "sn21.8:1.2": "Rồi Tôn giả Nanda, con của cậu Thế Tôn, mặc y được ủi phẳng, kẻ mắt, cầm bình bát bóng loáng, đến chỗ Thế Tôn; đến rồi, sau khi đảnh lễ Thế Tôn, ngồi xuống một bên. Thế Tôn nói với Tôn giả Nanda đang ngồi một bên: ",
  "sn21.8:1.3": "'Này Nanda, điều đó không thích hợp với ngươimột thiện nam tử xuất gia với lòng tin, từ bỏ gia đình, sống không gia đìnhmà lại mặc y được ủi phẳng, kẻ mắt, cầm bình bát bóng loáng. '",
  "sn21.8:1.4": "Này Nanda, điều này thích hợp với ngươimột thiện nam tử xuất gia với lòng tin, từ bỏ gia đình, sống không gia đìnhlà hãy sống ở rừng, là bậc trì bình khất thực, là bậc mặc y phấn tảo, và sống viễn ly với các dục.' ",
  "sn21.8:1.5": "Thế Tôn nói như vậy … ",
  "sn21.8:1.6": "Bậc Đạo Sư: ",
  "sn21.8:2.1": "'Bao giờ ta mới thấy Nanda, '",
  "sn21.8:2.2": "sống trong rừng, mặc y phấn tảo; ",
  "sn21.8:2.3": "Sống bằng thức ăn lượm nhặt, ",
  "sn21.8:2.4": "viễn ly với các dục.' ",
  "sn21.8:3.1": "Rồi Tôn giả Nanda, sau đó, đã sống ở rừng, là bậc trì bình khất thực, là bậc mặc y phấn tảo, viễn ly với các dục. ",
  "sn21.8:3.2": "Thứ tám. ",
  "sn21.9:0.1": "Tương Ưng Bộ 21.9 ",
  "sn21.9:0.2": "1. Phẩm Tỳ Kheo ",
  "sn21.9:0.3": "Kinh Tissa ",
  "sn21.9:1.1": "(Thế Tôn) trú tại Sāvatthi. ",
  "sn21.9:1.2": "Rồi Tôn giả Tissa, con của cô Thế Tôn, đến chỗ Thế Tôn; đến rồi, sau khi đảnh lễ Thế Tôn, ngồi xuống một bên, buồn khổ, sầu muộn, nước mắt chảy dài. Rồi Thế Tôn hỏi Tôn giả Tissa: ",
  "sn21.9:1.3": "'Tại sao ngươi, này Tissa, ngồi một bên buồn khổ, sầu muộn, nước mắt chảy dài?' ",
  "sn21.9:1.4": "'Bạch Thế Tôn, vì các Tỳ Kheo xung quanh con nói những lời mắng nhiếc, châm chọc con.' ",
  "sn21.9:1.5": "'Này Tissa, vì ngươi hay chỉ trích người khác mà lại không chịu đựng được lời khuyên bảo; '",
  "sn21.9:1.6": "Này Tissa, điều đó không thích hợp với ngươimột thiện nam tử xuất gia với lòng tin, từ bỏ gia đình, sống không gia đìnhlà hay chỉ trích người khác mà lại không chịu đựng được lời khuyên bảo. ",
  "sn21.9:1.7": "Điều này thích hợp với ngươi, này Tissa, một thiện nam tử xuất gia với lòng tin, từ bỏ gia đình, sống không gia đình: ",
  "sn21.9:1.8": "'Hãy vừa là người hay chỉ trích vừa chịu đựng được lời khuyên bảo.'' '",
  "sn21.9:2.1": "Thế Tôn nói như vậy. ",
  "sn21.9:2.2": "Nói xong, Bậc Thiện Thệ, Bậc Đạo Sư lại nói thêm: ",
  "sn21.9:3.1": "'Tại sao ngươi tức giận? Chớ giận, '",
  "sn21.9:3.2": "Không sân hận, này Tissa, là tốt hơn cho ngươi; ",
  "sn21.9:3.3": "Vì để điều phục sân hận, kiêu mạn và ganh tỵ, ",
  "sn21.9:3.4": "Này Tissa, phạm hạnh được tu tập.' ",
  "sn21.9:3.5": "Thứ chín. ",
  "sn21.10:0.1": "Tương Ưng Bộ 21.10 ",
  "sn21.10:0.2": "1. Phẩm Tỳ Kheo ",
  "sn21.10:0.3": "Kinh Trưởng Lão ",
  "sn21.10:1.1": "Một thời, Thế Tôn trú tại Rājagaha, trong Veḷuvana, vườn sóc. ",
  "sn21.10:1.2": "Lúc bấy giờ, có một Tỳ Kheo tên Thera sống độc cư và ca ngợi sự độc cư. ",
  "sn21.10:1.3": "Vị ấy một mình vào làng khất thực, một mình trở về, một mình ngồi nơi vắng vẻ, một mình kinh hành. ",
  "sn21.10:1.4": "Rồi nhiều Tỳ Kheo đến chỗ Thế Tôn; đến rồi, sau khi đảnh lễ Thế Tôn, ngồi xuống một bên. Ngồi một bên, các Tỳ Kheo ấy bạch Thế Tôn: ",
  "sn21.10:1.5": "'Bạch Thế Tôn, ở đây có Tỳ Kheo tên Thera sống độc cư và ca ngợi sự độc cư.' ",
  "sn21.10:2.1": "Rồi Thế Tôn gọi một Tỳ Kheo: ",
  "sn21.10:2.2": "'Hãy đến đây, Tỳ Kheo, thay mặt ta gọi Tỳ Kheo Thera: '",
  "sn21.10:2.3": "'Này Trưởng Lão, Bậc Đạo Sư gọi Trưởng Lão.'' '",
  "sn21.10:2.4": "'Thưa vâng, bạch Thế Tôn,' Tỳ Kheo ấy vâng lời Thế Tôn, đến chỗ Tôn giả Thera; đến rồi nói với Tôn giả Thera: ",
  "sn21.10:2.5": "'Này Trưởng Lão, Bậc Đạo Sư gọi Trưởng Lão.' ",
  "sn21.10:2.6": "'Thưa vâng, hiền giả,' Tôn giả Thera vâng lời Tỳ Kheo kia, đến chỗ Thế Tôn; đến rồi, sau khi đảnh lễ Thế Tôn, ngồi xuống một bên. Thế Tôn nói với Tôn giả Thera đang ngồi một bên: ",
  "sn21.10:2.7": "'Này Thera, có thật chăng rằng ngươi sống độc cư và ca ngợi sự độc cư?' ",
  "sn21.10:2.8": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn21.10:2.9": "'Này Thera, ngươi sống độc cư và ca ngợi sự độc cư như thế nào?' ",
  "sn21.10:2.10": "'Bạch Thế Tôn, ở đây con một mình vào làng khất thực, một mình trở về, một mình ngồi nơi vắng vẻ, một mình kinh hành. '",
  "sn21.10:2.11": "Như vậy, bạch Thế Tôn, con sống độc cư và ca ngợi sự độc cư.' ",
  "sn21.10:3.1": "'Này Thera, có sự độc cư như vậy, ta không nói là không có. '",
  "sn21.10:3.2": "Nhưng này Thera, hãy nghe về sự độc cư đầy đủ theo nghĩa rộng ",
  "sn21.10:3.3": "hãy lắng nghe, hãy khéo tác ý; ta sẽ giảng.' ",
  "sn21.10:3.4": "'Thưa vâng, bạch Thế Tôn,' … ",
  "sn21.10:3.5": "'Và này Thera, thế nào là sự độc cư đầy đủ theo nghĩa rộng? '",
  "sn21.10:3.6": "Này Thera, ở đây cái gì thuộc quá khứ đã được từ bỏ, cái gì thuộc tương lai đã được từ khước, và tham dục đối với các thân phận hiện tại đã được khéo điều phục. ",
  "sn21.10:3.7": "Như vậy, này Thera, là sự độc cư đầy đủ theo nghĩa rộng.' ",
  "sn21.10:4.1": "Thế Tôn nói như vậy. ",
  "sn21.10:4.2": "Nói xong, Bậc Thiện Thệ, Bậc Đạo Sư lại nói thêm: ",
  "sn21.10:5.1": "'Bậc đã chinh phục tất cả, biết tất cả, có trí tuệ siêu việt, '",
  "sn21.10:5.2": "không bị ô nhiễm bởi bất kỳ pháp nào; ",
  "sn21.10:5.3": "Đã từ bỏ tất cả, giải thoát khi ái diệt, ",
  "sn21.10:5.4": "Ta gọi người ấy là bậc sống độc cư.' ",
  "sn21.10:5.5": "Thứ mười. ",
  "sn21.11:0.1": "Tương Ưng Bộ 21.11 ",
  "sn21.11:0.2": "1. Phẩm Tỳ Kheo ",
  "sn21.11:0.3": "Kinh Mahākappina ",
  "sn21.11:1.1": "(Thế Tôn) trú tại Sāvatthi. ",
  "sn21.11:1.2": "Rồi Tôn giả Mahākappina đến chỗ Thế Tôn. ",
  "sn21.11:1.3": "Thế Tôn thấy Tôn giả Mahākappina từ xa đi đến. ",
  "sn21.11:1.4": "Thấy vậy, Ngài gọi các Tỳ Kheo: ",
  "sn21.11:1.5": "'Này các Tỳ Kheo, các ngươi có thấy Tỳ Kheo kia đang đến khôngnước da trắng, thân gầy, mũi cao?' ",
  "sn21.11:1.6": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn21.11:1.7": "'Này các Tỳ Kheo, Tỳ Kheo ấy có đại thần thông, đại oai lực. '",
  "sn21.11:1.8": "Không dễ gì đạt được các thiền định mà Tỳ Kheo ấy chưa từng đạt trước đây. ",
  "sn21.11:1.9": "Tỳ Kheo này đã chứng ngộ, bằng thắng trí, ngay trong đời hiện tại, mục đích tối thượng của phạm hạnh mà các thiện nam tử đã xuất gia từ bỏ gia đình, sống không gia đình vì mục đích đó, và đang an trú trong đó.' ",
  "sn21.11:2.1": "Thế Tôn nói như vậy. ",
  "sn21.11:2.2": "Nói xong, Bậc Thiện Thệ, Bậc Đạo Sư lại nói thêm: ",
  "sn21.11:3.1": "'Sát-đế-lị là tối thượng trong số người, '",
  "sn21.11:3.2": "đối với những ai quý trọng dòng dõi; ",
  "sn21.11:3.3": "Bậc đầy đủ minh và hạnh, ",
  "sn21.11:3.4": "là tối thượng trong hàng chư thiên và loài người. ",
  "sn21.11:4.1": "Ban ngày mặt trời tỏa sáng, ",
  "sn21.11:4.2": "ban đêm mặt trăng chiếu sáng; ",
  "sn21.11:4.3": "Chiến sĩ tỏa sáng khi mặc giáp, ",
  "sn21.11:4.4": "bà-la-môn tỏa sáng trong thiền định; ",
  "sn21.11:4.5": "Nhưng trọn cả ngày và đêm, ",
  "sn21.11:4.6": "Đức Phật tỏa sáng bằng hào quang.' ",
  "sn21.11:4.7": "Thứ mười một. ",
  "sn21.12:0.1": "Tương Ưng Bộ 21.12 ",
  "sn21.12:0.2": "1. Phẩm Tỳ Kheo ",
  "sn21.12:0.3": "Kinh Bạn Đồng Hành ",
  "sn21.12:1.1": "(Thế Tôn) trú tại Sāvatthi. ",
  "sn21.12:1.2": "Rồi hai Tỳ Kheo bạn đồng hành, là thị giả của Tôn giả Mahākappina, đến chỗ Thế Tôn. ",
  "sn21.12:1.3": "Thế Tôn thấy các Tỳ Kheo ấy từ xa đi đến. ",
  "sn21.12:1.4": "Thấy vậy, Ngài gọi các Tỳ Kheo: ",
  "sn21.12:1.5": "'Này các Tỳ Kheo, các ngươi có thấy hai Tỳ Kheo bạn đồng hành kia đang đến, là thị giả của Kappina?' ",
  "sn21.12:1.6": "'Thưa vâng, bạch Thế Tôn.' ",
  "sn21.12:1.7": "'Các Tỳ Kheo ấy có đại thần thông, đại oai lực. '",
  "sn21.12:1.8": "Không dễ gì đạt được các thiền định mà các Tỳ Kheo ấy chưa từng đạt trước đây. ",
  "sn21.12:1.9": "Các Tỳ Kheo này đã chứng ngộ, bằng thắng trí, ngay trong đời hiện tại, mục đích tối thượng của phạm hạnh mà các thiện nam tử đã xuất gia từ bỏ gia đình, sống không gia đình vì mục đích đó, và đang an trú trong đó.' ",
  "sn21.12:2.1": "Thế Tôn nói như vậy. ",
  "sn21.12:2.2": "Nói xong, Bậc Thiện Thệ, Bậc Đạo Sư lại nói thêm: ",
  "sn21.12:3.1": "'Hai Tỳ Kheo bạn đồng hành này, '",
  "sn21.12:3.2": "đã hội tụ lại từ lâu; ",
  "sn21.12:3.3": "Diệu Pháp của họ hội tụ, ",
  "sn21.12:3.4": "pháp mà Đức Phật đã tuyên thuyết. ",
  "sn21.12:4.1": "Được Kappina khéo giáo dưỡng, ",
  "sn21.12:4.2": "trong pháp do bậc Thánh tuyên thuyết; ",
  "sn21.12:4.3": "Mang thân xác cuối cùng, ",
  "sn21.12:4.4": "đã chiến thắng Ma vương cùng đoàn tùy tùng.' ",
  "sn21.12:4.5": "Thứ mười hai. ",
  "sn21.12:4.6": "Phẩm Tỳ Kheo thứ nhất. ",
  "sn21.12:5.0": "Tóm lược phẩm này: ",
  "sn21.12:5.1": "Kolita và Upatissa, ",
  "sn21.12:5.2": "còn được gọi là Ghaṭa; ",
  "sn21.12:5.3": "Tỳ Kheo Mới, Sujāta, Bhaddi, ",
  "sn21.12:5.4": "Visākha, Nanda, Tissa; ",
  "sn21.12:5.5": "Tên Thera và Kappina, ",
  "sn21.12:5.6": "cùng Bạn Đồng Hành, tổng cộng mười hai. ",
  "sn21.12:5.7": "Tương Ưng Tỳ Kheo hoàn tất. ",
  "sn21.12:5.8": "Phẩm Nidāna thứ hai. ",
  "sn21.12:6.0": "Tóm lược phẩm này: ",
  "sn21.12:6.1": "Nidāna, Abhisamaya, Dhātu, ",
  "sn21.12:6.2": "Anamatagga cùng Kassapa; ",
  "sn21.12:6.3": "Sakkāra, Rāhula, Lakkhaṇa, ",
  "sn21.12:6.4": "Opamma và phẩm Tỳ Kheo. ",
  "sn21.12:6.5": "Đây được gọi là phẩm thứ hai. ",
  "sn21.12:6.6": "Tương Ưng Nidāna Vagga Pāḷi kết thúc. "
}
window.BILARA["sn21_v1"]["vi"]["sn21_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
