window.BILARA = window.BILARA || {};
window.BILARA["sn23_v1"] = window.BILARA["sn23_v1"] || {};
window.BILARA["sn23_v1"]["vi"] = {
  "sn23.1:0.1": "Tương Ưng Bộ 23.1 ",
  "sn23.1:0.2": "1. Phẩm Ma Vương Thứ Nhất ",
  "sn23.1:0.3": "Kinh Ma Vương ",
  "sn23.1:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.1:1.2": "Rồi Tôn giả Rādha đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn, rồi ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.1:2.1": "''Ma Vương, Ma Vương', bạch Thế Tôn, người ta thường nói. '",
  "sn23.1:2.2": "Cho đến mức nào, bạch Thế Tôn, được gọi là Ma Vương?' ",
  "sn23.1:2.3": "'Này Rādha, khi có sắc thì đó là Ma Vương, hay kẻ sát hại, hay kẻ bị sát hại. '",
  "sn23.1:2.4": "Vì vậy, này Rādha, hãy quán sắc là Ma Vương, hãy quán là kẻ sát hại, hãy quán là kẻ bị sát hại, hãy quán là bệnh tật, hãy quán là ung nhọt, hãy quán là mũi tên, hãy quán là điều bất hạnh, hãy quán là điều trở thành bất hạnh. ",
  "sn23.1:2.5": "Những ai quán như vậy, những người ấy quán đúng đắn. ",
  "sn23.1:2.6": "Khi có thọ… ",
  "sn23.1:2.7": "khi có tưởng… ",
  "sn23.1:2.8": "khi có các hành… ",
  "sn23.1:2.9": "khi có thức thì đó là Ma Vương, hay kẻ sát hại, hay kẻ bị sát hại. ",
  "sn23.1:2.10": "Vì vậy, này Rādha, hãy quán thức là Ma Vương, hãy quán là kẻ sát hại, hãy quán là kẻ bị sát hại, hãy quán là bệnh tật, hãy quán là ung nhọt, hãy quán là mũi tên, hãy quán là điều bất hạnh, hãy quán là điều trở thành bất hạnh. ",
  "sn23.1:2.11": "Những ai quán như vậy, những người ấy quán đúng đắn.' ",
  "sn23.1:3.1": "'Nhưng bạch Thế Tôn, chánh kiến có mục đích gì?' ",
  "sn23.1:3.2": "'Này Rādha, chánh kiến có mục đích là yếm ly.' ",
  "sn23.1:3.3": "'Nhưng bạch Thế Tôn, yếm ly có mục đích gì?' ",
  "sn23.1:3.4": "'Này Rādha, yếm ly có mục đích là ly tham.' ",
  "sn23.1:3.5": "'Nhưng bạch Thế Tôn, ly tham có mục đích gì?' ",
  "sn23.1:3.6": "'Này Rādha, ly tham có mục đích là giải thoát.' ",
  "sn23.1:3.7": "'Nhưng bạch Thế Tôn, giải thoát có mục đích gì?' ",
  "sn23.1:3.8": "'Này Rādha, giải thoát có mục đích là Niết-bàn.' ",
  "sn23.1:3.9": "'Nhưng bạch Thế Tôn, Niết-bàn có mục đích gì?' ",
  "sn23.1:3.10": "'Này Rādha, ông đã hỏi quá mức, không thể nắm bắt được giới hạn của câu hỏi này. '",
  "sn23.1:3.11": "Phạm hạnh được sống với Niết-bàn là nơi nương tựa, Niết-bàn là mục tiêu tối hậu, Niết-bàn là chỗ cuối cùng.' ",
  "sn23.1:3.12": "Thứ nhất. ",
  "sn23.2:0.1": "Tương Ưng Bộ 23.2 ",
  "sn23.2:0.2": "1. Phẩm Ma Vương Thứ Nhất ",
  "sn23.2:0.3": "Kinh Chúng Sanh ",
  "sn23.2:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.2:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.2:1.3": "''Chúng sanh, chúng sanh', bạch Thế Tôn, người ta thường nói. '",
  "sn23.2:1.4": "Cho đến mức nào, bạch Thế Tôn, được gọi là chúng sanh?' ",
  "sn23.2:1.5": "'Này Rādha, đối với sắc, ai có ham muốn, tham ái, hỷ lạc, khát ái thì bị trói buộc vào đó, bị ràng buộc vào đó, vì vậy được gọi là chúng sanh. '",
  "sn23.2:1.6": "Đối với thọ… ",
  "sn23.2:1.7": "đối với tưởng… ",
  "sn23.2:1.8": "đối với các hành… ",
  "sn23.2:1.9": "đối với thức, ai có ham muốn, tham ái, hỷ lạc, khát ái thì bị trói buộc vào đó, bị ràng buộc vào đó, vì vậy được gọi là chúng sanh. ",
  "sn23.2:2.1": "Này Rādha, ví như các trẻ em trai hay trẻ em gái đang chơi với những ngôi nhà bằng cát. ",
  "sn23.2:2.2": "Khi nào chúng còn chưa ly tham đối với những ngôi nhà bằng cát đó, còn ham muốn, còn yêu thích, còn khát khao, còn say đắm, còn ái luyến  thì chúng sẽ chơi đùa, nâng niu, quý trọng và giữ gìn những ngôi nhà bằng cát ấy. ",
  "sn23.2:2.3": "Nhưng khi nào, này Rādha, các trẻ em trai hay trẻ em gái đã ly tham đối với những ngôi nhà bằng cát, không còn ham muốn, không còn yêu thích, không còn khát khao, không còn say đắm, không còn ái luyến  thì chúng sẽ dùng tay chân phá tan, đập vỡ, phá hủy và không còn chơi đùa với chúng nữa. ",
  "sn23.2:2.4": "Cũng vậy, này Rādha, các ông hãy phá tan, đập vỡ, phá hủy sắc, không còn chơi đùa với nó nữa, hãy thực hành để đoạn trừ ái. ",
  "sn23.2:2.5": "Hãy phá tan, đập vỡ, phá hủy thọ, không còn chơi đùa với nó nữa, hãy thực hành để đoạn trừ ái. ",
  "sn23.2:2.6": "Đối với tưởng… ",
  "sn23.2:2.7": "hãy phá tan, đập vỡ, phá hủy các hành, không còn chơi đùa với chúng nữa, hãy thực hành để đoạn trừ ái. ",
  "sn23.2:2.8": "Hãy phá tan, đập vỡ, phá hủy thức, không còn chơi đùa với nó nữa, hãy thực hành để đoạn trừ ái. ",
  "sn23.2:2.9": "Vì này Rādha, đoạn trừ ái chính là Niết-bàn.' ",
  "sn23.2:2.10": "Thứ hai. ",
  "sn23.3:0.1": "Tương Ưng Bộ 23.3 ",
  "sn23.3:0.2": "1. Phẩm Ma Vương Thứ Nhất ",
  "sn23.3:0.3": "Kinh Sợi Dây Dẫn Đến Tái Sanh ",
  "sn23.3:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.3:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.3:1.3": "''Đoạn trừ sợi dây dẫn đến tái sanh, đoạn trừ sợi dây dẫn đến tái sanh', bạch Thế Tôn, người ta thường nói. '",
  "sn23.3:1.4": "Bạch Thế Tôn, thế nào là sợi dây dẫn đến tái sanh, thế nào là đoạn trừ sợi dây dẫn đến tái sanh?' ",
  "sn23.3:1.5": "'Này Rādha, đối với sắc, những ham muốn, tham ái, hỷ lạc, khát ái, những sự tiếp cận và chấp thủ, sự an trú của tâm, sự thiên chấp và tùy miên  '",
  "sn23.3:1.6": "đây gọi là sợi dây dẫn đến tái sanh. ",
  "sn23.3:1.7": "Sự đoạn diệt những điều đó là đoạn trừ sợi dây dẫn đến tái sanh. ",
  "sn23.3:1.8": "Đối với thọ… ",
  "sn23.3:1.9": "đối với tưởng… ",
  "sn23.3:1.10": "đối với các hành… ",
  "sn23.3:1.11": "đối với thức, những ham muốn… và tùy miên  ",
  "sn23.3:1.12": "đây gọi là sợi dây dẫn đến tái sanh. ",
  "sn23.3:1.13": "Sự đoạn diệt những điều đó là đoạn trừ sợi dây dẫn đến tái sanh.' ",
  "sn23.3:1.14": "Thứ ba. ",
  "sn23.4:0.1": "Tương Ưng Bộ 23.4 ",
  "sn23.4:0.2": "1. Phẩm Ma Vương Thứ Nhất ",
  "sn23.4:0.3": "Kinh Cần Liễu Tri ",
  "sn23.4:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.4:1.2": "Tôn giả Rādha đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn, rồi ngồi xuống một bên. Rồi Thế Tôn nói với Tôn giả Rādha đang ngồi một bên: ",
  "sn23.4:2.1": "'Này Rādha, Ta sẽ giảng cho ông nghe về các pháp cần được liễu tri, về sự liễu tri, và về người đã liễu tri. '",
  "sn23.4:2.2": "Hãy nghe và khéo tác ý; Ta sẽ nói.' ",
  "sn23.4:2.3": "'Thưa vâng, bạch Thế Tôn,' Tôn giả Rādha đáp lại Thế Tôn. ",
  "sn23.4:2.4": "Thế Tôn nói: ",
  "sn23.4:2.5": "'Này Rādha, thế nào là các pháp cần được liễu tri? '",
  "sn23.4:2.6": "Này Rādha, sắc là pháp cần được liễu tri, thọ là pháp cần được liễu tri, tưởng là pháp cần được liễu tri, các hành là pháp cần được liễu tri, thức là pháp cần được liễu tri. ",
  "sn23.4:2.7": "Này Rādha, đây gọi là các pháp cần được liễu tri. ",
  "sn23.4:2.8": "Và này Rādha, thế nào là sự liễu tri? ",
  "sn23.4:2.9": "Này Rādha, sự đoạn trừ tham, sự đoạn trừ sân, sự đoạn trừ si  ",
  "sn23.4:2.10": "này Rādha, đây gọi là sự liễu tri. ",
  "sn23.4:2.11": "Và này Rādha, thế nào là người đã liễu tri? ",
  "sn23.4:2.12": "Phải nói rằng đó là bậc A-la-hán. ",
  "sn23.4:2.13": "Đó là vị Tôn giả có tên này, có dòng họ này  ",
  "sn23.4:2.14": "này Rādha, đây gọi là người đã liễu tri.' ",
  "sn23.4:2.15": "Thứ tư. ",
  "sn23.5:0.1": "Tương Ưng Bộ 23.5 ",
  "sn23.5:0.2": "1. Phẩm Ma Vương Thứ Nhất ",
  "sn23.5:0.3": "Kinh Sa-môn Thứ Nhất ",
  "sn23.5:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.5:1.2": "Rồi Thế Tôn nói với Tôn giả Rādha đang ngồi một bên: ",
  "sn23.5:1.3": "'Này Rādha, có năm thủ uẩn này. '",
  "sn23.5:1.4": "Năm là gì? ",
  "sn23.5:1.5": "Sắc thủ uẩn, thọ thủ uẩn, tưởng thủ uẩn, hành thủ uẩn, thức thủ uẩn. ",
  "sn23.5:1.6": "Này Rādha, những Sa-môn hay Bà-la-môn nào không như thật biết rõ vị ngọt, sự nguy hiểm và sự xuất ly của năm thủ uẩn này; ",
  "sn23.5:1.7": "những vị ấy, này Rādha, không được Ta xem là Sa-môn trong hàng Sa-môn, hay Bà-la-môn trong hàng Bà-la-môn, và các vị Tôn giả ấy cũng không tự mình chứng ngộ, chứng đắc và an trú mục đích của Sa-môn hạnh hay Bà-la-môn hạnh ngay trong hiện tại. ",
  "sn23.5:1.8": "Này Rādha, những Sa-môn hay Bà-la-môn nào như thật biết rõ vị ngọt, sự nguy hiểm và sự xuất ly của năm thủ uẩn này; ",
  "sn23.5:1.9": "những vị ấy, này Rādha, được Ta xem là Sa-môn trong hàng Sa-môn, là Bà-la-môn trong hàng Bà-la-môn, và các vị Tôn giả ấy tự mình chứng ngộ, chứng đắc và an trú mục đích của Sa-môn hạnh và Bà-la-môn hạnh ngay trong hiện tại.' ",
  "sn23.5:1.10": "Thứ năm. ",
  "sn23.6:0.1": "Tương Ưng Bộ 23.6 ",
  "sn23.6:0.2": "1. Phẩm Ma Vương Thứ Nhất ",
  "sn23.6:0.3": "Kinh Sa-môn Thứ Hai ",
  "sn23.6:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.6:1.2": "Rồi Thế Tôn nói với Tôn giả Rādha đang ngồi một bên: ",
  "sn23.6:1.3": "'Này Rādha, có năm thủ uẩn này. '",
  "sn23.6:1.4": "Năm là gì? ",
  "sn23.6:1.5": "Sắc thủ uẩn … thức thủ uẩn. ",
  "sn23.6:1.6": "Này Rādha, những Sa-môn hay Bà-la-môn nào không như thật biết rõ sự sanh khởi, sự đoạn diệt, vị ngọt, sự nguy hiểm và sự xuất ly của năm thủ uẩn này … ",
  "sn23.6:1.7": "tự mình chứng ngộ, chứng đắc và an trú.' ",
  "sn23.6:1.8": "Thứ sáu. ",
  "sn23.7:0.1": "Tương Ưng Bộ 23.7 ",
  "sn23.7:0.2": "1. Phẩm Ma Vương Thứ Nhất ",
  "sn23.7:0.3": "Kinh Dự Lưu ",
  "sn23.7:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.7:1.2": "Rồi Thế Tôn nói với Tôn giả Rādha đang ngồi một bên: ",
  "sn23.7:1.3": "'Này Rādha, có năm thủ uẩn này. '",
  "sn23.7:1.4": "Năm là gì? ",
  "sn23.7:1.5": "Sắc thủ uẩn … thức thủ uẩn. ",
  "sn23.7:1.6": "Khi nào, này Rādha, vị Thánh đệ tử như thật biết rõ sự sanh khởi, sự đoạn diệt, vị ngọt, sự nguy hiểm và sự xuất ly của năm thủ uẩn này  ",
  "sn23.7:1.7": "khi ấy, này Rādha, vị Thánh đệ tử được gọi là bậc Dự Lưu, không còn rơi vào các cõi khổ, quyết định sẽ đạt giác ngộ.' ",
  "sn23.7:1.8": "Thứ bảy. ",
  "sn23.8:0.1": "Tương Ưng Bộ 23.8 ",
  "sn23.8:0.2": "1. Phẩm Ma Vương Thứ Nhất ",
  "sn23.8:0.3": "Kinh A-la-hán ",
  "sn23.8:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.8:1.2": "Rồi Thế Tôn nói với Tôn giả Rādha đang ngồi một bên: ",
  "sn23.8:1.3": "'Này Rādha, có năm thủ uẩn này. '",
  "sn23.8:1.4": "Năm là gì? ",
  "sn23.8:1.5": "Sắc thủ uẩn … thức thủ uẩn. ",
  "sn23.8:1.6": "Khi nào, này Rādha, Tỳ Kheo sau khi như thật biết rõ sự sanh khởi, sự đoạn diệt, vị ngọt, sự nguy hiểm và sự xuất ly của năm thủ uẩn này, được giải thoát không còn chấp thủ  ",
  "sn23.8:1.7": "khi ấy, này Rādha, Tỳ Kheo ấy được gọi là bậc A-la-hán, đã đoạn tận các lậu hoặc, đã sống phạm hạnh, đã làm những gì cần làm, đã đặt xuống gánh nặng, đã đạt mục đích tối thượng, đã đoạn trừ hữu kiết sử, được giải thoát với chánh trí.' ",
  "sn23.8:1.8": "Thứ tám. ",
  "sn23.9:0.1": "Tương Ưng Bộ 23.9 ",
  "sn23.9:0.2": "1. Phẩm Ma Vương Thứ Nhất ",
  "sn23.9:0.3": "Kinh Dục Tham Thứ Nhất ",
  "sn23.9:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.9:1.2": "Rồi Thế Tôn nói với Tôn giả Rādha đang ngồi một bên: ",
  "sn23.9:1.3": "'Này Rādha, đối với sắc, những ham muốn, tham ái, hỷ lạc, khát ái  hãy đoạn trừ chúng. '",
  "sn23.9:1.4": "Như vậy sắc ấy sẽ được đoạn trừ, bị cắt đứt tận gốc, không còn điều kiện để tồn tại, không còn sanh khởi trong tương lai. ",
  "sn23.9:1.5": "Đối với thọ, những ham muốn, tham ái, hỷ lạc, khát ái  hãy đoạn trừ chúng. ",
  "sn23.9:1.6": "Như vậy thọ ấy sẽ được đoạn trừ, bị cắt đứt tận gốc, không còn điều kiện để tồn tại, không còn sanh khởi trong tương lai. ",
  "sn23.9:1.7": "Đối với tưởng… ",
  "sn23.9:1.8": "đối với các hành, những ham muốn, tham ái, hỷ lạc, khát ái  hãy đoạn trừ chúng. ",
  "sn23.9:1.9": "Như vậy các hành ấy sẽ được đoạn trừ, bị cắt đứt tận gốc, không còn điều kiện để tồn tại, không còn sanh khởi trong tương lai. ",
  "sn23.9:1.10": "Đối với thức, những ham muốn, tham ái, hỷ lạc, khát ái  hãy đoạn trừ chúng. ",
  "sn23.9:1.11": "Như vậy thức ấy sẽ được đoạn trừ … không còn sanh khởi trong tương lai.' ",
  "sn23.9:1.12": "Thứ chín. ",
  "sn23.10:0.1": "Tương Ưng Bộ 23.10 ",
  "sn23.10:0.2": "1. Phẩm Ma Vương Thứ Nhất ",
  "sn23.10:0.3": "Kinh Dục Tham Thứ Hai ",
  "sn23.10:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.10:1.2": "Rồi Thế Tôn nói với Tôn giả Rādha đang ngồi một bên: ",
  "sn23.10:1.3": "'Này Rādha, đối với sắc, những ham muốn, tham ái, hỷ lạc, khát ái, những sự tiếp cận và chấp thủ, sự an trú của tâm, sự thiên chấp và tùy miên  hãy đoạn trừ chúng. '",
  "sn23.10:1.4": "Như vậy sắc ấy sẽ được đoạn trừ, bị cắt đứt tận gốc, không còn điều kiện để tồn tại, không còn sanh khởi trong tương lai. ",
  "sn23.10:1.5": "Đối với thọ, những ham muốn, tham ái, hỷ lạc, khát ái, những sự tiếp cận và chấp thủ, sự an trú của tâm, sự thiên chấp và tùy miên  hãy đoạn trừ chúng. ",
  "sn23.10:1.6": "Như vậy thọ ấy sẽ được đoạn trừ, bị cắt đứt tận gốc, không còn điều kiện để tồn tại, không còn sanh khởi trong tương lai. ",
  "sn23.10:1.7": "Đối với tưởng… ",
  "sn23.10:1.8": "đối với các hành, những ham muốn, tham ái, hỷ lạc, khát ái, những sự tiếp cận và chấp thủ, sự an trú của tâm, sự thiên chấp và tùy miên  hãy đoạn trừ chúng. ",
  "sn23.10:1.9": "Như vậy các hành ấy sẽ được đoạn trừ, bị cắt đứt tận gốc, không còn điều kiện để tồn tại, không còn sanh khởi trong tương lai. ",
  "sn23.10:1.10": "Đối với thức, những ham muốn, tham ái, hỷ lạc, khát ái, những sự tiếp cận và chấp thủ, sự an trú của tâm, sự thiên chấp và tùy miên  hãy đoạn trừ chúng. ",
  "sn23.10:1.11": "Như vậy thức ấy sẽ được đoạn trừ, bị cắt đứt tận gốc, không còn điều kiện để tồn tại, không còn sanh khởi trong tương lai.' ",
  "sn23.10:1.12": "Thứ mười. ",
  "sn23.10:1.13": "Phẩm Ma Vương Thứ Nhất của Tương Ưng Rādha. ",
  "sn23.10:2.0": "Tóm tắt phẩm ",
  "sn23.10:2.1": "Ma Vương, chúng sanh, sợi dây dẫn đến tái sanh, ",
  "sn23.10:2.2": "cần liễu tri, hai kinh về Sa-môn; ",
  "sn23.10:2.3": "Dự Lưu, A-la-hán, ",
  "sn23.10:2.4": "và hai kinh về dục tham. ",
  "sn23.11:0.1": "Tương Ưng Bộ 23.11 ",
  "sn23.11:0.2": "2. Phẩm Ma Vương Thứ Hai ",
  "sn23.11:0.3": "Kinh Ma Vương ",
  "sn23.11:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.11:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.11:1.3": "''Ma Vương, Ma Vương', bạch Thế Tôn, người ta thường nói. '",
  "sn23.11:1.4": "Bạch Thế Tôn, thế nào là Ma Vương?' ",
  "sn23.11:1.5": "'Này Rādha, sắc là Ma Vương, thọ là Ma Vương, tưởng là Ma Vương, các hành là Ma Vương, thức là Ma Vương. '",
  "sn23.11:1.6": "Quán như vậy, này Rādha, vị Thánh đệ tử có học thức yếm ly đối với sắc, yếm ly đối với thọ, yếm ly đối với tưởng, yếm ly đối với các hành, yếm ly đối với thức. ",
  "sn23.11:1.7": "Do yếm ly, vị ấy ly tham; do ly tham, vị ấy được giải thoát. Khi được giải thoát, có trí biết rằng 'Ta đã được giải thoát.' ",
  "sn23.11:1.8": "Vị ấy biết rõ: 'Sanh đã tận, phạm hạnh đã sống, những việc cần làm đã làm, không còn trở lại trạng thái này nữa.'' ",
  "sn23.11:1.9": "Thứ nhất. ",
  "sn23.12:0.1": "Tương Ưng Bộ 23.12 ",
  "sn23.12:0.2": "2. Phẩm Ma Vương Thứ Hai ",
  "sn23.12:0.3": "Kinh Pháp Ma Vương ",
  "sn23.12:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.12:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.12:1.3": "''Pháp Ma Vương, pháp Ma Vương', bạch Thế Tôn, người ta thường nói. '",
  "sn23.12:1.4": "Bạch Thế Tôn, thế nào là pháp Ma Vương?' ",
  "sn23.12:1.5": "'Này Rādha, sắc là pháp Ma Vương, thọ là pháp Ma Vương, tưởng là pháp Ma Vương, các hành là pháp Ma Vương, thức là pháp Ma Vương. '",
  "sn23.12:1.6": "Quán như vậy … ",
  "sn23.12:1.7": "không còn trở lại trạng thái này nữa.' ",
  "sn23.12:1.8": "Thứ hai. ",
  "sn23.13:0.1": "Tương Ưng Bộ 23.13 ",
  "sn23.13:0.2": "2. Phẩm Ma Vương Thứ Hai ",
  "sn23.13:0.3": "Kinh Vô Thường ",
  "sn23.13:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.13:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.13:1.3": "''Vô thường, vô thường', bạch Thế Tôn, người ta thường nói. '",
  "sn23.13:1.4": "Bạch Thế Tôn, thế nào là vô thường?' ",
  "sn23.13:1.5": "'Này Rādha, sắc là vô thường, thọ là vô thường, tưởng là vô thường, các hành là vô thường, thức là vô thường. '",
  "sn23.13:1.6": "Quán như vậy … ",
  "sn23.13:1.7": "không còn trở lại trạng thái này nữa.' ",
  "sn23.13:1.8": "Thứ ba. ",
  "sn23.14:0.1": "Tương Ưng Bộ 23.14 ",
  "sn23.14:0.2": "2. Phẩm Ma Vương Thứ Hai ",
  "sn23.14:0.3": "Kinh Pháp Vô Thường ",
  "sn23.14:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.14:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.14:1.3": "''Pháp vô thường, pháp vô thường', bạch Thế Tôn, người ta thường nói. '",
  "sn23.14:1.4": "Bạch Thế Tôn, thế nào là pháp vô thường?' ",
  "sn23.14:1.5": "'Này Rādha, sắc là pháp vô thường, thọ là pháp vô thường, tưởng là pháp vô thường, các hành là pháp vô thường, thức là pháp vô thường. '",
  "sn23.14:1.6": "Quán như vậy … ",
  "sn23.14:1.7": "không còn trở lại trạng thái này nữa.' ",
  "sn23.14:1.8": "Thứ tư. ",
  "sn23.15:0.1": "Tương Ưng Bộ 23.15 ",
  "sn23.15:0.2": "2. Phẩm Ma Vương Thứ Hai ",
  "sn23.15:0.3": "Kinh Khổ ",
  "sn23.15:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.15:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.15:1.3": "''Khổ, khổ', bạch Thế Tôn, người ta thường nói. '",
  "sn23.15:1.4": "Bạch Thế Tôn, thế nào là khổ?' ",
  "sn23.15:1.5": "'Này Rādha, sắc là khổ, thọ là khổ, tưởng là khổ, các hành là khổ, thức là khổ. '",
  "sn23.15:1.6": "Quán như vậy … ",
  "sn23.15:1.7": "không còn trở lại trạng thái này nữa.' ",
  "sn23.15:1.8": "Thứ năm. ",
  "sn23.16:0.1": "Tương Ưng Bộ 23.16 ",
  "sn23.16:0.2": "2. Phẩm Ma Vương Thứ Hai ",
  "sn23.16:0.3": "Kinh Pháp Khổ ",
  "sn23.16:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.16:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.16:1.3": "''Pháp khổ, pháp khổ', bạch Thế Tôn, người ta thường nói. '",
  "sn23.16:1.4": "Bạch Thế Tôn, thế nào là pháp khổ?' ",
  "sn23.16:1.5": "'Này Rādha, sắc là pháp khổ, thọ là pháp khổ, tưởng là pháp khổ, các hành là pháp khổ, thức là pháp khổ. '",
  "sn23.16:1.6": "Quán như vậy … ",
  "sn23.16:1.7": "không còn trở lại trạng thái này nữa.' ",
  "sn23.16:1.8": "Thứ sáu. ",
  "sn23.17:0.1": "Tương Ưng Bộ 23.17 ",
  "sn23.17:0.2": "2. Phẩm Ma Vương Thứ Hai ",
  "sn23.17:0.3": "Kinh Vô Ngã ",
  "sn23.17:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.17:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.17:1.3": "''Vô ngã, vô ngã', bạch Thế Tôn, người ta thường nói. '",
  "sn23.17:1.4": "Bạch Thế Tôn, thế nào là vô ngã?' ",
  "sn23.17:1.5": "'Này Rādha, sắc là vô ngã, thọ là vô ngã, tưởng là vô ngã, các hành là vô ngã, thức là vô ngã. '",
  "sn23.17:1.6": "Quán như vậy … ",
  "sn23.17:1.7": "không còn trở lại trạng thái này nữa.' ",
  "sn23.17:1.8": "Thứ bảy. ",
  "sn23.18:0.1": "Tương Ưng Bộ 23.18 ",
  "sn23.18:0.2": "2. Phẩm Ma Vương Thứ Hai ",
  "sn23.18:0.3": "Kinh Pháp Vô Ngã ",
  "sn23.18:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.18:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.18:1.3": "''Pháp vô ngã, pháp vô ngã', bạch Thế Tôn, người ta thường nói. '",
  "sn23.18:1.4": "Bạch Thế Tôn, thế nào là pháp vô ngã?' ",
  "sn23.18:1.5": "'Này Rādha, sắc là pháp vô ngã, thọ là pháp vô ngã, tưởng là pháp vô ngã, các hành là pháp vô ngã, thức là pháp vô ngã. '",
  "sn23.18:1.6": "Quán như vậy … ",
  "sn23.18:1.7": "không còn trở lại trạng thái này nữa.' ",
  "sn23.18:1.8": "Thứ tám. ",
  "sn23.19:0.1": "Tương Ưng Bộ 23.19 ",
  "sn23.19:0.2": "2. Phẩm Ma Vương Thứ Hai ",
  "sn23.19:0.3": "Kinh Pháp Đoạn Tận ",
  "sn23.19:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.19:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.19:1.3": "''Pháp đoạn tận, pháp đoạn tận', bạch Thế Tôn, người ta thường nói. '",
  "sn23.19:1.4": "Bạch Thế Tôn, thế nào là pháp đoạn tận?' ",
  "sn23.19:1.5": "'Này Rādha, sắc là pháp đoạn tận, thọ là pháp đoạn tận, tưởng là pháp đoạn tận, các hành là pháp đoạn tận, thức là pháp đoạn tận. '",
  "sn23.19:1.6": "Quán như vậy … ",
  "sn23.19:1.7": "không còn trở lại trạng thái này nữa.' ",
  "sn23.19:1.8": "Thứ chín. ",
  "sn23.20:0.1": "Tương Ưng Bộ 23.20 ",
  "sn23.20:0.2": "2. Phẩm Ma Vương Thứ Hai ",
  "sn23.20:0.3": "Kinh Pháp Hoại Diệt ",
  "sn23.20:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.20:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.20:1.3": "''Pháp hoại diệt, pháp hoại diệt', bạch Thế Tôn, người ta thường nói. '",
  "sn23.20:1.4": "Bạch Thế Tôn, thế nào là pháp hoại diệt?' ",
  "sn23.20:1.5": "'Này Rādha, sắc là pháp hoại diệt, thọ là pháp hoại diệt, tưởng là pháp hoại diệt, các hành là pháp hoại diệt, thức là pháp hoại diệt. '",
  "sn23.20:1.6": "Quán như vậy … ",
  "sn23.20:1.7": "không còn trở lại trạng thái này nữa.' ",
  "sn23.20:1.8": "Thứ mười. ",
  "sn23.21:0.1": "Tương Ưng Bộ 23.21 ",
  "sn23.21:0.2": "2. Phẩm Ma Vương Thứ Hai ",
  "sn23.21:0.3": "Kinh Pháp Sanh Khởi ",
  "sn23.21:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.21:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.21:1.3": "''Pháp sanh khởi, pháp sanh khởi', bạch Thế Tôn, người ta thường nói. '",
  "sn23.21:1.4": "Bạch Thế Tôn, thế nào là pháp sanh khởi?' ",
  "sn23.21:1.5": "'Này Rādha, sắc là pháp sanh khởi, thọ là pháp sanh khởi, tưởng là pháp sanh khởi, các hành là pháp sanh khởi, thức là pháp sanh khởi. '",
  "sn23.21:1.6": "Quán như vậy … ",
  "sn23.21:1.7": "không còn trở lại trạng thái này nữa.' ",
  "sn23.21:1.8": "Thứ mười một. ",
  "sn23.22:0.1": "Tương Ưng Bộ 23.22 ",
  "sn23.22:0.2": "2. Phẩm Ma Vương Thứ Hai ",
  "sn23.22:0.3": "Kinh Pháp Diệt Tận ",
  "sn23.22:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.22:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.22:1.3": "''Pháp diệt tận, pháp diệt tận', bạch Thế Tôn, người ta thường nói. '",
  "sn23.22:1.4": "Bạch Thế Tôn, thế nào là pháp diệt tận?' ",
  "sn23.22:1.5": "'Này Rādha, sắc là pháp diệt tận, thọ là pháp diệt tận, tưởng là pháp diệt tận, các hành là pháp diệt tận, thức là pháp diệt tận. '",
  "sn23.22:1.6": "Quán như vậy … ",
  "sn23.22:1.7": "không còn trở lại trạng thái này nữa.' ",
  "sn23.22:1.8": "Thứ mười hai. ",
  "sn23.22:1.9": "Phẩm Ma Vương Thứ Hai. ",
  "sn23.22:2.0": "Tóm tắt phẩm ",
  "sn23.22:2.1": "Ma Vương và pháp Ma Vương, ",
  "sn23.22:2.2": "Tiếp theo hai kinh về vô thường; ",
  "sn23.22:2.3": "Hai kinh về khổ, ",
  "sn23.22:2.4": "Cũng vậy hai kinh về vô ngã; ",
  "sn23.22:2.5": "Đoạn tận, hoại diệt, sanh khởi, ",
  "sn23.22:2.6": "Và pháp diệt tận  mười hai kinh. ",
  "sn23.23:0.1": "Tương Ưng Bộ 23.23–33 ",
  "sn23.23:0.2": "3. Phẩm Thỉnh Cầu ",
  "sn23.23:0.3": "Mười Một Kinh Về Ma Vương Và Các Pháp ",
  "sn23.23:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.23:1.2": "Ngồi xuống một bên, Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.23:1.3": "'Lành thay, bạch Thế Tôn, xin Thế Tôn hãy thuyết pháp vắn tắt cho con, để con sau khi nghe pháp của Thế Tôn, có thể sống một mình, xa lánh, không phóng dật, nhiệt tâm, tinh cần.' ",
  "sn23.23:2.1": "'Này Rādha, những gì là Ma Vương  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó. '",
  "sn23.23:2.2": "Và này Rādha, thế nào là Ma Vương? ",
  "sn23.23:2.3": "Này Rādha, sắc là Ma Vương  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó. ",
  "sn23.23:2.4": "Thọ là Ma Vương  hãy đoạn trừ ham muốn ở đó … ",
  "sn23.23:2.5": "tưởng là Ma Vương  hãy đoạn trừ ham muốn ở đó … ",
  "sn23.23:2.6": "các hành là Ma Vương  hãy đoạn trừ ham muốn ở đó … ",
  "sn23.23:2.7": "thức là Ma Vương  hãy đoạn trừ ham muốn ở đó … ",
  "sn23.23:2.8": "những gì là Ma Vương  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó.' ",
  "sn23.24:1.1": "'Này Rādha, những gì là pháp Ma Vương  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó … '",
  "sn23.25:1.1": "'Này Rādha, những gì là vô thường … '",
  "sn23.26:1.1": "'Này Rādha, những gì là pháp vô thường … '",
  "sn23.27:1.1": "'Này Rādha, những gì là khổ … '",
  "sn23.28:1.1": "'Này Rādha, những gì là pháp khổ … '",
  "sn23.29:1.1": "'Này Rādha, những gì là vô ngã … '",
  "sn23.30:1.1": "'Này Rādha, những gì là pháp vô ngã … '",
  "sn23.31:1.1": "'Này Rādha, những gì là pháp đoạn tận … '",
  "sn23.32:1.1": "'Này Rādha, những gì là pháp hoại diệt … '",
  "sn23.33:1.1": "'Này Rādha, những gì là pháp sanh khởi  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó … '",
  "sn23.34:0.1": "Tương Ưng Bộ 23.34 ",
  "sn23.34:0.2": "3. Phẩm Thỉnh Cầu ",
  "sn23.34:0.3": "Kinh Pháp Diệt Tận ",
  "sn23.34:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.34:1.2": "Tôn giả Rādha bạch Thế Tôn: ",
  "sn23.34:1.3": "'Lành thay, bạch Thế Tôn, xin Thế Tôn hãy thuyết pháp vắn tắt cho con, để con sau khi nghe pháp của Thế Tôn, có thể sống một mình, xa lánh, không phóng dật, nhiệt tâm, tinh cần.' ",
  "sn23.34:2.1": "'Này Rādha, những gì là pháp diệt tận  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó. '",
  "sn23.34:2.2": "Và này Rādha, thế nào là pháp diệt tận? ",
  "sn23.34:2.3": "Này Rādha, sắc là pháp diệt tận  hãy đoạn trừ ham muốn ở đó … ",
  "sn23.34:2.4": "thọ là pháp diệt tận  hãy đoạn trừ ham muốn ở đó … ",
  "sn23.34:2.5": "tưởng là pháp diệt tận  hãy đoạn trừ ham muốn ở đó … ",
  "sn23.34:2.6": "các hành là pháp diệt tận  hãy đoạn trừ ham muốn ở đó … ",
  "sn23.34:2.7": "thức là pháp diệt tận  hãy đoạn trừ ham muốn ở đó … ",
  "sn23.34:2.8": "những gì là pháp diệt tận  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó.' ",
  "sn23.34:2.9": "Phẩm Thỉnh Cầu, thứ ba. ",
  "sn23.34:3.0": "Tóm tắt phẩm ",
  "sn23.34:3.1": "Ma Vương và pháp Ma Vương, ",
  "sn23.34:3.2": "Tiếp theo hai kinh về vô thường; ",
  "sn23.34:3.3": "Hai kinh về khổ, ",
  "sn23.34:3.4": "Cũng vậy hai kinh về vô ngã; ",
  "sn23.34:3.5": "Đoạn tận, hoại diệt, sanh khởi, ",
  "sn23.34:3.6": "Và pháp diệt tận  mười hai kinh. ",
  "sn23.35:0.1": "Tương Ưng Bộ 23.35–45 ",
  "sn23.35:0.2": "4. Phẩm Ngồi Gần ",
  "sn23.35:0.3": "Mười Một Kinh Về Ma Vương Và Các Pháp ",
  "sn23.35:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.35:1.2": "Rồi Thế Tôn nói với Tôn giả Rādha đang ngồi một bên: ",
  "sn23.35:1.3": "'Này Rādha, những gì là Ma Vương  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó. '",
  "sn23.35:1.4": "Và này Rādha, thế nào là Ma Vương? ",
  "sn23.35:1.5": "Này Rādha, sắc là Ma Vương  hãy đoạn trừ ham muốn ở đó … ",
  "sn23.35:1.6": "thức là Ma Vương  hãy đoạn trừ ham muốn ở đó … ",
  "sn23.35:1.7": "những gì là Ma Vương  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó.' ",
  "sn23.36:1.1": "'Này Rādha, những gì là pháp Ma Vương  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó … '",
  "sn23.37:1.1": "'Này Rādha, những gì là vô thường … '",
  "sn23.38:1.1": "'Này Rādha, những gì là pháp vô thường … '",
  "sn23.39:1.1": "'Này Rādha, những gì là khổ … '",
  "sn23.40:1.1": "'Này Rādha, những gì là pháp khổ … '",
  "sn23.41:1.1": "'Này Rādha, những gì là vô ngã … '",
  "sn23.42:1.1": "'Này Rādha, những gì là pháp vô ngã … '",
  "sn23.43:1.1": "'Này Rādha, những gì là pháp đoạn tận … '",
  "sn23.44:1.1": "'Này Rādha, những gì là pháp hoại diệt … '",
  "sn23.45:1.1": "'Này Rādha, những gì là pháp sanh khởi  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó … '",
  "sn23.46:0.1": "Tương Ưng Bộ 23.46 ",
  "sn23.46:0.2": "4. Phẩm Ngồi Gần ",
  "sn23.46:0.3": "Kinh Pháp Diệt Tận ",
  "sn23.46:1.1": "Nhân duyên ở Sāvatthi. ",
  "sn23.46:1.2": "Rồi Thế Tôn nói với Tôn giả Rādha đang ngồi một bên: ",
  "sn23.46:1.3": "'Này Rādha, những gì là pháp diệt tận  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó. '",
  "sn23.46:1.4": "Và này Rādha, thế nào là pháp diệt tận? ",
  "sn23.46:1.5": "Này Rādha, sắc là pháp diệt tận  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó. ",
  "sn23.46:1.6": "Thọ … ",
  "sn23.46:1.7": "tưởng … ",
  "sn23.46:1.8": "các hành … ",
  "sn23.46:1.9": "thức là pháp diệt tận  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó. ",
  "sn23.46:1.10": "Những gì là pháp diệt tận  hãy đoạn trừ ham muốn ở đó, hãy đoạn trừ tham ái ở đó, hãy đoạn trừ dục tham ở đó.' ",
  "sn23.46:1.11": "Phẩm Ngồi Gần, thứ tư. ",
  "sn23.46:2.0": "Tóm tắt phẩm ",
  "sn23.46:2.1": "Ma Vương và pháp Ma Vương, ",
  "sn23.46:2.2": "Tiếp theo hai kinh về vô thường; ",
  "sn23.46:2.3": "Hai kinh về khổ, ",
  "sn23.46:2.4": "Cũng vậy hai kinh về vô ngã; ",
  "sn23.46:2.5": "Đoạn tận, hoại diệt, sanh khởi, ",
  "sn23.46:2.6": "Và pháp diệt tận  mười hai kinh. ",
  "sn23.46:2.7": "Tương Ưng Rādha đã hoàn tất. "
}
window.BILARA["sn23_v1"]["vi"]["sn23_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
