window.BILARA = window.BILARA || {};
window.BILARA["sn25_v1"] = window.BILARA["sn25_v1"] || {};
window.BILARA["sn25_v1"]["vi"] = {
  "sn25.1:0.1": "Tương Ưng Bộ 25.1 ",
  "sn25.1:0.2": "1. Phẩm Mắt ",
  "sn25.1:0.3": "Kinh Mắt ",
  "sn25.1:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn25.1:1.2": "'Này các Tỳ Kheo, mắt là vô thường, biến đổi, trở thành khác đi; '",
  "sn25.1:1.3": "tai là vô thường, biến đổi, trở thành khác đi; ",
  "sn25.1:1.4": "mũi là vô thường, biến đổi, trở thành khác đi; ",
  "sn25.1:1.5": "lưỡi là vô thường, biến đổi, trở thành khác đi; ",
  "sn25.1:1.6": "thân là vô thường, biến đổi, trở thành khác đi; ",
  "sn25.1:1.7": "ý là vô thường, biến đổi, trở thành khác đi. ",
  "sn25.1:1.8": "Này các Tỳ Kheo, ai tin tưởng và quyết tâm với các pháp này như vậyngười ấy được gọi là tùy tín hành, đã bước vào chánh tánh quyết định, đã bước vào địa vị bậc chân nhân, đã vượt qua địa vị phàm phu; ",
  "sn25.1:1.9": "không thể làm nghiệp mà do làm nghiệp ấy sẽ tái sinh vào địa ngục, loài súc sinh, hay cõi ngạ quỷ; ",
  "sn25.1:1.10": "không thể mạng chung trước khi chứng đắc quả Nhập Lưu. ",
  "sn25.1:2.1": "Này các Tỳ Kheo, ai quán xét các pháp này một cách vừa phải bằng trí tuệ, người ấy được gọi là: 'tùy pháp hành, đã bước vào chánh tánh quyết định, đã bước vào địa vị bậc chân nhân, đã vượt qua địa vị phàm phu; ",
  "sn25.1:2.2": "không thể làm nghiệp mà do làm nghiệp ấy sẽ tái sinh vào địa ngục, loài súc sinh, hay cõi ngạ quỷ; ",
  "sn25.1:2.3": "không thể mạng chung trước khi chứng đắc quả Nhập Lưu'. ",
  "sn25.1:2.4": "Này các Tỳ Kheo, ai hiểu rõ và thấy rõ các pháp này như vậy, người ấy được gọi là: 'bậc Nhập Lưu, không còn rơi vào khổ cảnh, quyết định hướng đến giác ngộ viên mãn'.' ",
  "sn25.1:2.5": "Thứ nhất. ",
  "sn25.2:0.1": "Tương Ưng Bộ 25.2 ",
  "sn25.2:0.2": "1. Phẩm Mắt ",
  "sn25.2:0.3": "Kinh Sắc ",
  "sn25.2:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn25.2:1.2": "'Này các Tỳ Kheo, các sắc là vô thường, biến đổi, trở thành khác đi; '",
  "sn25.2:1.3": "các âm thanh là vô thường, biến đổi, trở thành khác đi; ",
  "sn25.2:1.4": "các mùi hương là vô thường, biến đổi, trở thành khác đi; ",
  "sn25.2:1.5": "các vị là vô thường, biến đổi, trở thành khác đi; ",
  "sn25.2:1.6": "các xúc chạm là vô thường, biến đổi, trở thành khác đi; ",
  "sn25.2:1.7": "các pháp là vô thường, biến đổi, trở thành khác đi. ",
  "sn25.2:1.8": "Này các Tỳ Kheo, ai tin tưởng và quyết tâm với các pháp này như vậy, người ấy được gọi là tùy tín hành, đã bước vào chánh tánh quyết định, đã bước vào địa vị bậc chân nhân, đã vượt qua địa vị phàm phu; ",
  "sn25.2:1.9": "không thể làm nghiệp mà do làm nghiệp ấy sẽ tái sinh vào địa ngục, loài súc sinh, hay cõi ngạ quỷ; ",
  "sn25.2:1.10": "không thể mạng chung trước khi chứng đắc quả Nhập Lưu. ",
  "sn25.2:2.1": "Này các Tỳ Kheo, ai quán xét các pháp này một cách vừa phải bằng trí tuệ, người ấy được gọi là: 'tùy pháp hành, đã bước vào chánh tánh quyết định, đã bước vào địa vị bậc chân nhân, đã vượt qua địa vị phàm phu; ",
  "sn25.2:2.2": "không thể làm nghiệp mà do làm nghiệp ấy sẽ tái sinh vào địa ngục, loài súc sinh, hay cõi ngạ quỷ; ",
  "sn25.2:2.3": "không thể mạng chung trước khi chứng đắc quả Nhập Lưu'. ",
  "sn25.2:2.4": "Này các Tỳ Kheo, ai hiểu rõ và thấy rõ các pháp này như vậy, người ấy được gọi là: ",
  "sn25.2:2.5": "'bậc Nhập Lưu, không còn rơi vào khổ cảnh, quyết định hướng đến giác ngộ viên mãn'.' '",
  "sn25.2:2.6": "Thứ hai. ",
  "sn25.3:0.1": "Tương Ưng Bộ 25.3 ",
  "sn25.3:0.2": "1. Phẩm Mắt ",
  "sn25.3:0.3": "Kinh Thức ",
  "sn25.3:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn25.3:1.2": "'Này các Tỳ Kheo, nhãn thức là vô thường, biến đổi, trở thành khác đi; '",
  "sn25.3:1.3": "nhĩ thức … ",
  "sn25.3:1.4": "tỷ thức … ",
  "sn25.3:1.5": "thiệt thức … ",
  "sn25.3:1.6": "thân thức … ",
  "sn25.3:1.7": "ý thức là vô thường, biến đổi, trở thành khác đi. ",
  "sn25.3:1.8": "Này các Tỳ Kheo, …pe… ",
  "sn25.3:1.9": "hướng đến giác ngộ viên mãn.' ",
  "sn25.3:1.10": "Thứ ba. ",
  "sn25.4:0.1": "Tương Ưng Bộ 25.4 ",
  "sn25.4:0.2": "1. Phẩm Mắt ",
  "sn25.4:0.3": "Kinh Xúc ",
  "sn25.4:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn25.4:1.2": "'Này các Tỳ Kheo, nhãn xúc là vô thường, biến đổi, trở thành khác đi; '",
  "sn25.4:1.3": "nhĩ xúc … ",
  "sn25.4:1.4": "tỷ xúc … ",
  "sn25.4:1.5": "thiệt xúc … ",
  "sn25.4:1.6": "thân xúc … ",
  "sn25.4:1.7": "ý xúc là vô thường, biến đổi, trở thành khác đi. ",
  "sn25.4:1.8": "Này các Tỳ Kheo, ai tin tưởng và quyết tâm với các pháp này như vậy, người ấy được gọi là 'tùy tín hành …pe… ",
  "sn25.4:1.9": "hướng đến giác ngộ viên mãn'.' ",
  "sn25.4:1.10": "Thứ tư. ",
  "sn25.5:0.1": "Tương Ưng Bộ 25.5 ",
  "sn25.5:0.2": "1. Phẩm Mắt ",
  "sn25.5:0.3": "Kinh Thọ Do Xúc Sinh ",
  "sn25.5:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn25.5:1.2": "'Này các Tỳ Kheo, thọ do nhãn xúc sinh là vô thường, biến đổi, trở thành khác đi; '",
  "sn25.5:1.3": "thọ do nhĩ xúc sinh …pe… ",
  "sn25.5:1.4": "thọ do tỷ xúc sinh …pe… ",
  "sn25.5:1.5": "thọ do thiệt xúc sinh …pe… ",
  "sn25.5:1.6": "thọ do thân xúc sinh …pe… ",
  "sn25.5:1.7": "thọ do ý xúc sinh là vô thường, biến đổi, trở thành khác đi. ",
  "sn25.5:1.8": "Này các Tỳ Kheo, ai tin tưởng và quyết tâm với các pháp này như vậy, người ấy được gọi là 'tùy tín hành …pe… ",
  "sn25.5:1.9": "hướng đến giác ngộ viên mãn'.' ",
  "sn25.5:1.10": "Thứ năm. ",
  "sn25.6:0.1": "Tương Ưng Bộ 25.6 ",
  "sn25.6:0.2": "1. Phẩm Mắt ",
  "sn25.6:0.3": "Kinh Tưởng Về Sắc ",
  "sn25.6:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn25.6:1.2": "'Này các Tỳ Kheo, tưởng về sắc là vô thường, biến đổi, trở thành khác đi; '",
  "sn25.6:1.3": "tưởng về tiếng … ",
  "sn25.6:1.4": "tưởng về mùi … ",
  "sn25.6:1.5": "tưởng về vị … ",
  "sn25.6:1.6": "tưởng về xúc chạm … ",
  "sn25.6:1.7": "tưởng về pháp là vô thường, biến đổi, trở thành khác đi. ",
  "sn25.6:1.8": "Này các Tỳ Kheo, ai tin tưởng và quyết tâm với các pháp này như vậy, người ấy được gọi là 'tùy tín hành …pe… ",
  "sn25.6:1.9": "hướng đến giác ngộ viên mãn'.' ",
  "sn25.6:1.10": "Thứ sáu. ",
  "sn25.7:0.1": "Tương Ưng Bộ 25.7 ",
  "sn25.7:0.2": "1. Phẩm Mắt ",
  "sn25.7:0.3": "Kinh Tư Về Sắc ",
  "sn25.7:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn25.7:1.2": "'Này các Tỳ Kheo, tư về sắc là vô thường, biến đổi, trở thành khác đi; '",
  "sn25.7:1.3": "tư về tiếng … ",
  "sn25.7:1.4": "tư về mùi … ",
  "sn25.7:1.5": "tư về vị … ",
  "sn25.7:1.6": "tư về xúc chạm … ",
  "sn25.7:1.7": "tư về pháp là vô thường, biến đổi, trở thành khác đi. ",
  "sn25.7:1.8": "Này các Tỳ Kheo, ai tin tưởng và quyết tâm với các pháp này như vậy, người ấy được gọi là 'tùy tín hành …pe… ",
  "sn25.7:1.9": "hướng đến giác ngộ viên mãn'.' ",
  "sn25.7:1.10": "Thứ bảy. ",
  "sn25.8:0.1": "Tương Ưng Bộ 25.8 ",
  "sn25.8:0.2": "1. Phẩm Mắt ",
  "sn25.8:0.3": "Kinh Ái Về Sắc ",
  "sn25.8:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn25.8:1.2": "'Này các Tỳ Kheo, ái về sắc là vô thường, biến đổi, trở thành khác đi; '",
  "sn25.8:1.3": "ái về tiếng … ",
  "sn25.8:1.4": "ái về mùi … ",
  "sn25.8:1.5": "ái về vị … ",
  "sn25.8:1.6": "ái về xúc chạm … ",
  "sn25.8:1.7": "ái về pháp là vô thường, biến đổi, trở thành khác đi. ",
  "sn25.8:1.8": "Này các Tỳ Kheo, ai tin tưởng và quyết tâm với các pháp này như vậy, người ấy được gọi là 'tùy tín hành …pe… ",
  "sn25.8:1.9": "hướng đến giác ngộ viên mãn'.' ",
  "sn25.8:1.10": "Thứ tám. ",
  "sn25.9:0.1": "Tương Ưng Bộ 25.9 ",
  "sn25.9:0.2": "1. Phẩm Mắt ",
  "sn25.9:0.3": "Kinh Địa Đại ",
  "sn25.9:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn25.9:1.2": "'Này các Tỳ Kheo, địa đại là vô thường, biến đổi, trở thành khác đi; '",
  "sn25.9:1.3": "thủy đại … ",
  "sn25.9:1.4": "hỏa đại … ",
  "sn25.9:1.5": "phong đại … ",
  "sn25.9:1.6": "không đại … ",
  "sn25.9:1.7": "thức đại là vô thường, biến đổi, trở thành khác đi. ",
  "sn25.9:1.8": "Này các Tỳ Kheo, ai tin tưởng và quyết tâm với các pháp này như vậy, người ấy được gọi là 'tùy tín hành …pe… ",
  "sn25.9:1.9": "hướng đến giác ngộ viên mãn'.' ",
  "sn25.9:1.10": "Thứ chín. ",
  "sn25.10:0.1": "Tương Ưng Bộ 25.10 ",
  "sn25.10:0.2": "1. Phẩm Mắt ",
  "sn25.10:0.3": "Kinh Uẩn ",
  "sn25.10:1.1": "Nhân duyên tại Sāvatthī. ",
  "sn25.10:1.2": "'Này các Tỳ Kheo, sắc là vô thường, biến đổi, trở thành khác đi; '",
  "sn25.10:1.3": "thọ là vô thường, biến đổi, trở thành khác đi; ",
  "sn25.10:1.4": "tưởng … ",
  "sn25.10:1.5": "các hành là vô thường, biến đổi, trở thành khác đi; ",
  "sn25.10:1.6": "thức là vô thường, biến đổi, trở thành khác đi. ",
  "sn25.10:1.7": "Này các Tỳ Kheo, ai tin tưởng và quyết tâm với các pháp này như vậy, người ấy được gọi là tùy tín hành, đã bước vào chánh tánh quyết định, đã bước vào địa vị bậc chân nhân, đã vượt qua địa vị phàm phu; ",
  "sn25.10:1.8": "không thể làm nghiệp mà do làm nghiệp ấy sẽ tái sinh vào địa ngục, loài súc sinh, hay cõi ngạ quỷ; ",
  "sn25.10:1.9": "không thể mạng chung trước khi chứng đắc quả Nhập Lưu. ",
  "sn25.10:2.1": "Này các Tỳ Kheo, ai quán xét các pháp này một cách vừa phải bằng trí tuệ, người ấy được gọi là: 'tùy pháp hành, đã bước vào chánh tánh quyết định, đã bước vào địa vị bậc chân nhân, đã vượt qua địa vị phàm phu; ",
  "sn25.10:2.2": "không thể làm nghiệp mà do làm nghiệp ấy sẽ tái sinh vào địa ngục, loài súc sinh, hay cõi ngạ quỷ; ",
  "sn25.10:2.3": "không thể mạng chung trước khi chứng đắc quả Nhập Lưu'. ",
  "sn25.10:2.4": "Này các Tỳ Kheo, ai hiểu rõ và thấy rõ các pháp này như vậy, người ấy được gọi là: ",
  "sn25.10:2.5": "'bậc Nhập Lưu, không còn rơi vào khổ cảnh, quyết định hướng đến giác ngộ viên mãn'.' '",
  "sn25.10:2.6": "Thứ mười. ",
  "sn25.10:2.7": "Phẩm Mắt, Thứ nhất. ",
  "sn25.10:3.0": "Tóm lược ",
  "sn25.10:3.1": "Mắt, sắc và thức, ",
  "sn25.10:3.2": "xúc và thọ; ",
  "sn25.10:3.3": "Tưởng, tư và ái, ",
  "sn25.10:3.4": "địa đại và uẩn, ấy là mười. ",
  "sn25.10:3.5": "Tương Ưng Nhập Lưu kết thúc. "
}
window.BILARA["sn25_v1"]["vi"]["sn25_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
