window.BILARA = window.BILARA || {};
window.BILARA["sn27_v1"] = window.BILARA["sn27_v1"] || {};
window.BILARA["sn27_v1"]["vi"] = {
  "sn27.1:0.1": "Tương Ưng Bộ 27.1 ",
  "sn27.1:0.2": "1. Phẩm Phiền Não ",
  "sn27.1:0.3": "Kinh Mắt ",
  "sn27.1:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn27.1:1.2": "'Này các Tỳ Kheo, dục tham nào đối với mắt, đó là cấu uế của tâm. '",
  "sn27.1:1.3": "Dục tham nào đối với tai, đó là cấu uế của tâm. ",
  "sn27.1:1.4": "Dục tham nào đối với mũi, đó là cấu uế của tâm. ",
  "sn27.1:1.5": "Dục tham nào đối với lưỡi, đó là cấu uế của tâm. ",
  "sn27.1:1.6": "Dục tham nào đối với thân, đó là cấu uế của tâm. ",
  "sn27.1:1.7": "Dục tham nào đối với ý, đó là cấu uế của tâm. ",
  "sn27.1:1.8": "Này các Tỳ Kheo, khi nào cấu uế của tâm Tỳ Kheo đã được đoạn trừ ở sáu xứ này, tâm vị ấy nghiêng về xuất ly. ",
  "sn27.1:1.9": "Tâm được tu tập bởi xuất ly thì trở nên nhu nhuyến, có thể chứng ngộ những pháp cần được chứng ngộ bằng thắng trí.' ",
  "sn27.1:1.10": "Thứ nhất. ",
  "sn27.2:0.1": "Tương Ưng Bộ 27.2 ",
  "sn27.2:0.2": "1. Phẩm Phiền Não ",
  "sn27.2:0.3": "Kinh Sắc ",
  "sn27.2:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn27.2:1.2": "'Này các Tỳ Kheo, dục tham nào đối với các sắc, đó là cấu uế của tâm. '",
  "sn27.2:1.3": "Dục tham nào đối với các tiếng… ",
  "sn27.2:1.4": "đối với các mùi… ",
  "sn27.2:1.5": "đối với các vị… ",
  "sn27.2:1.6": "đối với các xúc… ",
  "sn27.2:1.7": "dục tham nào đối với các pháp, đó là cấu uế của tâm. ",
  "sn27.2:1.8": "Này các Tỳ Kheo, khi nào cấu uế của tâm Tỳ Kheo đã được đoạn trừ ở sáu xứ này, tâm vị ấy nghiêng về xuất ly. ",
  "sn27.2:1.9": "Tâm được tu tập bởi xuất ly thì trở nên nhu nhuyến, có thể chứng ngộ những pháp cần được chứng ngộ bằng thắng trí.' ",
  "sn27.2:1.10": "Thứ hai. ",
  "sn27.3:0.1": "Tương Ưng Bộ 27.3 ",
  "sn27.3:0.2": "1. Phẩm Phiền Não ",
  "sn27.3:0.3": "Kinh Thức ",
  "sn27.3:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn27.3:1.2": "'Này các Tỳ Kheo, dục tham nào đối với nhãn thức, đó là cấu uế của tâm. '",
  "sn27.3:1.3": "Dục tham nào đối với nhĩ thức… ",
  "sn27.3:1.4": "đối với tỷ thức… ",
  "sn27.3:1.5": "đối với thiệt thức… ",
  "sn27.3:1.6": "đối với thân thức… ",
  "sn27.3:1.7": "dục tham nào đối với ý thức, đó là cấu uế của tâm. ",
  "sn27.3:1.8": "Này các Tỳ Kheo, khi nào cấu uế của tâm Tỳ Kheo đã được đoạn trừ ở sáu xứ này, tâm vị ấy nghiêng về xuất ly. ",
  "sn27.3:1.9": "Tâm được tu tập bởi xuất ly thì trở nên nhu nhuyến, có thể chứng ngộ những pháp cần được chứng ngộ bằng thắng trí.' ",
  "sn27.3:1.10": "Thứ ba. ",
  "sn27.4:0.1": "Tương Ưng Bộ 27.4 ",
  "sn27.4:0.2": "1. Phẩm Phiền Não ",
  "sn27.4:0.3": "Kinh Xúc ",
  "sn27.4:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn27.4:1.2": "'Này các Tỳ Kheo, dục tham nào đối với nhãn xúc, đó là cấu uế của tâm. '",
  "sn27.4:1.3": "Dục tham nào đối với nhĩ xúc… ",
  "sn27.4:1.4": "đối với tỷ xúc… ",
  "sn27.4:1.5": "đối với thiệt xúc… ",
  "sn27.4:1.6": "đối với thân xúc… ",
  "sn27.4:1.7": "dục tham nào đối với ý xúc, đó là cấu uế của tâm. ",
  "sn27.4:1.8": "Này các Tỳ Kheo, Tỳ Kheo …(như trên)… ",
  "sn27.4:1.9": "có thể chứng ngộ những pháp cần được chứng ngộ bằng thắng trí.' ",
  "sn27.4:1.10": "Thứ tư. ",
  "sn27.5:0.1": "Tương Ưng Bộ 27.5 ",
  "sn27.5:0.2": "1. Phẩm Phiền Não ",
  "sn27.5:0.3": "Kinh Thọ Do Xúc Sinh ",
  "sn27.5:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn27.5:1.2": "'Này các Tỳ Kheo, dục tham nào đối với cảm thọ do nhãn xúc sinh, đó là cấu uế của tâm. '",
  "sn27.5:1.3": "Dục tham nào đối với cảm thọ do nhĩ xúc sinh… ",
  "sn27.5:1.4": "đối với cảm thọ do tỷ xúc sinh… ",
  "sn27.5:1.5": "đối với cảm thọ do thiệt xúc sinh… ",
  "sn27.5:1.6": "đối với cảm thọ do thân xúc sinh… ",
  "sn27.5:1.7": "dục tham nào đối với cảm thọ do ý xúc sinh, đó là cấu uế của tâm. ",
  "sn27.5:1.8": "Này các Tỳ Kheo, Tỳ Kheo …(như trên)… ",
  "sn27.5:1.9": "có thể chứng ngộ những pháp cần được chứng ngộ bằng thắng trí.' ",
  "sn27.5:1.10": "Thứ năm. ",
  "sn27.6:0.1": "Tương Ưng Bộ 27.6 ",
  "sn27.6:0.2": "1. Phẩm Phiền Não ",
  "sn27.6:0.3": "Kinh Tưởng ",
  "sn27.6:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn27.6:1.2": "'Này các Tỳ Kheo, dục tham nào đối với tưởng về sắc, đó là cấu uế của tâm. '",
  "sn27.6:1.3": "Dục tham nào đối với tưởng về tiếng… ",
  "sn27.6:1.4": "đối với tưởng về mùi… ",
  "sn27.6:1.5": "đối với tưởng về vị… ",
  "sn27.6:1.6": "đối với tưởng về xúc… ",
  "sn27.6:1.7": "dục tham nào đối với tưởng về pháp, đó là cấu uế của tâm. ",
  "sn27.6:1.8": "Này các Tỳ Kheo, Tỳ Kheo …(như trên)… ",
  "sn27.6:1.9": "có thể chứng ngộ những pháp cần được chứng ngộ bằng thắng trí.' ",
  "sn27.6:1.10": "Thứ sáu. ",
  "sn27.7:0.1": "Tương Ưng Bộ 27.7 ",
  "sn27.7:0.2": "1. Phẩm Phiền Não ",
  "sn27.7:0.3": "Kinh Tư ",
  "sn27.7:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn27.7:1.2": "'Này các Tỳ Kheo, dục tham nào đối với tư về sắc, đó là cấu uế của tâm. '",
  "sn27.7:1.3": "Dục tham nào đối với tư về tiếng… ",
  "sn27.7:1.4": "đối với tư về mùi… ",
  "sn27.7:1.5": "đối với tư về vị… ",
  "sn27.7:1.6": "đối với tư về xúc… ",
  "sn27.7:1.7": "dục tham nào đối với tư về pháp, đó là cấu uế của tâm. ",
  "sn27.7:1.8": "Này các Tỳ Kheo, Tỳ Kheo …(như trên)… ",
  "sn27.7:1.9": "có thể chứng ngộ những pháp cần được chứng ngộ bằng thắng trí.' ",
  "sn27.7:1.10": "Thứ bảy. ",
  "sn27.8:0.1": "Tương Ưng Bộ 27.8 ",
  "sn27.8:0.2": "1. Phẩm Phiền Não ",
  "sn27.8:0.3": "Kinh Ái ",
  "sn27.8:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn27.8:1.2": "'Này các Tỳ Kheo, dục tham nào đối với ái về sắc, đó là cấu uế của tâm. '",
  "sn27.8:1.3": "Dục tham nào đối với ái về tiếng… ",
  "sn27.8:1.4": "đối với ái về mùi… ",
  "sn27.8:1.5": "đối với ái về vị… ",
  "sn27.8:1.6": "đối với ái về xúc… ",
  "sn27.8:1.7": "dục tham nào đối với ái về pháp, đó là cấu uế của tâm. ",
  "sn27.8:1.8": "Này các Tỳ Kheo, Tỳ Kheo …(như trên)… ",
  "sn27.8:1.9": "có thể chứng ngộ những pháp cần được chứng ngộ bằng thắng trí.' ",
  "sn27.8:1.10": "Thứ tám. ",
  "sn27.9:0.1": "Tương Ưng Bộ 27.9 ",
  "sn27.9:0.2": "1. Phẩm Phiền Não ",
  "sn27.9:0.3": "Kinh Giới ",
  "sn27.9:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn27.9:1.2": "'Này các Tỳ Kheo, dục tham nào đối với địa giới, đó là cấu uế của tâm. '",
  "sn27.9:1.3": "Dục tham nào đối với thủy giới… ",
  "sn27.9:1.4": "đối với hỏa giới… ",
  "sn27.9:1.5": "đối với phong giới… ",
  "sn27.9:1.6": "đối với không giới… ",
  "sn27.9:1.7": "dục tham nào đối với thức giới, đó là cấu uế của tâm. ",
  "sn27.9:1.8": "Này các Tỳ Kheo, khi nào cấu uế của tâm Tỳ Kheo đã được đoạn trừ ở sáu xứ này, tâm vị ấy nghiêng về xuất ly. ",
  "sn27.9:1.9": "Tâm được tu tập bởi xuất ly thì trở nên nhu nhuyến, có thể chứng ngộ những pháp cần được chứng ngộ bằng thắng trí.' ",
  "sn27.9:1.10": "Thứ chín. ",
  "sn27.10:0.1": "Tương Ưng Bộ 27.10 ",
  "sn27.10:0.2": "1. Phẩm Phiền Não ",
  "sn27.10:0.3": "Kinh Uẩn ",
  "sn27.10:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn27.10:1.2": "'Này các Tỳ Kheo, dục tham nào đối với sắc uẩn, đó là cấu uế của tâm …(cho đến)… dục tham nào đối với thức uẩn, đó là cấu uế của tâm. '",
  "sn27.10:1.3": "Này các Tỳ Kheo, khi nào cấu uế của tâm Tỳ Kheo đã được đoạn trừ ở năm xứ này, tâm vị ấy nghiêng về xuất ly. ",
  "sn27.10:1.4": "Tâm được tu tập bởi xuất ly thì trở nên nhu nhuyến, có thể chứng ngộ những pháp cần được chứng ngộ bằng thắng trí.' ",
  "sn27.10:1.5": "Thứ mười. ",
  "sn27.10:1.6": "Phẩm Phiền Não, thứ nhất. ",
  "sn27.10:2.0": "Tóm lược ",
  "sn27.10:2.1": "Mắt, sắc và thức, ",
  "sn27.10:2.2": "xúc và thọ; ",
  "sn27.10:2.3": "Tưởng, tư, ái, ",
  "sn27.10:2.4": "giới, uẩn  mười pháp ấy. ",
  "sn27.10:2.5": "Tương Ưng Phiền Não, hoàn tất. "
}
window.BILARA["sn27_v1"]["vi"]["sn27_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
