window.BILARA = window.BILARA || {};
window.BILARA["sn29_v1"] = window.BILARA["sn29_v1"] || {};
window.BILARA["sn29_v1"]["vi"] = {
  "sn29.1:0.1": "Kinh Tương Ưng 29.1 ",
  "sn29.1:0.2": "1. Phẩm Rồng ",
  "sn29.1:0.3": "Kinh Thuần Túy ",
  "sn29.1:1.1": "Duyên khởi tại Sāvatthi. ",
  "sn29.1:1.2": "'Này các Tỳ Kheo, có bốn loại thai sinh của loài rồng. '",
  "sn29.1:1.3": "Bốn loại đó là gì? ",
  "sn29.1:1.4": "Rồng noãn sinh, rồng thai sinh, rồng thấp sinh, rồng hóa sinh ",
  "sn29.1:1.5": "này các Tỳ Kheo, đây là bốn loại thai sinh của loài rồng'. ",
  "sn29.1:1.6": "Kinh thứ nhất. ",
  "sn29.2:0.1": "Kinh Tương Ưng 29.2 ",
  "sn29.2:0.2": "1. Phẩm Rồng ",
  "sn29.2:0.3": "Kinh Cao Quý Hơn ",
  "sn29.2:1.1": "Duyên khởi tại Sāvatthi. ",
  "sn29.2:1.2": "'Này các Tỳ Kheo, có bốn loại thai sinh của loài rồng. '",
  "sn29.2:1.3": "Bốn loại đó là gì? ",
  "sn29.2:1.4": "Rồng noãn sinh, rồng thai sinh, rồng thấp sinh, rồng hóa sinh. ",
  "sn29.2:1.5": "Trong đó, này các Tỳ Kheo, rồng thai sinh, rồng thấp sinh và rồng hóa sinh cao quý hơn rồng noãn sinh. ",
  "sn29.2:1.6": "Trong đó, này các Tỳ Kheo, rồng thấp sinh và rồng hóa sinh cao quý hơn rồng noãn sinh và rồng thai sinh. ",
  "sn29.2:1.7": "Trong đó, này các Tỳ Kheo, rồng hóa sinh cao quý hơn rồng noãn sinh, rồng thai sinh và rồng thấp sinh. ",
  "sn29.2:1.8": "Này các Tỳ Kheo, đây là bốn loại thai sinh của loài rồng'. ",
  "sn29.2:1.9": "Kinh thứ hai. ",
  "sn29.3:0.1": "Kinh Tương Ưng 29.3 ",
  "sn29.3:0.2": "1. Phẩm Rồng ",
  "sn29.3:0.3": "Kinh Bát Quan Trai ",
  "sn29.3:1.1": "Một thời, Thế Tôn trú tại Sāvatthi, trong vườn Jeta, tu viện của ông Anāthapiṇḍika. ",
  "sn29.3:1.2": "Rồi một Tỳ Kheo đi đến chỗ Thế Tôn, sau khi đến ngồi xuống một bên. Vị Tỳ Kheo ấy ngồi xuống một bên rồi thưa với Thế Tôn: ",
  "sn29.3:1.3": "'Bạch Thế Tôn, do nhân gì, duyên gì mà ở đây một số rồng noãn sinh giữ ngày trai giới và buông bỏ thân xác?' ",
  "sn29.3:2.1": "'Này Tỳ Kheo, ở đây một số rồng noãn sinh nghĩ như sau: '",
  "sn29.3:2.2": "'Trước đây chúng ta đã làm điều sai quấy bằng thân, làm điều sai quấy bằng lời nói, làm điều sai quấy bằng ý. '",
  "sn29.3:2.3": "Do làm điều sai quấy bằng thân, bằng lời nói, bằng ý, sau khi thân hoại mạng chung, chúng ta đã tái sinh vào cõi của loài rồng noãn sinh. ",
  "sn29.3:2.4": "Nếu hôm nay chúng ta sống theo hạnh lành bằng thân, bằng lời nói, bằng ý, thì sau khi thân hoại mạng chung, chúng ta có thể tái sinh vào cõi lành, cõi trời. ",
  "sn29.3:2.5": "Thôi nào, bây giờ hãy sống theo hạnh lành bằng thân, bằng lời nói, bằng ý.' ",
  "sn29.3:2.6": "Này Tỳ Kheo, đó là nhân, đó là duyên khiến ở đây một số rồng noãn sinh giữ ngày trai giới và buông bỏ thân xác'. ",
  "sn29.3:2.7": "Kinh thứ ba. ",
  "sn29.4:0.1": "Kinh Tương Ưng 29.4 ",
  "sn29.4:0.2": "1. Phẩm Rồng ",
  "sn29.4:0.3": "Kinh Bát Quan Trai Thứ Hai ",
  "sn29.4:1.1": "Duyên khởi tại Sāvatthi. ",
  "sn29.4:1.2": "Rồi một Tỳ Kheo đi đến chỗ Thế Tôn …(như trên)… vị Tỳ Kheo ấy ngồi xuống một bên rồi thưa với Thế Tôn: ",
  "sn29.4:1.3": "'Bạch Thế Tôn, do nhân gì, duyên gì mà ở đây một số rồng thai sinh giữ ngày trai giới và buông bỏ thân xác?' ",
  "sn29.4:1.4": "(Cần trình bày đầy đủ.) ",
  "sn29.4:1.5": "'Này Tỳ Kheo, đó là nhân, đó là duyên khiến ở đây một số rồng thai sinh giữ ngày trai giới và buông bỏ thân xác'. ",
  "sn29.4:1.6": "Kinh thứ tư. ",
  "sn29.5:0.1": "Kinh Tương Ưng 29.5 ",
  "sn29.5:0.2": "1. Phẩm Rồng ",
  "sn29.5:0.3": "Kinh Bát Quan Trai Thứ Ba ",
  "sn29.5:1.1": "Duyên khởi tại Sāvatthi. ",
  "sn29.5:1.2": "Vị Tỳ Kheo ấy ngồi xuống một bên rồi thưa với Thế Tôn: ",
  "sn29.5:1.3": "'Bạch Thế Tôn, do nhân gì, duyên gì mà ở đây một số rồng thấp sinh giữ ngày trai giới và buông bỏ thân xác?' ",
  "sn29.5:1.4": "(Cần trình bày đầy đủ.) ",
  "sn29.5:1.5": "'Này Tỳ Kheo, đó là nhân, đó là duyên khiến ở đây một số rồng thấp sinh giữ ngày trai giới và buông bỏ thân xác'. ",
  "sn29.5:1.6": "Kinh thứ năm. ",
  "sn29.6:0.1": "Kinh Tương Ưng 29.6 ",
  "sn29.6:0.2": "1. Phẩm Rồng ",
  "sn29.6:0.3": "Kinh Bát Quan Trai Thứ Tư ",
  "sn29.6:1.1": "Duyên khởi tại Sāvatthi. ",
  "sn29.6:1.2": "Vị Tỳ Kheo ấy ngồi xuống một bên rồi thưa với Thế Tôn: ",
  "sn29.6:1.3": "'Bạch Thế Tôn, do nhân gì, duyên gì mà ở đây một số rồng hóa sinh giữ ngày trai giới và buông bỏ thân xác?' ",
  "sn29.6:2.1": "'Này Tỳ Kheo, ở đây một số rồng hóa sinh nghĩ như sau: '",
  "sn29.6:2.2": "'Trước đây chúng ta đã làm điều sai quấy bằng thân, làm điều sai quấy bằng lời nói, làm điều sai quấy bằng ý. '",
  "sn29.6:2.3": "Do làm điều sai quấy bằng thân, bằng lời nói, bằng ý, sau khi thân hoại mạng chung, chúng ta đã tái sinh vào cõi của loài rồng hóa sinh. ",
  "sn29.6:2.4": "Nếu hôm nay chúng ta sống theo hạnh lành bằng thân, … bằng ý, thì sau khi thân hoại mạng chung, chúng ta có thể tái sinh vào cõi lành, cõi trời. ",
  "sn29.6:2.5": "Thôi nào, bây giờ hãy sống theo hạnh lành bằng thân, … bằng ý.' ",
  "sn29.6:2.6": "Này Tỳ Kheo, đó là nhân, đó là duyên khiến ở đây một số rồng hóa sinh giữ ngày trai giới và buông bỏ thân xác'. ",
  "sn29.6:2.7": "Kinh thứ sáu. ",
  "sn29.7:0.1": "Kinh Tương Ưng 29.7 ",
  "sn29.7:0.2": "1. Phẩm Rồng ",
  "sn29.7:0.3": "Kinh Được Nghe ",
  "sn29.7:1.1": "Duyên khởi tại Sāvatthi. ",
  "sn29.7:1.2": "Vị Tỳ Kheo ấy ngồi xuống một bên rồi thưa với Thế Tôn: ",
  "sn29.7:1.3": "'Bạch Thế Tôn, do nhân gì, duyên gì mà ở đây có người sau khi thân hoại mạng chung tái sinh vào cõi của loài rồng noãn sinh?' ",
  "sn29.7:2.1": "'Này Tỳ Kheo, ở đây có người làm điều sai quấy bằng thân, làm điều sai quấy bằng lời nói, làm điều sai quấy bằng ý. '",
  "sn29.7:2.2": "Người ấy nghe rằng: ",
  "sn29.7:2.3": "'Rồng noãn sinh sống lâu, xinh đẹp và nhiều an lạc.' ",
  "sn29.7:2.4": "Người ấy nghĩ như sau: ",
  "sn29.7:2.5": "'Ước gì sau khi thân hoại mạng chung, ta được tái sinh vào cõi của loài rồng noãn sinh.' ",
  "sn29.7:2.6": "Người ấy sau khi thân hoại mạng chung liền tái sinh vào cõi của loài rồng noãn sinh. ",
  "sn29.7:2.7": "Này Tỳ Kheo, đó là nhân, đó là duyên khiến ở đây có người sau khi thân hoại mạng chung tái sinh vào cõi của loài rồng noãn sinh'. ",
  "sn29.7:2.8": "Kinh thứ bảy. ",
  "sn29.8:0.1": "Kinh Tương Ưng 29.8 ",
  "sn29.8:0.2": "1. Phẩm Rồng ",
  "sn29.8:0.3": "Kinh Được Nghe Thứ Hai ",
  "sn29.8:1.1": "Duyên khởi tại Sāvatthi. ",
  "sn29.8:1.2": "Vị Tỳ Kheo ấy ngồi xuống một bên rồi thưa với Thế Tôn: ",
  "sn29.8:1.3": "'Bạch Thế Tôn, do nhân gì, duyên gì mà ở đây có người sau khi thân hoại mạng chung tái sinh vào cõi của loài rồng thai sinh?' ",
  "sn29.8:1.4": "…(chi tiết như trên)… ",
  "sn29.8:1.5": "Này Tỳ Kheo, đó là nhân, đó là duyên khiến ở đây có người sau khi thân hoại mạng chung tái sinh vào cõi của loài rồng thai sinh'. ",
  "sn29.8:1.6": "Kinh thứ tám. ",
  "sn29.9:0.1": "Kinh Tương Ưng 29.9 ",
  "sn29.9:0.2": "1. Phẩm Rồng ",
  "sn29.9:0.3": "Kinh Được Nghe Thứ Ba ",
  "sn29.9:1.1": "Duyên khởi tại Sāvatthi. ",
  "sn29.9:1.2": "Vị Tỳ Kheo ấy ngồi xuống một bên rồi thưa với Thế Tôn: ",
  "sn29.9:1.3": "'Bạch Thế Tôn, do nhân gì, duyên gì mà ở đây có người sau khi thân hoại mạng chung tái sinh vào cõi của loài rồng thấp sinh?' ",
  "sn29.9:1.4": "…(chi tiết như trên)… ",
  "sn29.9:1.5": "Này Tỳ Kheo, đó là nhân, đó là duyên khiến ở đây có người sau khi thân hoại mạng chung tái sinh vào cõi của loài rồng thấp sinh'. ",
  "sn29.9:1.6": "Kinh thứ chín. ",
  "sn29.10:0.1": "Kinh Tương Ưng 29.10 ",
  "sn29.10:0.2": "1. Phẩm Rồng ",
  "sn29.10:0.3": "Kinh Được Nghe Thứ Tư ",
  "sn29.10:1.1": "Duyên khởi tại Sāvatthi. ",
  "sn29.10:1.2": "Vị Tỳ Kheo ấy ngồi xuống một bên rồi thưa với Thế Tôn: ",
  "sn29.10:1.3": "'Bạch Thế Tôn, do nhân gì, duyên gì mà ở đây có người sau khi thân hoại mạng chung tái sinh vào cõi của loài rồng hóa sinh?' ",
  "sn29.10:2.1": "'Này Tỳ Kheo, ở đây có người làm điều sai quấy bằng thân, bằng lời nói, bằng ý. '",
  "sn29.10:2.2": "Người ấy nghe rằng: ",
  "sn29.10:2.3": "'Rồng hóa sinh sống lâu, xinh đẹp và nhiều an lạc.' ",
  "sn29.10:2.4": "Người ấy nghĩ như sau: ",
  "sn29.10:2.5": "'Ước gì sau khi thân hoại mạng chung, ta được tái sinh vào cõi của loài rồng hóa sinh.' ",
  "sn29.10:2.6": "Người ấy sau khi thân hoại mạng chung liền tái sinh vào cõi của loài rồng hóa sinh. ",
  "sn29.10:2.7": "Này Tỳ Kheo, đó là nhân, đó là duyên khiến ở đây có người sau khi thân hoại mạng chung tái sinh vào cõi của loài rồng hóa sinh'. ",
  "sn29.10:2.8": "Kinh thứ mười. ",
  "sn29.11-20:0.1": "Kinh Tương Ưng 29.11–20 ",
  "sn29.11-20:0.2": "1. Phẩm Rồng ",
  "sn29.11-20:0.3": "Mười Kinh về Bố Thí Được Sanh vào Cõi Rồng Noãn Sinh ",
  "sn29.11-20:1.1": "Vị Tỳ Kheo ấy ngồi xuống một bên rồi thưa với Thế Tôn: ",
  "sn29.11-20:1.2": "'Bạch Thế Tôn, do nhân gì, duyên gì mà ở đây có người sau khi thân hoại mạng chung tái sinh vào cõi của loài rồng noãn sinh?' ",
  "sn29.11-20:2.1": "'Này Tỳ Kheo, ở đây có người làm điều sai quấy bằng thân, bằng lời nói, bằng ý. '",
  "sn29.11-20:2.2": "Người ấy nghe rằng: ",
  "sn29.11-20:2.3": "'Rồng noãn sinh sống lâu, xinh đẹp và nhiều an lạc.' ",
  "sn29.11-20:2.4": "Người ấy nghĩ như sau: ",
  "sn29.11-20:2.5": "'Ước gì sau khi thân hoại mạng chung, ta được tái sinh vào cõi của loài rồng noãn sinh.' ",
  "sn29.11-20:2.6": "Người ấy bố thí thức ăn. ",
  "sn29.11-20:2.7": "Người ấy sau khi thân hoại mạng chung liền tái sinh vào cõi của loài rồng noãn sinh. ",
  "sn29.11-20:2.8": "Này Tỳ Kheo, đó là nhân …(như trên)… tái sinh vào cõi đó …(như trên)… ",
  "sn29.11-20:2.9": "bố thí đồ uống …(như trên)… ",
  "sn29.11-20:2.10": "bố thí vải vóc …(như trên)… ",
  "sn29.11-20:2.11": "bố thí xe cộ …(như trên)… ",
  "sn29.11-20:2.12": "bố thí tràng hoa …(như trên)… ",
  "sn29.11-20:2.13": "bố thí hương thơm …(như trên)… ",
  "sn29.11-20:2.14": "bố thí dầu thoa …(như trên)… ",
  "sn29.11-20:2.15": "bố thí chỗ nằm …(như trên)… ",
  "sn29.11-20:2.16": "bố thí chỗ ở …(như trên)… ",
  "sn29.11-20:2.17": "bố thí đèn dầu. ",
  "sn29.11-20:2.18": "Người ấy sau khi thân hoại mạng chung liền tái sinh vào cõi của loài rồng noãn sinh. ",
  "sn29.11-20:2.19": "Này Tỳ Kheo, đó là nhân, đó là duyên khiến ở đây có người sau khi thân hoại mạng chung tái sinh vào cõi của loài rồng noãn sinh'. ",
  "sn29.11-20:2.20": "Kinh thứ hai mươi. ",
  "sn29.21-50:0.1": "Kinh Tương Ưng 29.21–50 ",
  "sn29.21-50:0.2": "1. Phẩm Rồng ",
  "sn29.21-50:0.3": "Ba Mươi Kinh về Bố Thí Được Sanh vào Cõi Rồng Thai Sinh và Các Loài Khác ",
  "sn29.21-50:1.1": "Duyên khởi tại Sāvatthi. ",
  "sn29.21-50:1.2": "Vị Tỳ Kheo ấy ngồi xuống một bên rồi thưa với Thế Tôn: ",
  "sn29.21-50:1.3": "'Bạch Thế Tôn, do nhân gì, duyên gì mà ở đây có người sau khi thân hoại mạng chung tái sinh vào cõi của loài rồng thai sinh …(như trên)… '",
  "sn29.21-50:1.4": "cõi của loài rồng thấp sinh …(như trên)… ",
  "sn29.21-50:1.5": "cõi của loài rồng hóa sinh?' ",
  "sn29.21-50:2.1": "'Này Tỳ Kheo, ở đây có người làm điều sai quấy bằng thân, bằng lời nói, bằng ý. '",
  "sn29.21-50:2.2": "Người ấy nghe rằng: ",
  "sn29.21-50:2.3": "'Rồng hóa sinh sống lâu, xinh đẹp và nhiều an lạc.' ",
  "sn29.21-50:2.4": "Người ấy nghĩ như sau: ",
  "sn29.21-50:2.5": "'Ước gì sau khi thân hoại mạng chung, ta được tái sinh vào cõi của loài rồng hóa sinh.' ",
  "sn29.21-50:2.6": "Người ấy bố thí thức ăn …(như trên)… ",
  "sn29.21-50:2.7": "bố thí đồ uống …(như trên)… ",
  "sn29.21-50:2.8": "bố thí đèn dầu. ",
  "sn29.21-50:2.9": "Người ấy sau khi thân hoại mạng chung liền tái sinh vào cõi của loài rồng hóa sinh. ",
  "sn29.21-50:2.10": "Này Tỳ Kheo, đó là nhân, đó là duyên khiến ở đây có người sau khi thân hoại mạng chung tái sinh vào cõi của loài rồng hóa sinh'. ",
  "sn29.21-50:3.1": "(Với phương thức tóm lược này, mười mười kinh cần được trình bày đầy đủ. ",
  "sn29.21-50:3.2": "Như vậy có bốn mươi câu trả lời trong bốn loại thai sinh. ",
  "sn29.21-50:3.3": "Cùng với mười kinh trước đó, tổng cộng là năm mươi kinh.) ",
  "sn29.21-50:3.4": "Phẩm Rồng thứ nhất. ",
  "sn29.21-50:4.0": "Tóm tắt nội dung ",
  "sn29.21-50:4.1": "Kinh thuần túy, kinh cao quý hơn, ",
  "sn29.21-50:4.2": "và bốn kinh bát quan trai; ",
  "sn29.21-50:4.3": "Bốn kinh được nghe, ",
  "sn29.21-50:4.4": "và bốn mươi kinh về bố thí; ",
  "sn29.21-50:4.5": "Tổng cộng năm mươi kinh, ",
  "sn29.21-50:4.6": "được giảng dạy rõ ràng về loài rồng. ",
  "sn29.21-50:4.7": "Tương Ưng về Rồng hoàn tất. "
}
window.BILARA["sn29_v1"]["vi"]["sn29_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
