window.BILARA = window.BILARA || {};
window.BILARA["sn30_v1"] = window.BILARA["sn30_v1"] || {};
window.BILARA["sn30_v1"]["vi"] = {
  "sn30.1:0.1": "Tương Ưng Bộ Kinh 30.1 ",
  "sn30.1:0.2": "1. Phẩm Kim Sí Điểu ",
  "sn30.1:0.3": "Kinh Thuần Túy ",
  "sn30.1:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn30.1:1.2": "'Này các Tỳ Kheo, có bốn loài Kim Sí Điểu theo nguồn gốc sinh. '",
  "sn30.1:1.3": "Bốn loài đó là gì? ",
  "sn30.1:1.4": "Kim Sí Điểu sinh từ trứng, Kim Sí Điểu sinh từ bào thai, Kim Sí Điểu sinh từ ẩm ướt, Kim Sí Điểu hóa sinh ",
  "sn30.1:1.5": "Này các Tỳ Kheo, đó là bốn loài Kim Sí Điểu theo nguồn gốc sinh.' ",
  "sn30.1:1.6": "Kinh thứ nhất. ",
  "sn30.2:0.1": "Tương Ưng Bộ Kinh 30.2 ",
  "sn30.2:0.2": "1. Phẩm Kim Sí Điểu ",
  "sn30.2:0.3": "Kinh Bắt Rồng ",
  "sn30.2:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn30.2:1.2": "'Này các Tỳ Kheo, có bốn loài Kim Sí Điểu theo nguồn gốc sinh. '",
  "sn30.2:1.3": "Bốn loài đó là gì? ",
  "sn30.2:1.4": "Kim Sí Điểu sinh từ trứng …pe… ",
  "sn30.2:1.5": "Này các Tỳ Kheo, đó là bốn loài Kim Sí Điểu theo nguồn gốc sinh. ",
  "sn30.2:1.6": "Này các Tỳ Kheo, ở đây Kim Sí Điểu sinh từ trứng chỉ bắt được các Rồng sinh từ trứng, không bắt được Rồng sinh từ bào thai, không bắt được Rồng sinh từ ẩm ướt, không bắt được Rồng hóa sinh. ",
  "sn30.2:1.7": "Này các Tỳ Kheo, ở đây Kim Sí Điểu sinh từ bào thai bắt được cả Rồng sinh từ trứng lẫn Rồng sinh từ bào thai, không bắt được Rồng sinh từ ẩm ướt, không bắt được Rồng hóa sinh. ",
  "sn30.2:1.8": "Này các Tỳ Kheo, ở đây Kim Sí Điểu sinh từ ẩm ướt bắt được Rồng sinh từ trứng, Rồng sinh từ bào thai, và Rồng sinh từ ẩm ướt, nhưng không bắt được Rồng hóa sinh. ",
  "sn30.2:1.9": "Này các Tỳ Kheo, ở đây Kim Sí Điểu hóa sinh bắt được Rồng sinh từ trứng, Rồng sinh từ bào thai, Rồng sinh từ ẩm ướt, và cả Rồng hóa sinh. ",
  "sn30.2:1.10": "Này các Tỳ Kheo, đó là bốn loài Kim Sí Điểu theo nguồn gốc sinh.' ",
  "sn30.2:1.11": "Kinh thứ hai. ",
  "sn30.3:0.1": "Tương Ưng Bộ Kinh 30.3 ",
  "sn30.3:0.2": "1. Phẩm Kim Sí Điểu ",
  "sn30.3:0.3": "Kinh Làm Hai Việc ",
  "sn30.3:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn30.3:1.2": "Một Tỳ Kheo đi đến chỗ Đức Thế Tôn; sau khi đến, đảnh lễ Đức Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, vị Tỳ Kheo đó bạch Đức Thế Tôn rằng: ",
  "sn30.3:1.3": "'Bạch Thế Tôn, đâu là nhân, đâu là duyên, khiến ở đây có người sau khi thân tan hoại, sau khi chết, tái sinh vào cõi của các Kim Sí Điểu sinh từ trứng?' ",
  "sn30.3:1.4": "'Này Tỳ Kheo, ở đây có người làm cả hai loại việc bằng thân, làm cả hai loại việc bằng lời nói, làm cả hai loại việc bằng ý. '",
  "sn30.3:1.5": "Người ấy đã nghe: ",
  "sn30.3:1.6": "'Các Kim Sí Điểu sinh từ trứng sống thọ, có sắc đẹp, và nhiều an lạc.' ",
  "sn30.3:1.7": "Người ấy nghĩ: ",
  "sn30.3:1.8": "'Ước gì sau khi thân tan hoại, sau khi chết, ta được tái sinh vào cõi của các Kim Sí Điểu sinh từ trứng!' ",
  "sn30.3:1.9": "Người ấy sau khi thân tan hoại, sau khi chết, tái sinh vào cõi của các Kim Sí Điểu sinh từ trứng. ",
  "sn30.3:1.10": "Này Tỳ Kheo, đó là nhân, đó là duyên, khiến ở đây có người sau khi thân tan hoại, sau khi chết, tái sinh vào cõi của các Kim Sí Điểu sinh từ trứng.' ",
  "sn30.3:1.11": "Kinh thứ ba. ",
  "sn30.4-6:0.1": "Tương Ưng Bộ Kinh 30.4–6 ",
  "sn30.4-6:0.2": "1. Phẩm Kim Sí Điểu ",
  "sn30.4-6:0.3": "Ba Kinh Làm Hai Việc (thứ hai trở đi) ",
  "sn30.4-6:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn30.4-6:1.2": "Ngồi xuống một bên, vị Tỳ Kheo đó bạch Đức Thế Tôn rằng: ",
  "sn30.4-6:1.3": "'Bạch Thế Tôn, đâu là nhân, đâu là duyên, khiến ở đây có người sau khi thân tan hoại, sau khi chết, tái sinh vào cõi của các Kim Sí Điểu sinh từ bào thai …pe… '",
  "sn30.4-6:1.4": "vào cõi của các Kim Sí Điểu sinh từ ẩm ướt …pe… ",
  "sn30.4-6:1.5": "vào cõi của các Kim Sí Điểu hóa sinh?' ",
  "sn30.4-6:1.6": "'Này Tỳ Kheo, ở đây có người làm cả hai loại việc bằng thân, làm cả hai loại việc bằng lời nói, làm cả hai loại việc bằng ý. '",
  "sn30.4-6:1.7": "Người ấy đã nghe: ",
  "sn30.4-6:1.8": "'Các Kim Sí Điểu hóa sinh sống thọ, có sắc đẹp, và nhiều an lạc.' ",
  "sn30.4-6:1.9": "Người ấy nghĩ: ",
  "sn30.4-6:1.10": "'Ước gì sau khi thân tan hoại, sau khi chết, ta được tái sinh vào cõi của các Kim Sí Điểu hóa sinh!' ",
  "sn30.4-6:1.11": "Người ấy sau khi thân tan hoại, sau khi chết, tái sinh vào cõi của các Kim Sí Điểu hóa sinh. ",
  "sn30.4-6:1.12": "Này Tỳ Kheo, đó là nhân, đó là duyên, khiến ở đây có người sau khi thân tan hoại, sau khi chết, tái sinh vào cõi của các Kim Sí Điểu hóa sinh.' ",
  "sn30.4-6:1.13": "Kinh thứ sáu. ",
  "sn30.7-16:0.1": "Tương Ưng Bộ Kinh 30.7–16 ",
  "sn30.7-16:0.2": "1. Phẩm Kim Sí Điểu ",
  "sn30.7-16:0.3": "Mười Kinh Bố Thí Giúp Ích (Kim Sí Điểu sinh từ trứng) ",
  "sn30.7-16:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn30.7-16:1.2": "Ngồi xuống một bên, vị Tỳ Kheo đó bạch Đức Thế Tôn rằng: ",
  "sn30.7-16:1.3": "'Bạch Thế Tôn, đâu là nhân, đâu là duyên, khiến ở đây có người sau khi thân tan hoại, sau khi chết, tái sinh vào cõi của các Kim Sí Điểu sinh từ trứng?' ",
  "sn30.7-16:1.4": "'Này Tỳ Kheo, ở đây có người làm cả hai loại việc bằng thân, làm cả hai loại việc bằng lời nói, làm cả hai loại việc bằng ý. '",
  "sn30.7-16:1.5": "Người ấy đã nghe: ",
  "sn30.7-16:1.6": "'Các Kim Sí Điểu sinh từ trứng sống thọ, có sắc đẹp, và nhiều an lạc.' ",
  "sn30.7-16:1.7": "Người ấy nghĩ: ",
  "sn30.7-16:1.8": "'Ước gì sau khi thân tan hoại, sau khi chết, ta được tái sinh vào cõi của các Kim Sí Điểu sinh từ trứng!' ",
  "sn30.7-16:1.9": "Người ấy bố thí thức ăn …pe… ",
  "sn30.7-16:1.10": "bố thí đồ uống … ",
  "sn30.7-16:1.11": "bố thí y phục … ",
  "sn30.7-16:1.12": "bố thí phương tiện đi lại … ",
  "sn30.7-16:1.13": "bố thí vòng hoa … ",
  "sn30.7-16:1.14": "bố thí hương thơm … ",
  "sn30.7-16:1.15": "bố thí thuốc xoa … ",
  "sn30.7-16:1.16": "bố thí chỗ nằm … ",
  "sn30.7-16:1.17": "bố thí chỗ ở … ",
  "sn30.7-16:1.18": "bố thí đèn nến. ",
  "sn30.7-16:1.19": "Người ấy sau khi thân tan hoại, sau khi chết, tái sinh vào cõi của các Kim Sí Điểu sinh từ trứng. ",
  "sn30.7-16:1.20": "Này Tỳ Kheo, đó là nhân, đó là duyên, khiến ở đây có người sau khi thân tan hoại, sau khi chết, tái sinh vào cõi của các Kim Sí Điểu sinh từ trứng.' ",
  "sn30.7-16:1.21": "Kinh thứ mười sáu. ",
  "sn30.17-46:0.1": "Tương Ưng Bộ Kinh 30.17–46 ",
  "sn30.17-46:0.2": "1. Phẩm Kim Sí Điểu ",
  "sn30.17-46:0.3": "Kinh Bố Thí Giúp Ích (Kim Sí Điểu sinh từ bào thai và các loại khác) ",
  "sn30.17-46:1.1": "Nhân duyên tại Sāvatthi. ",
  "sn30.17-46:1.2": "Ngồi xuống một bên, vị Tỳ Kheo đó bạch Đức Thế Tôn rằng: ",
  "sn30.17-46:1.3": "'Bạch Thế Tôn, đâu là nhân, đâu là duyên, khiến ở đây có người sau khi thân tan hoại, sau khi chết, tái sinh vào cõi của các Kim Sí Điểu sinh từ bào thai …pe… '",
  "sn30.17-46:1.4": "vào cõi của các Kim Sí Điểu sinh từ ẩm ướt …pe… ",
  "sn30.17-46:1.5": "vào cõi của các Kim Sí Điểu hóa sinh?' ",
  "sn30.17-46:1.6": "'Này Tỳ Kheo, ở đây có người làm cả hai loại việc bằng thân, làm cả hai loại việc bằng lời nói, làm cả hai loại việc bằng ý. '",
  "sn30.17-46:1.7": "Người ấy đã nghe: ",
  "sn30.17-46:1.8": "'Các Kim Sí Điểu hóa sinh sống thọ, có sắc đẹp, và nhiều an lạc.' ",
  "sn30.17-46:1.9": "Người ấy nghĩ: ",
  "sn30.17-46:1.10": "'Ước gì sau khi thân tan hoại, sau khi chết, ta được tái sinh vào cõi của các Kim Sí Điểu hóa sinh!' ",
  "sn30.17-46:1.11": "Người ấy bố thí thức ăn …pe… ",
  "sn30.17-46:1.12": "bố thí đồ uống …pe… ",
  "sn30.17-46:1.13": "bố thí đèn nến. ",
  "sn30.17-46:1.14": "Người ấy sau khi thân tan hoại, sau khi chết, tái sinh vào cõi của các Kim Sí Điểu hóa sinh. ",
  "sn30.17-46:1.15": "Này Tỳ Kheo, đó là nhân, đó là duyên, khiến ở đây có người sau khi thân tan hoại, sau khi chết, tái sinh vào cõi của các Kim Sí Điểu hóa sinh.' ",
  "sn30.17-46:1.16": "Kinh thứ bốn mươi sáu. ",
  "sn30.17-46:1.17": "(Như vậy, tính tổng cộng có bốn mươi sáu kinh.) ",
  "sn30.17-46:1.18": "Phẩm Kim Sí Điểu thứ nhất. ",
  "sn30.17-46:2.0": "Kệ tóm tắt của phẩm này: ",
  "sn30.17-46:2.1": "Kinh Thuần Túy và Kinh Bắt Rồng, ",
  "sn30.17-46:2.2": "bốn kinh Làm Hai Việc; ",
  "sn30.17-46:2.3": "bốn mươi kinh Bố Thí Giúp Ích, ",
  "sn30.17-46:2.4": "được giảng rõ về Kim Sí Điểu. ",
  "sn30.17-46:2.5": "Tương Ưng Kim Sí Điểu kết thúc. "
}
window.BILARA["sn30_v1"]["vi"]["sn30_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
