window.BILARA = window.BILARA || {};
window.BILARA["sn37_v1"] = window.BILARA["sn37_v1"] || {};
window.BILARA["sn37_v1"]["vi"] = {
  "sn37.1:0.1": "Tương Ưng Bộ 37.1 ",
  "sn37.1:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.1:0.3": "Kinh Người Phụ Nữ ",
  "sn37.1:1.1": "'Này các Tỳ Kheo, người phụ nữ có năm đặc tính thì hoàn toàn không được người đàn ông ưa thích. '",
  "sn37.1:1.2": "Đó là năm đặc tính nào? ",
  "sn37.1:1.3": "Không có sắc đẹp, không có của cải, không có giới hạnh, lười biếng, và không sinh được con",
  "sn37.1:1.4": "Này các Tỳ Kheo, người phụ nữ có năm đặc tính này thì hoàn toàn không được người đàn ông ưa thích. ",
  "sn37.1:1.5": "Này các Tỳ Kheo, người phụ nữ có năm đặc tính thì hoàn toàn được người đàn ông ưa thích. ",
  "sn37.1:1.6": "Đó là năm đặc tính nào? ",
  "sn37.1:1.7": "Có sắc đẹp, có của cải, có giới hạnh, siêng năng không lười biếng, và sinh được con",
  "sn37.1:1.8": "Này các Tỳ Kheo, người phụ nữ có năm đặc tính này thì hoàn toàn được người đàn ông ưa thích.' ",
  "sn37.1:1.9": "Thứ nhất. ",
  "sn37.2:0.1": "Tương Ưng Bộ 37.2 ",
  "sn37.2:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.2:0.3": "Kinh Người Đàn Ông ",
  "sn37.2:1.1": "'Này các Tỳ Kheo, người đàn ông có năm đặc tính thì hoàn toàn không được người phụ nữ ưa thích. '",
  "sn37.2:1.2": "Đó là năm đặc tính nào? ",
  "sn37.2:1.3": "Không có sắc đẹp, không có của cải, không có giới hạnh, lười biếng, và không sinh được con",
  "sn37.2:1.4": "Này các Tỳ Kheo, người đàn ông có năm đặc tính này thì hoàn toàn không được người phụ nữ ưa thích. ",
  "sn37.2:1.5": "Này các Tỳ Kheo, người đàn ông có năm đặc tính thì hoàn toàn được người phụ nữ ưa thích. ",
  "sn37.2:1.6": "Đó là năm đặc tính nào? ",
  "sn37.2:1.7": "Có sắc đẹp, có của cải, có giới hạnh, siêng năng không lười biếng, và sinh được con",
  "sn37.2:1.8": "Này các Tỳ Kheo, người đàn ông có năm đặc tính này thì hoàn toàn được người phụ nữ ưa thích.' ",
  "sn37.2:1.9": "Thứ hai. ",
  "sn37.3:0.1": "Tương Ưng Bộ 37.3 ",
  "sn37.3:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.3:0.3": "Kinh Khổ Riêng Biệt ",
  "sn37.3:1.1": "'Này các Tỳ Kheo, có năm nỗi khổ riêng biệt của người phụ nữ mà chỉ người phụ nữ phải chịu đựng, không phải đàn ông. '",
  "sn37.3:1.2": "Đó là năm nỗi khổ nào? ",
  "sn37.3:1.3": "Này các Tỳ Kheo, người phụ nữ khi còn trẻ đã phải về nhà chồng, xa lìa thân quyến. ",
  "sn37.3:1.4": "Này các Tỳ Kheo, đây là nỗi khổ riêng biệt thứ nhất của người phụ nữ mà chỉ người phụ nữ phải chịu đựng, không phải đàn ông. ",
  "sn37.3:1.5": "Lại nữa, này các Tỳ Kheo, người phụ nữ có kinh nguyệt. ",
  "sn37.3:1.6": "Này các Tỳ Kheo, đây là nỗi khổ riêng biệt thứ hai của người phụ nữ mà chỉ người phụ nữ phải chịu đựng, không phải đàn ông. ",
  "sn37.3:1.7": "Lại nữa, này các Tỳ Kheo, người phụ nữ mang thai. ",
  "sn37.3:1.8": "Này các Tỳ Kheo, đây là nỗi khổ riêng biệt thứ ba của người phụ nữ mà chỉ người phụ nữ phải chịu đựng, không phải đàn ông. ",
  "sn37.3:1.9": "Lại nữa, này các Tỳ Kheo, người phụ nữ phải sinh con. ",
  "sn37.3:1.10": "Này các Tỳ Kheo, đây là nỗi khổ riêng biệt thứ tư của người phụ nữ mà chỉ người phụ nữ phải chịu đựng, không phải đàn ông. ",
  "sn37.3:1.11": "Lại nữa, này các Tỳ Kheo, người phụ nữ phải phục vụ người đàn ông. ",
  "sn37.3:1.12": "Này các Tỳ Kheo, đây là nỗi khổ riêng biệt thứ năm của người phụ nữ mà chỉ người phụ nữ phải chịu đựng, không phải đàn ông. ",
  "sn37.3:1.13": "Này các Tỳ Kheo, đây là năm nỗi khổ riêng biệt của người phụ nữ mà chỉ người phụ nữ phải chịu đựng, không phải đàn ông.' ",
  "sn37.3:1.14": "Thứ ba. ",
  "sn37.4:0.1": "Tương Ưng Bộ 37.4 ",
  "sn37.4:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.4:0.3": "Kinh Ba Pháp ",
  "sn37.4:1.1": "'Này các Tỳ Kheo, người phụ nữ có ba pháp thì đa phần sau khi thân hoại mạng chung sẽ tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục. '",
  "sn37.4:1.2": "Đó là ba pháp nào? ",
  "sn37.4:1.3": "Này các Tỳ Kheo, buổi sáng người phụ nữ sống trong nhà với tâm bị cấu uế bủn xỉn bao phủ. ",
  "sn37.4:1.4": "Buổi trưa sống trong nhà với tâm bị ganh tị bao phủ. ",
  "sn37.4:1.5": "Buổi chiều sống trong nhà với tâm bị tham dục bao phủ. ",
  "sn37.4:1.6": "Này các Tỳ Kheo, người phụ nữ có ba pháp này thì đa phần sau khi thân hoại mạng chung sẽ tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục.' ",
  "sn37.4:1.7": "Thứ tư. ",
  "sn37.4:1.8": "(…) ",
  "sn37.5:0.1": "Tương Ưng Bộ 37.5 ",
  "sn37.5:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.5:0.3": "Kinh Người Hay Giận ",
  "sn37.5:1.1": "Rồi Tôn giả Anuruddha đến chỗ Thế Tôn; sau khi đến, ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Anuruddha bạch Thế Tôn rằng: ",
  "sn37.5:1.2": "'Bạch Thế Tôn, ở đây con thấy bằng thiên nhãn thanh tịnh siêu việt loài người, người phụ nữ sau khi thân hoại mạng chung tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục. '",
  "sn37.5:1.3": "Bạch Thế Tôn, người phụ nữ có bao nhiêu pháp mà sau khi thân hoại mạng chung tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục?' ",
  "sn37.5:2.1": "'Này Anuruddha, người phụ nữ có năm pháp thì sau khi thân hoại mạng chung tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục. '",
  "sn37.5:2.2": "Đó là năm pháp nào? ",
  "sn37.5:2.3": "Không có lòng tin, không biết hổ thẹn, không sợ tội lỗi, hay giận dữ, và thiếu trí tuệ",
  "sn37.5:2.4": "Này Anuruddha, người phụ nữ có năm pháp này thì sau khi thân hoại mạng chung tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục.' ",
  "sn37.5:2.5": "Thứ năm. ",
  "sn37.6:0.1": "Tương Ưng Bộ 37.6 ",
  "sn37.6:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.6:0.3": "Kinh Người Hay Thù Hận ",
  "sn37.6:1.1": "'Này Anuruddha, người phụ nữ có năm pháp thì sau khi thân hoại mạng chung tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục. '",
  "sn37.6:1.2": "Đó là năm pháp nào? ",
  "sn37.6:1.3": "Không có lòng tin, không biết hổ thẹn, không sợ tội lỗi, hay thù hận, và thiếu trí tuệ",
  "sn37.6:1.4": "Này Anuruddha, người phụ nữ có năm pháp này thì sau khi thân hoại mạng chung tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục.' ",
  "sn37.6:1.5": "Thứ sáu. ",
  "sn37.7:0.1": "Tương Ưng Bộ 37.7 ",
  "sn37.7:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.7:0.3": "Kinh Người Hay Ganh Tị ",
  "sn37.7:1.1": "'Này Anuruddha, người phụ nữ có năm pháp thì sau khi thân hoại mạng chung tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục. '",
  "sn37.7:1.2": "Đó là năm pháp nào? ",
  "sn37.7:1.3": "Không có lòng tin, không biết hổ thẹn, không sợ tội lỗi, hay ganh tị, và thiếu trí tuệ",
  "sn37.7:1.4": "Này Anuruddha, người phụ nữ có năm pháp này thì sau khi thân hoại mạng chung tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục.' ",
  "sn37.7:1.5": "Thứ bảy. ",
  "sn37.8:0.1": "Tương Ưng Bộ 37.8 ",
  "sn37.8:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.8:0.3": "Kinh Người Hay Bủn Xỉn ",
  "sn37.8:1.1": "'Này Anuruddha, người phụ nữ có năm pháp thì sau khi thân hoại mạng chung tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục. '",
  "sn37.8:1.2": "Đó là năm pháp nào? ",
  "sn37.8:1.3": "Không có lòng tin, không biết hổ thẹn, không sợ tội lỗi, hay bủn xỉn, và thiếu trí tuệ",
  "sn37.8:1.4": "Này Anuruddha, người phụ nữ có năm pháp này …(lược)… ",
  "sn37.8:1.5": "tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục.' ",
  "sn37.8:1.6": "Thứ tám. ",
  "sn37.9:0.1": "Tương Ưng Bộ 37.9 ",
  "sn37.9:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.9:0.3": "Kinh Người Tà Hạnh ",
  "sn37.9:1.1": "'Này Anuruddha, người phụ nữ có năm pháp …(lược)… tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục. '",
  "sn37.9:1.2": "Đó là năm pháp nào? ",
  "sn37.9:1.3": "Không có lòng tin, không biết hổ thẹn, không sợ tội lỗi, tà hạnh, và thiếu trí tuệ",
  "sn37.9:1.4": "Này Anuruddha, người phụ nữ có năm pháp này …(lược)… tái sinh.' ",
  "sn37.9:1.5": "Thứ chín. ",
  "sn37.10:0.1": "Tương Ưng Bộ 37.10 ",
  "sn37.10:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.10:0.3": "Kinh Người Phá Giới ",
  "sn37.10:1.1": "'Này Anuruddha, người phụ nữ có năm pháp …(lược)… tái sinh vào địa ngục. '",
  "sn37.10:1.2": "Đó là năm pháp nào? ",
  "sn37.10:1.3": "Không có lòng tin, không biết hổ thẹn, không sợ tội lỗi, phá giới, và thiếu trí tuệ",
  "sn37.10:1.4": "Này Anuruddha, người phụ nữ có năm pháp này …(lược)… tái sinh vào địa ngục.' ",
  "sn37.10:1.5": "Thứ mười. ",
  "sn37.11:0.1": "Tương Ưng Bộ 37.11 ",
  "sn37.11:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.11:0.3": "Kinh Người Ít Học ",
  "sn37.11:1.1": "'Này Anuruddha, người phụ nữ có năm pháp …(lược)… tái sinh vào địa ngục. '",
  "sn37.11:1.2": "Đó là năm pháp nào? ",
  "sn37.11:1.3": "Không có lòng tin, không biết hổ thẹn, không sợ tội lỗi, ít học, và thiếu trí tuệ",
  "sn37.11:1.4": "Này Anuruddha, người phụ nữ có năm pháp này …(lược)… tái sinh vào địa ngục.' ",
  "sn37.11:1.5": "Thứ mười một. ",
  "sn37.12:0.1": "Tương Ưng Bộ 37.12 ",
  "sn37.12:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.12:0.3": "Kinh Người Biếng Nhác ",
  "sn37.12:1.1": "'Này Anuruddha, người phụ nữ có năm pháp …(lược)… tái sinh vào địa ngục. '",
  "sn37.12:1.2": "Đó là năm pháp nào? ",
  "sn37.12:1.3": "Không có lòng tin, không biết hổ thẹn, không sợ tội lỗi, biếng nhác, và thiếu trí tuệ",
  "sn37.12:1.4": "Này Anuruddha, người phụ nữ có năm pháp này …(lược)… tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục.' ",
  "sn37.12:1.5": "Thứ mười hai. ",
  "sn37.13:0.1": "Tương Ưng Bộ 37.13 ",
  "sn37.13:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.13:0.3": "Kinh Người Thất Niệm ",
  "sn37.13:1.1": "'Này Anuruddha, người phụ nữ có năm pháp …(lược)… tái sinh vào địa ngục. '",
  "sn37.13:1.2": "Đó là năm pháp nào? ",
  "sn37.13:1.3": "Không có lòng tin, không biết hổ thẹn, không sợ tội lỗi, thất niệm, và thiếu trí tuệ",
  "sn37.13:1.4": "Này Anuruddha, người phụ nữ có năm pháp này …(lược)… tái sinh vào địa ngục.' ",
  "sn37.13:1.5": "Thứ mười ba. ",
  "sn37.14:0.1": "Tương Ưng Bộ 37.14 ",
  "sn37.14:0.2": "1. Phẩm Peyyāla Thứ Nhất ",
  "sn37.14:0.3": "Kinh Năm Giới Cấm ",
  "sn37.14:1.1": "'Này Anuruddha, người phụ nữ có năm pháp …(lược)… tái sinh vào địa ngục. '",
  "sn37.14:1.2": "Đó là năm pháp nào? ",
  "sn37.14:1.3": "Sát hại sinh vật, trộm cắp tài sản người khác, tà dâm, nói dối, và uống rượu say",
  "sn37.14:1.4": "Này Anuruddha, người phụ nữ có năm pháp này thì sau khi thân hoại mạng chung tái sinh vào cõi khổ, ác đạo, đọa xứ, địa ngục.' ",
  "sn37.14:1.5": "Thứ mười bốn. ",
  "sn37.14:1.6": "Phẩm Peyyāla Thứ Nhất. ",
  "sn37.14:2.0": "Tóm tắt phẩm ",
  "sn37.14:2.1": "Người phụ nữ và người đàn ông, ",
  "sn37.14:2.2": "khổ riêng biệt và ba pháp; ",
  "sn37.14:2.3": "Hay giận, hay thù hận, ",
  "sn37.14:2.4": "hay ganh tị, bủn xỉn; ",
  "sn37.14:2.5": "Tà hạnh và phá giới, ",
  "sn37.14:2.6": "ít học và biếng nhác; ",
  "sn37.14:2.7": "Thất niệm và năm giới cấm, ",
  "sn37.14:2.8": "được giảng rõ thuộc phần tối. ",
  "sn37.15:0.1": "Tương Ưng Bộ 37.15 ",
  "sn37.15:0.2": "2. Phẩm Peyyāla Thứ Hai ",
  "sn37.15:0.3": "Kinh Người Không Hay Giận ",
  "sn37.15:1.1": "Rồi Tôn giả Anuruddha đến chỗ Thế Tôn; sau khi đến …(lược)… ngồi xuống một bên, Tôn giả Anuruddha bạch Thế Tôn rằng: ",
  "sn37.15:1.2": "'Bạch Thế Tôn, ở đây con thấy bằng thiên nhãn thanh tịnh siêu việt loài người, người phụ nữ sau khi thân hoại mạng chung tái sinh vào cõi lành, cõi trời. '",
  "sn37.15:1.3": "Bạch Thế Tôn, người phụ nữ có bao nhiêu pháp mà sau khi thân hoại mạng chung tái sinh vào cõi lành, cõi trời?' ",
  "sn37.15:2.1": "'Này Anuruddha, người phụ nữ có năm pháp thì sau khi thân hoại mạng chung tái sinh vào cõi lành, cõi trời. '",
  "sn37.15:2.2": "Đó là năm pháp nào? ",
  "sn37.15:2.3": "Có lòng tin, biết hổ thẹn, sợ tội lỗi, không hay giận, và có trí tuệ",
  "sn37.15:2.4": "Này Anuruddha, người phụ nữ có năm pháp này thì sau khi thân hoại mạng chung tái sinh vào cõi lành, cõi trời.' ",
  "sn37.15:2.5": "Thứ nhất. ",
  "sn37.16:0.1": "Tương Ưng Bộ 37.16 ",
  "sn37.16:0.2": "2. Phẩm Peyyāla Thứ Hai ",
  "sn37.16:0.3": "Kinh Người Không Hay Thù Hận ",
  "sn37.16:1.1": "'Này Anuruddha, người phụ nữ có năm pháp thì sau khi thân hoại mạng chung tái sinh vào cõi lành, cõi trời. '",
  "sn37.16:1.2": "Đó là năm pháp nào? ",
  "sn37.16:1.3": "Có lòng tin, biết hổ thẹn, sợ tội lỗi, không hay thù hận, và có trí tuệ",
  "sn37.16:1.4": "Này Anuruddha, người phụ nữ có năm pháp này thì sau khi thân hoại mạng chung tái sinh vào cõi lành, cõi trời.' ",
  "sn37.16:1.5": "Thứ hai. ",
  "sn37.17:0.1": "Tương Ưng Bộ 37.17 ",
  "sn37.17:0.2": "2. Phẩm Peyyāla Thứ Hai ",
  "sn37.17:0.3": "Kinh Người Không Hay Ganh Tị ",
  "sn37.17:1.1": "'Này Anuruddha, người phụ nữ có năm pháp thì sau khi thân hoại mạng chung tái sinh vào cõi lành, cõi trời. '",
  "sn37.17:1.2": "Đó là năm pháp nào? ",
  "sn37.17:1.3": "Có lòng tin, biết hổ thẹn, sợ tội lỗi, không hay ganh tị, và có trí tuệ …(lược)…. ",
  "sn37.17:1.4": "Thứ ba. ",
  "sn37.18:0.1": "Tương Ưng Bộ 37.18 ",
  "sn37.18:0.2": "2. Phẩm Peyyāla Thứ Hai ",
  "sn37.18:0.3": "Kinh Người Không Hay Bủn Xỉn ",
  "sn37.18:1.1": "'Không hay bủn xỉn và có trí tuệ …(lược)…. '",
  "sn37.18:1.2": "Thứ tư. ",
  "sn37.19:0.1": "Tương Ưng Bộ 37.19 ",
  "sn37.19:0.2": "2. Phẩm Peyyāla Thứ Hai ",
  "sn37.19:0.3": "Kinh Người Không Tà Hạnh ",
  "sn37.19:1.1": "'Không tà hạnh và có trí tuệ …(lược)…. '",
  "sn37.19:1.2": "Thứ năm. ",
  "sn37.20:0.1": "Tương Ưng Bộ 37.20 ",
  "sn37.20:0.2": "2. Phẩm Peyyāla Thứ Hai ",
  "sn37.20:0.3": "Kinh Người Có Giới Hạnh ",
  "sn37.20:1.1": "'Có giới hạnh và có trí tuệ …(lược)…. '",
  "sn37.20:1.2": "Thứ sáu. ",
  "sn37.21:0.1": "Tương Ưng Bộ 37.21 ",
  "sn37.21:0.2": "2. Phẩm Peyyāla Thứ Hai ",
  "sn37.21:0.3": "Kinh Người Đa Văn ",
  "sn37.21:1.1": "'Đa văn và có trí tuệ …(lược)…. '",
  "sn37.21:1.2": "Thứ bảy. ",
  "sn37.22:0.1": "Tương Ưng Bộ 37.22 ",
  "sn37.22:0.2": "2. Phẩm Peyyāla Thứ Hai ",
  "sn37.22:0.3": "Kinh Người Tinh Tấn ",
  "sn37.22:1.1": "'Tinh tấn và có trí tuệ …(lược)…. '",
  "sn37.22:1.2": "Thứ tám. ",
  "sn37.23:0.1": "Tương Ưng Bộ 37.23 ",
  "sn37.23:0.2": "2. Phẩm Peyyāla Thứ Hai ",
  "sn37.23:0.3": "Kinh Người Có Chánh Niệm ",
  "sn37.23:1.1": "'Có chánh niệm và có trí tuệ …(lược)… '",
  "sn37.23:1.2": "Này Anuruddha, người phụ nữ có năm pháp này thì sau khi thân hoại mạng chung tái sinh vào cõi lành, cõi trời.' ",
  "sn37.23:1.3": "Thứ chín. ",
  "sn37.23:2.1": "Tám kinh này được tóm lược. ",
  "sn37.24:0.1": "Tương Ưng Bộ 37.24 ",
  "sn37.24:0.2": "2. Phẩm Peyyāla Thứ Hai ",
  "sn37.24:0.3": "Kinh Năm Giới ",
  "sn37.24:1.1": "'Này Anuruddha, người phụ nữ có năm pháp thì sau khi thân hoại mạng chung tái sinh vào cõi lành, cõi trời. '",
  "sn37.24:1.2": "Đó là năm pháp nào? ",
  "sn37.24:1.3": "Từ bỏ sát hại sinh vật, từ bỏ trộm cắp, từ bỏ tà dâm, từ bỏ nói dối, và từ bỏ uống rượu say",
  "sn37.24:1.4": "Này Anuruddha, người phụ nữ có năm pháp này thì sau khi thân hoại mạng chung tái sinh vào cõi lành, cõi trời.' ",
  "sn37.24:1.5": "Thứ mười. ",
  "sn37.24:1.6": "Phẩm Peyyāla Thứ Hai. ",
  "sn37.24:2.0": "Tóm tắt phẩm ",
  "sn37.24:2.1": "Phẩm hai: không hay giận, ",
  "sn37.24:2.2": "không hay thù hận, không hay ganh tị; ",
  "sn37.24:2.3": "Không hay bủn xỉn, không tà hạnh, ",
  "sn37.24:2.4": "có giới hạnh và đa văn; ",
  "sn37.24:2.5": "Tinh tấn, chánh niệm và giới hạnh, ",
  "sn37.24:2.6": "được giảng rõ thuộc phần sáng. ",
  "sn37.25:0.1": "Tương Ưng Bộ 37.25 ",
  "sn37.25:0.2": "3. Phẩm Sức Mạnh ",
  "sn37.25:0.3": "Kinh Tự Tin ",
  "sn37.25:1.1": "'Này các Tỳ Kheo, người phụ nữ có năm sức mạnh. '",
  "sn37.25:1.2": "Đó là năm sức mạnh nào? ",
  "sn37.25:1.3": "Sức mạnh sắc đẹp, sức mạnh của cải, sức mạnh thân quyến, sức mạnh con cái, sức mạnh giới hạnh",
  "sn37.25:1.4": "Này các Tỳ Kheo, đây là năm sức mạnh của người phụ nữ. ",
  "sn37.25:1.5": "Này các Tỳ Kheo, người phụ nữ có đủ năm sức mạnh này thì sống trong nhà với sự tự tin.' ",
  "sn37.25:1.6": "Thứ nhất. ",
  "sn37.26:0.1": "Tương Ưng Bộ 37.26 ",
  "sn37.26:0.2": "3. Phẩm Sức Mạnh ",
  "sn37.26:0.3": "Kinh Áp Đảo ",
  "sn37.26:1.1": "'Này các Tỳ Kheo, người phụ nữ có năm sức mạnh. '",
  "sn37.26:1.2": "Đó là năm sức mạnh nào? ",
  "sn37.26:1.3": "Sức mạnh sắc đẹp, sức mạnh của cải, sức mạnh thân quyến, sức mạnh con cái, sức mạnh giới hạnh",
  "sn37.26:1.4": "Này các Tỳ Kheo, đây là năm sức mạnh của người phụ nữ. ",
  "sn37.26:1.5": "Này các Tỳ Kheo, người phụ nữ có đủ năm sức mạnh này thì sống trong nhà bằng cách áp đảo người chồng.' ",
  "sn37.26:1.6": "Thứ hai. ",
  "sn37.27:0.1": "Tương Ưng Bộ 37.27 ",
  "sn37.27:0.2": "3. Phẩm Sức Mạnh ",
  "sn37.27:0.3": "Kinh Thống Trị ",
  "sn37.27:1.1": "'Này các Tỳ Kheo, người phụ nữ có năm sức mạnh. '",
  "sn37.27:1.2": "Đó là năm sức mạnh nào? ",
  "sn37.27:1.3": "Sức mạnh sắc đẹp, sức mạnh của cải, sức mạnh thân quyến, sức mạnh con cái, sức mạnh giới hạnh",
  "sn37.27:1.4": "Này các Tỳ Kheo, đây là năm sức mạnh của người phụ nữ. ",
  "sn37.27:1.5": "Này các Tỳ Kheo, người phụ nữ có đủ năm sức mạnh này thì thống trị người chồng.' ",
  "sn37.27:1.6": "Thứ ba. ",
  "sn37.28:0.1": "Tương Ưng Bộ 37.28 ",
  "sn37.28:0.2": "3. Phẩm Sức Mạnh ",
  "sn37.28:0.3": "Kinh Một Điều ",
  "sn37.28:1.1": "'Này các Tỳ Kheo, người đàn ông với một sức mạnh thì thống trị người phụ nữ. '",
  "sn37.28:1.2": "Đó là một sức mạnh nào? ",
  "sn37.28:1.3": "Người phụ nữ bị thống trị bởi sức mạnh quyền uy thì sức mạnh sắc đẹp không bảo vệ được, sức mạnh của cải không bảo vệ được, sức mạnh thân quyến không bảo vệ được, sức mạnh con cái không bảo vệ được, sức mạnh giới hạnh cũng không bảo vệ được.' ",
  "sn37.28:1.4": "Thứ tư. ",
  "sn37.29:0.1": "Tương Ưng Bộ 37.29 ",
  "sn37.29:0.2": "3. Phẩm Sức Mạnh ",
  "sn37.29:0.3": "Kinh Các Đặc Tính ",
  "sn37.29:1.1": "'Này các Tỳ Kheo, người phụ nữ có năm sức mạnh. '",
  "sn37.29:1.2": "Đó là năm sức mạnh nào? ",
  "sn37.29:1.3": "Sức mạnh sắc đẹp, sức mạnh của cải, sức mạnh thân quyến, sức mạnh con cái, sức mạnh giới hạnh. ",
  "sn37.29:1.4": "Này các Tỳ Kheo, người phụ nữ có sức mạnh sắc đẹp mà không có sức mạnh của cải",
  "sn37.29:1.5": "thì người ấy không đầy đủ về đặc tính đó. ",
  "sn37.29:1.6": "Này các Tỳ Kheo, khi người phụ nữ có sức mạnh sắc đẹp và có cả sức mạnh của cải",
  "sn37.29:1.7": "thì người ấy đầy đủ về đặc tính đó. ",
  "sn37.29:1.8": "Này các Tỳ Kheo, người phụ nữ có sức mạnh sắc đẹp, có sức mạnh của cải, mà không có sức mạnh thân quyến",
  "sn37.29:1.9": "thì người ấy không đầy đủ về đặc tính đó. ",
  "sn37.29:1.10": "Này các Tỳ Kheo, khi người phụ nữ có sức mạnh sắc đẹp, có sức mạnh của cải, và có sức mạnh thân quyến",
  "sn37.29:1.11": "thì người ấy đầy đủ về đặc tính đó. ",
  "sn37.29:1.12": "Này các Tỳ Kheo, người phụ nữ có sức mạnh sắc đẹp, của cải, thân quyến, mà không có sức mạnh con cái",
  "sn37.29:1.13": "thì người ấy không đầy đủ về đặc tính đó. ",
  "sn37.29:1.14": "Này các Tỳ Kheo, khi người phụ nữ có sức mạnh sắc đẹp, của cải, thân quyến, và có sức mạnh con cái",
  "sn37.29:1.15": "thì người ấy đầy đủ về đặc tính đó. ",
  "sn37.29:1.16": "Này các Tỳ Kheo, người phụ nữ có sức mạnh sắc đẹp, của cải, thân quyến, con cái, mà không có sức mạnh giới hạnh",
  "sn37.29:1.17": "thì người ấy không đầy đủ về đặc tính đó. ",
  "sn37.29:1.18": "Này các Tỳ Kheo, khi người phụ nữ có sức mạnh sắc đẹp, của cải, thân quyến, con cái, và có sức mạnh giới hạnh",
  "sn37.29:1.19": "thì người ấy đầy đủ về đặc tính đó. ",
  "sn37.29:1.20": "Này các Tỳ Kheo, đây là năm sức mạnh của người phụ nữ.' ",
  "sn37.29:1.21": "Thứ năm. ",
  "sn37.30:0.1": "Tương Ưng Bộ 37.30 ",
  "sn37.30:0.2": "3. Phẩm Sức Mạnh ",
  "sn37.30:0.3": "Kinh Bị Đuổi ",
  "sn37.30:1.1": "'Này các Tỳ Kheo, người phụ nữ có năm sức mạnh. '",
  "sn37.30:1.2": "Đó là năm sức mạnh nào? ",
  "sn37.30:1.3": "Sức mạnh sắc đẹp, sức mạnh của cải, sức mạnh thân quyến, sức mạnh con cái, sức mạnh giới hạnh. ",
  "sn37.30:1.4": "Này các Tỳ Kheo, người phụ nữ có sức mạnh sắc đẹp mà không có giới hạnh, thì người ta đuổi đi, không cho ở trong nhà. ",
  "sn37.30:1.5": "Này các Tỳ Kheo, người phụ nữ có sức mạnh sắc đẹp, của cải, mà không có giới hạnh, thì người ta đuổi đi, không cho ở trong nhà. ",
  "sn37.30:1.6": "Này các Tỳ Kheo, người phụ nữ có sức mạnh sắc đẹp, của cải, thân quyến, mà không có giới hạnh, thì người ta đuổi đi, không cho ở trong nhà. ",
  "sn37.30:1.7": "Này các Tỳ Kheo, người phụ nữ có sức mạnh sắc đẹp, của cải, thân quyến, con cái, mà không có giới hạnh, thì người ta đuổi đi, không cho ở trong nhà. ",
  "sn37.30:1.8": "Này các Tỳ Kheo, người phụ nữ có giới hạnh mà không có sắc đẹp, thì người ta vẫn cho ở, không đuổi đi. ",
  "sn37.30:1.9": "Này các Tỳ Kheo, người phụ nữ có giới hạnh mà không có của cải, thì người ta vẫn cho ở, không đuổi đi. ",
  "sn37.30:1.10": "Này các Tỳ Kheo, người phụ nữ có giới hạnh mà không có thân quyến, thì người ta vẫn cho ở, không đuổi đi. ",
  "sn37.30:1.11": "Này các Tỳ Kheo, người phụ nữ có giới hạnh mà không có con cái, thì người ta vẫn cho ở, không đuổi đi. ",
  "sn37.30:1.12": "Này các Tỳ Kheo, đây là năm sức mạnh của người phụ nữ.' ",
  "sn37.30:1.13": "Thứ sáu. ",
  "sn37.31:0.1": "Tương Ưng Bộ 37.31 ",
  "sn37.31:0.2": "3. Phẩm Sức Mạnh ",
  "sn37.31:0.3": "Kinh Nguyên Nhân ",
  "sn37.31:1.1": "'Này các Tỳ Kheo, người phụ nữ có năm sức mạnh. '",
  "sn37.31:1.2": "Đó là năm sức mạnh nào? ",
  "sn37.31:1.3": "Sức mạnh sắc đẹp, sức mạnh của cải, sức mạnh thân quyến, sức mạnh con cái, sức mạnh giới hạnh. ",
  "sn37.31:1.4": "Này các Tỳ Kheo, người phụ nữ không nhờ sức mạnh sắc đẹp, hay sức mạnh của cải, hay sức mạnh thân quyến, hay sức mạnh con cái mà sau khi thân hoại mạng chung tái sinh vào cõi lành, cõi trời. ",
  "sn37.31:1.5": "Này các Tỳ Kheo, chính nhờ sức mạnh giới hạnh mà người phụ nữ sau khi thân hoại mạng chung tái sinh vào cõi lành, cõi trời. ",
  "sn37.31:1.6": "Này các Tỳ Kheo, đây là năm sức mạnh của người phụ nữ.' ",
  "sn37.31:1.7": "Thứ bảy. ",
  "sn37.32:0.1": "Tương Ưng Bộ 37.32 ",
  "sn37.32:0.2": "3. Phẩm Sức Mạnh ",
  "sn37.32:0.3": "Kinh Cơ Hội ",
  "sn37.32:1.1": "'Này các Tỳ Kheo, có năm cơ hội khó có được đối với người phụ nữ không có phước đức. '",
  "sn37.32:1.2": "Đó là năm cơ hội nào? ",
  "sn37.32:1.3": "Được sinh vào gia đình xứng đáng",
  "sn37.32:1.4": "Này các Tỳ Kheo, đây là cơ hội thứ nhất khó có được đối với người phụ nữ không có phước đức. ",
  "sn37.32:1.5": "Sau khi sinh vào gia đình xứng đáng, được về gia đình chồng xứng đáng",
  "sn37.32:1.6": "Này các Tỳ Kheo, đây là cơ hội thứ hai khó có được đối với người phụ nữ không có phước đức. ",
  "sn37.32:1.7": "Sau khi sinh vào gia đình xứng đáng, về gia đình chồng xứng đáng, sống trong nhà không có vợ lẽ",
  "sn37.32:1.8": "Này các Tỳ Kheo, đây là cơ hội thứ ba khó có được đối với người phụ nữ không có phước đức. ",
  "sn37.32:1.9": "Sau khi sinh vào gia đình xứng đáng, về gia đình chồng xứng đáng, sống trong nhà không có vợ lẽ, và có con trai",
  "sn37.32:1.10": "Này các Tỳ Kheo, đây là cơ hội thứ tư khó có được đối với người phụ nữ không có phước đức. ",
  "sn37.32:1.11": "Sau khi sinh vào gia đình xứng đáng, về gia đình chồng xứng đáng, sống trong nhà không có vợ lẽ, có con trai, và thống trị người chồng",
  "sn37.32:1.12": "Này các Tỳ Kheo, đây là cơ hội thứ năm khó có được đối với người phụ nữ không có phước đức. ",
  "sn37.32:1.13": "Này các Tỳ Kheo, đây là năm cơ hội khó có được đối với người phụ nữ không có phước đức. ",
  "sn37.32:2.1": "Này các Tỳ Kheo, có năm cơ hội dễ có được đối với người phụ nữ có phước đức. ",
  "sn37.32:2.2": "Đó là năm cơ hội nào? ",
  "sn37.32:2.3": "Được sinh vào gia đình xứng đáng",
  "sn37.32:2.4": "Này các Tỳ Kheo, đây là cơ hội thứ nhất dễ có được đối với người phụ nữ có phước đức. ",
  "sn37.32:2.5": "Sau khi sinh vào gia đình xứng đáng, được về gia đình chồng xứng đáng",
  "sn37.32:2.6": "Này các Tỳ Kheo, đây là cơ hội thứ hai dễ có được đối với người phụ nữ có phước đức. ",
  "sn37.32:2.7": "Sau khi sinh vào gia đình xứng đáng, về gia đình chồng xứng đáng, sống trong nhà không có vợ lẽ",
  "sn37.32:2.8": "Này các Tỳ Kheo, đây là cơ hội thứ ba dễ có được đối với người phụ nữ có phước đức. ",
  "sn37.32:2.9": "Sau khi sinh vào gia đình xứng đáng, về gia đình chồng xứng đáng, sống trong nhà không có vợ lẽ, và có con trai",
  "sn37.32:2.10": "Này các Tỳ Kheo, đây là cơ hội thứ tư dễ có được đối với người phụ nữ có phước đức. ",
  "sn37.32:2.11": "Sau khi sinh vào gia đình xứng đáng, về gia đình chồng xứng đáng, sống trong nhà không có vợ lẽ, có con trai, và thống trị người chồng",
  "sn37.32:2.12": "Này các Tỳ Kheo, đây là cơ hội thứ năm dễ có được đối với người phụ nữ có phước đức. ",
  "sn37.32:2.13": "Này các Tỳ Kheo, đây là năm cơ hội dễ có được đối với người phụ nữ có phước đức.' ",
  "sn37.32:2.14": "Thứ tám. ",
  "sn37.33:0.1": "Tương Ưng Bộ 37.33 ",
  "sn37.33:0.2": "3. Phẩm Sức Mạnh ",
  "sn37.33:0.3": "Kinh Tự Tin Với Năm Giới ",
  "sn37.33:1.1": "'Này các Tỳ Kheo, người phụ nữ có năm pháp thì sống trong nhà với sự tự tin. '",
  "sn37.33:1.2": "Đó là năm pháp nào? ",
  "sn37.33:1.3": "Từ bỏ sát hại sinh vật, từ bỏ trộm cắp, từ bỏ tà dâm, từ bỏ nói dối, và từ bỏ uống rượu say",
  "sn37.33:1.4": "Này các Tỳ Kheo, người phụ nữ có năm pháp này thì sống trong nhà với sự tự tin.' ",
  "sn37.33:1.5": "Thứ chín. ",
  "sn37.34:0.1": "Tương Ưng Bộ 37.34 ",
  "sn37.34:0.2": "3. Phẩm Sức Mạnh ",
  "sn37.34:0.3": "Kinh Tăng Trưởng ",
  "sn37.34:1.1": "'Này các Tỳ Kheo, người nữ đệ tử bậc thánh tăng trưởng với năm sự tăng trưởng thì tăng trưởng bằng sự tăng trưởng bậc thánh, nhận được tinh hoa và nhận được điều tốt lành cho thân. '",
  "sn37.34:1.2": "Đó là năm sự tăng trưởng nào? ",
  "sn37.34:1.3": "Tăng trưởng bằng lòng tin, tăng trưởng bằng giới hạnh, tăng trưởng bằng học hỏi, tăng trưởng bằng bố thí, tăng trưởng bằng trí tuệ",
  "sn37.34:1.4": "Này các Tỳ Kheo, người nữ đệ tử bậc thánh tăng trưởng với năm sự tăng trưởng này thì tăng trưởng bằng sự tăng trưởng bậc thánh, nhận được tinh hoa và nhận được điều tốt lành cho thân. ",
  "sn37.34:2.1": "Ai ở đây tăng trưởng bằng lòng tin và giới hạnh, ",
  "sn37.34:2.2": "bằng trí tuệ, bố thí, và cả học hỏi; ",
  "sn37.34:2.3": "Người nữ cư sĩ có giới hạnh như vậy, ",
  "sn37.34:2.4": "nhận được tinh hoa ngay trong đời này. ",
  "sn37.34:2.5": "Thứ mười. ",
  "sn37.34:2.6": "Phẩm Sức Mạnh, phẩm thứ ba. ",
  "sn37.34:3.0": "Tóm tắt phẩm ",
  "sn37.34:3.1": "Tự tin, áp đảo, thống trị, ",
  "sn37.34:3.2": "một điều và các đặc tính, thứ năm; ",
  "sn37.34:3.3": "Bị đuổi, nguyên nhân và cơ hội, ",
  "sn37.34:3.4": "tự tin và tăng trưởng, mười bài. ",
  "sn37.34:3.5": "Kết thúc Tương Ưng về Người Phụ Nữ. "
}
window.BILARA["sn37_v1"]["vi"]["sn37_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
