window.BILARA = window.BILARA || {};
window.BILARA["sn8_v1"] = window.BILARA["sn8_v1"] || {};
window.BILARA["sn8_v1"]["vi"] = {
  "sn8.1:0.1": "Tương Ưng Bộ 8.1 ",
  "sn8.1:0.2": "1. Phẩm Vaṅgīsa ",
  "sn8.1:0.3": "Kinh Đã Xuất Gia ",
  "sn8.1:1.1": "Tôi nghe như vầy",
  "sn8.1:1.2": "Một thời Tôn giả Vaṅgīsa trú tại Āḷavī, ở điện thờ Aggāḷava, cùng với Tôn giả Nigrodhakappa, vị thầy tế độ. ",
  "sn8.1:1.3": "Lúc bấy giờ Tôn giả Vaṅgīsa còn là người mới xuất gia chẳng bao lâu, là người trông coi và ở lại tịnh xá. ",
  "sn8.1:1.4": "Rồi nhiều người phụ nữ trang điểm đẹp đẽ đi đến khu vườn Aggāḷava để xem tịnh xá. ",
  "sn8.1:1.5": "Rồi Tôn giả Vaṅgīsa, sau khi nhìn thấy những người phụ nữ ấy, sự không hài lòng khởi lên, tham ái khuấy động tâm. ",
  "sn8.1:1.6": "Rồi Tôn giả Vaṅgīsa suy nghĩ: ",
  "sn8.1:1.7": "'Thật bất hạnh cho ta, thật không phải may mắn cho ta; thật khó đạt được cho ta, thật không dễ đạt được cho ta; '",
  "sn8.1:1.8": "khi ta đã khởi lên sự không hài lòng, tham ái khuấy động tâmlàm sao có thể, ai đó mới xua tan sự không hài lòng và làm khởi lên sự hài lòng cho ta được. ",
  "sn8.1:1.9": "Vậy ta hãy tự mình xua tan sự không hài lòng và làm khởi lên sự hài lòng cho chính mình.' ",
  "sn8.1:1.10": "Rồi Tôn giả Vaṅgīsa, tự mình xua tan sự không hài lòng và làm khởi lên sự hài lòng cho chính mình, vào lúc đó đã đọc những bài kệ này: ",
  "sn8.1:2.1": "'Ta đã xuất gia thanh thản, '",
  "sn8.1:2.2": "từ gia đình đến không gia đình; ",
  "sn8.1:2.3": "Những tư duy cứ chạy theo, ",
  "sn8.1:2.4": "bạo dạn, từ phía tăm tối. ",
  "sn8.1:3.1": "Con của các bậc anh hùng, cung thủ tài ba, ",
  "sn8.1:3.2": "thiện xảo, vững chãi trong Pháp; ",
  "sn8.1:3.3": "Họ có thể bao vây tứ phía, ",
  "sn8.1:3.4": "hàng ngàn người không lui bước. ",
  "sn8.1:4.1": "Dù còn nhiều hơn thế nữa, ",
  "sn8.1:4.2": "nếu những người phụ nữ ấy đến; ",
  "sn8.1:4.3": "Họ sẽ không thể lay chuyển ta, ",
  "sn8.1:4.4": "người đã an trú trong Pháp. ",
  "sn8.1:5.1": "Chính ta đã nghe điều này, ",
  "sn8.1:5.2": "từ Đức Phật, bậc thân thuộc mặt trời; ",
  "sn8.1:5.3": "Con đường dẫn đến Niết-bàn, ",
  "sn8.1:5.4": "tâm ta hoan hỷ ở đó. ",
  "sn8.1:6.1": "Nếu ngươi đến gần ta, ",
  "sn8.1:6.2": "hỡi Ma vương, khi ta đang sống như vậy; ",
  "sn8.1:6.3": "Ta sẽ làm với ngươi như với cái chết, ",
  "sn8.1:6.4": "ngươi sẽ không thấy được đường đi của ta.' ",
  "sn8.2:0.1": "Tương Ưng Bộ 8.2 ",
  "sn8.2:0.2": "1. Phẩm Vaṅgīsa ",
  "sn8.2:0.3": "Kinh Không Hài Lòng ",
  "sn8.2:1.1": "Một thời… Tôn giả Vaṅgīsa trú tại Āḷavī, ở điện thờ Aggāḷava, cùng với Tôn giả Nigrodhakappa, vị thầy tế độ. ",
  "sn8.2:1.2": "Lúc bấy giờ Tôn giả Nigrodhakappa sau buổi khất thực trở về, vào tịnh xá buổi chiều, ra ngoài buổi tối hay buổi sáng sớm ngày hôm sau. ",
  "sn8.2:1.3": "Lúc bấy giờ Tôn giả Vaṅgīsa khởi lên sự không hài lòng, tham ái khuấy động tâm. ",
  "sn8.2:1.4": "Rồi Tôn giả Vaṅgīsa suy nghĩ: ",
  "sn8.2:1.5": "'Thật bất hạnh cho ta, thật không phải may mắn cho ta; thật khó đạt được cho ta, thật không dễ đạt được cho ta; '",
  "sn8.2:1.6": "khi ta đã khởi lên sự không hài lòng, tham ái khuấy động tâm; làm sao có thể, ai đó mới xua tan sự không hài lòng và làm khởi lên sự hài lòng cho ta được. ",
  "sn8.2:1.7": "Vậy ta hãy tự mình xua tan sự không hài lòng và làm khởi lên sự hài lòng cho chính mình.' ",
  "sn8.2:1.8": "Rồi Tôn giả Vaṅgīsa, tự mình xua tan sự không hài lòng và làm khởi lên sự hài lòng cho chính mình, vào lúc đó đã đọc những bài kệ này: ",
  "sn8.2:2.1": "'Hãy từ bỏ không hài lòng và hài lòng, '",
  "sn8.2:2.2": "Mọi tư duy bám víu vào nhà cửa; ",
  "sn8.2:2.3": "Chớ tạo ra sự vướng bận bất cứ đâu, ",
  "sn8.2:2.4": "Không vướng bận, không ham muốnđó là Tỳ Kheo. ",
  "sn8.2:3.1": "Những gì ở đây, trên đất, trên hư không, ",
  "sn8.2:3.2": "Những gì thuộc về sắc, trầm ngập trong thế gian; ",
  "sn8.2:3.3": "Bất cứ điều gì cũng tan rã, tất cả đều vô thường, ",
  "sn8.2:3.4": "Những người trí tuệ thấy vậy, sống như thế. ",
  "sn8.2:4.1": "Người ta bị ràng buộc vào các sở hữu, ",
  "sn8.2:4.2": "Vào những gì đã thấy, nghe, ngửi, nếm và suy nghĩ; ",
  "sn8.2:4.3": "Hãy xua tan ở đây sự ham muốn, không dao động, ",
  "sn8.2:4.4": "Người không bị vấy bẩn bởi đâyhọ gọi là bậc ẩn sĩ. ",
  "sn8.2:5.1": "Rồi sáu mươi loại tà tư duy, ",
  "sn8.2:5.2": "Bất thiện bám chặt vào nhiều người; ",
  "sn8.2:5.3": "Không bao giờ thuộc về ai theo phe phái, ",
  "sn8.2:5.4": "Cũng không phải Tỳ Kheo nói những lời thô lỗ. ",
  "sn8.2:6.1": "Dabba, đã thiền định lâu dài, ",
  "sn8.2:6.2": "Không lừa dối, sáng suốt, không tham lam; ",
  "sn8.2:6.3": "Bậc ẩn sĩ đã đạt đến trạng thái an tịnh, ",
  "sn8.2:6.4": "Đã viên tịch, chờ đợi thời gian.' ",
  "sn8.3:0.1": "Tương Ưng Bộ 8.3 ",
  "sn8.3:0.2": "1. Phẩm Vaṅgīsa ",
  "sn8.3:0.3": "Kinh Người Hiền Thiện ",
  "sn8.3:1.1": "Một thời Tôn giả Vaṅgīsa trú tại Āḷavī, ở điện thờ Aggāḷava, cùng với Tôn giả Nigrodhakappa, vị thầy tế độ. ",
  "sn8.3:1.2": "Lúc bấy giờ Tôn giả Vaṅgīsa do trí tuệ thơ ca của mình mà khinh thường các Tỳ Kheo hiền thiện khác. ",
  "sn8.3:1.3": "Rồi Tôn giả Vaṅgīsa suy nghĩ: ",
  "sn8.3:1.4": "'Thật bất hạnh cho ta, thật không phải may mắn cho ta; thật khó đạt được cho ta, thật không dễ đạt được cho ta; '",
  "sn8.3:1.5": "vì ta đã khinh thường các Tỳ Kheo hiền thiện khác do trí tuệ thơ ca của mình.' ",
  "sn8.3:1.6": "Rồi Tôn giả Vaṅgīsa, tự mình khởi lên sự ăn năn hối lỗi, vào lúc đó đã đọc những bài kệ này: ",
  "sn8.3:2.1": "'Hãy từ bỏ kiêu mạn, này Gotama, '",
  "sn8.3:2.2": "Và hãy từ bỏ con đường của kiêu mạn; ",
  "sn8.3:2.3": "Chìm đắm hoàn toàn trong con đường của kiêu mạn, ",
  "sn8.3:2.4": "Ngươi đã hối hận mãi lâu dài. ",
  "sn8.3:3.1": "Người ta bị vấy bẩn bởi sự ô nhiễm kiêu mạn, ",
  "sn8.3:3.2": "Bị kiêu mạn đánh gục, rơi vào địa ngục; ",
  "sn8.3:3.3": "Người ta sầu khổ lâu dài, ",
  "sn8.3:3.4": "Bị kiêu mạn đánh gục, tái sinh vào địa ngục. ",
  "sn8.3:4.1": "Tỳ Kheo không bao giờ sầu khổ, ",
  "sn8.3:4.2": "Người chiến thắng trên đường đạo, thực hành đúng đắn; ",
  "sn8.3:4.3": "Người hưởng được danh vọng và an lạc, ",
  "sn8.3:4.4": "Người thấy Pháphọ gọi là người tinh cần. ",
  "sn8.3:5.1": "Do vậy, ở đây hãy tinh cần không cứng nhắc, ",
  "sn8.3:5.2": "Thanh tịnh, đã từ bỏ các triền cái; ",
  "sn8.3:5.3": "Và từ bỏ kiêu mạn hoàn toàn, ",
  "sn8.3:5.4": "Người chấm dứt minh, đã tịch tĩnh.' ",
  "sn8.4:0.1": "Tương Ưng Bộ 8.4 ",
  "sn8.4:0.2": "1. Phẩm Vaṅgīsa ",
  "sn8.4:0.3": "Kinh Ānanda ",
  "sn8.4:1.1": "Một thời Tôn giả Ānanda trú tại Sāvatthī, trong rừng Jeta, vườn ông Anāthapiṇḍika. ",
  "sn8.4:1.2": "Rồi Tôn giả Ānanda vào buổi sáng sớm, mặc áo, mang y bát, đi vào Sāvatthī để khất thực, với Tôn giả Vaṅgīsa theo sau như người hầu. ",
  "sn8.4:1.3": "Lúc bấy giờ Tôn giả Vaṅgīsa khởi lên sự không hài lòng, tham ái khuấy động tâm. ",
  "sn8.4:1.4": "Rồi Tôn giả Vaṅgīsa ngỏ lời với Tôn giả Ānanda bằng bài kệ: ",
  "sn8.4:2.1": "'Con đang bị đốt cháy bởi dục ái, '",
  "sn8.4:2.2": "tâm con đang bừng cháy; ",
  "sn8.4:2.3": "Xin hãy nói cho con cách dập tắt, ",
  "sn8.4:2.4": "vì lòng từ bi, hỡi Gotama.' ",
  "sn8.4:3.1": "'Do nhận thức bị đảo lộn, '",
  "sn8.4:3.2": "tâm ngươi đang bừng cháy; ",
  "sn8.4:3.3": "Hãy tránh xa tướng đẹp đẽ, ",
  "sn8.4:3.4": "liên quan đến tham ái. ",
  "sn8.4:4.1": "Hãy thấy các hành là khác với ngã, ",
  "sn8.4:4.2": "là khổ, không phải là tự ngã; ",
  "sn8.4:4.3": "Hãy dập tắt ngọn lửa tham lớn, ",
  "sn8.4:4.4": "chớ để bị đốt cháy mãi mãi. ",
  "sn8.4:5.1": "Hãy tu tập tâm với bất tịnh quán, ",
  "sn8.4:5.2": "nhất tâm, khéo định tĩnh; ",
  "sn8.4:5.3": "Hãy có chánh niệm về thân, ",
  "sn8.4:5.4": "hãy nhiều nhàm chán. ",
  "sn8.4:6.1": "Hãy tu tập vô tướng quán, ",
  "sn8.4:6.2": "hãy từ bỏ tùy miên ngã mạn; ",
  "sn8.4:6.3": "Rồi do thắng tri ngã mạn, ",
  "sn8.4:6.4": "ngươi sẽ sống an tịnh.' ",
  "sn8.5:0.1": "Tương Ưng Bộ 8.5 ",
  "sn8.5:0.2": "1. Phẩm Vaṅgīsa ",
  "sn8.5:0.3": "Kinh Lời Nói Khéo ",
  "sn8.5:1.1": "Nhân duyên ở Sāvatthī. ",
  "sn8.5:1.2": "Ở đó, Thế Tôn gọi các Tỳ Kheo: ",
  "sn8.5:1.3": "'Này các Tỳ Kheo.' ",
  "sn8.5:1.4": "'Bạch Thế Tôn,' các Tỳ Kheo ấy đáp lại Thế Tôn. ",
  "sn8.5:1.5": "Thế Tôn dạy điều này: ",
  "sn8.5:2.1": "'Này các Tỳ Kheo, lời nói được đầy đủ bốn yếu tố là lời nói khéo, không phải lời nói vụng; không lỗi và không đáng bị trách bởi người trí. '",
  "sn8.5:2.2": "Là bốn yếu tố gì? ",
  "sn8.5:2.3": "Ở đây, này các Tỳ Kheo, Tỳ Kheo chỉ nói những gì khéo, không nói những gì vụng; chỉ nói Pháp, không nói phi Pháp; chỉ nói những gì dễ thương, không nói những gì không dễ thương; chỉ nói sự thật, không nói điều không thật. ",
  "sn8.5:2.4": "Này các Tỳ Kheo, lời nói được đầy đủ bốn yếu tố này là lời nói khéo, không phải lời nói vụng, không lỗi và không đáng bị trách bởi người trí.' ",
  "sn8.5:2.5": "Thế Tôn đã dạy điều này. ",
  "sn8.5:2.6": "Đã nói điều này, bậc Thiện Thệ, bậc Đạo Sư còn nói thêm điều này: ",
  "sn8.5:3.1": "'Người hiền nói lời nói khéo là tối thượng, '",
  "sn8.5:3.2": "Thứ hai là nói Pháp, không phải phi Pháp; ",
  "sn8.5:3.3": "Thứ ba là nói dễ thương, không phải không dễ thương, ",
  "sn8.5:3.4": "Thứ tư là nói thật, không nói dối.' ",
  "sn8.5:4.1": "Rồi Tôn giả Vaṅgīsa đứng dậy từ chỗ ngồi, đắp y một bên vai, chắp tay hướng về Thế Tôn và thưa với Thế Tôn: ",
  "sn8.5:4.2": "'Bạch Thế Tôn, con cảm hứng, bạch Đấng Thiện Thệ, con cảm hứng.' ",
  "sn8.5:4.3": "'Hãy nói lên, Vaṅgīsa,' Thế Tôn nói. ",
  "sn8.5:4.4": "Rồi Tôn giả Vaṅgīsa tán thán Thế Tôn bằng những bài kệ thích hợp trước mặt Ngài: ",
  "sn8.5:5.1": "'Chỉ nên nói những lời nói '",
  "sn8.5:5.2": "không làm khổ tự thân; ",
  "sn8.5:5.3": "Và không gây tổn hại kẻ khác, ",
  "sn8.5:5.4": "đó thực là lời nói khéo. ",
  "sn8.5:6.1": "Chỉ nên nói lời dễ thương, ",
  "sn8.5:6.2": "lời được hoan nghênh; ",
  "sn8.5:6.3": "Những gì không chấp nhận điều ác, ",
  "sn8.5:6.4": "nói điều dễ thương với người khác. ",
  "sn8.5:7.1": "Lời thật là lời bất tử, ",
  "sn8.5:7.2": "đó là pháp từ thuở xưa; ",
  "sn8.5:7.3": "Trong sự thật, trong nghĩa và trong Pháp, ",
  "sn8.5:7.4": "người hiền nói là được an trú. ",
  "sn8.5:8.1": "Lời Phật nói ",
  "sn8.5:8.2": "an toàn, để đạt Niết-bàn; ",
  "sn8.5:8.3": "Để chấm dứt khổ đau, ",
  "sn8.5:8.4": "đó thực là tối thượng trong các lời nói.' ",
  "sn8.6:0.1": "Tương Ưng Bộ 8.6 ",
  "sn8.6:0.2": "1. Phẩm Vaṅgīsa ",
  "sn8.6:0.3": "Kinh Sāriputta ",
  "sn8.6:1.1": "Một thời Tôn giả Sāriputta trú tại Sāvatthī, trong rừng Jeta, vườn ông Anāthapiṇḍika. ",
  "sn8.6:1.2": "Lúc bấy giờ Tôn giả Sāriputta đang chỉ dạy, khuyến khích, khích lệ và làm cho các Tỳ Kheo hoan hỷ bằng bài Pháp thoại, với lời nói thanh lịch, rõ ràng, không rườm rà, có thể truyền đạt ý nghĩa. ",
  "sn8.6:1.3": "Các Tỳ Kheo ấy lắng nghe Pháp với sự chú tâm, hướng tâm và chú ý với toàn bộ tâm ý. ",
  "sn8.6:1.4": "Rồi Tôn giả Vaṅgīsa suy nghĩ: ",
  "sn8.6:1.5": "'Tôn giả Sāriputta đang chỉ dạy, khuyến khích, khích lệ và làm cho các Tỳ Kheo hoan hỷ bằng bài Pháp thoại, với lời nói thanh lịch, rõ ràng, không rườm rà, có thể truyền đạt ý nghĩa. '",
  "sn8.6:1.6": "Các Tỳ Kheo ấy lắng nghe Pháp với sự chú tâm, hướng tâm và chú ý với toàn bộ tâm ý. ",
  "sn8.6:1.7": "Vậy ta hãy tán thán Tôn giả Sāriputta bằng những bài kệ thích hợp trước mặt Ngài.' ",
  "sn8.6:2.1": "Rồi Tôn giả Vaṅgīsa đứng dậy từ chỗ ngồi, đắp y một bên vai, chắp tay hướng về Tôn giả Sāriputta và thưa: ",
  "sn8.6:2.2": "'Bạch hiền giả Sāriputta, con cảm hứng, bạch hiền giả Sāriputta, con cảm hứng.' ",
  "sn8.6:2.3": "'Hãy nói lên, này hiền giả Vaṅgīsa.' ",
  "sn8.6:2.4": "Rồi Tôn giả Vaṅgīsa tán thán Tôn giả Sāriputta bằng những bài kệ thích hợp trước mặt Ngài: ",
  "sn8.6:3.1": "'Tuệ sâu xa, người trí tuệ, '",
  "sn8.6:3.2": "thiện xảo về đạo và phi đạo; ",
  "sn8.6:3.3": "Sāriputta đại trí tuệ, ",
  "sn8.6:3.4": "giảng Pháp cho các Tỳ Kheo. ",
  "sn8.6:4.1": "Ngài giảng vắn tắt, ",
  "sn8.6:4.2": "cũng nói rộng rãi; ",
  "sn8.6:4.3": "Như tiếng hót của chim sáo, ",
  "sn8.6:4.4": "phát ra sự hứng khởi. ",
  "sn8.6:5.1": "Khi Ngài giảng dạy như vậy, ",
  "sn8.6:5.2": "các Tỳ Kheo lắng nghe giọng nói ngọt ngào; ",
  "sn8.6:5.3": "Với giọng hấp dẫn, ",
  "sn8.6:5.4": "đáng được lắng nghe, dịu dàng; ",
  "sn8.6:5.5": "Tâm vui vẻ, hoan hỷ, ",
  "sn8.6:5.6": "các Tỳ Kheo lắng tai nghe.' ",
  "sn8.7:0.1": "Tương Ưng Bộ 8.7 ",
  "sn8.7:0.2": "1. Phẩm Vaṅgīsa ",
  "sn8.7:0.3": "Kinh Tự Tứ ",
  "sn8.7:1.1": "Một thời Thế Tôn trú tại Sāvatthī, ở Đông Viên, tại lầu của mẫu thân Migāra, cùng với đại chúng Tỳ Kheo khoảng năm trăm vị, tất cả đều là bậc A-la-hán. ",
  "sn8.7:1.2": "Lúc bấy giờ, vào ngày Tự Tứ, ngày rằm tháng đó, Thế Tôn ngồi ngoài trời giữa vòng vây của chúng Tăng. ",
  "sn8.7:1.3": "Rồi Thế Tôn nhìn quanh chúng Tăng đang im lặng và gọi các Tỳ Kheo: ",
  "sn8.7:1.4": "'Nào các Tỳ Kheo, bây giờ ta mời chư vị tự tứ. '",
  "sn8.7:1.5": "Chư vị hãy trách cứ ta nếu có điều gì về thân hay lời nói.' ",
  "sn8.7:2.1": "Được nói như vậy, Tôn giả Sāriputta đứng dậy từ chỗ ngồi, đắp y một bên vai, chắp tay hướng về Thế Tôn và thưa: ",
  "sn8.7:2.2": "'Bạch Thế Tôn, chúng con không tìm thấy bất kỳ điều gì để trách cứ Thế Tôn về thân hay lời nói. '",
  "sn8.7:2.3": "Vì Thế Tôn, bạch Thế Tôn, là người khai mở con đường chưa được khai mở, người tạo ra con đường chưa được tạo ra, người tuyên thuyết con đường chưa được tuyên thuyết; Ngài biết đường, thấy đường, thiện xảo về đường. ",
  "sn8.7:2.4": "Và các đệ tử, bạch Thế Tôn, hiện đang đi theo con đường đó, theo sau; ",
  "sn8.7:2.5": "còn con, bạch Thế Tôn, con mời Thế Tôn tự tứ. ",
  "sn8.7:2.6": "Thế Tôn hãy trách cứ con nếu có điều gì về thân hay lời nói.' ",
  "sn8.7:3.1": "'Ta không tìm thấy bất kỳ điều gì để trách cứ ngươi về thân hay lời nói, này Sāriputta. '",
  "sn8.7:3.2": "Ngươi là người trí, này Sāriputta; ngươi có đại trí tuệ, này Sāriputta; ngươi có trí tuệ rộng lớn, này Sāriputta; ngươi có trí tuệ vui vẻ, này Sāriputta; ngươi có trí tuệ nhanh nhạy, này Sāriputta; ngươi có trí tuệ sắc bén, này Sāriputta; ngươi có trí tuệ thấu suốt, này Sāriputta. ",
  "sn8.7:3.3": "Ví như, này Sāriputta, trưởng tử của vua Chuyển luân vương lăn đúng bánh xe đã được vua cha lăn; ",
  "sn8.7:3.4": "cũng vậy, này Sāriputta, ngươi đã lăn đúng bánh xe Pháp vô thượng đã được ta lăn.' ",
  "sn8.7:4.1": "'Vậy, bạch Thế Tôn, Thế Tôn không tìm thấy bất kỳ điều gì để trách cứ con về thân hay lời nói. '",
  "sn8.7:4.2": "Vậy Thế Tôn có không tìm thấy bất kỳ điều gì để trách cứ năm trăm Tỳ Kheo này về thân hay lời nói không, bạch Thế Tôn?' ",
  "sn8.7:4.3": "'Ta cũng không tìm thấy bất kỳ điều gì để trách cứ năm trăm Tỳ Kheo này về thân hay lời nói, này Sāriputta. '",
  "sn8.7:4.4": "Này Sāriputta, trong số năm trăm Tỳ Kheo này, sáu mươi Tỳ Kheo là bậc tam minh, sáu mươi Tỳ Kheo là bậc lục thông, sáu mươi Tỳ Kheo là bậc câu phần giải thoát, còn những vị khác là bậc tuệ giải thoát.' ",
  "sn8.7:5.1": "Rồi Tôn giả Vaṅgīsa đứng dậy từ chỗ ngồi, đắp y một bên vai, chắp tay hướng về Thế Tôn và thưa: ",
  "sn8.7:5.2": "'Bạch Thế Tôn, con cảm hứng, bạch Đấng Thiện Thệ, con cảm hứng.' ",
  "sn8.7:5.3": "'Hãy nói lên, Vaṅgīsa,' Thế Tôn nói. ",
  "sn8.7:5.4": "Rồi Tôn giả Vaṅgīsa tán thán Thế Tôn bằng những bài kệ thích hợp trước mặt Ngài: ",
  "sn8.7:6.1": "'Ngày rằm thanh tịnh này, '",
  "sn8.7:6.2": "năm trăm Tỳ Kheo tụ họp; ",
  "sn8.7:6.3": "Đã cắt đứt những trói buộc của kiết sử, ",
  "sn8.7:6.4": "Các bậc ẩn sĩ không còn khổ não, đã đoạn tận tái sinh. ",
  "sn8.7:7.1": "Như vua Chuyển luân vương, ",
  "sn8.7:7.2": "được bao quanh bởi các quan đại thần; ",
  "sn8.7:7.3": "Đi khắp mọi nơi, ",
  "sn8.7:7.4": "trên vùng đất này đến tận biển. ",
  "sn8.7:8.1": "Vậy đây vị đã chiến thắng trận chiến, ",
  "sn8.7:8.2": "bậc dẫn đường vô thượng; ",
  "sn8.7:8.3": "Các đệ tử vây quanh hầu hạ, ",
  "sn8.7:8.4": "bậc tam minh, đã vượt qua cái chết. ",
  "sn8.7:9.1": "Tất cả đều là con của Thế Tôn, ",
  "sn8.7:9.2": "không có rơm rác ở đây; ",
  "sn8.7:9.3": "Con xin đảnh lễ chân ",
  "sn8.7:9.4": "bậc nhổ sạch mũi tên ái dục, bậc thân thuộc mặt trời.' ",
  "sn8.8:0.1": "Tương Ưng Bộ 8.8 ",
  "sn8.8:0.2": "1. Phẩm Vaṅgīsa ",
  "sn8.8:0.3": "Kinh Hơn Một Ngàn ",
  "sn8.8:1.1": "Một thời Thế Tôn trú tại Sāvatthī, trong rừng Jeta, vườn ông Anāthapiṇḍika, cùng với đại chúng Tỳ Kheo gồm một ngàn ba trăm rưỡi vị. ",
  "sn8.8:1.2": "Lúc bấy giờ Thế Tôn đang chỉ dạy, khuyến khích, khích lệ và làm cho các Tỳ Kheo hoan hỷ bằng bài Pháp thoại liên quan đến Niết-bàn. ",
  "sn8.8:1.3": "Các Tỳ Kheo ấy lắng nghe Pháp với sự chú tâm, hướng tâm và chú ý với toàn bộ tâm ý. ",
  "sn8.8:1.4": "Rồi Tôn giả Vaṅgīsa suy nghĩ: ",
  "sn8.8:1.5": "'Thế Tôn đang chỉ dạy, khuyến khích, khích lệ và làm cho các Tỳ Kheo hoan hỷ bằng bài Pháp thoại liên quan đến Niết-bàn. '",
  "sn8.8:1.6": "Các Tỳ Kheo ấy lắng nghe Pháp với sự chú tâm, hướng tâm và chú ý với toàn bộ tâm ý. ",
  "sn8.8:1.7": "Vậy ta hãy tán thán Thế Tôn bằng những bài kệ thích hợp trước mặt Ngài.' ",
  "sn8.8:2.1": "Rồi Tôn giả Vaṅgīsa đứng dậy từ chỗ ngồi, đắp y một bên vai, chắp tay hướng về Thế Tôn và thưa: ",
  "sn8.8:2.2": "'Bạch Thế Tôn, con cảm hứng, bạch Đấng Thiện Thệ, con cảm hứng.' ",
  "sn8.8:2.3": "'Hãy nói lên, Vaṅgīsa,' Thế Tôn nói. ",
  "sn8.8:2.4": "Rồi Tôn giả Vaṅgīsa tán thán Thế Tôn bằng những bài kệ thích hợp trước mặt Ngài: ",
  "sn8.8:3.1": "'Hơn một ngàn Tỳ Kheo, '",
  "sn8.8:3.2": "hầu hạ bậc Thiện Thệ; ",
  "sn8.8:3.3": "Ngài đang giảng Pháp thanh tịnh, ",
  "sn8.8:3.4": "Niết-bàn không có sợ hãi từ bất cứ đâu. ",
  "sn8.8:4.1": "Họ lắng nghe Pháp trong sạch, ",
  "sn8.8:4.2": "được Đức Phật Chánh Đẳng Giác giảng dạy; ",
  "sn8.8:4.3": "Thật rực rỡ thay bậc Chánh Đẳng Giác, ",
  "sn8.8:4.4": "được vây quanh bởi chúng Tỳ Kheo. ",
  "sn8.8:5.1": "Thế Tôn, Ngài có tên là Nāga, ",
  "sn8.8:5.2": "bậc thứ bảy trong các bậc ẩn sĩ; ",
  "sn8.8:5.3": "Như đám mây lớn, ",
  "sn8.8:5.4": "Ngài tưới mưa xuống các đệ tử. ",
  "sn8.8:6.1": "Rời thiền định buổi chiều, ",
  "sn8.8:6.2": "với ước muốn yết kiến bậc Đạo Sư; ",
  "sn8.8:6.3": "Vaṅgīsa, đệ tử của bậc Đại Hùng, ",
  "sn8.8:6.4": "đảnh lễ chân Ngài.' ",
  "sn8.8:7.1": "'Này Vaṅgīsa, các bài kệ này của ngươi được suy nghĩ từ trước hay đột nhiên hiện ra với ngươi?' ",
  "sn8.8:7.2": "'Bạch Thế Tôn, những bài kệ này không được con suy nghĩ từ trước, mà đột nhiên hiện ra với con.' ",
  "sn8.8:7.3": "'Vậy thì, Vaṅgīsa, hãy làm cho nhiều hơn nữa những bài kệ chưa từng được suy nghĩ từ trước hiện ra với ngươi.' ",
  "sn8.8:7.4": "'Thưa vâng, bạch Thế Tôn,' Tôn giả Vaṅgīsa vâng đáp Thế Tôn và làm cho nhiều hơn nữa những bài kệ chưa từng được suy nghĩ từ trước tán thán Thế Tôn: ",
  "sn8.8:8.1": "'Vượt qua con đường lầm lạc của Ma vương, '",
  "sn8.8:8.2": "Ngài đi, phá vỡ những cứng nhắc; ",
  "sn8.8:8.3": "Hãy nhìn Ngài, người giải thoát khỏi sự ràng buộc, ",
  "sn8.8:8.4": "Phân tích những gì chưa được tiêu hóa theo từng phần. ",
  "sn8.8:9.1": "Để vượt qua dòng lũ, ",
  "sn8.8:9.2": "Ngài đã tuyên thuyết con đường nhiều loại; ",
  "sn8.8:9.3": "Khi bất tử đã được tuyên thuyết đó, ",
  "sn8.8:9.4": "Những người thấy Pháp đứng vững, không lay chuyển. ",
  "sn8.8:10.1": "Bậc thắp sáng, thấu suốt, ",
  "sn8.8:10.2": "đã thấy vượt qua tất cả các trú xứ; ",
  "sn8.8:10.3": "Sau khi biết và trực tiếp chứng nghiệm, ",
  "sn8.8:10.4": "Ngài đã giảng điều tối thượng cho mười phương. ",
  "sn8.8:11.1": "Khi Pháp được giảng tốt như vậy, ",
  "sn8.8:11.2": "Ai là người biết Pháp mà phóng dật? ",
  "sn8.8:11.3": "Do vậy, trong lời dạy của Thế Tôn đó, ",
  "sn8.8:11.4": "Hãy không phóng dật, luôn kính lễ và học tập.' ",
  "sn8.9:0.1": "Tương Ưng Bộ 8.9 ",
  "sn8.9:0.2": "1. Phẩm Vaṅgīsa ",
  "sn8.9:0.3": "Kinh Koṇḍañña ",
  "sn8.9:1.1": "Một thời Thế Tôn trú tại Rājagaha, trong rừng tre, tại vườn sóc. ",
  "sn8.9:1.2": "Rồi Tôn giả Aññāsikoṇḍañña, sau một thời gian dài, đi đến chỗ Thế Tôn; đến rồi, quỳ xuống, đầu lạy chân Thế Tôn, hôn chân Thế Tôn bằng miệng, xoa chân Ngài bằng hai tay, và xưng tên mình: ",
  "sn8.9:1.3": "'Koṇḍañña là con, bạch Thế Tôn, Koṇḍañña là con, bạch Đấng Thiện Thệ.' ",
  "sn8.9:1.4": "Rồi Tôn giả Vaṅgīsa suy nghĩ: ",
  "sn8.9:1.5": "'Tôn giả Aññāsikoṇḍañña, sau một thời gian dài, đã đi đến chỗ Thế Tôn; đến rồi, quỳ xuống, đầu lạy chân Thế Tôn, hôn chân Thế Tôn bằng miệng, xoa chân Ngài bằng hai tay, và xưng tên mình: '",
  "sn8.9:1.6": "'Koṇḍañña là con, bạch Thế Tôn, Koṇḍañña là con, bạch Đấng Thiện Thệ.' ",
  "sn8.9:1.7": "Vậy ta hãy tán thán Tôn giả Aññāsikoṇḍañña bằng những bài kệ thích hợp trước mặt Thế Tôn.' ",
  "sn8.9:2.1": "Rồi Tôn giả Vaṅgīsa đứng dậy từ chỗ ngồi, đắp y một bên vai, chắp tay hướng về Thế Tôn và thưa: ",
  "sn8.9:2.2": "'Bạch Thế Tôn, con cảm hứng, bạch Đấng Thiện Thệ, con cảm hứng.' ",
  "sn8.9:2.3": "'Hãy nói lên, Vaṅgīsa,' Thế Tôn nói. ",
  "sn8.9:2.4": "Rồi Tôn giả Vaṅgīsa tán thán Tôn giả Aññāsikoṇḍañña bằng những bài kệ thích hợp trước mặt Thế Tôn: ",
  "sn8.9:3.1": "'Vị trưởng lão đó giác ngộ theo Phật, '",
  "sn8.9:3.2": "Koṇḍañña, tinh tấn mạnh mẽ; ",
  "sn8.9:3.3": "Người thường xuyên hưởng lạc thiền định, ",
  "sn8.9:3.4": "và ly dục liên tục. ",
  "sn8.9:4.1": "Những gì đệ tử cần đạt được, ",
  "sn8.9:4.2": "người thực hành theo lời dạy của bậc Đạo Sư; ",
  "sn8.9:4.3": "Tất cả điều đó đã được Ngài đạt đến, ",
  "sn8.9:4.4": "người không phóng dật khi học tập. ",
  "sn8.9:5.1": "Đại oai lực, bậc tam minh, ",
  "sn8.9:5.2": "thiện xảo về việc đọc tâm người; ",
  "sn8.9:5.3": "Koṇḍañña, người thừa kế Phật, ",
  "sn8.9:5.4": "đảnh lễ chân bậc Đạo Sư.' ",
  "sn8.10:0.1": "Tương Ưng Bộ 8.10 ",
  "sn8.10:0.2": "1. Phẩm Vaṅgīsa ",
  "sn8.10:0.3": "Kinh Moggallāna ",
  "sn8.10:1.1": "Một thời Thế Tôn trú tại Rājagaha, bên sườn núi Isigili, tại Đá Đen, cùng với đại chúng Tỳ Kheo khoảng năm trăm vị, tất cả đều là bậc A-la-hán. ",
  "sn8.10:1.2": "Tôn giả Mahāmoggallāna đang dùng tâm quán sát tâm của tất cả những vị ấytâm giải thoát, không còn ô nhiễm. ",
  "sn8.10:1.3": "Rồi Tôn giả Vaṅgīsa suy nghĩ: ",
  "sn8.10:1.4": "'Thế Tôn đang trú tại Rājagaha, bên sườn núi Isigili, tại Đá Đen, cùng với đại chúng Tỳ Kheo khoảng năm trăm vị, tất cả đều là bậc A-la-hán. '",
  "sn8.10:1.5": "Tôn giả Mahāmoggallāna đang dùng tâm quán sát tâm của tất cả những vị ấytâm giải thoát, không còn ô nhiễm. ",
  "sn8.10:1.6": "Vậy ta hãy tán thán Tôn giả Mahāmoggallāna bằng những bài kệ thích hợp trước mặt Thế Tôn.' ",
  "sn8.10:2.1": "Rồi Tôn giả Vaṅgīsa đứng dậy từ chỗ ngồi, đắp y một bên vai, chắp tay hướng về Thế Tôn và thưa: ",
  "sn8.10:2.2": "'Bạch Thế Tôn, con cảm hứng, bạch Đấng Thiện Thệ, con cảm hứng.' ",
  "sn8.10:2.3": "'Hãy nói lên, Vaṅgīsa,' Thế Tôn nói. ",
  "sn8.10:2.4": "Rồi Tôn giả Vaṅgīsa tán thán Tôn giả Mahāmoggallāna bằng những bài kệ thích hợp trước mặt Thế Tôn: ",
  "sn8.10:3.1": "'Bậc ẩn sĩ ngồi bên sườn núi, '",
  "sn8.10:3.2": "đã vượt qua bờ kia của khổ đau; ",
  "sn8.10:3.3": "Các đệ tử vây quanh hầu hạ, ",
  "sn8.10:3.4": "bậc tam minh, đã vượt qua cái chết. ",
  "sn8.10:4.1": "Moggallāna, bậc đại thần thông, ",
  "sn8.10:4.2": "đang dùng tâm quán sát các vị ấy; ",
  "sn8.10:4.3": "Quán sát tâm của họ, ",
  "sn8.10:4.4": "giải thoát, không còn ô nhiễm. ",
  "sn8.10:5.1": "Vậy đây bậc đầy đủ mọi chi phần, ",
  "sn8.10:5.2": "bậc ẩn sĩ đã vượt qua bờ kia của khổ đau; ",
  "sn8.10:5.3": "Đầy đủ nhiều loại phẩm chất, ",
  "sn8.10:5.4": "các đệ tử vây quanh hầu hạ bậc Gotama.' ",
  "sn8.11:0.1": "Tương Ưng Bộ 8.11 ",
  "sn8.11:0.2": "1. Phẩm Vaṅgīsa ",
  "sn8.11:0.3": "Kinh Hồ Gaggarā ",
  "sn8.11:1.1": "Một thời Thế Tôn trú tại Campā, bên bờ hồ sen Gaggarā, cùng với đại chúng Tỳ Kheo khoảng năm trăm vị, bảy trăm cư sĩ nam, bảy trăm cư sĩ nữ, và hàng ngàn chư thiên. ",
  "sn8.11:1.2": "Thế Tôn chiếu sáng hơn tất cả về sắc đẹp và danh tiếng. ",
  "sn8.11:1.3": "Rồi Tôn giả Vaṅgīsa suy nghĩ: ",
  "sn8.11:1.4": "'Thế Tôn đang trú tại Campā, bên bờ hồ sen Gaggarā, cùng với đại chúng Tỳ Kheo khoảng năm trăm vị, bảy trăm cư sĩ nam, bảy trăm cư sĩ nữ, và hàng ngàn chư thiên. '",
  "sn8.11:1.5": "Thế Tôn chiếu sáng hơn tất cả về sắc đẹp và danh tiếng. ",
  "sn8.11:1.6": "Vậy ta hãy tán thán Thế Tôn bằng bài kệ thích hợp trước mặt Ngài.' ",
  "sn8.11:2.1": "Rồi Tôn giả Vaṅgīsa đứng dậy từ chỗ ngồi, đắp y một bên vai, chắp tay hướng về Thế Tôn và thưa: ",
  "sn8.11:2.2": "'Bạch Thế Tôn, con cảm hứng, bạch Đấng Thiện Thệ, con cảm hứng.' ",
  "sn8.11:2.3": "'Hãy nói lên, Vaṅgīsa,' Thế Tôn nói. ",
  "sn8.11:2.4": "Rồi Tôn giả Vaṅgīsa tán thán Thế Tôn bằng bài kệ thích hợp trước mặt Ngài: ",
  "sn8.11:3.1": "'Như mặt trăng trên bầu trời không mây, '",
  "sn8.11:3.2": "chiếu sáng như mặt trời không tì vết; ",
  "sn8.11:3.3": "Cũng vậy, hỡi Aṅgīrasa, Đại Ẩn Sĩ, ",
  "sn8.11:3.4": "Ngài chiếu sáng vượt trội danh tiếng khắp thế gian.' ",
  "sn8.12:0.1": "Tương Ưng Bộ 8.12 ",
  "sn8.12:0.2": "1. Phẩm Vaṅgīsa ",
  "sn8.12:0.3": "Kinh Vaṅgīsa ",
  "sn8.12:1.1": "Một thời Tôn giả Vaṅgīsa trú tại Sāvatthī, trong rừng Jeta, vườn ông Anāthapiṇḍika. ",
  "sn8.12:1.2": "Lúc bấy giờ Tôn giả Vaṅgīsa vừa đắc quả A-la-hán chẳng bao lâu, đang cảm nhận an lạc giải thoát, vào lúc đó đã đọc những bài kệ này: ",
  "sn8.12:2.1": "'Trước kia ta lang thang như kẻ say thơ ca, '",
  "sn8.12:2.2": "từ làng này đến làng khác, từ thành này đến thành khác; ",
  "sn8.12:2.3": "Rồi ta thấy bậc Chánh Đẳng Giác, ",
  "sn8.12:2.4": "đức tin khởi lên trong ta. ",
  "sn8.12:3.1": "Ngài đã dạy Pháp cho ta, ",
  "sn8.12:3.2": "các uẩn, các xứ và các giới; ",
  "sn8.12:3.3": "Sau khi nghe Pháp của Ngài, ",
  "sn8.12:3.4": "ta đã xuất gia không nhà. ",
  "sn8.12:4.1": "Thật vậy, vì lợi ích của nhiều người, ",
  "sn8.12:4.2": "bậc ẩn sĩ đã đạt giác ngộ; ",
  "sn8.12:4.3": "Của các Tỳ Kheo và Tỳ Kheo Ni, ",
  "sn8.12:4.4": "những người đã thấy con đường dẫn đến Niết-bàn. ",
  "sn8.12:5.1": "Thật may mắn thay cho ta, ",
  "sn8.12:5.2": "được ở gần Đức Phật; ",
  "sn8.12:5.3": "Đã đạt được tam minh, ",
  "sn8.12:5.4": "đã thực hiện lời dạy của Phật. ",
  "sn8.12:6.1": "Ta biết các kiếp sống trước, ",
  "sn8.12:6.2": "thiên nhãn đã được thanh lọc; ",
  "sn8.12:6.3": "Ta là bậc tam minh, đã đắc thần thông, ",
  "sn8.12:6.4": "thiện xảo về việc đọc tâm người.' ",
  "sn8.12:7.0": "Tổng kết của phẩm ",
  "sn8.12:7.1": "Đã xuất gia và không hài lòng, ",
  "sn8.12:7.2": "hiền thiện và khinh thường; ",
  "sn8.12:7.3": "Với Ānandalời nói khéo, ",
  "sn8.12:7.4": "Sāriputta và Tự Tứ; ",
  "sn8.12:7.5": "Hơn một ngàn, Koṇḍañña, ",
  "sn8.12:7.6": "với Moggallāna và Gaggarā; ",
  "sn8.12:7.7": "Vaṅgīsamười hai bài. ",
  "sn8.12:7.8": "Tương Ưng Vaṅgīsa đã hoàn tất. "
}
window.BILARA["sn8_v1"]["vi"]["sn8_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
