window.BILARA = window.BILARA || {};
window.BILARA["sn9_v1"] = window.BILARA["sn9_v1"] || {};
window.BILARA["sn9_v1"]["vi"] = {
  "sn9.1:0.1": "Tương Ưng Bộ 9.1 ",
  "sn9.1:0.2": "1. Phẩm Rừng ",
  "sn9.1:0.3": "Kinh Viễn Ly ",
  "sn9.1:1.1": "Tôi nghe như vầy",
  "sn9.1:1.2": "Một thời, một Tỳ Kheo trú tại một khu rừng ở xứ Kosala. ",
  "sn9.1:1.3": "Lúc bấy giờ, Tỳ Kheo đó, trong khi nghỉ ngơi ban ngày, khởi lên những suy tầm xấu ác, bất thiện, thuộc về gia cư. ",
  "sn9.1:1.4": "Rồi vị thiên thần trú trong khu rừng đó, thương xót, muốn lợi ích, muốn khơi dậy tâm chấn động nơi Tỳ Kheo ấy, đã đến chỗ Tỳ Kheo; sau khi đến, nói với Tỳ Kheo bằng những bài kệ: ",
  "sn9.1:2.1": "'Ông muốn viễn ly, đã vào rừng, '",
  "sn9.1:2.2": "Nhưng tâm ông lại phóng ra ngoài; ",
  "sn9.1:2.3": "Hãy điều phục ái dục giữa đám người, ",
  "sn9.1:2.4": "Rồi ông sẽ hạnh phúc, thoát khỏi tham ái. ",
  "sn9.1:3.1": "Với chánh niệm, hãy đoạn trừ bất mãn, ",
  "sn9.1:3.2": "Ông thuộc về bậc thiện; chúng tôi nhắc nhở ông; ",
  "sn9.1:3.3": "Bụi dưới vực thẳm thật khó vượt qua, ",
  "sn9.1:3.4": "Đừng để bụi dục vọng cuốn trôi ông. ",
  "sn9.1:4.1": "Như con chim bị bụi phủ đầy, ",
  "sn9.1:4.2": "Rũ bỏ, phủi sạch bụi trắng bay đi; ",
  "sn9.1:4.3": "Cũng vậy, Tỳ Kheo tinh tấn, chánh niệm, ",
  "sn9.1:4.4": "Rũ bỏ, phủi sạch bụi trắng bay đi.' ",
  "sn9.1:5.1": "Rồi Tỳ Kheo đó, được vị thiên khơi dậy tâm chấn động, đã đạt được tâm chấn động. ",
  "sn9.2:0.1": "Tương Ưng Bộ 9.2 ",
  "sn9.2:0.2": "1. Phẩm Rừng ",
  "sn9.2:0.3": "Kinh Phục Vụ ",
  "sn9.2:1.1": "Một thời, một Tỳ Kheo trú tại một khu rừng ở xứ Kosala. ",
  "sn9.2:1.2": "Lúc bấy giờ, Tỳ Kheo đó, trong khi nghỉ ngơi ban ngày, nằm ngủ. ",
  "sn9.2:1.3": "Rồi vị thiên thần trú trong khu rừng đó, thương xót, muốn lợi ích, muốn khơi dậy tâm chấn động nơi Tỳ Kheo ấy, đã đến chỗ Tỳ Kheo; sau khi đến, nói với Tỳ Kheo bằng những bài kệ: ",
  "sn9.2:2.1": "'Hãy đứng dậy, Tỳ Kheo! Tại sao ông ngủ? '",
  "sn9.2:2.2": "Ông ngủ có ích lợi gì? ",
  "sn9.2:2.3": "Với người đang bệnh hoạn, giấc ngủ ích gì, ",
  "sn9.2:2.4": "Người bị mũi tên đâm đang đau khổ. ",
  "sn9.2:3.1": "Với đức tin đó ông đã xuất gia, ",
  "sn9.2:3.2": "Từ gia đình đến vô gia đình; ",
  "sn9.2:3.3": "Hãy vun trồng đức tin đó, ",
  "sn9.2:3.4": "Đừng rơi vào ách thống trị của giấc ngủ.' ",
  "sn9.2:4.1": "'Các dục vọng vô thường, không bền vững, '",
  "sn9.2:4.2": "Kẻ ngu say đắm trong đó; ",
  "sn9.2:4.3": "Được giải thoát khỏi điều bị trói buộc, không bám víu, ",
  "sn9.2:4.4": "Tại sao lại hành hạ người xuất gia? ",
  "sn9.2:5.1": "Vì sự điều phục tham ái, ",
  "sn9.2:5.2": "Vì sự vượt qua vô minh; ",
  "sn9.2:5.3": "Trí tuệ đó là tối thượng, ",
  "sn9.2:5.4": "Tại sao lại hành hạ người xuất gia? ",
  "sn9.2:6.1": "Sau khi đoạn trừ vô minh bằng trí tuệ, ",
  "sn9.2:6.2": "Với sự đoạn tận các lậu hoặc; ",
  "sn9.2:6.3": "Không sầu bi, không não loạn, ",
  "sn9.2:6.4": "Tại sao lại hành hạ người xuất gia? ",
  "sn9.2:7.1": "Với tinh tấn đã được khởi phát, tâm chuyên nhất, ",
  "sn9.2:7.2": "Luôn luôn nỗ lực vững chắc; ",
  "sn9.2:7.3": "Đang mong cầu Niết-bàn, ",
  "sn9.2:7.4": "Tại sao lại hành hạ người xuất gia?' ",
  "sn9.3:0.1": "Tương Ưng Bộ 9.3 ",
  "sn9.3:0.2": "1. Phẩm Rừng ",
  "sn9.3:0.3": "Kinh Kassapagotta ",
  "sn9.3:1.1": "Một thời, Tôn giả Kassapagotta trú tại một khu rừng ở xứ Kosala. ",
  "sn9.3:1.2": "Lúc bấy giờ, Tôn giả Kassapagotta, trong khi nghỉ ngơi ban ngày, đang giáo giới một người thợ rừng. ",
  "sn9.3:1.3": "Rồi vị thiên thần trú trong khu rừng đó, muốn khơi dậy tâm chấn động nơi Tôn giả Kassapagotta, đã đến chỗ Tôn giả Kassapagotta; sau khi đến, nói với Tôn giả Kassapagotta bằng những bài kệ: ",
  "sn9.3:2.1": "'Người thợ rừng đi lại khó khăn trên núi, '",
  "sn9.3:2.2": "Kém trí tuệ, không có tâm; ",
  "sn9.3:2.3": "Tỳ Kheo giáo giới không đúng thời, ",
  "sn9.3:2.4": "Đối với tôi dường như thật ngu ngốc. ",
  "sn9.3:3.1": "Nghe nhưng không hiểu, ",
  "sn9.3:3.2": "Nhìn nhưng không thấy; ",
  "sn9.3:3.3": "Khi Pháp được giảng dạy, ",
  "sn9.3:3.4": "Kẻ ngu không hiểu được nghĩa. ",
  "sn9.3:4.1": "Dù cho mang theo mười ngọn đuốc, ",
  "sn9.3:4.2": "Này Kassapa; ",
  "sn9.3:4.3": "Cũng không thể thấy được các sắc pháp, ",
  "sn9.3:4.4": "Vì mắt của họ không tồn tại.' ",
  "sn9.3:5.1": "Rồi Tôn giả Kassapagotta, được vị thiên khơi dậy tâm chấn động, đã đạt được tâm chấn động. ",
  "sn9.4:0.1": "Tương Ưng Bộ 9.4 ",
  "sn9.4:0.2": "1. Phẩm Rừng ",
  "sn9.4:0.3": "Kinh Nhiều Vị ",
  "sn9.4:1.1": "Một thời, nhiều Tỳ Kheo trú tại một khu rừng ở xứ Kosala. ",
  "sn9.4:1.2": "Rồi các Tỳ Kheo đó, sau khi an cư mùa mưa xong, đến cuối ba tháng, đã lên đường du hành. ",
  "sn9.4:1.3": "Rồi vị thiên thần trú trong khu rừng đó, không thấy các Tỳ Kheo, than thở và đã nói lên bài kệ này vào lúc đó: ",
  "sn9.4:2.1": "'Hôm nay dường như có vẻ buồn chán, '",
  "sn9.4:2.2": "Khi nhìn thấy nhiều chỗ ngồi vắng vẻ; ",
  "sn9.4:2.3": "Những vị đó khéo nói, đa văn, ",
  "sn9.4:2.4": "Các đệ tử Gotama đã đi đâu rồi?' ",
  "sn9.4:3.1": "Khi nói vậy, một vị thiên khác đáp lại vị thiên đó bằng bài kệ: ",
  "sn9.4:4.1": "'Một số đến Magadha, một số đến Kosala, '",
  "sn9.4:4.2": "Một số thì đến vùng đất Vajji; ",
  "sn9.4:4.3": "Như những con hươu đi không vướng bận, ",
  "sn9.4:4.4": "Các Tỳ Kheo sống không có chỗ ở cố định.' ",
  "sn9.5:0.1": "Tương Ưng Bộ 9.5 ",
  "sn9.5:0.2": "1. Phẩm Rừng ",
  "sn9.5:0.3": "Kinh Ānanda ",
  "sn9.5:1.1": "Một thời, Tôn giả Ānanda trú tại một khu rừng ở xứ Kosala. ",
  "sn9.5:1.2": "Lúc bấy giờ, Tôn giả Ānanda sống quá nhiều thời gian tiếp xúc và giao thiệp với cư sĩ. ",
  "sn9.5:1.3": "Rồi vị thiên thần trú trong khu rừng đó, thương xót, muốn lợi ích, muốn khơi dậy tâm chấn động nơi Tôn giả Ānanda, đã đến chỗ Tôn giả Ānanda; sau khi đến, nói với Tôn giả Ānanda bằng bài kệ: ",
  "sn9.5:2.1": "'Hãy lui vào chỗ rậm rạp gốc cây, '",
  "sn9.5:2.2": "Đặt Niết-bàn vào trong tâm; ",
  "sn9.5:2.3": "Hãy thiền định, này Gotama, đừng phóng dật, ",
  "sn9.5:2.4": "Những lời ồn ào kia sẽ làm gì được ông?' ",
  "sn9.5:3.1": "Rồi Tôn giả Ānanda, được vị thiên khơi dậy tâm chấn động, đã đạt được tâm chấn động. ",
  "sn9.6:0.1": "Tương Ưng Bộ 9.6 ",
  "sn9.6:0.2": "1. Phẩm Rừng ",
  "sn9.6:0.3": "Kinh Anuruddha ",
  "sn9.6:1.1": "Một thời, Tôn giả Anuruddha trú tại một khu rừng ở xứ Kosala. ",
  "sn9.6:1.2": "Rồi một vị thiên thuộc cõi trời Đao Lợi tên là Jālinī, vốn là bạn đời cũ của Tôn giả Anuruddha, đã đến chỗ Tôn giả Anuruddha; sau khi đến, nói với Tôn giả Anuruddha bằng bài kệ: ",
  "sn9.6:2.1": "'Hãy hướng tâm đến đó, '",
  "sn9.6:2.2": "Nơi ông đã từng cư trú trước đây; ",
  "sn9.6:2.3": "Giữa các chư thiên cõi Đao Lợi, ",
  "sn9.6:2.4": "Nơi mọi dục vọng đều được thỏa mãn; ",
  "sn9.6:2.5": "Được tôn kính và vây quanh, ",
  "sn9.6:2.6": "Ông rạng ngời giữa các thiên nữ.' ",
  "sn9.6:3.1": "'Các thiên nữ ở trong cảnh khổ, '",
  "sn9.6:3.2": "Bị dính chặt vào thân kiến; ",
  "sn9.6:3.3": "Những chúng sinh đó cũng ở cảnh khổ, ",
  "sn9.6:3.4": "Bị các thiên nữ ước mong.' ",
  "sn9.6:4.1": "'Họ không biết đến an lạc, '",
  "sn9.6:4.2": "Những ai không thấy vườn Hoan Hỷ; ",
  "sn9.6:4.3": "Trú xứ của chư thiên và người, ",
  "sn9.6:4.4": "Của ba mươi ba vị danh tiếng.' ",
  "sn9.6:5.1": "'Này kẻ ngu, ngươi không hiểu, '",
  "sn9.6:5.2": "Như lời của các bậc A-la-hán; ",
  "sn9.6:5.3": "Tất cả các hành đều vô thường, ",
  "sn9.6:5.4": "Có bản chất sinh và diệt; ",
  "sn9.6:5.5": "Sinh rồi diệt, ",
  "sn9.6:5.6": "Sự an tịnh của chúng là an lạc. ",
  "sn9.6:6.1": "Nay không còn tái sinh nữa, ",
  "sn9.6:6.2": "Trong cõi chư thiên, này Jālinī; ",
  "sn9.6:6.3": "Vòng luân hồi đã được đoạn tận, ",
  "sn9.6:6.4": "Nay không còn tái sinh nữa.' ",
  "sn9.7:0.1": "Tương Ưng Bộ 9.7 ",
  "sn9.7:0.2": "1. Phẩm Rừng ",
  "sn9.7:0.3": "Kinh Nāgadatta ",
  "sn9.7:1.1": "Một thời, Tôn giả Nāgadatta trú tại một khu rừng ở xứ Kosala. ",
  "sn9.7:1.2": "Lúc bấy giờ, Tôn giả Nāgadatta vào làng quá sớm và trở về quá muộn. ",
  "sn9.7:1.3": "Rồi vị thiên thần trú trong khu rừng đó, thương xót, muốn lợi ích, muốn khơi dậy tâm chấn động nơi Tôn giả Nāgadatta, đã đến chỗ Tôn giả Nāgadatta; sau khi đến, nói với Tôn giả Nāgadatta bằng những bài kệ: ",
  "sn9.7:2.1": "'Hãy vào đúng thời, này Nāgadatta, '",
  "sn9.7:2.2": "Và đừng đi lại quá lâu vào ban ngày khi trở về; ",
  "sn9.7:2.3": "Thân cận với các gia chủ, ",
  "sn9.7:2.4": "Chia sẻ vui và khổ với họ. ",
  "sn9.7:3.1": "Tôi lo sợ cho Nāgadatta quá tự tin, ",
  "sn9.7:3.2": "Bị ràng buộc bởi các gia đình; ",
  "sn9.7:3.3": "Chớ để mà rơi vào quyền lực, ",
  "sn9.7:3.4": "Của Thần Chết, Thần kết thúc đầy uy lực.' ",
  "sn9.7:4.1": "Rồi Tôn giả Nāgadatta, được vị thiên khơi dậy tâm chấn động, đã đạt được tâm chấn động. ",
  "sn9.8:0.1": "Tương Ưng Bộ 9.8 ",
  "sn9.8:0.2": "1. Phẩm Rừng ",
  "sn9.8:0.3": "Kinh Bà Chủ Nhà ",
  "sn9.8:1.1": "Một thời, một Tỳ Kheo trú tại một khu rừng ở xứ Kosala. ",
  "sn9.8:1.2": "Lúc bấy giờ, Tỳ Kheo đó sống quá nhiều thời gian thân cận với một gia đình. ",
  "sn9.8:1.3": "Rồi vị thiên thần trú trong khu rừng đó, thương xót, muốn lợi ích, muốn khơi dậy tâm chấn động nơi Tỳ Kheo ấy, đã hóa hiện thành hình dạng bà chủ nhà của gia đình đó, đến chỗ Tỳ Kheo; sau khi đến, nói với Tỳ Kheo bằng bài kệ: ",
  "sn9.8:2.1": "'Ở bờ sông và chỗ tụ họp, '",
  "sn9.8:2.2": "Trong hội trường và trên đường phố; ",
  "sn9.8:2.3": "Người ta tụ họp bàn tán, ",
  "sn9.8:2.4": "Về tôi và người kia, có gì khác nhau?' ",
  "sn9.8:3.1": "'Nhiều tiếng đồn thổi là chướng ngại, '",
  "sn9.8:3.2": "Cần được chịu đựng bởi người tu khổ hạnh; ",
  "sn9.8:3.3": "Không nên bị hoang mang vì điều đó, ",
  "sn9.8:3.4": "Vì thật sự không bị ô nhiễm bởi điều đó. ",
  "sn9.8:4.1": "Người sợ hãi tiếng đồn, ",
  "sn9.8:4.2": "Như hươu nai sợ gió trong rừng; ",
  "sn9.8:4.3": "Người ta gọi đó là tâm nhẹ dạ, ",
  "sn9.8:4.4": "Và giới của họ không thành tựu.' ",
  "sn9.9:0.1": "Tương Ưng Bộ 9.9 ",
  "sn9.9:0.2": "1. Phẩm Rừng ",
  "sn9.9:0.3": "Kinh Người Vajji ",
  "sn9.9:1.1": "Một thời, một Tỳ Kheo người Vajji trú tại một khu rừng ở Vesāli. ",
  "sn9.9:1.2": "Lúc bấy giờ ở Vesāli, người Vajji thức suốt đêm. ",
  "sn9.9:1.3": "Rồi Tỳ Kheo đó, nghe tiếng trống và nhạc cụ vang lên ở Vesāli, than thở và đã nói lên bài kệ này vào lúc đó: ",
  "sn9.9:2.1": "'Chúng tôi sống một mình trong rừng, '",
  "sn9.9:2.2": "Như khúc gỗ bị vứt bỏ trong rừng; ",
  "sn9.9:2.3": "Trong một đêm như thế này, ",
  "sn9.9:2.4": "Ai khổ hơn chúng tôi đây?' ",
  "sn9.9:3.1": "Rồi vị thiên thần trú trong khu rừng đó, thương xót, muốn lợi ích, muốn khơi dậy tâm chấn động nơi Tỳ Kheo ấy, đã đến chỗ Tỳ Kheo; sau khi đến, nói với Tỳ Kheo bằng bài kệ: ",
  "sn9.9:4.1": "'Ông sống một mình trong rừng, '",
  "sn9.9:4.2": "Như khúc gỗ bị vứt bỏ trong rừng; ",
  "sn9.9:4.3": "Nhiều người ngưỡng mộ điều đó nơi ông, ",
  "sn9.9:4.4": "Như người địa ngục ngưỡng mộ người đang đi lên thiên đường.' ",
  "sn9.9:5.1": "Rồi Tỳ Kheo đó, được vị thiên khơi dậy tâm chấn động, đã đạt được tâm chấn động. ",
  "sn9.10:0.1": "Tương Ưng Bộ 9.10 ",
  "sn9.10:0.2": "1. Phẩm Rừng ",
  "sn9.10:0.3": "Kinh Tụng Đọc ",
  "sn9.10:1.1": "Một thời, một Tỳ Kheo trú tại một khu rừng ở xứ Kosala. ",
  "sn9.10:1.2": "Lúc bấy giờ, Tỳ Kheo đó trước kia vốn sống siêng năng tụng đọc, sau đó trở nên thờ ơ, im lặng, ngập ngừng. ",
  "sn9.10:1.3": "Rồi vị thiên thần trú trong khu rừng đó, không nghe Pháp từ Tỳ Kheo ấy, đã đến chỗ Tỳ Kheo; sau khi đến, nói với Tỳ Kheo bằng bài kệ: ",
  "sn9.10:2.1": "'Tại sao ông, này Tỳ Kheo, '",
  "sn9.10:2.2": "Không học thuộc các câu Pháp khi sống với các Tỳ Kheo? ",
  "sn9.10:2.3": "Nghe Pháp thì được tịnh tín, ",
  "sn9.10:2.4": "Và được tán thán ngay trong đời này.' ",
  "sn9.10:3.1": "'Trước kia có ý muốn học các câu Pháp, '",
  "sn9.10:3.2": "Cho đến khi tôi đạt được ly tham; ",
  "sn9.10:3.3": "Từ khi đạt được ly tham, ",
  "sn9.10:3.4": "Bất cứ điều gì thấy, nghe hay cảm nhận; ",
  "sn9.10:3.5": "Bậc thiện trí gọi đó là đặt xuống sau khi đã hiểu.' ",
  "sn9.11:0.1": "Tương Ưng Bộ 9.11 ",
  "sn9.11:0.2": "1. Phẩm Rừng ",
  "sn9.11:0.3": "Kinh Suy Tầm Bất Thiện ",
  "sn9.11:1.1": "Một thời, một Tỳ Kheo trú tại một khu rừng ở xứ Kosala. ",
  "sn9.11:1.2": "Lúc bấy giờ, Tỳ Kheo đó, trong khi nghỉ ngơi ban ngày, khởi lên những suy tầm xấu ác, bất thiện, đó là",
  "sn9.11:1.3": "Dục tầm, sân tầm, hại tầm. ",
  "sn9.11:1.4": "Rồi vị thiên thần trú trong khu rừng đó, thương xót, muốn lợi ích, muốn khơi dậy tâm chấn động nơi Tỳ Kheo ấy, đã đến chỗ Tỳ Kheo; sau khi đến, nói với Tỳ Kheo bằng những bài kệ: ",
  "sn9.11:2.1": "'Do không như lý tác ý, '",
  "sn9.11:2.2": "Ông bị các suy tầm gặm nhấm; ",
  "sn9.11:2.3": "Hãy từ bỏ sự không như lý tác ý, ",
  "sn9.11:2.4": "Và hãy suy xét như lý. ",
  "sn9.11:3.1": "Hướng tâm về bậc Đạo Sư và Pháp, ",
  "sn9.11:3.2": "Về Tăng đoàn và giới của chính mình; ",
  "sn9.11:3.3": "Ông sẽ đạt được hỷ lạc, ",
  "sn9.11:3.4": "Và hạnh phúc không còn nghi ngờ; ",
  "sn9.11:3.5": "Từ đó, với nhiều hỷ lạc, ",
  "sn9.11:3.6": "Ông sẽ chấm dứt mọi khổ đau.' ",
  "sn9.11:4.1": "Rồi Tỳ Kheo đó, được vị thiên khơi dậy tâm chấn động, đã đạt được tâm chấn động. ",
  "sn9.12:0.1": "Tương Ưng Bộ 9.12 ",
  "sn9.12:0.2": "1. Phẩm Rừng ",
  "sn9.12:0.3": "Kinh Giữa Trưa ",
  "sn9.12:1.1": "Một thời, một Tỳ Kheo trú tại một khu rừng ở xứ Kosala. ",
  "sn9.12:1.2": "Rồi vị thiên thần trú trong khu rừng đó đến chỗ Tỳ Kheo; sau khi đến, đã nói bài kệ này trước mặt Tỳ Kheo: ",
  "sn9.12:2.1": "'Khi buổi trưa đứng bóng, '",
  "sn9.12:2.2": "Khi các loài chim im lặng đậu xuống; ",
  "sn9.12:2.3": "Khu rừng lớn xào xạc, ",
  "sn9.12:2.4": "Điều đó khơi dậy nỗi sợ hãi trong tôi. ",
  "sn9.12:3.1": "Khi buổi trưa đứng bóng, ",
  "sn9.12:3.2": "Khi các loài chim im lặng đậu xuống; ",
  "sn9.12:3.3": "Khu rừng lớn xào xạc, ",
  "sn9.12:3.4": "Điều đó khơi dậy niềm vui trong tôi.' ",
  "sn9.13:0.1": "Tương Ưng Bộ 9.13 ",
  "sn9.13:0.2": "1. Phẩm Rừng ",
  "sn9.13:0.3": "Kinh Các Căn Không Phòng Hộ ",
  "sn9.13:1.1": "Một thời, nhiều Tỳ Kheo trú tại một khu rừng ở xứ Kosala, kiêu ngạo, ngã mạn, phóng túng, lắm lời, nói bừa bãi, thất niệm, không tỉnh giác, không định tâm, tâm tán loạn, các căn không được phòng hộ. ",
  "sn9.13:1.2": "Rồi vị thiên thần trú trong khu rừng đó, thương xót, muốn lợi ích, muốn khơi dậy tâm chấn động nơi các Tỳ Kheo ấy, đã đến chỗ các Tỳ Kheo; sau khi đến, nói với các Tỳ Kheo bằng những bài kệ: ",
  "sn9.13:2.1": "'Trước kia họ sống an lạc, '",
  "sn9.13:2.2": "Các Tỳ Kheo đệ tử Gotama; ",
  "sn9.13:2.3": "Không tham cầu khi đi khất thực, ",
  "sn9.13:2.4": "Không tham cầu chỗ ngủ nghỉ; ",
  "sn9.13:2.5": "Biết rõ sự vô thường ở đời, ",
  "sn9.13:2.6": "Họ đã chấm dứt mọi khổ đau. ",
  "sn9.13:3.1": "Sau khi làm cho mình khó nuôi dưỡng, ",
  "sn9.13:3.2": "Như các trưởng làng; ",
  "sn9.13:3.3": "Ăn rồi lại nằm xuống, ",
  "sn9.13:3.4": "Say mê ở nhà người khác. ",
  "sn9.13:4.1": "Chắp tay trước Tăng đoàn, ",
  "sn9.13:4.2": "Tôi nói với một số vị ở đây; ",
  "sn9.13:4.3": "Họ bị bỏ rơi, không ai che chở, ",
  "sn9.13:4.4": "Họ cũng như những ngạ quỷ vậy. ",
  "sn9.13:5.1": "Những vị nào sống phóng dật, ",
  "sn9.13:5.2": "Những điều tôi nói là hướng đến họ; ",
  "sn9.13:5.3": "Những vị nào sống không phóng dật, ",
  "sn9.13:5.4": "Tôi xin kính lễ các vị đó.' ",
  "sn9.13:6.1": "Rồi các Tỳ Kheo đó, được vị thiên khơi dậy tâm chấn động, đã đạt được tâm chấn động. ",
  "sn9.14:0.1": "Tương Ưng Bộ 9.14 ",
  "sn9.14:0.2": "1. Phẩm Rừng ",
  "sn9.14:0.3": "Kinh Kẻ Trộm Hương ",
  "sn9.14:1.1": "Một thời, một Tỳ Kheo trú tại một khu rừng ở xứ Kosala. ",
  "sn9.14:1.2": "Lúc bấy giờ, Tỳ Kheo đó, sau bữa ăn, trở về sau khi đi khất thực, xuống ao sen và đứng ngửi hoa sen. ",
  "sn9.14:1.3": "Rồi vị thiên thần trú trong khu rừng đó, thương xót, muốn lợi ích, muốn khơi dậy tâm chấn động nơi Tỳ Kheo ấy, đã đến chỗ Tỳ Kheo; sau khi đến, nói với Tỳ Kheo bằng bài kệ: ",
  "sn9.14:2.1": "'Bông hoa mọc dưới nước này, '",
  "sn9.14:2.2": "Ông đang ngửi mà không được cho phép; ",
  "sn9.14:2.3": "Đây là một phần của hành vi trộm cắp, ",
  "sn9.14:2.4": "Ông là kẻ trộm hương, này bạn.' ",
  "sn9.14:3.1": "'Tôi không lấy đi, không bẻ gãy, '",
  "sn9.14:3.2": "Tôi ngửi hoa nước từ xa; ",
  "sn9.14:3.3": "Thế thì vì lý do gì, ",
  "sn9.14:3.4": "Lại gọi tôi là kẻ trộm hương? ",
  "sn9.14:4.1": "Người đào củ sen, ",
  "sn9.14:4.2": "Bẻ hoa sen trắng; ",
  "sn9.14:4.3": "Kẻ làm việc như vậy, ",
  "sn9.14:4.4": "Tại sao không gọi như vậy?' ",
  "sn9.14:5.1": "'Người thô lỗ, tham lam, '",
  "sn9.14:5.2": "Như bị vấy bẩn bởi bụi đất; ",
  "sn9.14:5.3": "Tôi không có lời nói với người đó, ",
  "sn9.14:5.4": "Nhưng tôi cần nói với ông. ",
  "sn9.14:6.1": "Với người không có vết nhơ, ",
  "sn9.14:6.2": "Luôn luôn tìm kiếm sự thanh tịnh; ",
  "sn9.14:6.3": "Tội lỗi nhỏ bằng đầu sợi tóc, ",
  "sn9.14:6.4": "Dường như to lớn như đám mây.' ",
  "sn9.14:7.1": "'Thật vậy, này Dạ-xoa, ngươi biết tôi, '",
  "sn9.14:7.2": "Và thương xót tôi; ",
  "sn9.14:7.3": "Này Dạ-xoa, hãy đến nhắc lại nữa, ",
  "sn9.14:7.4": "Khi nào ngươi thấy điều như vậy nơi tôi.' ",
  "sn9.14:8.1": "'Chúng tôi không sống nhờ vào ông, '",
  "sn9.14:8.2": "Cũng không muốn trở thành người hầu của ông; ",
  "sn9.14:8.3": "Ông, này Tỳ Kheo, hãy tự mình biết, ",
  "sn9.14:8.4": "Con đường để đi đến cõi lành.' ",
  "sn9.14:9.1": "Rồi Tỳ Kheo đó, được vị thiên khơi dậy tâm chấn động, đã đạt được tâm chấn động. ",
  "sn9.14:9.2": "Phẩm Rừng, thứ nhất. ",
  "sn9.14:10.0": "Tóm tắt chúng ",
  "sn9.14:10.1": "Viễn Ly và Phục Vụ, ",
  "sn9.14:10.2": "Cùng với Kassapagotta và Nhiều Vị; ",
  "sn9.14:10.3": "Ānanda và Anuruddha, ",
  "sn9.14:10.4": "Và Nāgadatta cùng Bà Chủ Nhà. ",
  "sn9.14:11.1": "Và Người Vajji ở Vesāli, ",
  "sn9.14:11.2": "Tụng Đọc và Không Như Lý; ",
  "sn9.14:11.3": "Giữa Trưa và Các Căn Không Phòng Hộ ",
  "sn9.14:11.4": "Hoa Sen làm thành mười bốn kinh. ",
  "sn9.14:11.5": "Tương Ưng Rừng đã hoàn tất. "
}
window.BILARA["sn9_v1"]["vi"]["sn9_v1:source"] =
 "Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com ";
