window.BILARA = window.BILARA || {};
window.BILARA["sn17_v1"] = window.BILARA["sn17_v1"] || {};
window.BILARA["sn17_v1"]["en"] = {
  "sn17.1:0.1": "Linked Discourses 17.1 ",
  "sn17.1:0.2": "Chapter One ",
  "sn17.1:0.3": "Grim ",
  "sn17.1:1.1": "So I have heard. ",
  "sn17.1:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn17.1:1.3": "There the Buddha addressed the mendicants, ",
  "sn17.1:1.4": "“Mendicants!” ",
  "sn17.1:1.5": "“Venerable sir,” they replied. ",
  "sn17.1:1.6": "The Buddha said this: ",
  "sn17.1:2.1": "“Possessions, honor, and popularity are grim, bitter, and harsh. They’re an obstacle to reaching the supreme sanctuary from the yoke. ",
  "sn17.1:2.2": "So you should train like this: ",
  "sn17.1:2.3": "‘We will give up arisen possessions, honor, and popularity, and we won’t let them occupy our minds.’ ",
  "sn17.1:2.4": "That’s how you should train.” ",
  "sn17.2:0.1": "Linked Discourses 17.2 ",
  "sn17.2:0.2": "Chapter One ",
  "sn17.2:0.3": "A Hook ",
  "sn17.2:1.1": "At Sāvatthī. ",
  "sn17.2:1.2": "“Possessions, honor, and popularity are grim, bitter, and harsh. They’re an obstacle to reaching the supreme sanctuary from the yoke. ",
  "sn17.2:1.3": "Suppose an angler was to cast a baited hook into a deep lake. ",
  "sn17.2:1.4": "Seeing the bait, a fish would swallow it. ",
  "sn17.2:1.5": "And so the fish that swallowed the hook would meet with tragedy and disaster, and the angler can do what he wants with it. ",
  "sn17.2:2.1": "‘Angler’ is a term for Māra the Wicked. ",
  "sn17.2:2.2": "‘Hook’ is a term for possessions, honor, and popularity. ",
  "sn17.2:2.3": "Whoever enjoys and likes arisen possessions, honor, and popularity is called a mendicant who has swallowed Māra’s hook. They’ve met with tragedy and disaster, and the Wicked One can do with them what he wants. ",
  "sn17.2:2.4": "So grim are possessions, honor, and popularitybitter and harsh, an obstacle to reaching the supreme sanctuary from the yoke. ",
  "sn17.2:2.5": "So you should train like this: ",
  "sn17.2:2.6": "‘We will give up arisen possessions, honor, and popularity, and we won’t let them occupy our minds.’ ",
  "sn17.2:2.7": "That’s how you should train.” ",
  "sn17.3:0.1": "Linked Discourses 17.3 ",
  "sn17.3:0.2": "Chapter One ",
  "sn17.3:0.3": "A Turtle ",
  "sn17.3:1.1": "At Sāvatthī. ",
  "sn17.3:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.3:1.3": "Once upon a time in a certain lake there was a large family of turtles that had lived there for a long time. ",
  "sn17.3:1.4": "Then one of the turtles said to another, ",
  "sn17.3:1.5": "‘My dear turtle, don’t you go to that place.’ ",
  "sn17.3:1.6": "But that turtle did go to that place, ",
  "sn17.3:1.7": "and a hunter pierced her with a harpoon. ",
  "sn17.3:1.8": "Then that turtle went back to the other turtle. ",
  "sn17.3:1.9": "When the other turtle saw her coming off in the distance, ",
  "sn17.3:1.10": "he said, ",
  "sn17.3:1.11": "‘My dear turtle, I hope you didn’t go to that place!’ ",
  "sn17.3:1.12": "‘I did.’ ",
  "sn17.3:1.13": "‘But my dear turtle, I hope you’re not hurt or injured!’ ",
  "sn17.3:1.14": "‘I’m not hurt or injured. But this cord keeps dragging behind me.’ ",
  "sn17.3:1.15": "‘Indeed, my dear turtle, you’re hurt and injured! ",
  "sn17.3:1.16": "Your father and grandfather met with tragedy and disaster because of such a cord. ",
  "sn17.3:1.17": "Go now, you are no longer one of us.’ ",
  "sn17.3:2.1": "‘Hunter’ is a term for Māra the Wicked. ",
  "sn17.3:2.2": "‘Harpoon’ is a term for possessions, honor, and popularity. ",
  "sn17.3:2.3": "‘Cord’ is a term for greed and relishing. ",
  "sn17.3:2.4": "Whoever enjoys and likes arisen possessions, honor, and popularity is called a mendicant who has been pierced with a harpoon. They’ve met with tragedy and disaster, and the Wicked One can do with them what he wants. ",
  "sn17.3:2.5": "",
  "sn17.3:2.6": "So grim are possessions, honor, and popularity. …” ",
  "sn17.3:2.7": "",
  "sn17.4:0.1": "Linked Discourses 17.4 ",
  "sn17.4:0.2": "Chapter One ",
  "sn17.4:0.3": "A Fleecy Sheep ",
  "sn17.4:1.1": "At Sāvatthī. ",
  "sn17.4:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.4:1.3": "Suppose a fleecy sheep was to enter a briar patch. ",
  "sn17.4:1.4": "She’d get caught, snagged, and trapped at every turn, coming to ruin. ",
  "sn17.4:1.5": "In the same way, take a certain mendicant whose mind is overcome and overwhelmed by possessions, honor, and popularity. They robe up in the morning and, taking their bowl and robe, enter the village or town for alms. ",
  "sn17.4:1.6": "They get caught, snagged, and trapped at every turn, coming to ruin. ",
  "sn17.4:1.7": "So grim are possessions, honor, and popularity. …” ",
  "sn17.4:1.8": "",
  "sn17.5:0.1": "Linked Discourses 17.5 ",
  "sn17.5:0.2": "Chapter One ",
  "sn17.5:0.3": "A Dung Beetle ",
  "sn17.5:1.1": "At Sāvatthī. ",
  "sn17.5:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.5:1.3": "Suppose there was a dung-eating beetle full of dung, stuffed with dung, and before her was a huge pile of dung. ",
  "sn17.5:1.4": "She’d look down on other beetles, thinking: ",
  "sn17.5:1.5": "‘For I am a dung-eating beetle full of dung, stuffed with dung, and before me is a huge pile of dung.’ ",
  "sn17.5:1.6": "In the same way, take a certain mendicant whose mind is overcome and overwhelmed by possessions, honor, and popularity. They robe up in the morning and, taking their bowl and robe, enter the village or town for alms. ",
  "sn17.5:1.7": "There they eat as much as they like, get invited back tomorrow, and have plenty of almsfood. ",
  "sn17.5:1.8": "When they get back to the monastery, they boast in the middle of a group of mendicants: ",
  "sn17.5:1.9": "‘I ate as much as I liked, got invited back tomorrow, and had plenty of almsfood. I get robes, almsfood, lodgings, and medicines and supplies for the sick. But these other mendicants have little merit or significance, so they don’t get these things.’ ",
  "sn17.5:1.10": "With a mind overcome and overwhelmed by possessions, honor, and popularity, they look down on other good-hearted mendicants. ",
  "sn17.5:1.11": "This will be for their lasting harm and suffering. ",
  "sn17.5:1.12": "So grim are possessions, honor, and popularity. …” ",
  "sn17.5:1.13": "",
  "sn17.6:0.1": "Linked Discourses 17.6 ",
  "sn17.6:0.2": "Chapter One ",
  "sn17.6:0.3": "A Bolt of Lightning ",
  "sn17.6:1.1": "At Sāvatthī. ",
  "sn17.6:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.6:1.3": "Let forked lightning fall on whom? Let possessions, honor, and popularity come to a trainee who has not achieved their heart’s desire. ",
  "sn17.6:2.1": "‘Forked lightning’ is a term for possessions, honor, and popularity. ",
  "sn17.6:2.2": "So grim are possessions, honor, and popularity. …” ",
  "sn17.6:2.3": "",
  "sn17.7:0.1": "Linked Discourses 17.7 ",
  "sn17.7:0.2": "Chapter One ",
  "sn17.7:0.3": "A Poisoned Arrow ",
  "sn17.7:1.1": "At Sāvatthī. ",
  "sn17.7:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.7:1.3": "Let whom be pierced by a poisoned arrow? Let possessions, honor, and popularity come to a trainee who has not achieved their heart’s desire. ",
  "sn17.7:2.1": "‘Arrow’ is a term for possessions, honor, and popularity. ",
  "sn17.7:2.2": "So grim are possessions, honor, and popularity. …” ",
  "sn17.7:2.3": "",
  "sn17.8:0.1": "Linked Discourses 17.8 ",
  "sn17.8:0.2": "Chapter One ",
  "sn17.8:0.3": "A Jackal ",
  "sn17.8:1.1": "At Sāvatthī. ",
  "sn17.8:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.8:1.3": "Mendicants, did you hear an old jackal howling at the crack of dawn?” ",
  "sn17.8:1.4": "“Yes, sir.” ",
  "sn17.8:1.5": "“That old jackal has the disease called mange. He’s not happy in his den, or at the root of a tree, or out in the open. ",
  "sn17.8:1.6": "Wherever he goes, stands, sits, or lies down he meets with tragedy and disaster. ",
  "sn17.8:1.7": "In the same way, take a certain mendicant whose mind is overcome and overwhelmed by possessions, honor, and popularity. They’re not happy in an empty hut, at the root of a tree, or out in the open. ",
  "sn17.8:1.8": "Wherever they go, stand, sit, or lie down they meet with tragedy and disaster. ",
  "sn17.8:1.9": "So grim are possessions, honor, and popularity. …” ",
  "sn17.8:1.10": "",
  "sn17.9:0.1": "Linked Discourses 17.9 ",
  "sn17.9:0.2": "Chapter One ",
  "sn17.9:0.3": "Gale-force Winds ",
  "sn17.9:1.1": "At Sāvatthī. ",
  "sn17.9:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.9:1.3": "High in the atmosphere there are gale-force winds blowing. ",
  "sn17.9:1.4": "Any bird that flies there is flung about by those gale-force winds. ",
  "sn17.9:1.5": "Their feet go one way, their wings another, their head another, and their body another. ",
  "sn17.9:1.6": "In the same way, take a certain monk whose mind is overcome and overwhelmed by possessions, honor, and popularity. He robes up in the morning and, taking his bowl and robe, enters the village or town for alms without guarding body, speech, and mind, without establishing mindfulness, and without restraining the sense faculties. ",
  "sn17.9:1.7": "There he sees a lady scantily clad, with revealing clothes. ",
  "sn17.9:1.8": "Lust infects his mind. ",
  "sn17.9:1.9": "He disavows the training and returns to a lesser life. ",
  "sn17.9:1.10": "Some take his robe, others his bowl, others his sitting cloth, others his needle case, just like the bird flung about by the gale-force winds. ",
  "sn17.9:1.11": "So grim are possessions, honor, and popularity. …” ",
  "sn17.9:1.12": "",
  "sn17.10:0.1": "Linked Discourses 17.10 ",
  "sn17.10:0.2": "Chapter One ",
  "sn17.10:0.3": "With Verses ",
  "sn17.10:1.1": "At Sāvatthī. ",
  "sn17.10:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.10:1.3": "Take a case where I see a certain individual whose mind is overcome and overwhelmed by honor. When their body breaks up, after death, they’re reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn17.10:1.4": "Take another case where I see a certain individual whose mind is overcome and overwhelmed by lack of honor. When their body breaks up, after death, they’re reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn17.10:1.5": "And take another case where I see a certain individual whose mind is overcome and overwhelmed by both honor and lack of honor. When their body breaks up, after death, they’re reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn17.10:1.6": "So grim are possessions, honor, and popularity. …” ",
  "sn17.10:1.7": "",
  "sn17.10:2.1": "That is what the Buddha said. ",
  "sn17.10:2.2": "Then the Holy One, the Teacher, went on to say: ",
  "sn17.10:3.1": "“Whether they’re honored ",
  "sn17.10:3.2": "or not honored, or both, ",
  "sn17.10:3.3": "their immersion doesn’t waver ",
  "sn17.10:3.4": "as they abide in the immeasurables. ",
  "sn17.10:4.1": "They persistently meditate ",
  "sn17.10:4.2": "with subtle view and discernment. ",
  "sn17.10:4.3": "Rejoicing in the ending of grasping, ",
  "sn17.10:4.4": "they’re said to be a true person.” ",
  "sn17.10:4.5": "",
  "sn17.10:4.6": "",
  "sn17.10:5.1": "",
  "sn17.10:5.2": "",
  "sn17.10:5.3": "",
  "sn17.11:0.1": "Linked Discourses 17.11 ",
  "sn17.11:0.2": "Chapter Two ",
  "sn17.11:0.3": "A Gold Cup ",
  "sn17.11:1.1": "At Sāvatthī. ",
  "sn17.11:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.11:1.3": "When I’ve comprehended the mind of a certain individual, I understand: ",
  "sn17.11:1.4": "‘This venerable would not tell a deliberate lie even for the sake of a gold cup filled with silver powder.’ ",
  "sn17.11:1.5": "But some time later I see them tell a deliberate lie because their mind is overcome and overwhelmed by possessions, honor, and popularity. ",
  "sn17.11:1.6": "So grim are possessions, honor, and popularity. …” ",
  "sn17.11:1.7": "",
  "sn17.12:0.1": "Linked Discourses 17.12 ",
  "sn17.12:0.2": "Chapter Two ",
  "sn17.12:0.3": "A Silver Pot ",
  "sn17.12:1.1": "At Sāvatthī. ",
  "sn17.12:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.12:1.3": "When I’ve comprehended the mind of a certain individual, I understand: ",
  "sn17.12:1.4": "‘This venerable would not tell a deliberate lie even for the sake of a silver pot filled with gold powder.’ ",
  "sn17.12:1.5": "But some time later I see them tell a deliberate lie because their mind is overcome and overwhelmed by possessions, honor, and popularity. ",
  "sn17.12:1.6": "So grim are possessions, honor, and popularity. …” ",
  "sn17.12:1.7": "",
  "sn17.13-20:0.1": "Linked Discourses 17.13–20 ",
  "sn17.13-20:0.2": "Chapter Two ",
  "sn17.13-20:0.3": "A Gold Ingot, Etc. ",
  "sn17.13-20:1.1": "At Sāvatthī. ",
  "sn17.13-20:1.2": "“Mendicants, when I’ve comprehended the mind of a certain individual, I understand: ",
  "sn17.13-20:1.3": "‘This venerable would not tell a deliberate lie even for the sake of a gold ingot.’ …” ",
  "sn17.13-20:1.4": "“‘… for the sake of a hundred gold ingots.’ …” ",
  "sn17.13-20:1.5": "“‘… for the sake of a mountain of gold.’ …” ",
  "sn17.13-20:1.6": "“‘… for the sake of a hundred mountains of gold.’ …” ",
  "sn17.13-20:1.7": "“‘… for the sake of the whole earth full of gold.’ …” ",
  "sn17.13-20:1.8": "“‘… for any kind of material reward.’ …” ",
  "sn17.13-20:1.9": "“‘… for the sake of life.’ …” ",
  "sn17.13-20:1.10": "“‘… for the sake of the finest lady in the land.’ ",
  "sn17.13-20:1.11": "But some time later I see them tell a deliberate lie because their mind is overcome and overwhelmed by possessions, honor, and popularity. ",
  "sn17.13-20:1.12": "So grim are possessions, honor, and popularity. …” ",
  "sn17.13-20:1.13": "",
  "sn17.13-20:1.14": "",
  "sn17.13-20:1.15": "",
  "sn17.13-20:2.1": "",
  "sn17.13-20:2.2": "",
  "sn17.13-20:2.3": "",
  "sn17.21:0.1": "Linked Discourses 17.21 ",
  "sn17.21:0.2": "Chapter Three ",
  "sn17.21:0.3": "A Female ",
  "sn17.21:1.1": "At Sāvatthī. ",
  "sn17.21:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.21:1.3": "Even if you’re alone with a lady she might not occupy your mind, but possessions, honor and popularity would still occupy your mind. ",
  "sn17.21:1.4": "So grim are possessions, honor, and popularity. …” ",
  "sn17.21:1.5": "",
  "sn17.22:0.1": "Linked Discourses 17.22 ",
  "sn17.22:0.2": "Chapter Three ",
  "sn17.22:0.3": "The Finest Lady in the Land ",
  "sn17.22:1.1": "At Sāvatthī. ",
  "sn17.22:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.22:1.3": "Even if you’re alone with the finest lady in the land she might not occupy your mind, but possessions, honor and popularity would still occupy your mind. ",
  "sn17.22:1.4": "So grim are possessions, honor, and popularity. …” ",
  "sn17.22:1.5": "",
  "sn17.23:0.1": "Linked Discourses 17.23 ",
  "sn17.23:0.2": "Chapter Three ",
  "sn17.23:0.3": "An Only Son ",
  "sn17.23:1.1": "At Sāvatthī. ",
  "sn17.23:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.23:1.3": "A faithful laywoman with a dear and beloved only son would rightly appeal to him, ",
  "sn17.23:1.4": "‘My darling, please be like the householder Citta and Hatthaka of Āḷavī.’ ",
  "sn17.23:1.5": "These are a standard and a measure for my male lay disciples, that is, the householder Citta and Hatthaka of Āḷavī. ",
  "sn17.23:1.6": "‘But my darling, if you go forth from the lay life to homelessness, ",
  "sn17.23:1.7": "please be like Sāriputta and Moggallāna.’ ",
  "sn17.23:1.8": "These are a standard and a measure for my monk disciples, that is, Sāriputta and Moggallāna. ",
  "sn17.23:1.9": "‘And my darling, may you not come into possessions, honor, and popularity while you’re still a trainee and haven’t achieved your heart’s desire.’ ",
  "sn17.23:1.10": "If a trainee who hasn’t achieved their heart’s desire comes into possessions, honor, and popularity it’s an obstacle for them. ",
  "sn17.23:1.11": "So grim are possessions, honor, and popularity. …” ",
  "sn17.23:1.12": "",
  "sn17.24:0.1": "Linked Discourses 17.24 ",
  "sn17.24:0.2": "Chapter Three ",
  "sn17.24:0.3": "An Only Daughter ",
  "sn17.24:1.1": "At Sāvatthī. ",
  "sn17.24:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.24:1.3": "A faithful laywoman with a dear and beloved only daughter would rightly appeal to her, ",
  "sn17.24:1.4": "‘My darling, please be like the laywomen Khujjuttarā and Veḷukaṇṭakī, Nanda’s mother.’ ",
  "sn17.24:1.5": "These are a standard and a measure for my female lay disciples, that is, the laywomen Khujjuttarā and Veḷukaṇṭakī, Nanda’s mother. ",
  "sn17.24:1.6": "‘But my darling, if you go forth from the lay life to homelessness, ",
  "sn17.24:1.7": "please be like the nuns Khemā and Uppalavaṇṇā.’ ",
  "sn17.24:1.8": "These are a standard and a measure for my nun disciples, that is, the nuns Khemā and Uppalavaṇṇā. ",
  "sn17.24:1.9": "‘And my darling, may you not come into possessions, honor, and popularity while you’re still a trainee and haven’t achieved your heart’s desire.’ ",
  "sn17.24:1.10": "If a trainee who hasn’t achieved their heart’s desire comes into possessions, honor, and popularity it’s an obstacle for them. ",
  "sn17.24:1.11": "So grim are possessions, honor, and popularity. …” ",
  "sn17.24:1.12": "",
  "sn17.25:0.1": "Linked Discourses 17.25 ",
  "sn17.25:0.2": "Chapter Three ",
  "sn17.25:0.3": "Ascetics and Brahmins ",
  "sn17.25:1.1": "At Sāvatthī. ",
  "sn17.25:1.2": "“Mendicants, there are ascetics and brahmins who don’t truly understand the gratification, drawback, and escape when it comes to possessions, honor, and popularity. ",
  "sn17.25:1.3": "I don’t deem them as true ascetics and brahmins. Those venerables don’t realize the goal of life as an ascetic or brahmin, and don’t live having realized it with their own insight. ",
  "sn17.25:1.4": "There are ascetics and brahmins who do truly understand the gratification, drawback, and escape when it comes to possessions, honor, and popularity. ",
  "sn17.25:1.5": "I deem them as true ascetics and brahmins. Those venerables realize the goal of life as an ascetic or brahmin, and live having realized it with their own insight.” ",
  "sn17.26:0.1": "Linked Discourses 17.26 ",
  "sn17.26:0.2": "Chapter Three ",
  "sn17.26:0.3": "Ascetics and Brahmins (2nd) ",
  "sn17.26:1.1": "At Sāvatthī. ",
  "sn17.26:1.2": "“There are ascetics and brahmins who don’t truly understand the origin, disappearance, gratification, drawback, and escape when it comes to possessions, honor, and popularity … ",
  "sn17.26:1.3": "There are ascetics and brahmins who do truly understand …” ",
  "sn17.26:1.4": "",
  "sn17.27:0.1": "Linked Discourses 17.27 ",
  "sn17.27:0.2": "Chapter Three ",
  "sn17.27:0.3": "Ascetics and Brahmins (3rd) ",
  "sn17.27:1.1": "At Sāvatthī. ",
  "sn17.27:1.2": "“There are ascetics and brahmins who don’t truly understand possessions, honor, and popularity, their origin, their cessation, and the path that leads to their cessation … ",
  "sn17.27:1.3": "There are ascetics and brahmins who do truly understand …” ",
  "sn17.27:1.4": "",
  "sn17.28:0.1": "Linked Discourses 17.28 ",
  "sn17.28:0.2": "Chapter Three ",
  "sn17.28:0.3": "Skin ",
  "sn17.28:1.1": "At Sāvatthī. ",
  "sn17.28:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.28:1.3": "They cut through the outer skin, the inner skin, the flesh, sinews, and bones, until they reach the marrow and keep pressing. ",
  "sn17.28:1.4": "So grim are possessions, honor, and popularity. …” ",
  "sn17.28:1.5": "",
  "sn17.29:0.1": "Linked Discourses 17.29 ",
  "sn17.29:0.2": "Chapter Three ",
  "sn17.29:0.3": "A Rope ",
  "sn17.29:1.1": "At Sāvatthī. ",
  "sn17.29:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.29:1.3": "They cut through the outer skin, the inner skin, the flesh, sinews, and bones, until they reach the marrow and keep pressing. ",
  "sn17.29:2.1": "Suppose a strong man was to twist a strong horse-hair rope around your shin and tighten it. ",
  "sn17.29:2.2": "It would cut through the outer skin, the inner skin, the flesh, sinews, and bones, until it reached the marrow and kept pressing. ",
  "sn17.29:2.3": "In the same way, possessions, honor, and popularity cut through the outer skin, the inner skin, the flesh, sinews, and bones, until they reach the marrow and keep pressing. ",
  "sn17.29:2.4": "So grim are possessions, honor, and popularity. …” ",
  "sn17.29:2.5": "",
  "sn17.30:0.1": "Linked Discourses 17.30 ",
  "sn17.30:0.2": "Chapter Three ",
  "sn17.30:0.3": "A Mendicant With Defilements Ended ",
  "sn17.30:1.1": "At Sāvatthī. ",
  "sn17.30:1.2": "“Mendicants, possessions, honor, and popularity are an obstacle even for a mendicant who is perfected, with defilements ended.” ",
  "sn17.30:1.3": "When he said this, Venerable Ānanda said to the Buddha, ",
  "sn17.30:1.4": "“Sir, what do possessions, honor, and popularity obstruct for a mendicant with defilements ended?” ",
  "sn17.30:1.5": "“Ānanda, I don’t say that possessions, honor, and popularity obstruct the unshakable freedom of heart. ",
  "sn17.30:1.6": "But I do say that possessions, honor, and popularity obstruct the achievement of blissful meditations in this life for a meditator who is diligent, keen, and resolute. ",
  "sn17.30:1.7": "So grim are possessions, honor, and popularitybitter and harsh, an obstacle to reaching the supreme sanctuary from the yoke. ",
  "sn17.30:1.8": "So you should train like this: ",
  "sn17.30:1.9": "‘We will give up arisen possessions, honor, and popularity, and we won’t let them occupy our minds.’ ",
  "sn17.30:1.10": "That’s how you should train.” ",
  "sn17.30:1.11": "",
  "sn17.30:1.12": "",
  "sn17.30:2.1": "",
  "sn17.30:2.2": "",
  "sn17.30:2.3": "",
  "sn17.31:0.1": "Linked Discourses 17.31 ",
  "sn17.31:0.2": "Chapter Four ",
  "sn17.31:0.3": "Schism ",
  "sn17.31:1.1": "At Sāvatthī. ",
  "sn17.31:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.31:1.3": "Devadatta split the Saṅgha because his mind was overcome and overwhelmed by possessions, honor, and popularity. ",
  "sn17.31:1.4": "So grim are possessions, honor, and popularity. …” ",
  "sn17.31:1.5": "",
  "sn17.32:0.1": "Linked Discourses 17.32 ",
  "sn17.32:0.2": "Chapter Four ",
  "sn17.32:0.3": "Skillful Root ",
  "sn17.32:1.1": "At Sāvatthī. ",
  "sn17.32:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.32:1.3": "Devadatta cut off his skillful root because his mind was overcome and overwhelmed by possessions, honor, and popularity. ",
  "sn17.32:1.4": "So grim are possessions, honor, and popularity. …” ",
  "sn17.32:1.5": "",
  "sn17.33:0.1": "Linked Discourses 17.33 ",
  "sn17.33:0.2": "Chapter Four ",
  "sn17.33:0.3": "Skillful Quality ",
  "sn17.33:1.1": "At Sāvatthī. ",
  "sn17.33:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.33:1.3": "Devadatta cut off his skillful quality because his mind was overcome and overwhelmed by possessions, honor, and popularity. ",
  "sn17.33:1.4": "So grim are possessions, honor, and popularity. …” ",
  "sn17.33:1.5": "",
  "sn17.34:0.1": "Linked Discourses 17.34 ",
  "sn17.34:0.2": "Chapter Four ",
  "sn17.34:0.3": "Bright Quality ",
  "sn17.34:1.1": "At Sāvatthī. ",
  "sn17.34:1.2": "“Possessions, honor, and popularity are grim … ",
  "sn17.34:1.3": "Devadatta cut off his bright quality because his mind was overcome and overwhelmed by possessions, honor, and popularity. ",
  "sn17.34:1.4": "So grim are possessions, honor, and popularity. …” ",
  "sn17.34:1.5": "",
  "sn17.35:0.1": "Linked Discourses 17.35 ",
  "sn17.35:0.2": "Chapter Four ",
  "sn17.35:0.3": "Shortly After He Left ",
  "sn17.35:1.1": "At one time the Buddha was staying near Rājagaha, on the Vulture’s Peak Mountain, not long after Devadatta had left. ",
  "sn17.35:1.2": "There the Buddha spoke to the mendicants about Devadatta: ",
  "sn17.35:1.3": "“Possessions, honor, and popularity came to Devadatta for his own ruin and downfall. ",
  "sn17.35:2.1": "It’s like a banana plant … ",
  "sn17.35:2.2": "",
  "sn17.35:3.1": "or a bamboo … ",
  "sn17.35:3.2": "",
  "sn17.35:4.1": "or a reed, all of which bear fruit to their own ruin and downfall … ",
  "sn17.35:4.2": "",
  "sn17.35:5.1": "It’s like a mule, which becomes pregnant to its own ruin and downfall. ",
  "sn17.35:5.2": "In the same way, possessions, honor, and popularity came to Devadatta for his own ruin and downfall. ",
  "sn17.35:5.3": "So grim are possessions, honor, and popularity. ",
  "sn17.35:5.4": "That’s how you should train.” ",
  "sn17.35:6.1": "That is what the Buddha said. ",
  "sn17.35:6.2": "Then the Holy One, the Teacher, went on to say: ",
  "sn17.35:7.1": "“The banana plant is destroyed by its own fruit, ",
  "sn17.35:7.2": "as are the bamboo and the reed. ",
  "sn17.35:7.3": "Honor destroys a reprobate, ",
  "sn17.35:7.4": "as pregnancy destroys a mule.” ",
  "sn17.36:0.1": "Linked Discourses 17.36 ",
  "sn17.36:0.2": "Chapter Four ",
  "sn17.36:0.3": "Five Hundred Carts ",
  "sn17.36:1.1": "Near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn17.36:1.2": "Now at that time Prince Ajātasattu was going with five hundred carts at daybreak and dusk to attend on Devadatta, presenting him with an offering of five hundred servings of food. ",
  "sn17.36:1.3": "Then several mendicants went up to the Buddha, bowed, sat down to one side, and said to him, ",
  "sn17.36:1.4": "“Sir, Prince Ajātasattu is going with five hundred carts at daybreak and dusk to attend on Devadatta, presenting him with an offering of five hundred servings of food.” ",
  "sn17.36:1.5": "“Mendicants, don’t envy Devadatta’s possessions, honor, and popularity. ",
  "sn17.36:1.6": "As long as Prince Ajātasattu goes with five hundred carts at daybreak and dusk to attend on Devadatta, presenting him with an offering of five hundred servings of food, Devadatta can expect decline, not growth, in skillful qualities. ",
  "sn17.36:2.1": "If they were to lance a boil on a wild dog’s nose, it would get even wilder. ",
  "sn17.36:2.2": "In the same way, as long as Prince Ajātasattu goes with five hundred carts at daybreak and dusk to attend on Devadatta, presenting him with an offering of five hundred servings of food, Devadatta can expect decline, not growth, in skillful qualities. ",
  "sn17.36:2.3": "So grim are possessions, honor, and popularity. …” ",
  "sn17.36:2.4": "",
  "sn17.37:0.1": "Linked Discourses 17.37 ",
  "sn17.37:0.2": "Chapter Four ",
  "sn17.37:0.3": "Mother ",
  "sn17.37:1.1": "At Sāvatthī. ",
  "sn17.37:1.2": "“Possessions, honor, and popularity are grim, bitter, and harsh. They’re an obstacle to reaching the supreme sanctuary from the yoke. ",
  "sn17.37:1.3": "When I’ve comprehended the mind of a certain individual, I understand: ",
  "sn17.37:1.4": "‘This venerable would not tell a deliberate lie even for the sake of their mother.’ ",
  "sn17.37:1.5": "But some time later I see them tell a deliberate lie because their mind is overcome and overwhelmed by possessions, honor, and popularity. ",
  "sn17.37:1.6": "So grim are possessions, honor, and popularitybitter and harsh, an obstacle to reaching the supreme sanctuary from the yoke. ",
  "sn17.37:1.7": "So you should train like this: ",
  "sn17.37:1.8": "‘We will give up arisen possessions, honor, and popularity, and we won’t let them occupy our minds.’ ",
  "sn17.37:1.9": "",
  "sn17.37:1.10": "That’s how you should train.” ",
  "sn17.38-43:0.1": "Linked Discourses 17.38–43 ",
  "sn17.38-43:0.2": "Chapter Four ",
  "sn17.38-43:0.3": "Father, Etc. ",
  "sn17.38-43:1.1": "At Sāvatthī. ",
  "sn17.38-43:1.2": "“Possessions, honor, and popularity are grim, bitter, and harsh. They’re an obstacle to reaching the supreme sanctuary from the yoke. ",
  "sn17.38-43:1.3": "When I’ve comprehended the mind of a certain individual, I understand: ",
  "sn17.38-43:1.4": "‘This venerable would not tell a deliberate lie even for the sake of their father.’ …” ",
  "sn17.38-43:1.5": "(Tell in full as in SN 17.37.) ",
  "sn17.38-43:1.6": "“‘… brother.’ …” ",
  "sn17.38-43:1.7": "“‘… sister.’ …” ",
  "sn17.38-43:1.8": "“‘… son.’ …” ",
  "sn17.38-43:1.9": "“‘… daughter.’ …” ",
  "sn17.38-43:1.10": "“‘… wife.’ ",
  "sn17.38-43:1.11": "But some time later I see them tell a deliberate lie because their mind is overcome and overwhelmed by possessions, honor, and popularity. ",
  "sn17.38-43:1.12": "So grim are possessions, honor, and popularitybitter and harsh, an obstacle to reaching the supreme sanctuary from the yoke. ",
  "sn17.38-43:1.13": "So you should train like this: ",
  "sn17.38-43:1.14": "‘We will give up arisen possessions, honor, and popularity, and we won’t let them occupy our minds.’ ",
  "sn17.38-43:1.15": "That’s how you should train.” ",
  "sn17.38-43:1.16": "",
  "sn17.38-43:1.17": "",
  "sn17.38-43:2.1": "",
  "sn17.38-43:2.2": "",
  "sn17.38-43:2.3": "",
  "sn17.38-43:2.4": "",
  "sn17.38-43:2.5": "The Linked Discourses on possessions, honor, and popularity are complete. "
}
window.BILARA["sn17_v1"]["en"]["sn17_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
