window.BILARA = window.BILARA || {};
window.BILARA["sn20_v1"] = window.BILARA["sn20_v1"] || {};
window.BILARA["sn20_v1"]["en"] = {
  "sn20.1:0.1": "Linked Discourses 20.1 ",
  "sn20.1:0.2": "1. Similes ",
  "sn20.1:0.3": "A Roof Peak ",
  "sn20.1:1.1": "So I have heard. ",
  "sn20.1:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn20.1:1.3": "There the Buddha … said: ",
  "sn20.1:1.4": "“Mendicants, the rafters of a bungalow all lean to the peak and meet at the peak, and when the peak is demolished they’re all demolished too. ",
  "sn20.1:1.5": "In the same way all unskillful qualities are rooted in ignorance and meet in ignorance, and when ignorance is demolished they’re all demolished too. ",
  "sn20.1:1.6": "So you should train like this: ",
  "sn20.1:1.7": "‘We will stay diligent.’ ",
  "sn20.1:1.8": "That’s how you should train.” ",
  "sn20.2:0.1": "Linked Discourses 20.2 ",
  "sn20.2:0.2": "1. Similes ",
  "sn20.2:0.3": "A Fingernail ",
  "sn20.2:1.1": "At Sāvatthī. ",
  "sn20.2:1.2": "Then the Buddha, picking up a little bit of dirt on his fingernail, addressed the mendicants: ",
  "sn20.2:1.3": "“What do you think, mendicants? ",
  "sn20.2:1.4": "Which is more: the little bit of dirt on my fingernail, or this great earth?” ",
  "sn20.2:1.5": "“Sir, the great earth is far more. ",
  "sn20.2:1.6": "The little bit of dirt on your fingernail is tiny. ",
  "sn20.2:1.7": "Compared to the great earth, it doesn’t count, there’s no comparison, it’s not worth a fraction.” ",
  "sn20.2:1.8": "“In the same way the sentient beings reborn as humans are few, ",
  "sn20.2:1.9": "while those not reborn as humans are many. ",
  "sn20.2:1.10": "So you should train like this: ",
  "sn20.2:1.11": "‘We will stay diligent.’ ",
  "sn20.2:1.12": "That’s how you should train.” ",
  "sn20.3:0.1": "Linked Discourses 20.3 ",
  "sn20.3:0.2": "1. Similes ",
  "sn20.3:0.3": "Families ",
  "sn20.3:1.1": "At Sāvatthī. ",
  "sn20.3:1.2": "“Mendicants, those families with many women and few men are easy prey for bandits and  grain-jar thieves. ",
  "sn20.3:1.3": "In the same way any mendicant who has not developed and cultivated the heart’s release by love is easy prey for non-humans. ",
  "sn20.3:1.4": "Those families with few women and many men are hard prey for bandits and grain-jar thieves. ",
  "sn20.3:1.5": "In the same way a mendicant who has developed and cultivated the heart’s release by love is hard prey for non-humans. ",
  "sn20.3:1.6": "So you should train like this: ",
  "sn20.3:1.7": "‘We will develop the heart’s release by love. We’ll cultivate it, make it our vehicle and our basis, keep it up, consolidate it, and properly implement it.’ ",
  "sn20.3:1.8": "That’s how you should train.” ",
  "sn20.4:0.1": "Linked Discourses 20.4 ",
  "sn20.4:0.2": "1. Similes ",
  "sn20.4:0.3": "Cauldrons ",
  "sn20.4:1.1": "At Sāvatthī. ",
  "sn20.4:1.2": "“Mendicants, suppose one person was to give a gift of a hundred cauldrons of rice in the morning, at midday, and in the evening. And someone else was to develop a heart of love, even just as long as it takes to pull a cow’s udder. The latter would be more fruitful. ",
  "sn20.4:1.3": "So you should train like this: ",
  "sn20.4:1.4": "‘We will develop the heart’s release by love. We’ll cultivate it, make it our vehicle and our basis, keep it up, consolidate it, and properly implement it.’ ",
  "sn20.4:1.5": "That’s how you should train.” ",
  "sn20.5:0.1": "Linked Discourses 20.5 ",
  "sn20.5:0.2": "1. Similes ",
  "sn20.5:0.3": "A Spear ",
  "sn20.5:1.1": "At Sāvatthī. ",
  "sn20.5:1.2": "“Mendicants, suppose there was a sharp-pointed spear. ",
  "sn20.5:1.3": "And a man came along and thought, ",
  "sn20.5:1.4": "‘With my hand or fist I’ll fold this sharp spear over, crumple it, and bend it back!’ ",
  "sn20.5:1.5": "What do you think, mendicants? ",
  "sn20.5:1.6": "Is that man capable of doing so?” ",
  "sn20.5:1.7": "“No, sir. ",
  "sn20.5:1.8": "Why not? ",
  "sn20.5:1.9": "Because it’s not easy to fold that sharp spear over, crumple it, and bend it back with the hand or fist. ",
  "sn20.5:1.10": "That man will eventually get weary and frustrated.” ",
  "sn20.5:2.1": "“In the same way, suppose a mendicant has developed the heart’s release by love, has cultivated it, made it a vehicle and a basis, kept it up, consolidated it, and properly implemented it. Should any non-human think to overthrow their mind, ",
  "sn20.5:2.2": "they’ll eventually get weary and frustrated. ",
  "sn20.5:2.3": "So you should train like this: ",
  "sn20.5:2.4": "‘We will develop the heart’s release by love. We’ll cultivate it, make it our vehicle and our basis, keep it up, consolidate it, and properly implement it.’ ",
  "sn20.5:2.5": "That’s how you should train.” ",
  "sn20.6:0.1": "Linked Discourses 20.6 ",
  "sn20.6:0.2": "1. Similes ",
  "sn20.6:0.3": "The Archers ",
  "sn20.6:1.1": "At Sāvatthī. ",
  "sn20.6:1.2": "“Mendicants, suppose there were four well-trained expert archers with strong bows standing in the four quarters. ",
  "sn20.6:1.3": "And a man came along and thought, ",
  "sn20.6:1.4": "‘When these four well-trained expert archers shoot arrows in four quarters, I’ll catch them before they reach the ground, and then I’ll bring them back.’ ",
  "sn20.6:1.5": "What do you think, mendicants? ",
  "sn20.6:1.6": "Are they qualified to be called ‘a speedster endowed with super-speed’?” ",
  "sn20.6:2.1": "“If he could catch an arrow shot by just one well-trained expert archer before it reaches the ground and bring it back, ",
  "sn20.6:2.2": "he’d be qualified to be called ‘a speedster endowed with super-speed’. How much more so arrows shot by four archers!” ",
  "sn20.6:3.1": "“As fast as that man is, the sun and moon are faster. ",
  "sn20.6:3.2": "As fast as that man is, as fast as the sun and moon are, and as fast as the deities that run before the sun and moon are, the waning of the life forces is faster. ",
  "sn20.6:3.3": "So you should train like this: ",
  "sn20.6:3.4": "‘We will stay diligent.’ ",
  "sn20.6:3.5": "That’s how you should train.” ",
  "sn20.7:0.1": "Linked Discourses 20.7 ",
  "sn20.7:0.2": "1. Similes ",
  "sn20.7:0.3": "The Drum Called Plugger ",
  "sn20.7:1.1": "At Sāvatthī. ",
  "sn20.7:1.2": "“Once upon a time, mendicants, the Dasārahas had a *mridangam* drum called the Plugger. ",
  "sn20.7:1.3": "When the Plugger cracked, the Dasārahas patched it with another plug. ",
  "sn20.7:1.4": "Eventually, there came a time when the original wooden shell for the drumskin disappeared ",
  "sn20.7:1.5": "and all that was left of the *mridangam* Plugger was a mass of plugs. ",
  "sn20.7:1.6": "In the same way, in a future time there will be mendicants who won’t want to listen when discourses spoken by the Realized Onedeep, profound, transcendent, dealing with emptinessare being recited. They won’t actively listen or try to understand, nor will they think those teachings are worth learning and memorizing. ",
  "sn20.7:2.1": "But when discourses composed by poetspoetry, with fancy words and phrases, composed by outsiders or spoken by disciplesare being recited they will want to listen. They’ll actively listen and try to understand, and they’ll think those teachings are worth learning and memorizing. ",
  "sn20.7:2.2": "And that is how the discourses spoken by the Realized Onedeep, profound, transcendent, dealing with emptinesswill disappear. ",
  "sn20.7:2.3": "So you should train like this: ",
  "sn20.7:2.4": "‘When discourses spoken by the Realized Onedeep, profound, transcendent, dealing with emptinessare being recited we will want to listen. We will actively listen and trying to understand, and we will think those teachings are worth learning and memorizing.’ ",
  "sn20.7:2.5": "That’s how you should train.” ",
  "sn20.8:0.1": "Linked Discourses 20.8 ",
  "sn20.8:0.2": "1. Similes ",
  "sn20.8:0.3": "Wood Blocks ",
  "sn20.8:1.1": "So I have heard. ",
  "sn20.8:1.2": "At one time the Buddha was staying near Vesālī, at the Great Wood, in the hall with the peaked roof. ",
  "sn20.8:1.3": "There the Buddha addressed the mendicants, ",
  "sn20.8:1.4": "“Mendicants!” ",
  "sn20.8:1.5": "“Venerable sir,” they replied. ",
  "sn20.8:1.6": "The Buddha said this: ",
  "sn20.8:2.1": "“Mendicants, these days the Licchavis live using wood blocks as pillows, and they exercise diligently and keenly. ",
  "sn20.8:2.2": "King Ajātasattu of Magadha, son of the princess of Videha, finds no vulnerability, he’s got no opportunity. ",
  "sn20.8:2.3": "But in the future the Licchavis will become delicate, with soft and tender hands and feet. ",
  "sn20.8:2.4": "They’ll sleep on soft beds with down pillows until the sun comes up. ",
  "sn20.8:2.5": "King Ajātasattu of Magadha, son of the princess of Videha, will find a vulnerability and get an opportunity. ",
  "sn20.8:3.1": "These days the mendicants live using wood blocks as pillows, and they meditate diligently and keenly. ",
  "sn20.8:3.2": "Māra the Wicked finds no vulnerability, he’s got no opportunity. ",
  "sn20.8:3.3": "But in the future the mendicants will become delicate, with soft and tender hands and feet. ",
  "sn20.8:3.4": "They’ll sleep on soft beds with down pillows until the sun comes up. ",
  "sn20.8:3.5": "Māra the Wicked will find a vulnerability and get an opportunity. ",
  "sn20.8:3.6": "So you should train like this: ",
  "sn20.8:3.7": "‘We will live using wood blocks as pillows, and we will meditate diligently and keenly.’ ",
  "sn20.8:3.8": "That’s how you should train.” ",
  "sn20.9:0.1": "Linked Discourses 20.9 ",
  "sn20.9:0.2": "1. Similes ",
  "sn20.9:0.3": "A Bull Elephant ",
  "sn20.9:1.1": "So I have heard. ",
  "sn20.9:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn20.9:1.3": "Now at that time a certain junior mendicant went to visit families too often. ",
  "sn20.9:1.4": "The mendicants said to him, ",
  "sn20.9:1.5": "“Venerable, don’t go to visit families too often.” ",
  "sn20.9:1.6": "But that mendicant, when spoken to by the mendicants, said this, ",
  "sn20.9:1.7": "“But these senior mendicants think they can go to visit families, so why can’t I?” ",
  "sn20.9:2.1": "And then several mendicants went up to the Buddha, bowed, sat down to one side, and told him what had happened. The Buddha said: ",
  "sn20.9:2.2": "",
  "sn20.9:2.3": "",
  "sn20.9:2.4": "",
  "sn20.9:2.5": "",
  "sn20.9:2.6": "",
  "sn20.9:3.1": "“Once upon a time, mendicants, there was a great lake in the jungle, ",
  "sn20.9:3.2": "with bull elephants living nearby. ",
  "sn20.9:3.3": "They’d plunge into the lake and pull up lotus bulbs with their trunks. They’d wash them thoroughly until they were free of mud before chewing and swallowing them. ",
  "sn20.9:3.4": "That was good for their appearance and strength, and wouldn’t result in death or deadly pain. ",
  "sn20.9:3.5": "The young cubs, following the example of the great bull elephants, plunged into the lake and pulled up lotus bulbs with their trunks. But they didn’t wash them thoroughly, and while they were still muddy they chewed and swallowed them. ",
  "sn20.9:3.6": "That was not good for their appearance and strength, and resulted in death or deadly pain. ",
  "sn20.9:3.7": "",
  "sn20.9:4.1": "In the same way, there are senior mendicants who robe up in the morning and, taking their bowl and robe, enter the town or village for alms. ",
  "sn20.9:4.2": "There they speak on the teachings, ",
  "sn20.9:4.3": "and lay people demonstrate their confidence in them. ",
  "sn20.9:4.4": "And when they get things, they use them untied, uninfatuated, unattached, seeing the drawbacks, and understanding the escape. ",
  "sn20.9:4.5": "That’s good for their appearance and strength, and doesn’t result in death or deadly pain. ",
  "sn20.9:4.6": "Junior mendicants, following the example of the senior mendicants, robe up in the morning and, taking their bowl and robe, enter the town or village for alms. ",
  "sn20.9:4.7": "There they speak on the teachings, ",
  "sn20.9:4.8": "and lay people demonstrate their confidence in them. ",
  "sn20.9:4.9": "But when they get things, they use them tied, infatuated, attached, blind to the drawbacks, not understanding the escape. ",
  "sn20.9:4.10": "That’s not good for their appearance and strength, and results in death or deadly pain. ",
  "sn20.9:4.11": "So you should train like this: ",
  "sn20.9:4.12": "‘When we get things, we will use them untied, uninfatuated, unattached, seeing the drawbacks, and understanding the escape.’ ",
  "sn20.9:4.13": "That’s how you should train.” ",
  "sn20.10:0.1": "Linked Discourses 20.10 ",
  "sn20.10:0.2": "1. Similes ",
  "sn20.10:0.3": "A Cat ",
  "sn20.10:1.1": "At Sāvatthī. ",
  "sn20.10:1.2": "Now at that time a certain mendicant socialized with families too often. ",
  "sn20.10:1.3": "The mendicants said to him, ",
  "sn20.10:1.4": "“Venerable, don’t socialize with families too often.” ",
  "sn20.10:1.5": "But that mendicant, when spoken to by the mendicants, did not stop. ",
  "sn20.10:1.6": "And then several mendicants went up to the Buddha, bowed, sat down to one side, and told him what had happened. The Buddha said: ",
  "sn20.10:1.7": "",
  "sn20.10:1.8": "",
  "sn20.10:1.9": "",
  "sn20.10:1.10": "",
  "sn20.10:2.1": "“Once upon a time, mendicants, a cat was standing by an alley or a drain or a dustbin hunting a little mouse, thinking, ",
  "sn20.10:2.2": "‘When that little mouse comes out to feed, I’ll catch it right there and eat it!’ ",
  "sn20.10:2.3": "And then that little mouse came out to feed. ",
  "sn20.10:2.4": "The cat caught it and hastily swallowed it without chewing. ",
  "sn20.10:2.5": "But that little mouse ate its intestines and mesentery, ",
  "sn20.10:2.6": "resulting in death and deadly pain. ",
  "sn20.10:3.1": "In the same way, take a certain monk who robes up in the morning and, taking his bowl and robe, enters the village or town for alms without guarding body, speech, and mind, without establishing mindfulness, and without restraining the sense faculties. ",
  "sn20.10:3.2": "There he sees a lady scantily clad, with revealing clothes. ",
  "sn20.10:3.3": "Lust infects his mind, ",
  "sn20.10:3.4": "resulting in death or deadly pain. ",
  "sn20.10:3.5": "For it is death in the training of the Noble One to disavow the training and return to a lesser life. ",
  "sn20.10:3.6": "And it is deadly pain to commit one of the corrupt offenses ",
  "sn20.10:3.7": "for which rehabilitation is possible. ",
  "sn20.10:3.8": "So you should train like this: ",
  "sn20.10:3.9": "‘We will enter the village or town for alms guarding body, speech, and mind, establishing mindfulness, and restraining the sense faculties.’ ",
  "sn20.10:3.10": "That’s how you should train.” ",
  "sn20.11:0.1": "Linked Discourses 20.11 ",
  "sn20.11:0.2": "1. Similes ",
  "sn20.11:0.3": "A Jackal ",
  "sn20.11:1.1": "At Sāvatthī. ",
  "sn20.11:1.2": "“Mendicants, did you hear an old jackal howling at the crack of dawn?” ",
  "sn20.11:1.3": "“Yes, sir.” ",
  "sn20.11:1.4": "“That old jackal has the disease called mange. ",
  "sn20.11:1.5": "Yet it still goes where it wants, ",
  "sn20.11:1.6": "stands where it wants, ",
  "sn20.11:1.7": "sits where it wants, ",
  "sn20.11:1.8": "and lies down where it wants. ",
  "sn20.11:1.9": "And the cool breeze still blows on it. ",
  "sn20.11:1.10": "A certain person here who claims to follow the Sakyan would be lucky to experience even such an incarnation. ",
  "sn20.11:1.11": "So you should train like this: ",
  "sn20.11:1.12": "‘We will stay diligent.’ ",
  "sn20.11:1.13": "That’s how you should train.” ",
  "sn20.12:0.1": "Linked Discourses 20.12 ",
  "sn20.12:0.2": "1. Similes ",
  "sn20.12:0.3": "A Jackal (2nd) ",
  "sn20.12:1.1": "At Sāvatthī. ",
  "sn20.12:1.2": "“Mendicants, did you hear an old jackal howling at the crack of dawn?” ",
  "sn20.12:1.3": "“Yes, sir.” ",
  "sn20.12:1.4": "“There might be some gratitude and thankfulness in that old jackal, but there is none in a certain person here who claims to follow the Sakyan. ",
  "sn20.12:1.5": "So you should train like this: ",
  "sn20.12:1.6": "‘We will be grateful and thankful. ",
  "sn20.12:1.7": "We won’t forget even a small thing done for us.’ ",
  "sn20.12:1.8": "That’s how you should train.” ",
  "sn20.12:1.9": "",
  "sn20.12:1.10": "",
  "sn20.12:2.1": "",
  "sn20.12:2.2": "",
  "sn20.12:2.3": "",
  "sn20.12:2.4": "",
  "sn20.12:2.5": "The Linked Discourses with similes are complete. "
}
window.BILARA["sn20_v1"]["en"]["sn20_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
