window.BILARA = window.BILARA || {};
window.BILARA["sn25_v1"] = window.BILARA["sn25_v1"] || {};
window.BILARA["sn25_v1"]["en"] = {
  "sn25.1:0.1": "Linked Discourses 25.1 ",
  "sn25.1:0.2": "1. The Eye ",
  "sn25.1:0.3": "The Eye ",
  "sn25.1:1.1": "At Sāvatthī. ",
  "sn25.1:1.2": "“Mendicants, the eye is impermanent, decaying, and perishing. ",
  "sn25.1:1.3": "The ear, ",
  "sn25.1:1.4": "nose, ",
  "sn25.1:1.5": "tongue, ",
  "sn25.1:1.6": "body, ",
  "sn25.1:1.7": "and mind are impermanent, decaying, and perishing. ",
  "sn25.1:1.8": "Someone who has faith and confidence in these teachings is called a follower by faith. They’ve stepped into the sure path, they’ve stepped into the level of the true person, and they’ve passed beyond the level of the untrue person. ",
  "sn25.1:1.9": "They can’t do any deed which would make them be reborn in hell, the animal realm, or the ghost realm. ",
  "sn25.1:1.10": "They can’t die without realizing the fruit of stream-entry. ",
  "sn25.1:2.1": "Someone who accepts these teachings after deliberating them with a degree of wisdom is called a follower of teachings. They’ve stepped into the sure path, they’ve stepped into the level of the true person, and they’ve passed beyond the level of the untrue person. ",
  "sn25.1:2.2": "They can’t do any deed which would make them be reborn in hell, the animal realm, or the ghost realm. ",
  "sn25.1:2.3": "They can’t die without realizing the fruit of stream-entry. ",
  "sn25.1:2.4": "Someone who understands and sees these principles is called a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn25.2:0.1": "Linked Discourses 25.2 ",
  "sn25.2:0.2": "1. The Eye ",
  "sn25.2:0.3": "Sights ",
  "sn25.2:1.1": "At Sāvatthī. ",
  "sn25.2:1.2": "“Mendicants, sights are impermanent, decaying, and perishing. ",
  "sn25.2:1.3": "Sounds, ",
  "sn25.2:1.4": "smells, ",
  "sn25.2:1.5": "tastes, ",
  "sn25.2:1.6": "touches, ",
  "sn25.2:1.7": "and ideas are impermanent, decaying, and perishing. ",
  "sn25.2:1.8": "Someone who has faith and confidence in these teachings is called a follower by faith. They’ve stepped into the sure path, they’ve stepped into the level of the true person, and they’ve passed beyond the level of the untrue person. ",
  "sn25.2:1.9": "They can’t do any deed which would make them be reborn in hell, the animal realm, or the ghost realm. ",
  "sn25.2:1.10": "They can’t die without realizing the fruit of stream-entry. ",
  "sn25.2:2.1": "Someone who accepts these teachings after deliberating them with a degree of wisdom is called a follower of teachings. They’ve stepped into the sure path, they’ve stepped into the level of the true person, and they’ve passed beyond the level of the untrue person. ",
  "sn25.2:2.2": "They can’t do any deed which would make them be reborn in hell, the animal realm, or the ghost realm. ",
  "sn25.2:2.3": "They can’t die without realizing the fruit of stream-entry. ",
  "sn25.2:2.4": "Someone who understands and sees these principles is called ",
  "sn25.2:2.5": "a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn25.3:0.1": "Linked Discourses 25.3 ",
  "sn25.3:0.2": "1. The Eye ",
  "sn25.3:0.3": "Consciousness ",
  "sn25.3:1.1": "At Sāvatthī. ",
  "sn25.3:1.2": "“Mendicants, eye consciousness is impermanent, decaying, and perishing. ",
  "sn25.3:1.3": "Ear consciousness, ",
  "sn25.3:1.4": "nose consciousness, ",
  "sn25.3:1.5": "tongue consciousness, ",
  "sn25.3:1.6": "body consciousness, ",
  "sn25.3:1.7": "and mind consciousness are impermanent, decaying, and perishing. ",
  "sn25.3:1.8": "Someone who has faith and confidence in these teachings is called a follower by faith. …” ",
  "sn25.3:1.9": "",
  "sn25.4:0.1": "Linked Discourses 25.4 ",
  "sn25.4:0.2": "1. The Eye ",
  "sn25.4:0.3": "Contact ",
  "sn25.4:1.1": "At Sāvatthī. ",
  "sn25.4:1.2": "“Mendicants, eye contact is impermanent, decaying, and perishing. ",
  "sn25.4:1.3": "Ear contact, ",
  "sn25.4:1.4": "nose contact, ",
  "sn25.4:1.5": "tongue contact, ",
  "sn25.4:1.6": "body contact, ",
  "sn25.4:1.7": "and mind contact are impermanent, decaying, and perishing. ",
  "sn25.4:1.8": "Someone who has faith and confidence in these teachings is called a follower by faith. …” ",
  "sn25.4:1.9": "",
  "sn25.5:0.1": "Linked Discourses 25.5 ",
  "sn25.5:0.2": "1. The Eye ",
  "sn25.5:0.3": "Feeling ",
  "sn25.5:1.1": "At Sāvatthī. ",
  "sn25.5:1.2": "“Mendicants, feeling born of eye contact is impermanent, decaying, and perishing. ",
  "sn25.5:1.3": "Feeling born of ear contact, ",
  "sn25.5:1.4": "feeling born of nose contact, ",
  "sn25.5:1.5": "feeling born of tongue contact, ",
  "sn25.5:1.6": "feeling born of body contact, ",
  "sn25.5:1.7": "and feeling born of mind contact are impermanent, decaying, and perishing. ",
  "sn25.5:1.8": "Someone who has faith and confidence in these teachings is called a follower by faith. …” ",
  "sn25.5:1.9": "",
  "sn25.6:0.1": "Linked Discourses 25.6 ",
  "sn25.6:0.2": "1. The Eye ",
  "sn25.6:0.3": "Perception ",
  "sn25.6:1.1": "At Sāvatthī. ",
  "sn25.6:1.2": "“Mendicants, perception of sights is impermanent, decaying, and perishing. ",
  "sn25.6:1.3": "Perception of sounds, ",
  "sn25.6:1.4": "perception of smells, ",
  "sn25.6:1.5": "perception of tastes, ",
  "sn25.6:1.6": "perception of touches, ",
  "sn25.6:1.7": "and perception of ideas are impermanent, decaying, and perishing. ",
  "sn25.6:1.8": "Someone who has faith and confidence in these teachings is called a follower by faith. …” ",
  "sn25.6:1.9": "",
  "sn25.7:0.1": "Linked Discourses 25.7 ",
  "sn25.7:0.2": "1. The Eye ",
  "sn25.7:0.3": "Intention ",
  "sn25.7:1.1": "At Sāvatthī. ",
  "sn25.7:1.2": "“Mendicants, intention regarding sights is impermanent, decaying, and perishing. ",
  "sn25.7:1.3": "Intention regarding sounds, ",
  "sn25.7:1.4": "intention regarding smells, ",
  "sn25.7:1.5": "intention regarding tastes, ",
  "sn25.7:1.6": "intention regarding touches, ",
  "sn25.7:1.7": "and intentions regarding ideas are impermanent, decaying, and perishing. ",
  "sn25.7:1.8": "Someone who has faith and confidence in these teachings is called a follower by faith. …” ",
  "sn25.7:1.9": "",
  "sn25.8:0.1": "Linked Discourses 25.8 ",
  "sn25.8:0.2": "1. The Eye ",
  "sn25.8:0.3": "Craving For Sights ",
  "sn25.8:1.1": "At Sāvatthī. ",
  "sn25.8:1.2": "“Mendicants, craving for sights is impermanent, decaying, and perishing. ",
  "sn25.8:1.3": "Craving for sounds, ",
  "sn25.8:1.4": "craving for smells, ",
  "sn25.8:1.5": "craving for tastes, ",
  "sn25.8:1.6": "craving for touches, ",
  "sn25.8:1.7": "and craving for ideas are impermanent, decaying, and perishing. ",
  "sn25.8:1.8": "Someone who has faith and confidence in these teachings is called a follower by faith. …” ",
  "sn25.8:1.9": "",
  "sn25.9:0.1": "Linked Discourses 25.9 ",
  "sn25.9:0.2": "1. The Eye ",
  "sn25.9:0.3": "Elements ",
  "sn25.9:1.1": "At Sāvatthī. ",
  "sn25.9:1.2": "“Mendicants, the earth element is impermanent, decaying, and perishing. ",
  "sn25.9:1.3": "The water element, ",
  "sn25.9:1.4": "the fire element, ",
  "sn25.9:1.5": "the air element, ",
  "sn25.9:1.6": "the space element, ",
  "sn25.9:1.7": "and the consciousness element are impermanent, decaying, and perishing. ",
  "sn25.9:1.8": "Someone who has faith and confidence in these teachings is called a follower by faith. …” ",
  "sn25.9:1.9": "",
  "sn25.10:0.1": "Linked Discourses 25.10 ",
  "sn25.10:0.2": "1. The Eye ",
  "sn25.10:0.3": "The Aggregates ",
  "sn25.10:1.1": "At Sāvatthī. ",
  "sn25.10:1.2": "“Mendicants, form is impermanent, decaying, and perishing. ",
  "sn25.10:1.3": "Feeling, ",
  "sn25.10:1.4": "perception, ",
  "sn25.10:1.5": "choices, ",
  "sn25.10:1.6": "and consciousness are impermanent, decaying, and perishing. ",
  "sn25.10:1.7": "Someone who has faith and confidence in these teachings is called a follower by faith. They’ve stepped into the sure path, they’ve stepped into the level of the true person, and they’ve passed beyond the level of the untrue person. ",
  "sn25.10:1.8": "They can’t do any deed which would make them be reborn in hell, the animal realm, or the ghost realm. ",
  "sn25.10:1.9": "They can’t die without realizing the fruit of stream-entry. ",
  "sn25.10:2.1": "Someone who accepts these teachings after deliberating them with a degree of wisdom is called a follower of teachings. They’ve stepped into the sure path, they’ve stepped into the level of the true person, and they’ve passed beyond the level of the untrue person. ",
  "sn25.10:2.2": "They can’t do any deed which would make them be reborn in hell, the animal realm, or the ghost realm. ",
  "sn25.10:2.3": "They can’t die without realizing the fruit of stream-entry. ",
  "sn25.10:2.4": "Someone who understands and sees these principles is called ",
  "sn25.10:2.5": "a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn25.10:2.6": "",
  "sn25.10:2.7": "",
  "sn25.10:3.1": "",
  "sn25.10:3.2": "",
  "sn25.10:3.3": "",
  "sn25.10:3.4": "",
  "sn25.10:3.5": "The Linked Discourses on stepping into are complete. "
}
window.BILARA["sn25_v1"]["en"]["sn25_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
