window.BILARA = window.BILARA || {};
window.BILARA["sn32_v1"] = window.BILARA["sn32_v1"] || {};
window.BILARA["sn32_v1"]["en"] = {
  "sn32.1:0.1": "Linked Discourses 32.1 ",
  "sn32.1:0.2": "1. Gods of the Thunderclouds ",
  "sn32.1:0.3": "Plain Version ",
  "sn32.1:1.1": "At Sāvatthī. ",
  "sn32.1:1.2": "“Mendicants, I will teach you about the gods of the thundercloud host. ",
  "sn32.1:1.3": "Listen … ",
  "sn32.1:1.4": "And what are the gods of the thundercloud host? ",
  "sn32.1:1.5": "There are gods of the cool thunderclouds, ",
  "sn32.1:1.6": "warm thunderclouds, ",
  "sn32.1:1.7": "stormy thunderclouds, ",
  "sn32.1:1.8": "windy thunderclouds, ",
  "sn32.1:1.9": "and rainy thunderclouds. ",
  "sn32.1:1.10": "These are called gods of the thundercloud host.” ",
  "sn32.2:0.1": "Linked Discourses 32.2 ",
  "sn32.2:0.2": "1. Gods of the Thunderclouds ",
  "sn32.2:0.3": "Good Conduct ",
  "sn32.2:1.1": "At Sāvatthī. ",
  "sn32.2:1.2": "Seated to one side, that mendicant said to the Buddha: ",
  "sn32.2:1.3": "“Sir, what is the cause, what is the reason why someone, when their body breaks up, after death, is reborn in the company of the gods of the thundercloud host?” ",
  "sn32.2:1.4": "“Mendicant, it’s when someone does good things by way of body, speech, and mind. ",
  "sn32.2:1.5": "And they’ve heard: ",
  "sn32.2:1.6": "‘The gods of the thundercloud host are long-lived, beautiful, and very happy.’ ",
  "sn32.2:1.7": "They think: ",
  "sn32.2:1.8": "‘If only, when my body breaks up, after death, I would be reborn in the company of the gods of the thundercloud host!’ ",
  "sn32.2:1.9": "When their body breaks up, after death, they’re reborn in the company of the gods of the thundercloud host. ",
  "sn32.2:1.10": "This is the cause, this is the reason why someone, when their body breaks up, after death, is reborn in the company of the gods of the thundercloud host.” ",
  "sn32.3-12:0.1": "Linked Discourses 32.3–12 ",
  "sn32.3-12:0.2": "1. Gods of the Thunderclouds ",
  "sn32.3-12:0.3": "Ten Discourses On How Giving Helps to Become a Cool Thundercloud God ",
  "sn32.3-12:1.1": "At Sāvatthī. ",
  "sn32.3-12:1.2": "Seated to one side, that mendicant said to the Buddha: ",
  "sn32.3-12:1.3": "“Sir, what is the cause, what is the reason why someone, when their body breaks up, after death, is reborn in the company of the gods of cool thunderclouds?” ",
  "sn32.3-12:1.4": "“Mendicant, it’s when someone does good things by way of body, speech, and mind. ",
  "sn32.3-12:1.5": "And they’ve heard: ",
  "sn32.3-12:1.6": "‘The gods of cool thunderclouds are long-lived, beautiful, and very happy.’ ",
  "sn32.3-12:1.7": "They think: ",
  "sn32.3-12:1.8": "‘If only, when my body breaks up, after death, I would be reborn in the company of the gods of the cool thunderclouds!’ ",
  "sn32.3-12:1.9": "They give food … ",
  "sn32.3-12:1.10": "a lamp. ",
  "sn32.3-12:1.11": "When their body breaks up, after death, they’re reborn in the company of the gods of cool thunderclouds. ",
  "sn32.3-12:1.12": "This is the cause, this is the reason why someone, when their body breaks up, after death, is reborn in the company of the gods of cool thunderclouds.” ",
  "sn32.13-52:0.1": "Linked Discourses 32.13–52 ",
  "sn32.13-52:0.2": "1. Gods of the Thunderclouds ",
  "sn32.13-52:0.3": "How Giving Helps to Become a Warm Thundercloud God, Etc. ",
  "sn32.13-52:1.1": "At Sāvatthī. ",
  "sn32.13-52:1.2": "Seated to one side, that mendicant said to the Buddha: ",
  "sn32.13-52:1.3": "“Sir, what is the cause, what is the reason why someone, when their body breaks up, after death, is reborn in the company of the gods of warm thunderclouds … ",
  "sn32.13-52:1.4": "stormy thunderclouds … ",
  "sn32.13-52:1.5": "windy thunderclouds … ",
  "sn32.13-52:1.6": "rainy thunderclouds?” ",
  "sn32.13-52:1.7": "“Mendicant, it’s when someone does good things by way of body, speech, and mind. ",
  "sn32.13-52:1.8": "And they’ve heard: ",
  "sn32.13-52:1.9": "‘The gods of rainy thunderclouds are long-lived, beautiful, and very happy.’ ",
  "sn32.13-52:1.10": "They think: ",
  "sn32.13-52:1.11": "‘If only, when my body breaks up, after death, I would be reborn in the company of the gods of rainy thunderclouds!’ ",
  "sn32.13-52:1.12": "They give food … ",
  "sn32.13-52:1.13": "a lamp. ",
  "sn32.13-52:1.14": "When their body breaks up, after death, they’re reborn in the company of the gods of rainy thunderclouds. ",
  "sn32.13-52:1.15": "This is the cause, this is the reason why someone, when their body breaks up, after death, is reborn in the company of the gods of rainy thunderclouds.” ",
  "sn32.53:0.1": "Linked Discourses 32.53 ",
  "sn32.53:0.2": "1. Gods of the Thunderclouds ",
  "sn32.53:0.3": "Gods of the Cool Thunderclouds ",
  "sn32.53:1.1": "At Sāvatthī. ",
  "sn32.53:1.2": "Seated to one side, that mendicant said to the Buddha: ",
  "sn32.53:1.3": "“Sir, what is the cause, what is the reason why sometimes it becomes cool?” ",
  "sn32.53:1.4": "“Mendicant, there are what are called gods of the cool thunderclouds. ",
  "sn32.53:1.5": "Sometimes they think: ",
  "sn32.53:1.6": "‘Why don’t we revel in our own kind of enjoyment?’ Then, in accordance with their wish, it becomes cool. ",
  "sn32.53:1.7": "This is the cause, this is the reason why sometimes it becomes cool.” ",
  "sn32.54:0.1": "Linked Discourses 32.54 ",
  "sn32.54:0.2": "1. Gods of the Thunderclouds ",
  "sn32.54:0.3": "Gods of the Warm Thunderclouds ",
  "sn32.54:1.1": "At Sāvatthī. ",
  "sn32.54:1.2": "Seated to one side, that mendicant said to the Buddha: ",
  "sn32.54:1.3": "“Sir, what is the cause, what is the reason why sometimes it becomes warm?” ",
  "sn32.54:1.4": "“Mendicant, there are what are called gods of the warm thunderclouds. ",
  "sn32.54:1.5": "Sometimes they think: ",
  "sn32.54:1.6": "‘Why don’t we revel in our own kind of enjoyment?’ Then, in accordance with their wish, it becomes warm. ",
  "sn32.54:1.7": "This is the cause, this is the reason why sometimes it becomes warm.” ",
  "sn32.55:0.1": "Linked Discourses 32.55 ",
  "sn32.55:0.2": "1. Gods of the Thunderclouds ",
  "sn32.55:0.3": "Gods of the Stormy Thunderclouds ",
  "sn32.55:1.1": "At Sāvatthī. ",
  "sn32.55:1.2": "Seated to one side, that mendicant said to the Buddha: ",
  "sn32.55:1.3": "“Sir, what is the cause, what is the reason why sometimes it becomes stormy?” ",
  "sn32.55:1.4": "“Mendicant, there are what are called gods of the stormy thunderclouds. ",
  "sn32.55:1.5": "Sometimes they think: ",
  "sn32.55:1.6": "‘Why don’t we revel in our own kind of enjoyment?’ Then, in accordance with their wish, it becomes stormy. ",
  "sn32.55:1.7": "This is the cause, this is the reason why sometimes it becomes stormy.” ",
  "sn32.56:0.1": "Linked Discourses 32.56 ",
  "sn32.56:0.2": "1. Gods of the Thunderclouds ",
  "sn32.56:0.3": "Gods of the Windy Thunderclouds ",
  "sn32.56:1.1": "At Sāvatthī. ",
  "sn32.56:1.2": "Seated to one side, that mendicant said to the Buddha: ",
  "sn32.56:1.3": "“Sir, what is the cause, what is the reason why sometimes it becomes windy?” ",
  "sn32.56:1.4": "“Mendicant, there are what are called gods of the windy thunderclouds. ",
  "sn32.56:1.5": "Sometimes they think: ",
  "sn32.56:1.6": "‘Why don’t we revel in our own kind of enjoyment?’ Then, in accordance with their wish, it becomes windy. ",
  "sn32.56:1.7": "This is the cause, this is the reason why sometimes it becomes windy.” ",
  "sn32.57:0.1": "Linked Discourses 32.57 ",
  "sn32.57:0.2": "1. Gods of the Thunderclouds ",
  "sn32.57:0.3": "Gods of the Rainy Thunderclouds ",
  "sn32.57:1.1": "At Sāvatthī. ",
  "sn32.57:1.2": "Seated to one side, that mendicant said to the Buddha: ",
  "sn32.57:1.3": "“Sir, what is the cause, what is the reason why sometimes the heavens rain?” ",
  "sn32.57:1.4": "“Mendicant, there are what are called gods of the rainy thunderclouds. ",
  "sn32.57:1.5": "Sometimes they think: ",
  "sn32.57:1.6": "‘Why don’t we revel in our own kind of enjoyment?’ Then, in accordance with their wish, the heavens rain down. ",
  "sn32.57:1.7": "This is the cause, this is the reason why sometimes the heavens rain.” ",
  "sn32.57:1.8": "",
  "sn32.57:1.9": "",
  "sn32.57:1.10": "",
  "sn32.57:2.1": "",
  "sn32.57:2.2": "",
  "sn32.57:2.3": "",
  "sn32.57:2.4": "",
  "sn32.57:2.5": "The Linked Discourses on gods of the clouds are complete. "
}
window.BILARA["sn32_v1"]["en"]["sn32_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
