window.BILARA = window.BILARA || {};
window.BILARA["sn36_v1"] = window.BILARA["sn36_v1"] || {};
window.BILARA["sn36_v1"]["en"] = {
  "sn36.1:0.1": "Linked Discourses 36.1 ",
  "sn36.1:0.2": "1. With Verses ",
  "sn36.1:0.3": "Immersion ",
  "sn36.1:1.1": "“Mendicants, there are these three feelings. ",
  "sn36.1:1.2": "What three? ",
  "sn36.1:1.3": "Pleasant, painful, and neutral feeling. ",
  "sn36.1:1.4": "These are the three feelings. ",
  "sn36.1:2.1": "Stilled, aware, ",
  "sn36.1:2.2": "a mindful disciple of the Buddha ",
  "sn36.1:2.3": "understands feelings, ",
  "sn36.1:2.4": "the cause of feelings, ",
  "sn36.1:3.1": "where they cease, ",
  "sn36.1:3.2": "and the path that leads to their ending. ",
  "sn36.1:3.3": "With the ending of feelings, a mendicant ",
  "sn36.1:3.4": "is hungerless, quenched.” ",
  "sn36.2:0.1": "Linked Discourses 36.2 ",
  "sn36.2:0.2": "1. With Verses ",
  "sn36.2:0.3": "Pleasure ",
  "sn36.2:1.1": "“Mendicants, there are these three feelings. ",
  "sn36.2:1.2": "What three? ",
  "sn36.2:1.3": "Pleasant, painful, and neutral feeling. ",
  "sn36.2:1.4": "These are the three feelings. ",
  "sn36.2:2.1": "Whatever is felt ",
  "sn36.2:2.2": "internally and externally",
  "sn36.2:2.3": "whether pleasure or pain ",
  "sn36.2:2.4": "as well as what’s neutral",
  "sn36.2:3.1": "having known this as suffering, ",
  "sn36.2:3.2": "deceptive, breaking apart, ",
  "sn36.2:3.3": "one sees them vanish <j>as they’re experienced again and again: ",
  "sn36.2:3.4": "that’s how to be free of desire for them.” ",
  "sn36.3:0.1": "Linked Discourses 36.3 ",
  "sn36.3:0.2": "1. With Verses ",
  "sn36.3:0.3": "Giving Up ",
  "sn36.3:1.1": "“Mendicants, there are these three feelings. ",
  "sn36.3:1.2": "What three? ",
  "sn36.3:1.3": "Pleasant, painful, and neutral feeling. ",
  "sn36.3:1.4": "The underlying tendency to greed should be given up when it comes to pleasant feeling. The underlying tendency to aversion should be given up when it comes to painful feeling. The underlying tendency to ignorance should be given up when it comes to neutral feeling. ",
  "sn36.3:1.5": "When a mendicant has given up these underlying tendencies, they’re called a mendicant without underlying tendencies, who sees rightly, has cut off craving, cast off the fetters, and by rightly comprehending conceit has made an end of suffering. ",
  "sn36.3:2.1": "When you feel pleasure ",
  "sn36.3:2.2": "without understanding feeling, ",
  "sn36.3:2.3": "the underlying tendency to greed is there, ",
  "sn36.3:2.4": "if you don’t see the escape. ",
  "sn36.3:3.1": "When you feel pain ",
  "sn36.3:3.2": "without understanding feeling, ",
  "sn36.3:3.3": "the underlying tendency to aversion is there, ",
  "sn36.3:3.4": "if you don’t see the escape. ",
  "sn36.3:4.1": "As for that peaceful, neutral feeling: ",
  "sn36.3:4.2": "he of vast wisdom has taught ",
  "sn36.3:4.3": "that if you relish it, ",
  "sn36.3:4.4": "you’re still not released from suffering. ",
  "sn36.3:5.1": "But when a mendicant is keen, ",
  "sn36.3:5.2": "not neglecting situational awareness, ",
  "sn36.3:5.3": "that astute person ",
  "sn36.3:5.4": "understands all feelings. ",
  "sn36.3:6.1": "Completely understanding feelings, ",
  "sn36.3:6.2": "they’re without defilements in this very life. ",
  "sn36.3:6.3": "That knowledge master is firm in principle; ",
  "sn36.3:6.4": "when their body breaks up, they can’t be reckoned.” ",
  "sn36.4:0.1": "Linked Discourses 36.4 ",
  "sn36.4:0.2": "1. With Verses ",
  "sn36.4:0.3": "The Abyss ",
  "sn36.4:1.1": "“Mendicants, when an unlearned ordinary person says that ",
  "sn36.4:1.2": "there’s an abyss under the ocean, ",
  "sn36.4:1.3": "they’re speaking of something that doesn’t exist. ",
  "sn36.4:1.4": "",
  "sn36.4:1.5": "‘Abyss’ is a term for painful physical feelings. ",
  "sn36.4:1.6": "When an unlearned ordinary person experiences painful physical feelings they sorrow and wail and lament, beating their breast and falling into confusion. ",
  "sn36.4:1.7": "They’re called an unlearned ordinary person who hasn’t stood up in the abyss and has found no footing. ",
  "sn36.4:1.8": "When a learned noble disciple experiences painful physical feelings they don’t sorrow or wail or lament, beating their breast and falling into confusion. ",
  "sn36.4:1.9": "They’re called a learned noble disciple who has stood up in the abyss and found a footing. ",
  "sn36.4:2.1": "If you can’t abide ",
  "sn36.4:2.2": "those painful physical feelings ",
  "sn36.4:2.3": "that arise and sap your vitality; ",
  "sn36.4:2.4": "if you tremble at their touch, ",
  "sn36.4:3.1": "weeping and wailing, ",
  "sn36.4:3.2": "a weakling lacking strength",
  "sn36.4:3.3": "you won’t stand up in the abyss ",
  "sn36.4:3.4": "and find a footing. ",
  "sn36.4:4.1": "If you can endure ",
  "sn36.4:4.2": "those painful physical feelings ",
  "sn36.4:4.3": "that arise and sap your vitality; ",
  "sn36.4:4.4": "if you don’t tremble at their touch",
  "sn36.4:4.5": "you stand up in the abyss ",
  "sn36.4:4.6": "and find a footing.” ",
  "sn36.5:0.1": "Linked Discourses 36.5 ",
  "sn36.5:0.2": "1. With Verses ",
  "sn36.5:0.3": "Should Be Seen ",
  "sn36.5:1.1": "“Mendicants, there are these three feelings. ",
  "sn36.5:1.2": "What three? ",
  "sn36.5:1.3": "Pleasant, painful, and neutral feeling. ",
  "sn36.5:1.4": "Pleasant feeling should be seen as suffering. Painful feeling should be seen as a dart. Neutral feeling should be seen as impermanent. ",
  "sn36.5:1.5": "When a mendicant has seen these three feelings in this way, ",
  "sn36.5:1.6": "they’re called a mendicant who sees rightly, has cut off craving, cast off the fetters, and by rightly comprehending conceit has made an end of suffering. ",
  "sn36.5:2.1": "A mendicant who sees pleasure as pain, ",
  "sn36.5:2.2": "and suffering as a dart, ",
  "sn36.5:2.3": "and that peaceful, neutral feeling ",
  "sn36.5:2.4": "as impermanent ",
  "sn36.5:3.1": "sees rightly; ",
  "sn36.5:3.2": "they completely understand feelings. ",
  "sn36.5:3.3": "Completely understanding feelings, ",
  "sn36.5:3.4": "they’re without defilements in this very life. ",
  "sn36.5:3.5": "That knowledge master is firm in principle; ",
  "sn36.5:3.6": "when their body breaks up, they can’t be reckoned.” ",
  "sn36.6:0.1": "Linked Discourses 36.6 ",
  "sn36.6:0.2": "1. With Verses ",
  "sn36.6:0.3": "An Arrow ",
  "sn36.6:1.1": "“Mendicants, an unlearned ordinary person feels pleasant, painful, and neutral feelings. ",
  "sn36.6:1.2": "A learned noble disciple also feels pleasant, painful, and neutral feelings. ",
  "sn36.6:1.3": "What, then, is the difference between a learned noble disciple and an ordinary unlearned person?” ",
  "sn36.6:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn36.6:1.5": "“When an unlearned ordinary person experiences painful physical feelings they sorrow and wail and lament, beating their breast and falling into confusion. ",
  "sn36.6:1.6": "They experience two feelings: ",
  "sn36.6:1.7": "physical and mental. ",
  "sn36.6:1.8": "It’s like a person who is struck with an arrow, ",
  "sn36.6:1.9": "only to be struck with a second arrow. ",
  "sn36.6:1.10": "That person experiences the feeling of two arrows. ",
  "sn36.6:1.11": "In the same way, when an unlearned ordinary person experiences painful physical feelings they sorrow and wail and lament, beating their breast and falling into confusion. ",
  "sn36.6:1.12": "They experience two feelings: ",
  "sn36.6:1.13": "physical and mental. ",
  "sn36.6:1.14": "When they’re touched by painful feeling, they resist it. ",
  "sn36.6:1.15": "The underlying tendency for aversion towards painful feeling underlies that. ",
  "sn36.6:1.16": "When touched by painful feeling they look forward to enjoying sensual pleasures. ",
  "sn36.6:1.17": "Why is that? ",
  "sn36.6:1.18": "Because an unlearned ordinary person doesn’t understand any escape from painful feeling apart from sensual pleasures. ",
  "sn36.6:1.19": "Since they look forward to enjoying sensual pleasures, the underlying tendency to greed for pleasant feeling underlies that. ",
  "sn36.6:1.20": "They don’t truly understand feelings’ origin, disappearance, gratification, drawback, and escape. ",
  "sn36.6:1.21": "The underlying tendency to ignorance about neutral feeling underlies that. ",
  "sn36.6:1.22": "If they feel a pleasant feeling, they feel it attached. ",
  "sn36.6:1.23": "If they feel a painful feeling, they feel it attached. ",
  "sn36.6:1.24": "If they feel a neutral feeling, they feel it attached. ",
  "sn36.6:1.25": "They’re called an unlearned ordinary person who is attached to rebirth, old age, and death, to sorrow, lamentation, pain, sadness, and distress. They are attached to suffering, I say. ",
  "sn36.6:2.1": "When a learned noble disciple experiences painful physical feelings they don’t sorrow or wail or lament, beating their breast and falling into confusion. ",
  "sn36.6:2.2": "They experience one feeling: ",
  "sn36.6:2.3": "physical, not mental. ",
  "sn36.6:3.1": "It’s like a person who is struck with an arrow, ",
  "sn36.6:3.2": "but was not struck with a second arrow. ",
  "sn36.6:3.3": "That person would experience the feeling of one arrow. ",
  "sn36.6:3.4": "In the same way, when a learned noble disciple experiences painful physical feelings they don’t sorrow or wail or lament, beating their breast and falling into confusion. ",
  "sn36.6:3.5": "They experience one feeling: ",
  "sn36.6:3.6": "physical, not mental. ",
  "sn36.6:3.7": "When they’re touched by painful feeling, they don’t resist it. ",
  "sn36.6:3.8": "There’s no underlying tendency for aversion towards painful feeling underlying that. ",
  "sn36.6:3.9": "When touched by painful feeling they don’t look forward to enjoying sensual pleasures. ",
  "sn36.6:3.10": "Why is that? ",
  "sn36.6:3.11": "Because a learned noble disciple understands an escape from painful feeling apart from sensual pleasures. ",
  "sn36.6:3.12": "Since they don’t look forward to enjoying sensual pleasures, there’s no underlying tendency to greed for pleasant feeling underlying that. ",
  "sn36.6:3.13": "They truly understand feelings’ origin, disappearance, gratification, drawback, and escape. ",
  "sn36.6:3.14": "There’s no underlying tendency to ignorance about neutral feeling underlying that. ",
  "sn36.6:3.15": "If they feel a pleasant feeling, they feel it detached. ",
  "sn36.6:3.16": "If they feel a painful feeling, they feel it detached. ",
  "sn36.6:3.17": "If they feel a neutral feeling, they feel it detached. ",
  "sn36.6:3.18": "They’re called a learned noble disciple who is detached from rebirth, old age, and death, from sorrow, lamentation, pain, sadness, and distress. They are detached from suffering, I say. ",
  "sn36.6:3.19": "This is the difference between a learned noble disciple and an unlearned ordinary person. ",
  "sn36.6:4.1": "A wise and learned person does not not feel ",
  "sn36.6:4.2": "the feeling of pleasure and pain. ",
  "sn36.6:4.3": "This is the great difference of skill ",
  "sn36.6:4.4": "between the wise one and the ordinary. ",
  "sn36.6:5.1": "A learned person who has appraised the teaching ",
  "sn36.6:5.2": "discerns this world and the next. ",
  "sn36.6:5.3": "Desirable things don’t disturb their mind, ",
  "sn36.6:5.4": "nor are they repelled by the undesirable. ",
  "sn36.6:6.1": "Both favoring and opposing ",
  "sn36.6:6.2": "are cleared and ended, they are no more. ",
  "sn36.6:6.3": "Knowing the stainless, sorrowless state, ",
  "sn36.6:6.4": "they who have gone beyond rebirth <j>understand rightly.” ",
  "sn36.7:0.1": "Linked Discourses 36.7 ",
  "sn36.7:0.2": "1. With Verses ",
  "sn36.7:0.3": "The Infirmary (1st) ",
  "sn36.7:1.1": "At one time the Buddha was staying near Vesālī, at the Great Wood, in the hall with the peaked roof. ",
  "sn36.7:1.2": "Then in the late afternoon, the Buddha came out of retreat and went to the infirmary, where he sat down on the seat spread out, ",
  "sn36.7:1.3": "and addressed the mendicants: ",
  "sn36.7:2.1": "“Mendicants, a mendicant should await their time mindful and aware. ",
  "sn36.7:2.2": "This is my instruction to you. ",
  "sn36.7:3.1": "And how is a mendicant mindful? ",
  "sn36.7:3.2": "It’s when a mendicant meditates by observing an aspect of the bodykeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn36.7:3.3": "They meditate observing an aspect of feelings … ",
  "sn36.7:3.4": "They meditate observing an aspect of the mind … ",
  "sn36.7:3.5": "They meditate observing an aspect of principleskeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn36.7:3.6": "That’s how a mendicant is mindful. ",
  "sn36.7:4.1": "And how is a mendicant aware? ",
  "sn36.7:4.2": "It’s when a mendicant acts with situational awareness when going out and coming back; when looking ahead and aside; when bending and extending the limbs; when bearing the outer robe, bowl and robes; when eating, drinking, chewing, and tasting; when urinating and defecating; when walking, standing, sitting, sleeping, waking, speaking, and keeping silent. ",
  "sn36.7:4.3": "That’s how a mendicant acts with situational awareness. ",
  "sn36.7:4.4": "A mendicant should await their time mindful and aware. ",
  "sn36.7:4.5": "This is my instruction to you. ",
  "sn36.7:5.1": "While a mendicant is meditating like thismindful, aware, diligent, keen, and resoluteif pleasant feelings arise, they understand: ",
  "sn36.7:5.2": "‘A pleasant feeling has arisen in me. ",
  "sn36.7:5.3": "That’s dependent, not independent. ",
  "sn36.7:5.4": "Dependent on what? ",
  "sn36.7:5.5": "Dependent on my own body. ",
  "sn36.7:5.6": "But this body is impermanent, conditioned, dependently originated. ",
  "sn36.7:5.7": "So how could a pleasant feeling be permanent, since it has arisen dependent on a body that is impermanent, conditioned, and dependently originated?’ ",
  "sn36.7:5.8": "They meditate observing impermanence, vanishing, dispassion, cessation, and letting go in the body and pleasant feeling. ",
  "sn36.7:5.9": "As they do so, they give up the underlying tendency for greed for the body and pleasant feeling. ",
  "sn36.7:6.1": "While a mendicant is meditating like thismindful, aware, diligent, keen, and resoluteif painful feelings arise, they understand: ",
  "sn36.7:6.2": "",
  "sn36.7:6.3": "‘A painful feeling has arisen in me. ",
  "sn36.7:6.4": "That’s dependent, not independent. ",
  "sn36.7:6.5": "Dependent on what? ",
  "sn36.7:6.6": "Dependent on my own body. ",
  "sn36.7:6.7": "But this body is impermanent, conditioned, dependently originated. ",
  "sn36.7:6.8": "So how could a painful feeling be permanent, since it has arisen dependent on a body that is impermanent, conditioned, and dependently originated?’ ",
  "sn36.7:6.9": "They meditate observing impermanence, vanishing, dispassion, cessation, and letting go in the body and painful feeling. ",
  "sn36.7:6.10": "As they do so, they give up the underlying tendency for aversion towards the body and painful feeling. ",
  "sn36.7:7.1": "While a mendicant is meditating like thismindful, aware, diligent, keen, and resoluteif neutral feelings arise, they understand: ",
  "sn36.7:7.2": "‘A neutral feeling has arisen in me. ",
  "sn36.7:7.3": "That’s dependent, not independent. ",
  "sn36.7:7.4": "Dependent on what? ",
  "sn36.7:7.5": "Dependent on my own body. ",
  "sn36.7:7.6": "But this body is impermanent, conditioned, dependently originated. ",
  "sn36.7:7.7": "So how could a neutral feeling be permanent, since it has arisen dependent on a body that is impermanent, conditioned, and dependently originated?’ ",
  "sn36.7:7.8": "They meditate observing impermanence, vanishing, dispassion, cessation, and letting go in the body and neutral feeling. ",
  "sn36.7:7.9": "As they do so, they give up the underlying tendency for ignorance towards the body and neutral feeling. ",
  "sn36.7:8.1": "If they feel a pleasant feeling, they understand that it’s impermanent, that they’re not attached to it, and that they don’t take pleasure in it. ",
  "sn36.7:8.2": "If they feel a painful feeling, they understand that it’s impermanent, that they’re not attached to it, and that they don’t take pleasure in it. ",
  "sn36.7:8.3": "If they feel a neutral feeling, they understand that it’s impermanent, that they’re not attached to it, and that they don’t take pleasure in it. ",
  "sn36.7:8.4": "If they feel a pleasant feeling, they feel it detached. ",
  "sn36.7:8.5": "If they feel a painful feeling, they feel it detached. ",
  "sn36.7:8.6": "If they feel a neutral feeling, they feel it detached. ",
  "sn36.7:8.7": "Feeling the end of the body draw close, they understand: ‘I feel the end of the body draw close.’ Feeling the end of life draw close, they understand: ‘I feel the end of life draw close.’ ",
  "sn36.7:8.8": "They understand: ‘When my body breaks up and my life has come to an end, everything that’s felt, since I no longer take pleasure in it, will become cool right here.’ ",
  "sn36.7:9.1": "Suppose an oil lamp depended on oil and a wick to burn. ",
  "sn36.7:9.2": "As the oil and the wick are used up, it would be extinguished due to not being fed. ",
  "sn36.7:9.3": "In the same way, feeling the end of the body draw close, a mendicant understands: ‘I feel the end of the body draw close.’ Feeling the end of life draw close, a mendicant understands: ‘I feel the end of life draw close.’ ",
  "sn36.7:9.4": "They understand: ‘When my body breaks up and my life is over, everything that’s felt, since I no longer take pleasure in it, will become cool right here.’” ",
  "sn36.8:0.1": "Linked Discourses 36.8 ",
  "sn36.8:0.2": "1. With Verses ",
  "sn36.8:0.3": "The Infirmary (2nd) ",
  "sn36.8:1.1": "At one time the Buddha was staying near Vesālī, at the Great Wood, in the hall with the peaked roof. ",
  "sn36.8:1.2": "Then in the late afternoon, the Buddha came out of retreat and went to the infirmary, where he sat down on the seat spread out, ",
  "sn36.8:1.3": "and addressed the mendicants: ",
  "sn36.8:2.1": "“Mendicants, a mendicant should await their time mindful and aware. ",
  "sn36.8:2.2": "This is my instruction to you. ",
  "sn36.8:3.1": "And how is a mendicant mindful? ",
  "sn36.8:3.2": "It’s when a mendicant meditates by observing an aspect of the bodykeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn36.8:3.3": "They meditate observing an aspect of feelings … ",
  "sn36.8:3.4": "They meditate observing an aspect of the mind … ",
  "sn36.8:3.5": "They meditate observing an aspect of principleskeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn36.8:3.6": "That’s how a mendicant is mindful. ",
  "sn36.8:4.1": "And how is a mendicant aware? ",
  "sn36.8:4.2": "It’s when a mendicant acts with situational awareness when going out and coming back; when looking ahead and aside; when bending and extending the limbs; when bearing the outer robe, bowl and robes; when eating, drinking, chewing, and tasting; when urinating and defecating; when walking, standing, sitting, sleeping, waking, speaking, and keeping silent. ",
  "sn36.8:4.3": "That’s how a mendicant is aware. ",
  "sn36.8:4.4": "A mendicant should await their time mindful and aware. ",
  "sn36.8:4.5": "This is my instruction to you. ",
  "sn36.8:5.1": "While a mendicant is meditating like thismindful, aware, diligent, keen, and resoluteif pleasant feelings arise, they understand: ",
  "sn36.8:5.2": "",
  "sn36.8:5.3": "‘A pleasant feeling has arisen in me. ",
  "sn36.8:5.4": "That’s dependent, not independent. ",
  "sn36.8:5.5": "Dependent on what? ",
  "sn36.8:5.6": "Dependent on this very contact. ",
  "sn36.8:5.7": "But this contact is impermanent, conditioned, dependently originated. ",
  "sn36.8:5.8": "So how could a pleasant feeling be permanent, since it has arisen dependent on contact that is impermanent, conditioned, and dependently originated?’ ",
  "sn36.8:5.9": "They meditate observing impermanence, vanishing, dispassion, cessation, and letting go in contact and pleasant feeling. ",
  "sn36.8:5.10": "As they do so, they give up the underlying tendency for greed for contact and pleasant feeling. ",
  "sn36.8:6.1": "While a mendicant is meditating like thismindful, aware, diligent, keen, and resoluteif painful feelings arise … ",
  "sn36.8:6.2": "",
  "sn36.8:6.3": "if neutral feelings arise, they understand: ",
  "sn36.8:6.4": "",
  "sn36.8:6.5": "‘A neutral feeling has arisen in me. ",
  "sn36.8:6.6": "That’s dependent, not independent. ",
  "sn36.8:6.7": "Dependent on what? ",
  "sn36.8:6.8": "Dependent on this very contact. ",
  "sn36.8:6.9": "(Tell in full as in the previous discourse.) ",
  "sn36.8:6.10": "They understand: ‘When my body breaks up and my life is over, everything that’s felt, since I no longer take pleasure in it, will become cool right here.’ ",
  "sn36.8:7.1": "Suppose an oil lamp depended on oil and a wick to burn. ",
  "sn36.8:7.2": "As the oil and the wick are used up, it would be extinguished due to not being fed. ",
  "sn36.8:7.3": "In the same way, feeling the end of the body draw close, a mendicant understands: ‘I feel the end of the body draw close.’ Feeling the end of life draw close, they understand: ‘I feel the end of life draw close.’ ",
  "sn36.8:7.4": "They understand: ‘When my body breaks up and my life is over, everything that’s felt, since I no longer take pleasure in it, will become cool right here.’” ",
  "sn36.9:0.1": "Linked Discourses 36.9 ",
  "sn36.9:0.2": "1. With Verses ",
  "sn36.9:0.3": "Impermanent ",
  "sn36.9:1.1": "“Mendicants, these three feelings are impermanent, conditioned, dependently originated, liable to end, vanish, fade away, and cease. ",
  "sn36.9:1.2": "What three? ",
  "sn36.9:1.3": "Pleasant, painful, and neutral feeling. ",
  "sn36.9:1.4": "These are the three feelings that are impermanent, conditioned, dependently originated, liable to end, vanish, fade away, and cease.” ",
  "sn36.10:0.1": "Linked Discourses 36.10 ",
  "sn36.10:0.2": "1. With Verses ",
  "sn36.10:0.3": "Rooted in Contact ",
  "sn36.10:1.1": "“Mendicants, these three feelings are born, rooted, sourced, and dependent on contact. ",
  "sn36.10:1.2": "What three? ",
  "sn36.10:1.3": "Pleasant, painful, and neutral feeling. ",
  "sn36.10:1.4": "Pleasant feeling arises dependent on a contact to be experienced as pleasant. ",
  "sn36.10:1.5": "With the cessation of that contact to be experienced as pleasant, the corresponding pleasant feeling ceases and stops. ",
  "sn36.10:1.6": "Painful feeling arises dependent on a contact to be experienced as painful. ",
  "sn36.10:1.7": "With the cessation of that contact to be experienced as painful, the corresponding painful feeling ceases and stops. ",
  "sn36.10:1.8": "Neutral feeling arises dependent on a contact to be experienced as neutral. ",
  "sn36.10:1.9": "With the cessation of that contact to be experienced as neutral, the corresponding neutral feeling ceases and stops. ",
  "sn36.10:1.10": "When you rub two sticks together, heat is generated and fire is produced. But when you part the sticks and lay them aside, any corresponding heat ceases and stops. ",
  "sn36.10:1.11": "In the same way, these three feelings are born, rooted, sourced, and dependent on contact. ",
  "sn36.10:1.12": "The appropriate feeling arises dependent on the corresponding contact. ",
  "sn36.10:1.13": "When the corresponding contact ceases, the appropriate feeling ceases.” ",
  "sn36.10:1.14": "",
  "sn36.10:1.15": "",
  "sn36.10:2.1": "",
  "sn36.10:2.2": "",
  "sn36.10:2.3": "",
  "sn36.11:0.1": "Linked Discourses 36.11 ",
  "sn36.11:0.2": "2. In Private ",
  "sn36.11:0.3": "In Private ",
  "sn36.11:1.1": "Then a mendicant went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn36.11:1.2": "“Just now, sir, as I was in private retreat this thought came to mind. ",
  "sn36.11:1.3": "The Buddha has spoken of three feelings. ",
  "sn36.11:1.4": "Pleasant, painful, and neutral feeling. ",
  "sn36.11:1.5": "These are the three feelings the Buddha has spoken of. ",
  "sn36.11:1.6": "But the Buddha has also said: ",
  "sn36.11:1.7": "‘Suffering includes whatever is felt.’ ",
  "sn36.11:1.8": "What was the Buddha referring to when he said this?” ",
  "sn36.11:1.9": "",
  "sn36.11:2.1": "“Good, good, mendicant! ",
  "sn36.11:2.2": "I have spoken of these three feelings. ",
  "sn36.11:2.3": "Pleasant, painful, and neutral feeling. ",
  "sn36.11:2.4": "These are the three feelings I have spoken of. ",
  "sn36.11:2.5": "But I have also said: ",
  "sn36.11:2.6": "‘Suffering includes whatever is felt.’ ",
  "sn36.11:2.7": "When I said this I was referring to the impermanence of conditions, to the fact that conditions are ",
  "sn36.11:2.8": "",
  "sn36.11:2.9": "liable to end, ",
  "sn36.11:2.10": "vanish, ",
  "sn36.11:2.11": "fade away, ",
  "sn36.11:2.12": "cease, ",
  "sn36.11:2.13": "and perish. ",
  "sn36.11:2.14": "",
  "sn36.11:2.15": "But I have also explained the progressive cessation of activities. ",
  "sn36.11:2.16": "For someone who has attained the first absorption, speech has ceased. ",
  "sn36.11:2.17": "For someone who has attained the second absorption, the placing of the mind and keeping it connected have ceased. ",
  "sn36.11:2.18": "For someone who has attained the third absorption, rapture has ceased. ",
  "sn36.11:2.19": "For someone who has attained the fourth absorption, breathing has ceased. ",
  "sn36.11:2.20": "For someone who has attained the dimension of infinite space, the perception of form has ceased. ",
  "sn36.11:2.21": "For someone who has attained the dimension of infinite consciousness, the perception of the dimension of infinite space has ceased. ",
  "sn36.11:2.22": "For someone who has attained the dimension of nothingness, the perception of the dimension of infinite consciousness has ceased. ",
  "sn36.11:2.23": "For someone who has attained the dimension of neither perception nor non-perception, the perception of the dimension of nothingness has ceased. ",
  "sn36.11:2.24": "For someone who has attained the cessation of perception and feeling, perception and feeling have ceased. ",
  "sn36.11:2.25": "For a mendicant who has ended the defilements, greed, hate, and delusion have ceased. ",
  "sn36.11:2.26": "And I have also explained the progressive settling of activities. ",
  "sn36.11:2.27": "For someone who has attained the first absorption, speech has stilled. ",
  "sn36.11:2.28": "For someone who has attained the second absorption, the placing of the mind and keeping it connected have stilled. … ",
  "sn36.11:2.29": "For someone who has attained the cessation of perception and feeling, perception and feeling have stilled. ",
  "sn36.11:2.30": "For a mendicant who has ended the defilements, greed, hate, and delusion have stilled. ",
  "sn36.11:2.31": "There are these six levels of tranquility. ",
  "sn36.11:2.32": "For someone who has attained the first absorption, speech has been tranquilized. ",
  "sn36.11:2.33": "For someone who has attained the second absorption, the placing of the mind and keeping it connected have been tranquilized. ",
  "sn36.11:2.34": "For someone who has attained the third absorption, rapture has been tranquilized. ",
  "sn36.11:2.35": "For someone who has attained the fourth absorption, breathing has been tranquilized. ",
  "sn36.11:2.36": "For someone who has attained the cessation of perception and feeling, perception and feeling have been tranquilized. ",
  "sn36.11:2.37": "For a mendicant who has ended the defilements, greed, hate, and delusion have been tranquilized.” ",
  "sn36.12:0.1": "Linked Discourses 36.12 ",
  "sn36.12:0.2": "2. In Private ",
  "sn36.12:0.3": "In the Atmosphere (1st) ",
  "sn36.12:1.1": "“Mendicants, various winds blow in the atmosphere. ",
  "sn36.12:1.2": "Winds blow from the east, the west, the north, and the south. There are winds that are dusty and dustless, cool and warm, weak and strong. ",
  "sn36.12:1.3": "In the same way, various feelings arise in this body: pleasant, painful, and neutral feelings. ",
  "sn36.12:2.1": "There are many and various ",
  "sn36.12:2.2": "winds that blow in the atmosphere. ",
  "sn36.12:2.3": "From the east they come, also the west, ",
  "sn36.12:2.4": "the north, and then the south. ",
  "sn36.12:3.1": "They are dusty and dustless, ",
  "sn36.12:3.2": "cool and sometimes warm, ",
  "sn36.12:3.3": "strong and weak; ",
  "sn36.12:3.4": "these are the different gales that blow. ",
  "sn36.12:4.1": "So too, in this body ",
  "sn36.12:4.2": "feelings arise, ",
  "sn36.12:4.3": "pleasant and painful, ",
  "sn36.12:4.4": "and those that are neutral. ",
  "sn36.12:5.1": "But when a mendicant is keen, ",
  "sn36.12:5.2": "not neglecting situational awareness, ",
  "sn36.12:5.3": "that astute person ",
  "sn36.12:5.4": "understands all feelings. ",
  "sn36.12:6.1": "Completely understanding feelings, ",
  "sn36.12:6.2": "they’re without defilements in this very life. ",
  "sn36.12:6.3": "That knowledge master is firm in principle; ",
  "sn36.12:6.4": "when their body breaks up, they can’t be reckoned.” ",
  "sn36.13:0.1": "Linked Discourses 36.13 ",
  "sn36.13:0.2": "2. In Private ",
  "sn36.13:0.3": "In the Atmosphere (2nd) ",
  "sn36.13:1.1": "“Mendicants, various winds blow in the atmosphere. ",
  "sn36.13:1.2": "Winds blow from the east, the west, the north, and the south. There are winds that are dusty and dustless, cool and warm, weak and strong. ",
  "sn36.13:1.3": "In the same way, various feelings arise in this body: pleasant, painful, and neutral feelings.” ",
  "sn36.14:0.1": "Linked Discourses 36.14 ",
  "sn36.14:0.2": "2. In Private ",
  "sn36.14:0.3": "A Guest House ",
  "sn36.14:1.1": "“Mendicants, suppose there was a guest house. Lodgers come from the east, west, north, and south. Aristocrats, brahmins, peasants, and menials all stay there. ",
  "sn36.14:1.2": "In the same way, various feelings arise in this body: pleasant, painful, and neutral feelings. ",
  "sn36.14:1.3": "Also pleasant, painful, and neutral feelings of the flesh arise. ",
  "sn36.14:1.4": "Also pleasant, painful, and neutral feelings not of the flesh arise.” ",
  "sn36.15:0.1": "Linked Discourses 36.15 ",
  "sn36.15:0.2": "2. In Private ",
  "sn36.15:0.3": "With Ānanda (1st) ",
  "sn36.15:1.1": "Then Venerable Ānanda went up to the Buddha … sat down to one side, and said to him: ",
  "sn36.15:1.2": "“Sir, what is feeling? What’s the origin of feeling? What’s the cessation of feeling? What’s the practice that leads to the cessation of feeling? ",
  "sn36.15:1.3": "And what is feeling’s gratification, drawback, and escape?” ",
  "sn36.15:1.4": "“Ānanda, there are these three feelings: ",
  "sn36.15:1.5": "pleasant, painful, and neutral. ",
  "sn36.15:1.6": "These are called feelings. ",
  "sn36.15:1.7": "Feeling originates from contact. ",
  "sn36.15:1.8": "When contact ceases, feeling ceases. ",
  "sn36.15:1.9": "The practice that leads to the cessation of feelings is simply this noble eightfold path, that is: ",
  "sn36.15:1.10": "right view, right purpose, right speech, right action, right livelihood, right effort, right mindfulness, and right immersion. ",
  "sn36.15:1.11": "The pleasure and happiness that arise from feeling: this is its gratification. ",
  "sn36.15:1.12": "That feeling is impermanent, suffering, and perishable: this is its drawback. ",
  "sn36.15:1.13": "Removing and giving up desire and greed for feeling: this is its escape. ",
  "sn36.15:1.14": "But I have also explained the progressive cessation of activities. ",
  "sn36.15:1.15": "For someone who has attained the first absorption, speech has ceased. … ",
  "sn36.15:1.16": "For someone who has attained the cessation of perception and feeling, perception and feeling have ceased. ",
  "sn36.15:1.17": "For a mendicant who has ended the defilements, greed, hate, and delusion have ceased. ",
  "sn36.15:1.18": "And I have also explained the progressive settling of activities. ",
  "sn36.15:1.19": "For someone who has attained the first absorption, speech has stilled. … ",
  "sn36.15:1.20": "For someone who has attained the cessation of perception and feeling, perception and feeling have stilled. ",
  "sn36.15:1.21": "For a mendicant who has ended the defilements, greed, hate, and delusion have stilled. ",
  "sn36.15:1.22": "And I have also explained the progressive tranquilizing of activities. ",
  "sn36.15:1.23": "For someone who has attained the first absorption, speech has been tranquilized. … ",
  "sn36.15:1.24": "For someone who has attained the dimension of infinite space, the perception of form has been tranquilized. ",
  "sn36.15:1.25": "For someone who has attained the dimension of infinite consciousness, the perception of the dimension of infinite space has been tranquilized. ",
  "sn36.15:1.26": "For someone who has attained the dimension of nothingness, the perception of the dimension of infinite consciousness has been tranquilized. ",
  "sn36.15:1.27": "For someone who has attained the dimension of neither perception nor non-perception, the perception of the dimension of nothingness has been tranquilized. ",
  "sn36.15:1.28": "For someone who has attained the cessation of perception and feeling, perception and feeling have been tranquilized. ",
  "sn36.15:1.29": "For a mendicant who has ended the defilements, greed, hate, and delusion have been tranquilized.” ",
  "sn36.16:0.1": "Linked Discourses 36.16 ",
  "sn36.16:0.2": "2. In Private ",
  "sn36.16:0.3": "With Ānanda (2nd) ",
  "sn36.16:1.1": "Then Venerable Ānanda went up to the Buddha, bowed, and sat down to one side. The Buddha said to him, ",
  "sn36.16:1.2": "“Ānanda, what is feeling? What’s the origin of feeling? What’s the cessation of feeling? What’s the practice that leads to the cessation of feeling? ",
  "sn36.16:1.3": "And what is feeling’s gratification, drawback, and escape?” ",
  "sn36.16:1.4": "“Our teachings are rooted in the Buddha. He is our guide and our refuge. Sir, may the Buddha himself please clarify the meaning of this. The mendicants will listen and remember it.” ",
  "sn36.16:1.5": "“Well then, Ānanda, listen and apply your mind well, I will speak.” ",
  "sn36.16:1.6": "“Yes, sir,” Ānanda replied. ",
  "sn36.16:1.7": "The Buddha said this: ",
  "sn36.16:1.8": "“Ānanda, there are these three feelings: ",
  "sn36.16:1.9": "pleasant, painful, and neutral. ",
  "sn36.16:1.10": "These are called feelings. … ",
  "sn36.16:1.11": "",
  "sn36.16:1.12": "For a mendicant who has ended the defilements, greed, hate, and delusion have been tranquilized.” ",
  "sn36.17:0.1": "Linked Discourses 36.17 ",
  "sn36.17:0.2": "2. In Private ",
  "sn36.17:0.3": "With Several Mendicants (1st) ",
  "sn36.17:1.1": "Then several mendicants went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn36.17:1.2": "“Sir, what is feeling? What’s the origin of feeling? What’s the cessation of feeling? What’s the practice that leads to the cessation of feeling? ",
  "sn36.17:1.3": "And what is feeling’s gratification, drawback, and escape?” ",
  "sn36.17:1.4": "“Mendicants, there are these three feelings: ",
  "sn36.17:1.5": "pleasant, painful, and neutral. ",
  "sn36.17:1.6": "These are called feelings. ",
  "sn36.17:1.7": "Feeling originates from contact. ",
  "sn36.17:1.8": "When contact ceases, feeling ceases. ",
  "sn36.17:1.9": "The practice that leads to the cessation of feelings is simply this noble eightfold path, that is: ",
  "sn36.17:1.10": "right view, right purpose, right speech, right action, right livelihood, right effort, right mindfulness, and right immersion. ",
  "sn36.17:1.11": "The pleasure and happiness that arise from feeling: this is its gratification. ",
  "sn36.17:1.12": "That feeling is impermanent, suffering, and perishable: this is its drawback. ",
  "sn36.17:1.13": "Removing and giving up desire and greed for feeling: this is its escape. ",
  "sn36.17:2.1": "But I have also explained the progressive cessation of activities. … ",
  "sn36.17:2.2": "For someone who has attained the first absorption, speech has ceased. … ",
  "sn36.17:2.3": "For a mendicant who has ended the defilements, greed, hate, and delusion have ceased. ",
  "sn36.17:2.4": "And I have also explained the progressive settling of activities. ",
  "sn36.17:2.5": "For someone who has attained the first absorption, speech has stilled. … ",
  "sn36.17:2.6": "For a mendicant who has ended the defilements, greed, hate, and delusion have stilled. ",
  "sn36.17:2.7": "There are these six levels of tranquility. ",
  "sn36.17:2.8": "For someone who has attained the first absorption, speech has been tranquilized. ",
  "sn36.17:2.9": "For someone who has attained the second absorption, the placing of the mind and keeping it connected have been tranquilized. ",
  "sn36.17:2.10": "For someone who has attained the third absorption, rapture has been tranquilized. ",
  "sn36.17:2.11": "For someone who has attained the fourth absorption, breathing has been tranquilized. ",
  "sn36.17:2.12": "For someone who has attained the cessation of perception and feeling, perception and feeling have been tranquilized. ",
  "sn36.17:2.13": "For a mendicant who has ended the defilements, greed, hate, and delusion have been tranquilized.” ",
  "sn36.18:0.1": "Linked Discourses 36.18 ",
  "sn36.18:0.2": "2. In Private ",
  "sn36.18:0.3": "With Several Mendicants (2nd) ",
  "sn36.18:1.1": "Then several mendicants went up to the Buddha … ",
  "sn36.18:1.2": "The Buddha said to them: ",
  "sn36.18:1.3": "“Mendicants, what is feeling? What’s the origin of feeling? What’s the cessation of feeling? What’s the practice that leads to the cessation of feeling? ",
  "sn36.18:1.4": "And what is feeling’s gratification, drawback, and escape?” ",
  "sn36.18:1.5": "“Our teachings are rooted in the Buddha. …” ",
  "sn36.18:1.6": "“Mendicants, there are these three feelings: ",
  "sn36.18:1.7": "pleasant, painful, and neutral. ",
  "sn36.18:1.8": "These are called feelings. …” ",
  "sn36.18:1.9": "(Tell in full as in the previous discourse.) ",
  "sn36.19:0.1": "Linked Discourses 36.19 ",
  "sn36.19:0.2": "2. In Private ",
  "sn36.19:0.3": "With Pañcakaṅga ",
  "sn36.19:1.1": "Then the chamberlain Pañcakaṅga went up to Venerable Udāyī, bowed, sat down to one side, and asked him, ",
  "sn36.19:1.2": "“Sir, how many feelings has the Buddha spoken of?” ",
  "sn36.19:1.3": "“Chamberlain, the Buddha has spoken of three feelings: ",
  "sn36.19:1.4": "pleasant, painful, and neutral. ",
  "sn36.19:1.5": "The Buddha has spoken of these three feelings.” ",
  "sn36.19:1.6": "When he said this, Pañcakaṅga said to Udāyī, ",
  "sn36.19:1.7": "“Sir, Udāyī, the Buddha hasn’t spoken of three feelings. ",
  "sn36.19:1.8": "He’s spoken of two feelings: ",
  "sn36.19:1.9": "pleasant and painful. ",
  "sn36.19:1.10": "The Buddha said that neutral feeling is included as a peaceful and subtle kind of pleasure.” ",
  "sn36.19:2.1": "For a second time, Udāyī said to him, ",
  "sn36.19:2.2": "“The Buddha hasn’t spoken of two feelings, ",
  "sn36.19:2.3": "he’s spoken of three.” ",
  "sn36.19:2.4": "",
  "sn36.19:2.5": "",
  "sn36.19:2.6": "For a second time, Pañcakaṅga said to Udāyī, ",
  "sn36.19:2.7": "“The Buddha hasn’t spoken of three feelings, ",
  "sn36.19:2.8": "he’s spoken of two.” ",
  "sn36.19:2.9": "",
  "sn36.19:2.10": "",
  "sn36.19:3.1": "And for a third time, Udāyī said to him, ",
  "sn36.19:3.2": "“The Buddha hasn’t spoken of two feelings, ",
  "sn36.19:3.3": "he’s spoken of three.” ",
  "sn36.19:3.4": "",
  "sn36.19:3.5": "",
  "sn36.19:3.6": "And for a third time, Pañcakaṅga said to Udāyī, ",
  "sn36.19:3.7": "“The Buddha hasn’t spoken of three feelings, ",
  "sn36.19:3.8": "he’s spoken of two.” ",
  "sn36.19:3.9": "",
  "sn36.19:3.10": "",
  "sn36.19:3.11": "But neither was able to persuade the other. ",
  "sn36.19:3.12": "Venerable Ānanda heard this discussion between Udāyī and Pañcakaṅga. ",
  "sn36.19:4.1": "He went to the Buddha, bowed, sat down to one side, ",
  "sn36.19:4.2": "and informed the Buddha of all they had discussed. ",
  "sn36.19:5.1": "“Ānanda, the explanation by the mendicant Udāyī, which the chamberlain Pañcakaṅga didn’t agree with, was quite correct. ",
  "sn36.19:5.2": "But the explanation by Pañcakaṅga, which Udāyī didn’t agree with, was also quite correct. ",
  "sn36.19:5.3": "In one explanation I’ve spoken of two feelings. In another explanation I’ve spoken of three feelings, or five, six, eighteen, thirty-six, or a hundred and eight feelings. ",
  "sn36.19:5.4": "",
  "sn36.19:5.5": "",
  "sn36.19:5.6": "",
  "sn36.19:5.7": "",
  "sn36.19:5.8": "",
  "sn36.19:5.9": "",
  "sn36.19:5.10": "I’ve explained the teaching in all these different ways. ",
  "sn36.19:5.11": "This being so, you can expect that those who don’t concede, approve, or agree with what has been well spoken will fight, quarrel, and dispute, continually wounding each other with barbed words. ",
  "sn36.19:5.12": "I’ve explained the teaching in all these different ways. ",
  "sn36.19:5.13": "This being so, you can expect that those who do concede, approve, or agree with what has been well spoken will live in harmony, appreciating each other, without dispute, blending like milk and water, and regarding each other with kindly eyes. ",
  "sn36.19:6.1": "There are these five kinds of sensual stimulation. ",
  "sn36.19:6.2": "What five? ",
  "sn36.19:6.3": "Sights known by the eye, which are likable, desirable, agreeable, pleasant, sensual, and arousing. … ",
  "sn36.19:6.4": "Touches known by the body, which are likable, desirable, agreeable, pleasant, sensual, and arousing. ",
  "sn36.19:6.5": "These are the five kinds of sensual stimulation. ",
  "sn36.19:6.6": "The pleasure and happiness that arise from these five kinds of sensual stimulation is called sensual pleasure. ",
  "sn36.19:6.7": "",
  "sn36.19:6.8": "There are those who might say ",
  "sn36.19:6.9": "that this is the highest pleasure and happiness that sentient beings experience. ",
  "sn36.19:6.10": "But I don’t grant them that. ",
  "sn36.19:6.11": "Why is that? ",
  "sn36.19:6.12": "Because there is another pleasure that is finer than that. ",
  "sn36.19:7.1": "And what is that pleasure? ",
  "sn36.19:7.2": "It’s when a mendicant, quite secluded from sensual pleasures, secluded from unskillful qualities, enters and remains in the first absorption, which has the rapture and bliss born of seclusion, while placing the mind and keeping it connected. ",
  "sn36.19:7.3": "This is a pleasure that is finer than that. ",
  "sn36.19:7.4": "There are those who might say ",
  "sn36.19:7.5": "that this is the highest pleasure and happiness that sentient beings experience. ",
  "sn36.19:7.6": "But I don’t grant them that. ",
  "sn36.19:7.7": "Why is that? ",
  "sn36.19:7.8": "Because there is another pleasure that is finer than that. ",
  "sn36.19:8.1": "And what is that pleasure? ",
  "sn36.19:8.2": "It’s when, as the placing of the mind and keeping it connected are stilled, a mendicant enters and remains in the second absorption, which has the rapture and bliss born of immersion, with internal clarity and mind at one, without placing the mind and keeping it connected. ",
  "sn36.19:8.3": "This is a pleasure that is finer than that. ",
  "sn36.19:8.4": "There are those who might say ",
  "sn36.19:8.5": "that this is the highest pleasure and happiness that sentient beings experience. ",
  "sn36.19:8.6": "But I don’t grant them that. ",
  "sn36.19:8.7": "Why is that? ",
  "sn36.19:8.8": "Because there is another pleasure that is finer than that. ",
  "sn36.19:9.1": "And what is that pleasure? ",
  "sn36.19:9.2": "It’s when, with the fading away of rapture, a mendicant enters and remains in the third absorption, where they meditate with equanimity, mindful and aware, personally experiencing the bliss of which the noble ones declare, ‘Equanimous and mindful, one meditates in bliss.’ ",
  "sn36.19:9.3": "This is a pleasure that is finer than that. ",
  "sn36.19:9.4": "There are those who might say ",
  "sn36.19:9.5": "that this is the highest pleasure and happiness that sentient beings experience. ",
  "sn36.19:9.6": "But I don’t grant them that. ",
  "sn36.19:9.7": "Why is that? ",
  "sn36.19:9.8": "Because there is another pleasure that is finer than that. ",
  "sn36.19:10.1": "And what is that pleasure? ",
  "sn36.19:10.2": "It’s when, with the giving up of pleasure and pain and the disappearance of former happiness and sadness, a mendicant enters and remains in the fourth absorption, without pleasure or pain, with pure equanimity and mindfulness. ",
  "sn36.19:10.3": "This is a pleasure that is finer than that. ",
  "sn36.19:10.4": "There are those who might say ",
  "sn36.19:10.5": "that this is the highest pleasure and happiness that sentient beings experience. ",
  "sn36.19:10.6": "But I don’t grant them that. ",
  "sn36.19:10.7": "Why is that? ",
  "sn36.19:10.8": "Because there is another pleasure that is finer than that. ",
  "sn36.19:11.1": "And what is that pleasure? ",
  "sn36.19:11.2": "It’s when a mendicantgoing totally beyond perceptions of form, with the disappearance of perceptions of impingement, not focusing on perceptions of diversityaware that ‘space is infinite’, enters and remains in the dimension of infinite space. ",
  "sn36.19:11.3": "This is a pleasure that is finer than that. ",
  "sn36.19:11.4": "There are those who might say ",
  "sn36.19:11.5": "that this is the highest pleasure and happiness that sentient beings experience. ",
  "sn36.19:11.6": "But I don’t grant them that. ",
  "sn36.19:11.7": "Why is that? ",
  "sn36.19:11.8": "Because there is another pleasure that is finer than that. ",
  "sn36.19:12.1": "And what is that pleasure? ",
  "sn36.19:12.2": "It’s when a mendicant, going totally beyond the dimension of infinite space, aware that ‘consciousness is infinite’, enters and remains in the dimension of infinite consciousness. ",
  "sn36.19:12.3": "This is a pleasure that is finer than that. ",
  "sn36.19:12.4": "There are those who might say ",
  "sn36.19:12.5": "that this is the highest pleasure and happiness that sentient beings experience. ",
  "sn36.19:12.6": "But I don’t grant them that. ",
  "sn36.19:12.7": "Why is that? ",
  "sn36.19:12.8": "Because there is another pleasure that is finer than that. ",
  "sn36.19:13.1": "And what is that pleasure? ",
  "sn36.19:13.2": "It’s when a mendicant, going totally beyond the dimension of infinite consciousness, aware that ‘there is nothing at all’, enters and remains in the dimension of nothingness. ",
  "sn36.19:13.3": "This is a pleasure that is finer than that. ",
  "sn36.19:13.4": "There are those who might say ",
  "sn36.19:13.5": "that this is the highest pleasure and happiness that sentient beings experience. ",
  "sn36.19:13.6": "But I don’t grant them that. ",
  "sn36.19:13.7": "Why is that? ",
  "sn36.19:13.8": "Because there is another pleasure that is finer than that. ",
  "sn36.19:14.1": "And what is that pleasure? ",
  "sn36.19:14.2": "It’s when a mendicant, going totally beyond the dimension of nothingness, enters and remains in the dimension of neither perception nor non-perception. ",
  "sn36.19:14.3": "This is a pleasure that is finer than that. ",
  "sn36.19:14.4": "There are those who might say ",
  "sn36.19:14.5": "that this is the highest pleasure and happiness that sentient beings experience. ",
  "sn36.19:14.6": "But I don’t grant them that. ",
  "sn36.19:14.7": "Why is that? ",
  "sn36.19:14.8": "Because there is another pleasure that is finer than that. ",
  "sn36.19:15.1": "And what is that pleasure? ",
  "sn36.19:15.2": "It’s when a mendicant, going totally beyond the dimension of neither perception nor non-perception, enters and remains in the cessation of perception and feeling. ",
  "sn36.19:15.3": "This is a pleasure that is finer than that. ",
  "sn36.19:16.1": "It’s possible that wanderers of other religions might say: ",
  "sn36.19:16.2": "‘The ascetic Gotama spoke of the cessation of perception and feeling, and he includes it in happiness. ",
  "sn36.19:16.3": "What’s up with that?’ ",
  "sn36.19:16.4": "When wanderers of other religions say this, you should say to them: ",
  "sn36.19:16.5": "‘Reverends, when the Buddha describes what’s included in happiness, he’s not just referring to pleasant feeling. ",
  "sn36.19:16.6": "The Realized One describes pleasure as included in happiness wherever it is found, and in whatever context.’” ",
  "sn36.20:0.1": "Linked Discourses 36.20 ",
  "sn36.20:0.2": "2. In Private ",
  "sn36.20:0.3": "A Mendicant ",
  "sn36.20:1.1": "“Mendicants, in one explanation I’ve spoken of two feelings. In another explanation I’ve spoken of three feelings, or five, six, eighteen, thirty-six, or a hundred and eight feelings. ",
  "sn36.20:1.2": "I’ve taught the Dhamma with all these explanations. ",
  "sn36.20:1.3": "This being so, you can expect that those who don’t concede, approve, or agree with what has been well spoken will fight, quarrel, and dispute, continually wounding each other with barbed words. ",
  "sn36.20:1.4": "I’ve taught the Dhamma with all these explanations. ",
  "sn36.20:1.5": "This being so, you can expect that those who do concede, approve, or agree with what has been well spoken will live in harmony, appreciating each other, without dispute, blending like milk and water, and regarding each other with kindly eyes. ",
  "sn36.20:2.1": "There are these five kinds of sensual stimulation. … ",
  "sn36.20:2.2": "It’s possible that wanderers of other religions might say: ",
  "sn36.20:2.3": "‘The ascetic Gotama spoke of the cessation of perception and feeling, and he includes it in happiness. ",
  "sn36.20:2.4": "What’s up with that?’ ",
  "sn36.20:2.5": "Mendicants, when wanderers of other religions say this, you should say to them: ",
  "sn36.20:2.6": "‘Reverends, when the Buddha describes what’s included in happiness, he’s not just referring to pleasant feeling. ",
  "sn36.20:2.7": "The Realized One describes pleasure as included in happiness wherever it is found, and in whatever context.’” ",
  "sn36.20:2.8": "",
  "sn36.20:2.9": "",
  "sn36.20:3.1": "",
  "sn36.20:3.2": "",
  "sn36.20:3.3": "",
  "sn36.21:0.1": "Linked Discourses 36.21 ",
  "sn36.21:0.2": "3. The Explanation of the Hundred and Eight ",
  "sn36.21:0.3": "With Sīvaka ",
  "sn36.21:1.1": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn36.21:1.2": "Then the wanderer Moḷiyasīvaka went up to the Buddha and exchanged greetings with him. ",
  "sn36.21:1.3": "When the greetings and polite conversation were over, he sat down to one side and said to the Buddha: ",
  "sn36.21:1.4": "“Worthy Gotama, there are some ascetics and brahmins who have this doctrine and view: ",
  "sn36.21:1.5": "‘Everything this individual person experiencespleasurable, painful, or neutralis because of past deeds.’ ",
  "sn36.21:1.6": "What does the worthy Gotama say about this?” ",
  "sn36.21:2.1": "“Sīvaka, some feelings stem from bile disorders. ",
  "sn36.21:2.2": "You can know this from your own personal experience, ",
  "sn36.21:2.3": "and it is generally deemed to be true. ",
  "sn36.21:2.4": "Since this is so, the ascetics and brahmins whose view is that ",
  "sn36.21:2.5": "everything an individual person experiences is because of past deeds ",
  "sn36.21:2.6": "go beyond personal experience and beyond what is generally deemed to be true. ",
  "sn36.21:2.7": "So those ascetics and brahmins are wrong, I say. ",
  "sn36.21:3.1": "Some feelings stem from phlegm disorders … ",
  "sn36.21:3.2": "wind disorders … ",
  "sn36.21:3.3": "their conjunction … ",
  "sn36.21:3.4": "change in weather … ",
  "sn36.21:3.5": "not taking care of yourself … ",
  "sn36.21:3.6": "overexertion … ",
  "sn36.21:3.7": "Some feelings are the result of past deeds. ",
  "sn36.21:3.8": "You can know this from your own personal experience, ",
  "sn36.21:3.9": "",
  "sn36.21:3.10": "and it is generally deemed to be true. ",
  "sn36.21:3.11": "",
  "sn36.21:3.12": "Since this is so, the ascetics and brahmins whose view is that ",
  "sn36.21:3.13": "everything an individual person experiences is because of past deeds ",
  "sn36.21:3.14": "go beyond personal experience and beyond what is generally deemed to be true. ",
  "sn36.21:3.15": "So those ascetics and brahmins are wrong, I say.” ",
  "sn36.21:4.1": "When he said this, the wanderer Moḷiyasīvaka said to the Buddha, ",
  "sn36.21:4.2": "“Excellent, worthy Gotama! Excellent! … ",
  "sn36.21:4.3": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn36.21:5.1": "“Bile, phlegm, and wind, ",
  "sn36.21:5.2": "their conjunction, and the weather, ",
  "sn36.21:5.3": "not taking care of yourself, overexertion, ",
  "sn36.21:5.4": "and the result of deeds is the eighth.” ",
  "sn36.22:0.1": "Linked Discourses 36.22 ",
  "sn36.22:0.2": "3. The Explanation of the Hundred and Eight ",
  "sn36.22:0.3": "The Explanation of the Hundred and Eight ",
  "sn36.22:1.1": "“Mendicants, I will teach you an exposition of the teaching on the hundred and eight. ",
  "sn36.22:1.2": "Listen … ",
  "sn36.22:1.3": "And what is the exposition of the teaching on the hundred and eight? ",
  "sn36.22:1.4": "Mendicants, in one explanation I’ve spoken of two feelings. In another explanation I’ve spoken of three feelings, or five, six, eighteen, thirty-six, or a hundred and eight feelings. ",
  "sn36.22:1.5": "",
  "sn36.22:1.6": "",
  "sn36.22:1.7": "",
  "sn36.22:1.8": "",
  "sn36.22:1.9": "",
  "sn36.22:1.10": "",
  "sn36.22:2.1": "And what are the two feelings? ",
  "sn36.22:2.2": "Physical and mental. ",
  "sn36.22:2.3": "These are called the two feelings. ",
  "sn36.22:2.4": "And what are the three feelings? ",
  "sn36.22:2.5": "Pleasant, painful, and neutral feelings. … ",
  "sn36.22:2.6": "",
  "sn36.22:2.7": "And what are the five feelings? ",
  "sn36.22:2.8": "The faculties of pleasure, pain, happiness, sadness, and equanimity. … ",
  "sn36.22:2.9": "",
  "sn36.22:2.10": "And what are the six feelings? ",
  "sn36.22:2.11": "Feeling born of eye contact … ear contact … nose contact … tongue contact … body contact … ",
  "sn36.22:2.12": "mind contact. … ",
  "sn36.22:2.13": "",
  "sn36.22:2.14": "And what are the eighteen feelings? ",
  "sn36.22:2.15": "There are six preoccupations with happiness, six preoccupations with sadness, and six preoccupations with equanimity. … ",
  "sn36.22:2.16": "",
  "sn36.22:2.17": "And what are the thirty-six feelings? ",
  "sn36.22:2.18": "Six kinds of domestic happiness and six kinds of renunciate happiness. Six kinds of domestic sadness and six kinds of renunciate sadness. Six kinds of domestic equanimity and six kinds of renunciate equanimity. … ",
  "sn36.22:2.19": "",
  "sn36.22:2.20": "And what are the hundred and eight feelings? ",
  "sn36.22:2.21": "Thirty six feelings in the past, future, and present. ",
  "sn36.22:2.22": "These are called the hundred and eight feelings. ",
  "sn36.22:2.23": "This is the exposition of the teaching on the hundred and eight.” ",
  "sn36.23:0.1": "Linked Discourses 36.23 ",
  "sn36.23:0.2": "3. The Explanation of the Hundred and Eight ",
  "sn36.23:0.3": "With a Mendicant ",
  "sn36.23:1.1": "Then a mendicant went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn36.23:1.2": "“Sir, what is feeling? What’s the origin of feeling? What’s the practice that leads to the origin of feeling? ",
  "sn36.23:1.3": "What’s the cessation of feeling? What’s the practice that leads to the cessation of feeling? ",
  "sn36.23:1.4": "And what is feeling’s gratification, drawback, and escape?” ",
  "sn36.23:2.1": "“Mendicant, there are these three feelings: ",
  "sn36.23:2.2": "pleasant, painful, and neutral. ",
  "sn36.23:2.3": "These are called feelings. ",
  "sn36.23:2.4": "Feeling originates from contact. ",
  "sn36.23:2.5": "Craving is the practice that leads to the origin of feeling. ",
  "sn36.23:2.6": "When contact ceases, feeling ceases. ",
  "sn36.23:2.7": "The practice that leads to the cessation of feelings is simply this noble eightfold path, that is: ",
  "sn36.23:2.8": "right view, right purpose, right speech, right action, right livelihood, right effort, right mindfulness, and right immersion. ",
  "sn36.23:2.9": "The pleasure and happiness that arise from feeling: this is its gratification. ",
  "sn36.23:2.10": "That feeling is impermanent, suffering, and perishable: this is its drawback. ",
  "sn36.23:2.11": "Removing and giving up desire and greed for feeling: this is its escape.” ",
  "sn36.24:0.1": "Linked Discourses 36.24 ",
  "sn36.24:0.2": "3. The Explanation of the Hundred and Eight ",
  "sn36.24:0.3": "Before ",
  "sn36.24:1.1": "“Mendicants, before my awakeningwhen I was still unawakened but intent on awakeningI thought: ",
  "sn36.24:1.2": "‘What is feeling? What’s the origin of feeling? What’s the practice that leads to the origin of feeling? What’s the cessation of feeling? What’s the practice that leads to the cessation of feeling? ",
  "sn36.24:1.3": "And what is feeling’s gratification, drawback, and escape?’ ",
  "sn36.24:1.4": "Then it occurred to me: ",
  "sn36.24:1.5": "‘There are these three feelings: ",
  "sn36.24:1.6": "pleasant, painful, and neutral. ",
  "sn36.24:1.7": "These are called feelings. ",
  "sn36.24:1.8": "Feeling originates from contact. ",
  "sn36.24:1.9": "Craving is the practice that leads to the origin of feeling … ",
  "sn36.24:1.10": "Removing and giving up desire and greed for feeling: this is its escape.’” ",
  "sn36.25:0.1": "Linked Discourses 36.25 ",
  "sn36.25:0.2": "3. The Explanation of the Hundred and Eight ",
  "sn36.25:0.3": "Knowledge ",
  "sn36.25:1.1": "“‘These are the feelings.’ Such was the vision, knowledge, wisdom, realization, and light that arose in me regarding teachings not learned before from another. ",
  "sn36.25:1.2": "‘This is the origin of feeling.’ … ",
  "sn36.25:1.3": "‘This is the practice that leads to the origin of feeling.’ … ",
  "sn36.25:1.4": "‘This is the cessation of feeling.’ … ",
  "sn36.25:1.5": "‘This is the practice that leads to the cessation of feeling.’ … ",
  "sn36.25:1.6": "‘This is the gratification of feeling.’ … ",
  "sn36.25:1.7": "‘This is the drawback of feeling.’ … ",
  "sn36.25:1.8": "‘This is the escape from feeling.’ Such was the vision, knowledge, wisdom, realization, and light that arose in me regarding teachings not learned before from another.” ",
  "sn36.26:0.1": "Linked Discourses 36.26 ",
  "sn36.26:0.2": "3. The Explanation of the Hundred and Eight ",
  "sn36.26:0.3": "With Several Mendicants ",
  "sn36.26:1.1": "Then several mendicants went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn36.26:1.2": "“Sir, what is feeling? What’s the origin of feeling? What’s the practice that leads to the origin of feeling? ",
  "sn36.26:1.3": "What’s the cessation of feeling? What’s the practice that leads to the cessation of feeling? ",
  "sn36.26:1.4": "And what is feeling’s gratification, drawback, and escape?” ",
  "sn36.26:1.5": "“Mendicants, there are these three feelings. ",
  "sn36.26:1.6": "pleasant, painful, and neutral. ",
  "sn36.26:1.7": "These are called feelings. ",
  "sn36.26:1.8": "Feeling originates from contact. ",
  "sn36.26:1.9": "Craving is the practice that leads to the origin of feeling. ",
  "sn36.26:1.10": "When contact ceases, feeling ceases. … ",
  "sn36.26:1.11": "Removing and giving up desire and greed for feeling: this is its escape.” ",
  "sn36.27:0.1": "Linked Discourses 36.27 ",
  "sn36.27:0.2": "3. The Explanation of the Hundred and Eight ",
  "sn36.27:0.3": "Ascetics and Brahmins (1st) ",
  "sn36.27:1.1": "“Mendicants, there are these three feelings. ",
  "sn36.27:1.2": "What three? ",
  "sn36.27:1.3": "Pleasant, painful, and neutral feeling. ",
  "sn36.27:1.4": "There are ascetics and brahmins who don’t truly understand these three feelings’ gratification, drawback, and escape. ",
  "sn36.27:1.5": "I don’t deem them as true ascetics and brahmins. Those venerables don’t realize the goal of life as an ascetic or brahmin, and don’t live having realized it with their own insight. ",
  "sn36.27:1.6": "There are ascetics and brahmins who do truly understand these three feelings’ gratification, drawback, and escape. ",
  "sn36.27:1.7": "I deem them as true ascetics and brahmins. Those venerables realize the goal of life as an ascetic or brahmin, and live having realized it with their own insight.” ",
  "sn36.28:0.1": "Linked Discourses 36.28 ",
  "sn36.28:0.2": "3. The Explanation of the Hundred and Eight ",
  "sn36.28:0.3": "Ascetics and Brahmins (2nd) ",
  "sn36.28:1.1": "“Mendicants, there are these three feelings. ",
  "sn36.28:1.2": "What three? ",
  "sn36.28:1.3": "Pleasant, painful, and neutral feeling. ",
  "sn36.28:1.4": "There are ascetics and brahmins who don’t truly understand these three feelings’ origin, disappearance, gratification, drawback, and escape. … ",
  "sn36.28:1.5": "There are ascetics and brahmins who do truly understand …” ",
  "sn36.29:0.1": "Linked Discourses 36.29 ",
  "sn36.29:0.2": "3. The Explanation of the Hundred and Eight ",
  "sn36.29:0.3": "Ascetics and Brahmins (3rd) ",
  "sn36.29:1.1": "“Mendicants, there are ascetics and brahmins who don’t understand feeling, its origin, its cessation, and the practice that leads to its cessation. … ",
  "sn36.29:1.2": "There are ascetics and brahmins who do understand …” ",
  "sn36.30:0.1": "Linked Discourses 36.30 ",
  "sn36.30:0.2": "3. The Explanation of the Hundred and Eight ",
  "sn36.30:0.3": "Plain Version ",
  "sn36.30:1.1": "“Mendicants, there are these three feelings. ",
  "sn36.30:1.2": "What three? ",
  "sn36.30:1.3": "Pleasant, painful, and neutral feelings. ",
  "sn36.30:1.4": "These are the three feelings.” ",
  "sn36.31:0.1": "Linked Discourses 36.31 ",
  "sn36.31:0.2": "3. The Explanation of the Hundred and Eight ",
  "sn36.31:0.3": "Not of the Flesh ",
  "sn36.31:1.1": "“Mendicants, there is rapture of the flesh, rapture not  of the flesh, and rapture even more spiritual than that not of the flesh. ",
  "sn36.31:1.2": "There is pleasure of the flesh, pleasure not of the flesh, and pleasure even more spiritual than that not of the flesh. ",
  "sn36.31:1.3": "There is equanimity of the flesh, equanimity not of the flesh, and equanimity even more spiritual than that not of the flesh. ",
  "sn36.31:1.4": "There is liberation of the flesh, liberation not of the flesh, and liberation even more spiritual than that not of the flesh. ",
  "sn36.31:1.5": "And what is rapture of the flesh? ",
  "sn36.31:1.6": "There are these five kinds of sensual stimulation. ",
  "sn36.31:1.7": "What five? ",
  "sn36.31:1.8": "Sights known by the eye, which are likable, desirable, agreeable, pleasant, sensual, and arousing. Sounds … Smells … Tastes … ",
  "sn36.31:1.9": "Touches known by the body, which are likable, desirable, agreeable, pleasant, sensual, and arousing. ",
  "sn36.31:1.10": "These are the five kinds of sensual stimulation. ",
  "sn36.31:1.11": "The rapture that arises from these five kinds of sensual stimulation is called rapture of the flesh. ",
  "sn36.31:2.1": "And what is rapture not of the flesh? ",
  "sn36.31:2.2": "It’s when a mendicant, quite secluded from sensual pleasures, secluded from unskillful qualities, enters and remains in the first absorption, which has the rapture and bliss born of seclusion, while placing the mind and keeping it connected. ",
  "sn36.31:2.3": "As the placing of the mind and keeping it connected are stilled, they enter and remain in the second absorption, which has the rapture and bliss born of immersion, with internal clarity and mind at one, without placing the mind and keeping it connected. ",
  "sn36.31:2.4": "This is called rapture not of the flesh. ",
  "sn36.31:3.1": "And what is rapture even more spiritual than that not of the flesh? ",
  "sn36.31:3.2": "When a mendicant who has ended the defilements reviews their mind free from greed, hate, and delusion, rapture arises. This is called rapture even more spiritual than that not of the flesh. ",
  "sn36.31:4.1": "And what is pleasure of the flesh? ",
  "sn36.31:4.2": "Mendicants, there are these five kinds of sensual stimulation. ",
  "sn36.31:4.3": "What five? ",
  "sn36.31:4.4": "Sights known by the eye, which are likable, desirable, agreeable, pleasant, sensual, and arousing. Sounds … Smells … Tastes … ",
  "sn36.31:4.5": "Touches known by the body, which are likable, desirable, agreeable, pleasant, sensual, and arousing. ",
  "sn36.31:4.6": "These are the five kinds of sensual stimulation. ",
  "sn36.31:4.7": "The pleasure and happiness that arise from these five kinds of sensual stimulation is called pleasure of the flesh. ",
  "sn36.31:5.1": "And what is pleasure not of the flesh? ",
  "sn36.31:5.2": "It’s when a mendicant, quite secluded from sensual pleasures, secluded from unskillful qualities, enters and remains in the first absorption, which has the rapture and bliss born of seclusion, while placing the mind and keeping it connected. ",
  "sn36.31:5.3": "As the placing of the mind and keeping it connected are stilled, they enter and remain in the second absorption, which has the rapture and bliss born of immersion, with internal clarity and mind at one, without placing the mind and keeping it connected. ",
  "sn36.31:5.4": "And with the fading away of rapture, they enter and remain in the third absorption, where they meditate with equanimity, mindful and aware, personally experiencing the bliss of which the noble ones declare, ‘Equanimous and mindful, one meditates in bliss.’ ",
  "sn36.31:5.5": "This is called pleasure not of the flesh. ",
  "sn36.31:6.1": "And what is pleasure even more spiritual than that not of the flesh? ",
  "sn36.31:6.2": "When a mendicant who has ended the defilements reviews their mind free from greed, hate, and delusion, pleasure and happiness arises. This is called pleasure even more spiritual than that not of the flesh. ",
  "sn36.31:7.1": "And what is equanimity of the flesh? ",
  "sn36.31:7.2": "There are these five kinds of sensual stimulation. ",
  "sn36.31:7.3": "What five? ",
  "sn36.31:7.4": "Sights known by the eye, which are likable, desirable, agreeable, pleasant, sensual, and arousing. Sounds … Smells … Tastes … ",
  "sn36.31:7.5": "Touches known by the body, which are likable, desirable, agreeable, pleasant, sensual, and arousing. ",
  "sn36.31:7.6": "These are the five kinds of sensual stimulation. ",
  "sn36.31:7.7": "The equanimity that arises from these five kinds of sensual stimulation is called equanimity of the flesh. ",
  "sn36.31:8.1": "And what is equanimity not of the flesh? ",
  "sn36.31:8.2": "It’s when, with the giving up of pleasure and pain and the disappearance of former happiness and sadness, a mendicant enters and remains in the fourth absorption, without pleasure or pain, with pure equanimity and mindfulness. ",
  "sn36.31:8.3": "This is called equanimity not of the flesh. ",
  "sn36.31:9.1": "And what is equanimity even more spiritual than that not of the flesh? ",
  "sn36.31:9.2": "When a mendicant who has ended the defilements reviews their mind free from greed, hate, and delusion, equanimity arises. This is called equanimity even more spiritual than that not of the flesh. ",
  "sn36.31:10.1": "And what is liberation of the flesh? ",
  "sn36.31:10.2": "Liberation connected with form is liberation of the flesh. ",
  "sn36.31:11.1": "And what is liberation not of the flesh? ",
  "sn36.31:11.2": "Liberation connected with the formless is liberation not of the flesh. ",
  "sn36.31:12.1": "And what is liberation even more spiritual than that not of the flesh? ",
  "sn36.31:12.2": "When a mendicant who has ended the defilements reviews their mind free from greed, hate, and delusion, liberation arises. This is called liberation even more spiritual than that not of the flesh.” ",
  "sn36.31:12.3": "",
  "sn36.31:12.4": "",
  "sn36.31:13.1": "",
  "sn36.31:13.2": "",
  "sn36.31:13.3": "",
  "sn36.31:13.4": "",
  "sn36.31:13.5": "The Linked Discourses on feeling are complete. "
}
window.BILARA["sn36_v1"]["en"]["sn36_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
