window.BILARA = window.BILARA || {};
window.BILARA["sn37_v1"] = window.BILARA["sn37_v1"] || {};
window.BILARA["sn37_v1"]["en"] = {
  "sn37.1:0.1": "Linked Discourses 37.1 ",
  "sn37.1:0.2": "1. Abbreviated Texts ",
  "sn37.1:0.3": "A Female ",
  "sn37.1:1.1": "“Mendicants, when a lady has five factors she is extremely undesirable to a man. ",
  "sn37.1:1.2": "What five? ",
  "sn37.1:1.3": "She’s not attractive, wealthy, or ethical; she’s idle, and she doesn’t beget children. ",
  "sn37.1:1.4": "When a lady has these five factors she is extremely undesirable to a man. ",
  "sn37.1:1.5": "When a lady has five factors she is extremely desirable to a man. ",
  "sn37.1:1.6": "What five? ",
  "sn37.1:1.7": "She’s attractive, wealthy, and ethical; she’s deft and tireless, and she begets children. ",
  "sn37.1:1.8": "When a lady has these five factors she is extremely desirable to a man.” ",
  "sn37.2:0.1": "Linked Discourses 37.2 ",
  "sn37.2:0.2": "1. Abbreviated Texts ",
  "sn37.2:0.3": "A Man ",
  "sn37.2:1.1": "“Mendicants, when a man has five factors he is extremely undesirable to a lady. ",
  "sn37.2:1.2": "What five? ",
  "sn37.2:1.3": "He’s not attractive, wealthy, or ethical; he’s idle, and he doesn’t beget children. ",
  "sn37.2:1.4": "When a man has these five factors he is extremely undesirable to a lady. ",
  "sn37.2:1.5": "When a man has five factors he is extremely desirable to a lady. ",
  "sn37.2:1.6": "What five? ",
  "sn37.2:1.7": "He’s attractive, wealthy, and ethical; he’s deft and tireless, and he begets children. ",
  "sn37.2:1.8": "When a man has these five factors he is extremely desirable to a lady.” ",
  "sn37.3:0.1": "Linked Discourses 37.3 ",
  "sn37.3:0.2": "1. Abbreviated Texts ",
  "sn37.3:0.3": "Particular Suffering ",
  "sn37.3:1.1": "“Mendicants, there are these five kinds of suffering that particularly apply to ladies. They’re undergone by ladies and not by men. ",
  "sn37.3:1.2": "What five? ",
  "sn37.3:1.3": "Firstly, a lady, while still young, goes to live with her husband’s family and is separated from her relatives. ",
  "sn37.3:1.4": "This is the first kind of suffering that particularly applies to ladies. ",
  "sn37.3:1.5": "Furthermore, a lady undergoes the menstrual cycle. ",
  "sn37.3:1.6": "This is the second kind of suffering that particularly applies to ladies. ",
  "sn37.3:1.7": "Furthermore, a lady undergoes pregnancy. ",
  "sn37.3:1.8": "This is the third kind of suffering that particularly applies to ladies. ",
  "sn37.3:1.9": "Furthermore, a lady gives birth. ",
  "sn37.3:1.10": "This is the fourth kind of suffering that particularly applies to ladies. ",
  "sn37.3:1.11": "Furthermore, a lady provides services for a man. ",
  "sn37.3:1.12": "This is the fifth kind of suffering that particularly applies to ladies. ",
  "sn37.3:1.13": "These are the five kinds of suffering that particularly apply to ladies. They’re undergone by ladies and not by men.” ",
  "sn37.4:0.1": "Linked Discourses 37.4 ",
  "sn37.4:0.2": "1. Abbreviated Texts ",
  "sn37.4:0.3": "Three Qualities ",
  "sn37.4:1.1": "“Mendicants, when ladies have three qualities, when their body breaks up, after death, they are mostly reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn37.4:1.2": "What three? ",
  "sn37.4:1.3": "A female lives at home with a heart full of the stain of stinginess in the morning, jealousy in the afternoon, and sexual desire in the evening. ",
  "sn37.4:1.4": "",
  "sn37.4:1.5": "",
  "sn37.4:1.6": "When ladies possess these three qualities, when their body breaks up, after death, they are mostly reborn in a place of loss, a bad place, the underworld, hell.” ",
  "sn37.4:1.7": "",
  "sn37.5:0.1": "Linked Discourses 37.5 ",
  "sn37.5:0.2": "1. Abbreviated Texts ",
  "sn37.5:0.3": "Irritable ",
  "sn37.5:1.1": "Then Venerable Anuruddha went up to the Buddha, sat down to one side, and said to him: ",
  "sn37.5:1.2": "“Sometimes, sir, with my clairvoyance that’s purified and superhuman, I see that a ladywhen her body breaks up, after deathis reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn37.5:1.3": "How many qualities do ladies have so that they’re reborn in a place of loss, a bad place, the underworld, hell?” ",
  "sn37.5:2.1": "“Anuruddha, when ladies have five qualities, when their body breaks up, after death, they are reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn37.5:2.2": "What five? ",
  "sn37.5:2.3": "They’re faithless, shameless, imprudent, irritable, and witless. ",
  "sn37.5:2.4": "When ladies possess these five qualities, when their body breaks up, after death, they are reborn in a place of loss, a bad place, the underworld, hell.” ",
  "sn37.6:0.1": "Linked Discourses 37.6 ",
  "sn37.6:0.2": "1. Abbreviated Texts ",
  "sn37.6:0.3": "Acrimony ",
  "sn37.6:1.1": "",
  "sn37.6:1.2": "",
  "sn37.6:1.3": "“… They’re faithless, shameless, imprudent, acrimonious, and witless. …” ",
  "sn37.6:1.4": "",
  "sn37.7:0.1": "Linked Discourses 37.7 ",
  "sn37.7:0.2": "1. Abbreviated Texts ",
  "sn37.7:0.3": "Jealous ",
  "sn37.7:1.1": "",
  "sn37.7:1.2": "",
  "sn37.7:1.3": "“… They’re faithless, shameless, imprudent, jealous, and witless. …” ",
  "sn37.7:1.4": "",
  "sn37.8:0.1": "Linked Discourses 37.8 ",
  "sn37.8:0.2": "1. Abbreviated Texts ",
  "sn37.8:0.3": "Stingy ",
  "sn37.8:1.1": "",
  "sn37.8:1.2": "",
  "sn37.8:1.3": "“… They’re faithless, shameless, imprudent, stingy, and witless. …” ",
  "sn37.8:1.4": "",
  "sn37.8:1.5": "",
  "sn37.9:0.1": "Linked Discourses 37.9 ",
  "sn37.9:0.2": "1. Abbreviated Texts ",
  "sn37.9:0.3": "Adultery ",
  "sn37.9:1.1": "",
  "sn37.9:1.2": "",
  "sn37.9:1.3": "“… They’re faithless, shameless, imprudent, adulterous, and witless. …” ",
  "sn37.9:1.4": "",
  "sn37.10:0.1": "Linked Discourses 37.10 ",
  "sn37.10:0.2": "1. Abbreviated Texts ",
  "sn37.10:0.3": "Unethical ",
  "sn37.10:1.1": "",
  "sn37.10:1.2": "",
  "sn37.10:1.3": "“… They’re faithless, shameless, imprudent, unethical, and witless. …” ",
  "sn37.10:1.4": "",
  "sn37.11:0.1": "Linked Discourses 37.11 ",
  "sn37.11:0.2": "1. Abbreviated Texts ",
  "sn37.11:0.3": "Unlearned ",
  "sn37.11:1.1": "",
  "sn37.11:1.2": "",
  "sn37.11:1.3": "“… They’re faithless, shameless, imprudent, unlearned, and witless. …” ",
  "sn37.11:1.4": "",
  "sn37.12:0.1": "Linked Discourses 37.12 ",
  "sn37.12:0.2": "1. Abbreviated Texts ",
  "sn37.12:0.3": "Lazy ",
  "sn37.12:1.1": "",
  "sn37.12:1.2": "",
  "sn37.12:1.3": "“… They’re faithless, shameless, imprudent, lazy, and witless. …” ",
  "sn37.12:1.4": "",
  "sn37.13:0.1": "Linked Discourses 37.13 ",
  "sn37.13:0.2": "1. Abbreviated Texts ",
  "sn37.13:0.3": "Unmindful ",
  "sn37.13:1.1": "",
  "sn37.13:1.2": "",
  "sn37.13:1.3": "“… They’re faithless, shameless, imprudent, unmindful, and witless. …” ",
  "sn37.13:1.4": "",
  "sn37.14:0.1": "Linked Discourses 37.14 ",
  "sn37.14:0.2": "1. Abbreviated Texts ",
  "sn37.14:0.3": "Five Threats ",
  "sn37.14:1.1": "“Anuruddha, when ladies have five qualities, when their body breaks up, after death, they are reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn37.14:1.2": "What five? ",
  "sn37.14:1.3": "They kill living creatures, steal, commit sexual misconduct, lie, and consume beer, wine, and liquor intoxicants. ",
  "sn37.14:1.4": "When ladies possess these five qualities, when their body breaks up, after death, they are reborn in a place of loss, a bad place, the underworld, hell.” ",
  "sn37.14:1.5": "",
  "sn37.14:1.6": "",
  "sn37.14:2.1": "",
  "sn37.14:2.2": "",
  "sn37.14:2.3": "",
  "sn37.14:2.4": "",
  "sn37.14:2.5": "",
  "sn37.14:2.6": "",
  "sn37.14:2.7": "",
  "sn37.15:0.1": "Linked Discourses 37.15 ",
  "sn37.15:0.2": "2. Abbreviated Texts ",
  "sn37.15:0.3": "Loving ",
  "sn37.15:1.1": "Then Venerable Anuruddha went up to the Buddha … and asked him, ",
  "sn37.15:1.2": "“Sometimes, sir, with my clairvoyance that’s purified and superhuman, I see that a ladywhen her body breaks up, after deathis reborn in a good place, a heavenly realm. ",
  "sn37.15:1.3": "How many qualities do ladies have so that they’re reborn in a good place, a heavenly realm?” ",
  "sn37.15:2.1": "“Anuruddha, when ladies have five qualities, when their body breaks up, after death, they are reborn in a good place, a heavenly realm. ",
  "sn37.15:2.2": "What five? ",
  "sn37.15:2.3": "They’re faithful, conscientious, prudent, loving, and wise. ",
  "sn37.15:2.4": "When ladies possess these five qualities, when their body breaks up, after death, they are reborn in a good place, a heavenly realm.” ",
  "sn37.16:0.1": "Linked Discourses 37.16 ",
  "sn37.16:0.2": "2. Abbreviated Texts ",
  "sn37.16:0.3": "Free of Acrimony ",
  "sn37.16:1.1": "",
  "sn37.16:1.2": "",
  "sn37.16:1.3": "“… They’re faithful, conscientious, prudent, free of acrimony, and wise. …” ",
  "sn37.16:1.4": "",
  "sn37.17:0.1": "Linked Discourses 37.17 ",
  "sn37.17:0.2": "2. Abbreviated Texts ",
  "sn37.17:0.3": "Free of Jealousy ",
  "sn37.17:1.1": "",
  "sn37.17:1.2": "",
  "sn37.17:1.3": "“… They’re faithful, conscientious, prudent, free of jealousy, and wise. …” ",
  "sn37.18:0.1": "Linked Discourses 37.18 ",
  "sn37.18:0.2": "2. Abbreviated Texts ",
  "sn37.18:0.3": "Free of Stinginess ",
  "sn37.18:1.1": "“… They’re faithful, conscientious, prudent, free of stinginess, and wise. …” ",
  "sn37.19:0.1": "Linked Discourses 37.19 ",
  "sn37.19:0.2": "2. Abbreviated Texts ",
  "sn37.19:0.3": "Not Adulterous ",
  "sn37.19:1.1": "“… They’re faithful, conscientious, prudent, not adulterous, and wise. …” ",
  "sn37.20:0.1": "Linked Discourses 37.20 ",
  "sn37.20:0.2": "2. Abbreviated Texts ",
  "sn37.20:0.3": "Ethical ",
  "sn37.20:1.1": "“… They’re faithful, conscientious, prudent, ethical, and wise. …” ",
  "sn37.21:0.1": "Linked Discourses 37.21 ",
  "sn37.21:0.2": "2. Abbreviated Texts ",
  "sn37.21:0.3": "Very Learned ",
  "sn37.21:1.1": "“… They’re faithful, conscientious, prudent, learned, and wise. …” ",
  "sn37.22:0.1": "Linked Discourses 37.22 ",
  "sn37.22:0.2": "2. Abbreviated Texts ",
  "sn37.22:0.3": "Energetic ",
  "sn37.22:1.1": "“… They’re faithful, conscientious, prudent, energetic, and wise. …” ",
  "sn37.23:0.1": "Linked Discourses 37.23 ",
  "sn37.23:0.2": "2. Abbreviated Texts ",
  "sn37.23:0.3": "Mindful ",
  "sn37.23:1.1": "“… They’re faithful, conscientious, prudent, mindful, and wise. …” ",
  "sn37.23:1.2": "",
  "sn37.23:1.3": "",
  "sn37.24:0.1": "Linked Discourses 37.24 ",
  "sn37.24:0.2": "2. Abbreviated Texts ",
  "sn37.24:0.3": "Five Precepts ",
  "sn37.24:1.1": "“Anuruddha, when ladies have five qualities, when their body breaks up, after death, they are reborn in a good place, a heavenly realm. ",
  "sn37.24:1.2": "What five? ",
  "sn37.24:1.3": "They don’t kill living creatures, steal, commit sexual misconduct, lie, or consume beer, wine, and liquor intoxicants. ",
  "sn37.24:1.4": "When ladies possess these five qualities, when their body breaks up, after death, they are reborn in a good place, a heavenly realm.” ",
  "sn37.24:1.5": "",
  "sn37.24:1.6": "",
  "sn37.24:2.1": "",
  "sn37.24:2.2": "",
  "sn37.24:2.3": "",
  "sn37.24:2.4": "",
  "sn37.24:2.5": "",
  "sn37.25:0.1": "Linked Discourses 37.25 ",
  "sn37.25:0.2": "3. Powers ",
  "sn37.25:0.3": "Assured ",
  "sn37.25:1.1": "“Mendicants, there are these five powers of a lady. ",
  "sn37.25:1.2": "What five? ",
  "sn37.25:1.3": "Attractiveness, wealth, relatives, children, and ethical behavior. ",
  "sn37.25:1.4": "These are the five powers of a lady. ",
  "sn37.25:1.5": "A lady living at home with these five qualities is self-assured.” ",
  "sn37.26:0.1": "Linked Discourses 37.26 ",
  "sn37.26:0.2": "3. Powers ",
  "sn37.26:0.3": "Under Her Thumb ",
  "sn37.26:1.1": "“Mendicants, there are these five powers of a lady. ",
  "sn37.26:1.2": "What five? ",
  "sn37.26:1.3": "Attractiveness, wealth, relatives, children, and ethical behavior. ",
  "sn37.26:1.4": "These are the five powers of a lady. ",
  "sn37.26:1.5": "A lady living at home with these five powers has her husband under her thumb.” ",
  "sn37.27:0.1": "Linked Discourses 37.27 ",
  "sn37.27:0.2": "3. Powers ",
  "sn37.27:0.3": "Mastered ",
  "sn37.27:1.1": "“Mendicants, there are these five powers of a lady. ",
  "sn37.27:1.2": "What five? ",
  "sn37.27:1.3": "Attractiveness, wealth, relatives, children, and ethical behavior. ",
  "sn37.27:1.4": "These are the five powers of a lady. ",
  "sn37.27:1.5": "A lady with these five powers lives having mastered her husband.” ",
  "sn37.28:0.1": "Linked Discourses 37.28 ",
  "sn37.28:0.2": "3. Powers ",
  "sn37.28:0.3": "One ",
  "sn37.28:1.1": "“Mendicants, by means of one power a man lives having mastered a lady. ",
  "sn37.28:1.2": "By means of what one power? ",
  "sn37.28:1.3": "When a lady has been mastered by the power of authority, her powers of attractiveness, wealth, relatives, children, and ethical behavior do not avail her.” ",
  "sn37.29:0.1": "Linked Discourses 37.29 ",
  "sn37.29:0.2": "3. Powers ",
  "sn37.29:0.3": "In That Respect ",
  "sn37.29:1.1": "“Mendicants, there are these five powers of a lady. ",
  "sn37.29:1.2": "What five? ",
  "sn37.29:1.3": "Attractiveness, wealth, relatives, children, and ethical behavior. ",
  "sn37.29:1.4": "A lady who has the power of attractiveness but not the power of wealth ",
  "sn37.29:1.5": "is incomplete in that respect. ",
  "sn37.29:1.6": "But when she has the power of attractiveness and the power of wealth ",
  "sn37.29:1.7": "she’s complete in that respect. ",
  "sn37.29:1.8": "A lady who has the powers of attractiveness and wealth, but not the power of relatives ",
  "sn37.29:1.9": "is incomplete in that respect. ",
  "sn37.29:1.10": "But when she has the powers of attractiveness, wealth, and relatives ",
  "sn37.29:1.11": "she’s complete in that respect. ",
  "sn37.29:1.12": "A lady who has the powers of attractiveness, wealth, and relatives, but not the power of children ",
  "sn37.29:1.13": "is incomplete in that respect. ",
  "sn37.29:1.14": "But when she has the powers of attractiveness, wealth, relatives, and children ",
  "sn37.29:1.15": "she’s complete in that respect. ",
  "sn37.29:1.16": "A lady who has the powers of attractiveness, wealth, relatives, and children, but not the power of ethical behavior ",
  "sn37.29:1.17": "is incomplete in that respect. ",
  "sn37.29:1.18": "But when she has the powers of attractiveness, wealth, relatives, children, and ethical behavior ",
  "sn37.29:1.19": "she’s complete in that respect. ",
  "sn37.29:1.20": "These are the five powers of a lady.” ",
  "sn37.30:0.1": "Linked Discourses 37.30 ",
  "sn37.30:0.2": "3. Powers ",
  "sn37.30:0.3": "They Send Her Away ",
  "sn37.30:1.1": "“Mendicants, there are these five powers of a lady. ",
  "sn37.30:1.2": "What five? ",
  "sn37.30:1.3": "Attractiveness, wealth, relatives, children, and ethical behavior. ",
  "sn37.30:1.4": "If a lady has the power of attractiveness but not that of ethical behavior, the family will send her away, they won’t accommodate her. ",
  "sn37.30:1.5": "If a lady has the powers of attractiveness and wealth but not that of ethical behavior, the family will send her away, they won’t accommodate her. ",
  "sn37.30:1.6": "If a lady has the powers of attractiveness, wealth, and relatives, but not that of ethical behavior, the family will send her away, they won’t accommodate her. ",
  "sn37.30:1.7": "If a lady has the powers of attractiveness, wealth, relatives, and children, but not that of ethical behavior, the family will send her away, they won’t accommodate her. ",
  "sn37.30:1.8": "If a lady has the power of ethical behavior but not that of attractiveness, the family will accommodate her, they won’t send her away. ",
  "sn37.30:1.9": "If a lady has the power of ethical behavior but not that of wealth, the family will accommodate her, they won’t send her away. ",
  "sn37.30:1.10": "If a lady has the power of ethical behavior but not that of relatives, the family will accommodate her, they won’t send her away. ",
  "sn37.30:1.11": "If a lady has the power of ethical behavior but not that of children, the family will accommodate her, they won’t send her away. ",
  "sn37.30:1.12": "These are the five powers of a lady.” ",
  "sn37.31:0.1": "Linked Discourses 37.31 ",
  "sn37.31:0.2": "3. Powers ",
  "sn37.31:0.3": "Cause ",
  "sn37.31:1.1": "“Mendicants, there are these five powers of a lady. ",
  "sn37.31:1.2": "What five? ",
  "sn37.31:1.3": "Attractiveness, wealth, relatives, children, and ethical behavior. ",
  "sn37.31:1.4": "It is not because of the powers of attractiveness, wealth, relatives, or children that ladies, when their body breaks up, after death, are reborn in a good place, a heavenly realm. ",
  "sn37.31:1.5": "It is because of the power of ethical behavior that ladies, when their body breaks up, after death, are reborn in a good place, a heavenly realm. ",
  "sn37.31:1.6": "These are the five powers of a lady.” ",
  "sn37.32:0.1": "Linked Discourses 37.32 ",
  "sn37.32:0.2": "3. Powers ",
  "sn37.32:0.3": "Things ",
  "sn37.32:1.1": "“Mendicants, there are five things that are hard to get for ladies who have not made merit. ",
  "sn37.32:1.2": "What five? ",
  "sn37.32:1.3": "‘May I be born into a suitable family!’ ",
  "sn37.32:1.4": "This is the first thing. ",
  "sn37.32:1.5": "‘Having been born in a suitable family, may I marry into a suitable family!’ ",
  "sn37.32:1.6": "This is the second thing. ",
  "sn37.32:1.7": "‘Having been born in a suitable family and married into a suitable family, may I live at home without a co-wife!’ ",
  "sn37.32:1.8": "This is the third thing. ",
  "sn37.32:1.9": "‘Having been born in a suitable family, and married into a suitable family, and living at home without a co-wife, may I have children!’ ",
  "sn37.32:1.10": "This is the fourth thing. ",
  "sn37.32:1.11": "‘Having been born in a suitable family, and married into a suitable family, and living at home without a co-wife, and having had children, may I live having mastered my husband!’ ",
  "sn37.32:1.12": "This is the fifth thing. ",
  "sn37.32:1.13": "These are the five things that are hard to get for ladies who have not made merit. ",
  "sn37.32:2.1": "There are five things that are easy to get for ladies who have made merit. ",
  "sn37.32:2.2": "What five? ",
  "sn37.32:2.3": "‘May I be born into a suitable family!’ ",
  "sn37.32:2.4": "This is the first thing. ",
  "sn37.32:2.5": "‘Having been born into a suitable family, may I marry into a suitable family!’ ",
  "sn37.32:2.6": "This is the second thing. ",
  "sn37.32:2.7": "‘Having been born into a suitable family and married into a suitable family, may I live at home without a co-wife!’ ",
  "sn37.32:2.8": "This is the third thing. ",
  "sn37.32:2.9": "‘Having been born into a suitable family, and married into a suitable family, and living at home without a co-wife, may I have children!’ ",
  "sn37.32:2.10": "This is the fourth thing. ",
  "sn37.32:2.11": "‘Having been born into a suitable family, and married into a suitable family, and living at home without a co-wife, and having had children, may I live having mastered my husband!’ ",
  "sn37.32:2.12": "This is the fifth thing. ",
  "sn37.32:2.13": "These are the five things that are easy to get for ladies who have made merit.” ",
  "sn37.33:0.1": "Linked Discourses 37.33 ",
  "sn37.33:0.2": "3. Powers ",
  "sn37.33:0.3": "Living With Self-Assurance ",
  "sn37.33:1.1": "“Mendicants, a lady living at home with five qualities is self-assured. ",
  "sn37.33:1.2": "What five? ",
  "sn37.33:1.3": "She doesn’t kill living creatures, steal, commit sexual misconduct, lie, or consume beer, wine, and liquor intoxicants. ",
  "sn37.33:1.4": "A lady living at home with these five qualities is self-assured.” ",
  "sn37.34:0.1": "Linked Discourses 37.34 ",
  "sn37.34:0.2": "3. Powers ",
  "sn37.34:0.3": "Growth ",
  "sn37.34:1.1": "“Mendicants, a female noble disciple who grows in five ways grows nobly, taking on what is essential and excellent in this life. ",
  "sn37.34:1.2": "What five? ",
  "sn37.34:1.3": "She grows in faith, ethics, learning, generosity, and wisdom. ",
  "sn37.34:1.4": "A female noble disciple who grows in these five ways grows nobly, taking on what is essential and excellent in this life. ",
  "sn37.34:2.1": "When she grows in faith and ethics, ",
  "sn37.34:2.2": "wisdom, and both generosity and learning",
  "sn37.34:2.3": "a virtuous laywoman such as she ",
  "sn37.34:2.4": "takes on what is essential for herself in this life.” ",
  "sn37.34:2.5": "",
  "sn37.34:2.6": "",
  "sn37.34:3.1": "",
  "sn37.34:3.2": "",
  "sn37.34:3.3": "",
  "sn37.34:3.4": "",
  "sn37.34:3.5": "The Linked Discourses on ladies are complete. "
}
window.BILARA["sn37_v1"]["en"]["sn37_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
