window.BILARA = window.BILARA || {};
window.BILARA["sn3_v1"] = window.BILARA["sn3_v1"] || {};
window.BILARA["sn3_v1"]["en"] = {
  "sn3.1:0.1": "Linked Discourses 3.1 ",
  "sn3.1:0.2": "1. Shackles ",
  "sn3.1:0.3": "Young ",
  "sn3.1:1.1": "So I have heard. ",
  "sn3.1:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn3.1:1.3": "Then King Pasenadi of Kosala went up to the Buddha, and exchanged greetings with him. ",
  "sn3.1:1.4": "When the greetings and polite conversation were over, he sat down to one side and said to the Buddha, ",
  "sn3.1:1.5": "“Does the worthy Gotama claim to have awakened to the supreme perfect awakening?” ",
  "sn3.1:1.6": "“If anyone should rightly be said to have awakened to the supreme perfect awakening, it’s me. ",
  "sn3.1:1.7": "For, great king, I have awakened to the supreme perfect awakening.” ",
  "sn3.1:2.1": "“Well, there are those ascetics and brahmins who lead an order and a community, and tutor a community. They’re well-known and famous religious founders, deemed holy by many people. That is, ",
  "sn3.1:2.2": "Pūraṇa Kassapa, the bamboo-staffed ascetic Gosāla, the Jain ascetic of the Ñātika clan, Sañjaya Belaṭṭhiputta, Pakudha Kaccāyana, and Ajita of the hair blanket. ",
  "sn3.1:2.3": "I also asked them whether they claimed to have awakened to the supreme perfect awakening, but they made no such claim. ",
  "sn3.1:2.4": "So why do you, given that you’re so young in age and newly gone forth?” ",
  "sn3.1:3.1": "“Great king, these four things should not be looked down upon or disparaged because they are young. ",
  "sn3.1:3.2": "What four? ",
  "sn3.1:3.3": "An aristocrat, ",
  "sn3.1:3.4": "a serpent, ",
  "sn3.1:3.5": "a fire, ",
  "sn3.1:3.6": "and a mendicant. ",
  "sn3.1:3.7": "These four things should not be looked down upon or disparaged because they are young.” ",
  "sn3.1:4.1": "That is what the Buddha said. ",
  "sn3.1:4.2": "Then the Holy One, the Teacher, went on to say: ",
  "sn3.1:5.1": "“A man should not despise ",
  "sn3.1:5.2": "an aristocrat of impeccable lineage, ",
  "sn3.1:5.3": "high-born and famous, ",
  "sn3.1:5.4": "just because they’re young. ",
  "sn3.1:6.1": "For it’s possible that that lord of mankind, ",
  "sn3.1:6.2": "as aristocrat, will gain the throne. ",
  "sn3.1:6.3": "And in his anger he’ll execute a royal punishment, ",
  "sn3.1:6.4": "and have you violently beaten. ",
  "sn3.1:6.5": "Hence you should avoid him ",
  "sn3.1:6.6": "for the sake of your own life. ",
  "sn3.1:7.1": "Whether in village or wilderness, ",
  "sn3.1:7.2": "wherever a serpent is seen, ",
  "sn3.1:7.3": "a man should not look down on it ",
  "sn3.1:7.4": "or despise it for its youth. ",
  "sn3.1:8.1": "With its rainbow of colors, ",
  "sn3.1:8.2": "the serpent of fiery breath glides along. ",
  "sn3.1:8.3": "It lashes out and bites the fool, ",
  "sn3.1:8.4": "both men and women alike. ",
  "sn3.1:8.5": "Hence you should avoid it ",
  "sn3.1:8.6": "for the sake of your own life. ",
  "sn3.1:9.1": "A fire devours a huge amount, ",
  "sn3.1:9.2": "a conflagration with a blackened trail. ",
  "sn3.1:9.3": "A man should not look down on it ",
  "sn3.1:9.4": "just because it’s young. ",
  "sn3.1:10.1": "For once it gets fuel ",
  "sn3.1:10.2": "it’ll become a huge conflagration. ",
  "sn3.1:10.3": "It’ll lash out and burn the fool, ",
  "sn3.1:10.4": "both men and women alike. ",
  "sn3.1:10.5": "Hence you should avoid it ",
  "sn3.1:10.6": "for the sake of your own life. ",
  "sn3.1:11.1": "When a forest is burned by fire, ",
  "sn3.1:11.2": "a conflagration with a blackened trail, ",
  "sn3.1:11.3": "the shoots will spring up there again, ",
  "sn3.1:11.4": "with the passing of the days and nights. ",
  "sn3.1:12.1": "But if a mendicant endowed with ethics ",
  "sn3.1:12.2": "burns you with their power, ",
  "sn3.1:12.3": "you’ll have no children or livestock, ",
  "sn3.1:12.4": "nor will your heirs find wealth. ",
  "sn3.1:12.5": "Childless and heirless you become, ",
  "sn3.1:12.6": "like a palm-tree stump. ",
  "sn3.1:13.1": "That’s why an astute person, ",
  "sn3.1:13.2": "seeing what’s good for themselves, ",
  "sn3.1:13.3": "would always treat these properly: ",
  "sn3.1:13.4": "a snake, a conflagration, ",
  "sn3.1:13.5": "a famous aristocrat, ",
  "sn3.1:13.6": "and a mendicant endowed with ethics.” ",
  "sn3.1:14.1": "When this was said, King Pasenadi of Kosala said to the Buddha, ",
  "sn3.1:14.2": "“Excellent, sir! Excellent! ",
  "sn3.1:14.3": "As if he were righting the overturned, or revealing the hidden, or pointing out the path to the lost, or lighting a lamp in the dark so people with clear eyes can see what’s there, the Buddha has made the teaching clear in many ways. ",
  "sn3.1:14.4": "I go for refuge to the Buddha, to the teaching, and to the mendicant Saṅgha. ",
  "sn3.1:14.5": "From this day forth, may the Buddha remember me as a lay follower who has gone for refuge for life.” ",
  "sn3.2:0.1": "Linked Discourses 3.2 ",
  "sn3.2:0.2": "1. Shackles ",
  "sn3.2:0.3": "A Person ",
  "sn3.2:1.1": "At Sāvatthī. ",
  "sn3.2:1.2": "Then King Pasenadi of Kosala went up to the Buddha, bowed, sat down to one side, and said to the Buddha, ",
  "sn3.2:1.3": "“Sir, how many things arise inside a person for their harm, suffering, and discomfort?” ",
  "sn3.2:2.1": "“Great king, three things arise inside a person for their harm, suffering, and discomfort. ",
  "sn3.2:2.2": "What three? ",
  "sn3.2:2.3": "Greed, ",
  "sn3.2:2.4": "hate, ",
  "sn3.2:2.5": "and delusion. ",
  "sn3.2:2.6": "These three things arise inside a person for their harm, suffering, and discomfort.” ",
  "sn3.2:2.7": "That is what the Buddha said. … ",
  "sn3.2:3.1": "“When greed, hate, and delusion, ",
  "sn3.2:3.2": "originate inside oneself, ",
  "sn3.2:3.3": "they harm a person of wicked heart, ",
  "sn3.2:3.4": "as a bamboo is destroyed by its own fruit.” ",
  "sn3.3:0.1": "Linked Discourses 3.3 ",
  "sn3.3:0.2": "1. Shackles ",
  "sn3.3:0.3": "Old Age and Death ",
  "sn3.3:1.1": "At Sāvatthī. ",
  "sn3.3:1.2": "Seated to one side, King Pasenadi said to the Buddha, ",
  "sn3.3:1.3": "“Sir, for someone who has been reborn, is there any exemption from old age and death?” ",
  "sn3.3:1.4": "“Great king, for someone who has been reborn, there’s no exemption from old age and death. ",
  "sn3.3:1.5": "Even for well-to-do aristocrats, ",
  "sn3.3:1.6": "brahmins, ",
  "sn3.3:1.7": "or householdersrich, affluent, and wealthy, with lots of gold and silver, lots of property and assets, and lots of money and grainwhen they’re born, there’s no exemption from old age and death. ",
  "sn3.3:1.8": "Even for mendicants who are perfectedwho have ended the defilements, completed the spiritual journey, done what had to be done, laid down the burden, achieved their heart’s goal, utterly ended the fetter of continued existence, and are rightly freed through enlightenmenttheir bodies are liable to break up and be laid to rest.” ",
  "sn3.3:1.9": "That is what the Buddha said. … ",
  "sn3.3:2.1": "“Fancy chariots of kings wear out, ",
  "sn3.3:2.2": "and even this body gets old. ",
  "sn3.3:2.3": "But the truth of the good never gets old",
  "sn3.3:2.4": "so the good proclaim to the good.” ",
  "sn3.4:0.1": "Linked Discourses 3.4 ",
  "sn3.4:0.2": "1. Shackles ",
  "sn3.4:0.3": "Loved ",
  "sn3.4:1.1": "At Sāvatthī. ",
  "sn3.4:1.2": "Seated to one side, King Pasenadi said to the Buddha, ",
  "sn3.4:1.3": "“Just now, sir, as I was in private retreat this thought came to mind. ",
  "sn3.4:1.4": "‘Who are those who love themselves? And who are those who don’t love themselves?’ ",
  "sn3.4:1.5": "Then it occurred to me: ",
  "sn3.4:1.6": "‘Those who do bad things by way of body, speech, and mind ",
  "sn3.4:1.7": "don’t love themselves. ",
  "sn3.4:1.8": "Even though they may say: ",
  "sn3.4:1.9": "“I love myself”, they don’t really. ",
  "sn3.4:1.10": "Why is that? ",
  "sn3.4:1.11": "It’s because they treat themselves like an enemy. ",
  "sn3.4:1.12": "That’s why they don’t love themselves. ",
  "sn3.4:1.13": "Those who do good things by way of body, speech, and mind ",
  "sn3.4:1.14": "do love themselves. ",
  "sn3.4:1.15": "Even though they may say: ",
  "sn3.4:1.16": "“I don’t love myself”, they do really. ",
  "sn3.4:1.17": "Why is that? ",
  "sn3.4:1.18": "It’s because they treat themselves like a loved one. ",
  "sn3.4:1.19": "That’s why they do love themselves.’” ",
  "sn3.4:2.1": "“That’s so true, great king! That’s so true!” said the Buddha. And he repeated the king’s statement, adding: ",
  "sn3.4:2.2": "",
  "sn3.4:2.3": "",
  "sn3.4:2.4": "",
  "sn3.4:2.5": "",
  "sn3.4:2.6": "",
  "sn3.4:2.7": "",
  "sn3.4:2.8": "",
  "sn3.4:2.9": "",
  "sn3.4:2.10": "",
  "sn3.4:2.11": "",
  "sn3.4:2.12": "",
  "sn3.4:2.13": "",
  "sn3.4:2.14": "",
  "sn3.4:2.15": "",
  "sn3.4:2.16": "",
  "sn3.4:2.17": "",
  "sn3.4:3.1": "“If you knew your self as beloved, ",
  "sn3.4:3.2": "you’d not yoke yourself to wickedness. ",
  "sn3.4:3.3": "For happiness is not easy to find ",
  "sn3.4:3.4": "by someone who does bad deeds. ",
  "sn3.4:4.1": "When you’re seized by the terminator ",
  "sn3.4:4.2": "as you give up your human life, ",
  "sn3.4:4.3": "what can you call your own? ",
  "sn3.4:4.4": "What do you take when you go? ",
  "sn3.4:4.5": "What goes with you, ",
  "sn3.4:4.6": "like a shadow that never leaves? ",
  "sn3.4:5.1": "Both the good and the bad ",
  "sn3.4:5.2": "that a mortal does in this life ",
  "sn3.4:5.3": "is what they can call their own. ",
  "sn3.4:5.4": "That’s what they take when they go. ",
  "sn3.4:5.5": "That’s what goes with them, ",
  "sn3.4:5.6": "like a shadow that never leaves. ",
  "sn3.4:6.1": "That’s why you should do good, ",
  "sn3.4:6.2": "investing in the future life. ",
  "sn3.4:6.3": "The good deeds of sentient beings ",
  "sn3.4:6.4": "support them in the next world.” ",
  "sn3.5:0.1": "Linked Discourses 3.5 ",
  "sn3.5:0.2": "1. Shackles ",
  "sn3.5:0.3": "Self-Protected ",
  "sn3.5:1.1": "At Sāvatthī. ",
  "sn3.5:1.2": "Seated to one side, King Pasenadi said to the Buddha, ",
  "sn3.5:1.3": "“Just now, sir, as I was in private retreat this thought came to mind. ",
  "sn3.5:1.4": "‘Who are those who protect themselves? And who are those who don’t protect themselves?’ ",
  "sn3.5:1.5": "Then it occurred to me: ",
  "sn3.5:1.6": "‘Those who do bad things by way of body, speech, and mind ",
  "sn3.5:1.7": "don’t protect themselves. ",
  "sn3.5:1.8": "Even if they’re protected by a company of elephants, cavalry, chariots, or infantry, ",
  "sn3.5:1.9": "they still don’t protect themselves. ",
  "sn3.5:1.10": "Why is that? ",
  "sn3.5:1.11": "Because such protection is exterior, not interior. ",
  "sn3.5:1.12": "That’s why they don’t protect themselves. ",
  "sn3.5:1.13": "Those who do good things by way of body, speech, and mind ",
  "sn3.5:1.14": "do protect themselves. ",
  "sn3.5:1.15": "Even if they’re not protected by a company of elephants, cavalry, chariots, or infantry, ",
  "sn3.5:1.16": "they still protect themselves. ",
  "sn3.5:1.17": "Why is that? ",
  "sn3.5:1.18": "Because such protection is interior, not exterior. ",
  "sn3.5:1.19": "That’s why they do protect themselves.’” ",
  "sn3.5:2.1": "“That’s so true, great king! That’s so true!” said the Buddha. And he repeated the king’s statement, adding: ",
  "sn3.5:2.2": "",
  "sn3.5:2.3": "",
  "sn3.5:2.4": "",
  "sn3.5:2.5": "",
  "sn3.5:2.6": "",
  "sn3.5:2.7": "",
  "sn3.5:2.8": "",
  "sn3.5:2.9": "",
  "sn3.5:2.10": "",
  "sn3.5:2.11": "",
  "sn3.5:2.12": "",
  "sn3.5:2.13": "",
  "sn3.5:2.14": "",
  "sn3.5:3.1": "“Restraint of the body is good; ",
  "sn3.5:3.2": "restraint of speech is good; ",
  "sn3.5:3.3": "restraint of mind is good; ",
  "sn3.5:3.4": "everywhere, restraint is good. ",
  "sn3.5:3.5": "A sincere person, restrained everywhere, ",
  "sn3.5:3.6": "is said to be ‘protected’.” ",
  "sn3.6:0.1": "Linked Discourses 3.6 ",
  "sn3.6:0.2": "1. Shackles ",
  "sn3.6:0.3": "Few ",
  "sn3.6:1.1": "At Sāvatthī. ",
  "sn3.6:1.2": "Seated to one side, King Pasenadi said to the Buddha, ",
  "sn3.6:1.3": "“Just now, sir, as I was in private retreat this thought came to mind: ",
  "sn3.6:1.4": "‘Few are the sentient beings in the world who, when they obtain luxury possessions, don’t grow indulgent and negligent, giving in to greed for sensual pleasures, and doing the wrong thing by others. ",
  "sn3.6:1.5": "There are many more who, when they obtain luxury possessions, do grow indulgent and negligent, giving in to greed for sensual pleasures, and doing the wrong thing by others.’” ",
  "sn3.6:2.1": "“That’s so true, great king! That’s so true!” said the Buddha. And he repeated the king’s statement, adding: ",
  "sn3.6:2.2": "",
  "sn3.6:2.3": "",
  "sn3.6:2.4": "",
  "sn3.6:3.1": "“Full of desire for possessions and pleasures, ",
  "sn3.6:3.2": "greedy, infatuated by sensual pleasures; ",
  "sn3.6:3.3": "they don’t notice that they’ve gone too far, ",
  "sn3.6:3.4": "like deer ensnared in a trap set out. ",
  "sn3.6:3.5": "It’ll be bitter later on; ",
  "sn3.6:3.6": "for the result will be bad for them.” ",
  "sn3.7:0.1": "Linked Discourses 3.7 ",
  "sn3.7:0.2": "1. Shackles ",
  "sn3.7:0.3": "Judgment ",
  "sn3.7:1.1": "At Sāvatthī. ",
  "sn3.7:1.2": "Seated to one side, King Pasenadi said to the Buddha, ",
  "sn3.7:1.3": "“Sir, when I’m sitting in court I see well-to-do aristocrats, brahmins, and householdersrich, affluent, and wealthy, with lots of gold and silver, lots of property and assets, and lots of money and grain. But they tell deliberate lies for the sake of sensual pleasures. ",
  "sn3.7:1.4": "Then it occurred to me: ",
  "sn3.7:1.5": "‘Enough with passing judgment today. Now my dearest will be known by the judgments he makes.’” ",
  "sn3.7:2.1": "“That’s so true, great king! That’s so true! ",
  "sn3.7:2.2": "Those who are well-to-do aristocrats, brahmins, and householders tell deliberate lies for the sake of sensual pleasures. ",
  "sn3.7:2.3": "That is for their lasting harm and suffering.” ",
  "sn3.7:2.4": "That is what the Buddha said. … ",
  "sn3.7:3.1": "“Full of desire for possessions and pleasures, ",
  "sn3.7:3.2": "greedy, infatuated by sensual pleasures; ",
  "sn3.7:3.3": "they don’t notice that they’ve gone too far, ",
  "sn3.7:3.4": "like fish swiftly snared. ",
  "sn3.7:3.5": "It’ll be bitter later on; ",
  "sn3.7:3.6": "for the result will be bad for them.” ",
  "sn3.8:0.1": "Linked Discourses 3.8 ",
  "sn3.8:0.2": "1. Shackles ",
  "sn3.8:0.3": "With Queen Mallikā ",
  "sn3.8:1.1": "At Sāvatthī. ",
  "sn3.8:1.2": "Now at that time King Pasenadi of Kosala was upstairs in the royal longhouse together with Queen Mallikā. ",
  "sn3.8:1.3": "Then the king said to the queen, ",
  "sn3.8:1.4": "“Mallikā, is there anyone more dear to you than yourself?” ",
  "sn3.8:1.5": "“No, great king, there isn’t. ",
  "sn3.8:1.6": "But is there anyone more dear to you than yourself?” ",
  "sn3.8:1.7": "“For me also, Mallikā, there’s no-one.” ",
  "sn3.8:2.1": "Then King Pasenadi of Kosala came downstairs from the stilt longhouse, went to the Buddha, bowed, sat down to one side, and told him what had happened. ",
  "sn3.8:2.2": "",
  "sn3.8:2.3": "",
  "sn3.8:2.4": "",
  "sn3.8:2.5": "",
  "sn3.8:2.6": "",
  "sn3.8:2.7": "",
  "sn3.8:2.8": "",
  "sn3.8:3.1": "Then, understanding this matter, on that occasion the Buddha spoke this verse: ",
  "sn3.8:4.1": "“Having explored every quarter with the mind, ",
  "sn3.8:4.2": "one finds no-one dearer than oneself. ",
  "sn3.8:4.3": "Likewise for others, each holds themselves dear; ",
  "sn3.8:4.4": "so one who desires self-knowledge would harm no other.” ",
  "sn3.9:0.1": "Linked Discourses 3.9 ",
  "sn3.9:0.2": "1. Shackles ",
  "sn3.9:0.3": "Sacrifice ",
  "sn3.9:1.1": "At Sāvatthī. ",
  "sn3.9:1.2": "Now at that time a big sacrifice had been set up for King Pasenadi of Kosala. Bulls, bullocks, heifers, goats and ramsfive hundred of eachhad been led to the pillar for the sacrifice. ",
  "sn3.9:1.3": "His bondservants, servants, and workers did their jobs under threat of punishment and danger, weeping with tearful faces. ",
  "sn3.9:2.1": "Then several mendicants robed up in the morning and, taking their bowls and robes, entered Sāvatthī for alms. ",
  "sn3.9:2.2": "Then, after the meal, when they returned from almsround, they went up to the Buddha, bowed, sat down to one side, and told him what was happening. ",
  "sn3.9:2.3": "",
  "sn3.9:2.4": "",
  "sn3.9:3.1": "Then, understanding this matter, on that occasion the Buddha recited these verses: ",
  "sn3.9:4.1": "“Horse sacrifice, human sacrifice, ",
  "sn3.9:4.2": "the ‘casting of the yoke-pin’, <j>the ‘royal soma drinking’, ",
  "sn3.9:4.3": "and the ‘unimpeded’",
  "sn3.9:4.4": "these huge violent sacrifices yield no great fruit. ",
  "sn3.9:5.1": "The great sages of right comportment ",
  "sn3.9:5.2": "don’t attend sacrifices ",
  "sn3.9:5.3": "where goats, sheep, and cattle ",
  "sn3.9:5.4": "and various creatures are killed. ",
  "sn3.9:6.1": "But the great sages of right comportment ",
  "sn3.9:6.2": "do attend those sacrifices ",
  "sn3.9:6.3": "that are non-violent and propitious, ",
  "sn3.9:6.4": "where goats, sheep, and cattle, ",
  "sn3.9:6.5": "and various creatures are not killed. ",
  "sn3.9:6.6": "",
  "sn3.9:7.1": "A clever person should sacrifice like this, ",
  "sn3.9:7.2": "for this sacrifice is very fruitful. ",
  "sn3.9:7.3": "For a sponsor of sacrifices like this, ",
  "sn3.9:7.4": "things get better, not worse. ",
  "sn3.9:7.5": "Such a sacrifice is truly abundant, ",
  "sn3.9:7.6": "and even the deities are pleased.” ",
  "sn3.10:0.1": "Linked Discourses 3.10 ",
  "sn3.10:0.2": "1. Shackles ",
  "sn3.10:0.3": "Shackles ",
  "sn3.10:1.1": "Now at that time a large group of people had been put in shackles by King Pasenadi of Kosalasome in ropes, some in manacles, some in chains. ",
  "sn3.10:2.1": "Then several mendicants robed up in the morning and, taking their bowls and robes, entered Sāvatthī for alms. ",
  "sn3.10:2.2": "Then, after the meal, when they returned from almsround, they went up to the Buddha, bowed, sat down to one side, and told him what was happening. ",
  "sn3.10:2.3": "",
  "sn3.10:3.1": "Then, understanding this matter, on that occasion the Buddha recited these verses: ",
  "sn3.10:4.1": "“The attentive say that shackle is not strong ",
  "sn3.10:4.2": "that’s made of iron, wood, or knots. ",
  "sn3.10:4.3": "But obsession with jeweled earrings, ",
  "sn3.10:4.4": "concern for your partners and children: ",
  "sn3.10:5.1": "this, say the attentive, is a strong shackle ",
  "sn3.10:5.2": "dragging the indulgent down, hard to escape. ",
  "sn3.10:5.3": "Having cut this one too they go forth, ",
  "sn3.10:5.4": "unconcerned, having given up sensual pleasures.” ",
  "sn3.10:5.5": "",
  "sn3.10:6.1": "",
  "sn3.10:6.2": "",
  "sn3.10:6.3": "",
  "sn3.11:0.1": "Linked Discourses 3.11 ",
  "sn3.11:0.2": "2. Childless ",
  "sn3.11:0.3": "Seven Matted-Hair Ascetics ",
  "sn3.11:1.1": "At one time the Buddha was staying near Sāvatthī in the stilt longhouse of Migāra’s mother in the Eastern Monastery. ",
  "sn3.11:1.2": "Then in the late afternoon, the Buddha came out of retreat and sat outside the gate. ",
  "sn3.11:1.3": "Then King Pasenadi of Kosala went up to the Buddha, bowed, and sat down to one side. ",
  "sn3.11:2.1": "Now at that time seven matted-hair ascetics, seven Jain ascetics, seven naked ascetics, seven one-cloth ascetics, and seven wanderers passed by not far from the Buddha. Their armpits and bodies were hairy, and their nails were long; and they carried their pack with shoulder-poles. ",
  "sn3.11:2.2": "Then King Pasenadi got up from his seat, arranged his robe over one shoulder, knelt with his right knee on the ground, raised his joined palms toward those various ascetics, and pronounced his name three times: ",
  "sn3.11:2.3": "“Sirs, I am Pasenadi, king of Kosala! … ",
  "sn3.11:2.4": "I am Pasenadi, king of Kosala!” ",
  "sn3.11:3.1": "Then, soon after those ascetics had left, King Pasenadi went up to the Buddha, bowed, sat down to one side, and said to him, ",
  "sn3.11:3.2": "“Sir, these are among those in the world who are perfected or who are on the path to perfection!” ",
  "sn3.11:4.1": "“Great king, as a layman enjoying sensual pleasures, living at home with your children, using sandalwood imported from Kāsi, wearing garlands, fragrance, and makeup, and accepting gold and currency, it’s hard for you to know who is perfected or on the path to perfection. ",
  "sn3.11:5.1": "You can get to know a person’s ethics by living with them. But only after a long time, not casually; only when attentive, not when inattentive; and only by the wise, not the witless. ",
  "sn3.11:5.2": "You can get to know a person’s purity by dealing with them. … ",
  "sn3.11:5.3": "You can get to know a person’s resilience in times of trouble. … ",
  "sn3.11:5.4": "You can get to know a person’s wisdom by discussion. But only after a long time, not casually; only when attentive, not when inattentive; and only by the wise, not the witless.” ",
  "sn3.11:6.1": "“It’s incredible, sir, it’s amazing, ",
  "sn3.11:6.2": "how well said this was by the Buddha. … ",
  "sn3.11:6.3": "",
  "sn3.11:6.4": "",
  "sn3.11:6.5": "",
  "sn3.11:6.6": "",
  "sn3.11:6.7": "",
  "sn3.11:6.8": "",
  "sn3.11:7.1": "Sir, these are my spies, my undercover agents returning after spying on the country. ",
  "sn3.11:7.2": "I shall later make use of what they first spied out. ",
  "sn3.11:7.3": "Nowwhen they have rinsed off the dust and dirt, and are nicely bathed and anointed, with hair and beard dressed, and dressed in whitethey will amuse themselves, supplied and provided with the five kinds of sensual stimulation.” ",
  "sn3.11:8.1": "Then, understanding this matter, on that occasion the Buddha recited these verses: ",
  "sn3.11:9.1": "“It’s not easy to know a man by his appearance. ",
  "sn3.11:9.2": "You shouldn’t trust them at first sight. ",
  "sn3.11:9.3": "For undisciplined men live in this world ",
  "sn3.11:9.4": "disguised as the disciplined. ",
  "sn3.11:10.1": "Like a fake earring made of clay, ",
  "sn3.11:10.2": "like a copper halfpenny covered with gold, ",
  "sn3.11:10.3": "they live hidden in the world, ",
  "sn3.11:10.4": "corrupt inside but impressive outside.” ",
  "sn3.12:0.1": "Linked Discourses 3.12 ",
  "sn3.12:0.2": "2. Childless ",
  "sn3.12:0.3": "Five Kings ",
  "sn3.12:1.1": "At Sāvatthī. ",
  "sn3.12:1.2": "Now at that time five kings headed by Pasenadi were amusing themselves, supplied and provided with the five kinds of sensual stimulation, and this discussion came up among them: ",
  "sn3.12:1.3": "“What’s the best of sensual pleasures?” ",
  "sn3.12:1.4": "Some of them said, ",
  "sn3.12:1.5": "“Sights are the best of sensual pleasures!” ",
  "sn3.12:1.6": "Others said, ",
  "sn3.12:1.7": "“Sounds are best!” ",
  "sn3.12:1.8": "Others said, ",
  "sn3.12:1.9": "“Smells are best!” ",
  "sn3.12:1.10": "Others said, ",
  "sn3.12:1.11": "“Tastes are best!” ",
  "sn3.12:1.12": "Others said, ",
  "sn3.12:1.13": "“Touches are best!” ",
  "sn3.12:1.14": "Since those kings were unable to persuade each other, ",
  "sn3.12:2.1": "King Pasenadi said to them, ",
  "sn3.12:2.2": "“Come, good fellows, let’s go to the Buddha and ask him about this. ",
  "sn3.12:2.3": "As he answers, so we’ll remember it.” ",
  "sn3.12:2.4": "“Yes, good fellows,” replied those kings. ",
  "sn3.12:3.1": "Then those five kings headed by Pasenadi went to the Buddha, bowed, and sat down to one side. King Pasenadi reported their conversation to the Buddha, and said, ",
  "sn3.12:3.2": "",
  "sn3.12:3.3": "",
  "sn3.12:3.4": "",
  "sn3.12:3.5": "",
  "sn3.12:3.6": "",
  "sn3.12:3.7": "",
  "sn3.12:3.8": "",
  "sn3.12:3.9": "",
  "sn3.12:3.10": "",
  "sn3.12:3.11": "",
  "sn3.12:3.12": "",
  "sn3.12:3.13": "",
  "sn3.12:3.14": "“Sir, what’s the best of sensual pleasures?” ",
  "sn3.12:4.1": "“Great king, which kind of sensual stimulation is best is defined by which is most agreeable, I say. ",
  "sn3.12:4.2": "The very same sights that are agreeable to some are disagreeable to others. ",
  "sn3.12:4.3": "When you’re happy with certain sights, as you’ve got all you wished for, you don’t want any other sight that’s better or finer. ",
  "sn3.12:4.4": "For you, those sights are perfect ",
  "sn3.12:4.5": "and supreme. ",
  "sn3.12:5.1": "The very same sounds … ",
  "sn3.12:5.2": "",
  "sn3.12:5.3": "",
  "sn3.12:5.4": "",
  "sn3.12:6.1": "smells … ",
  "sn3.12:6.2": "",
  "sn3.12:6.3": "",
  "sn3.12:6.4": "",
  "sn3.12:7.1": "tastes … ",
  "sn3.12:7.2": "",
  "sn3.12:7.3": "",
  "sn3.12:7.4": "",
  "sn3.12:8.1": "touches that are agreeable to some are disagreeable to others. ",
  "sn3.12:8.2": "When you’re happy with certain touches, as you’ve got all you wished for, you don’t want any other touch that’s better or finer. ",
  "sn3.12:8.3": "For you, those touches are perfect ",
  "sn3.12:8.4": "and supreme.” ",
  "sn3.12:9.1": "Now at that time the lay follower Candanaṅgalika was sitting in that assembly. ",
  "sn3.12:9.2": "Then he got up from his seat, arranged his robe over one shoulder, raised his joined palms toward the Buddha, and said, ",
  "sn3.12:9.3": "“I feel inspired to speak, Blessed One! I feel inspired to speak, Holy One!” ",
  "sn3.12:9.4": "“Then speak as you feel inspired,” said the Buddha. ",
  "sn3.12:10.1": "Then the lay follower Candanaṅgalika extolled the Buddha in his presence with an appropriate verse: ",
  "sn3.12:11.1": "“Like a fragrant pink lotus ",
  "sn3.12:11.2": "that blooms at daybreak, its fragrance unfaded",
  "sn3.12:11.3": "see Aṅgīrasa shine, ",
  "sn3.12:11.4": "bright as the sun in the sky!” ",
  "sn3.12:12.1": "Then those five kings clothed Candanaṅgalika with five upper robes. ",
  "sn3.12:12.2": "And Candanaṅgalika in turn endowed the Buddha with those robes. ",
  "sn3.13:0.1": "Linked Discourses 3.13 ",
  "sn3.13:0.2": "2. Childless ",
  "sn3.13:0.3": "A Bucketful of Rice ",
  "sn3.13:1.1": "At Sāvatthī. ",
  "sn3.13:1.2": "Now at that time King Pasenadi of Kosala used to eat boiled rice by the bucketful. ",
  "sn3.13:1.3": "Then after eating King Pasenadi of Kosala went up to the Buddha, huffing and puffing. He bowed and sat down to one side. ",
  "sn3.13:2.1": "Then, knowing that King Pasenadi was huffing and puffing after eating, on that occasion the Buddha spoke this verse: ",
  "sn3.13:3.1": "“When a man is always mindful, ",
  "sn3.13:3.2": "knowing moderation in eating, ",
  "sn3.13:3.3": "his discomfort fades, ",
  "sn3.13:3.4": "and he ages slowly, taking care of his life.” ",
  "sn3.13:4.1": "Now at that time the student Sudassana was standing behind the king. ",
  "sn3.13:4.2": "Then King Pasenadi addressed him, ",
  "sn3.13:4.3": "“Please, dear Sudassana, memorize this verse in the Buddha’s presence and recite it to me whenever I am served a meal. ",
  "sn3.13:4.4": "I’ll set up a regular daily allowance of a hundred dollars for you.” ",
  "sn3.13:4.5": "“Yes, Your Majesty,” replied Sudassana. He memorized that verse in the Buddha’s presence, and then whenever the king was served a meal he would repeat it: ",
  "sn3.13:5.1": "“When a man is always mindful, ",
  "sn3.13:5.2": "knowing moderation in eating, ",
  "sn3.13:5.3": "his discomfort fades, ",
  "sn3.13:5.4": "and he ages slowly, taking care of his life.” ",
  "sn3.13:6.1": "Then the king gradually got used to having at most a cup of rice. ",
  "sn3.13:6.2": "After some time King Pasenadi’s body slimmed right down. Stroking his limbs with his hands, at that time he expressed this heartfelt sentiment: ",
  "sn3.13:6.3": "“In both ways the Buddha has sympathy for me: ",
  "sn3.13:6.4": "in the good of this life and the good of the next.” ",
  "sn3.14:0.1": "Linked Discourses 3.14 ",
  "sn3.14:0.2": "2. Childless ",
  "sn3.14:0.3": "Battle (1st) ",
  "sn3.14:1.1": "At Sāvatthī. ",
  "sn3.14:1.2": "Then King Ajātasattu of Magadha, son of the princess of Videha, mobilized an army of four divisions and marched to Kāsi to attack King Pasenadi of Kosala. ",
  "sn3.14:1.3": "When King Pasenadi heard of this, ",
  "sn3.14:1.4": "",
  "sn3.14:1.5": "he mobilized an army of four divisions and marched to Kāsi to defend it against Ajātasattu. ",
  "sn3.14:1.6": "Then the two kings met in battle. ",
  "sn3.14:1.7": "And in that battle Ajātasattu defeated Pasenadi, ",
  "sn3.14:1.8": "who withdrew to his own capital at Sāvatthī. ",
  "sn3.14:2.1": "Then several mendicants robed up in the morning and, taking their bowls and robes, entered Sāvatthī for alms. ",
  "sn3.14:2.2": "Then, after the meal, when they returned from almsround, they went up to the Buddha, bowed, sat down to one side, and told him what had happened. Then the Buddha said: ",
  "sn3.14:3.1": "",
  "sn3.14:3.2": "",
  "sn3.14:3.3": "",
  "sn3.14:3.4": "",
  "sn3.14:3.5": "",
  "sn3.14:3.6": "",
  "sn3.14:3.7": "",
  "sn3.14:4.1": "“Mendicants, King Ajātasattu has bad friends, companions, and associates. ",
  "sn3.14:4.2": "But King Pasenadi has good friends, companions, and associates. ",
  "sn3.14:4.3": "Yet on this day King Pasenadi will have a bad night’s sleep as one defeated.” ",
  "sn3.14:4.4": "That is what the Buddha said. … ",
  "sn3.14:5.1": "“Victory breeds enmity; ",
  "sn3.14:5.2": "the defeated sleep badly. ",
  "sn3.14:5.3": "The peaceful sleep at ease, ",
  "sn3.14:5.4": "having left victory and defeat behind.” ",
  "sn3.15:0.1": "Linked Discourses 3.15 ",
  "sn3.15:0.2": "2. Childless ",
  "sn3.15:0.3": "Battle (2nd) ",
  "sn3.15:1.1": "Then King Ajātasattu of Magadha, son of the princess of Videha, mobilized an army of four divisions and marched to Kāsi to attack King Pasenadi of Kosala. ",
  "sn3.15:1.2": "When King Pasenadi heard of this, ",
  "sn3.15:1.3": "",
  "sn3.15:1.4": "he mobilized an army of four divisions and marched to Kāsi to defend it against Ajātasattu. ",
  "sn3.15:1.5": "Then the two kings met in battle. ",
  "sn3.15:1.6": "And in that battle Pasenadi defeated Ajātasattu and captured him alive. ",
  "sn3.15:1.7": "Then King Pasenadi thought, ",
  "sn3.15:1.8": "“Even though I’ve never betrayed this King Ajātasattu, he betrayed me. Still, he is my nephew. ",
  "sn3.15:1.9": "Now that I’ve vanquished all of Ajātasattu’s elephant troops, cavalry, chariots, and infantry, why don’t I let him loose with just his life?” ",
  "sn3.15:2.1": "And that’s what he did. ",
  "sn3.15:3.1": "Then several mendicants … ",
  "sn3.15:3.2": "told the Buddha what had happened. ",
  "sn3.15:4.1": "",
  "sn3.15:4.2": "",
  "sn3.15:4.3": "",
  "sn3.15:4.4": "",
  "sn3.15:4.5": "",
  "sn3.15:4.6": "",
  "sn3.15:4.7": "",
  "sn3.15:4.8": "",
  "sn3.15:4.9": "",
  "sn3.15:5.1": "",
  "sn3.15:6.1": "Then, understanding this matter, on that occasion the Buddha recited these verses: ",
  "sn3.15:7.1": "“A man goes on plundering ",
  "sn3.15:7.2": "as long as it serves his ends. ",
  "sn3.15:7.3": "But as soon as others plunder him, ",
  "sn3.15:7.4": "the plunderer is plundered. ",
  "sn3.15:8.1": "For the fool thinks they’re on solid ground, ",
  "sn3.15:8.2": "so long as their wickedness has not ripened. ",
  "sn3.15:8.3": "But as soon as that wickedness ripens, ",
  "sn3.15:8.4": "they fall into suffering. ",
  "sn3.15:9.1": "A killer creates a killer; ",
  "sn3.15:9.2": "a conqueror creates a conqueror; ",
  "sn3.15:9.3": "an abuser creates abuse, ",
  "sn3.15:9.4": "and a bully creates a bully. ",
  "sn3.15:9.5": "And so as deeds unfold ",
  "sn3.15:9.6": "the plunderer is plundered.” ",
  "sn3.16:0.1": "Linked Discourses 3.16 ",
  "sn3.16:0.2": "2. Childless ",
  "sn3.16:0.3": "A Daughter ",
  "sn3.16:1.1": "At Sāvatthī. ",
  "sn3.16:1.2": "Then King Pasenadi of Kosala went up to the Buddha, bowed, and sat down to one side. ",
  "sn3.16:1.3": "Then a man went up to the king and whispered in his ear, ",
  "sn3.16:1.4": "“Your Majesty, Queen Mallikā has given birth to a daughter.” ",
  "sn3.16:1.5": "When this was said, King Pasenadi was disappointed. ",
  "sn3.16:2.1": "Then, knowing that King Pasenadi was disappointed, on that occasion the Buddha recited these verses: ",
  "sn3.16:3.1": "“Well, some women are better than men, ",
  "sn3.16:3.2": "O ruler of the people. ",
  "sn3.16:3.3": "Wise and virtuous, a devoted wife ",
  "sn3.16:3.4": "whose mother-in-law is her queen. ",
  "sn3.16:4.1": "And when she has a son, ",
  "sn3.16:4.2": "he becomes a hero, O lord of the land. ",
  "sn3.16:4.3": "The son of such a blessed lady ",
  "sn3.16:4.4": "may even rule the realm.” ",
  "sn3.17:0.1": "Linked Discourses 3.17 ",
  "sn3.17:0.2": "2. Childless ",
  "sn3.17:0.3": "Diligence ",
  "sn3.17:1.1": "At Sāvatthī. ",
  "sn3.17:1.2": "",
  "sn3.17:1.3": "Seated to one side, King Pasenadi said to the Buddha, ",
  "sn3.17:1.4": "“Sir, is there one thing that secures benefits for both ",
  "sn3.17:1.5": "this life and lives to come?” ",
  "sn3.17:2.1": "“There is, great king.” ",
  "sn3.17:2.2": "",
  "sn3.17:3.1": "“So what is that one thing?” ",
  "sn3.17:3.2": "",
  "sn3.17:4.1": "“Diligence, great king, is one thing that secures benefits for both ",
  "sn3.17:4.2": "this life and lives to come. ",
  "sn3.17:4.3": "The footprints of all creatures that walk can fit inside an elephant’s footprint. So an elephant’s footprint is said to be the biggest of them all. ",
  "sn3.17:4.4": "In the same way, diligence is one thing that secures benefits for both ",
  "sn3.17:4.5": "this life and lives to come.” ",
  "sn3.17:4.6": "That is what the Buddha said. … ",
  "sn3.17:5.1": "“For one who desires high delights ",
  "sn3.17:5.2": "again and again",
  "sn3.17:5.3": "long life, beauty, and health, ",
  "sn3.17:5.4": "heaven, and an eminent family",
  "sn3.17:6.1": "the astute praise diligence ",
  "sn3.17:6.2": "in making merit. ",
  "sn3.17:6.3": "Being diligent, an astute person ",
  "sn3.17:6.4": "secures both benefits: ",
  "sn3.17:7.1": "the benefit in this life, ",
  "sn3.17:7.2": "and in lives to come. ",
  "sn3.17:7.3": "An attentive one, comprehending the meaning, ",
  "sn3.17:7.4": "is said to be astute.” ",
  "sn3.18:0.1": "Linked Discourses 3.18 ",
  "sn3.18:0.2": "2. Childless ",
  "sn3.18:0.3": "Good Friends ",
  "sn3.18:1.1": "At Sāvatthī. ",
  "sn3.18:1.2": "Seated to one side, King Pasenadi said to the Buddha, ",
  "sn3.18:1.3": "“Just now, sir, as I was in private retreat this thought came to mind. ",
  "sn3.18:1.4": "‘The teaching is well explained by the Buddha. But it’s for someone with good friends, companions, and associates, not for someone with bad friends, companions, and associates.’” ",
  "sn3.18:2.1": "“That’s so true, great king! That’s so true!” said the Buddha. And he repeated the king’s statement, adding: ",
  "sn3.18:2.2": "",
  "sn3.18:3.1": "“Great king, this one time I was staying in the land of the Sakyans where they have a town named Townsville. ",
  "sn3.18:3.2": "Then the mendicant Ānanda came to me, bowed, sat down to one side, and said: ",
  "sn3.18:3.3": "‘Sir, good friends, companions, and associates are half the spiritual life.’ ",
  "sn3.18:4.1": "When he had spoken, I said to him: ",
  "sn3.18:4.2": "‘Not so, Ānanda! Not so, Ānanda! ",
  "sn3.18:4.3": "Good friends, companions, and associates are the whole of the spiritual life. ",
  "sn3.18:4.4": "A mendicant with good friends, companions, and associates can expect to develop and cultivate the noble eightfold path. ",
  "sn3.18:5.1": "And how does a mendicant with good friends develop and cultivate the noble eightfold path? ",
  "sn3.18:5.2": "It’s when a mendicant develops right view, right purpose, right speech, right action, right livelihood, right effort, right mindfulness, and right immersion, which rely on seclusion, fading away, and cessation, and ripen as letting go. ",
  "sn3.18:5.3": "That’s how a mendicant with good friends develops and cultivates the noble eightfold path. ",
  "sn3.18:5.4": "And here’s another way to understand how good friends are the whole of the spiritual life. ",
  "sn3.18:6.1": "For, by relying on me as a good friend, sentient beings who are liable to rebirth, old age, and death, to sorrow, lamentation, pain, sadness, and distress are freed from all these things. ",
  "sn3.18:6.2": "This is another way to understand how good friends are the whole of the spiritual life.’ ",
  "sn3.18:7.1": "So, great king, you should train like this: ",
  "sn3.18:7.2": "‘I will have good friends, companions, and associates.’ ",
  "sn3.18:7.3": "That’s how you should train. ",
  "sn3.18:8.1": "When you have good friends, companions, and associates, you should live supported by one thing: ",
  "sn3.18:8.2": "diligence in skillful qualities. ",
  "sn3.18:9.1": "When you’re diligent, supported by diligence, your ladies of the harem, ",
  "sn3.18:9.2": "",
  "sn3.18:9.3": "",
  "sn3.18:10.1": "aristocrat vassals, ",
  "sn3.18:10.2": "",
  "sn3.18:10.3": "",
  "sn3.18:11.1": "troops, ",
  "sn3.18:11.2": "",
  "sn3.18:11.3": "",
  "sn3.18:12.1": "and people of town and country will think: ",
  "sn3.18:12.2": "‘The king lives diligently, supported by diligence. ",
  "sn3.18:12.3": "We’d better live diligently, supported by diligence!’ ",
  "sn3.18:13.1": "When you’re diligent, supported by diligence, then not only you yourself, ",
  "sn3.18:13.2": "but your ladies of the harem, and your treasury and storehouses will be guarded and protected.” ",
  "sn3.18:13.3": "That is what the Buddha said. … ",
  "sn3.18:14.1": "“For one who desires high wealth ",
  "sn3.18:14.2": "again and again, ",
  "sn3.18:14.3": "the astute praise diligence ",
  "sn3.18:14.4": "in making merit. ",
  "sn3.18:14.5": "Being diligent, an astute person ",
  "sn3.18:14.6": "secures both benefits: ",
  "sn3.18:15.1": "the benefit in this life, ",
  "sn3.18:15.2": "and in lives to come. ",
  "sn3.18:15.3": "Attentive, comprehending the meaning, ",
  "sn3.18:15.4": "they are said to be astute.” ",
  "sn3.19:0.1": "Linked Discourses 3.19 ",
  "sn3.19:0.2": "2. Childless ",
  "sn3.19:0.3": "Childless (1st) ",
  "sn3.19:1.1": "At Sāvatthī. ",
  "sn3.19:1.2": "Then King Pasenadi of Kosala went up to the Buddha in the middle of the day, bowed, and sat down to one side. The Buddha said to him, ",
  "sn3.19:1.3": "“So, great king, where are you coming from in the middle of the day?” ",
  "sn3.19:2.1": "“Sir, here in Sāvatthī a financier householder has passed away. ",
  "sn3.19:2.2": "Since he died childless, I have come after transferring his fortune to the royal compound. ",
  "sn3.19:2.3": "There was eight million in gold coin, not to mention the silver coin. ",
  "sn3.19:2.4": "And yet that financier ate meals of ",
  "sn3.19:2.5": "rough gruel with false black pepper. ",
  "sn3.19:2.6": "He wore clothes consisting of ",
  "sn3.19:2.7": "three patches of sunn hemp. ",
  "sn3.19:2.8": "He traveled around in a vehicle that was ",
  "sn3.19:2.9": "a dilapidated little cart, holding a leaf as parasol.” ",
  "sn3.19:3.1": "“That’s so true, great king! That’s so true! ",
  "sn3.19:3.2": "When an untrue person has acquired notable wealth they don’t make themselves happy and pleased. Nor do they make their mother and father, partners and children, bondservants, workers, and staff, and friends and colleagues happy and pleased. And they don’t establish an uplifting religious donation for ascetics and brahmins that’s conducive to heaven, ripens in happiness, and leads to heaven. ",
  "sn3.19:3.3": "Because they haven’t made proper use of that wealth, rulers or bandits take it, or fire consumes it, or flood sweeps it away, or unloved heirs take it. ",
  "sn3.19:3.4": "Since that wealth is not properly utilized, it’s wasted, not used. ",
  "sn3.19:4.1": "Suppose there was a lotus pond in an uninhabited region with clear, sweet, cool water, clean, with smooth banks, delightful. ",
  "sn3.19:4.2": "But people don’t collect it or drink it or bathe in it or use it for any purpose. ",
  "sn3.19:4.3": "Since that water is not properly utilized, it’s wasted, not used. ",
  "sn3.19:4.4": "In the same way, when an untrue person has acquired notable wealth … ",
  "sn3.19:4.5": "",
  "sn3.19:4.6": "it’s wasted, not used. ",
  "sn3.19:5.1": "When a true person has acquired notable wealth they make themselves happy and pleased. And they make their mother and father, partners and children, bondservants, workers, and staff, and friends and colleagues happy and pleased. And they establish an uplifting religious donation for ascetics and brahmins that’s conducive to heaven, ripens in happiness, and leads to heaven. ",
  "sn3.19:5.2": "Because they make proper use of that wealth, rulers or bandits don’t take it, fire doesn’t consume it, flood doesn’t sweep it away, and unloved heirs don’t take it. ",
  "sn3.19:5.3": "Since that wealth is properly utilized, it’s used, not wasted. ",
  "sn3.19:6.1": "Suppose there was a lotus pond not far from a town or village with clear, sweet, cool water, clean, with smooth banks, delightful. ",
  "sn3.19:6.2": "And people collected it and drank it and bathed in it and used it for their own purpose. ",
  "sn3.19:6.3": "Since that water is properly utilized, it’s used, not wasted. ",
  "sn3.19:6.4": "In the same way, when a true person has acquired notable wealth … ",
  "sn3.19:6.5": "",
  "sn3.19:6.6": "it’s used, not wasted. ",
  "sn3.19:7.1": "As cool water in an uninhabited region ",
  "sn3.19:7.2": "evaporates when not drunk; ",
  "sn3.19:7.3": "so too when a reprobate acquires wealth, ",
  "sn3.19:7.4": "they neither use it themselves nor give it away. ",
  "sn3.19:8.1": "When the attentive and sensible acquire wealth, ",
  "sn3.19:8.2": "they use it, being dutiful. ",
  "sn3.19:8.3": "That boss, having supported the family unit, ",
  "sn3.19:8.4": "blameless, goes to a heavenly place.” ",
  "sn3.20:0.1": "Linked Discourses 3.20 ",
  "sn3.20:0.2": "2. Childless ",
  "sn3.20:0.3": "Childless (2nd) ",
  "sn3.20:1.1": "Then King Pasenadi of Kosala went up to the Buddha in the middle of the day … The Buddha said to him, ",
  "sn3.20:1.2": "“So, great king, where are you coming from in the middle of the day?” ",
  "sn3.20:2.1": "“Sir, here in Sāvatthī a financier householder has passed away. ",
  "sn3.20:2.2": "Since he died childless, I have come after transferring his fortune to the royal compound. ",
  "sn3.20:2.3": "There was ten million in gold coin, not to mention the silver coin. ",
  "sn3.20:2.4": "And yet that financier ate meals of ",
  "sn3.20:2.5": "rough gruel with false black pepper. ",
  "sn3.20:2.6": "He wore clothes consisting of ",
  "sn3.20:2.7": "three patches of sunn hemp. ",
  "sn3.20:2.8": "He traveled around in a vehicle that was ",
  "sn3.20:2.9": "a dilapidated little cart, holding a leaf as parasol.” ",
  "sn3.20:3.1": "“That’s so true, great king! That’s so true! ",
  "sn3.20:3.2": "Once upon a time, great king, that financier householder provided almsfood on behalf of an Independent Buddha named Tagarasikhī. ",
  "sn3.20:3.3": "He instructed: ‘Give alms to that ascetic,’ before getting up from his seat and leaving. ",
  "sn3.20:3.4": "But after giving he regretted it: ",
  "sn3.20:3.5": "‘It would have been better to feed the bondservants or workers with that almsfood.’ ",
  "sn3.20:3.6": "What’s more, he murdered his brother’s only child for the sake of his fortune. ",
  "sn3.20:4.1": "Because that financier provided Tagarasikhī with almsfood, as a result of that deed he was reborn seven times in a good place, a heavenly realm. ",
  "sn3.20:4.2": "And as a residual result of that same deed he held the position of financier seven times right here in Sāvatthī. ",
  "sn3.20:4.3": "But because that financier regretted giving alms, ",
  "sn3.20:4.4": "as a result of that deed his mind didn’t tend to enjoy nice food, clothes, vehicles, or the five refined kinds of sensual stimulation. ",
  "sn3.20:4.5": "And because that financier murdered his brother’s only child for the sake of his fortune, as a result of that deed he burned in hell for many years, for many hundreds, many thousands, many hundreds of thousands of years. ",
  "sn3.20:4.6": "And as a residual result of that same deed, he is childless for the seventh time, his fortune ending up in the royal treasury. ",
  "sn3.20:4.7": "Now the old merit of that financier has been used up, and he hasn’t accumulated new merit. ",
  "sn3.20:4.8": "Today, great king, that financier burns in the Great Hell of Screams.” ",
  "sn3.20:4.9": "“Really, sir, that financier has been reborn in the Great Hell of Screams?” ",
  "sn3.20:4.10": "“Yes he has, great king.” ",
  "sn3.20:4.11": "That is what the Buddha said. … ",
  "sn3.20:5.1": "“Grain, money, silver, and gold, ",
  "sn3.20:5.2": "or whatever other possessions there are; ",
  "sn3.20:5.3": "bondservants, workers, servants, ",
  "sn3.20:5.4": "and those dependent for their livelihood: ",
  "sn3.20:6.1": "you must go on without taking these; ",
  "sn3.20:6.2": "all of them are left behind. ",
  "sn3.20:6.3": "But the deeds you do ",
  "sn3.20:6.4": "by body, speech, and mind",
  "sn3.20:7.1": "that’s what you can call your own. ",
  "sn3.20:7.2": "That’s what you take when you go. ",
  "sn3.20:7.3": "That’s what goes with you, ",
  "sn3.20:7.4": "like a shadow that never leaves. ",
  "sn3.20:8.1": "That’s why you should do good, ",
  "sn3.20:8.2": "investing in the future life. ",
  "sn3.20:8.3": "The good deeds of sentient beings ",
  "sn3.20:8.4": "support them in the next world.” ",
  "sn3.20:8.5": "",
  "sn3.20:9.1": "",
  "sn3.20:9.2": "",
  "sn3.20:9.3": "",
  "sn3.20:9.4": "",
  "sn3.20:9.5": "",
  "sn3.21:0.1": "Linked Discourses 3.21 ",
  "sn3.21:0.2": "3. Kosala ",
  "sn3.21:0.3": "Individuals ",
  "sn3.21:1.1": "At Sāvatthī. ",
  "sn3.21:1.2": "Then King Pasenadi of Kosala went up to the Buddha, bowed, and sat down to one side. The Buddha said to him: ",
  "sn3.21:1.3": "“Great king, these four individuals are found in the world. ",
  "sn3.21:1.4": "What four? ",
  "sn3.21:1.5": "The dark bound for darkness, ",
  "sn3.21:1.6": "the dark bound for light, ",
  "sn3.21:1.7": "the light bound for darkness, ",
  "sn3.21:1.8": "and the light bound for light. ",
  "sn3.21:2.1": "And how is an individual dark and bound for darkness? ",
  "sn3.21:2.2": "It’s when an individual is reborn in a low familya family of corpse-workers, bamboo-workers, hunters, chariot-makers, or scavengerspoor, with little to eat or drink, where life is tough, and food and shelter are hard to find. ",
  "sn3.21:2.3": "And they’re ugly, unsightly, deformed, sicklyone-eyed, crippled, lame, or half-paralyzed. They don’t get to have food, drink, clothes, and vehicles; garlands, fragrance, and makeup; or bed, house, and lighting. ",
  "sn3.21:2.4": "And they do bad things by way of body, speech, and mind. ",
  "sn3.21:2.5": "When their body breaks up, after death, they’re reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn3.21:3.1": "This individual is like someone who goes from darkness to darkness, from blackness to blackness, from bloodstain to bloodstain. ",
  "sn3.21:3.2": "",
  "sn3.21:3.3": "That’s how an individual is dark and bound for darkness. ",
  "sn3.21:4.1": "And how is an individual dark and bound for light? ",
  "sn3.21:4.2": "It’s when an individual is reborn in a low familya family of corpse-workers, bamboo-workers, hunters, chariot-makers, or scavengerspoor, with little to eat or drink, where life is tough, and food and shelter are hard to find. ",
  "sn3.21:4.3": "And they’re ugly, unsightly, deformed, sicklyone-eyed, crippled, lame, or half-paralyzed. They don’t get to have food, drink, clothes, and vehicles; garlands, fragrance, and makeup; or bed, house, and lighting. ",
  "sn3.21:4.4": "But they do good things by way of body, speech, and mind. ",
  "sn3.21:4.5": "When their body breaks up, after death, they’re reborn in a good place, a heavenly realm. ",
  "sn3.21:5.1": "This individual is like someone who ascends from the ground to a couch; from a couch to horseback; from horseback to an elephant; and from an elephant to a stilt longhouse. ",
  "sn3.21:5.2": "",
  "sn3.21:5.3": "That’s how an individual is dark and bound for light. ",
  "sn3.21:6.1": "And how is an individual light and bound for darkness? ",
  "sn3.21:6.2": "It’s when an individual is reborn in an eminent familya well-to-do family of aristocrats, brahmins, or householdersrich, affluent, and wealthy, with lots of gold and silver, lots of property and assets, and lots of money and grain. ",
  "sn3.21:6.3": "And they’re attractive, good-looking, lovely, of surpassing beauty. They get to have food, drink, clothes, and vehicles; garlands, fragrance, and makeup; and bed, house, and lighting. ",
  "sn3.21:6.4": "But they do bad things by way of body, speech, and mind. ",
  "sn3.21:6.5": "When their body breaks up, after death, they’re reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn3.21:7.1": "This individual is like someone who descends from a stilt longhouse to an elephant; from an elephant to horseback; from horseback to a couch; and from a couch to the ground; and from the ground they enter darkness. ",
  "sn3.21:7.2": "",
  "sn3.21:7.3": "That’s how an individual is light and bound for darkness. ",
  "sn3.21:8.1": "And how is an individual light and bound for light? ",
  "sn3.21:8.2": "It’s when an individual is reborn in an eminent familya well-to-do family of aristocrats, brahmins, or householdersrich, affluent, and wealthy, with lots of gold and silver, lots of property and assets, and lots of money and grain. ",
  "sn3.21:8.3": "And they’re attractive, good-looking, lovely, of surpassing beauty. They get to have food, drink, clothes, and vehicles; garlands, fragrance, and makeup; and bed, house, and lighting. ",
  "sn3.21:8.4": "And they do good things by way of body, speech, and mind. ",
  "sn3.21:8.5": "When their body breaks up, after death, they’re reborn in a good place, a heavenly realm. ",
  "sn3.21:9.1": "This individual is like someone who shifts from one couch to another; from the back of one horse to another; from one elephant to another; or from one stilt longhouse to another. ",
  "sn3.21:9.2": "",
  "sn3.21:9.3": "That’s how an individual is light and bound for light. ",
  "sn3.21:9.4": "These are the four individuals found in the world.” ",
  "sn3.21:9.5": "That is what the Buddha said. … ",
  "sn3.21:10.1": "“O king, some people are poor, ",
  "sn3.21:10.2": "faithless and stingy. ",
  "sn3.21:10.3": "Miserly, with bad intentions, ",
  "sn3.21:10.4": "they lack regard, they have wrong view. ",
  "sn3.21:11.1": "They abuse and insult ",
  "sn3.21:11.2": "ascetics and brahmins ",
  "sn3.21:11.3": "and other supplicants. ",
  "sn3.21:11.4": "They’re nihilists and bullies, ",
  "sn3.21:12.1": "who prevent others from giving ",
  "sn3.21:12.2": "food to beggars. ",
  "sn3.21:12.3": "O king, ruler of the people: ",
  "sn3.21:12.4": "when such people die ",
  "sn3.21:12.5": "they fall into the terrible hell",
  "sn3.21:12.6": "from darkness they’re bound for darkness. ",
  "sn3.21:13.1": "O king, some people are poor, ",
  "sn3.21:13.2": "but faithful and not stingy. ",
  "sn3.21:13.3": "They give with best of intentions, ",
  "sn3.21:13.4": "that peaceful-hearted person. ",
  "sn3.21:14.1": "They rise for and bow to ",
  "sn3.21:14.2": "ascetics and brahmins ",
  "sn3.21:14.3": "and other supplicants. ",
  "sn3.21:14.4": "Training in moral conduct, ",
  "sn3.21:15.1": "they don’t prevent others from giving ",
  "sn3.21:15.2": "food to beggars. ",
  "sn3.21:15.3": "O king, ruler of the people: ",
  "sn3.21:15.4": "when such people die ",
  "sn3.21:15.5": "they go to the Third Heaven",
  "sn3.21:15.6": "from darkness they’re bound for light. ",
  "sn3.21:16.1": "O king, some people are rich, ",
  "sn3.21:16.2": "but faithless and stingy. ",
  "sn3.21:16.3": "Miserly, with bad intentions, ",
  "sn3.21:16.4": "they lack regard, they have wrong view. ",
  "sn3.21:17.1": "They abuse and insult ",
  "sn3.21:17.2": "ascetics and brahmins ",
  "sn3.21:17.3": "and other supplicants ",
  "sn3.21:17.4": "They’re nihilists and bullies, ",
  "sn3.21:18.1": "who prevent others from giving ",
  "sn3.21:18.2": "food to beggars. ",
  "sn3.21:18.3": "O king, ruler of the people: ",
  "sn3.21:18.4": "when such people die ",
  "sn3.21:18.5": "they fall into the terrible hell",
  "sn3.21:18.6": "from light they’re bound for darkness. ",
  "sn3.21:19.1": "O king, some people are rich, ",
  "sn3.21:19.2": "faithful and not stingy. ",
  "sn3.21:19.3": "They give with best of intentions, ",
  "sn3.21:19.4": "that peaceful-hearted person. ",
  "sn3.21:20.1": "They rise for and bow to ",
  "sn3.21:20.2": "ascetics and brahmins ",
  "sn3.21:20.3": "and other supplicants. ",
  "sn3.21:20.4": "Training in moral conduct, ",
  "sn3.21:21.1": "they don’t prevent others from giving ",
  "sn3.21:21.2": "food to beggars. ",
  "sn3.21:21.3": "O king, ruler of the people: ",
  "sn3.21:21.4": "when such people die ",
  "sn3.21:21.5": "they go to the Third Heaven",
  "sn3.21:21.6": "from light they’re bound for light.” ",
  "sn3.22:0.1": "Linked Discourses 3.22 ",
  "sn3.22:0.2": "3. Kosala ",
  "sn3.22:0.3": "Grandmother ",
  "sn3.22:1.1": "At Sāvatthī. ",
  "sn3.22:1.2": "King Pasenadi of Kosala sat to one side, and the Buddha said to him, ",
  "sn3.22:1.3": "“So, great king, where are you coming from in the middle of the day?” ",
  "sn3.22:2.1": "“Sir, my grandmother has passed away. She was old, elderly and senior. She was advanced in years and had reached the final stage of life; she was a hundred and twenty years old. ",
  "sn3.22:2.2": "But I loved my grandmother; she was dear to me. ",
  "sn3.22:2.3": "If by giving away the elephant-treasure I could get my grandmother back, I’d do it. ",
  "sn3.22:2.4": "",
  "sn3.22:2.5": "If by giving away the horse-treasure I could get my grandmother back, I’d do it. ",
  "sn3.22:2.6": "",
  "sn3.22:2.7": "If by giving away a prize village I could get my grandmother back, I’d do it. ",
  "sn3.22:2.8": "",
  "sn3.22:2.9": "If by giving away the whole country I could get my grandmother back, I’d do it.” ",
  "sn3.22:2.10": "",
  "sn3.22:2.11": "“Great king, all sentient beings are liable to die. Death is their end; they’re not exempt from death.” ",
  "sn3.22:2.12": "“It’s incredible, sir, it’s amazing, ",
  "sn3.22:2.13": "how well said this was by the Buddha: ",
  "sn3.22:2.14": "‘All sentient beings are liable to die. Death is their end; they’re not exempt from death.’” ",
  "sn3.22:3.1": "“That’s so true, great king! That’s so true! ",
  "sn3.22:3.2": "All sentient beings are liable to die. Death is their end; they’re not exempt from death. ",
  "sn3.22:3.3": "It’s like the vessels made by potters. Whatever kind they are, whether baked or unbaked, all of them are liable to break apart. Breaking is their end; they’re not exempt from breakage. ",
  "sn3.22:3.4": "In the same way, all sentient beings are liable to die. Death is their end; they’re not exempt from death.” ",
  "sn3.22:3.5": "That is what the Buddha said. … ",
  "sn3.22:4.1": "“All beings will die, ",
  "sn3.22:4.2": "for life ends in death. ",
  "sn3.22:4.3": "They pass on according to their deeds, ",
  "sn3.22:4.4": "reaping the fruits of good and bad. ",
  "sn3.22:4.5": "Those who do bad go to hell, ",
  "sn3.22:4.6": "and if you do good you go to heaven. ",
  "sn3.22:5.1": "That’s why you should do good, ",
  "sn3.22:5.2": "investing in the future life. ",
  "sn3.22:5.3": "The good deeds of sentient beings ",
  "sn3.22:5.4": "support them in the next world.” ",
  "sn3.23:0.1": "Linked Discourses 3.23 ",
  "sn3.23:0.2": "3. Kosala ",
  "sn3.23:0.3": "The World ",
  "sn3.23:1.1": "At Sāvatthī. ",
  "sn3.23:1.2": "Seated to one side, King Pasenadi said to the Buddha, ",
  "sn3.23:1.3": "“Sir, how many things arise in the world for its harm, suffering, and discomfort?” ",
  "sn3.23:1.4": "“Great king, three things arise in the world for its harm, suffering, and discomfort. ",
  "sn3.23:1.5": "What three? ",
  "sn3.23:1.6": "Greed, ",
  "sn3.23:1.7": "hate, ",
  "sn3.23:1.8": "and delusion. ",
  "sn3.23:1.9": "These three things arise in the world for its harm, suffering, and discomfort.” ",
  "sn3.23:1.10": "That is what the Buddha said. … ",
  "sn3.23:2.1": "“When greed, hate, and delusion, ",
  "sn3.23:2.2": "originate inside oneself, ",
  "sn3.23:2.3": "they harm a person of wicked heart, ",
  "sn3.23:2.4": "as a bamboo is destroyed by its own fruit.” ",
  "sn3.24:0.1": "Linked Discourses 3.24 ",
  "sn3.24:0.2": "3. Kosala ",
  "sn3.24:0.3": "Archery ",
  "sn3.24:1.1": "At Sāvatthī. ",
  "sn3.24:1.2": "Seated to one side, King Pasenadi said to the Buddha, ",
  "sn3.24:1.3": "“Sir, where should a gift be given?” ",
  "sn3.24:1.4": "“Wherever your heart feels inspired, great king.” ",
  "sn3.24:1.5": "“But sir, where is a gift very fruitful?” ",
  "sn3.24:1.6": "“Where a gift should be given is one thing, great king, but where a gift is very fruitful is another. ",
  "sn3.24:1.7": "A gift is very fruitful when it’s given to an ethical person, not so much to an unethical person. ",
  "sn3.24:1.8": "Well then, great king, I’ll ask you about this in return, and you can answer as you like. ",
  "sn3.24:1.9": "What do you think, great king? ",
  "sn3.24:1.10": "Suppose you were at war, ready to fight a battle. ",
  "sn3.24:1.11": "Then along comes an aristocrat youth who is untrained, inexpert, unfit, inexperienced. And he’s fearful, scared, nervous, quick to flee. ",
  "sn3.24:1.12": "Would you employ such a man? Would he be of any use to you?” ",
  "sn3.24:1.13": "“No, sir, I would have no use for such a man.” ",
  "sn3.24:1.14": "“What about a brahmin youth, ",
  "sn3.24:1.15": "a peasant youth, ",
  "sn3.24:1.16": "or a menial youth who was similar?” ",
  "sn3.24:1.17": "“No, sir, I would have no use for such a man.” ",
  "sn3.24:2.1": "“What do you think, great king? ",
  "sn3.24:2.2": "Suppose you were at war, ready to fight a battle. ",
  "sn3.24:2.3": "Then along comes an aristocrat youth who is trained, expert, fit, experienced. And he’s fearless, brave, bold, standing his ground. ",
  "sn3.24:2.4": "Would you employ such a man? Would he be of any use to you?” ",
  "sn3.24:2.5": "“Yes, sir, I would have a use for such a man.” ",
  "sn3.24:2.6": "“What about a brahmin youth, ",
  "sn3.24:2.7": "a peasant youth, ",
  "sn3.24:2.8": "or a menial youth who was similar? ",
  "sn3.24:2.9": "Would you employ such a man? Would he be of any use to you?” ",
  "sn3.24:2.10": "“Yes, sir, I would have a use for such a man.” ",
  "sn3.24:3.1": "“In the same way, a gift to anyone who has given up five factors and possesses five factors is very fruitful, no matter what family they’ve gone forth from. ",
  "sn3.24:3.2": "What are the five factors they’ve given up? ",
  "sn3.24:3.3": "Sensual desire, ill will, dullness and drowsiness, restlessness and remorse, and doubt. ",
  "sn3.24:3.4": "These are the five factors they’ve given up. ",
  "sn3.24:3.5": "What are the five factors they possess? ",
  "sn3.24:3.6": "The entire spectrum of an adept’s ethics, immersion, wisdom, freedom, and knowledge and vision of freedom. ",
  "sn3.24:3.7": "These are the five factors they possess. ",
  "sn3.24:3.8": "I say that a gift to anyone who has given up these five factors and possesses these five factors is very fruitful.” ",
  "sn3.24:3.9": "That is what the Buddha said. ",
  "sn3.24:3.10": "Then the Holy One, the Teacher, went on to say: ",
  "sn3.24:4.1": "“Any youth skilled at archery, ",
  "sn3.24:4.2": "powerful and vigorous, ",
  "sn3.24:4.3": "would be employed by a king going to war",
  "sn3.24:4.4": "one is not a coward by reason of birth. ",
  "sn3.24:5.1": "Just so, whoever is settled ",
  "sn3.24:5.2": "in the qualities of patience and gentleness, ",
  "sn3.24:5.3": "a clever person with noble conduct, ",
  "sn3.24:5.4": "should be venerated even if they’re low born. ",
  "sn3.24:6.1": "You should build lovely hermitages ",
  "sn3.24:6.2": "and settle learned people in them. ",
  "sn3.24:6.3": "You should set up water supplies in barren regions ",
  "sn3.24:6.4": "and passages in places hard to travel. ",
  "sn3.24:7.1": "Food, drink, edibles, ",
  "sn3.24:7.2": "clothes, and lodgings ",
  "sn3.24:7.3": "should be given to the upright ones, ",
  "sn3.24:7.4": "with a clear and confident heart. ",
  "sn3.24:8.1": "The thundering rain cloud, ",
  "sn3.24:8.2": "its hundred peaks wreathed in lightning, ",
  "sn3.24:8.3": "pours down over the rich earth, ",
  "sn3.24:8.4": "soaking the uplands and valleys. ",
  "sn3.24:9.1": "So too an astute person, ",
  "sn3.24:9.2": "faithful and learned, ",
  "sn3.24:9.3": "should prepare a meal to satisfy ",
  "sn3.24:9.4": "supplicants with food and drink. ",
  "sn3.24:10.1": "Rejoicing, they strew gifts about, ",
  "sn3.24:10.2": "crying ‘Give! give!’ ",
  "sn3.24:10.3": "For that is their thunder, ",
  "sn3.24:10.4": "like rain sent from the heavens. ",
  "sn3.24:10.5": "That stream of merit so abundant ",
  "sn3.24:10.6": "showers down on the giver.” ",
  "sn3.25:0.1": "Linked Discourses 3.25 ",
  "sn3.25:0.2": "3. Kosala ",
  "sn3.25:0.3": "The Simile of the Mountain ",
  "sn3.25:1.1": "At Sāvatthī. ",
  "sn3.25:1.2": "King Pasenadi of Kosala sat to one side, and the Buddha said to him, ",
  "sn3.25:1.3": "“So, great king, where are you coming from in the middle of the day?” ",
  "sn3.25:1.4": "“Sir, there are anointed aristocratic kings who are infatuated with authority, and obsessed with greed for sensual pleasures. They have attained stability in the country, occupying a vast conquered territory. Today I have been busy fulfilling the duties of such kings.” ",
  "sn3.25:2.1": "“What do you think, great king? ",
  "sn3.25:2.2": "Suppose a trustworthy and dependable man were to come from the east. ",
  "sn3.25:2.3": "He’d approach you and say: ",
  "sn3.25:2.4": "‘Please great king, you should know this. I come from the east. ",
  "sn3.25:2.5": "There I saw a huge mountain that reached the clouds. And it was coming this way, crushing all creatures. ",
  "sn3.25:2.6": "So then, great king, do what you must!’ ",
  "sn3.25:2.7": "Then a second trustworthy and dependable man were to come from the west … ",
  "sn3.25:2.8": "a third from the north … ",
  "sn3.25:2.9": "and a fourth from the south. ",
  "sn3.25:2.10": "He’d approach you and say: ",
  "sn3.25:2.11": "‘Please great king, you should know this. I come from the south. ",
  "sn3.25:2.12": "There I saw a huge mountain that reached the clouds. And it was coming this way, crushing all creatures. ",
  "sn3.25:2.13": "So then, great king, do what you must!’ ",
  "sn3.25:2.14": "Should such a dire threat arisea grim loss of human life, when human birth is so rarewhat would you do?” ",
  "sn3.25:3.1": "“Sir, what could I do but practice the teachings, practice morality, doing skillful and good actions?” ",
  "sn3.25:4.1": "“I tell you, great king, I announce to you: old age and death are advancing upon you. ",
  "sn3.25:4.2": "Since old age and death are advancing upon you, what would you do?” ",
  "sn3.25:4.3": "“Sir, what can I do but practice the teachings, practice morality, doing skillful and good actions? ",
  "sn3.25:4.4": "Sir, there are anointed aristocratic kings who are infatuated with authority, and obsessed with greed for sensual pleasures. They have attained stability in the country, occupying a vast conquered territory. Such kings engage in battles of elephants, ",
  "sn3.25:4.5": "",
  "sn3.25:4.6": "",
  "sn3.25:4.7": "cavalry, ",
  "sn3.25:4.8": "chariots, ",
  "sn3.25:4.9": "or infantry. ",
  "sn3.25:4.10": "But there is no place, no domain for such battles when old age and death are advancing. ",
  "sn3.25:4.11": "In this royal court there are ministers of wise counsel who are capable of dividing an approaching enemy by wise counsel. ",
  "sn3.25:4.12": "But there is no place, no domain for such diplomatic battles when old age and death are advancing. ",
  "sn3.25:4.13": "In this royal court there is abundant gold, both coined and uncoined, stored above and below ground. Using this wealth we can bribe an approaching enemy. ",
  "sn3.25:4.14": "But there is no place, no domain for such monetary battles when old age and death are advancing. ",
  "sn3.25:4.15": "When old age and death are advancing, what can I do but practice the teachings, practice morality, doing skillful and good actions?” ",
  "sn3.25:5.1": "“That’s so true, great king! That’s so true! ",
  "sn3.25:5.2": "When old age and death are advancing, what can you do but practice the teachings, practice morality, doing skillful and good actions?” ",
  "sn3.25:5.3": "That is what the Buddha said. ",
  "sn3.25:5.4": "Then the Holy One, the Teacher, went on to say: ",
  "sn3.25:6.1": "“Suppose there were vast mountains ",
  "sn3.25:6.2": "of solid rock pressing against the sky ",
  "sn3.25:6.3": "drawing in from all sides ",
  "sn3.25:6.4": "and crushing the four quarters. ",
  "sn3.25:7.1": "So too old age and death ",
  "sn3.25:7.2": "advance upon all living creatures",
  "sn3.25:7.3": "aristocrats, brahmins, peasants, ",
  "sn3.25:7.4": "menials, corpse-workers, and scavengers. ",
  "sn3.25:7.5": "They spare nothing. ",
  "sn3.25:7.6": "They crush all beneath them. ",
  "sn3.25:8.1": "There’s nowhere for elephants to take a stand, ",
  "sn3.25:8.2": "nor chariots nor infantry. ",
  "sn3.25:8.3": "They can’t be defeated ",
  "sn3.25:8.4": "by diplomatic battles or by wealth. ",
  "sn3.25:9.1": "That’s why an astute person, ",
  "sn3.25:9.2": "seeing what’s good for themselves, ",
  "sn3.25:9.3": "being wise, would place faith ",
  "sn3.25:9.4": "in the Buddha, the teaching, and the Saṅgha. ",
  "sn3.25:10.1": "Whoever lives by the teaching ",
  "sn3.25:10.2": "in body, speech, and mind, ",
  "sn3.25:10.3": "is praised in this life ",
  "sn3.25:10.4": "and departs to rejoice in heaven.” ",
  "sn3.25:10.5": "",
  "sn3.25:11.1": "",
  "sn3.25:11.2": "",
  "sn3.25:11.3": "",
  "sn3.25:11.4": "",
  "sn3.25:11.5": "The Linked Discourses with the Kosalan are completed. "
}
window.BILARA["sn3_v1"]["en"]["sn3_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
