window.BILARA = window.BILARA || {};
window.BILARA["sn44_v1"] = window.BILARA["sn44_v1"] || {};
window.BILARA["sn44_v1"]["en"] = {
  "sn44.1:0.1": "Linked Discourses 44.1 ",
  "sn44.1:0.2": "1. The Undeclared Points ",
  "sn44.1:0.3": "With Khemā ",
  "sn44.1:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn44.1:1.2": "Now at that time the nun Khemā was wandering in the land of the Kosalans between Sāvatthī and Sāketa when she took up residence in Toraṇavatthu. ",
  "sn44.1:1.3": "Then King Pasenadi was traveling from Sāketa to Sāvatthī, and he too stayed in Toraṇavatthu for a single night. ",
  "sn44.1:1.4": "Then King Pasenadi addressed a man, ",
  "sn44.1:1.5": "“Please, my friend, check if there’s a suitable (male) ascetic or brahmin in Toraṇavatthu to whom I can pay homage.” ",
  "sn44.1:2.1": "“Yes, Your Majesty,” replied that man. He searched all over Toraṇavatthu, but he couldn’t see a suitable ascetic or brahmin for the king to pay homage to. ",
  "sn44.1:2.2": "But he saw that the nun Khemā was staying there, ",
  "sn44.1:2.3": "so he went to the king and said to him, ",
  "sn44.1:3.1": "“Your Majesty, there’s no (male) ascetic or brahmin in Toraṇavatthu for the king to pay homage to. ",
  "sn44.1:3.2": "But there is the nun Khemā, who’s a disciple of the Blessed One, the perfected one, the fully awakened Buddha. ",
  "sn44.1:3.3": "She has a good reputation as being ",
  "sn44.1:3.4": "astute, competent, clever, learned, a brilliant speaker, and eloquent. ",
  "sn44.1:3.5": "Your Majesty may pay homage to her.” ",
  "sn44.1:4.1": "Then King Pasenadi of Kosala went up to the nun Khemā, bowed, sat down to one side, and said to her: ",
  "sn44.1:4.2": "“Ma’am, does a realized one still exist after death?” ",
  "sn44.1:4.3": "“Great king, this has not been declared by the Buddha.” ",
  "sn44.1:4.4": "",
  "sn44.1:4.5": "“Well then, does a realized one no longer exist after death?” ",
  "sn44.1:4.6": "“This too has not been declared by the Buddha.” ",
  "sn44.1:4.7": "",
  "sn44.1:4.8": "“Well then, does a realized one both exist and not exist after death?” ",
  "sn44.1:4.9": "“This has not been declared by the Buddha.” ",
  "sn44.1:4.10": "",
  "sn44.1:4.11": "“Well then, does a realized one neither exist nor not exist after death?” ",
  "sn44.1:4.12": "“This too has not been declared by the Buddha.” ",
  "sn44.1:4.13": "",
  "sn44.1:5.1": "“Ma’am, when asked these questions, you say ",
  "sn44.1:5.2": "that this has not been declared by the Buddha. ",
  "sn44.1:5.3": "",
  "sn44.1:5.4": "",
  "sn44.1:5.5": "",
  "sn44.1:5.6": "",
  "sn44.1:5.7": "",
  "sn44.1:5.8": "",
  "sn44.1:5.9": "",
  "sn44.1:5.10": "",
  "sn44.1:5.11": "",
  "sn44.1:5.12": "",
  "sn44.1:5.13": "What’s the cause, what’s the reason why this has not been declared by the Buddha?” ",
  "sn44.1:6.1": "“Well then, great king, I’ll ask you about this in return, and you can answer as you like. ",
  "sn44.1:6.2": "What do you think, great king? ",
  "sn44.1:6.3": "Do you have any accountant or finger-tallier or reckoner who can count the grains of sand in the Ganges, that is, ",
  "sn44.1:6.4": "how many grains of sand there are, how many hundreds or thousands or hundreds of thousands of grains of sand?” ",
  "sn44.1:6.5": "“No, ma’am.” ",
  "sn44.1:6.6": "“Do you have any accountant or finger-tallier or reckoner who can count the water in the ocean, that is, ",
  "sn44.1:6.7": "how many gallons of water there are, how many hundreds or thousands or hundreds of thousands of gallons of water?” ",
  "sn44.1:6.8": "“No, ma’am. ",
  "sn44.1:6.9": "Why is that? ",
  "sn44.1:6.10": "Because the ocean is deep, immeasurable, and hard to fathom.” ",
  "sn44.1:6.11": "“In the same way, great king, any form by which a realized one might be described has been cut off at the root, made like a palm stump, obliterated, and unable to arise in the future. ",
  "sn44.1:6.12": "A realized one is freed from reckoning in terms of form. They’re deep, immeasurable, and hard to fathom, ",
  "sn44.1:6.13": "like the ocean. ",
  "sn44.1:6.14": "To say that after death, a realized one still exists, or no longer exists, or both still exists and no longer exists, or neither still exists nor no longer exists: none of these apply. ",
  "sn44.1:7.1": "Any feeling … ",
  "sn44.1:7.2": "",
  "sn44.1:7.3": "",
  "sn44.1:7.4": "",
  "sn44.1:8.1": "perception … ",
  "sn44.1:8.2": "choices … ",
  "sn44.1:8.3": "",
  "sn44.1:8.4": "",
  "sn44.1:8.5": "",
  "sn44.1:9.1": "consciousness by which a realized one might be described has been cut off at the root, made like a palm stump, obliterated, and unable to arise in the future. ",
  "sn44.1:9.2": "A realized one is freed from reckoning in terms of consciousness. They’re deep, immeasurable, and hard to fathom, ",
  "sn44.1:9.3": "like the ocean. ",
  "sn44.1:9.4": "To say that after death, a realized one still exists, or no longer exists, or both still exists and no longer exists, or neither still exists nor no longer exists: none of these apply.” ",
  "sn44.1:9.5": "Then King Pasenadi approved and agreed with what the nun Khemā said. Then he got up from his seat, bowed, and respectfully circled her, keeping her on his right, before leaving. ",
  "sn44.1:10.1": "Then on a later occasion King Pasenadi of Kosala went up to the Buddha, bowed, and sat down to one side. He asked the Buddha exactly the same questions he had asked the nun Khemā, and received the same answers. ",
  "sn44.1:10.2": "",
  "sn44.1:10.3": "",
  "sn44.1:10.4": "",
  "sn44.1:10.5": "",
  "sn44.1:10.6": "",
  "sn44.1:10.7": "",
  "sn44.1:10.8": "",
  "sn44.1:10.9": "",
  "sn44.1:10.10": "",
  "sn44.1:10.11": "",
  "sn44.1:10.12": "",
  "sn44.1:10.13": "",
  "sn44.1:10.14": "",
  "sn44.1:10.15": "",
  "sn44.1:10.16": "",
  "sn44.1:10.17": "",
  "sn44.1:10.18": "",
  "sn44.1:10.19": "",
  "sn44.1:11.1": "",
  "sn44.1:11.2": "",
  "sn44.1:11.3": "",
  "sn44.1:11.4": "",
  "sn44.1:11.5": "",
  "sn44.1:11.6": "",
  "sn44.1:11.7": "",
  "sn44.1:11.8": "",
  "sn44.1:11.9": "",
  "sn44.1:11.10": "",
  "sn44.1:11.11": "",
  "sn44.1:11.12": "",
  "sn44.1:11.13": "",
  "sn44.1:11.14": "",
  "sn44.1:11.15": "",
  "sn44.1:11.16": "",
  "sn44.1:12.1": "",
  "sn44.1:12.2": "",
  "sn44.1:12.3": "",
  "sn44.1:12.4": "",
  "sn44.1:13.1": "He said, “It’s incredible, sir, it’s amazing! ",
  "sn44.1:13.2": "How the meaning and the phrasing of the teacher and the disciple fit together and agree without contradiction when it comes to the chief matter! ",
  "sn44.1:13.3": "This one time I went to the nun Khemā and asked her about this matter. ",
  "sn44.1:13.4": "And she explained it to me with these words and phrases, just like the Buddha. ",
  "sn44.1:13.5": "It’s incredible, sir, it’s amazing! ",
  "sn44.1:13.6": "How the meaning and the phrasing of the teacher and the disciple fit together and agree without contradiction when it comes to the chief matter! ",
  "sn44.1:13.7": "Well, now, sir, I must go. ",
  "sn44.1:13.8": "I have many duties, and much to do.” ",
  "sn44.1:13.9": "“Please, great king, go at your convenience.” ",
  "sn44.1:13.10": "Then King Pasenadi approved and agreed with what the Buddha said. Then he got up from his seat, bowed, and respectfully circled him, keeping him on his right, before leaving. ",
  "sn44.2:0.1": "Linked Discourses 44.2 ",
  "sn44.2:0.2": "1. The Undeclared Points ",
  "sn44.2:0.3": "With Anurādha ",
  "sn44.2:1.1": "At one time the Buddha was staying near Vesālī, at the Great Wood, in the hall with the peaked roof. ",
  "sn44.2:1.2": "Now at that time Venerable Anurādha was staying not far from the Buddha in a wilderness hut. ",
  "sn44.2:1.3": "Then several wanderers of other religions went up to Venerable Anurādha and exchanged greetings with him. ",
  "sn44.2:1.4": "When the greetings and polite conversation were over, they sat down to one side and said to him: ",
  "sn44.2:1.5": "“Reverend Anurādha, when a realized one is describing a realized onea supreme person, highest of people, who has reached the highest pointthey describe them in these four ways: ",
  "sn44.2:1.6": "After death, a realized one still exists, or no longer exists, or both still exists and no longer exists, or neither still exists nor no longer exists.” ",
  "sn44.2:1.7": "“Reverends, when a realized one is describing a realized onea supreme person, highest of people, who has reached the highest pointthey describe them other than these four ways: ",
  "sn44.2:1.8": "After death, a realized one still exists, or no longer exists, or both still exists and no longer exists, or neither still exists nor no longer exists.” ",
  "sn44.2:1.9": "When he said this, the wanderers said to him, ",
  "sn44.2:1.10": "“This mendicant must be junior, recently gone forth, or else a foolish, incompetent senior mendicant.” ",
  "sn44.2:1.11": "Then, after rebuking Venerable Anurādha by calling him “junior” and “foolish”, the wanderers got up from their seat and left. ",
  "sn44.2:2.1": "Soon after they had left, Anurādha thought, ",
  "sn44.2:2.2": "“If those wanderers were to inquire further, ",
  "sn44.2:2.3": "how should I answer them so as to repeat what the Buddha has said, and not misrepresent him with an untruth? How should I explain in line with his teaching, so that there would be no legitimate grounds for rebuttal and criticism?” ",
  "sn44.2:2.4": "Then Venerable Anurādha went up to the Buddha, bowed, sat down to one side, and told him what had happened. ",
  "sn44.2:2.5": "",
  "sn44.2:2.6": "",
  "sn44.2:2.7": "",
  "sn44.2:2.8": "",
  "sn44.2:2.9": "",
  "sn44.2:2.10": "",
  "sn44.2:2.11": "",
  "sn44.2:2.12": "",
  "sn44.2:2.13": "",
  "sn44.2:2.14": "",
  "sn44.2:2.15": "",
  "sn44.2:2.16": "",
  "sn44.2:2.17": "",
  "sn44.2:2.18": "",
  "sn44.2:2.19": "",
  "sn44.2:3.1": "“What do you think, Anurādha? ",
  "sn44.2:3.2": "Is form permanent or impermanent?” ",
  "sn44.2:4.1": "“Impermanent, sir.” ",
  "sn44.2:5.1": "“But if it’s impermanent, is it suffering or happiness?” ",
  "sn44.2:6.1": "“Suffering, sir.” ",
  "sn44.2:7.1": "“But if it’s impermanent, suffering, and perishable, is it fit to be regarded thus: ",
  "sn44.2:7.2": "‘This is mine, I am this, this is my self’?” ",
  "sn44.2:8.1": "“No, sir.” ",
  "sn44.2:9.1": "“Is feeling … ",
  "sn44.2:9.2": "",
  "sn44.2:9.3": "perception … ",
  "sn44.2:9.4": "choices … ",
  "sn44.2:9.5": "consciousness permanent or impermanent?” ",
  "sn44.2:10.1": "“Impermanent, sir.” ",
  "sn44.2:11.1": "“But if it’s impermanent, is it suffering or happiness?” ",
  "sn44.2:12.1": "“Suffering, sir.” ",
  "sn44.2:13.1": "“But if it’s impermanent, suffering, and perishable, is it fit to be regarded thus: ",
  "sn44.2:13.2": "‘This is mine, I am this, this is my self’?” ",
  "sn44.2:14.1": "“No, sir.” ",
  "sn44.2:15.1": "“So, Anurādha, you should truly see any kind of form at allpast, future, or present; internal or external; solid or subtle; inferior or superior; far or near: *all* formwith right understanding: ‘This is not mine, I am not this, this is not my self.’ ",
  "sn44.2:15.2": "Any kind of feeling … ",
  "sn44.2:15.3": "perception … ",
  "sn44.2:15.4": "choices … ",
  "sn44.2:15.5": "consciousness at allpast, future, or present; internal or external; solid or subtle; inferior or superior; far or near: *all* consciousnesswith right understanding: ‘This is not mine, I am not this, this is not my self.’ ",
  "sn44.2:15.6": "Seeing this, a learned noble disciple grows disillusioned with form, feeling, perception, choices, and consciousness. ",
  "sn44.2:15.7": "Being disillusioned, desire fades away. When desire fades away they’re freed. When they’re freed, they know they’re freed. ",
  "sn44.2:15.8": "They understand: ‘Rebirth is ended, the spiritual journey has been completed, what had to be done has been done, there is nothing further for this place.’ ",
  "sn44.2:16.1": "What do you think, Anurādha? ",
  "sn44.2:16.2": "Do you consider that the label ‘realized one’ applies to form?” ",
  "sn44.2:16.3": "“No, sir.” ",
  "sn44.2:16.4": "“Do you consider that the label ‘realized one’ applies to feeling?” … ",
  "sn44.2:16.5": "",
  "sn44.2:16.6": "“… perception?” … ",
  "sn44.2:16.7": "",
  "sn44.2:16.8": "“… choices?” … ",
  "sn44.2:16.9": "",
  "sn44.2:16.10": "“… consciousness?” ",
  "sn44.2:16.11": "“No, sir.” ",
  "sn44.2:16.12": "“What do you think, Anurādha? ",
  "sn44.2:16.13": "Do you consider that the label ‘realized one’ applies in relation to form?” ",
  "sn44.2:16.14": "“No, sir.” ",
  "sn44.2:16.15": "“Do you consider that the label ‘realized one’ applies apart from form?” ",
  "sn44.2:16.16": "“No, sir.” ",
  "sn44.2:16.17": "“Do you consider that the label ‘realized one’ applies in relation to feeling?” ",
  "sn44.2:16.18": "“… apart from feeling?” … ",
  "sn44.2:16.19": "“… in relation to perception?” … ",
  "sn44.2:16.20": "“… apart from perception?” … ",
  "sn44.2:16.21": "“… in relation to choices?” … ",
  "sn44.2:16.22": "“… apart from choices?” … ",
  "sn44.2:16.23": "“… in relation to consciousness?” … ",
  "sn44.2:16.24": "",
  "sn44.2:16.25": "“… apart from consciousness?” ",
  "sn44.2:16.26": "“No, sir.” ",
  "sn44.2:17.1": "“What do you think, Anurādha? ",
  "sn44.2:17.2": "Do you consider that the label ‘realized one’ applies to one who has form?” … “… feeling?” … “… perception?” … “… choices?” … “… consciousness?” ",
  "sn44.2:17.3": "“No, sir.” ",
  "sn44.2:17.4": "“What do you think, Anurādha? ",
  "sn44.2:17.5": "Do you consider that the label ‘realized one’ applies to that one who is without form?” … “… feeling?” … “… perception?” … “… choices?” … “… consciousness?” ",
  "sn44.2:17.6": "“No, sir.” ",
  "sn44.2:17.7": "“In that case, Anurādha, since a realized one is not found by you as a genuine fact in this very life, is it cogent for you to declare: ",
  "sn44.2:17.8": "‘Reverends, when a realized one is describing a realized onea supreme person, highest of people, who has reached the highest pointthey describe them other than these four ways: ",
  "sn44.2:17.9": "After death, a realized one still exists, or no longer exists, or both still exists and no longer exists, or neither still exists nor no longer exists’?” ",
  "sn44.2:17.10": "",
  "sn44.2:17.11": "“No, sir.” ",
  "sn44.2:17.12": "“Good, good, Anurādha! ",
  "sn44.2:17.13": "In the past, as today, what I describe is suffering and the cessation of suffering.” ",
  "sn44.3:0.1": "Linked Discourses 44.3 ",
  "sn44.3:0.2": "1. The Undeclared Points ",
  "sn44.3:0.3": "With Sāriputta and Koṭṭhita (1st) ",
  "sn44.3:1.1": "At one time Venerable Sāriputta and Venerable Mahākoṭṭhita were staying near Varanasi, in the deer park at Isipatana. ",
  "sn44.3:1.2": "Then in the late afternoon, Venerable Mahākoṭṭhita came out of retreat, went to Venerable Sāriputta, and exchanged greetings with him. ",
  "sn44.3:1.3": "When the greetings and polite conversation were over, he sat down to one side, and said to Sāriputta: ",
  "sn44.3:2.1": "“Reverend Sāriputta, does a realized one still exist after death?” ",
  "sn44.3:2.2": "“Reverend, this has not been declared by the Buddha.” ",
  "sn44.3:2.3": "",
  "sn44.3:2.4": "“Well then, does a realized one no longer exist after death? … ",
  "sn44.3:2.5": "",
  "sn44.3:2.6": "",
  "sn44.3:2.7": "Does a realized one both exist and not exist after death? … ",
  "sn44.3:2.8": "",
  "sn44.3:2.9": "",
  "sn44.3:2.10": "Does a realized one neither exist nor not exist after death?” ",
  "sn44.3:2.11": "“This too has not been declared by the Buddha.” ",
  "sn44.3:2.12": "",
  "sn44.3:3.1": "“Reverend, when asked these questions, you say that they have not been declared by the Buddha. ",
  "sn44.3:3.2": "",
  "sn44.3:3.3": "",
  "sn44.3:3.4": "",
  "sn44.3:3.5": "",
  "sn44.3:3.6": "What’s the cause, what’s the reason why they have not been declared by the Buddha?” ",
  "sn44.3:4.1": "“Reverend, ‘does a realized one still exist after death?’ is included in form. ",
  "sn44.3:4.2": "‘Does a realized one no longer exist after death?’ is included in form. ",
  "sn44.3:4.3": "‘Does a realized one both still exist and no longer exist after death?’ is included in form. ",
  "sn44.3:4.4": "‘Does a realized one neither still exist nor no longer exist after death?’ is included in form. ",
  "sn44.3:4.5": "‘does a realized one still exist after death?’ is included in feeling … ",
  "sn44.3:4.6": "",
  "sn44.3:4.7": "",
  "sn44.3:4.8": "",
  "sn44.3:4.9": "perception … ",
  "sn44.3:4.10": "",
  "sn44.3:4.11": "",
  "sn44.3:4.12": "",
  "sn44.3:4.13": "choices … ",
  "sn44.3:4.14": "",
  "sn44.3:4.15": "",
  "sn44.3:4.16": "",
  "sn44.3:4.17": "consciousness. ",
  "sn44.3:4.18": "‘Does a realized one no longer exist after death?’ is included in consciousness. ",
  "sn44.3:4.19": "‘Does a realized one both still exist and no longer exist after death?’ is included in consciousness. ",
  "sn44.3:4.20": "‘Does a realized one neither still exist nor no longer exist after death?’ is included in consciousness. ",
  "sn44.3:4.21": "This is the cause, this is the reason why this has not been declared by the Buddha.” ",
  "sn44.4:0.1": "Linked Discourses 44.4 ",
  "sn44.4:0.2": "1. The Undeclared Points ",
  "sn44.4:0.3": "With Sāriputta and Koṭṭhita (2nd) ",
  "sn44.4:1.1": "At one time Venerable Sāriputta and Venerable Mahākoṭṭhita were staying near Varanasi, in the deer park at Isipatana. … ",
  "sn44.4:1.2": "(The same down as far as:) ",
  "sn44.4:1.3": "“What’s the cause, reverend, what’s the reason why this has not been declared by the Buddha?” ",
  "sn44.4:1.4": "“Reverend, not truly knowing and seeing form, its origin, its cessation, and the practice that leads to its cessation, one thinks ‘a realized one still exists after death’ or ",
  "sn44.4:1.5": "‘A realized one no longer exists after death’ or ",
  "sn44.4:1.6": "‘a realized one both still exists and no longer exists after death’ or ",
  "sn44.4:1.7": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.4:1.8": "Not truly knowing or seeing feeling … ",
  "sn44.4:1.9": "perception … ",
  "sn44.4:1.10": "choices … ",
  "sn44.4:1.11": "consciousness, its origin, its cessation, and the practice that leads to its cessation, one thinks ‘a realized one still exists after death’ or ",
  "sn44.4:1.12": "‘A realized one no longer exists after death’ or ",
  "sn44.4:1.13": "‘a realized one both still exists and no longer exists after death’ or ",
  "sn44.4:1.14": "‘A realized one neither still exists nor no longer exists after death.’ ",
  "sn44.4:2.1": "Truly knowing and seeing form … ",
  "sn44.4:2.2": "",
  "sn44.4:2.3": "feeling … ",
  "sn44.4:2.4": "perception … ",
  "sn44.4:2.5": "choices … ",
  "sn44.4:2.6": "consciousness, its origin, its cessation, and the practice that leads to its cessation, one doesn’t think ‘a realized one still exists after death’ or ",
  "sn44.4:2.7": "‘A realized one no longer exists after death’ or ",
  "sn44.4:2.8": "‘a realized one both still exists and no longer exists after death’ or ",
  "sn44.4:2.9": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.4:2.10": "This is the cause, this is the reason why this has not been declared by the Buddha.” ",
  "sn44.5:0.1": "Linked Discourses 44.5 ",
  "sn44.5:0.2": "1. The Undeclared Points ",
  "sn44.5:0.3": "With Sāriputta and Koṭṭhita (3rd) ",
  "sn44.5:1.1": "At one time Venerable Sāriputta and Venerable Mahākoṭṭhita were staying near Varanasi, in the deer park at Isipatana. … ",
  "sn44.5:1.2": "(The same down as far as:) ",
  "sn44.5:1.3": "“What’s the cause, reverend, what’s the reason why this has not been declared by the Buddha?” ",
  "sn44.5:1.4": "“Reverend, if you’re not rid of greed, desire, fondness, thirst, passion, and craving for form … ",
  "sn44.5:1.5": "",
  "sn44.5:1.6": "feeling … ",
  "sn44.5:1.7": "perception … ",
  "sn44.5:1.8": "choices … ",
  "sn44.5:1.9": "consciousness, you think ‘a realized one still exists after death’ … ",
  "sn44.5:1.10": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.5:1.11": "If you are rid of greed for form … ",
  "sn44.5:1.12": "feeling … ",
  "sn44.5:1.13": "perception … ",
  "sn44.5:1.14": "choices … ",
  "sn44.5:1.15": "consciousness, you don’t think ‘a realized one still exists after death’ … ",
  "sn44.5:1.16": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.5:1.17": "This is the cause, this is the reason why this has not been declared by the Buddha.” ",
  "sn44.6:0.1": "Linked Discourses 44.6 ",
  "sn44.6:0.2": "1. The Undeclared Points ",
  "sn44.6:0.3": "With Sāriputta and Koṭṭhita (4th) ",
  "sn44.6:1.1": "At one time Venerable Sāriputta and Venerable Mahākoṭṭhita were staying near Varanasi, in the deer park at Isipatana. ",
  "sn44.6:1.2": "Then in the late afternoon, Venerable Sāriputta came out of retreat, went to Venerable Mahākoṭṭhita, and they greeted each other. ",
  "sn44.6:1.3": "When the greetings and polite conversation were over, he sat down to one side and said to Mahākoṭṭhita: ",
  "sn44.6:1.4": "“Reverend Koṭṭhita, does a realized one still exist after death?” … ",
  "sn44.6:1.5": "“Reverend, when asked these questions, you say that this has not been declared by the Buddha. ",
  "sn44.6:1.6": "",
  "sn44.6:1.7": "",
  "sn44.6:1.8": "What’s the cause, what’s the reason why this has not been declared by the Buddha?” ",
  "sn44.6:2.1": "“Reverend, if you like, love, and enjoy form, and don’t truly see the cessation of form, you think ‘a realized one still exists after death’ or ",
  "sn44.6:2.2": "‘A realized one no longer exists after death’ or ",
  "sn44.6:2.3": "‘a realized one both still exists and no longer exists after death’ or ",
  "sn44.6:2.4": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.6:2.5": "If you like, love, and enjoy feeling … ",
  "sn44.6:2.6": "perception … ",
  "sn44.6:2.7": "choices … ",
  "sn44.6:2.8": "consciousness, and don’t truly see the cessation of consciousness, you think ‘a realized one still exists after death’ … ",
  "sn44.6:2.9": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.6:3.1": "If you don’t like, love, and enjoy form … ",
  "sn44.6:3.2": "",
  "sn44.6:3.3": "feeling … ",
  "sn44.6:3.4": "perception … ",
  "sn44.6:3.5": "choices … ",
  "sn44.6:3.6": "consciousness, and you truly see the cessation of consciousness, you don’t think ‘a realized one still exists after death’ … ",
  "sn44.6:3.7": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.6:3.8": "This is the cause, this is the reason why this has not been declared by the Buddha.” ",
  "sn44.6:4.1": "“But reverend, could there be another way of explaining why this was not declared by the Buddha?” ",
  "sn44.6:4.2": "“There could, reverend. ",
  "sn44.6:4.3": "If you like, love, and enjoy existence, and don’t truly see the cessation of continued existence, you think ‘a realized one still exists after death’ … ",
  "sn44.6:4.4": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.6:4.5": "If you don’t like, love, and enjoy existence, and you truly see the cessation of continued existence, you don’t think ‘a realized one still exists after death’ … ",
  "sn44.6:4.6": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.6:4.7": "This too is a way of explaining why this was not declared by the Buddha.” ",
  "sn44.6:5.1": "“But reverend, could there be another way of explaining why this was not declared by the Buddha?” ",
  "sn44.6:5.2": "“There could, reverend. ",
  "sn44.6:5.3": "If you like, love, and enjoy grasping, and don’t truly see the cessation of grasping, you think ‘a realized one still exists after death’ … ",
  "sn44.6:5.4": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.6:5.5": "If you don’t like, love, and enjoy grasping, and you truly see the cessation of grasping, you don’t think ‘a realized one still exists after death’ … ",
  "sn44.6:5.6": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.6:5.7": "This too is a way of explaining why this was not declared by the Buddha.” ",
  "sn44.6:6.1": "“But reverend, could there be another way of explaining why this was not declared by the Buddha?” ",
  "sn44.6:6.2": "“There could, reverend. ",
  "sn44.6:6.3": "If you like, love, and enjoy craving, and don’t truly see the cessation of craving, you think ‘a realized one still exists after death’ … ",
  "sn44.6:6.4": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.6:6.5": "If you don’t like, love, and enjoy craving, and you truly see the cessation of craving, you don’t think ‘a realized one still exists after death’ … ",
  "sn44.6:6.6": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn44.6:6.7": "This too is a way of explaining why this was not declared by the Buddha.” ",
  "sn44.6:7.1": "“But reverend, could there be another way of explaining why this was not declared by the Buddha?” ",
  "sn44.6:7.2": "“Seriously, reverend, what more could you want? ",
  "sn44.6:7.3": "For one who is freed due to the ending of craving, there is no cycle of rebirths to be found.” ",
  "sn44.7:0.1": "Linked Discourses 44.7 ",
  "sn44.7:0.2": "1. The Undeclared Points ",
  "sn44.7:0.3": "With Moggallāna ",
  "sn44.7:1.1": "Then the wanderer Vacchagotta went up to Venerable Mahāmoggallāna, and exchanged greetings with him. ",
  "sn44.7:1.2": "When the greetings and polite conversation were over, he sat down to one side, and said to Mahāmoggallāna: ",
  "sn44.7:2.1": "“Worthy Moggallāna, is this right: ‘the cosmos is eternal’?” ",
  "sn44.7:2.2": "“Vaccha, this has not been declared by the Buddha.” ",
  "sn44.7:2.3": "",
  "sn44.7:2.4": "“Then is this right: ‘the cosmos is not eternal’ … ",
  "sn44.7:2.5": "",
  "sn44.7:2.6": "",
  "sn44.7:2.7": "‘the cosmos is finite’ … ",
  "sn44.7:2.8": "",
  "sn44.7:2.9": "",
  "sn44.7:2.10": "‘the cosmos is infinite’ … ",
  "sn44.7:2.11": "",
  "sn44.7:2.12": "",
  "sn44.7:2.13": "‘the soul and the body are one and the same’ … ",
  "sn44.7:2.14": "",
  "sn44.7:2.15": "",
  "sn44.7:2.16": "‘the soul is one thing, the body another’ … ",
  "sn44.7:2.17": "",
  "sn44.7:2.18": "",
  "sn44.7:2.19": "‘a realized one still exists after death’ … ",
  "sn44.7:2.20": "",
  "sn44.7:2.21": "",
  "sn44.7:2.22": "‘a realized one no longer exists after death’ … ",
  "sn44.7:2.23": "",
  "sn44.7:2.24": "",
  "sn44.7:2.25": "‘a realized one both still exists and no longer exists after death’ … ",
  "sn44.7:2.26": "",
  "sn44.7:2.27": "",
  "sn44.7:2.28": "‘a realized one neither still exists nor no longer exists after death’?” ",
  "sn44.7:2.29": "“This too has not been declared by the Buddha.” ",
  "sn44.7:2.30": "",
  "sn44.7:3.1": "“What’s the cause, worthy Moggallāna, what’s the reason why, when the wanderers of other religions are asked these questions, they declare one of these to be true? ",
  "sn44.7:3.2": "",
  "sn44.7:3.3": "And what’s the reason why, when the ascetic Gotama is asked these questions, he does not declare one of these to be true?” ",
  "sn44.7:3.4": "",
  "sn44.7:4.1": "“Vaccha, the wanderers of other religions regard the eye like this: ‘This is mine, I am this, this is my self.’ They regard the ear … nose … ",
  "sn44.7:4.2": "tongue … body … ",
  "sn44.7:4.3": "mind like this: ‘This is mine, I am this, this is my self.’ ",
  "sn44.7:4.4": "That’s why, when asked, they declare one of those answers to be true. ",
  "sn44.7:4.5": "",
  "sn44.7:4.6": "",
  "sn44.7:4.7": "The Realized One, the perfected one, the fully awakened Buddha regards the eye like this: ‘This is not mine, I am not this, this is not my self.’ He regards the ear … nose … ",
  "sn44.7:4.8": "tongue … body … ",
  "sn44.7:4.9": "mind like this: ‘This is not mine, I am not this, this is not my self.’ ",
  "sn44.7:4.10": "That’s why, when asked, he does not declare one of those answers to be true.” ",
  "sn44.7:4.11": "",
  "sn44.7:4.12": "",
  "sn44.7:5.1": "Then the wanderer Vacchagotta got up from his seat and went to the Buddha and exchanged greetings with him. ",
  "sn44.7:5.2": "When the greetings and polite conversation were over, he sat down to one side. He asked the Buddha the same questions, and received the same answers. ",
  "sn44.7:5.3": "",
  "sn44.7:5.4": "",
  "sn44.7:5.5": "",
  "sn44.7:5.6": "",
  "sn44.7:5.7": "",
  "sn44.7:6.1": "",
  "sn44.7:6.2": "",
  "sn44.7:6.3": "",
  "sn44.7:6.4": "",
  "sn44.7:6.5": "",
  "sn44.7:6.6": "",
  "sn44.7:7.1": "",
  "sn44.7:7.2": "",
  "sn44.7:7.3": "",
  "sn44.7:7.4": "",
  "sn44.7:7.5": "",
  "sn44.7:7.6": "",
  "sn44.7:7.7": "",
  "sn44.7:7.8": "",
  "sn44.7:7.9": "",
  "sn44.7:7.10": "",
  "sn44.7:7.11": "",
  "sn44.7:8.1": "He said, “It’s incredible, worthy Gotama, it’s amazing! ",
  "sn44.7:8.2": "How the meaning and the phrasing of the teacher and the disciple fit together and agree without contradiction when it comes to the chief matter! ",
  "sn44.7:8.3": "Just now I went to the ascetic Mahāmoggallāna and asked him about this matter. ",
  "sn44.7:8.4": "And he explained it to me with these words and phrases, just like the worthy Gotama. ",
  "sn44.7:8.5": "It’s incredible, worthy Gotama, it’s amazing! ",
  "sn44.7:8.6": "How the meaning and the phrasing of the teacher and the disciple fit together and agree without contradiction when it comes to the chief matter!” ",
  "sn44.8:0.1": "Linked Discourses 44.8 ",
  "sn44.8:0.2": "1. The Undeclared Points ",
  "sn44.8:0.3": "With Vacchagotta ",
  "sn44.8:1.1": "Then the wanderer Vacchagotta went up to the Buddha and exchanged greetings with him. ",
  "sn44.8:1.2": "When the greetings and polite conversation were over, he sat down to one side, and said to the Buddha: ",
  "sn44.8:1.3": "“Worthy Gotama, is this right: ‘the cosmos is eternal’?” ",
  "sn44.8:1.4": "“This has not been declared by me, Vaccha.” … ",
  "sn44.8:1.5": "“Then is this right: ‘a realized one neither still exists nor no longer exists after death’?” ",
  "sn44.8:1.6": "“This too has not been declared by me.” ",
  "sn44.8:1.7": "",
  "sn44.8:2.1": "“What’s the cause, worthy Gotama, what’s the reason why, when the wanderers of other religions are asked these questions, they declare one of these to be true? ",
  "sn44.8:2.2": "",
  "sn44.8:2.3": "",
  "sn44.8:2.4": "And what’s the reason why, when the worthy Gotama is asked these questions, he does not declare one of these to be true?” ",
  "sn44.8:2.5": "",
  "sn44.8:2.6": "",
  "sn44.8:3.1": "“Vaccha, the wanderers of other religions regard form as self, self as having form, form in self, or self in form. ",
  "sn44.8:3.2": "They regard feeling … ",
  "sn44.8:3.3": "perception … ",
  "sn44.8:3.4": "choices … ",
  "sn44.8:3.5": "consciousness as self, self as having consciousness, consciousness in self, or self in consciousness. ",
  "sn44.8:3.6": "That’s why, when asked, they declare one of those answers to be true. ",
  "sn44.8:3.7": "",
  "sn44.8:3.8": "",
  "sn44.8:3.9": "The Realized One doesn’t regard form as self, self as having form, form in self, or self in form. ",
  "sn44.8:3.10": "He doesn’t regard feeling … ",
  "sn44.8:3.11": "perception … ",
  "sn44.8:3.12": "choices … ",
  "sn44.8:3.13": "consciousness as self, self as having consciousness, consciousness in self, or self in consciousness. ",
  "sn44.8:3.14": "That’s why, when asked, he does not declare one of those answers to be true.” ",
  "sn44.8:3.15": "",
  "sn44.8:3.16": "",
  "sn44.8:4.1": "Then the wanderer Vacchagotta got up from his seat and went to Venerable Mahāmoggallāna, and exchanged greetings with him. ",
  "sn44.8:4.2": "When the greetings and polite conversation were over, he sat down to one side. He asked Mahāmoggallāna the same questions, and received the same answers. ",
  "sn44.8:4.3": "",
  "sn44.8:4.4": "",
  "sn44.8:4.5": "",
  "sn44.8:4.6": "",
  "sn44.8:4.7": "",
  "sn44.8:5.1": "",
  "sn44.8:5.2": "",
  "sn44.8:5.3": "",
  "sn44.8:5.4": "",
  "sn44.8:5.5": "",
  "sn44.8:5.6": "",
  "sn44.8:6.1": "",
  "sn44.8:6.2": "",
  "sn44.8:6.3": "",
  "sn44.8:6.4": "",
  "sn44.8:6.5": "",
  "sn44.8:6.6": "",
  "sn44.8:6.7": "",
  "sn44.8:6.8": "",
  "sn44.8:6.9": "",
  "sn44.8:6.10": "",
  "sn44.8:6.11": "",
  "sn44.8:6.12": "",
  "sn44.8:6.13": "",
  "sn44.8:6.14": "",
  "sn44.8:6.15": "",
  "sn44.8:7.1": "He said, “It’s incredible, worthy Moggallāna, it’s amazing. ",
  "sn44.8:7.2": "How the meaning and the phrasing of the teacher and the disciple fit together and agree without contradiction when it comes to the chief matter! ",
  "sn44.8:7.3": "Just now I went to the ascetic Gotama and asked him about this matter. ",
  "sn44.8:7.4": "And he explained it to me with these words and phrases, just like the worthy Moggallāna. ",
  "sn44.8:7.5": "It’s incredible, worthy Moggallāna, it’s amazing! ",
  "sn44.8:7.6": "How the meaning and the phrasing of the teacher and the disciple fit together and agree without contradiction when it comes to the chief matter!” ",
  "sn44.9:0.1": "Linked Discourses 44.9 ",
  "sn44.9:0.2": "1. The Undeclared Points ",
  "sn44.9:0.3": "The Debating Hall ",
  "sn44.9:1.1": "Then the wanderer Vacchagotta went up to the Buddha and exchanged greetings with him. ",
  "sn44.9:1.2": "When the greetings and polite conversation were over, he sat down to one side, and said to the Buddha: ",
  "sn44.9:2.1": "“Worthy Gotama, a few days ago several ascetics, brahmins, and wanderers who follow various other religions were sitting together in the debating hall, and this discussion came up among them: ",
  "sn44.9:2.2": "‘This Pūraṇa Kassapa leads an order and a community, and tutors a community. He’s a well-known and famous religious founder, deemed holy by many people. ",
  "sn44.9:2.3": "When a disciple passes away, he declares that ",
  "sn44.9:2.4": "this one is reborn here, while that one is reborn there. ",
  "sn44.9:2.5": "And as for a disciple who is a supreme person, highest of people, having reached the highest point, when they pass away he also declares that ",
  "sn44.9:2.6": "this one is reborn here, while that one is reborn there. ",
  "sn44.9:3.1": "This bamboo-staffed ascetic Gosāla … ",
  "sn44.9:3.2": "the Jain ascetic of the Ñātika clan … ",
  "sn44.9:3.3": "Sañjaya Belaṭṭhiputta … ",
  "sn44.9:3.4": "Pakudha Kaccāyana … ",
  "sn44.9:3.5": "Ajita of the hair blanket leads an order and a community, and tutors a community. He’s a well-known and famous religious founder, deemed holy by many people. ",
  "sn44.9:3.6": "When a disciple passes away, he declares that ",
  "sn44.9:3.7": "this one is reborn here, while that one is reborn there. ",
  "sn44.9:3.8": "And as for a disciple who is a supreme person, highest of people, having reached the highest point, when they pass away he also declares that ",
  "sn44.9:3.9": "this one is reborn here, while that one is reborn there. ",
  "sn44.9:4.1": "This ascetic Gotama leads an order and a community, and tutors a community. He’s a well-known and famous religious founder, deemed holy by many people. ",
  "sn44.9:4.2": "When a disciple passes away, he declares that ",
  "sn44.9:4.3": "this one is reborn here, while that one is reborn there. ",
  "sn44.9:4.4": "But as for a disciple who is a supreme person, highest of people, having reached the highest point, when they pass away he doesn’t declare that ",
  "sn44.9:4.5": "this one is reborn here, while that one is reborn there. ",
  "sn44.9:4.6": "Rather, he declares that they have ",
  "sn44.9:4.7": "cut off craving, cast off the fetters, and by rightly comprehending conceit have made an end of suffering.’ ",
  "sn44.9:4.8": "I had doubt and uncertainty about that: ",
  "sn44.9:4.9": "‘How on earth can I understand the ascetic Gotama’s teaching?’” ",
  "sn44.9:5.1": "“Vaccha, no wonder you’re doubting and uncertain. ",
  "sn44.9:5.2": "Doubt has come up in you about an uncertain matter. ",
  "sn44.9:5.3": "I describe rebirth for someone who grasps fuel, not for someone who does not. ",
  "sn44.9:5.4": "It’s like a fire which only burns with fuel, not without fuel. ",
  "sn44.9:5.5": "In the same way I describe rebirth for someone who grasps fuel, not for someone who doesn’t grasp fuel.” ",
  "sn44.9:6.1": "“But when a flame is blown away by the wind, what does the worthy Gotama say is its fuel then?” ",
  "sn44.9:6.2": "“At such a time, I say that it’s fueled by the wind. ",
  "sn44.9:6.3": "For the wind is its fuel then.” ",
  "sn44.9:6.4": "“But when someone who is attached has laid down this body and has not been reborn in one of the realms, what does the worthy Gotama say is their fuel then?” ",
  "sn44.9:6.5": "“When someone who is attached has laid down this body, Vaccha, and has not been reborn in one of the realms, I say they’re fueled by craving. ",
  "sn44.9:6.6": "For craving is their fuel then.” ",
  "sn44.10:0.1": "Linked Discourses 44.10 ",
  "sn44.10:0.2": "1. The Undeclared Points ",
  "sn44.10:0.3": "With Ānanda ",
  "sn44.10:1.1": "Then the wanderer Vacchagotta went up to the Buddha and exchanged greetings with him. ",
  "sn44.10:1.2": "When the greetings and polite conversation were over, he sat down to one side and said to the Buddha: ",
  "sn44.10:1.3": "“Worthy Gotama, does the self survive?” ",
  "sn44.10:1.4": "But when he said this, the Buddha kept silent. ",
  "sn44.10:1.5": "“Then does the self not survive?” ",
  "sn44.10:1.6": "But for a second time the Buddha kept silent. ",
  "sn44.10:1.7": "Then the wanderer Vacchagotta got up from his seat and left. ",
  "sn44.10:2.1": "And then, not long after Vacchagotta had left, Venerable Ānanda said to the Buddha: ",
  "sn44.10:2.2": "“Sir, why didn’t you answer Vacchagotta’s question?” ",
  "sn44.10:2.3": "“Ānanda, when Vacchagotta asked me whether the self survives, if I had answered that ‘the self survives’ I would have been siding with the ascetics and brahmins who are eternalists. ",
  "sn44.10:2.4": "When Vacchagotta asked me whether the self does not survive, if I had answered that ‘the self does not survive’ I would have been siding with the ascetics and brahmins who are annihilationists. ",
  "sn44.10:2.5": "When Vacchagotta asked me whether the self survives, if I had answered that ‘the self survives’, would that have facilitated the arising of the knowledge that ",
  "sn44.10:2.6": "all things are not-self?” ",
  "sn44.10:2.7": "“No, sir.” ",
  "sn44.10:2.8": "“When Vacchagotta asked me whether the self does not survive, if I had answered that ‘the self does not survive’, Vacchagottawho is already confusedwould have got even more confused, thinking: ",
  "sn44.10:2.9": "‘It seems that the self that I once had no longer survives.’” ",
  "sn44.11:0.1": "Linked Discourses 44.11 ",
  "sn44.11:0.2": "1. The Undeclared Points ",
  "sn44.11:0.3": "With Sabhiya Kaccāna ",
  "sn44.11:1.1": "At one time Venerable Sabhiya Kaccāna was staying at Ñātika in the brick house. ",
  "sn44.11:1.2": "Then the wanderer Vacchagotta went up to him, and exchanged greetings with him. ",
  "sn44.11:1.3": "When the greetings and polite conversation were over, he sat down to one side, and said to Sabhiya Kaccāna: ",
  "sn44.11:1.4": "“Worthy Kaccāna, does a realized one still exist after death?” ",
  "sn44.11:1.5": "“Vaccha, this has not been declared by the Buddha.” ",
  "sn44.11:1.6": "",
  "sn44.11:1.7": "“Well then, does a realized one no longer exist after death?” ",
  "sn44.11:1.8": "“This too has not been declared by the Buddha.” ",
  "sn44.11:1.9": "",
  "sn44.11:2.1": "“Well then, does a realized one both exist and not exist after death?” ",
  "sn44.11:2.2": "“This has not been declared by the Buddha.” ",
  "sn44.11:2.3": "",
  "sn44.11:2.4": "“Well then, does a realized one neither exist nor not exist after death?” ",
  "sn44.11:2.5": "“This too has not been declared by the Buddha.” ",
  "sn44.11:2.6": "",
  "sn44.11:3.1": "“Worthy Kaccāna, when asked these questions, you say that this has not been declared by the Buddha. ",
  "sn44.11:3.2": "",
  "sn44.11:3.3": "",
  "sn44.11:3.4": "",
  "sn44.11:3.5": "",
  "sn44.11:3.6": "",
  "sn44.11:3.7": "",
  "sn44.11:3.8": "",
  "sn44.11:3.9": "",
  "sn44.11:3.10": "",
  "sn44.11:3.11": "",
  "sn44.11:3.12": "",
  "sn44.11:3.13": "What’s the cause, what’s the reason why this has not been declared by the Buddha?” ",
  "sn44.11:3.14": "“In order to describe him as ‘formed’ or ‘formless’ or ‘percipient’ or ‘non-percipient’ or ‘neither percipient nor non-percipient’, there must be some cause or reason for doing so. But if that cause and reason were to totally and utterly cease without remainder, ",
  "sn44.11:3.15": "how could you describe him in any such terms?” ",
  "sn44.11:3.16": "“Worthy Kaccāna, how long has it been since you went forth?” ",
  "sn44.11:3.17": "“Not long, reverend: three years.” ",
  "sn44.11:3.18": "“One who has learned this much in this time, reverend, has learned a lot, who can say what lies ahead!” ",
  "sn44.11:3.19": "",
  "sn44.11:3.20": "",
  "sn44.11:4.1": "",
  "sn44.11:4.2": "",
  "sn44.11:4.3": "",
  "sn44.11:4.4": "",
  "sn44.11:4.5": "",
  "sn44.11:4.6": "The Linked Discourses on undeclared questions are complete. ",
  "sn44.11:5.1": "",
  "sn44.11:5.2": "",
  "sn44.11:5.3": "",
  "sn44.11:5.4": "",
  "sn44.11:5.5": "",
  "sn44.11:5.6": "",
  "sn44.11:5.7": "The Book of the Six Sense Fields is finished. "
}
window.BILARA["sn44_v1"]["en"]["sn44_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
