window.BILARA = window.BILARA || {};
window.BILARA["sn54_v1"] = window.BILARA["sn54_v1"] || {};
window.BILARA["sn54_v1"]["en"] = {
  "sn54.1:0.1": "Linked Discourses 54.1 ",
  "sn54.1:0.2": "1. One Thing ",
  "sn54.1:0.3": "One Thing ",
  "sn54.1:1.1": "At Sāvatthī. ",
  "sn54.1:1.2": "",
  "sn54.1:1.3": "“Mendicants, when one thing is developed and cultivated it’s very fruitful and beneficial. ",
  "sn54.1:1.4": "What one thing? ",
  "sn54.1:1.5": "Mindfulness of breathing. ",
  "sn54.1:1.6": "And how is mindfulness of breathing developed and cultivated to be very fruitful and beneficial? ",
  "sn54.1:1.7": "It’s when a mendicantgone to a wilderness, or to the root of a tree, or to an empty hutsits down cross-legged, sets their body straight, and brings mindfulness to the present. ",
  "sn54.1:1.8": "Just mindful, they breathe in. Mindful, they breathe out. ",
  "sn54.1:2.1": "Breathing in heavily they know: ‘I’m breathing in heavily.’ Breathing out heavily they know: ‘I’m breathing out heavily.’ ",
  "sn54.1:2.2": "When breathing in lightly they know: ‘I’m breathing in lightly.’ Breathing out lightly they know: ‘I’m breathing out lightly.’ ",
  "sn54.1:2.3": "They practice like this: ‘I’ll breathe in experiencing the whole body.’ They practice like this: ‘I’ll breathe out experiencing the whole body.’ ",
  "sn54.1:2.4": "They practice like this: ‘I’ll breathe in stilling the physical process.’ They practice like this: ‘I’ll breathe out stilling the physical process.’ ",
  "sn54.1:3.1": "They practice like this: ‘I’ll breathe in experiencing rapture.’ They practice like this: ‘I’ll breathe out experiencing rapture.’ ",
  "sn54.1:3.2": "They practice like this: ‘I’ll breathe in experiencing bliss.’ They practice like this: ‘I’ll breathe out experiencing bliss.’ ",
  "sn54.1:3.3": "They practice like this: ‘I’ll breathe in experiencing the mental process.’ They practice like this: ‘I’ll breathe out experiencing the mental process.’ ",
  "sn54.1:3.4": "They practice like this: ‘I’ll breathe in stilling the mental process.’ They practice like this: ‘I’ll breathe out stilling the mental process.’ ",
  "sn54.1:4.1": "They practice like this: ‘I’ll breathe in experiencing the mind.’ They practice like this: ‘I’ll breathe out experiencing the mind.’ ",
  "sn54.1:4.2": "They practice like this: ‘I’ll breathe in gladdening the mind.’ They practice like this: ‘I’ll breathe out gladdening the mind.’ ",
  "sn54.1:4.3": "They practice like this: ‘I’ll breathe in immersing the mind in samādhi.’ They practice like this: ‘I’ll breathe out immersing the mind in samādhi.’ ",
  "sn54.1:4.4": "They practice like this: ‘I’ll breathe in freeing the mind.’ They practice like this: ‘I’ll breathe out freeing the mind.’ ",
  "sn54.1:4.5": "They practice like this: ‘I’ll breathe in observing impermanence.’ They practice like this: ‘I’ll breathe out observing impermanence.’ ",
  "sn54.1:5.1": "",
  "sn54.1:5.2": "They practice like this: ‘I’ll breathe in observing fading away.’ They practice like this: ‘I’ll breathe out observing fading away.’ ",
  "sn54.1:5.3": "They practice like this: ‘I’ll breathe in observing cessation.’ They practice like this: ‘I’ll breathe out observing cessation.’ ",
  "sn54.1:5.4": "They practice like this: ‘I’ll breathe in observing letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.1:6.1": "Mindfulness of breathing, when developed and cultivated in this way, is very fruitful and beneficial.” ",
  "sn54.2:0.1": "Linked Discourses 54.2 ",
  "sn54.2:0.2": "1. One Thing ",
  "sn54.2:0.3": "Awakening Factors ",
  "sn54.2:1.1": "“Mendicants, when mindfulness of breathing is developed and cultivated it’s very fruitful and beneficial. ",
  "sn54.2:1.2": "And how is mindfulness of breathing developed and cultivated to be very fruitful and beneficial? ",
  "sn54.2:1.3": "It’s when a mendicant develops mindfulness of breathing together with the awakening factors of mindfulness, ",
  "sn54.2:1.4": "investigation of principles, energy, rapture, tranquility, immersion, ",
  "sn54.2:1.5": "and equanimity, which rely on seclusion, fading away, and cessation, and ripen as letting go. ",
  "sn54.2:1.6": "Mindfulness of breathing, when developed and cultivated in this way, is very fruitful and beneficial.” ",
  "sn54.3:0.1": "Linked Discourses 54.3 ",
  "sn54.3:0.2": "1. One Thing ",
  "sn54.3:0.3": "Plain Version ",
  "sn54.3:1.1": "“Mendicants, when mindfulness of breathing is developed and cultivated it’s very fruitful and beneficial. ",
  "sn54.3:1.2": "And how is mindfulness of breathing developed and cultivated to be very fruitful and beneficial? ",
  "sn54.3:1.3": "It’s when a mendicantgone to a wilderness, or to the root of a tree, or to an empty hutsits down cross-legged, sets their body straight, and brings mindfulness to the present. ",
  "sn54.3:1.4": "Just mindful, they breathe in. Mindful, they breathe out. … ",
  "sn54.3:1.5": "They practice like this: ‘I’ll breathe in observing letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.3:1.6": "Mindfulness of breathing, when developed and cultivated in this way, is very fruitful and beneficial.” ",
  "sn54.4:0.1": "Linked Discourses 54.4 ",
  "sn54.4:0.2": "1. One Thing ",
  "sn54.4:0.3": "Fruits (1st) ",
  "sn54.4:1.1": "“Mendicants, when mindfulness of breathing is developed and cultivated it’s very fruitful and beneficial. ",
  "sn54.4:1.2": "And how is mindfulness of breathing developed and cultivated to be very fruitful and beneficial? ",
  "sn54.4:1.3": "It’s when a mendicantgone to a wilderness, or to the root of a tree, or to an empty hutsits down cross-legged, sets their body straight, and brings mindfulness to the present. ",
  "sn54.4:1.4": "Just mindful, they breathe in. Mindful, they breathe out. … ",
  "sn54.4:1.5": "They practice like this: ‘I’ll breathe in observing letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.4:1.6": "Mindfulness of breathing, when developed and cultivated in this way, is very fruitful and beneficial. ",
  "sn54.4:1.7": "When mindfulness of breathing is developed and cultivated in this way you can expect one of two results: ",
  "sn54.4:1.8": "enlightenment in this very life, or if there’s residue left behind, non-return.” ",
  "sn54.5:0.1": "Linked Discourses 54.5 ",
  "sn54.5:0.2": "1. One Thing ",
  "sn54.5:0.3": "Fruits (2nd) ",
  "sn54.5:1.1": "“Mendicants, when mindfulness of breathing is developed and cultivated it’s very fruitful and beneficial. ",
  "sn54.5:1.2": "And how is mindfulness of breathing developed and cultivated to be very fruitful and beneficial? ",
  "sn54.5:1.3": "It’s when a mendicantgone to a wilderness, or to the root of a tree, or to an empty hutsits down cross-legged, sets their body straight, and brings mindfulness to the present. ",
  "sn54.5:1.4": "Just mindful, they breathe in. Mindful, they breathe out. … ",
  "sn54.5:1.5": "They practice like this: ‘I’ll breathe in observing letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.5:1.6": "Mindfulness of breathing, when developed and cultivated in this way, is very fruitful and beneficial. ",
  "sn54.5:2.1": "When mindfulness of breathing is developed and cultivated in this way you can expect seven fruits and benefits. ",
  "sn54.5:2.2": "What seven? ",
  "sn54.5:2.3": "You attain enlightenment early on in this very life. ",
  "sn54.5:2.4": "",
  "sn54.5:2.5": "If not, you attain enlightenment at the time of death. ",
  "sn54.5:2.6": "",
  "sn54.5:2.7": "If not, with the ending of the five lower fetters you’re extinguished in between one life and the next … ",
  "sn54.5:2.8": "you’re extinguished upon landing … ",
  "sn54.5:2.9": "you’re extinguished without extra effort … ",
  "sn54.5:2.10": "you’re extinguished with extra effort … ",
  "sn54.5:2.11": "you head upstream, going to the Akaniṭṭha realm … ",
  "sn54.5:2.12": "When mindfulness of breathing is developed and cultivated in this way you can expect these seven fruits and benefits.” ",
  "sn54.6:0.1": "Linked Discourses 54.6 ",
  "sn54.6:0.2": "1. One Thing ",
  "sn54.6:0.3": "With Ariṭṭha ",
  "sn54.6:1.1": "At Sāvatthī. ",
  "sn54.6:1.2": "There the Buddha … said: ",
  "sn54.6:1.3": "“Mendicants, do you develop mindfulness of breathing?” ",
  "sn54.6:1.4": "When he said this, Venerable Ariṭṭha said to him: ",
  "sn54.6:1.5": "“Sir, I develop mindfulness of breathing.” ",
  "sn54.6:1.6": "“But mendicant, how do you develop it?” ",
  "sn54.6:1.7": "“Sir, I’ve given up desire for sensual pleasures of the past. I’m rid of desire for sensual pleasures of the future. And I have eliminated perception of aversion regarding phenomena internally and externally. ",
  "sn54.6:1.8": "Just mindful, I will breathe in. Mindful, I will breathe out. ",
  "sn54.6:1.9": "That’s how I develop mindfulness of breathing.” ",
  "sn54.6:2.1": "“That is mindfulness of breathing, Ariṭṭha; I don’t deny it. ",
  "sn54.6:2.2": "But as to how mindfulness of breathing is fulfilled in detail, ",
  "sn54.6:2.3": "listen and apply your mind well, I will speak.” ",
  "sn54.6:2.4": "“Yes, sir,” Ariṭṭha replied. ",
  "sn54.6:2.5": "The Buddha said this: ",
  "sn54.6:3.1": "“And how is mindfulness of breathing fulfilled in detail? ",
  "sn54.6:3.2": "It’s when a mendicantgone to a wilderness, or to the root of a tree, or to an empty hutsits down cross-legged, sets their body straight, and brings mindfulness to the present. ",
  "sn54.6:3.3": "Just mindful, they breathe in. Mindful, they breathe out. ",
  "sn54.6:3.4": "Breathing in heavily they know: ‘I’m breathing in heavily.’ Breathing out heavily they know: ‘I’m breathing out heavily.’ … ",
  "sn54.6:3.5": "They practice like this: ‘I’ll breathe in observing letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.6:3.6": "This is how mindfulness of breathing is fulfilled in detail.” ",
  "sn54.7:0.1": "Linked Discourses 54.7 ",
  "sn54.7:0.2": "1. One Thing ",
  "sn54.7:0.3": "About Mahākappina ",
  "sn54.7:1.1": "At Sāvatthī. ",
  "sn54.7:1.2": "Now at that time Venerable Mahākappina was sitting not far from the Buddha, cross-legged, his body set straight, and mindfulness brought to the present. ",
  "sn54.7:1.3": "The Buddha saw him, ",
  "sn54.7:1.4": "and addressed the mendicants: ",
  "sn54.7:2.1": "“Mendicants, do you see any disturbance or trembling in that mendicant’s body?” ",
  "sn54.7:2.2": "“Sir, whenever we see that mendicant meditatingwhether in the middle of the Saṅgha or alone in privatewe never see any disturbance or trembling in his body.” ",
  "sn54.7:3.1": "“Mendicants, when an immersion has been developed and cultivated there’s no disturbance or trembling of the body or mind. That mendicant gets such immersion when he wants, without trouble or difficulty. ",
  "sn54.7:3.2": "And what is that immersion? ",
  "sn54.7:4.1": "When immersion due to mindfulness of breathing has been developed and cultivated there’s no disturbance or trembling of the body or mind. ",
  "sn54.7:4.2": "And how is immersion due to mindfulness of breathing developed and cultivated in such a way? ",
  "sn54.7:5.1": "It’s when a mendicantgone to a wilderness, or to the root of a tree, or to an empty hutsits down cross-legged, sets their body straight, and brings mindfulness to the present. ",
  "sn54.7:5.2": "Just mindful, they breathe in. Mindful, they breathe out. … ",
  "sn54.7:5.3": "They practice like this: ‘I’ll breathe in observing letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.7:5.4": "That’s how immersion due to mindfulness of breathing is developed and cultivated so that there’s no disturbance or trembling of the body or mind.” ",
  "sn54.8:0.1": "Linked Discourses 54.8 ",
  "sn54.8:0.2": "1. One Thing ",
  "sn54.8:0.3": "The Simile of the Lamp ",
  "sn54.8:1.1": "“Mendicants, when immersion due to mindfulness of breathing is developed and cultivated it’s very fruitful and beneficial. ",
  "sn54.8:1.2": "How so? ",
  "sn54.8:2.1": "It’s when a mendicantgone to a wilderness, or to the root of a tree, or to an empty hutsits down cross-legged, sets their body straight, and brings mindfulness to the present. ",
  "sn54.8:2.2": "Just mindful, they breathe in. Mindful, they breathe out. ",
  "sn54.8:2.3": "Breathing in heavily they know: ‘I’m breathing in heavily.’ Breathing out heavily they know: ‘I’m breathing out heavily.’ … ",
  "sn54.8:2.4": "They practice like this: ‘I’ll breathe in observing letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.8:2.5": "That’s how immersion due to mindfulness of breathing, when developed and cultivated, is very fruitful and beneficial. ",
  "sn54.8:3.1": "Before my awakeningwhen I was still unawakened but intent on awakeningI too usually practiced this kind of meditation. ",
  "sn54.8:3.2": "And while I was usually practicing this kind of meditation neither my body nor my eyes became fatigued. ",
  "sn54.8:3.3": "And my mind was freed from defilements by not grasping. ",
  "sn54.8:4.1": "Now, a mendicant might wish: ",
  "sn54.8:4.2": "‘May neither my body nor my eyes became fatigued. And may my mind be freed from the defilements by not grasping.’ ",
  "sn54.8:4.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:5.1": "Now, a mendicant might wish: ",
  "sn54.8:5.2": "‘May I give up memories and thoughts tied to domestic life.’ ",
  "sn54.8:5.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:6.1": "Now, a mendicant might wish: ",
  "sn54.8:6.2": "‘May I meditate perceiving the repulsive in the unrepulsive.’ ",
  "sn54.8:6.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:7.1": "Now, a mendicant might wish: ",
  "sn54.8:7.2": "‘May I meditate perceiving the unrepulsive in the repulsive.’ ",
  "sn54.8:7.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:8.1": "Now, a mendicant might wish: ",
  "sn54.8:8.2": "‘May I meditate perceiving the repulsive in the unrepulsive and the repulsive.’ ",
  "sn54.8:8.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:9.1": "Now, a mendicant might wish: ",
  "sn54.8:9.2": "‘May I meditate perceiving the unrepulsive in the repulsive and the unrepulsive.’ ",
  "sn54.8:9.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:10.1": "Now, a mendicant might wish: ",
  "sn54.8:10.2": "‘May I meditate staying equanimous, mindful and aware, shunning both the repulsive and the unrepulsive.’ ",
  "sn54.8:10.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:11.1": "Now, a mendicant might wish: ",
  "sn54.8:11.2": "‘Quite secluded from sensual pleasures, secluded from unskillful qualities, may I enter and remain in the first absorption, which has the rapture and bliss born of seclusion, while placing the mind and keeping it connected.’ ",
  "sn54.8:11.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:12.1": "Now, a mendicant might wish: ",
  "sn54.8:12.2": "‘As the placing of the mind and keeping it connected are stilled, may I enter and remain in the second absorption, which has the rapture and bliss born of immersion, with internal clarity and mind at one, without placing the mind and keeping it connected.’ ",
  "sn54.8:12.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:13.1": "Now, a mendicant might wish: ",
  "sn54.8:13.2": "‘With the fading away of rapture, may I enter and remain in the third absorption, where I will meditate with equanimity, mindful and aware, personally experiencing the bliss of which the noble ones declare, “Equanimous and mindful, one meditates in bliss.”’ ",
  "sn54.8:13.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:14.1": "Now, a mendicant might wish: ",
  "sn54.8:14.2": "‘With the giving up of pleasure and pain, and the ending of former happiness and sadness, may I enter and remain in the fourth absorption, without pleasure or pain, with pure equanimity and mindfulness.’ ",
  "sn54.8:14.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:15.1": "Now, a mendicant might wish: ",
  "sn54.8:15.2": "‘Going totally beyond perceptions of form, with the disappearance of perceptions of impingement, not focusing on perceptions of diversity, aware that “space is infinite”, may I enter and remain in the dimension of infinite space.’ ",
  "sn54.8:15.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:16.1": "Now, a mendicant might wish: ",
  "sn54.8:16.2": "‘Going totally beyond the dimension of infinite space, aware that “consciousness is infinite”, may I enter and remain in the dimension of infinite consciousness.’ ",
  "sn54.8:16.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:17.1": "Now, a mendicant might wish: ",
  "sn54.8:17.2": "‘Going totally beyond the dimension of infinite consciousness, aware that “there is nothing at all”, may I enter and remain in the dimension of nothingness.’ ",
  "sn54.8:17.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:18.1": "Now, a mendicant might wish: ",
  "sn54.8:18.2": "‘Going totally beyond the dimension of nothingness, may I enter and remain in the dimension of neither perception nor non-perception.’ ",
  "sn54.8:18.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:19.1": "Now, a mendicant might wish: ",
  "sn54.8:19.2": "‘Going totally beyond the dimension of neither perception nor non-perception, may I enter and remain in the cessation of perception and feeling.’ ",
  "sn54.8:19.3": "So let them closely focus on this immersion due to mindfulness of breathing. ",
  "sn54.8:20.1": "When immersion due to mindfulness of breathing has been developed and cultivated in this way, if they feel a pleasant feeling, they understand that it’s impermanent, that they’re not attached to it, and that they don’t take pleasure in it. ",
  "sn54.8:20.2": "If they feel a painful feeling, they understand that it’s impermanent, that they’re not attached to it, and that they don’t take pleasure in it. ",
  "sn54.8:20.3": "If they feel a neutral feeling, they understand that it’s impermanent, that they’re not attached to it, and that they don’t take pleasure in it. ",
  "sn54.8:21.1": "If they feel a pleasant feeling, they feel it detached. ",
  "sn54.8:21.2": "If they feel a painful feeling, they feel it detached. ",
  "sn54.8:21.3": "If they feel a neutral feeling, they feel it detached. ",
  "sn54.8:21.4": "Feeling the end of the body draw close, they understand: ‘I feel the end of the body draw close.’ Feeling the end of life draw close, they understand: ‘I feel the end of life draw close.’ ",
  "sn54.8:21.5": "They understand: ‘When my body breaks up and my life has come to an end, everything that’s felt, since I no longer take pleasure in it, will become cool right here.’ ",
  "sn54.8:22.1": "Suppose an oil lamp depended on oil and a wick to burn. ",
  "sn54.8:22.2": "As the oil and the wick are used up, it would be extinguished due to not being fed. ",
  "sn54.8:22.3": "In the same way, feeling the end of the body draw close, they understand: ‘I feel the end of the body draw close.’ Feeling the end of life draw close, they understand: ‘I feel the end of life draw close.’ ",
  "sn54.8:22.4": "They understand: ‘When my body breaks up and my life has come to an end, everything that’s felt, since I no longer take pleasure in it, will become cool right here.’” ",
  "sn54.9:0.1": "Linked Discourses 54.9 ",
  "sn54.9:0.2": "1. One Thing ",
  "sn54.9:0.3": "At Vesālī ",
  "sn54.9:1.1": "So I have heard. ",
  "sn54.9:1.2": "At one time the Buddha was staying near Vesālī, at the Great Wood, in the hall with the peaked roof. ",
  "sn54.9:1.3": "Now at that time the Buddha spoke in many ways to the mendicants about the meditation on ugliness. He praised the meditation on ugliness and its development. ",
  "sn54.9:2.1": "Then the Buddha said to the mendicants, ",
  "sn54.9:2.2": "“Mendicants, I wish to go on retreat for a fortnight. ",
  "sn54.9:2.3": "No-one should approach me, except for the one who brings my almsfood.” ",
  "sn54.9:2.4": "“Yes, sir,” replied those mendicants. And no-one approached him, except for the one who brought the almsfood. ",
  "sn54.9:3.1": "Then those mendicants thought, ",
  "sn54.9:3.2": "“The Buddha spoke in many ways about the meditation on ugliness. He praised the meditation on ugliness and its development.” They committed themselves to developing the many different facets of the meditation on ugliness. ",
  "sn54.9:3.3": "Becoming horrified, repelled, and disgusted with this body, they looked for a suicide weapon. ",
  "sn54.9:3.4": "Each day ten, twenty, or thirty mendicants committed suicide. ",
  "sn54.9:4.1": "Then after a fortnight had passed, the Buddha came out of retreat and addressed Ānanda, ",
  "sn54.9:4.2": "“Ānanda, why does the mendicant Saṅgha seem so diminished?” ",
  "sn54.9:4.3": "Ānanda told the Buddha all that had happened, and said, ",
  "sn54.9:4.4": "",
  "sn54.9:4.5": "",
  "sn54.9:4.6": "“Sir, please explain another way the mendicant Saṅgha might be settled in enlightenment.” ",
  "sn54.9:5.1": "“Well then, Ānanda, gather all the mendicants staying in the vicinity of Vesālī together in the assembly hall.” ",
  "sn54.9:5.2": "“Yes, sir,” replied Ānanda. He did what the Buddha asked, went up to him, and said, ",
  "sn54.9:5.3": "“Sir, the mendicant Saṅgha has assembled. ",
  "sn54.9:5.4": "Please, sir, come at your convenience.” ",
  "sn54.9:6.1": "Then the Buddha went to the assembly hall, sat down on the seat spread out, ",
  "sn54.9:6.2": "and addressed the mendicants: ",
  "sn54.9:6.3": "“Mendicants, when this immersion due to mindfulness of breathing is developed and cultivated it’s peaceful and sublime, a delectable and blissful meditation. And it disperses and settles unskillful qualities on the spot whenever they arise. ",
  "sn54.9:7.1": "In the last month of summer, when the dust and dirt is stirred up, a large storm out of season disperses and settles it on the spot. ",
  "sn54.9:7.2": "In the same way, when this immersion due to mindfulness of breathing is developed and cultivated it’s peaceful and sublime, a delectable and blissful meditation. And it disperses and settles unskillful qualities on the spot whenever they arise. ",
  "sn54.9:7.3": "And how is it so developed and cultivated? ",
  "sn54.9:8.1": "It’s when a mendicantgone to a wilderness, or to the root of a tree, or to an empty hutsits down cross-legged, sets their body straight, and brings mindfulness to the present. ",
  "sn54.9:8.2": "Just mindful, they breathe in. Mindful, they breathe out. … ",
  "sn54.9:8.3": "They practice like this: ‘I’ll breathe in observing letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.9:8.4": "That’s how this immersion due to mindfulness of breathing is developed and cultivated so that it’s peaceful and sublime, a delectable and blissful  meditation. And it disperses and settles unskillful qualities on the spot whenever they arise.” ",
  "sn54.10:0.1": "Linked Discourses 54.10 ",
  "sn54.10:0.2": "1. One Thing ",
  "sn54.10:0.3": "With Kimbila ",
  "sn54.10:1.1": "So I have heard. ",
  "sn54.10:1.2": "At one time the Buddha was staying near Kimbilā in the Freshwater Mangrove Wood. ",
  "sn54.10:1.3": "Then the Buddha said to Venerable Kimbila, ",
  "sn54.10:1.4": "“Kimbila, how is immersion due to mindfulness of breathing developed and cultivated so that it is very fruitful and beneficial?” ",
  "sn54.10:2.1": "When he said this, Kimbila kept silent. ",
  "sn54.10:2.2": "For a second time … ",
  "sn54.10:2.3": "And for a third time, the Buddha said to him, ",
  "sn54.10:2.4": "“How is immersion due to mindfulness of breathing developed and cultivated so that it is very fruitful and beneficial?” ",
  "sn54.10:2.5": "And a second time and a third time Kimbila kept silent. ",
  "sn54.10:3.1": "When he said this, Venerable Ānanda said to the Buddha, ",
  "sn54.10:3.2": "“Now is the time, Blessed One! Now is the time, Holy One! ",
  "sn54.10:3.3": "Let the Buddha speak on immersion due to mindfulness of breathing. The mendicants will listen and remember it.” ",
  "sn54.10:4.1": "“Well then, Ānanda, listen and apply your mind well, I will speak.” ",
  "sn54.10:4.2": "“Yes, sir,” Ānanda replied. ",
  "sn54.10:4.3": "The Buddha said this: ",
  "sn54.10:4.4": "“Ānanda, how is immersion due to mindfulness of breathing developed and cultivated so that it is very fruitful and beneficial? ",
  "sn54.10:4.5": "It’s when a mendicantgone to a wilderness, or to the root of a tree, or to an empty hutsits down cross-legged, sets their body straight, and brings mindfulness to the present. ",
  "sn54.10:4.6": "Just mindful, they breathe in. Mindful, they breathe out. … ",
  "sn54.10:4.7": "They practice like this: ‘I’ll breathe in observing letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.10:4.8": "That’s how immersion due to mindfulness of breathing, when developed and cultivated, is very fruitful and beneficial. ",
  "sn54.10:5.1": "There’s a time when a mendicant is breathing in heavily, and they know: ‘I’m breathing in heavily.’ Breathing out heavily they know: ‘I’m breathing out heavily.’ ",
  "sn54.10:5.2": "When breathing in lightly they know: ‘I’m breathing in lightly.’ Breathing out lightly they know: ‘I’m breathing out lightly.’ ",
  "sn54.10:5.3": "They practice like this: ‘I’ll breathe in experiencing the whole body.’ They practice like this: ‘I’ll breathe out experiencing the whole body.’ ",
  "sn54.10:5.4": "They practice like this: ‘I’ll breathe in stilling the physical process.’ They practice like this: ‘I’ll breathe out stilling the physical process.’ ",
  "sn54.10:5.5": "At such a time a mendicant is meditating by observing an aspect of the bodykeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.10:5.6": "Why is that? ",
  "sn54.10:5.7": "Because the breath is a certain aspect of the body, I say. ",
  "sn54.10:5.8": "Therefore, at such a time a mendicant is meditating by observing an aspect of the bodykeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.10:6.1": "There’s a time when a mendicant practices like this: ‘I’ll breathe in experiencing rapture.’ They practice like this: ‘I’ll breathe out experiencing rapture.’ ",
  "sn54.10:6.2": "They practice like this: ‘I’ll breathe in experiencing bliss.’ They practice like this: ‘I’ll breathe out experiencing bliss.’ ",
  "sn54.10:6.3": "They practice like this: ‘I’ll breathe in experiencing the the mental process.’ They practice like this: ‘I’ll breathe out experiencing the the mental process.’ ",
  "sn54.10:6.4": "They practice like this: ‘I’ll breathe in stilling the mental process.’ They practice like this: ‘I’ll breathe out stilling the mental process.’ ",
  "sn54.10:6.5": "At such a time a mendicant is meditating by observing an aspect of feelingskeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.10:6.6": "Why is that? ",
  "sn54.10:6.7": "Because careful application of mind to the in-breaths and out-breaths is a certain aspect of feelings, I say. ",
  "sn54.10:6.8": "Therefore, at such a time a mendicant is meditating by observing an aspect of feelingskeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.10:7.1": "There’s a time when a mendicant practices like this: ‘I’ll breathe in experiencing the mind.’ They practice like this: ‘I’ll breathe out experiencing the mind.’ ",
  "sn54.10:7.2": "They practice like this: ‘I’ll breathe in gladdening the mind.’ They practice like this: ‘I’ll breathe out gladdening the mind.’ ",
  "sn54.10:7.3": "They practice like this: ‘I’ll breathe in immersing the mind in samādhi.’ They practice like this: ‘I’ll breathe out immersing the mind in samādhi.’ ",
  "sn54.10:7.4": "They practice like this: ‘I’ll breathe in freeing the mind.’ They practice like this: ‘I’ll breathe out freeing the mind.’ ",
  "sn54.10:7.5": "At such a time a mendicant is meditating by observing an aspect of the mindkeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.10:7.6": "Why is that? ",
  "sn54.10:7.7": "Because there is no development of immersion due to mindfulness of breathing for someone who is unmindful and lacks awareness, I say. ",
  "sn54.10:7.8": "Therefore, at such a time a mendicant is meditating by observing an aspect of the mindkeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.10:8.1": "There’s a time when a mendicant practices like this: ‘I’ll breathe in observing impermanence.’ They practice like this: ‘I’ll breathe out observing impermanence.’ ",
  "sn54.10:8.2": "They practice like this: ‘I’ll breathe in observing fading away.’ They practice like this: ‘I’ll breathe out observing fading away.’ ",
  "sn54.10:8.3": "They practice like this: ‘I’ll breathe in observing cessation.’ They practice like this: ‘I’ll breathe out observing cessation.’ ",
  "sn54.10:8.4": "They practice like this: ‘I’ll breathe in observing letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.10:8.5": "At such a time a mendicant is meditating by observing an aspect of principleskeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.10:8.6": "Having seen with wisdom the giving up of covetousness and displeasure, they watch closely over with equanimity. ",
  "sn54.10:8.7": "Therefore, at such a time a mendicant is meditating by observing an aspect of principleskeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.10:9.1": "Suppose there was a large heap of sand at the crossroads. ",
  "sn54.10:9.2": "And a cart or chariot were to come by from the east, ",
  "sn54.10:9.3": "west, ",
  "sn54.10:9.4": "north, ",
  "sn54.10:9.5": "or south and destroy that heap of sand. ",
  "sn54.10:9.6": "In the same way, when a mendicant is meditating by observing an aspect of the body, ",
  "sn54.10:9.7": "feelings, ",
  "sn54.10:9.8": "mind, ",
  "sn54.10:9.9": "or principles, they destroy bad, unskillful qualities.” ",
  "sn54.10:9.10": "",
  "sn54.10:9.11": "",
  "sn54.10:10.1": "",
  "sn54.10:10.2": "",
  "sn54.10:10.3": "",
  "sn54.11:0.1": "Linked Discourses 54.11 ",
  "sn54.11:0.2": "Chapter Two ",
  "sn54.11:0.3": "Icchānaṅgala ",
  "sn54.11:1.1": "At one time the Buddha was staying in a forest near Icchānaṅgala. ",
  "sn54.11:1.2": "There he addressed the mendicants, ",
  "sn54.11:1.3": "“Mendicants, I wish to go on retreat for three months. ",
  "sn54.11:1.4": "No-one should approach me, except for the one who brings my almsfood.” ",
  "sn54.11:1.5": "“Yes, sir,” replied those mendicants. And no-one approached him, except for the one who brought the almsfood. ",
  "sn54.11:2.1": "Then after three months had passed, the Buddha came out of retreat and addressed the mendicants: ",
  "sn54.11:2.2": "“Mendicants, if wanderers who follow another religion were to ask you: ",
  "sn54.11:2.3": "‘Reverends, what was the ascetic Gotama’s usual meditation during the rainy season residence?’ You should answer them like this. ",
  "sn54.11:2.4": "‘Reverends, the ascetic Gotama’s usual meditation during the rainy season residence was immersion due to mindfulness of breathing.’ ",
  "sn54.11:2.5": "In this regard: mindful, I breathe in. Mindful, I breathe out. ",
  "sn54.11:2.6": "Breathing in heavily I know: ‘I’m breathing in heavily.’ Breathing out heavily I know: ‘I’m breathing out heavily.’ ",
  "sn54.11:2.7": "When breathing in lightly I know: ‘I’m breathing in lightly.’ Breathing out lightly I know: ‘I’m breathing out lightly.’ ",
  "sn54.11:2.8": "I know: ‘I’ll breathe in experiencing the whole body.’ … ",
  "sn54.11:2.9": "I know: ‘I’ll breathe in observing letting go.’ I know: ‘I’ll breathe out observing letting go.’ ",
  "sn54.11:3.1": "For if anything should be rightly called ",
  "sn54.11:3.2": "‘a noble meditation’, or else ‘a divine meditation’, or else ‘a realized one’s meditation’, ",
  "sn54.11:3.3": "it’s immersion due to mindfulness of breathing. ",
  "sn54.11:3.4": "",
  "sn54.11:3.5": "For those mendicants who are traineeswho haven’t achieved their heart’s desire, but live aspiring to the supreme sanctuary from the yokethe development and cultivation of immersion due to mindfulness of breathing leads to the ending of defilements. ",
  "sn54.11:3.6": "For those mendicants who are perfectedwho have ended the defilements, completed the spiritual journey, done what had to be done, laid down the burden, achieved their heart’s goal, utterly ended the fetter of continued existence, and are rightly freed through enlightenmentthe development and cultivation of immersion due to mindfulness of breathing leads to blissful meditation in this life, and to mindfulness and awareness. ",
  "sn54.11:4.1": "For if anything should be rightly called ",
  "sn54.11:4.2": "‘a noble meditation’, or else ‘a divine meditation’, or else ‘a realized one’s meditation’, ",
  "sn54.11:4.3": "it’s immersion due to mindfulness of breathing.” ",
  "sn54.11:4.4": "",
  "sn54.12:0.1": "Linked Discourses 54.12 ",
  "sn54.12:0.2": "Chapter Two ",
  "sn54.12:0.3": "In Doubt ",
  "sn54.12:1.1": "At one time Venerable Lomasakaṅgiya was staying in the land of the Sakyans, near Kapilavatthu in the Banyan Tree Monastery. ",
  "sn54.12:1.2": "Then Mahānāma the Sakyan went up to Venerable Lomasakaṅgiya, bowed, sat down to one side, and said to him, ",
  "sn54.12:1.3": "“Sir, is the meditation of a trainee just the same as the meditation of a realized one? Or is the meditation of a trainee different from the meditation of a realized one?” ",
  "sn54.12:2.1": "“Reverend Mahānāma, the meditation of a trainee and a realized one are not the same; ",
  "sn54.12:2.2": "they are different. ",
  "sn54.12:2.3": "Those mendicants who are trainees haven’t achieved their heart’s desire, but live aspiring for the supreme sanctuary from the yoke. They meditate after giving up the five hindrances. ",
  "sn54.12:2.4": "What five? ",
  "sn54.12:2.5": "The hindrances of sensual desire, ill will, ",
  "sn54.12:2.6": "dullness and drowsiness, ",
  "sn54.12:2.7": "restlessness and remorse, ",
  "sn54.12:2.8": "and doubt. ",
  "sn54.12:3.1": "Those who are trainee mendicants … meditate after giving up the five hindrances. ",
  "sn54.12:4.1": "Those mendicants who are perfectedwho have ended the defilements, completed the spiritual journey, done what had to be done, laid down the burden, achieved their heart’s goal, utterly ended the fetter of continued existence, and are rightly freed through enlightenmentfor them, the five hindrances are cut off at the root, made like a palm stump, obliterated, and unable to arise in the future. ",
  "sn54.12:4.2": "What five? ",
  "sn54.12:4.3": "The hindrances of sensual desire, ",
  "sn54.12:4.4": "ill will, ",
  "sn54.12:4.5": "dullness and drowsiness, ",
  "sn54.12:4.6": "restlessness and remorse, ",
  "sn54.12:4.7": "and doubt. ",
  "sn54.12:5.1": "Those mendicants who are perfectedwho have ended the defilements … for them, the five hindrances are cut off at the root … and unable to arise in the future. ",
  "sn54.12:5.2": "And here’s another way to understand how ",
  "sn54.12:5.3": "the meditation of a trainee and a realized one are different. ",
  "sn54.12:6.1": "At one time the Buddha was staying in a forest near Icchānaṅgala. ",
  "sn54.12:6.2": "There he addressed the mendicants, ",
  "sn54.12:6.3": "‘Mendicants, I wish to go on retreat for three months. ",
  "sn54.12:6.4": "No-one should approach me, except for the one who brings my almsfood.’ ",
  "sn54.12:6.5": "‘Yes, sir,’ replied those mendicants. And no-one approached him, except for the one who brought the almsfood. ",
  "sn54.12:7.1": "Then after three months had passed, the Buddha came out of retreat and addressed the mendicants: ",
  "sn54.12:7.2": "‘Mendicants, if wanderers who follow another religion were to ask you: ",
  "sn54.12:7.3": "“Reverends, what was the ascetic Gotama’s usual meditation during the rainy season residence?” You should answer them like this: ",
  "sn54.12:7.4": "“Reverends, the ascetic Gotama’s usual meditation during the rainy season residence was immersion due to mindfulness of breathing.” ",
  "sn54.12:7.5": "In this regard: mindful, I breathe in. Mindful, I breathe out. ",
  "sn54.12:7.6": "Breathing in heavily I know: “I’m breathing in heavily.” Breathing out heavily I know: “I’m breathing out heavily.” … ",
  "sn54.12:7.7": "I know: “I’ll breathe in observing letting go.” I know: “I’ll breathe out observing letting go.” ",
  "sn54.12:8.1": "For if anything should be rightly called ",
  "sn54.12:8.2": "“noble meditation”, or else “divine meditation’, or else “a realized one’s meditation”, ",
  "sn54.12:8.3": "it’s immersion due to mindfulness of breathing. ",
  "sn54.12:8.4": "",
  "sn54.12:9.1": "For those mendicants who are traineeswho haven’t achieved their heart’s desire, but live aspiring for the supreme sanctuary from the yokethe development and cultivation of immersion due to mindfulness of breathing leads to the ending of defilements. ",
  "sn54.12:10.1": "For those mendicants who are perfectedwho have ended the defilements, completed the spiritual journey, done what had to be done, laid down the burden, achieved their heart’s goal, utterly ended the fetter of continued existence, and are rightly freed through enlightenmentthe development and cultivation of immersion due to mindfulness of breathing leads to blissful meditation in this very life, and to mindfulness and awareness. ",
  "sn54.12:11.1": "For if anything should be rightly called ",
  "sn54.12:11.2": "“noble meditation”, or else “divine meditation’, or else “a realized one’s meditation”, ",
  "sn54.12:11.3": "it’s immersion due to mindfulness of breathing.’ ",
  "sn54.12:11.4": "",
  "sn54.12:11.5": "This is another way to understand how ",
  "sn54.12:11.6": "the meditation of a trainee and a realized one are different.” ",
  "sn54.13:0.1": "Linked Discourses 54.13 ",
  "sn54.13:0.2": "Chapter Two ",
  "sn54.13:0.3": "With Ānanda (1st) ",
  "sn54.13:1.1": "At Sāvatthī. ",
  "sn54.13:1.2": "Then Venerable Ānanda went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn54.13:1.3": "“Sir, is there one thing that, when developed and cultivated, fulfills four things; and those four things, when developed and cultivated, fulfill seven things; and those seven things, when developed and cultivated, fulfill two things?” ",
  "sn54.13:2.1": "“There is, Ānanda.” ",
  "sn54.13:3.1": "“Sir, what is that one thing?” ",
  "sn54.13:3.2": "“Immersion due to mindfulness of breathing is one thing that, when developed and cultivated, fulfills the four kinds of mindfulness meditation. And the four kinds of mindfulness meditation, when developed and cultivated, fulfill the seven awakening factors. And the seven awakening factors, when developed and cultivated, fulfill knowledge and freedom. ",
  "sn54.13:4.1": "And how is mindfulness of breathing developed and cultivated so as to fulfill the four kinds of mindfulness meditation? ",
  "sn54.13:4.2": "It’s when a mendicantgone to a wilderness, or to the root of a tree, or to an empty hutsits down cross-legged, sets their body straight, and brings mindfulness to the present. ",
  "sn54.13:4.3": "Just mindful, they breathe in. Mindful, they breathe out. ",
  "sn54.13:4.4": "Breathing in heavily they know: ‘I’m breathing in heavily.’ Breathing out heavily they know: ‘I’m breathing out heavily.’ … ",
  "sn54.13:4.5": "They practice like this: ‘I’ll breathe in observing letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.13:5.1": "There’s a time when a mendicant is breathing in heavily, and they know: ‘I’m breathing in heavily.’ Breathing out heavily they know: ‘I’m breathing out heavily.’ ",
  "sn54.13:5.2": "… ",
  "sn54.13:5.3": "They practice like this: ‘I’ll breathe in stilling the physical process.’ They practice like this: ‘I’ll breathe out stilling the physical process.’ ",
  "sn54.13:5.4": "At such a time a mendicant is meditating by observing an aspect of the bodykeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.13:5.5": "Why is that? ",
  "sn54.13:5.6": "Because the breath is a certain aspect of the body, I say. ",
  "sn54.13:5.7": "Therefore, at such a time a mendicant is meditating by observing an aspect of the bodykeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.13:6.1": "There’s a time when a mendicant practices like this: ‘I’ll breathe in experiencing rapture … ",
  "sn54.13:6.2": "bliss … ",
  "sn54.13:6.3": "mind …’ … ",
  "sn54.13:6.4": "They practice like this: ‘I’ll breathe in stilling the mental process.’ They practice like this: ‘I’ll breathe out stilling the mental process.’ ",
  "sn54.13:6.5": "At such a time a mendicant is meditating by observing an aspect of feelingskeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.13:6.6": "Why is that? ",
  "sn54.13:6.7": "Because careful application of mind to the in-breaths and out-breaths is a certain aspect of feelings, I say. ",
  "sn54.13:6.8": "Therefore, at such a time a mendicant is meditating by observing an aspect of feelingskeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.13:7.1": "There’s a time when a mendicant practices like this: ‘I’ll breathe in experiencing the mind.’ They practice like this: ‘I’ll breathe out experiencing the mind.’ ",
  "sn54.13:7.2": "They practice like this: ‘I’ll breathe in gladdening the mind … ",
  "sn54.13:7.3": "immersing the mind in samādhi … ",
  "sn54.13:7.4": "freeing the mind.’ They practice like this: ‘I’ll breathe out freeing the mind.’ ",
  "sn54.13:7.5": "At such a time a mendicant is meditating by observing an aspect of the mindkeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.13:7.6": "Why is that? ",
  "sn54.13:7.7": "Because there is no development of immersion due to mindfulness of breathing for someone who is unmindful and lacks awareness, I say. ",
  "sn54.13:7.8": "Therefore, at such a time a mendicant is meditating by observing an aspect of the mindkeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.13:8.1": "There’s a time when a mendicant practices like this: ‘I’ll breathe in observing impermanence … ",
  "sn54.13:8.2": "fading away … ",
  "sn54.13:8.3": "cessation … ",
  "sn54.13:8.4": "letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.13:8.5": "At such a time a mendicant is meditating by observing an aspect of principleskeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.13:8.6": "Having seen with wisdom the giving up of covetousness and displeasure, they watch closely over with equanimity. ",
  "sn54.13:8.7": "Therefore, at such a time a mendicant is meditating by observing an aspect of principleskeen, aware, and mindful, rid of covetousness and displeasure for the world. ",
  "sn54.13:9.1": "That’s how immersion due to mindfulness of breathing is developed and cultivated so as to fulfill the four kinds of mindfulness meditation. ",
  "sn54.13:10.1": "And how are the four kinds of mindfulness meditation developed and cultivated so as to fulfill the seven awakening factors? ",
  "sn54.13:10.2": "Whenever a mendicant meditates by observing an aspect of the body, ",
  "sn54.13:10.3": "their mindfulness is established and lucid. ",
  "sn54.13:10.4": "At such a time, a mendicant has initiated the awakening factor of mindfulness; they develop it and perfect it. ",
  "sn54.13:11.1": "As they live mindfully in this way they investigate, explore, and inquire into that principle with wisdom. ",
  "sn54.13:11.2": "At such a time, a mendicant has activated the awakening factor of investigation of principles; they develop it and perfect it. ",
  "sn54.13:11.3": "",
  "sn54.13:12.1": "As they investigate principles with wisdom in this way their energy is roused up and unflagging. ",
  "sn54.13:12.2": "At such a time, a mendicant has initiated the awakening factor of energy; they develop it and perfect it. ",
  "sn54.13:12.3": "",
  "sn54.13:13.1": "When you’re energetic, rapture not of the flesh arises. ",
  "sn54.13:13.2": "At such a time, a mendicant has initiated the awakening factor of rapture; they develop it and perfect it. ",
  "sn54.13:13.3": "",
  "sn54.13:14.1": "When the mind is full of rapture, the body and mind become tranquil. ",
  "sn54.13:14.2": "At such a time, a mendicant has activated the awakening factor of tranquility; they develop it and perfect it. ",
  "sn54.13:14.3": "",
  "sn54.13:15.1": "When the body is tranquil and one feels bliss, the mind becomes immersed in samādhi. ",
  "sn54.13:15.2": "At such a time, a mendicant has activated the awakening factor of immersion; they develop it and perfect it. ",
  "sn54.13:15.3": "",
  "sn54.13:16.1": "They closely watch over that mind immersed in samādhi. ",
  "sn54.13:16.2": "At such a time, a mendicant has activated the awakening factor of equanimity; they develop it and perfect it. ",
  "sn54.13:16.3": "",
  "sn54.13:17.1": "Whenever a mendicant meditates by observing an aspect of feelings … ",
  "sn54.13:17.2": "mind … ",
  "sn54.13:17.3": "principles, ",
  "sn54.13:17.4": "their mindfulness is established and lucid. ",
  "sn54.13:17.5": "At such a time, a mendicant has activated the awakening factor of mindfulness; they develop it and perfect it. … ",
  "sn54.13:17.6": "",
  "sn54.13:17.7": "(Tell in full as for the first kind of mindfulness meditation.) ",
  "sn54.13:18.1": "They closely watch over that mind immersed in samādhi. ",
  "sn54.13:18.2": "At such a time, a mendicant has activated the awakening factor of equanimity; they develop it and perfect it. ",
  "sn54.13:18.3": "",
  "sn54.13:18.4": "That’s how the four kinds of mindfulness meditation are developed and cultivated so as to fulfill the seven awakening factors. ",
  "sn54.13:19.1": "And how are the seven awakening factors developed and cultivated so as to fulfill knowledge and freedom? ",
  "sn54.13:19.2": "It’s when a mendicant develops the awakening factors of mindfulness, ",
  "sn54.13:19.3": "investigation of principles, energy, rapture, tranquility, immersion, ",
  "sn54.13:19.4": "and equanimity, which rely on seclusion, fading away, and cessation, and ripen as letting go. ",
  "sn54.13:19.5": "That’s how the seven awakening factors are developed and cultivated so as to fulfill knowledge and freedom.” ",
  "sn54.14:0.1": "Linked Discourses 54.14 ",
  "sn54.14:0.2": "Chapter Two ",
  "sn54.14:0.3": "With Ānanda (2nd) ",
  "sn54.14:1.1": "Then Venerable Ānanda went up to the Buddha, bowed, and sat down to one side. The Buddha said to him: ",
  "sn54.14:1.2": "“Ānanda, is there one thing that, when developed and cultivated, fulfills four things; and those four things, when developed and cultivated, fulfill seven things; and those seven things, when developed and cultivated, fulfill two things?” ",
  "sn54.14:1.3": "“Our teachings are rooted in the Buddha. …” ",
  "sn54.14:1.4": "“There is, Ānanda. ",
  "sn54.14:2.1": "And what is that one thing? ",
  "sn54.14:2.2": "Immersion due to mindfulness of breathing is one thing that, when developed and cultivated, fulfills the four kinds of mindfulness meditation. And the four kinds of mindfulness meditation, when developed and cultivated, fulfill the seven awakening factors. And the seven awakening factors, when developed and cultivated, fulfill knowledge and freedom. ",
  "sn54.14:2.3": "And how is mindfulness of breathing developed and cultivated so as to fulfill the four kinds of mindfulness meditation? … ",
  "sn54.14:2.4": "",
  "sn54.14:2.5": "That’s how the seven awakening factors are developed and cultivated so as to fulfill knowledge and freedom.” ",
  "sn54.15:0.1": "Linked Discourses 54.15 ",
  "sn54.15:0.2": "Chapter Two ",
  "sn54.15:0.3": "Several Mendicants (1st) ",
  "sn54.15:1.1": "Then several mendicants went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn54.15:1.2": "“Sir, is there one thing that, when developed and cultivated, fulfills four things; and those four things, when developed and cultivated, fulfill seven things; and those seven things, when developed and cultivated, fulfill two things?” ",
  "sn54.15:1.3": "“There is, mendicants.” ",
  "sn54.15:2.1": "“Sir, what is that one thing?” ",
  "sn54.15:2.2": "“Immersion due to mindfulness of breathing is one thing that, when developed and cultivated, fulfills the four kinds of mindfulness meditation. And the four kinds of mindfulness meditation, when developed and cultivated, fulfill the seven awakening factors. And the seven awakening factors, when developed and cultivated, fulfill knowledge and freedom. ",
  "sn54.15:3.1": "And how is mindfulness of breathing developed and cultivated so as to fulfill the four kinds of mindfulness meditation? … ",
  "sn54.15:3.2": "",
  "sn54.15:3.3": "That’s how the seven awakening factors are developed and cultivated so as to fulfill knowledge and freedom.” ",
  "sn54.16:0.1": "Linked Discourses 54.16 ",
  "sn54.16:0.2": "Chapter Two ",
  "sn54.16:0.3": "Several Mendicants (2nd) ",
  "sn54.16:1.1": "Then several mendicants went up to the Buddha, bowed, and sat down to one side. The Buddha said to them: ",
  "sn54.16:1.2": "“Mendicants, is there one thing that, when developed and cultivated, fulfills four things; and those four things, when developed and cultivated, fulfill seven things; and those seven things, when developed and cultivated, fulfill two things?” ",
  "sn54.16:1.3": "“Our teachings are rooted in the Buddha. …” ",
  "sn54.16:1.4": "“There is, mendicants. ",
  "sn54.16:2.1": "And what is that one thing? ",
  "sn54.16:2.2": "Immersion due to mindfulness of breathing is one thing that, when developed and cultivated, fulfills the four kinds of mindfulness meditation. And the four kinds of mindfulness meditation, when developed and cultivated, fulfill the seven awakening factors. And the seven awakening factors, when developed and cultivated, fulfill knowledge and freedom. ",
  "sn54.16:3.1": "And how is mindfulness of breathing developed and cultivated so as to fulfill the four kinds of mindfulness meditation? ",
  "sn54.16:3.2": "It’s when a mendicantgone to a wilderness, or to the root of a tree, or to an empty hutsits down cross-legged, sets their body straight, and brings mindfulness to the present. … ",
  "sn54.16:3.3": "",
  "sn54.16:3.4": "",
  "sn54.16:4.1": "",
  "sn54.16:4.2": "",
  "sn54.16:4.3": "",
  "sn54.16:4.4": "",
  "sn54.16:4.5": "",
  "sn54.16:4.6": "",
  "sn54.16:4.7": "",
  "sn54.16:5.1": "",
  "sn54.16:5.2": "",
  "sn54.16:5.3": "",
  "sn54.16:5.4": "",
  "sn54.16:5.5": "",
  "sn54.16:5.6": "",
  "sn54.16:5.7": "",
  "sn54.16:5.8": "",
  "sn54.16:6.1": "",
  "sn54.16:6.2": "",
  "sn54.16:6.3": "",
  "sn54.16:6.4": "",
  "sn54.16:6.5": "",
  "sn54.16:6.6": "",
  "sn54.16:6.7": "",
  "sn54.16:6.8": "",
  "sn54.16:7.1": "",
  "sn54.16:7.2": "",
  "sn54.16:7.3": "",
  "sn54.16:7.4": "",
  "sn54.16:7.5": "",
  "sn54.16:7.6": "",
  "sn54.16:7.7": "",
  "sn54.16:8.1": "",
  "sn54.16:9.1": "",
  "sn54.16:9.2": "",
  "sn54.16:9.3": "",
  "sn54.16:9.4": "",
  "sn54.16:10.1": "",
  "sn54.16:10.2": "",
  "sn54.16:10.3": "",
  "sn54.16:11.1": "",
  "sn54.16:11.2": "",
  "sn54.16:11.3": "",
  "sn54.16:12.1": "",
  "sn54.16:12.2": "",
  "sn54.16:12.3": "",
  "sn54.16:13.1": "",
  "sn54.16:13.2": "",
  "sn54.16:13.3": "",
  "sn54.16:14.1": "",
  "sn54.16:14.2": "",
  "sn54.16:14.3": "",
  "sn54.16:15.1": "",
  "sn54.16:15.2": "",
  "sn54.16:15.3": "",
  "sn54.16:16.1": "",
  "sn54.16:16.2": "",
  "sn54.16:16.3": "",
  "sn54.16:16.4": "",
  "sn54.16:16.5": "",
  "sn54.16:17.1": "",
  "sn54.16:17.2": "",
  "sn54.16:17.3": "",
  "sn54.16:17.4": "",
  "sn54.16:18.1": "",
  "sn54.16:18.2": "",
  "sn54.16:18.3": "",
  "sn54.16:18.4": "",
  "sn54.16:18.5": "That’s how the seven awakening factors are developed and cultivated so as to fulfill knowledge and freedom.” ",
  "sn54.17:0.1": "Linked Discourses 54.17 ",
  "sn54.17:0.2": "Chapter Two ",
  "sn54.17:0.3": "Giving Up the Fetters ",
  "sn54.17:1.1": "“Mendicants, when immersion due to mindfulness of breathing is developed and cultivated it leads to giving up the fetters …” ",
  "sn54.18:0.1": "Linked Discourses 54.18 ",
  "sn54.18:0.2": "Chapter Two ",
  "sn54.18:0.3": "Uprooting the Tendencies ",
  "sn54.18:1.1": "“Mendicants, when immersion due to mindfulness of breathing is developed and cultivated it leads to uprooting the underlying tendencies …” ",
  "sn54.19:0.1": "Linked Discourses 54.19 ",
  "sn54.19:0.2": "Chapter Two ",
  "sn54.19:0.3": "Completely Understanding the Course of Time ",
  "sn54.19:1.1": "“Mendicants, when immersion due to mindfulness of breathing is developed and cultivated it leads to completely understanding the course of time …” ",
  "sn54.20:0.1": "Linked Discourses 54.20 ",
  "sn54.20:0.2": "Chapter Two ",
  "sn54.20:0.3": "The Ending of Defilements ",
  "sn54.20:1.1": "“Mendicants, when immersion due to mindfulness of breathing is developed and cultivated it leads to the ending of defilements. ",
  "sn54.20:1.2": "And how is immersion due to mindfulness of breathing developed and cultivated so as to lead to giving up the fetters, ",
  "sn54.20:1.3": "uprooting the underlying tendencies, ",
  "sn54.20:1.4": "completely understanding the course of time, ",
  "sn54.20:1.5": "and ending the defilements? ",
  "sn54.20:1.6": "It’s when a mendicantgone to a wilderness, or to the root of a tree, or to an empty hutsits down cross-legged, sets their body straight, and establishes mindfulness in front of them. … ",
  "sn54.20:1.7": "They practice like this: ‘I’ll breathe in observing letting go.’ They practice like this: ‘I’ll breathe out observing letting go.’ ",
  "sn54.20:1.8": "That’s how immersion due to mindfulness of breathing is developed and cultivated so as to lead to giving up the fetters, ",
  "sn54.20:1.9": "uprooting the underlying tendencies, ",
  "sn54.20:1.10": "completely understanding the course of time, ",
  "sn54.20:1.11": "and ending the defilements.” ",
  "sn54.20:1.12": "",
  "sn54.20:1.13": "",
  "sn54.20:2.1": "",
  "sn54.20:2.2": "",
  "sn54.20:2.3": "",
  "sn54.20:2.4": "",
  "sn54.20:2.5": "The Linked Discourses on Mindfulness of Breathing is the tenth section. "
}
window.BILARA["sn54_v1"]["en"]["sn54_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
