window.BILARA = window.BILARA || {};
window.BILARA["sn5_v1"] = window.BILARA["sn5_v1"] || {};
window.BILARA["sn5_v1"]["en"] = {
  "sn5.1:0.1": "Linked Discourses 5.1 ",
  "sn5.1:0.2": "1. Nuns ",
  "sn5.1:0.3": "With Āḷavikā ",
  "sn5.1:1.1": "So I have heard. ",
  "sn5.1:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn5.1:1.3": "Then the nun Āḷavikā robed up in the morning and, taking her bowl and robe, entered Sāvatthī for alms. ",
  "sn5.1:1.4": "She wandered for alms in Sāvatthī. After the meal, on her return from almsround, she went to the Dark Forest seeking seclusion. ",
  "sn5.1:1.5": "Then Māra the Wicked, wanting to make the nun Āḷavikā feel fear, terror, and goosebumps, wanting to make her fall away from seclusion, went up to her and addressed her in verse: ",
  "sn5.1:2.1": "“There’s no escape in the world, ",
  "sn5.1:2.2": "so what will seclusion do for you? ",
  "sn5.1:2.3": "Enjoy erotic delights; ",
  "sn5.1:2.4": "don’t regret it later.” ",
  "sn5.1:3.1": "Then the nun Āḷavikā thought, ",
  "sn5.1:3.2": "“Who’s speaking this verse, a human or a non-human?” ",
  "sn5.1:3.3": "Then she thought, ",
  "sn5.1:3.4": "“This is Māra the Wicked, wanting to make me feel fear, terror, and goosebumps, wanting to make me fall away from seclusion!” ",
  "sn5.1:3.5": "Then Āḷavikā, knowing that this was Māra the Wicked, replied to him in verse: ",
  "sn5.1:4.1": "“There is an escape in the world, ",
  "sn5.1:4.2": "and I’ve personally experienced it with wisdom. ",
  "sn5.1:4.3": "O Wicked One, kinsman of the negligent, ",
  "sn5.1:4.4": "you don’t know that state. ",
  "sn5.1:5.1": "Sensual pleasures are like swords and spears; ",
  "sn5.1:5.2": "the aggregates are their chopping block. ",
  "sn5.1:5.3": "What you call erotic delight ",
  "sn5.1:5.4": "is now no delight for me.” ",
  "sn5.1:6.1": "Then Māra the Wicked, thinking, “The nun Āḷavikā knows me!” miserable and sad, vanished right there. ",
  "sn5.2:0.1": "Linked Discourses 5.2 ",
  "sn5.2:0.2": "1. Nuns ",
  "sn5.2:0.3": "With Somā ",
  "sn5.2:1.1": "At Sāvatthī. ",
  "sn5.2:1.2": "Then the nun Somā robed up in the morning and, taking her bowl and robe, entered Sāvatthī for alms. ",
  "sn5.2:1.3": "She wandered for alms in Sāvatthī. After the meal, on her return from almsround, she went to the Dark Forest for the day’s meditation, ",
  "sn5.2:1.4": "plunged deep into it, and sat at the root of a tree to meditate. ",
  "sn5.2:1.5": "Then Māra the Wicked, wanting to make the nun Somā feel fear, terror, and goosebumps, wanting to make her fall away from immersion, went up to her and addressed her in verse: ",
  "sn5.2:2.1": "“That state’s very challenging; ",
  "sn5.2:2.2": "it’s for the sages to attain. ",
  "sn5.2:2.3": "With her two-inch wisdom, ",
  "sn5.2:2.4": "it’s not possible for a woman.” ",
  "sn5.2:3.1": "Then the nun Somā thought, ",
  "sn5.2:3.2": "“Who’s speaking this verse, a human or a non-human?” ",
  "sn5.2:3.3": "Then she thought, ",
  "sn5.2:3.4": "“This is Māra the Wicked, wanting to make me feel fear, terror, and goosebumps, wanting to make me fall away from immersion!” ",
  "sn5.2:3.5": "Then Somā, knowing that this was Māra the Wicked, replied to him in verse: ",
  "sn5.2:4.1": "“What difference does womanhood make ",
  "sn5.2:4.2": "when the mind is serene, ",
  "sn5.2:4.3": "and knowledge is present ",
  "sn5.2:4.4": "as you rightly discern the Dhamma. ",
  "sn5.2:5.1": "Surely someone who might think: ",
  "sn5.2:5.2": "‘I am woman’, or ‘I am man’, ",
  "sn5.2:5.3": "or ‘I am’ anything at all, ",
  "sn5.2:5.4": "is fit for Māra to address.” ",
  "sn5.2:6.1": "Then Māra the Wicked, thinking, “The nun Somā knows me!” miserable and sad, vanished right there. ",
  "sn5.3:0.1": "Linked Discourses 5.3 ",
  "sn5.3:0.2": "1. Nuns ",
  "sn5.3:0.3": "With Kisāgotamī ",
  "sn5.3:1.1": "At Sāvatthī. ",
  "sn5.3:1.2": "Then the nun Kisāgotamī robed up in the morning and, taking her bowl and robe, entered Sāvatthī for alms. ",
  "sn5.3:1.3": "She wandered for alms in Sāvatthī. After the meal, on her return from almsround, she went to the Dark Forest for the day’s meditation, ",
  "sn5.3:1.4": "plunged deep into it, and sat at the root of a tree to meditate. ",
  "sn5.3:1.5": "Then Māra the Wicked, wanting to make the nun Kisāgotamī feel fear, terror, and goosebumps, wanting to make her fall away from immersion, went up to her and addressed her in verse: ",
  "sn5.3:2.1": "“Why do you sit alone and cry ",
  "sn5.3:2.2": "as if your children have died? ",
  "sn5.3:2.3": "You’ve come to the woods all alone",
  "sn5.3:2.4": "are you looking for a man?” ",
  "sn5.3:3.1": "Then the nun Kisāgotamī thought, ",
  "sn5.3:3.2": "“Who’s speaking this verse, a human or a non-human?” ",
  "sn5.3:3.3": "Then she thought, ",
  "sn5.3:3.4": "“This is Māra the Wicked, wanting to make me feel fear, terror, and goosebumps, wanting to make me fall away from immersion!” ",
  "sn5.3:4.1": "Then Kisāgotamī, knowing that this was Māra the Wicked, replied to him in verse: ",
  "sn5.3:5.1": "“I’ve got over the death of children, ",
  "sn5.3:5.2": "and I’m finished with men. ",
  "sn5.3:5.3": "I don’t grieve or lament, ",
  "sn5.3:5.4": "and I’m not afraid of you, sir! ",
  "sn5.3:6.1": "Relishing is banished in every respect, ",
  "sn5.3:6.2": "and the mass of darkness is shattered. ",
  "sn5.3:6.3": "I’ve defeated the army of death, ",
  "sn5.3:6.4": "and live without defilements.” ",
  "sn5.3:7.1": "Then Māra the Wicked, thinking, “The nun Kisāgotamī knows me!” miserable and sad, vanished right there. ",
  "sn5.4:0.1": "Linked Discourses 5.4 ",
  "sn5.4:0.2": "1. Nuns ",
  "sn5.4:0.3": "With Vijayā ",
  "sn5.4:1.1": "At Sāvatthī. ",
  "sn5.4:1.2": "Then the nun Vijayā robed up in the morning … ",
  "sn5.4:1.3": "and sat at the root of a tree for the day’s meditation. ",
  "sn5.4:1.4": "Then Māra the Wicked, wanting to make the nun Vijayā feel fear, terror, and goosebumps, wanting to make her fall away from immersion, went up to her and addressed her in verse: ",
  "sn5.4:2.1": "“You’re so young and beautiful, ",
  "sn5.4:2.2": "and I’m a youth in my prime. ",
  "sn5.4:2.3": "Come, my lady, let us enjoy ",
  "sn5.4:2.4": "the music of a five-piece band.” ",
  "sn5.4:3.1": "Then the nun Vijayā thought, ",
  "sn5.4:3.2": "“Who’s speaking this verse, a human or a non-human?” ",
  "sn5.4:3.3": "Then she thought, ",
  "sn5.4:3.4": "“This is Māra the Wicked, wanting to make me feel fear, terror, and goosebumps, wanting to make me fall away from immersion!” ",
  "sn5.4:3.5": "Then Vijayā, knowing that this was Māra the Wicked, replied to him in verse: ",
  "sn5.4:4.1": "“Sights, sounds, tastes, smells, ",
  "sn5.4:4.2": "and touches so delightful. ",
  "sn5.4:4.3": "I hand them right back to you, Māra, ",
  "sn5.4:4.4": "for I have no use for them. ",
  "sn5.4:5.1": "This body is rotting, ",
  "sn5.4:5.2": "decaying and frail. ",
  "sn5.4:5.3": "I’m horrified and repelled by it, ",
  "sn5.4:5.4": "and I’ve eradicated sensual craving. ",
  "sn5.4:6.1": "There are beings in the realm of luminous form, ",
  "sn5.4:6.2": "and others stuck in the formless. ",
  "sn5.4:6.3": "I’ve destroyed the darkness ",
  "sn5.4:6.4": "regarding all such peaceful attainments.” ",
  "sn5.4:7.1": "Then Māra the Wicked, thinking, “The nun Vijayā knows me!” miserable and sad, vanished right there. ",
  "sn5.5:0.1": "Linked Discourses 5.5 ",
  "sn5.5:0.2": "1. Nuns ",
  "sn5.5:0.3": "With Uppalavaṇṇā ",
  "sn5.5:1.1": "At Sāvatthī. ",
  "sn5.5:1.2": "Then the nun Uppalavaṇṇā robed up in the morning … ",
  "sn5.5:1.3": "and stood at the root of a sal tree in full flower. ",
  "sn5.5:1.4": "Then Māra the Wicked, wanting to make the nun Uppalavaṇṇā feel fear, terror, and goosebumps, wanting to make her fall away from immersion, went up to her and addressed her in verse: ",
  "sn5.5:2.1": "“You’ve come to this sal tree all crowned with flowers, ",
  "sn5.5:2.2": "and stand at its root all alone, O nun. ",
  "sn5.5:2.3": "Your beauty is second to none ",
  "sn5.5:2.4": "silly girl, aren’t you afraid of rascals?” ",
  "sn5.5:3.1": "Then the nun Uppalavaṇṇā thought, ",
  "sn5.5:3.2": "“Who’s speaking this verse, a human or a non-human?” ",
  "sn5.5:3.3": "Then she thought, ",
  "sn5.5:3.4": "“This is Māra the Wicked, wanting to make me feel fear, terror, and goosebumps, wanting to make me fall away from immersion!” ",
  "sn5.5:3.5": "Then Uppalavaṇṇā, knowing that this was Māra the Wicked, replied to him in verse: ",
  "sn5.5:4.1": "“Even if 100,000 rascals like you ",
  "sn5.5:4.2": "were to come here, ",
  "sn5.5:4.3": "I’d stir not a hair nor panic. ",
  "sn5.5:4.4": "I’m not scared of you, Māra, even alone. ",
  "sn5.5:5.1": "I’ll vanish, ",
  "sn5.5:5.2": "or I’ll enter your belly; ",
  "sn5.5:5.3": "I could stand between your eyebrows ",
  "sn5.5:5.4": "and you still wouldn’t see me. ",
  "sn5.5:6.1": "I’m the master of my own mind, ",
  "sn5.5:6.2": "I’ve developed the bases of psychic power well. ",
  "sn5.5:6.3": "I’m free from all bonds, ",
  "sn5.5:6.4": "and I’m not afraid of you, sir!” ",
  "sn5.5:7.1": "Then Māra the Wicked, thinking, “The nun Uppalavaṇṇā knows me!” miserable and sad, vanished right there. ",
  "sn5.6:0.1": "Linked Discourses 5.6 ",
  "sn5.6:0.2": "1. Nuns ",
  "sn5.6:0.3": "With Cālā ",
  "sn5.6:1.1": "At Sāvatthī. ",
  "sn5.6:1.2": "Then the nun Cālā robed up in the morning … ",
  "sn5.6:1.3": "and sat at the root of a tree for the day’s meditation. ",
  "sn5.6:1.4": "Then Māra the Wicked went up to Cālā and said to her, ",
  "sn5.6:1.5": "“Nun, what don’t you approve of?” ",
  "sn5.6:1.6": "“I don’t approve of rebirth, sir.” ",
  "sn5.6:2.1": "“Why don’t you approve of rebirth? ",
  "sn5.6:2.2": "When you’re born, you get to enjoy sensual pleasures. ",
  "sn5.6:2.3": "Who put this idea in your head: ",
  "sn5.6:2.4": "‘Nun, don’t approve of rebirth’?” ",
  "sn5.6:3.1": "“Death comes to those who are born, ",
  "sn5.6:3.2": "when you’re born you undergo sufferings",
  "sn5.6:3.3": "killing, caging, misery",
  "sn5.6:3.4": "that’s why you shouldn’t approve of rebirth. ",
  "sn5.6:4.1": "The Buddha taught me the Dhamma ",
  "sn5.6:4.2": "for transcending rebirth, ",
  "sn5.6:4.3": "for giving up all suffering; ",
  "sn5.6:4.4": "he settled me in the truth. ",
  "sn5.6:5.1": "There are beings in the realm of luminous form, ",
  "sn5.6:5.2": "and others stuck in the formless. ",
  "sn5.6:5.3": "Not understanding cessation, ",
  "sn5.6:5.4": "they return in future lives.” ",
  "sn5.6:6.1": "Then Māra the Wicked, thinking, “The nun Cālā knows me!” miserable and sad, vanished right there. ",
  "sn5.7:0.1": "Linked Discourses 5.7 ",
  "sn5.7:0.2": "1. Nuns ",
  "sn5.7:0.3": "With Upacālā ",
  "sn5.7:1.1": "At Sāvatthī. ",
  "sn5.7:1.2": "Then the nun Upacālā robed up in the morning … ",
  "sn5.7:1.3": "and sat at the root of a tree for the day’s meditation. ",
  "sn5.7:1.4": "Then Māra the Wicked went up to Upacālā and said to her, ",
  "sn5.7:1.5": "“Nun, where do you want to be reborn?” ",
  "sn5.7:1.6": "“I don’t want to be reborn anywhere, sir.” ",
  "sn5.7:2.1": "“There are the gods of the thirty-three, <j>and those of Yama; ",
  "sn5.7:2.2": "also the Joyful Deities, ",
  "sn5.7:2.3": "the gods who love to create, ",
  "sn5.7:2.4": "and the gods who control that imagined by others. ",
  "sn5.7:2.5": "Set your heart on such places, ",
  "sn5.7:2.6": "and you’ll undergo delight.” ",
  "sn5.7:3.1": "“The gods of the thirty-three, <j>and those of Yama; ",
  "sn5.7:3.2": "also the Joyful Deities, ",
  "sn5.7:3.3": "the gods who love to create, ",
  "sn5.7:3.4": "and the gods who control that imagined by others",
  "sn5.7:3.5": "they’re bound with the bonds of sensuality; ",
  "sn5.7:3.6": "they fall under your sway again. ",
  "sn5.7:4.1": "All the world is on fire, ",
  "sn5.7:4.2": "all the world is smoldering, ",
  "sn5.7:4.3": "all the world is ablaze, ",
  "sn5.7:4.4": "all the world is rocking. ",
  "sn5.7:5.1": "My mind adores that place ",
  "sn5.7:5.2": "where Māra cannot go; ",
  "sn5.7:5.3": "it’s not shaking or burning, ",
  "sn5.7:5.4": "and not frequented by ordinary people.” ",
  "sn5.7:6.1": "Then Māra the Wicked, thinking, “The nun Upacālā knows me!” miserable and sad, vanished right there. ",
  "sn5.8:0.1": "Linked Discourses 5.8 ",
  "sn5.8:0.2": "1. Nuns ",
  "sn5.8:0.3": "With Sīsupacālā ",
  "sn5.8:1.1": "At Sāvatthī. ",
  "sn5.8:1.2": "Then the nun Sīsupacālā robed up in the morning … ",
  "sn5.8:1.3": "and sat at the root of a tree for the day’s meditation. ",
  "sn5.8:1.4": "Then Māra the Wicked went up to Sīsupacālā and said to her, ",
  "sn5.8:1.5": "“Nun, whose creed do you approve of?” ",
  "sn5.8:1.6": "“I don’t approve anyone’s creed, sir.” ",
  "sn5.8:2.1": "“In whose name did you shave your head? ",
  "sn5.8:2.2": "You look like an ascetic, ",
  "sn5.8:2.3": "but you don’t approve any creed. ",
  "sn5.8:2.4": "Why do you wander as if lost?” ",
  "sn5.8:3.1": "“Followers of other creeds ",
  "sn5.8:3.2": "are confident in their views. ",
  "sn5.8:3.3": "But I don’t approve their teaching, ",
  "sn5.8:3.4": "for they’re no experts in the Dhamma. ",
  "sn5.8:4.1": "But there is one born in the Sakyan clan, ",
  "sn5.8:4.2": "the unrivaled Buddha, ",
  "sn5.8:4.3": "champion, dispeller of Māra, ",
  "sn5.8:4.4": "everywhere undefeated, ",
  "sn5.8:5.1": "everywhere freed, and unattached, ",
  "sn5.8:5.2": "the Clear-eyed One sees all. ",
  "sn5.8:5.3": "He has attained the end of all deeds, ",
  "sn5.8:5.4": "freed with the ending of attachments. ",
  "sn5.8:5.5": "That Blessed One is my Teacher, ",
  "sn5.8:5.6": "and I approve his instruction.” ",
  "sn5.8:6.1": "Then Māra the Wicked, thinking, “The nun Sīsupacālā knows me!” miserable and sad, vanished right there. ",
  "sn5.9:0.1": "Linked Discourses 5.9 ",
  "sn5.9:0.2": "1. Nuns ",
  "sn5.9:0.3": "With Selā ",
  "sn5.9:1.1": "At Sāvatthī. ",
  "sn5.9:1.2": "Then the nun Selā robed up in the morning … ",
  "sn5.9:1.3": "and sat at the root of a tree for the day’s meditation. ",
  "sn5.9:1.4": "Then Māra the Wicked, wanting to make the nun Selā feel fear, terror, and goosebumps … ",
  "sn5.9:1.5": "addressed her in verse: ",
  "sn5.9:2.1": "“Who created this puppet? ",
  "sn5.9:2.2": "Where is its maker? ",
  "sn5.9:2.3": "Where has the puppet arisen? ",
  "sn5.9:2.4": "And where does it cease?” ",
  "sn5.9:3.1": "Then the nun Selā thought, ",
  "sn5.9:3.2": "“Who’s speaking this verse, a human or a non-human?” ",
  "sn5.9:3.3": "Then she thought, ",
  "sn5.9:3.4": "“This is Māra the Wicked, wanting to make me feel fear, terror, and goosebumps, wanting to make me fall away from immersion!” ",
  "sn5.9:3.5": "Then Selā, knowing that this was Māra the Wicked, replied to him in verse: ",
  "sn5.9:4.1": "“This puppet isn’t self-made, ",
  "sn5.9:4.2": "nor is this gloom made by another. ",
  "sn5.9:4.3": "It comes to be because of a cause, ",
  "sn5.9:4.4": "and ceases when the cause breaks up. ",
  "sn5.9:5.1": "It’s like a seed that’s sown ",
  "sn5.9:5.2": "in a field; it grows ",
  "sn5.9:5.3": "relying on both the soil’s nutrients ",
  "sn5.9:5.4": "as well as moisture. ",
  "sn5.9:6.1": "In the same way the aggregates and elements ",
  "sn5.9:6.2": "and these six sense fields ",
  "sn5.9:6.3": "come to be because of a cause, ",
  "sn5.9:6.4": "and cease when the cause breaks up.” ",
  "sn5.9:7.1": "Then Māra the Wicked, thinking, “The nun Selā knows me!” miserable and sad, vanished right there. ",
  "sn5.10:0.1": "Linked Discourses 5.10 ",
  "sn5.10:0.2": "1. Nuns ",
  "sn5.10:0.3": "With Vajirā ",
  "sn5.10:1.1": "At Sāvatthī. ",
  "sn5.10:1.2": "Then the nun Vajirā robed up in the morning and, taking her bowl and robe, entered Sāvatthī for alms. ",
  "sn5.10:1.3": "She wandered for alms in Sāvatthī. After the meal, on her return from almsround, she went to the Dark Forest for the day’s meditation, ",
  "sn5.10:1.4": "plunged deep into it, and sat at the root of a tree to meditate. ",
  "sn5.10:1.5": "Then Māra the Wicked, wanting to make the nun Vajirā feel fear, terror, and goosebumps, wanting to make her fall away from immersion, went up to her and addressed her in verse: ",
  "sn5.10:2.1": "“Who created this sentient being? ",
  "sn5.10:2.2": "Where is its maker? ",
  "sn5.10:2.3": "Where has the being arisen? ",
  "sn5.10:2.4": "And where does it cease?” ",
  "sn5.10:3.1": "Then the nun Vajirā thought, ",
  "sn5.10:3.2": "“Who’s speaking this verse, a human or a non-human?” ",
  "sn5.10:3.3": "Then she thought, ",
  "sn5.10:3.4": "“This is Māra the Wicked, wanting to make me feel fear, terror, and goosebumps, wanting to make me fall away from immersion!” ",
  "sn5.10:3.5": "Then Vajirā, knowing that this was Māra the Wicked, replied to him in verse: ",
  "sn5.10:4.1": "“Why do you believe there’s such a thing as a <j>‘sentient being’? ",
  "sn5.10:4.2": "Māra, is this your theory? ",
  "sn5.10:4.3": "This is just a pile of conditions, ",
  "sn5.10:4.4": "you won’t find a sentient being here. ",
  "sn5.10:5.1": "When the parts are assembled ",
  "sn5.10:5.2": "we use the word ‘chariot’. ",
  "sn5.10:5.3": "So too, when the aggregates are present ",
  "sn5.10:5.4": "‘sentient being’ is the convention we use. ",
  "sn5.10:6.1": "But it’s only suffering that comes to be, ",
  "sn5.10:6.2": "lasts a while, then expires. ",
  "sn5.10:6.3": "Naught but suffering comes to be, ",
  "sn5.10:6.4": "naught but suffering ceases.” ",
  "sn5.10:7.1": "Then Māra the Wicked, thinking, “The nun Vajirā knows me!” miserable and sad, vanished right there. ",
  "sn5.10:7.2": "",
  "sn5.10:8.1": "",
  "sn5.10:8.2": "",
  "sn5.10:8.3": "",
  "sn5.10:8.4": "",
  "sn5.10:8.5": "",
  "sn5.10:8.6": "The Linked Discourses on Nuns are completed. "
}
window.BILARA["sn5_v1"]["en"]["sn5_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
