window.BILARA = window.BILARA || {};
window.BILARA["sn8_v1"] = window.BILARA["sn8_v1"] || {};
window.BILARA["sn8_v1"]["en"] = {
  "sn8.1:0.1": "Linked Discourses 8.1 ",
  "sn8.1:0.2": "1. With Vaṅgīsa ",
  "sn8.1:0.3": "Renounced ",
  "sn8.1:1.1": "So I have heard. ",
  "sn8.1:1.2": "At one time Venerable Vaṅgīsa was staying near Āḷavī, at Āḷavī’s premier shrine, together with his mentor, Venerable Nigrodhakappa. ",
  "sn8.1:1.3": "Now at that time Vaṅgīsa was junior, recently gone forth. He had been left behind to look after the dwelling. ",
  "sn8.1:1.4": "Then several women dressed in all their finery went to the monastery at Āḷavī’s premier shrine in order to inspect the dwelling. ",
  "sn8.1:1.5": "When Vaṅgīsa saw them he became dissatisfied, with lust infecting his mind. ",
  "sn8.1:1.6": "Then he thought, ",
  "sn8.1:1.7": "“It’s my loss, my misfortune, ",
  "sn8.1:1.8": "that I’ve become dissatisfied, with lust infecting my mind. How is it possible for someone else to dispel my discontent and give rise to satisfaction? ",
  "sn8.1:1.9": "Why don’t I do it myself?” ",
  "sn8.1:1.10": "Then, on the occasion of dispelling his own discontent and giving rise to satisfaction, he recited these verses: ",
  "sn8.1:2.1": "“Now that I’ve renounced ",
  "sn8.1:2.2": "the home life for homelessness ",
  "sn8.1:2.3": "I’m overrun ",
  "sn8.1:2.4": "by the rude thoughts of the Dark One. ",
  "sn8.1:3.1": "Even if a thousand warrior chiefs and great archers, ",
  "sn8.1:3.2": "well trained, with strong bows, ",
  "sn8.1:3.3": "were to completely surround me; ",
  "sn8.1:3.4": "I would never flee. ",
  "sn8.1:4.1": "And even if women come, ",
  "sn8.1:4.2": "many more than that, ",
  "sn8.1:4.3": "they won’t bother me, ",
  "sn8.1:4.4": "for I stand firm in the teaching. ",
  "sn8.1:5.1": "I heard with my own ears ",
  "sn8.1:5.2": "from the Buddha, Kinsman of the Sun, ",
  "sn8.1:5.3": "about the path going to extinguishment; ",
  "sn8.1:5.4": "that’s what delights my mind. ",
  "sn8.1:6.1": "Wicked One, if you come near me ",
  "sn8.1:6.2": "as I meditate like this, ",
  "sn8.1:6.3": "I’ll make sure that you, Death, ",
  "sn8.1:6.4": "won’t even see the path I take.” ",
  "sn8.2:0.1": "Linked Discourses 8.2 ",
  "sn8.2:0.2": "1. With Vaṅgīsa ",
  "sn8.2:0.3": "Dissatisfaction ",
  "sn8.2:1.1": "At one time Venerable Vaṅgīsa was staying near Āḷavī, at Āḷavī’s premier shrine, together with his mentor, Venerable Nigrodhakappa. ",
  "sn8.2:1.2": "Now at that time after Venerable Nigrodhakappa had finished his meal, on his return from almsround, he would enter his dwelling and not emerge for the rest of that day, or the next. ",
  "sn8.2:1.3": "And at that time Venerable Vaṅgīsa became dissatisfied, as lust infected his mind. ",
  "sn8.2:1.4": "Then he thought, ",
  "sn8.2:1.5": "“It’s my loss, my misfortune, ",
  "sn8.2:1.6": "that I’ve become dissatisfied, with lust infecting my mind. How is it possible for someone else to dispel my discontent and give rise to satisfaction? ",
  "sn8.2:1.7": "Why don’t I do it myself?” ",
  "sn8.2:1.8": "Then, on the occasion of dispelling his own discontent and giving rise to satisfaction, he recited these verses: ",
  "sn8.2:2.1": "“Giving up desire and discontent, ",
  "sn8.2:2.2": "along with all thoughts of domestic life, ",
  "sn8.2:2.3": "they wouldn’t get snarled in anything; ",
  "sn8.2:2.4": "unsnarled, undesiring: that’s a real mendicant. ",
  "sn8.2:3.1": "Whatever here is included in form",
  "sn8.2:3.2": "on earth, in the sky, or in planet’s deep",
  "sn8.2:3.3": "wears out, it is all impermanent: ",
  "sn8.2:3.4": "the self-examined live having comprehended this. ",
  "sn8.2:4.1": "People are bound to their attachments, ",
  "sn8.2:4.2": "to impingement of the seen and heard, <j>and to what is thought. ",
  "sn8.2:4.3": "Unstirred, dispel desire for these things; ",
  "sn8.2:4.4": "for one called ‘a sage’ does not cling to them. ",
  "sn8.2:5.1": "Trapped in the sixty wrong views, <j>full of their own opinions, ",
  "sn8.2:5.2": "ordinary people are fixed in wrong principles. ",
  "sn8.2:5.3": "But that mendicant wouldn’t join a sect, ",
  "sn8.2:5.4": "still less would they utter lewd speech. ",
  "sn8.2:6.1": "Clever, serene for a long time, ",
  "sn8.2:6.2": "free of deceit, alert, without envy, ",
  "sn8.2:6.3": "the sage has reached the state of peace; ",
  "sn8.2:6.4": "quenched, he awaits his time.” ",
  "sn8.3:0.1": "Linked Discourses 8.3 ",
  "sn8.3:0.2": "1. With Vaṅgīsa ",
  "sn8.3:0.3": "Good-Hearted ",
  "sn8.3:1.1": "At one time Venerable Vaṅgīsa was staying near Āḷavī, at Āḷavī’s premier shrine, together with his mentor, Venerable Nigrodhakappa. ",
  "sn8.3:1.2": "Now at that time Venerable Vaṅgīsa looked down upon other good-hearted mendicants because of his own poetic virtuosity. ",
  "sn8.3:1.3": "Then he thought, ",
  "sn8.3:1.4": "“It’s my loss, my misfortune, ",
  "sn8.3:1.5": "that I look down on other good-hearted mendicants because of my own poetic virtuosity.” ",
  "sn8.3:1.6": "Then, on the occasion of arousing remorse in himself, he recited these verses: ",
  "sn8.3:2.1": "“Give up conceit, Gotama! ",
  "sn8.3:2.2": "Completely abandon the different kinds of conceit! ",
  "sn8.3:2.3": "Besotted with the different kinds of conceit, ",
  "sn8.3:2.4": "you’ve had regrets for a long time. ",
  "sn8.3:3.1": "Smeared by smears and slain by conceit, ",
  "sn8.3:3.2": "people fall into hell. ",
  "sn8.3:3.3": "When people slain by conceit are reborn in hell, ",
  "sn8.3:3.4": "they grieve for a long time. ",
  "sn8.3:4.1": "But a mendicant who practices rightly, ",
  "sn8.3:4.2": "a path-victor, never grieves. ",
  "sn8.3:4.3": "They enjoy happiness and a good reputation, ",
  "sn8.3:4.4": "and they rightly call him a ‘Seer of Truth’. ",
  "sn8.3:5.1": "So being not hard-hearted, but energetic, ",
  "sn8.3:5.2": "with hindrances given up, pure; ",
  "sn8.3:5.3": "and having completely given up conceit, ",
  "sn8.3:5.4": "the one who makes an end with knowledge is assuaged.” ",
  "sn8.4:0.1": "Linked Discourses 8.4 ",
  "sn8.4:0.2": "1. With Vaṅgīsa ",
  "sn8.4:0.3": "With Ānanda ",
  "sn8.4:1.1": "At one time Venerable Ānanda was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn8.4:1.2": "Then Venerable Ānanda robed up in the morning and, taking his bowl and robe, entered Sāvatthī for alms with Venerable Vaṅgīsa as his second monk. ",
  "sn8.4:1.3": "And at that time Venerable Vaṅgīsa became dissatisfied, as lust infected his mind. ",
  "sn8.4:1.4": "Then he addressed Ānanda in verse: ",
  "sn8.4:2.1": "“I’ve got a burning desire for pleasure; ",
  "sn8.4:2.2": "My mind is on fire! ",
  "sn8.4:2.3": "Please, out of compassion, Gotama, ",
  "sn8.4:2.4": "tell me how to quench the flames.” ",
  "sn8.4:3.1": "“Your mind is on fire ",
  "sn8.4:3.2": "because of a perversion of perception. ",
  "sn8.4:3.3": "Turn away from the feature of things ",
  "sn8.4:3.4": "that’s attractive, provoking lust. ",
  "sn8.4:4.1": "See all conditioned phenomena as alien, ",
  "sn8.4:4.2": "as suffering and not-self. ",
  "sn8.4:4.3": "Extinguish the great fire of lust, ",
  "sn8.4:4.4": "don’t burn up again and again. ",
  "sn8.4:5.1": "With mind unified and serene, ",
  "sn8.4:5.2": "meditate on the ugly aspects of the body. ",
  "sn8.4:5.3": "With mindfulness immersed in the body, ",
  "sn8.4:5.4": "be full of disillusionment. ",
  "sn8.4:6.1": "Meditate on the signless, ",
  "sn8.4:6.2": "give up the underlying tendency to conceit; ",
  "sn8.4:6.3": "and when you comprehend conceit, ",
  "sn8.4:6.4": "you will live at peace.” ",
  "sn8.5:0.1": "Linked Discourses 8.5 ",
  "sn8.5:0.2": "1. With Vaṅgīsa ",
  "sn8.5:0.3": "Well-Spoken Words ",
  "sn8.5:1.1": "At Sāvatthī. ",
  "sn8.5:1.2": "There the Buddha addressed the mendicants, ",
  "sn8.5:1.3": "“Mendicants!” ",
  "sn8.5:1.4": "“Venerable sir,” they replied. ",
  "sn8.5:1.5": "The Buddha said this: ",
  "sn8.5:2.1": "“Mendicants, speech that has four factors is well spoken, not poorly spoken. It’s blameless and is not criticized by sensible people. ",
  "sn8.5:2.2": "What four? ",
  "sn8.5:2.3": "It’s when a mendicant speaks well, not poorly; their speech is principled, not unprincipled; they speak pleasantly, not unpleasantly; and they speak truthfully, not falsely. ",
  "sn8.5:2.4": "Speech with these four factors is well spoken, not poorly spoken. It’s blameless and is not criticized by sensible people.” ",
  "sn8.5:2.5": "That is what the Buddha said. ",
  "sn8.5:2.6": "Then the Holy One, the Teacher, went on to say: ",
  "sn8.5:3.1": "“Good people say well-spoken words are foremost; ",
  "sn8.5:3.2": "second, speech ought be principled, not unprincipled; ",
  "sn8.5:3.3": "third, speak pleasantly, not unpleasantly; ",
  "sn8.5:3.4": "and fourth, speak truthfully, not falsely.” ",
  "sn8.5:4.1": "Then Venerable Vaṅgīsa got up from his seat, arranged his robe over one shoulder, raised his joined palms toward the Buddha, and said, ",
  "sn8.5:4.2": "“I feel inspired to speak, Blessed One! I feel inspired to speak, Holy One!” ",
  "sn8.5:4.3": "“Then speak as you feel inspired,” said the Buddha. ",
  "sn8.5:4.4": "Then Vaṅgīsa extolled the Buddha in his presence with fitting verses: ",
  "sn8.5:5.1": "“Speak only such words ",
  "sn8.5:5.2": "as do not hurt yourself ",
  "sn8.5:5.3": "nor harm others; ",
  "sn8.5:5.4": "such speech is truly well spoken. ",
  "sn8.5:6.1": "Speak only pleasing words, ",
  "sn8.5:6.2": "words gladly welcomed. ",
  "sn8.5:6.3": "Pleasing words are those ",
  "sn8.5:6.4": "that bring nothing bad to others. ",
  "sn8.5:7.1": "Truth itself is undying speech: ",
  "sn8.5:7.2": "this is an ancient teaching. ",
  "sn8.5:7.3": "Good people say the teaching and meaning ",
  "sn8.5:7.4": "are grounded in truth. ",
  "sn8.5:8.1": "The words spoken by the Buddha ",
  "sn8.5:8.2": "for finding the sanctuary, extinguishment, ",
  "sn8.5:8.3": "for making an end of suffering: ",
  "sn8.5:8.4": "this really is the best kind of speech.” ",
  "sn8.6:0.1": "Linked Discourses 8.6 ",
  "sn8.6:0.2": "1. With Vaṅgīsa ",
  "sn8.6:0.3": "With Sāriputta ",
  "sn8.6:1.1": "At one time Venerable Sāriputta was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn8.6:1.2": "Now at that time Venerable Sāriputta was educating, encouraging, firing up, and inspiring the mendicants in the assembly hall with a Dhamma talk. His words were polished, clear, articulate, and expressed the meaning. ",
  "sn8.6:1.3": "And those mendicants were paying attention, applying the mind, concentrating wholeheartedly, and actively listening. ",
  "sn8.6:1.4": "Then Venerable Vaṅgīsa thought, ",
  "sn8.6:1.5": "“This Venerable Sāriputta is educating the mendicants. … ",
  "sn8.6:1.6": "And those mendicants are paying attention, applying the mind, concentrating wholeheartedly, and actively listening. ",
  "sn8.6:1.7": "Why don’t I extoll him in his presence with fitting verses?” ",
  "sn8.6:2.1": "Then Venerable Vaṅgīsa got up from his seat, arranged his robe over one shoulder, raised his joined palms toward Sāriputta, and said, ",
  "sn8.6:2.2": "“I feel inspired to speak, Reverend Sāriputta! I feel inspired to speak, Reverend Sāriputta!” ",
  "sn8.6:2.3": "“Then speak as you feel inspired,” said Sāriputta. ",
  "sn8.6:2.4": "Then Vaṅgīsa extolled Sāriputta in his presence with fitting verses: ",
  "sn8.6:3.1": "“Deep in wisdom, intelligent, ",
  "sn8.6:3.2": "expert in the path and what is not the path; ",
  "sn8.6:3.3": "Sāriputta, so greatly wise, ",
  "sn8.6:3.4": "teaches Dhamma to the mendicants. ",
  "sn8.6:4.1": "He teaches in brief, ",
  "sn8.6:4.2": "or he speaks at length. ",
  "sn8.6:4.3": "His call, like a myna bird, ",
  "sn8.6:4.4": "overflows with inspiration. ",
  "sn8.6:5.1": "While he teaches ",
  "sn8.6:5.2": "the mendicants listen to his sweet voice, ",
  "sn8.6:5.3": "sounding attractive, ",
  "sn8.6:5.4": "clear and graceful. ",
  "sn8.6:5.5": "They listen joyfully, ",
  "sn8.6:5.6": "their hearts elated.” ",
  "sn8.7:0.1": "Linked Discourses 8.7 ",
  "sn8.7:0.2": "1. With Vaṅgīsa ",
  "sn8.7:0.3": "The Invitation to Admonish ",
  "sn8.7:1.1": "At one time the Buddha was staying near Sāvatthī in the stilt longhouse of Migāra’s mother in the Eastern Monastery, together with a large Saṅgha of around five hundred monks, all of whom were perfected ones. ",
  "sn8.7:1.2": "Now, at that time it was the sabbaththe full moon on the fifteenth dayand the Buddha was sitting in the open surrounded by the Saṅgha of monks for the invitation to admonish. ",
  "sn8.7:1.3": "Then the Buddha looked around the Saṅgha of monks, who were silent. He addressed them: ",
  "sn8.7:1.4": "“Come now, monks, I invite you all: ",
  "sn8.7:1.5": "Is there anything I’ve done by way of body or speech that you would criticize?” ",
  "sn8.7:2.1": "When he had spoken, Venerable Sāriputta got up from his seat, arranged his robe over one shoulder, raised his joined palms toward the Buddha, and said: ",
  "sn8.7:2.2": "“There is nothing, sir, that you’ve done by way of body or speech that we would criticize. ",
  "sn8.7:2.3": "For the Blessed One gave rise to the unarisen path, gave birth to the unborn path, and explained the unexplained path. He is the knower of the path, the discoverer of the path, the expert on the path. ",
  "sn8.7:2.4": "And now the disciples live following the path; they acquire it later. ",
  "sn8.7:2.5": "And sir, I invite the Blessed One. ",
  "sn8.7:2.6": "Is there anything I’ve done by way of body or speech that you would criticize?” ",
  "sn8.7:3.1": "“There is nothing, Sāriputta, that you’ve done by way of body or speech that I would criticize. ",
  "sn8.7:3.2": "Sāriputta, you are astute. You have great wisdom, widespread wisdom, laughing wisdom, swift wisdom, sharp wisdom, penetrating wisdom. ",
  "sn8.7:3.3": "A wheel-turning monarch’s oldest son rightly keeps wielding the power set in motion by his father. ",
  "sn8.7:3.4": "In the same way, Sāriputta rightly keeps rolling the supreme Wheel of Dhamma that was rolled forth by me.” ",
  "sn8.7:4.1": "“Since it seems I have done nothing worthy of the Blessed One’s criticism, ",
  "sn8.7:4.2": "is there anything these five hundred monks have done by way of body or speech that you would criticize?” ",
  "sn8.7:4.3": "“There is nothing, Sāriputta, that these five hundred monks have done by way of body or speech that I would criticize. ",
  "sn8.7:4.4": "For of these five hundred monks, sixty have the three knowledges, sixty have the six direct knowledges, sixty are freed both ways, and the rest are freed by wisdom.” ",
  "sn8.7:5.1": "Then Venerable Vaṅgīsa got up from his seat, arranged his robe over one shoulder, raised his joined palms toward the Buddha, and said, ",
  "sn8.7:5.2": "“I feel inspired to speak, Blessed One! I feel inspired to speak, Holy One!” ",
  "sn8.7:5.3": "“Then speak as you feel inspired,” said the Buddha. ",
  "sn8.7:5.4": "Then Vaṅgīsa extolled the Buddha in his presence with fitting verses: ",
  "sn8.7:6.1": "“Today, on the fifteenth day sabbath, ",
  "sn8.7:6.2": "five hundred monks have gathered together <j>to purify their precepts. ",
  "sn8.7:6.3": "These untroubled sages <j>have cut off their fetters and bonds, ",
  "sn8.7:6.4": "they will not be reborn again. ",
  "sn8.7:7.1": "Just as a wheel-turning monarch ",
  "sn8.7:7.2": "surrounded by ministers ",
  "sn8.7:7.3": "travels all around this ",
  "sn8.7:7.4": "land girt by sea. ",
  "sn8.7:8.1": "So disciples with the three knowledges, ",
  "sn8.7:8.2": "conquerors of death, ",
  "sn8.7:8.3": "revere the winner of the battle, ",
  "sn8.7:8.4": "the unsurpassed caravan leader. ",
  "sn8.7:9.1": "All are sons of the Blessed One",
  "sn8.7:9.2": "there is no rubbish here. ",
  "sn8.7:9.3": "I bow to the Kinsman of the Sun, ",
  "sn8.7:9.4": "destroyer of the dart of craving.” ",
  "sn8.8:0.1": "Linked Discourses 8.8 ",
  "sn8.8:0.2": "1. With Vaṅgīsa ",
  "sn8.8:0.3": "Over a Thousand ",
  "sn8.8:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery, together with a large Saṅgha of 1,250 mendicants. ",
  "sn8.8:1.2": "Now at that time the Buddha was educating, encouraging, firing up, and inspiring the mendicants with a Dhamma talk about extinguishment. ",
  "sn8.8:1.3": "And those mendicants were paying attention, applying the mind, concentrating wholeheartedly, and actively listening. ",
  "sn8.8:1.4": "Then Venerable Vaṅgīsa thought, ",
  "sn8.8:1.5": "“The Buddha is educating, encouraging, firing up, and inspiring the mendicants with a Dhamma talk about extinguishment. ",
  "sn8.8:1.6": "And those mendicants are paying attention, applying the mind, concentrating wholeheartedly, and actively listening. ",
  "sn8.8:1.7": "Why don’t I extoll him in his presence with fitting verses?” ",
  "sn8.8:2.1": "Then Venerable Vaṅgīsa got up from his seat, arranged his robe over one shoulder, raised his joined palms toward the Buddha, and said, ",
  "sn8.8:2.2": "“I feel inspired to speak, Blessed One! I feel inspired to speak, Holy One!” ",
  "sn8.8:2.3": "“Then speak as you feel inspired,” said the Buddha. ",
  "sn8.8:2.4": "Then Vaṅgīsa extolled the Buddha in his presence with fitting verses: ",
  "sn8.8:3.1": "“Over a thousand mendicants ",
  "sn8.8:3.2": "revere the Holy One ",
  "sn8.8:3.3": "as he teaches the immaculate Dhamma, ",
  "sn8.8:3.4": "extinguishment, fearing nothing from any quarter. ",
  "sn8.8:4.1": "They listen to the immaculate Dhamma ",
  "sn8.8:4.2": "taught by the fully awakened Buddha; ",
  "sn8.8:4.3": "the Buddha is so brilliant, ",
  "sn8.8:4.4": "at the fore of the mendicant Saṅgha, ",
  "sn8.8:5.1": "Blessed One, your name is ‘Giant’, ",
  "sn8.8:5.2": "seventh of the seers. ",
  "sn8.8:5.3": "You are like a great cloud ",
  "sn8.8:5.4": "that rains on your disciples. ",
  "sn8.8:6.1": "I’ve left my day’s meditation, ",
  "sn8.8:6.2": "out of desire to see the teacher. ",
  "sn8.8:6.3": "Great hero, your disciple Vaṅgīsa ",
  "sn8.8:6.4": "bows at your feet.” ",
  "sn8.8:7.1": "“Vaṅgīsa, had you previously composed these verses, or did they spring to mind in the moment?” ",
  "sn8.8:7.2": "“They sprang to mind in the moment, sir.” ",
  "sn8.8:7.3": "“Well then, Vaṅgīsa, speak some more spontaneously inspired verses.” ",
  "sn8.8:7.4": "“Yes, sir,” replied Vaṅgīsa. Then he extolled the Buddha with some more spontaneously inspired verses, not previously composed: ",
  "sn8.8:8.1": "“Having overcome Māra’s wrong path, ",
  "sn8.8:8.2": "you wander with hard-heartedness dissolved. ",
  "sn8.8:8.3": "See him, the liberator from bonds, ",
  "sn8.8:8.4": "dissecting the unattached section by section. ",
  "sn8.8:9.1": "You have explained in many ways ",
  "sn8.8:9.2": "the path to cross the flood. ",
  "sn8.8:9.3": "The Seers of Truth stand unfaltering ",
  "sn8.8:9.4": "in the freedom from death explained by you. ",
  "sn8.8:10.1": "As the bringer of light who has pierced the truth, ",
  "sn8.8:10.2": "you’ve seen what lies beyond all planes. ",
  "sn8.8:10.3": "When you saw and realized this for yourself, ",
  "sn8.8:10.4": "you taught it first to the group of five. ",
  "sn8.8:11.1": "When the Dhamma has been so well taught, ",
  "sn8.8:11.2": "how could those who know it be negligent? ",
  "sn8.8:11.3": "That’s why, being diligent, we should always train ",
  "sn8.8:11.4": "respectfully in the Buddha’s teaching.” ",
  "sn8.9:0.1": "Linked Discourses 8.9 ",
  "sn8.9:0.2": "1. With Vaṅgīsa ",
  "sn8.9:0.3": "With Koṇḍañña ",
  "sn8.9:1.1": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn8.9:1.2": "Then Venerable Koṇḍañña Who Understood approached the Buddha after a very long absence. He bowed with his head at the Buddha’s feet, caressing them and covering them with kisses, and pronounced his name: ",
  "sn8.9:1.3": "“I am Koṇḍañña, Blessed One! I am Koṇḍañña, Holy One!” ",
  "sn8.9:1.4": "Then Venerable Vaṅgīsa thought, ",
  "sn8.9:1.5": "“This Venerable Koṇḍañña Who Understood has approached the Buddha after a very long absence. He bowed with his head at the Buddha’s feet, caressing them and covering them with kisses, and pronounced his name: ",
  "sn8.9:1.6": "‘I am Koṇḍañña, Blessed One! I am Koṇḍañña, Holy One!’ ",
  "sn8.9:1.7": "Why don’t I extoll him in the Buddha’s presence with fitting verses?” ",
  "sn8.9:2.1": "Then Venerable Vaṅgīsa got up from his seat, arranged his robe over one shoulder, raised his joined palms toward the Buddha, and said, ",
  "sn8.9:2.2": "“I feel inspired to speak, Blessed One! I feel inspired to speak, Holy One!” ",
  "sn8.9:2.3": "“Then speak as you feel inspired,” said the Buddha. ",
  "sn8.9:2.4": "Then Vaṅgīsa extolled Koṇḍañña in the Buddha’s presence with fitting verses: ",
  "sn8.9:3.1": "“The senior monk awakened after the Buddha, ",
  "sn8.9:3.2": "Koṇḍañña, is keenly energetic. ",
  "sn8.9:3.3": "He regularly gains ",
  "sn8.9:3.4": "the blissful meditations of seclusion. ",
  "sn8.9:4.1": "Whatever can be attained by a disciple ",
  "sn8.9:4.2": "who does the Teacher’s bidding, ",
  "sn8.9:4.3": "he has attained it all, ",
  "sn8.9:4.4": "through diligently training himself. ",
  "sn8.9:5.1": "With great power and the three knowledges, ",
  "sn8.9:5.2": "expert in encompassing the minds of others, ",
  "sn8.9:5.3": "Koṇḍañña, the heir to the Buddha, ",
  "sn8.9:5.4": "bows at the Teacher’s feet.” ",
  "sn8.10:0.1": "Linked Discourses 8.10 ",
  "sn8.10:0.2": "1. With Vaṅgīsa ",
  "sn8.10:0.3": "With Moggallāna ",
  "sn8.10:1.1": "At one time the Buddha was staying on the slopes of Isigili at the Black Rock, together with a large Saṅgha of five hundred mendicants, all of whom were perfected ones. ",
  "sn8.10:1.2": "Thereupon, with his mind, Venerable Mahāmoggallāna checked to see whose mind was liberated and free of attachments. ",
  "sn8.10:1.3": "Then Venerable Vaṅgīsa thought, ",
  "sn8.10:1.4": "“The Buddha is staying on the slopes of Isigili … with five hundred perfected ones. ",
  "sn8.10:1.5": "Mahāmoggallāna is checking to see whose mind is liberated and free of attachments. ",
  "sn8.10:1.6": "Why don’t I extoll him in the Buddha’s presence with fitting verses?” ",
  "sn8.10:2.1": "Then Venerable Vaṅgīsa got up from his seat, arranged his robe over one shoulder, raised his joined palms toward the Buddha, and said, ",
  "sn8.10:2.2": "“I feel inspired to speak, Blessed One! I feel inspired to speak, Holy One!” ",
  "sn8.10:2.3": "“Then speak as you feel inspired,” said the Buddha. ",
  "sn8.10:2.4": "Then Vaṅgīsa extolled Mahāmoggallāna in his presence with fitting verses: ",
  "sn8.10:3.1": "“As the sage, who has gone beyond suffering, ",
  "sn8.10:3.2": "sits upon the mountain slope, ",
  "sn8.10:3.3": "he is revered by disciples with the three knowledges, ",
  "sn8.10:3.4": "conquerors of death. ",
  "sn8.10:4.1": "Moggallāna, of great psychic power, ",
  "sn8.10:4.2": "encompasses with his mind, ",
  "sn8.10:4.3": "scrutinizing their minds, ",
  "sn8.10:4.4": "liberated, free of attachments. ",
  "sn8.10:5.1": "That is how those endowed <j>with many fine qualities ",
  "sn8.10:5.2": "revere Gotama, ",
  "sn8.10:5.3": "the sage gone beyond suffering, ",
  "sn8.10:5.4": "perfect in every respect.” ",
  "sn8.11:0.1": "Linked Discourses 8.11 ",
  "sn8.11:0.2": "1. With Vaṅgīsa ",
  "sn8.11:0.3": "At Gaggarā ",
  "sn8.11:1.1": "At one time the Buddha was staying near Campā on the banks of the Gaggarā Lotus Pond, together with a large Saṅgha of five hundred mendicants, seven hundred male and seven hundred female lay followers, and many thousands of deities. ",
  "sn8.11:1.2": "But the Buddha outshone them all in beauty and glory. ",
  "sn8.11:1.3": "Then Venerable Vaṅgīsa thought, ",
  "sn8.11:1.4": "“The Buddha is staying near Campā on the banks of the Gaggarā Lotus Pond, together with a large Saṅgha of five hundred mendicants, seven hundred male and seven hundred female lay followers, and many thousands of deities. ",
  "sn8.11:1.5": "And he outshines them all in beauty and glory. ",
  "sn8.11:1.6": "Why don’t I extoll him in his presence with fitting verses?” ",
  "sn8.11:2.1": "Then Venerable Vaṅgīsa got up from his seat, arranged his robe over one shoulder, raised his joined palms toward the Buddha, and said, ",
  "sn8.11:2.2": "“I feel inspired to speak, Blessed One! I feel inspired to speak, Holy One!” ",
  "sn8.11:2.3": "“Then speak as you feel inspired,” said the Buddha. ",
  "sn8.11:2.4": "Then Vaṅgīsa extolled the Buddha in his presence with fitting verses: ",
  "sn8.11:3.1": "“Like the moon on a cloudless night, ",
  "sn8.11:3.2": "like the shining immaculate sun, ",
  "sn8.11:3.3": "so too Aṅgīrasa, O great sage, ",
  "sn8.11:3.4": "your glory outshines the entire world.” ",
  "sn8.12:0.1": "Linked Discourses 8.12 ",
  "sn8.12:0.2": "1. With Vaṅgīsa ",
  "sn8.12:0.3": "With Vaṅgīsa ",
  "sn8.12:1.1": "At one time Venerable Vaṅgīsa was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn8.12:1.2": "Now at that time Vaṅgīsa had recently attained perfection. While experiencing the bliss of freedom, on that occasion he recited these verses: ",
  "sn8.12:2.1": "“We used to wander, drunk on poetry, ",
  "sn8.12:2.2": "village to village, town to town. ",
  "sn8.12:2.3": "Then we saw the Buddha, ",
  "sn8.12:2.4": "and faith arose in us. ",
  "sn8.12:3.1": "He taught me Dhamma: ",
  "sn8.12:3.2": "the aggregates, sense fields, and elements. ",
  "sn8.12:3.3": "When I heard his teaching ",
  "sn8.12:3.4": "I went forth to homelessness. ",
  "sn8.12:4.1": "It was truly for the benefit of many ",
  "sn8.12:4.2": "that the sage achieved awakening",
  "sn8.12:4.3": "for the monks and for the nuns ",
  "sn8.12:4.4": "who see that they’ve reached certainty. ",
  "sn8.12:5.1": "It was so welcome for me ",
  "sn8.12:5.2": "to be in the presence of the Buddha. ",
  "sn8.12:5.3": "I’ve attained the three knowledges, ",
  "sn8.12:5.4": "and fulfilled the Buddha’s instructions. ",
  "sn8.12:6.1": "I know my past lives, ",
  "sn8.12:6.2": "my clairvoyance is purified, ",
  "sn8.12:6.3": "I am master of three knowledges, <j>attained in psychic power, ",
  "sn8.12:6.4": "expert in encompassing the minds of others.” ",
  "sn8.12:7.1": "",
  "sn8.12:7.2": "",
  "sn8.12:7.3": "",
  "sn8.12:7.4": "",
  "sn8.12:7.5": "",
  "sn8.12:7.6": "",
  "sn8.12:7.7": "",
  "sn8.12:7.8": "The Linked Discourses with Vaṅgīsa are complete. "
}
window.BILARA["sn8_v1"]["en"]["sn8_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
