window.BILARA = window.BILARA || {};
window.BILARA["sn10_v1"] = window.BILARA["sn10_v1"] || {};
window.BILARA["sn10_v1"]["en"] = {
  "sn10.1:0.1": "Linked Discourses 10.1 ",
  "sn10.1:0.2": "1. With Indaka ",
  "sn10.1:0.3": "With Indaka ",
  "sn10.1:1.1": "So I have heard. ",
  "sn10.1:1.2": "At one time the Buddha was staying near Rājagaha on Mount Indra’s Peak, the haunt of the native spirit Indaka. ",
  "sn10.1:1.3": "Then the native spirit Indaka went up to the Buddha, and addressed him in verse: ",
  "sn10.1:2.1": "“The Buddhas say that form is not the soul. ",
  "sn10.1:2.2": "Then how does this one obtain this body? ",
  "sn10.1:2.3": "From where do his bones and organs come? ",
  "sn10.1:2.4": "How does this one coalesce in the womb?” ",
  "sn10.1:3.1": "“First there’s the zygote; ",
  "sn10.1:3.2": "then there’s the blastocyst; ",
  "sn10.1:3.3": "from there arises the gastrula; ",
  "sn10.1:3.4": "which produces the embryonic mass. ",
  "sn10.1:3.5": "From that the limb buds appear, ",
  "sn10.1:3.6": "the head hair, body hair, and nails. ",
  "sn10.1:4.1": "And whatever the mother eats",
  "sn10.1:4.2": "the food and drink that she consumes",
  "sn10.1:4.3": "nourishes them there, ",
  "sn10.1:4.4": "the person in the mother’s womb.” ",
  "sn10.2:0.1": "Linked Discourses 10.2 ",
  "sn10.2:0.2": "1. With Indaka ",
  "sn10.2:0.3": "Sakka In Name Only ",
  "sn10.2:1.1": "At one time the Buddha was staying near Rājagaha, on the Vulture’s Peak Mountain. ",
  "sn10.2:1.2": "Then a spirit who was Sakka in name only went up to the Buddha, and addressed him in verse: ",
  "sn10.2:2.1": "“You’ve given up all ties, ",
  "sn10.2:2.2": "and are fully freed. ",
  "sn10.2:2.3": "It’s not a good idea for you, ascetic, ",
  "sn10.2:2.4": "to be instructing others.” ",
  "sn10.2:3.1": "“No matter how you explain why ",
  "sn10.2:3.2": "people gather together, Sakka, ",
  "sn10.2:3.3": "it’s unworthy for a wise person ",
  "sn10.2:3.4": "not to think of the other with sympathy. ",
  "sn10.2:4.1": "If you instruct others ",
  "sn10.2:4.2": "with a mind clear and confident, ",
  "sn10.2:4.3": "your compassion and empathy ",
  "sn10.2:4.4": "don’t create attachments.” ",
  "sn10.3:0.1": "Linked Discourses 10.3 ",
  "sn10.3:0.2": "1. With Indaka ",
  "sn10.3:0.3": "With Spiky ",
  "sn10.3:1.1": "At one time the Buddha was staying near Gayā on the cut-stone ledge in the haunt of Spiky the native spirit. ",
  "sn10.3:1.2": "Now at that time the native spirits Shaggy and Spiky were passing by not far from the Buddha. ",
  "sn10.3:1.3": "So Shaggy said to Spiky, ",
  "sn10.3:1.4": "“That’s an ascetic.” ",
  "sn10.3:1.5": "“That’s no ascetic, he’s a faker! ",
  "sn10.3:1.6": "I’ll soon find out whether he’s an ascetic or a faker.” ",
  "sn10.3:2.1": "Then Spiky went up to the Buddha and leaned up against his body, ",
  "sn10.3:2.2": "but the Buddha pulled away. ",
  "sn10.3:2.3": "Then Spiky said to the Buddha, ",
  "sn10.3:2.4": "“Are you afraid, ascetic?” ",
  "sn10.3:2.5": "“No, respectable sir, I’m not afraid. ",
  "sn10.3:2.6": "But your touch is nasty.” ",
  "sn10.3:2.7": "“I will ask you a question, ascetic. ",
  "sn10.3:2.8": "If you don’t answer me, I’ll drive you insane, or explode your heart, or grab you by the feet and throw you to the far shore of the Ganges!” ",
  "sn10.3:2.9": "“I don’t see anyone in this world with its gods, Māras, and Divinities, this population with its ascetics and brahmins, its gods and humans who could do that to me. ",
  "sn10.3:2.10": "But anyway, ask what you wish.” ",
  "sn10.3:3.1": "“Where do greed and hate come from? ",
  "sn10.3:3.2": "From where spring discontent, desire, and terror? ",
  "sn10.3:3.3": "Where do the mind’s thoughts originate, ",
  "sn10.3:3.4": "like a crow let loose by boys.” ",
  "sn10.3:4.1": "“Greed and hate come from here; ",
  "sn10.3:4.2": "from here spring discontent, desire, and terror; ",
  "sn10.3:4.3": "here’s where the mind’s thoughts originate, ",
  "sn10.3:4.4": "like a crow let loose by boys. ",
  "sn10.3:5.1": "Born of affection, originating in oneself, ",
  "sn10.3:5.2": "like prop roots sprouting from a banyan; ",
  "sn10.3:5.3": "the many kinds of attachment to sensual pleasures ",
  "sn10.3:5.4": "are like camel’s foot creeper <j>creeping through the woods. ",
  "sn10.3:6.1": "Those who understand where they come from ",
  "sn10.3:6.2": "get rid of themlisten up, spirit! ",
  "sn10.3:6.3": "They cross this flood so hard to cross, ",
  "sn10.3:6.4": "not crossed before, so as to not be reborn.” ",
  "sn10.4:0.1": "Linked Discourses 10.4 ",
  "sn10.4:0.2": "1. With Indaka ",
  "sn10.4:0.3": "With Maṇibhadda ",
  "sn10.4:1.1": "At one time the Buddha was staying in the land of the Magadhans at the Maṇimālika Shrine, the haunt of the native spirit Maṇibhadda. ",
  "sn10.4:1.2": "Then the native spirit Maṇibhadda went up to the Buddha, and spoke this verse in the Buddha’s presence: ",
  "sn10.4:2.1": "“It’s always auspicious for the mindful; ",
  "sn10.4:2.2": "the mindful prosper in happiness. ",
  "sn10.4:2.3": "Each new day is better for the mindful, ",
  "sn10.4:2.4": "and they are freed from enmity.” ",
  "sn10.4:3.1": "“It’s always auspicious for the mindful; ",
  "sn10.4:3.2": "the mindful prosper in happiness. ",
  "sn10.4:3.3": "Each new day is better for the mindful, ",
  "sn10.4:3.4": "but they’re not freed from enmity. ",
  "sn10.4:4.1": "But someone whose mind delights in harmlessness, ",
  "sn10.4:4.2": "all day and all night, ",
  "sn10.4:4.3": "with love for all living creatures",
  "sn10.4:4.4": "they have no enmity for anyone.” ",
  "sn10.5:0.1": "Linked Discourses 10.5 ",
  "sn10.5:0.2": "1. With Indaka ",
  "sn10.5:0.3": "With Sānu ",
  "sn10.5:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn10.5:1.2": "Now at that time a certain lay woman had a son named Sānu who had been seized by a native spirit. ",
  "sn10.5:1.3": "And as that lay woman wept, on that occasion she recited these verses: ",
  "sn10.5:2.1": "“I have heard this from the perfected ones. ",
  "sn10.5:2.2": "The native spirits will not mess with anyone ",
  "sn10.5:2.3": "who leads the spiritual life ",
  "sn10.5:2.4": "by observing the sabbath ",
  "sn10.5:3.1": "complete in all eight factors ",
  "sn10.5:3.2": "on the fourteenth and the fifteenth days, ",
  "sn10.5:3.3": "and the eighth day of the fortnight, ",
  "sn10.5:3.4": "as well as on the fortnight of special displays. ",
  "sn10.5:3.5": "But now today I see ",
  "sn10.5:3.6": "native spirits messing with Sānu.” ",
  "sn10.5:4.1": "“What you heard from the perfected ones is right. ",
  "sn10.5:4.2": "The native spirits will not mess with anyone ",
  "sn10.5:4.3": "who leads the spiritual life ",
  "sn10.5:4.4": "by observing the sabbath ",
  "sn10.5:5.1": "complete in all eight factors ",
  "sn10.5:5.2": "on the fourteenth and the fifteenth days, ",
  "sn10.5:5.3": "and the eighth day of the fortnight, ",
  "sn10.5:5.4": "as well as on the fortnight of special displays. ",
  "sn10.5:6.1": "When Sānu regains consciousness tell him ",
  "sn10.5:6.2": "this saying of the native spirits: ",
  "sn10.5:6.3": "Don’t do bad deeds ",
  "sn10.5:6.4": "either openly or in secret. ",
  "sn10.5:7.1": "If you should do a bad deed, ",
  "sn10.5:7.2": "or you’re doing one now, ",
  "sn10.5:7.3": "you won’t be freed from suffering, ",
  "sn10.5:7.4": "though you fly away and flee.” ",
  "sn10.5:8.1": "“Mum, they cry for the dead, ",
  "sn10.5:8.2": "or for one who’s alive but missing. ",
  "sn10.5:8.3": "I’m alive and you can see me, ",
  "sn10.5:8.4": "so mum, why do you weep for me?” ",
  "sn10.5:9.1": "“Son, they cry for the dead, ",
  "sn10.5:9.2": "or for one who’s alive but missing. ",
  "sn10.5:9.3": "But someone who has given up sensual pleasures ",
  "sn10.5:9.4": "only to come back here again: ",
  "sn10.5:9.5": "they cry for them as well, ",
  "sn10.5:9.6": "for though still alive they’re really dead. ",
  "sn10.5:10.1": "My dear, you’ve been rescued from hot coals, ",
  "sn10.5:10.2": "and you want to plunge right back in them! ",
  "sn10.5:10.3": "My dear, you’ve been rescued from the abyss, ",
  "sn10.5:10.4": "and you want to plunge right back there! ",
  "sn10.5:11.1": "Hurry up, good luck to you! ",
  "sn10.5:11.2": "To whom should we complain? ",
  "sn10.5:11.3": "A valuable saved from a fire, ",
  "sn10.5:11.4": "you want to burn again!” ",
  "sn10.6:0.1": "Linked Discourses 10.6 ",
  "sn10.6:0.2": "1. With Indaka ",
  "sn10.6:0.3": "With Piyaṅkara ",
  "sn10.6:1.1": "At one time Venerable Sāriputta was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn10.6:1.2": "Now at that time Venerable Anuruddha rose at the crack of dawn and recited passages of the teaching. ",
  "sn10.6:1.3": "Then the native spirit Piyaṅkara’s Mother soothed her little child, saying: ",
  "sn10.6:2.1": "“Don’t make a sound, Piyaṅkara! ",
  "sn10.6:2.2": "A mendicant recites passages of the teaching. ",
  "sn10.6:2.3": "When we understand a passage, ",
  "sn10.6:2.4": "we can practice for our welfare. ",
  "sn10.6:3.1": "Let us restrain ourselves from harming living creatures, ",
  "sn10.6:3.2": "and speak no lying words. ",
  "sn10.6:3.3": "We should train ourselves well in ethics, ",
  "sn10.6:3.4": "and hopefully we’ll be freed from the goblin realm.” ",
  "sn10.7:0.1": "Linked Discourses 10.7 ",
  "sn10.7:0.2": "1. With Indaka ",
  "sn10.7:0.3": "With Punabbasu ",
  "sn10.7:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn10.7:1.2": "Now at that time the Buddha was educating, encouraging, firing up, and inspiring the mendicants with a Dhamma talk about extinguishment. ",
  "sn10.7:1.3": "And those mendicants were paying attention, applying the mind, concentrating wholeheartedly, and actively listening. ",
  "sn10.7:1.4": "Then the native spirit Punabbasu’s Mother soothed her little children, saying: ",
  "sn10.7:2.1": "“Hush, little Uttarā! ",
  "sn10.7:2.2": "Hush, Punabbasu! ",
  "sn10.7:2.3": "For I want to listen to the teaching ",
  "sn10.7:2.4": "of the Teacher, the supreme Buddha. ",
  "sn10.7:3.1": "Extinguishment, the Blessed One said, ",
  "sn10.7:3.2": "is the release from all ties. ",
  "sn10.7:3.3": "I have a lasting love ",
  "sn10.7:3.4": "for this teaching. ",
  "sn10.7:4.1": "In this world, your own child is dear; ",
  "sn10.7:4.2": "in this world, your own husband is dear; ",
  "sn10.7:4.3": "but even greater than that is my love ",
  "sn10.7:4.4": "for this teaching’s quest. ",
  "sn10.7:5.1": "For neither son nor husband, ",
  "sn10.7:5.2": "dear as they are, can free you from suffering; ",
  "sn10.7:5.3": "as listening to the true teaching ",
  "sn10.7:5.4": "frees living creatures from suffering. ",
  "sn10.7:6.1": "In this world mired in suffering, ",
  "sn10.7:6.2": "fettered by old age and death, ",
  "sn10.7:6.3": "I want to listen to the teaching ",
  "sn10.7:6.4": "through which the Buddha awakened, ",
  "sn10.7:6.5": "which frees you from old age and death. ",
  "sn10.7:6.6": "So hush, Punabbasu!” ",
  "sn10.7:7.1": "“Mom, I’m not speaking, ",
  "sn10.7:7.2": "and Uttarā is silent, too. ",
  "sn10.7:7.3": "Focus just on the teaching, ",
  "sn10.7:7.4": "for it’s nice to listen to the true teaching. ",
  "sn10.7:7.5": "And it’s because we haven’t understood the teaching ",
  "sn10.7:7.6": "that we live in suffering, Mom. ",
  "sn10.7:8.1": "He is a beacon for those who are lost ",
  "sn10.7:8.2": "among gods and humans. ",
  "sn10.7:8.3": "The Buddha, bearing his final body, ",
  "sn10.7:8.4": "the Clear-eyed One teaches Dhamma.” ",
  "sn10.7:9.1": "“It’s good that my child’s so astute, ",
  "sn10.7:9.2": "this child I bore and suckled! ",
  "sn10.7:9.3": "My child loves the pure teaching ",
  "sn10.7:9.4": "of the supreme Buddha. ",
  "sn10.7:10.1": "Punabbasu, may you be happy! ",
  "sn10.7:10.2": "Today, I rise. ",
  "sn10.7:10.3": "Hear me too, Uttarā: ",
  "sn10.7:10.4": "I have seen the noble truths!” ",
  "sn10.8:0.1": "Linked Discourses 10.8 ",
  "sn10.8:0.2": "1. With Indaka ",
  "sn10.8:0.3": "With Sudatta ",
  "sn10.8:1.1": "At one time the Buddha was staying near Rājagaha in the Cool Grove. ",
  "sn10.8:1.2": "Now at that time the householder Anāthapiṇḍika had arrived at Rājagaha on some business. ",
  "sn10.8:1.3": "He heard ",
  "sn10.8:1.4": "a rumor that a Buddha had arisen in the world. ",
  "sn10.8:1.5": "Right away he wanted to go and see the Buddha, but he thought, ",
  "sn10.8:1.6": "“It’s too late to go and see the Buddha today. ",
  "sn10.8:1.7": "I’ll go and see him tomorrow.” He went to bed thinking of the Buddha. ",
  "sn10.8:1.8": "During the night he got up three times thinking it was morning. ",
  "sn10.8:1.9": "Then he approached the Sivaka Gate, ",
  "sn10.8:1.10": "and non-human beings opened it for him. ",
  "sn10.8:1.11": "But as he was leaving the city, light vanished and darkness appeared to him. He felt fear, terror, and goosebumps, and wanted to turn back. ",
  "sn10.8:1.12": "Then the invisible spirit Sivaka called out: ",
  "sn10.8:2.1": "“A hundred elephants, a hundred horses, ",
  "sn10.8:2.2": "a hundred mule-drawn chariots, ",
  "sn10.8:2.3": "a hundred thousand maidens ",
  "sn10.8:2.4": "bedecked with jeweled earrings: ",
  "sn10.8:2.5": "these are not worth a sixteenth part ",
  "sn10.8:2.6": "of a single forward stride! ",
  "sn10.8:3.1": "Forward, householder! ",
  "sn10.8:3.2": "Forward, householder! ",
  "sn10.8:3.3": "Going forward is better for you, ",
  "sn10.8:3.4": "not turning back!” ",
  "sn10.8:4.1": "Then darkness vanished and light appeared to Anāthapiṇḍika. His fear, terror, and goosebumps settled down. ",
  "sn10.8:4.2": "But for a second time, light vanished and darkness appeared to him. … ",
  "sn10.8:4.3": "For a second time the invisible spirit Sivaka called out … ",
  "sn10.8:5.1": "",
  "sn10.8:5.2": "",
  "sn10.8:5.3": "",
  "sn10.8:6.1": "",
  "sn10.8:6.2": "",
  "sn10.8:6.3": "“… Going forward is better for you, ",
  "sn10.8:6.4": "not turning back!” ",
  "sn10.8:7.1": "Then darkness vanished and light appeared to Anāthapiṇḍika. His fear, terror, and goosebumps settled down. ",
  "sn10.8:7.2": "But for a third time, light vanished and darkness appeared to him. … ",
  "sn10.8:7.3": "For a third time the invisible spirit Sivaka called out … ",
  "sn10.8:8.1": "",
  "sn10.8:8.2": "",
  "sn10.8:8.3": "",
  "sn10.8:9.1": "",
  "sn10.8:9.2": "",
  "sn10.8:9.3": "“… Going forward is better for you, ",
  "sn10.8:9.4": "not turning back!” ",
  "sn10.8:10.1": "Then darkness vanished and light appeared to Anāthapiṇḍika. His fear, terror, and goosebumps settled down. ",
  "sn10.8:10.2": "Then the householder Anāthapiṇḍika went to the Cool Grove and approached the Buddha. ",
  "sn10.8:11.1": "Now at that time the Buddha had risen at the crack of dawn and was walking mindfully in the open. ",
  "sn10.8:11.2": "He saw Anāthapiṇḍika coming off in the distance. ",
  "sn10.8:11.3": "So he stepped down from the walking path, sat down on the seat spread out, ",
  "sn10.8:11.4": "and said to Anāthapiṇḍika, ",
  "sn10.8:11.5": "“Come, Sudatta.” ",
  "sn10.8:11.6": "Then Anāthapiṇḍika thought, “The Buddha calls me by name!” Smiling and elated, he bowed with his head at the Buddha’s feet and said to him, ",
  "sn10.8:11.7": "“Sir, I trust the Buddha slept well?” ",
  "sn10.8:12.1": "“A brahmin who is fully quenched ",
  "sn10.8:12.2": "always sleeps at ease. ",
  "sn10.8:12.3": "Sensual pleasures slip off them, ",
  "sn10.8:12.4": "they’re cooled, free of attachments. ",
  "sn10.8:13.1": "Since they’ve cut off all clinging, ",
  "sn10.8:13.2": "and removed the stress from the heart, ",
  "sn10.8:13.3": "the peaceful sleep at ease, ",
  "sn10.8:13.4": "having found peace of mind.” ",
  "sn10.9:0.1": "Linked Discourses 10.9 ",
  "sn10.9:0.2": "1. With Indaka ",
  "sn10.9:0.3": "With the Nun Sukkā (1st) ",
  "sn10.9:1.1": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn10.9:1.2": "Now, at that time the nun Sukkā was teaching Dhamma, surrounded by a large assembly. ",
  "sn10.9:1.3": "Then a native spirit was so devoted to Sukkā that he went from street to street and from square to square, and on that occasion recited these verses: ",
  "sn10.9:2.1": "“What’s up with these people in Rājagaha? ",
  "sn10.9:2.2": "They sleep like they’ve been drinking mead! ",
  "sn10.9:2.3": "They don’t attend on Sukkā ",
  "sn10.9:2.4": "as she’s teaching the state free of death. ",
  "sn10.9:3.1": "But the wise",
  "sn10.9:3.2": "it’s as if they drink it up, ",
  "sn10.9:3.3": "so irresistible, delectable, and nutritious, ",
  "sn10.9:3.4": "like travelers enjoying a cool cloud.” ",
  "sn10.10:0.1": "Linked Discourses 10.10 ",
  "sn10.10:0.2": "1. With Indaka ",
  "sn10.10:0.3": "With the Nun Sukkā (2nd) ",
  "sn10.10:1.1": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn10.10:1.2": "Now at that time a certain lay follower gave food to the nun Sukkā. ",
  "sn10.10:1.3": "Then a native spirit was so devoted to Sukkā that he went from street to street and from square to square, and on that occasion recited these verses: ",
  "sn10.10:2.1": "“O! He has made so much merit! ",
  "sn10.10:2.2": "That lay follower is so very wise. ",
  "sn10.10:2.3": "He just gave food to Sukkā, ",
  "sn10.10:2.4": "who is released from all ties.” ",
  "sn10.11:0.1": "Linked Discourses 10.11 ",
  "sn10.11:0.2": "1. With Indaka ",
  "sn10.11:0.3": "With the Nun Cīrā ",
  "sn10.11:1.1": "So I have heard. ",
  "sn10.11:1.2": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn10.11:1.3": "Now at that time a certain lay follower gave a robe to the nun Cīrā. ",
  "sn10.11:1.4": "Then a native spirit was so devoted to Cīrā that he went from street to street and from square to square, and on that occasion recited these verses: ",
  "sn10.11:2.1": "“O! He has made so much merit! ",
  "sn10.11:2.2": "That lay-follower is so very wise. ",
  "sn10.11:2.3": "He gave a robe to Cīrā, ",
  "sn10.11:2.4": "who is released from all yokes.” ",
  "sn10.12:0.1": "Linked Discourses 10.12 ",
  "sn10.12:0.2": "1. With Indaka ",
  "sn10.12:0.3": "With Āḷavaka ",
  "sn10.12:1.1": "So I have heard. ",
  "sn10.12:1.2": "At one time the Buddha was staying near Āḷavī in the haunt of the native spirit Āḷavaka. ",
  "sn10.12:1.3": "Then the native spirit Āḷavaka went up to the Buddha, and said to him: ",
  "sn10.12:1.4": "“Get out, ascetic!” ",
  "sn10.12:1.5": "Saying, “All right, respectable sir,” the Buddha went out. ",
  "sn10.12:1.6": "“Get in, ascetic!” ",
  "sn10.12:1.7": "Saying, “All right, respectable sir,” the Buddha went in. ",
  "sn10.12:1.8": "And for a second time the native spirit Āḷavaka said to the Buddha, ",
  "sn10.12:1.9": "“Get out, ascetic!” ",
  "sn10.12:1.10": "Saying, “All right, respectable sir,” the Buddha went out. ",
  "sn10.12:1.11": "“Get in, ascetic!” ",
  "sn10.12:1.12": "Saying, “All right, respectable sir,” the Buddha went in. ",
  "sn10.12:1.13": "And for a third time the native spirit Āḷavaka said to the Buddha, ",
  "sn10.12:1.14": "“Get out, ascetic!” ",
  "sn10.12:1.15": "Saying, “All right, respectable sir,” the Buddha went out. ",
  "sn10.12:1.16": "“Get in, ascetic!” ",
  "sn10.12:1.17": "Saying, “All right, respectable sir,” the Buddha went in. ",
  "sn10.12:1.18": "And for a fourth time the native spirit Āḷavaka said to the Buddha, ",
  "sn10.12:1.19": "“Get out, ascetic!” ",
  "sn10.12:1.20": "“No, respectable sir, I won’t get out. ",
  "sn10.12:1.21": "Do what you must.” ",
  "sn10.12:1.22": "“I will ask you a question, ascetic. ",
  "sn10.12:1.23": "If you don’t answer me, I’ll drive you insane, or explode your heart, or grab you by the feet and throw you to the far shore of the Ganges!” ",
  "sn10.12:1.24": "“I don’t see anyone in this world with its gods, Māras, and Divinities, this population with its ascetics and brahmins, its gods and humans who could do that to me. ",
  "sn10.12:1.25": "But anyway, ask what you wish.” ",
  "sn10.12:2.1": "“What’s a person’s best wealth? ",
  "sn10.12:2.2": "What brings happiness when practiced well? ",
  "sn10.12:2.3": "What’s the sweetest taste of all? ",
  "sn10.12:2.4": "The one they say has the best life: how do they live?” ",
  "sn10.12:3.1": "“Faith here is a person’s best wealth. ",
  "sn10.12:3.2": "The teaching brings happiness when practiced well. ",
  "sn10.12:3.3": "Truth is the sweetest taste of all. ",
  "sn10.12:3.4": "The one they say has the best life lives by wisdom.” ",
  "sn10.12:4.1": "“How do you cross the flood? ",
  "sn10.12:4.2": "How do you cross the deluge? ",
  "sn10.12:4.3": "How do you get over suffering? ",
  "sn10.12:4.4": "How do you get purified?” ",
  "sn10.12:5.1": "“By faith you cross the flood, ",
  "sn10.12:5.2": "and by diligence the deluge. ",
  "sn10.12:5.3": "By energy you get past suffering, ",
  "sn10.12:5.4": "and you’re purified by wisdom.” ",
  "sn10.12:6.1": "“How do you get wisdom? ",
  "sn10.12:6.2": "How do you earn wealth? ",
  "sn10.12:6.3": "How do you get a good reputation? ",
  "sn10.12:6.4": "How do you hold on to friends? ",
  "sn10.12:6.5": "How do the departed not grieve ",
  "sn10.12:6.6": "when passing from this world to the next?” ",
  "sn10.12:7.1": "“One who is diligent and discerning ",
  "sn10.12:7.2": "gains wisdom by wanting to learn, ",
  "sn10.12:7.3": "having faith in the perfected ones, ",
  "sn10.12:7.4": "and the teaching for becoming extinguished. ",
  "sn10.12:8.1": "Being responsible, acting appropriately, ",
  "sn10.12:8.2": "and working hard you earn wealth. ",
  "sn10.12:8.3": "Truthfulness wins you a good reputation. ",
  "sn10.12:8.4": "You hold on to friends by giving. ",
  "sn10.12:8.5": "That’s how the departed do not grieve ",
  "sn10.12:8.6": "when passing from this world to the next. ",
  "sn10.12:9.1": "A faithful householder of discernment ",
  "sn10.12:9.2": "who possesses these four qualities ",
  "sn10.12:9.3": "does not grieve after passing away: ",
  "sn10.12:9.4": "truth, principle, steadfastness, and generosity. ",
  "sn10.12:10.1": "Go ahead, ask others as well, ",
  "sn10.12:10.2": "there are many ascetics and brahmins. ",
  "sn10.12:10.3": "See whether anything better is found ",
  "sn10.12:10.4": "than truth, principle, generosity, and patience.” ",
  "sn10.12:11.1": "“Why now would I question ",
  "sn10.12:11.2": "the many ascetics and brahmins? ",
  "sn10.12:11.3": "Today I understand ",
  "sn10.12:11.4": "what’s good for the next life. ",
  "sn10.12:12.1": "It was truly for my benefit ",
  "sn10.12:12.2": "that the Buddha came to stay at Āḷavī. ",
  "sn10.12:12.3": "Today I understand ",
  "sn10.12:12.4": "where a gift is very fruitful. ",
  "sn10.12:13.1": "I myself will journey ",
  "sn10.12:13.2": "village to village, town to town, ",
  "sn10.12:13.3": "paying homage to the Buddha, ",
  "sn10.12:13.4": "and the clear rightness of the teaching!” ",
  "sn10.12:13.5": "",
  "sn10.12:14.1": "",
  "sn10.12:14.2": "",
  "sn10.12:14.3": "",
  "sn10.12:14.4": "",
  "sn10.12:14.5": "The Linked Discourses with Native Spirits are complete. "
}
window.BILARA["sn10_v1"]["en"]["sn10_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
