window.BILARA = window.BILARA || {};
window.BILARA["sn15_v1"] = window.BILARA["sn15_v1"] || {};
window.BILARA["sn15_v1"]["en"] = {
  "sn15.1:0.1": "Linked Discourses 15.1 ",
  "sn15.1:0.2": "Chapter One ",
  "sn15.1:0.3": "Grass and Sticks ",
  "sn15.1:1.1": "So I have heard. ",
  "sn15.1:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn15.1:1.3": "There the Buddha addressed the mendicants, ",
  "sn15.1:1.4": "“Mendicants!” ",
  "sn15.1:1.5": "“Venerable sir,” they replied. ",
  "sn15.1:1.6": "The Buddha said this: ",
  "sn15.1:1.7": "“Mendicants, this transmigration has no known beginning. ",
  "sn15.1:1.8": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.1:1.9": "Suppose a person was to strip all the grass, sticks, branches, and leaves in the Black Plum Tree Land, gather them together into one pile, and chop them each into four inch pieces. They’d lay them down, saying: ",
  "sn15.1:1.10": "‘This is my mother, this is my grandmother.’ The grass, sticks, branches, and leaves of the Black Plum Tree Land would run out before that person’s mothers and grandmothers. ",
  "sn15.1:1.11": "Why is that? ",
  "sn15.1:1.12": "This transmigration has no known beginning. ",
  "sn15.1:1.13": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.1:1.14": "For such a long time you have undergone suffering, agony, and disaster, swelling the cemeteries. ",
  "sn15.1:1.15": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.2:0.1": "Linked Discourses 15.2 ",
  "sn15.2:0.2": "Chapter One ",
  "sn15.2:0.3": "The Earth ",
  "sn15.2:1.1": "At Sāvatthī. ",
  "sn15.2:1.2": "“Mendicants, this transmigration has no known beginning. ",
  "sn15.2:1.3": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.2:1.4": "Suppose a person was to make the whole earth into clay balls the size of jujube seeds. They’d lay them down, saying: ",
  "sn15.2:1.5": "‘This is my father, this is my grandfather.’ The whole earth would run out before that person’s fathers and grandfathers. ",
  "sn15.2:1.6": "Why is that? ",
  "sn15.2:1.7": "This transmigration has no known beginning. ",
  "sn15.2:1.8": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.2:1.9": "For such a long time you have undergone suffering, agony, and disaster, swelling the cemeteries. ",
  "sn15.2:1.10": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.3:0.1": "Linked Discourses 15.3 ",
  "sn15.3:0.2": "Chapter One ",
  "sn15.3:0.3": "Tears ",
  "sn15.3:1.1": "At Sāvatthī. ",
  "sn15.3:1.2": "“Mendicants, this transmigration has no known beginning. ",
  "sn15.3:1.3": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.3:1.4": "What do you think? Which is more: the flow of tears you’ve shed while roaming and transmigrating for such a very long timeweeping and wailing from being coupled with the unloved and separated from the lovedor the water in the four oceans?” ",
  "sn15.3:1.5": "“As we understand the Buddha’s teaching, the flow of tears we’ve shed while roaming and transmigrating is more than the water in the four oceans.” ",
  "sn15.3:2.1": "“Good, good, mendicants! It’s good that you understand my teaching like this. ",
  "sn15.3:2.2": "The flow of tears you’ve shed while roaming and transmigrating is indeed more than the water in the four oceans. ",
  "sn15.3:2.3": "For a long time you’ve undergone the death of a mother … ",
  "sn15.3:2.4": "",
  "sn15.3:2.5": "father … ",
  "sn15.3:2.6": "brother … ",
  "sn15.3:2.7": "sister … ",
  "sn15.3:2.8": "son … ",
  "sn15.3:2.9": "daughter … ",
  "sn15.3:2.10": "loss of relatives … ",
  "sn15.3:2.11": "loss of wealth … ",
  "sn15.3:2.12": "or loss through illness. From being coupled with the unloved and separated from the loved, the flow of tears you’ve shed while roaming and transmigrating is indeed more than the water in the four oceans. ",
  "sn15.3:2.13": "Why is that? ",
  "sn15.3:2.14": "This transmigration has no known beginning. … ",
  "sn15.3:2.15": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.4:0.1": "Linked Discourses 15.4 ",
  "sn15.4:0.2": "Chapter One ",
  "sn15.4:0.3": "Mother’s Milk ",
  "sn15.4:1.1": "At Sāvatthī. ",
  "sn15.4:1.2": "“Mendicants, this transmigration has no known beginning. ",
  "sn15.4:1.3": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.4:1.4": "What do you think? Which is more: the mother’s milk you’ve drunk while roaming and transmigrating for such a very long time, or the water in the four oceans?” ",
  "sn15.4:1.5": "“As we understand the Buddha’s teaching, the mother’s milk we’ve drunk while roaming and transmigrating is more than the water in the four oceans.” ",
  "sn15.4:2.1": "“Good, good, mendicants! It’s good that you understand my teaching like this. ",
  "sn15.4:2.2": "The mother’s milk you’ve drunk while roaming and transmigrating for such a very long time is more than the water in the four oceans. ",
  "sn15.4:2.3": "Why is that? ",
  "sn15.4:2.4": "This transmigration has no known beginning. … ",
  "sn15.4:2.5": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.5:0.1": "Linked Discourses 15.5 ",
  "sn15.5:0.2": "Chapter One ",
  "sn15.5:0.3": "A Mountain ",
  "sn15.5:1.1": "At Sāvatthī. ",
  "sn15.5:1.2": "Then a mendicant went up to the Buddha, bowed, sat down to one side, and asked him, ",
  "sn15.5:1.3": "“Sir, how long is an eon?” ",
  "sn15.5:1.4": "“Mendicant, an eon is long. ",
  "sn15.5:1.5": "It’s not easy to calculate how many years, how many hundreds or thousands or hundreds of thousands of years it lasts.” ",
  "sn15.5:2.1": "“But sir, is it possible to give a simile?” ",
  "sn15.5:2.2": "“It’s possible,” said the Buddha. ",
  "sn15.5:2.3": "“Suppose there was a huge stone mountain, a league long, a league wide, and a league high, with no cracks or holes, one solid mass. ",
  "sn15.5:2.4": "And as each century passed someone would stroke it once with a fine cloth from Kāsi. ",
  "sn15.5:2.5": "By this means the huge stone mountain would be worn away before the eon comes to an end. ",
  "sn15.5:2.6": "That’s how long an eon is. ",
  "sn15.5:2.7": "And we’ve transmigrated through many such eons, many hundreds, many thousands, many hundreds of thousands. ",
  "sn15.5:2.8": "Why is that? ",
  "sn15.5:2.9": "This transmigration has no known beginning. … ",
  "sn15.5:2.10": "",
  "sn15.5:2.11": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.6:0.1": "Linked Discourses 15.6 ",
  "sn15.6:0.2": "Chapter One ",
  "sn15.6:0.3": "A Mustard Seed ",
  "sn15.6:1.1": "At Sāvatthī. ",
  "sn15.6:1.2": "Then a mendicant went up to the Buddha … and asked him, ",
  "sn15.6:1.3": "“Sir, how long is an eon?” ",
  "sn15.6:1.4": "“Mendicant, an eon is long. ",
  "sn15.6:1.5": "It’s not easy to calculate how many years, how many hundreds or thousands or hundreds of thousands of years it lasts.” ",
  "sn15.6:2.1": "“But sir, is it possible to give a simile?” ",
  "sn15.6:2.2": "“It’s possible,” said the Buddha. ",
  "sn15.6:2.3": "“Suppose there was an iron citadel, a league long, a league wide, and a league high, full of mustard seeds pressed into balls. ",
  "sn15.6:2.4": "And as each century passed someone would remove a single mustard seed. ",
  "sn15.6:2.5": "By this means the huge heap of mustard seeds would be used up before the eon comes to an end. ",
  "sn15.6:2.6": "That’s how long an eon is. ",
  "sn15.6:2.7": "And we’ve transmigrated through many such eons, many hundreds, many thousands, many hundreds of thousands. ",
  "sn15.6:2.8": "Why is that? ",
  "sn15.6:2.9": "This transmigration has no known beginning. … ",
  "sn15.6:2.10": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.7:0.1": "Linked Discourses 15.7 ",
  "sn15.7:0.2": "Chapter One ",
  "sn15.7:0.3": "Disciples ",
  "sn15.7:1.1": "At Sāvatthī. ",
  "sn15.7:1.2": "Then several mendicants went up to the Buddha … and asked him, ",
  "sn15.7:1.3": "“Sir, how many eons have passed?” ",
  "sn15.7:1.4": "“Mendicants, many eons have passed. ",
  "sn15.7:1.5": "It’s not easy to calculate ",
  "sn15.7:1.6": "how many eons have passed, how many hundreds or thousands or hundreds of thousands of eons.” ",
  "sn15.7:2.1": "“But sir, is it possible to give a simile?” ",
  "sn15.7:2.2": "“It’s possible,” said the Buddha. ",
  "sn15.7:2.3": "“Suppose there were four disciples with a lifespan of a hundred years. ",
  "sn15.7:2.4": "And each day they would each recollect a hundred thousand eons. ",
  "sn15.7:2.5": "Those four disciples would pass away after a hundred years and there would still be eons that they haven’t recollected. ",
  "sn15.7:2.6": "That’s how many eons have passed. ",
  "sn15.7:2.7": "It’s not easy to calculate ",
  "sn15.7:2.8": "how many eons have passed, how many hundreds or thousands or hundreds of thousands of eons. ",
  "sn15.7:2.9": "Why is that? ",
  "sn15.7:2.10": "This transmigration has no known beginning. … ",
  "sn15.7:2.11": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.8:0.1": "Linked Discourses 15.8 ",
  "sn15.8:0.2": "Chapter One ",
  "sn15.8:0.3": "The Ganges ",
  "sn15.8:1.1": "Near Rājagaha, in the Bamboo Grove. ",
  "sn15.8:1.2": "Then a certain brahmin went up to the Buddha, and exchanged greetings with him. ",
  "sn15.8:1.3": "When the greetings and polite conversation were over, he sat down to one side and asked the Buddha, ",
  "sn15.8:1.4": "“Worthy Gotama, how many eons have passed?” ",
  "sn15.8:1.5": "“Brahmin, many eons have passed. ",
  "sn15.8:1.6": "It’s not easy to calculate ",
  "sn15.8:1.7": "how many eons have passed, how many hundreds or thousands or hundreds of thousands of eons.” ",
  "sn15.8:2.1": "“But worthy Gotama, can you give a simile?” ",
  "sn15.8:2.2": "“I can,” said the Buddha. ",
  "sn15.8:2.3": "“Consider the Ganges river from where it originates to where it meets the ocean. Between these places it’s not easy to calculate ",
  "sn15.8:2.4": "how many grains of sand there are, how many hundreds or thousands or hundreds of thousands of grains of sand. ",
  "sn15.8:2.5": "The eons that have passed are more than this. ",
  "sn15.8:2.6": "It’s not easy to calculate ",
  "sn15.8:2.7": "how many eons have passed, how many hundreds or thousands or hundreds of thousands of eons. ",
  "sn15.8:2.8": "Why is that? ",
  "sn15.8:2.9": "This transmigration has no known beginning. ",
  "sn15.8:2.10": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.8:2.11": "For such a long time you have undergone suffering, agony, and disaster, swelling the cemeteries. ",
  "sn15.8:2.12": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.8:3.1": "When he said this, the brahmin said to the Buddha, ",
  "sn15.8:3.2": "“Excellent, worthy Gotama! Excellent! … ",
  "sn15.8:3.3": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn15.9:0.1": "Linked Discourses 15.9 ",
  "sn15.9:0.2": "Chapter One ",
  "sn15.9:0.3": "A Stick ",
  "sn15.9:1.1": "At Sāvatthī. ",
  "sn15.9:1.2": "“Mendicants, this transmigration has no known beginning. ",
  "sn15.9:1.3": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.9:1.4": "Suppose a stick was tossed up in the air. Sometimes it’d fall on its bottom, sometimes the middle, and sometimes the end. ",
  "sn15.9:1.5": "It’s the same for sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. Sometimes they go from this world to the other world, and sometimes they come from the other world to this world. ",
  "sn15.9:1.6": "Why is that? ",
  "sn15.9:1.7": "This transmigration has no known beginning. … ",
  "sn15.9:1.8": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.10:0.1": "Linked Discourses 15.10 ",
  "sn15.10:0.2": "Chapter One ",
  "sn15.10:0.3": "A Single Individual ",
  "sn15.10:1.1": "At one time the Buddha was staying near Rājagaha, on the Vulture’s Peak Mountain. ",
  "sn15.10:1.2": "There the Buddha addressed the mendicants, ",
  "sn15.10:1.3": "“Mendicants!” ",
  "sn15.10:1.4": "“Venerable sir,” they replied. ",
  "sn15.10:1.5": "The Buddha said this: ",
  "sn15.10:2.1": "“Mendicants, this transmigration has no known beginning. … ",
  "sn15.10:2.2": "One individual roaming and transmigrating for an eon would amass a heap of bones the size of this Mount Vepulla, if they were gathered together and not lost. ",
  "sn15.10:2.3": "Why is that? ",
  "sn15.10:2.4": "This transmigration has no known beginning. … ",
  "sn15.10:2.5": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.10:3.1": "That is what the Buddha said. ",
  "sn15.10:3.2": "Then the Holy One, the Teacher, went on to say: ",
  "sn15.10:4.1": "“If the bones of a single individual ",
  "sn15.10:4.2": "for a single eon were gathered up, ",
  "sn15.10:4.3": "they’d make a pile the size of a mountain: ",
  "sn15.10:4.4": "so said the great seer. ",
  "sn15.10:5.1": "And this is declared to be ",
  "sn15.10:5.2": "as huge as Mount Vepulla, ",
  "sn15.10:5.3": "higher than the Vulture’s Peak ",
  "sn15.10:5.4": "in the Magadhan mountain range. ",
  "sn15.10:6.1": "But then, with right understanding, ",
  "sn15.10:6.2": "one sees the noble truths",
  "sn15.10:6.3": "suffering, suffering’s origin, ",
  "sn15.10:6.4": "suffering’s transcendence, ",
  "sn15.10:6.5": "and the noble eightfold path ",
  "sn15.10:6.6": "that leads to the stilling of suffering. ",
  "sn15.10:7.1": "After roaming on seven times at most, ",
  "sn15.10:7.2": "that individual ",
  "sn15.10:7.3": "makes an end of suffering, ",
  "sn15.10:7.4": "with the ending of all fetters.” ",
  "sn15.10:7.5": "",
  "sn15.10:7.6": "",
  "sn15.10:8.1": "",
  "sn15.10:8.2": "",
  "sn15.10:8.3": "",
  "sn15.11:0.1": "Linked Discourses 15.11 ",
  "sn15.11:0.2": "Chapter Two ",
  "sn15.11:0.3": "In a Sorry State ",
  "sn15.11:1.1": "At one time the Buddha was staying near Sāvatthī. ",
  "sn15.11:1.2": "",
  "sn15.11:1.3": "“Mendicants, this transmigration has no known beginning. ",
  "sn15.11:1.4": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.11:1.5": "When you see someone in a sorry state, in distress, you should conclude: ",
  "sn15.11:1.6": "‘In all this long time, we too have undergone the same thing.’ ",
  "sn15.11:1.7": "Why is that? This transmigration has no known beginning. … ",
  "sn15.11:1.8": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.12:0.1": "Linked Discourses 15.12 ",
  "sn15.12:0.2": "Chapter Two ",
  "sn15.12:0.3": "In a Good Way ",
  "sn15.12:1.1": "At Sāvatthī. ",
  "sn15.12:1.2": "“Mendicants, this transmigration has no known beginning. … ",
  "sn15.12:1.3": "When you see someone in a good way, in a happy state, you should conclude: ",
  "sn15.12:1.4": "‘In all this long time, we too have undergone the same thing.’ ",
  "sn15.12:1.5": "Why is that? ",
  "sn15.12:1.6": "This transmigration has no known beginning. … ",
  "sn15.12:1.7": "",
  "sn15.12:1.8": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.13:0.1": "Linked Discourses 15.13 ",
  "sn15.13:0.2": "Chapter Two ",
  "sn15.13:0.3": "Thirty Mendicants ",
  "sn15.13:1.1": "Near Rājagaha, in the Bamboo Grove. ",
  "sn15.13:1.2": "Then thirty mendicants from Pāvā went to the Buddha. All of them lived in the wilderness, ate only almsfood, wore rag robes, and owned just three robes; yet they all still had fetters. They bowed to the Buddha and sat down to one side. ",
  "sn15.13:1.3": "Then it occurred to the Buddha, ",
  "sn15.13:1.4": "“These thirty mendicants from Pāvā live in the wilderness, eat only almsfood, wear rag robes, and own just three robes; yet they all still have fetters. ",
  "sn15.13:1.5": "Why don’t I teach them the Dhamma in such a way that their minds are freed from defilements by not grasping while sitting in this very seat?” ",
  "sn15.13:1.6": "Then the Buddha said to the mendicants, ",
  "sn15.13:1.7": "“Mendicants!” ",
  "sn15.13:1.8": "“Venerable sir,” they replied. ",
  "sn15.13:1.9": "The Buddha said this: ",
  "sn15.13:2.1": "“Mendicants, this transmigration has no known beginning. ",
  "sn15.13:2.2": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.13:2.3": "What do you think? Which is more: the flow of blood you’ve shed when your head was chopped off while roaming and transmigrating for such a very long time, or the water in the four oceans?” ",
  "sn15.13:2.4": "“As we understand the Buddha’s teaching, the flow of blood we’ve shed when our head was chopped off while roaming and transmigrating is more than the water in the four oceans.” ",
  "sn15.13:3.1": "“Good, good, mendicants! It’s good that you understand my teaching like this. ",
  "sn15.13:3.2": "The flow of blood you’ve shed when your head was chopped off while roaming and transmigrating is indeed more than the water in the four oceans. ",
  "sn15.13:3.3": "For a long time you’ve been cows, and the flow of blood you’ve shed when your head was chopped off as a cow is more than the water in the four oceans. ",
  "sn15.13:3.4": "For a long time you’ve been buffalo … ",
  "sn15.13:3.5": "sheep … ",
  "sn15.13:3.6": "goats … ",
  "sn15.13:3.7": "deer … ",
  "sn15.13:3.8": "chickens … ",
  "sn15.13:3.9": "pigs … ",
  "sn15.13:3.10": "For a long time you’ve been bandits, arrested for raiding villages, ",
  "sn15.13:3.11": "highway robbery, ",
  "sn15.13:3.12": "or adultery. And the flow of blood you’ve shed when your head was chopped off as a bandit is more than the water in the four oceans. ",
  "sn15.13:3.13": "Why is that? ",
  "sn15.13:3.14": "This transmigration has no known beginning. … ",
  "sn15.13:3.15": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.13:4.1": "That is what the Buddha said. ",
  "sn15.13:4.2": "Satisfied, the mendicants approved what the Buddha said. ",
  "sn15.13:4.3": "And while this discourse was being spoken, the minds of the thirty mendicants from Pāvā were freed from defilements by not grasping. ",
  "sn15.14:0.1": "Linked Discourses 15.14 ",
  "sn15.14:0.2": "Chapter Two ",
  "sn15.14:0.3": "Mother ",
  "sn15.14:1.1": "At Sāvatthī. ",
  "sn15.14:1.2": "“Mendicants, this transmigration has no known beginning. … ",
  "sn15.14:1.3": "It’s not easy to find a sentient being who in all this long time has not previously been your mother. ",
  "sn15.14:1.4": "Why is that? ",
  "sn15.14:1.5": "This transmigration has no known beginning. … ",
  "sn15.14:1.6": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.15:0.1": "Linked Discourses 15.15 ",
  "sn15.15:0.2": "Chapter Two ",
  "sn15.15:0.3": "Father ",
  "sn15.15:1.1": "At Sāvatthī. ",
  "sn15.15:1.2": "“Mendicants, this transmigration has no known beginning. … ",
  "sn15.15:1.3": "It’s not easy to find a sentient being who in all this long time has not previously been your father. … ",
  "sn15.15:1.4": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.16:0.1": "Linked Discourses 15.16 ",
  "sn15.16:0.2": "Chapter Two ",
  "sn15.16:0.3": "Brother ",
  "sn15.16:1.1": "At Sāvatthī. ",
  "sn15.16:1.2": "“It’s not easy to find a sentient being who in all this long time has not previously been your brother. … ",
  "sn15.16:1.3": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.17:0.1": "Linked Discourses 15.17 ",
  "sn15.17:0.2": "Chapter Two ",
  "sn15.17:0.3": "Sister ",
  "sn15.17:1.1": "At Sāvatthī. ",
  "sn15.17:1.2": "“It’s not easy to find a sentient being who in all this long time has not previously been your sister. … ",
  "sn15.17:1.3": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.18:0.1": "Linked Discourses 15.18 ",
  "sn15.18:0.2": "Chapter Two ",
  "sn15.18:0.3": "Son ",
  "sn15.18:1.1": "At Sāvatthī. ",
  "sn15.18:1.2": "“It’s not easy to find a sentient being who in all this long time has not previously been your son. … ",
  "sn15.18:1.3": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.19:0.1": "Linked Discourses 15.19 ",
  "sn15.19:0.2": "2. Chapter Two ",
  "sn15.19:0.3": "Daughter ",
  "sn15.19:1.1": "At Sāvatthī. ",
  "sn15.19:1.2": "“Mendicants, this transmigration has no known beginning. ",
  "sn15.19:1.3": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.19:1.4": "It’s not easy to find a sentient being who in all this long time has not previously been your daughter. ",
  "sn15.19:1.5": "Why is that? ",
  "sn15.19:1.6": "This transmigration has no known beginning. ",
  "sn15.19:1.7": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.19:1.8": "For such a long time you have undergone suffering, agony, and disaster, swelling the cemeteries. ",
  "sn15.19:1.9": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.20:0.1": "Linked Discourses 15.20 ",
  "sn15.20:0.2": "2. Chapter Two ",
  "sn15.20:0.3": "Mount Vepulla ",
  "sn15.20:1.1": "At one time the Buddha was staying near Rājagaha, on the Vulture’s Peak Mountain. ",
  "sn15.20:1.2": "There the Buddha addressed the mendicants, ",
  "sn15.20:1.3": "“Mendicants!” ",
  "sn15.20:1.4": "“Venerable sir,” they replied. ",
  "sn15.20:1.5": "The Buddha said this: ",
  "sn15.20:2.1": "“Mendicants, this transmigration has no known beginning. ",
  "sn15.20:2.2": "No first point is found of sentient beings roaming and transmigrating, shrouded by ignorance and fettered by craving. ",
  "sn15.20:2.3": "Once upon a time, mendicants, this Mount Vepulla was known as Pācīnavaṁsa. ",
  "sn15.20:2.4": "And at that time people were known as Tivaras. ",
  "sn15.20:2.5": "The lifespan of the Tivaras was 40,000 years. ",
  "sn15.20:2.6": "It took them four days to climb Mount Vepulla, and four days to descend. ",
  "sn15.20:2.7": "At that time Kakusandha, the Blessed One, the perfected one, the fully awakened Buddha arose in the world. ",
  "sn15.20:2.8": "Kakusandha had a fine pair of chief disciples named Vidhura and Sañjīva. ",
  "sn15.20:2.9": "See, mendicants! This mountain’s name has vanished, those people have passed away, and that Buddha has become fully quenched. ",
  "sn15.20:2.10": "So impermanent are conditions, ",
  "sn15.20:2.11": "so unstable are conditions, ",
  "sn15.20:2.12": "so unreliable are conditions. ",
  "sn15.20:2.13": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions. ",
  "sn15.20:3.1": "Once upon a time this Mount Vepulla was known as Vaṅkaka. ",
  "sn15.20:3.2": "And at that time people were known as Rohitassas. ",
  "sn15.20:3.3": "The lifespan of the Rohitassas was 30,000 years. ",
  "sn15.20:3.4": "It took them three days to climb Mount Vepulla, and three days to descend. ",
  "sn15.20:3.5": "At that time Koṇāgamana, the Blessed One, the perfected one, the fully awakened Buddha arose in the world. ",
  "sn15.20:3.6": "Koṇāgamana had a fine pair of chief disciples named Bhiyyosa and Uttara. ",
  "sn15.20:3.7": "See, mendicants! This mountain’s name has vanished, those people have passed away, and that Buddha has become fully quenched. ",
  "sn15.20:3.8": "So impermanent are conditions … ",
  "sn15.20:3.9": "",
  "sn15.20:4.1": "Once upon a time this Mount Vepulla was known as Supassa. ",
  "sn15.20:4.2": "And at that time people were known as Suppiyas. ",
  "sn15.20:4.3": "The lifespan of the Suppiyas was 20,000 years. ",
  "sn15.20:4.4": "It took them two days to climb Mount Vepulla, and two days to descend. ",
  "sn15.20:4.5": "At that time Kassapa, the Blessed One, the perfected one, the fully awakened Buddha arose in the world. ",
  "sn15.20:4.6": "Kassapa had a fine pair of chief disciples named Tissa and Bhāradvāja. ",
  "sn15.20:4.7": "See, mendicants! This mountain’s name has vanished, those people have passed away, and that Buddha has become fully quenched. ",
  "sn15.20:4.8": "So impermanent are conditions … ",
  "sn15.20:4.9": "",
  "sn15.20:4.10": "",
  "sn15.20:5.1": "These days this Mount Vepulla is known as Vepulla. ",
  "sn15.20:5.2": "And these people are known as Magadhans. ",
  "sn15.20:5.3": "The lifespan of the Magadhans is short, brief, and fleeting. ",
  "sn15.20:5.4": "A long life is a hundred years or a little more. ",
  "sn15.20:5.5": "It takes the Magadhans an hour to climb Mount Vepulla, and an hour to descend. ",
  "sn15.20:5.6": "And now I am the Blessed One, the perfected one, the fully awakened Buddha who has arisen in the world. ",
  "sn15.20:5.7": "I have a fine pair of chief disciples named Sāriputta and Moggallāna. ",
  "sn15.20:5.8": "There will come a time when this mountain’s name will vanish, those people will die, and I will be fully extinguished. ",
  "sn15.20:5.9": "So impermanent are conditions, ",
  "sn15.20:5.10": "so unstable are conditions, ",
  "sn15.20:5.11": "so unreliable are conditions. ",
  "sn15.20:5.12": "This is quite enough for you to become disillusioned, dispassionate, and freed regarding all conditions.” ",
  "sn15.20:6.1": "That is what the Buddha said. ",
  "sn15.20:6.2": "Then the Holy One, the Teacher, went on to say: ",
  "sn15.20:7.1": "“For the Tivaras it was Pācīnavaṁsa, ",
  "sn15.20:7.2": "for the Rohitassas, Vaṅkaka, ",
  "sn15.20:7.3": "Supassa for the Suppiyas, ",
  "sn15.20:7.4": "and Vepulla for the Magadhans. ",
  "sn15.20:8.1": "Oh! Conditions are impermanent, ",
  "sn15.20:8.2": "their nature is to rise and fall; ",
  "sn15.20:8.3": "having arisen, they cease; ",
  "sn15.20:8.4": "their settling is such bliss.” ",
  "sn15.20:8.5": "",
  "sn15.20:8.6": "",
  "sn15.20:9.1": "",
  "sn15.20:9.2": "",
  "sn15.20:9.3": "",
  "sn15.20:9.4": "",
  "sn15.20:9.5": "The Linked Discourses on the unknown beginning are complete. "
}
window.BILARA["sn15_v1"]["en"]["sn15_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
