window.BILARA = window.BILARA || {};
window.BILARA["sn19_v1"] = window.BILARA["sn19_v1"] || {};
window.BILARA["sn19_v1"]["en"] = {
  "sn19.1:0.1": "Linked Discourses 19.1 ",
  "sn19.1:0.2": "Chapter One ",
  "sn19.1:0.3": "A Skeleton ",
  "sn19.1:1.1": "So I have heard. ",
  "sn19.1:1.2": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn19.1:1.3": "Now at that time Venerable Mark and Venerable Mahāmoggallāna were staying on the Vulture’s Peak Mountain. ",
  "sn19.1:1.4": "Then Mahāmoggallāna robed up in the morning and, taking his bowl and robe, went to Mark and said to him, ",
  "sn19.1:1.5": "“Come, Reverend Mark, let’s enter Rājagaha for alms.” ",
  "sn19.1:1.6": "“Yes, reverend,” Mark replied. ",
  "sn19.1:1.7": "As Mahāmoggallāna was descending from Vulture’s Peak Mountain he smiled at a certain spot. ",
  "sn19.1:1.8": "So Lakkhaṇa said to Mahāmoggallāna, ",
  "sn19.1:1.9": "“What is the cause, Reverend Moggallāna, what is the reason you smiled?” ",
  "sn19.1:1.10": "“Reverend Mark, it’s the wrong time for this question. ",
  "sn19.1:1.11": "Ask me when we’re in the Buddha’s presence.” ",
  "sn19.1:2.1": "Then Mark and Mahāmoggallāna wandered for alms in Rājagaha. After the meal, on their return from almsround, they went to the Buddha, bowed, and sat down to one side. Mark said to Mahāmoggallāna: ",
  "sn19.1:2.2": "“Just now, as Mahāmoggallāna was descending from Vulture’s Peak Mountain he smiled at a certain spot. ",
  "sn19.1:2.3": "What is the cause, Reverend Moggallāna, what is the reason you smiled?” ",
  "sn19.1:3.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a skeleton flying through the air. ",
  "sn19.1:3.2": "Vultures, crows, and hawks kept chasing it, pecking, clawing, and stabbing it in the ribs ",
  "sn19.1:3.3": "as it screeched in pain. ",
  "sn19.1:3.4": "It occurred to me: ",
  "sn19.1:3.5": "‘Oh lord, how incredible, how amazing! ",
  "sn19.1:3.6": "That there can be such a sentient being, ",
  "sn19.1:3.7": "such a spirit, ",
  "sn19.1:3.8": "such an incarnation!’” ",
  "sn19.1:4.1": "Then the Buddha said to the mendicants: ",
  "sn19.1:4.2": "“Mendicants, there are disciples who live full of vision and knowledge, ",
  "sn19.1:4.3": "since a disciple knows, sees, and witnesses such a thing. ",
  "sn19.1:4.4": "Formerly, I too saw that being, but I did not speak of it. ",
  "sn19.1:4.5": "For if I had spoken of it others would not have believed me, ",
  "sn19.1:4.6": "which would be for their lasting harm and suffering. ",
  "sn19.1:4.7": "That being used to be a cattle butcher right here in Rājagaha. ",
  "sn19.1:4.8": "As a result of that deed he burned in hell for many years, many hundreds, many thousands, many hundreds of thousands of years. Now he experiences the residual result of that deed in such an incarnation.” ",
  "sn19.1:4.9": "(Tell all these discourses in full like this.) ",
  "sn19.2:0.1": "Linked Discourses 19.2 ",
  "sn19.2:0.2": "Chapter One ",
  "sn19.2:0.3": "A Piece of Meat ",
  "sn19.2:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a scrap of meat flying through the air. ",
  "sn19.2:1.2": "Vultures, crows, and hawks kept chasing it, pecking and clawing ",
  "sn19.2:1.3": "as it screeched in pain. …” … ",
  "sn19.2:1.4": "“That being used to be a cattle butcher right here in Rājagaha. …” ",
  "sn19.3:0.1": "Linked Discourses 19.3 ",
  "sn19.3:0.2": "Chapter One ",
  "sn19.3:0.3": "A Piece of Flesh ",
  "sn19.3:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a piece of flesh flying through the air. ",
  "sn19.3:1.2": "Vultures, crows, and hawks kept chasing it, pecking and clawing ",
  "sn19.3:1.3": "as it screeched in pain. …” … ",
  "sn19.3:1.4": "“That being used to be a bird hunter right here in Rājagaha. …” ",
  "sn19.4:0.1": "Linked Discourses 19.4 ",
  "sn19.4:0.2": "Chapter One ",
  "sn19.4:0.3": "A Flayed Man ",
  "sn19.4:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a flayed man flying through the air. ",
  "sn19.4:1.2": "Vultures, crows, and hawks kept chasing it, pecking and clawing ",
  "sn19.4:1.3": "as he screamed in pain. …” … ",
  "sn19.4:1.4": "“That being used to be a sheep butcher right here in Rājagaha. …” ",
  "sn19.5:0.1": "Linked Discourses 19.5 ",
  "sn19.5:0.2": "Chapter One ",
  "sn19.5:0.3": "Sword Hairs ",
  "sn19.5:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a man whose body hairs were swords flying through the air. ",
  "sn19.5:1.2": "And those swords kept rising up and falling on his body ",
  "sn19.5:1.3": "as he screamed in pain. …” … ",
  "sn19.5:1.4": "“That being used to be a pig butcher right here in Rājagaha. …” ",
  "sn19.6:0.1": "Linked Discourses 19.6 ",
  "sn19.6:0.2": "Chapter One ",
  "sn19.6:0.3": "Spear Hairs ",
  "sn19.6:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a man whose body hairs were spears flying through the air. ",
  "sn19.6:1.2": "And those spears kept rising up and falling on his body ",
  "sn19.6:1.3": "as he screamed in pain. …” … ",
  "sn19.6:1.4": "“That being used to be a deer hunter right here in Rājagaha. …” ",
  "sn19.7:0.1": "Linked Discourses 19.7 ",
  "sn19.7:0.2": "Chapter One ",
  "sn19.7:0.3": "Arrow Hairs ",
  "sn19.7:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a man whose body hairs were arrows flying through the air. ",
  "sn19.7:1.2": "And those arrows kept rising up and falling on his body ",
  "sn19.7:1.3": "as he screamed in pain. …” … ",
  "sn19.7:1.4": "“That being used to be a punisher right here in Rājagaha. …” ",
  "sn19.8:0.1": "Linked Discourses 19.8 ",
  "sn19.8:0.2": "Chapter One ",
  "sn19.8:0.3": "Needle Hairs ",
  "sn19.8:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a man whose body hairs were needles flying through the air. ",
  "sn19.8:1.2": "And those needles kept rising up and falling on his body ",
  "sn19.8:1.3": "as he screamed in pain. …” … ",
  "sn19.8:1.4": "“That being used to be an equerry right here in Rājagaha. …” ",
  "sn19.9:0.1": "Linked Discourses 19.9 ",
  "sn19.9:0.2": "Chapter One ",
  "sn19.9:0.3": "Needle Hairs (2nd) ",
  "sn19.9:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a man whose body hairs were needles flying through the air. ",
  "sn19.9:1.2": "The needles bored into his head and out his mouth, ",
  "sn19.9:1.3": "into his mouth and out his chest, ",
  "sn19.9:1.4": "into his chest and out his belly, ",
  "sn19.9:1.5": "into his belly and out his thighs, ",
  "sn19.9:1.6": "into his thighs and out his calves, ",
  "sn19.9:1.7": "and into his calves and out his feet. ",
  "sn19.9:1.8": "And he screamed in pain. …” … ",
  "sn19.9:1.9": "“That being used to be an informant right here in Rājagaha. …” ",
  "sn19.10:0.1": "Linked Discourses 19.10 ",
  "sn19.10:0.2": "Chapter One ",
  "sn19.10:0.3": "Pot Balls ",
  "sn19.10:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a man with testicles big as pots flying through the air. ",
  "sn19.10:1.2": "When he was walking he had to lift his testicles on to his shoulder. ",
  "sn19.10:1.3": "And when he sat down, he sat right on them. ",
  "sn19.10:1.4": "Vultures, crows, and hawks kept chasing him, pecking and clawing ",
  "sn19.10:1.5": "as he screamed in pain. …” … ",
  "sn19.10:1.6": "“That being used to be a corrupt village head right here in Rājagaha. …” ",
  "sn19.10:1.7": "",
  "sn19.10:1.8": "",
  "sn19.10:2.1": "",
  "sn19.10:2.2": "",
  "sn19.10:2.3": "",
  "sn19.10:2.4": "",
  "sn19.10:2.5": "",
  "sn19.11:0.1": "Linked Discourses 19.11 ",
  "sn19.11:0.2": "Chapter Two ",
  "sn19.11:0.3": "Over His Head ",
  "sn19.11:1.1": "So I have heard. ",
  "sn19.11:1.2": "At one time near Rājagaha in the Bamboo Grove … ",
  "sn19.11:1.3": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a man sunk over his head in a sewer. …” … ",
  "sn19.11:1.4": "“That being used to be an adulterer right here in Rājagaha. …” ",
  "sn19.12:0.1": "Linked Discourses 19.12 ",
  "sn19.12:0.2": "Chapter Two ",
  "sn19.12:0.3": "A Dung Eater ",
  "sn19.12:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a man sunk in a sewer, eating dung with both hands. …” … ",
  "sn19.12:1.2": "“That being used to be a nasty brahmin right here in Rājagaha. ",
  "sn19.12:1.3": "In the time of the Buddha Kassapa’s dispensation he invited the Saṅgha of mendicants for a meal. He filled a trough with dung and said: ",
  "sn19.12:1.4": "‘My good men, eat as much as you like, and take what’s left.’ …” ",
  "sn19.13:0.1": "Linked Discourses 19.13 ",
  "sn19.13:0.2": "Chapter Two ",
  "sn19.13:0.3": "A Flayed Woman ",
  "sn19.13:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a flayed woman flying through the air. ",
  "sn19.13:1.2": "Vultures, crows, and hawks kept chasing her, pecking and clawing ",
  "sn19.13:1.3": "as she screamed in pain. …” … ",
  "sn19.13:1.4": "“That woman used to be an adulteress right here in Rājagaha. …” ",
  "sn19.14:0.1": "Linked Discourses 19.14 ",
  "sn19.14:0.2": "Chapter Two ",
  "sn19.14:0.3": "A Fishwife ",
  "sn19.14:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a woman stinking and dingy as a catfish flying through the air. ",
  "sn19.14:1.2": "Vultures, crows, and hawks kept chasing her, pecking and clawing ",
  "sn19.14:1.3": "as she screamed in pain. …” … ",
  "sn19.14:1.4": "“That woman used to be a sorceress right here in Rājagaha. …” ",
  "sn19.15:0.1": "Linked Discourses 19.15 ",
  "sn19.15:0.2": "Chapter Two ",
  "sn19.15:0.3": "A Sweltering Woman ",
  "sn19.15:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a scorched woman, sooty and sweaty, flying through the air, ",
  "sn19.15:1.2": "as she screamed in pain. …” … ",
  "sn19.15:1.3": "“That woman used to be the king of Kaliṅga’s chief queen. ",
  "sn19.15:1.4": "She was of jealous nature, and poured a brazier of hot coals over her co-wife. …” … ",
  "sn19.16:0.1": "Linked Discourses 19.16 ",
  "sn19.16:0.2": "Chapter Two ",
  "sn19.16:0.3": "A Headless Trunk ",
  "sn19.16:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a headless trunk flying through the air. ",
  "sn19.16:1.2": "Its eyes and mouth were on its chest. ",
  "sn19.16:1.3": "Vultures, crows, and hawks kept chasing it, pecking and clawing ",
  "sn19.16:1.4": "as it screamed in pain. …” … ",
  "sn19.16:1.5": "“That being used to be an executioner named Taker right here in Rājagaha. …” ",
  "sn19.17:0.1": "Linked Discourses 19.17 ",
  "sn19.17:0.2": "Chapter Two ",
  "sn19.17:0.3": "A Bad Monk ",
  "sn19.17:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a monk flying through the air. ",
  "sn19.17:1.2": "His outer robe, bowl, belt, and body were burning, blazing, and glowing ",
  "sn19.17:1.3": "as he screamed in pain. …” … ",
  "sn19.17:1.4": "“That monk used to be a bad monk in the time of Buddha Kassapa’s dispensation. …” ",
  "sn19.18:0.1": "Linked Discourses 19.18 ",
  "sn19.18:0.2": "Chapter Two ",
  "sn19.18:0.3": "A Bad Nun ",
  "sn19.18:1.1": "“I saw a nun flying through the air. ",
  "sn19.18:1.2": "Her outer robe was burning …” … ",
  "sn19.18:1.3": "“She used to be a bad nun …” ",
  "sn19.19:0.1": "Linked Discourses 19.19 ",
  "sn19.19:0.2": "Chapter Two ",
  "sn19.19:0.3": "A Bad Trainee Nun ",
  "sn19.19:1.1": "“I saw a trainee nun flying through the air. ",
  "sn19.19:1.2": "Her outer robe was burning …” … ",
  "sn19.19:1.3": "“She used to be a bad trainee nun …” ",
  "sn19.20:0.1": "Linked Discourses 19.20 ",
  "sn19.20:0.2": "Chapter Two ",
  "sn19.20:0.3": "A Bad Novice Monk ",
  "sn19.20:1.1": "“I saw a novice monk flying through the air. ",
  "sn19.20:1.2": "His outer robe was burning …” … ",
  "sn19.20:1.3": "“He used to be a bad novice monk …” ",
  "sn19.21:0.1": "Linked Discourses 19.21 ",
  "sn19.21:0.2": "Chapter Two ",
  "sn19.21:0.3": "A Bad Novice Nun ",
  "sn19.21:1.1": "“Just now, reverend, as I was descending from Vulture’s Peak Mountain I saw a novice nun flying through the air. ",
  "sn19.21:1.2": "Her outer robe, bowl, belt, and body were burning, blazing, and glowing ",
  "sn19.21:1.3": "as she screamed in pain. ",
  "sn19.21:1.4": "It occurred to me: ",
  "sn19.21:1.5": "‘Oh lord, how incredible, how amazing! ",
  "sn19.21:1.6": "That there can be such a sentient being, ",
  "sn19.21:1.7": "such a spirit, ",
  "sn19.21:1.8": "such an incarnation!’” ",
  "sn19.21:2.1": "Then the Buddha said to the mendicants: ",
  "sn19.21:2.2": "“Mendicants, there are disciples who live full of vision and knowledge, ",
  "sn19.21:2.3": "since a disciple knows, sees, and witnesses such a thing. ",
  "sn19.21:2.4": "Formerly, I too saw that novice nun, but I did not speak of it. ",
  "sn19.21:2.5": "",
  "sn19.21:2.6": "For if I had spoken of it others would not have believed me, ",
  "sn19.21:2.7": "which would be for their lasting harm and suffering. ",
  "sn19.21:2.8": "That female novice used to be a bad novice nun in the time of the Buddha Kassapa’s dispensation. ",
  "sn19.21:2.9": "As a result of that deed she burned in hell for many years, many hundreds, many thousands, many hundreds of thousands of years. Now she experiences the residual result of that deed in such an incarnation.” ",
  "sn19.21:2.10": "",
  "sn19.21:2.11": "",
  "sn19.21:3.1": "",
  "sn19.21:3.2": "",
  "sn19.21:3.3": "",
  "sn19.21:3.4": "",
  "sn19.21:3.5": "",
  "sn19.21:3.6": "",
  "sn19.21:4.1": "",
  "sn19.21:4.2": "",
  "sn19.21:4.3": "",
  "sn19.21:4.4": "",
  "sn19.21:4.5": "The Linked Discourses with Mark are complete. "
}
window.BILARA["sn19_v1"]["en"]["sn19_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
