window.BILARA = window.BILARA || {};
window.BILARA["sn1_v1"] = window.BILARA["sn1_v1"] || {};
window.BILARA["sn1_v1"]["en"] = {
  "sn1.1:0.1": "Linked Discourses 1.1 ",
  "sn1.1:0.2": "1. A Reed ",
  "sn1.1:0.3": "Crossing the Flood ",
  "sn1.1:1.1": "So I have heard. ",
  "sn1.1:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s Monastery. ",
  "sn1.1:1.3": "Then, late at night, a glorious deity, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, stood to one side, and said to him, ",
  "sn1.1:1.4": "“Good fellow, how did you cross the flood?” ",
  "sn1.1:1.5": "“Neither standing nor swimming, respectable sir, I crossed the flood.” ",
  "sn1.1:1.6": "“But in what way did you cross the flood neither standing nor swimming?” ",
  "sn1.1:1.7": "“When I stood, I sank under. ",
  "sn1.1:1.8": "When I swam, I was swept away. ",
  "sn1.1:1.9": "That’s how I crossed the flood neither standing nor swimming.” ",
  "sn1.1:2.1": "“After a long time I see ",
  "sn1.1:2.2": "a brahmin fully quenched. ",
  "sn1.1:2.3": "Neither standing nor swimming, ",
  "sn1.1:2.4": "he’s crossed over clinging to the world.” ",
  "sn1.1:3.1": "This is what that deity said, ",
  "sn1.1:3.2": "and the teacher approved. ",
  "sn1.1:3.3": "",
  "sn1.1:3.4": "Then that deity, knowing that the teacher approved, bowed and respectfully circled the Buddha, keeping him on his right, before vanishing right there. ",
  "sn1.2:0.1": "Linked Discourses 1.2 ",
  "sn1.2:0.2": "1. A Reed ",
  "sn1.2:0.3": "Liberation ",
  "sn1.2:1.1": "At Sāvatthī. ",
  "sn1.2:1.2": "Then, late at night, a glorious deity, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, stood to one side, and said to him, ",
  "sn1.2:2.1": "“Good fellow, do you know the liberation, emancipation, and seclusion of sentient beings?” ",
  "sn1.2:3.1": "“I do, good sir.” ",
  "sn1.2:4.1": "“But how is it that you know the liberation, emancipation, and seclusion of sentient beings?” ",
  "sn1.2:5.1": "“Due to the ending of relish for rebirth; ",
  "sn1.2:5.2": "due to the finishing of perception and consciousness; ",
  "sn1.2:5.3": "due to the cessation and stilling of feelings",
  "sn1.2:5.4": "that, respectable sir, is how I know the liberation, ",
  "sn1.2:5.5": "emancipation, and seclusion of sentient beings.” ",
  "sn1.3:0.1": "Linked Discourses 1.3 ",
  "sn1.3:0.2": "1. A Reed ",
  "sn1.3:0.3": "Led On ",
  "sn1.3:1.1": "At Sāvatthī. ",
  "sn1.3:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence: ",
  "sn1.3:2.1": "“This life, so very short, is led onward. ",
  "sn1.3:2.2": "One led on to old age has no shelter. ",
  "sn1.3:2.3": "Seeing this peril in death, ",
  "sn1.3:2.4": "do good deeds that bring you joy.” ",
  "sn1.3:3.1": "“This life, so very short, is led onward; ",
  "sn1.3:3.2": "one led on to old age has no shelter. ",
  "sn1.3:3.3": "Seeing this peril in death, ",
  "sn1.3:3.4": "a seeker of peace would drop the world’s bait.” ",
  "sn1.4:0.1": "Linked Discourses 1.4 ",
  "sn1.4:0.2": "1. A Reed ",
  "sn1.4:0.3": "Time Flies ",
  "sn1.4:1.1": "At Sāvatthī. ",
  "sn1.4:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence: ",
  "sn1.4:2.1": "“Time flies, nights pass by, ",
  "sn1.4:2.2": "the stages of life leave us one by one. ",
  "sn1.4:2.3": "Seeing this peril in death, ",
  "sn1.4:2.4": "do good deeds that bring you joy.” ",
  "sn1.4:3.1": "“Time flies, nights pass by, ",
  "sn1.4:3.2": "the stages of life leave us one by one. ",
  "sn1.4:3.3": "Seeing this peril in death, ",
  "sn1.4:3.4": "a seeker of peace would drop the world’s bait.” ",
  "sn1.5:0.1": "Linked Discourses 1.5 ",
  "sn1.5:0.2": "1. A Reed ",
  "sn1.5:0.3": "Cut How Many? ",
  "sn1.5:1.1": "At Sāvatthī. ",
  "sn1.5:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence: ",
  "sn1.5:2.1": "“Cut how many? Drop how many? ",
  "sn1.5:2.2": "Develop how many more? ",
  "sn1.5:2.3": "When a mendicant slips how many chains ",
  "sn1.5:2.4": "are they said to have crossed the flood?” ",
  "sn1.5:3.1": "“Five to cut, five to drop, ",
  "sn1.5:3.2": "and five more to develop. ",
  "sn1.5:3.3": "When a mendicant slips five chains ",
  "sn1.5:3.4": "they’re said to have crossed the flood.” ",
  "sn1.6:0.1": "Linked Discourses 1.6 ",
  "sn1.6:0.2": "1. A Reed ",
  "sn1.6:0.3": "Awake ",
  "sn1.6:1.1": "At Sāvatthī. ",
  "sn1.6:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence: ",
  "sn1.6:2.1": "“How many sleep among the waking? ",
  "sn1.6:2.2": "How many wake among the sleeping? ",
  "sn1.6:2.3": "By how many do you gather dust? ",
  "sn1.6:2.4": "By how many are you cleansed?” ",
  "sn1.6:3.1": "“Five sleep among the waking. ",
  "sn1.6:3.2": "Five wake among the sleeping. ",
  "sn1.6:3.3": "By five you gather dust. ",
  "sn1.6:3.4": "By five you’re cleansed.” ",
  "sn1.7:0.1": "Linked Discourses 1.7 ",
  "sn1.7:0.2": "1. A Reed ",
  "sn1.7:0.3": "Not Comprehending ",
  "sn1.7:1.1": "At Sāvatthī. ",
  "sn1.7:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence: ",
  "sn1.7:2.1": "“Those have not deciphered the teachings ",
  "sn1.7:2.2": "may be led astray by the doctrines of others. ",
  "sn1.7:2.3": "Asleep, they have not woken up: ",
  "sn1.7:2.4": "it is time for them to wake!” ",
  "sn1.7:3.1": "“Those who have well deciphered the teachings ",
  "sn1.7:3.2": "won’t be led astray by the doctrines of others. ",
  "sn1.7:3.3": "They have woken up, they rightly know, ",
  "sn1.7:3.4": "smoothly they walk in the rough.” ",
  "sn1.8:0.1": "Linked Discourses 1.8 ",
  "sn1.8:0.2": "1. A Reed ",
  "sn1.8:0.3": "Very Confused ",
  "sn1.8:1.1": "At Sāvatthī. ",
  "sn1.8:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence: ",
  "sn1.8:2.1": "“Those who are very confused about the teachings ",
  "sn1.8:2.2": "may be led astray by the doctrines of others. ",
  "sn1.8:2.3": "Asleep, they have not woken up: ",
  "sn1.8:2.4": "it is time for them to wake!” ",
  "sn1.8:3.1": "“Those who are unconfused about the teachings, ",
  "sn1.8:3.2": "won’t be led astray by the doctrines of others. ",
  "sn1.8:3.3": "They have woken up, they rightly know, ",
  "sn1.8:3.4": "smoothly they walk in the rough.” ",
  "sn1.9:0.1": "Linked Discourses 1.9 ",
  "sn1.9:0.2": "1. A Reed ",
  "sn1.9:0.3": "Fond of Conceit ",
  "sn1.9:1.1": "At Sāvatthī. ",
  "sn1.9:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence: ",
  "sn1.9:2.1": "“One fond of conceit can’t be tamed, ",
  "sn1.9:2.2": "no sage is lacking immersion. ",
  "sn1.9:2.3": "Living negligent alone in the wilderness, ",
  "sn1.9:2.4": "they can’t cross beyond Death’s dominion.” ",
  "sn1.9:3.1": "“Having given up conceit, serene within oneself, ",
  "sn1.9:3.2": "with a good heart, everywhere free; ",
  "sn1.9:3.3": "living diligent alone in the wilderness, ",
  "sn1.9:3.4": "they cross beyond Death’s dominion.” ",
  "sn1.10:0.1": "Linked Discourses 1.10 ",
  "sn1.10:0.2": "1. A Reed ",
  "sn1.10:0.3": "Wilderness ",
  "sn1.10:1.1": "At Sāvatthī. ",
  "sn1.10:1.2": "Standing to one side, that deity addressed the Buddha in verse: ",
  "sn1.10:2.1": "“Living in the wilderness, ",
  "sn1.10:2.2": "peaceful spiritual practitioners ",
  "sn1.10:2.3": "eat just one meal a day: ",
  "sn1.10:2.4": "so why is their complexion so clear?” ",
  "sn1.10:3.1": "“They don’t grieve for the past, ",
  "sn1.10:3.2": "nor do they pray for the future; ",
  "sn1.10:3.3": "they feed on whatever comes that day, ",
  "sn1.10:3.4": "that’s why their complexion’s so clear. ",
  "sn1.10:4.1": "Because they long for the future, ",
  "sn1.10:4.2": "and grieve for the past, ",
  "sn1.10:4.3": "fools wither away, ",
  "sn1.10:4.4": "like a green reed mowed down.” ",
  "sn1.10:4.5": "",
  "sn1.10:5.1": "",
  "sn1.10:5.2": "",
  "sn1.10:5.3": "",
  "sn1.10:5.4": "",
  "sn1.10:5.5": "",
  "sn1.11:0.1": "Linked Discourses 1.11 ",
  "sn1.11:0.2": "2. The Garden of Delight ",
  "sn1.11:0.3": "The Garden of Delight ",
  "sn1.11:1.1": "So I have heard. ",
  "sn1.11:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn1.11:1.3": "There the Buddha addressed the mendicants, ",
  "sn1.11:1.4": "“Mendicants!” ",
  "sn1.11:1.5": "“Venerable sir,” they replied. ",
  "sn1.11:1.6": "The Buddha said this: ",
  "sn1.11:2.1": "“Once upon a time, mendicants, a certain deity of the company of the thirty-three was amusing themselves in the Garden of Delight, escorted by a band of nymphs, and supplied and provided with the five kinds of heavenly sensual stimulation. On that occasion she spoke this verse: ",
  "sn1.11:3.1": "‘They don’t know pleasure ",
  "sn1.11:3.2": "who don’t see the Garden of Delight! ",
  "sn1.11:3.3": "It’s the abode of lordly gods, ",
  "sn1.11:3.4": "the glorious host of Thirty!’ ",
  "sn1.11:4.1": "When they had spoken, another deity replied with this verse: ",
  "sn1.11:5.1": "‘Fool, don’t you understand ",
  "sn1.11:5.2": "the saying of the perfected ones: ",
  "sn1.11:5.3": "All conditions are impermanent, ",
  "sn1.11:5.4": "their nature is to rise and fall; ",
  "sn1.11:5.5": "having arisen, they cease; ",
  "sn1.11:5.6": "their settling is such bliss.’” ",
  "sn1.12:0.1": "Linked Discourses 1.12 ",
  "sn1.12:0.2": "2. The Garden of Delight ",
  "sn1.12:0.3": "Delight ",
  "sn1.12:1.1": "At Sāvatthī. ",
  "sn1.12:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence: ",
  "sn1.12:2.1": "“Children bring you delight! ",
  "sn1.12:2.2": "Cattle also bring you delight! ",
  "sn1.12:2.3": "For attachments are a man’s delight; ",
  "sn1.12:2.4": "without attachments there’s no delight.” ",
  "sn1.12:3.1": "“Children bring you sorrow. ",
  "sn1.12:3.2": "Cattle also bring you sorrow. ",
  "sn1.12:3.3": "For attachments are a man’s sorrow; ",
  "sn1.12:3.4": "without attachments there are no sorrows.” ",
  "sn1.13:0.1": "Linked Discourses 1.13 ",
  "sn1.13:0.2": "2. The Garden of Delight ",
  "sn1.13:0.3": "There’s Nothing Like a Child ",
  "sn1.13:1.1": "At Sāvatthī. ",
  "sn1.13:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence: ",
  "sn1.13:2.1": "“There’s no fondness like that for a child, ",
  "sn1.13:2.2": "no wealth equal to cattle, ",
  "sn1.13:2.3": "no light like that of the sun, ",
  "sn1.13:2.4": "and of lakes the ocean is paramount.” ",
  "sn1.13:3.1": "“There’s no fondness like that for oneself, ",
  "sn1.13:3.2": "no wealth equal to grain, ",
  "sn1.13:3.3": "no light like that of wisdom, ",
  "sn1.13:3.4": "and of waters the rain is paramount.” ",
  "sn1.14:0.1": "Linked Discourses 1.14 ",
  "sn1.14:0.2": "2. The Garden of Delight ",
  "sn1.14:0.3": "Aristocrats ",
  "sn1.14:1.1": "“An aristocrat is the best of bipeds, ",
  "sn1.14:1.2": "an ox is the best of quadrupeds, ",
  "sn1.14:1.3": "a maiden is the best of wives, ",
  "sn1.14:1.4": "and a first-born the best of sons.” ",
  "sn1.14:2.1": "“A Buddha is the best of bipeds, ",
  "sn1.14:2.2": "a thoroughbred, the best of quadrupeds, ",
  "sn1.14:2.3": "a good listener is the best of wives, ",
  "sn1.14:2.4": "and the best of sons is loyal.” ",
  "sn1.15:0.1": "Linked Discourses 1.15 ",
  "sn1.15:0.2": "2. The Garden of Delight ",
  "sn1.15:0.3": "Whispering ",
  "sn1.15:1.1": "“In the still of high noon, ",
  "sn1.15:1.2": "when the birds have settled down, ",
  "sn1.15:1.3": "the mighty forest itself resounds",
  "sn1.15:1.4": "that strikes me as so scary!” ",
  "sn1.15:2.1": "“In the still of high noon, ",
  "sn1.15:2.2": "when the birds have settled down, ",
  "sn1.15:2.3": "the mighty forest itself resounds",
  "sn1.15:2.4": "that strikes me as so delightful!” ",
  "sn1.16:0.1": "Linked Discourses 1.16 ",
  "sn1.16:0.2": "2. The Garden of Delight ",
  "sn1.16:0.3": "Sleepiness and Sloth ",
  "sn1.16:1.1": "“Sleepiness, sloth, and yawning, ",
  "sn1.16:1.2": "discontent, and grogginess after eating: ",
  "sn1.16:1.3": "because of this the noble path ",
  "sn1.16:1.4": "doesn’t shine for creatures here.” ",
  "sn1.16:2.1": "“Sleepiness, sloth, and yawning, ",
  "sn1.16:2.2": "discontent, and grogginess after eating: ",
  "sn1.16:2.3": "when this is energetically fended off, ",
  "sn1.16:2.4": "the noble path is purified.” ",
  "sn1.17:0.1": "Linked Discourses 1.17 ",
  "sn1.17:0.2": "2. The Garden of Delight ",
  "sn1.17:0.3": "Hard to Do ",
  "sn1.17:1.1": "“Hard to do, hard to endure, ",
  "sn1.17:1.2": "is the ascetic life for the inept, ",
  "sn1.17:1.3": "for it has many narrow passes ",
  "sn1.17:1.4": "where the fool founders.” ",
  "sn1.17:2.1": "“How many days could an ascetic live ",
  "sn1.17:2.2": "without controlling the mind? ",
  "sn1.17:2.3": "They’d founder with each step, ",
  "sn1.17:2.4": "under the sway of thoughts. ",
  "sn1.17:3.1": "A mendicant should collect their thoughts ",
  "sn1.17:3.2": "as a tortoise draws its limbs into its shell. ",
  "sn1.17:3.3": "Independent, not disturbing others, ",
  "sn1.17:3.4": "quenched: they wouldn’t blame anyone.” ",
  "sn1.18:0.1": "Linked Discourses 1.18 ",
  "sn1.18:0.2": "2. The Garden of Delight ",
  "sn1.18:0.3": "Conscience ",
  "sn1.18:1.1": "“Can a person constrained by conscience ",
  "sn1.18:1.2": "be found in the world, ",
  "sn1.18:1.3": "who is cognizant of blame, ",
  "sn1.18:1.4": "like a fine horse of the whip?” ",
  "sn1.18:2.1": "“Few are those constrained by conscience, ",
  "sn1.18:2.2": "who live always mindful. ",
  "sn1.18:2.3": "Having reached the end of suffering, ",
  "sn1.18:2.4": "smoothly they walk in the rough.” ",
  "sn1.19:0.1": "Linked Discourses 1.19 ",
  "sn1.19:0.2": "2. The Garden of Delight ",
  "sn1.19:0.3": "Little Hut ",
  "sn1.19:1.1": "“Don’t you have a little hut? ",
  "sn1.19:1.2": "Don’t you have a little nest? ",
  "sn1.19:1.3": "Don’t you have any networks? ",
  "sn1.19:1.4": "Aren’t you free of shackles?” ",
  "sn1.19:2.1": "“Indeed I have no little hut. ",
  "sn1.19:2.2": "Indeed I have no little nest. ",
  "sn1.19:2.3": "Indeed I have no networks. ",
  "sn1.19:2.4": "Indeed I’m free from shackles.” ",
  "sn1.19:3.1": "“What do you think I call your little hut? ",
  "sn1.19:3.2": "What do I call your little nest? ",
  "sn1.19:3.3": "What do I call your network? ",
  "sn1.19:3.4": "And what do I call your shackle?” ",
  "sn1.19:4.1": "“You call mother a little hut; ",
  "sn1.19:4.2": "and wife a little nest. ",
  "sn1.19:4.3": "You call children a network, ",
  "sn1.19:4.4": "and you call my craving a shackle.” ",
  "sn1.19:5.1": "“It’s good you have no little hut! ",
  "sn1.19:5.2": "It’s good you have no little nest! ",
  "sn1.19:5.3": "It’s good you have no networks! ",
  "sn1.19:5.4": "And good that you’re free from shackles.” ",
  "sn1.20:0.1": "Linked Discourses 1.20 ",
  "sn1.20:0.2": "2. The Garden of Delight ",
  "sn1.20:0.3": "With Samiddhi ",
  "sn1.20:1.1": "So I have heard. ",
  "sn1.20:1.2": "At one time the Buddha was staying near Rājagaha in the Hot Springs Monastery. ",
  "sn1.20:1.3": "Then Venerable Samiddhi rose at the crack of dawn and went to the hot springs to bathe. ",
  "sn1.20:1.4": "When he had bathed and emerged from the water he stood in one robe drying his limbs. ",
  "sn1.20:1.5": "Then, late at night, a glorious deity, lighting up the entire hot springs, went up to Samiddhi, and, standing in the air, addressed him in verse: ",
  "sn1.20:2.1": "“Mendicant, you seek alms before you eat; ",
  "sn1.20:2.2": "you don’t seek alms after eating. ",
  "sn1.20:2.3": "But you should eat first, then seek alms: ",
  "sn1.20:2.4": "don’t let the time pass you by.” ",
  "sn1.20:3.1": "“I actually don’t know the time; ",
  "sn1.20:3.2": "it’s hidden and unseen. ",
  "sn1.20:3.3": "That’s why I seek alms before eating, ",
  "sn1.20:3.4": "so that the time may not pass me by!” ",
  "sn1.20:4.1": "Then that deity landed on the ground and said to Samiddhi, ",
  "sn1.20:4.2": "“You’ve gone forth while young, mendicant. With pristine black hair, you’re blessed with youth, in the prime of life, and you’ve never flirted with sensual pleasures. ",
  "sn1.20:4.3": "Enjoy human sensual pleasures! ",
  "sn1.20:4.4": "Don’t give up what is apparent in the present to chase after what takes effect over time.” ",
  "sn1.20:5.1": "“I’m not, reverend. ",
  "sn1.20:5.2": "I’m giving up what takes effect over time to chase after what is apparent in the present. ",
  "sn1.20:5.3": "For the Buddha has said that sensual pleasures take effect over time, with much suffering and distress, and they’re all the more full of drawbacks. ",
  "sn1.20:5.4": "But this teaching is apparent in the present life, immediately effective, inviting inspection, relevant, so that sensible people can know it for themselves.” ",
  "sn1.20:6.1": "“But in what way, mendicant, has the Buddha said that sensual pleasures take effect over time, with much suffering and distress, and they’re all the more full of drawbacks? ",
  "sn1.20:6.2": "And how is this teaching apparent in the present life, immediately effective, inviting inspection, relevant, so that sensible people can know it for themselves?” ",
  "sn1.20:7.1": "“I’m junior, respectable sir, recently gone forth, newly come to this teaching and training. ",
  "sn1.20:7.2": "I’m not able to explain this in detail. ",
  "sn1.20:7.3": "But he, that Blessed One, the perfected one, the fully awakened Buddha, is staying near Rājagaha in the Hot Springs Monastery. ",
  "sn1.20:7.4": "You should approach him and ask about this matter. ",
  "sn1.20:7.5": "And you should remember it in line with the Buddha’s answer.” ",
  "sn1.20:8.1": "“It’s not easy for us to approach the Buddha, as he is surrounded by other illustrious deities. ",
  "sn1.20:8.2": "If you go to the Buddha and ask him about this matter, we’ll come along and listen to the teaching.” ",
  "sn1.20:8.3": "“Yes, reverend,” Venerable Samiddhi replied. He went to the Buddha, bowed, sat down to one side, and told him what had happened. Then he added: ",
  "sn1.20:9.1": "",
  "sn1.20:9.2": "",
  "sn1.20:9.3": "",
  "sn1.20:10.1": "",
  "sn1.20:10.2": "",
  "sn1.20:10.3": "",
  "sn1.20:10.4": "",
  "sn1.20:11.1": "",
  "sn1.20:12.1": "",
  "sn1.20:12.2": "",
  "sn1.20:12.3": "",
  "sn1.20:12.4": "",
  "sn1.20:13.1": "",
  "sn1.20:13.2": "",
  "sn1.20:13.3": "",
  "sn1.20:13.4": "",
  "sn1.20:14.1": "",
  "sn1.20:14.2": "",
  "sn1.20:14.3": "",
  "sn1.20:14.4": "",
  "sn1.20:14.5": "",
  "sn1.20:15.1": "",
  "sn1.20:15.2": "",
  "sn1.20:15.3": "",
  "sn1.20:16.1": "",
  "sn1.20:16.2": "",
  "sn1.20:16.3": "",
  "sn1.20:16.4": "",
  "sn1.20:16.5": "",
  "sn1.20:17.1": "",
  "sn1.20:17.2": "",
  "sn1.20:17.3": "",
  "sn1.20:17.4": "“Sir, if that deity spoke the truth, he’ll be close by.” ",
  "sn1.20:18.1": "When he had spoken, that deity said to Samiddhi, ",
  "sn1.20:18.2": "“Ask, mendicant, ask! For I have arrived.” ",
  "sn1.20:19.1": "Then the Buddha addressed the deity in verse: ",
  "sn1.20:20.1": "“Sentient beings who perceive the communicable, ",
  "sn1.20:20.2": "become established in the communicable. ",
  "sn1.20:20.3": "Not understanding the communicable, ",
  "sn1.20:20.4": "they fall under the yoke of Death. ",
  "sn1.20:21.1": "But having fully understood the communicable, ",
  "sn1.20:21.2": "they don’t conceive a communicator, ",
  "sn1.20:21.3": "for they have nothing ",
  "sn1.20:21.4": "by which they might be described. ",
  "sn1.20:21.5": "Tell me if you understand, spirit.” ",
  "sn1.20:22.1": "“I don’t understand the detailed meaning of the Buddha’s brief statement. ",
  "sn1.20:22.2": "Please teach me this matter so I can understand the detailed meaning.” ",
  "sn1.20:23.1": "“If you think that ‘I’m equal, ",
  "sn1.20:23.2": "special, or worse’, you’ll dispute about that. ",
  "sn1.20:23.3": "Unwavering in the face of the three discriminations, ",
  "sn1.20:23.4": "you’ll have no thought ‘I’m equal or special’. ",
  "sn1.20:23.5": "Tell me if you understand, spirit.” ",
  "sn1.20:24.1": "“I don’t understand the detailed meaning of the Buddha’s brief statement. ",
  "sn1.20:24.2": "Please teach me this matter so I can understand the detailed meaning.” ",
  "sn1.20:25.1": "“They gave up judgement without falling into conceit; ",
  "sn1.20:25.2": "craving for name and form was cut off right here. ",
  "sn1.20:25.3": "They cut the ties, untroubled, <j>with no need for hope. ",
  "sn1.20:25.4": "Though gods and humans search for them ",
  "sn1.20:25.5": "in this life or the next, they never find them, ",
  "sn1.20:25.6": "not in heaven nor in any abode. ",
  "sn1.20:26.1": "Tell me if you understand, spirit.” ",
  "sn1.20:27.1": "“This is how I understand the detailed meaning of the Buddha’s brief statement: ",
  "sn1.20:28.1": "You should never do anything bad ",
  "sn1.20:28.2": "by speech or mind or body in all the world. ",
  "sn1.20:28.3": "Having given up sensual pleasures, <j>mindful and aware, ",
  "sn1.20:28.4": "you shouldn’t keep doing  <j>what’s painful and pointless.” ",
  "sn1.20:28.5": "",
  "sn1.20:29.1": "",
  "sn1.20:29.2": "",
  "sn1.20:29.3": "",
  "sn1.20:29.4": "",
  "sn1.20:29.5": "",
  "sn1.21:0.1": "Linked Discourses 1.21 ",
  "sn1.21:0.2": "3. A Sword ",
  "sn1.21:0.3": "A Sword ",
  "sn1.21:1.1": "At Sāvatthī. ",
  "sn1.21:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence: ",
  "sn1.21:2.1": "“Like they’re struck by a sword, ",
  "sn1.21:2.2": "like their head was on fire, ",
  "sn1.21:2.3": "a mendicant, mindful, should go forth, ",
  "sn1.21:2.4": "to give up sensual desire.” ",
  "sn1.21:3.1": "“Like they’re struck by a sword, ",
  "sn1.21:3.2": "like their head was on fire, ",
  "sn1.21:3.3": "a mendicant, mindful, should go forth, ",
  "sn1.21:3.4": "to give up substantialist view.” ",
  "sn1.22:0.1": "Linked Discourses 1.22 ",
  "sn1.22:0.2": "3. A Sword ",
  "sn1.22:0.3": "Impact ",
  "sn1.22:1.1": "“It doesn’t impact one who doesn’t impact others. ",
  "sn1.22:1.2": "It impacts one because they impact others. ",
  "sn1.22:1.3": "That’s why it impacts one who impacts, ",
  "sn1.22:1.4": "who wrongs one who’s done no wrong.” ",
  "sn1.22:2.1": "“Whoever wrongs a man who has done no wrong, ",
  "sn1.22:2.2": "a pure man who has not a blemish, ",
  "sn1.22:2.3": "the evil backfires on the fool, ",
  "sn1.22:2.4": "like fine dust thrown upwind.” ",
  "sn1.23:0.1": "Linked Discourses 1.23 ",
  "sn1.23:0.2": "3. A Sword ",
  "sn1.23:0.3": "A Tangle ",
  "sn1.23:1.1": "“Tangled within, tangled without: ",
  "sn1.23:1.2": "these people are tangled in tangles. ",
  "sn1.23:1.3": "I ask you this, Gotama: ",
  "sn1.23:1.4": "who can untangle this tangle?” ",
  "sn1.23:2.1": "“A wise person grounded in ethics, ",
  "sn1.23:2.2": "developing the mind and wisdom, ",
  "sn1.23:2.3": "a keen and alert mendicant",
  "sn1.23:2.4": "they can untangle this tangle. ",
  "sn1.23:3.1": "Those in whom greed, hate, and ignorance ",
  "sn1.23:3.2": "have faded away; ",
  "sn1.23:3.3": "the perfected ones with defilements ended",
  "sn1.23:3.4": "they have untangled the tangle. ",
  "sn1.23:4.1": "And where name and form ",
  "sn1.23:4.2": "cease with no residue left behind; ",
  "sn1.23:4.3": "and impingement and perception of form: ",
  "sn1.23:4.4": "it’s here that the tangle is cut.” ",
  "sn1.24:0.1": "Linked Discourses 1.24 ",
  "sn1.24:0.2": "3. A Sword ",
  "sn1.24:0.3": "Shielding the Mind ",
  "sn1.24:1.1": "“Whatever you’ve shielded the mind from ",
  "sn1.24:1.2": "can’t cause you suffering. ",
  "sn1.24:1.3": "So you should shield the mind from everything, ",
  "sn1.24:1.4": "then you’re freed from all suffering.” ",
  "sn1.24:2.1": "“You need not shield the mind from everything, ",
  "sn1.24:2.2": "nor has the mind gained self-control. ",
  "sn1.24:2.3": "The mind need only be shielded ",
  "sn1.24:2.4": "from where the bad things come.” ",
  "sn1.25:0.1": "Linked Discourses 1.25 ",
  "sn1.25:0.2": "3. A Sword ",
  "sn1.25:0.3": "A Perfected One ",
  "sn1.25:1.1": "“When a mendicant is perfected, proficient, ",
  "sn1.25:1.2": "with defilements ended, bearing the final body: ",
  "sn1.25:1.3": "would they say, ‘I speak’, ",
  "sn1.25:1.4": "or even ‘they speak to me’?” ",
  "sn1.25:2.1": "“When a mendicant is perfected, proficient, ",
  "sn1.25:2.2": "with defilements ended, bearing the final body: ",
  "sn1.25:2.3": "they would say, ‘I speak’, ",
  "sn1.25:2.4": "and also ‘they speak to me’. ",
  "sn1.25:2.5": "Skillful, understanding the world’s labels, ",
  "sn1.25:2.6": "they’d use these terms as mere expressions.” ",
  "sn1.25:3.1": "“When a mendicant is perfected, proficient, ",
  "sn1.25:3.2": "with defilements ended, bearing the final body: ",
  "sn1.25:3.3": "is such a mendicant drawing close to conceit ",
  "sn1.25:3.4": "if they’d say, ‘I speak’, ",
  "sn1.25:3.5": "or even ‘they speak to me’?” ",
  "sn1.25:4.1": "“Someone who has given up conceit has no ties, ",
  "sn1.25:4.2": "the ties of conceit are all dissipated. ",
  "sn1.25:4.3": "Though that intelligent person has passed beyond conceiving, ",
  "sn1.25:4.4": "they’d still say, ‘I speak’, ",
  "sn1.25:5.1": "and also ‘they speak to me’. ",
  "sn1.25:5.2": "Skillful, understanding the world’s labels, ",
  "sn1.25:5.3": "they’d use these terms as mere expressions.” ",
  "sn1.26:0.1": "Linked Discourses 1.26 ",
  "sn1.26:0.2": "3. A Sword ",
  "sn1.26:0.3": "Lamps ",
  "sn1.26:1.1": "“How many lamps are there ",
  "sn1.26:1.2": "that light up the world? ",
  "sn1.26:1.3": "We’ve come to ask you, worthy sir: ",
  "sn1.26:1.4": "how are we to understand this?” ",
  "sn1.26:2.1": "“There are four lamps in the world, ",
  "sn1.26:2.2": "a fifth is not found. ",
  "sn1.26:2.3": "The sun blazes by day, ",
  "sn1.26:2.4": "the moon radiates at night, ",
  "sn1.26:3.1": "while a fire illuminates both ",
  "sn1.26:3.2": "by day and by night. ",
  "sn1.26:3.3": "But a Buddha is the best of blazes: ",
  "sn1.26:3.4": "this is the supreme radiance.” ",
  "sn1.27:0.1": "Linked Discourses 1.27 ",
  "sn1.27:0.2": "3. A Sword ",
  "sn1.27:0.3": "Streams ",
  "sn1.27:1.1": "“From where do streams recoil? ",
  "sn1.27:1.2": "Where does the cycle spin no more? ",
  "sn1.27:1.3": "Where does name and form ",
  "sn1.27:1.4": "cease with no residue left behind?” ",
  "sn1.27:2.1": "“Where water and earth, ",
  "sn1.27:2.2": "fire and air have no footing",
  "sn1.27:2.3": "from here the streams recoil; ",
  "sn1.27:2.4": "in reference to this, the cycle spins no more; ",
  "sn1.27:2.5": "in reference to this, name and form ",
  "sn1.27:2.6": "ceases with no residue left behind.” ",
  "sn1.28:0.1": "Linked Discourses 1.28 ",
  "sn1.28:0.2": "3. A Sword ",
  "sn1.28:0.3": "Affluent ",
  "sn1.28:1.1": "“The affluent and the wealthy, ",
  "sn1.28:1.2": "even the aristocrats who rule the land, ",
  "sn1.28:1.3": "are jealous of each other, ",
  "sn1.28:1.4": "insatiable in sensual pleasures. ",
  "sn1.28:2.1": "Among those of such an avid nature, ",
  "sn1.28:2.2": "flowing along the stream of lives, ",
  "sn1.28:2.3": "who here has given up craving? ",
  "sn1.28:2.4": "Who in the world is not avid?” ",
  "sn1.28:3.1": "“Having given up their home, their child, their cattle, ",
  "sn1.28:3.2": "and all that they love, they went forth. ",
  "sn1.28:3.3": "Having given up desire and hate, ",
  "sn1.28:3.4": "having dispelled ignorance, ",
  "sn1.28:3.5": "the perfected ones with defilements ended",
  "sn1.28:3.6": "they in the world are not avid.” ",
  "sn1.29:0.1": "Linked Discourses 1.29 ",
  "sn1.29:0.2": "3. A Sword ",
  "sn1.29:0.3": "Four Wheels ",
  "sn1.29:1.1": "“Four are its wheels, and nine its doors; ",
  "sn1.29:1.2": "it’s stuffed full, bound with greed, ",
  "sn1.29:1.3": "and born from a bog. ",
  "sn1.29:1.4": "Great hero, how will I keep going?” ",
  "sn1.29:2.1": "“Having cut the strap and harness",
  "sn1.29:2.2": "the wicked desire and greed",
  "sn1.29:2.3": "and having plucked out craving, root and all: ",
  "sn1.29:2.4": "that’s how you will keep going.” ",
  "sn1.30:0.1": "Linked Discourses 1.30 ",
  "sn1.30:0.2": "3. A Sword ",
  "sn1.30:0.3": "Antelope Calves ",
  "sn1.30:1.1": "“O hero so lean, with antelope calves, ",
  "sn1.30:1.2": "not greedy, eating little, ",
  "sn1.30:1.3": "a giant, wandering alone like a lion, ",
  "sn1.30:1.4": "you’re not concerned for sensual pleasures. ",
  "sn1.30:1.5": "We’ve come to ask a question: ",
  "sn1.30:1.6": "How is one released from all suffering?” ",
  "sn1.30:2.1": "“The world has five kinds of sensual stimulation, ",
  "sn1.30:2.2": "and the mind is said to be the sixth. ",
  "sn1.30:2.3": "When you’ve discarded desire for these, ",
  "sn1.30:2.4": "you’re released from all suffering.” ",
  "sn1.30:2.5": "",
  "sn1.30:3.1": "",
  "sn1.30:3.2": "",
  "sn1.30:3.3": "",
  "sn1.30:3.4": "",
  "sn1.30:3.5": "",
  "sn1.31:0.1": "Linked Discourses 1.31 ",
  "sn1.31:0.2": "4. The Host of a Hundred Felicities ",
  "sn1.31:0.3": "Virtuous ",
  "sn1.31:1.1": "So I have heard. ",
  "sn1.31:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s Monastery. ",
  "sn1.31:1.3": "Then, late at night, several glorious deities of the host of a hundred felicities, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, and stood to one side. ",
  "sn1.31:1.4": "Standing to one side, one deity spoke this verse in the Buddha’s presence: ",
  "sn1.31:2.1": "“Associate only with the virtuous! ",
  "sn1.31:2.2": "Try to get close to the virtuous! ",
  "sn1.31:2.3": "Understanding the true teaching of the good, ",
  "sn1.31:2.4": "things get better, not worse.” ",
  "sn1.31:3.1": "Then another deity spoke this verse in the Buddha’s presence: ",
  "sn1.31:4.1": "“Associate only with the virtuous! ",
  "sn1.31:4.2": "Try to get close to the virtuous! ",
  "sn1.31:4.3": "Understanding the true teaching of the good, ",
  "sn1.31:4.4": "wisdom is gainedbut not from anyone else.” ",
  "sn1.31:5.1": "Then another deity spoke this verse in the Buddha’s presence: ",
  "sn1.31:6.1": "“Associate only with the virtuous! ",
  "sn1.31:6.2": "Try to get close to the virtuous! ",
  "sn1.31:6.3": "Understanding the true teaching of the good, ",
  "sn1.31:6.4": "you grieve not among the grieving.” ",
  "sn1.31:7.1": "Then another deity spoke this verse in the Buddha’s presence: ",
  "sn1.31:8.1": "“Associate only with the virtuous! ",
  "sn1.31:8.2": "Try to get close to the virtuous! ",
  "sn1.31:8.3": "Understanding the true teaching of the good, ",
  "sn1.31:8.4": "you shine among your relatives.” ",
  "sn1.31:9.1": "Then another deity spoke this verse in the Buddha’s presence: ",
  "sn1.31:10.1": "“Associate only with the virtuous! ",
  "sn1.31:10.2": "Try to get close to the virtuous! ",
  "sn1.31:10.3": "Understanding the true teaching of the good, ",
  "sn1.31:10.4": "sentient beings go to a good place.” ",
  "sn1.31:11.1": "Then another deity spoke this verse in the Buddha’s presence: ",
  "sn1.31:12.1": "“Associate only with the virtuous! ",
  "sn1.31:12.2": "Try to get close to the virtuous! ",
  "sn1.31:12.3": "Understanding the true teaching of the good, ",
  "sn1.31:12.4": "sentient beings live happily.” ",
  "sn1.31:13.1": "Then another deity said to the Buddha, ",
  "sn1.31:13.2": "“Sir, who has spoken well?” ",
  "sn1.31:14.1": "“You’ve all spoken well in your own way. However, listen to me also: ",
  "sn1.31:15.1": "Associate only with the virtuous! ",
  "sn1.31:15.2": "Try to get close to the virtuous! ",
  "sn1.31:15.3": "Understanding the true teaching of the good, ",
  "sn1.31:15.4": "you’re released from all suffering.” ",
  "sn1.31:16.1": "That is what the Buddha said. ",
  "sn1.31:16.2": "Then those deities, knowing that the teacher approved, bowed and respectfully circled the Buddha, keeping him on their right, before vanishing right there. ",
  "sn1.32:0.1": "Linked Discourses 1.32 ",
  "sn1.32:0.2": "4. The Host of a Hundred Felicities ",
  "sn1.32:0.3": "Stinginess ",
  "sn1.32:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn1.32:1.2": "Then, late at night, several glorious deities of the host of a hundred felicities, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, and stood to one side. ",
  "sn1.32:1.3": "Standing to one side, one deity spoke this verse in the Buddha’s presence: ",
  "sn1.32:2.1": "“Because of stinginess and negligence ",
  "sn1.32:2.2": "a gift is not given. ",
  "sn1.32:2.3": "Wanting merit, ",
  "sn1.32:2.4": "a smart person would give.” ",
  "sn1.32:3.1": "Then another deity recited these verses in the Buddha’s presence: ",
  "sn1.32:4.1": "“When a miser fails to give because of fear, ",
  "sn1.32:4.2": "the very thing they’re afraid of comes to pass. ",
  "sn1.32:4.3": "The hunger and thirst ",
  "sn1.32:4.4": "that a miser fears ",
  "sn1.32:4.5": "hurt the fool ",
  "sn1.32:4.6": "in this world and the next. ",
  "sn1.32:5.1": "So you should dispel stinginess, ",
  "sn1.32:5.2": "overcoming that stain, and give a gift. ",
  "sn1.32:5.3": "The good deeds of sentient beings ",
  "sn1.32:5.4": "support them in the next world.” ",
  "sn1.32:6.1": "Then another deity recited these verses in the Buddha’s presence: ",
  "sn1.32:7.1": "“Among the dead they do not die, ",
  "sn1.32:7.2": "those who, like fellow travelers on the road, ",
  "sn1.32:7.3": "are happy to provide, though they have but little. ",
  "sn1.32:7.4": "This is an ancient teaching. ",
  "sn1.32:8.1": "Some who have little are happy to provide, ",
  "sn1.32:8.2": "while some who have much don’t wish to give. ",
  "sn1.32:8.3": "An offering given from little ",
  "sn1.32:8.4": "is multiplied a thousand times.” ",
  "sn1.32:9.1": "Then another deity recited these verses in the Buddha’s presence: ",
  "sn1.32:10.1": "“Giving what’s hard to give, ",
  "sn1.32:10.2": "doing what’s hard to do; ",
  "sn1.32:10.3": "the wicked don’t act like this, ",
  "sn1.32:10.4": "for the teaching of the good is hard to follow. ",
  "sn1.32:11.1": "That’s why the virtuous and the wicked ",
  "sn1.32:11.2": "have different destinations after here. ",
  "sn1.32:11.3": "The wicked go to hell, ",
  "sn1.32:11.4": "while the virtuous are bound for heaven.” ",
  "sn1.32:12.1": "Then another deity said to the Buddha, ",
  "sn1.32:12.2": "“Sir, who has spoken well?” ",
  "sn1.32:13.1": "“You’ve all spoken well in your own way. However, listen to me also: ",
  "sn1.32:14.1": "A hundred thousand people <j>making a thousand sacrifices ",
  "sn1.32:14.2": "isn’t worth a fraction of that sort, ",
  "sn1.32:14.3": "who lives rightly, wandering for gleanings, ",
  "sn1.32:14.4": "or one who supports their partner <j>with what little they have.” ",
  "sn1.32:15.1": "Then another deity addressed the Buddha in verse: ",
  "sn1.32:16.1": "“Why doesn’t that sacrifice of theirs, so abundant and magnificent, ",
  "sn1.32:16.2": "equal the value of a moral person’s gift? ",
  "sn1.32:16.3": "How is it that a hundred thousand people  <j>making a thousand sacrifices ",
  "sn1.32:16.4": "isn’t worth a fraction of what’s offered by that sort?” ",
  "sn1.32:17.1": "“Some give based on immorality",
  "sn1.32:17.2": "after slaying, killing, and tormenting. ",
  "sn1.32:17.3": "Such an offeringtearful, violent",
  "sn1.32:17.4": "in no way equals the value of a moral person’s gift. ",
  "sn1.32:18.1": "That’s how it is that a hundred thousand people  <j>making a thousand sacrifices ",
  "sn1.32:18.2": "isn’t worth a fraction of what’s offered by that sort.” ",
  "sn1.33:0.1": "Linked Discourses 1.33 ",
  "sn1.33:0.2": "4. The Host of a Hundred Felicities ",
  "sn1.33:0.3": "Good ",
  "sn1.33:1.1": "At Sāvatthī. ",
  "sn1.33:1.2": "Then, late at night, several glorious deities of the host of a hundred felicities, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, and stood to one side. ",
  "sn1.33:1.3": "Standing to one side, one deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.33:2.1": "“Good, good fellow, is giving! ",
  "sn1.33:2.2": "Because of stinginess and negligence ",
  "sn1.33:2.3": "a gift is not given. ",
  "sn1.33:2.4": "Wanting merit, ",
  "sn1.33:2.5": "a smart person would give.” ",
  "sn1.33:3.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.33:4.1": "“Good, good fellow, is giving! ",
  "sn1.33:4.2": "Even when one has little, giving is good. ",
  "sn1.33:5.1": "Some who have little are happy to provide, ",
  "sn1.33:5.2": "while some who have much don’t wish to give. ",
  "sn1.33:5.3": "An offering given from little ",
  "sn1.33:5.4": "is multiplied a thousand times.” ",
  "sn1.33:6.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.33:7.1": "“Good, good fellow, is giving! ",
  "sn1.33:7.2": "Even when one has little, giving is good. ",
  "sn1.33:7.3": "And it’s also good to give out of faith. ",
  "sn1.33:7.4": "Giving and warfare are similar, they say, ",
  "sn1.33:7.5": "for even a few of the good may conquer the many. ",
  "sn1.33:7.6": "If a faithful person gives even a little, ",
  "sn1.33:7.7": "it still brings them happiness in the hereafter.” ",
  "sn1.33:8.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.33:9.1": "“Good, good fellow, is giving! ",
  "sn1.33:9.2": "Even when one has little, giving is good. ",
  "sn1.33:9.3": "And it’s also good to give out of faith. ",
  "sn1.33:9.4": "And it’s also good to give legitimate wealth. ",
  "sn1.33:10.1": "A personage who gives legitimate wealth, ",
  "sn1.33:10.2": "earned by his efforts and initiative, ",
  "sn1.33:10.3": "has passed over Yama’s Vetaraṇī River; ",
  "sn1.33:10.4": "that mortal arrives at celestial fields.” ",
  "sn1.33:11.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.33:12.1": "“Good, good fellow, is giving! ",
  "sn1.33:12.2": "Even when one has little, giving is good. ",
  "sn1.33:12.3": "And it’s also good to give out of faith. ",
  "sn1.33:12.4": "And it’s also good to give legitimate wealth. ",
  "sn1.33:12.5": "And it’s also good to give intelligently. ",
  "sn1.33:13.1": "The Holy One praises giving intelligently ",
  "sn1.33:13.2": "to those worthy of offerings here  <j>in the world of the living. ",
  "sn1.33:13.3": "What’s given to these is very fruitful, ",
  "sn1.33:13.4": "like seeds sown in a fertile field.” ",
  "sn1.33:14.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.33:15.1": "“Good, good fellow, is giving! ",
  "sn1.33:15.2": "Even when one has little, giving is good. ",
  "sn1.33:15.3": "And it’s also good to give out of faith. ",
  "sn1.33:15.4": "And it’s also good to give legitimate wealth. ",
  "sn1.33:15.5": "And it’s also good to give intelligently. ",
  "sn1.33:15.6": "And it’s also good to be restrained  <j>when it comes to living creatures. ",
  "sn1.33:16.1": "One who lives without harming any living being ",
  "sn1.33:16.2": "does no bad because of others’ blame. ",
  "sn1.33:16.3": "Were that the case they praise the coward, not the brave; ",
  "sn1.33:16.4": "for the virtuous do no bad out of fear.” ",
  "sn1.33:17.1": "Then another deity said to the Buddha, ",
  "sn1.33:17.2": "“Sir, who has spoken well?” ",
  "sn1.33:18.1": "“You’ve all spoken well in your own way. However, listen to me also: ",
  "sn1.33:19.1": "A gift of faith is praised in many ways, ",
  "sn1.33:19.2": "but a passage of teaching is better than giving, ",
  "sn1.33:19.3": "for the virtuous, in days old and older still, ",
  "sn1.33:19.4": "even attained extinction with wisdom.” ",
  "sn1.34:0.1": "Linked Discourses 1.34 ",
  "sn1.34:0.2": "4. The Host of a Hundred Felicities ",
  "sn1.34:0.3": "There Are None ",
  "sn1.34:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s Monastery. ",
  "sn1.34:1.2": "Then, late at night, several glorious deities of the host of a hundred felicities, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, and stood to one side. ",
  "sn1.34:1.3": "Standing to one side, one deity spoke this verse in the Buddha’s presence: ",
  "sn1.34:2.1": "“Among mankind there are no sensual pleasures that are permanent. ",
  "sn1.34:2.2": "Here there are sensuous things, bound to which, ",
  "sn1.34:2.3": "drunk on which, there’s no coming back. ",
  "sn1.34:2.4": "That person doesn’t return from Death’s dominion.” ",
  "sn1.34:3.1": "“Gloom is born of desire; suffering is born of desire; ",
  "sn1.34:3.2": "when desire is removed, gloom is removed; ",
  "sn1.34:3.3": "when gloom is removed, suffering is removed.” ",
  "sn1.34:4.1": "“The world’s pretty things aren’t sensual pleasures. ",
  "sn1.34:4.2": "Greedy intention is a person’s sensual pleasure. ",
  "sn1.34:4.3": "The world’s pretty things stay just as they are, ",
  "sn1.34:4.4": "but the attentive remove desire for them. ",
  "sn1.34:5.1": "Give up anger, get rid of conceit, ",
  "sn1.34:5.2": "and get past all the fetters. ",
  "sn1.34:5.3": "Sufferings don’t torment the one who has nothing, ",
  "sn1.34:5.4": "not clinging to name and form. ",
  "sn1.34:6.1": "They gave up judgement without falling into conceit; ",
  "sn1.34:6.2": "craving for name and form was cut off right here. ",
  "sn1.34:6.3": "They cut the ties, untroubled, <j>with no need for hope. ",
  "sn1.34:6.4": "Though gods and humans search for them ",
  "sn1.34:6.5": "in this life or the next, they never find them, ",
  "sn1.34:6.6": "not in heaven nor in any abode.” ",
  "sn1.34:7.1": "“If neither gods nor humans see one freed in this way,” ",
  "sn1.34:7.2": "said Venerable Mogharāja, ",
  "sn1.34:7.3": "“in this life or the next, ",
  "sn1.34:7.4": "are those who revere that supreme man, ",
  "sn1.34:7.5": "who lives for the good of mankind, <j>also worthy of praise?” ",
  "sn1.34:8.1": "“The mendicants who revere one freed in this way,” ",
  "sn1.34:8.2": "said the Buddha, ",
  "sn1.34:8.3": "“are also worthy of praise, Mogharāja. ",
  "sn1.34:8.4": "Having understood the teaching <j>and given up doubt, ",
  "sn1.34:8.5": "those mendicants slip their chains.” ",
  "sn1.35:0.1": "Linked Discourses 1.35 ",
  "sn1.35:0.2": "4. The Host of a Hundred Felicities ",
  "sn1.35:0.3": "Fault-Finding Deities ",
  "sn1.35:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s Monastery. ",
  "sn1.35:1.2": "Then, late at night, several glorious deities of the host of the fault-finders, lighting up the entire Jeta’s Grove, went up to the Buddha, and stood in the air. ",
  "sn1.35:1.3": "Standing in the air, one deity spoke this verse in the Buddha’s presence: ",
  "sn1.35:2.1": "“Someone who pretends ",
  "sn1.35:2.2": "to be other than they really are, ",
  "sn1.35:2.3": "is like a cheating gambler ",
  "sn1.35:2.4": "who enjoys what was gained by theft. ",
  "sn1.35:3.1": "You should only say what you would do; ",
  "sn1.35:3.2": "you shouldn’t say what you wouldn’t do. ",
  "sn1.35:3.3": "The wise will recognize ",
  "sn1.35:3.4": "one who talks without doing.” ",
  "sn1.35:4.1": "“Not just by speaking, ",
  "sn1.35:4.2": "nor solely by listening, ",
  "sn1.35:4.3": "are you able to progress ",
  "sn1.35:4.4": "on this hard path, ",
  "sn1.35:4.5": "by which the attentive practicing absorption ",
  "sn1.35:4.6": "are released from Māra’s bonds. ",
  "sn1.35:5.1": "The attentive certainly don’t act like that, ",
  "sn1.35:5.2": "for they understand the way of the world. ",
  "sn1.35:5.3": "The attentive are quenched by understanding, ",
  "sn1.35:5.4": "they’ve crossed over clinging to the world.” ",
  "sn1.35:6.1": "Then those deities landed on the ground, bowed with their heads at the Buddha’s feet and said, ",
  "sn1.35:6.2": "“We made a mistake, sir. It was foolish, stupid, and unskillful of us to presume to attack the Buddha! ",
  "sn1.35:6.3": "Please, sir, accept our mistake for what it is, so we will restrain ourselves in future.” ",
  "sn1.35:6.4": "At that, the Buddha smiled. ",
  "sn1.35:6.5": "Then those deities, becoming even more fault-finding, flew up in the air. ",
  "sn1.35:6.6": "One deity spoke this verse in the Buddha’s presence: ",
  "sn1.35:7.1": "“If you don’t give your pardon ",
  "sn1.35:7.2": "when a mistake is confessed, ",
  "sn1.35:7.3": "with hidden anger and heavy hate, ",
  "sn1.35:7.4": "you’re stuck in your enmity.” ",
  "sn1.35:8.1": "“Suppose no mistake were found, ",
  "sn1.35:8.2": "and no-one here had gone astray: ",
  "sn1.35:8.3": "if enmities were not settled, ",
  "sn1.35:8.4": "how could that be skilful?” ",
  "sn1.35:9.1": "“Who makes no mistakes? ",
  "sn1.35:9.2": "Who doesn’t go astray? ",
  "sn1.35:9.3": "Who doesn’t fall into confusion? ",
  "sn1.35:9.4": "Who is attentive, ever mindful?” ",
  "sn1.35:10.1": "“The Realized One, the Buddha, ",
  "sn1.35:10.2": "sympathetic for all beings: ",
  "sn1.35:10.3": "that’s who makes no mistakes, ",
  "sn1.35:10.4": "and that’s who doesn’t go astray. ",
  "sn1.35:10.5": "He doesn’t fall into confusion, ",
  "sn1.35:10.6": "for he’s attentive, ever mindful. ",
  "sn1.35:11.1": "If you don’t give your pardon ",
  "sn1.35:11.2": "when a mistake is confessed, ",
  "sn1.35:11.3": "with hidden anger and heavy hate, ",
  "sn1.35:11.4": "you’re stuck in your enmity. ",
  "sn1.35:11.5": "I don’t approve of such enmity, ",
  "sn1.35:11.6": "and so I pardon your mistake.” ",
  "sn1.36:0.1": "Linked Discourses 1.36 ",
  "sn1.36:0.2": "4. The Host of a Hundred Felicities ",
  "sn1.36:0.3": "Faith ",
  "sn1.36:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn1.36:1.2": "Then, late at night, several glorious deities of the host of a hundred felicities, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, and stood to one side. ",
  "sn1.36:1.3": "Standing to one side, one deity spoke this verse in the Buddha’s presence: ",
  "sn1.36:2.1": "“Faith is a person’s partner. ",
  "sn1.36:2.2": "If faithlessness doesn’t linger, ",
  "sn1.36:2.3": "fame and renown are theirs, ",
  "sn1.36:2.4": "and when they discard this corpse they go to heaven.” ",
  "sn1.36:3.1": "Then another deity recited these verses in the Buddha’s presence: ",
  "sn1.36:4.1": "“Give up anger, get rid of conceit, ",
  "sn1.36:4.2": "and get past all the fetters. ",
  "sn1.36:4.3": "Chains don’t torment one who has nothing, ",
  "sn1.36:4.4": "not clinging to name and form.” ",
  "sn1.36:5.1": "“Fools and simpletons ",
  "sn1.36:5.2": "devote themselves to negligence. ",
  "sn1.36:5.3": "But the wise protect diligence ",
  "sn1.36:5.4": "as their best treasure. ",
  "sn1.36:6.1": "Don’t devote yourself to negligence, ",
  "sn1.36:6.2": "or delight in erotic intimacy. ",
  "sn1.36:6.3": "For if you’re diligent and practice absorption, ",
  "sn1.36:6.4": "you’ll attain ultimate happiness.” ",
  "sn1.37:0.1": "Linked Discourses 1.37 ",
  "sn1.37:0.2": "4. The Host of a Hundred Felicities ",
  "sn1.37:0.3": "The Congregation ",
  "sn1.37:1.1": "So I have heard. ",
  "sn1.37:1.2": "At one time the Buddha was staying in the land of the Sakyans, in the Great Wood near Kapilavatthu, together with a large Saṅgha of five hundred mendicants, all of whom were perfected ones. ",
  "sn1.37:1.3": "And most of the deities from ten solar systems had gathered to see the Buddha and the Saṅgha of mendicants. ",
  "sn1.37:1.4": "Then four deities of the Pure Abodes, aware of what was happening, thought: ",
  "sn1.37:1.5": "",
  "sn1.37:1.6": "",
  "sn1.37:1.7": "“Why don’t we go to the Buddha and each recite a verse in his presence?” ",
  "sn1.37:2.1": "Then, as easily as a strong person would extend or contract their arm, they vanished from the Pure Abodes and reappeared in front of the Buddha. ",
  "sn1.37:2.2": "They bowed to the Buddha and stood to one side. ",
  "sn1.37:2.3": "Standing to one side, one deity spoke this verse in the Buddha’s presence: ",
  "sn1.37:3.1": "“There’s a great congregation in the woods, ",
  "sn1.37:3.2": "where hosts of gods have assembled. ",
  "sn1.37:3.3": "We’ve come to this righteous congregation ",
  "sn1.37:3.4": "to see the invincible Saṅgha!” ",
  "sn1.37:4.1": "Then another deity spoke this verse in the Buddha’s presence: ",
  "sn1.37:5.1": "“The mendicants there have immersion, ",
  "sn1.37:5.2": "they’ve straightened their own minds. ",
  "sn1.37:5.3": "Like a charioteer holding the reins, ",
  "sn1.37:5.4": "the astute ones protect their senses.” ",
  "sn1.37:6.1": "Then another deity spoke this verse in the Buddha’s presence: ",
  "sn1.37:7.1": "“They snapped the post and snapped the cross-bar, ",
  "sn1.37:7.2": "unstirred, they tore out Indra’s pillar. ",
  "sn1.37:7.3": "They live pure and immaculate, ",
  "sn1.37:7.4": "the young giants tamed by the Clear-eyed One.” ",
  "sn1.37:8.1": "Then another deity spoke this verse in the Buddha’s presence: ",
  "sn1.37:9.1": "“Anyone who has gone to the Buddha for refuge ",
  "sn1.37:9.2": "won’t go to a plane of loss. ",
  "sn1.37:9.3": "After giving up this human body, ",
  "sn1.37:9.4": "they swell the hosts of gods.” ",
  "sn1.38:0.1": "Linked Discourses 1.38 ",
  "sn1.38:0.2": "4. The Host of a Hundred Felicities ",
  "sn1.38:0.3": "A Splinter ",
  "sn1.38:1.1": "So I have heard. ",
  "sn1.38:1.2": "At one time the Buddha was staying near Rājagaha in the Maddakucchi deer park. ",
  "sn1.38:1.3": "Now at that time the Buddha’s foot had been cut by a wooden splinter. ",
  "sn1.38:1.4": "The Buddha was stricken by harrowing pains; physical feelings that were painful, sharp, severe, acute, unpleasant, and disagreeable. ",
  "sn1.38:1.5": "But he endured unbothered, with mindfulness and situational awareness. ",
  "sn1.38:1.6": "And then he spread out his outer robe folded in four and laid down in the lion’s postureon the right side, placing one foot on top of the othermindful and aware. ",
  "sn1.38:2.1": "Then, late at night, seven hundred glorious deities of the host of a hundred felicities, lighting up the entire Maddakucchi, went up to the Buddha, bowed, and stood to one side. ",
  "sn1.38:2.2": "Standing to one side, one deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.38:2.3": "“The ascetic Gotama is such an elephant, sir! ",
  "sn1.38:2.4": "And as an elephant, he endures painful physical feelings that have come upsharp, severe, acute, unpleasant, and disagreeableunbothered, with mindfulness and situational awareness.” ",
  "sn1.38:3.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.38:3.2": "“The ascetic Gotama is such a lion, sir! ",
  "sn1.38:3.3": "And as a lion, he endures painful physical feelings … unbothered.” ",
  "sn1.38:4.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.38:4.2": "“The ascetic Gotama is such a thoroughbred, sir! ",
  "sn1.38:4.3": "And as a thoroughbred, he endures painful physical feelings … unbothered.” ",
  "sn1.38:5.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.38:5.2": "“The ascetic Gotama is such a boss bull, sir! ",
  "sn1.38:5.3": "And as a boss bull, he endures painful physical feelings … unbothered.” ",
  "sn1.38:6.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.38:6.2": "“The ascetic Gotama is such a behemoth, sir! ",
  "sn1.38:6.3": "And as a behemoth, he endures painful physical feelings … unbothered.” ",
  "sn1.38:7.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.38:7.2": "“The ascetic Gotama is truly tamed, sir! ",
  "sn1.38:7.3": "And as someone tamed, he endures painful physical feelings … unbothered.” ",
  "sn1.38:8.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence: ",
  "sn1.38:8.2": "“See, his immersion is so well developed, and his mind is so well freednot leaning forward or pulling back, and not held in place by forceful suppression. ",
  "sn1.38:8.3": "If anyone imagines that they can overcome such an elephant of a man, a lion of a man, a thoroughbred of a man, a boss bull of a man, a behemoth of a man, a tamed manwhat is that but a failure to see?” ",
  "sn1.38:9.1": "“Learned in the five branches of Vedic lore, ",
  "sn1.38:9.2": "brahmins practice fervent mortification for a full century. ",
  "sn1.38:9.3": "But their minds are not properly freed, ",
  "sn1.38:9.4": "for those of base character don’t cross to the far shore. ",
  "sn1.38:10.1": "Seized by craving,  <j>attached to precept and observance, ",
  "sn1.38:10.2": "they practice rough and fervent mortification for a hundred years. ",
  "sn1.38:10.3": "But their minds are not properly freed, ",
  "sn1.38:10.4": "for those of base character don’t cross to the far shore. ",
  "sn1.38:11.1": "Someone who’s fond of conceit can’t be tamed, ",
  "sn1.38:11.2": "and someone without immersion can’t be a sage. ",
  "sn1.38:11.3": "Living negligent alone in the wilderness, ",
  "sn1.38:11.4": "they can’t cross beyond Death’s dominion.” ",
  "sn1.38:12.1": "“Having given up conceit, serene within oneself, ",
  "sn1.38:12.2": "with a good heart, everywhere free; ",
  "sn1.38:12.3": "living diligent alone in the wilderness, ",
  "sn1.38:12.4": "they cross beyond Death’s dominion.” ",
  "sn1.39:0.1": "Linked Discourses 1.39 ",
  "sn1.39:0.2": "4. The Host of a Hundred Felicities ",
  "sn1.39:0.3": "With Pajjunna’s Daughter (1st) ",
  "sn1.39:1.1": "So I have heard. ",
  "sn1.39:1.2": "At one time the Buddha was staying near Vesālī, at the Great Wood, in the hall with the peaked roof. ",
  "sn1.39:1.3": "Then, late at night, the glorious Kokanadā, Pajjunna’s daughter, lighting up the entire Great Wood, went up to the Buddha, bowed, stood to one side, ",
  "sn1.39:1.4": "and recited these verses in the Buddha’s presence: ",
  "sn1.39:2.1": "“Staying in the woods of Vesālī ",
  "sn1.39:2.2": "is the Buddha, best of creation. ",
  "sn1.39:2.3": "Kokanadā am I who worships him, ",
  "sn1.39:2.4": "Kokanadā, Pajjuna’s daughter. ",
  "sn1.39:3.1": "Previously I had only heard ",
  "sn1.39:3.2": "the teaching realized by the Clear-eyed One. ",
  "sn1.39:3.3": "But now I know it as a witness ",
  "sn1.39:3.4": "while the sage, the Holy One teaches. ",
  "sn1.39:4.1": "There are simpletons who go about ",
  "sn1.39:4.2": "denouncing the teaching of the noble ones. ",
  "sn1.39:4.3": "They fall into the terrible Hell of Screams ",
  "sn1.39:4.4": "where they suffer long. ",
  "sn1.39:5.1": "There are those who have found  <j>acceptance and peace ",
  "sn1.39:5.2": "in the teaching of the noble ones. ",
  "sn1.39:5.3": "After giving up this human body, ",
  "sn1.39:5.4": "they swell the hosts of gods.” ",
  "sn1.40:0.1": "Linked Discourses 1.40 ",
  "sn1.40:0.2": "4. The Host of a Hundred Felicities ",
  "sn1.40:0.3": "With Pajjunna’s Daughter (2nd) ",
  "sn1.40:1.1": "So I have heard. ",
  "sn1.40:1.2": "At one time the Buddha was staying near Vesālī, at the Great Wood, in the hall with the peaked roof. ",
  "sn1.40:1.3": "Then, late at night, the glorious Kokanadā the Younger, Pajjunna’s daughter, lighting up the entire Great Wood, went up to the Buddha, bowed, stood to one side, ",
  "sn1.40:1.4": "and recited these verses in the Buddha’s presence: ",
  "sn1.40:2.1": "“She came here, beautiful as a flash of lightning, ",
  "sn1.40:2.2": "Kokanadā, Pajjunna’s daughter. ",
  "sn1.40:2.3": "Revering the Buddha and the teaching, ",
  "sn1.40:2.4": "she spoke these verses full of meaning. ",
  "sn1.40:3.1": "The teaching is such that ",
  "sn1.40:3.2": "I could analyze it in many different ways. ",
  "sn1.40:3.3": "However, I will state the meaning in brief ",
  "sn1.40:3.4": "as far as I have learned it by heart. ",
  "sn1.40:4.1": "You should never do anything bad ",
  "sn1.40:4.2": "by speech or mind or body in all the world. ",
  "sn1.40:4.3": "Having given up sensual pleasures,  <j>mindful and aware, ",
  "sn1.40:4.4": "you shouldn’t keep doing  <j>what’s painful and pointless.” ",
  "sn1.40:4.5": "",
  "sn1.40:5.1": "",
  "sn1.40:5.2": "",
  "sn1.40:5.3": "",
  "sn1.41:0.1": "Linked Discourses 1.41 ",
  "sn1.41:0.2": "5. On Fire ",
  "sn1.41:0.3": "On Fire ",
  "sn1.41:1.1": "So I have heard. ",
  "sn1.41:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s Monastery. ",
  "sn1.41:1.3": "Then, late at night, a glorious deity, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, stood to one side, ",
  "sn1.41:1.4": "and recited these verses in the Buddha’s presence: ",
  "sn1.41:2.1": "“When your house is on fire, ",
  "sn1.41:2.2": "you rescue the pot ",
  "sn1.41:2.3": "that’s useful, ",
  "sn1.41:2.4": "not the one that’s burnt. ",
  "sn1.41:3.1": "And as the world is on fire ",
  "sn1.41:3.2": "with old age and death, ",
  "sn1.41:3.3": "you should rescue by giving, ",
  "sn1.41:3.4": "for what’s given is rescued. ",
  "sn1.41:4.1": "What’s given has happiness as its fruit, ",
  "sn1.41:4.2": "but not what isn’t given. ",
  "sn1.41:4.3": "Bandits take it, or rulers, ",
  "sn1.41:4.4": "it’s consumed by fire, or lost. ",
  "sn1.41:5.1": "Then in the end this corpse is cast off, ",
  "sn1.41:5.2": "along with all your possessions. ",
  "sn1.41:5.3": "Knowing this, a clever person ",
  "sn1.41:5.4": "would enjoy what they have and also give it away. ",
  "sn1.41:5.5": "After giving and using according to their means, ",
  "sn1.41:5.6": "blameless, they go to a heavenly place.” ",
  "sn1.42:0.1": "Linked Discourses 1.42 ",
  "sn1.42:0.2": "5. On Fire ",
  "sn1.42:0.3": "Giving What? ",
  "sn1.42:1.1": "“Giving what do you give strength? ",
  "sn1.42:1.2": "Giving what do you give beauty? ",
  "sn1.42:1.3": "Giving what do you give happiness? ",
  "sn1.42:1.4": "Giving what do you give vision? ",
  "sn1.42:1.5": "And who is the giver of all? ",
  "sn1.42:1.6": "Please answer my question.” ",
  "sn1.42:2.1": "“Giving food you give strength. ",
  "sn1.42:2.2": "Giving clothes you give beauty. ",
  "sn1.42:2.3": "Giving a vehicle you give happiness. ",
  "sn1.42:2.4": "Giving a lamp you give vision. ",
  "sn1.42:3.1": "And the giver of all ",
  "sn1.42:3.2": "is the one who gives monastic quarters. ",
  "sn1.42:3.3": "But one who teaches the Dhamma ",
  "sn1.42:3.4": "gives the gift of freedom from death.” ",
  "sn1.43:0.1": "Linked Discourses 1.43 ",
  "sn1.43:0.2": "5. On Fire ",
  "sn1.43:0.3": "Food ",
  "sn1.43:1.1": "“Both gods and humans ",
  "sn1.43:1.2": "enjoy their food. ",
  "sn1.43:1.3": "So what’s the name of the spirit ",
  "sn1.43:1.4": "who doesn’t enjoy food?” ",
  "sn1.43:2.1": "“Those who give with faith ",
  "sn1.43:2.2": "and a clear and confident heart, ",
  "sn1.43:2.3": "partake of food ",
  "sn1.43:2.4": "in this world and the next. ",
  "sn1.43:3.1": "So you should dispel stinginess, ",
  "sn1.43:3.2": "overcoming that stain, and give a gift. ",
  "sn1.43:3.3": "The good deeds of sentient beings ",
  "sn1.43:3.4": "support them in the next world.” ",
  "sn1.44:0.1": "Linked Discourses 1.44 ",
  "sn1.44:0.2": "5. On Fire ",
  "sn1.44:0.3": "One Root ",
  "sn1.44:1.1": "“One the root, two the loops, ",
  "sn1.44:1.2": "three the stains, five the spreads, ",
  "sn1.44:1.3": "and the ocean, the twelfth whirlpool: ",
  "sn1.44:1.4": "such is the abyss crossed by the seer.” ",
  "sn1.45:0.1": "Linked Discourses 1.45 ",
  "sn1.45:0.2": "5. On Fire ",
  "sn1.45:0.3": "Peerless ",
  "sn1.45:1.1": "“Behold him of peerless name <j>who sees the subtle meaning, ",
  "sn1.45:1.2": "giver of wisdom, <j>unattached to the realm of sensuality: ",
  "sn1.45:1.3": "the all-knower, so very intelligent, ",
  "sn1.45:1.4": "the great seer treading the noble road.” ",
  "sn1.46:0.1": "Linked Discourses 1.46 ",
  "sn1.46:0.2": "5. On Fire ",
  "sn1.46:0.3": "Nymphs ",
  "sn1.46:1.1": "“It’s resounding with a group of nymphs, ",
  "sn1.46:1.2": "but haunted by a gang of goblins! ",
  "sn1.46:1.3": "This grove is called ‘Deluding’. ",
  "sn1.46:1.4": "How will I keep going?” ",
  "sn1.46:2.1": "“That path is called ‘the direct way’, ",
  "sn1.46:2.2": "and it’s headed for the place called ‘fearless’. ",
  "sn1.46:2.3": "The chariot is called ‘unswerving’, ",
  "sn1.46:2.4": "fitted with wheels of the teaching. ",
  "sn1.46:3.1": "Conscience is its bench-back, ",
  "sn1.46:3.2": "mindfulness its upholstery. ",
  "sn1.46:3.3": "I say the teaching is the driver, ",
  "sn1.46:3.4": "with right view running out in front. ",
  "sn1.46:4.1": "Any woman or man ",
  "sn1.46:4.2": "who has such a vehicle, ",
  "sn1.46:4.3": "by means of this vehicle ",
  "sn1.46:4.4": "has drawn near to extinguishment.” ",
  "sn1.47:0.1": "Linked Discourses 1.47 ",
  "sn1.47:0.2": "5. On Fire ",
  "sn1.47:0.3": "Planters ",
  "sn1.47:1.1": "“Whose merit always grows ",
  "sn1.47:1.2": "by day and by night? ",
  "sn1.47:1.3": "What peoplefirm in principle, <j>accomplished in conduct",
  "sn1.47:1.4": "are going to heaven?” ",
  "sn1.47:2.1": "“Planters of parks or groves, ",
  "sn1.47:2.2": "those who build a bridge, ",
  "sn1.47:2.3": "a drinking place and well, ",
  "sn1.47:2.4": "and those who give monastic quarters. ",
  "sn1.47:3.1": "Their merit always grows ",
  "sn1.47:3.2": "by day and by night. ",
  "sn1.47:3.3": "Those peoplefirm in principle, <j>accomplished in conduct",
  "sn1.47:3.4": "are going to heaven.” ",
  "sn1.48:0.1": "Linked Discourses 1.48 ",
  "sn1.48:0.2": "5. On Fire ",
  "sn1.48:0.3": "Jeta’s Grove ",
  "sn1.48:1.1": "“This is indeed that Jeta’s Grove, ",
  "sn1.48:1.2": "frequented by the Saṅgha of seers, ",
  "sn1.48:1.3": "where the King of Dhamma stayed: ",
  "sn1.48:1.4": "it brings me joy! ",
  "sn1.48:2.1": "Deeds, knowledge, and principle; ",
  "sn1.48:2.2": "ethical conduct, an excellent livelihood; ",
  "sn1.48:2.3": "by these are mortals purified, ",
  "sn1.48:2.4": "not by clan or wealth. ",
  "sn1.48:3.1": "That’s why an astute person, ",
  "sn1.48:3.2": "seeing what’s good for themselves, ",
  "sn1.48:3.3": "would examine the teaching rationally, ",
  "sn1.48:3.4": "and thus be purified in it. ",
  "sn1.48:4.1": "Sāriputta is full of wisdom, ",
  "sn1.48:4.2": "ethics, and peace. ",
  "sn1.48:4.3": "Even a mendicant who has crossed over ",
  "sn1.48:4.4": "might at best equal him.” ",
  "sn1.49:0.1": "Linked Discourses 1.49 ",
  "sn1.49:0.2": "5. On Fire ",
  "sn1.49:0.3": "Stingy ",
  "sn1.49:1.1": "“Those folk in the world who are stingy, ",
  "sn1.49:1.2": "miserly and abusive, ",
  "sn1.49:1.3": "setting up obstacles ",
  "sn1.49:1.4": "for others who give. ",
  "sn1.49:2.1": "What kind of result do they reap? ",
  "sn1.49:2.2": "What kind of future life? ",
  "sn1.49:2.3": "We’ve come to ask you, worthy sir: ",
  "sn1.49:2.4": "how are we to understand this?” ",
  "sn1.49:3.1": "“Those folk in the world who are stingy, ",
  "sn1.49:3.2": "miserly and abusive, ",
  "sn1.49:3.3": "setting up obstacles ",
  "sn1.49:3.4": "for others who give: ",
  "sn1.49:4.1": "they’re reborn in hell, ",
  "sn1.49:4.2": "the animal realm, or Yama’s world. ",
  "sn1.49:4.3": "If they return to the human state, ",
  "sn1.49:4.4": "they’re born in a poor family, ",
  "sn1.49:5.1": "where clothes, food, pleasure, and play ",
  "sn1.49:5.2": "are hard to find. ",
  "sn1.49:5.3": "They don’t even get ",
  "sn1.49:5.4": "what they hope for from others. ",
  "sn1.49:5.5": "This is the result in the present life, ",
  "sn1.49:5.6": "and in the next, a bad destination.” ",
  "sn1.49:6.1": "“We understand what you’re saying, ",
  "sn1.49:6.2": "and ask another question, Gotama. ",
  "sn1.49:6.3": "What about those who’ve gained the human state, ",
  "sn1.49:6.4": "who are bountiful and rid of stinginess, ",
  "sn1.49:7.1": "confident in the Buddha and the teaching, ",
  "sn1.49:7.2": "with keen respect for the Saṅgha? ",
  "sn1.49:7.3": "What kind of result do they reap? ",
  "sn1.49:7.4": "What kind of future life? ",
  "sn1.49:7.5": "We’ve come to ask you, worthy sir: ",
  "sn1.49:7.6": "how are we to understand this?” ",
  "sn1.49:8.1": "“Those who’ve gained the human state ",
  "sn1.49:8.2": "who are bountiful and rid of stinginess, ",
  "sn1.49:8.3": "confident in the Buddha and the teaching, ",
  "sn1.49:8.4": "with keen respect for the Saṅgha: ",
  "sn1.49:8.5": "they illuminate the heavens ",
  "sn1.49:8.6": "wherever they’re reborn. ",
  "sn1.49:9.1": "If they return to the human state, ",
  "sn1.49:9.2": "they’re reborn in a rich family, ",
  "sn1.49:9.3": "where clothes, food, pleasure, and play ",
  "sn1.49:9.4": "are easy to find. ",
  "sn1.49:10.1": "They rejoice like those ",
  "sn1.49:10.2": "who control the possessions of others. ",
  "sn1.49:10.3": "This is the result in the present life, ",
  "sn1.49:10.4": "and in the next, a good destination.” ",
  "sn1.50:0.1": "Linked Discourses 1.50 ",
  "sn1.50:0.2": "5. On Fire ",
  "sn1.50:0.3": "With Ghaṭīkāra ",
  "sn1.50:1.1": "“Seven mendicants reborn in Aviha ",
  "sn1.50:1.2": "have been freed. ",
  "sn1.50:1.3": "With the complete ending of greed and hate, ",
  "sn1.50:1.4": "they’ve crossed over clinging to the world.” ",
  "sn1.50:2.1": "“Who are those who’ve crossed the bog, ",
  "sn1.50:2.2": "Death’s dominion so hard to pass? ",
  "sn1.50:2.3": "Who, after leaving behind the human body, ",
  "sn1.50:2.4": "have risen above celestial yokes?” ",
  "sn1.50:3.1": "“Upaka and Palagaṇḍa, ",
  "sn1.50:3.2": "and Pukkusāti, these three; ",
  "sn1.50:3.3": "Bhaddiya and Bhaddadeva, ",
  "sn1.50:3.4": "and Bāhudanti and Piṅgiya. ",
  "sn1.50:3.5": "They, after leaving behind the human body, ",
  "sn1.50:3.6": "have risen above celestial yokes.” ",
  "sn1.50:4.1": "“You speak well of them, ",
  "sn1.50:4.2": "who have let go the snares of Māra. ",
  "sn1.50:4.3": "Whose teaching did they understand ",
  "sn1.50:4.4": "to cut the bonds of rebirth?” ",
  "sn1.50:5.1": "“None other than the Blessed One! ",
  "sn1.50:5.2": "None other than your instruction! ",
  "sn1.50:5.3": "It was your teaching that they understood ",
  "sn1.50:5.4": "to cut the bonds of rebirth. ",
  "sn1.50:6.1": "Where name and form ",
  "sn1.50:6.2": "cease with no residue left behind; ",
  "sn1.50:6.3": "understanding this teaching, ",
  "sn1.50:6.4": "they cut the bonds of rebirth.” ",
  "sn1.50:7.1": "“The words you say are deep, ",
  "sn1.50:7.2": "hard to understand, so very hard to wake up to. ",
  "sn1.50:7.3": "Whose teaching did you understand ",
  "sn1.50:7.4": "that you can say such things?” ",
  "sn1.50:8.1": "“In the past I was a potter ",
  "sn1.50:8.2": "in Vebhaliṅga called Ghaṭīkāra. ",
  "sn1.50:8.3": "I took care of my parents ",
  "sn1.50:8.4": "as a lay follower of Buddha Kassapa. ",
  "sn1.50:9.1": "I refrained from sexual intercourse, ",
  "sn1.50:9.2": "I was chaste, spiritual. ",
  "sn1.50:9.3": "We lived in the same village; ",
  "sn1.50:9.4": "in the past I was your comrade. ",
  "sn1.50:10.1": "I am the one who understands ",
  "sn1.50:10.2": "that these seven mendicants have been freed. ",
  "sn1.50:10.3": "With the complete ending of greed and hate, ",
  "sn1.50:10.4": "they’ve crossed over clinging to the world.” ",
  "sn1.50:11.1": "“That’s exactly how it was, ",
  "sn1.50:11.2": "just as you say, Bhaggava. ",
  "sn1.50:11.3": "In the past you were a potter ",
  "sn1.50:11.4": "in Vebhaliṅga called Ghaṭīkāra. ",
  "sn1.50:11.5": "You took care of your parents ",
  "sn1.50:11.6": "as a lay follower of Buddha Kassapa. ",
  "sn1.50:12.1": "You refrained from sexual intercourse, ",
  "sn1.50:12.2": "you were chaste, spiritual. ",
  "sn1.50:12.3": "We lived in the same village; ",
  "sn1.50:12.4": "in the past you were my comrade.” ",
  "sn1.50:13.1": "That’s how it was ",
  "sn1.50:13.2": "when those friends of old met again. ",
  "sn1.50:13.3": "Both of them were evolved, ",
  "sn1.50:13.4": "bearing their final body. ",
  "sn1.50:13.5": "",
  "sn1.50:14.1": "",
  "sn1.50:14.2": "",
  "sn1.50:14.3": "",
  "sn1.51:0.1": "Linked Discourses 1.51 ",
  "sn1.51:0.2": "6. Old Age ",
  "sn1.51:0.3": "Old Age ",
  "sn1.51:1.1": "“What’s still good in old age? ",
  "sn1.51:1.2": "What’s good when grounded? ",
  "sn1.51:1.3": "What is people’s treasure? ",
  "sn1.51:1.4": "What’s hard for thieves to take?” ",
  "sn1.51:2.1": "“Ethics are still good in old age. ",
  "sn1.51:2.2": "Faith is good when grounded. ",
  "sn1.51:2.3": "Wisdom is people’s treasure. ",
  "sn1.51:2.4": "Merit’s hard for thieves to take.” ",
  "sn1.52:0.1": "Linked Discourses 1.52 ",
  "sn1.52:0.2": "6. Old Age ",
  "sn1.52:0.3": "Getting Old ",
  "sn1.52:1.1": "“What’s good because it never gets old? ",
  "sn1.52:1.2": "What’s good when committed? ",
  "sn1.52:1.3": "What is people’s treasure? ",
  "sn1.52:1.4": "What can thieves never take?” ",
  "sn1.52:2.1": "“Ethics are good because they never grow old. ",
  "sn1.52:2.2": "Faith is good when committed. ",
  "sn1.52:2.3": "Wisdom is people’s treasure. ",
  "sn1.52:2.4": "Merit’s what thieves can never take.” ",
  "sn1.53:0.1": "Linked Discourses 1.53 ",
  "sn1.53:0.2": "6. Old Age ",
  "sn1.53:0.3": "A Friend ",
  "sn1.53:1.1": "“Who’s your friend while journeying? ",
  "sn1.53:1.2": "Who’s your friend at home? ",
  "sn1.53:1.3": "Who’s your friend in need? ",
  "sn1.53:1.4": "Who’s your friend in the next life?” ",
  "sn1.53:2.1": "“A caravan is your friend while journeying. ",
  "sn1.53:2.2": "Mother is your friend at home. ",
  "sn1.53:2.3": "An ally in a time of need ",
  "sn1.53:2.4": "is a friend time and again. ",
  "sn1.53:2.5": "But the good deeds you’ve done yourself",
  "sn1.53:2.6": "that’s your friend in the next life.” ",
  "sn1.54:0.1": "Linked Discourses 1.54 ",
  "sn1.54:0.2": "6. Old Age ",
  "sn1.54:0.3": "Grounds ",
  "sn1.54:1.1": "“What is the site for human beings? ",
  "sn1.54:1.2": "What is the best comrade here? ",
  "sn1.54:1.3": "By what do the creatures who live off the earth ",
  "sn1.54:1.4": "sustain their life?” ",
  "sn1.54:2.1": "“Children are the site for human beings. ",
  "sn1.54:2.2": "A wife is the best comrade. ",
  "sn1.54:2.3": "The creatures who live off the earth ",
  "sn1.54:2.4": "sustain their life by rain.” ",
  "sn1.55:0.1": "Linked Discourses 1.55 ",
  "sn1.55:0.2": "6. Old Age ",
  "sn1.55:0.3": "Gives Birth (1st) ",
  "sn1.55:1.1": "“What gives birth to a person? ",
  "sn1.55:1.2": "What do they have that runs about? ",
  "sn1.55:1.3": "What enters transmigration? ",
  "sn1.55:1.4": "What’s their greatest fear?” ",
  "sn1.55:2.1": "“Craving gives birth to a person. ",
  "sn1.55:2.2": "Their mind is what runs about. ",
  "sn1.55:2.3": "A sentient being enters transmigration. ",
  "sn1.55:2.4": "Suffering is their greatest fear.” ",
  "sn1.56:0.1": "Linked Discourses 1.56 ",
  "sn1.56:0.2": "6. Old Age ",
  "sn1.56:0.3": "Gives Birth (2nd) ",
  "sn1.56:1.1": "“What gives birth to a person? ",
  "sn1.56:1.2": "What do they have that runs about? ",
  "sn1.56:1.3": "What enters transmigration? ",
  "sn1.56:1.4": "From what are they not free?” ",
  "sn1.56:2.1": "“Craving gives birth to a person. ",
  "sn1.56:2.2": "Their mind is what runs about. ",
  "sn1.56:2.3": "A sentient being enters transmigration. ",
  "sn1.56:2.4": "From suffering they are not free.” ",
  "sn1.57:0.1": "Linked Discourses 1.57 ",
  "sn1.57:0.2": "6. Old Age ",
  "sn1.57:0.3": "Gives Birth (3rd) ",
  "sn1.57:1.1": "“What gives birth to a person? ",
  "sn1.57:1.2": "What do they have that runs about? ",
  "sn1.57:1.3": "What enters transmigration? ",
  "sn1.57:1.4": "What is their destiny?” ",
  "sn1.57:2.1": "“Craving gives birth to a person. ",
  "sn1.57:2.2": "Their mind is what runs about. ",
  "sn1.57:2.3": "A sentient being enters transmigration. ",
  "sn1.57:2.4": "Deeds are their final haven.” ",
  "sn1.58:0.1": "Linked Discourses 1.58 ",
  "sn1.58:0.2": "6. Old Age ",
  "sn1.58:0.3": "Deviation ",
  "sn1.58:1.1": "“What’s declared to be a deviation? ",
  "sn1.58:1.2": "What is ending day and night? ",
  "sn1.58:1.3": "What’s the stain of chastity? ",
  "sn1.58:1.4": "What’s the waterless bath?” ",
  "sn1.58:2.1": "“Lust is declared to be a deviation. ",
  "sn1.58:2.2": "Youth is ending day and night. ",
  "sn1.58:2.3": "Women are the stain of chastity, ",
  "sn1.58:2.4": "to which this generation clings. ",
  "sn1.58:2.5": "Fervor and chastity ",
  "sn1.58:2.6": "are the waterless bath.” ",
  "sn1.59:0.1": "Linked Discourses 1.59 ",
  "sn1.59:0.2": "6. Old Age ",
  "sn1.59:0.3": "A Partner ",
  "sn1.59:1.1": "“What is a person’s partner? ",
  "sn1.59:1.2": "What instructs them? ",
  "sn1.59:1.3": "Enjoying what is a mortal ",
  "sn1.59:1.4": "released from all suffering?” ",
  "sn1.59:2.1": "“Faith is a person’s partner. ",
  "sn1.59:2.2": "Wisdom instructs them. ",
  "sn1.59:2.3": "Delighting in extinguishment a mortal ",
  "sn1.59:2.4": "is released from all suffering.” ",
  "sn1.60:0.1": "Linked Discourses 1.60 ",
  "sn1.60:0.2": "6. Old Age ",
  "sn1.60:0.3": "A Poet ",
  "sn1.60:1.1": "“What’s the source of verses? ",
  "sn1.60:1.2": "What constitutes their phrasing? ",
  "sn1.60:1.3": "What do verses depend upon? ",
  "sn1.60:1.4": "What underlies verses?” ",
  "sn1.60:2.1": "“Metre is the source of verses. ",
  "sn1.60:2.2": "Syllables constitute their phrasing. ",
  "sn1.60:2.3": "Verses depend on names. ",
  "sn1.60:2.4": "A poet underlies verses.” ",
  "sn1.60:2.5": "",
  "sn1.60:3.1": "",
  "sn1.60:3.2": "",
  "sn1.60:3.3": "",
  "sn1.61:0.1": "Linked Discourses 1.61 ",
  "sn1.61:0.2": "7. Overcome ",
  "sn1.61:0.3": "Name ",
  "sn1.61:1.1": "“What overcomes everything? ",
  "sn1.61:1.2": "What is it that nothing excels? ",
  "sn1.61:1.3": "What is the one thing ",
  "sn1.61:1.4": "that has everything under its sway?” ",
  "sn1.61:2.1": "“Name overcomes everything. ",
  "sn1.61:2.2": "Nothing excels name. ",
  "sn1.61:2.3": "Name is the one thing ",
  "sn1.61:2.4": "that has everything under its sway.” ",
  "sn1.62:0.1": "Linked Discourses 1.62 ",
  "sn1.62:0.2": "7. Overcome ",
  "sn1.62:0.3": "Mind ",
  "sn1.62:1.1": "“What leads the world on? ",
  "sn1.62:1.2": "What drags it around? ",
  "sn1.62:1.3": "What is the one thing ",
  "sn1.62:1.4": "that has everything under its sway?” ",
  "sn1.62:2.1": "“The mind leads the world on. ",
  "sn1.62:2.2": "The mind drags it around. ",
  "sn1.62:2.3": "Mind is the one thing ",
  "sn1.62:2.4": "that has everything under its sway.” ",
  "sn1.63:0.1": "Linked Discourses 1.63 ",
  "sn1.63:0.2": "7. Overcome ",
  "sn1.63:0.3": "Craving ",
  "sn1.63:1.1": "“What leads the world on? ",
  "sn1.63:1.2": "What drags it around? ",
  "sn1.63:1.3": "What is the one thing ",
  "sn1.63:1.4": "that has everything under its sway?” ",
  "sn1.63:2.1": "“Craving leads the world on. ",
  "sn1.63:2.2": "Craving drags it around. ",
  "sn1.63:2.3": "Craving is the one thing ",
  "sn1.63:2.4": "that has everything under its sway.” ",
  "sn1.64:0.1": "Linked Discourses 1.64 ",
  "sn1.64:0.2": "7. Overcome ",
  "sn1.64:0.3": "Fetter ",
  "sn1.64:1.1": "“What fetters the world? ",
  "sn1.64:1.2": "How does it travel about? ",
  "sn1.64:1.3": "With the giving up of what ",
  "sn1.64:1.4": "is extinguishment spoken of?” ",
  "sn1.64:2.1": "“Delight fetters the world. ",
  "sn1.64:2.2": "It travels about by means of thought. ",
  "sn1.64:2.3": "With the giving up of craving ",
  "sn1.64:2.4": "extinguishment is spoken of.” ",
  "sn1.65:0.1": "Linked Discourses 1.65 ",
  "sn1.65:0.2": "7. Overcome ",
  "sn1.65:0.3": "Bonds ",
  "sn1.65:1.1": "“What binds the world? ",
  "sn1.65:1.2": "How does it travel about? ",
  "sn1.65:1.3": "With the giving up of what ",
  "sn1.65:1.4": "are all bonds severed?” ",
  "sn1.65:2.1": "“Delight binds the world. ",
  "sn1.65:2.2": "It travels about by means of thought. ",
  "sn1.65:2.3": "With the giving up of craving ",
  "sn1.65:2.4": "all bonds are severed.” ",
  "sn1.66:0.1": "Linked Discourses 1.66 ",
  "sn1.66:0.2": "7. Overcome ",
  "sn1.66:0.3": "Beaten Down ",
  "sn1.66:1.1": "“By what is the world beaten down? ",
  "sn1.66:1.2": "By what is it surrounded? ",
  "sn1.66:1.3": "What dart has laid it low? ",
  "sn1.66:1.4": "With what is it always fuming?” ",
  "sn1.66:2.1": "“The world is beaten down by death. ",
  "sn1.66:2.2": "It’s surrounded by old age. ",
  "sn1.66:2.3": "The dart of craving has laid it low. ",
  "sn1.66:2.4": "It’s always fuming with desire.” ",
  "sn1.67:0.1": "Linked Discourses 1.67 ",
  "sn1.67:0.2": "7. Overcome ",
  "sn1.67:0.3": "Ensnared ",
  "sn1.67:1.1": "“By what is the world ensnared? ",
  "sn1.67:1.2": "By what is it surrounded? ",
  "sn1.67:1.3": "By what is the world fastened shut? ",
  "sn1.67:1.4": "On what is the world grounded?” ",
  "sn1.67:2.1": "“Craving has ensnared the world. ",
  "sn1.67:2.2": "It’s surrounded by old age. ",
  "sn1.67:2.3": "The world is fastened shut by mortality. ",
  "sn1.67:2.4": "The world is grounded on suffering.” ",
  "sn1.68:0.1": "Linked Discourses 1.68 ",
  "sn1.68:0.2": "7. Overcome ",
  "sn1.68:0.3": "Fastened Shut ",
  "sn1.68:1.1": "“By what is the world fastened shut? ",
  "sn1.68:1.2": "On what is the world grounded? ",
  "sn1.68:1.3": "By what is the world ensnared? ",
  "sn1.68:1.4": "By what is it surrounded?” ",
  "sn1.68:2.1": "“The world is fastened shut by mortality. ",
  "sn1.68:2.2": "The world is grounded on suffering. ",
  "sn1.68:2.3": "Craving has ensnared the world. ",
  "sn1.68:2.4": "It’s surrounded by old age.” ",
  "sn1.69:0.1": "Linked Discourses 1.69 ",
  "sn1.69:0.2": "7. Overcome ",
  "sn1.69:0.3": "Desire ",
  "sn1.69:1.1": "“What is it that binds the world? ",
  "sn1.69:1.2": "By removing what is it freed? ",
  "sn1.69:1.3": "With the giving up of what ",
  "sn1.69:1.4": "are all bonds severed?” ",
  "sn1.69:2.1": "“Desire is what binds the world. ",
  "sn1.69:2.2": "By the removing of desire it’s freed. ",
  "sn1.69:2.3": "With the giving up of desire, ",
  "sn1.69:2.4": "all bonds are severed.” ",
  "sn1.70:0.1": "Linked Discourses 1.70 ",
  "sn1.70:0.2": "7. Overcome ",
  "sn1.70:0.3": "The World ",
  "sn1.70:1.1": "“In what has the world arisen? ",
  "sn1.70:1.2": "With what does it get intimate? ",
  "sn1.70:1.3": "By grasping what ",
  "sn1.70:1.4": "is the world troubled in what?” ",
  "sn1.70:2.1": "“The world has arisen in six. ",
  "sn1.70:2.2": "It gets intimate with six. ",
  "sn1.70:2.3": "Derived from the six, ",
  "sn1.70:2.4": "the world’s troubled in six.” ",
  "sn1.70:2.5": "",
  "sn1.70:3.1": "",
  "sn1.70:3.2": "",
  "sn1.70:3.3": "",
  "sn1.71:0.1": "Linked Discourses 1.71 ",
  "sn1.71:0.2": "8. Slain ",
  "sn1.71:0.3": "Slain ",
  "sn1.71:1.1": "At Sāvatthī. ",
  "sn1.71:1.2": "Standing to one side, that deity addressed the Buddha in verse: ",
  "sn1.71:2.1": "“When what is slain do you sleep at ease? ",
  "sn1.71:2.2": "When what is slain is there no sorrow? ",
  "sn1.71:2.3": "What’s the one thing, Gotama, ",
  "sn1.71:2.4": "whose killing you approve?” ",
  "sn1.71:3.1": "“When anger’s slain you sleep at ease. ",
  "sn1.71:3.2": "When anger’s slain there is no sorrow. ",
  "sn1.71:3.3": "O deity, anger has a poisonous root ",
  "sn1.71:3.4": "and a sweet tip. ",
  "sn1.71:3.5": "The noble ones praise its killing, ",
  "sn1.71:3.6": "for when it’s slain there is no sorrow.” ",
  "sn1.72:0.1": "Linked Discourses 1.72 ",
  "sn1.72:0.2": "8. Slain ",
  "sn1.72:0.3": "A Chariot ",
  "sn1.72:1.1": "“What is a chariot known by? ",
  "sn1.72:1.2": "What is fire known by? ",
  "sn1.72:1.3": "What is a nation known by? ",
  "sn1.72:1.4": "What is a woman known by?” ",
  "sn1.72:2.1": "“A chariot is known by a banner. ",
  "sn1.72:2.2": "Fire is known by smoke. ",
  "sn1.72:2.3": "A nation is known by its ruler. ",
  "sn1.72:2.4": "A woman is known by her husband.” ",
  "sn1.73:0.1": "Linked Discourses 1.73 ",
  "sn1.73:0.2": "8. Slain ",
  "sn1.73:0.3": "Wealth ",
  "sn1.73:1.1": "“What’s a person’s best wealth? ",
  "sn1.73:1.2": "What brings happiness when practiced well? ",
  "sn1.73:1.3": "What’s the sweetest taste of all? ",
  "sn1.73:1.4": "The one they say has the best life: how do they live?” ",
  "sn1.73:2.1": "“Faith here is a person’s best wealth. ",
  "sn1.73:2.2": "The teaching brings happiness when practiced well. ",
  "sn1.73:2.3": "Truth is the sweetest taste of all. ",
  "sn1.73:2.4": "The one they say has the best life lives by wisdom.” ",
  "sn1.74:0.1": "Linked Discourses 1.74 ",
  "sn1.74:0.2": "8. Slain ",
  "sn1.74:0.3": "Rain ",
  "sn1.74:1.1": "“What’s the best of things that rise? ",
  "sn1.74:1.2": "And what’s the finest thing to fall? ",
  "sn1.74:1.3": "And what of the things that go forth? ",
  "sn1.74:1.4": "And who’s the finest speaker?” ",
  "sn1.74:2.1": "“A seed’s the best of things that rise. ",
  "sn1.74:2.2": "Rain’s the finest thing to fall. ",
  "sn1.74:2.3": "Cattle, of things that go forth. ",
  "sn1.74:2.4": "And a child is the finest speaker.” ",
  "sn1.74:3.1": "“Knowledge is best of things that rise. ",
  "sn1.74:3.2": "Ignorance the finest thing to fall. ",
  "sn1.74:3.3": "The Saṅgha, of things that go forth. ",
  "sn1.74:3.4": "And the Buddha is the finest speaker.” ",
  "sn1.75:0.1": "Linked Discourses 1.75 ",
  "sn1.75:0.2": "8. Slain ",
  "sn1.75:0.3": "Afraid ",
  "sn1.75:1.1": "“Why are so many people here afraid, ",
  "sn1.75:1.2": "when the path has been taught <j>with so many dimensions? ",
  "sn1.75:1.3": "I ask you, Gotama, whose wisdom is vast: ",
  "sn1.75:1.4": "Standing on what need one not fear the next world?” ",
  "sn1.75:2.1": "“When speech and mind are directed right, ",
  "sn1.75:2.2": "and you don’t do anything bad with the body ",
  "sn1.75:2.3": "while dwelling at home with plenty of food and drink. ",
  "sn1.75:2.4": "Faithful, gentle, charitable, and bountiful: ",
  "sn1.75:2.5": "one who stands on these four principles, ",
  "sn1.75:2.6": "who stands on the teaching <j>need not fear the next world.” ",
  "sn1.76:0.1": "Linked Discourses 1.76 ",
  "sn1.76:0.2": "8. Slain ",
  "sn1.76:0.3": "Getting Old ",
  "sn1.76:1.1": "“What ages, what does not age? ",
  "sn1.76:1.2": "What’s called a deviation? ",
  "sn1.76:1.3": "What’s a roadblock for skillful qualities? ",
  "sn1.76:1.4": "What is ending day and night? ",
  "sn1.76:1.5": "What’s the stain of celibacy? ",
  "sn1.76:1.6": "What’s the waterless bath? ",
  "sn1.76:2.1": "How many holes are there in the world, ",
  "sn1.76:2.2": "where one’s wealth leaks out? ",
  "sn1.76:2.3": "We’ve come to ask you, worthy sir: ",
  "sn1.76:2.4": "how are we to understand this?” ",
  "sn1.76:3.1": "“The physical form of mortals gets old, ",
  "sn1.76:3.2": "but their name and clan don’t. ",
  "sn1.76:3.3": "Lust is called a deviation, ",
  "sn1.76:4.1": "and greed is a roadblock for skillful qualities. ",
  "sn1.76:4.2": "Youth is ending day and night. ",
  "sn1.76:4.3": "Women are the stain of chastity, ",
  "sn1.76:4.4": "to which this generation clings. ",
  "sn1.76:4.5": "Fervor and chastity ",
  "sn1.76:4.6": "are the waterless bath. ",
  "sn1.76:5.1": "There are six holes in the world, ",
  "sn1.76:5.2": "where one’s wealth leaks out: ",
  "sn1.76:5.3": "laziness and negligence, ",
  "sn1.76:5.4": "lack of initiative and lack of restraint, ",
  "sn1.76:5.5": "sleepiness and sloth. ",
  "sn1.76:5.6": "You should completely get rid of these holes!” ",
  "sn1.77:0.1": "Linked Discourses 1.77 ",
  "sn1.77:0.2": "8. Slain ",
  "sn1.77:0.3": "Authority ",
  "sn1.77:1.1": "“What is authority in the world? ",
  "sn1.77:1.2": "What’s the best of valuables? ",
  "sn1.77:1.3": "What in the world is a rusty sword? ",
  "sn1.77:1.4": "Who is a pest in the world? ",
  "sn1.77:2.1": "Who gets arrested when they take things away? ",
  "sn1.77:2.2": "And who is loved when they take things away? ",
  "sn1.77:2.3": "And who is approved by the astute ",
  "sn1.77:2.4": "when they come again and again?” ",
  "sn1.77:3.1": "“Sway is authority in the world. ",
  "sn1.77:3.2": "A woman is the best of valuables. ",
  "sn1.77:3.3": "Anger in the world is a rusty sword. ",
  "sn1.77:3.4": "A bandit is a pest in the world. ",
  "sn1.77:4.1": "A bandit gets arrested when they take things away. ",
  "sn1.77:4.2": "And an ascetic is loved when they take things away. ",
  "sn1.77:4.3": "An ascetic is approved by the astute ",
  "sn1.77:4.4": "when they come again and again.” ",
  "sn1.78:0.1": "Linked Discourses 1.78 ",
  "sn1.78:0.2": "8. Slain ",
  "sn1.78:0.3": "Desire ",
  "sn1.78:1.1": "“What should one who wants what’s best <j>not give away? ",
  "sn1.78:1.2": "What should a mortal not forsake? ",
  "sn1.78:1.3": "What should be released when it’s good, ",
  "sn1.78:1.4": "but not when it’s bad?” ",
  "sn1.78:2.1": "“A man shouldn’t give away himself. ",
  "sn1.78:2.2": "He shouldn’t forsake himself. ",
  "sn1.78:2.3": "Speech should be released when it’s good, ",
  "sn1.78:2.4": "but not when it’s bad.” ",
  "sn1.79:0.1": "Linked Discourses 1.79 ",
  "sn1.79:0.2": "8. Slain ",
  "sn1.79:0.3": "Provisions ",
  "sn1.79:1.1": "“What binds the provisions for a journey? ",
  "sn1.79:1.2": "What’s the vault of wealth? ",
  "sn1.79:1.3": "What drags a person around? ",
  "sn1.79:1.4": "What in the world is hard to give up? ",
  "sn1.79:1.5": "With what are ordinary beings bound, ",
  "sn1.79:1.6": "like birds in a snare?” ",
  "sn1.79:2.1": "“Faith binds the provisions for a journey. ",
  "sn1.79:2.2": "Majesty is the vault of wealth. ",
  "sn1.79:2.3": "Desire drags a person around. ",
  "sn1.79:2.4": "Desire in the world is hard to give up. ",
  "sn1.79:2.5": "Ordinary beings are bound by desire, ",
  "sn1.79:2.6": "like birds in a snare.” ",
  "sn1.80:0.1": "Linked Discourses 1.80 ",
  "sn1.80:0.2": "8. Slain ",
  "sn1.80:0.3": "Lamp ",
  "sn1.80:1.1": "“What’s the lamp for the world? ",
  "sn1.80:1.2": "What in the world is wakeful? ",
  "sn1.80:1.3": "Who are one’s work colleagues? ",
  "sn1.80:1.4": "What is one’s walk of life? ",
  "sn1.80:2.1": "What nurtures the idle and the tireless, ",
  "sn1.80:2.2": "like a mother her child? ",
  "sn1.80:2.3": "By what do the creatures who live off the earth ",
  "sn1.80:2.4": "sustain their life?” ",
  "sn1.80:3.1": "“Wisdom is the lamp for the world. ",
  "sn1.80:3.2": "Mindfulness in the world is wakeful. ",
  "sn1.80:3.3": "Cattle are one’s work colleagues, ",
  "sn1.80:3.4": "and the furrow is one’s walk of life. ",
  "sn1.80:4.1": "Rain nurtures the idle and the tireless, ",
  "sn1.80:4.2": "like a mother her child. ",
  "sn1.80:4.3": "The creatures who live off the earth ",
  "sn1.80:4.4": "sustain their life by rain.” ",
  "sn1.81:0.1": "Linked Discourses 1.81 ",
  "sn1.81:0.2": "8. Slain ",
  "sn1.81:0.3": "Free of Strife ",
  "sn1.81:1.1": "“Who in the world is free of strife? ",
  "sn1.81:1.2": "Whose life is not wasted? ",
  "sn1.81:1.3": "Who here completely understands desire? ",
  "sn1.81:1.4": "Who always lives as their own master? ",
  "sn1.81:2.1": "To whom do mother, father, and brothers ",
  "sn1.81:2.2": "bow when they’re established? ",
  "sn1.81:2.3": "Who here, though low born, ",
  "sn1.81:2.4": "is bowed to even by aristocrats?” ",
  "sn1.81:3.1": "“Ascetics are free of strife in the world. ",
  "sn1.81:3.2": "The life of ascetics is not wasted. ",
  "sn1.81:3.3": "Ascetics completely understand desire. ",
  "sn1.81:3.4": "Ascetics always live as their own master. ",
  "sn1.81:4.1": "Mother, father, and brothers ",
  "sn1.81:4.2": "bow to ascetics when they’re established. ",
  "sn1.81:4.3": "Even though an ascetic is low born, ",
  "sn1.81:4.4": "they’re bowed to even by aristocrats.” ",
  "sn1.81:4.5": "",
  "sn1.81:5.1": "",
  "sn1.81:5.2": "",
  "sn1.81:5.3": "",
  "sn1.81:5.4": "",
  "sn1.81:5.5": "The Linked Discourses on Deities are complete. "
}
window.BILARA["sn1_v1"]["en"]["sn1_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
