window.BILARA = window.BILARA || {};
window.BILARA["sn21_v1"] = window.BILARA["sn21_v1"] || {};
window.BILARA["sn21_v1"]["en"] = {
  "sn21.1:0.1": "Linked Discourses 21.1 ",
  "sn21.1:0.2": "1. Monks ",
  "sn21.1:0.3": "With Kolita ",
  "sn21.1:1.1": "So I have heard. ",
  "sn21.1:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn21.1:1.3": "There Venerable Mahāmoggallāna addressed the mendicants: ",
  "sn21.1:1.4": "“Reverends, mendicants!” ",
  "sn21.1:1.5": "“Reverend,” they replied. ",
  "sn21.1:2.1": "Venerable Mahāmoggallāna said this: ",
  "sn21.1:2.2": "“Just now, reverends, as I was in private retreat this thought came to mind: ",
  "sn21.1:2.3": "‘They speak of this thing called “noble silence”. ",
  "sn21.1:2.4": "What then is this noble silence?’ ",
  "sn21.1:2.5": "It occurred to me: ",
  "sn21.1:2.6": "‘As the placing of the mind and keeping it connected are stilled, a mendicant enters and remains in the second absorption, which has the rapture and bliss born of immersion, with internal clarity and mind at one, without placing the mind and keeping it connected. ",
  "sn21.1:2.7": "This is called noble silence.’ ",
  "sn21.1:2.8": "And so, as the placing of the mind and keeping it connected were stilled, I was entering and remaining in the second absorption, which has the rapture and bliss born of immersion, with internal clarity and mind at one, without placing the mind and keeping it connected. ",
  "sn21.1:2.9": "While I was in that meditation, perception and focus accompanied by placing the mind beset me. ",
  "sn21.1:3.1": "Then the Buddha came up to me with his psychic power and said, ",
  "sn21.1:3.2": "‘Moggallāna, Moggallāna! Don’t neglect noble silence, brahmin! Settle your mind in noble silence; unify your mind and bring it to immersion in noble silence.’ ",
  "sn21.1:3.3": "And so, after some time, as the placing of the mind and keeping it connected were stilled, I entered and remained in the second absorption … ",
  "sn21.1:3.4": "So if anyone should be rightly called ",
  "sn21.1:3.5": "a disciple who attained to great direct knowledge with help from the Teacher, it’s me.” ",
  "sn21.1:3.6": "",
  "sn21.2:0.1": "Linked Discourses 21.2 ",
  "sn21.2:0.2": "1. Monks ",
  "sn21.2:0.3": "With Upatissa ",
  "sn21.2:1.1": "At Sāvatthī. ",
  "sn21.2:1.2": "There Sāriputta addressed the mendicants: ",
  "sn21.2:1.3": "“Reverends, mendicants!” ",
  "sn21.2:1.4": "“Reverend,” they replied. ",
  "sn21.2:1.5": "Sāriputta said this: ",
  "sn21.2:2.1": "“Just now, reverends, as I was in private retreat this thought came to mind: ",
  "sn21.2:2.2": "‘Is there anything in the world whose decay and perishing would give rise to sorrow, lamentation, pain, sadness, and distress in me?’ ",
  "sn21.2:2.3": "It occurred to me: ",
  "sn21.2:2.4": "‘There is nothing in the world whose decay and perishing would give rise to sorrow, lamentation, pain, sadness, and distress in me.’” ",
  "sn21.2:3.1": "When he said this, Venerable Ānanda said to him, ",
  "sn21.2:3.2": "“Even if the Teacher were to decay and perish? Wouldn’t that give rise to sorrow, lamentation, pain, sadness, and distress in you?” ",
  "sn21.2:3.3": "“Even if the Teacher were to decay and perish, that wouldn’t give rise to sorrow, lamentation, pain, sadness, and distress in me. Still, I would think: ",
  "sn21.2:3.4": "‘Oh lord, the illustrious Teacher, so mighty and powerful, has vanished! ",
  "sn21.2:3.5": "If the Buddha was to remain for a long time, that would be for the welfare and happiness of the people, out of sympathy for the world, for the benefit, welfare, and happiness of gods and humans.’” ",
  "sn21.2:3.6": "“That must be because Venerable Sāriputta has long ago totally eradicated I-making, mine-making, and the underlying tendency to conceit. ",
  "sn21.2:3.7": "So even if the Teacher were to decay and perish, it wouldn’t give rise to sorrow, lamentation, pain, sadness, and distress in him.” ",
  "sn21.3:0.1": "Linked Discourses 21.3 ",
  "sn21.3:0.2": "1. Monks ",
  "sn21.3:0.3": "A Mound of Salt ",
  "sn21.3:1.1": "So I have heard. ",
  "sn21.3:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn21.3:1.3": "At that time Venerables Sāriputta and Moggallāna were staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn21.3:1.4": "Then in the late afternoon, Venerable Sāriputta came out of retreat, went to Venerable Moggallāna, and exchanged greetings with him. ",
  "sn21.3:1.5": "When the greetings and polite conversation were over, Sāriputta sat down to one side, and said to Mahāmoggallāna: ",
  "sn21.3:2.1": "“Reverend Moggallāna, your faculties are so very clear, and your complexion is pure and bright. ",
  "sn21.3:2.2": "Have you spent the day in a peaceful meditation?” ",
  "sn21.3:2.3": "“Reverend, I’ve spent the day in a coarse meditation. ",
  "sn21.3:2.4": "But I have had some Dhamma talk.” ",
  "sn21.3:2.5": "“Who did you have a Dhamma talk with?” ",
  "sn21.3:2.6": "“With the Buddha.” ",
  "sn21.3:2.7": "“But Reverend, the Buddha is far away. He’s staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn21.3:2.8": "Did you go to him with your psychic power, ",
  "sn21.3:2.9": "or did he come to you?” ",
  "sn21.3:2.10": "“No reverend, I didn’t go to him with my psychic power, ",
  "sn21.3:2.11": "nor did he come to me. ",
  "sn21.3:2.12": "Rather, the Buddha cleared his clairvoyance and clairaudience towards me, ",
  "sn21.3:2.13": "and I cleared my clairvoyance and clairaudience towards him.” ",
  "sn21.3:2.14": "“But what manner of Dhamma talk did you have together?” ",
  "sn21.3:3.1": "“Well, reverend, I said to the Buddha, ",
  "sn21.3:3.2": "‘Sir, they speak of one who is energetic. ",
  "sn21.3:3.3": "How is an energetic person defined?’ ",
  "sn21.3:3.4": "When I said this, the Buddha said, ",
  "sn21.3:3.5": "‘Moggallāna, it’s when a mendicant lives with energy roused up: ",
  "sn21.3:3.6": "“Gladly, let only skin, sinews, and bones remain! Let the flesh and blood waste away in my body! I will not stop trying until I have achieved what is possible by human strength, energy, and vigor.” ",
  "sn21.3:3.7": "That’s how an individual is energetic.’ ",
  "sn21.3:3.8": "That’s the Dhamma talk I had together with the Buddha.” ",
  "sn21.3:4.1": "“Reverend, next to Venerable Mahāmoggallāna I’m like a few pieces of gravel next to the Himalayas, the king of mountains. ",
  "sn21.3:4.2": "",
  "sn21.3:4.3": "Venerable Mahāmoggallāna is so mighty and powerful he could, if he wished, live on for the proper lifespan.” ",
  "sn21.3:5.1": "“Reverend, next to Venerable Sāriputta I’m like a few grains of salt next to a mound of salt. ",
  "sn21.3:5.2": "",
  "sn21.3:5.3": "Venerable Sāriputta has been commended, complimented, and praised by the Buddha: ",
  "sn21.3:6.1": "‘Sāriputta is full of wisdom, ",
  "sn21.3:6.2": "ethics, and peace. ",
  "sn21.3:6.3": "Even a mendicant who has crossed over ",
  "sn21.3:6.4": "might at best equal him.’” ",
  "sn21.3:7.1": "And so these two spiritual giants agreed with each others’ fine words. ",
  "sn21.4:0.1": "Linked Discourses 21.4 ",
  "sn21.4:0.2": "1. Monks ",
  "sn21.4:0.3": "A Junior Mendicant ",
  "sn21.4:1.1": "At Sāvatthī. ",
  "sn21.4:1.2": "Now at that time a certain junior monk, after his meal, on his return from almsround, entered his dwelling, where he adhered to passivity and silence. And he didn’t help the mendicants out when it was time to sew robes. ",
  "sn21.4:1.3": "Then several mendicants went up to the Buddha, bowed, sat down to one side, and told him what had happened. ",
  "sn21.4:1.4": "",
  "sn21.4:2.1": "So the Buddha addressed one of the monks, ",
  "sn21.4:2.2": "“Please, monk, in my name tell that monk that the Teacher summons him.” ",
  "sn21.4:2.3": "“Yes, sir,” that monk replied. He went to that monk and said to him, ",
  "sn21.4:2.4": "“Reverend, the teacher summons you.” ",
  "sn21.4:2.5": "“Yes, reverend,” that monk replied. He went to the Buddha, bowed, and sat down to one side. The Buddha said to him: ",
  "sn21.4:2.6": "“Is it really true, monk, that after your meal, on your return from almsround, you entered your dwelling, where you adhered to passivity and silence, and you didn’t help the mendicants out when it was time to sew robes?” ",
  "sn21.4:2.7": "“Sir, I am doing my own work.” ",
  "sn21.4:3.1": "Then the Buddha, knowing that monk’s train of thought, addressed the mendicants: ",
  "sn21.4:3.2": "“Mendicants, don’t complain about this monk. ",
  "sn21.4:3.3": "This monk gets the four absorptionsblissful meditations in this life that belong to the higher mindwhen he wants, without trouble or difficulty. He has realized the supreme culmination of the spiritual path in this very life, and lives having achieved with his own insight the goal for which gentlemen rightly go forth from the lay life to homelessness.” ",
  "sn21.4:4.1": "That is what the Buddha said. ",
  "sn21.4:4.2": "Then the Holy One, the Teacher, went on to say: ",
  "sn21.4:5.1": "“Not by being slack, ",
  "sn21.4:5.2": "or with little strength ",
  "sn21.4:5.3": "may this be realizedextinguishment, ",
  "sn21.4:5.4": "the release from all suffering. ",
  "sn21.4:6.1": "This young monk, ",
  "sn21.4:6.2": "this best of men, ",
  "sn21.4:6.3": "bears his final body, ",
  "sn21.4:6.4": "having vanquished Māra with his legions.” ",
  "sn21.5:0.1": "Linked Discourses 21.5 ",
  "sn21.5:0.2": "1. Monks ",
  "sn21.5:0.3": "With Sujāta ",
  "sn21.5:1.1": "At Sāvatthī. ",
  "sn21.5:1.2": "Then Venerable Sujāta went to see the Buddha. ",
  "sn21.5:1.3": "The Buddha saw him coming off in the distance, ",
  "sn21.5:1.4": "and addressed the mendicants: ",
  "sn21.5:1.5": "“This gentleman shines in both ways. ",
  "sn21.5:1.6": "He’s attractive, good-looking, lovely, of surpassing beauty. And he has realized the supreme end of the spiritual path in this very life. He lives having achieved with his own insight the goal for which gentlemen rightly go forth from the lay life to homelessness.” ",
  "sn21.5:1.7": "That is what the Buddha said. ",
  "sn21.5:1.8": "Then the Holy One, the Teacher, went on to say: ",
  "sn21.5:2.1": "“This mendicant truly shines. ",
  "sn21.5:2.2": "His heart is upright, ",
  "sn21.5:2.3": "he’s unfettered, detached, ",
  "sn21.5:2.4": "quenched by not grasping. ",
  "sn21.5:2.5": "He bears his final body, ",
  "sn21.5:2.6": "having vanquished Māra with his legions.” ",
  "sn21.6:0.1": "Linked Discourses 21.6 ",
  "sn21.6:0.2": "1. Monks ",
  "sn21.6:0.3": "With Bhaddiya the Dwarf ",
  "sn21.6:1.1": "At Sāvatthī. ",
  "sn21.6:1.2": "Then Venerable Bhaddiya the Dwarf went to see the Buddha. ",
  "sn21.6:1.3": "The Buddha saw him coming off in the distance, ",
  "sn21.6:1.4": "and addressed the mendicants: ",
  "sn21.6:1.5": "“Mendicants, do you see this monk comingugly, unsightly, deformed, and despised by the mendicants?” ",
  "sn21.6:1.6": "“Yes, sir.” ",
  "sn21.6:1.7": "“That mendicant is very mighty and powerful. It’s not easy to find an attainment that he has not already attained. ",
  "sn21.6:1.8": "And he has realized the supreme end of the spiritual path in this very life. He lives having achieved with his own insight the goal for which gentlemen rightly go forth from the lay life to homelessness.” ",
  "sn21.6:1.9": "That is what the Buddha said. ",
  "sn21.6:1.10": "Then the Holy One, the Teacher, went on to say: ",
  "sn21.6:2.1": "“Geese, herons, and peacocks, ",
  "sn21.6:2.2": "elephants and spotted deer",
  "sn21.6:2.3": "though their bodies are not equal, ",
  "sn21.6:2.4": "they all fear the lion. ",
  "sn21.6:3.1": "So it is for humans",
  "sn21.6:3.2": "if a little person is wise, ",
  "sn21.6:3.3": "they’re the truly great one, ",
  "sn21.6:3.4": "not the fool with a good body.” ",
  "sn21.7:0.1": "Linked Discourses 21.7 ",
  "sn21.7:0.2": "1. Monks ",
  "sn21.7:0.3": "With Visākha, Pañcāli’s Son ",
  "sn21.7:1.1": "So I have heard. ",
  "sn21.7:1.2": "At one time the Buddha was staying near Vesālī, at the Great Wood, in the hall with the peaked roof. ",
  "sn21.7:1.3": "Now at that time Venerable Visākha, Pañcāli’s son, was educating, encouraging, firing up, and inspiring the mendicants in the assembly hall with a Dhamma talk. His words were polished, clear, articulate, expressing the meaning, comprehensive, and independent. ",
  "sn21.7:2.1": "Then in the late afternoon, the Buddha came out of retreat and went to the assembly hall. He sat down on the seat spread out, ",
  "sn21.7:2.2": "and addressed the mendicants: ",
  "sn21.7:2.3": "“Mendicants, who was educating, encouraging, firing up, and inspiring the mendicants in the assembly hall with a Dhamma talk?” ",
  "sn21.7:2.4": "“Sir, it was Venerable Visākha, Pañcāli’s son.” ",
  "sn21.7:3.1": "Then the Buddha said to Visākha: ",
  "sn21.7:3.2": "“Good, good, Visākha! ",
  "sn21.7:3.3": "It’s good that you educate, encourage, fire up, and inspire the mendicants in the assembly hall with a Dhamma talk, with words that are polished, clear, articulate, expressing the meaning, comprehensive, and independent.” ",
  "sn21.7:4.1": "That is what the Buddha said. ",
  "sn21.7:4.2": "Then the Holy One, the Teacher, went on to say: ",
  "sn21.7:5.1": "“Though an astute person is mixed up with fools, ",
  "sn21.7:5.2": "they don’t know unless he speaks. ",
  "sn21.7:5.3": "But when he speaks they know, ",
  "sn21.7:5.4": "he’s teaching the state free of death. ",
  "sn21.7:6.1": "He should speak and illustrate the teaching, ",
  "sn21.7:6.2": "holding up the banner of the seers. ",
  "sn21.7:6.3": "Words well spoken are the seers’ banner, ",
  "sn21.7:6.4": "for the teaching is the banner of the seers.” ",
  "sn21.8:0.1": "Linked Discourses 21.8 ",
  "sn21.8:0.2": "1. Monks ",
  "sn21.8:0.3": "With Nanda ",
  "sn21.8:1.1": "At Sāvatthī. ",
  "sn21.8:1.2": "Then Venerable Nandathe Buddha’s cousin on his mother’s sidedressed in nicely pressed and ironed robes, applied eyeshadow, and took a glazed bowl. He went to the Buddha, bowed, and sat down to one side. The Buddha said to him: ",
  "sn21.8:1.3": "“Nanda, as a gentleman who has gone forth out of faith from the lay life to homelessness, it’s not appropriate for you to dress in nicely pressed and ironed robes, apply eyeshadow, and carry a glazed bowl. ",
  "sn21.8:1.4": "It’s appropriate for you to stay in the wilderness, eat only almsfood, wear rag robes, and live without concern for sensual pleasures.” ",
  "sn21.8:1.5": "That is what the Buddha said. ",
  "sn21.8:1.6": "Then the Holy One, the Teacher, went on to say: ",
  "sn21.8:2.1": "“When will I see Nanda ",
  "sn21.8:2.2": "in the wilderness, wearing rag robes, ",
  "sn21.8:2.3": "feeding on scraps offered by strangers, ",
  "sn21.8:2.4": "unconcerned for sensual pleasures?” ",
  "sn21.8:3.1": "Then some time later Venerable Nanda stayed in the wilderness, ate only almsfood, wore rag robes, and lived without concern for sensual pleasures. ",
  "sn21.9:0.1": "Linked Discourses 21.9 ",
  "sn21.9:0.2": "1. Monks ",
  "sn21.9:0.3": "With Tissa ",
  "sn21.9:1.1": "At Sāvatthī. ",
  "sn21.9:1.2": "Then Venerable Tissathe Buddha’s cousin on his father’s sidewent to the Buddha, bowed, and sat down to one side. He was miserable and sad, with tears flowing. Then the Buddha said to him: ",
  "sn21.9:1.3": "“Tissa, why are you sitting there so miserable and sad, with tears flowing?” ",
  "sn21.9:1.4": "“Sir, it’s because the mendicants beset me on all sides with sneering and jeering.” ",
  "sn21.9:1.5": "“That’s because you admonish others, but don’t accept admonition yourself. ",
  "sn21.9:1.6": "As a gentleman who has gone forth out of faith from the lay life to homelessness, it’s not appropriate for you to admonish others without accepting admonition yourself. ",
  "sn21.9:1.7": "It’s appropriate for you to ",
  "sn21.9:1.8": "admonish others and accept admonition yourself.” ",
  "sn21.9:2.1": "That is what the Buddha said. ",
  "sn21.9:2.2": "Then the Holy One, the Teacher, went on to say: ",
  "sn21.9:3.1": "“Why are you angry? Don’t be angry! ",
  "sn21.9:3.2": "It’s better to not be angry, Tissa. ",
  "sn21.9:3.3": "For this spiritual life is lived ",
  "sn21.9:3.4": "in order to remove anger, conceit, and denigration.” ",
  "sn21.10:0.1": "Linked Discourses 21.10 ",
  "sn21.10:0.2": "1. Monks ",
  "sn21.10:0.3": "Senior In Name Only ",
  "sn21.10:1.1": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn21.10:1.2": "Now at that time there was a certain mendicant who was Senior in name only. He lived alone and praised living alone. ",
  "sn21.10:1.3": "He entered the village for alms alone, returned alone, sat in private alone, and focussed on walking mindfully alone. ",
  "sn21.10:1.4": "Then several mendicants went up to the Buddha, bowed, sat down to one side, and said to him, ",
  "sn21.10:1.5": "“Sir, there’s a certain mendicant who is Senior in name only. He lives alone and praises living alone.” ",
  "sn21.10:2.1": "So the Buddha addressed one of the monks, ",
  "sn21.10:2.2": "“Please, monk, in my name tell the mendicant Senior that ",
  "sn21.10:2.3": "the teacher summons him.” ",
  "sn21.10:2.4": "“Yes, sir,” that monk replied. He went to Venerable Senior and said to him, ",
  "sn21.10:2.5": "“Reverend Senior, the teacher summons you.” ",
  "sn21.10:2.6": "“Yes, reverend,” that monk replied. He went to the Buddha, bowed, and sat down to one side. The Buddha said to him: ",
  "sn21.10:2.7": "“Is it really true, Senior, that you live alone and praise living alone?” ",
  "sn21.10:2.8": "“Yes, sir.” ",
  "sn21.10:2.9": "“But in what way do you live alone and praise living alone?” ",
  "sn21.10:2.10": "“Well, sir, I enter the village for alms alone, return alone, sit in private alone, and focus on walking mindfully alone. ",
  "sn21.10:2.11": "That’s how I live alone and praise living alone.” ",
  "sn21.10:3.1": "“That is a kind of living alone, I don’t deny it. ",
  "sn21.10:3.2": "But as to how living alone is fulfilled in detail, ",
  "sn21.10:3.3": "listen and apply your mind well, I will speak.” ",
  "sn21.10:3.4": "“Yes, sir,” he replied. ",
  "sn21.10:3.5": "“And how, Senior, is living alone fulfilled in detail? ",
  "sn21.10:3.6": "It’s when what’s in the past is given up, what’s in the future is relinquished, and desire and greed for present incarnations is eliminated. ",
  "sn21.10:3.7": "That’s how living alone is fulfilled in detail.” ",
  "sn21.10:4.1": "That is what the Buddha said. ",
  "sn21.10:4.2": "Then the Holy One, the Teacher, went on to say: ",
  "sn21.10:5.1": "“The champion, all-knower, so very intelligent, ",
  "sn21.10:5.2": "is unsullied in the midst of all things. ",
  "sn21.10:5.3": "He’s given up all, freed in the ending of craving: ",
  "sn21.10:5.4": "I declare that man to be one who lives alone.” ",
  "sn21.11:0.1": "Linked Discourses 21.11 ",
  "sn21.11:0.2": "1. Monks ",
  "sn21.11:0.3": "With Mahākappina ",
  "sn21.11:1.1": "At Sāvatthī. ",
  "sn21.11:1.2": "Then Venerable Mahākappina went to see the Buddha. ",
  "sn21.11:1.3": "The Buddha saw him coming off in the distance, ",
  "sn21.11:1.4": "and addressed the mendicants: ",
  "sn21.11:1.5": "“Mendicants, do you see that monk comingwhite, thin, with a pointy nose?” ",
  "sn21.11:1.6": "“Yes, sir.” ",
  "sn21.11:1.7": "“That mendicant is very mighty and powerful. ",
  "sn21.11:1.8": "It’s not easy to find an attainment that he has not already attained. ",
  "sn21.11:1.9": "And he has realized the supreme end of the spiritual path in this very life. He lives having achieved with his own insight the goal for which gentlemen rightly go forth from the lay life to homelessness.” ",
  "sn21.11:2.1": "That is what the Buddha said. ",
  "sn21.11:2.2": "Then the Holy One, the Teacher, went on to say: ",
  "sn21.11:3.1": "“The aristocrat is best among people ",
  "sn21.11:3.2": "who take clan as the standard. ",
  "sn21.11:3.3": "But one accomplished in knowledge and conduct ",
  "sn21.11:3.4": "is best among gods and humans. ",
  "sn21.11:4.1": "The sun blazes by day, ",
  "sn21.11:4.2": "the moon radiates at night, ",
  "sn21.11:4.3": "the aristocrat shines in armor, ",
  "sn21.11:4.4": "and the brahmin shines in absorption. ",
  "sn21.11:4.5": "But all day and all night, ",
  "sn21.11:4.6": "the Buddha blazes with glory.” ",
  "sn21.12:0.1": "Linked Discourses 21.12 ",
  "sn21.12:0.2": "1. Monks ",
  "sn21.12:0.3": "Companions ",
  "sn21.12:1.1": "At Sāvatthī. ",
  "sn21.12:1.2": "Then two mendicants who were companions, protégés of Venerable Mahākappina, went to see the Buddha. ",
  "sn21.12:1.3": "The Buddha saw them coming off in the distance, ",
  "sn21.12:1.4": "and addressed the mendicants: ",
  "sn21.12:1.5": "“Mendicants, do you see those monks coming who are companions, protégés of Venerable Mahākappina?” ",
  "sn21.12:1.6": "“Yes, sir.” ",
  "sn21.12:1.7": "“Those mendicants are very mighty and powerful. ",
  "sn21.12:1.8": "It’s not easy to find an attainment that they have not already attained. ",
  "sn21.12:1.9": "And they’ve realized the supreme end of the spiritual path in this very life. They live having achieved with their own insight the goal for which gentlemen rightly go forth from the lay life to homelessness.” ",
  "sn21.12:2.1": "That is what the Buddha said. ",
  "sn21.12:2.2": "Then the Holy One, the Teacher, went on to say: ",
  "sn21.12:3.1": "“These companion mendicants ",
  "sn21.12:3.2": "have been together for a long time. ",
  "sn21.12:3.3": "The true teaching has brought them together, ",
  "sn21.12:3.4": "the teaching proclaimed by the Buddha. ",
  "sn21.12:4.1": "They’ve been well trained by Kappina ",
  "sn21.12:4.2": "in the teaching proclaimed by the Noble One. ",
  "sn21.12:4.3": "They bear their final body, ",
  "sn21.12:4.4": "having vanquished Māra with his legions.” ",
  "sn21.12:4.5": "",
  "sn21.12:4.6": "",
  "sn21.12:5.1": "",
  "sn21.12:5.2": "",
  "sn21.12:5.3": "",
  "sn21.12:5.4": "",
  "sn21.12:5.5": "",
  "sn21.12:5.6": "",
  "sn21.12:5.7": "The Linked Discourses on monks are complete. ",
  "sn21.12:5.8": "",
  "sn21.12:6.1": "",
  "sn21.12:6.2": "",
  "sn21.12:6.3": "",
  "sn21.12:6.4": "",
  "sn21.12:6.5": "",
  "sn21.12:6.6": "The Book of Causality is finished. "
}
window.BILARA["sn21_v1"]["en"]["sn21_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
