window.BILARA = window.BILARA || {};
window.BILARA["sn23_v1"] = window.BILARA["sn23_v1"] || {};
window.BILARA["sn23_v1"]["en"] = {
  "sn23.1:0.1": "Linked Discourses 23.1 ",
  "sn23.1:0.2": "1. About Māra ",
  "sn23.1:0.3": "About Māra ",
  "sn23.1:1.1": "At Sāvatthī. ",
  "sn23.1:1.2": "Then Venerable Rādha went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn23.1:2.1": "“Sir, they speak of this thing called ‘Māra’. ",
  "sn23.1:2.2": "How is Māra defined?” ",
  "sn23.1:2.3": "“When there is form, Rādha, there would be Māra, or the murderer, or the murdered. ",
  "sn23.1:2.4": "So you should see form as Māra, the murderer, the murdered, the diseased, the boil, the dart, the gloom, the gloominess. ",
  "sn23.1:2.5": "Those who see it like this see rightly. ",
  "sn23.1:2.6": "When there is feeling … ",
  "sn23.1:2.7": "perception … ",
  "sn23.1:2.8": "choices … ",
  "sn23.1:2.9": "consciousness, there may be Māra, or the murderer, or the murdered. ",
  "sn23.1:2.10": "So you should see consciousness as Māra, the murderer, the murdered, the diseased, the boil, the dart, the gloom, the gloominess. ",
  "sn23.1:2.11": "Those who see it like this see rightly.” ",
  "sn23.1:3.1": "“But sir, what’s the purpose of seeing rightly?” ",
  "sn23.1:3.2": "“Disillusionment is the purpose of seeing rightly.” ",
  "sn23.1:3.3": "“But what’s the purpose of disillusionment?” ",
  "sn23.1:3.4": "“Dispassion is the purpose of disillusionment.” ",
  "sn23.1:3.5": "“But what’s the purpose of dispassion?” ",
  "sn23.1:3.6": "“Freedom is the purpose of dispassion.” ",
  "sn23.1:3.7": "“But what’s the purpose of freedom?” ",
  "sn23.1:3.8": "“Extinguishment is the purpose of freedom.” ",
  "sn23.1:3.9": "“But sir, what is the purpose of extinguishment?” ",
  "sn23.1:3.10": "“Your question goes too far, Rādha. You weren’t able to grasp the limit of questioning. ",
  "sn23.1:3.11": "For extinguishment is the objective, destination, and culmination of the spiritual life.” ",
  "sn23.2:0.1": "Linked Discourses 23.2 ",
  "sn23.2:0.2": "1. About Māra ",
  "sn23.2:0.3": "Sentient Beings ",
  "sn23.2:1.1": "At Sāvatthī. ",
  "sn23.2:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.2:1.3": "“Sir, they speak of this thing called a ‘sentient being’. ",
  "sn23.2:1.4": "How is a sentient being defined?” ",
  "sn23.2:1.5": "“Rādha, when you cling, strongly cling, to desire, greed, relishing, and craving for form, then a being is spoken of. ",
  "sn23.2:1.6": "When you cling, strongly cling, to desire, greed, relishing, and craving for feeling … ",
  "sn23.2:1.7": "perception … ",
  "sn23.2:1.8": "choices … ",
  "sn23.2:1.9": "consciousness, then a being is spoken of. ",
  "sn23.2:2.1": "Suppose some boys or girls were playing with sandcastles. ",
  "sn23.2:2.2": "As long as they’re not rid of greed, desire, fondness, thirst, passion, and craving for those sandcastles, they cling to them, dally with them, treasure them, and treat them as their own. ",
  "sn23.2:2.3": "But when they are rid of greed, desire, fondness, thirst, passion, and craving for those sandcastles, they scatter, smash, and destroy them with their hands and feet, making them unplayable. ",
  "sn23.2:2.4": "In the same way, you should scatter, smash, and destroy form, making it unplayable. And you should practice for the ending of craving. ",
  "sn23.2:2.5": "You should scatter, smash, and destroy feeling … ",
  "sn23.2:2.6": "perception … ",
  "sn23.2:2.7": "choices … ",
  "sn23.2:2.8": "consciousness, making it unplayable. And you should practice for the ending of craving. ",
  "sn23.2:2.9": "For the ending of craving is extinguishment.” ",
  "sn23.3:0.1": "Linked Discourses 23.3 ",
  "sn23.3:0.2": "1. About Māra ",
  "sn23.3:0.3": "The Leash to Existence ",
  "sn23.3:1.1": "At Sāvatthī. ",
  "sn23.3:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.3:1.3": "“Sir, they speak of this thing called ‘the cessation of the leash to existence’. ",
  "sn23.3:1.4": "What is the leash to existence? And what is the cessation of the leash to existence?” ",
  "sn23.3:1.5": "“Rādha, any desire, greed, relishing, and craving for form; and any attraction, grasping, mental fixation, insistence, and underlying tendencies",
  "sn23.3:1.6": "this is called the leash to existence. ",
  "sn23.3:1.7": "Their cessation is the cessation of the leash to existence. ",
  "sn23.3:1.8": "Any desire, greed, relishing, and craving for feeling … ",
  "sn23.3:1.9": "perception … ",
  "sn23.3:1.10": "choices … ",
  "sn23.3:1.11": "consciousness; and any attraction, grasping, mental fixation, insistence, and underlying tendencies",
  "sn23.3:1.12": "this is called the leash to existence. ",
  "sn23.3:1.13": "Their cessation is the cessation of the leash to existence.” ",
  "sn23.4:0.1": "Linked Discourses 23.4 ",
  "sn23.4:0.2": "1. About Māra ",
  "sn23.4:0.3": "Should Be Completely Understood ",
  "sn23.4:1.1": "At Sāvatthī. ",
  "sn23.4:1.2": "Then Venerable Rādha went up to the Buddha, bowed, and sat down to one side. The Buddha said to him: ",
  "sn23.4:2.1": "“Rādha, I will teach you the things that should be completely understood, complete understanding, and the individual who has completely understood. ",
  "sn23.4:2.2": "Listen and apply your mind well, I will speak.” ",
  "sn23.4:2.3": "“Yes, sir,” Rādha replied. ",
  "sn23.4:2.4": "The Buddha said this: ",
  "sn23.4:2.5": "“And what things should be completely understood? ",
  "sn23.4:2.6": "Form, feeling, perception, choices, and consciousness. ",
  "sn23.4:2.7": "These are called the things that should be completely understood. ",
  "sn23.4:2.8": "And what is complete understanding? ",
  "sn23.4:2.9": "The ending of greed, hate, and delusion. ",
  "sn23.4:2.10": "This is called complete understanding. ",
  "sn23.4:2.11": "And what is the individual who has completely understood? ",
  "sn23.4:2.12": "It should be said: a perfected one, ",
  "sn23.4:2.13": "the venerable of such and such name and clan. ",
  "sn23.4:2.14": "This is called the individual who has completely understood.” ",
  "sn23.5:0.1": "Linked Discourses 23.5 ",
  "sn23.5:0.2": "1. About Māra ",
  "sn23.5:0.3": "Ascetics and Brahmins ",
  "sn23.5:1.1": "At Sāvatthī. ",
  "sn23.5:1.2": "When Venerable Rādha was seated to one side, the Buddha said to him: ",
  "sn23.5:1.3": "“Rādha, there are these five grasping aggregates. ",
  "sn23.5:1.4": "What five? ",
  "sn23.5:1.5": "The grasping aggregates of form, feeling, perception, choices, and consciousness. ",
  "sn23.5:1.6": "There are ascetics and brahmins who don’t truly understand these five grasping aggregates’ gratification, drawback, and escape. ",
  "sn23.5:1.7": "I don’t deem them as true ascetics and brahmins. Those venerables don’t realize the goal of life as an ascetic or brahmin, and don’t live having realized it with their own insight. ",
  "sn23.5:1.8": "There are ascetics and brahmins who do truly understand these five grasping aggregates’ gratification, drawback, and escape. ",
  "sn23.5:1.9": "I deem them as true ascetics and brahmins. Those venerables realize the goal of life as an ascetic or brahmin, and live having realized it with their own insight.” ",
  "sn23.6:0.1": "Linked Discourses 23.6 ",
  "sn23.6:0.2": "1. About Māra ",
  "sn23.6:0.3": "Ascetics and Brahmins (2nd) ",
  "sn23.6:1.1": "At Sāvatthī. ",
  "sn23.6:1.2": "When Venerable Rādha was seated to one side, the Buddha said to him: ",
  "sn23.6:1.3": "“Rādha, there are these five grasping aggregates. ",
  "sn23.6:1.4": "What five? ",
  "sn23.6:1.5": "The grasping aggregates of form, feeling, perception, choices, and consciousness. ",
  "sn23.6:1.6": "There are ascetics and brahmins who don’t truly understand these five grasping aggregates’ origin, disappearance, gratification, drawback, and escape … Those venerables don’t realize the goal of life as an ascetic or brahmin … ",
  "sn23.6:1.7": "There are ascetics and brahmins who do truly understand … Those venerables realize the goal of life as an ascetic or brahmin, and live having realized it with their own insight.” ",
  "sn23.7:0.1": "Linked Discourses 23.7 ",
  "sn23.7:0.2": "1. About Māra ",
  "sn23.7:0.3": "A Stream-Enterer ",
  "sn23.7:1.1": "At Sāvatthī. ",
  "sn23.7:1.2": "When Venerable Rādha was seated to one side, the Buddha said to him: ",
  "sn23.7:1.3": "“Rādha, there are these five grasping aggregates. ",
  "sn23.7:1.4": "What five? ",
  "sn23.7:1.5": "The grasping aggregates of form, feeling, perception, choices, and consciousness. ",
  "sn23.7:1.6": "When a noble disciple truly understands these five grasping aggregates’ origin, disappearance, gratification, drawback, and escape, ",
  "sn23.7:1.7": "they’re called a noble disciple who is a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn23.8:0.1": "Linked Discourses 23.8 ",
  "sn23.8:0.2": "1. About Māra ",
  "sn23.8:0.3": "A Perfected One ",
  "sn23.8:1.1": "At Sāvatthī. ",
  "sn23.8:1.2": "When Venerable Rādha was seated to one side, the Buddha said to him: ",
  "sn23.8:1.3": "“Rādha, there are these five grasping aggregates. ",
  "sn23.8:1.4": "What five? ",
  "sn23.8:1.5": "The grasping aggregates of form, feeling, perception, choices, and consciousness. ",
  "sn23.8:1.6": "A mendicant comes to be freed by not grasping after truly understanding these five grasping aggregates’ origin, disappearance, gratification, drawback, and escape. ",
  "sn23.8:1.7": "Such a mendicant is called a perfected one, with defilements ended, who has completed the spiritual journey, done what had to be done, laid down the burden, achieved their heart’s goal, utterly ended the fetter of continued existence, and is rightly freed through enlightenment.” ",
  "sn23.9:0.1": "Linked Discourses 23.9 ",
  "sn23.9:0.2": "1. About Māra ",
  "sn23.9:0.3": "Desire and Greed ",
  "sn23.9:1.1": "At Sāvatthī. ",
  "sn23.9:1.2": "When Venerable Rādha was seated to one side, the Buddha said to him: ",
  "sn23.9:1.3": "“Rādha, you should give up any desire, greed, relishing, and craving for form. ",
  "sn23.9:1.4": "Thus that form will be given up, cut off at the root, made like a palm stump, obliterated, and unable to arise in the future. ",
  "sn23.9:1.5": "You should give up any desire, greed, relishing, and craving for feeling … ",
  "sn23.9:1.6": "",
  "sn23.9:1.7": "perception … ",
  "sn23.9:1.8": "choices … ",
  "sn23.9:1.9": "",
  "sn23.9:1.10": "consciousness. ",
  "sn23.9:1.11": "Thus that consciousness will be given up, cut off at the root, made like a palm stump, obliterated, and unable to arise in the future.” ",
  "sn23.10:0.1": "Linked Discourses 23.10 ",
  "sn23.10:0.2": "1. About Māra ",
  "sn23.10:0.3": "Desire and Greed (2nd) ",
  "sn23.10:1.1": "At Sāvatthī. ",
  "sn23.10:1.2": "When Venerable Rādha was seated to one side, the Buddha said to him: ",
  "sn23.10:1.3": "“Rādha, you should give up any desire, greed, relishing, and craving for form; and any attraction, grasping, mental fixation, insistence, and underlying tendencies. ",
  "sn23.10:1.4": "Thus that form will be given up, cut off at the root, made like a palm stump, obliterated, and unable to arise in the future. ",
  "sn23.10:1.5": "You should give up any desire, greed, relishing, and craving for feeling … ",
  "sn23.10:1.6": "",
  "sn23.10:1.7": "perception … ",
  "sn23.10:1.8": "choices … ",
  "sn23.10:1.9": "",
  "sn23.10:1.10": "consciousness; and any attraction, grasping, mental fixation, insistence, and underlying tendencies. ",
  "sn23.10:1.11": "Thus that consciousness will be given up, cut off at the root, made like a palm stump, obliterated, and unable to arise in the future.” ",
  "sn23.10:1.12": "",
  "sn23.10:1.13": "",
  "sn23.10:2.1": "",
  "sn23.10:2.2": "",
  "sn23.10:2.3": "",
  "sn23.11:0.1": "Linked Discourses 23.11 ",
  "sn23.11:0.2": "2. About Māra (2nd) ",
  "sn23.11:0.3": "About Māra ",
  "sn23.11:1.1": "At Sāvatthī. ",
  "sn23.11:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.11:1.3": "“Sir, they speak of ‘Māra’. ",
  "sn23.11:1.4": "How is Māra defined?” ",
  "sn23.11:1.5": "“Rādha, form is Māra, feeling is Māra, perception is Māra, choices are Māra, consciousness is Māra. ",
  "sn23.11:1.6": "Seeing this, a learned noble disciple grows disillusioned with form, feeling, perception, choices, and consciousness. ",
  "sn23.11:1.7": "Being disillusioned, desire fades away. When desire fades away they’re freed. When they’re freed, they know they’re freed. ",
  "sn23.11:1.8": "They understand: ‘Rebirth is ended, the spiritual journey has been completed, what had to be done has been done, there is nothing further for this place.’” ",
  "sn23.12:0.1": "Linked Discourses 23.12 ",
  "sn23.12:0.2": "2. About Māra (2nd) ",
  "sn23.12:0.3": "Subject to Māra ",
  "sn23.12:1.1": "At Sāvatthī. ",
  "sn23.12:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.12:1.3": "“Sir, they speak of ‘Māra nature’. ",
  "sn23.12:1.4": "What is of Māra nature?” ",
  "sn23.12:1.5": "“Rādha, form is of Māra nature. Feeling, perception, choices, and consciousness are of Māra nature. ",
  "sn23.12:1.6": "Seeing this … ",
  "sn23.12:1.7": "They understand: ‘… there is nothing further for this place.’” ",
  "sn23.13:0.1": "Linked Discourses 23.13 ",
  "sn23.13:0.2": "2. About Māra (2nd) ",
  "sn23.13:0.3": "Impermanence ",
  "sn23.13:1.1": "At Sāvatthī. ",
  "sn23.13:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.13:1.3": "“Sir, they speak of ‘impermanence’. ",
  "sn23.13:1.4": "What has impermanent nature?” ",
  "sn23.13:1.5": "“Rādha, form, feeling, perception, choices, and consciousness are impermanent. ",
  "sn23.13:1.6": "Seeing this … ",
  "sn23.13:1.7": "They understand: ‘… there is nothing further for this place.’” ",
  "sn23.14:0.1": "Linked Discourses 23.14 ",
  "sn23.14:0.2": "2. About Māra (2nd) ",
  "sn23.14:0.3": "Liable to Impermanence ",
  "sn23.14:1.1": "At Sāvatthī. ",
  "sn23.14:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.14:1.3": "“Sir, they speak of having ‘impermanent nature’. ",
  "sn23.14:1.4": "What is of impermanent nature? ",
  "sn23.14:1.5": "“Rādha, form, feeling, perception, choices, and consciousness are of impermanent nature. ",
  "sn23.14:1.6": "Seeing this … ",
  "sn23.14:1.7": "They understand: ‘… there is nothing further for this place.’” ",
  "sn23.15:0.1": "Linked Discourses 23.15 ",
  "sn23.15:0.2": "2. About Māra (2nd) ",
  "sn23.15:0.3": "Suffering ",
  "sn23.15:1.1": "At Sāvatthī. ",
  "sn23.15:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.15:1.3": "“Sir, they speak of ‘suffering’. ",
  "sn23.15:1.4": "What is suffering?” ",
  "sn23.15:1.5": "“Rādha, form, feeling, perception, choices, and consciousness are suffering. ",
  "sn23.15:1.6": "Seeing this … ",
  "sn23.15:1.7": "They understand: ‘… there is nothing further for this place.’” ",
  "sn23.16:0.1": "Linked Discourses 23.16 ",
  "sn23.16:0.2": "2. About Māra (2nd) ",
  "sn23.16:0.3": "Liable to Suffering ",
  "sn23.16:1.1": "At Sāvatthī. ",
  "sn23.16:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.16:1.3": "“Sir, they speak of having ‘suffering nature’. ",
  "sn23.16:1.4": "What is of a nature to suffer?” ",
  "sn23.16:1.5": "“Rādha, form, feeling, perception, choices, and consciousness are of a nature to suffer. ",
  "sn23.16:1.6": "Seeing this … ",
  "sn23.16:1.7": "They understand: ‘… there is nothing further for this place.’” ",
  "sn23.17:0.1": "Linked Discourses 23.17 ",
  "sn23.17:0.2": "2. About Māra (2nd) ",
  "sn23.17:0.3": "Not-Self ",
  "sn23.17:1.1": "At Sāvatthī. ",
  "sn23.17:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.17:1.3": "“Sir, they speak of ‘not-self’. ",
  "sn23.17:1.4": "What is not-self?” ",
  "sn23.17:1.5": "“Rādha, form, feeling, perception, choices, and consciousness are not-self. ",
  "sn23.17:1.6": "Seeing this … ",
  "sn23.17:1.7": "They understand: ‘… there is nothing further for this place.’” ",
  "sn23.18:0.1": "Linked Discourses 23.18 ",
  "sn23.18:0.2": "2. About Māra (2nd) ",
  "sn23.18:0.3": "Naturally Not-Self ",
  "sn23.18:1.1": "At Sāvatthī. ",
  "sn23.18:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.18:1.3": "“Sir, they speak of having ‘not-self nature’. ",
  "sn23.18:1.4": "What has a nature of not-self?” ",
  "sn23.18:1.5": "“Rādha, form, feeling, perception, choices, and consciousness have a nature of not-self. ",
  "sn23.18:1.6": "Seeing this … ",
  "sn23.18:1.7": "They understand: ‘… there is nothing further for this place.’” ",
  "sn23.19:0.1": "Linked Discourses 23.19 ",
  "sn23.19:0.2": "2. About Māra (2nd) ",
  "sn23.19:0.3": "Liable To End ",
  "sn23.19:1.1": "At Sāvatthī. ",
  "sn23.19:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.19:1.3": "“Sir, they speak of a ‘liability to end’. ",
  "sn23.19:1.4": "What has a liability to end?” ",
  "sn23.19:1.5": "“Rādha, form, feeling, perception, choices, and consciousness have a liability to end. ",
  "sn23.19:1.6": "Seeing this … ",
  "sn23.19:1.7": "They understand: ‘… there is nothing further for this place.’” ",
  "sn23.20:0.1": "Linked Discourses 23.20 ",
  "sn23.20:0.2": "2. About Māra (2nd) ",
  "sn23.20:0.3": "liable to fall ",
  "sn23.20:1.1": "At Sāvatthī. ",
  "sn23.20:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.20:1.3": "“Sir, they speak of a ‘liability to fall’. ",
  "sn23.20:1.4": "What has a liability to fall?” ",
  "sn23.20:1.5": "“Rādha, form, feeling, perception, choices, and consciousness have a liability to fall. ",
  "sn23.20:1.6": "Seeing this … ",
  "sn23.20:1.7": "They understand: ‘… there is nothing further for this place.’” ",
  "sn23.21:0.1": "Linked Discourses 23.21 ",
  "sn23.21:0.2": "2. About Māra (2nd) ",
  "sn23.21:0.3": "Liable To Originate ",
  "sn23.21:1.1": "At Sāvatthī. ",
  "sn23.21:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.21:1.3": "“Sir, they speak of a ‘liability to originate’. ",
  "sn23.21:1.4": "What has a liability to originate?” ",
  "sn23.21:1.5": "“Rādha, form, feeling, perception, choices, and consciousness have a liability to originate. ",
  "sn23.21:1.6": "Seeing this … ",
  "sn23.21:1.7": "They understand: ‘… there is nothing further for this place.’” ",
  "sn23.22:0.1": "Linked Discourses 23.22 ",
  "sn23.22:0.2": "2. About Māra (2nd) ",
  "sn23.22:0.3": "Liable To Cease ",
  "sn23.22:1.1": "At Sāvatthī. ",
  "sn23.22:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.22:1.3": "“Sir, they speak of a ‘liability to cease’. ",
  "sn23.22:1.4": "What has a liability to cease?” ",
  "sn23.22:1.5": "“Rādha, form, feeling, perception, choices, and consciousness have a liability to cease. ",
  "sn23.22:1.6": "Seeing this … ",
  "sn23.22:1.7": "They understand: ‘… there is nothing further for this place.’” ",
  "sn23.22:1.8": "",
  "sn23.22:1.9": "",
  "sn23.22:2.1": "",
  "sn23.22:2.2": "",
  "sn23.22:2.3": "",
  "sn23.22:2.4": "",
  "sn23.22:2.5": "",
  "sn23.23:0.1": "Linked Discourses 23.23–33 ",
  "sn23.23:0.2": "3. Appeals ",
  "sn23.23:0.3": "Eleven Discourses on Māra, Etc. ",
  "sn23.23:1.1": "At Sāvatthī. ",
  "sn23.23:1.2": "Seated to one side, Venerable Rādha said to the Buddha: ",
  "sn23.23:1.3": "“Sir, may the Buddha please teach me Dhamma in brief. When I’ve heard it, I’ll live alone, withdrawn, diligent, keen, and resolute.” ",
  "sn23.23:2.1": "“Rādha, you should give up any desire, any greed, any desire and greed for whatever is Māra. ",
  "sn23.23:2.2": "And what is Māra? ",
  "sn23.23:2.3": "Form is Māra. You should give up any desire, any greed, any desire and greed for it. ",
  "sn23.23:2.4": "Feeling … ",
  "sn23.23:2.5": "Perception … ",
  "sn23.23:2.6": "Choices … ",
  "sn23.23:2.7": "Consciousness is Māra. You should give up any desire, any greed, any desire and greed for it. ",
  "sn23.23:2.8": "You should give up any desire, any greed, any desire and greed for whatever is Māra.” ",
  "sn23.24:1.1": "“You should give up any desire, any greed, any desire and greed for whatever is of Māra nature …” ",
  "sn23.25:1.1": "“… impermanent …” ",
  "sn23.26:1.1": "“… of impermanent nature …” ",
  "sn23.27:1.1": "“… suffering …” ",
  "sn23.28:1.1": "“… of suffering nature …” ",
  "sn23.29:1.1": "“… not-self …” ",
  "sn23.30:1.1": "“… of not-self nature …” ",
  "sn23.31:1.1": "“… of a nature to end …” ",
  "sn23.32:1.1": "“… of a nature to fall …” ",
  "sn23.33:1.1": "“… of a nature to originate …” ",
  "sn23.34:0.1": "Linked Discourses 23.34 ",
  "sn23.34:0.2": "3. Appeals ",
  "sn23.34:0.3": "Liable To Cease ",
  "sn23.34:1.1": "At Sāvatthī. ",
  "sn23.34:1.2": "Venerable Rādha said to the Buddha: ",
  "sn23.34:1.3": "“Sir, may the Buddha please teach me Dhamma in brief. When I’ve heard it, I’ll live alone, withdrawn, diligent, keen, and resolute.” ",
  "sn23.34:2.1": "“Rādha, you should give up any desire, any greed, any desire and greed for whatever is of a nature to cease. ",
  "sn23.34:2.2": "And what is of a nature to cease? ",
  "sn23.34:2.3": "Form is of a nature to cease. You should give up any desire, any greed, any desire and greed for it. ",
  "sn23.34:2.4": "Feeling … ",
  "sn23.34:2.5": "Perception … ",
  "sn23.34:2.6": "Choices … ",
  "sn23.34:2.7": "Consciousness is of a nature to cease. You should give up any desire, any greed, any desire and greed for it. ",
  "sn23.34:2.8": "You should give up any desire, any greed, any desire and greed for whatever is of a nature to cease.” ",
  "sn23.34:2.9": "",
  "sn23.34:3.1": "",
  "sn23.34:3.2": "",
  "sn23.34:3.3": "",
  "sn23.34:3.4": "",
  "sn23.34:3.5": "",
  "sn23.35:0.1": "Linked Discourses 23.35 ",
  "sn23.35:0.2": "4. Sitting Close ",
  "sn23.35:0.3": "Eleven Discourses on Māra, Etc. ",
  "sn23.35:1.1": "At Sāvatthī. ",
  "sn23.35:1.2": "When Venerable Rādha was seated to one side, the Buddha said to him: ",
  "sn23.35:1.3": "“Rādha, you should give up any desire, any greed, any desire and greed for whatever is Māra. ",
  "sn23.35:1.4": "And what is Māra? ",
  "sn23.35:1.5": "Form is Māra. You should give up any desire, any greed, any desire and greed for it. … ",
  "sn23.35:1.6": "Consciousness is Māra. You should give up any desire, any greed, any desire and greed for it. ",
  "sn23.35:1.7": "You should give up any desire, any greed, any desire and greed for whatever is Māra.” ",
  "sn23.36:1.1": "“You should give up any desire, any greed, any desire and greed for whatever is subject to Māra …” ",
  "sn23.37:1.1": "“… impermanent …” ",
  "sn23.38:1.1": "“… liable to impermanence …” ",
  "sn23.39:1.1": "“… suffering …” ",
  "sn23.40:1.1": "“… liable to suffering …” ",
  "sn23.41:1.1": "“… not-self …” ",
  "sn23.42:1.1": "“… liable to not-self …” ",
  "sn23.43:1.1": "“… liable to end …” ",
  "sn23.44:1.1": "“… liable to fall …” ",
  "sn23.45:1.1": "“… liable to originate …” ",
  "sn23.46:0.1": "Linked Discourses 23.46 ",
  "sn23.46:0.2": "4. Sitting Close ",
  "sn23.46:0.3": "Liable To Cease ",
  "sn23.46:1.1": "At Sāvatthī. ",
  "sn23.46:1.2": "When Venerable Rādha was seated to one side, the Buddha said to him: ",
  "sn23.46:1.3": "“Rādha, you should give up any desire, any greed, any desire and greed for whatever is liable to cease. ",
  "sn23.46:1.4": "And what is liable to cease? ",
  "sn23.46:1.5": "Form is liable to cease. You should give up any desire, any greed, any desire and greed for it. ",
  "sn23.46:1.6": "Feeling … ",
  "sn23.46:1.7": "Perception … ",
  "sn23.46:1.8": "Choices … ",
  "sn23.46:1.9": "Consciousness is liable to cease. You should give up any desire, any greed, any desire and greed for it. ",
  "sn23.46:1.10": "You should give up any desire, any greed, any desire and greed for whatever is liable to cease.” ",
  "sn23.46:1.11": "",
  "sn23.46:2.1": "",
  "sn23.46:2.2": "",
  "sn23.46:2.3": "",
  "sn23.46:2.4": "",
  "sn23.46:2.5": "",
  "sn23.46:2.6": "",
  "sn23.46:2.7": "The Linked Discourses with Rādha are complete. "
}
window.BILARA["sn23_v1"]["en"]["sn23_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
