window.BILARA = window.BILARA || {};
window.BILARA["sn24_v1"] = window.BILARA["sn24_v1"] || {};
window.BILARA["sn24_v1"]["en"] = {
  "sn24.1:0.1": "Linked Discourses 24.1 ",
  "sn24.1:0.2": "1. Stream-Entry ",
  "sn24.1:0.3": "Winds ",
  "sn24.1:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove. ",
  "sn24.1:1.2": "The Buddha said this: ",
  "sn24.1:1.3": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.1:1.4": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’?” ",
  "sn24.1:2.1": "“Our teachings are rooted in the Buddha. He is our guide and our refuge. Sir, may the Buddha himself please clarify the meaning of this. The mendicants will listen and remember it.” ",
  "sn24.1:2.2": "“Well then, mendicants, listen and apply your mind well, I will speak.” ",
  "sn24.1:2.3": "“Yes, sir,” they replied. ",
  "sn24.1:2.4": "The Buddha said this: ",
  "sn24.1:3.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.1:3.2": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’ ",
  "sn24.1:3.3": "When feeling … ",
  "sn24.1:3.4": "perception … ",
  "sn24.1:3.5": "choices … ",
  "sn24.1:3.6": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.1:3.7": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’ ",
  "sn24.1:3.8": "What do you think, mendicants? ",
  "sn24.1:3.9": "Is form permanent or impermanent?” ",
  "sn24.1:3.10": "“Impermanent, sir.” ",
  "sn24.1:3.11": "“But if it’s impermanent, is it suffering or happiness?” ",
  "sn24.1:3.12": "“Suffering, sir.” ",
  "sn24.1:3.13": "“But by not grasping what’s impermanent, suffering, and perishable, would the view arise: ",
  "sn24.1:3.14": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar’?” ",
  "sn24.1:3.15": "“No, sir.” ",
  "sn24.1:4.1": "“Is feeling … ",
  "sn24.1:4.2": "perception … ",
  "sn24.1:4.3": "choices … ",
  "sn24.1:4.4": "consciousness permanent or impermanent?” ",
  "sn24.1:4.5": "“Impermanent, sir.” ",
  "sn24.1:4.6": "“But if it’s impermanent, is it suffering or happiness?” ",
  "sn24.1:4.7": "“Suffering, sir.” ",
  "sn24.1:4.8": "“But by not grasping what’s impermanent, suffering, and perishable, would the view arise: ",
  "sn24.1:4.9": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar’?” ",
  "sn24.1:4.10": "“No, sir.” ",
  "sn24.1:4.11": "“That which is seen, heard, thought, known, attained, sought, and explored by the mind: is that permanent or impermanent?” ",
  "sn24.1:4.12": "“Impermanent, sir.” ",
  "sn24.1:4.13": "“But if it’s impermanent, is it suffering or happiness?” ",
  "sn24.1:4.14": "“Suffering, sir.” ",
  "sn24.1:4.15": "“But by not grasping what’s impermanent, suffering, and perishable, would the view arise: ",
  "sn24.1:4.16": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar’?” ",
  "sn24.1:4.17": "“No, sir.” ",
  "sn24.1:5.1": "“When a noble disciple has given up doubt regarding these six grounds, and has given up doubt in suffering, its origin, its cessation, and the practice that leads to its cessation, ",
  "sn24.1:5.2": "they’re called a noble disciple who is a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn24.2:0.1": "Linked Discourses 24.2 ",
  "sn24.2:0.2": "1. Stream-Entry ",
  "sn24.2:0.3": "This Is Mine ",
  "sn24.2:1.1": "At Sāvatthī. ",
  "sn24.2:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.2:1.3": "‘This is mine, I am this, this is my self’?” ",
  "sn24.2:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.2:1.5": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.2:1.6": "‘This is mine, I am this, this is my self.’ ",
  "sn24.2:1.7": "When feeling … ",
  "sn24.2:1.8": "perception … ",
  "sn24.2:1.9": "choices … ",
  "sn24.2:1.10": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.2:1.11": "‘This is mine, I am this, this is my self.’ ",
  "sn24.2:2.1": "What do you think, mendicants? ",
  "sn24.2:2.2": "Is form permanent or impermanent?” ",
  "sn24.2:2.3": "“Impermanent, sir.” … ",
  "sn24.2:2.4": "“Is feeling … ",
  "sn24.2:2.5": "perception … ",
  "sn24.2:2.6": "choices … ",
  "sn24.2:2.7": "consciousness permanent or impermanent?” ",
  "sn24.2:2.8": "“Impermanent, sir.” … ",
  "sn24.2:2.9": "",
  "sn24.2:2.10": "",
  "sn24.2:2.11": "",
  "sn24.2:2.12": "“That which is seen, heard, thought, known, attained, sought, and explored by the mind: is that permanent or impermanent?” ",
  "sn24.2:2.13": "“Impermanent, sir.” ",
  "sn24.2:2.14": "“But if it’s impermanent, is it suffering or happiness?” ",
  "sn24.2:2.15": "“Suffering, sir.” ",
  "sn24.2:2.16": "“But by not grasping what’s impermanent, suffering, and perishable, would the view arise: ",
  "sn24.2:2.17": "‘This is mine, I am this, this is my self’?” ",
  "sn24.2:2.18": "“No, sir.” ",
  "sn24.2:3.1": "“When a noble disciple has given up doubt regarding these six grounds, and has given up doubt in suffering, its origin, its cessation, and the practice that leads to its cessation, ",
  "sn24.2:3.2": "they’re called a noble disciple who is a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn24.3:0.1": "Linked Discourses 24.3 ",
  "sn24.3:0.2": "1. Stream-Entry ",
  "sn24.3:0.3": "This Is My Self ",
  "sn24.3:1.1": "At Sāvatthī. ",
  "sn24.3:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.3:1.3": "‘The self and the cosmos are one and the same. After death I will be that, permanent, everlasting, eternal, and imperishable’?” ",
  "sn24.3:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.3:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.3:2.2": "‘The self and the cosmos are one and the same. After death I will be that, permanent, everlasting, eternal, and imperishable.’ ",
  "sn24.3:2.3": "When feeling … ",
  "sn24.3:2.4": "perception … ",
  "sn24.3:2.5": "choices … ",
  "sn24.3:2.6": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.3:2.7": "‘The self and the cosmos are one and the same. After death I will be that, permanent, everlasting, eternal, and imperishable.’ ",
  "sn24.3:3.1": "What do you think, mendicants? ",
  "sn24.3:3.2": "Is form permanent or impermanent?” ",
  "sn24.3:3.3": "“Impermanent, sir.” … ",
  "sn24.3:3.4": "",
  "sn24.3:3.5": "",
  "sn24.3:3.6": "",
  "sn24.3:3.7": "",
  "sn24.3:3.8": "“Is feeling … ",
  "sn24.3:3.9": "perception … ",
  "sn24.3:3.10": "choices … ",
  "sn24.3:3.11": "consciousness permanent or impermanent?” ",
  "sn24.3:3.12": "“Impermanent, sir.” … ",
  "sn24.3:3.13": "",
  "sn24.3:3.14": "",
  "sn24.3:3.15": "",
  "sn24.3:3.16": "",
  "sn24.3:3.17": "“That which is seen, heard, thought, known, attained, sought, and explored by the mind: is that permanent or impermanent?” ",
  "sn24.3:3.18": "“Impermanent, sir.” … ",
  "sn24.3:3.19": "“But by not grasping what’s impermanent, suffering, and perishable, would such a view arise?” ",
  "sn24.3:3.20": "",
  "sn24.3:3.21": "“No, sir.” ",
  "sn24.3:4.1": "“When a noble disciple has given up doubt regarding these six grounds, and has given up doubt in suffering, its origin, its cessation, and the practice that leads to its cessation, ",
  "sn24.3:4.2": "they’re called a noble disciple who is a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn24.4:0.1": "Linked Discourses 24.4 ",
  "sn24.4:0.2": "1. Stream-Entry ",
  "sn24.4:0.3": "It Might Not Be Mine ",
  "sn24.4:1.1": "At Sāvatthī. ",
  "sn24.4:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.4:1.3": "‘I might not be, and it might not be mine. I will not be, and it will not be mine’?” ",
  "sn24.4:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.4:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.4:2.2": "‘I might not be, and it might not be mine. I will not be, and it will not be mine.’ ",
  "sn24.4:2.3": "When feeling … ",
  "sn24.4:2.4": "perception … ",
  "sn24.4:2.5": "choices … ",
  "sn24.4:2.6": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.4:2.7": "‘I might not be, and it might not be mine. I will not be, and it will not be mine.’ ",
  "sn24.4:3.1": "What do you think, mendicants? ",
  "sn24.4:3.2": "Is form permanent or impermanent?” ",
  "sn24.4:3.3": "“Impermanent, sir.” … ",
  "sn24.4:3.4": "",
  "sn24.4:3.5": "",
  "sn24.4:3.6": "",
  "sn24.4:3.7": "“Is feeling … ",
  "sn24.4:3.8": "perception … ",
  "sn24.4:3.9": "choices … ",
  "sn24.4:3.10": "consciousness permanent or impermanent?” ",
  "sn24.4:3.11": "“Impermanent, sir.” … ",
  "sn24.4:3.12": "",
  "sn24.4:3.13": "",
  "sn24.4:3.14": "",
  "sn24.4:3.15": "“That which is seen, heard, thought, known, attained, sought, and explored by the mind: is that permanent or impermanent?” ",
  "sn24.4:3.16": "“Impermanent, sir.” … ",
  "sn24.4:3.17": "“But by not grasping what’s impermanent, suffering, and perishable, would such a view arise?” ",
  "sn24.4:3.18": "",
  "sn24.4:3.19": "“No, sir.” ",
  "sn24.4:4.1": "“When a noble disciple has given up doubt regarding these six grounds, and has given up doubt in suffering, its origin, its cessation, and the practice that leads to its cessation, ",
  "sn24.4:4.2": "they’re called a noble disciple who is a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn24.5:0.1": "Linked Discourses 24.5 ",
  "sn24.5:0.2": "1. Stream-Entry ",
  "sn24.5:0.3": "There’s No Meaning in Giving ",
  "sn24.5:1.1": "At Sāvatthī. ",
  "sn24.5:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.5:1.3": "‘There’s no meaning in giving, sacrifice, or offerings. There’s no fruit or result of good and bad deeds. There’s no afterlife. There’s no such thing as mother and father, or beings that are reborn spontaneously. And there’s no ascetic or brahmin who is rightly comported and rightly practiced, and who describes the afterlife after realizing it with their own insight. ",
  "sn24.5:1.4": "This person is made up of the four principal states. When they die, the earth in their body progresses and proceeds to the substance of earth. The water in their body progresses and proceeds to the substance of water. The fire in their body progresses and proceeds to the substance of fire. The air in their body progresses and proceeds to the substance of air. ",
  "sn24.5:1.5": "The faculties are transferred to space. ",
  "sn24.5:1.6": "Four men with a bier carry away the corpse. ",
  "sn24.5:1.7": "Their footprints show the way to the cremation ground. ",
  "sn24.5:1.8": "The bones become bleached. ",
  "sn24.5:1.9": "Offerings dedicated to the gods end in ashes. ",
  "sn24.5:1.10": "Giving is a doctrine of morons. ",
  "sn24.5:1.11": "When anyone affirms a positive teaching it’s just baseless, false nonsense. ",
  "sn24.5:1.12": "Both the foolish and the astute are annihilated and destroyed when their body breaks up, and don’t exist after death’?” ",
  "sn24.5:1.13": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.5:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.5:2.2": "‘There’s no meaning in giving, sacrifice, or offerings. … ",
  "sn24.5:2.3": "Both the foolish and the astute are annihilated and destroyed when their body breaks up, and don’t exist after death.’ ",
  "sn24.5:2.4": "When feeling … ",
  "sn24.5:2.5": "perception … ",
  "sn24.5:2.6": "choices … ",
  "sn24.5:2.7": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.5:2.8": "‘There’s no meaning in giving, sacrifice, or offerings. … ",
  "sn24.5:2.9": "Both the foolish and the astute are annihilated and destroyed when their body breaks up, and don’t exist after death.’ ",
  "sn24.5:3.1": "What do you think, mendicants? ",
  "sn24.5:3.2": "Is form permanent or impermanent?” ",
  "sn24.5:3.3": "“Impermanent, sir.” … ",
  "sn24.5:3.4": "",
  "sn24.5:3.5": "",
  "sn24.5:3.6": "",
  "sn24.5:3.7": "",
  "sn24.5:3.8": "“Is feeling … ",
  "sn24.5:3.9": "perception … ",
  "sn24.5:3.10": "choices … ",
  "sn24.5:3.11": "consciousness permanent or impermanent?” ",
  "sn24.5:3.12": "“Impermanent, sir.” … ",
  "sn24.5:3.13": "",
  "sn24.5:3.14": "",
  "sn24.5:3.15": "",
  "sn24.5:3.16": "",
  "sn24.5:3.17": "“That which is seen, heard, thought, known, attained, sought, and explored by the mind: is that permanent or impermanent?” ",
  "sn24.5:3.18": "“Impermanent, sir.” … ",
  "sn24.5:3.19": "“But by not grasping what’s impermanent, suffering, and perishable, would such a view arise?” ",
  "sn24.5:3.20": "",
  "sn24.5:3.21": "",
  "sn24.5:3.22": "",
  "sn24.5:3.23": "“No, sir.” ",
  "sn24.5:4.1": "“When a noble disciple has given up doubt regarding these six grounds, and has given up doubt in suffering, its origin, its cessation, and the practice that leads to its cessation, ",
  "sn24.5:4.2": "they’re called a noble disciple who is a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn24.6:0.1": "Linked Discourses 24.6 ",
  "sn24.6:0.2": "1. Stream-Entry ",
  "sn24.6:0.3": "Acting ",
  "sn24.6:1.1": "At Sāvatthī. ",
  "sn24.6:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.6:1.3": "‘The one who acts does nothing wrong when they punish, mutilate, torture, aggrieve, oppress, intimidate, or when they encourage others to do the same. Nothing bad is done when they kill, steal, break into houses, plunder wealth, steal from isolated buildings, commit highway robbery, commit adultery, and lie. ",
  "sn24.6:1.4": "If you were to reduce all the living creatures of this earth to one heap and mass of flesh with a razor-edged chakram, no evil comes of that, and no outcome of evil. ",
  "sn24.6:1.5": "If you were to go along the south bank of the Ganges killing, mutilating, and torturing, and encouraging others to do the same, no evil comes of that, and no outcome of evil. ",
  "sn24.6:1.6": "If you were to go along the north bank of the Ganges giving and sacrificing and encouraging others to do the same, no merit comes of that, and no outcome of merit. ",
  "sn24.6:1.7": "In giving, self-control, restraint, and truthfulness there is no merit or outcome of merit’?” ",
  "sn24.6:1.8": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.6:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.6:2.2": "‘The one who acts does nothing wrong … ",
  "sn24.6:2.3": "there is no merit or outcome of merit.’ ",
  "sn24.6:2.4": "When feeling … ",
  "sn24.6:2.5": "perception … ",
  "sn24.6:2.6": "choices … ",
  "sn24.6:2.7": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.6:2.8": "‘The one who acts does nothing wrong … ",
  "sn24.6:2.9": "there is no merit or outcome of merit.’ ",
  "sn24.6:3.1": "What do you think, mendicants? ",
  "sn24.6:3.2": "Is form permanent or impermanent?” ",
  "sn24.6:3.3": "“Impermanent, sir.” … ",
  "sn24.6:3.4": "",
  "sn24.6:3.5": "",
  "sn24.6:3.6": "",
  "sn24.6:3.7": "",
  "sn24.6:3.8": "“Is feeling … ",
  "sn24.6:3.9": "perception … ",
  "sn24.6:3.10": "choices … ",
  "sn24.6:3.11": "consciousness permanent or impermanent?” ",
  "sn24.6:3.12": "“Impermanent, sir.” … ",
  "sn24.6:3.13": "",
  "sn24.6:3.14": "",
  "sn24.6:3.15": "",
  "sn24.6:3.16": "",
  "sn24.6:3.17": "“That which is seen, heard, thought, known, attained, sought, and explored by the mind: is that permanent or impermanent?” ",
  "sn24.6:3.18": "“Impermanent, sir.” … ",
  "sn24.6:3.19": "“But by not grasping what’s impermanent, suffering, and perishable, would such a view arise?” ",
  "sn24.6:3.20": "",
  "sn24.6:3.21": "",
  "sn24.6:3.22": "“No, sir.” ",
  "sn24.6:4.1": "“When a noble disciple has given up doubt regarding these six grounds, and has given up doubt in suffering, its origin, its cessation, and the practice that leads to its cessation, ",
  "sn24.6:4.2": "they’re called a noble disciple who is a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn24.7:0.1": "Linked Discourses 24.7 ",
  "sn24.7:0.2": "1. Stream-Entry ",
  "sn24.7:0.3": "Cause ",
  "sn24.7:1.1": "At Sāvatthī. ",
  "sn24.7:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.7:1.3": "‘There is no cause or reason for the corruption of sentient beings. ",
  "sn24.7:1.4": "Sentient beings are corrupted without cause or reason. ",
  "sn24.7:1.5": "There’s no cause or reason for the purification of sentient beings. ",
  "sn24.7:1.6": "Sentient beings are purified without cause or reason. ",
  "sn24.7:1.7": "There is no power, no energy, no human strength or vigor. ",
  "sn24.7:1.8": "All sentient beings, all living creatures, all beings, all souls lack control, power, and energy. Molded by destiny, circumstance, and nature, they experience pleasure and pain in the six classes of rebirth’?” ",
  "sn24.7:1.9": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.7:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.7:2.2": "‘There is no cause or reason … ",
  "sn24.7:2.3": "they experience pleasure and pain in the six classes of rebirth.’ ",
  "sn24.7:2.4": "When feeling … ",
  "sn24.7:2.5": "perception … ",
  "sn24.7:2.6": "choices … ",
  "sn24.7:2.7": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.7:2.8": "‘There is no cause or reason … ",
  "sn24.7:2.9": "they experience pleasure and pain in the six classes of rebirth.’ ",
  "sn24.7:3.1": "What do you think, mendicants? ",
  "sn24.7:3.2": "Is form permanent or impermanent?” ",
  "sn24.7:3.3": "“Impermanent, sir.” … ",
  "sn24.7:3.4": "",
  "sn24.7:3.5": "",
  "sn24.7:3.6": "",
  "sn24.7:3.7": "",
  "sn24.7:3.8": "“Is feeling … ",
  "sn24.7:3.9": "perception … ",
  "sn24.7:3.10": "choices … ",
  "sn24.7:3.11": "consciousness permanent or impermanent?” ",
  "sn24.7:3.12": "“Impermanent, sir.” … ",
  "sn24.7:3.13": "",
  "sn24.7:3.14": "",
  "sn24.7:3.15": "",
  "sn24.7:3.16": "",
  "sn24.7:3.17": "“That which is seen, heard, thought, known, attained, sought, and explored by the mind: is that permanent or impermanent?” ",
  "sn24.7:3.18": "“Impermanent, sir.” … ",
  "sn24.7:3.19": "“But by not grasping what’s impermanent, suffering, and perishable, would such a view arise?” ",
  "sn24.7:3.20": "",
  "sn24.7:3.21": "",
  "sn24.7:3.22": "“No, sir.” ",
  "sn24.7:4.1": "“When a noble disciple has given up doubt regarding these six grounds, and has given up doubt in suffering, its origin, its cessation, and the practice that leads to its cessation, ",
  "sn24.7:4.2": "they’re called a noble disciple who is a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn24.8:0.1": "Linked Discourses 24.8 ",
  "sn24.8:0.2": "1. Stream-Entry ",
  "sn24.8:0.3": "The Extensive View ",
  "sn24.8:1.1": "At Sāvatthī. ",
  "sn24.8:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.8:1.3": "‘There are these seven substances that are not made, not derived, not created, without a creator, barren, steady as a mountain peak, standing firm like a pillar. ",
  "sn24.8:1.4": "They don’t move or deteriorate or obstruct each other. They’re unable to cause pleasure, pain, or both pleasure and pain to each other. ",
  "sn24.8:1.5": "What seven? ",
  "sn24.8:1.6": "The substances of earth, water, fire, air; pleasure, pain, and the soul is the seventh. ",
  "sn24.8:1.7": "These seven substances are not made, not derived, not created, without a creator, barren, steady as a mountain peak, standing firm like a pillar. ",
  "sn24.8:1.8": "They don’t move or deteriorate or obstruct each other. They’re unable to cause pleasure, pain, or both pleasure and pain to each other. ",
  "sn24.8:1.9": "If you chop off someone’s head with a sharp sword, you don’t take anyone’s life. ",
  "sn24.8:1.10": "The sword simply passes through the gap between the seven substances. ",
  "sn24.8:1.11": "There are 1.4 million main wombs, and 6,000, and 600; 500 deeds, and five, and three; deeds and half-deeds; 62 paths of practice, 62 sub-eons, six classes of rebirth, and eight stages in a person’s life; 4,900 Ājīvaka ascetics, 4,900 wanderers, and 4,900 dragon abodes; 2,000 lordships, 3,000 hells, and 36 realms of dusky sky; seven percipient embryos, seven non-percipient embryos, seven knotless embryos, seven gods, seven mental heavens, seven goblins, seven streams, seven castoff incarnations and 700 castoff incarnations, seven downfalls and 700 downfalls, seven dreams and 700 dreams, and 8.4 million great eonsthrough all of which the foolish and the astute transmigrate before making an end of suffering. ",
  "sn24.8:1.12": "And here there is no such thing as this: “By this precept or observance or fervent austerity or spiritual practice I shall force unripened deeds to bear their fruit, or eliminate old deeds by experiencing their results little by little”for that cannot be. ",
  "sn24.8:1.13": "Pleasure and pain are allotted. Transmigration lasts only for a limited period, so there’s no increase or decrease, no getting better or worse. ",
  "sn24.8:1.14": "It’s like how, when you toss a ball of string, it rolls away unraveling. ",
  "sn24.8:1.15": "In the same way, after transmigrating the foolish and the astute roll away unraveling as far as pleasure and pain extend’?” ",
  "sn24.8:1.16": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.8:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.8:2.2": "‘There are these seven substances that are not made … ",
  "sn24.8:2.3": "the foolish and the astute will make an end of suffering.’ ",
  "sn24.8:2.4": "When feeling … ",
  "sn24.8:2.5": "perception … ",
  "sn24.8:2.6": "choices … ",
  "sn24.8:2.7": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.8:2.8": "‘There are these seven substances that are not made … ",
  "sn24.8:2.9": "the foolish and the astute will make an end of suffering.’ ",
  "sn24.8:3.1": "What do you think, mendicants? ",
  "sn24.8:3.2": "Is form permanent or impermanent?” ",
  "sn24.8:3.3": "“Impermanent, sir.” … ",
  "sn24.8:3.4": "",
  "sn24.8:3.5": "",
  "sn24.8:3.6": "",
  "sn24.8:3.7": "",
  "sn24.8:3.8": "“That which is seen, heard, thought, known, attained, sought, and explored by the mind: is that permanent or impermanent?” ",
  "sn24.8:3.9": "“Impermanent, sir.” … ",
  "sn24.8:3.10": "“But by not grasping what’s impermanent, suffering, and perishable, would such a view arise?” ",
  "sn24.8:3.11": "",
  "sn24.8:3.12": "",
  "sn24.8:3.13": "“No, sir.” ",
  "sn24.8:4.1": "“When a noble disciple has given up doubt regarding these six grounds, and has given up doubt in suffering, its origin, its cessation, and the practice that leads to its cessation, ",
  "sn24.8:4.2": "they’re called a noble disciple who is a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn24.9:0.1": "Linked Discourses 24.9 ",
  "sn24.9:0.2": "1. Stream-Entry ",
  "sn24.9:0.3": "The Cosmos is Eternal ",
  "sn24.9:1.1": "At Sāvatthī. ",
  "sn24.9:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.9:1.3": "‘The cosmos is eternal’?” ",
  "sn24.9:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.9:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.9:2.2": "‘The cosmos is eternal.’ ",
  "sn24.9:2.3": "When feeling … perception … ",
  "sn24.9:2.4": "choices … ",
  "sn24.9:2.5": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.9:2.6": "‘The cosmos is eternal.’ ",
  "sn24.9:3.1": "What do you think, mendicants? ",
  "sn24.9:3.2": "Is form permanent or impermanent?” ",
  "sn24.9:3.3": "“Impermanent, sir.” … ",
  "sn24.9:3.4": "",
  "sn24.9:3.5": "",
  "sn24.9:3.6": "",
  "sn24.9:3.7": "",
  "sn24.9:3.8": "",
  "sn24.9:3.9": "",
  "sn24.9:3.10": "",
  "sn24.9:3.11": "",
  "sn24.9:3.12": "",
  "sn24.9:3.13": "",
  "sn24.9:3.14": "",
  "sn24.9:3.15": "",
  "sn24.9:3.16": "",
  "sn24.9:3.17": "",
  "sn24.9:3.18": "",
  "sn24.9:3.19": "“But by not grasping what’s impermanent, suffering, and perishable, would such a view arise?” ",
  "sn24.9:3.20": "",
  "sn24.9:3.21": "“No, sir.” ",
  "sn24.9:4.1": "“When a noble disciple has given up doubt regarding these six grounds, and has given up doubt in suffering, its origin, its cessation, and the practice that leads to its cessation, ",
  "sn24.9:4.2": "they’re called a noble disciple who is a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn24.10:0.1": "Linked Discourses 24.10 ",
  "sn24.10:0.2": "1. Stream-Entry ",
  "sn24.10:0.3": "The Cosmos Is Not Eternal ",
  "sn24.10:1.1": "At Sāvatthī. ",
  "sn24.10:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.10:1.3": "‘The cosmos is not eternal’?” ",
  "sn24.10:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.10:2.1": "“When form exists …” … ",
  "sn24.10:2.2": "",
  "sn24.10:2.3": "",
  "sn24.10:2.4": "",
  "sn24.10:2.5": "",
  "sn24.10:2.6": "",
  "sn24.10:2.7": "",
  "sn24.10:2.8": "",
  "sn24.10:2.9": "“But by not grasping what’s impermanent, suffering, and perishable, would such a view arise?” ",
  "sn24.10:2.10": "",
  "sn24.10:2.11": "“No, sir.” ",
  "sn24.10:3.1": "“When a noble disciple has given up doubt regarding these six grounds, and has given up doubt in suffering, its origin, its cessation, and the practice that leads to its cessation, ",
  "sn24.10:3.2": "they’re called a noble disciple who is a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn24.11:0.1": "Linked Discourses 24.11 ",
  "sn24.11:0.2": "1. Stream-Entry ",
  "sn24.11:0.3": "The Cosmos is Finite ",
  "sn24.11:1.1": "At Sāvatthī. ",
  "sn24.11:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.11:1.3": "‘The cosmos is finite’?” … ",
  "sn24.11:1.4": "",
  "sn24.11:1.5": "",
  "sn24.12:0.1": "Linked Discourses 24.12 ",
  "sn24.12:0.2": "1. Stream-Entry ",
  "sn24.12:0.3": "The Cosmos is Infinite ",
  "sn24.12:1.1": "At Sāvatthī. ",
  "sn24.12:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.12:1.3": "‘The cosmos is infinite’?” … ",
  "sn24.12:1.4": "",
  "sn24.12:1.5": "",
  "sn24.13:0.1": "Linked Discourses 24.13 ",
  "sn24.13:0.2": "1. Stream-Entry ",
  "sn24.13:0.3": "The Soul and the Body are One and the Same ",
  "sn24.13:1.1": "At Sāvatthī. ",
  "sn24.13:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.13:1.3": "‘The soul and the body are one and the same’?” … ",
  "sn24.13:1.4": "",
  "sn24.13:1.5": "",
  "sn24.14:0.1": "Linked Discourses 24.14 ",
  "sn24.14:0.2": "1. Stream-Entry ",
  "sn24.14:0.3": "The soul is one thing, the body another ",
  "sn24.14:1.1": "At Sāvatthī. ",
  "sn24.14:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.14:1.3": "‘The soul is one thing, the body another’?” … ",
  "sn24.14:1.4": "",
  "sn24.14:1.5": "",
  "sn24.15:0.1": "Linked Discourses 24.15 ",
  "sn24.15:0.2": "1. Stream-Entry ",
  "sn24.15:0.3": "A Realized One Still Exists ",
  "sn24.15:1.1": "At Sāvatthī. ",
  "sn24.15:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.15:1.3": "‘A realized one still exists after death’?” … ",
  "sn24.15:1.4": "",
  "sn24.15:1.5": "",
  "sn24.16:0.1": "Linked Discourses 24.16 ",
  "sn24.16:0.2": "1. Stream-Entry ",
  "sn24.16:0.3": "A Realized One No Longer Exists ",
  "sn24.16:1.1": "At Sāvatthī. ",
  "sn24.16:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.16:1.3": "‘A realized one no longer exists after death’?” … ",
  "sn24.16:1.4": "",
  "sn24.16:1.5": "",
  "sn24.17:0.1": "Linked Discourses 24.17 ",
  "sn24.17:0.2": "1. Stream-Entry ",
  "sn24.17:0.3": "A Realized One Both Still Exists and No Longer Exists ",
  "sn24.17:1.1": "At Sāvatthī. ",
  "sn24.17:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.17:1.3": "‘A realized one both still exists and no longer exists after death’?” … ",
  "sn24.17:1.4": "",
  "sn24.17:1.5": "",
  "sn24.18:0.1": "Linked Discourses 24.18 ",
  "sn24.18:0.2": "1. Stream-Entry ",
  "sn24.18:0.3": "A Realized One Neither Still Exists Nor No Longer Exists ",
  "sn24.18:1.1": "At Sāvatthī. ",
  "sn24.18:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.18:1.3": "‘A realized one neither still exists nor no longer exists after death’?” ",
  "sn24.18:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.18:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.18:2.2": "‘A realized one neither still exists nor no longer exists after death’ … ",
  "sn24.18:3.1": "What do you think, mendicants? ",
  "sn24.18:3.2": "Is form permanent or impermanent?” ",
  "sn24.18:3.3": "“Impermanent, sir.” … ",
  "sn24.18:3.4": "“But by not grasping what’s impermanent, suffering, and perishable, would the view arise: ",
  "sn24.18:3.5": "‘A realized one neither still exists nor no longer exists after death’?” ",
  "sn24.18:3.6": "“No, sir.” ",
  "sn24.18:3.7": "“That which is seen, heard, thought, known, attained, sought, and explored by the mind: is that permanent or impermanent?” ",
  "sn24.18:3.8": "“Impermanent, sir.” ",
  "sn24.18:3.9": "“But if it’s impermanent, is it suffering or happiness?” ",
  "sn24.18:3.10": "“Suffering, sir.” ",
  "sn24.18:3.11": "“But by not grasping what’s impermanent, suffering, and perishable, would the view arise: ",
  "sn24.18:3.12": "‘A realized one neither still exists nor no longer exists after death’?” ",
  "sn24.18:3.13": "“No, sir.” ",
  "sn24.18:4.1": "“When a noble disciple has given up doubt regarding these six grounds, and has given up doubt in suffering, its origin, its cessation, and the practice that leads to its cessation, ",
  "sn24.18:4.2": "they’re called a noble disciple who is a stream-enterer, not liable to be reborn in the underworld, destined for awakening.” ",
  "sn24.18:4.3": "",
  "sn24.18:4.4": "",
  "sn24.18:4.5": "",
  "sn24.18:5.1": "",
  "sn24.18:5.2": "",
  "sn24.18:5.3": "",
  "sn24.18:5.4": "",
  "sn24.18:6.1": "",
  "sn24.18:6.2": "",
  "sn24.18:6.3": "",
  "sn24.18:6.4": "",
  "sn24.18:7.1": "",
  "sn24.18:7.2": "",
  "sn24.19:0.1": "Linked Discourses 24.19 ",
  "sn24.19:0.2": "2. The Second Round ",
  "sn24.19:0.3": "Winds ",
  "sn24.19:1.1": "At Sāvatthī. ",
  "sn24.19:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.19:1.3": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar’?” ",
  "sn24.19:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.19:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.19:2.2": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’ ",
  "sn24.19:2.3": "When feeling … ",
  "sn24.19:2.4": "perception … ",
  "sn24.19:2.5": "choices … ",
  "sn24.19:2.6": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.19:2.7": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’ ",
  "sn24.19:3.1": "What do you think, mendicants? ",
  "sn24.19:3.2": "Is form permanent or impermanent?” ",
  "sn24.19:3.3": "“Impermanent, sir.” … ",
  "sn24.19:3.4": "“But by not grasping what’s impermanent, suffering, and perishable, would the view arise: ",
  "sn24.19:3.5": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar’?” ",
  "sn24.19:3.6": "“No, sir.” ",
  "sn24.19:3.7": "“And so, when suffering exists, because of grasping suffering and insisting on suffering, the view arises: ",
  "sn24.19:3.8": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’ ",
  "sn24.19:3.9": "Is feeling … ",
  "sn24.19:3.10": "perception … ",
  "sn24.19:3.11": "choices … ",
  "sn24.19:3.12": "consciousness permanent or impermanent?” ",
  "sn24.19:3.13": "“Impermanent, sir.” … ",
  "sn24.19:3.14": "“But by not grasping what’s impermanent, suffering, and perishable, would such a view arise?” ",
  "sn24.19:3.15": "",
  "sn24.19:3.16": "“No, sir.” ",
  "sn24.19:3.17": "“And so, when suffering exists, because of grasping suffering and insisting on suffering, the view arises: ",
  "sn24.19:3.18": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’” ",
  "sn24.20-35:0.1": "Linked Discourses 24.20–35 ",
  "sn24.20-35:0.2": "2. The Second Round ",
  "sn24.20-35:0.3": "This Is Mine, Etc. ",
  "sn24.20-35:1.1": "(Tell these in full as in discourses 2 through 17 of the previous chapter.) ",
  "sn24.36:0.1": "Linked Discourses 24.36 ",
  "sn24.36:0.2": "2. The Second Round ",
  "sn24.36:0.3": "Neither Still Exists Nor No Longer Exists ",
  "sn24.36:1.1": "At Sāvatthī. ",
  "sn24.36:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.36:1.3": "‘A realized one neither still exists nor no longer exists after death’?” ",
  "sn24.36:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.36:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.36:2.2": "‘A realized one neither still exists nor no longer exists after death.’ ",
  "sn24.36:2.3": "When feeling … ",
  "sn24.36:2.4": "perception … ",
  "sn24.36:2.5": "choices … ",
  "sn24.36:2.6": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.36:2.7": "‘a realized one neither still exists nor no longer exists after death.’ ",
  "sn24.36:3.1": "What do you think, mendicants? ",
  "sn24.36:3.2": "Is form permanent or impermanent?” ",
  "sn24.36:3.3": "“Impermanent, sir.” … ",
  "sn24.36:3.4": "",
  "sn24.36:3.5": "",
  "sn24.36:3.6": "",
  "sn24.36:3.7": "“And so, when suffering exists, because of grasping suffering and insisting on suffering, the view arises: ",
  "sn24.36:3.8": "‘A realized one neither still exists nor no longer exists after death.’” … ",
  "sn24.36:3.9": "“Is feeling … ",
  "sn24.36:3.10": "perception … ",
  "sn24.36:3.11": "choices … ",
  "sn24.36:3.12": "consciousness permanent or impermanent?” ",
  "sn24.36:3.13": "“Impermanent, sir.” … ",
  "sn24.36:3.14": "“But by not grasping what’s impermanent, suffering, and perishable, would such a view arise?” ",
  "sn24.36:3.15": "",
  "sn24.36:3.16": "“No, sir.” ",
  "sn24.36:3.17": "“And so, when suffering exists, because of grasping suffering and insisting on suffering, the view arises: ",
  "sn24.36:3.18": "‘A realized one neither still exists nor no longer exists after death.’” ",
  "sn24.37:0.1": "Linked Discourses 24.37 ",
  "sn24.37:0.2": "2. The Second Round ",
  "sn24.37:0.3": "The Self is Formed ",
  "sn24.37:1.1": "At Sāvatthī. ",
  "sn24.37:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.37:1.3": "‘The self is formed and is free of disease after death’?” … ",
  "sn24.37:1.4": "",
  "sn24.37:2.1": "",
  "sn24.37:2.2": "",
  "sn24.37:2.3": "",
  "sn24.37:2.4": "",
  "sn24.37:2.5": "",
  "sn24.37:2.6": "",
  "sn24.37:2.7": "",
  "sn24.37:3.1": "",
  "sn24.37:3.2": "",
  "sn24.37:3.3": "",
  "sn24.37:3.4": "",
  "sn24.37:3.5": "",
  "sn24.37:3.6": "",
  "sn24.37:3.7": "",
  "sn24.37:3.8": "",
  "sn24.37:3.9": "",
  "sn24.37:3.10": "",
  "sn24.37:3.11": "",
  "sn24.38:0.1": "Linked Discourses 24.38 ",
  "sn24.38:0.2": "2. The Second Round ",
  "sn24.38:0.3": "The Self Is Formless ",
  "sn24.38:1.1": "At Sāvatthī. ",
  "sn24.38:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.38:1.3": "‘The self is formless and healthy after death’?” … ",
  "sn24.38:1.4": "",
  "sn24.39:0.1": "Linked Discourses 24.39 ",
  "sn24.39:0.2": "2. The Second Round ",
  "sn24.39:0.3": "The Self is Formed and Formless ",
  "sn24.39:1.1": "At Sāvatthī. ",
  "sn24.39:1.2": "“‘The self is formed and formless, and is healthy after death’?” … ",
  "sn24.40:0.1": "Linked Discourses 24.40 ",
  "sn24.40:0.2": "2. The Second Round ",
  "sn24.40:0.3": "The Self is Neither Formed Nor Formless ",
  "sn24.40:1.1": "“‘The self is neither formed nor formless, and is healthy after death’?” … ",
  "sn24.41:0.1": "Linked Discourses 24.41 ",
  "sn24.41:0.2": "2. The Second Round ",
  "sn24.41:0.3": "The Self Is Perfectly Happy ",
  "sn24.41:1.1": "“‘The self is perfectly happy, and is free of disease after death’?” … ",
  "sn24.42:0.1": "Linked Discourses 24.42 ",
  "sn24.42:0.2": "2. The Second Round ",
  "sn24.42:0.3": "Exclusively Suffering ",
  "sn24.42:1.1": "“‘The self is exclusively suffering, and is healthy after death’?” … ",
  "sn24.43:0.1": "Linked Discourses 24.43 ",
  "sn24.43:0.2": "2. The Second Round ",
  "sn24.43:0.3": "The Self Is Happy and Suffering ",
  "sn24.43:1.1": "“‘The self is happy and suffering, and is healthy after death’?” … ",
  "sn24.44:0.1": "Linked Discourses 24.44 ",
  "sn24.44:0.2": "2. The Second Round ",
  "sn24.44:0.3": "The Self Is Neither Happy Nor Suffering ",
  "sn24.44:1.1": "“‘The self is neither happy nor suffering, and is healthy after death’?” … ",
  "sn24.44:1.2": "",
  "sn24.44:2.1": "",
  "sn24.44:2.2": "",
  "sn24.44:2.3": "",
  "sn24.44:2.4": "",
  "sn24.44:2.5": "",
  "sn24.44:2.6": "",
  "sn24.44:2.7": "",
  "sn24.44:3.1": "",
  "sn24.44:3.2": "",
  "sn24.44:3.3": "",
  "sn24.44:3.4": "",
  "sn24.44:3.5": "",
  "sn24.44:3.6": "",
  "sn24.44:3.7": "",
  "sn24.44:3.8": "",
  "sn24.44:3.9": "",
  "sn24.44:3.10": "",
  "sn24.44:3.11": "",
  "sn24.44:3.12": "",
  "sn24.44:3.13": "",
  "sn24.44:3.14": "",
  "sn24.44:3.15": "",
  "sn24.44:3.16": "",
  "sn24.44:3.17": "",
  "sn24.44:3.18": "",
  "sn24.44:3.19": "",
  "sn24.44:4.1": "",
  "sn24.44:4.2": "",
  "sn24.44:4.3": "",
  "sn24.44:4.4": "",
  "sn24.44:5.1": "",
  "sn24.44:5.2": "",
  "sn24.44:5.3": "",
  "sn24.44:5.4": "",
  "sn24.44:6.1": "",
  "sn24.44:6.2": "",
  "sn24.44:6.3": "",
  "sn24.44:6.4": "",
  "sn24.44:7.1": "",
  "sn24.44:7.2": "",
  "sn24.44:7.3": "",
  "sn24.44:7.4": "",
  "sn24.44:7.5": "",
  "sn24.45:0.1": "Linked Discourses 24.45 ",
  "sn24.45:0.2": "3. The Third Round ",
  "sn24.45:0.3": "Winds ",
  "sn24.45:1.1": "At Sāvatthī. ",
  "sn24.45:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.45:1.3": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar’?” ",
  "sn24.45:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.45:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.45:2.2": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’ ",
  "sn24.45:2.3": "When feeling … ",
  "sn24.45:2.4": "perception … ",
  "sn24.45:2.5": "choices … ",
  "sn24.45:2.6": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.45:2.7": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’ ",
  "sn24.45:3.1": "What do you think, mendicants? ",
  "sn24.45:3.2": "Is form permanent or impermanent?” ",
  "sn24.45:3.3": "“Impermanent, sir.” … ",
  "sn24.45:3.4": "“But by not grasping what’s impermanent, suffering, and perishable, would the view arise: ",
  "sn24.45:3.5": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar’?” ",
  "sn24.45:3.6": "“No, sir.” ",
  "sn24.45:3.7": "“And so, what’s impermanent is suffering. ",
  "sn24.45:3.8": "When this exists, grasping at this, the view arises: ",
  "sn24.45:3.9": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’ ",
  "sn24.45:3.10": "Is feeling … ",
  "sn24.45:3.11": "perception … ",
  "sn24.45:3.12": "choices … ",
  "sn24.45:3.13": "consciousness permanent or impermanent?” ",
  "sn24.45:3.14": "“Impermanent, sir.” … ",
  "sn24.45:3.15": "",
  "sn24.45:3.16": "",
  "sn24.45:3.17": "",
  "sn24.45:3.18": "“And so, what’s impermanent is suffering. ",
  "sn24.45:3.19": "When this exists, grasping at this, the view arises: ",
  "sn24.45:3.20": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’” ",
  "sn24.46-69:0.1": "Linked Discourses 24.46–69 ",
  "sn24.46-69:0.2": "3. The Third Round ",
  "sn24.46-69:0.3": "This Is Mine, etc. ",
  "sn24.46-69:1.1": "(Tell in full as in discourses 20 through 43 of the second chapter.) ",
  "sn24.70:0.1": "Linked Discourses 24.70 ",
  "sn24.70:0.2": "3. The Third Round ",
  "sn24.70:0.3": "The Self Is Neither Happy Nor Suffering ",
  "sn24.70:1.1": "At Sāvatthī. ",
  "sn24.70:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.70:1.3": "‘The self is neither happy nor suffering, and healthy after death’?” ",
  "sn24.70:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.70:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.70:2.2": "‘The self is neither happy nor suffering, and is healthy after death.’ ",
  "sn24.70:2.3": "When feeling … ",
  "sn24.70:2.4": "perception … ",
  "sn24.70:2.5": "choices … ",
  "sn24.70:2.6": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.70:2.7": "‘The self is neither happy nor suffering, and healthy after death.’ ",
  "sn24.70:3.1": "What do you think, mendicants? ",
  "sn24.70:3.2": "Is form permanent or impermanent?” ",
  "sn24.70:3.3": "“Impermanent, sir.” … ",
  "sn24.70:3.4": "",
  "sn24.70:3.5": "",
  "sn24.70:3.6": "",
  "sn24.70:3.7": "“And so, what’s impermanent is suffering. ",
  "sn24.70:3.8": "When this exists, grasping at this, the view arises: ",
  "sn24.70:3.9": "‘The self is neither happy nor suffering, and is healthy after death.’ ",
  "sn24.70:3.10": "Is feeling … ",
  "sn24.70:3.11": "perception … ",
  "sn24.70:3.12": "choices … ",
  "sn24.70:3.13": "consciousness permanent or impermanent?” ",
  "sn24.70:3.14": "“Impermanent, sir.” … ",
  "sn24.70:3.15": "“But by not grasping what’s impermanent, suffering, and perishable, would such a view arise?” ",
  "sn24.70:3.16": "",
  "sn24.70:3.17": "“No, sir.” ",
  "sn24.70:3.18": "“And so, what’s impermanent is suffering. ",
  "sn24.70:3.19": "When this exists, grasping at this, the view arises: ",
  "sn24.70:3.20": "‘The self is neither happy nor suffering, and healthy after death.’” ",
  "sn24.70:3.21": "",
  "sn24.71:0.1": "Linked Discourses 24.71 ",
  "sn24.71:0.2": "4. The Fourth Round ",
  "sn24.71:0.3": "Winds ",
  "sn24.71:1.1": "At Sāvatthī. ",
  "sn24.71:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.71:1.3": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar’?” ",
  "sn24.71:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.71:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.71:2.2": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’ ",
  "sn24.71:2.3": "When feeling … ",
  "sn24.71:2.4": "perception … ",
  "sn24.71:2.5": "choices … ",
  "sn24.71:2.6": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.71:2.7": "‘Winds don’t blow; rivers don’t flow; pregnant women don’t give birth; the moon and stars neither rise nor set, but stand firm like a pillar.’ ",
  "sn24.71:2.8": "What do you think, mendicants? ",
  "sn24.71:2.9": "Is form permanent or impermanent?” ",
  "sn24.71:2.10": "“Impermanent, sir.” ",
  "sn24.71:2.11": "“But if it’s impermanent, is it suffering or happiness?” ",
  "sn24.71:2.12": "“Suffering, sir.” ",
  "sn24.71:2.13": "“But if it’s impermanent, suffering, and perishable, is it fit to be regarded thus: ",
  "sn24.71:2.14": "‘This is mine, I am this, this is my self’?” ",
  "sn24.71:2.15": "“No, sir.” ",
  "sn24.71:2.16": "“Is feeling … ",
  "sn24.71:2.17": "perception … ",
  "sn24.71:2.18": "choices … ",
  "sn24.71:2.19": "consciousness permanent or impermanent?” ",
  "sn24.71:2.20": "“Impermanent, sir.” ",
  "sn24.71:2.21": "“But if it’s impermanent, is it suffering or happiness?” ",
  "sn24.71:2.22": "“Suffering, sir.” ",
  "sn24.71:2.23": "“But if it’s impermanent, suffering, and perishable, is it fit to be regarded thus: ",
  "sn24.71:2.24": "‘This is mine, I am this, this is my self’?” ",
  "sn24.71:2.25": "“No, sir.” ",
  "sn24.71:3.1": "“So you should truly see any kind of form at allpast, future, or present; internal or external; solid or subtle; inferior or superior; far or near: *all* formwith right understanding: ‘This is not mine, I am not this, this is not my self.’ ",
  "sn24.71:3.2": "You should truly see any kind of feeling … ",
  "sn24.71:3.3": "perception … ",
  "sn24.71:3.4": "choices … ",
  "sn24.71:3.5": "consciousness at allpast, future, or present; internal or external; solid or subtle; inferior or superior; far or near: *all* consciousnesswith right understanding: ‘This is not mine, I am not this, this is not my self.’ ",
  "sn24.71:4.1": "Seeing this … ",
  "sn24.71:4.2": "They understand: ‘… there is nothing further for this place.’” ",
  "sn24.72-95:0.1": "Linked Discourses 24.72–95 ",
  "sn24.72-95:0.2": "4. The Fourth Round ",
  "sn24.72-95:0.3": "This Is Mine, Etc. ",
  "sn24.72-95:1.1": "(Tell in full as in the 24 discourses of the second chapter.) ",
  "sn24.96:0.1": "Linked Discourses 24.96 ",
  "sn24.96:0.2": "4. The Fourth Round ",
  "sn24.96:0.3": "The Self Is Neither Happy Nor Suffering ",
  "sn24.96:1.1": "At Sāvatthī. ",
  "sn24.96:1.2": "“Mendicants, when what exists, because of grasping what and insisting on what, does the view arise: ",
  "sn24.96:1.3": "‘The self is neither happy nor suffering, and is healthy after death’?” ",
  "sn24.96:1.4": "“Our teachings are rooted in the Buddha. …” ",
  "sn24.96:2.1": "“When form exists, because of grasping form and insisting on form, the view arises: ",
  "sn24.96:2.2": "‘The self is neither happy nor suffering, and healthy after death.’ ",
  "sn24.96:2.3": "When feeling … ",
  "sn24.96:2.4": "perception … ",
  "sn24.96:2.5": "choices … ",
  "sn24.96:2.6": "consciousness exists, because of grasping consciousness and insisting on consciousness, the view arises: ",
  "sn24.96:2.7": "‘The self is neither happy nor suffering, and is healthy after death.’ ",
  "sn24.96:3.1": "What do you think, mendicants? ",
  "sn24.96:3.2": "Is form permanent or impermanent?” ",
  "sn24.96:3.3": "“Impermanent, sir.” ",
  "sn24.96:3.4": "“But if it’s impermanent, is it suffering or happiness?” ",
  "sn24.96:3.5": "“Suffering, sir.” ",
  "sn24.96:3.6": "“But if it’s impermanent, suffering, and perishable, is it fit to be regarded thus: ",
  "sn24.96:3.7": "‘This is mine, I am this, this is my self’?” ",
  "sn24.96:3.8": "“No, sir.” ",
  "sn24.96:3.9": "“Is feeling … ",
  "sn24.96:3.10": "perception … ",
  "sn24.96:3.11": "choices … ",
  "sn24.96:3.12": "consciousness permanent or impermanent?” ",
  "sn24.96:3.13": "“Impermanent, sir.” ",
  "sn24.96:3.14": "“But if it’s impermanent, is it suffering or happiness?” ",
  "sn24.96:3.15": "“Suffering, sir.” ",
  "sn24.96:3.16": "“But if it’s impermanent, suffering, and perishable, is it fit to be regarded thus: ",
  "sn24.96:3.17": "‘This is mine, I am this, this is my self’?” ",
  "sn24.96:3.18": "“No, sir.” ",
  "sn24.96:4.1": "“So you should truly see any kind of form at allpast, future, or present; internal or external; solid or subtle; inferior or superior; far or near: *all* formwith right understanding: ‘This is not mine, I am not this, this is not my self.’ ",
  "sn24.96:4.2": "You should truly see any kind of feeling … ",
  "sn24.96:4.3": "perception … ",
  "sn24.96:4.4": "choices … ",
  "sn24.96:4.5": "consciousness at allpast, future, or present; internal or external; solid or subtle; inferior or superior; far or near: *all* consciousnesswith right understanding: ‘This is not mine, I am not this, this is not my self.’ ",
  "sn24.96:5.1": "Seeing this, a learned noble disciple grows disillusioned with form, feeling, perception, choices, and consciousness. ",
  "sn24.96:5.2": "Being disillusioned, desire fades away. When desire fades away they’re freed. When they’re freed, they know they’re freed. ",
  "sn24.96:5.3": "They understand: ‘Rebirth is ended, the spiritual journey has been completed, what had to be done has been done, there is nothing further for this place.’” ",
  "sn24.96:5.4": "",
  "sn24.96:6.1": "",
  "sn24.96:6.2": "",
  "sn24.96:6.3": "",
  "sn24.96:6.4": "",
  "sn24.96:6.5": "The Linked Discourses on views are complete. "
}
window.BILARA["sn24_v1"]["en"]["sn24_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
