window.BILARA = window.BILARA || {};
window.BILARA["sn40_v1"] = window.BILARA["sn40_v1"] || {};
window.BILARA["sn40_v1"]["en"] = {
  "sn40.1:0.1": "Linked Discourses 40.1 ",
  "sn40.1:0.2": "1. By Moggallāna ",
  "sn40.1:0.3": "A Question About the First Absorption ",
  "sn40.1:1.1": "At one time Venerable Mahāmoggallāna was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn40.1:1.2": "There Venerable Mahāmoggallāna addressed the mendicants: ",
  "sn40.1:1.3": "“Reverends, mendicants!” ",
  "sn40.1:1.4": "“Reverend,” they replied. ",
  "sn40.1:1.5": "Venerable Mahāmoggallāna said this: ",
  "sn40.1:2.1": "“Just now, reverends, as I was in private retreat this thought came to mind: ",
  "sn40.1:2.2": "‘They speak of this thing called the “first absorption”. ",
  "sn40.1:2.3": "What is the first absorption?’ ",
  "sn40.1:2.4": "It occurred to me: ",
  "sn40.1:2.5": "‘It’s when a mendicant, quite secluded from sensual pleasures, secluded from unskillful qualities, enters and remains in the first absorption, which has the rapture and bliss born of seclusion, while placing the mind and keeping it connected. ",
  "sn40.1:2.6": "This is called the first absorption.’ ",
  "sn40.1:2.7": "And so … I was entering and remaining in the first absorption. ",
  "sn40.1:2.8": "While I was in that meditation, perception and focus accompanied by sensual pleasures beset me. ",
  "sn40.1:3.1": "Then the Buddha came up to me with his psychic power and said, ",
  "sn40.1:3.2": "‘Moggallāna, Moggallāna! ",
  "sn40.1:3.3": "Don’t neglect the first absorption, brahmin! Settle your mind in the first absorption; unify your mind and immerse it in the first absorption.’ ",
  "sn40.1:3.4": "And so, after some time … I entered and remained in the first absorption. ",
  "sn40.1:3.5": "So if anyone should be rightly called ",
  "sn40.1:3.6": "a disciple who attained to great direct knowledge with help from the Teacher, it’s me.” ",
  "sn40.1:3.7": "",
  "sn40.2:0.1": "Linked Discourses 40.2 ",
  "sn40.2:0.2": "1. By Moggallāna ",
  "sn40.2:0.3": "A Question About the Second Absorption ",
  "sn40.2:1.1": "“They speak of this thing called the ‘second absorption’. ",
  "sn40.2:1.2": "What is the second absorption? ",
  "sn40.2:1.3": "It occurred to me: ",
  "sn40.2:1.4": "‘As the placing of the mind and keeping it connected are stilled, a mendicant enters and remains in the second absorption, which has the rapture and bliss born of immersion, with internal clarity and mind at one, without placing the mind and keeping it connected. ",
  "sn40.2:1.5": "This is called the second absorption.’ ",
  "sn40.2:1.6": "And so … I was entering and remaining in the second absorption. ",
  "sn40.2:1.7": "While I was in that meditation, perception and focus accompanied by placing the mind beset me. ",
  "sn40.2:2.1": "Then the Buddha came up to me with his psychic power and said, ",
  "sn40.2:2.2": "‘Moggallāna, Moggallāna! ",
  "sn40.2:2.3": "Don’t neglect the second absorption, brahmin! Settle your mind in the second absorption; unify your mind and immerse it in the second absorption.’ ",
  "sn40.2:2.4": "And so, after some time … I entered and remained in the second absorption. ",
  "sn40.2:2.5": "So if anyone should be rightly called ",
  "sn40.2:2.6": "a disciple who attained to great direct knowledge with help from the Teacher, it’s me.” ",
  "sn40.2:2.7": "",
  "sn40.3:0.1": "Linked Discourses 40.3 ",
  "sn40.3:0.2": "1. By Moggallāna ",
  "sn40.3:0.3": "A Question About the Third Absorption ",
  "sn40.3:1.1": "“They speak of this thing called the ‘third absorption’. ",
  "sn40.3:1.2": "What is the third absorption? ",
  "sn40.3:1.3": "It occurred to me: ",
  "sn40.3:1.4": "‘With the fading away of rapture, a mendicant enters and remains in the third absorption, where they meditate with equanimity, mindful and aware, personally experiencing the bliss of which the noble ones declare, “Equanimous and mindful, one meditates in bliss.” ",
  "sn40.3:1.5": "This is called the third absorption.’ ",
  "sn40.3:1.6": "And so … I was entering and remaining in the third absorption. ",
  "sn40.3:1.7": "While I was in that meditation, perception and focus accompanied by rapture beset me. ",
  "sn40.3:2.1": "Then the Buddha came up to me with his psychic power and said, ",
  "sn40.3:2.2": "‘Moggallāna, Moggallāna! ",
  "sn40.3:2.3": "Don’t neglect the third absorption, brahmin! Settle your mind in the third absorption; unify your mind and immerse it in the third absorption.’ ",
  "sn40.3:2.4": "And so, after some time … I entered and remained in the third absorption. ",
  "sn40.3:2.5": "So if anyone should be rightly called a disciple who attained to great direct knowledge with help from the Teacher, it’s me.” ",
  "sn40.4:0.1": "Linked Discourses 40.4 ",
  "sn40.4:0.2": "1. By Moggallāna ",
  "sn40.4:0.3": "A Question About the Fourth Absorption ",
  "sn40.4:1.1": "“They speak of this thing called the ‘fourth absorption’. ",
  "sn40.4:1.2": "What is the fourth absorption? ",
  "sn40.4:1.3": "It occurred to me: ",
  "sn40.4:1.4": "‘It’s when, with the giving up of pleasure and pain and the disappearance of former happiness and sadness, a mendicant enters and remains in the fourth absorption, without pleasure or pain, with pure equanimity and mindfulness. ",
  "sn40.4:1.5": "This is called the fourth absorption.’ ",
  "sn40.4:1.6": "And so … I was entering and remaining in the fourth absorption. ",
  "sn40.4:1.7": "While I was in that meditation, perception and focus accompanied by pleasure beset me. ",
  "sn40.4:2.1": "Then the Buddha came up to me with his psychic power and said, ",
  "sn40.4:2.2": "‘Moggallāna, Moggallāna! ",
  "sn40.4:2.3": "Don’t neglect the fourth absorption, brahmin! Settle your mind in the fourth absorption; unify your mind and immerse it in the fourth absorption.’ ",
  "sn40.4:2.4": "And so, after some time … I entered and remained in the fourth absorption. ",
  "sn40.4:2.5": "So if anyone should be rightly called a disciple who attained to great direct knowledge with help from the Teacher, it’s me.” ",
  "sn40.5:0.1": "Linked Discourses 40.5 ",
  "sn40.5:0.2": "1. By Moggallāna ",
  "sn40.5:0.3": "A Question About the Dimension of Infinite Space ",
  "sn40.5:1.1": "“They speak of this thing called the ‘dimension of infinite space’. ",
  "sn40.5:1.2": "What is the dimension of infinite space? ",
  "sn40.5:1.3": "It occurred to me: ",
  "sn40.5:1.4": "‘It’s when a mendicantgoing totally beyond perceptions of form, with the disappearance of perceptions of impingement, not focusing on perceptions of diversityaware that “space is infinite”, enters and remains in the dimension of infinite space. ",
  "sn40.5:1.5": "This is called the dimension of infinite space.’ ",
  "sn40.5:1.6": "And so … I was entering and remaining in the dimension of infinite space. ",
  "sn40.5:1.7": "While I was in that meditation, perception and focus accompanied by forms beset me. ",
  "sn40.5:2.1": "Then the Buddha came up to me with his psychic power and said, ",
  "sn40.5:2.2": "‘Moggallāna, Moggallāna! ",
  "sn40.5:2.3": "Don’t neglect the dimension of infinite space, brahmin! Settle your mind in the dimension of infinite space; unify your mind and immerse it in the dimension of infinite space.’ ",
  "sn40.5:2.4": "And so, after some time … I entered and remained in the dimension of infinite space. ",
  "sn40.5:2.5": "So if anyone should be rightly called a disciple who attained to great direct knowledge with help from the Teacher, it’s me.” ",
  "sn40.6:0.1": "Linked Discourses 40.6 ",
  "sn40.6:0.2": "1. By Moggallāna ",
  "sn40.6:0.3": "A Question About the Dimension of Infinite Consciousness ",
  "sn40.6:1.1": "“They speak of this thing called the ‘dimension of infinite consciousness’. ",
  "sn40.6:1.2": "What is the dimension of infinite consciousness? ",
  "sn40.6:1.3": "It occurred to me: ",
  "sn40.6:1.4": "‘It’s when a mendicant, going totally beyond the dimension of infinite space, aware that “consciousness is infinite”, enters and remains in the dimension of infinite consciousness. ",
  "sn40.6:1.5": "This is called the dimension of infinite consciousness.’ ",
  "sn40.6:1.6": "And so … I was entering and remaining in the dimension of infinite consciousness. ",
  "sn40.6:1.7": "While I was in that meditation, perception and focus accompanied by the dimension of infinite space beset me. ",
  "sn40.6:2.1": "Then the Buddha came up to me with his psychic power and said, ",
  "sn40.6:2.2": "‘Moggallāna, Moggallāna! ",
  "sn40.6:2.3": "Don’t neglect the dimension of infinite consciousness, brahmin! Settle your mind in the dimension of infinite consciousness; unify your mind and immerse it in the dimension of infinite consciousness.’ ",
  "sn40.6:2.4": "And so, after some time … I entered and remained in the dimension of infinite consciousness. ",
  "sn40.6:2.5": "So if anyone should be rightly called a disciple who attained to great direct knowledge with help from the Teacher, it’s me.” ",
  "sn40.7:0.1": "Linked Discourses 40.7 ",
  "sn40.7:0.2": "1. By Moggallāna ",
  "sn40.7:0.3": "A Question About the Dimension of Nothingness ",
  "sn40.7:1.1": "“They speak of this thing called the ‘dimension of nothingness’. ",
  "sn40.7:1.2": "What is the dimension of nothingness? ",
  "sn40.7:1.3": "It occurred to me: ",
  "sn40.7:1.4": "‘It’s when a mendicant, going totally beyond the dimension of infinite consciousness, aware that “there is nothing at all”, enters and remains in the dimension of nothingness. ",
  "sn40.7:1.5": "This is called the dimension of nothingness.’ ",
  "sn40.7:1.6": "And so … I was entering and remaining in the dimension of nothingness. ",
  "sn40.7:1.7": "While I was in that meditation, perception and focus accompanied by the dimension of infinite consciousness beset me. ",
  "sn40.7:2.1": "Then the Buddha came up to me with his psychic power and said, ",
  "sn40.7:2.2": "‘Moggallāna, Moggallāna! ",
  "sn40.7:2.3": "Don’t neglect the dimension of nothingness, brahmin! Settle your mind in the dimension of nothingness; unify your mind and immerse it in the dimension of nothingness.’ ",
  "sn40.7:2.4": "And so, after some time … I entered and remained in the dimension of nothingness. ",
  "sn40.7:2.5": "So if anyone should be rightly called a disciple who attained to great direct knowledge with help from the Teacher, it’s me.” ",
  "sn40.8:0.1": "Linked Discourses 40.8 ",
  "sn40.8:0.2": "1. By Moggallāna ",
  "sn40.8:0.3": "A Question About the Dimension of Neither Perception Nor Non-Perception ",
  "sn40.8:1.1": "“They speak of this thing called the ‘dimension of neither perception nor non-perception’. ",
  "sn40.8:1.2": "What is the dimension of neither perception nor non-perception? ",
  "sn40.8:1.3": "It occurred to me: ",
  "sn40.8:1.4": "‘It’s when a mendicant, going totally beyond the dimension of nothingness, enters and remains in the dimension of neither perception nor non-perception. ",
  "sn40.8:1.5": "This is called the dimension of neither perception nor non-perception.’ ",
  "sn40.8:1.6": "And so … I was entering and remaining in the dimension of neither perception nor non-perception. ",
  "sn40.8:1.7": "While I was in that meditation, perception and focus accompanied by the dimension of nothingness beset me. ",
  "sn40.8:2.1": "Then the Buddha came up to me with his psychic power and said, ",
  "sn40.8:2.2": "‘Moggallāna, Moggallāna! ",
  "sn40.8:2.3": "Don’t neglect the dimension of neither perception nor non-perception, brahmin! Settle your mind in the dimension of neither perception nor non-perception; unify your mind and immerse it in the dimension of neither perception nor non-perception.’ ",
  "sn40.8:2.4": "And so, after some time … I entered and remained in the dimension of neither perception nor non-perception. ",
  "sn40.8:2.5": "So if anyone should be rightly called a disciple who attained to great direct knowledge with help from the Teacher, it’s me.” ",
  "sn40.9:0.1": "Linked Discourses 40.9 ",
  "sn40.9:0.2": "1. By Moggallāna ",
  "sn40.9:0.3": "A Question About the Signless ",
  "sn40.9:1.1": "“They speak of this thing called the ‘signless immersion of the heart’. ",
  "sn40.9:1.2": "What is the signless immersion of the heart? ",
  "sn40.9:1.3": "It occurred to me: ",
  "sn40.9:1.4": "‘It’s when a mendicant, not focusing on any signs, enters and remains in the signless immersion of the heart. ",
  "sn40.9:1.5": "This is called the signless immersion of the heart.’ ",
  "sn40.9:1.6": "And so … I was entering and remaining in the signless immersion of the heart. ",
  "sn40.9:1.7": "While I was in that meditation, my consciousness followed after signs. ",
  "sn40.9:2.1": "Then the Buddha came up to me with his psychic power and said, ",
  "sn40.9:2.2": "‘Moggallāna, Moggallāna! ",
  "sn40.9:2.3": "Don’t neglect the signless immersion of the heart, brahmin! Settle your mind in the signless immersion of the heart; unify your mind and immerse it in the signless immersion of the heart.’ ",
  "sn40.9:2.4": "And so, after some time … I entered and remained in the signless immersion of the heart. ",
  "sn40.9:2.5": "So if anyone should be rightly called ",
  "sn40.9:2.6": "a disciple who attained to great direct knowledge with help from the Teacher, it’s me.” ",
  "sn40.9:2.7": "",
  "sn40.10:0.1": "Linked Discourses 40.10 ",
  "sn40.10:0.2": "1. By Moggallāna ",
  "sn40.10:0.3": "With Sakka ",
  "sn40.10:1.1": "And then Venerable Mahāmoggallāna, as easily as a strong person would extend or contract their arm, vanished from Jeta’s Grove and reappeared among the gods of the thirty-three. ",
  "sn40.10:1.2": "Then Sakka, lord of gods, with five hundred deities came up to Mahāmoggallāna, bowed, and stood to one side. Mahāmoggallāna said to him: ",
  "sn40.10:2.1": "“Lord of gods, it’s good to go for refuge to the Buddha. ",
  "sn40.10:2.2": "It’s the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm. ",
  "sn40.10:2.3": "It’s good to go for refuge to the teaching. ",
  "sn40.10:2.4": "It’s the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm. ",
  "sn40.10:2.5": "It’s good to go for refuge to the Saṅgha. ",
  "sn40.10:2.6": "It’s the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm.” ",
  "sn40.10:3.1": "“My good Moggallāna, it’s good to go for refuge to the Buddha … ",
  "sn40.10:3.3": "the teaching … ",
  "sn40.10:3.5": "the Saṅgha. ",
  "sn40.10:3.6": "It’s the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm.” ",
  "sn40.10:4.1": "Then Sakka, lord of gods, with six hundred deities … ",
  "sn40.10:4.2": "Then Sakka, lord of gods, with seven hundred deities … ",
  "sn40.10:4.3": "Then Sakka, lord of gods, with eight hundred deities … ",
  "sn40.10:4.4": "Then Sakka, lord of gods, with eighty thousand deities … ",
  "sn40.10:7.1": "Then Sakka, lord of gods, with five hundred deities came up to Mahāmoggallāna, bowed, and stood to one side. Mahāmoggallāna said to him: ",
  "sn40.10:8.1": "“Lord of gods, it’s good to have experiential confidence in the Buddha: ",
  "sn40.10:8.2": "‘That Blessed One is perfected, a fully awakened Buddha, accomplished in knowledge and conduct, holy, knower of the world, supreme guide for those fit for training, teacher of gods and humans, awakened, blessed.’ ",
  "sn40.10:8.3": "It’s the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm. ",
  "sn40.10:9.1": "It’s good to have experiential confidence in the teaching: ",
  "sn40.10:9.2": "‘The teaching is well explained by the Buddhaapparent in the present life, immediately effective, inviting inspection, relevant, so that sensible people can know it for themselves.’ ",
  "sn40.10:9.3": "It’s the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm. ",
  "sn40.10:10.1": "It’s good to have experiential confidence in the Saṅgha: ",
  "sn40.10:10.2": "‘The Saṅgha of the Buddha’s disciples is practicing the way that’s good, direct, systematic, and proper. It consists of the four pairs, the eight individual persons. This is the Saṅgha of the Buddha’s disciples that is worthy of offerings dedicated to the gods, worthy of hospitality, worthy of a religious donation, worthy of greeting with joined palms, and is the supreme field of merit for the world.’ ",
  "sn40.10:10.3": "It’s the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm. ",
  "sn40.10:11.1": "It’s good to have the ethical conduct that’s loved by the noble ones, unbroken, impeccable, spotless, and unmarred, liberating, praised by sensible people, not mistaken, and leading to immersion. ",
  "sn40.10:11.2": "It’s the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm.” ",
  "sn40.10:12.1": "“My good Moggallāna, it’s good to have experiential confidence in the Buddha … ",
  "sn40.10:13.1": "the teaching … ",
  "sn40.10:14.1": "the Saṅgha … ",
  "sn40.10:15.1": "and to have the ethical conduct that’s loved by the noble ones … ",
  "sn40.10:15.2": "It’s the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm.” ",
  "sn40.10:16.1": "Then Sakka, lord of gods, with six hundred deities … ",
  "sn40.10:16.2": "Then Sakka, lord of gods, with seven hundred deities … ",
  "sn40.10:16.3": "Then Sakka, lord of gods, with eight hundred deities … ",
  "sn40.10:16.4": "Then Sakka, lord of gods, with eighty thousand deities … ",
  "sn40.10:25.1": "Then Sakka, lord of gods, with five hundred deities came up to Mahāmoggallāna, ",
  "sn40.10:25.2": "bowed, and stood to one side. Mahāmoggallāna said to him: ",
  "sn40.10:26.1": "“Lord of gods, it’s good to go for refuge to the Buddha. ",
  "sn40.10:26.2": "It’s the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm. ",
  "sn40.10:26.3": "They surpass other gods in ten respects: ",
  "sn40.10:26.4": "heavenly lifespan, beauty, happiness, glory, sovereignty, sights, sounds, smells, tastes, and touches. ",
  "sn40.10:27.1": "It’s good to go for refuge to the teaching … ",
  "sn40.10:28.1": "It’s good to go for refuge to the Saṅgha. ",
  "sn40.10:28.2": "It’s the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm. ",
  "sn40.10:28.3": "They surpass other gods in ten respects: ",
  "sn40.10:28.4": "heavenly lifespan, beauty, happiness, glory, sovereignty, sights, sounds, smells, tastes, and touches.” ",
  "sn40.10:29.1": "“My good Moggallāna, it’s good to go for refuge to the Buddha …” ",
  "sn40.10:32.1": "Then Sakka, lord of gods, with six hundred deities … ",
  "sn40.10:32.2": "Then Sakka, lord of gods, with seven hundred deities … ",
  "sn40.10:32.3": "Then Sakka, lord of gods, with eight hundred deities … ",
  "sn40.10:32.4": "Then Sakka, lord of gods, with eighty thousand deities … ",
  "sn40.10:37.1": "Then Sakka, lord of gods, with five hundred deities came up to Mahāmoggallāna, bowed, and stood to one side. Mahāmoggallāna said to him: ",
  "sn40.10:38.1": "“Lord of gods, it’s good to have experiential confidence in the Buddha: ",
  "sn40.10:38.2": "‘That Blessed One is perfected, a fully awakened Buddha … teacher of gods and humans, awakened, blessed.’ ",
  "sn40.10:38.3": "It’s the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm. ",
  "sn40.10:38.4": "They surpass other gods in ten respects: ",
  "sn40.10:38.5": "heavenly lifespan, beauty, happiness, glory, sovereignty, sights, sounds, smells, tastes, and touches. ",
  "sn40.10:39.1": "It’s good to have experiential confidence in the teaching … ",
  "sn40.10:40.1": "It’s good to have experiential confidence in the Saṅgha … ",
  "sn40.10:41.1": "It’s good to have the ethical conduct that’s loved by the noble ones …” ",
  "sn40.10:42.1": "“My good Moggallāna, it’s good to have experiential confidence in the Buddha …” ",
  "sn40.10:46.1": "Then Sakka, lord of gods, with six hundred deities … ",
  "sn40.10:46.2": "Then Sakka, lord of gods, with seven hundred deities … ",
  "sn40.10:46.3": "Then Sakka, lord of gods, with eight hundred deities … ",
  "sn40.10:46.4": "Then Sakka, lord of gods, with eighty thousand deities … ",
  "sn40.11:0.1": "Linked Discourses 40.11 ",
  "sn40.11:0.2": "1. By Moggallāna ",
  "sn40.11:0.3": "With Candana, Etc. ",
  "sn40.11:1.1": "Then the godling Candana … ",
  "sn40.11:2.1": "the godling Suyāma … ",
  "sn40.11:3.1": "the godling Santusita … ",
  "sn40.11:4.1": "the godling Sunimmita … ",
  "sn40.11:5.1": "the godling Vasavatti … ",
  "sn40.11:6.1": "(Tell in full  as in the Discourse With Sakka.) ",
  "sn40.11:6.2": "",
  "sn40.11:6.3": "",
  "sn40.11:7.1": "",
  "sn40.11:7.2": "",
  "sn40.11:7.3": "",
  "sn40.11:7.4": "",
  "sn40.11:7.5": "",
  "sn40.11:7.6": "",
  "sn40.11:7.7": "The Linked Discourses on Moggallāna are complete. "
}
window.BILARA["sn40_v1"]["en"]["sn40_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
