window.BILARA = window.BILARA || {};
window.BILARA["sn42_v1"] = window.BILARA["sn42_v1"] || {};
window.BILARA["sn42_v1"]["en"] = {
  "sn42.1:0.1": "Linked Discourses 42.1 ",
  "sn42.1:0.2": "1. Chiefs ",
  "sn42.1:0.3": "Fury ",
  "sn42.1:1.1": "At Sāvatthī. ",
  "sn42.1:1.2": "Then Fury the chief went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn42.1:1.3": "“What is the cause, sir, what is the reason why some people are regarded as furious, ",
  "sn42.1:1.4": "while others are regarded as gentle?” ",
  "sn42.1:1.5": "“Take someone who hasn’t given up greed. ",
  "sn42.1:1.6": "So they get annoyed by others, and they show it. ",
  "sn42.1:1.7": "They’re regarded as furious. ",
  "sn42.1:1.8": "They haven’t given up hate. ",
  "sn42.1:1.9": "So they get annoyed by others, and they show it. ",
  "sn42.1:1.10": "They’re regarded as furious. ",
  "sn42.1:1.11": "They haven’t given up delusion. ",
  "sn42.1:1.12": "So they get annoyed by others, and they show it. ",
  "sn42.1:1.13": "They’re regarded as furious. ",
  "sn42.1:1.14": "This is the cause, this is the reason why some people are regarded as furious. ",
  "sn42.1:2.1": "But take someone who has given up greed. ",
  "sn42.1:2.2": "So they don’t get annoyed by others, and don’t show it. ",
  "sn42.1:2.3": "They’re regarded as gentle. ",
  "sn42.1:2.4": "They’ve given up hate. ",
  "sn42.1:2.5": "So they don’t get annoyed by others, and don’t show it. ",
  "sn42.1:2.6": "They’re regarded as gentle. ",
  "sn42.1:2.7": "They’ve given up delusion. ",
  "sn42.1:2.8": "So they don’t get annoyed by others, and don’t show it. ",
  "sn42.1:2.9": "They’re regarded as gentle. ",
  "sn42.1:2.10": "This is the cause, this is the reason why some people are regarded as gentle.” ",
  "sn42.1:3.1": "When he said this, Fury the chief said to the Buddha, ",
  "sn42.1:3.2": "“Excellent, sir! Excellent! ",
  "sn42.1:3.3": "As if he were righting the overturned, or revealing the hidden, or pointing out the path to the lost, or lighting a lamp in the dark so people with clear eyes can see what’s there, the Buddha has made the teaching clear in many ways. ",
  "sn42.1:3.4": "I go for refuge to the Buddha, to the teaching, and to the mendicant Saṅgha. ",
  "sn42.1:3.5": "From this day forth, may the Buddha remember me as a lay follower who has gone for refuge for life.” ",
  "sn42.2:0.1": "Linked Discourses 42.2 ",
  "sn42.2:0.2": "1. Chiefs ",
  "sn42.2:0.3": "With Tālapuṭa ",
  "sn42.2:1.1": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn42.2:1.2": "Then Tālapuṭa the dancing chief came up to the Buddha, bowed, sat down to one side, and said to the Buddha: ",
  "sn42.2:1.3": "“Sir, I have heard that the dancers of the past who were tutors of tutors said: ",
  "sn42.2:1.4": "‘Suppose a dancer entertains and amuses people on a stage or at a festival with mixed truth and lies. When their body breaks up, after death, they’re reborn in the company of laughing gods.’ ",
  "sn42.2:1.5": "What does the Buddha say about this?” ",
  "sn42.2:1.6": "“Enough, chief, let it be. Don’t ask me that.” ",
  "sn42.2:1.7": "For a second time … ",
  "sn42.2:1.8": "",
  "sn42.2:1.9": "",
  "sn42.2:1.10": "",
  "sn42.2:1.11": "",
  "sn42.2:1.12": "And for a third time Tālapuṭa said to the Buddha: ",
  "sn42.2:1.13": "“Sir, I have heard that the dancers of the past who were tutors of tutors said: ",
  "sn42.2:1.14": "‘Suppose a dancer entertains and amuses people on a stage or at a festival with mixed truth and lies. When their body breaks up, after death, they’re reborn in the company of laughing gods.’ ",
  "sn42.2:1.15": "What does the Buddha say about this?” ",
  "sn42.2:2.1": "“Clearly, chief, I’m not getting through to you when I say: ",
  "sn42.2:2.2": "‘Enough, chief, let it be. ",
  "sn42.2:2.3": "Don’t ask me that.’ ",
  "sn42.2:2.4": "Nevertheless, I will answer you. ",
  "sn42.2:2.5": "When sentient beings are still not free of greed, and are still bound by greed, ",
  "sn42.2:2.6": "a dancer in a stage or festival presents them with even more arousing things. ",
  "sn42.2:2.7": "When sentient beings are still not free of hate, and are still bound by hate, ",
  "sn42.2:2.8": "a dancer in a stage or festival presents them with even more hateful things. ",
  "sn42.2:2.9": "When sentient beings are still not free of delusion, and are still bound by delusion, ",
  "sn42.2:2.10": "a dancer in a stage or festival presents them with even more delusory things. ",
  "sn42.2:2.11": "And so, being heedless and negligent themselves, they’ve encouraged others to be heedless and negligent. When their body breaks up, after death, they’re reborn in the hell called ‘Laughter’. ",
  "sn42.2:2.12": "But if you have such a view: ",
  "sn42.2:2.13": "‘Suppose a dancer entertains and amuses people on a stage or at a festival with mixed truth and lies. When their body breaks up, after death, they’re reborn in the company of laughing gods.’ This is your wrong view. ",
  "sn42.2:2.14": "An individual with wrong view is reborn in one of two places, I say: ",
  "sn42.2:2.15": "hell or the animal realm.” ",
  "sn42.2:3.1": "When he said this, Tālapuṭa cried and burst out in tears. ",
  "sn42.2:3.2": "“This is what I didn’t get through to you when I said: ",
  "sn42.2:3.3": "‘Enough, chief, let it be. Don’t ask me that.’” ",
  "sn42.2:3.4": "“Sir, I’m not crying because of what the Buddha said. ",
  "sn42.2:3.5": "But sir, for a long time I’ve been cheated, tricked, and deceived by the dancers of the past who were tutors of tutors, who said: ",
  "sn42.2:3.6": "‘Suppose a dancer entertains and amuses people on a stage or at a festival with mixed truth and lies. When their body breaks up, after death, they’re reborn in the company of laughing gods.’ ",
  "sn42.2:3.7": "Excellent, sir! Excellent! ",
  "sn42.2:3.8": "As if he were righting the overturned, or revealing the hidden, or pointing out the path to the lost, or lighting a lamp in the dark so people with clear eyes can see what’s there, the Buddha has made the teaching clear in many ways. ",
  "sn42.2:3.9": "I go for refuge to the Buddha, to the teaching, and to the mendicant Saṅgha. ",
  "sn42.2:3.10": "Sir, may I receive the going forth, the ordination in the Buddha’s presence?” ",
  "sn42.2:3.11": "And Tālapuṭa the dancing chief received the going forth, the ordination in the Buddha’s presence. ",
  "sn42.2:3.12": "Not long after his ordination, Venerable Tālapuṭa ",
  "sn42.2:3.13": "became one of the perfected. ",
  "sn42.3:0.1": "Linked Discourses 42.3 ",
  "sn42.3:0.2": "1. Chiefs ",
  "sn42.3:0.3": "A Warrior ",
  "sn42.3:1.1": "Then Dustin the warrior chief went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn42.3:1.2": "“Sir, I have heard that the warriors of the past who were tutors of tutors said: ",
  "sn42.3:1.3": "‘Suppose a warrior, while striving and struggling in battle, is killed and finished off by his foes. When his body breaks up, after death, he’s reborn in the company of the gods of the fallen.’ ",
  "sn42.3:1.4": "What does the Buddha say about this?” ",
  "sn42.3:1.5": "“Enough, chief, let it be. Don’t ask me that.” ",
  "sn42.3:1.6": "For a second time … ",
  "sn42.3:1.7": "And for a third time Dustin the warrior chief said to the Buddha: ",
  "sn42.3:1.8": "“Sir, I have heard that the warriors of the past who were tutors of tutors said: ",
  "sn42.3:1.9": "‘Suppose a warrior, while striving and struggling in battle, is killed and finished off by his foes. When his body breaks up, after death, he’s reborn in the company of the gods of the fallen.’ ",
  "sn42.3:1.10": "What does the Buddha say about this?” ",
  "sn42.3:2.1": "“Clearly, chief, I’m not getting through to you when I say: ",
  "sn42.3:2.2": "‘Enough, chief, let it be. Don’t ask me that.’ ",
  "sn42.3:2.3": "Nevertheless, I will answer you. ",
  "sn42.3:2.4": "When a warrior strives and struggles in battle, their mind is already low, degraded, and misdirected as they think: ",
  "sn42.3:2.5": "‘May these sentient beings be killed, slaughtered, slain, destroyed, or annihilated!’ ",
  "sn42.3:2.6": "His foes kill him and finish him off, and ",
  "sn42.3:2.7": "when his body breaks up, after death, he’s reborn in the hell called ‘The Fallen’. ",
  "sn42.3:2.8": "But if you have such a view: ",
  "sn42.3:2.9": "‘Suppose a warrior, while striving and struggling in battle, is killed and finished off by his foes. When his body breaks up, after death, he’s reborn in the company of the gods of the fallen.’ This is your wrong view. ",
  "sn42.3:2.10": "An individual with wrong view is reborn in one of two places, I say: ",
  "sn42.3:2.11": "hell or the animal realm.” ",
  "sn42.3:3.1": "When he said this, Dustin the warrior chief cried and burst out in tears. ",
  "sn42.3:3.2": "“This is what I didn’t get through to you when I said: ",
  "sn42.3:3.3": "‘Enough, chief, let it be. Don’t ask me that.’” ",
  "sn42.3:3.4": "“Sir, I’m not crying because of what the Buddha said. ",
  "sn42.3:3.5": "But sir, for a long time I’ve been cheated, tricked, and deceived by the warriors of the past who were tutors of tutors, who said: ",
  "sn42.3:3.6": "‘Suppose a warrior, while striving and struggling in battle, is killed and finished off by his foes. When his body breaks up, after death, he’s reborn in the company of the gods of the fallen.’ ",
  "sn42.3:3.7": "Excellent, sir! Excellent! … ",
  "sn42.3:3.8": "From this day forth, may the Buddha remember me as a lay follower who has gone for refuge for life.” ",
  "sn42.4:0.1": "Linked Discourses 42.4 ",
  "sn42.4:0.2": "1. Chiefs ",
  "sn42.4:0.3": "An Elephant Marshal ",
  "sn42.4:1.1": "Then an elephant marshal chief went up to the Buddha … ",
  "sn42.4:1.2": "“From this day forth, may the Buddha remember me as a lay follower who has gone for refuge for life.” ",
  "sn42.5:0.1": "Linked Discourses 42.5 ",
  "sn42.5:0.2": "1. Chiefs ",
  "sn42.5:0.3": "A Cavalryman ",
  "sn42.5:1.1": "Then a cavalry chief went up to the Buddha … ",
  "sn42.5:1.2": "",
  "sn42.5:1.3": "",
  "sn42.5:1.4": "",
  "sn42.5:1.5": "",
  "sn42.5:2.1": "",
  "sn42.5:2.2": "",
  "sn42.5:2.3": "",
  "sn42.5:2.4": "",
  "sn42.5:2.5": "",
  "sn42.5:3.1": "",
  "sn42.5:3.2": "",
  "sn42.5:3.3": "",
  "sn42.5:3.4": "",
  "sn42.5:3.5": "",
  "sn42.5:3.6": "",
  "sn42.5:3.7": "",
  "sn42.5:3.8": "",
  "sn42.5:3.9": "",
  "sn42.5:3.10": "",
  "sn42.5:4.1": "",
  "sn42.5:4.2": "",
  "sn42.5:4.3": "",
  "sn42.5:4.4": "",
  "sn42.5:4.5": "",
  "sn42.5:4.6": "",
  "sn42.5:4.7": "",
  "sn42.5:4.8": "“From this day forth, may the Buddha remember me as a lay follower who has gone for refuge for life.” ",
  "sn42.6:0.1": "Linked Discourses 42.6 ",
  "sn42.6:0.2": "1. Chiefs ",
  "sn42.6:0.3": "With Asibandhaka’s Son ",
  "sn42.6:1.1": "At one time the Buddha was staying near Nāḷandā in Pāvārika’s mango grove. ",
  "sn42.6:1.2": "Then Asibandhaka’s son the chief went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn42.6:2.1": "“Sir, there are western brahmins garlanded with aquatic flowers who carry pitchers, immerse themselves in water, and serve the sacred flame. ",
  "sn42.6:2.2": "When someone has passed away, oh! they lift them up, send them well, and convey them to heaven. ",
  "sn42.6:2.3": "But what about the Blessed One, the perfected one, the fully awakened Buddha: is he able to ensure that the whole world will be reborn in a good place, a heavenly realm when their body breaks up, after death?” ",
  "sn42.6:3.1": "“Well then, chief, I’ll ask you about this in return, and you can answer as you like. ",
  "sn42.6:4.1": "What do you think, chief? ",
  "sn42.6:4.2": "Take an individual who kills living creatures, steals, and commits sexual misconduct. They use speech that’s false, backbiting, harsh, or nonsensical. And they’re covetous, malicious, and have wrong view. ",
  "sn42.6:4.3": "A large crowd were to come together to offer up supplication and entreaty, circumambulating them with joined palms and saying: ",
  "sn42.6:4.4": "‘When this person’s body breaks up, after death, may they be reborn in a good place, a heavenly realm!’ ",
  "sn42.6:4.5": "What do you think, chief? ",
  "sn42.6:4.6": "Would that person be reborn in heaven because of their supplications?” ",
  "sn42.6:4.7": "“No, sir.” ",
  "sn42.6:5.1": "“Chief, suppose a person were to throw a broad rock into a deep lake. ",
  "sn42.6:5.2": "And a large crowd were to come together to offer up supplication and entreaty, circumambulating it with joined palms, and saying: ",
  "sn42.6:5.3": "‘Rise, good rock! Float, good rock! Float to shore, good rock!’ ",
  "sn42.6:5.4": "What do you think, chief? ",
  "sn42.6:5.5": "Would that broad rock rise up or float because of their supplications?” ",
  "sn42.6:5.6": "“No, sir.” ",
  "sn42.6:5.7": "“In the same way, take a person who kills living creatures, steals, and commits sexual misconduct. They use speech that’s false, backbiting, harsh, or nonsensical. And they’re covetous, malicious, and have wrong view. ",
  "sn42.6:5.8": "Even though a large crowd were to come together to offer up supplication and entreaty … ",
  "sn42.6:5.9": "when their body breaks up, after death, they’re reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn42.6:6.1": "What do you think, chief? ",
  "sn42.6:6.2": "Take an individual who doesn’t kill living creatures, steal, or commit sexual misconduct. They don’t use speech that’s false, backbiting, harsh, or nonsensical. And they’re contented, kind-hearted, and have right view. ",
  "sn42.6:6.3": "And a large crowd were to come together to offer up supplication and entreaty, circumambulating them with joined palms and saying: ",
  "sn42.6:6.4": "‘When this person’s body breaks up, after death, may they be reborn in a place of loss, a bad place, the underworld, hell!’ ",
  "sn42.6:6.5": "What do you think, chief? ",
  "sn42.6:6.6": "Would that person be reborn in hell because of their supplications?” ",
  "sn42.6:6.7": "“No, sir.” ",
  "sn42.6:7.1": "“Chief, suppose a person were to sink a pot of ghee or oil into a deep lake and break it open. Its shards and chips would sink down, while the ghee or oil in it would rise up. ",
  "sn42.6:7.2": "And a large crowd were to come together to offer up supplication and entreaty, circumambulating it with joined palms and saying: ",
  "sn42.6:7.3": "‘Sink, good ghee or oil! Descend, good ghee or oil! Go down, good ghee or oil!’ ",
  "sn42.6:7.4": "What do you think, chief? ",
  "sn42.6:7.5": "Would that ghee or oil sink and descend because of their supplications?” ",
  "sn42.6:7.6": "“No, sir.” ",
  "sn42.6:8.1": "“In the same way, take an individual who doesn’t kill living creatures, steal, or commit sexual misconduct. They don’t use speech that’s false, backbiting, harsh, or nonsensical. And they’re contented, kind-hearted, and have right view. ",
  "sn42.6:8.2": "Even though a large crowd were to come together to offer up supplication and entreaty … ",
  "sn42.6:8.3": "when their body breaks up, after death, they’re reborn in a good place, a heavenly realm.” ",
  "sn42.6:8.4": "When he said this, Asibandhaka’s son the chief said to the Buddha, ",
  "sn42.6:8.5": "“Excellent, sir! … ",
  "sn42.6:8.6": "From this day forth, may the Buddha remember me as a lay follower who has gone for refuge for life.” ",
  "sn42.7:0.1": "Linked Discourses 42.7 ",
  "sn42.7:0.2": "1. Chiefs ",
  "sn42.7:0.3": "The Simile of the Field ",
  "sn42.7:1.1": "At one time the Buddha was staying near Nāḷandā in Pāvārika’s mango grove. ",
  "sn42.7:1.2": "Then Asibandhaka’s son the chief went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn42.7:1.3": "“Sir, doesn’t the Buddha live full of sympathy for all living beings?” ",
  "sn42.7:1.4": "“Yes, chief.” ",
  "sn42.7:1.5": "“So why then, sir, do you teach some people thoroughly and others less thoroughly?” ",
  "sn42.7:1.6": "“Well then, chief, I’ll ask you about this in return, and you can answer as you like. ",
  "sn42.7:1.7": "What do you think? Suppose a farmer has three fields: one is good, one is average, and one is poorbad ground of sand and salt. ",
  "sn42.7:1.8": "What do you think? When that farmer wants to plant seeds, where would he plant them first: the good field, the average one, or the poor one?” ",
  "sn42.7:1.9": "“Sir, he’d plant them first in the good field, then the average, then he may or may not plant seed in the poor field. ",
  "sn42.7:1.10": "Why is that? ",
  "sn42.7:1.11": "Because at least it can be fodder for the cattle.” ",
  "sn42.7:2.1": "“To me, the monks and nuns are like the good field. ",
  "sn42.7:2.2": "I teach them the Dhamma that’s good in the beginning, good in the middle, and good in the end, meaningful and well-phrased. And I reveal a spiritual practice that’s entirely full and pure. ",
  "sn42.7:2.3": "Why is that? ",
  "sn42.7:2.4": "Because they live with me as their island, asylum, shelter, and refuge. ",
  "sn42.7:2.5": "To me, the laymen and laywomen are like the average field. ",
  "sn42.7:2.6": "I also teach them the Dhamma that’s good in the beginning, good in the middle, and good in the end, meaningful and well-phrased. And I reveal a spiritual practice that’s entirely full and pure. ",
  "sn42.7:2.7": "Why is that? ",
  "sn42.7:2.8": "Because they live with me as their island, asylum, shelter, and refuge. ",
  "sn42.7:2.9": "To me, the ascetics, brahmins, and wanderers of other religions are like the poor field, the bad ground of sand and salt. ",
  "sn42.7:2.10": "I also teach them the Dhamma that’s good in the beginning, good in the middle, and good in the end, meaningful and well-phrased. And I reveal a spiritual practice that’s entirely full and pure. ",
  "sn42.7:2.11": "Why is that? ",
  "sn42.7:2.12": "Hopefully they might understand even a single sentence, which would be for their lasting welfare and happiness. ",
  "sn42.7:3.1": "Suppose a person had three water jars: one that’s uncracked and nonporous; one that’s uncracked but porous; and one that’s cracked and porous. ",
  "sn42.7:3.2": "What do you think? When that person wants to store water, where would they store it first: in the jar that’s uncracked and nonporous, the one that’s uncracked but porous, or the one that’s cracked and porous?” ",
  "sn42.7:3.3": "“Sir, they’d store water first in the jar that’s uncracked and nonporous, then the one that’s uncracked but porous, then they may or may not store water in the one that’s cracked and porous. ",
  "sn42.7:3.4": "Why is that? ",
  "sn42.7:3.5": "Because at least it can be used for washing the dishes.” ",
  "sn42.7:4.1": "“To me, the monks and nuns are like the water jar that’s uncracked and nonporous. ",
  "sn42.7:4.2": "I teach them the Dhamma that’s good in the beginning, good in the middle, and good in the end, meaningful and well-phrased. And I reveal a spiritual practice that’s entirely full and pure. ",
  "sn42.7:4.3": "Why is that? ",
  "sn42.7:4.4": "Because they live with me as their island, asylum, shelter, and refuge. ",
  "sn42.7:4.5": "To me, the laymen and laywomen are like the water jar that’s uncracked but porous. ",
  "sn42.7:4.6": "I also teach them the Dhamma that’s good in the beginning, good in the middle, and good in the end, meaningful and well-phrased. And I reveal a spiritual practice that’s entirely full and pure. ",
  "sn42.7:4.7": "Why is that? ",
  "sn42.7:4.8": "Because they live with me as their island, asylum, shelter, and refuge. ",
  "sn42.7:4.9": "To me, the ascetics, brahmins, and wanderers of other religions are like the water jar that’s cracked and porous. ",
  "sn42.7:4.10": "I also teach them the Dhamma that’s good in the beginning, good in the middle, and good in the end, meaningful and well-phrased. And I reveal a spiritual practice that’s entirely full and pure. ",
  "sn42.7:4.11": "Why is that? ",
  "sn42.7:4.12": "Hopefully they might understand even a single sentence, which would be for their lasting welfare and happiness.” ",
  "sn42.7:5.1": "When he said this, Asibandhaka’s son the chief said to the Buddha, ",
  "sn42.7:5.2": "“Excellent, sir! Excellent! … ",
  "sn42.7:5.3": "From this day forth, may the Buddha remember me as a lay follower who has gone for refuge for life.” ",
  "sn42.8:0.1": "Linked Discourses 42.8 ",
  "sn42.8:0.2": "1. Chiefs ",
  "sn42.8:0.3": "A Horn Blower ",
  "sn42.8:1.1": "At one time the Buddha was staying near Nāḷandā in Pāvārika’s mango grove. ",
  "sn42.8:1.2": "Then Asibandhaka’s son the chief, who was a disciple of the Jains, went up to the Buddha, and sat down to one side. The Buddha said to him, ",
  "sn42.8:1.3": "“Chief, how does the Jain ascetic of the Ñātika clan teach his disciples?” ",
  "sn42.8:1.4": "“Sir, this is how the Jain Ñātika teaches his disciples: ",
  "sn42.8:1.5": "‘Everyone who kills a living creature, steals, commits sexual misconduct, or lies goes to a place of loss, to hell. ",
  "sn42.8:1.6": "You’re led on by what you frequently live by.’ ",
  "sn42.8:1.7": "This is how the Jain Ñātika teaches his disciples.” ",
  "sn42.8:1.8": "“‘You’re led on by what you usually live by’: if this were true, then, according to what the Jain Ñātika says, no-one would go to a place of loss, to hell. ",
  "sn42.8:2.1": "What do you think, chief? ",
  "sn42.8:2.2": "Take an individual who kills living creatures. If we compare periods of time during the day and night, which is more frequent: the occasions when they’re killing or when they’re not killing?” ",
  "sn42.8:2.3": "“The occasions when they’re killing are less frequent, while the occasions when they’re not killing are more frequent.” ",
  "sn42.8:2.4": "“‘You’re led on by what you usually live by’: if this were true, then, according to what the Jain ascetic of the Ñātika clan says, no-one would go to a place of loss, to hell. ",
  "sn42.8:3.1": "What do you think, chief? ",
  "sn42.8:3.2": "Take an individual who steals … ",
  "sn42.8:3.3": "",
  "sn42.8:3.4": "",
  "sn42.8:4.1": "Take an individual who commits sexual misconduct … ",
  "sn42.8:4.2": "",
  "sn42.8:4.3": "",
  "sn42.8:5.1": "Take an individual who lies. If we compare periods of time during the day and night, which is more frequent: the occasions when they’re lying or when they’re not lying?” ",
  "sn42.8:5.2": "“The occasions when they’re lying are less frequent, while the occasions when they’re not lying are more frequent.” ",
  "sn42.8:5.3": "“‘You’re led on by what you usually live by’: if this were true, then, according to what the Jain Ñātika says, no-one would go to a place of loss, to hell. ",
  "sn42.8:6.1": "Take some teacher who has this doctrine and view: ",
  "sn42.8:6.2": "‘Everyone who kills a living creature, steals, commits sexual misconduct, or lies goes to a place of loss, to hell.’ ",
  "sn42.8:6.3": "And there’s a disciple who is devoted to that teacher. ",
  "sn42.8:6.4": "They think: ",
  "sn42.8:6.5": "‘My teacher has this doctrine and view: ",
  "sn42.8:6.6": "“Everyone who kills a living creature, steals, commits sexual misconduct, or lies goes to a place of loss, to hell.” ",
  "sn42.8:6.7": "But I’ve killed living creatures … ",
  "sn42.8:6.8": "",
  "sn42.8:6.9": "",
  "sn42.8:6.10": "",
  "sn42.8:6.11": "stolen … ",
  "sn42.8:6.12": "",
  "sn42.8:6.13": "",
  "sn42.8:6.14": "",
  "sn42.8:6.15": "committed sexual misconduct … ",
  "sn42.8:6.16": "",
  "sn42.8:6.17": "",
  "sn42.8:6.18": "",
  "sn42.8:6.19": "",
  "sn42.8:6.20": "or lied.’ ",
  "sn42.8:6.21": "They get the view: ‘I too am going to a place of loss, to hell.’ ",
  "sn42.8:6.22": "Unless they give up that speech and that thought, and let go of that view, they will be placed in hell as if delivered there. ",
  "sn42.8:7.1": "But consider when a Realized One arises in the world, perfected, a fully awakened Buddha, accomplished in knowledge and conduct, holy, knower of the world, supreme guide for those fit for training, teacher of gods and humans, awakened, blessed. ",
  "sn42.8:7.2": "In many ways he criticizes and denounces killing living creatures, saying: ‘Stop killing living creatures!’ ",
  "sn42.8:7.3": "He criticizes and denounces stealing … ",
  "sn42.8:7.4": "sexual misconduct … ",
  "sn42.8:7.5": "lying, saying: ‘Stop lying!’ ",
  "sn42.8:7.6": "And there’s a disciple who is devoted to that teacher. ",
  "sn42.8:7.7": "Then they reflect: ",
  "sn42.8:7.8": "‘In many ways the Buddha criticizes and denounces killing living creatures, saying: “Stop killing living creatures!” ",
  "sn42.8:7.9": "But I have killed living creatures to a certain extent. ",
  "sn42.8:7.10": "That’s not right, it’s not good, ",
  "sn42.8:7.11": "and I feel remorseful because of it. ",
  "sn42.8:7.12": "But I can’t undo what I have done.’ ",
  "sn42.8:7.13": "Reflecting like this, they give up killing living creatures, ",
  "sn42.8:7.14": "and in future they don’t kill living creatures. ",
  "sn42.8:7.15": "That’s how to give up this bad deed ",
  "sn42.8:7.16": "and get past it. ",
  "sn42.8:8.1": "‘In many ways the Buddha criticizes and denounces stealing …’ ",
  "sn42.8:8.2": "",
  "sn42.8:8.3": "",
  "sn42.8:8.4": "",
  "sn42.8:8.5": "",
  "sn42.8:8.6": "",
  "sn42.8:8.7": "",
  "sn42.8:8.8": "",
  "sn42.8:9.1": "‘In many ways the Buddha criticizes and denounces sexual misconduct …’ ",
  "sn42.8:9.2": "",
  "sn42.8:9.3": "",
  "sn42.8:9.4": "",
  "sn42.8:9.5": "",
  "sn42.8:9.6": "",
  "sn42.8:9.7": "",
  "sn42.8:10.1": "‘In many ways the Buddha criticizes and denounces lying, saying: “Stop lying!” ",
  "sn42.8:10.2": "But I have lied to a certain extent. ",
  "sn42.8:10.3": "That’s not right, it’s not good, and I feel remorseful because of it. But I can’t undo what I have done.’ ",
  "sn42.8:10.4": "Reflecting like this, they give up lying, and in future they refrain from lying. ",
  "sn42.8:10.5": "That’s how to give up this bad deed and get past it. ",
  "sn42.8:11.1": "They give up killing living creatures. ",
  "sn42.8:11.2": "They give up stealing. ",
  "sn42.8:11.3": "They give up sexual misconduct. ",
  "sn42.8:11.4": "They give up lying. ",
  "sn42.8:11.5": "They give up backbiting. ",
  "sn42.8:11.6": "They give up harsh speech. ",
  "sn42.8:11.7": "They give up talking nonsense. ",
  "sn42.8:11.8": "They give up covetousness. ",
  "sn42.8:11.9": "They give up ill will and malevolence. ",
  "sn42.8:11.10": "They give up wrong view and have right view. ",
  "sn42.8:12.1": "That noble disciple is rid of desire, rid of ill will, unconfused, aware, and mindful. They meditate spreading a heart full of love to one direction, and to the second, and to the third, and to the fourth. In the same way above, below, across, everywhere, all around, they spread a heart full of love to the whole worldabundant, expansive, limitless, free of enmity and ill will. ",
  "sn42.8:12.2": "Suppose there was a powerful horn blower. They’d easily make themselves heard in the four quarters. ",
  "sn42.8:12.3": "In the same way, when the heart’s release by love has been developed and cultivated like this, any limited deeds they’ve done don’t remain or persist there. ",
  "sn42.8:13.1": "Then that noble disciple is rid of desire, rid of ill will, unconfused, aware, and mindful. They meditate spreading a heart full of compassion … ",
  "sn42.8:13.2": "They meditate spreading a heart full of rejoicing … ",
  "sn42.8:13.3": "They meditate spreading a heart full of equanimity to one direction, and to the second, and to the third, and to the fourth. In the same way above, below, across, everywhere, all around, they spread a heart full of equanimity to the whole worldabundant, expansive, limitless, free of enmity and ill will. ",
  "sn42.8:13.4": "Suppose there was a powerful horn blower. They’d easily make themselves heard in the four quarters. ",
  "sn42.8:13.5": "In the same way, when the heart’s release by equanimity has been developed and cultivated like this, any limited deeds they’ve done don’t remain or persist there.” ",
  "sn42.8:14.1": "When he said this, Asibandhaka’s son the chief said to the Buddha, ",
  "sn42.8:14.2": "“Excellent, sir! Excellent! … ",
  "sn42.8:14.3": "From this day forth, may the Buddha remember me as a lay follower who has gone for refuge for life.” ",
  "sn42.9:0.1": "Linked Discourses 42.9 ",
  "sn42.9:0.2": "1. Chiefs ",
  "sn42.9:0.3": "Families ",
  "sn42.9:1.1": "At one time the Buddha was wandering in the land of the Kosalans together with a large Saṅgha of mendicants when he arrived at Nāḷandā. ",
  "sn42.9:1.2": "There he stayed near Nāḷandā in Pāvārika’s mango grove. ",
  "sn42.9:2.1": "Now at that time Nāḷandā was undergoing famine and scarcity, with crops blighted and turned to straw. ",
  "sn42.9:2.2": "At that time the Jain ascetic of the Ñātika clan was residing at Nāḷandā together with a large assembly of Jain ascetics. ",
  "sn42.9:2.3": "Then Asibandhaka’s son the chief, who was a disciple of the Jains, went up to the Jain Ñātika, bowed, and sat down to one side. The Jain Ñātika said to him: ",
  "sn42.9:2.4": "“Come, chief, refute the ascetic Gotama’s doctrine. ",
  "sn42.9:2.5": "Then you will get a good reputation: ",
  "sn42.9:2.6": "‘Asibandhaka’s son the chief refuted the doctrine of the ascetic Gotama, so mighty and powerful!’” ",
  "sn42.9:3.1": "“But sir, how am I to do this?” ",
  "sn42.9:3.2": "“Here, brahmin, go to the ascetic Gotama and say to him: ",
  "sn42.9:3.3": "‘Sir, don’t you in many ways praise kindness, protection, and sympathy for families?’ ",
  "sn42.9:3.4": "When he’s asked this, if he answers: ",
  "sn42.9:3.5": "‘Indeed I do, chief,’ say this to him: ",
  "sn42.9:3.6": "‘So what then are you doing, wandering together with this large Saṅgha of mendicants during a time of famine and scarcity, with crops blighted and turned to straw? ",
  "sn42.9:3.7": "The Buddha is practicing to annihilate, collapse, and ruin families!’ ",
  "sn42.9:3.8": "When you put this dilemma to him, the Buddha won’t be able to either spit it out or swallow it down.” ",
  "sn42.9:3.9": "“Yes, sir,” replied Asibandhaka’s son. He got up from his seat, bowed, and respectfully circled the Jain Ñātika, keeping him on his right. Then he went to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn42.9:4.1": "“Sir, don’t you in many ways praise kindness, protection, and sympathy for families?” ",
  "sn42.9:4.2": "“Indeed I do, chief.” ",
  "sn42.9:4.3": "“So what then are you doing, wandering together with this large Saṅgha of mendicants during a time of famine and scarcity, with crops blighted and turned to straw? ",
  "sn42.9:4.4": "The Buddha is practicing to annihilate, collapse, and ruin families!” ",
  "sn42.9:4.5": "“Well, chief, I recollect ninety-one eons back but I’m not aware of any family that’s been ruined merely by offering some cooked almsfood. ",
  "sn42.9:4.6": "Rather, rich, affluent, and wealthy familieswith lots of gold and silver, lots of property and assets, and lots of money and grainall acquired their wealth because of giving, truth, and restraint. ",
  "sn42.9:4.7": "Chief, there are eight causes and reasons for the ruin of families. ",
  "sn42.9:4.8": "Their ruin stems from rulers, bandits, fire, or flood. Or they lose their savings. Or their business fails due to not applying themselves to work. Or a wastrel is born into the family who squanders and fritters away their wealth. And impermanence is the eighth. ",
  "sn42.9:4.9": "These are the eight causes and reasons for the ruin of families. ",
  "sn42.9:4.10": "Given that these eight reasons are found, suppose someone says this: ",
  "sn42.9:4.11": "‘The Buddha is practicing to annihilate, collapse, and ruin families!’ ",
  "sn42.9:4.12": "Unless they give up that speech and that thought, and let go of that view, they will be placed in hell as if delivered there.” ",
  "sn42.9:5.1": "When he said this, Asibandhaka’s son the chief said to the Buddha, ",
  "sn42.9:5.2": "“Excellent, sir! Excellent! … ",
  "sn42.9:5.3": "From this day forth, may the Buddha remember me as a lay follower who has gone for refuge for life.” ",
  "sn42.10:0.1": "Linked Discourses 42.10 ",
  "sn42.10:0.2": "1. Chiefs ",
  "sn42.10:0.3": "With Maṇicūḷaka ",
  "sn42.10:1.1": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn42.10:1.2": "Now at that time while the king’s retinue was sitting together in the royal compound this discussion came up among them, ",
  "sn42.10:1.3": "“Gold and currency are proper for ascetics who follow the Sakyan. They accept and receive gold and currency.” ",
  "sn42.10:2.1": "Now at that time the chief Maṇicūḷaka was sitting in that assembly. ",
  "sn42.10:2.2": "He said to that retinue, ",
  "sn42.10:2.3": "“Good masters, don’t say that. ",
  "sn42.10:2.4": "Gold and currency are not proper for ascetics who follow the Sakyan. They neither accept nor receive gold and currency. They have set aside gems and gold, and quit using gold and currency.” ",
  "sn42.10:2.5": "He was able to persuade that assembly. ",
  "sn42.10:2.6": "Then Maṇicūḷaka went up to the Buddha, bowed, sat down to one side, and told him what had happened. He then said, ",
  "sn42.10:2.7": "",
  "sn42.10:2.8": "",
  "sn42.10:2.9": "",
  "sn42.10:2.10": "",
  "sn42.10:2.11": "",
  "sn42.10:2.12": "",
  "sn42.10:2.13": "“Answering this way, I trust that I repeat what the Buddha has said, and don’t misrepresent him with an untruth. I trust my explanation is in line with the teaching, and that there are no legitimate grounds for rebuttal or criticism.” ",
  "sn42.10:3.1": "“Indeed, in answering this way you repeat what I’ve said, and don’t misrepresent me with an untruth. Your explanation is in line with the teaching, and there are no legitimate grounds for rebuttal or criticism. ",
  "sn42.10:3.2": "Gold and currency are not proper for ascetics who follow the Sakyan. They neither accept nor receive gold and currency. They have set aside gems and gold, and quit using gold and currency. ",
  "sn42.10:3.3": "If gold and currency were proper for them, then the five kinds of sensual stimulation would also be proper. ",
  "sn42.10:3.4": "And if the five kinds of sensual stimulation are proper for them, you should categorically regard them as not having the qualities of an ascetic or a follower of the Sakyan. ",
  "sn42.10:3.5": "Rather, chief, I say this: ",
  "sn42.10:3.6": "Straw may be looked for by one needing straw; wood may be looked for by one needing wood; a cart may be looked for by one needing a cart; a workman may be looked for by one needing a workman. ",
  "sn42.10:3.7": "But in any case, there is no way they can accept or look for gold and currency, I say .” ",
  "sn42.11:0.1": "Linked Discourses 42.11 ",
  "sn42.11:0.2": "1. Chiefs ",
  "sn42.11:0.3": "With Bhadraka ",
  "sn42.11:1.1": "At one time the Buddha was staying in the land of the Mallas, near the Mallian town named Uruvelakappa. ",
  "sn42.11:1.2": "Then Bhadraka the village chief went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn42.11:1.3": "“Please, sir, let the Blessed One teach me the origin and disappearance of suffering.” ",
  "sn42.11:1.4": "“Chief, if I were to teach you about the origin and disappearance of suffering in connection with the past, saying ",
  "sn42.11:1.5": "‘this is how it was in the past,’ you might have doubts or uncertainties about that. ",
  "sn42.11:1.6": "If I were to teach you about the origin and disappearance of suffering in connection with the future, saying ",
  "sn42.11:1.7": "‘this is how it will be in the future,’ you might have doubts or uncertainties about that. ",
  "sn42.11:1.8": "Rather, chief, I will teach you about the origin and disappearance of suffering as I am sitting right here and you are sitting right there. ",
  "sn42.11:1.9": "Listen and apply your mind well, I will speak.” ",
  "sn42.11:1.10": "“Yes, sir,” Bhadraka replied. ",
  "sn42.11:1.11": "The Buddha said this: ",
  "sn42.11:2.1": "“What do you think, chief? ",
  "sn42.11:2.2": "Are there any people here in Uruvelakappa who, if they were executed, imprisoned, fined, or condemned, it would cause you sorrow, lamentation, pain, sadness, and distress?” ",
  "sn42.11:2.3": "“There are, sir.” ",
  "sn42.11:2.4": "“But are there any people here in Uruvelakappa who, if they were executed, imprisoned, fined, or condemned, it would not cause you sorrow, lamentation, pain, sadness, and distress?” ",
  "sn42.11:2.5": "“There are, sir.” ",
  "sn42.11:2.6": "“What’s the cause, chief, what’s the reason why, if this was to happen to some people it could cause you sorrow, while if it happens to others it does not?” ",
  "sn42.11:2.7": "“The people regarding whom this would give rise to sorrow are those I have desire and passion. ",
  "sn42.11:2.8": "The people regarding whom this would not give rise to sorrow are those I don’t have desire and passion.” ",
  "sn42.11:2.9": "“With this present phenomenon that you have seen, understood, immediately attained, and fathomed, you can apply the same method to the past and future: ",
  "sn42.11:2.10": "‘All the suffering that arose in the past was rooted and sourced in desire. ",
  "sn42.11:2.11": "For desire is the root of suffering. ",
  "sn42.11:2.12": "All the suffering that will arise in the future will be rooted and sourced in desire. ",
  "sn42.11:2.13": "For desire is the root of suffering.’” ",
  "sn42.11:2.14": "“It’s incredible, sir, it’s amazing! ",
  "sn42.11:2.15": "How well said this was by the Buddha! ",
  "sn42.11:2.16": "‘All the suffering that arises is rooted and sourced in desire. ",
  "sn42.11:2.17": "For desire is the root of suffering.’ ",
  "sn42.11:2.18": "I have a boy called Ciravāsi, who resides in a house away from here. ",
  "sn42.11:2.19": "I rise early and dispatch someone, saying: ",
  "sn42.11:2.20": "‘Go, I must say, and check on my boy Ciravāsi.’ ",
  "sn42.11:2.21": "Until they get back I worry: ",
  "sn42.11:2.22": "‘I hope nothing’s wrong with Ciravāsi!’” ",
  "sn42.11:3.1": "“What do you think, chief? ",
  "sn42.11:3.2": "If Ciravāsi was executed, imprisoned, fined, or condemned, would it cause you sorrow, lamentation, pain, sadness, and distress?” ",
  "sn42.11:3.3": "“How could it not, sir?” ",
  "sn42.11:3.4": "“This too is a way to understand: ",
  "sn42.11:3.5": "‘All the suffering that arises is rooted and sourced in desire. ",
  "sn42.11:3.6": "For desire is the root of suffering.’ ",
  "sn42.11:4.1": "What do you think, chief? ",
  "sn42.11:4.2": "Before you’d seen or heard of Ciravāsi’s mother, did you have any desire or passion or fondness for her?” ",
  "sn42.11:4.3": "“No, sir.” ",
  "sn42.11:4.4": "“Then was it because you saw or heard of her that you had ",
  "sn42.11:4.5": "desire or passion or fondness for her?” ",
  "sn42.11:4.6": "“Yes, sir.” ",
  "sn42.11:5.1": "“What do you think, chief? ",
  "sn42.11:5.2": "If Ciravāsi’s mother was executed, imprisoned, fined, or condemned, would it cause you sorrow, lamentation, pain, sadness, and distress?” ",
  "sn42.11:5.3": "“How could it not, sir?” ",
  "sn42.11:5.4": "“This too is a way to understand: ",
  "sn42.11:5.5": "‘All the suffering that arises is rooted and sourced in desire. ",
  "sn42.11:5.6": "For desire is the root of suffering.’” ",
  "sn42.12:0.1": "Linked Discourses 42.12 ",
  "sn42.12:0.2": "1. Chiefs ",
  "sn42.12:0.3": "With Rāsiya ",
  "sn42.12:1.1": "Then Rāsiya the chief went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn42.12:1.2": "“Sir, I have heard this: ‘The ascetic Gotama criticizes all forms of mortification. He categorically condemns and denounces those fervent mortifiers who live rough.’ ",
  "sn42.12:1.3": "Do those who say this repeat what the Buddha has said, and not misrepresent him with an untruth? Is their explanation in line with the teaching? Are there any legitimate grounds for rebuttal and criticism?” ",
  "sn42.12:1.4": "“Chief, those who say this do not repeat what I have said. They misrepresent me with what is false, hollow, and untrue. ",
  "sn42.12:2.1": "These two extremes should not be cultivated by one who has gone forth. ",
  "sn42.12:2.2": "Indulgence in sensual pleasures, which is low, crude, ordinary, ignoble, and pointless. And indulgence in self-mortification, which is painful, ignoble, and pointless. ",
  "sn42.12:2.3": "Avoiding these two extremes, the Realized One understood the middle way of practice, which gives vision and knowledge, and leads to peace, direct knowledge, awakening, and extinguishment. ",
  "sn42.12:2.4": "And what is that middle way of practice? ",
  "sn42.12:2.5": "It is simply this noble eightfold path, that is: ",
  "sn42.12:2.6": "right view, right purpose, right speech, right action, right livelihood, right effort, right mindfulness, and right immersion. ",
  "sn42.12:2.7": "This, chief, is the middle way of practice that was understood by the Realized One, which gives vision and knowledge, and leads to peace, direct knowledge, awakening, and extinguishment. ",
  "sn42.12:3.1": "There are these three pleasure seekers in the world. ",
  "sn42.12:3.2": "What three? ",
  "sn42.12:3.3": "Take a pleasure seeker who seeks wealth using illegitimate, coercive means, and who doesn’t make themselves happy and pleased, or share it and make merit. ",
  "sn42.12:3.4": "Next, a pleasure seeker seeks wealth using illegitimate, coercive means. ",
  "sn42.12:3.5": "They make themselves happy and pleased, but don’t share it and make merit. ",
  "sn42.12:3.6": "Next, a pleasure seeker seeks wealth using illegitimate, coercive means. ",
  "sn42.12:3.7": "They make themselves happy and pleased, and they share it and make merit. ",
  "sn42.12:4.1": "Next, a pleasure seeker seeks wealth using means both legitimate and illegitimate, and coercive and non-coercive. ",
  "sn42.12:4.2": "They don’t make themselves happy and pleased, or share it and make merit. ",
  "sn42.12:4.3": "Next, a pleasure seeker seeks wealth using means both legitimate and illegitimate, and coercive and non-coercive. ",
  "sn42.12:4.4": "They don’t make themselves happy and pleased, or share it and make merit. ",
  "sn42.12:4.5": "Next, a pleasure seeker seeks wealth using means both legitimate and illegitimate, and coercive and non-coercive. ",
  "sn42.12:4.6": "They make themselves happy and pleased, and they share it and make merit. ",
  "sn42.12:5.1": "Next, a pleasure seeker seeks wealth using legitimate, non-coercive means. ",
  "sn42.12:5.2": "They don’t make themselves happy and pleased, or share it and make merit. ",
  "sn42.12:5.3": "Next, a pleasure seeker seeks wealth using legitimate, non-coercive means. ",
  "sn42.12:5.4": "They make themselves happy and pleased, but don’t share it and make merit. ",
  "sn42.12:5.5": "Next, a pleasure seeker seeks wealth using legitimate, non-coercive means. ",
  "sn42.12:5.6": "They make themselves happy and pleased, and they share it and make merit. ",
  "sn42.12:5.7": "They enjoy that wealth tied, infatuated, attached, blind to the drawbacks, and not understanding the escape. ",
  "sn42.12:5.8": "Next, a pleasure seeker seeks wealth using legitimate, non-coercive means. ",
  "sn42.12:5.9": "They make themselves happy and pleased, and they share it and make merit. ",
  "sn42.12:5.10": "And they enjoy that wealth untied, uninfatuated, unattached, seeing the drawbacks, and understanding the escape. ",
  "sn42.12:6.1": "Now, consider the pleasure seeker who seeks wealth using illegitimate, coercive means, and who doesn’t make themselves happy and pleased, or share it and make merit. ",
  "sn42.12:6.2": "They may be criticized on three grounds. ",
  "sn42.12:6.3": "What three? ",
  "sn42.12:6.4": "They seek wealth using illegitimate, coercive means. This is the first ground for criticism. ",
  "sn42.12:6.5": "They don’t make themselves happy and pleased. This is the second ground for criticism. ",
  "sn42.12:6.6": "They don’t share it and make merit. This is the third ground for criticism. ",
  "sn42.12:6.7": "This pleasure seeker may be criticized on these three grounds. ",
  "sn42.12:7.1": "Now, consider the pleasure seeker who seeks wealth using illegitimate, coercive means, and who makes themselves happy and pleased, but doesn’t share it and make merit. ",
  "sn42.12:7.2": "This pleasure seeker may be criticized on two grounds, and praised on one. ",
  "sn42.12:7.3": "What are the two grounds for criticism? ",
  "sn42.12:7.4": "They seek wealth using illegitimate, coercive means. This is the first ground for criticism. ",
  "sn42.12:7.5": "They don’t share it and make merit. This is the second ground for criticism. ",
  "sn42.12:7.6": "What is the one ground for praise? ",
  "sn42.12:7.7": "They make themselves happy and pleased. This is the one ground for praise. ",
  "sn42.12:7.8": "This pleasure seeker may be criticized on these two grounds, and praised on this one. ",
  "sn42.12:8.1": "Now, consider the pleasure seeker who seeks wealth using illegitimate, coercive means, and who makes themselves happy and pleased, and shares it and makes merit. ",
  "sn42.12:8.2": "This pleasure seeker may be criticized on one ground, and praised on two. ",
  "sn42.12:8.3": "What is the one ground for criticism? ",
  "sn42.12:8.4": "They seek wealth using illegitimate, coercive means. This is the one ground for criticism. ",
  "sn42.12:8.5": "What are the two grounds for praise? ",
  "sn42.12:8.6": "They make themselves happy and pleased. This is the first ground for praise. ",
  "sn42.12:8.7": "They share it and make merit. This is the second ground for praise. ",
  "sn42.12:8.8": "This pleasure seeker may be criticized on this one ground, and praised on these two. ",
  "sn42.12:9.1": "Now, consider the pleasure seeker who seeks wealth using means both legitimate and illegitimate, and coercive and non-coercive, and who doesn’t make themselves happy and pleased, or share it and make merit. ",
  "sn42.12:9.2": "They may be praised on one ground, and criticized on three. ",
  "sn42.12:9.3": "What is the one ground for praise? ",
  "sn42.12:9.4": "They seek wealth using legitimate, non-coercive means. This is the one ground for praise. ",
  "sn42.12:9.5": "What are the three grounds for criticism? ",
  "sn42.12:9.6": "They seek wealth using illegitimate, coercive means. This is the first ground for criticism. ",
  "sn42.12:9.7": "They don’t make themselves happy and pleased. This is the second ground for criticism. ",
  "sn42.12:9.8": "They don’t share it and make merit. This is the third ground for criticism. ",
  "sn42.12:9.9": "This pleasure seeker may be praised on this one ground, and criticized on these three. ",
  "sn42.12:10.1": "Now, consider the pleasure seeker who seeks wealth using means both legitimate and illegitimate, and coercive and non-coercive, and makes themselves happy and pleased, but doesn’t share it and make merit. ",
  "sn42.12:10.2": "They may be praised on two grounds, and criticized on two. ",
  "sn42.12:10.3": "What are the two grounds for praise? ",
  "sn42.12:10.4": "They seek wealth using legitimate, non-coercive means. This is the first ground for praise. ",
  "sn42.12:10.5": "They make themselves happy and pleased. This is the second ground for praise. ",
  "sn42.12:10.6": "What are the two grounds for criticism? ",
  "sn42.12:10.7": "They seek wealth using illegitimate, coercive means. This is the first ground for criticism. ",
  "sn42.12:10.8": "They don’t share it and make merit. This is the second ground for criticism. ",
  "sn42.12:10.9": "This pleasure seeker may be praised on these two grounds, and criticized on these two. ",
  "sn42.12:11.1": "Now, consider the pleasure seeker who seeks wealth using means both legitimate and illegitimate, and coercive and non-coercive, and who makes themselves happy and pleased, and shares it and makes merit. ",
  "sn42.12:11.2": "They may be praised on three grounds, and criticized on one. ",
  "sn42.12:11.3": "What are the three grounds for praise? ",
  "sn42.12:11.4": "They seek wealth using legitimate, non-coercive means. This is the first ground for praise. ",
  "sn42.12:11.5": "They make themselves happy and pleased. This is the second ground for praise. ",
  "sn42.12:11.6": "They share it and make merit. This is the third ground for praise. ",
  "sn42.12:11.7": "What is the one ground for criticism? ",
  "sn42.12:11.8": "They seek wealth using illegitimate, coercive means. This is the one ground for criticism. ",
  "sn42.12:11.9": "This pleasure seeker may be praised on these three grounds, and criticized on this one. ",
  "sn42.12:12.1": "Now, consider the pleasure seeker who seeks wealth using legitimate, non-coercive means, but who doesn’t make themselves happy and pleased, or share it and make merit. ",
  "sn42.12:12.2": "They may be praised on one ground, and criticized on two. ",
  "sn42.12:12.3": "What is the one ground for praise? ",
  "sn42.12:12.4": "They seek wealth using legitimate, non-coercive means. This is the one ground for praise. ",
  "sn42.12:12.5": "What are the two grounds for criticism? ",
  "sn42.12:12.6": "They don’t make themselves happy and pleased. This is the first ground for criticism. ",
  "sn42.12:12.7": "They don’t share it and make merit. This is the second ground for criticism. ",
  "sn42.12:12.8": "This pleasure seeker may be praised on this one ground, and criticized on these two. ",
  "sn42.12:13.1": "Now, consider the pleasure seeker who seeks wealth using legitimate, non-coercive means, and who makes themselves happy and pleased, but doesn’t share it and make merit. ",
  "sn42.12:13.2": "This pleasure seeker may be praised on two grounds, and criticized on one. ",
  "sn42.12:13.3": "What are the two grounds for praise? ",
  "sn42.12:13.4": "They seek wealth using legitimate, non-coercive means. This is the first ground for praise. ",
  "sn42.12:13.5": "They make themselves happy and pleased. This is the second ground for praise. ",
  "sn42.12:13.6": "What is the one ground for criticism? ",
  "sn42.12:13.7": "They don’t share it and make merit. This is the one ground for criticism. ",
  "sn42.12:13.8": "This pleasure seeker may be praised on these two grounds, and criticized on this one. ",
  "sn42.12:14.1": "Now, consider the pleasure seeker who seeks wealth using legitimate, non-coercive means, and who makes themselves happy and pleased, and shares it and makes merit. But they enjoy that wealth tied, infatuated, attached, blind to the drawbacks, and not understanding the escape. ",
  "sn42.12:14.2": "They may be praised on three grounds and criticized on one. ",
  "sn42.12:14.3": "What are the three grounds for praise? ",
  "sn42.12:14.4": "They seek wealth using legitimate, non-coercive means. This is the first ground for praise. ",
  "sn42.12:14.5": "They make themselves happy and pleased. This is the second ground for praise. ",
  "sn42.12:14.6": "They share it and make merit. This is the third ground for praise. ",
  "sn42.12:14.7": "What is the one ground for criticism? ",
  "sn42.12:14.8": "They enjoy that wealth tied, infatuated, attached, blind to the drawbacks, and not understanding the escape. This is the one ground for criticism. ",
  "sn42.12:14.9": "This pleasure seeker may be praised on these three grounds, and criticized on this one. ",
  "sn42.12:15.1": "Now, consider the pleasure seeker who seeks wealth using legitimate, non-coercive means, and who makes themselves happy and pleased, and shares it and makes merit. ",
  "sn42.12:15.2": "And they enjoy that wealth untied, uninfatuated, unattached, seeing the drawbacks, and understanding the escape. ",
  "sn42.12:15.3": "This pleasure seeker may be praised on four grounds. ",
  "sn42.12:15.4": "What are the four grounds for praise? ",
  "sn42.12:15.5": "They seek wealth using legitimate, non-coercive means. This is the first ground for praise. ",
  "sn42.12:15.6": "They make themselves happy and pleased. This is the second ground for praise. ",
  "sn42.12:15.7": "They share it and make merit. This is the third ground for praise. ",
  "sn42.12:15.8": "They enjoy that wealth untied, uninfatuated, unattached, seeing the drawbacks, and understanding the escape. This is the fourth ground for praise. ",
  "sn42.12:15.9": "This pleasure seeker may be praised on these four grounds. ",
  "sn42.12:16.1": "These three fervent mortifiers who live rough are found in the world. ",
  "sn42.12:16.2": "What three? ",
  "sn42.12:16.3": "Take a fervent mortifier who has gone forth out of faith from the lay life to homelessness, thinking: ",
  "sn42.12:16.4": "‘Hopefully I will achieve a skillful quality! Hopefully I will realize a superhuman distinction in knowledge and vision worthy of the noble ones!’ ",
  "sn42.12:16.5": "They mortify and torment themselves. But they don’t achieve any skillful quality, or realize any superhuman distinction in knowledge and vision worthy of the noble ones. ",
  "sn42.12:17.1": "Take another fervent mortifier who has gone forth out of faith from the lay life to homelessness, thinking: ",
  "sn42.12:17.2": "‘Hopefully I will achieve a skillful quality! Hopefully I will realize a superhuman distinction in knowledge and vision worthy of the noble ones!’ ",
  "sn42.12:17.3": "They mortify and torment themselves. And they achieve a skillful quality, but don’t realize any superhuman distinction in knowledge and vision worthy of the noble ones. ",
  "sn42.12:18.1": "Take another fervent mortifier who has gone forth out of faith from the lay life to homelessness, thinking: ",
  "sn42.12:18.2": "‘Hopefully I will achieve a skillful quality! Hopefully I will realize a superhuman distinction in knowledge and vision worthy of the noble ones!’ ",
  "sn42.12:18.3": "They mortify and torment themselves. And they achieve a skillful quality, and they realize a superhuman distinction in knowledge and vision worthy of the noble ones. ",
  "sn42.12:19.1": "In this case, the first fervent mortifier may be criticized on three grounds. ",
  "sn42.12:19.2": "What three? ",
  "sn42.12:19.3": "They mortify and torment themselves. This is the first ground for criticism. ",
  "sn42.12:19.4": "They don’t achieve a skillful quality. This is the second ground for criticism. ",
  "sn42.12:19.5": "They don’t realize a superhuman distinction in knowledge and vision worthy of the noble ones. This is the third ground for criticism. ",
  "sn42.12:19.6": "This fervent mortifier may be criticized on these three grounds. ",
  "sn42.12:20.1": "In this case, the second fervent mortifier ",
  "sn42.12:20.2": "may be criticized on two grounds, and praised on one. ",
  "sn42.12:20.3": "What are the two grounds for criticism? ",
  "sn42.12:20.4": "They mortify and torment themselves. This is the first ground for criticism. ",
  "sn42.12:20.5": "They don’t realize a superhuman distinction in knowledge and vision worthy of the noble ones. This is the second ground for criticism. ",
  "sn42.12:20.6": "What is the one ground for praise? ",
  "sn42.12:20.7": "They achieve a skillful quality. This is the one ground for praise. ",
  "sn42.12:20.8": "This fervent mortifier may be criticized on these two grounds, and praised on one. ",
  "sn42.12:21.1": "In this case, the third fervent mortifier may be criticized on one ground, and praised on two. ",
  "sn42.12:21.2": "What is the one ground for criticism? ",
  "sn42.12:21.3": "They mortify and torment themselves. This is the one ground for criticism. ",
  "sn42.12:21.4": "What are the two grounds for praise? ",
  "sn42.12:21.5": "They achieve a skillful quality. This is the first ground for praise. ",
  "sn42.12:21.6": "They realize a superhuman distinction in knowledge and vision worthy of the noble ones. This is the second ground for praise. ",
  "sn42.12:21.7": "This fervent mortifier may be criticized on this one ground, and praised on two. ",
  "sn42.12:22.1": "There are these three kinds of wearing away that are apparent in the present life, immediately effective, inviting inspection, relevant, so that sensible people can know them for themselves. ",
  "sn42.12:22.2": "What three? ",
  "sn42.12:22.3": "A greedy person, because of greed, intends to hurt themselves, hurt others, and hurt both. ",
  "sn42.12:22.4": "When they’ve given up greed they don’t have such intentions. ",
  "sn42.12:22.5": "This wearing away is apparent in the present life, immediately effective, inviting inspection, relevant, so that sensible people can know it for themselves. ",
  "sn42.12:22.6": "A hateful person, because of hate, intends to hurt themselves, hurt others, and hurt both. ",
  "sn42.12:22.7": "When they’ve given up hate they don’t have such intentions. ",
  "sn42.12:22.8": "This wearing away is apparent in the present life, immediately effective, inviting inspection, relevant, so that sensible people can know it for themselves. ",
  "sn42.12:22.9": "A deluded person, because of delusion, intends to hurt themselves, hurt others, and hurt both. ",
  "sn42.12:22.10": "When they’ve given up delusion they don’t have such intentions. ",
  "sn42.12:22.11": "This wearing away is apparent in the present life, immediately effective, inviting inspection, relevant, so that sensible people can know it for themselves. ",
  "sn42.12:22.12": "These are the three kinds of wearing away that are apparent in the present life, immediately effective, inviting inspection, relevant, so that sensible people can know them for themselves.” ",
  "sn42.12:23.1": "When he said this, Rāsiya the chief said to the Buddha, ",
  "sn42.12:23.2": "“Excellent, sir! Excellent! … ",
  "sn42.12:23.3": "From this day forth, may the Buddha remember me as a lay follower who has gone for refuge for life.” ",
  "sn42.13:0.1": "Linked Discourses 42.13 ",
  "sn42.13:0.2": "1. Chiefs ",
  "sn42.13:0.3": "With Pāṭaliya ",
  "sn42.13:1.1": "At one time the Buddha was staying in the land of the Koliyans, where they have a town named Uttarakā. ",
  "sn42.13:1.2": "Then Pāṭaliya the chief went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn42.13:1.3": "“Sir, I have heard this: ",
  "sn42.13:1.4": "‘The ascetic Gotama knows deceit.’ ",
  "sn42.13:2.1": "Do those who say this repeat what the Buddha has said, and not misrepresent him with an untruth? Is their explanation in line with the teaching? Are there any legitimate grounds for rebuttal and criticism? ",
  "sn42.13:2.2": "For we don’t want to misrepresent the Blessed One.” ",
  "sn42.13:2.3": "“Chief, those who say this repeat what I have said, and don’t misrepresent me with an untruth. Their explanation is in line with the teaching, and there are no legitimate grounds for rebuttal and criticism.” ",
  "sn42.13:2.4": "“Sir, we didn’t believe that what those ascetics and brahmins said was really true. ",
  "sn42.13:2.5": "But it seems the ascetic Gotama is deceitful!” ",
  "sn42.13:2.6": "“Chief, does someone who says ‘I know deceit’ also say ‘I am deceitful’?” ",
  "sn42.13:2.7": "“That’s right, Blessed One! That’s right, Holy One!” ",
  "sn42.13:2.8": "“Well then, chief, I’ll ask you about this in return, and you can answer as you like. ",
  "sn42.13:3.1": "What do you think, chief? ",
  "sn42.13:3.2": "Do you know the Koliyan officers with drooping headdresses?” ",
  "sn42.13:3.3": "“I know them, sir.” ",
  "sn42.13:3.4": "“And what’s their job?” ",
  "sn42.13:3.5": "“To put a stop to bandits and to deliver messages for the Koliyans.” ",
  "sn42.13:3.6": "“What do you think, chief? ",
  "sn42.13:3.7": "Are the Koliyan officers with drooping headdresses moral or immoral?” ",
  "sn42.13:3.8": "“I know that they’re immoral, of bad character, sir. They are among those in the world who are immoral and of bad character.” ",
  "sn42.13:3.9": "“Would it be right to say that ",
  "sn42.13:3.10": "Pāṭaliya knows the Kolyian officers with drooping headdresses who are immoral, of bad character, so he too must be immoral and of bad character?” ",
  "sn42.13:3.11": "“No, sir. ",
  "sn42.13:3.12": "I’m quite different from the Koliyan officers with drooping headdresses; we have quite different characters.” ",
  "sn42.13:3.13": "“So if you can know those officers of bad character while you are not of bad character, why can’t the Realized One know deceit, without being deceitful? ",
  "sn42.13:3.14": "I understand deceit and its result. And I understand how the deceitful practice so that when their body breaks up, after death, they’re reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn42.13:4.1": "I understand killing living creatures and its result. And I understand how those who kill living creatures practice so that when their body breaks up, after death, they’re reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn42.13:4.2": "I understand stealing … ",
  "sn42.13:4.3": "sexual misconduct … ",
  "sn42.13:4.4": "lying … ",
  "sn42.13:4.5": "backbiting … ",
  "sn42.13:4.6": "harsh speech … ",
  "sn42.13:4.7": "talking nonsense … ",
  "sn42.13:4.8": "covetousness … ",
  "sn42.13:4.9": "ill will … ",
  "sn42.13:4.10": "wrong view and its result. And I understand how those who have wrong view practice so that when their body breaks up, after death, they’re reborn in a place of loss, a bad place, the underworld, hell. ",
  "sn42.13:5.1": "There are some ascetics and brahmins who have this doctrine and view: ",
  "sn42.13:5.2": "‘Everyone who kills living creatures experiences pain and sadness in this very life. ",
  "sn42.13:5.3": "Everyone who steals … ",
  "sn42.13:5.4": "commits sexual misconduct … ",
  "sn42.13:5.5": "lies experiences pain and sadness in this very life.’ ",
  "sn42.13:6.1": "But you can see someone, garlanded and adorned, nicely bathed and anointed, hair and beard dressed, taking his pleasure with women as if he were a king. ",
  "sn42.13:6.2": "You might ask someone: ",
  "sn42.13:6.3": "‘My friend, what did that man do?’ ",
  "sn42.13:6.4": "And they’d reply: ",
  "sn42.13:6.5": "‘My friend, that man attacked the king’s enemy and killed them. ",
  "sn42.13:6.6": "The king was delighted and gave him this reward. ",
  "sn42.13:6.7": "That’s why he’s garlanded and adorned, nicely bathed and anointed, hair and beard dressed, taking his pleasure with women as if he were a king.’ ",
  "sn42.13:7.1": "And you can see someone else, his arms tied tightly behind his back with a strong rope. His head is shaven and he’s marched from street to street and from square to square to the beating of a harsh drum. Then he’s taken out the south gate and there, to the south of the city, they chop off his head. ",
  "sn42.13:7.2": "You might ask someone: ",
  "sn42.13:7.3": "‘My friend, what did that man do?’ ",
  "sn42.13:7.4": "And they’d reply: ",
  "sn42.13:7.5": "‘My friend, that man is an enemy of the king, and he has murdered a man or a woman. ",
  "sn42.13:7.6": "That’s why the rulers arrested him and inflicted such punishment.’ ",
  "sn42.13:8.1": "What do you think, chief? ",
  "sn42.13:8.2": "Have you seen or heard of such a thing?” ",
  "sn42.13:8.3": "“Sir, we have seen it and heard of it, and we will hear of it again.” ",
  "sn42.13:8.4": "“Since this is so, the ascetics and brahmins whose view is that ",
  "sn42.13:8.5": "everyone who kills living creatures experiences pain and sadness in this very life: are they right or wrong?” ",
  "sn42.13:8.6": "“They’re wrong, sir.” ",
  "sn42.13:8.7": "“But those who speak hollow, false nonsense: are they moral or immoral?” ",
  "sn42.13:8.8": "“Immoral, sir.” ",
  "sn42.13:8.9": "“And are those who are immoral, of bad character practicing wrongly or rightly?” ",
  "sn42.13:8.10": "“They’re practicing wrongly, sir.” ",
  "sn42.13:8.11": "“And do those who are practicing wrongly have wrong view or right view?” ",
  "sn42.13:8.12": "“They have wrong view, sir.” ",
  "sn42.13:8.13": "“But is it appropriate to have confidence in those of wrong view?” ",
  "sn42.13:8.14": "“No, sir.” ",
  "sn42.13:9.1": "“You can see someone, garlanded and adorned … ",
  "sn42.13:9.2": "",
  "sn42.13:9.3": "",
  "sn42.13:9.4": "",
  "sn42.13:9.5": "‘My friend, that man attacked the king’s enemy and took their valuables. ",
  "sn42.13:9.6": "The king was delighted and gave him this reward. …’ … ",
  "sn42.13:9.7": "",
  "sn42.13:10.1": "And you can see someone else, his arms tied tightly behind his back … ",
  "sn42.13:10.2": "",
  "sn42.13:10.3": "",
  "sn42.13:10.4": "‘My friend, that man took something from a village or wilderness, with the intention to commit theft. ",
  "sn42.13:10.5": "That’s why the rulers arrested him and inflicted such punishment.’ ",
  "sn42.13:10.6": "What do you think, chief? ",
  "sn42.13:10.7": "Have you seen or heard of such a thing?” ",
  "sn42.13:10.8": "“Sir, we have seen it and heard of it, and we will hear of it again.” ",
  "sn42.13:10.9": "“Since this is so, the ascetics and brahmins whose view is that ",
  "sn42.13:10.10": "everyone who steals experiences pain and sadness in this very life: are they right or wrong? … ",
  "sn42.13:10.11": "Is it appropriate to have confidence in them?” ",
  "sn42.13:10.12": "“No, sir.” ",
  "sn42.13:11.1": "“You can see someone, garlanded and adorned … ",
  "sn42.13:11.2": "",
  "sn42.13:11.3": "",
  "sn42.13:11.4": "",
  "sn42.13:11.5": "‘My friend, that man had sexual relations with the wives of an enemy king. ",
  "sn42.13:11.6": "The king was delighted and gave him this reward. …’ … ",
  "sn42.13:11.7": "",
  "sn42.13:12.1": "And you can see someone else, his arms tied tightly behind his back … ",
  "sn42.13:12.2": "",
  "sn42.13:12.3": "",
  "sn42.13:12.4": "",
  "sn42.13:12.5": "‘My friend, that man had sexual relations with the women and maidens of good families. ",
  "sn42.13:12.6": "That’s why the rulers arrested him and inflicted such punishment.’ ",
  "sn42.13:12.7": "What do you think, chief? ",
  "sn42.13:12.8": "Have you seen or heard of such a thing?” ",
  "sn42.13:12.9": "“Sir, we have seen it and heard of it, and we will hear of it again.” ",
  "sn42.13:12.10": "“Since this is so, the ascetics and brahmins whose view is that ",
  "sn42.13:12.11": "everyone who commits sexual misconduct experiences pain and sadness in this very life: are they right or wrong? … ",
  "sn42.13:12.12": "Is it appropriate to have confidence in them?” ",
  "sn42.13:12.13": "“No, sir.” ",
  "sn42.13:13.1": "“And you can see someone, garlanded and adorned … ",
  "sn42.13:13.2": "",
  "sn42.13:13.3": "",
  "sn42.13:13.4": "",
  "sn42.13:13.5": "‘My friend, that man amused the king with lies. ",
  "sn42.13:13.6": "The king was delighted and gave him this reward. …’ … ",
  "sn42.13:13.7": "",
  "sn42.13:14.1": "And you can see someone else, his arms tied tightly behind his back … ",
  "sn42.13:14.2": "",
  "sn42.13:14.3": "",
  "sn42.13:14.4": "",
  "sn42.13:14.5": "‘My friend, that man has ruined a householder or householder’s child by lying. ",
  "sn42.13:14.6": "That’s why the rulers arrested him and inflicted such punishment.’ ",
  "sn42.13:14.7": "What do you think, chief? ",
  "sn42.13:14.8": "Have you seen or heard of such a thing?” ",
  "sn42.13:14.9": "“Sir, we have seen it and heard of it, and we will hear of it again.” ",
  "sn42.13:14.10": "“Since this is so, the ascetics and brahmins whose view is that ",
  "sn42.13:14.11": "everyone who lies experiences pain and sadness in this very life: are they right or wrong?” ",
  "sn42.13:14.12": "“They’re wrong, sir.” ",
  "sn42.13:14.13": "“But those who speak hollow, false nonsense: are they moral or immoral?” ",
  "sn42.13:14.14": "“Immoral, sir.” ",
  "sn42.13:14.15": "“And are those who are immoral, of bad character practicing wrongly or rightly?” ",
  "sn42.13:14.16": "“They’re practicing wrongly, sir.” ",
  "sn42.13:14.17": "“And do those who are practicing wrongly have wrong view or right view?” ",
  "sn42.13:14.18": "“They have wrong view, sir.” ",
  "sn42.13:14.19": "“But is it appropriate to have confidence in those of wrong view?” ",
  "sn42.13:14.20": "“No, sir. ",
  "sn42.13:15.1": "It’s incredible, sir, it’s amazing! ",
  "sn42.13:15.2": "I have a guest house, ",
  "sn42.13:15.3": "where there are cots, seats, water jars, and oil lamps. ",
  "sn42.13:15.4": "Whenever an ascetic or brahmin comes to stay, I share what I have as best I can. ",
  "sn42.13:15.5": "Once it so happened, sir, that four teachers of different views, beliefs, and opinions came to stay at my guest house. ",
  "sn42.13:16.1": "One teacher had this doctrine and view: ",
  "sn42.13:16.2": "‘There’s no meaning in giving, sacrifice, or offerings. There’s no fruit or result of good and bad deeds. There’s no afterlife. There’s no such thing as mother and father, or beings that are reborn spontaneously. And there’s no ascetic or brahmin who is rightly comported and rightly practiced, and who describes the afterlife after realizing it with their own insight.’ ",
  "sn42.13:17.1": "One teacher had this doctrine and view: ",
  "sn42.13:17.2": "‘There is meaning in giving, sacrifice, and offerings. There are fruits and results of good and bad deeds. There is an afterlife. There are such things as mother and father, and beings that are reborn spontaneously. And there are ascetics and brahmins who are rightly comported and rightly practiced, and who describe the afterlife after realizing it with their own insight.’ ",
  "sn42.13:18.1": "One teacher had this doctrine and view: ",
  "sn42.13:18.2": "‘The one who acts does nothing wrong when they punish, mutilate, torture, aggrieve, oppress, intimidate, or when they encourage others to do the same. Nothing bad is done when they kill, steal, break into houses, plunder wealth, steal from isolated buildings, commit highway robbery, commit adultery, and lie. ",
  "sn42.13:18.3": "If you were to reduce all the living creatures of this earth to one heap and mass of flesh with a razor-edged chakram, no evil comes of that, and no outcome of evil. ",
  "sn42.13:18.4": "If you were to go along the south bank of the Ganges killing, mutilating, and torturing, and encouraging others to do the same, no evil comes of that, and no outcome of evil. ",
  "sn42.13:18.5": "If you were to go along the north bank of the Ganges giving and sacrificing and encouraging others to do the same, no merit comes of that, and no outcome of merit. ",
  "sn42.13:18.6": "In giving, self-control, restraint, and truthfulness there is no merit or outcome of merit.’ ",
  "sn42.13:19.1": "One teacher had this doctrine and view: ",
  "sn42.13:19.2": "‘The one who acts does a bad deed when they punish, mutilate, torture, aggrieve, oppress, intimidate, or when they encourage others to do the same. A bad deed is done when they kill, steal, break into houses, plunder wealth, steal from isolated buildings, commit highway robbery, commit adultery, and lie. ",
  "sn42.13:19.3": "If you were to reduce all the living creatures of this earth to one heap and mass of flesh with a razor-edged chakram, evil comes of that, and an outcome of evil. ",
  "sn42.13:19.4": "If you were to go along the south bank of the Ganges killing, mutilating, and torturing, and encouraging others to do the same, evil comes of that, and an outcome of evil. ",
  "sn42.13:19.5": "If you were to go along the north bank of the Ganges giving and sacrificing and encouraging others to do the same, merit comes of that, and an outcome of merit. ",
  "sn42.13:19.6": "In giving, self-control, restraint, and truthfulness there is merit and outcome of merit.’ ",
  "sn42.13:20.1": "I had doubt and uncertainty about that: ",
  "sn42.13:20.2": "‘I wonder who of these respected ascetics and brahmins speaks the truth, and who speaks falsehood?’” ",
  "sn42.13:21.1": "“Chief, no wonder you’re doubting and uncertain. ",
  "sn42.13:21.2": "Doubt has come up in you about an uncertain matter.” ",
  "sn42.13:21.3": "“I am quite confident that the Buddha is capable of teaching me so that I can give up this state of uncertainty.” ",
  "sn42.13:22.1": "“Chief, there is immersion based on understanding of principle. ",
  "sn42.13:22.2": "If you gain such mental immersion, you can give up that state of uncertainty. ",
  "sn42.13:22.3": "And what is immersion based on understanding of principle? ",
  "sn42.13:22.4": "It’s when a noble disciple has given up killing living creatures, stealing, sexual misconduct, lying, backbiting, harsh speech, talking nonsense, covetousness, ill will, and wrong view. ",
  "sn42.13:23.1": "Then that noble disciple is rid of desire, rid of ill will, unconfused, aware, and mindful. They meditate spreading a heart full of love to one direction, and to the second, and to the third, and to the fourth. In the same way above, below, across, everywhere, all around, they spread a heart full of love to the whole worldabundant, expansive, limitless, free of enmity and ill will. ",
  "sn42.13:23.2": "They reflect thus: ",
  "sn42.13:23.3": "‘That teacher who had this doctrine and view: ",
  "sn42.13:23.4": "“There’s no meaning in giving, sacrifice, or offerings. There’s no fruit or result of good and bad deeds. There’s no afterlife. There’s no such thing as mother and father, or beings that are reborn spontaneously. And there’s no ascetic or brahmin who is rightly comported and rightly practiced, and who describes the afterlife after realizing it with their own insight.” ",
  "sn42.13:23.5": "If what this good teacher says is true, it’s a sure bet for me to not hurt any creature firm or frail. ",
  "sn42.13:23.6": "I hold a winning hand on both counts, since I’m restrained in body, speech, and mind, and when my body breaks up, after death, I’ll be reborn in a good place, a heavenly realm.’ ",
  "sn42.13:23.7": "Joy springs up in them. ",
  "sn42.13:23.8": "Being joyful, rapture springs up. ",
  "sn42.13:23.9": "When the mind is full of rapture, the body becomes tranquil. ",
  "sn42.13:23.10": "When the body is tranquil, they feel bliss. ",
  "sn42.13:23.11": "And when blissful, the mind becomes immersed in samādhi. ",
  "sn42.13:23.12": "This is that immersion based on understanding of principle. ",
  "sn42.13:23.13": "If you gain such mental immersion, you can give up that state of uncertainty. ",
  "sn42.13:24.1": "Then that noble disciple is rid of desire, rid of ill will, unconfused, aware, and mindful. They meditate spreading a heart full of love to one direction, and to the second, and to the third, and to the fourth. In the same way above, below, across, everywhere, all around, they spread a heart full of love to the whole worldabundant, expansive, limitless, free of enmity and ill will. ",
  "sn42.13:24.2": "They reflect thus: ",
  "sn42.13:24.3": "‘That teacher who had this doctrine and view: ",
  "sn42.13:24.4": "“There is meaning in giving, sacrifice, and offerings. There are fruits and results of good and bad deeds. There is an afterlife. There are such things as mother and father, and beings that are reborn spontaneously. And there are ascetics and brahmins who are rightly comported and rightly practiced, and who describe the afterlife after realizing it with their own insight.” ",
  "sn42.13:24.5": "If what this good teacher says is true, it’s a sure bet for me to not hurt any creature firm or frail. ",
  "sn42.13:24.6": "I hold a winning hand on both counts, since I’m restrained in body, speech, and mind, and when my body breaks up, after death, I’ll be reborn in a good place, a heavenly realm.’ ",
  "sn42.13:24.7": "Joy springs up in them. ",
  "sn42.13:24.8": "Being joyful, rapture springs up. ",
  "sn42.13:24.9": "When the mind is full of rapture, the body becomes tranquil. ",
  "sn42.13:24.10": "When the body is tranquil, they feel bliss. ",
  "sn42.13:24.11": "And when blissful, the mind becomes immersed in samādhi. ",
  "sn42.13:24.12": "This is that immersion based on understanding of principle. ",
  "sn42.13:24.13": "If you gain such mental immersion, you can give up that state of uncertainty. ",
  "sn42.13:25.1": "Then that noble disciple is rid of desire, rid of ill will, unconfused, aware, and mindful. They meditate spreading a heart full of love to one direction, and to the second, and to the third, and to the fourth. In the same way above, below, across, everywhere, all around, they spread a heart full of love to the whole worldabundant, expansive, limitless, free of enmity and ill will. ",
  "sn42.13:25.2": "They reflect thus: ",
  "sn42.13:25.3": "‘That teacher who had this doctrine and view: ",
  "sn42.13:25.4": "“The one who acts does nothing wrong when they punish, mutilate, torture, aggrieve, oppress, intimidate, or when they encourage others to do the same. Nothing bad is done when they kill, steal, break into houses, plunder wealth, steal from isolated buildings, commit highway robbery, commit adultery, and lie. ",
  "sn42.13:25.5": "If you were to reduce all the living creatures of this earth to one heap and mass of flesh with a razor-edged chakram, no evil comes of that, and no outcome of evil. ",
  "sn42.13:25.6": "If you were to go along the south bank of the Ganges killing, mutilating, and torturing, and encouraging others to do the same, no evil comes of that, and no outcome of evil. ",
  "sn42.13:25.7": "If you were to go along the north bank of the Ganges giving and sacrificing and encouraging others to do the same, no merit comes of that, and no outcome of merit. ",
  "sn42.13:25.8": "In giving, self-control, restraint, and truthfulness there is no merit or outcome of merit.” ",
  "sn42.13:25.9": "If what this good teacher says is true, it’s a sure bet for me to not hurt any creature firm or frail. ",
  "sn42.13:25.10": "I hold a winning hand on both counts, since I’m restrained in body, speech, and mind, and when my body breaks up, after death, I’ll be reborn in a good place, a heavenly realm.’ ",
  "sn42.13:25.11": "Joy springs up in them. ",
  "sn42.13:25.12": "Being joyful, rapture springs up. ",
  "sn42.13:25.13": "When the mind is full of rapture, the body becomes tranquil. ",
  "sn42.13:25.14": "When the body is tranquil, they feel bliss. ",
  "sn42.13:25.15": "And when blissful, the mind becomes immersed in samādhi. ",
  "sn42.13:25.16": "This is that immersion based on understanding of principle. ",
  "sn42.13:25.17": "If you gain such mental immersion, you can give up that state of uncertainty. ",
  "sn42.13:26.1": "Then that noble disciple is rid of desire, rid of ill will, unconfused, aware, and mindful. They meditate spreading a heart full of love to one direction, and to the second, and to the third, and to the fourth. In the same way above, below, across, everywhere, all around, they spread a heart full of love to the whole worldabundant, expansive, limitless, free of enmity and ill will. ",
  "sn42.13:26.2": "They reflect thus: ",
  "sn42.13:26.3": "‘That teacher who had this doctrine and view: ",
  "sn42.13:26.4": "“The one who acts does a bad deed when they punish, mutilate, torture, aggrieve, oppress, intimidate, or when they encourage others to do the same. A bad deed is done when they kill, steal, break into houses, plunder wealth, steal from isolated buildings, commit highway robbery, commit adultery, and lie. ",
  "sn42.13:26.5": "If you were to reduce all the living creatures of this earth to one heap and mass of flesh with a razor-edged chakram, evil comes of that, and an outcome of evil. ",
  "sn42.13:26.6": "If you were to go along the south bank of the Ganges killing, mutilating, and torturing, and encouraging others to do the same, evil comes of that, and an outcome of evil. ",
  "sn42.13:26.7": "If you were to go along the north bank of the Ganges giving and sacrificing and encouraging others to do the same, merit comes of that, and an outcome of merit. ",
  "sn42.13:26.8": "In giving, self-control, restraint, and truthfulness there is merit and outcome of merit.” ",
  "sn42.13:26.9": "If what this good teacher says is true, it’s a sure bet for me to not hurt any creature firm or frail. ",
  "sn42.13:26.10": "I hold a winning hand on both counts, since I’m restrained in body, speech, and mind, and when my body breaks up, after death, I’ll be reborn in a good place, a heavenly realm.’ ",
  "sn42.13:26.11": "Joy springs up in them. ",
  "sn42.13:26.12": "Being joyful, rapture springs up. ",
  "sn42.13:26.13": "When the mind is full of rapture, the body becomes tranquil. ",
  "sn42.13:26.14": "When the body is tranquil, they feel bliss. ",
  "sn42.13:26.15": "And when blissful, the mind becomes immersed in samādhi. ",
  "sn42.13:26.16": "This is that immersion based on understanding of principle. ",
  "sn42.13:26.17": "If you gain such mental immersion, you can give up that state of uncertainty. ",
  "sn42.13:27.1": "Then that noble disciple is rid of desire, rid of ill will, unconfused, aware, and mindful. They meditate spreading a heart full of compassion … ",
  "sn42.13:27.2": "rejoicing … ",
  "sn42.13:28.1": "equanimity to one direction, and to the second, and to the third, and to the fourth. In the same way above, below, across, everywhere, all around, they spread a heart full of equanimity to the whole worldabundant, expansive, limitless, free of enmity and ill will. ",
  "sn42.13:28.2": "",
  "sn42.13:28.3": "",
  "sn42.13:28.4": "",
  "sn42.13:28.5": "",
  "sn42.13:28.6": "",
  "sn42.13:28.7": "",
  "sn42.13:28.8": "",
  "sn42.13:28.9": "",
  "sn42.13:28.10": "",
  "sn42.13:28.11": "",
  "sn42.13:28.12": "",
  "sn42.13:28.13": "",
  "sn42.13:29.1": "",
  "sn42.13:29.2": "",
  "sn42.13:29.3": "",
  "sn42.13:29.4": "",
  "sn42.13:29.5": "",
  "sn42.13:29.6": "",
  "sn42.13:29.7": "",
  "sn42.13:29.8": "",
  "sn42.13:29.9": "",
  "sn42.13:29.10": "",
  "sn42.13:29.11": "",
  "sn42.13:29.12": "",
  "sn42.13:29.13": "",
  "sn42.13:30.1": "",
  "sn42.13:30.2": "",
  "sn42.13:30.3": "",
  "sn42.13:30.4": "",
  "sn42.13:30.5": "",
  "sn42.13:30.6": "",
  "sn42.13:30.7": "",
  "sn42.13:30.8": "",
  "sn42.13:30.9": "",
  "sn42.13:30.10": "",
  "sn42.13:30.11": "",
  "sn42.13:30.12": "",
  "sn42.13:30.13": "",
  "sn42.13:30.14": "",
  "sn42.13:30.15": "",
  "sn42.13:30.16": "",
  "sn42.13:30.17": "",
  "sn42.13:31.1": "",
  "sn42.13:31.2": "They reflect thus: ",
  "sn42.13:31.3": "",
  "sn42.13:31.4": "",
  "sn42.13:31.5": "",
  "sn42.13:31.6": "",
  "sn42.13:31.7": "",
  "sn42.13:31.8": "",
  "sn42.13:31.9": "‘If what this good teacher says is true, it’s a sure bet for me to not hurt any creature firm or frail. ",
  "sn42.13:31.10": "I hold a winning hand on both counts, since I’m restrained in body, speech, and mind, and when my body breaks up, after death, I’ll be reborn in a good place, a heavenly realm.’ ",
  "sn42.13:31.11": "Joy springs up in them. ",
  "sn42.13:31.12": "Being joyful, rapture springs up. ",
  "sn42.13:31.13": "When the mind is full of rapture, the body becomes tranquil. ",
  "sn42.13:31.14": "When the body is tranquil, they feel bliss. ",
  "sn42.13:31.15": "And when blissful, the mind becomes immersed in samādhi. ",
  "sn42.13:31.16": "This is that immersion based on understanding of principle. ",
  "sn42.13:31.17": "If you gain such mental immersion, you can give up that state of uncertainty.” ",
  "sn42.13:32.1": "When he said this, Pāṭaliya the chief said to the Buddha, ",
  "sn42.13:32.2": "“Excellent, sir! Excellent! … ",
  "sn42.13:32.3": "From this day forth, may the Buddha remember me as a lay follower who has gone for refuge for life.” ",
  "sn42.13:32.4": "",
  "sn42.13:32.5": "",
  "sn42.13:33.1": "",
  "sn42.13:33.2": "",
  "sn42.13:33.3": "",
  "sn42.13:33.4": "",
  "sn42.13:33.5": "The Linked Discourses on chiefs are complete. "
}
window.BILARA["sn42_v1"]["en"]["sn42_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
