window.BILARA = window.BILARA || {};
window.BILARA["sn51_v1"] = window.BILARA["sn51_v1"] || {};
window.BILARA["sn51_v1"]["en"] = {
  "sn51.1:0.1": "Linked Discourses 51.1 ",
  "sn51.1:0.2": "1. At the Cāpāla Shrine ",
  "sn51.1:0.3": "From the Near Shore ",
  "sn51.1:1.1": "“Mendicants, when these four bases of psychic power are developed and cultivated they lead to going from the near shore to the far shore. ",
  "sn51.1:1.2": "What four? ",
  "sn51.1:1.3": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm, and active effort. ",
  "sn51.1:1.4": "They develop the basis of psychic power that has immersion due to energy, and active effort. ",
  "sn51.1:1.5": "They develop the basis of psychic power that has immersion due to mental development, and active effort. ",
  "sn51.1:1.6": "They develop the basis of psychic power that has immersion due to inquiry, and active effort. ",
  "sn51.1:1.7": "When these four bases of psychic power are developed and cultivated they lead to going from the near shore to the far shore.” ",
  "sn51.2:0.1": "Linked Discourses 51.2 ",
  "sn51.2:0.2": "1. At the Cāpāla Shrine ",
  "sn51.2:0.3": "Missed Out ",
  "sn51.2:1.1": "“Mendicants, whoever has missed out on the four bases of psychic power has missed out on the noble path to the complete ending of suffering. ",
  "sn51.2:1.2": "Whoever has undertaken the four bases of psychic power has undertaken the noble path to the complete ending of suffering. ",
  "sn51.2:1.3": "What four? ",
  "sn51.2:1.4": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.2:1.5": "energy … ",
  "sn51.2:1.6": "mental development … ",
  "sn51.2:1.7": "inquiry, and active effort. ",
  "sn51.2:1.8": "Whoever has missed out on these four bases of psychic power has missed out on the noble path to the complete ending of suffering. ",
  "sn51.2:1.9": "Whoever has undertaken these four bases of psychic power has undertaken the noble path to the complete ending of suffering.” ",
  "sn51.3:0.1": "Linked Discourses 51.3 ",
  "sn51.3:0.2": "1. At the Cāpāla Shrine ",
  "sn51.3:0.3": "A Noble One ",
  "sn51.3:1.1": "“Mendicants, when these four bases of psychic power are developed and cultivated they are noble and emancipating, and bring one who practices them to the complete ending of suffering. ",
  "sn51.3:1.2": "What four? ",
  "sn51.3:1.3": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.3:1.4": "energy … ",
  "sn51.3:1.5": "mental development … ",
  "sn51.3:1.6": "inquiry, and active effort. ",
  "sn51.3:1.7": "When these four bases of psychic power are developed and cultivated they are noble and emancipating, and bring one who practices them to the complete ending of suffering.” ",
  "sn51.4:0.1": "Linked Discourses 51.4 ",
  "sn51.4:0.2": "1. At the Cāpāla Shrine ",
  "sn51.4:0.3": "Disillusionment ",
  "sn51.4:1.1": "“Mendicants, these four bases of psychic power, when developed and cultivated, lead solely to disillusionment, dispassion, cessation, peace, insight, awakening, and extinguishment. ",
  "sn51.4:1.2": "What four? ",
  "sn51.4:1.3": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.4:1.4": "energy … ",
  "sn51.4:1.5": "mental development … ",
  "sn51.4:1.6": "inquiry, and active effort. ",
  "sn51.4:1.7": "These four bases of psychic power, when developed and cultivated, lead solely to disillusionment, dispassion, cessation, peace, insight, awakening, and extinguishment.” ",
  "sn51.5:0.1": "Linked Discourses 51.5 ",
  "sn51.5:0.2": "1. At the Cāpāla Shrine ",
  "sn51.5:0.3": "Partly ",
  "sn51.5:1.1": "“Mendicants, all the ascetics and brahmins in the past who have partly manifested psychic powers have done so by developing and cultivating the four bases of psychic power. ",
  "sn51.5:1.2": "All the ascetics and brahmins in the future who will partly manifest psychic powers will do so by developing and cultivating the four bases of psychic power. ",
  "sn51.5:1.3": "All the ascetics and brahmins in the present who are partly manifesting psychic powers do so by developing and cultivating the four bases of psychic power. ",
  "sn51.5:2.1": "What four? ",
  "sn51.5:2.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.5:2.3": "energy … ",
  "sn51.5:2.4": "mental development … ",
  "sn51.5:2.5": "inquiry, and active effort. ",
  "sn51.5:2.6": "All the ascetics and brahmins in the past who have partly manifested psychic powers have done so by developing and cultivating these four bases of psychic power. ",
  "sn51.5:2.7": "All the ascetics and brahmins in the future who will partly manifest psychic powers will do so by developing and cultivating these four bases of psychic power. ",
  "sn51.5:2.8": "All the ascetics and brahmins in the present who are partly manifesting psychic powers do so by developing and cultivating these four bases of psychic power.” ",
  "sn51.6:0.1": "Linked Discourses 51.6 ",
  "sn51.6:0.2": "1. At the Cāpāla Shrine ",
  "sn51.6:0.3": "Completely ",
  "sn51.6:1.1": "“Mendicants, all the ascetics and brahmins in the past who have completely manifested psychic powers have done so by developing and cultivating the four bases of psychic power. ",
  "sn51.6:1.2": "All the ascetics and brahmins in the future who will completely manifest psychic powers will do so by developing and cultivating the four bases of psychic power. ",
  "sn51.6:1.3": "All the ascetics and brahmins in the present who are completely manifesting psychic powers do so by developing and cultivating the four bases of psychic power. ",
  "sn51.6:2.1": "What four? ",
  "sn51.6:2.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.6:2.3": "energy … ",
  "sn51.6:2.4": "mental development … ",
  "sn51.6:2.5": "inquiry, and active effort. ",
  "sn51.6:2.6": "All the ascetics and brahmins in the past who have completely manifested psychic powers have done so by developing and cultivating these four bases of psychic power. ",
  "sn51.6:2.7": "All the ascetics and brahmins in the future who will completely manifest psychic powers will do so by developing and cultivating these four bases of psychic power. ",
  "sn51.6:2.8": "All the ascetics and brahmins in the present who are completely manifesting psychic powers do so by developing and cultivating these four bases of psychic power.” ",
  "sn51.7:0.1": "Linked Discourses 51.7 ",
  "sn51.7:0.2": "1. At the Cāpāla Shrine ",
  "sn51.7:0.3": "A Mendicant ",
  "sn51.7:1.1": "“Mendicants, all the mendicants in the past … ",
  "sn51.7:1.2": "future … ",
  "sn51.7:1.3": "present who realize the undefiled freedom of heart and freedom by wisdom in this very life, and who live having realized it with their own insight due to the ending of defilements, do so by developing and cultivating the four bases of psychic power. ",
  "sn51.7:2.1": "What four? ",
  "sn51.7:2.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.7:2.3": "energy … ",
  "sn51.7:2.4": "mental development … ",
  "sn51.7:2.5": "inquiry, and active effort. ",
  "sn51.7:2.6": "All the mendicants in the past … ",
  "sn51.7:2.7": "future … ",
  "sn51.7:2.8": "present who realize the undefiled freedom of heart and freedom by wisdom in this very life, and who live having realized it with their own insight due to the ending of defilements, do so by developing and cultivating these four bases of psychic power.” ",
  "sn51.8:0.1": "Linked Discourses 51.8 ",
  "sn51.8:0.2": "1. At the Cāpāla Shrine ",
  "sn51.8:0.3": "Awakened ",
  "sn51.8:1.1": "“Mendicants, there are these four bases of psychic power. ",
  "sn51.8:1.2": "What four? ",
  "sn51.8:1.3": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.8:1.4": "energy … ",
  "sn51.8:1.5": "mental development … ",
  "sn51.8:1.6": "inquiry, and active effort. ",
  "sn51.8:1.7": "These are the four bases of psychic power. ",
  "sn51.8:1.8": "It is because he has developed and cultivated these four bases of psychic power that the Realized One is called ‘the perfected one, the fully awakened Buddha’.” ",
  "sn51.9:0.1": "Linked Discourses 51.9 ",
  "sn51.9:0.2": "1. At the Cāpāla Shrine ",
  "sn51.9:0.3": "Knowledge ",
  "sn51.9:1.1": "“Mendicants: ‘This is the basis of psychic power that has immersion due to enthusiasm, and active effort.’ Such was the vision, knowledge, wisdom, realization, and light that arose in me regarding teachings not learned before from another. ",
  "sn51.9:1.2": "‘This basis of psychic power … should be developed.’ … ",
  "sn51.9:1.3": "‘This basis of psychic power … has been developed.’ Such was the vision, knowledge, wisdom, realization, and light that arose in me regarding teachings not learned before from another. ",
  "sn51.9:2.1": "‘This is the basis of psychic power that has immersion due to energy, and active effort.’ … ",
  "sn51.9:2.2": "‘This basis of psychic power … should be developed.’ … ",
  "sn51.9:2.3": "‘This basis of psychic power … has been developed.’ Such was the vision, knowledge, wisdom, realization, and light that arose in me regarding teachings not learned before from another. ",
  "sn51.9:3.1": "‘This is the basis of psychic power that has immersion due to mental development, and active effort.’ … ",
  "sn51.9:3.2": "‘This basis of psychic power … should be developed.’ … ",
  "sn51.9:3.3": "‘This basis of psychic power … has been developed.’ Such was the vision, knowledge, wisdom, realization, and light that arose in me regarding teachings not learned before from another. ",
  "sn51.9:4.1": "‘This is the basis of psychic power that has immersion due to inquiry, and active effort.’ … ",
  "sn51.9:4.2": "‘This basis of psychic power … should be developed.’ … ",
  "sn51.9:4.3": "‘This basis of psychic power … has been developed.’ Such was the vision, knowledge, wisdom, realization, and light that arose in me regarding teachings not learned before from another.” ",
  "sn51.10:0.1": "Linked Discourses 51.10 ",
  "sn51.10:0.2": "1. At the Cāpāla Shrine ",
  "sn51.10:0.3": "At the Cāpāla Shrine ",
  "sn51.10:1.1": "So I have heard. ",
  "sn51.10:1.2": "At one time the Buddha was staying near Vesālī, at the Great Wood, in the hall with the peaked roof. ",
  "sn51.10:1.3": "Then the Buddha robed up in the morning and, taking his bowl and robe, entered Vesālī for alms. ",
  "sn51.10:1.4": "Then, after the meal, on his return from almsround, he addressed Venerable Ānanda: ",
  "sn51.10:1.5": "“Ānanda, get your sitting cloth. ",
  "sn51.10:1.6": "Let’s go to the Cāpāla Shrine for the day’s meditation.” ",
  "sn51.10:1.7": "“Yes, sir,” replied Ānanda. Taking his sitting cloth he followed behind the Buddha. ",
  "sn51.10:2.1": "Then the Buddha went up to the Cāpāla Shrine, and sat down on the seat spread out. ",
  "sn51.10:2.2": "Ānanda bowed to the Buddha and sat down to one side. ",
  "sn51.10:2.3": "The Buddha said to him: ",
  "sn51.10:3.1": "“Ānanda, Vesālī is lovely. And the Udena, Gotamaka, Seven Maidens, Many Sons, Sārandada, and Cāpāla Shrines are all lovely. ",
  "sn51.10:3.2": "Whoever has developed and cultivated the four bases of psychic powermade them a vehicle and a basis, kept them up, consolidated them, and properly implemented themmay, if they wish, live for the proper lifespan or what’s left of it. ",
  "sn51.10:3.3": "The Realized One has developed and cultivated the four bases of psychic power, made them a vehicle and a basis, kept them up, consolidated them, and properly implemented them. If he wished, the Realized One could live for the proper lifespan or what’s left of it.” ",
  "sn51.10:4.1": "But Ānanda didn’t get it, even though the Buddha dropped such an obvious hint, such a clear sign. ",
  "sn51.10:4.2": "He didn’t beg the Buddha, ",
  "sn51.10:4.3": "“Sir, may the Blessed One please remain for the proper lifespan! May the Holy One please remain for the proper lifespan! That would be for the welfare and happiness of the people, out of sympathy for the world, for the benefit, welfare, and happiness of gods and humans.” For his mind was as if possessed by Māra. ",
  "sn51.10:5.1": "For a second time … ",
  "sn51.10:5.2": "and for a third time, the Buddha said to Ānanda: ",
  "sn51.10:5.3": "“Ānanda, Vesālī is lovely. And the Udena, Gotamaka, Seven Maidens, Many Sons, Sārandada, and Cāpāla Shrines are all lovely. ",
  "sn51.10:5.4": "Whoever has developed and cultivated the four bases of psychic powermade them a vehicle and a basis, kept them up, consolidated them, and properly implemented themmay, if they wish, live for the proper lifespan or what’s left of it. ",
  "sn51.10:5.5": "The Realized One has developed and cultivated the four bases of psychic power, made them a vehicle and a basis, kept them up, consolidated them, and properly implemented them. If he wished, the Realized One could live for the proper lifespan or what’s left of it.” ",
  "sn51.10:6.1": "But Ānanda didn’t get it, even though the Buddha dropped such an obvious hint, such a clear sign. ",
  "sn51.10:6.2": "He didn’t beg the Buddha, ",
  "sn51.10:6.3": "“Sir, may the Blessed One please remain for the proper lifespan! May the Holy One please remain for the proper lifespan! That would be for the welfare and happiness of the people, out of sympathy for the world, for the benefit, welfare, and happiness of gods and humans.” For his mind was as if possessed by Māra. ",
  "sn51.10:7.1": "Then the Buddha said to him, ",
  "sn51.10:7.2": "“Go now, Ānanda, ",
  "sn51.10:7.3": "at your convenience.” ",
  "sn51.10:7.4": "“Yes, sir,” replied Ānanda. He rose from his seat, bowed, and respectfully circled the Buddha, keeping him on his right, before sitting at the root of a tree close by. ",
  "sn51.10:8.1": "And then, not long after Ānanda had left, Māra the Wicked went up to the Buddha and said to him: ",
  "sn51.10:9.1": "“Sir, may the Blessed One now be fully extinguished! May the Holy One now be fully extinguished! Now is the time for the full extinguishment of the Buddha. ",
  "sn51.10:9.2": "Sir, you once made this statement: ",
  "sn51.10:9.3": "‘Wicked One, I shall not be fully extinguished until I have monk disciples who are competent, educated, assured, learned, have memorized the teachings, and practice in line with the teaching. Not until they practice properly, living in line with the teaching. Not until they’ve learned their own tradition, and explain, teach, assert, establish, disclose, analyze, and make it clear. Not until they can legitimately and completely refute the doctrines of others that come up, and teach with a demonstrable basis.’ ",
  "sn51.10:10.1": "Today you do have such monk disciples. ",
  "sn51.10:10.2": "May the Blessed One now be fully extinguished! May the Holy One now be fully extinguished! Now is the time for the full extinguishment of the Buddha. ",
  "sn51.10:11.1": "Sir, you once made this statement: ",
  "sn51.10:11.2": "‘Wicked One, I shall not be fully extinguished until I have nun disciples who are competent, educated, assured, learned …’ … ",
  "sn51.10:12.1": "Today you do have such nun disciples. ",
  "sn51.10:12.2": "May the Blessed One now be fully extinguished! May the Holy One now be fully extinguished! Now is the time for the full extinguishment of the Buddha. ",
  "sn51.10:13.1": "Sir, you once made this statement: ",
  "sn51.10:13.2": "‘Wicked One, I shall not be fully extinguished until I have layman disciples … ",
  "sn51.10:13.3": "and laywoman disciples who are competent, educated, assured, learned …’ … ",
  "sn51.10:14.1": "Today you do have such layman ",
  "sn51.10:14.2": "and laywoman disciples. ",
  "sn51.10:14.3": "May the Blessed One now be fully extinguished! May the Holy One now be fully extinguished! Now is the time for the full extinguishment of the Buddha. ",
  "sn51.10:15.1": "Sir, you once made this statement: ",
  "sn51.10:15.2": "‘Wicked One, I shall not be fully extinguished until my spiritual path is successful and prosperous, extensive, popular, widespread, and well proclaimed wherever there are gods and humans.’ ",
  "sn51.10:15.3": "Today your spiritual path is successful and prosperous, extensive, popular, widespread, and well proclaimed wherever there are gods and humans. ",
  "sn51.10:15.4": "May the Blessed One now be fully extinguished! May the Holy One now be fully extinguished! Now is the time for the full extinguishment of the Buddha.” ",
  "sn51.10:16.1": "When this was said, the Buddha said to Māra, ",
  "sn51.10:16.2": "“Relax, Wicked One. The full extinguishment of the Realized One will be soon. ",
  "sn51.10:16.3": "Three months from now the Realized One will be fully extinguished.” ",
  "sn51.10:17.1": "So at the Cāpāla Shrine the Buddha, mindful and aware, surrendered the life force. ",
  "sn51.10:17.2": "When he did so there was a great earthquake, awe-inspiring and hair-raising, and thunder cracked the sky. ",
  "sn51.10:17.3": "Then, understanding this matter, on that occasion the Buddha expressed this heartfelt sentiment: ",
  "sn51.10:18.1": "“Comparing the incomparable <j>with the creation of prolonged life, ",
  "sn51.10:18.2": "the sage surrendered the life force. ",
  "sn51.10:18.3": "Happy inside, serene, ",
  "sn51.10:18.4": "he shattered self-creation like a suit of armor.” ",
  "sn51.10:18.5": "",
  "sn51.10:18.6": "",
  "sn51.10:19.1": "",
  "sn51.10:19.2": "",
  "sn51.10:19.3": "",
  "sn51.11:0.1": "Linked Discourses 51.11 ",
  "sn51.11:0.2": "2. Shaking the Stilt Longhouse ",
  "sn51.11:0.3": "Before ",
  "sn51.11:1.1": "At Sāvatthī. ",
  "sn51.11:1.2": "“Mendicants, before my awakeningwhen I was still unawakened but intent on awakeningI thought: ",
  "sn51.11:1.3": "‘What’s the cause, what’s the reason for the development of the bases of psychic power?’ ",
  "sn51.11:1.4": "Then it occurred to me: ",
  "sn51.11:1.5": "‘It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm, and active effort. ",
  "sn51.11:1.6": "They think: “My enthusiasm won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.” ",
  "sn51.11:1.7": "And they meditate perceiving before and behind: ",
  "sn51.11:1.8": "as before, so behind; as behind, so before; ",
  "sn51.11:1.9": "as below, so above; as above, so below; ",
  "sn51.11:1.10": "as by day, so by night; as by night, so by day. ",
  "sn51.11:1.11": "And so, with an open and unenveloped heart, they develop a mind that’s full of radiance. ",
  "sn51.11:2.1": "They develop the basis of psychic power that has immersion due to energy … ",
  "sn51.11:2.2": "",
  "sn51.11:2.3": "",
  "sn51.11:2.4": "",
  "sn51.11:2.5": "",
  "sn51.11:2.6": "",
  "sn51.11:2.7": "",
  "sn51.11:3.1": "mental development … ",
  "sn51.11:3.2": "",
  "sn51.11:3.3": "",
  "sn51.11:3.4": "",
  "sn51.11:3.5": "",
  "sn51.11:3.6": "",
  "sn51.11:3.7": "",
  "sn51.11:4.1": "inquiry, and active effort. ",
  "sn51.11:4.2": "They think: “My inquiry won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.” ",
  "sn51.11:4.3": "And they meditate perceiving before and behind: ",
  "sn51.11:4.4": "as before, so behind; as behind, so before; ",
  "sn51.11:4.5": "as below, so above; as above, so below; ",
  "sn51.11:4.6": "as by day, so by night; as by night, so by day. ",
  "sn51.11:4.7": "And so, with an open and unenveloped heart, they develop a mind that’s full of radiance.’ ",
  "sn51.11:5.1": "When the four bases of psychic power have been developed and cultivated in this way, they wield the many kinds of psychic power: multiplying themselves and becoming one again; materializing and dematerializing; going unobstructed through a wall, a rampart, or a mountain as if through space; diving in and out of the earth as if it were water; walking on water as if it were earth; flying cross-legged through the sky like a bird; touching and stroking with the hand the sun and moon, so mighty and powerful; controlling the body as far as the realm of divinity. ",
  "sn51.11:6.1": "When the four bases of psychic power have been developed and cultivated in this way, they hear both kinds of sounds, human and heavenly, whether near or far. ",
  "sn51.11:7.1": "When the four bases of psychic power have been developed and cultivated in this way, they understand the minds of other beings and individuals, having encompassed them with their own mind. ",
  "sn51.11:7.2": "They understand mind with greed as ‘mind with greed’, ",
  "sn51.11:7.3": "and mind without greed as ‘mind without greed’. ",
  "sn51.11:7.4": "They understand mind with hate … ",
  "sn51.11:7.5": "mind without hate … ",
  "sn51.11:7.6": "mind with delusion … ",
  "sn51.11:7.7": "mind without delusion … ",
  "sn51.11:7.8": "constricted mind … ",
  "sn51.11:7.9": "scattered mind … ",
  "sn51.11:7.10": "expansive mind … ",
  "sn51.11:7.11": "unexpansive mind … ",
  "sn51.11:7.12": "mind that is not supreme … ",
  "sn51.11:7.13": "mind that is supreme … ",
  "sn51.11:7.14": "mind immersed in samādhi … ",
  "sn51.11:7.15": "mind not immersed in samādhi … ",
  "sn51.11:7.16": "freed mind … ",
  "sn51.11:7.17": "They understand unfreed mind as ‘unfreed mind’. ",
  "sn51.11:8.1": "When the four bases of psychic power have been developed and cultivated in this way, they recollect many kinds of past lives. That is: one, two, three, four, five, ten, twenty, thirty, forty, fifty, a hundred, a thousand, a hundred thousand rebirths; many eons of the world contracting, many eons of the world expanding, many eons of the world contracting and expanding. They remember: ‘There, I was named this, my clan was that, I looked like this, and that was my food. This was how I felt pleasure and pain, and that was how my life ended. When I passed away from that place I was reborn somewhere else. There, too, I was named this, my clan was that, I looked like this, and that was my food. This was how I felt pleasure and pain, and that was how my life ended. When I passed away from that place I was reborn here.’ And so they recollect their many kinds of past lives, with features and details. ",
  "sn51.11:9.1": "When the four bases of psychic power have been developed and cultivated in this way, with clairvoyance that is purified and superhuman, they see sentient beings passing away and being reborninferior and superior, beautiful and ugly, in a good place or a bad place. They understand how sentient beings pass on according to their deeds. ‘These dear beings did bad things by way of body, speech, and mind. They denounced the noble ones; they had wrong view; and they chose to act out of that wrong view. When their body breaks up, after death, they’re reborn in a place of loss, a bad place, the underworld, hell. These dear beings, however, did good things by way of body, speech, and mind. They never denounced the noble ones; they had right view; and they chose to act out of that right view. When their body breaks up, after death, they’re reborn in a good place, a heavenly realm.’ And so, with clairvoyance that is purified and superhuman, they see sentient beings passing away and being reborninferior and superior, beautiful and ugly, in a good place or a bad place. They understand how sentient beings pass on according to their deeds. ",
  "sn51.11:10.1": "When the four bases of psychic power have been developed and cultivated in this way, they realize the undefiled freedom of heart and freedom by wisdom in this very life. And they live having realized it with their own insight due to the ending of defilements.” ",
  "sn51.12:0.1": "Linked Discourses 51.12 ",
  "sn51.12:0.2": "2. Shaking the Stilt Longhouse ",
  "sn51.12:0.3": "Very Fruitful ",
  "sn51.12:1.1": "“Mendicants, when the four bases of psychic power are developed and cultivated they’re very fruitful and beneficial. ",
  "sn51.12:1.2": "How so? ",
  "sn51.12:1.3": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm, and active effort. ",
  "sn51.12:1.4": "They think: ‘My enthusiasm won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.’ ",
  "sn51.12:1.5": "And they meditate perceiving before and behind: ",
  "sn51.12:1.6": "as before, so behind; as behind, so before; ",
  "sn51.12:1.7": "as below, so above; as above, so below; ",
  "sn51.12:1.8": "as by day, so by night; as by night, so by day. ",
  "sn51.12:1.9": "And so, with an open and unenveloped heart, they develop a mind that’s full of radiance. ",
  "sn51.12:2.1": "They develop the basis of psychic power that has immersion due to energy … ",
  "sn51.12:2.2": "mental development … ",
  "sn51.12:2.3": "inquiry, and active effort. ",
  "sn51.12:2.4": "They think: ‘My inquiry won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.’ ",
  "sn51.12:2.5": "And they meditate perceiving before and behind: ",
  "sn51.12:2.6": "as before, so behind; as behind, so before; ",
  "sn51.12:2.7": "as below, so above; as above, so below; ",
  "sn51.12:2.8": "as by day, so by night; as by night, so by day. ",
  "sn51.12:2.9": "And so, with an open and unenveloped heart, they develop a mind that’s full of radiance. ",
  "sn51.12:2.10": "When the four bases of psychic power have been developed and cultivated in this way they’re very fruitful and beneficial. ",
  "sn51.12:3.1": "When the four bases of psychic power have been developed and cultivated in this way, a mendicant wields the many kinds of psychic power: multiplying themselves and becoming one again … controlling the body as far as the realm of divinity. … ",
  "sn51.12:4.1": "When the four bases of psychic power have been developed and cultivated in this way, they realize the undefiled freedom of heart and freedom by wisdom in this very life. And they live having realized it with their own insight due to the ending of defilements.” ",
  "sn51.13:0.1": "Linked Discourses 51.13 ",
  "sn51.13:0.2": "2. Shaking the Stilt Longhouse ",
  "sn51.13:0.3": "Immersion Due to Enthusiasm ",
  "sn51.13:1.1": "“Mendicants, if a mendicant depends on enthusiasm in order to gain immersion, gain unification of mind, ",
  "sn51.13:1.2": "this is called immersion due to enthusiasm. ",
  "sn51.13:1.3": "They generate enthusiasm, try, make an effort, exert the mind, and strive so that bad, unskillful qualities don’t arise. ",
  "sn51.13:1.4": "They generate enthusiasm, try, make an effort, exert the mind, and strive so that bad, unskillful qualities that have arisen are given up. ",
  "sn51.13:1.5": "They generate enthusiasm, try, make an effort, exert the mind, and strive so that skillful qualities arise. ",
  "sn51.13:1.6": "They generate enthusiasm, try, make an effort, exert the mind, and strive so that skillful qualities that have arisen remain, are not lost, but increase, mature, and are fulfilled by development. ",
  "sn51.13:1.7": "These are called active efforts. ",
  "sn51.13:1.8": "And so there is this enthusiasm, this immersion due to enthusiasm, and these active efforts. ",
  "sn51.13:1.9": "This is called the basis of psychic power that has immersion due to enthusiasm, and active effort. ",
  "sn51.13:2.1": "If a mendicant depends on energy in order to gain immersion, gain unification of mind, ",
  "sn51.13:2.2": "this is called immersion due to energy. ",
  "sn51.13:2.3": "They generate enthusiasm, try, make an effort, exert the mind, and strive so that bad, unskillful qualities don’t arise … ",
  "sn51.13:2.4": "so that skillful qualities that have arisen remain, are not lost, but increase, mature, and are fulfilled by development. ",
  "sn51.13:2.5": "These are called active efforts. ",
  "sn51.13:2.6": "And so there is this energy, this immersion due to energy, and these active efforts. ",
  "sn51.13:2.7": "This is called the basis of psychic power that has immersion due to energy, and active effort. ",
  "sn51.13:3.1": "If a mendicant depends on mental development in order to gain immersion, gain unification of mind, ",
  "sn51.13:3.2": "this is called immersion due to mental development. ",
  "sn51.13:3.3": "They generate enthusiasm, try, make an effort, exert the mind, and strive so that bad, unskillful qualities don’t arise … ",
  "sn51.13:3.4": "so that skillful qualities that have arisen remain, are not lost, but increase, mature, and are fulfilled by development. ",
  "sn51.13:3.5": "These are called active efforts. ",
  "sn51.13:3.6": "And so there is this mental development, this immersion due to mental development, and these active efforts. ",
  "sn51.13:3.7": "This is called the basis of psychic power that has immersion due to mental development, and active effort. ",
  "sn51.13:4.1": "If a mendicant depends on inquiry in order to gain immersion, gain unification of mind, ",
  "sn51.13:4.2": "this is called immersion due to inquiry. ",
  "sn51.13:4.3": "They generate enthusiasm, try, make an effort, exert the mind, and strive so that bad, unskillful qualities don’t arise … ",
  "sn51.13:4.4": "so that skillful qualities that have arisen remain, are not lost, but increase, mature, and are fulfilled by development. ",
  "sn51.13:4.5": "These are called active efforts. ",
  "sn51.13:4.6": "And so there is this inquiry, this immersion due to inquiry, and these active efforts. ",
  "sn51.13:4.7": "This is called the basis of psychic power that has immersion due to inquiry, and active effort.” ",
  "sn51.14:0.1": "Linked Discourses 51.14 ",
  "sn51.14:0.2": "2. Shaking the Stilt Longhouse ",
  "sn51.14:0.3": "With Moggallāna ",
  "sn51.14:1.1": "So I have heard. ",
  "sn51.14:1.2": "At one time the Buddha was staying near Sāvatthī in the stilt longhouse of Migāra’s mother in the Eastern Monastery. ",
  "sn51.14:1.3": "Now at that time several mendicants were staying beneath the longhouse. They were restless, insolent, fickle, scurrilous, loose-tongued, unmindful, lacking situational awareness and immersion, with straying minds and undisciplined faculties. ",
  "sn51.14:2.1": "Then the Buddha addressed Venerable Mahāmoggallāna, ",
  "sn51.14:2.2": "“These spiritual companions of yours staying beneath the longhouse are restless, insolent, fickle, scurrilous, loose-tongued, unmindful, lacking situational awareness and immersion, with straying minds and undisciplined faculties. ",
  "sn51.14:2.3": "Go, Moggallāna, and strike awe in those mendicants!” ",
  "sn51.14:3.1": "“Yes, sir,” replied Mahāmoggallāna. Then he used his psychic power to make the longhouse shake and rock and tremble with his big toe. ",
  "sn51.14:3.2": "Then those mendicants stood to one side, shocked and awestruck. ",
  "sn51.14:3.3": "“Oh lord, how incredible, how amazing! ",
  "sn51.14:3.4": "There’s no wind at all; and this stilt longhouse of Migāra’s mother has deep foundations. It’s firmly embedded, imperturbable and unshakable. And yet it shakes and rocks and trembles!” ",
  "sn51.14:4.1": "Then the Buddha went up to those mendicants and said: ",
  "sn51.14:4.2": "“Why do you, mendicants, stand to one side, shocked and awestruck?” ",
  "sn51.14:4.3": "“It’s incredible, sir, it’s amazing! ",
  "sn51.14:4.4": "There’s no wind at all; and this stilt longhouse of Migāra’s mother has deep foundations. It’s firmly embedded, imperturbable and unshakable. And yet it shakes and rocks and trembles!” ",
  "sn51.14:4.5": "“Wanting to strike awe in you, the mendicant Moggallāna made the longhouse shake and rock and tremble with his big toe. ",
  "sn51.14:4.6": "What do you think, mendicants? ",
  "sn51.14:4.7": "What things has the mendicant Moggallāna developed and cultivated so as to have such power and might?” ",
  "sn51.14:4.8": "“Our teachings are rooted in the Buddha. He is our guide and our refuge. Sir, may the Buddha himself please clarify the meaning of this. The mendicants will listen and remember it.” ",
  "sn51.14:5.1": "“Well then, mendicants, listen. ",
  "sn51.14:5.2": "The mendicant Moggallāna has become so powerful and mighty by developing and cultivating the four bases of psychic power. ",
  "sn51.14:5.3": "What four? ",
  "sn51.14:5.4": "Moggallāna develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.14:5.5": "energy … ",
  "sn51.14:5.6": "mental development … ",
  "sn51.14:5.7": "inquiry, and active effort. ",
  "sn51.14:5.8": "He thinks: ‘My inquiry won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.’ ",
  "sn51.14:5.9": "",
  "sn51.14:5.10": "And he meditates perceiving before and behind: ",
  "sn51.14:5.11": "as before, so behind; as behind, so before; ",
  "sn51.14:5.12": "as below, so above; as above, so below; ",
  "sn51.14:5.13": "as by day, so by night; as by night, so by day. ",
  "sn51.14:5.14": "And so, with an open and unenveloped heart, he develops a mind that’s full of radiance. ",
  "sn51.14:5.15": "The mendicant Moggallāna has become so powerful and mighty by developing and cultivating these four bases of psychic power. ",
  "sn51.14:5.16": "And by developing and cultivating these four bases of psychic power, the mendicant Moggallāna wields the many kinds of psychic power … controlling the body as far as the realm of divinity. … ",
  "sn51.14:5.17": "And by developing and cultivating these four bases of psychic power, the mendicant Moggallāna realizes the undefiled freedom of heart and freedom by wisdom in this very life. And he lives having realized it with his own insight due to the ending of defilements.” ",
  "sn51.15:0.1": "Linked Discourses 51.15 ",
  "sn51.15:0.2": "2. Shaking the Stilt Longhouse ",
  "sn51.15:0.3": "The Brahmin Uṇṇābha ",
  "sn51.15:1.1": "So I have heard. ",
  "sn51.15:1.2": "At one time Venerable Ānanda was staying near Kosambī, in Ghosita’s Monastery. ",
  "sn51.15:1.3": "Then Uṇṇābha the brahmin went up to Venerable Ānanda, and exchanged greetings with him. ",
  "sn51.15:1.4": "When the greetings and polite conversation were over, he sat down to one side and said to him, ",
  "sn51.15:1.5": "“Worthy Ānanda, what’s the goal of leading the spiritual life under the ascetic Gotama?” ",
  "sn51.15:1.6": "“The goal of leading the spiritual life under the Buddha, brahmin, is to give up desire.” ",
  "sn51.15:2.1": "“But is there a path and a practice for giving up that desire?” ",
  "sn51.15:2.2": "“There is.” ",
  "sn51.15:3.1": "“What is that path?” ",
  "sn51.15:3.2": "“It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.15:3.3": "energy … ",
  "sn51.15:3.4": "mental development … ",
  "sn51.15:3.5": "inquiry, and active effort. ",
  "sn51.15:3.6": "This is the path and the practice for giving up that desire.” ",
  "sn51.15:4.1": "“This being the case, worthy Ānanda, the path is endless, not finite. ",
  "sn51.15:4.2": "For it’s not possible to give up desire by means of desire.” ",
  "sn51.15:4.3": "“Well then, brahmin, I’ll ask you about this in return, and you can answer as you like. ",
  "sn51.15:4.4": "What do you think, brahmin? ",
  "sn51.15:4.5": "Have you ever had a desire to walk to the park, ",
  "sn51.15:4.6": "but when you arrived at the park, the corresponding desire faded away?” ",
  "sn51.15:4.7": "“Yes, sir.” ",
  "sn51.15:4.8": "“Have you ever had the energy to walk to the park, ",
  "sn51.15:4.9": "but when you arrived at the park, the corresponding energy faded away?” ",
  "sn51.15:4.10": "“Yes, sir.” ",
  "sn51.15:4.11": "“Have you ever had the idea to walk to the park, ",
  "sn51.15:4.12": "but when you arrived at the park, the corresponding idea faded away?” ",
  "sn51.15:4.13": "“Yes, sir.” ",
  "sn51.15:4.14": "“Have you ever inquired regarding a walk to the park, ",
  "sn51.15:4.15": "but when you arrived at the park, the corresponding inquiry faded away?” ",
  "sn51.15:4.16": "“Yes, sir.” ",
  "sn51.15:5.1": "“In the same way, take a mendicant who is perfectedwith defilements ended, who has completed the spiritual journey, done what had to be done, laid down the burden, achieved their heart’s goal, utterly ended the fetter of continued existence, and is rightly freed through enlightenment. They formerly had the desire to attain perfection, but when they attained perfection the corresponding desire faded away. ",
  "sn51.15:5.2": "They formerly had the energy to attain perfection, but when they attained perfection the corresponding energy faded away. ",
  "sn51.15:5.3": "They formerly had the idea to attain perfection, but when they attained perfection the corresponding idea faded away. ",
  "sn51.15:5.4": "They formerly inquired regarding attaining perfection, but when they attained perfection the corresponding inquiry faded away. ",
  "sn51.15:5.5": "What do you think, brahmin? ",
  "sn51.15:5.6": "This being the case, is the path endless or finite?” ",
  "sn51.15:6.1": "“Clearly, worthy Ānanda, this being the case, the path is finite, not endless. ",
  "sn51.15:6.2": "Excellent, worthy Ānanda! Excellent! ",
  "sn51.15:6.3": "As if he were righting the overturned, or revealing the hidden, or pointing out the path to the lost, or lighting a lamp in the dark so people with clear eyes can see what’s there, the worthy Ānanda has made the teaching clear in many ways. ",
  "sn51.15:6.4": "I go for refuge to the worthy Gotama, to the teaching, and to the mendicant Saṅgha. ",
  "sn51.15:6.5": "From this day forth, may the worthy Ānanda remember me as a lay follower who has gone for refuge for life.” ",
  "sn51.16:0.1": "Linked Discourses 51.16 ",
  "sn51.16:0.2": "2. Shaking the Stilt Longhouse ",
  "sn51.16:0.3": "Ascetics and Brahmins (1st) ",
  "sn51.16:1.1": "“Mendicants, all the ascetics and brahmins in the past, ",
  "sn51.16:1.2": "future, ",
  "sn51.16:1.3": "or present who are mighty and powerful have become so by developing and cultivating the four bases of psychic power. ",
  "sn51.16:2.1": "What four? ",
  "sn51.16:2.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.16:2.3": "energy … ",
  "sn51.16:2.4": "mental development … ",
  "sn51.16:2.5": "inquiry, and active effort. ",
  "sn51.16:2.6": "All the ascetics and brahmins in the past, ",
  "sn51.16:2.7": "future, ",
  "sn51.16:2.8": "or present who are mighty and powerful have become so by developing and cultivating the four bases of psychic power.” ",
  "sn51.17:0.1": "Linked Discourses 51.17 ",
  "sn51.17:0.2": "2. Shaking the Stilt Longhouse ",
  "sn51.17:0.3": "Ascetics and Brahmins (2nd) ",
  "sn51.17:1.1": "“Mendicants, all the ascetics and brahmins in the past, ",
  "sn51.17:1.2": "",
  "sn51.17:2.1": "future, ",
  "sn51.17:2.2": "",
  "sn51.17:3.1": "or present who wield the various kinds of psychic powermultiplying themselves and becoming one again; materializing and dematerializing; going unobstructed through a wall, a rampart, or a mountain as if through space; diving in and out of the earth as if it were water; walking on water as if it were earth; flying cross-legged through the sky like a bird; touching and stroking with the hand the sun and moon, so mighty and powerful; controlling their body as far as the realm of divinity",
  "sn51.17:3.2": "do so by developing and cultivating the four bases of psychic power. ",
  "sn51.17:4.1": "What four? ",
  "sn51.17:4.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.17:4.3": "energy … ",
  "sn51.17:4.4": "mental development … ",
  "sn51.17:4.5": "inquiry, and active effort. ",
  "sn51.17:4.6": "Mendicants, all the ascetics and brahmins in the past, ",
  "sn51.17:4.7": "",
  "sn51.17:5.1": "future, ",
  "sn51.17:5.2": "",
  "sn51.17:6.1": "or present who wield the many kinds of psychic powermultiplying themselves and becoming one again … controlling their body as far as the realm of divinity",
  "sn51.17:6.2": "do so by developing and cultivating these four bases of psychic power.” ",
  "sn51.18:0.1": "Linked Discourses 51.18 ",
  "sn51.18:0.2": "2. Shaking the Stilt Longhouse ",
  "sn51.18:0.3": "A Mendicant ",
  "sn51.18:1.1": "“Mendicants, by developing and cultivating the four bases of psychic power, a mendicant realizes the undefiled freedom of heart and freedom by wisdom in this very life. And they live having realized it with their own insight due to the ending of defilements. ",
  "sn51.18:2.1": "What four? ",
  "sn51.18:2.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.18:2.3": "energy … ",
  "sn51.18:2.4": "mental development … ",
  "sn51.18:2.5": "inquiry, and active effort. ",
  "sn51.18:2.6": "By developing and cultivating these four bases of psychic power, a mendicant realizes the undefiled freedom of heart and freedom by wisdom in this very life. And they live having realized it with their own insight due to the ending of defilements.” ",
  "sn51.19:0.1": "Linked Discourses 51.19 ",
  "sn51.19:0.2": "2. Shaking the Stilt Longhouse ",
  "sn51.19:0.3": "A Teaching on Psychic Power, Etc. ",
  "sn51.19:1.1": "“Mendicants, I will teach you psychic power, the bases of psychic power, the development of the bases of psychic power, and the practice that leads to the development of the bases of psychic power. ",
  "sn51.19:1.2": "Listen … ",
  "sn51.19:2.1": "And what is psychic power? ",
  "sn51.19:2.2": "It’s when a mendicant wields the many kinds of psychic power: multiplying themselves and becoming one again … controlling the body as far as the realm of divinity. ",
  "sn51.19:2.3": "This is called psychic power. ",
  "sn51.19:3.1": "And what is the basis of psychic power? ",
  "sn51.19:3.2": "The path and practice that leads to gaining psychic power. ",
  "sn51.19:3.3": "This is called the basis of psychic power. ",
  "sn51.19:4.1": "And what is the development of the bases of psychic power? ",
  "sn51.19:4.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.19:4.3": "energy … ",
  "sn51.19:4.4": "mental development … ",
  "sn51.19:4.5": "inquiry, and active effort. ",
  "sn51.19:4.6": "This is called the development of the bases of psychic power. ",
  "sn51.19:5.1": "And what is the practice that leads to the development of the bases of psychic power? ",
  "sn51.19:5.2": "It is simply this noble eightfold path, that is: ",
  "sn51.19:5.3": "right view, right purpose, right speech, right action, right livelihood, right effort, right mindfulness, and right immersion. ",
  "sn51.19:5.4": "This is called the practice that leads to the development of the bases of psychic power.” ",
  "sn51.20:0.1": "Linked Discourses 51.20 ",
  "sn51.20:0.2": "2. Shaking the Stilt Longhouse ",
  "sn51.20:0.3": "Analysis ",
  "sn51.20:1.1": "“Mendicants, when the four bases of psychic power are developed and cultivated they’re very fruitful and beneficial. ",
  "sn51.20:2.1": "How so? ",
  "sn51.20:2.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm, and active effort. ",
  "sn51.20:2.3": "They think: ‘My enthusiasm won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.’ ",
  "sn51.20:2.4": "And they meditate perceiving before and behind: ",
  "sn51.20:2.5": "as before, so behind; as behind, so before; ",
  "sn51.20:2.6": "as below, so above; as above, so below; ",
  "sn51.20:2.7": "as by day, so by night; as by night, so by day. ",
  "sn51.20:2.8": "And so, with an open and unenveloped heart, they develop a mind that’s full of radiance. ",
  "sn51.20:2.9": "They develop the basis of psychic power that has immersion due to energy … ",
  "sn51.20:2.10": "mental development … ",
  "sn51.20:2.11": "inquiry, and active effort. ",
  "sn51.20:2.12": "They think: ‘My inquiry won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.’ ",
  "sn51.20:2.13": "And they meditate perceiving before and behind: ",
  "sn51.20:2.14": "as before, so behind; as behind, so before; ",
  "sn51.20:2.15": "as below, so above; as above, so below; ",
  "sn51.20:2.16": "as by day, so by night; as by night, so by day. ",
  "sn51.20:2.17": "And so, with an open and unenveloped heart, they develop a mind that’s full of radiance. ",
  "sn51.20:3.1": "And what is enthusiasm that’s too lax? ",
  "sn51.20:3.2": "It’s when enthusiasm is coupled with laziness. ",
  "sn51.20:3.3": "This is called lax enthusiasm. ",
  "sn51.20:4.1": "And what is enthusiasm that’s too tense? ",
  "sn51.20:4.2": "It’s when enthusiasm is coupled with restlessness. ",
  "sn51.20:4.3": "This is called tense enthusiasm. ",
  "sn51.20:5.1": "And what is enthusiasm that’s constricted internally? ",
  "sn51.20:5.2": "It’s when enthusiasm is coupled with dullness and drowsiness. ",
  "sn51.20:5.3": "This is called enthusiasm constricted internally. ",
  "sn51.20:6.1": "And what is enthusiasm that’s scattered externally? ",
  "sn51.20:6.2": "It’s when enthusiasm is frequently scattered and diffused externally on account of the five kinds of sensual stimulation. ",
  "sn51.20:6.3": "This is called enthusiasm scattered externally. ",
  "sn51.20:7.1": "And how does a mendicant meditate perceiving before and behind: ",
  "sn51.20:7.2": "as before, so behind; as behind, so before? ",
  "sn51.20:7.3": "It’s when the perception of before and behind is properly grasped, focused on, borne in mind, and penetrated with wisdom by a mendicant. ",
  "sn51.20:7.4": "That’s how a mendicant meditates perceiving before and behind: ",
  "sn51.20:7.5": "as before, so behind; as behind, so before. ",
  "sn51.20:8.1": "And how does a mendicant meditate as below, so above; as above, so below? ",
  "sn51.20:8.2": "It’s when a mendicant examines their own body up from the soles of the feet and down from the tips of the hairs, wrapped in skin and full of many kinds of filth. ",
  "sn51.20:8.3": "‘In this body there is head hair, body hair, nails, teeth, skin, flesh, sinews, bones, bone marrow, kidneys, heart, liver, diaphragm, spleen, lungs, intestines, mesentery, undigested food, feces, bile, phlegm, pus, blood, sweat, fat, tears, grease, saliva, snot, synovial fluid, urine.’ ",
  "sn51.20:8.4": "That’s how a mendicant meditates as below, so above; as above, so below. ",
  "sn51.20:9.1": "And how does a mendicant meditate as by day, so by night; as by night, so by day? ",
  "sn51.20:9.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm, and active effort, with the same features, attributes, and signs by day as by night. ",
  "sn51.20:9.3": "And they develop it with the same features, attributes, and signs by night as by day. ",
  "sn51.20:9.4": "That’s how a mendicant meditates as by day, so by night; as by night, so by day. ",
  "sn51.20:10.1": "And how, with an open and unenveloped heart, does a mendicant develop a mind that’s full of radiance? ",
  "sn51.20:10.2": "It’s when a mendicant has properly grasped the perception of light, and has properly grasped the perception of day. ",
  "sn51.20:10.3": "That’s how, with an open and unenveloped heart, a mendicant develops a mind that’s full of radiance. ",
  "sn51.20:11.1": "And what is energy that’s too lax? … ",
  "sn51.20:11.2": "",
  "sn51.20:11.3": "",
  "sn51.20:12.1": "",
  "sn51.20:12.2": "",
  "sn51.20:12.3": "",
  "sn51.20:13.1": "",
  "sn51.20:13.2": "",
  "sn51.20:13.3": "",
  "sn51.20:14.1": "",
  "sn51.20:14.2": "",
  "sn51.20:15.1": "",
  "sn51.20:15.2": "",
  "sn51.20:15.3": "",
  "sn51.20:16.1": "And what is mental development that’s too lax? … ",
  "sn51.20:16.2": "",
  "sn51.20:16.3": "",
  "sn51.20:17.1": "",
  "sn51.20:17.2": "",
  "sn51.20:17.3": "",
  "sn51.20:18.1": "",
  "sn51.20:18.2": "",
  "sn51.20:18.3": "",
  "sn51.20:19.1": "",
  "sn51.20:19.2": "",
  "sn51.20:19.3": "",
  "sn51.20:19.4": "",
  "sn51.20:20.1": "And what is inquiry that’s too lax? ",
  "sn51.20:20.2": "It’s when inquiry is coupled with laziness. ",
  "sn51.20:20.3": "This is called lax inquiry. ",
  "sn51.20:21.1": "And what is inquiry that’s too tense? ",
  "sn51.20:21.2": "It’s when inquiry is coupled with restlessness. ",
  "sn51.20:21.3": "This is called tense inquiry. ",
  "sn51.20:22.1": "And what is inquiry that’s constricted internally? ",
  "sn51.20:22.2": "It’s when inquiry is coupled with dullness and drowsiness. ",
  "sn51.20:22.3": "This is called inquiry constricted internally. ",
  "sn51.20:23.1": "And what is inquiry that’s scattered externally? ",
  "sn51.20:23.2": "It’s when inquiry is frequently scattered and diffused externally on account of the five kinds of sensual stimulation. ",
  "sn51.20:23.3": "This is called inquiry scattered externally. … ",
  "sn51.20:23.4": "That’s how, with an open and unenveloped heart, a mendicant develops a mind that’s full of radiance. ",
  "sn51.20:23.5": "When the four bases of psychic power have been developed and cultivated in this way they’re very fruitful and beneficial. ",
  "sn51.20:24.1": "When the four bases of psychic power have been developed and cultivated in this way, a mendicant wields the many kinds of psychic power: multiplying themselves and becoming one again … controlling the body as far as the realm of divinity. ",
  "sn51.20:24.2": "When the four bases of psychic power have been developed and cultivated in this way, they realize the undefiled freedom of heart and freedom by wisdom in this very life. And they live having realized it with their own insight due to the ending of defilements.” ",
  "sn51.20:24.3": "",
  "sn51.20:24.4": "",
  "sn51.20:25.1": "",
  "sn51.20:25.2": "",
  "sn51.20:25.3": "",
  "sn51.21:0.1": "Linked Discourses 51.21 ",
  "sn51.21:0.2": "3. The Iron Ball ",
  "sn51.21:0.3": "The Path ",
  "sn51.21:1.1": "At Sāvatthī. ",
  "sn51.21:1.2": "“Mendicants, before my awakeningwhen I was still unawakened but intent on awakeningI thought: ",
  "sn51.21:1.3": "‘What’s the path and practice for developing the bases of psychic power?’ ",
  "sn51.21:1.4": "Then it occurred to me: ",
  "sn51.21:1.5": "‘It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm, and active effort. ",
  "sn51.21:1.6": "They think: “My enthusiasm won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.” ",
  "sn51.21:1.7": "And they meditate perceiving before and behind: ",
  "sn51.21:1.8": "as before, so behind; as behind, so before; ",
  "sn51.21:1.9": "as below, so above; as above, so below; ",
  "sn51.21:1.10": "as by day, so by night; as by night, so by day. ",
  "sn51.21:1.11": "And so, with an open and unenveloped heart, they develop a mind that’s full of radiance. ",
  "sn51.21:1.12": "They develop the basis of psychic power that has immersion due to energy … ",
  "sn51.21:1.13": "mental development … ",
  "sn51.21:1.14": "inquiry, and active effort. ",
  "sn51.21:1.15": "They think: “My inquiry won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.” ",
  "sn51.21:1.16": "And they meditate perceiving before and behind: ",
  "sn51.21:1.17": "as before, so behind; as behind, so before; ",
  "sn51.21:1.18": "as below, so above; as above, so below; ",
  "sn51.21:1.19": "as by day, so by night; as by night, so by day. ",
  "sn51.21:1.20": "And so, with an open and unenveloped heart, they develop a mind that’s full of radiance.’ ",
  "sn51.21:2.1": "When the four bases of psychic power have been developed and cultivated in this way, a mendicant wields the many kinds of psychic power: multiplying themselves and becoming one again … controlling the body as far as the realm of divinity. ",
  "sn51.21:2.2": "When the four bases of psychic power have been developed and cultivated in this way, they realize the undefiled freedom of heart and freedom by wisdom in this very life. And they live having realized it with their own insight due to the ending of defilements.” ",
  "sn51.21:2.3": "",
  "sn51.21:2.4": "(The six direct knowledges should be told in full.) ",
  "sn51.22:0.1": "Linked Discourses 51.22 ",
  "sn51.22:0.2": "3. The Iron Ball ",
  "sn51.22:0.3": "The Iron Ball ",
  "sn51.22:1.1": "At Sāvatthī. ",
  "sn51.22:1.2": "Then Venerable Ānanda went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn51.22:1.3": "“Sir, do you have personal experience of going to the realm of divinity by psychic power with a mind-made body?” ",
  "sn51.22:1.4": "“I do, Ānanda.” ",
  "sn51.22:1.5": "“But do you have personal experience of going to the realm of divinity by psychic power with this body made up of the four principal states?” ",
  "sn51.22:1.6": "“I do, Ānanda.” ",
  "sn51.22:2.1": "“It’s incredible and amazing that the Buddha is capable of going to the realm of divinity by psychic power with a mind-made body! And that he has personal experience of going to the realm of divinity by psychic power with this body made up of the four principal states!” ",
  "sn51.22:2.2": "“Ānanda, the Realized Ones are incredible and have incredible qualities. They’re amazing and have amazing qualities. ",
  "sn51.22:3.1": "Sometimes the Realized One submerges his body in his mind and his mind in his body. He meditates after sinking into a perception of bliss and lightness in the body. ",
  "sn51.22:3.2": "At that time his body becomes lighter, softer, more workable, and more radiant. ",
  "sn51.22:4.1": "Suppose there was an iron ball that had been heated all day. It’d become lighter, softer, more workable, and more radiant. ",
  "sn51.22:4.2": "In the same way, sometimes the Realized One submerges his body in his mind and his mind in his body. He meditates after sinking into a perception of bliss and lightness in the body. ",
  "sn51.22:4.3": "At that time his body becomes lighter, softer, more workable, and more radiant. ",
  "sn51.22:5.1": "Sometimes the Realized One submerges his body in his mind and his mind in his body. He meditates after sinking into a perception of bliss and lightness in the body. ",
  "sn51.22:5.2": "At that time his body easily rises up from the ground into the air. ",
  "sn51.22:5.3": "He wields the many kinds of psychic power: multiplying himself and becoming one again … controlling the body as far as the realm of divinity. ",
  "sn51.22:6.1": "Suppose there was a light tuft of cotton-wool or kapok. Taken up by the wind, it would easily rise up from the ground into the air. ",
  "sn51.22:6.2": "In the same way, sometimes the Realized One submerges his body in his mind and his mind in his body. He meditates after sinking into a perception of bliss and lightness in the body. ",
  "sn51.22:6.3": "At that time his body easily rises up from the ground into the air. ",
  "sn51.22:6.4": "He wields the many kinds of psychic power: multiplying himself and becoming one again … controlling the body as far as the realm of divinity.” ",
  "sn51.23:0.1": "Linked Discourses 51.23 ",
  "sn51.23:0.2": "3. The Iron Ball ",
  "sn51.23:0.3": "A Mendicant ",
  "sn51.23:1.1": "“Mendicants, there are these four bases of psychic power. ",
  "sn51.23:1.2": "What four? ",
  "sn51.23:1.3": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.23:1.4": "energy … ",
  "sn51.23:1.5": "mental development … ",
  "sn51.23:1.6": "inquiry, and active effort. ",
  "sn51.23:1.7": "These are the four bases of psychic power. ",
  "sn51.23:1.8": "By developing and cultivating these four bases of psychic power, a mendicant realizes the undefiled freedom of heart and freedom by wisdom in this very life. And they live having realized it with their own insight due to the ending of defilements.” ",
  "sn51.24:0.1": "Linked Discourses 51.24 ",
  "sn51.24:0.2": "3. The Iron Ball ",
  "sn51.24:0.3": "Plain Version ",
  "sn51.24:1.1": "“Mendicants, there are these four bases of psychic power. ",
  "sn51.24:1.2": "What four? ",
  "sn51.24:1.3": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.24:1.4": "energy … ",
  "sn51.24:1.5": "mental development … ",
  "sn51.24:1.6": "inquiry, and active effort. ",
  "sn51.24:1.7": "These are the four bases of psychic power.” ",
  "sn51.25:0.1": "Linked Discourses 51.25 ",
  "sn51.25:0.2": "3. The Iron Ball ",
  "sn51.25:0.3": "Fruits (1st) ",
  "sn51.25:1.1": "“Mendicants, there are these four bases of psychic power. ",
  "sn51.25:1.2": "What four? ",
  "sn51.25:1.3": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.25:1.4": "energy … ",
  "sn51.25:1.5": "mental development … ",
  "sn51.25:1.6": "inquiry, and active effort. ",
  "sn51.25:1.7": "These are the four bases of psychic power. ",
  "sn51.25:1.8": "Because of developing and cultivating these four bases of psychic power, one of two results can be expected: ",
  "sn51.25:1.9": "enlightenment in this very life, or if there’s residue left behind, non-return.” ",
  "sn51.26:0.1": "Linked Discourses 51.26 ",
  "sn51.26:0.2": "3. The Iron Ball ",
  "sn51.26:0.3": "Fruits (2nd) ",
  "sn51.26:1.1": "“Mendicants, there are these four bases of psychic power. ",
  "sn51.26:1.2": "What four? ",
  "sn51.26:1.3": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.26:1.4": "energy … ",
  "sn51.26:1.5": "mental development … ",
  "sn51.26:1.6": "inquiry, and active effort. ",
  "sn51.26:1.7": "These are the four bases of psychic power. ",
  "sn51.26:1.8": "Because of developing and cultivating these four bases of psychic power, seven fruits and benefits can be expected. ",
  "sn51.26:2.1": "What seven? ",
  "sn51.26:2.2": "They attain enlightenment early on in this very life. ",
  "sn51.26:2.3": "If not, they attain enlightenment at the time of death. ",
  "sn51.26:2.4": "If not, with the ending of the five lower fetters, they’re extinguished between one life and the next … they’re extinguished upon landing … they’re extinguished without extra effort … they’re extinguished with extra effort … they head upstream, going to the Akaniṭṭha realm. ",
  "sn51.26:2.5": "Because of developing and cultivating these four bases of psychic power, these seven fruits and benefits can be expected.” ",
  "sn51.27:0.1": "Linked Discourses 51.27 ",
  "sn51.27:0.2": "3. The Iron Ball ",
  "sn51.27:0.3": "With Ānanda (1st) ",
  "sn51.27:1.1": "At Sāvatthī. ",
  "sn51.27:1.2": "Then Venerable Ānanda went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn51.27:2.1": "“Sir, what is psychic power? What is the basis of psychic power? What is the development of the bases of psychic power? And what is the practice that leads to the development of the bases of psychic power?” ",
  "sn51.27:2.2": "“Ānanda, take a mendicant who wields the many kinds of psychic power: multiplying themselves and becoming one again … controlling the body as far as the realm of divinity. ",
  "sn51.27:2.3": "This is called psychic power. ",
  "sn51.27:3.1": "And what is the basis of psychic power? ",
  "sn51.27:3.2": "The path and practice that leads to gaining psychic power. ",
  "sn51.27:3.3": "This is called the basis of psychic power. ",
  "sn51.27:4.1": "And what is the development of the bases of psychic power? ",
  "sn51.27:4.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.27:4.3": "energy … ",
  "sn51.27:4.4": "mental development … ",
  "sn51.27:4.5": "inquiry, and active effort. ",
  "sn51.27:4.6": "This is called the development of the bases of psychic power. ",
  "sn51.27:5.1": "And what is the practice that leads to the development of the bases of psychic power? ",
  "sn51.27:5.2": "It is simply this noble eightfold path, that is: ",
  "sn51.27:5.3": "right view, right purpose, right speech, right action, right livelihood, right effort, right mindfulness, and right immersion. ",
  "sn51.27:5.4": "This is called the practice that leads to the development of the bases of psychic power.” ",
  "sn51.28:0.1": "Linked Discourses 51.28 ",
  "sn51.28:0.2": "3. The Iron Ball ",
  "sn51.28:0.3": "With Ānanda (2nd) ",
  "sn51.28:1.1": "The Buddha said to Venerable Ānanda: ",
  "sn51.28:1.2": "“Ānanda, what is psychic power? What is the basis of psychic power? What is the development of the bases of psychic power? And what is the practice that leads to the development of the bases of psychic power?” ",
  "sn51.28:1.3": "“Our teachings are rooted in the Buddha. He is our guide and our refuge. …” ",
  "sn51.28:2.1": "“Ānanda, take a mendicant who wields the many kinds of psychic power: multiplying themselves and becoming one again … controlling the body as far as the realm of divinity. ",
  "sn51.28:2.2": "This is called psychic power. ",
  "sn51.28:3.1": "And what is the basis of psychic power? ",
  "sn51.28:3.2": "The path and practice that leads to gaining psychic power. ",
  "sn51.28:3.3": "This is called the basis of psychic power. ",
  "sn51.28:4.1": "And what is the development of the bases of psychic power? ",
  "sn51.28:4.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.28:4.3": "energy … ",
  "sn51.28:4.4": "mental development … ",
  "sn51.28:4.5": "inquiry, and active effort. ",
  "sn51.28:4.6": "This is called the development of the bases of psychic power. ",
  "sn51.28:5.1": "And what is the practice that leads to the development of the bases of psychic power? ",
  "sn51.28:5.2": "It is simply this noble eightfold path, that is: ",
  "sn51.28:5.3": "right view, right purpose, right speech, right action, right livelihood, right effort, right mindfulness, and right immersion. ",
  "sn51.28:5.4": "This is called the practice that leads to the development of the bases of psychic power.” ",
  "sn51.29:0.1": "Linked Discourses 51.29 ",
  "sn51.29:0.2": "3. The Iron Ball ",
  "sn51.29:0.3": "Several Mendicants (1st) ",
  "sn51.29:1.1": "Then several mendicants went up to the Buddha, bowed, sat down to one side, and said to him: ",
  "sn51.29:1.2": "“Sir, what is psychic power? What is the basis of psychic power? What is the development of the bases of psychic power? And what is the practice that leads to the development of the bases of psychic power?” ",
  "sn51.29:2.1": "“Mendicants, take a mendicant who wields the many kinds of psychic power: multiplying themselves and becoming one again … controlling the body as far as the realm of divinity. ",
  "sn51.29:2.2": "This is called psychic power. ",
  "sn51.29:3.1": "And what is the basis of psychic power? ",
  "sn51.29:3.2": "The path and practice that leads to gaining psychic power. ",
  "sn51.29:3.3": "This is called the basis of psychic power. ",
  "sn51.29:4.1": "And what is the development of the bases of psychic power? ",
  "sn51.29:4.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.29:4.3": "energy … ",
  "sn51.29:4.4": "mental development … ",
  "sn51.29:4.5": "inquiry, and active effort. ",
  "sn51.29:4.6": "This is called the development of the bases of psychic power. ",
  "sn51.29:5.1": "And what is the practice that leads to the development of the bases of psychic power? ",
  "sn51.29:5.2": "It is simply this noble eightfold path, that is: ",
  "sn51.29:5.3": "right view, right purpose, right speech, right action, right livelihood, right effort, right mindfulness, and right immersion. ",
  "sn51.29:5.4": "This is called the practice that leads to the development of the bases of psychic power.” ",
  "sn51.30:0.1": "Linked Discourses 51.30 ",
  "sn51.30:0.2": "3. The Iron Ball ",
  "sn51.30:0.3": "Several Mendicants (2nd) ",
  "sn51.30:1.1": "Then several mendicants went up to the Buddha … ",
  "sn51.30:1.2": "The Buddha said to them: ",
  "sn51.30:1.3": "“Mendicants, what is psychic power? What is the basis of psychic power? What is the development of the bases of psychic power? And what is the practice that leads to the development of the bases of psychic power?” ",
  "sn51.30:1.4": "“Our teachings are rooted in the Buddha. He is our guide and our refuge. …” ",
  "sn51.30:2.1": "“And what is psychic power? ",
  "sn51.30:2.2": "It’s a mendicant who wields the many kinds of psychic power: multiplying themselves and becoming one again … controlling the body as far as the realm of divinity. ",
  "sn51.30:2.3": "This is called psychic power. ",
  "sn51.30:3.1": "And what is the basis of psychic power? ",
  "sn51.30:3.2": "The path and practice that leads to gaining psychic power. ",
  "sn51.30:3.3": "This is called the basis of psychic power. ",
  "sn51.30:4.1": "And what is the development of the bases of psychic power? ",
  "sn51.30:4.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.30:4.3": "energy … ",
  "sn51.30:4.4": "mental development … ",
  "sn51.30:4.5": "inquiry, and active effort. ",
  "sn51.30:4.6": "This is called the development of the bases of psychic power. ",
  "sn51.30:5.1": "And what is the practice that leads to the development of the bases of psychic power? ",
  "sn51.30:5.2": "It is simply this noble eightfold path, that is: ",
  "sn51.30:5.3": "right view, right purpose, right speech, right action, right livelihood, right effort, right mindfulness, and right immersion. ",
  "sn51.30:5.4": "This is called the practice that leads to the development of the bases of psychic power.” ",
  "sn51.31:0.1": "Linked Discourses 51.31 ",
  "sn51.31:0.2": "3. The Iron Ball ",
  "sn51.31:0.3": "About Moggallāna ",
  "sn51.31:1.1": "There the Buddha addressed the mendicants: ",
  "sn51.31:1.2": "“What do you think, mendicants? ",
  "sn51.31:1.3": "What things has the mendicant Moggallāna developed and cultivated so as to have such power and might?” ",
  "sn51.31:2.1": "“Our teachings are rooted in the Buddha. He is our guide and our refuge. …” ",
  "sn51.31:2.2": "“The mendicant Moggallāna has become so powerful and mighty by developing and cultivating the four bases of psychic power. ",
  "sn51.31:3.1": "What four? ",
  "sn51.31:3.2": "Moggallāna develops the basis of psychic power that has immersion due to enthusiasm, and active effort. ",
  "sn51.31:3.3": "He thinks: ‘My enthusiasm won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.’ ",
  "sn51.31:3.4": "And he meditates perceiving before and behind: ",
  "sn51.31:3.5": "as before, so behind; as behind, so before; ",
  "sn51.31:3.6": "as below, so above; as above, so below; ",
  "sn51.31:3.7": "as by day, so by night; as by night, so by day. ",
  "sn51.31:3.8": "And so, with an open and unenveloped heart, he develops a mind that’s full of radiance. ",
  "sn51.31:3.9": "He develops the basis of psychic power that has immersion due to energy … ",
  "sn51.31:3.10": "mental development … ",
  "sn51.31:3.11": "inquiry, and active effort. ",
  "sn51.31:3.12": "He thinks: ‘My inquiry won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.’ … ",
  "sn51.31:3.13": "And so, with an open and unenveloped heart, he develops a mind that’s full of radiance. ",
  "sn51.31:3.14": "The mendicant Moggallāna has become so powerful and mighty by developing and cultivating these four bases of psychic power. ",
  "sn51.31:4.1": "And by developing and cultivating these four bases of psychic power, the mendicant Moggallāna wields the many kinds of psychic power: multiplying himself and becoming one again … controlling the body as far as the realm of divinity. ",
  "sn51.31:4.2": "And by developing and cultivating these four bases of psychic power, the mendicant Moggallāna realizes the undefiled freedom of heart and freedom by wisdom in this very life. And he lives having realized it with his own insight due to the ending of defilements.” ",
  "sn51.32:0.1": "Linked Discourses 51.32 ",
  "sn51.32:0.2": "3. The Iron Ball ",
  "sn51.32:0.3": "The Realized One ",
  "sn51.32:1.1": "There the Buddha addressed the mendicants: ",
  "sn51.32:1.2": "“What do you think, mendicants? ",
  "sn51.32:1.3": "What things has the Realized One developed and cultivated so as to have such power and might?” ",
  "sn51.32:2.1": "“Our teachings are rooted in the Buddha. …” ",
  "sn51.32:2.2": "“The Realized One has become so powerful and mighty by developing and cultivating the four bases of psychic power. ",
  "sn51.32:3.1": "What four? ",
  "sn51.32:3.2": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm, and active effort. ",
  "sn51.32:3.3": "He thinks: ‘My enthusiasm won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.’ ",
  "sn51.32:3.4": "And he meditates perceiving before and behind: ",
  "sn51.32:3.5": "as before, so behind; as behind, so before; ",
  "sn51.32:3.6": "as below, so above; as above, so below; ",
  "sn51.32:3.7": "as by day, so by night; as by night, so by day. ",
  "sn51.32:3.8": "And so, with an open and unenveloped heart, he develops a mind that’s full of radiance. ",
  "sn51.32:3.9": "He develops the basis of psychic power that has immersion due to energy … ",
  "sn51.32:3.10": "mental development … ",
  "sn51.32:3.11": "inquiry, and active effort. ",
  "sn51.32:3.12": "He thinks: ‘My inquiry won’t be too lax or too tense. And it’ll be neither constricted internally nor scattered externally.’ ",
  "sn51.32:3.13": "And he meditates perceiving before and behind: ",
  "sn51.32:3.14": "as before, so behind; as behind, so before; ",
  "sn51.32:3.15": "as below, so above; as above, so below; ",
  "sn51.32:3.16": "as by day, so by night; as by night, so by day. ",
  "sn51.32:3.17": "And so, with an open and unenveloped heart, he develops a mind that’s full of radiance. ",
  "sn51.32:3.18": "The Realized One has become so powerful and mighty by developing and cultivating these four bases of psychic power. ",
  "sn51.32:4.1": "And by developing and cultivating these four bases of psychic power, the Realized One wields the many kinds of psychic power: multiplying himself and becoming one again … controlling the body as far as the realm of divinity. ",
  "sn51.32:4.2": "And by developing and cultivating these four bases of psychic power, the Realized One realizes the undefiled freedom of heart and freedom by wisdom in this very life. And he lives having realized it with his own insight due to the ending of defilements.” ",
  "sn51.32:4.3": "",
  "sn51.32:4.4": "(The six direct knowledges should be told in full.) ",
  "sn51.32:4.5": "",
  "sn51.32:5.1": "",
  "sn51.32:5.2": "",
  "sn51.32:5.3": "",
  "sn51.33-44:0.1": "Linked Discourses 51.33–44 ",
  "sn51.33-44:0.2": "4. Abbreviated Texts on the Ganges ",
  "sn51.33-44:0.3": "The Ganges River, Etc. ",
  "sn51.33-44:1.1": "“Mendicants, the Ganges river slants, slopes, and inclines to the east. ",
  "sn51.33-44:1.2": "In the same way, a mendicant who develops and cultivates the four bases of psychic power slants, slopes, and inclines to extinguishment. ",
  "sn51.33-44:1.3": "And how does a mendicant who develops the four bases of psychic power slant, slope, and incline to extinguishment? ",
  "sn51.33-44:1.4": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.33-44:1.5": "energy … ",
  "sn51.33-44:1.6": "mental development … ",
  "sn51.33-44:1.7": "inquiry, and active effort. ",
  "sn51.33-44:2.1": "That’s how a mendicant who develops and cultivates the four bases of psychic power slants, slopes, and inclines to extinguishment.” ",
  "sn51.33-44:2.2": "",
  "sn51.33-44:2.3": "",
  "sn51.33-44:3.1": "Six on slanting to the east, ",
  "sn51.33-44:3.2": "and six on slanting to the ocean; ",
  "sn51.33-44:3.3": "these two sixes make twelve, ",
  "sn51.33-44:3.4": "and that’s how this chapter is recited. ",
  "sn51.45-54:0.1": "Linked Discourses 51.45–54 ",
  "sn51.45-54:0.2": "5. Diligence ",
  "sn51.45-54:0.3": "Diligence ",
  "sn51.45-54:1.1": "(Tell in full as in the chapter on diligence at SN 45.139–148.) ",
  "sn51.45-54:2.1": "The Realized One, footprint, roof peak, ",
  "sn51.45-54:2.2": "roots, heartwood, jasmine, ",
  "sn51.45-54:2.3": "monarch, sun and moon, ",
  "sn51.45-54:2.4": "and cloth is the tenth. ",
  "sn51.55-66:0.1": "Linked Discourses 51.55–66 ",
  "sn51.55-66:0.2": "6. Hard Work ",
  "sn51.55-66:0.3": "Hard Work ",
  "sn51.55-66:1.1": "(Tell in full as in the chapter on hard work at SN 45.149–160.) ",
  "sn51.55-66:2.1": "Hard work, seeds, and dragons, ",
  "sn51.55-66:2.2": "a tree, a pot, and a spike, ",
  "sn51.55-66:2.3": "the atmosphere, and two on clouds, ",
  "sn51.55-66:2.4": "a ship, a guest house, and a river. ",
  "sn51.67-76:0.1": "Linked Discourses 51.67–76 ",
  "sn51.67-76:0.2": "7. Searches ",
  "sn51.67-76:0.3": "Searches ",
  "sn51.67-76:1.1": "(Tell in full as in the chapter on searches at SN 45.161–170.) ",
  "sn51.67-76:2.1": "Searches, discriminations, defilements, ",
  "sn51.67-76:2.2": "states of existence, three kinds of suffering, ",
  "sn51.67-76:2.3": "barrenness, stains, and troubles, ",
  "sn51.67-76:2.4": "feelings, craving, and thirst. ",
  "sn51.77-86:0.1": "Linked Discourses 51.77–86 ",
  "sn51.77-86:0.2": "8. Floods ",
  "sn51.77-86:0.3": "Floods, Etc. ",
  "sn51.77-86:1.1": "“Mendicants, there are five higher fetters. ",
  "sn51.77-86:1.2": "What five? ",
  "sn51.77-86:1.3": "Desire for rebirth in the realm of luminous form, desire for rebirth in the formless realm, conceit, restlessness, and ignorance. ",
  "sn51.77-86:1.4": "These are the five higher fetters. ",
  "sn51.77-86:1.5": "The four bases of psychic power should be developed for the direct knowledge, complete understanding, finishing, and giving up of these five higher fetters. ",
  "sn51.77-86:1.6": "What four? ",
  "sn51.77-86:1.7": "It’s when a mendicant develops the basis of psychic power that has immersion due to enthusiasm … ",
  "sn51.77-86:1.8": "energy … ",
  "sn51.77-86:1.9": "mental development … ",
  "sn51.77-86:1.10": "inquiry, and active effort. ",
  "sn51.77-86:1.11": "These four bases of psychic power should be developed for the direct knowledge, complete understanding, finishing, and giving up of these five higher fetters.” ",
  "sn51.77-86:1.12": "(Tell in full as in the Linked Discourses on the Path at SN 45.171–180.) ",
  "sn51.77-86:1.13": "",
  "sn51.77-86:2.1": "Floods, yokes, grasping, ",
  "sn51.77-86:2.2": "ties, and underlying tendencies, ",
  "sn51.77-86:2.3": "kinds of sensual stimulation, hindrances, ",
  "sn51.77-86:2.4": "aggregates, and fetters high and low. ",
  "sn51.77-86:2.5": "The Linked Discourses on the Bases of Psychic Power is the seventh section. "
}
window.BILARA["sn51_v1"]["en"]["sn51_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
