window.BILARA = window.BILARA || {};
window.BILARA["sn6_v1"] = window.BILARA["sn6_v1"] || {};
window.BILARA["sn6_v1"]["en"] = {
  "sn6.1:0.1": "Linked Discourses 6.1 ",
  "sn6.1:0.2": "1. The Appeal ",
  "sn6.1:0.3": "The Appeal of the Divinity ",
  "sn6.1:1.1": "So I have heard. ",
  "sn6.1:1.2": "At one time, when he was first awakened, the Buddha was staying in Uruvelā at the root of the goatherd’s banyan tree on the bank of the Nerañjarā River. ",
  "sn6.1:1.3": "Then as he was in private retreat this thought came to his mind, ",
  "sn6.1:1.4": "“This principle I have discovered is deep, hard to see, hard to understand, peaceful, sublime, beyond the scope of logic, subtle, comprehensible to the astute. ",
  "sn6.1:1.5": "But people like clinging, they love it and enjoy it. ",
  "sn6.1:1.6": "It’s hard for them to see this topic; that is, specific conditionality, dependent origination. ",
  "sn6.1:1.7": "It’s also hard for them to see this topic; that is, the stilling of all activities, the letting go of all attachments, the ending of craving, fading away, cessation, extinguishment. ",
  "sn6.1:1.8": "And if I were to teach this principle, others might not understand me, which would be wearying and troublesome for me.” ",
  "sn6.1:1.9": "And then these verses, which were neither supernaturally inspired, nor learned before in the past, occurred to the Buddha: ",
  "sn6.1:2.1": "“I’ve struggled hard to realize this, ",
  "sn6.1:2.2": "enough with trying to explain it! ",
  "sn6.1:2.3": "Those mired in greed and hate ",
  "sn6.1:2.4": "can’t really understand this teaching. ",
  "sn6.1:3.1": "It goes against the stream, subtle, ",
  "sn6.1:3.2": "deep, obscure, and very fine. ",
  "sn6.1:3.3": "Those besotted by greed cannot see, ",
  "sn6.1:3.4": "for they’re shrouded in a mass of darkness.” ",
  "sn6.1:4.1": "And as the Buddha reflected like this, his mind inclined to remaining passive, not to teaching the Dhamma. ",
  "sn6.1:5.1": "Then, knowing the Buddha’s train of thought, it occurred to the divinity Sahampati, ",
  "sn6.1:5.2": "“Oh lord! The world will be lost, the world will perish! For the mind of the Realized One, the perfected one, the fully awakened Buddha, inclines to remaining passive, not to teaching the Dhamma.” ",
  "sn6.1:5.3": "Then, as easily as a strong person would extend or contract their arm, he vanished from the realm of divinity and reappeared in front of the Buddha. ",
  "sn6.1:5.4": "He arranged his robe over one shoulder, knelt with his right knee on the ground, raised his joined palms toward the Buddha, and said: ",
  "sn6.1:5.5": "“Sir, let the Blessed One teach the Dhamma! Let the Holy One teach the Dhamma! ",
  "sn6.1:5.6": "There are beings with little dust in their eyes. They’re in decline because they haven’t heard the teaching. ",
  "sn6.1:5.7": "There will be those who understand the teaching!” ",
  "sn6.1:5.8": "This is what the divinity Sahampati said. Then he went on to say: ",
  "sn6.1:6.1": "“Among the Magadhans there appeared in the past ",
  "sn6.1:6.2": "an impure teaching thought up by the stained. ",
  "sn6.1:6.3": "Fling open the door to freedom from death! ",
  "sn6.1:6.4": "Let them hear the teaching <j>the immaculate one discovered. ",
  "sn6.1:7.1": "Standing high on a rocky mountain, ",
  "sn6.1:7.2": "you can see the people all around. ",
  "sn6.1:7.3": "In just the same way, All-seer, so intelligent, ",
  "sn6.1:7.4": "having ascended the Temple of Truth, ",
  "sn6.1:7.5": "rid of sorrow, look upon the people ",
  "sn6.1:7.6": "swamped with sorrow,  <j>oppressed by rebirth and old age. ",
  "sn6.1:8.1": "Rise, hero! Victor in battle, caravan leader, ",
  "sn6.1:8.2": "wander the world cleared of debt. ",
  "sn6.1:8.3": "Let the Blessed One teach the Dhamma! ",
  "sn6.1:8.4": "There will be those who understand!” ",
  "sn6.1:9.1": "Then the Buddha, understanding the Divinity’s invitation, surveyed the world with the eye of a Buddha, out of his compassion for sentient beings. ",
  "sn6.1:9.2": "And the Buddha saw sentient beings with little dust in their eyes, and some with much dust in their eyes; with keen faculties and with weak faculties, with good qualities and with bad qualities, easy to teach and hard to teach. And some of them lived seeing the danger in the fault to do with the next world, while others did not. ",
  "sn6.1:9.3": "It’s like a pool with blue water lilies, or pink or white lotuses. Some of them sprout and grow in the water without rising above it, thriving underwater. Some of them sprout and grow in the water reaching the water’s surface. And some of them sprout and grow in the water but rise up above the water and stand with no water clinging to them. ",
  "sn6.1:9.4": "In the same way, the Buddha saw sentient beings with little dust in their eyes, and some with much dust in their eyes; with keen faculties and with weak faculties, with good qualities and with bad qualities, easy to teach and hard to teach. And some of them lived seeing the danger in the fault to do with the next world, while others did not. ",
  "sn6.1:9.5": "When he had seen this he replied in verse to the divinity Sahampati: ",
  "sn6.1:10.1": "“Flung open are the doors to freedom from death! ",
  "sn6.1:10.2": "Let those with ears to hear commit to faith. ",
  "sn6.1:10.3": "Thinking it would be troublesome, Divinity, <j>I did not teach ",
  "sn6.1:10.4": "the sophisticated, sublime Dhamma among mankind.” ",
  "sn6.1:11.1": "Then the divinity Sahampati, knowing that his request for the Buddha to teach the Dhamma had been granted, bowed and respectfully circled the Buddha, keeping him on his right, before vanishing right there. ",
  "sn6.2:0.1": "Linked Discourses 6.2 ",
  "sn6.2:0.2": "1. The Appeal ",
  "sn6.2:0.3": "Respect ",
  "sn6.2:1.1": "So I have heard. ",
  "sn6.2:1.2": "At one time, when he was first awakened, the Buddha was staying in Uruvelā at the root of the goatherd’s banyan tree on the bank of the Nerañjarā River. ",
  "sn6.2:1.3": "Then as he was in private retreat this thought came to his mind, ",
  "sn6.2:1.4": "“One without respect and reverence lives in suffering. What ascetic or brahmin should I honor and respect and rely on?” ",
  "sn6.2:2.1": "Then it occurred to him: ",
  "sn6.2:2.2": "“I’d honor and respect and rely on another ascetic or brahmin so as to complete the entire spectrum of ethics, if it were incomplete. ",
  "sn6.2:2.3": "But I don’t see any other ascetic or brahmin in this worldwith its gods, Māras, and Divinities, this population with its ascetics and brahmins, its gods and humanswho is more accomplished than myself in ethics, who I should honor and respect and rely on. ",
  "sn6.2:3.1": "I’d honor and respect and rely on another ascetic or brahmin so as to complete the entire spectrum of immersion, if it were incomplete. ",
  "sn6.2:3.2": "But I don’t see any other ascetic or brahmin … who is more accomplished than myself in immersion … ",
  "sn6.2:4.1": "I’d honor and respect and rely on another ascetic or brahmin so as to complete the entire spectrum of wisdom, if it were incomplete. ",
  "sn6.2:4.2": "But I don’t see any other ascetic or brahmin … who is more accomplished than myself in wisdom … ",
  "sn6.2:5.1": "I’d honor and respect and rely on another ascetic or brahmin so as to complete the entire spectrum of freedom, if it were incomplete. ",
  "sn6.2:5.2": "But I don’t see any other ascetic or brahmin … who is more accomplished than myself in freedom … ",
  "sn6.2:6.1": "I’d honor and respect and rely on another ascetic or brahmin so as to complete the entire spectrum of the knowledge and vision of freedom, if it were incomplete. ",
  "sn6.2:6.2": "But I don’t see any other ascetic or brahmin in this worldwith its gods, Māras, and Divinities, this population with its ascetics and brahmins, its gods and humanswho is more accomplished than myself in the knowledge and vision of freedom, who I should honor and respect and rely on. ",
  "sn6.2:6.3": "Why don’t I honor and respect and rely on the same Dhamma to which I was awakened?” ",
  "sn6.2:7.1": "Then the divinity Sahampati knew the Buddha’s train of thought. As easily as a strong person would extend or contract their arm, he vanished from the realm of divinity and reappeared in front of the Buddha. ",
  "sn6.2:7.2": "He arranged his robe over one shoulder, raised his joined palms toward the Buddha, and said: ",
  "sn6.2:7.3": "“That’s so true, Blessed One! That’s so true, Holy One! ",
  "sn6.2:7.4": "All the perfected ones, the fully awakened Buddhas who lived in the past honored and respected and relied on this same teaching. ",
  "sn6.2:7.5": "All the perfected ones, the fully awakened Buddhas who will live in the future will honor and respect and rely on this same teaching. ",
  "sn6.2:7.6": "May the Blessed One, who is the perfected one, the fully awakened Buddha at present, also honor and respect and rely on this same teaching.” ",
  "sn6.2:7.7": "This is what the divinity Sahampati said. Then he went on to say: ",
  "sn6.2:8.1": "“All Buddhas in the past, ",
  "sn6.2:8.2": "the Buddhas of the future, ",
  "sn6.2:8.3": "and the Buddha at present",
  "sn6.2:8.4": "destroyer of the sorrows of many",
  "sn6.2:9.1": "respecting the true teaching ",
  "sn6.2:9.2": "they did live, they do live, ",
  "sn6.2:9.3": "and they also will live. ",
  "sn6.2:9.4": "This is the nature of the Buddhas. ",
  "sn6.2:10.1": "Therefore someone who desires self-knowledge, ",
  "sn6.2:10.2": "and aspires to greatness themselves, ",
  "sn6.2:10.3": "should respect the true teaching, ",
  "sn6.2:10.4": "remembering the instructions of the Buddhas.” ",
  "sn6.3:0.1": "Linked Discourses 6.3 ",
  "sn6.3:0.2": "1. The Appeal ",
  "sn6.3:0.3": "With Brahmadeva ",
  "sn6.3:1.1": "So I have heard. ",
  "sn6.3:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn6.3:1.3": "Now at that time a certain brahmin lady had a son called Brahmadeva, who had gone forth from the lay life to homelessness in the presence of the Buddha. ",
  "sn6.3:2.1": "Then Venerable Brahmadeva, living alone, withdrawn, diligent, keen, and resolute, soon realized the supreme end of the spiritual path in this very life. He lived having achieved with his own insight the goal for which gentlemen rightly go forth from the lay life to homelessness. ",
  "sn6.3:2.2": "He understood: “Rebirth is ended; the spiritual journey has been completed; what had to be done has been done; there is nothing further for this place.” ",
  "sn6.3:2.3": "And Venerable Brahmadeva became one of the perfected. ",
  "sn6.3:3.1": "Then Brahmadeva robed up in the morning and, taking his bowl and robe, entered Sāvatthī for alms. ",
  "sn6.3:3.2": "Wandering indiscriminately for almsfood in Sāvatthī, he approached his own mother’s home. ",
  "sn6.3:3.3": "Now at that time Brahmadeva’s mother, the brahmin lady, was presenting a regular oblation to the Divinity. ",
  "sn6.3:3.4": "Then the divinity Sahampati thought, ",
  "sn6.3:3.5": "“This Venerable Brahmadeva’s mother, the brahmin lady, offers up a regular oblation to the Divinity. ",
  "sn6.3:3.6": "Why don’t I go and stir up a sense of urgency in her?” ",
  "sn6.3:3.7": "Then, as easily as a strong person would extend or contract their arm, he vanished from the realm of divinity and reappeared in the home of Brahmadeva’s mother. ",
  "sn6.3:3.8": "Then the divinity Sahampati, while standing in the air, addressed Brahmadeva’s mother in verse: ",
  "sn6.3:4.1": "“Far from here is the realm of divinity, madam, ",
  "sn6.3:4.2": "to which you present a regular oblation. ",
  "sn6.3:4.3": "But the Divinity doesn’t eat that kind of food. ",
  "sn6.3:4.4": "Why pray, when you don’t know the path to divinity? ",
  "sn6.3:5.1": "This Brahmadeva, madam, ",
  "sn6.3:5.2": "free of attachments, has surpassed the gods. ",
  "sn6.3:5.3": "Owning nothing, providing for no other, <j>a mendicant ",
  "sn6.3:5.4": "has entered your house for alms. ",
  "sn6.3:6.1": "He’s worthy of offerings dedicated to the gods, <j>a knowledge master, evolved. ",
  "sn6.3:6.2": "He’s worthy of a religious donation <j>from gods and men. ",
  "sn6.3:6.3": "Having banished all evils, he’s unsullied. ",
  "sn6.3:6.4": "Cool at heart, he wanders searching for food. ",
  "sn6.3:7.1": "He has no before and after, ",
  "sn6.3:7.2": "peaceful, unclouded, untroubled, <j>with no need for hope, ",
  "sn6.3:7.3": "he has laid down the rod <j>for all creatures firm and frail. ",
  "sn6.3:7.4": "So let him enjoy your offering of alms for the highest. ",
  "sn6.3:8.1": "With peaceful mind, he has left the crowd, ",
  "sn6.3:8.2": "he wanders like a tamed elephant, unperturbed. ",
  "sn6.3:8.3": "He’s a mendicant fair in ethics, with heart well freed. ",
  "sn6.3:8.4": "So let him enjoy your offering of alms for the highest. ",
  "sn6.3:9.1": "With unwavering confidence in him, ",
  "sn6.3:9.2": "present your religious donation <j>to one who is worthy of it. ",
  "sn6.3:9.3": "Now that you’ve seen the sage who has crossed over, <j>madam, ",
  "sn6.3:9.4": "make merit for the sake of future happiness!” ",
  "sn6.3:10.1": "With unwavering confidence in him, ",
  "sn6.3:10.2": "she presented her religious donation <j>to one who is worthy of it. ",
  "sn6.3:10.3": "After seeing the sage who had crossed over, <j>the brahmin lady ",
  "sn6.3:10.4": "made merit for the sake of future happiness. ",
  "sn6.4:0.1": "Linked Discourses 6.4 ",
  "sn6.4:0.2": "1. The Appeal ",
  "sn6.4:0.3": "With Baka the Divinity ",
  "sn6.4:1.1": "So I have heard. ",
  "sn6.4:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. ",
  "sn6.4:1.3": "Now at that time Baka the Divinity had the following harmful misconception: ",
  "sn6.4:1.4": "“This is permanent, this is everlasting, this is eternal, this is whole, this is not liable to pass away. For this is where there’s no being born, growing old, dying, passing away, or being reborn. And there’s no other escape beyond this.” ",
  "sn6.4:2.1": "Then the Buddha knew Baka the Divinity’s train of thought. As easily as a strong person would extend or contract their arm, he vanished from Jeta’s Grove and reappeared in that realm of divinity. ",
  "sn6.4:2.2": "Baka the Divinity saw the Buddha coming off in the distance ",
  "sn6.4:2.3": "and said to him, ",
  "sn6.4:2.4": "“Come, good fellow! Welcome, good fellow! ",
  "sn6.4:2.5": "It’s been a long time since you took the opportunity to come here. ",
  "sn6.4:2.6": "For this is permanent, this is everlasting, this is eternal, this is complete, this is not liable to pass away. For this is where there’s no being born, growing old, dying, passing away, or being reborn. And there’s no other escape beyond this.” ",
  "sn6.4:3.1": "When he had spoken, the Buddha said to him, ",
  "sn6.4:3.2": "“Alas, Baka the Divinity is lost in ignorance! Alas, Baka the Divinity is lost in ignorance! ",
  "sn6.4:3.3": "Because what is actually impermanent, not lasting, transient, incomplete, and liable to pass away, he says is permanent, everlasting, eternal, complete, and not liable to pass away. ",
  "sn6.4:3.4": "And where there is being born, growing old, dying, passing away, and being reborn, he says that ",
  "sn6.4:3.5": "there’s no being born, growing old, dying, passing away, or being reborn. ",
  "sn6.4:3.6": "And although there is another escape beyond this, he says that there’s no other escape beyond this.” ",
  "sn6.4:4.1": "“Gotama, we seventy-two merit-makers <j>are now wielders of power, ",
  "sn6.4:4.2": "having passed beyond rebirth and old age. ",
  "sn6.4:4.3": "This is our last rebirth as the Divinity, <j>O knowledge master. ",
  "sn6.4:4.4": "And now many people pray to us.” ",
  "sn6.4:5.1": "“But, Baka, the lifespan here is short, not long, ",
  "sn6.4:5.2": "though you think it’s long. ",
  "sn6.4:5.3": "A hundred thousand times a hundred million years ",
  "sn6.4:5.4": "I understand your lifespan, Divinity.” ",
  "sn6.4:6.1": "“I am the blessed one of infinite vision, ",
  "sn6.4:6.2": "who has gone beyond rebirth and old age and sorrow. ",
  "sn6.4:6.3": "What was my past practice of precept and observance? ",
  "sn6.4:6.4": "Explain to me so that I may understand.” ",
  "sn6.4:7.1": "“You gave drink to many humans ",
  "sn6.4:7.2": "who were oppressed by thirst and heat. ",
  "sn6.4:7.3": "That’s your past practice of precept and observance. ",
  "sn6.4:7.4": "I recollect it like one who has wakened from sleep. ",
  "sn6.4:8.1": "When people at Deer River Bank were seized, ",
  "sn6.4:8.2": "you released the captives as they were led away. ",
  "sn6.4:8.3": "That’s your past practice of precept and observance. ",
  "sn6.4:8.4": "I recollect it like one who has wakened from sleep. ",
  "sn6.4:9.1": "When a boat on the Ganges River was seized ",
  "sn6.4:9.2": "by a fierce dragon desiring human flesh, ",
  "sn6.4:9.3": "you freed it wielding mighty force. ",
  "sn6.4:9.4": "That’s your past practice of precept and observance. ",
  "sn6.4:9.5": "I recollect it like one who has wakened from sleep. ",
  "sn6.4:10.1": "I used to be your footman named Kappa. ",
  "sn6.4:10.2": "You thought he was intelligent and loyal. ",
  "sn6.4:10.3": "That’s your past practice of precept and observance. ",
  "sn6.4:10.4": "I recollect it like one who has wakened from sleep.” ",
  "sn6.4:11.1": "“You certainly understand this lifespan of mine. ",
  "sn6.4:11.2": "And others, too, you know; <j>that’s why you’re the Buddha. ",
  "sn6.4:11.3": "And that’s why your blazing glory ",
  "sn6.4:11.4": "lights up even the realm of divinity.” ",
  "sn6.5:0.1": "Linked Discourses 6.5 ",
  "sn6.5:0.2": "1. The Appeal ",
  "sn6.5:0.3": "A Certain Divinity ",
  "sn6.5:1.1": "At Sāvatthī. ",
  "sn6.5:1.2": "Now at that time a certain divinity had the following harmful misconception: ",
  "sn6.5:1.3": "“No ascetic or brahmin can come here!” ",
  "sn6.5:1.4": "Then the Buddha knew that divinity’s train of thought. As easily as a strong person would extend or contract their arm, he vanished from Jeta’s Grove and reappeared in that realm of divinity. ",
  "sn6.5:1.5": "Then the Buddha sat cross-legged in the air above that Divinity, having entered upon the fire element. ",
  "sn6.5:2.1": "Then Venerable Mahāmoggallāna thought, ",
  "sn6.5:2.2": "“Where is the Buddha staying at present?” ",
  "sn6.5:2.3": "With clairvoyance that is purified and superhuman, he saw the Buddha seated cross-legged in the air above that Divinity, having entered upon the fire element. ",
  "sn6.5:2.4": "Then, as easily as a strong person would extend or contract their arm, he vanished from Jeta’s Grove and reappeared in that realm of divinity. ",
  "sn6.5:2.5": "Then Mahāmoggallānapositioning himself in the east, below the Buddhasat cross-legged in the air above that Divinity, having entered upon the fire element. ",
  "sn6.5:3.1": "Then Venerable Mahākassapa … ",
  "sn6.5:3.2": "",
  "sn6.5:3.3": "",
  "sn6.5:3.4": "",
  "sn6.5:3.5": "positioned himself in the south … ",
  "sn6.5:4.1": "Venerable Mahākappina … ",
  "sn6.5:4.2": "",
  "sn6.5:4.3": "",
  "sn6.5:4.4": "",
  "sn6.5:4.5": "",
  "sn6.5:4.6": "positioned himself in the west … ",
  "sn6.5:5.1": "Venerable Anuruddha … ",
  "sn6.5:5.2": "",
  "sn6.5:5.3": "",
  "sn6.5:5.4": "",
  "sn6.5:5.5": "positioned himself in the north, below the Buddha, sitting cross-legged in the air above that Divinity, having entered upon the fire element. ",
  "sn6.5:6.1": "Then Mahāmoggallāna addressed that Divinity in verse: ",
  "sn6.5:7.1": "“Good sir, do you still have the same view ",
  "sn6.5:7.2": "that you had in the past? ",
  "sn6.5:7.3": "Or do you see the radiance ",
  "sn6.5:7.4": "surpassing the realm of divinity?” ",
  "sn6.5:8.1": "“Good fellow, I don’t have that view ",
  "sn6.5:8.2": "that I had in the past. ",
  "sn6.5:8.3": "I see the radiance ",
  "sn6.5:8.4": "surpassing the realm of divinity. ",
  "sn6.5:8.5": "So how could I say today ",
  "sn6.5:8.6": "that I am permanent and eternal?” ",
  "sn6.5:9.1": "Having inspired a sense of awe in the Divinity, as easily as a strong person would extend or contract their arm, the Buddha vanished from the realm of divinity and reappeared in Jeta’s Grove. ",
  "sn6.5:9.2": "Then that Divinity addressed a member of his retinue, ",
  "sn6.5:9.3": "“Please, good fellow, go up to Venerable Mahāmoggallāna and say to him: ",
  "sn6.5:9.4": "‘Moggallāna my good fellow, are there any other disciples of the Buddha who have power and might ",
  "sn6.5:9.5": "comparable to the worthies Moggallāna, Kassapa, Kappina, and Anuruddha?’” ",
  "sn6.5:9.6": "“Yes, good fellow,” replied that retinue member. He went to Moggallāna and asked as instructed. ",
  "sn6.5:9.7": "",
  "sn6.5:9.8": "",
  "sn6.5:9.9": "Then Mahāmoggallāna addressed that member of the retinue of Divinity in verse: ",
  "sn6.5:10.1": "“There are many disciples of the Buddha ",
  "sn6.5:10.2": "who have the three knowledges, ",
  "sn6.5:10.3": "and have attained psychic power, <j>expert in encompassing minds, ",
  "sn6.5:10.4": "they’re perfected ones with defilements ended.” ",
  "sn6.5:11.1": "Then that member of the retinue of Divinity, having approved and agreed with what Mahāmoggallāna said, went to that Divinity and said to him, ",
  "sn6.5:11.2": "“Good fellow, Venerable Mahāmoggallāna said this: ",
  "sn6.5:12.1": "‘There are many disciples of the Buddha ",
  "sn6.5:12.2": "who have the three knowledges, ",
  "sn6.5:12.3": "and have attained psychic power, <j>expert in encompassing minds, ",
  "sn6.5:12.4": "they’re perfected ones with defilements ended.’” ",
  "sn6.5:13.1": "That’s what that member of the retinue of Divinity said. ",
  "sn6.5:13.2": "Satisfied, that Divinity approved what the member of his retinue said. ",
  "sn6.6:0.1": "Linked Discourses 6.6 ",
  "sn6.6:0.2": "1. The Appeal ",
  "sn6.6:0.3": "The Negligent Divinity ",
  "sn6.6:1.1": "At Sāvatthī. ",
  "sn6.6:1.2": "Now at that time the Buddha had gone into retreat for the day’s meditation. ",
  "sn6.6:1.3": "Then the independent divinities Subrahmā and Suddhāvāsa went to the Buddha and stationed themselves one by each door-post. But Subrahmā said to Suddhāvāsa, ",
  "sn6.6:1.4": "“Good fellow, it’s the wrong time to pay homage to the Buddha. ",
  "sn6.6:1.5": "He has gone into retreat for the day’s meditation. ",
  "sn6.6:1.6": "But such and such realm of divinity is successful and prosperous, while the divinity living there is negligent. ",
  "sn6.6:1.7": "Come, let’s go to that realm of divinity and inspire awe in that Divinity!” ",
  "sn6.6:1.8": "“Yes, good fellow,” replied Suddhāvāsa. ",
  "sn6.6:2.1": "Then, as easily as a strong person would extend or contract their arm, they vanished from in front of the Buddha and appeared in that realm of divinity. ",
  "sn6.6:2.2": "That divinity saw those divinities coming off in the distance and said to them, ",
  "sn6.6:2.3": "“Well now, good fellows, where have you come from?” ",
  "sn6.6:2.4": "“Good fellow, we’ve come from the presence of the Blessed One, the perfected one, the fully awakened Buddha. ",
  "sn6.6:2.5": "Shouldn’t you go to attend on that Blessed One?” ",
  "sn6.6:3.1": "When they had spoken, that divinity refused to accept their advice. He multiplied himself a thousand times and said to Subrahmā, ",
  "sn6.6:3.2": "“Good fellow, can’t you see that I have such psychic power?” ",
  "sn6.6:3.3": "“I see that, good fellow.” ",
  "sn6.6:3.4": "“Since I have such psychic power and might, what other ascetic or brahmin should I go to and attend upon?” ",
  "sn6.6:4.1": "Then Subrahmā multiplied himself two thousand times and said to that Divinity, ",
  "sn6.6:4.2": "“Good fellow, can’t you see that I have such psychic power?” ",
  "sn6.6:4.3": "“I see that, good fellow.” ",
  "sn6.6:4.4": "“That Buddha has even more psychic power and might than you or me. ",
  "sn6.6:4.5": "Shouldn’t you go to attend on that Blessed One?” ",
  "sn6.6:4.6": "Then that divinity addressed Subrahmā in verse: ",
  "sn6.6:5.1": "“There are three hundreds of phoenixes, four of swans, ",
  "sn6.6:5.2": "and five of tigerhawks. To he who practiced absorption ",
  "sn6.6:5.3": "belongs this palace; it shines, Divinity, ",
  "sn6.6:5.4": "lighting up the northern quarter!” ",
  "sn6.6:6.1": "“So what if your palace shines, ",
  "sn6.6:6.2": "lighting up the northern quarter? ",
  "sn6.6:6.3": "A clever person, seeing the strife in form, ",
  "sn6.6:6.4": "its chronic trembling, takes no pleasure in it.” ",
  "sn6.6:7.1": "Then after inspiring awe in that divinity, the independent divinities Subrahmā and Suddhāvāsa vanished right there. ",
  "sn6.6:7.2": "And after some time that divinity went to attend on the Buddha. ",
  "sn6.7:0.1": "Linked Discourses 6.7 ",
  "sn6.7:0.2": "1. The Appeal ",
  "sn6.7:0.3": "About Kokālika ",
  "sn6.7:1.1": "At Sāvatthī. ",
  "sn6.7:1.2": "Now at that time the Buddha had gone into retreat for the day’s meditation. ",
  "sn6.7:1.3": "Then the independent divinities Subrahmā and Suddhāvāsa went to the Buddha and stationed themselves one by each door-post. ",
  "sn6.7:1.4": "Then Subrahmā spoke this verse about the mendicant Kokālika in the Buddha’s presence: ",
  "sn6.7:2.1": "“Who having known would judge ",
  "sn6.7:2.2": "the immeasurable by measuring them? ",
  "sn6.7:2.3": "I think anyone who’d do such a thing ",
  "sn6.7:2.4": "is an ordinary person, shrouded in darkness.” ",
  "sn6.8:0.1": "Linked Discourses 6.8 ",
  "sn6.8:0.2": "1. The Appeal ",
  "sn6.8:0.3": "About Katamorakatissaka ",
  "sn6.8:1.1": "At Sāvatthī. ",
  "sn6.8:1.2": "Now at that time the Buddha had gone into retreat for the day’s meditation. ",
  "sn6.8:1.3": "Then the independent divinities Subrahmā and Suddhāvāsa went to the Buddha and stationed themselves one by each door-post. ",
  "sn6.8:1.4": "Then Suddhāvāsa spoke this verse about the mendicant Katamorakatissaka in the Buddha’s presence: ",
  "sn6.8:2.1": "“What wise person here would judge ",
  "sn6.8:2.2": "the immeasurable by measuring them? ",
  "sn6.8:2.3": "I think anyone who’d do such a thing ",
  "sn6.8:2.4": "is an ignoramus, shrouded in darkness.” ",
  "sn6.9:0.1": "Linked Discourses 6.9 ",
  "sn6.9:0.2": "1. The Appeal ",
  "sn6.9:0.3": "With the Divinity Tudu ",
  "sn6.9:1.1": "At Sāvatthī. ",
  "sn6.9:1.2": "Now at that time the mendicant Kokālika was sick, suffering, gravely ill. ",
  "sn6.9:1.3": "Then, late at night, the glorious independent divinity Tudu, lighting up the entire Jeta’s Grove, went up to the mendicant Kokālika, and standing in the air he said to him, ",
  "sn6.9:1.4": "“Kokālika, have confidence in Sāriputta and Moggallāna, ",
  "sn6.9:1.5": "they’re good monks.” ",
  "sn6.9:1.6": "“Who are you, reverend?” ",
  "sn6.9:1.7": "“I am Tudu the independent divinity.” ",
  "sn6.9:1.8": "“Didn’t the Buddha declare you a non-returner? So what then are you doing back here? ",
  "sn6.9:1.9": "See how far you have strayed!” ",
  "sn6.9:2.1": "“A man is born ",
  "sn6.9:2.2": "with an axe in his mouth. ",
  "sn6.9:2.3": "A fool cuts themselves with it ",
  "sn6.9:2.4": "when they say bad words. ",
  "sn6.9:3.1": "When you praise someone worthy of criticism, ",
  "sn6.9:3.2": "or criticize someone worthy of praise, ",
  "sn6.9:3.3": "you choose a losing hand with your own mouth: ",
  "sn6.9:3.4": "you’ll never find happiness that way. ",
  "sn6.9:4.1": "A losing hand at dice is a trivial thing, ",
  "sn6.9:4.2": "if all you lose is your money ",
  "sn6.9:4.3": "and all you own, even yourself. ",
  "sn6.9:4.4": "What’s a really terrible hand ",
  "sn6.9:4.5": "is to hate the holy ones. ",
  "sn6.9:5.1": "For a hundred thousand times a hundred million, ",
  "sn6.9:5.2": "times five hundred and thirty-six times <j>a thousand times ten million years ",
  "sn6.9:5.3": "a slanderer of noble ones goes to hell, ",
  "sn6.9:5.4": "having aimed bad words and thoughts at them.” ",
  "sn6.10:0.1": "Linked Discourses 6.10 ",
  "sn6.10:0.2": "1. The Appeal ",
  "sn6.10:0.3": "With Kokālika ",
  "sn6.10:1.1": "At Sāvatthī. ",
  "sn6.10:1.2": "Then the mendicant Kokālika went up to the Buddha, bowed, sat down to one side, and said to him, ",
  "sn6.10:1.3": "“Sir, Sāriputta and Moggallāna have corrupt wishes. They’ve fallen under the sway of corrupt wishes.” ",
  "sn6.10:1.4": "When this was said, the Buddha said to Kokālika, ",
  "sn6.10:1.5": "“Don’t say that, Kokālika! Don’t say that, Kokālika! ",
  "sn6.10:1.6": "Have confidence in Sāriputta and Moggallāna, they’re good monks.” ",
  "sn6.10:1.7": "For a second time Kokālika said to the Buddha, ",
  "sn6.10:1.8": "“Despite my faith and trust in the Buddha, Sāriputta and Moggallāna have corrupt wishes. They’ve fallen under the sway of corrupt wishes.” ",
  "sn6.10:1.9": "For a second time, the Buddha said to Kokālika, ",
  "sn6.10:1.10": "“Don’t say that, Kokālika! Don’t say that, Kokālika! ",
  "sn6.10:1.11": "Have confidence in Sāriputta and Moggallāna, they’re good monks.” ",
  "sn6.10:1.12": "For a third time Kokālika said to the Buddha, ",
  "sn6.10:1.13": "“Despite my faith and trust in the Buddha, Sāriputta and Moggallāna have corrupt wishes. They’ve fallen under the sway of corrupt wishes.” ",
  "sn6.10:1.14": "For a third time, the Buddha said to Kokālika, ",
  "sn6.10:1.15": "“Don’t say that, Kokālika! Don’t say that, Kokālika! ",
  "sn6.10:1.16": "Have confidence in Sāriputta and Moggallāna, they’re good monks.” ",
  "sn6.10:2.1": "Then Kokālika got up from his seat, bowed, and respectfully circled the Buddha, keeping him on his right, before leaving. ",
  "sn6.10:2.2": "Not long after he left his body erupted with boils the size of mustard seeds. ",
  "sn6.10:2.3": "The boils grew to the size of mung beans, then chickpeas, then jujube seeds, then jujubes, then myrobalans, then unripe wood-apples, then ripe wood-apples. Finally they burst open, and pus and blood oozed out. ",
  "sn6.10:2.4": "Then the mendicant Kokālika died of that illness. ",
  "sn6.10:2.5": "He was reborn in the Pink Lotus hell because of his resentment for Sāriputta and Moggallāna. ",
  "sn6.10:3.1": "Then, late at night, the glorious divinity Sahampati, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, stood to one side, and said to him, ",
  "sn6.10:3.2": "“Sir, the mendicant Kokālika has passed away. ",
  "sn6.10:3.3": "He was reborn in the Pink Lotus hell because of his resentment for Sāriputta and Moggallāna.” ",
  "sn6.10:3.4": "That’s what the divinity Sahampati said. ",
  "sn6.10:3.5": "Then he bowed and respectfully circled the Buddha, keeping him on his right side, before vanishing right there. ",
  "sn6.10:4.1": "Then, when the night had passed, the Buddha told the mendicants all that had happened. ",
  "sn6.10:4.2": "",
  "sn6.10:4.3": "",
  "sn6.10:4.4": "",
  "sn6.10:4.5": "",
  "sn6.10:5.1": "When he said this, one of the mendicants asked the Buddha, ",
  "sn6.10:5.2": "“Sir, how long is the lifespan in the Pink Lotus hell?” ",
  "sn6.10:5.3": "“It’s long, mendicant. ",
  "sn6.10:5.4": "It’s not easy to calculate ",
  "sn6.10:5.5": "how many years, how many hundreds or thousands or hundreds of thousands of years it lasts.” ",
  "sn6.10:5.6": "“But sir, is it possible to give a simile?” ",
  "sn6.10:5.7": "“It’s possible,” said the Buddha. ",
  "sn6.10:6.1": "“Suppose there was a Kosalan load of twenty packs of sesame seed. And at the end of every hundred years someone would remove a single seed from it. ",
  "sn6.10:6.2": "By this means the Kosalan load of twenty packs of sesame seed would run out faster than a single lifetime in the Abbuda hell. ",
  "sn6.10:6.3": "Now, twenty lifetimes in the Abbuda hell equal one lifetime in the Nirabbuda hell. ",
  "sn6.10:6.4": "Twenty lifetimes in the Nirabbuda hell equal one lifetime in the Ababa hell. ",
  "sn6.10:6.5": "Twenty lifetimes in the Ababa hell equal one lifetime in the Aṭaṭa hell. ",
  "sn6.10:6.6": "Twenty lifetimes in the Aṭaṭa hell equal one lifetime in the Ahaha hell. ",
  "sn6.10:6.7": "Twenty lifetimes in the Ahaha hell equal one lifetime in the Yellow Lotus hell. ",
  "sn6.10:6.8": "Twenty lifetimes in the Yellow Lotus hell equal one lifetime in the Fragrant Water Lily hell. ",
  "sn6.10:6.9": "Twenty lifetimes in the Fragrant Water Lily hell equal one lifetime in the Blue Water Lily hell. ",
  "sn6.10:6.10": "Twenty lifetimes in the Blue Water Lily hell equal one lifetime in the White Lotus hell. ",
  "sn6.10:6.11": "Twenty lifetimes in the White Lotus hell equal one lifetime in the Pink Lotus hell. ",
  "sn6.10:6.12": "The mendicant Kokālika has been reborn in the Pink Lotus hell because of his resentment for Sāriputta and Moggallāna.” ",
  "sn6.10:6.13": "That is what the Buddha said. ",
  "sn6.10:6.14": "Then the Holy One, the Teacher, went on to say: ",
  "sn6.10:7.1": "“A man is born ",
  "sn6.10:7.2": "with an axe in his mouth. ",
  "sn6.10:7.3": "A fool cuts themselves with it ",
  "sn6.10:7.4": "when they say bad words. ",
  "sn6.10:8.1": "When you praise someone worthy of criticism, ",
  "sn6.10:8.2": "or criticize someone worthy of praise, ",
  "sn6.10:8.3": "you choose a losing hand with your own mouth: ",
  "sn6.10:8.4": "you’ll never find happiness that way. ",
  "sn6.10:9.1": "A losing hand at dice is a trivial thing, ",
  "sn6.10:9.2": "if all you lose is your money ",
  "sn6.10:9.3": "and all you own, even yourself. ",
  "sn6.10:9.4": "What’s a really terrible hand ",
  "sn6.10:9.5": "is to hate the holy ones. ",
  "sn6.10:10.1": "For a hundred thousand times a hundred million, ",
  "sn6.10:10.2": "times five hundred and thirty-six times <j>a thousand times ten million years ",
  "sn6.10:10.3": "a slanderer of noble ones goes to hell, ",
  "sn6.10:10.4": "having aimed bad words and thoughts at them.” ",
  "sn6.10:10.5": "",
  "sn6.10:11.1": "",
  "sn6.10:11.2": "",
  "sn6.10:11.3": "",
  "sn6.11:0.1": "Linked Discourses 6.11 ",
  "sn6.11:0.2": "Chapter Two ",
  "sn6.11:0.3": "With Sanaṅkumāra ",
  "sn6.11:1.1": "So I have heard. ",
  "sn6.11:1.2": "At one time the Buddha was staying near Rājagaha, on the bank of the Serpentine river. ",
  "sn6.11:1.3": "Then, late at night, the glorious divinity Sanaṅkumāra, lighting up the entire Serpentine riverbank, went up to the Buddha, bowed, stood to one side, ",
  "sn6.11:1.4": "and spoke this verse in the Buddha’s presence: ",
  "sn6.11:2.1": "“The aristocrat is best among people ",
  "sn6.11:2.2": "who take clan as the standard. ",
  "sn6.11:2.3": "But one accomplished in knowledge and conduct ",
  "sn6.11:2.4": "is best among gods and humans.” ",
  "sn6.11:3.1": "That’s what the divinity Sanaṅkumāra said, ",
  "sn6.11:3.2": "and the teacher approved. ",
  "sn6.11:3.3": "Then the divinity Sanaṅkumāra, knowing that the teacher approved, bowed and respectfully circled the Buddha, keeping him on his right, before vanishing right there. ",
  "sn6.12:0.1": "Linked Discourses 6.12 ",
  "sn6.12:0.2": "Chapter Two ",
  "sn6.12:0.3": "About Devadatta ",
  "sn6.12:1.1": "So I have heard. ",
  "sn6.12:1.2": "At one time the Buddha was staying near Rājagaha, on the Vulture’s Peak Mountain, not long after Devadatta had left. ",
  "sn6.12:1.3": "Then, late at night, the glorious divinity Sahampati, lighting up the entire Vulture’s Peak, went up to the Buddha, bowed, stood to one side, ",
  "sn6.12:1.4": "and spoke this verse in the Buddha’s presence: ",
  "sn6.12:2.1": "“The banana plant is destroyed by its own fruit, ",
  "sn6.12:2.2": "as are the bamboo and the reed. ",
  "sn6.12:2.3": "Honor destroys a reprobate, ",
  "sn6.12:2.4": "as pregnancy destroys a mule.” ",
  "sn6.13:0.1": "Linked Discourses 6.13 ",
  "sn6.13:0.2": "Chapter Two ",
  "sn6.13:0.3": "At Andhakavinda ",
  "sn6.13:1.1": "At one time the Buddha was staying in the land of the Magadhans at Andhakavinda. ",
  "sn6.13:1.2": "Now at that time the Buddha was meditating in the open during the dark of night, while a gentle rain drizzled down. ",
  "sn6.13:1.3": "Then, late at night, the glorious divinity Sahampati, lighting up the entirety of Andhakavinda, went up to the Buddha, bowed, stood to one side, ",
  "sn6.13:1.4": "and recited these verses in the Buddha’s presence: ",
  "sn6.13:2.1": "“One should frequent secluded lodgings, ",
  "sn6.13:2.2": "and practice to be released from fetters. ",
  "sn6.13:2.3": "If you don’t find enjoyment there, ",
  "sn6.13:2.4": "live in the Saṅgha, self-protected and mindful. ",
  "sn6.13:3.1": "Walking for alms from family to family, ",
  "sn6.13:3.2": "with senses guarded, alert and mindful. ",
  "sn6.13:3.3": "One should frequent secluded lodgings, ",
  "sn6.13:3.4": "free of fear, freed in the fearless. ",
  "sn6.13:4.1": "Where dreadful serpents slither, ",
  "sn6.13:4.2": "where the lightning flashes and the heavens thunder ",
  "sn6.13:4.3": "in the dark of the night; ",
  "sn6.13:4.4": "there meditates a mendicant, free of goosebumps. ",
  "sn6.13:5.1": "For this is ever seen by me, ",
  "sn6.13:5.2": "it isn’t just the testament of hearsay. ",
  "sn6.13:5.3": "Within a single spiritual dispensation ",
  "sn6.13:5.4": "there are a thousand conquerors of Death. ",
  "sn6.13:6.1": "And of trainees, more than five hundred, ",
  "sn6.13:6.2": "and ten times ten tens, ",
  "sn6.13:6.3": "are all stream-enterers, ",
  "sn6.13:6.4": "freed from rebirth in the animal realm. ",
  "sn6.13:7.1": "And as for the rest of folk ",
  "sn6.13:7.2": "who I think have shared in merit",
  "sn6.13:7.3": "I couldn’t even number them, ",
  "sn6.13:7.4": "for fear of speaking falsely.” ",
  "sn6.14:0.1": "Linked Discourses 6.14 ",
  "sn6.14:0.2": "Chapter Two ",
  "sn6.14:0.3": "About Aruṇavatī ",
  "sn6.14:1.1": "So I have heard. ",
  "sn6.14:1.2": "At one time the Buddha was staying near Sāvatthī. ",
  "sn6.14:1.3": "There he addressed the mendicants, ",
  "sn6.14:1.4": "“Mendicants!” ",
  "sn6.14:1.5": "“Venerable sir,” they replied. ",
  "sn6.14:1.6": "The Buddha said this: ",
  "sn6.14:2.1": "“Once upon a time, mendicants, there was a king named Aruṇavā. ",
  "sn6.14:2.2": "He had a capital named Aruṇavatī. ",
  "sn6.14:2.3": "Sikhī the Blessed One, the perfected one, the fully awakened Buddha lived supported by Aruṇavatī. ",
  "sn6.14:2.4": "Sikhī had a fine pair of chief disciples named Abhibhū and Sambhava. ",
  "sn6.14:2.5": "Then the Buddha Sikhī addressed the mendicant Abhibhū, ",
  "sn6.14:2.6": "‘Come, brahmin, let’s go to one of the realms of divinity until it’s time for our meal.’ ",
  "sn6.14:2.7": "‘Yes, sir,’ replied Abhibhū. ",
  "sn6.14:2.8": "Then, as easily as a strong person would extend or contract their arm, they vanished from Aruṇavatī and appeared in that realm of divinity. ",
  "sn6.14:3.1": "Then the Buddha Sikhī addressed the mendicant Abhibhū, ",
  "sn6.14:3.2": "‘Brahmin, teach the Dhamma as you feel inspired for that Divinity, his assembly, and the members of his retinue.’ ",
  "sn6.14:3.3": "‘Yes, sir,’ replied Abhibhū. Then he educated, encouraged, fired up, and inspired them with a Dhamma talk. ",
  "sn6.14:3.4": "But the Divinity, his assembly, and his retinue complained, grumbled, and objected, ",
  "sn6.14:3.5": "‘Oh lord, how incredible, how amazing! How on earth can a disciple teach Dhamma in the presence of the Teacher?’ ",
  "sn6.14:4.1": "Then the Buddha Sikhī addressed the mendicant Abhibhū, ",
  "sn6.14:4.2": "‘Brahmin, the Divinity, his assembly, and his retinue are complaining ",
  "sn6.14:4.3": "that a disciple teaches Dhamma in the presence of the Teacher. ",
  "sn6.14:4.4": "Well then, brahmin, stir them up even more!’ ",
  "sn6.14:4.5": "‘Yes, sir,’ replied Abhibhū. Then he taught Dhamma with his body visible; with his body invisible; with the lower half visible and the upper half invisible; and with the upper half visible and the lower half invisible. ",
  "sn6.14:4.6": "And the Divinity, his assembly, and his retinue, their minds full of wonder and amazement, thought, ",
  "sn6.14:4.7": "‘Oh lord, how incredible, how amazing! The ascetic has such psychic power and might!’ ",
  "sn6.14:5.1": "Then Abhibhū said to the Buddha Sikhī, ",
  "sn6.14:5.2": "‘Sir, I recall having said this in the middle of the Saṅgha: ",
  "sn6.14:5.3": "“Standing in the realm of divinity, I can make my voice heard throughout the thousandfold galaxy.”’ ",
  "sn6.14:5.4": "‘Now is the time, brahmin! Now is the time, brahmin! ",
  "sn6.14:5.5": "Standing in the realm of divinity, make your voice heard throughout the thousandfold galaxy.’ ",
  "sn6.14:5.6": "‘Yes, sir,’ replied Abhibhū. Standing in the realm of divinity, he spoke this verse: ",
  "sn6.14:6.1": "‘Rouse yourselves! Try harder! ",
  "sn6.14:6.2": "Devote yourselves to the teachings of the Buddha! ",
  "sn6.14:6.3": "Crush the army of Death, ",
  "sn6.14:6.4": "as an elephant a hut of reeds. ",
  "sn6.14:7.1": "Whoever shall meditate diligently ",
  "sn6.14:7.2": "in this teaching and training, ",
  "sn6.14:7.3": "giving up transmigration through rebirths, ",
  "sn6.14:7.4": "will make an end of suffering.’ ",
  "sn6.14:8.1": "Having inspired that Divinity, his assembly, and his retinue with a sense of awe, ",
  "sn6.14:8.2": "as easily as a strong person would extend or contract their arm, Sikhī and Abhibhū vanished from that realm of divinity and appeared in Aruṇavatī. ",
  "sn6.14:8.3": "Then the Buddha Sikhī addressed the mendicants, ",
  "sn6.14:8.4": "‘Mendicants, did you hear the mendicant Abhibhū speaking a verse while standing in a realm of divinity?’ ",
  "sn6.14:8.5": "‘We did, sir.’ ",
  "sn6.14:8.6": "‘But what exactly did you hear?’ ",
  "sn6.14:8.7": "‘This is what we heard, sir: ",
  "sn6.14:9.1": "“Rouse yourselves! Try harder! ",
  "sn6.14:9.2": "Devote yourselves to the teachings of the Buddha! ",
  "sn6.14:9.3": "Crush the army of Death, ",
  "sn6.14:9.4": "as an elephant a hut of reeds. ",
  "sn6.14:10.1": "Whoever shall meditate diligently ",
  "sn6.14:10.2": "in this teaching and training, ",
  "sn6.14:10.3": "giving up transmigration through rebirths, ",
  "sn6.14:10.4": "will make an end of suffering.” ",
  "sn6.14:11.1": "That’s what we heard, sir.’ ",
  "sn6.14:11.2": "‘Good, good, mendicants! ",
  "sn6.14:11.3": "It’s good that you heard the mendicant Abhibhū speaking this verse while standing in a realm of divinity.’” ",
  "sn6.14:12.1": "That is what the Buddha said. Satisfied, the mendicants approved what the Buddha said. ",
  "sn6.15:0.1": "Linked Discourses 6.15 ",
  "sn6.15:0.2": "Chapter Two ",
  "sn6.15:0.3": "Full Extinguishment ",
  "sn6.15:1.1": "At one time the Buddha was staying between a pair of sal trees in the sal forest of the Mallas at Upavattana near Kusinārā at the time of his full extinguishment. ",
  "sn6.15:1.2": "Then the Buddha said to the mendicants: ",
  "sn6.15:1.3": "“Come now, mendicants, I say to you all: ",
  "sn6.15:1.4": "‘Conditions fall apart. Persist with diligence.’” ",
  "sn6.15:1.5": "These were the Realized One’s last words. ",
  "sn6.15:2.1": "Then the Buddha entered the first absorption. Emerging from that, he entered the second absorption. Emerging from that, he successively entered into and emerged from the third absorption, the fourth absorption, the dimension of infinite space, the dimension of infinite consciousness, the dimension of nothingness, and the dimension of neither perception nor non-perception. Then he entered the cessation of perception and feeling. ",
  "sn6.15:3.1": "Then he emerged from the cessation of perception and feeling and entered the dimension of neither perception nor non-perception. Emerging from that, he successively entered into and emerged from the dimension of nothingness, the dimension of infinite consciousness, the dimension of infinite space, the fourth absorption, the third absorption, the second absorption, and the first absorption. Emerging from that, he successively entered into and emerged from the second absorption and the third absorption. Then he entered the fourth absorption. Emerging from that the Buddha immediately became fully extinguished. ",
  "sn6.15:3.2": "When the Buddha was fully quenched, along with the full extinguishment, the divinity Sahampati spoke this verse: ",
  "sn6.15:4.1": "“All creatures in this world ",
  "sn6.15:4.2": "must lay down this bag of bones. ",
  "sn6.15:4.3": "For even a Teacher such as this, ",
  "sn6.15:4.4": "unrivaled in the world, ",
  "sn6.15:4.5": "the Realized One, attained to power, ",
  "sn6.15:4.6": "the Buddha was fully quenched.” ",
  "sn6.15:5.1": "When the Buddha was fully quenched, Sakka, lord of gods, spoke this verse: ",
  "sn6.15:6.1": "“Oh! Conditions are impermanent, ",
  "sn6.15:6.2": "their nature is to rise and fall; ",
  "sn6.15:6.3": "having arisen, they cease; ",
  "sn6.15:6.4": "their settling is such bliss.” ",
  "sn6.15:7.1": "When the Buddha was fully quenched, Venerable Ānanda spoke this verse: ",
  "sn6.15:8.1": "“Then there was terror! ",
  "sn6.15:8.2": "Then they had goosebumps! ",
  "sn6.15:8.3": "When the Buddha, endowed with all fine qualities, ",
  "sn6.15:8.4": "was fully quenched.” ",
  "sn6.15:9.1": "When the Buddha was fully quenched, Venerable Anuruddha spoke this verse: ",
  "sn6.15:10.1": "“There was no more breathing ",
  "sn6.15:10.2": "for the unaffected one of steady heart. ",
  "sn6.15:10.3": "Imperturbable, committed to peace, ",
  "sn6.15:10.4": "the Clear-eyed One was fully quenched. ",
  "sn6.15:11.1": "He put up with painful feelings ",
  "sn6.15:11.2": "without flinching. ",
  "sn6.15:11.3": "The liberation of his heart ",
  "sn6.15:11.4": "was like the extinguishing of a lamp.” ",
  "sn6.15:11.5": "",
  "sn6.15:12.1": "",
  "sn6.15:12.2": "",
  "sn6.15:12.3": "",
  "sn6.15:12.4": "",
  "sn6.15:12.5": "The Linked Discourses on the Divinity are complete. "
}
window.BILARA["sn6_v1"]["en"]["sn6_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
