window.BILARA = window.BILARA || {};
window.BILARA["sn7_v1"] = window.BILARA["sn7_v1"] || {};
window.BILARA["sn7_v1"]["en"] = {
  "sn7.1:0.1": "Linked Discourses 7.1 ",
  "sn7.1:0.2": "1. The Perfected Ones ",
  "sn7.1:0.3": "With Dhanañjānī ",
  "sn7.1:1.1": "So I have heard. ",
  "sn7.1:1.2": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn7.1:1.3": "Now at that time the wife of a certain brahmin of the Bhāradvāja clan, a brahmin lady named Dhanañjānī, was devoted to the Buddha, the teaching, and the Saṅgha. ",
  "sn7.1:1.4": "Once, while she was bringing her husband his meal, she tripped and expressed this heartfelt sentiment three times: ",
  "sn7.1:2.1": "“Homage to him, the blessed one, the perfected one, the fully awakened Buddha! ",
  "sn7.1:3.1": "Homage to him, the blessed one, the perfected one, the fully awakened Buddha! ",
  "sn7.1:4.1": "Homage to him, the blessed one, the perfected one, the fully awakened Buddha!” ",
  "sn7.1:5.1": "When she said this, the brahmin said to Dhanañjānī: ",
  "sn7.1:5.2": "“That’d be right. For the slightest thing this lowlife woman spouts out praise for that bald ascetic. ",
  "sn7.1:5.3": "Right now, lowlife woman, I’m going to refute your teacher’s doctrine!” ",
  "sn7.1:5.4": "“Brahmin, I don’t see anyone in this worldwith its gods, Māras, and Divinities, this population with its ascetics and brahmins, its gods and humanswho can refute the doctrine of the Blessed One, the perfected one, the fully awakened Buddha. ",
  "sn7.1:5.5": "But anyway, you should go. When you’ve gone you’ll understand.” ",
  "sn7.1:6.1": "Then the brahmin of the Bhāradvāja clan, angry and upset, went to the Buddha and exchanged greetings with him. ",
  "sn7.1:6.2": "When the greetings and polite conversation were over, he sat down to one side, ",
  "sn7.1:6.3": "and addressed the Buddha in verse: ",
  "sn7.1:7.1": "“When what is slain do you sleep at ease? ",
  "sn7.1:7.2": "When what is slain is there no sorrow? ",
  "sn7.1:7.3": "What is the one thing ",
  "sn7.1:7.4": "whose killing you approve?” ",
  "sn7.1:8.1": "“When anger’s slain you sleep at ease. ",
  "sn7.1:8.2": "When anger’s slain there is no sorrow. ",
  "sn7.1:8.3": "O brahmin, anger has a poisonous root ",
  "sn7.1:8.4": "and a sweet tip. ",
  "sn7.1:8.5": "The noble ones praise its killing, ",
  "sn7.1:8.6": "for when it’s slain there is no sorrow.” ",
  "sn7.1:9.1": "When he said this, the brahmin said to the Buddha, ",
  "sn7.1:9.2": "“Excellent, worthy Gotama! Excellent! ",
  "sn7.1:9.3": "As if he were righting the overturned, or revealing the hidden, or pointing out the path to the lost, or lighting a lamp in the dark so people with clear eyes can see what’s there, worthy Gotama has made the teaching clear in many ways. ",
  "sn7.1:9.4": "I go for refuge to the worthy Gotama, to the teaching, and to the mendicant Saṅgha. ",
  "sn7.1:9.5": "May I receive the going forth, the ordination in the worthy Gotama’s presence?” ",
  "sn7.1:10.1": "And the brahmin received the going forth, the ordination in the Buddha’s presence. ",
  "sn7.1:10.2": "Not long after his ordination, Venerable Bhāradvāja, living alone, withdrawn, diligent, keen, and resolute, soon realized the supreme end of the spiritual path in this very life. He lived having achieved with his own insight the goal for which gentlemen rightly go forth from the lay life to homelessness. ",
  "sn7.1:10.3": "He understood: “Rebirth is ended; the spiritual journey has been completed; what had to be done has been done; there is nothing further for this place.” ",
  "sn7.1:10.4": "And Venerable Bhāradvāja became one of the perfected. ",
  "sn7.2:0.1": "Linked Discourses 7.2 ",
  "sn7.2:0.2": "1. The Perfected Ones ",
  "sn7.2:0.3": "With Bhāradvāja the Rude ",
  "sn7.2:1.1": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn7.2:1.2": "The brahmin Bhāradvāja the Rude heard a rumor that ",
  "sn7.2:2.1": "a brahmin of the Bhāradvāja clan had gone forth from the lay life to homelessness in the presence of the ascetic Gotama. Angry and displeased he went to the Buddha and abused and insulted him with rude, harsh words. When he had spoken, the Buddha said to him: ",
  "sn7.2:2.2": "“What do you think, brahmin? ",
  "sn7.2:2.3": "Do friends and colleagues, relatives and kin, and guests still come to visit you?” ",
  "sn7.2:2.4": "“Sometimes they do, worthy Gotama.” ",
  "sn7.2:2.5": "“Do you then serve them with fresh and cooked foods and savories?” ",
  "sn7.2:2.6": "“Sometimes I do.” ",
  "sn7.2:2.7": "“But if they don’t accept it, brahmin, who does it belong to?” ",
  "sn7.2:2.8": "“In that case it still belongs to me.” ",
  "sn7.2:2.9": "“In the same way, brahmin, when you abuse, harass, and attack us who do not abuse, harass, and attack, we don’t accept it. ",
  "sn7.2:2.10": "It still belongs to you, brahmin, ",
  "sn7.2:2.11": "it still belongs to you! ",
  "sn7.2:3.1": "Someone who, when abused, harassed, and attacked, abuses, harasses, and attacks in return is said to eat the food and have a reaction to it. ",
  "sn7.2:3.2": "But we neither eat your food nor do we have a reaction to it. ",
  "sn7.2:3.3": "It still belongs to you, brahmin, ",
  "sn7.2:3.4": "it still belongs to you!” ",
  "sn7.2:3.5": "“The king and his retinue believe of the worthy Gotama, ",
  "sn7.2:3.6": "‘the ascetic Gotama is a perfected one’. ",
  "sn7.2:3.7": "And yet he still gets angry.” ",
  "sn7.2:4.1": "“Whence anger for one free of anger, ",
  "sn7.2:4.2": "tamed, living justly, ",
  "sn7.2:4.3": "freed by right knowledge, ",
  "sn7.2:4.4": "peaceful and unaffected? ",
  "sn7.2:5.1": "When you get angry at an angry person ",
  "sn7.2:5.2": "you just make things worse for yourself. ",
  "sn7.2:5.3": "When you don’t get angry at an angry person ",
  "sn7.2:5.4": "you win a battle hard to win. ",
  "sn7.2:6.1": "When you know that the other is angry, ",
  "sn7.2:6.2": "you act for the good of both ",
  "sn7.2:6.3": "yourself and the other ",
  "sn7.2:6.4": "if you’re mindful and stay calm. ",
  "sn7.2:7.1": "People inexpert in the teaching ",
  "sn7.2:7.2": "consider one who heals both ",
  "sn7.2:7.3": "oneself and the other ",
  "sn7.2:7.4": "to be a fool.” ",
  "sn7.2:8.1": "When he had spoken, Bhāradvāja the Rude said to the Buddha, ",
  "sn7.2:8.2": "“Excellent, worthy Gotama! … ",
  "sn7.2:8.3": "I go for refuge to the worthy Gotama, to the teaching, and to the mendicant Saṅgha. ",
  "sn7.2:8.4": "Sir, may I receive the going forth, the ordination in the worthy Gotama’s presence?” ",
  "sn7.2:9.1": "And the brahmin Bhāradvāja the Rude received the going forth, the ordination in the Buddha’s presence. ",
  "sn7.2:9.2": "Not long after his ordination, Venerable Bhāradvāja the Rude, living alone, withdrawn, diligent, keen, and resolute, soon realized the supreme end of the spiritual path in this very life. He lived having achieved with his own insight the goal for which gentlemen rightly go forth from the lay life to homelessness. ",
  "sn7.2:9.3": "He understood: “Rebirth is ended; the spiritual journey has been completed; what had to be done has been done; there is nothing further for this place.” ",
  "sn7.2:9.4": "And Venerable Bhāradvāja became one of the perfected. ",
  "sn7.3:0.1": "Linked Discourses 7.3 ",
  "sn7.3:0.2": "1. The Perfected Ones ",
  "sn7.3:0.3": "With Bhāradvāja the Fiend ",
  "sn7.3:1.1": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn7.3:1.2": "The brahmin Bhāradvāja the Fiend heard a rumor to the effect that ",
  "sn7.3:1.3": "a brahmin of the Bhāradvāja clan had gone forth from the lay life to homelessness in the presence of the ascetic Gotama. Angry and displeased he went to the Buddha and abused and insulted him with rude, harsh words. ",
  "sn7.3:1.4": "But when he said this, the Buddha kept silent. ",
  "sn7.3:1.5": "Then Bhāradvāja the Fiend said to the Buddha, ",
  "sn7.3:1.6": "“You’re beaten, ascetic, you’re beaten!” ",
  "sn7.3:2.1": "“‘Ha! I won!’ thinks the fool, ",
  "sn7.3:2.2": "when speaking with harsh words. ",
  "sn7.3:2.3": "The victory for one who understands ",
  "sn7.3:2.4": "is that very endurance. ",
  "sn7.3:3.1": "When you get angry at an angry person ",
  "sn7.3:3.2": "you just make things worse for yourself. ",
  "sn7.3:3.3": "When you don’t get angry at an angry person ",
  "sn7.3:3.4": "you win a battle hard to win. ",
  "sn7.3:4.1": "When you know that the other is angry, ",
  "sn7.3:4.2": "you act for the good of both ",
  "sn7.3:4.3": "yourself and the other ",
  "sn7.3:4.4": "if you’re mindful and stay calm. ",
  "sn7.3:5.1": "People inexpert in Dhamma ",
  "sn7.3:5.2": "consider one who heals both ",
  "sn7.3:5.3": "oneself and the other ",
  "sn7.3:5.4": "to be a fool.” ",
  "sn7.3:6.1": "When he had spoken, Bhāradvāja the Fiend said to the Buddha, ",
  "sn7.3:6.2": "“Excellent, worthy Gotama! …” … ",
  "sn7.3:6.3": "",
  "sn7.3:6.4": "And Venerable Bhāradvāja became one of the perfected. ",
  "sn7.4:0.1": "Linked Discourses 7.4 ",
  "sn7.4:0.2": "1. The Perfected Ones ",
  "sn7.4:0.3": "With Bhāradvāja the Bitter ",
  "sn7.4:1.1": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn7.4:1.2": "The brahmin Bhāradvāja the Bitter heard a rumor that ",
  "sn7.4:1.3": "a brahmin of the Bhāradvāja clan had gone forth from the lay life to homelessness in the presence of the ascetic Gotama. Angry and displeased he went to the Buddha and stood silently to one side. ",
  "sn7.4:1.4": "Then the Buddha, knowing Bhāradvāja the Bitter’s train of thought, addressed him in verse: ",
  "sn7.4:2.1": "“Whoever wrongs a man who has done no wrong, ",
  "sn7.4:2.2": "a pure man who has not a blemish, ",
  "sn7.4:2.3": "the evil backfires on the fool, ",
  "sn7.4:2.4": "like fine dust thrown upwind.” ",
  "sn7.4:3.1": "When he said this, the brahmin Bhāradvāja the Bitter said to the Buddha, ",
  "sn7.4:3.2": "“Excellent, worthy Gotama! …” … ",
  "sn7.4:3.3": "",
  "sn7.4:3.4": "And Venerable Bhāradvāja became one of the perfected. ",
  "sn7.5:0.1": "Linked Discourses 7.5 ",
  "sn7.5:0.2": "1. The Perfected Ones ",
  "sn7.5:0.3": "Harmless ",
  "sn7.5:1.1": "At Sāvatthī. ",
  "sn7.5:1.2": "Then the brahmin Bhāradvāja the Harmless went up to the Buddha, and exchanged greetings with him. ",
  "sn7.5:1.3": "When the greetings and polite conversation were over, he sat down to one side and said, ",
  "sn7.5:1.4": "“I am Harmless, worthy Gotama, I am Harmless!” ",
  "sn7.5:2.1": "“If you were really like your name, ",
  "sn7.5:2.2": "then you’d be Harmless. ",
  "sn7.5:2.3": "But a truly harmless person ",
  "sn7.5:2.4": "does no harm by way of ",
  "sn7.5:2.5": "body, speech, or mind; ",
  "sn7.5:2.6": "they don’t harm anyone else.” ",
  "sn7.5:3.1": "When he had spoken, the brahmin Bhāradvāja the Harmless said to the Buddha, ",
  "sn7.5:3.2": "“Excellent, worthy Gotama! …” … ",
  "sn7.5:3.3": "",
  "sn7.5:3.4": "And Venerable Bhāradvāja the Harmless became one of the perfected. ",
  "sn7.6:0.1": "Linked Discourses 7.6 ",
  "sn7.6:0.2": "1. The Perfected Ones ",
  "sn7.6:0.3": "With Bhāradvāja of the Matted Hair ",
  "sn7.6:1.1": "At Sāvatthī. ",
  "sn7.6:1.2": "Then the brahmin Bhāradvāja of the Matted Hair went up to the Buddha, and exchanged greetings with him. ",
  "sn7.6:1.3": "When the greetings and polite conversation were over, he sat down to one side, ",
  "sn7.6:1.4": "and addressed the Buddha in verse: ",
  "sn7.6:2.1": "“Tangled within, tangled without: ",
  "sn7.6:2.2": "these people are tangled in tangles. ",
  "sn7.6:2.3": "I ask you this, Gotama: ",
  "sn7.6:2.4": "who can untangle this tangle?” ",
  "sn7.6:3.1": "“A wise person grounded in ethics, ",
  "sn7.6:3.2": "developing the mind and wisdom, ",
  "sn7.6:3.3": "a keen and alert mendicant",
  "sn7.6:3.4": "they can untangle this tangle. ",
  "sn7.6:4.1": "Those in whom greed, hate, and ignorance ",
  "sn7.6:4.2": "have faded away; ",
  "sn7.6:4.3": "the perfected ones with defilements ended",
  "sn7.6:4.4": "they have untangled the tangle. ",
  "sn7.6:5.1": "Where name and form ",
  "sn7.6:5.2": "cease with no residue left behind; ",
  "sn7.6:5.3": "as well as impingement and perception of form: ",
  "sn7.6:5.4": "it’s there that the tangle is cut.” ",
  "sn7.6:6.1": "When he had spoken, Bhāradvāja of the Matted Hair said to the Buddha, ",
  "sn7.6:6.2": "“Excellent, worthy Gotama! …” … ",
  "sn7.6:6.3": "And Venerable Bhāradvāja became one of the perfected. ",
  "sn7.7:0.1": "Linked Discourses 7.7 ",
  "sn7.7:0.2": "1. The Perfected Ones ",
  "sn7.7:0.3": "With Bhāradvāja the Pure ",
  "sn7.7:1.1": "At Sāvatthī. ",
  "sn7.7:1.2": "Then the brahmin Bhāradvāja the Pure went up to the Buddha, and exchanged greetings with him. ",
  "sn7.7:1.3": "When the greetings and polite conversation were over, he sat down to one side, ",
  "sn7.7:1.4": "and spoke this verse in his presence: ",
  "sn7.7:2.1": "“No brahmin in the world is ever purified ",
  "sn7.7:2.2": "even though he’s ethical and mortifies himself. ",
  "sn7.7:2.3": "But one accomplished in knowledge and conduct ",
  "sn7.7:2.4": "is purified, not these other commoners.” ",
  "sn7.7:3.1": "“Even one who mutters many prayers ",
  "sn7.7:3.2": "is no brahmin by birth ",
  "sn7.7:3.3": "if they’re filthy and corrupt within, ",
  "sn7.7:3.4": "supporting themselves by fawning. ",
  "sn7.7:4.1": "Regardless of whether you’re an aristocrat, ",
  "sn7.7:4.2": "a brahmin, peasant, menial, <j>or a corpse-worker or scavenger",
  "sn7.7:4.3": "if you’re energetic and resolute, ",
  "sn7.7:4.4": "always staunchly vigorous, ",
  "sn7.7:4.5": "you’ll attain ultimate purity. ",
  "sn7.7:4.6": "Know that for a fact, brahmin.” ",
  "sn7.7:5.1": "When he had spoken, the brahmin Bhāradvāja the Pure said to the Buddha, ",
  "sn7.7:5.2": "“Excellent, worthy Gotama …” … ",
  "sn7.7:5.3": "And Venerable Bhāradvāja became one of the perfected. ",
  "sn7.8:0.1": "Linked Discourses 7.8 ",
  "sn7.8:0.2": "1. The Perfected Ones ",
  "sn7.8:0.3": "With Bhāradvāja the Fire-Worshiper ",
  "sn7.8:1.1": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground. ",
  "sn7.8:1.2": "Now at that time ghee and milk-rice had been set out for the brahmin Bhāradvāja the Fire-Worshiper, who thought, ",
  "sn7.8:1.3": "“I will serve the sacred flame! I will perform the fire sacrifice!” ",
  "sn7.8:2.1": "Then the Buddha robed up in the morning and, taking his bowl and robe, entered Rājagaha for alms. ",
  "sn7.8:2.2": "Wandering indiscriminately for almsfood in Rājagaha, he approached Bhāradvāja the Fire-Worshiper’s home and stood to one side. ",
  "sn7.8:2.3": "Bhāradvāja the Fire-Worshiper saw him standing for alms ",
  "sn7.8:2.4": "and addressed him in verse: ",
  "sn7.8:3.1": "“One who’s accomplished in the three knowledges, ",
  "sn7.8:3.2": "of good birth and ample learning, ",
  "sn7.8:3.3": "accomplished in knowledge and conduct ",
  "sn7.8:3.4": "may enjoy this milk-rice.” ",
  "sn7.8:4.1": "“Even one who mutters many prayers ",
  "sn7.8:4.2": "is no brahmin by birth ",
  "sn7.8:4.3": "if they’re filthy and corrupt within, ",
  "sn7.8:4.4": "with a following gained by fawning. ",
  "sn7.8:5.1": "One who knows their past lives, ",
  "sn7.8:5.2": "sees heaven and places of loss, ",
  "sn7.8:5.3": "and has attained the ending of rebirth, ",
  "sn7.8:5.4": "is a sage of perfect insight. ",
  "sn7.8:6.1": "Because of these three knowledges ",
  "sn7.8:6.2": "a brahmin is a master of the three knowledges. ",
  "sn7.8:6.3": "Accomplished in knowledge and conduct, ",
  "sn7.8:6.4": "they may enjoy this milk-rice.” ",
  "sn7.8:7.1": "“May the worthy Gotama eat! ",
  "sn7.8:7.2": "The worthy one is a brahmin.” ",
  "sn7.8:8.1": "“Food enchanted by a verse isn’t fit for me to eat. ",
  "sn7.8:8.2": "That’s not the principle of those who see, brahmin. ",
  "sn7.8:8.3": "The Buddhas cast aside things enchanted with verses. ",
  "sn7.8:8.4": "Since there is such a principle, brahmin, <j>that’s how they live. ",
  "sn7.8:9.1": "Serve with other food and drink ",
  "sn7.8:9.2": "the consummate one, the great seer, ",
  "sn7.8:9.3": "with defilements ended and remorse stilled. ",
  "sn7.8:9.4": "For he is the field for the seeker of merit.” ",
  "sn7.8:10.1": "When he had spoken, the brahmin Bhāradvāja the Fire-Worshiper said to the Buddha, ",
  "sn7.8:10.2": "“Excellent, worthy Gotama! …” … ",
  "sn7.8:10.3": "And Venerable Bhāradvāja the Fire-Worshiper became one of the perfected. ",
  "sn7.9:0.1": "Linked Discourses 7.9 ",
  "sn7.9:0.2": "1. The Perfected Ones ",
  "sn7.9:0.3": "With Bhāradvāja of Sundarikā ",
  "sn7.9:1.1": "At one time the Buddha was staying in the Kosalan lands on the bank of the Sundarikā river. ",
  "sn7.9:1.2": "Now at that time the brahmin Bhāradvāja of Sundarikā was serving the sacred flame and performing the fire sacrifice on the bank of the Sundarikā. ",
  "sn7.9:1.3": "Then he surveyed the four quarters, wondering, ",
  "sn7.9:1.4": "“Now who might eat the leftovers of this oblation?” ",
  "sn7.9:1.5": "He saw the Buddha meditating at the root of a certain tree with his robe pulled over his head. ",
  "sn7.9:1.6": "Taking the leftovers of the oblation in his left hand and a pitcher in the right he approached the Buddha. ",
  "sn7.9:1.7": "When he heard Bhāradvāja of Sundarikā’s footsteps the Buddha uncovered his head. ",
  "sn7.9:1.8": "Bhāradvāja of Sundarikā thought, “This man is shaven, he is shaven!” And he wanted to turn back. ",
  "sn7.9:1.9": "But he thought, ",
  "sn7.9:1.10": "“Even some brahmins are shaven. ",
  "sn7.9:1.11": "Why don’t I go to him and ask about his birth?” ",
  "sn7.9:2.1": "Then the brahmin Bhāradvāja of Sundarikā went up to the Buddha, and said to him, ",
  "sn7.9:2.2": "“Sir, what are you by birth?” ",
  "sn7.9:3.1": "“Don’t ask about birth, ask about conduct; ",
  "sn7.9:3.2": "for the fire of Jātaveda is born from sticks. ",
  "sn7.9:3.3": "A steadfast sage, even though from a low class family, ",
  "sn7.9:3.4": "is a thoroughbred checked by conscience. ",
  "sn7.9:4.1": "Tamed by truth, fulfilled by taming, ",
  "sn7.9:4.2": "a complete knowledge master <j>who has completed the spiritual journey",
  "sn7.9:4.3": "that’s who a sacrificer should woo, ",
  "sn7.9:4.4": "and offer a timely oblation <j>to one worthy of a religious donation.” ",
  "sn7.9:5.1": "“My sacrificial offering <j>must have been well performed, ",
  "sn7.9:5.2": "since I have met such a knowledge master! ",
  "sn7.9:5.3": "It’s because I’d never met anyone like you ",
  "sn7.9:5.4": "that others ate the leftover oblation. ",
  "sn7.9:6.1": "May the worthy Gotama eat! ",
  "sn7.9:6.2": "The worthy one is a brahmin.” ",
  "sn7.9:7.1": "“Food enchanted by a verse isn’t fit for me to eat. ",
  "sn7.9:7.2": "That’s not the principle of those who see, brahmin. ",
  "sn7.9:7.3": "The Buddhas cast aside things enchanted with verses. ",
  "sn7.9:7.4": "Since there is such a principle, brahmin, <j>that’s how they live. ",
  "sn7.9:8.1": "Serve with other food and drink ",
  "sn7.9:8.2": "the consummate one, the great seer, ",
  "sn7.9:8.3": "with defilements ended and remorse stilled. ",
  "sn7.9:8.4": "For he is the field for the seeker of merit.” ",
  "sn7.9:9.1": "“Then, Mister Gotama, to whom should I give the leftovers of this oblation?” ",
  "sn7.9:9.2": "“Brahmin, I don’t see anyone in this worldwith its gods, Māras, and Divinities, this population with its ascetics and brahmins, its gods and humanswho can properly digest these leftovers, except for the Realized One or one of his disciples. ",
  "sn7.9:9.3": "Well then, brahmin, throw out those leftovers where there is little that grows, or drop them into water that has no living creatures.” ",
  "sn7.9:10.1": "So Bhāradvāja of Sundarikā dropped the leftover oblation in water that had no living creatures. ",
  "sn7.9:10.2": "And when those leftovers were placed in the water, they sizzled and hissed, steaming and fuming. ",
  "sn7.9:10.3": "Suppose there was an iron cauldron that had been heated all day. If you placed it in the water, it would sizzle and hiss, steaming and fuming. ",
  "sn7.9:10.4": "In the same way, when those leftovers were placed in the water, they sizzled and hissed, steaming and fuming. ",
  "sn7.9:11.1": "Then the brahmin Bhāradvāja of Sundarikā, shocked and awestruck, went up to the Buddha, and stood to one side. ",
  "sn7.9:11.2": "The Buddha addressed him in verse: ",
  "sn7.9:12.1": "“When you’re kindling the wood, brahmin, ",
  "sn7.9:12.2": "don’t imagine this is purity, for it’s just external. ",
  "sn7.9:12.3": "For those who are skilled say this is no way to purity, ",
  "sn7.9:12.4": "when one seeks purity in externals. ",
  "sn7.9:13.1": "I’ve given up kindling firewood, brahmin, ",
  "sn7.9:13.2": "now I light only the inner flame. ",
  "sn7.9:13.3": "Always blazing, always serene, ",
  "sn7.9:13.4": "I am a perfected one leading the spiritual life. ",
  "sn7.9:14.1": "Conceit, brahmin, is the burden of your pack, ",
  "sn7.9:14.2": "anger your smoke, and lies your ashes. ",
  "sn7.9:14.3": "The tongue is the ladle, the heart the fireplace; ",
  "sn7.9:14.4": "a well-tamed self is a person’s light. ",
  "sn7.9:15.1": "The teaching is a lake, brahmin, <j>into which ethics are the stairs, ",
  "sn7.9:15.2": "unclouded, praised by the fine to the good. ",
  "sn7.9:15.3": "There the knowledge masters go to bathe, ",
  "sn7.9:15.4": "and cross to the far shore with dry limbs. ",
  "sn7.9:16.1": "Truth, principle, restraint, the spiritual life, ",
  "sn7.9:16.2": "attaining divinity based on the middle, brahmin ",
  "sn7.9:16.3": "pay homage to the upright ones. ",
  "sn7.9:16.4": "I declare that man one who follows the teaching.” ",
  "sn7.9:17.1": "When he had spoken, the brahmin Bhāradvāja of Sundarikā said to the Buddha, ",
  "sn7.9:17.2": "“Excellent, worthy Gotama …” … ",
  "sn7.9:17.3": "And Venerable Bhāradvāja became one of the perfected. ",
  "sn7.10:0.1": "Linked Discourses 7.10 ",
  "sn7.10:0.2": "1. The Perfected Ones ",
  "sn7.10:0.3": "Many Daughters ",
  "sn7.10:1.1": "At one time the Buddha was staying in the land of the Kosalans in a certain forest grove. ",
  "sn7.10:1.2": "Now at that time one of the brahmins of the Bhāradvāja clan had lost fourteen oxen. ",
  "sn7.10:1.3": "While looking for them he went to that forest grove, where he saw the Buddha sitting down cross-legged, his body set straight, and mindfulness brought to the present. ",
  "sn7.10:1.4": "He went up to the Buddha, and recited these verses in the Buddha’s presence: ",
  "sn7.10:2.1": "“This ascetic mustn’t have ",
  "sn7.10:2.2": "fourteen oxen ",
  "sn7.10:2.3": "missing for the past six days: ",
  "sn7.10:2.4": "that’s why this ascetic is happy. ",
  "sn7.10:3.1": "This ascetic mustn’t have ",
  "sn7.10:3.2": "a field of sesame ruined, ",
  "sn7.10:3.3": "with just one or two leaves: ",
  "sn7.10:3.4": "that’s why this ascetic is happy. ",
  "sn7.10:4.1": "This ascetic mustn’t have ",
  "sn7.10:4.2": "rats in a vacant barn ",
  "sn7.10:4.3": "dancing merrily: ",
  "sn7.10:4.4": "that’s why this ascetic is happy. ",
  "sn7.10:5.1": "This ascetic mustn’t have ",
  "sn7.10:5.2": "carpets that for seven months ",
  "sn7.10:5.3": "have been infested with fleas: ",
  "sn7.10:5.4": "that’s why this ascetic is happy. ",
  "sn7.10:6.1": "This ascetic mustn’t have ",
  "sn7.10:6.2": "seven widowed daughters ",
  "sn7.10:6.3": "with one or two children each: ",
  "sn7.10:6.4": "that’s why this ascetic is happy. ",
  "sn7.10:7.1": "This ascetic mustn’t have ",
  "sn7.10:7.2": "a wife with sallow, blotchy skin ",
  "sn7.10:7.3": "to wake him with a kick: ",
  "sn7.10:7.4": "that’s why this ascetic is happy. ",
  "sn7.10:8.1": "This ascetic mustn’t have ",
  "sn7.10:8.2": "creditors knocking at dawn, ",
  "sn7.10:8.3": "demanding, ‘Pay up! Pay up!’: ",
  "sn7.10:8.4": "that’s why this ascetic is happy.” ",
  "sn7.10:9.1": "“You’re right, brahmin, I don’t have ",
  "sn7.10:9.2": "fourteen oxen ",
  "sn7.10:9.3": "missing for the past six days: ",
  "sn7.10:9.4": "that’s why I’m happy, brahmin. ",
  "sn7.10:10.1": "You’re right, brahmin, I don’t have ",
  "sn7.10:10.2": "a field of sesame ruined, ",
  "sn7.10:10.3": "with just one or two leaves: ",
  "sn7.10:10.4": "that’s why I’m happy, brahmin. ",
  "sn7.10:11.1": "You’re right, brahmin, I don’t have ",
  "sn7.10:11.2": "rats in a vacant barn ",
  "sn7.10:11.3": "dancing merrily: ",
  "sn7.10:11.4": "that’s why I’m happy, brahmin. ",
  "sn7.10:12.1": "You’re right, brahmin, I don’t have ",
  "sn7.10:12.2": "carpets that for seven months ",
  "sn7.10:12.3": "have been infested with fleas: ",
  "sn7.10:12.4": "that’s why I’m happy, brahmin. ",
  "sn7.10:13.1": "You’re right, brahmin, I don’t have ",
  "sn7.10:13.2": "seven widowed daughters ",
  "sn7.10:13.3": "with one or two children each: ",
  "sn7.10:13.4": "that’s why I’m happy, brahmin. ",
  "sn7.10:14.1": "You’re right, brahmin, I don’t have ",
  "sn7.10:14.2": "a wife with blotchy, pockmarked skin ",
  "sn7.10:14.3": "to wake me up with a kick: ",
  "sn7.10:14.4": "that’s why I’m happy, brahmin. ",
  "sn7.10:15.1": "You’re right, brahmin, I don’t have ",
  "sn7.10:15.2": "creditors knocking at dawn, ",
  "sn7.10:15.3": "warning, ‘Pay up! Pay up!’: ",
  "sn7.10:15.4": "that’s why I’m happy, brahmin.” ",
  "sn7.10:16.1": "When he had spoken, the brahmin said to the Buddha, ",
  "sn7.10:16.2": "“Excellent, worthy Gotama! Excellent! … ",
  "sn7.10:16.3": "As if he were righting the overturned, or revealing the hidden, or pointing out the path to the lost, or lighting a lamp in the dark so people with clear eyes can see what’s there, worthy Gotama has made the teaching clear in many ways. ",
  "sn7.10:16.4": "I go for refuge to the worthy Gotama, to the teaching, and to the mendicant Saṅgha. ",
  "sn7.10:16.5": "May I receive the going forth, the ordination in the worthy Gotama’s presence?” ",
  "sn7.10:17.1": "And the brahmin received the going forth, the ordination in the Buddha’s presence. ",
  "sn7.10:17.2": "Not long after his ordination, Venerable Bhāradvāja, living alone, withdrawn, diligent, keen, and resolute, soon realized the supreme end of the spiritual path in this very life. He lived having achieved with his own insight the goal for which gentlemen rightly go forth from the lay life to homelessness. ",
  "sn7.10:17.3": "He understood: “Rebirth is ended; the spiritual journey has been completed; what had to be done has been done; there is nothing further for this place.” ",
  "sn7.10:17.4": "And Venerable Bhāradvāja became one of the perfected. ",
  "sn7.10:17.5": "",
  "sn7.10:18.1": "",
  "sn7.10:18.2": "",
  "sn7.10:18.3": "",
  "sn7.10:18.4": "",
  "sn7.10:18.5": "",
  "sn7.11:0.1": "Linked Discourses 7.11 ",
  "sn7.11:0.2": "2. Lay Followers ",
  "sn7.11:0.3": "With Bhāradvāja the Farmer ",
  "sn7.11:1.1": "So I have heard. ",
  "sn7.11:1.2": "At one time the Buddha was staying in the land of the Magadhans in the Southern Hills near the brahmin village of Ekanāḷa. ",
  "sn7.11:1.3": "Now at that time the brahmin Bhāradvāja the Farmer had harnessed around five hundred plows, it being the season for sowing. ",
  "sn7.11:1.4": "Then the Buddha robed up in the morning and, taking his bowl and robe, went to where Bhāradvāja the Farmer was working. ",
  "sn7.11:2.1": "Now at that time Bhāradvāja the Farmer was distributing food. ",
  "sn7.11:2.2": "Then the Buddha went to where the distribution was taking place and stood to one side. ",
  "sn7.11:2.3": "Bhāradvāja the Farmer saw him standing for alms ",
  "sn7.11:2.4": "and said to him, ",
  "sn7.11:2.5": "“I plough and sow, ascetic, and then I eat. ",
  "sn7.11:2.6": "You too should plough and sow, then you may eat.” ",
  "sn7.11:2.7": "“I too plough and sow, brahmin, and then I eat.” ",
  "sn7.11:2.8": "“I don’t see the worthy Gotama with a yoke or plow or plowshare or goad or oxen, yet he says: ",
  "sn7.11:2.9": "‘I too plough and sow, brahmin, and then I eat.’” ",
  "sn7.11:2.10": "Then Bhāradvāja the Farmer addressed the Buddha in verse: ",
  "sn7.11:3.1": "“You claim to be a farmer, ",
  "sn7.11:3.2": "but I don’t see you farming. ",
  "sn7.11:3.3": "Tell me how you’re a farmer when asked: ",
  "sn7.11:3.4": "how am I to recognize your farming?” ",
  "sn7.11:4.1": "“Faith is my seed, fervor my rain, ",
  "sn7.11:4.2": "and wisdom is my yoke and plough. ",
  "sn7.11:4.3": "Conscience is my draft-pole, mind my strap, ",
  "sn7.11:4.4": "mindfulness my plowshare and goad. ",
  "sn7.11:5.1": "Guarded in body and speech, ",
  "sn7.11:5.2": "I restrict my intake of food. ",
  "sn7.11:5.3": "I use truth as my scythe, ",
  "sn7.11:5.4": "and gentleness is my release. ",
  "sn7.11:6.1": "Energy is my harnessed beast, ",
  "sn7.11:6.2": "transporting me to sanctuary from the yoke. ",
  "sn7.11:6.3": "It goes without turning back ",
  "sn7.11:6.4": "to where there is no sorrow. ",
  "sn7.11:7.1": "That’s how to do the farming ",
  "sn7.11:7.2": "that has freedom from death as its fruit. ",
  "sn7.11:7.3": "When you finish this farming ",
  "sn7.11:7.4": "you’re released from all suffering.” ",
  "sn7.11:8.1": "“May the worthy Gotama eat! ",
  "sn7.11:8.2": "The worthy one is a farmer. ",
  "sn7.11:8.3": "For the worthy Gotama does the farming that has freedom from death as its fruit.” ",
  "sn7.11:9.1": "“Food enchanted by a verse isn’t fit for me to eat. ",
  "sn7.11:9.2": "That’s not the principle of those who see, brahmin. ",
  "sn7.11:9.3": "The Buddhas cast aside things enchanted with verses. ",
  "sn7.11:9.4": "Since there is such a principle, brahmin, <j>that’s how they live. ",
  "sn7.11:10.1": "Serve with other food and drink ",
  "sn7.11:10.2": "the consummate one, the great seer, ",
  "sn7.11:10.3": "with defilements ended and remorse stilled. ",
  "sn7.11:10.4": "For he is the field for the seeker of merit.” ",
  "sn7.11:11.1": "When he had spoken, the brahmin Bhāradvāja the Farmer said to the Buddha, ",
  "sn7.11:11.2": "“Excellent, worthy Gotama … ",
  "sn7.11:11.3": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn7.12:0.1": "Linked Discourses 7.12 ",
  "sn7.12:0.2": "2. Lay Followers ",
  "sn7.12:0.3": "With Udaya ",
  "sn7.12:1.1": "At Sāvatthī. ",
  "sn7.12:1.2": "Then the Buddha robed up in the morning and, taking his bowl and robe, went to the home of the brahmin Udaya. ",
  "sn7.12:1.3": "Then Udaya filled the Buddha’s bowl with rice. ",
  "sn7.12:1.4": "The next day … Udaya again filled the Buddha’s bowl with rice. ",
  "sn7.12:1.5": "But when he had filled the Buddha’s bowl on the third day, he said to the Buddha, ",
  "sn7.12:1.6": "“This ascetic Gotama is such a drag! He keeps coming back again and again!” ",
  "sn7.12:2.1": "“Again and again, they sow the seed; ",
  "sn7.12:2.2": "again and again, the king of the heavens sends rain; ",
  "sn7.12:2.3": "again and again, farmers plough the field; ",
  "sn7.12:2.4": "again and again, grain is produced for the nation. ",
  "sn7.12:3.1": "Again and again, the beggars beg; ",
  "sn7.12:3.2": "again and again, the donors give. ",
  "sn7.12:3.3": "Again and again, when the donors have given, ",
  "sn7.12:3.4": "again and again, they take their place in heaven. ",
  "sn7.12:4.1": "Again and again, dairy farmers milk; ",
  "sn7.12:4.2": "again and again, a calf cleaves to its mother; ",
  "sn7.12:4.3": "again and again, oppressing and intimidating, ",
  "sn7.12:4.4": "that dullard returns to the womb again and again. ",
  "sn7.12:5.1": "Again and again, you’re reborn and die; ",
  "sn7.12:5.2": "again and again, you get carried to a charnel ground. ",
  "sn7.12:5.3": "But when they’ve gained the path <j>for no further rebirth, ",
  "sn7.12:5.4": "one of vast wisdom is not reborn again and again.” ",
  "sn7.12:6.1": "When he had spoken, the brahmin Udaya said to the Buddha, ",
  "sn7.12:6.2": "“Excellent, worthy Gotama … ",
  "sn7.12:6.3": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn7.13:0.1": "Linked Discourses 7.13 ",
  "sn7.13:0.2": "2. Lay Followers ",
  "sn7.13:0.3": "With Devahita ",
  "sn7.13:1.1": "At Sāvatthī. ",
  "sn7.13:1.2": "Now at that time the Buddha was afflicted by winds. ",
  "sn7.13:1.3": "Venerable Upavāṇa was his carer. ",
  "sn7.13:1.4": "Then the Buddha said to Upavāṇa, ",
  "sn7.13:1.5": "“Go on then, Upavāṇa, find some hot water for me.” ",
  "sn7.13:1.6": "“Yes, sir,” replied Upavāṇa. He robed up, and, taking his bowl and robe, went to the home of the brahmin Devahita, and stood silently to one side. ",
  "sn7.13:1.7": "Devahita saw him standing there ",
  "sn7.13:1.8": "and addressed him in verse: ",
  "sn7.13:2.1": "“Silent stands the worthy one, ",
  "sn7.13:2.2": "shaven, wrapped in his outer robe. ",
  "sn7.13:2.3": "What do you want? What are you looking for? ",
  "sn7.13:2.4": "What have you come here to ask for?” ",
  "sn7.13:3.1": "“The perfected one, the Holy One in the world, ",
  "sn7.13:3.2": "the sage is afflicted by winds. ",
  "sn7.13:3.3": "If there’s hot water, ",
  "sn7.13:3.4": "give it to the sage, brahmin. ",
  "sn7.13:4.1": "I wish to bring it to the one ",
  "sn7.13:4.2": "who is esteemed by the estimable, ",
  "sn7.13:4.3": "honored by the honorable, ",
  "sn7.13:4.4": "venerated by the venerable.” ",
  "sn7.13:5.1": "Then Devahita had a man fetch a carrying-pole with hot water. He also presented Upavāṇa with a jar of molasses. ",
  "sn7.13:5.2": "Then Venerable Upavāṇa went up to the Buddha and bathed him with the hot water. Then he stirred molasses into hot water and presented it to the Buddha. ",
  "sn7.13:5.3": "Then the Buddha’s illness died down. ",
  "sn7.13:6.1": "Then the brahmin Devahita went up to the Buddha, and exchanged greetings with him. ",
  "sn7.13:6.2": "When the greetings and polite conversation were over, he sat down to one side, ",
  "sn7.13:6.3": "and addressed the Buddha in verse: ",
  "sn7.13:7.1": "“Where should you give an available gift? ",
  "sn7.13:7.2": "Where is a gift very fruitful? ",
  "sn7.13:7.3": "How does one who is donating ",
  "sn7.13:7.4": "ensure the success of their religious donation?” ",
  "sn7.13:8.1": "“One who knows their past lives, ",
  "sn7.13:8.2": "sees heaven and places of loss, ",
  "sn7.13:8.3": "and has attained the ending of rebirth, ",
  "sn7.13:8.4": "is a sage of perfect insight. ",
  "sn7.13:9.1": "Here you should give an available gift; ",
  "sn7.13:9.2": "what’s given here is very fruitful. ",
  "sn7.13:9.3": "That’s how a sponsor of sacrifices ",
  "sn7.13:9.4": "ensures the success of their religious donation.” ",
  "sn7.13:10.1": "When he had spoken, the brahmin Devahita said to the Buddha, ",
  "sn7.13:10.2": "“Excellent, worthy Gotama … ",
  "sn7.13:10.3": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn7.14:0.1": "Linked Discourses 7.14 ",
  "sn7.14:0.2": "2. Lay Followers ",
  "sn7.14:0.3": "A well-to-do brahmin ",
  "sn7.14:1.1": "At Sāvatthī. ",
  "sn7.14:1.2": "Then a certain well-to-do brahmin, shabby, wearing a shabby cloak, went up to the Buddha, and exchanged greetings with him. ",
  "sn7.14:1.3": "When the greetings and polite conversation were over, he sat down to one side. The Buddha said to him, ",
  "sn7.14:1.4": "“Brahmin, why are you so shabby, wearing a shabby cloak?” ",
  "sn7.14:1.5": "“Worthy Gotama, I have four sons. ",
  "sn7.14:1.6": "At their wives’ bidding they expelled me from my house.” ",
  "sn7.14:1.7": "“Well then, brahmin, memorize these verses and recite them to your sons when you are all seated in the council hall with a large crowd. ",
  "sn7.14:2.1": "‘I was overjoyed when they were born, ",
  "sn7.14:2.2": "and wished prosperity for them. ",
  "sn7.14:2.3": "But at their wives’ bidding they chased me out, ",
  "sn7.14:2.4": "like hounds after hogs. ",
  "sn7.14:3.1": "It turns out they’re wicked, those nasty men, ",
  "sn7.14:3.2": "though they called me their dear old Dad. ",
  "sn7.14:3.3": "They’re monsters in the shape of sons, ",
  "sn7.14:3.4": "throwing me out as I’ve grown old. ",
  "sn7.14:4.1": "Like an old, useless horse ",
  "sn7.14:4.2": "led away from its fodder, ",
  "sn7.14:4.3": "the elderly father of those kids ",
  "sn7.14:4.4": "begs for alms at others’ homes. ",
  "sn7.14:5.1": "Even my staff is better ",
  "sn7.14:5.2": "than those disobedient sons, ",
  "sn7.14:5.3": "for it wards off a wild bull, ",
  "sn7.14:5.4": "and even a wild dog. ",
  "sn7.14:6.1": "It goes before me in the dark; ",
  "sn7.14:6.2": "in deep waters it finds a footing. ",
  "sn7.14:6.3": "By the wonderful power of this staff, ",
  "sn7.14:6.4": "when I stumble, I stand firm again.’” ",
  "sn7.14:7.1": "Having memorized those verses in the Buddha’s presence, the brahmin recited them to his sons when they were all seated in the council hall with a large crowd. … ",
  "sn7.14:8.1": "",
  "sn7.14:8.2": "",
  "sn7.14:8.3": "",
  "sn7.14:8.4": "",
  "sn7.14:9.1": "",
  "sn7.14:9.2": "",
  "sn7.14:9.3": "",
  "sn7.14:9.4": "",
  "sn7.14:10.1": "",
  "sn7.14:10.2": "",
  "sn7.14:10.3": "",
  "sn7.14:10.4": "",
  "sn7.14:11.1": "",
  "sn7.14:11.2": "",
  "sn7.14:11.3": "",
  "sn7.14:11.4": "",
  "sn7.14:12.1": "",
  "sn7.14:12.2": "",
  "sn7.14:12.3": "",
  "sn7.14:12.4": "",
  "sn7.14:13.1": "Then the brahmin’s sons led him back home, bathed him, and each clothed him with a fine pair of garments. ",
  "sn7.14:13.2": "Then the brahmin, taking one pair of garments, went to the Buddha and exchanged greetings with him. ",
  "sn7.14:13.3": "When the greetings and polite conversation were over, he sat down to one side and said to the Buddha: ",
  "sn7.14:13.4": "“Worthy Gotama, we brahmins seek a fee for our tutor. ",
  "sn7.14:13.5": "May the worthy Gotama please accept my tutor’s fee!” ",
  "sn7.14:13.6": "So the Buddha accepted it out of sympathy. ",
  "sn7.14:13.7": "Then the well-to-do brahmin said to the Buddha, ",
  "sn7.14:13.8": "“Excellent, worthy Gotama … ",
  "sn7.14:13.9": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn7.15:0.1": "Linked Discourses 7.15 ",
  "sn7.15:0.2": "2. Lay Followers ",
  "sn7.15:0.3": "Stuck-Up ",
  "sn7.15:1.1": "At Sāvatthī. ",
  "sn7.15:1.2": "Now at that time a brahmin named Stuck-Up was residing in Sāvatthī. ",
  "sn7.15:1.3": "He didn’t bow to his mother or father, his tutor, or his oldest brother. ",
  "sn7.15:1.4": "Now, at that time the Buddha was teaching Dhamma, surrounded by a large assembly. ",
  "sn7.15:1.5": "Then Stuck-Up thought, ",
  "sn7.15:1.6": "“The ascetic Gotama is teaching Dhamma, surrounded by a large assembly. ",
  "sn7.15:1.7": "Why don’t I approach him? ",
  "sn7.15:1.8": "If he speaks to me, I’ll speak to him. ",
  "sn7.15:1.9": "But if he doesn’t speak, neither will I.” ",
  "sn7.15:1.10": "Then the brahmin Stuck-Up went up to the Buddha, and stood silently to one side. ",
  "sn7.15:1.11": "But the Buddha didn’t speak to him. ",
  "sn7.15:1.12": "Then Stuck-Up thought, ",
  "sn7.15:1.13": "“This ascetic Gotama knows nothing!” And he wanted to go back from there right away. ",
  "sn7.15:1.14": "Then the Buddha, knowing Stuck-Up’s train of thought, addressed him in verse: ",
  "sn7.15:2.1": "“It’s not good to foster conceit ",
  "sn7.15:2.2": "if you want what’s good for you, brahmin. ",
  "sn7.15:2.3": "You should foster the goal ",
  "sn7.15:2.4": "which brought you here.” ",
  "sn7.15:3.1": "Then Stuck-Up thought, ",
  "sn7.15:3.2": "“The ascetic Gotama knows my mind!” He bowed with his head at the Buddha’s feet, caressing them and covering them with kisses, and pronounced his name: ",
  "sn7.15:3.3": "“Worthy Gotama, I am Stuck-Up! I am Stuck-Up!” ",
  "sn7.15:3.4": "Then that assembly was stunned: ",
  "sn7.15:3.5": "“Oh lord, how incredible, how amazing! ",
  "sn7.15:3.6": "This brahmin Stuck-Up doesn’t bow to his mother or father, his tutor, or his oldest brother. ",
  "sn7.15:3.7": "Yet he shows such utmost deference to the ascetic Gotama!” ",
  "sn7.15:3.8": "Then the Buddha said to the brahmin Stuck-Up, ",
  "sn7.15:3.9": "“Enough, brahmin. Get up, and take your own seat. ",
  "sn7.15:3.10": "For your mind has confidence in me.” ",
  "sn7.15:3.11": "Then Stuck-Up took his seat and said to the Buddha: ",
  "sn7.15:4.1": "“Regarding whom should you not be conceited? ",
  "sn7.15:4.2": "Who should you respect? ",
  "sn7.15:4.3": "Who should you esteem? ",
  "sn7.15:4.4": "Who is it good to venerate properly?” ",
  "sn7.15:5.1": "“Your mother and father, ",
  "sn7.15:5.2": "and also your oldest brother, ",
  "sn7.15:5.3": "with tutor as fourth. ",
  "sn7.15:5.4": "Regarding these you should not be conceited. ",
  "sn7.15:5.5": "They are who you should respect. ",
  "sn7.15:5.6": "They are who you should esteem. ",
  "sn7.15:5.7": "And they’re who it’s good to venerate properly. ",
  "sn7.15:6.1": "And when with bent knee, not stiff with conceit, ",
  "sn7.15:6.2": "show supreme reverence for ",
  "sn7.15:6.3": "the perfected onescooled, ",
  "sn7.15:6.4": "their task complete, free of defilements.” ",
  "sn7.15:7.1": "When he had spoken, the brahmin Stuck-Up said to the Buddha, ",
  "sn7.15:7.2": "“Excellent, worthy Gotama … ",
  "sn7.15:7.3": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn7.16:0.1": "Linked Discourses 7.16 ",
  "sn7.16:0.2": "2. Lay Followers ",
  "sn7.16:0.3": "The Contraphile ",
  "sn7.16:1.1": "At Sāvatthī. ",
  "sn7.16:1.2": "Now at that time a brahmin named Contraphile, who loved contradiction, was residing in Sāvatthī. ",
  "sn7.16:1.3": "Then Contraphile thought, ",
  "sn7.16:1.4": "“Why don’t I go to the ascetic Gotama and ",
  "sn7.16:1.5": "contradict everything he says?” ",
  "sn7.16:1.6": "At that time the Buddha was walking mindfully in the open air. ",
  "sn7.16:1.7": "Then the brahmin Contraphile went up to the Buddha, and said to him as he was walking, ",
  "sn7.16:1.8": "“Ascetic, preach the Dhamma.” ",
  "sn7.16:2.1": "“Fine words aren’t easy to understand ",
  "sn7.16:2.2": "by a lover of contradiction, ",
  "sn7.16:2.3": "whose mind is tainted ",
  "sn7.16:2.4": "and full of aggression. ",
  "sn7.16:3.1": "But when you’ve dispelled aggression, ",
  "sn7.16:3.2": "and your suspicious mind, ",
  "sn7.16:3.3": "and you’ve got rid of resentment, ",
  "sn7.16:3.4": "then you’ll understand fine words.” ",
  "sn7.16:4.1": "When he had spoken, the brahmin Contraphile said to the Buddha, ",
  "sn7.16:4.2": "“Excellent, worthy Gotama! Excellent! … ",
  "sn7.16:4.3": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn7.17:0.1": "Linked Discourses 7.17 ",
  "sn7.17:0.2": "2. Lay Followers ",
  "sn7.17:0.3": "The Builder ",
  "sn7.17:1.1": "At one time the Buddha was staying in the land of the Kosalans in a certain forest grove. ",
  "sn7.17:1.2": "Now at that time the brahmin Bhāradvāja the Builder was having some building work done in that jungle thicket. ",
  "sn7.17:1.3": "He saw the Buddha sitting down cross-legged at the root of a certain sal tree, his body set straight, and mindfulness brought to the present. ",
  "sn7.17:1.4": "Seeing this, it occurred to him, ",
  "sn7.17:1.5": "“I enjoy having this building work done here in the jungle. ",
  "sn7.17:1.6": "I wonder what the ascetic Gotama enjoys having done?” ",
  "sn7.17:1.7": "Then Bhāradvāja the Builder went up to the Buddha and addressed him in verse: ",
  "sn7.17:2.1": "“What kind of works are done by you, ",
  "sn7.17:2.2": "a mendicant in the sal jungle? ",
  "sn7.17:2.3": "How do you find enjoyment ",
  "sn7.17:2.4": "alone in the wilderness, Gotama?” ",
  "sn7.17:3.1": "“There’s nothing I need do in the jungle; ",
  "sn7.17:3.2": "my jungle’s cut at the root, it’s withered away. ",
  "sn7.17:3.3": "Free of snarls and thorns in the jungle, ",
  "sn7.17:3.4": "I enjoy solitude, having given up discontent.” ",
  "sn7.17:4.1": "When he had spoken, the brahmin Bhāradvāja the Builder said to the Buddha, ",
  "sn7.17:4.2": "“Excellent, worthy Gotama … ",
  "sn7.17:4.3": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn7.18:0.1": "Linked Discourses 7.18 ",
  "sn7.18:0.2": "2. Lay Followers ",
  "sn7.18:0.3": "Collecting Firewood ",
  "sn7.18:1.1": "At one time the Buddha was staying in the land of the Kosalans in a certain forest grove. ",
  "sn7.18:1.2": "Then several students, pupils of one of the Bhāradvāja brahmins, approached a forest grove while collecting firewood. They saw the Buddha sitting down cross-legged at the root of a certain sal tree, his body set straight, and mindfulness brought to the present. Seeing this, they went up to Bhāradvāja and said to him, ",
  "sn7.18:1.3": "“Please sir, you should know this. ",
  "sn7.18:1.4": "In such and such a forest grove the ascetic Gotama is sitting down cross-legged, his body set straight, and mindfulness brought to the present.” ",
  "sn7.18:1.5": "Then Bhāradvāja together with those young students went to that forest grove ",
  "sn7.18:1.6": "where he saw the Buddha sitting down cross-legged, his body set straight, and mindfulness brought to the present. ",
  "sn7.18:1.7": "He went up to the Buddha and addressed him in verse: ",
  "sn7.18:2.1": "“Deep in the jungle so full of terrors, ",
  "sn7.18:2.2": "you’ve plunged into the empty, desolate wilderness. ",
  "sn7.18:2.3": "Still, steady, and graceful: ",
  "sn7.18:2.4": "how beautifully you meditate, mendicant! ",
  "sn7.18:3.1": "Where there is no song or music, ",
  "sn7.18:3.2": "a lonely sage resorts to the wilderness. ",
  "sn7.18:3.3": "This strikes me as an amazing thing, ",
  "sn7.18:3.4": "that you dwell so joyfully alone in the jungle. ",
  "sn7.18:4.1": "I suppose you wish to be reborn in the company ",
  "sn7.18:4.2": "of the supreme world-sovereign of the Third Heaven. ",
  "sn7.18:4.3": "Is that why you resort to the desolate wilderness, ",
  "sn7.18:4.4": "to practice fervor for attaining divinity?” ",
  "sn7.18:5.1": "“Any wishes and hopes that are always attached ",
  "sn7.18:5.2": "to the many and various realms",
  "sn7.18:5.3": "the yearnings sprung from the root of unknowing",
  "sn7.18:5.4": "I’ve eliminated them all down to the root. ",
  "sn7.18:6.1": "So I’m wishless, unattached, uninvolved; ",
  "sn7.18:6.2": "amongst all things, my vision is clear. ",
  "sn7.18:6.3": "I’ve attained the state of grace, <j>the supreme awakening; ",
  "sn7.18:6.4": "I meditate alone, brahmin, and self-assured.” ",
  "sn7.18:7.1": "When he had spoken, Bhāradvāja said to the Buddha, ",
  "sn7.18:7.2": "“Excellent, worthy Gotama! Excellent! … ",
  "sn7.18:7.3": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn7.19:0.1": "Linked Discourses 7.19 ",
  "sn7.19:0.2": "2. Lay Followers ",
  "sn7.19:0.3": "The Brahmin Who Provided for His Mother ",
  "sn7.19:1.1": "At Sāvatthī. ",
  "sn7.19:1.2": "Then a brahmin who provided for his mother went up to the Buddha, and exchanged greetings with him. ",
  "sn7.19:1.3": "When the greetings and polite conversation were over, he sat down to one side and said to the Buddha, ",
  "sn7.19:1.4": "“Worthy Gotama, I seek alms by legitimate means, which I use to provide for my mother and father. ",
  "sn7.19:1.5": "In doing so, am I doing my duty?” ",
  "sn7.19:1.6": "“Indeed, brahmin, in so doing you are doing your duty. ",
  "sn7.19:1.7": "Whoever seeks alms by legitimate means, and uses them to provide for their mother and father brims with much merit. ",
  "sn7.19:2.1": "A mortal provides for their mother ",
  "sn7.19:2.2": "and father by legitimate means; ",
  "sn7.19:2.3": "because they serve ",
  "sn7.19:2.4": "their parents like this, ",
  "sn7.19:2.5": "they’re praised in this life by the astute, ",
  "sn7.19:2.6": "and they depart to rejoice in heaven.” ",
  "sn7.19:3.1": "When he said this, the brahmin who provided for his mother said to the Buddha, ",
  "sn7.19:3.2": "“Excellent, worthy Gotama! Excellent! … ",
  "sn7.19:3.3": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn7.20:0.1": "Linked Discourses 7.20 ",
  "sn7.20:0.2": "2. Lay Followers ",
  "sn7.20:0.3": "An Almsman ",
  "sn7.20:1.1": "At Sāvatthī. ",
  "sn7.20:1.2": "Then a brahmin almsman went up to the Buddha, and exchanged greetings with him. ",
  "sn7.20:1.3": "When the greetings and polite conversation were over, he sat down to one side and said to the Buddha, ",
  "sn7.20:1.4": "“Worthy Gotama, both you and I are almsmen. What, then, is the difference between us?” ",
  "sn7.20:2.1": "“You don’t become an almsman ",
  "sn7.20:2.2": "just by begging alms from others. ",
  "sn7.20:2.3": "One who has undertaken domestic duties ",
  "sn7.20:2.4": "has not yet become a mendicant. ",
  "sn7.20:3.1": "But one living a spiritual life ",
  "sn7.20:3.2": "who has banished both merit and evil, ",
  "sn7.20:3.3": "and wanders having appraised the world, ",
  "sn7.20:3.4": "is said to be a mendicant.” ",
  "sn7.20:4.1": "When he had spoken, the brahmin almsman said to the Buddha, ",
  "sn7.20:4.2": "“Excellent, worthy Gotama! Excellent! … ",
  "sn7.20:4.3": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn7.21:0.1": "Linked Discourses 7.21 ",
  "sn7.21:0.2": "2. Lay Followers ",
  "sn7.21:0.3": "With Saṅgārava ",
  "sn7.21:1.1": "At Sāvatthī. ",
  "sn7.21:1.2": "Now at that time there was a brahmin named Saṅgārava staying in Sāvatthī. He practiced purification by water, believing in purification by water. He lived committed to the practice of immersing himself in water at daybreak and dusk. ",
  "sn7.21:1.3": "Then Venerable Ānanda robed up in the morning and, taking his bowl and robe, entered Sāvatthī for alms. ",
  "sn7.21:1.4": "He wandered for alms in Sāvatthī. After the meal, on his return from almsround, he went to the Buddha, bowed, sat down to one side, and said to him, ",
  "sn7.21:1.5": "“Sir, there is a brahmin named Saṅgārava staying in Sāvatthī. He practices purification by water, believing in purification by water. He lives devoted to ritual bathing at daybreak and dusk. ",
  "sn7.21:1.6": "Please visit him at his home out of sympathy.” ",
  "sn7.21:1.7": "The Buddha consented with silence. ",
  "sn7.21:2.1": "Then the Buddha robed up in the morning and, taking his bowl and robe, went to the home of the brahmin Saṅgārava, and sat down on the seat spread out. ",
  "sn7.21:2.2": "Then the brahmin Saṅgārava went up to the Buddha, and exchanged greetings with him. ",
  "sn7.21:2.3": "When the greetings and polite conversation were over, he sat down to one side. The Buddha said to him, ",
  "sn7.21:2.4": "“Is it really true, brahmin, that you practice purification by water, believing in purification by water; that you live committed to the practice of immersing yourself in water at daybreak and dusk?” ",
  "sn7.21:2.5": "“Yes, worthy Gotama.” ",
  "sn7.21:2.6": "“But brahmin, for what reason do you practice purification by water?” ",
  "sn7.21:2.7": "“It’s because, Mister Gotama, whatever bad deeds I’ve done during the day I rinse off by bathing at dusk; and whatever bad deeds I’ve done during the night, I rinse off by bathing at dawn. ",
  "sn7.21:2.8": "That’s the reason why I practice purification by water.” ",
  "sn7.21:3.1": "“The teaching is a lake, brahmin, <j>into which ethics are the stairs, ",
  "sn7.21:3.2": "unclouded, praised by the fine to the good. ",
  "sn7.21:3.3": "There the knowledge masters go to bathe, ",
  "sn7.21:3.4": "and cross to the far shore with dry limbs.” ",
  "sn7.21:4.1": "When he had spoken, Saṅgārava said to the Buddha, ",
  "sn7.21:4.2": "“Excellent, worthy Gotama! Excellent! … ",
  "sn7.21:4.3": "From this day forth, may the worthy Gotama remember me as a lay follower who has gone for refuge for life.” ",
  "sn7.22:0.1": "Linked Discourses 7.22 ",
  "sn7.22:0.2": "2. Lay Followers ",
  "sn7.22:0.3": "At Khomadussa ",
  "sn7.22:1.1": "So I have heard. ",
  "sn7.22:1.2": "At one time the Buddha was staying in the land of the Sakyans, where they have a town named Khomadussa. ",
  "sn7.22:1.3": "Then the Buddha robed up in the morning and, taking his bowl and robe, entered Khomadussa for alms. ",
  "sn7.22:1.4": "Now at that time the brahmins and householders of Khomadussa were gathered in the council hall for some business, while a gentle rain drizzled down. ",
  "sn7.22:1.5": "Then the Buddha approached that council. ",
  "sn7.22:1.6": "The brahmins and householders saw the Buddha coming off in the distance, ",
  "sn7.22:1.7": "and said, ",
  "sn7.22:1.8": "“Who are these shavelings, these fake ascetics? Don’t they understand the council rules?” ",
  "sn7.22:1.9": "Then the Buddha addressed the brahmins and householders of Khomadussa in verse: ",
  "sn7.22:2.1": "“If good people are not present it is no true council; ",
  "sn7.22:2.2": "and those whose speak against principle <j>are not good people. ",
  "sn7.22:2.3": "Having given up greed, hate, and delusion, ",
  "sn7.22:2.4": "speakers of principle are good people.” ",
  "sn7.22:3.1": "When he had spoken, the brahmins and householders of Khomadussa said to the Buddha, ",
  "sn7.22:3.2": "“Excellent, worthy Gotama! Excellent! ",
  "sn7.22:3.3": "As if he were righting the overturned, or revealing the hidden, or pointing out the path to the lost, or lighting a lamp in the dark so people with clear eyes can see what’s there, worthy Gotama has made the teaching clear in many ways. ",
  "sn7.22:3.4": "We go for refuge to the worthy Gotama, to the teaching, and to the mendicant Saṅgha. ",
  "sn7.22:3.5": "From this day forth, may the worthy Gotama remember us as lay followers who have gone for refuge for life.” ",
  "sn7.22:3.6": "",
  "sn7.22:4.1": "",
  "sn7.22:4.2": "",
  "sn7.22:4.3": "",
  "sn7.22:4.4": "",
  "sn7.22:4.5": "",
  "sn7.22:4.6": "",
  "sn7.22:4.7": "The Linked Discourses with Brahmins are complete. "
}
window.BILARA["sn7_v1"]["en"]["sn7_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
