window.BILARA = window.BILARA || {};
window.BILARA["sn9_v1"] = window.BILARA["sn9_v1"] || {};
window.BILARA["sn9_v1"]["en"] = {
  "sn9.1:0.1": "Linked Discourses 9.1 ",
  "sn9.1:0.2": "1. In the Woods ",
  "sn9.1:0.3": "Seclusion ",
  "sn9.1:1.1": "So I have heard. ",
  "sn9.1:1.2": "At one time one of the mendicants was staying in the land of the Kosalans in a certain forest grove. ",
  "sn9.1:1.3": "Now at that time that mendicant, during their day’s meditation, was thinking bad, unskillful thoughts to do with the domestic life. ",
  "sn9.1:1.4": "The deity haunting that forest had sympathy for that mendicant, and wanted what’s best for them. So they approached that mendicant wanting to stir them up, and addressed them in verse: ",
  "sn9.1:2.1": "“You entered the woods desiring seclusion, ",
  "sn9.1:2.2": "yet your mind strays to outward things. ",
  "sn9.1:2.3": "As a person, dispel the desire for people; ",
  "sn9.1:2.4": "then you’ll be happy, free of greed. ",
  "sn9.1:3.1": "Give up discontent; be mindful; ",
  "sn9.1:3.2": "let us remind you to be mindful. ",
  "sn9.1:3.3": "The dusty abyss is so hard to cross; ",
  "sn9.1:3.4": "don’t let sensual dust drag you down. ",
  "sn9.1:4.1": "Just as a bird strewn with dirt ",
  "sn9.1:4.2": "sheds that clingy dust with a shake; ",
  "sn9.1:4.3": "so too, an energetic, mindful mendicant ",
  "sn9.1:4.4": "sheds that clingy dust with a shake.” ",
  "sn9.1:5.1": "Impelled by that deity, that mendicant was struck with a sense of urgency. ",
  "sn9.2:0.1": "Linked Discourses 9.2 ",
  "sn9.2:0.2": "1. In the Woods ",
  "sn9.2:0.3": "Application ",
  "sn9.2:1.1": "At one time one of the mendicants was staying in the land of the Kosalans in a certain forest grove. ",
  "sn9.2:1.2": "Now at that time that mendicant went for the day’s meditation, but fell asleep. ",
  "sn9.2:1.3": "The deity haunting that forest had sympathy for that mendicant, and wanted what’s best for them. So they approached that mendicant wanting to stir them up, and addressed them in verse: ",
  "sn9.2:2.1": "“Get up, mendicant! Why lie down? ",
  "sn9.2:2.2": "What’s the point in sleeping? ",
  "sn9.2:2.3": "How can the afflicted slumber, ",
  "sn9.2:2.4": "inflicted by an arrow strike? ",
  "sn9.2:3.1": "You should amplify the faith ",
  "sn9.2:3.2": "that led you to go forth ",
  "sn9.2:3.3": "from the home life to homelessness. ",
  "sn9.2:3.4": "Don’t fall under the sway of slumber.” ",
  "sn9.2:4.1": "“Sensual pleasures are impermanent and unstable, ",
  "sn9.2:4.2": "but dullards still fall for them. ",
  "sn9.2:4.3": "Among those who are bound, <j>they’re free and unattached: ",
  "sn9.2:4.4": "why bother a renunciate? ",
  "sn9.2:5.1": "By removing desire and greed, ",
  "sn9.2:5.2": "by going beyond ignorance, ",
  "sn9.2:5.3": "that knowledge has been perfectly cleansed: ",
  "sn9.2:5.4": "why bother a renunciate? ",
  "sn9.2:6.1": "By breaking ignorance with knowledge, ",
  "sn9.2:6.2": "by the ending of defilements, ",
  "sn9.2:6.3": "they’re sorrowless, unstressed: ",
  "sn9.2:6.4": "why bother a renunciate? ",
  "sn9.2:7.1": "Energetic, resolute, ",
  "sn9.2:7.2": "always staunchly vigorous, ",
  "sn9.2:7.3": "aspiring to extinguishment: ",
  "sn9.2:7.4": "why bother a renunciate?” ",
  "sn9.3:0.1": "Linked Discourses 9.3 ",
  "sn9.3:0.2": "1. In the Woods ",
  "sn9.3:0.3": "With Kassapagotta ",
  "sn9.3:1.1": "At one time Venerable Kassapagotta was staying in the land of the Kosalans in a certain forest grove. ",
  "sn9.3:1.2": "Now at that time Venerable Kassapagotta, having withdrawn for his day’s meditation, tried to advise a nimrod. ",
  "sn9.3:1.3": "Then the deity haunting that forest approached Kassapagotta wanting to stir him up, and recited these verses: ",
  "sn9.3:2.1": "“A nimrod wandering the rugged hills ",
  "sn9.3:2.2": "is unintelligent, unthinking. ",
  "sn9.3:2.3": "It’s a waste of time to advise him, mendicant; ",
  "sn9.3:2.4": "he strikes me as an idiot. ",
  "sn9.3:3.1": "He listens without understanding, ",
  "sn9.3:3.2": "looks without seeing. ",
  "sn9.3:3.3": "Though the teaching is spoken, ",
  "sn9.3:3.4": "the fool doesn’t get it. ",
  "sn9.3:4.1": "Even if you lit ten lamps ",
  "sn9.3:4.2": "and brought them to him, Kassapa, ",
  "sn9.3:4.3": "he wouldn’t see anything, ",
  "sn9.3:4.4": "for he has no eyes to see.” ",
  "sn9.3:5.1": "Impelled by that deity, Venerable Kassapagotta was struck with a sense of urgency. ",
  "sn9.4:0.1": "Linked Discourses 9.4 ",
  "sn9.4:0.2": "1. In the Woods ",
  "sn9.4:0.3": "Several Mendicants Set Out Wandering ",
  "sn9.4:1.1": "At one time several mendicants were staying in the land of the Kosalans in a certain forest grove. ",
  "sn9.4:1.2": "Then after completing the three months of the rainy season residence, those mendicants set out wandering. ",
  "sn9.4:1.3": "Not seeing those mendicants, the deity haunting that forest cried. And on that occasion they spoke this verse: ",
  "sn9.4:2.1": "“Dissatisfaction, <j>it seems to me today, ",
  "sn9.4:2.2": "seeing so many vacated seats. ",
  "sn9.4:2.3": "They were so learned, such brilliant speakers! ",
  "sn9.4:2.4": "Where have these disciples of Gotama gone?” ",
  "sn9.4:3.1": "When they had spoken, another deity replied with this verse: ",
  "sn9.4:4.1": "“They’ve gone to Magadha, they’ve gone to Kosala, ",
  "sn9.4:4.2": "and some are in the Vajjian lands. ",
  "sn9.4:4.3": "Like deer that wander free of ties, ",
  "sn9.4:4.4": "the mendicants live with no abode.” ",
  "sn9.5:0.1": "Linked Discourses 9.5 ",
  "sn9.5:0.2": "1. In the Woods ",
  "sn9.5:0.3": "With Ānanda ",
  "sn9.5:1.1": "At one time Venerable Ānanda was staying in the land of the Kosalans in a certain forest grove. ",
  "sn9.5:1.2": "Now at that time Ānanda was spending too much time persuading lay people. ",
  "sn9.5:1.3": "Then the deity haunting that forest had sympathy for Ānanda, wanting what’s best for him. So they approached him wanting to stir him up, and recited these verses: ",
  "sn9.5:2.1": "“You’ve left for the jungle, the root of a tree, ",
  "sn9.5:2.2": "having laid extinguishment in your heart. ",
  "sn9.5:2.3": "Meditate, Gotama, don’t be negligent! ",
  "sn9.5:2.4": "What use is this hullabaloo to you?” ",
  "sn9.5:3.1": "Impelled by that deity, Venerable Ānanda was struck with a sense of urgency. ",
  "sn9.6:0.1": "Linked Discourses 9.6 ",
  "sn9.6:0.2": "1. In the Woods ",
  "sn9.6:0.3": "With Anuruddha ",
  "sn9.6:1.1": "At one time Venerable Anuruddha was staying in the land of the Kosalans in a certain forest grove. ",
  "sn9.6:1.2": "Then a certain deity of the company of the thirty-three named Penelope had been Anuruddha’s partner in a former life. She went up to Anuruddha, and recited these verses: ",
  "sn9.6:2.1": "“Set your heart there, ",
  "sn9.6:2.2": "where you used to live: ",
  "sn9.6:2.3": "among the gods of the thirty-three, ",
  "sn9.6:2.4": "whose every desire is granted! ",
  "sn9.6:2.5": "At the fore of a retinue ",
  "sn9.6:2.6": "of divine maidens, you’ll shine!” ",
  "sn9.6:3.1": "“Divine maidens are in a sorry state, ",
  "sn9.6:3.2": "stuck in substantial reality. ",
  "sn9.6:3.3": "And those beings too are in a sorry state, ",
  "sn9.6:3.4": "who are attached to divine maidens.” ",
  "sn9.6:4.1": "“They don’t know pleasure ",
  "sn9.6:4.2": "who don’t see the Garden of Delight! ",
  "sn9.6:4.3": "It’s the abode of lordly gods, ",
  "sn9.6:4.4": "the glorious host of Thirty!” ",
  "sn9.6:5.1": "“Fool, don’t you understand ",
  "sn9.6:5.2": "the saying of the perfected ones: ",
  "sn9.6:5.3": "all conditions are impermanent, ",
  "sn9.6:5.4": "their nature is to rise and fall; ",
  "sn9.6:5.5": "having arisen, they cease; ",
  "sn9.6:5.6": "their settling is such bliss. ",
  "sn9.6:6.1": "O Penelope, weaver of the web",
  "sn9.6:6.2": "there are no more abodes for me in the host of gods. ",
  "sn9.6:6.3": "Transmigration through births is finished, ",
  "sn9.6:6.4": "now there’ll be no more future lives.” ",
  "sn9.7:0.1": "Linked Discourses 9.7 ",
  "sn9.7:0.2": "1. In the Woods ",
  "sn9.7:0.3": "With Nāgadatta ",
  "sn9.7:1.1": "At one time Venerable Nāgadatta was staying in the land of the Kosalans in a certain forest grove. ",
  "sn9.7:1.2": "Now at that time Venerable Nāgadatta had been entering the village too early and returning late in the day. ",
  "sn9.7:1.3": "Then the deity haunting that forest had sympathy for Nāgadatta, wanting what’s best for him. So they approached him wanting to stir him up, and recited these verses: ",
  "sn9.7:2.1": "“Entering the village too early, ",
  "sn9.7:2.2": "and returning too late in the day, ",
  "sn9.7:2.3": "Nāgadatta mixes with lay people, ",
  "sn9.7:2.4": "sharing their joys and sorrows. ",
  "sn9.7:3.1": "I’m afraid for Nāgadatta; he’s reckless, ",
  "sn9.7:3.2": "shackled to families. ",
  "sn9.7:3.3": "May he not come under the King of Death’s power, ",
  "sn9.7:3.4": "under the sway of the terminator!” ",
  "sn9.7:4.1": "Impelled by that deity, Venerable Nāgadatta was struck with a sense of urgency. ",
  "sn9.8:0.1": "Linked Discourses 9.8 ",
  "sn9.8:0.2": "1. In the Woods ",
  "sn9.8:0.3": "The Mistress of the House ",
  "sn9.8:1.1": "At one time one of the monks was staying in the land of the Kosalans in a certain forest grove. ",
  "sn9.8:1.2": "Now at that time that monk had become too closely involved in the affairs of a certain family. ",
  "sn9.8:1.3": "The deity haunting that forest had sympathy for that monk, wanting what’s best for him. So, wanting to stir him up, they manifested in the appearance of the mistress of that family, approached the monk, and addressed him in verse: ",
  "sn9.8:2.1": "“At river banks and guest houses, ",
  "sn9.8:2.2": "hotels and highways, ",
  "sn9.8:2.3": "people gather to gossip about ",
  "sn9.8:2.4": "what’s going on between you and me.” ",
  "sn9.8:3.1": "“There are many sounds echoing ",
  "sn9.8:3.2": "that a fervent ascetic must endure. ",
  "sn9.8:3.3": "They ought not be dismayed by that, ",
  "sn9.8:3.4": "for that’s not what defiles you. ",
  "sn9.8:4.1": "If you’re startled by every little sound, ",
  "sn9.8:4.2": "like a wind-deer in the wood, ",
  "sn9.8:4.3": "they’ll call you ‘flighty minded’; ",
  "sn9.8:4.4": "and your practice won’t succeed.” ",
  "sn9.9:0.1": "Linked Discourses 9.9 ",
  "sn9.9:0.2": "1. In the Woods ",
  "sn9.9:0.3": "A Vajji ",
  "sn9.9:1.1": "At one time a certain Vajjian mendicant was staying near Vesālī in a certain forest grove. ",
  "sn9.9:1.2": "Now at that time the Vajjis were holding an all-night event in Vesālī. ",
  "sn9.9:1.3": "Then that mendicant, complaining at the noise of musical instruments being beaten and played, on that occasion spoke this verse: ",
  "sn9.9:2.1": "“We dwell alone in the wilderness, ",
  "sn9.9:2.2": "like a log dumped in the forest. ",
  "sn9.9:2.3": "On a night like this, ",
  "sn9.9:2.4": "who’s worse off than me?” ",
  "sn9.9:3.1": "The deity haunting that forest had sympathy for that mendicant, and wanted what’s best for them. So they approached that mendicant wanting to stir them up, and addressed them in verse: ",
  "sn9.9:4.1": "“You dwell alone in the wilderness, ",
  "sn9.9:4.2": "like a log dumped in the forest. ",
  "sn9.9:4.3": "Lots of people are jealous of you, ",
  "sn9.9:4.4": "like beings in hell of those going to heaven.” ",
  "sn9.9:5.1": "Impelled by that deity, that mendicant was struck with a sense of urgency. ",
  "sn9.10:0.1": "Linked Discourses 9.10 ",
  "sn9.10:0.2": "1. In the Woods ",
  "sn9.10:0.3": "Recitation ",
  "sn9.10:1.1": "At one time one of the mendicants was staying in the land of the Kosalans in a certain forest grove. ",
  "sn9.10:1.2": "Now at that time that mendicant had previously been spending too much time rehearsing. But some time later they adhered to passivity and silence. ",
  "sn9.10:1.3": "Not hearing the teaching, the deity haunting that forest approached that mendicant, and addressed them in verse: ",
  "sn9.10:2.1": "“Mendicant, why don’t you recite <j>passages of the teaching, ",
  "sn9.10:2.2": "living together with other mendicants? ",
  "sn9.10:2.3": "Hearing the teaching, one garners confidence; ",
  "sn9.10:2.4": "and in this very life, one garners praise.” ",
  "sn9.10:3.1": "“I used to be zealous for <j>passages of the teaching, ",
  "sn9.10:3.2": "until I encountered dispassion. ",
  "sn9.10:3.3": "When I encountered dispassion, ",
  "sn9.10:3.4": "whatever was seen, heard, and thought, ",
  "sn9.10:3.5": "this, good people say, <j>is the laying down by complete understanding.” ",
  "sn9.11:0.1": "Linked Discourses 9.11 ",
  "sn9.11:0.2": "1. In the Woods ",
  "sn9.11:0.3": "Unskillful Thoughts ",
  "sn9.11:1.1": "At one time one of the mendicants was staying in the land of the Kosalans in a certain forest grove. ",
  "sn9.11:1.2": "Now at that time that mendicant, during their day’s meditation, was thinking bad, unskillful thoughts, that is, ",
  "sn9.11:1.3": "sensual, malicious, and cruel thoughts. ",
  "sn9.11:1.4": "The deity haunting that forest had sympathy for that mendicant, and wanted what’s best for them. So they approached that mendicant wanting to stir them up, and addressed them in verse: ",
  "sn9.11:2.1": "“Because of irrational application of mind, ",
  "sn9.11:2.2": "you’re consumed by your thoughts. ",
  "sn9.11:2.3": "When you’ve given up irrationality, ",
  "sn9.11:2.4": "make sure your thoughts are rational. ",
  "sn9.11:3.1": "Thinking about the Teacher, the teaching, ",
  "sn9.11:3.2": "the Saṅgha, and your own ethics, ",
  "sn9.11:3.3": "you’ll find gladness, ",
  "sn9.11:3.4": "and rapture and bliss as well, no doubt. ",
  "sn9.11:3.5": "And when you’re full of joy, ",
  "sn9.11:3.6": "you’ll make an end to suffering.” ",
  "sn9.11:4.1": "Impelled by that deity, that mendicant was struck with a sense of urgency. ",
  "sn9.12:0.1": "Linked Discourses 9.12 ",
  "sn9.12:0.2": "1. In the Woods ",
  "sn9.12:0.3": "Midday ",
  "sn9.12:1.1": "At one time one of the mendicants was staying in the land of the Kosalans in a certain forest grove. ",
  "sn9.12:1.2": "The deity haunting that forest approached that mendicant and spoke this verse in their presence: ",
  "sn9.12:2.1": "“In the still of high noon, ",
  "sn9.12:2.2": "when the birds have settled down, ",
  "sn9.12:2.3": "the mighty forest itself resounds",
  "sn9.12:2.4": "that strikes me as so scary!” ",
  "sn9.12:3.1": "“In the still of high noon, ",
  "sn9.12:3.2": "when the birds have settled down, ",
  "sn9.12:3.3": "the mighty forest itself resounds",
  "sn9.12:3.4": "that strikes me as so delightful!” ",
  "sn9.13:0.1": "Linked Discourses 9.13 ",
  "sn9.13:0.2": "1. In the Woods ",
  "sn9.13:0.3": "Undisciplined Faculties ",
  "sn9.13:1.1": "At one time several mendicants were staying in the Kosalan lands in a certain forest grove. They were restless, insolent, fickle, scurrilous, loose-tongued, unmindful, lacking situational awareness and immersion, with straying minds and undisciplined faculties. ",
  "sn9.13:1.2": "The deity haunting that forest had sympathy for those mendicants, and wanted what’s best for them. So they approached those mendicants wanting to stir them up, and addressed them in verse: ",
  "sn9.13:2.1": "“The mendicants used to live happily, ",
  "sn9.13:2.2": "as disciples of Gotama. ",
  "sn9.13:2.3": "Desireless they sought alms; ",
  "sn9.13:2.4": "desireless they used their lodgings. ",
  "sn9.13:2.5": "Knowing that the world was impermanent ",
  "sn9.13:2.6": "they made an end of suffering. ",
  "sn9.13:3.1": "But now they’ve made themselves hard to look after, ",
  "sn9.13:3.2": "like chiefs in a village. ",
  "sn9.13:3.3": "They eat and eat and then lie down, ",
  "sn9.13:3.4": "unconscious in the homes of others. ",
  "sn9.13:4.1": "Having raised my joined palms to the Saṅgha, ",
  "sn9.13:4.2": "I speak here only about certain people. ",
  "sn9.13:4.3": "They’re dregs, with no protector, ",
  "sn9.13:4.4": "just like those who have passed away. ",
  "sn9.13:5.1": "I’m speaking about ",
  "sn9.13:5.2": "those who live negligently. ",
  "sn9.13:5.3": "To those who live diligently ",
  "sn9.13:5.4": "I pay homage.” ",
  "sn9.13:6.1": "Impelled by that deity, those mendicants were struck with a sense of urgency. ",
  "sn9.14:0.1": "Linked Discourses 9.14 ",
  "sn9.14:0.2": "1. In the Woods ",
  "sn9.14:0.3": "The Thief of Scent ",
  "sn9.14:1.1": "At one time one of the mendicants was staying in the land of the Kosalans in a certain forest grove. ",
  "sn9.14:1.2": "Now at that time, after the meal, on their return from almsround, that mendicant plunged into a lotus pond and sniffed a pink lotus. ",
  "sn9.14:1.3": "The deity haunting that forest had sympathy for that mendicant, and wanted what’s best for them. So they approached that mendicant wanting to stir them up, and addressed them in verse: ",
  "sn9.14:2.1": "“This water flower has not been given. ",
  "sn9.14:2.2": "When you sniff it, ",
  "sn9.14:2.3": "this is one factor of theft. ",
  "sn9.14:2.4": "Good fellow, you are a thief of scent!” ",
  "sn9.14:3.1": "“I do not take, nor do I break; ",
  "sn9.14:3.2": "I sniff the water flower from afar. ",
  "sn9.14:3.3": "So how do you explain why ",
  "sn9.14:3.4": "you call me a thief of scent? ",
  "sn9.14:4.1": "Why don’t you accuse someone ",
  "sn9.14:4.2": "who does such vandalizing ",
  "sn9.14:4.3": "as digging up the roots, ",
  "sn9.14:4.4": "or breaking off the flowers?” ",
  "sn9.14:5.1": "“I have nothing to say ",
  "sn9.14:5.2": "to a person who is a crude vandal, ",
  "sn9.14:5.3": "soiled like a used nappy. ",
  "sn9.14:5.4": "You’re the one who deserves to be spoken to. ",
  "sn9.14:6.1": "To the man who has not a blemish ",
  "sn9.14:6.2": "who is always seeking purity, ",
  "sn9.14:6.3": "even a hair-tip of evil ",
  "sn9.14:6.4": "seems as big as a stormcloud.” ",
  "sn9.14:7.1": "“Indeed, O spirit, you understand me, ",
  "sn9.14:7.2": "and you empathize with me. ",
  "sn9.14:7.3": "Please speak to me again, ",
  "sn9.14:7.4": "whenever you see something like this.” ",
  "sn9.14:8.1": "“We are no dependent of yours, ",
  "sn9.14:8.2": "nor are we your servant. ",
  "sn9.14:8.3": "You yourself should know, mendicant, ",
  "sn9.14:8.4": "the way that leads to a good place.” ",
  "sn9.14:9.1": "Impelled by that deity, that mendicant was struck with a sense of urgency. ",
  "sn9.14:9.2": "",
  "sn9.14:10.1": "",
  "sn9.14:10.2": "",
  "sn9.14:10.3": "",
  "sn9.14:10.4": "",
  "sn9.14:11.1": "",
  "sn9.14:11.2": "",
  "sn9.14:11.3": "",
  "sn9.14:11.4": "",
  "sn9.14:11.5": "The Linked Discourses in the Forest are completed. "
}
window.BILARA["sn9_v1"]["en"]["sn9_v1:source"] =
  "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
